### ISSUE TITLE
wrong answer by Inequality solver , from sympy.solvers.inequalities import solve_univariate_inequality

### ISSUE THREAD

**Issue by Shekharrajak** [sympy/sympy#10033]
```
>> solve_univariate_inequality(2*x**2 + 4*x > x**2 - x -6,x)
(-∞ < x ∧ x < -3) ∨ (-2 < x ∧ x < ∞)
```
Answer should include -3 and -2 means : x <= 3  or  x >=2
```
>> solve_univariate_inequality(-x**2 +6*6  >= 9 ,x)
     ___               ___
-3⋅╲╱ 3  ≤ x ∧ x ≤ 3⋅╲╱ 3 
```
Answer should be : 
```
–x^2 + 6x – 9 = 0 
x^2 – 6x + 9 = 0 
(x – 3)(x – 3) = 0 
x = 3
```
I also found some **trigonometric inequalities**  
```
>>> solve_univariate_inequality(sin(x) > 0.709,x)
0.788079176244539 ≤ x ∧ x < 2.35351347734525
```
means π/4 < x < 3π/4 Answer within interval (0, π)
so correct answer should be greater than π/4  means(0.788079176244539 ) _not greater than or equal_.
Extended answers is : π/4 + 2k.π < x < 3 π/4 + 2k.π ,where k = 0,1,2,..
so it is returning  answer within interval (0,π) only.
Is there a way to get extended answer  and answer within certain intervals ?
I tested with more examples which have same type of problem.

Even some equations give wrong answers like : 
```
>>> solve_univariate_inequality(sin(x) + sin(3*x) + sin(2*x) < 0,x)
-∞ < x ∧ x < 0
```
Solution set of the trig inequality must be : (π/2 , 2π/3) and (π , 4π/3) and (3π/2 , 2π)

these are the few simple cases ,I found similar problem in few more cases.

**Comment by gxyd** [comment]
I think they are working just fine. Probably you noted them on the terminal wrongly. Is that the case?
As for the last two expressions: Some of them `raise AttributeError`.

**Comment by Shekharrajak** [comment]
Yeah ,I tested them on the terminal .Is there other good way also?
I imported 

```
>>> from sympy.solvers.inequalities import solve_univariate_inequality
>>> from sympy.core.symbol import Symbol
```
using the [docs](http://docs.sympy.org/dev/modules/solvers/inequalities.html)
Are you getting correct answers ? @gxyd

**Comment by gxyd** [comment]
This is what i get on `0.7.7.dev`
```
gxyd@swap:~/Public/sympy$ python3.4
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
>>> from sympy import *
>>> x, y, z = symbols('x y z')
>>> solve_univariate_inequality(2*x**2 + 4*x > x**2 - x -6, x)
Or(And(-2 < x, x < oo), And(-oo < x, x < -3))           # i think this is correct
```

For
```
>>> solve_univariate_inequality(-x**2 +6*6  >= 9 ,x)
And(-3*sqrt(3) <= x, x <= 3*sqrt(3))             # i think this is also correct
```

For
```
>>> solve_univariate_inequality(sin(x) > 0.709,x)
And(0.788079176244539 < x, x < 2.35351347734525)   # i don't get (=) equality here
```
For
```
>>> solve_univariate_inequality(sin(x) + sin(3*x) + sin(2*x) < 0,x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gxyd/Public/sympy/sympy/solvers/inequalities.py", line 446, in solve_univariate_inequality
    reals = _nsort(set(solns + singularities), separated=True)[0]
  File "/home/gxyd/Public/sympy/sympy/polys/polyutils.py", line 45, in _nsort
    if any(i._prec == 1 for k in key for i in k):
  File "/home/gxyd/Public/sympy/sympy/polys/polyutils.py", line 45, in <genexpr>
    if any(i._prec == 1 for k in key for i in k):
AttributeError: 're' object has no attribute '_prec'
```

**Comment by Shekharrajak** [comment]
Oops 
In first case I wrote only ' > ' not ' > ='
and in second case I wrote 6*6 it was 6*x in my question. so 1 and 2 are giving correct. 

let me check again other similar cases where I got confused.

In 3rd and 4th expression ,I again get same answer.Let me check again if I am doing any mistake here . 
thanks @gxyd

**Comment by smichr** [comment]
This looks like a stale issue that should be closed. ping @Shekharrajak

**Comment by smichr** [comment]
I guess this is not stale: there is more than one interval in which, for example, `sin(x) < 0`

```
>>> solveset(sin(x)<=0,x,S.Reals)
Union({0}, Interval(pi, 2*pi))
```

The equality returns a solution in terms of imageset; the inequality should do something similar:

```
>>> solveset(sin(x),x,S.Reals)
Union(ImageSet(Lambda(_n, 2*_n*pi), S.Integers), ImageSet(Lambda(_n, 2*_n*pi + pi), S.Integers))
```

**Comment by oscargus** [comment]
Or even better `ImageSet(Lambda(_n, _n*pi), S.Integers)`

This is one of the simplifications that I was talking about elsewhere.
