### ISSUE TITLE
solve generates a NaN comparison error

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10086]
```python
>>> solve(Abs(x-4)-(x-1)/(x+2)-(x-3)/(x+1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solvers.py", line 1194, in solve
    solution.sort(key=default_sort_key)
  File "sympy\core\numbers.py", line 1807, in __lt__
    return Rational.__lt__(self, other)
  File "sympy\core\numbers.py", line 1485, in __lt__
    return Expr.__lt__(expr, other)
  File "sympy\core\expr.py", line 301, in __lt__
    raise TypeError("Invalid NaN comparison")
TypeError: Invalid NaN comparison
```

It looks like the problem is that it is trying to sort the solution which contains a nan. One can see the solutions it is working with by requesting a set:

```
>>> print filldedent(solve(Abs(x-4)-(x-1)/(x+2)-(x-3)/(x+1), set=True))

([x], set([(1 + sqrt(6),), (Piecewise((2**(2/3)*(-4 + (1 +
sqrt(3)*I)*(2 + (-1 - sqrt(3)*I)*(6 + 2*sqrt(7)*I)**(1/3))*(6 +
2*sqrt(7)*I)**(1/3)/4)/((1 + sqrt(3)*I)*(3 + sqrt(7)*I)**(1/3)),
2**(2/3)*(4 + (1 + sqrt(3)*I)*(6 + 2*sqrt(7)*I)**(1/3)*(6 + (1 +
sqrt(3)*I)*(6 + 2*sqrt(7)*I)**(1/3))/4)/((1 + sqrt(3)*I)*(3 +
sqrt(7)*I)**(1/3)) <= 0), (nan, True)),), (-sqrt(6) + 1,), (nan,),
(-3,), (Piecewise((1 + 2*2**(2/3)/(3 + sqrt(7)*I)**(1/3) + 2**(1/3)*(3
+ sqrt(7)*I)**(1/3), -3 + 2*2**(2/3)/(3 + sqrt(7)*I)**(1/3) +
2**(1/3)*(3 + sqrt(7)*I)**(1/3) >= 0), (nan, True)),)]))
```

It's interesting to see that a Piecewise is present because it couldn't decide the sign of an expression.

BTW, the actual solutions (confirmed visually) are:

```
>>> nsolve(eq,-3)
mpf('-3.0')
>>> nsolve(eq,-1.5)
mpf('-1.4494897427831781')
>>> nsolve(eq,3.2)
mpf('3.4494897427831781')
>>> nsolve(eq,5)
mpf('4.8844837019393323')
```

**Comment by oscarbenjamin** [comment]
Current master gives
```
In [16]: solve(Abs(x-4)-(x-1)/(x+2)-(x-3)/(x+1))                                                                                                              
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-16-2268a3b8c29b> in <module>
----> 1 solve(Abs(x-4)-(x-1)/(x+2)-(x-3)/(x+1))

~/current/sympy/sympy/sympy/solvers/solvers.py in solve(f, *symbols, **flags)
   1046         for e in fi.find(Abs):
   1047             if e.has(*symbols):
-> 1048                 raise NotImplementedError('solving %s when the argument '
   1049                     'is not real or imaginary.' % e)
   1050 

NotImplementedError: solving Abs(x - 4) when the argument is not real or imaginary.
```
Declaring x to be real I get:
```
In [17]: x = Symbol('x', real=True)                                                                                                                           

In [18]: solve(Abs(x-4)-(x-1)/(x+2)-(x-3)/(x+1))                                                                                                              
Out[18]: 
⎡                    ⎧                                                                    2/3 ⎛     3 ___            3 __________ ⎛    3 ___             3 _
⎢                    ⎪    ⎛  1   √3⋅ⅈ⎞ 3 ____________                4                   2   ⋅⎝16 + ╲╱ 2 ⋅(1 + √3⋅ⅈ)⋅╲╱ 3 + √7⋅ⅈ ⋅⎝6 - ╲╱ 2 ⋅(-1 - √3⋅ⅈ)⋅╲╱ 
⎢                    ⎪1 + ⎜- ─ - ────⎟⋅╲╱ 6 + 2⋅√7⋅ⅈ  + ───────────────────────────  for ───────────────────────────────────────────────────────────────────
⎢                    ⎪    ⎝  2    2  ⎠                  ⎛  1   √3⋅ⅈ⎞ 3 ____________                                             3 __________                
⎢-3, 1 - √6, 1 + √6, ⎨                                  ⎜- ─ - ────⎟⋅╲╱ 6 + 2⋅√7⋅ⅈ                                 4⋅(1 + √3⋅ⅈ)⋅╲╱ 3 + √7⋅ⅈ                 
⎢                    ⎪                                  ⎝  2    2  ⎠                                                                                        
⎢                    ⎪                                                                                                                                      
⎢                    ⎪                             nan                                                                     otherwise                        
⎣                    ⎩                                                                                                                                      

_________⎞⎞      ⎧                                                                    2/3 ⎛      3 ___ ⎛     3 ___             3 __________⎞            3 __
3 + √7⋅ⅈ ⎠⎠      ⎪                 4                ⎛  1   √3⋅ⅈ⎞ 3 ____________      2   ⋅⎝-16 + ╲╱ 2 ⋅⎝-6 + ╲╱ 2 ⋅(-1 + √3⋅ⅈ)⋅╲╱ 3 + √7⋅ⅈ ⎠⋅(1 - √3⋅ⅈ)⋅╲╱ 3
─────────── ≤ 0  ⎪1 + ─────────────────────────── + ⎜- ─ + ────⎟⋅╲╱ 6 + 2⋅√7⋅ⅈ   for ───────────────────────────────────────────────────────────────────────
                 ⎪    ⎛  1   √3⋅ⅈ⎞ 3 ____________   ⎝  2    2  ⎠                                                             3 __________                   
               , ⎨    ⎜- ─ + ────⎟⋅╲╱ 6 + 2⋅√7⋅ⅈ                                                                4⋅(1 - √3⋅ⅈ)⋅╲╱ 3 + √7⋅ⅈ                    
                 ⎪    ⎝  2    2  ⎠                                                                                                                          
                 ⎪                                                                                                                                          
                 ⎪                             nan                                                                      otherwise                           
                 ⎩                                                                                                                                          

________⎞                                                                                                           ⎤
 + √7⋅ⅈ ⎠      ⎧                                          2/3 ⎛    3 ___ ⎛     3 ___ 3 __________⎞ 3 __________⎞    ⎥
───────── ≥ 0  ⎪          4          3 ____________      2   ⋅⎝4 + ╲╱ 2 ⋅⎝-3 + ╲╱ 2 ⋅╲╱ 3 + √7⋅ⅈ ⎠⋅╲╱ 3 + √7⋅ⅈ ⎠    ⎥
               ⎪1 + ────────────── + ╲╱ 6 + 2⋅√7⋅ⅈ   for ─────────────────────────────────────────────────────── ≥ 0⎥
             , ⎨    3 ____________                                              3 __________                        ⎥
               ⎪    ╲╱ 6 + 2⋅√7⋅ⅈ                                             2⋅╲╱ 3 + √7⋅ⅈ                         ⎥
               ⎪                                                                                                    ⎥
               ⎩                nan                                             otherwise                           ⎥
                                                                                                                    ⎦
```
So we get 3 simple looking expressions and one complicated one. Numerically the first 3 are are
```
-3.0, -1.44948974278318, 3.44948974278318
```
which matches with what @smichr has above. The 4th root does not numerically evaluate:
```
In [58]: sol[3]                                                                                                                                               
Out[58]: 
⎧                                                                    2/3 ⎛     3 ___            3 __________ ⎛    3 ___             3 __________⎞⎞    
⎪    ⎛  1   √3⋅ⅈ⎞ 3 ____________                4                   2   ⋅⎝16 + ╲╱ 2 ⋅(1 + √3⋅ⅈ)⋅╲╱ 3 + √7⋅ⅈ ⋅⎝6 - ╲╱ 2 ⋅(-1 - √3⋅ⅈ)⋅╲╱ 3 + √7⋅ⅈ ⎠⎠    
⎪1 + ⎜- ─ - ────⎟⋅╲╱ 6 + 2⋅√7⋅ⅈ  + ───────────────────────────  for ────────────────────────────────────────────────────────────────────────────── ≤ 0
⎪    ⎝  2    2  ⎠                  ⎛  1   √3⋅ⅈ⎞ 3 ____________                                             3 __________                               
⎨                                  ⎜- ─ - ────⎟⋅╲╱ 6 + 2⋅√7⋅ⅈ                                 4⋅(1 + √3⋅ⅈ)⋅╲╱ 3 + √7⋅ⅈ                                
⎪                                  ⎝  2    2  ⎠                                                                                                       
⎪                                                                                                                                                     
⎪                             nan                                                                     otherwise                                       
⎩                                                                                                                                                     

In [59]: sol[3].n()                                                                                                                                           
Out[59]: 
⎧                                                                                                                                                           
⎪                                                  0.333333333333333                                             0.333333333333333                          
⎪1.0 - 1.57367259513247⋅ⅈ⋅(1 + 0.881917103688197⋅ⅈ)                  - 0.90856029641607⋅(1 + 0.881917103688197⋅ⅈ)                  - 0.90856029641607⋅(1 - 0
⎨                                                                                                                                                           
⎪                                                                                                                                                           
⎪                                                                                                                                                           
⎩                                                                                                                              nan                          

                                                                                                           2/3 ⎛     3 ___            3 __________ ⎛    3 __
                   0.333333333333333                                               0.333333333333333      2   ⋅⎝16 + ╲╱ 2 ⋅(1 + √3⋅ⅈ)⋅╲╱ 3 + √7⋅ⅈ ⋅⎝6 - ╲╱ 2
.881917103688197⋅ⅈ)                  + 1.57367259513247⋅ⅈ⋅(1 - 0.881917103688197⋅ⅈ)                   for ──────────────────────────────────────────────────
                                                                                                                                                 3 _________
                                                                                                                                    4⋅(1 + √3⋅ⅈ)⋅╲╱ 3 + √7⋅ⅈ
                                                                                                                                                            
                                                                                                                                            otherwise       

_             3 __________⎞⎞    
 ⋅(-1 - √3⋅ⅈ)⋅╲╱ 3 + √7⋅ⅈ ⎠⎠    
──────────────────────────── ≤ 0
_    

In [60]: srepr(sol[3])                                                                                                                                        
Out[60]: 'Piecewise(ExprCondPair(Add(Integer(1), Mul(Add(Rational(-1, 2), Mul(Integer(-1), Rational(1, 2), Pow(Integer(3), Rational(1, 2)), I)), Pow(Add(Integer(6), Mul(Integer(2), Pow(Integer(7), Rational(1, 2)), I)), Rational(1, 3))), Mul(Integer(4), Pow(Add(Rational(-1, 2), Mul(Integer(-1), Rational(1, 2), Pow(Integer(3), Rational(1, 2)), I)), Integer(-1)), Pow(Add(Integer(6), Mul(Integer(2), Pow(Integer(7), Rational(1, 2)), I)), Rational(-1, 3)))), LessThan(Mul(Rational(1, 4), Pow(Integer(2), Rational(2, 3)), Pow(Add(Integer(1), Mul(Pow(Integer(3), Rational(1, 2)), I)), Integer(-1)), Pow(Add(Integer(3), Mul(Pow(Integer(7), Rational(1, 2)), I)), Rational(-1, 3)), Add(Integer(16), Mul(Pow(Integer(2), Rational(1, 3)), Add(Integer(1), Mul(Pow(Integer(3), Rational(1, 2)), I)), Pow(Add(Integer(3), Mul(Pow(Integer(7), Rational(1, 2)), I)), Rational(1, 3)), Add(Integer(6), Mul(Integer(-1), Pow(Integer(2), Rational(1, 3)), Add(Integer(-1), Mul(Integer(-1), Pow(Integer(3), Rational(1, 2)), I)), Pow(Add(Integer(3), Mul(Pow(Integer(7), Rational(1, 2)), I)), Rational(1, 3))))))), Integer(0))), ExprCondPair(nan, true))'                               
```
