### ISSUE TITLE
Make atan work with rs_series

### ISSUE THREAD

**Issue by shivamvats** [sympy/sympy#10190]
See #10189

**Comment by tokencolour** [comment]
I would like to work on this.

**Comment by shivamvats** [comment]
@tokencolour Sure! Go ahead. Let me know if you need help.

**Comment by tokencolour** [comment]
It seems `rs_atan` method already handles constant terms of both kinds (constant value or a term of a multivariate series not involving the generator). I have added the key `atan` to  `_convert_func` dictionary. @shivamvats kindly suggest what can be those use cases where the solution fails, so that I can amend it.

**Comment by shivamvats** [comment]
Cool! Have a look at the tests for other functions and write similar ones for atan. They should pass if all is well.

**Comment by tokencolour** [comment]
Sorry for the delay, had been travelling for a while.

I tried to write tests for atan in line with other tests in `test_rs_series` .
I added assert statements like:
`assert rs_series(atan(a), a, 5).as_expr() == (atan(a).series(a, 0, 5)).removeO()`
But it seems there's a problem in first part of the equality test here.
whenever I try to print `rs_series(atan(a), a, 5).as_expr()`  it runs into an Attribute Error:
```
>>> rs_series(atan(a), a, 5)
-1/3*a**3 + a
>>> rs_series(atan(a), a, 5).as_expr()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thd/sympy/sympy/polys/rings.py", line 593, in as_expr
    return expr_from_dict(self.as_expr_dict(), *symbols)
  File "/home/thd/sympy/sympy/polys/rings.py", line 597, in as_expr_dict
    return dict([ (monom, to_sympy(coeff)) for monom, coeff in self.iterterms() ])
  File "/home/thd/sympy/sympy/polys/rings.py", line 597, in <listcomp>
    return dict([ (monom, to_sympy(coeff)) for monom, coeff in self.iterterms() ])
  File "/home/thd/sympy/sympy/polys/domains/pythonrationalfield.py", line 30, in to_sympy
    return SymPyRational(a.numerator, a.denominator)
AttributeError: 'Rational' object has no attribute 'numerator'
```
Observation:
the `-1/3` in the value of `rs_series(atan(a), a, 5) should be a `sympy.polys.domains.pythonrational.PythonRational` type object while it actually is a `sympy.core.numbers.Rational` type object.

Problem:
I can't figure out where the rationals are added to the variant. Is changing their type safe? Or should there be other kind of tests? I can't seem to figure a way to go about it. 
@shivamvats It would be great if you could help me.

**Comment by tokencolour** [comment]
This is still work in progress.

**Comment by tokencolour** [comment]
The tests have failed. What I tried to do was to change  the type of coefficients decided by `rs_diff` and `rs_integrate`. @shivamvats, Am I going in the direction? Is there a better way to change the type of the coefficients?

**Comment by SooryaN** [comment]
@shivamvats, seeing as how this hasn't been resolved yet, I'd like to have a go at it too.

**Comment by tokencolour** [comment]
@SooryaN Actually, I am in the middle of it at #10320 .

**Comment by shivamvats** [comment]
@SooryaN You are more than welcome to work with @tokencolour to solve this issue. Collaborative PR's are very much encouraged.

**Comment by Krashcan** [comment]
@shivamvats I would like to work on this issue

**Comment by Naba7** [comment]
I am working on this

**Comment by Naba7** [comment]
Since the inverse trigonometric functions are analytic functions, they can be extended from the real line to the complex plane. I am adding tests for complex functions in atan which fails the tests.

**Comment by Naba7** [comment]
@shivamvats  can you give a look at my pr?
