### ISSUE TITLE
solving abs with negative powers

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10198]
The condition that prevents the following from being solved should be removed:

```python
>>> reduce_inequalities(-1 + 1/Abs(1/x - 1) < 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\inequalities.py", line 607, in reduce_inequalities
    rv = _reduce_inequalities(inequalities, symbols)
  File "sympy\solvers\inequalities.py", line 552, in _reduce_inequalities
    abs_reduced.append(reduce_abs_inequalities(exprs, gen))
  File "sympy\solvers\inequalities.py", line 378, in reduce_abs_inequalities
    for expr, rel in exprs ])
  File "sympy\solvers\inequalities.py", line 338, in reduce_abs_inequality
    exprs = _bottom_up_scan(expr)
  File "sympy\solvers\inequalities.py", line 304, in _bottom_up_scan
    _exprs = _bottom_up_scan(arg)
  File "sympy\solvers\inequalities.py", line 321, in _bottom_up_scan
    "only non-negative integer powers are allowed")
ValueError: only non-negative integer powers are allowed
```

**Comment by smichr** [comment]
duplicates #9451 (same error) but this expression is pehaps different in that it includes a negative power of the Abs -- so I'll leave both open

**Comment by Curious72** [comment]
#10286

**Comment by Curious72** [comment]
@smichr  I have made a PR at #10286 !! Please have a look at it !!

**Comment by akki** [comment]
@smichr 
Please review - #10588
Thanks

**Comment by akki** [comment]
@smichr @certik 
Please review - #10588 
Thanks

**Comment by smichr** [comment]
@akki, let's give @Curious72 a chance first. If there is no response by next Monday then do what I suggest on his PR #10286 and we'll go from there.

**Comment by akki** [comment]
Ohh I am sorry, I saw #10199 and thought the PR is closed :)
