### ISSUE TITLE
Bug in rs_series

### ISSUE THREAD

**Issue by shivamvats** [sympy/sympy#10191]
`rs_series` misses a term for this input:

```
In [88]: rs_series(sin(a**QQ(3,7))*exp(a + b**QQ(6,7)), a,2)
Out[88]: -1/6*a**(9/7)*exp(b**(6/7)) + a**(3/7)*exp(b**(6/7))

In [89]: (sin(a**QQ(3,7))*exp(a + b**QQ(6,7))).series(a,0,2)
Out[89]: a**(3/7)*exp(b**(6/7)) - a**(9/7)*exp(b**(6/7))/6 + a**(10/7)*exp(b**(6/7)) + O(a**2)
```

**Comment by ishanaj** [comment]
@shivamvats I am working on this issue. But the first statement doesn't give the output as mentioned above rather it gives a `TypeError` : 
```
Traceback (most recent call last):
  File "ring_series.py", line 2022, in <module>
    print(rs_series(sin(a**QQ(3,7))*exp(a + b**QQ(6,7)), a,2))
  File "ring_series.py", line 1984, in rs_series
    series = _rs_series(expr, series, a, prec)
  File "ring_series.py", line 1914, in _rs_series
    min_pows[i])
  File "ring_series.py", line 1898, in _rs_series
    R(a), prec)
  File "ring_series.py", line 1135, in rs_exp
    return const*rs_exp(p1, x, prec)
  File "ring_series.py", line 1143, in rs_exp
    for k in range(prec):
TypeError: 'Rational' object cannot be interpreted as an integer
 ```

Which is because the `range` of the `for` loop is a fraction. Therefore on making the fraction evaluate the error disappears.
This could be the statement before the `for` loop executes:
 (where prec-->range)
```
if not(type(prec) is int):
        prec = int(prec.p/prec.q) + 1
```
Is this correct?

**Comment by shivamvats** [comment]
@ishanaj Are you using Python3? I do not get that error on my machine.

**Comment by ishanaj** [comment]
@shivamvats I am using python 3.5.

**Comment by gxyd** [comment]
I can also reproduce this `TypeError` issue in python3 only. This error is probably because of https://github.com/sympy/sympy/blob/master/sympy/polys/ring_series.py#L1143 . This raises `TypeError` in python3 when `prec` is a non-integer.

**Comment by czgdp1807** [comment]
The TypeError still persists. Opening a new issue.

**Comment by guptapratykshh** [comment]
we could ensure converting `prec` to integer using `int(prec)` avoids `TypeError` when `range(prec)` is been called.

```
    if len(p) > 20:
        return _exp1(p, x, prec)
    one = R(1)
    n = 1
    c = []
    prec = int(prec)
    for k in range(prec):
        c.append(one/n)
        k += 1
        n *= k
```
 Is this approach right ? 

```
>>> from sympy.polys.ring_series import rs_series
>>> from sympy.abc import a, b
>>> rs_series(sin(a**QQ(3,7))*exp(a + b**QQ(6,7)), a, 2)
-1/6*a**(9/7)*(exp(b**(6/7))) + a**(3/7)*(exp(b**(6/7)))
>>> (sin(a**QQ(3,7))*exp(a + b**QQ(6,7))).series(a,0,2)
                     ⎛ 6/7⎞                        
      ⎛ 6/7⎞    9/7  ⎝b   ⎠          ⎛ 6/7⎞        
 3/7  ⎝b   ⎠   a   ⋅ℯ          10/7  ⎝b   ⎠    ⎛ 2⎞
a   ⋅ℯ       - ──────────── + a    ⋅ℯ       + O⎝a ⎠
                    6                       
```
