### ISSUE TITLE
AttributeError when solving Eq(1/x, 2) > 0

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10218]
The expression is kind of odd and I'm not sure right now what should be done with it, but I am just documenting the issue:

```python
>>> solve(Eq(1/x, 2)>0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solvers.py", line 814, in solve
    return reduce_inequalities(f, symbols=symbols)
  File "sympy\solvers\inequalities.py", line 608, in reduce_inequalities
    rv = _reduce_inequalities(inequalities, symbols)
  File "sympy\solvers\inequalities.py", line 540, in _reduce_inequalities
    other.append(_solve_inequality(Relational(expr, 0, rel), gen))
  File "sympy\solvers\inequalities.py", line 493, in _solve_inequality
    return solve_univariate_inequality(ie, s)
  File "sympy\solvers\inequalities.py", line 457, in solve_univariate_inequality

    if valid((start + end)/2 if start != S.NegativeInfinity else end - 1):
  File "sympy\solvers\inequalities.py", line 430, in valid
    r = expr.func(v, 0)
  File "sympy\core\relational.py", line 407, in __new__
    r = cls._eval_relation(lhs, rhs)
  File "sympy\core\relational.py", line 728, in _eval_relation
    return _sympify(lhs.__gt__(rhs))
AttributeError: 'BooleanFalse' object has no attribute '__gt__'
```

**Comment by tokencolour** [comment]
Hello Sir,
I am a newbie here and I would like to work on this issue. As it is recommended that new people try issues that have Easy to fix labels associated to them, I wanted to ask if, in your opinion, it would be fine if I worked on this.

**Comment by sampadsaha5** [comment]
I went through your issue and I found that : 
Eq(a,b) -- Represents that two objects a,b are equal.It means
                                        1    
Eq(1/2,x) represents       ─  =  2 
                                        x    
                                                                                1                                                                     1
After this if we use  Eq(1/2,x)>0 , it represents       ─  =  2  > 0   which makes no sense, since   ─  is  
                                                                                x                                                                     x
already made equals to 2.

So instead of using   solve(Eq(1/x, 2)>0)  we can use:                                                                           solve( Rel (1/x,  2 ,  ' > ' ) )   or   solve( (1/x-2) > 0 ) which gives    0 < x ∧ x < 1/2     as output.

@smichr @asmeurer

**Comment by aktech** [comment]
@smichr

I didn't noticed the expression, but as @sampadsaha5  mentioned, I think `Eq(1/x, 2) > 0` doesn't makes sense.

**Comment by sampadsaha5** [comment]
@aktech 
So, it means that there is no bug here

**Comment by smichr** [comment]
> doesn't makes sense

Another way to think of it is an equality represents a set of values (so Eq(1/x,2) is x = {2} whereas Eq(x*(x-1), 0) is x = {0, 1}) and saying `set > 0` might be construed to mean "all members of the set that are positive".  Does that make sense?

**Comment by asmeurer** [comment]
I don't think we should think of Eq as a set (it's a boolean), but even if we did, `>` on sets should mean a superset relationship with other sets, not "all members are greater than".

**Comment by smichr** [comment]
Does the same apply to inequalities like Ge? If so, then I guess the way to think when "solving" these things for a set is that you are finding the set of values that makes the relationship True. 

Perhaps we should raise an error, then, when Eq, Ne, Gt, ... are used as an argument in a Relational?

**Comment by sampadsaha5** [comment]
@smichr 
I am feeling like we are confusing among  what `Eq(1/x,2)` really does. `Eq(1/x,2)` actually produces a relation between `1/x` and `2` and the relation is of equality "`=`". `Eq(1/x,2)` just outputs `1/x = 2` that's it. `Eq(1/x,2)` doesn't solve `1/x = 2` for `x` . Now, If we use `solve(Eq(1/x, 2))` it would give `x = 2` as output which we may consider as a set. After this if we will be using `solve(Eq(1/x), 2))>0` it would output `TRUE` since `x = {1/2}  >  0`.

I think this would be a correct explanation.
@asmeurer

**Comment by oscarbenjamin** [comment]
Solve now gives an error for this:
```
In [32]: solve(Eq(1/x, 2)>0)                                                                                                                   
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-32-0ca2901240aa> in <module>
----> 1 solve(Eq(1/x, 2)>0)

~/current/sympy/sympy/sympy/solvers/solvers.py in solve(f, *symbols, **flags)
    983 
    984         if fi.is_Relational:
--> 985             return reduce_inequalities(f, symbols=symbols)
    986 
    987         if isinstance(fi, Poly):

~/current/sympy/sympy/sympy/solvers/inequalities.py in reduce_inequalities(inequalities, symbols)
    985 
    986     # solve system
--> 987     rv = _reduce_inequalities(inequalities, symbols)
    988 
    989     # restore original symbols and return

~/current/sympy/sympy/sympy/solvers/inequalities.py in _reduce_inequalities(inequalities, symbols)
    916                 abs_part.setdefault(gen, []).append((expr, rel))
    917             else:
--> 918                 other.append(_solve_inequality(Relational(expr, 0, rel), gen))
    919 
    920     poly_reduced = []

~/current/sympy/sympy/sympy/core/relational.py in __new__(cls, lhs, rhs, rop, **assumptions)
     84                             Eq and Ne; all other relationals expect
     85                             real expressions.
---> 86                         '''))
     87             # \\\
     88             return rv

TypeError: 
A Boolean argument can only be used in Eq and Ne; all other
relationals expect real expressions.
```

I'm still unclear what this means though:
```
In [36]: Eq(1/x, 2)>0                                                                                                                          
Out[36]: 
1        
─ = 2 > 0
x        
```
The srepr
```
StrictGreaterThan(Equality(Pow(Symbol('x'), Integer(-1)), Integer(2)), Integer(0))
```
just looks like garbage in, garbage out.

Should it have a proper meaning?

**Comment by smichr** [comment]
`True > 0` raises `TypeError: BooleanAtom not allowed in this context.` I think we should do the same thing when an unevaluted Boolean (i.e. Relational) is used instead of a literal.

**Comment by oscargus** [comment]
So basically change the error message for the exception? (It is currently a `TypeError` as well.)

**Comment by oscarbenjamin** [comment]
I think that we should make it so that Relational is not a subclass of Expr and also that relations (apart from Eq, Ne) can only be defined between instances of Expr. Then `Eq(1/x, 2) > 0` should raise from Gt with something like:
```
TypeError: GreaterThan is only defined for real expressions, not  Equality/bool.
```
There is an awkwardness though in Python that True is an instance of int and is equal to 1 so we need to make sure that that doesn't leak into SymPy somehow:
```julia
In [9]: isinstance(True, int)                                                                                                     
Out[9]: True

In [10]: True == 1                                                                                                                
Out[10]: True

In [16]: True > 0                                                                                                                 
Out[16]: True
```
SymPy's S.true already sensibly rejects this:
```julia
In [19]: Eq(x, x+1)                                                                                                               
Out[19]: False

In [22]: type(Eq(x, x+1))                                                                                                         
Out[22]: sympy.logic.boolalg.BooleanFalse

In [20]: False > 4                                                                                                                
Out[20]: False

In [21]: Eq(x, x+1) > 4                                                                                                           
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-023f964a7f78> in <module>
----> 1 Eq(x, x+1) > 4

~/current/sympy/sympy/sympy/logic/boolalg.py in __lt__(self, other)
    215             Eq and Ne; all other relationals expect
    216             real expressions.
--> 217         '''))
    218 
    219     __le__ = __lt__

TypeError: 
A Boolean argument can only be used in Eq and Ne; all other
relationals expect real expressions.

```
so it should be fine as long as no SymPy objects evaluate to a normal Python bool.

**Comment by oscargus** [comment]
Right now it is a bit inconsistent (and biased).

`return S.true` is used in 40 lines and `return True` in 1040 lines...

For `S.false` vs `False`: 48 vs. 1937

Should no SymPy methods return `True/False`?

It seems to me that at least `__eq__`, `__le__`, etc should return `S.true/false`.

Quite a simple, but tedious, effort to change.

**Comment by oscargus** [comment]
Tedious in the sense that there will probably be lots of test failures.

**Comment by oscargus** [comment]
I changed a few in #17344 to see what happens...

**Comment by smichr** [comment]
This seems odd to me:
```python
>>> Eq(1,1) in (0,1)
False
>>> Eq(1,1) in (True, False)
True
>>> True in (0,1)
True
```

I see you close the test PR...I would have thought that all relational routines should be returning sympified values, too.

**Comment by oscarbenjamin** [comment]
> Should no SymPy methods return `True/False`?

I think that we need to distinguish between symbolic and non symbolic return values. Anywhere we exchange a symbolic object for True/False should be S.true/S.false so this should be the result whenever any SymPy boolean object evaluates.

On the other hand I think that `is_x` attributes/properties should return plain Python True/False/None: these are not symbolic attributes and are just used for branching in the internal logic. So this means that `_eval_is` methods should normally return True/False.

We should also consistently use `is False` rather than `== False` when we want to exclude the None case. We should use `is S.false` when testing if an object like a Relational evaluates to True. Using `is` is probably faster and will also weed out cases where methods are returning the wrong version. 

This is particularly important in tests which should be as precise as possible about what is returned. I often see contributors writing something like:
```
    assert x > 0
```
which will "pass" when the result is unevaluated.

**Comment by oscarbenjamin** [comment]
@smichr when you do `in` with a Python container both `is` and `==` are used internally. So these are equivalent:
```python
r1 = Eq(1, 1) in (0, 1)
r2 = any(x is Eq(1, 1) or x == Eq(1, 1) for x in (0, 1))
```

**Comment by oscargus** [comment]
> I would have thought that all relational routines should be returning sympified values, too.

There were very few who did. Which made me unsure.

What about `is_xxx`? Right now most do not return sympified values. 

Also, some methods (both comparisons and other) return `a == b` type expressions.

**Comment by oscargus** [comment]
So `Piecewise((x, x.is_real), (0, True))` should not be used?

(In fact, it should be `S.true` in all `Piecewise`, right?)

**Comment by oscarbenjamin** [comment]
> So `Piecewise((x, x.is_real), (0, True))` should not be used?

No that's fine. We allow unsimpified *inputs* e.g. int/float/bool etc to many functions. They will be simpified in `Piecewise.__new__`. This issue is about what is *returned* from SymPy functions.

**Comment by oscarbenjamin** [comment]
Correction: `x.is_real` is not a symbolic object and cannot necessarily be simpified to one so should not be used there:
```julia
In [32]: Piecewise((x, x.is_real), (0, True))                                                            
TypeError:
Second argument must be a Boolean, not `NoneType`
```
The True is fine though.

**Comment by oscargus** [comment]
But what is the fundamental difference between that and `Piecewise((x, Eq(im(x), 0), (0, True))`?

It may be that we do not want to be able to write `x.is_real` in expressions? (Why? Because it has a boolean return value? Because it is not an expression? Because we need to figure out how to print it?) Isn't this the problem really, that sometimes we use expressions in the code, `if b < 0:`, sometimes `if b.is_negative:`. I think a consequence of this is also that we should try to avoid the first type of expressions is possible? Or wrap the check into `fuzzy_bool`?

If `Eq` should return `S.true` or `S.false` (or stay unevaluated), wouldn't the consequence be that it should say `Piecewise((x, Eq(im(x), 0), (0, S.true))`? 

Just trying to straighten things out...

**Comment by oscarbenjamin** [comment]
@asmeurer and I both referred in #17344 to the docstring for BooleanTrue which discusses this. One point mentioned there is that the assumptions system (i.e. `x.is_real`) uses ternary logic whereas symbolic Booleans in SymPy use binary logic. The equivalent of the None in the ternary logic is the unevaluated binary logic expression. Once a Boolean evaluates it must always be S.true or S.false though.

Fundamentally though it is about distinguishing between symbolic and non-symbolic objects. The assumptions system is a low-level API on top of which symbolic manipulations are implemented.

Fundamentally `x.is_real` is not a symbolic Boolean object. The symbolic `Eq(im(x), 0)` is the right way to do this in your example. Of course under the hood `Eq(im(x), 0)` will check `x.is_real` when trying to evaluate and if `x.is_real` is not None then it will return *symbolic* true or false.

There is no harm in using `S.true` or `True` as *input* to Piecewise since both will be simpified to the same thing. This is like the fact that I can do `2*pi` rather than `Integer(2)*pi`.

**Comment by oscargus** [comment]
But what is the correct way to output a Piecewise? Say, after a `.rewrite(Piecewise)`. Wouldn't that be to use `S.true`?

To me, the consequence seems to be that there should be no comparisons in the code (unless wrapped with `(...) == True`, but ideally no) and only use `.is_x` type of statements. Unless one knows for sure that there will be numerical/comparable values. Exactly that type of problem that we are discussing in #17343 which would never have happened.

**Comment by oscarbenjamin** [comment]
> But what is the correct way to output a Piecewise? Say, after a `.rewrite(Piecewise)`. Wouldn't that be to use `S.true`?

If you mean to call `Piecewise((o1, c1), (o2, True))` then True or S.true is fine. Potentially S.true should be preferred for performance reasons but both are equally correct as per the documented behaviour of SymPy that sympifiable objects are acceptable as arguments to most API.

> To me, the consequence seems to be that there should be no comparisons in the code (unless wrapped with `(...) == True`, but ideally no) and only use `.is_x` type of statements. Unless one knows for sure that there will be numerical/comparable values. Exactly that type of problem that we are discussing in #17343 which would never have happened.

There are still reasons to use comparisons such as `a > b` since `(a-b).is_extended_positive` is not equivalent when a and b are both oo. However when a contributor writes `if a > b:` then it is likely to be an error based on not understanding/considering the unevaluated case which will raise when used with `if`. So yes in general I think it should be `if (a > b) is S.true` or `if (a > b) is not S.false` depending on which branch we want the unevaluated case to use.

**Comment by oscargus** [comment]
I mean this:
https://github.com/sympy/sympy/blob/a4297a11fd8f3e8af17efda85e3047e32e470a70/sympy/functions/elementary/complexes.py#L388-L390

Here, I would claim that it is better to write `S.true` than `True`.

**Comment by oscarbenjamin** [comment]
> Here, I would claim that it is better to write `S.true` than `True`.

It is potentially better since otherwise it will just need to be simpified in `Piecewise.__new__`. The difference is potentially a small performance improvement but both should give the same result. Or do you see some other advantage?

The question is how far you want to take this because each of the integers in that expression also needs to be simpified so you could use `S.One` and `S.Zero` or `Integer(-1)` and so on. You could also use `Gt` and `Lt` instead of `>` and `<` as well to cut out the middle man there. If you keep going then you get closer and closer to the `srepr`:
```python
Piecewise(ExprCondPair(Integer(1), StrictGreaterThan(Symbol('arg'), Integer(0))),
          ExprCondPair(Integer(-1), StrictLessThan(Symbol('arg'), Integer(0))),
          ExprCondPair(Integer(0), true))
```
which is a bit ugly.

I would say that the priority should be:
1. Correctness - *returning* True instead of S.true sometimes gives wrong results
2. Clarity - a Piecewise can be tricky to interpret even when written nicely
3. Performance - the kind of performance improvement that makes the code ugly can usually be done in a better way.

Although I put performance last it can trump clarity but it needs to be demonstrated that the performance improvement is significant.

**Comment by oscargus** [comment]
> Or do you see some other advantage?

I'm just trying to understand the different situations and the practical difference between `True` and `S.true`. I think `True/False` vs `S.true/false` are cases where 2 not really comes into play.

**Comment by oscarbenjamin** [comment]
> where 2 not really comes into play

That's a fair point. I think in this particular example the differences are small in any direction.
