### ISSUE TITLE
solveset doesn't handle high-order EX polynomials

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10226]
```python
>>> eq = x**5+x-sqrt(2)
>>> solveset(eq,x,S.Reals)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <lambda>
  File "sympy\solvers\solveset.py", line 967, in solveset
    return solveset_real(f, symbol)
  File "sympy\solvers\solveset.py", line 511, in solveset_real
    as_poly_solver=_solve_as_poly_real)
  File "sympy\solvers\solveset.py", line 531, in _solve_as_rational
    return as_poly_solver(g, symbol)
  File "sympy\solvers\solveset.py", line 630, in _solve_as_poly_real
    invert_func=invert_real)
  File "sympy\solvers\solveset.py", line 576, in _solve_as_poly
    solns = poly.all_roots()
  File "sympy\polys\polytools.py", line 3362, in all_roots
    roots = sympy.polys.rootoftools.RootOf.all_roots(f, radicals=radicals)
  File "sympy\polys\rootoftools.py", line 149, in all_roots
    return cls._get_roots("_all_roots", poly, radicals)
  File "sympy\polys\rootoftools.py", line 509, in _get_roots
    coeff, poly = cls._preprocess_roots(poly)
  File "sympy\polys\rootoftools.py", line 488, in _preprocess_roots
    "sorted roots not supported over %s" % dom)
NotImplementedError: sorted roots not supported over EX
```

When trying to solve the inequality, EmptySet is returned:
```python
>>> solveset(eq>0,x,S.Reals)
EmptySet()
```

The correct interval is `x > RootOf(x**10 + 2*x**6 + x**2 - 2, 1)`

```python
>>> eq.subs(x,RootOf(x**10 + 2*x**6 + x**2 - 2, 1)).n()
0.e-124
>>> eq.subs(x,RootOf(x**10 + 2*x**6 + x**2 - 2, 1)+1).n()
24.0534761294837
```

**Comment by sampadsaha5** [comment]
I don't know why I am having  `NameError: name 'solveset' is not defined`  as error.

**Comment by moorepants** [comment]
@sampadsaha5 You'll have to paste the full session's code for us to know.

**Comment by smichr** [comment]
(I always start a session with `from sympy import *`; `solveset` is in `sympy.solvers.solveset`.)

**Comment by smichr** [comment]
It seems like it should not be trying to get anything from a solver that requires roots to be sorted. If the domain is real the `real_roots` routine should be used. If all radicals are removed from the OP expression,

```
>>> eq = x**5 + x - sqrt(2)
>>> from sympy.solvers.solvers import unrad
>>> unrad(eq.subs(2, y))
(x**10 + 2*x**6 + x**2 - y, [])
>>> u = _[0].subs(y, 2)
>>> from sympy.polys import real_roots
>>> real_roots(u)
[CRootOf(x**10 + 2*x**6 + x**2 - 2, 0), CRootOf(x**10 + 2*x**6 + x**2 - 2, 1)]
>>> [eq.subs(x,i).n(2) for i in ans]
[-2.8, 0.e-110]
```

**Comment by oscargus** [comment]
Current master returns `ConditionSet(x, Eq(x**5 + x - sqrt(2), 0), Reals)` so better than exception.
