### ISSUE TITLE
Error while importing Plot in autowrap_ufuncify.py 

### ISSUE THREAD

**Issue by tokencolour** [sympy/sympy#10234]
I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Plot
It seems Plot is absent from the sympy.plotting.__init__.py as pointed out by @leosartaj on gitter.
I added `from sympy.plotting.plot import Plot` into the file autowrap_ufuncify.py in sympy/examples/advanced
There's a problem here.I get the following error.
*Traceback (most recent call last):
File "autowrap_ufuncify.py", line 83, in <module>
main()
File "autowrap_ufuncify.py", line 80, in main
plot1.show()
File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/plot.py";, line 185, in show
self._backend.show()
File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/plot.py";, line 1018, in show
self.process_series()
File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/plot.py";, line 980, in process_series
self.ax.set_xlim(min(starts), max(ends))
ValueError: min() arg is an empty sequence*

`parent._series` in the method `process_series` of class `MatplotlibBackend` remains empty here.
IMHO the technique used to plot in the example autowrap_ufuncify.py bears a resemblance to http://docs.sympy.org/dev/modules/plotting.html#using-the-interactive-interface
This plotting module uses pyglet. But installing it does not solve the problem I face while importing Plot from sympy.
Furthermore, I added the line `from sympy.plotting.pygletplot import PygletPlot as Plot` to get some luck. I got none.
I get the following key error:
*Traceback (most recent call last):
File "tryplot.py", line 87, in <module>
main()
File "tryplot.py", line 79, in main
plot1[n] = g(x), [200]
File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/pygletplot/plot.py";, line 319, in setitem
f = PlotMode(args, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/pygletplot/plotmode.py", line 78, in _new
subcls = PlotMode._get_mode(mode_arg, i, d)
File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/pygletplot/plot_mode.py", line 156, in _get_mode
return PlotMode._get_default_mode(i, d)
File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/pygletplot/plot_mode.py", line 170, in _get_default_mode
return PlotMode._mode_default_map[d][i]
KeyError: 1*
I get a similar KeyError when I try to run sympy/examples/advanced/pyglet_plotting.py

**Comment by leosartaj** [comment]
You can enclose code-blocks in ```. See [this](https://help.github.com/articles/github-flavored-markdown/).

**Comment by tokencolour** [comment]
Thank you for the suggestion.

**Comment by moorepants** [comment]
These examples haven't been updated as the plot api has changed over the last releases. The examples are not run on our automated testing so they get out of date and have to be manually updated. You probably just want to use `plot`.

**Comment by Mindey** [comment]
@tokencolour so, I also, try to use pyglet plot, and running into the same error. @moorepants , does plot support interactive plots? I've seen a [mention](http://matplotlib.org/1.4.3/mpl_toolkits/mplot3d/index.html) of interactive plots on matplotlib, which combined with mpld3, could probably give something close to what we have with pyglet. However, right now I see no true alternative to the kind of interactive 3D plots like [MapleSoft Maple](https://en.wikipedia.org/wiki/Maple_(software)) provides. It is quite obvious, that interactivity will require a decent GL library, like that of a gaming environment. However, I'm not sure if matplotlib is going to that direction. It seems that matplotlib is trying to [approximate](https://en.wikipedia.org/w/index.php?title=Matplotlib&oldid=699874443) [MathWorks MATLAB](https://en.wikipedia.org/wiki/MATLAB)'s graphing functionality, which is not focusing on plotting of symbolic expressions. So, I think, sympy would benefit from implementing its own graphing capabilities, or at least having a clean universal interactive plotting API, without tight integration with any specific plotting library.

I bumped into this issue by trying to go through the most basic Maple tutorial with SymPy, and I needed an animated 3D surface plot over time. I remembered that a few years ago I had enjoyed beautiful interactive SymPy 3D plots, but now, I couldn't even get a static interactive. It seems this ```plot``` gives only static.

```{python}
from sympy.plotting.pygletplot import PygletPlot as Plot
from sympy import var
var('x y z')
Plot(x*y**3-y*x**3)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-8f704f4bd6f7> in <module>()
      3 from sympy import var
      4 var('x y z')
----> 5 Plot(x*y**3-y*x**3)
      6 

/run/media/mindey/files/Documents/analysis/.env/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/pygletplot/__init__.pyc in PygletPlot(*args, **kwargs)
    138 
    139         import plot
--> 140         return plot.PygletPlot(*args, **kwargs)
    141 
    142 except Exception as e:

/run/media/mindey/files/Documents/analysis/.env/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/pygletplot/plot.pyc in __init__(self, *fargs, **win_args)
    240         self._pobjects.append(self.axes)
    241 
--> 242         self[0] = fargs
    243         if win_args.get('visible', True):
    244             self.show()

/run/media/mindey/files/Documents/analysis/.env/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/pygletplot/plot.pyc in __setitem__(self, i, args)
    317                 return  # no arguments given
    318             kwargs = dict(bounds_callback=self.adjust_all_bounds)
--> 319             f = PlotMode(*args, **kwargs)
    320 
    321         if f:

/run/media/mindey/files/Documents/analysis/.env/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/pygletplot/plot_mode.pyc in __new__(cls, *args, **kwargs)
     76 
     77         # Find the appropriate mode
---> 78         subcls = PlotMode._get_mode(mode_arg, i, d)
     79 
     80         # Create the object

/run/media/mindey/files/Documents/analysis/.env/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/pygletplot/plot_mode.pyc in _get_mode(mode_arg, i_var_count, d_var_count)
    154             # default mode
    155             if not mode_arg:
--> 156                 return PlotMode._get_default_mode(i, d)
    157             # Otherwise, interpret the string as a mode
    158             # alias (e.g. 'cartesian', 'parametric', etc)

/run/media/mindey/files/Documents/analysis/.env/lib/python2.7/site-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/pygletplot/plot_mode.pyc in _get_default_mode(i, d, i_vars)
    168             i_vars = i
    169         try:
--> 170             return PlotMode._mode_default_map[d][i]
    171         except TypeError:
    172             # Keep looking for modes in higher i var counts

KeyError: 2
```

The plots from matplotlib seem static.

![matplotlib3dgraph](https://raw.githubusercontent.com/Mindey/mindey.github.io/master/media/conversations/mat3dplot.png)

What are our options for dynamic interactive 3D graphs?

**Comment by moorepants** [comment]
I think your comment warrants a new issue. This issue has been fixed I believe. Can you open a new issue and mover your comment there?

**Comment by asmeurer** [comment]
That's because you chose `%pylab inline` (side note: `%pylab` is no longer recommended, you should use `%matplotlib` instead). The inline plots in the qtconsole are not interactive. If you use the default backend (use `%matplotlib` instead of `%matplotlib inline`) you should get an interactive plot in a new window.

**Comment by moorepants** [comment]
You can also use matplotlib's `%matplotlib notebook` to get a notebook enabled graph that will be interactive in the notebook itself.
