### ISSUE TITLE
problems converting an intersection to a list

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10248]
```
>>> list(Intersection(S.Reals, FiniteSet(x)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\sets\sets.py", line 1434, in <genexpr>
    return (x for x in s if x in other)
  File "sympy\sets\sets.py", line 516, in __contains__
    raise TypeError('contains did not evaluate to a bool: %r' % symb)
TypeError: contains did not evaluate to a bool: And(x < oo, x > -oo)
```

**Comment by gxyd** [comment]
What is the expected answer?

**Comment by smichr** [comment]
The answer I would expect is `And(x < oo, x > -oo)`. If this is wrong, please open a new issue.
