### ISSUE TITLE
Run the examples during automated testing or at release

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#10243]
Right now `examples/advanced/autowrap_ufuncify` doesn't run with the development version of SymPy because of backwards incompatible API changes, see #10234. We should figure out how to run these on Travis or simply before each release.

**Comment by leosartaj** [comment]
Some of these examples make graphs. They are of varying type. I am not sure what will be the best way to test them.

**Comment by moorepants** [comment]
The don't have to be unit tested, per se, but simply shown that they still execute. If you want to test graphs you can use matplotlib's image comparison testing framework.

**Comment by asmeurer** [comment]
I think most of the examples are run, but we skip the ones with plots.

**Comment by tokencolour** [comment]
I would like to work on this.

**Comment by tokencolour** [comment]
I had made a few changes to  `autowrap_ufuncify.py`  so as to use `plot` from `sympy.plotting` and had run it  interactively to find out:
```
>>> g=implemented_function('g', binary_poly)
>>> g._imp_(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'wrapper_module_5' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

>>> lambdified_poly=lambdify(x, expr)
>>> f=implemented_function('f', lamdified_poly)
>>> f._imp_(x)
63*x**5/8 - 35*x**3/4 + 15*x/8
```
It can plot f(x) for all n using `plot()` and `plot.extend()` but not g(x). It shows the following error:
```
Traceback (most recent call last):
  File "legendre_try.py", line 84, in <module>
    plot1.show()
  File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/plot.py", line 185, in show
    self._backend.show()
  File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/plot.py", line 1018, in show
    self.process_series()
  File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/plot.py", line 897, in process_series
    collection = self.LineCollection(s.get_segments())
  File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/plot.py", line 503, in get_segments
    f_start = f(self.start)
  File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/plotting/experimental_lambdify.py", line 228, in __call__
    result = self.lambda_func(args)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/core/expr.py", line 231, in __complex__
    return complex(float(re), float(im))
  File "/usr/local/lib/python2.7/dist-packages/sympy-0.7.7.dev0-py2.7.egg/sympy/core/expr.py", line 226, in __float__
    raise TypeError("can't convert expression to float")
TypeError: can't convert expression to float
```
I guess that g(x), though an instance of the Function class, is not being type-casted properly. 
I can't seem to figure out how to get this to work.
Please help me.

**Comment by tokencolour** [comment]
Can you help me with this, @moorepants ?

**Comment by amitsaha** [comment]
Besides the matplotlib image testing framework, another option to actuallt test graphs created by plots is pytest-mpl: https://pypi.python.org/pypi/pytest-mpl which may be useful here.

**Comment by tokencolour** [comment]
@amitsaha , Once I get the plots using `ufuncify`, I'll try to write tests for it. As of now, I can only plot implemented functions via `lambdify`

**Comment by moorepants** [comment]
I don't think it is necessary to turn the examples into unit tests. We really just needed to check and see if the examples execute before each release. Ideally, there is a script that we can run that will run them all from the top level directory, i.e.:

`bin/run_examples`

**Comment by asmeurer** [comment]
examples/all.py runs all the examples (but I think it skips this one).

**Comment by tokencolour** [comment]
I have changed the file so that it uses the new `plot` API. Though I feel, just plotting the `expr` defeats the purpose. Kindly have a look at it and should it be necessary, suggest some alternative solution.
