### ISSUE TITLE
nsolve: NameError: global name 'Derivative' is not defined

### ISSUE THREAD

**Issue by satels** [sympy/sympy#10250]
f = 2*x/(3+log((Abs(x-1)))-log((Abs(x-3))))

>>> f = 2*x/(3+log((Abs(x-1)))-log((Abs(x-3))))

```python
>>> nsolve(f.diff(), x, 0)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/sympy/sympy/solvers/solvers.py", line 2480, in nsolve

    return findroot(f, x0, **kwargs)

  File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/sympy/sympy/mpmath/calculus/optimization.py", line 928, in findroot

    fx = f(*x0)
  File "<string>", line 1, in <lambda>

NameError: global name 'Derivative' is not defined
```

**Comment by Vutsuak16** [comment]
do  f.diff()  separately u will get 
 2*x*(((re(x) - 3)*Derivative(re(x), x) + im(x)*Derivative(im(x), x))/Abs(x - 3)**2 - ((re(x) - 1)*Derivative(re(x), x) + im(x)*Derivative(im(x), x))/Abs(x - 1)**2)/(-log(Abs(x - 3)) + log(Abs(x - 1)) + 3)**2 + 2/(-log(Abs(x - 3)) + log(Abs(x - 1)) + 3)
 Hence Derivative an undefined name

**Comment by kshitij10496** [comment]
`nsolve` calls `mpmath.findroot` which, in turn, cannot handle `Derivative` objects.
@satels 
I think, you can try `solveset(f.diff(), x)`.

Ping @aktech.
What are your inputs on this ?

**Comment by aktech** [comment]
> nsolve calls mpmath.findroot which, in turn, cannot handle Derivative objects.

I think you are right.

**Comment by oscarbenjamin** [comment]
The Derivative is there because the symbol is not real e.g.:
```julia
In [28]: x = Symbol('x')                                                                                                                                      

In [29]: f = 2*x/(3+log((Abs(x-1)))-log((Abs(x-3))))                                                                                                          

In [30]: f                                                                                                                                                    
Out[30]: 
              2⋅x               
────────────────────────────────
-log(│x - 3│) + log(│x - 1│) + 3

In [31]: f.diff(x)                                                                                                                                            
Out[31]: 
    ⎛  ⎛            d                 d        ⎞               ⎛            d                 d        ⎞            ⎞                                   
    ⎜  ⎜(re(x) - 1)⋅──(re(x)) + im(x)⋅──(im(x))⎟⋅sign(x - 1)   ⎜(re(x) - 3)⋅──(re(x)) + im(x)⋅──(im(x))⎟⋅sign(x - 3)⎟                                   
    ⎜  ⎝            dx                dx       ⎠               ⎝            dx                dx       ⎠            ⎟                                   
2⋅x⋅⎜- ───────────────────────────────────────────────────── + ─────────────────────────────────────────────────────⎟                                   
    ⎝                     (x - 1)⋅│x - 1│                                         (x - 3)⋅│x - 3│                   ⎠                  2                
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────── + ────────────────────────────────
                                                                           2                                            -log(│x - 3│) + log(│x - 1│) + 3
                                         (-log(│x - 3│) + log(│x - 1│) + 3)                                                                             

In [32]: x = Symbol('x', real=True)                                                                                                                           

In [33]: f = 2*x/(3+log((Abs(x-1)))-log((Abs(x-3))))                                                                                                          

In [34]: f.diff(x)                                                                                                                                            
Out[34]: 
     ⎛  sign(x - 1)   sign(x - 3)⎞                                    
 2⋅x⋅⎜- ─────────── + ───────────⎟                                    
     ⎝    │x - 1│       │x - 3│  ⎠                   2                
─────────────────────────────────── + ────────────────────────────────
                                  2   -log(│x - 3│) + log(│x - 1│) + 3
(-log(│x - 3│) + log(│x - 1│) + 3) 
```
That should be solvable by `nsolve` but apparently is not:
```julia
In [36]: nsolve(f.diff(), x, 0)                                                                                                                               
---------------------------------------------------------------------------
ValueError: Could not find root within given tolerance. (0.444444444444444444444 > 2.16840434497100886801e-19)
Try another starting point or tweak arguments.  
```
