### ISSUE TITLE
solving a Relational involving Piecewise fails

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#10255]
```python
>>> q=Piecewise((1, x < 1), (3, True)) > 1
>>> solve(q,x)
False  <---- should be (x >= 1)
>>> q.subs(x,1)  <-- for example, q is True when x is 1
True
```

**Comment by smichr** [comment]
I now get the following:
```
Traceback (most recent call last):
  File "/home/runner/.site-packages/sympy/polys/polyutils.py", line 209, in_parallel_dict_from_expr_if_gens
    monom[indices[base]] = exp
KeyError: Piecewise((1, _x < 1), (3, True))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.site-packages/sympy/solvers/inequalities.py", line 809, in _solve_inequality
    p = Poly(expr, s)
  File "/home/runner/.site-packages/sympy/polys/polytools.py", line 129, in__new__
    return cls._from_expr(rep, opt)
  File "/home/runner/.site-packages/sympy/polys/polytools.py", line 239, in_from_expr
    rep, opt = _dict_from_expr(rep, opt)
  File "/home/runner/.site-packages/sympy/polys/polyutils.py", line 366, in_dict_from_expr
    rep, gens = _dict_from_expr_if_gens(expr, opt)
  File "/home/runner/.site-packages/sympy/polys/polyutils.py", line 305, in_dict_from_expr_if_gens
    (poly,), gens = _parallel_dict_from_expr_if_gens((expr,), opt)
  File "/home/runner/.site-packages/sympy/polys/polyutils.py", line 215, in_parallel_dict_from_expr_if_gens
    "the set of generators." % factor)
sympy.polys.polyerrors.PolynomialError: Piecewise((1, _x < 1), (3, True)) contains an element of the set of generators.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.site-packages/sympy/polys/polyutils.py", line 209, in_parallel_dict_from_expr_if_gens
    monom[indices[base]] = exp
KeyError: Piecewise((1, _x < 1), (3, True))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.site-packages/sympy/solvers/inequalities.py", line 244, in reduce_rational_inequalities
    (numer, denom), gen)
  File "/home/runner/.site-packages/sympy/polys/polytools.py", line 4313, in parallel_poly_from_expr
    return _parallel_poly_from_expr(exprs, opt)
  File "/home/runner/.site-packages/sympy/polys/polytools.py", line 4366, in _parallel_poly_from_expr
    reps, opt = _parallel_dict_from_expr(exprs, opt)
  File "/home/runner/.site-packages/sympy/polys/polyutils.py", line 330, in_parallel_dict_from_expr
    reps, gens = _parallel_dict_from_expr_if_gens(exprs, opt)
  File "/home/runner/.site-packages/sympy/polys/polyutils.py", line 215, in_parallel_dict_from_expr_if_gens
    "the set of generators." % factor)
sympy.polys.polyerrors.PolynomialError: Piecewise((1, _x < 1), (3, True)) contains an element of the set of generators.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.site-packages/sympy/solvers/inequalities.py", line 818, in _solve_inequality
    rv = reduce_rational_inequalities([[ie]], s)
  File "/home/runner/.site-packages/sympy/solvers/inequalities.py", line 249, in reduce_rational_inequalities
    '''))
sympy.polys.polyerrors.PolynomialError:
only polynomials and rational functions are supported in this context.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    print(solve(q,x))
  File "/home/runner/.site-packages/sympy/solvers/solvers.py", line 980, insolve
    return reduce_inequalities(f, symbols=symbols)
  File "/home/runner/.site-packages/sympy/solvers/inequalities.py", line 987, in reduce_inequalities
    rv = _reduce_inequalities(inequalities, symbols)
  File "/home/runner/.site-packages/sympy/solvers/inequalities.py", line 918, in _reduce_inequalities
    other.append(_solve_inequality(Relational(expr, 0, rel), gen))
  File "/home/runner/.site-packages/sympy/solvers/inequalities.py", line 820, in _solve_inequality
    rv = solve_univariate_inequality(ie, s)
  File "/home/runner/.site-packages/sympy/solvers/inequalities.py", line 483, in solve_univariate_inequality
    period = periodicity(e, gen)
  File "/home/runner/.site-packages/sympy/calculus/util.py", line 473, in periodicity
    g_s = decompogen(f, symbol)
  File "/home/runner/.site-packages/sympy/solvers/decompogen.py", line 47, in decompogen
    result += [f.subs(f.args[0], symbol)] + decompogen(f.args[0], symbol)
  File "/home/runner/.site-packages/sympy/solvers/decompogen.py", line 37, in decompogen
    raise TypeError('expecting Expr but got: `%s`' % func_name(f))
TypeError: expecting Expr but got: `ExprCondPair`
```

**Comment by jksuom** [comment]
>  File "/home/runner/.site-packages/sympy/solvers/decompogen.py", line 47, in decompogen
    result += [f.subs(f.args[0], symbol)] + decompogen(f.args[0], symbol)
  File "/home/runner/.site-packages/sympy/solvers/decompogen.py", line 37, in decompogen
    raise TypeError('expecting Expr but got: `%s`' % func_name(f))
TypeError: expecting Expr but got: `ExprCondPair`

`decompogen` treats `Piecewise` as a "simple function" on line 47. It will obviously need a special handling.

**Comment by NotWearingPants** [comment]
Now raises `NotImplementedError: The inequality, Piecewise((1, x < 1), (3, True)) - 1 > 0, cannot be solved using solve_univariate_inequality.` inside `sympy.solvers.inequalities.solve_univariate_inequality`
