### ISSUE TITLE
Computing series where the free variable is not just a symbol is broken

### ISSUE THREAD

**Issue by MooVI** [sympy/sympy#10290]
```python
In [1]: sin(x).series(x)
Out[1]: x - x**3/6 + x**5/120 + O(x**6)

In [2]: sin(sin(x)).series(sin(x))
Out[2]: sin(x) - sin(x)**3/6 + sin(x)**5/120 + O(x**6) #Correct, but odd notation

In [3]: sin(exp(x)).series(exp(x))
Out[3]: exp(5*x)/120 - exp(3*x)/6 + exp(x) #Wrong, and also missing big O

In [4]: sin(cos(x)).series(cos(x))
TypeError: zip argument #2 must support iteration
```

Arguably series should just complain and quit if it's not given an symbol for the free variable.

This odd behaviour is related to what `Order` does under `subs`:

```python
In [5]: Order(x).subs(x, exp(x))
Out[5]: 0

In [6]: Order(x).subs(x, cos(x))
TypeError: zip argument #2 must support iteration
```

The error is occurring because `solveset` cannot solve an equation Order gives it in `.eval_subs`, and there is no code handling no solution.

**Comment by oscarbenjamin** [comment]
One of those examples has now changed (not for the better):
```
In [6]:  sin(exp(x)).series(exp(x))                                                                                                            
Out[6]: 
O⎛1; x →  lim log(x) mod 2⋅ⅈ⋅π⎞
 ⎝       x─→0⁺                ⎠
```

**Comment by MooVI** [comment]
Hmm, I wonder why the supposed quick exit for not-a-symbol wasn't triggered?

**Comment by sachin-4099** [comment]
One of those examples has now changed:
```
In [5]: sin(exp(x)).series(exp(x))
Out[5]:
      3*x    5*x
 x   e      e       / 6*x          \
e  - ---- + ---- + O\e   ; x -> -oo/
      6     120
```

**Comment by anutosh491** [comment]
The fix for this has been reported in #22339 . The reason why this gives an error is because while we substitute any expression like `cos(x)` for `x` using `subs`, the point at which the order has to be calculated will also be changed and currently the solvers module(`solveset `method in  particular) can't compute the point at which the order has to be calculated . Hence a `NotImplementedError` has been raised in the Pr for the same .
For eg
```
>>> Order(x).subs(x, cos(x))
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\anuto\sympy\sympy\sympy\core\basic.py", line 953, in subs
    rv = rv._subs(old, new, **kwargs)
  File "C:\Users\anuto\sympy\sympy\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Users\anuto\sympy\sympy\sympy\core\basic.py", line 1065, in _subs
    rv = self._eval_subs(old, new)
  File "C:\Users\anuto\sympy\sympy\sympy\series\order.py", line 487, in _eval_subs
    raise NotImplementedError("SymPy is unable to solve the following equation: {} = 0".format(sol_str))

NotImplementedError: SymPy is unable to solve the following equation: x - cos(x) = 0
```
