### ISSUE TITLE
i get error while sympy installation using conda

### ISSUE THREAD

**Issue by joseph02** [sympy/sympy#10393]
os :: Linux Mint 17
```
(sympy35) ~/Desktop/sympy $ setupegg.py develop
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.5/site.py", line 587, in <module>
    main()
  File "/usr/lib/python3.5/site.py", line 573, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.5/site.py", line 287, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.5/site.py", line 263, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.5/site.py", line 253, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.5/sysconfig.py", line 595, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.5/sysconfig.py", line 538, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.5/sysconfig.py", line 410, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python3.5/_sysconfigdata.py", line 4, in <module>
    _sysconfigdata = importlib.import_module("_sysconfigdata_%s" % sys.abiflags)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_sysconfigdata_m'
```

**Comment by asmeurer** [comment]
https://groups.google.com/forum/#!topic/sympy/rbrvEZKECAo
