### ISSUE TITLE
Can't solve simple equation with Unequality

### ISSUE THREAD

**Issue by Ghost99** [sympy/sympy#10408]
I trying to validate some simple math expressions, such as `[a=1, b=2, a!=b]`, with `solve` function.
But instead of True, False, or empty list I got `NotImplementedError: only univariate inequalities are supported`
```
>>> from sympy.core.relational import Eq, Ne
>>> from sympy.core.symbol import Symbol
>>> from sympy.solvers.solvers import solve
>>> a = Symbol('a', integer=True)
>>> b = Symbol('b', integer=True)
>>> solve([Eq(a, 1), Eq(b, 2), Eq(a, b)])
[]
>>> solve([Eq(a, 1), Eq(b, 1), Eq(a, b)])
[{a: 1, b: 1}]
>>> solve([Eq(a, 1), Eq(b, 2), Ne(a, b)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/sympy/solvers/solvers.py", line 691, in solve
    return reduce_inequalities(f, symbols=symbols)
  File "/usr/lib64/python2.7/site-packages/sympy/solvers/inequalities.py", line 491, in reduce_inequalities
    "only univariate inequalities are supported")
NotImplementedError: only univariate inequalities are supported
```
Is there some other way to validate such simple expressions?

**Comment by smichr** [comment]
Find a solution from the equalities and then test it in the inequality(ies) to see that it(they) are not False:

```python
>>> solve([Eq(a, 1), Eq(b, 2)])
{b: 2, a: 1}
>>> Ne(a, b).subs(_)
True
```

**Comment by Ghost99** [comment]
Ok, it will work. But what if I have list with thousands of Eq, Ne, Ge, Le, Gt, Lt statements with hundreds of variables?
I need to programmatically verify (check for having at least one solution) arbitrary lists of simple mathematical statements. `solve` looks like best solution for that, but unfortunately, for some reason it can't handle Ne statements with variables. Is it really a way how that function should work?

**Comment by asmeurer** [comment]
@smichr's suggestion is just a workaround. This definitely should work, but it doesn't. I think his workaround might not scale to your problem. There may be many solutions to the equalities but few solutions when also considering the inequalities. 

As the error message indicates, multivariate inequalities are not yet supported. 

(By the way, you might try passing your problem to an SMT solver like Z3. Such solvers are a good fit for what you want to do)

**Comment by smichr** [comment]
Can you use the fact that if `Ne(x, y)` then multiplying denominators by `x-y` would exclude that relationship?

**Comment by Ghost99** [comment]
@asmeurer Thanks for Z3 suggestion, I'll look at it.
I just opened issue to report problem with `solve` function.

@smichr This will probably work. Thanks for another workaround, I have to use some of this.

**Comment by oscarbenjamin** [comment]
The branch of solve that handles systems with inequalities is very much incomplete and returns types/values that are inconsistent with the rest of solve. It should probably be split out into a separate API.
