### ISSUE TITLE
Error when pretty printing a slice of MatrixSymbol

### ISSUE THREAD

**Issue by Adrien79** [sympy/sympy#10520]
Slicing a MatrixSymbol with pretty printing on triggers an error. 

```
In [76]: A = MatrixSymbol('A', 4, 4)

In [77]: pretty(A[1,:])
Traceback (most recent call last):

  File "<ipython-input-75-db6dca8e482a>", line 1, in <module>
    pretty(A[1,:])

  File "D:\Anaconda3\lib\site-packages\sympy\printing\pretty\pretty.py", line 1917, in pretty
    return pp.doprint(expr)

  File "D:\Anaconda3\lib\site-packages\sympy\printing\pretty\pretty.py", line 50, in doprint
    return self._print(expr).render(**self._settings)

  File "D:\Anaconda3\lib\site-packages\sympy\printing\printer.py", line 257, in _print
    return getattr(self, printmethod)(expr, *args, **kwargs)

  File "D:\Anaconda3\lib\site-packages\sympy\printing\pretty\pretty.py", line 683, in _print_MatrixSlice
    prettyArgs = self._print_seq((ppslice(m.rowslice),

  File "D:\Anaconda3\lib\site-packages\sympy\printing\pretty\pretty.py", line 682, in ppslice
    return prettyForm(*self._print_seq(x, delimiter=':'))

  File "D:\Anaconda3\lib\site-packages\sympy\printing\pretty\stringpict.py", line 357, in __len__
    return len(self.s)

AttributeError: 'prettyForm' object has no attribute 's'
```

**Comment by shubhamtibra** [comment]
This was the output when I tested
`>>> A = MatrixSymbol('A', 4, 4)
>>> pretty(A[1,:])
'A[1, :4]'`
Sympy version
`
>>> sympy.__version__
'0.7.7.dev'
`

**Comment by Adrien79** [comment]
You're right, the bug was in 0.7.6.1.
I've just checked in 0.7.7.dev and it works for me too, sorry.
