### ISSUE TITLE
plot3d_parametric_line don't plot constant functions.

### ISSUE THREAD

**Issue by gabrielantao** [sympy/sympy#10529]
I've tried to plot a 3d particle path by using the Sympy` plot3d_parametric_line` function, but when I use a constant function (I mean, a integer number as `args`) I get a 0-dimension error. I tracked the problem in a `tree2str_translate` called inside of `Lambdifier` class. This method returns just a string with a number (representing this number) which cannot be correctly translated to lambda function later. In my case, I solved using a temporary solution below. Instead of translate directly the expr attribute, I tried to force a conversion of `str2tree` return in a float number, if this can be done we have a `np.full_like` function using the same shape of my single argument `args[0]`. Otherwise we get the translated string as usually we want.  So I decided ask for a better solution here.  

```
#expr.evalf() forces a numerical return 
try:                 
    tree = self.str2tree(str(expr.evalf())) 
    newexpr = "np.full_like(%s, %s)" % (args[0], float(tree))
except (ValueError, TypeError):    
    newexpr = self.tree2str_translate(tree)

```

**Comment by retsyo** [comment]
any update in sympy? I met this today:
```python
x_u, y_u, z_u = 0.25*u, 0.25 * sympy.cos(u), 0

plot3d_parametric_line(x_u, y_u, z_u)
```
says 
```
Traceback (most recent call last):
  File "test_sympy_plot.py", line 10, in <module>
    plot3d_parametric_line(x_u, y_u, z_u)
  File "E:\prg\py\Anaconda3_64\lib\site-packages\sympy\plotting\plot.py", line 1525, in plot3d_parametric_line
    plots.show()
  File "E:\prg\py\Anaconda3_64\lib\site-packages\sympy\plotting\plot.py", line 198, in show
    self._backend.show()
  File "E:\prg\py\Anaconda3_64\lib\site-packages\sympy\plotting\plot.py", line 1030, in show
    self.process_series()
  File "E:\prg\py\Anaconda3_64\lib\site-packages\sympy\plotting\plot.py", line 924, in process_series
    self.ax.set_zlim((min(z), max(z)))
TypeError: iteration over a 0-d array
```

**Comment by shiMusa** [comment]
I just encountered the same issue:
![image](https://user-images.githubusercontent.com/17574234/79082474-433a9a80-7cf4-11ea-911a-9d9e7c080ae4.png)

**Comment by kubajal** [comment]
Hi,
I have the same problem. It's a shame it is not documented in https://docs.sympy.org/latest/modules/plotting.html. You either have to come up with the idea that constants are not working or find this thread.
My use case was that I want to visualize eigenvectors in a Jupyter Notebook in VSCode: 
![image](https://user-images.githubusercontent.com/9532517/84569316-e015c480-ad85-11ea-89fc-c0945314b26f.png). But apparently because some of my eigenvectors have zeros in them nothing is plotted. :( VSCode doesn't help either with understanding the problem.

**Comment by oscarbenjamin** [comment]
> It's a shame it is not documented

The problem should be fixed rather than documented.

**Comment by antibunching** [comment]
I was trying to visualize some geometry constructs and I met this error as well. I include several more instances below.
```
plot3d_parametric_line(t, t, 0, (t, 0, 1)) #is fine, 
# however this function fails if I try to plot 
plot3d_parametric_line(0, t, 0, (t, 0, 1)) 
#or 
plot3d_parametric_line(t, 0, 0, (t, 0, 1))
#ValueError: x and y must have same first dimension, but have shapes (300,) and (1,)
```
```
#would give a similar error "ValueError: cannot broadcast a non-scalar to a scalar array"
plot3d_parametric_line(0, 0, t, (t, 0, 1)) 
```

**Comment by GitHunter0** [comment]
`plot3d()` suffers from the same [issue](https://stackoverflow.com/questions/57122835/sympy-plotting-plot3d-dont-plot-constant-functions)

It is a very essential feature, I hope it can be fixed.
