### ISSUE TITLE
ufuncify fails with complex numbers + matrices

### ISSUE THREAD

**Issue by dalum** [sympy/sympy#10522]
I don't know if this is intentional or not, but ufuncify does not seem to handle complex numbers at all and complains that the symbol `I` is undeclared when compiling (with backend 'numpy'). By adding `#include <complex.h>` to the temporary output and changing `double` to `double complex` I was able to compile it manually by running the generated `setup.py` script, but this is of course a suboptimal solution. A simple example that fails is:

`f = ufuncify((a,), exp(I * a))`

Also, when trying to use a matrix as the expression, it doesn't even generate output but gives the error:
`CodeGenArgumentListError: ("Argument list didn't specify: out_8932729926928909049 ", [OutputArgument(out_8932729926928909049, Matrix([ <<insert long matrix expression here>> ]), out_8932729926928909049])`

Using the f2py Fortran compiler, I am able to generate some code, but it seems to assign the entire matrix to a dummy variable, although I am not well–versed in Fortran. But it produces something like:
`subroutine autofunc(Dummy...)
...
REAL*8, intent(in), dimension(1:Dummy_884_885) :: V_ss_sigma__SnSn__2_909
INTEGER*4 :: Dummy_885_886

REAL*8 :: Matrix([ <<insert 1000 lines of matrix expression>> ])
do ...blahblahblah`

It might be worth mentioning that this is a very real application where I'm using SymPy to generate generic numerical tight–binding hamiltonians (hermitian matrices) which are subsequently diagonalised using numpy. So far, lambdify actually does what I need, but it would be nice to be able to add a bit of speed on top of it by generating optimized code, especially if it is to be run on a cluster or supercomputer.

I use Python 3.5 and the latest SymPy (0.7.7.dev), numpy (1.10.4), etc. from PyPI on Arch Linux with GCC (5.3.0).

**Comment by thisch** [comment]
Thx for the report. I'll take a look at it.

**Comment by ronanpaixao** [comment]
I have a minimal test case for the matrix bug:

```python
import sympy as sym
from sympy.utilities import autowrap
from sympy.abc import x, t
expr = sym.Matrix(2, 2, [x, 2*x, 3*x, 4*t])
func3 = autowrap.ufuncify([x, t], expr)
```

```python
Traceback (most recent call last):

  (...)

  File "D:\Anaconda\lib\site-packages\sympy\utilities\autowrap.py", line 881, in ufuncify
    routine = make_routine('autofunc', expr, args)

  File "D:\Anaconda\lib\site-packages\sympy\utilities\codegen.py", line 1608, in make_routine
    return code_gen.routine(name, expr, argument_sequence, global_vars)

  File "D:\Anaconda\lib\site-packages\sympy\utilities\codegen.py", line 605, in routine
    raise CodeGenArgumentListError(msg, missing)

CodeGenArgumentListError: ("Argument list didn't specify: out_251651943 ", [OutputArgument(out_251651943, Matrix([
[  x, 2*x],
[3*x, 4*t]]), out_251651943)])
```

It's seems like the bug is caused by the generated program expecting an `out_###` output variable. This seems like the usual Fortran way to output a matrix. This should probably be allocated and passed by the wrapper function, but maybe isn't?
