### ISSUE TITLE
unable to get unevaluated Integral object for  integrate ( x**log (x**log (x**log(x) ) ) , x) .

### ISSUE THREAD

**Issue by wrat** [sympy/sympy#10680]
while Evaluating  
>>>integrate ( x**log (x**log (x**log(x) ) ) , x)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 365, in from_expr
    poly = self._rebuild_expr(expr, mapping)
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 359, in _rebuild_expr
    return _rebuild(sympify(expr))
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 351, in _rebuild
    return reduce(add, list(map(_rebuild, expr.args)))
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 353, in _rebuild
    return reduce(mul, list(map(_rebuild, expr.args)))
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 351, in _rebuild
    return reduce(add, list(map(_rebuild, expr.args)))
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 353, in _rebuild
    return reduce(mul, list(map(_rebuild, expr.args)))
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 351, in _rebuild
    return reduce(add, list(map(_rebuild, expr.args)))
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 353, in _rebuild
    return reduce(mul, list(map(_rebuild, expr.args)))
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 357, in _rebuild
    return domain.convert(expr)
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/domains/domain.py", line 146, in convert
    raise CoercionFailed("can't convert %s of type %s to %s" % (element, type(element), self))
sympy.polys.polyerrors.CoercionFailed: can't convert _x0**_x1 of type <class 'sympy.core.power.Pow'> to QQ[_A0,_A1,_A2,_A3,_A4,_A5,_A6,_A7,_A8,_A9,_A10,_A11,_A12,_A13,_A14,_A15,_A16,_A17,_A18,_A19,_A20,_A21,_A22,_A23,_A24,_A25,_A26,_A27,_A28,_A29,_A30,_A31,_A32,_A33,_A34,_A35,_A36,_A37,_A38,_A39,_A40,_A41,_A42,_A43,_A44,_A45,_A46,_A47,_A48,_A49,_A50,_A51,_A52,_A53,_A54,_A55,_A56,_A57,_A58,_A59,_A60,_A61,_A62,_A63,_A64,_A65,_A66,_A67,_A68,_A69,_A70,_A71,_A72,_A73,_A74,_A75,_A76,_A77,_A78,_A79,_A80,_A81,_A82,_A83,_A84,_A85,_A86,_A87,_A88,_A89,_A90,_A91,_A92,_A93,_A94,_A95,_A96,_A97,_A98,_A99,_A100,_A101,_A102,_A103,_A104,_A105,_A106,_A107,_A108,_A109,_A110,_A111,_A112,_A113,_A114,_A115,_A116,_A117,_A118,_A119,_B0]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/sympy/utilities/decorator.py", line 35, in threaded_func
    return func(expr, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/integrals.py", line 1232, in integrate
    risch=risch, manual=manual)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/integrals.py", line 487, in doit
    conds=conds)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/integrals.py", line 862, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/heurisch.py", line 128, in heurisch_wrapper
    unnecessary_permutations)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/heurisch.py", line 566, in heurisch
    solution = _integrate('Q')
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/heurisch.py", line 555, in _integrate
    numer = ring.from_expr(raw_numer)
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 367, in from_expr
    raise ValueError("expected an expression convertible to a polynomial in %s, got %s" % (self, expr))
ValueError: expected an expression convertible to a polynomial in Polynomial ring in _x0, _x1, _x2, _x3, _x4, _x5, _x6 over QQ[_A0,_A1,_A2,_A3,_A4,_A5,_A6,_A7,_A8,_A9,_A10,_A11,_A12,_A13,_A14,_A15,_A16,_A17,_A18,_A19,_A20,_A21,_A22,_A23,_A24,_A25,_A26,_A27,_A28,_A29,_A30,_A31,_A32,_A33,_A34,_A35,_A36,_A37,_A38,_A39,_A40,_A41,_A42,_A43,_A44,_A45,_A46,_A47,_A48,_A49,_A50,_A51,_A52,_A53,_A54,_A55,_A56,_A57,_A58,_A59,_A60,_A61,_A62,_A63,_A64,_A65,_A66,_A67,_A68,_A69,_A70,_A71,_A72,_A73,_A74,_A75,_A76,_A77,_A78,_A79,_A80,_A81,_A82,_A83,_A84,_A85,_A86,_A87,_A88,_A89,_A90,_A91,_A92,_A93,_A94,_A95,_A96,_A97,_A98,_A99,_A100,_A101,_A102,_A103,_A104,_A105,_A106,_A107,_A108,_A109,_A110,_A111,_A112,_A113,_A114,_A115,_A116,_A117,_A118,_A119,_B0] with lex order, got _x0**5*_x5 - _x0**3*(2*_x0**_x2*_x2*(2*_A103*_x2*_x6 + _A106*_x4*_x5 + _x4**2*_A107 + _A108*_x1*_x2 + _A110*_x4 + _A116*_x0*_x1 + 2*_A12*_x1*_x6 + 2*_A19*_x4*_x6 + _A2 + _A20*_x2*_x3 + _A21*_x1*_x3 + _A23*_x3*_x4 + _A26*_x0*_x3 + _A3*_x2 + _x5**2*_A32 + _A35*_x0*_x2 + _A39*_x1 + _x2**2*_A41 + _A50*_x3 + 3*_x6**2*_A52 + 2*_A58*_x6 + _A6*_x0*_x4 + _A62*_x0*_x5 + _x1**2*_A69 + _A72*_x2*_x5 + _A74*_x2*_x4 + 2*_A77*_x0*_x6 + _x0**2*_A78 + _A8*_x5 + _x3**2*_A81 + 2*_A83*_x3*_x6 + _A89*_x0 + 2*_A90*_x5*_x6 + _A95*_x1*_x4 + _A96*_x1*_x5 + _A99*_x3*_x5) + _A101*_x0*_x1 + _A102*_x0*_x4 + _x6**2*_A103 + _A105*_x0*_x3 + _A108*_x1*_x6 + _A109*_x0*_x5 + _A11*_x3*_x5 + _A14*_x3 + 2*_A15*_x2*_x3 + _A18*_x4 + _A20*_x3*_x6 + 2*_A24*_x1*_x2 + 2*_A27*_x2*_x5 + _A3*_x6 + _A31*_x1*_x4 + _x5**2*_A33 + _A35*_x0*_x6 + 2*_A36*_x2 + 3*_x2**2*_A38 + _A40*_x3*_x4 + 2*_A41*_x2*_x6 + _A42*_x1*_x5 + _A61*_x1 + _A70*_x0 + _x0**2*_A71 + _A72*_x5*_x6 + _A74*_x4*_x6 + _A75*_x5 + 2*_A76*_x0*_x2 + 2*_A80*_x2*_x4 + _x1**2*_A82 + _A86*_x4*_x5 + _A87*_x1*_x3 + _x4**2*_A9 + _x3**2*_A93 + _A94 + 2*_x2*(2*_A1*_x1*_x5 + _A10 + _A101*_x0*_x2 + _A108*_x2*_x6 + _x5**2*_A112 + _A113*_x3*_x4 + _A116*_x0*_x6 + 2*_A117*_x0*_x1 + _x6**2*_A12 + 2*_A13*_x1 + _A21*_x3*_x6 + _x4**2*_A22 + _x2**2*_A24 + _A31*_x2*_x4 + _A34*_x0*_x5 + _A37*_x3 + _A39*_x6 + _A4*_x3*_x5 + _A42*_x2*_x5 + _A45*_x5 + _A47*_x0*_x4 + 3*_x1**2*_A5 + _A51*_x0*_x3 + _x0**2*_A53 + _A56*_x0 + 2*_A59*_x1*_x4 + _A60*_x4*_x5 + _A61*_x2 + _x3**2*_A64 + 2*_A66*_x1*_x3 + 2*_A69*_x1*_x6 + 2*_A82*_x1*_x2 + _A87*_x2*_x3 + _A95*_x4*_x6 + _A96*_x5*_x6 + _A98*_x4) + (_x1 + 2*_x2**2)*(_A100*_x0*_x3 + _A102*_x0*_x2 + _A106*_x5*_x6 + 2*_A107*_x4*_x6 + _A110*_x6 + _A113*_x1*_x3 + _x5**2*_A115 + _A16*_x0*_x5 + 2*_A17*_x3*_x4 + _A18*_x2 + _x6**2*_A19 + 2*_A22*_x1*_x4 + _A23*_x3*_x6 + _A31*_x1*_x2 + _A40*_x2*_x3 + 2*_A46*_x0*_x4 + _A47*_x0*_x1 + _x0**2*_A48 + _x3**2*_A55 + _x1**2*_A59 + _A6*_x0*_x6 + _A60*_x1*_x5 + _A63 + _A65*_x0 + _A7*_x3*_x5 + _A74*_x2*_x6 + 2*_A79*_x4*_x5 + _x2**2*_A80 + _A84*_x3 + _A85*_x5 + _A86*_x2*_x5 + 2*_A88*_x4 + 2*_A9*_x2*_x4 + 3*_x4**2*_A91 + _A95*_x1*_x6 + _A98*_x1) + (_x0**_x1*_x1 + 2*_x0**_x1*_x2**2)*(_A100*_x0*_x4 + 2*_A104*_x3*_x5 + _A105*_x0*_x2 + _A11*_x2*_x5 + _A113*_x1*_x4 + 2*_A118*_x0*_x3 + _A119*_x0*_x5 + _A14*_x2 + _x2**2*_A15 + _x4**2*_A17 + _A20*_x2*_x6 + _A21*_x1*_x6 + _A23*_x4*_x6 + _A26*_x0*_x6 + _A29 + _A30*_x5 + _A37*_x1 + _A4*_x1*_x5 + _A40*_x2*_x4 + _x0**2*_A43 + _A50*_x6 + _A51*_x0*_x1 + _x5**2*_A54 + 2*_A55*_x3*_x4 + _A57*_x0 + 2*_A64*_x1*_x3 + _x1**2*_A66 + _A7*_x4*_x5 + 2*_A81*_x3*_x6 + _x6**2*_A83 + _A84*_x4 + _A87*_x1*_x2 + 2*_A92*_x3 + 2*_A93*_x2*_x3 + 3*_x3**2*_A97 + _A99*_x5*_x6) + (_x1*_x2*_x5 + 2*_x2**3*_x5 + _x4*_x5)*(_x1**2*_A1 + _x3**2*_A104 + _A106*_x4*_x6 + _A109*_x0*_x2 + _A11*_x2*_x3 + _A111*_x0 + 2*_A112*_x1*_x5 + _x0**2*_A114 + 2*_A115*_x4*_x5 + _A119*_x0*_x3 + _A16*_x0*_x4 + _x2**2*_A27 + _A30*_x3 + 2*_A32*_x5*_x6 + 2*_A33*_x2*_x5 + _A34*_x0*_x1 + _A4*_x1*_x3 + _A42*_x1*_x2 + 3*_x5**2*_A44 + _A45*_x1 + 2*_A49*_x5 + 2*_A54*_x3*_x5 + _A60*_x1*_x4 + _A62*_x0*_x6 + 2*_A68*_x0*_x5 + _A7*_x3*_x4 + _A72*_x2*_x6 + _A73 + _A75*_x2 + _x4**2*_A79 + _A8*_x6 + _A85*_x4 + _A86*_x2*_x4 + _x6**2*_A90 + _A96*_x1*_x6 + _A99*_x3*_x6)) - _x0**2*(_x0**2*(_A100*_x3*_x4 + _A101*_x1*_x2 + _A102*_x2*_x4 + _A105*_x2*_x3 + _A109*_x2*_x5 + _A111*_x5 + 2*_A114*_x0*_x5 + _A116*_x1*_x6 + _x1**2*_A117 + _x3**2*_A118 + _A119*_x3*_x5 + _A16*_x4*_x5 + 3*_x0**2*_A25 + _A26*_x3*_x6 + 2*_A28*_x0 + _A34*_x1*_x5 + _A35*_x2*_x6 + 2*_A43*_x0*_x3 + _x4**2*_A46 + _A47*_x1*_x4 + 2*_A48*_x0*_x4 + _A51*_x1*_x3 + 2*_A53*_x0*_x1 + _A56*_x1 + _A57*_x3 + _A6*_x4*_x6 + _A62*_x5*_x6 + _A65*_x4 + _A67 + _x5**2*_A68 + _A70*_x2 + 2*_A71*_x0*_x2 + _x2**2*_A76 + _x6**2*_A77 + 2*_A78*_x0*_x6 + _A89*_x6 + _B0) + _x0*(-_A0 - _x1**2*_A1*_x5 - _A10*_x1 - _A100*_x0*_x3*_x4 - _A101*_x0*_x1*_x2 - _A102*_x0*_x2*_x4 - _x6**2*_A103*_x2 - _x3**2*_A104*_x5 - _A105*_x0*_x2*_x3 - _A106*_x4*_x5*_x6 - _x4**2*_A107*_x6 - _A108*_x1*_x2*_x6 - _A109*_x0*_x2*_x5 - _A11*_x2*_x3*_x5 - _A110*_x4*_x6 - _A111*_x0*_x5 - _x5**2*_A112*_x1 - _A113*_x1*_x3*_x4 - _x0**2*_A114*_x5 - _x5**2*_A115*_x4 - _A116*_x0*_x1*_x6 - _x1**2*_A117*_x0 - _x3**2*_A118*_x0 - _A119*_x0*_x3*_x5 - _x6**2*_A12*_x1 - _x1**2*_A13 - _A14*_x2*_x3 - _x2**2*_A15*_x3 - _A16*_x0*_x4*_x5 - _x4**2*_A17*_x3 - _A18*_x2*_x4 - _x6**2*_A19*_x4 - _A2*_x6 - _A20*_x2*_x3*_x6 - _A21*_x1*_x3*_x6 - _x4**2*_A22*_x1 - _A23*_x3*_x4*_x6 - _x2**2*_A24*_x1 - _x0**3*_A25 - _A26*_x0*_x3*_x6 - _x2**2*_A27*_x5 - _x0**2*_A28 - _A29*_x3 - _A3*_x2*_x6 - _A30*_x3*_x5 - _A31*_x1*_x2*_x4 - _x5**2*_A32*_x6 - _x5**2*_A33*_x2 - _A34*_x0*_x1*_x5 - _A35*_x0*_x2*_x6 - _x2**2*_A36 - _A37*_x1*_x3 - _x2**3*_A38 - _A39*_x1*_x6 - _A4*_x1*_x3*_x5 - _A40*_x2*_x3*_x4 - _x2**2*_A41*_x6 - _A42*_x1*_x2*_x5 - _x0**2*_A43*_x3 - _x5**3*_A44 - _A45*_x1*_x5 - _x4**2*_A46*_x0 - _A47*_x0*_x1*_x4 - _x0**2*_A48*_x4 - _x5**2*_A49 - _x1**3*_A5 - _A50*_x3*_x6 - _A51*_x0*_x1*_x3 - _x6**3*_A52 - _x0**2*_A53*_x1 - _x5**2*_A54*_x3 - _x3**2*_A55*_x4 - _A56*_x0*_x1 - _A57*_x0*_x3 - _x6**2*_A58 - _x1**2*_A59*_x4 - _A6*_x0*_x4*_x6 - _A60*_x1*_x4*_x5 - _A61*_x1*_x2 - _A62*_x0*_x5*_x6 - _A63*_x4 - _x3**2*_A64*_x1 - _A65*_x0*_x4 - _x1**2*_A66*_x3 - _A67*_x0 - _x5**2*_A68*_x0 - _x1**2*_A69*_x6 - _A7*_x3*_x4*_x5 - _A70*_x0*_x2 - _x0**2*_A71*_x2 - _A72*_x2*_x5*_x6 - _A73*_x5 - _A74*_x2*_x4*_x6 - _A75*_x2*_x5 - _x2**2*_A76*_x0 - _x6**2*_A77*_x0 - _x0**2*_A78*_x6 - _x4**2*_A79*_x5 - _A8*_x5*_x6 - _x2**2*_A80*_x4 - _x3**2*_A81*_x6 - _x1**2*_A82*_x2 - _x6**2*_A83*_x3 - _A84*_x3*_x4 - _A85*_x4*_x5 - _A86*_x2*_x4*_x5 - _A87*_x1*_x2*_x3 - _x4**2*_A88 - _A89*_x0*_x6 - _x4**2*_A9*_x2 - _x6**2*_A90*_x5 - _x4**3*_A91 - _x3**2*_A92 - _x3**2*_A93*_x2 - _A94*_x2 - _A95*_x1*_x4*_x6 - _A96*_x1*_x5*_x6 - _x3**3*_A97 - _A98*_x1*_x4 - _A99*_x3*_x5*_x6))
 but as we know from Documentation that If integrate is unable to compute an integral, it returns an unevaluated Integral object.

**Comment by danielbarter** [comment]
I think you may just be using the wrong syntax.

integrate(x * log( x * log(x * log(x))),x)

returns the correct integral object for me.

**Comment by danielbarter** [comment]
My mistake, the syntax from the title does reproduce the error on my end.

**Comment by danielbarter** [comment]
```{python}
from sympy import *
import pdb

x = Symbol('x')

pdb.set_trace()
i = integrate ( x**log (x**log (x**log(x) ) ) , x)
```

and stepping through the code doesn't reveal anything obvious to me. This needs the attention of someone more experienced.

**Comment by wrat** [comment]
Yeah I want to work on this but I am unable to find right way.Can anyone Help me?

**Comment by jksuom** [comment]
The expression is not a polynomial. (On the first line there is ``_x2**_x6`` having a variable as exponent.)

You should catch the ValueError resulting from ``numer = ring.from_expr(raw_numer)`` in heurisch.py and raise a PolynomialError instead. That will be caught by ``_eval_integral`` and an unevaluated integral will be returned.

**Comment by wrat** [comment]
I also found an expr where it is unable to evalute the 
expr=expr= (4/(8*x+1)) - (2/(8*x+4)) - (1/(8*x+5)) - (1/(8*x+6)) * (1/16)**x 
its also shows error while calculating integrate(expr,x)
 it shows like this----
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/sympy/utilities/decorator.py", line 35, in threaded_func
    return func(expr, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/integrals.py", line 1232, in integrate
    risch=risch, manual=manual)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/integrals.py", line 487, in doit
    conds=conds)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/integrals.py", line 754, in _eval_integral
    result, i = risch_integrate(f, x, separate_integral=True, conds=conds)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/risch.py", line 1678, in risch_integrate
    ans, i, b = integrate_hyperexponential(fa, fd, DE, conds=conds)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/risch.py", line 1439, in integrate_hyperexponential
    (integrate((p - i).subs(DE.t, 1).subs(s), DE.x), Eq(qds, 0)),
  File "/usr/local/lib/python3.4/dist-packages/sympy/utilities/decorator.py", line 35, in threaded_func
    return func(expr, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/integrals.py", line 1232, in integrate
    risch=risch, manual=manual)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/integrals.py", line 487, in doit
    conds=conds)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/integrals.py", line 754, in _eval_integral
    result, i = risch_integrate(f, x, separate_integral=True, conds=conds)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/risch.py", line 1684, in risch_integrate
    ans = integrate(fa.as_expr()/fd.as_expr(), DE.x, risch=False)
  File "/usr/local/lib/python3.4/dist-packages/sympy/utilities/decorator.py", line 35, in threaded_func
    return func(expr, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/integrals.py", line 1232, in integrate
    risch=risch, manual=manual)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/integrals.py", line 487, in doit
    conds=conds)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/integrals.py", line 830, in _eval_integral
    parts.append(coeff * ratint(g, x))
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/rationaltools.py", line 71, in ratint
    L = ratint_logpart(r, Q, x, t)
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/rationaltools.py", line 208, in ratint_logpart
    res, R = resultant(a, b, includePRS=True)
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/polytools.py", line 4800, in resultant
    result, R = F.resultant(G, includePRS=includePRS)
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/polytools.py", line 2464, in resultant
    result, R = F.resultant(G, includePRS=includePRS)
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/polyclasses.py", line 648, in resultant
    res, R = dmp_resultant(F, G, lev, dom, includePRS=includePRS)
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/euclidtools.py", line 835, in dmp_resultant
    return dup_resultant(f, g, K, includePRS=includePRS)
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/euclidtools.py", line 465, in dup_resultant
    return dup_prs_resultant(f, g, K)
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/euclidtools.py", line 445, in dup_prs_resultant
    res = K.quo(res*p, q)
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/domains/ring.py", line 29, in quo
    return a // b
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 1264, in __truediv__
    return p1.quo(p2)
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 1443, in quo
    return f.div(G)[0]
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 1379, in div
    p = p._iadd_poly_monom(fv[i], (expv1, -c))
  File "/usr/local/lib/python3.4/dist-packages/sympy/polys/rings.py", line 1526, in _iadd_poly_monom
    del p1[ka]
KeyError: (10,)

**Comment by jksuom** [comment]
Floating point numbers (such as Python 1/16 = 0.0625 ) should be avoided in integration and other applications of polynomials, since they are inexact and often lead to errors. SymPy rational numbers (written ``S(1)/16``) should be used instead.
In this example the last term has no elementary integral, and Risch's algorithm returns an unevaluated integral:
```
>>> integrate((S(1)/16)**x/(8*x + 6), x, risch=True)
Integral(16**(-x)/(8*x + 6), x)
```

**Comment by wrat** [comment]
ohkkk thanks @jksuom  I understood now.
@jksuom  as you told me about above expression is not polynomial and polynomial error should be raised while evaluating the expression.so I make some changes in heurisch.py and   catch the ValueError
,but can  you tell me , how I will check that changes that i  maked in file , will work or not ??

**Comment by jksuom** [comment]
You will see that it works, when running the integration command results in the unevaluated integral with no error message.

**Comment by asmeurer** [comment]
Why does it create a non-polynomial in the first place?

**Comment by wrat** [comment]
try:
         numer = ring.from_expr(raw_numer)
except ValueError:
         raise PolynomialError
I have changed something in code but I don't know why this is occurring
File "heurisch.py", line 5, in <module>
    from sympy.core.add import Add
  File "/usr/local/lib/python3.4/dist-packages/sympy/__init__.py", line 51, in <module>
    from .integrals import *
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/__init__.py", line 12, in <module>
    from .integrals import integrate, Integral, line_integrate
  File "/usr/local/lib/python3.4/dist-packages/sympy/integrals/integrals.py", line 6, in <module>
    from sympy.core.compatibility import is_sequence, range
ImportError: cannot import name 'range'

But I think that no problem while importing 'range' 
???

**Comment by jksuom** [comment]
> Why does it create a non-polynomial in the first place?

The candidate solutions are polynomials in the components of the integrand, but their derivatives are not necessarily so, because they are constructed from the derivatives of the components.

In this example the components are ``x, log(x), x**log(x), log(x**log(x)), x**log(x**log(x))``, etc., and they are replaced by dummy symbols acting as independent variables. Their derivatives can be expressed in terms of these variables in several ways depending on the order of substitution.

The non-polynomial arises in this case from the derivative of ``x**log(x)``:
``2*x**log(x)*log(x)/x``
when ``log(x)`` and ``x`` are substituted before ``x**log(x)``.

**Comment by wrat** [comment]
@jksuom  Ping!

**Comment by jksuom** [comment]
Now you should create the actual pull request for SymPy repository by following the directions given [here](https://github.com/sympy/sympy/wiki/Development-workflow#id42). The current PR above is only for your private repository https://github.com/wrat/sympy.

**Comment by wrat** [comment]
thanks @jksuom
