### ISSUE TITLE
solve() only works if simplify() is used first in this case

### ISSUE THREAD

**Issue by augustt198** [sympy/sympy#10716]
I was using sympy to solve `2 * sec(x)**2 + tan(x)**2 - 3 = 0`, and I came across this error:

```
>>> solve(2 * sec(x)**2 + tan(x)**2 - 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/sympy/solvers/solvers.py", line 909, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/usr/local/lib/python2.7/site-packages/sympy/solvers/solvers.py", line 1298, in _solve
    return _solve(newf, symbol, **flags)
  File "/usr/local/lib/python2.7/site-packages/sympy/solvers/solvers.py", line 1406, in _solve
    result = _tsolve(f_num, symbol, **flags)
  File "/usr/local/lib/python2.7/site-packages/sympy/solvers/solvers.py", line 2338, in _tsolve
    return _solve(rewrite - rhs, sym, **flags)
  File "/usr/local/lib/python2.7/site-packages/sympy/solvers/solvers.py", line 1427, in _solve
    for den in dens)]
  File "/usr/local/lib/python2.7/site-packages/sympy/solvers/solvers.py", line 1427, in <genexpr>
    for den in dens)]
  File "/usr/local/lib/python2.7/site-packages/sympy/solvers/solvers.py", line 289, in checksol
    return bool(abs(val.n(18).n(12, chop=True)) < 1e-9)
  File "/usr/local/lib/python2.7/site-packages/sympy/core/evalf.py", line 1317, in evalf
    result = evalf(self, prec + 4, options)
  File "/usr/local/lib/python2.7/site-packages/sympy/core/evalf.py", line 1211, in evalf
    r = rf(x, prec, options)
  File "/usr/local/lib/python2.7/site-packages/sympy/core/evalf.py", line 646, in evalf_pow
    xre, xim, _, _ = evalf(base, prec + 5, options)
  File "/usr/local/lib/python2.7/site-packages/sympy/core/evalf.py", line 1217, in evalf
    re, im = x._eval_evalf(prec).as_real_imag()
  File "/usr/local/lib/python2.7/site-packages/sympy/polys/rootoftools.py", line 555, in _eval_evalf
    root = findroot(func, x0)
  File "/usr/local/lib/python2.7/site-packages/sympy/mpmath/calculus/optimization.py", line 931, in findroot
    fx = f(x0[0])
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/site-packages/sympy/core/expr.py", line 225, in __float__
    raise TypeError("can't convert expression to float")
TypeError: can't convert expression to float
can't convert expression to float
```

However, if I simplify before calling solve() it works:
```
>>> solve(simplify(2 * sec(x)**2 + tan(x)**2 - 3))
[-pi/6, pi/6]
```

Is this expected behavior?

**Comment by chiragsinghal283** [comment]
I got ```[-I*log(-sqrt(3)/2 - I/2), -I*log(-sqrt(3)/2 + I/2), -I*log(sqrt(3)/2 - I/2), -I*log(sqrt(3)/2 + I/2)]``` as the output.

**Comment by hargup** [comment]
Works fine with solveset, though the solution can be simplified. @augustt198 you can use solveset from the development branch.

```
In [22]: solveset(2 * sec(x)**2 + tan(x)**2 - 3, x, domain=S.Reals)
Out[22]: ImageSet(Lambda(_n, 2*_n*pi - 5*pi/6), Integers()) U ImageSet(Lambda(_n, 2*_n*pi + 5*pi/6), Integers()) U ImageSet(Lambda(_n, 2*_n*pi - pi/6), Integers()) U ImageSet(Lambda(_n, 2*_n*pi + pi/6), Integers())
```

Since we intend to replace `solve` with `solveset` I'm closing this issue.
