### ISSUE TITLE
TensorProduct does not work with ImmutableMatrices

### ISSUE THREAD

**Issue by raineszm** [sympy/sympy#10734]
Currently attempting to pass one or more `ImmutableMatrix` instances to `sympy.physics.quantum.tensorproduct.TensorProduct` leads to an error.

For example,

``` python
>>> from sympy import *
>>> from sympy.physics.quantum.tensorproduct import TensorProduct
>>> M = eye(2).as_immutable()
>>> N = eye(2).as_immutable()
>>> MN = TensorProduct(M, N)
Traceback (most recent call last):
  File "<ipython-input-6-c2dec18d1267>", line 1, in <module>
    MN = TensorProduct(M, N)
  File "/Users/rainesz/anaconda3/lib/python3.5/site-packages/sympy/physics/quantum/tensorproduct.py", line 122, in __new__
    c_part, new_args = cls.flatten(sympify(args))
  File "/Users/rainesz/anaconda3/lib/python3.5/site-packages/sympy/physics/quantum/tensorproduct.py", line 138, in flatten
    cp, ncp = arg.args_cnc()
  File "/Users/rainesz/anaconda3/lib/python3.5/site-packages/sympy/matrices/matrices.py", line 3084, in __getattr__
    "%s has no attribute %s." % (self.__class__.__name__, attr))
AttributeError: ImmutableMatrix has no attribute args_cnc.
```

or

``` python
>>> from sympy import *
>>> from sympy.physics.quantum.tensorproduct import TensorProduct
>>> M = eye(2).as_mutable()
>>> N = eye(2).as_immutable()
>>> MN = TensorProduct(M, N)
Traceback (most recent call last):
  File "<ipython-input-14-c2dec18d1267>", line 1, in <module>
    MN = TensorProduct(M, N)
  File "/Users/rainesz/anaconda3/lib/python3.5/site-packages/sympy/physics/quantum/tensorproduct.py", line 121, in __new__
    return matrix_tensor_product(*args)
  File "/Users/rainesz/anaconda3/lib/python3.5/site-packages/sympy/physics/quantum/matrixutils.py", line 246, in matrix_tensor_product
    return _sympy_tensor_product(*product)
  File "/Users/rainesz/anaconda3/lib/python3.5/site-packages/sympy/physics/quantum/matrixutils.py", line 193, in _sympy_tensor_product
    'Sequence of Matrices expected, got: %s' % repr(matrices)
TypeError: Sequence of Matrices expected, got: (Matrix([
[1, 0],
[0, 1]]), Matrix([
[1, 0],
[0, 1]]))
```

The code specifically tests if objects are of class `Matrix` instead of `MatrixBase`, however, the general logic as written should work perfectly fine for `ImmutableMatrix` instances.

**Comment by czgdp1807** [comment]
Current status.
```python
>>> M = eye(2).as_immutable()
>>> from sympy.physics.quantum.tensorproduct import TensorProduct
>>> M = eye(2).as_immutable()>>> N = eye(2).as_immutable()>>> MN = TensorProduct(M, N)>>> MN
⎡1  0⎤  ⎡1  0⎤
⎢    ⎥⨂ ⎢    ⎥
⎣0  1⎦  ⎣0  1⎦
>>> type(MN)
<class 'sympy.physics.quantum.tensorproduct.TensorProd
uct'>
>>> _M = eye(2).as_mutable()
>>> _MN = TensorProduct(_M, N)
>>> _MN
⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  0  0⎥
⎢          ⎥
⎢0  0  1  0⎥
⎢          ⎥
⎣0  0  0  1⎦
>>> type(_MN)
<class 'sympy.matrices.immutable.ImmutableDenseMatrix'
>
```
It looks like the issue is partly resolved. However, `TensorProduct`doesn't seem to be evaluated with all immutable matrices as input. Opening a new issue for the same.
