### ISSUE TITLE
The sympy 1.0 gives:

### ISSUE THREAD

**Issue by certik** [sympy/sympy#10732]
```
certik@redhawk:~/Downloads/sympy-1.0$ bin/isympy 
Traceback (most recent call last):
  File "bin/isympy", line 357, in <module>
    main()
  File "bin/isympy", line 354, in main
    init_session(ipython, **args)
  File "/home/certik/Downloads/sympy-1.0/sympy/interactive/session.py", line 470, in init_session
    message = _make_message(ipython, quiet, _preexec_source)
  File "/home/certik/Downloads/sympy-1.0/sympy/interactive/session.py", line 78, in _make_message
    doc_version = "%s.%s.%s/" % tuple(doc_version.split('.')[:3])
TypeError: not enough arguments for format string

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```
I am still debugging this.

**Comment by certik** [comment]
Ok, so `sympy/release.py` must be changed from `__version__ = "1.0"` to `__version__ = "1.0.0"`. Then this issue is fixed.

**Comment by asmeurer** [comment]
I pushed a fix to the release branch.

**Comment by asmeurer** [comment]
This code was also wrong for the last release (0.7.6.1).

**Comment by certik** [comment]
Nobody noticed for the last release?

**Comment by asmeurer** [comment]
The code didn't error. The last release was a tiny bugfix release over 0.7.6.
