### ISSUE TITLE
PolynomialError from risch with integrate(1/(1-(x*y)**2), (x, 0, 1), (y, 0, 1))

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10798]
```
In [121]: sqrt(8*integrate(1/(1-(x*y)**2), (x, 0, 1), (y, 0, 1)))
---------------------------------------------------------------------------
PolynomialError                           Traceback (most recent call last)
<ipython-input-121-c6f62679df7e> in <module>()
----> 1 sqrt(8*integrate(1/(1-(x*y)**2), (x, 0, 1), (y, 0, 1)))

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/integrals.py in integrate(*args, **kwargs)
   1278     if isinstance(integral, Integral):
   1279         return integral.doit(deep=False, meijerg=meijerg, conds=conds,
-> 1280                              risch=risch, manual=manual)
   1281     else:
   1282         return integral

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/integrals.py in doit(self, **hints)
    484                     function, xab[0],
    485                     meijerg=meijerg1, risch=risch, manual=manual,
--> 486                     conds=conds)
    487                 if antideriv is None and meijerg1 is True:
    488                     ret = try_meijerg(function, xab)

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/integrals.py in _eval_integral(self, f, x, meijerg, risch, manual, conds)
    777         if risch is not False:
    778             try:
--> 779                 result, i = risch_integrate(f, x, separate_integral=True, conds=conds)
    780             except NotImplementedError:
    781                 pass

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/risch.py in risch_integrate(f, x, extension, handle_first, separate_integral, rewrite_complex, conds)
   1669     f = S(f)
   1670
-> 1671     DE = extension or DifferentialExtension(f, x, handle_first=handle_first, rewrite_complex=rewrite_complex)
   1672     fa, fd = DE.fa, DE.fd
   1673

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/risch.py in __init__(self, f, x, handle_first, dummy, extension, rewrite_complex)
    395
    396             if handle_first == 'log' or not exp_new_extension:
--> 397                 log_new_extension = self._log_part(logs, dummy=dummy)
    398
    399         self.fa, self.fd = frac_in(self.newf, self.t)

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/risch.py in _log_part(self, logs, dummy)
    552             # In other words, we don't have to worry about radicals.
    553             arga, argd = frac_in(arg, self.t)
--> 554             A = is_deriv_k(arga, argd, self)
    555             if A is not None:
    556                 ans, u, const = A

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/prde.py in is_deriv_k(fa, fd, DE)
    669                 # We need to get around things like sqrt(x**2) != x
    670                 # and also sqrt(x**2 + 2*x + 1) != x + 1
--> 671                 icoeff, iterms = sqf_list(i)
    672                 l.append(Mul(*([Pow(icoeff, j)] + [Pow(b, e*j) for b, e in iterms])))
    673             const = cancel(fa.as_expr()/fd.as_expr()/Mul(*l))

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/polytools.py in sqf_list(f, *gens, **args)
   5951
   5952     """
-> 5953     return _generic_factor_list(f, gens, args, method='sqf')
   5954
   5955

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/polytools.py in _generic_factor_list(expr, gens, args, method)
   5722
   5723         if fq and not opt.frac:
-> 5724             raise PolynomialError("a polynomial expected, got %s" % expr)
   5725
   5726         _opt = opt.clone(dict(expand=True))

PolynomialError: a polynomial expected, got 1/y
```

**Comment by jksuom** [comment]
``sqf_list`` only accepts polynomials as arguments. A quick fix could be the following.
```
--- a/sympy/integrals/prde.py
+++ b/sympy/integrals/prde.py
@@ -664,13 +664,17 @@ def is_deriv_k(fa, fd, DE):
             ans = list(zip(terms, u))
             result = Add(*[Mul(i, j) for i, j in ans])
             argterms = [DE.T[i] for i in DE.E_K] + DE.L_args
-            l = []
+            l = ld = []
             for i, j in zip(argterms, u):
                 # We need to get around things like sqrt(x**2) != x
                 # and also sqrt(x**2 + 2*x + 1) != x + 1
+                # Issue 10798: i need not be a polynomial
+                i, d = i.as_numer_denom()
                 icoeff, iterms = sqf_list(i)
                 l.append(Mul(*([Pow(icoeff, j)] + [Pow(b, e*j) for b, e in iterms])))
-            const = cancel(fa.as_expr()/fd.as_expr()/Mul(*l))
+                dcoeff, dterms = sqf_list(d)
+                ld.append(Mul(*([Pow(dcoeff, j)] + [Pow(b, e*j) for b, e in dterms])))
+            const = cancel(fa.as_expr()/fd.as_expr()/Mul(*l)*Mul(*ld))
 
             return (ans, result, const)
```
Alternatively, ``DifferentialExtension._log_part`` could be modified to split logarithms with fractional arguments into two parts: ``log(a/d) = log(a) - log(d)``.

**Comment by rd13123013** [comment]
@jksuom  what should be modified in `DifferentialExtension._log_part` , should we convert each element of form `log(a/d)`  in `logs` ( `_log_part(self, logs, dummy=True) ` ) to two new elements `log(a)` and `-log(d)`

**Comment by asmeurer** [comment]
Changing _log_part might break other stuff (I can't say for sure). The patch to is_deriv_k looks better. There's no reason it should assume that the log_args are polynomials.

**Comment by asmeurer** [comment]
I can confirm that @jksuom's patch fixes this. A more direct test is `integrate(integrate(1/(1-(x*y)**2), (x, 0, 1)), y, risch=True)`. Unfortunately, the integral isn't elementary. There seems to be another bug, though:

```
In [1]: integrate(integrate(1/(1-(x*y)**2), (x, 0, 1)), y, risch=True)
Out[1]:
⌠               ⌠               ⌠                   ⌠
⎮    ⎛-1 ⎞      ⎮     ⎛1⎞       ⎮     ⎛    1⎞       ⎮    ⎛    1⎞
⎮ log⎜───⎟      ⎮ -log⎜─⎟       ⎮ -log⎜1 - ─⎟       ⎮ log⎜1 + ─⎟
⎮    ⎝ y ⎠      ⎮     ⎝y⎠       ⎮     ⎝    y⎠       ⎮    ⎝    y⎠
⎮ ──────── dy + ⎮ ──────── dy + ⎮ ──────────── dy + ⎮ ────────── dy
⎮    y          ⎮    y          ⎮      y            ⎮     y
⌡               ⌡               ⌡                   ⌡
───────────────────────────────────────────────────────────────────
                                 2
```

Half of the integrals returned are nonelementary (the ones with sums in the log, c.f. http://www.wolframalpha.com/input/?i=integrate(-log(1+-+1%2Fy)%2Fy,+y)&dataset=), but the other half aren't

```
In [6]: from sympy.integrals.risch import risch_integrate

In [7]: risch_integrate(log(-1/y)/y, y)
Out[7]:
    2⎛-1 ⎞
-log ⎜───⎟
     ⎝ y ⎠
───────────
     2
```

This should be a separate issue, though.

**Comment by jksuom** [comment]
I think splitting the logs might be made to work. That would make the logs look better (no denoms) but their number would in general be bigger. I'll finish the tests with the patch to is_deriv_k and send a PR.

**Comment by asmeurer** [comment]
Ah, scratch that. There are several test failures with @jksuom's patch:

```
sympyrisch*%$./bin/test sympy//integrals/tests/test_risch.py
==================================================================== test process starts =====================================================================
executable:         /Users/aaronmeurer/anaconda/bin/python  (3.5.1-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python
random seed:        26732340
hash randomization: on (PYTHONHASHSEED=3819057531)

sympy/integrals/tests/test_risch.py[32] ....................EE...E..E...                                                                                [FAIL]

______________________________________________________________________________________________________________________________________________________________
_____________________________________________ sympy/integrals/tests/test_risch.py:test_DifferentialExtension_log _____________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/integrals/tests/test_risch.py", line 451, in test_DifferentialExtension_log
    dummy=False)._important_attrs == \
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/risch.py", line 258, in __init__
    "manual extension with the extension flag.")
NotImplementedError: Couldn't find an elementary transcendental extension for log(x)*log(x + 1)*log(2*x**2 + 2*x).  Try using a manual extension with the extension flag.
______________________________________________________________________________________________________________________________________________________________
___________________________________________ sympy/integrals/tests/test_risch.py:test_DifferentialExtension_symlog ____________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/integrals/tests/test_risch.py", line 465, in test_DifferentialExtension_symlog
    assert DifferentialExtension(log(x**x), x, dummy=False)._important_attrs == \
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/risch.py", line 258, in __init__
    "manual extension with the extension flag.")
NotImplementedError: Couldn't find an elementary transcendental extension for log(x**x).  Try using a manual extension with the extension flag.
______________________________________________________________________________________________________________________________________________________________
____________________________________________ sympy/integrals/tests/test_risch.py:test_DifferentialExtension_misc _____________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/integrals/tests/test_risch.py", line 563, in test_DifferentialExtension_misc
    assert DifferentialExtension(log(x) + log(x**2), x, dummy=False)._important_attrs in [
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/risch.py", line 258, in __init__
    "manual extension with the extension flag.")
NotImplementedError: Couldn't find an elementary transcendental extension for log(x) + log(x**2).  Try using a manual extension with the extension flag.
______________________________________________________________________________________________________________________________________________________________
__________________________________________________ sympy/integrals/tests/test_risch.py:test_risch_integrate __________________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/integrals/tests/test_risch.py", line 655, in test_risch_integrate
    assert risch_integrate(log(x**x), x) == x**2*log(x)/2 - x**2/4
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/risch.py", line 1671, in risch_integrate
    DE = extension or DifferentialExtension(f, x, handle_first=handle_first, rewrite_complex=rewrite_complex)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/integrals/risch.py", line 258, in __init__
    "manual extension with the extension flag.")
NotImplementedError: Couldn't find an elementary transcendental extension for log(x**x).  Try using a manual extension with the extension flag.

================================================== tests finished: 28 passed, 4 exceptions, in 8.51 seconds ==================================================
DO *NOT* COMMIT!
sympyrisch*%$./bin/test sympy//integrals/tests/test_prde.py
==================================================================== test process starts =====================================================================
executable:         /Users/aaronmeurer/anaconda/bin/python  (3.5.1-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python
random seed:        875421
hash randomization: on (PYTHONHASHSEED=688272957)

sympy/integrals/tests/test_prde.py[12] .........F..                                                                                                     [FAIL]

______________________________________________________________________________________________________________________________________________________________
_____________________________________________________ sympy/integrals/tests/test_prde.py:test_is_deriv_k _____________________________________________________
  File "/users/aaronmeurer/documents/python/sympy/sympy/sympy/integrals/tests/test_prde.py", line 172, in test_is_deriv_k
    ([(t1, 1), (t2, 1)], t1 + t2, 2)
AssertionError

==================================================== tests finished: 11 passed, 1 failed, in 1.44 seconds ====================================================
DO *NOT* COMMIT!
```

**Comment by jksuom** [comment]
That does not necessarily mean that the patch would not work. The form of the results could be slightly different.

**Comment by asmeurer** [comment]
Risch definitely can be smarter about logs (if I recall correctly, it tends to return things like log(a/b) + log(b)). I don't know if splitting logs in _log_part is the way to fix that. My preference in risch has generally been to try to keep the integrated expression as close to the integrand in form as possible.

**Comment by asmeurer** [comment]
The test failures in risch are troubling. They suggest to me that is_deriv_k isn't working at all (the whole point of the function is to detect cases like `log(x), log(x**2)` or `log(x), log(x + 1), log(2*x**2 + 2*x)` where the logs are algebraically dependent).

**Comment by jksuom** [comment]
I think that those failures should be investigated in any case.

**Comment by asmeurer** [comment]
Oh, I see the problem. You need to do 

```
l = []
ld = []
```

not,

```
l = ld = []
```

(otherwise they are the same list). With that change there are no test failures.

**Comment by jksuom** [comment]
Thanks. I did not think of it in detail.

**Comment by asmeurer** [comment]
I've looked at it closer and I think this patch is fine. I'm a little baffled this issue hasn't come up already.

**Comment by jksuom** [comment]
When I looked at the tests I noticed that all arguments were polynomials.

**Comment by asmeurer** [comment]
I guess this only comes up when you have two logarithms that are algebraically dependent, and have denominators.

**Comment by jksuom** [comment]
Closing because of #10842.
