### ISSUE TITLE
Implemented function gives ValueError when constructing float expression in sympy 1.0

### ISSUE THREAD

**Issue by matthew-brett** [sympy/sympy#10810]
Please forgive my imcomplete understanding here, but we ran into a new error with our package (nipy) when testing against sympy 1.0. (https://github.com/nipy/nipy/issues/395).

We use `sympy.utilities.lambdify.implemented_function` quite a bit to represent expressions which would be very cumbersome to represent symbolically.

One common implementation we use is an interpolated function of some numerical time-course - here's a toy example:

```
from scipy.interpolate import interp1d

from sympy.abc import t
from sympy.utilities.lambdify import implemented_function

func = interp1d(range(10), range(10))
sym_func = implemented_function('func', func)
```

In sympy 0.7.6 we could create expressions like this (these represent the onset of an event in time):

```
event_func = sym_func(t - 2.)
```

In sympy 1.0 this causes an error inside the implemented function, with this traceback:

```
Traceback (most recent call last):
  File "bad_func.py", line 14, in <module>
    sym_func(t - 2.)
  File "/Users/mb312/.virtualenvs/nibabel/lib/python2.7/site-packages/sympy/core/function.py", line 720, in __new__
    obj = super(AppliedUndef, cls).__new__(cls, *args, **options)
  File "/Users/mb312/.virtualenvs/nibabel/lib/python2.7/site-packages/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/mb312/.virtualenvs/nibabel/lib/python2.7/site-packages/sympy/core/compatibility.py", line 899, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/mb312/.virtualenvs/nibabel/lib/python2.7/site-packages/sympy/core/function.py", line 392, in __new__
    return result.evalf(mlib.libmpf.prec_to_dps(pr))
  File "/Users/mb312/.virtualenvs/nibabel/lib/python2.7/site-packages/sympy/core/evalf.py", line 1385, in evalf
    result = evalf(self, prec + 4, options)
  File "/Users/mb312/.virtualenvs/nibabel/lib/python2.7/site-packages/sympy/core/evalf.py", line 1284, in evalf
    re, im = x._eval_evalf(prec).as_real_imag()
  File "/Users/mb312/.virtualenvs/nibabel/lib/python2.7/site-packages/sympy/core/function.py", line 468, in _eval_evalf
    return Float(self._imp_(*self.args), prec)
  File "/Users/mb312/.virtualenvs/nibabel/lib/python2.7/site-packages/scipy/interpolate/polyint.py", line 79, in __call__
    x, x_shape = self._prepare_x(x)
  File "/Users/mb312/.virtualenvs/nibabel/lib/python2.7/site-packages/scipy/interpolate/polyint.py", line 91, in _prepare_x
    x = _asarray_validated(x, check_finite=False, as_inexact=True)
  File "/Users/mb312/.virtualenvs/nibabel/lib/python2.7/site-packages/scipy/_lib/_util.py", line 190, in _asarray_validated
    raise ValueError('object arrays are not supported')
ValueError: object arrays are not supported
```

What is happening at line 468 of `sympy/core/function.py` above is that sympy is trying to evaluate the implemented (therefore, numerical) function at the value `t - 2.` of type `sympy.core.add.Add`, and failing.

Looking at line 467-470 of `sympy/core/function.py`

```
            try:
                return Float(self._imp_(*self.args), prec)
            except (AttributeError, TypeError):
                return
```

The implemented function `_imp_` could reasonably return a ValueError at this point, when trying to evaluate the expression, rather than an AttributeError or TypeError, and in fact that is what the scipy interpolate function does.

Adding `ValueError` to the caught exceptions above fixes this for me.   That seems like a reasonable and general solution to me, but I may be missing something.  Should I submit a PR?

Thanks for your patience in reading this long report.

**Comment by oscarbenjamin** [comment]
I think this was supposed to be closed when #10874 was merged. I'm closing this now.
