### ISSUE TITLE
TypeError, SystemError and RecursionError from plot3d_parametric_surface

### ISSUE THREAD

**Issue by grelston** [sympy/sympy#10828]
I'm trying to plot the surface of an ellipsoid, following the parametric equations from [MathWorld](http://mathworld.wolfram.com/Ellipsoid.html). I get a 30,000-line Traceback, which I'll summarise later.

1. Environment:
  - Server Information:
    - You are using Jupyter notebook.
    - The version of the notebook server is 4.1.0 and is running on:
      - Python 3.5.1 |Anaconda 2.5.0 (32-bit)| (default, Jan 29 2016, 15:46:01) [MSC v.1900 32 bit (Intel)]
  - Current Kernel Information:
    - Python 3.5.1 |Anaconda 2.5.0 (32-bit)| (default, Jan 29 2016, 15:46:01) [MSC v.1900 32 bit (Intel)]
    - IPython 4.0.3 -- An enhanced Interactive Python.
2. Note: similar Traceback seen with Python 2.7.9 |Anaconda 2.3.0 (32-bit)| (default, Dec 18 2014, 17:00:07) [MSC v.1500 32 bit (Intel)]
3. Code:
```python
import sympy
sympy.__version__
# '0.7.6.1'
import numpy
numpy.__version__
# '1.10.4'
import matplotlib
matplotlib.__version__
# '1.5.1'

from sympy import symbols, init_printing
from sympy import exp, pi, sin, cos
init_printing()
a, b, c, u, v = symbols('a, b, c, u, v')

x = a * cos(u) * sin(v)
y = b * sin(u) * sin(v)
z = c * cos(v)

from sympy.plotting import plot3d_parametric_surface
%matplotlib qt
plot3d_parametric_surface(x, y, z, (u, 0, 2*pi), (v, 0, pi))
```
This is the Traceback, with a lot of repeated lines snipped:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: can't convert expression to float

During handling of the above exception, another exception occurred:

SystemError                               Traceback (most recent call last)
SystemError: <class 'int'> returned a result with an error set

[snip ~25,000 lines of repeated SystemErrors]

During handling of the above exception, another exception occurred:

SystemError                               Traceback (most recent call last)
<ipython-input-9-210dbd8237e1> in <module>()
----> 1 plot3d_parametric_surface(x, y, z, (u, 0, 2*pi), (v, 0, pi))

C:\Anaconda32\envs\py35-ana250\lib\site-packages\sympy\plotting\plot.py in plot3d_parametric_surface(*args, **kwargs)
   1712     plots = Plot(*series, **kwargs)
   1713     if show:
-> 1714         plots.show()
   1715     return plots
   1716 

C:\Anaconda32\envs\py35-ana250\lib\site-packages\sympy\plotting\plot.py in show(self)
    183             self._backend.close()
    184         self._backend = self.backend(self)
--> 185         self._backend.show()
    186 
    187     def save(self, path):

C:\Anaconda32\envs\py35-ana250\lib\site-packages\sympy\plotting\plot.py in show(self)
   1016 
   1017     def show(self):
-> 1018         self.process_series()
   1019         #TODO after fixing https://github.com/ipython/ipython/issues/1255
   1020         # you can uncomment the next line and remove the pyplot.show() call

C:\Anaconda32\envs\py35-ana250\lib\site-packages\sympy\plotting\plot.py in process_series(self)
    914                 collection = self.ax.plot_surface(x, y, z, cmap=self.cm.jet,
    915                                                   rstride=1, cstride=1,
--> 916                                                   linewidth=0.1)
    917             elif s.is_implicit:
    918                 #Smart bounds have to be set to False for implicit plots.

C:\Anaconda32\envs\py35-ana250\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py in plot_surface(self, X, Y, Z, *args, **kwargs)
   1679 
   1680         self.add_collection(polyc)
-> 1681         self.auto_scale_xyz(X, Y, Z, had_data)
   1682 
   1683         return polyc

C:\Anaconda32\envs\py35-ana250\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py in auto_scale_xyz(self, X, Y, Z, had_data)
    471         # to what the minimum sized rectangular volume holds the
    472         # data.
--> 473         self.xy_dataLim.update_from_data_xy(np.array([x, y]).T, not had_data)
    474         if z is not None:
    475             self.zz_dataLim.update_from_data_xy(np.array([z, z]).T, not had_data)

C:\Anaconda32\envs\py35-ana250\lib\site-packages\matplotlib\transforms.py in update_from_data_xy(self, xy, ignore, updatex, updatey)
    951             return
    952 
--> 953         path = Path(xy)
    954         self.update_from_path(path, ignore=ignore,
    955                                     updatex=updatex, updatey=updatey)

C:\Anaconda32\envs\py35-ana250\lib\site-packages\matplotlib\path.py in __init__(self, vertices, codes, _interpolation_steps, closed, readonly)
    135             vertices = vertices.astype(np.float_).filled(np.nan)
    136         else:
--> 137             vertices = np.asarray(vertices, np.float_)
    138 
    139         if (vertices.ndim != 2) or (vertices.shape[1] != 2):

C:\Anaconda32\envs\py35-ana250\lib\site-packages\numpy\core\numeric.py in asarray(a, dtype, order)
    472 
    473     """
--> 474     return array(a, dtype, copy=False, order=order)
    475 
    476 def asanyarray(a, dtype=None, order=None):

C:\Anaconda32\envs\py35-ana250\lib\site-packages\sympy\core\expr.py in __float__(self)
    218         # to fail, and if it is we still need to check that it evalf'ed to
    219         # a number.
--> 220         result = self.evalf()
    221         if result.is_Number:
    222             return float(result)

C:\Anaconda32\envs\py35-ana250\lib\site-packages\sympy\core\evalf.py in evalf(self, n, subs, maxn, chop, strict, quad, verbose)
   1307         if not evalf_table:
   1308             _create_evalf_table()
-> 1309         prec = dps_to_prec(n)
   1310         options = {'maxprec': max(prec, int(maxn*LG10)), 'chop': chop,
   1311                'strict': strict, 'verbose': verbose}

C:\Anaconda32\envs\py35-ana250\lib\site-packages\sympy\mpmath\libmp\libmpf.py in dps_to_prec(n)
     65     """Return the number of bits required to represent n decimals
     66     accurately."""
---> 67     return max(1, int(round((int(n)+1)*3.3219280948873626)))
     68 
     69 def repr_dps(n):

SystemError: <class 'int'> returned a result with an error set

Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Anaconda32\envs\py35-ana250\lib\site-packages\ipykernel\kernelapp.py", line 158, in excepthook
    traceback.print_exception(etype, evalue, tb, file=sys.__stderr__)
  File "C:\Anaconda32\envs\py35-ana250\lib\traceback.py", line 100, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "C:\Anaconda32\envs\py35-ana250\lib\traceback.py", line 463, in __init__
    _seen=_seen)
  File "C:\Anaconda32\envs\py35-ana250\lib\traceback.py", line 463, in __init__
    _seen=_seen)

[snip ~400 lines of this message]

  File "C:\Anaconda32\envs\py35-ana250\lib\traceback.py", line 457, in __init__
    type(exc_value.__context__),
RecursionError: maximum recursion depth exceeded while calling a Python object

Original exception was:
TypeError: can't convert expression to float

During handling of the above exception, another exception occurred:

SystemError: <class 'int'> returned a result with an error set

During handling of the above exception, another exception occurred:

SystemError: <class 'int'> returned a result with an error set

[snip ~5,000 lines of SystemErrors]
```

**Comment by grelston** [comment]
I ran the notebook again after updating to sympy-1.0 and got [very similar results](https://gist.github.com/grelston/bb4affd1072402c7ed96).
