### ISSUE TITLE
sympy.doctest("plotting") fails in python 3.5

### ISSUE THREAD

**Issue by ThomasHickman** [sympy/sympy#10855]
When running `sympy.doctest("plotting")`, the following errors occur:

```
>>> sympy.doctest("plotting")
========================================================================= test process starts =========================================================================
executable:         C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\python.exe  (3.5.0-final-0) [CPython]
architecture:       32-bit
cache:              yes
ground types:       python
hash randomization: on (PYTHONHASHSEED=2621906298)

sympy\plotting\experimental_lambdify.py[2] ..                                                                                                                      [OK]
sympy\plotting\plot.py[8] .sssssss                                                                                                                                 [OK]
sympy\plotting\plot_implicit.py[1] s                                                                                                                               [OK]
sympy\plotting\pygletplot\color_scheme.py[?]   Failed to import                                                                                                  [FAIL]
sympy\plotting\pygletplot\plot.py[?]   Failed to import                                                                                                          [FAIL]
sympy\plotting\pygletplot\plot_axes.py[?]   Failed to import                                                                                                     [FAIL]
sympy\plotting\pygletplot\plot_camera.py[?]   Failed to import                                                                                                   [FAIL]
sympy\plotting\pygletplot\plot_controller.py[?]   Failed to import                                                                                               [FAIL]
sympy\plotting\pygletplot\plot_curve.py[?]   Failed to import                                                                                                    [FAIL]
sympy\plotting\pygletplot\plot_mode.py[?]   Failed to import                                                                                                     [FAIL]
sympy\plotting\pygletplot\plot_modes.py[?]   Failed to import                                                                                                    [FAIL]
sympy\plotting\pygletplot\plot_mode_base.py[?]   Failed to import                                                                                                [FAIL]
sympy\plotting\pygletplot\plot_surface.py[?]   Failed to import                                                                                                  [FAIL]
sympy\plotting\pygletplot\plot_window.py[?]   Failed to import                                                                                                   [FAIL]
sympy\plotting\pygletplot\__init__.py[1] F                                                                                                                       [FAIL]

_______________________________________________________________________________________________________________________________________________________________________
__________________________________________ c:\users\hickman\documents\github\sympy\sympy\plotting\pygletplot\color_scheme.py __________________________________________
  File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 209, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
  File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\color_scheme.py", line 4, in <module>
    from util import interpolate, rinterpolate, create_bounds, update_bounds
ImportError: No module named 'util'
_______________________________________________________________________________________________________________________________________________________________________
______________________________________________ c:\users\hickman\documents\github\sympy\sympy\plotting\pygletplot\plot.py ______________________________________________
  File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 209, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
  File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\plot.py", line 15, in <module>
    from plot_object import PlotObject
ImportError: No module named 'plot_object'
_______________________________________________________________________________________________________________________________________________________________________
___________________________________________ c:\users\hickman\documents\github\sympy\sympy\plotting\pygletplot\plot_axes.py ____________________________________________
  File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 209, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
  File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\plot_axes.py", line 6, in <module>
    from plot_object import PlotObject
ImportError: No module named 'plot_object'
_______________________________________________________________________________________________________________________________________________________________________
__________________________________________ c:\users\hickman\documents\github\sympy\sympy\plotting\pygletplot\plot_camera.py ___________________________________________
  File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 209, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
  File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\plot_camera.py", line 4, in <module>
    from plot_rotation import get_spherical_rotatation
ImportError: No module named 'plot_rotation'
_______________________________________________________________________________________________________________________________________________________________________
________________________________________ c:\users\hickman\documents\github\sympy\sympy\plotting\pygletplot\plot_controller.py _________________________________________
  File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 209, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
  File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\plot_controller.py", line 5, in <module>
    from util import get_direction_vectors, get_basis_vectors
ImportError: No module named 'util'
_______________________________________________________________________________________________________________________________________________________________________
___________________________________________ c:\users\hickman\documents\github\sympy\sympy\plotting\pygletplot\plot_curve.py ___________________________________________
  File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 209, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
  File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\plot_curve.py", line 4, in <module>
    from plot_mode_base import PlotModeBase
ImportError: No module named 'plot_mode_base'
_______________________________________________________________________________________________________________________________________________________________________
___________________________________________ c:\users\hickman\documents\github\sympy\sympy\plotting\pygletplot\plot_mode.py ____________________________________________
  File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 209, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
  File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\plot_mode.py", line 4, in <module>
    from plot_interval import PlotInterval
ImportError: No module named 'plot_interval'
_______________________________________________________________________________________________________________________________________________________________________
___________________________________________ c:\users\hickman\documents\github\sympy\sympy\plotting\pygletplot\plot_modes.py ___________________________________________
  File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 209, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
  File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\plot_modes.py", line 3, in <module>
    from plot_curve import PlotCurve
ImportError: No module named 'plot_curve'
_______________________________________________________________________________________________________________________________________________________________________
_________________________________________ c:\users\hickman\documents\github\sympy\sympy\plotting\pygletplot\plot_mode_base.py _________________________________________
  File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 209, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
  File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\plot_mode_base.py", line 4, in <module>
    from plot_mode import PlotMode
ImportError: No module named 'plot_mode'
_______________________________________________________________________________________________________________________________________________________________________
__________________________________________ c:\users\hickman\documents\github\sympy\sympy\plotting\pygletplot\plot_surface.py __________________________________________
  File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 209, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
  File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\plot_surface.py", line 4, in <module>
    from plot_mode_base import PlotModeBase
ImportError: No module named 'plot_mode_base'
_______________________________________________________________________________________________________________________________________________________________________
__________________________________________ c:\users\hickman\documents\github\sympy\sympy\plotting\pygletplot\plot_window.py ___________________________________________
  File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 209, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
  File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\plot_window.py", line 4, in <module>
    from managed_window import ManagedWindow
ImportError: No module named 'managed_window'

_______________________________________________________________________________________________________________________________________________________________________
____________________________________________________________ sympy.plotting.pygletplot.__init__.PygletPlot ____________________________________________________________
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 20, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    Plot(x*y**3-y*x**3)
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[3]>", line 1, in <module>
        Plot(x*y**3-y*x**3)
      File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 139, in PygletPlot
        import plot
    ImportError: No module named 'plot'
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 23, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p = Plot()
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[4]>", line 1, in <module>
        p = Plot()
      File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 139, in PygletPlot
        import plot
    ImportError: No module named 'plot'
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 24, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p[1] = x*y
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[5]>", line 1, in <module>
        p[1] = x*y
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 25, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p[1].color = z, (0.4,0.4,0.9), (0.9,0.4,0.4)
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[6]>", line 1, in <module>
        p[1].color = z, (0.4,0.4,0.9), (0.9,0.4,0.4)
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 27, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p = Plot()
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[7]>", line 1, in <module>
        p = Plot()
      File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 139, in PygletPlot
        import plot
    ImportError: No module named 'plot'
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 28, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p[1] =  x**2+y**2
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[8]>", line 1, in <module>
        p[1] =  x**2+y**2
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 29, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p[2] = -x**2-y**2
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[9]>", line 1, in <module>
        p[2] = -x**2-y**2
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 39, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    Plot(x**2) # implies [x,-5,5,100]
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[10]>", line 1, in <module>
        Plot(x**2) # implies [x,-5,5,100]
      File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 139, in PygletPlot
        import plot
    ImportError: No module named 'plot'
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 42, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    Plot(x**2, [], []) # [x,-1,1,40], [y,-1,1,40]
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[11]>", line 1, in <module>
        Plot(x**2, [], []) # [x,-1,1,40], [y,-1,1,40]
      File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 139, in PygletPlot
        import plot
    ImportError: No module named 'plot'
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 44, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    Plot(x**2-y**2, [100], [100]) # [x,-1,1,100], [y,-1,1,100]
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[12]>", line 1, in <module>
        Plot(x**2-y**2, [100], [100]) # [x,-1,1,100], [y,-1,1,100]
      File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 139, in PygletPlot
        import plot
    ImportError: No module named 'plot'
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 46, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    Plot(x**2, [x,-13,13,100])
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[13]>", line 1, in <module>
        Plot(x**2, [x,-13,13,100])
      File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 139, in PygletPlot
        import plot
    ImportError: No module named 'plot'
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 48, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    Plot(x**2, [-13,13]) # [x,-13,13,100]
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[14]>", line 1, in <module>
        Plot(x**2, [-13,13]) # [x,-13,13,100]
      File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 139, in PygletPlot
        import plot
    ImportError: No module named 'plot'
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 50, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    Plot(x**2, [x,-13,13]) # [x,-13,13,100]
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[15]>", line 1, in <module>
        Plot(x**2, [x,-13,13]) # [x,-13,13,100]
      File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 139, in PygletPlot
        import plot
    ImportError: No module named 'plot'
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 52, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    Plot(1*x, [], [x], mode='cylindrical')
    # [unbound_theta,0,2*Pi,40], [x,-1,1,20]
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[16]>", line 1, in <module>
        Plot(1*x, [], [x], mode='cylindrical')
      File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 139, in PygletPlot
        import plot
    ImportError: No module named 'plot'
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 85, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p = Plot(visible=False)
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[18]>", line 1, in <module>
        p = Plot(visible=False)
      File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 139, in PygletPlot
        import plot
    ImportError: No module named 'plot'
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 87, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p[1] = f
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[20]>", line 1, in <module>
        p[1] = f
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 88, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p[2] = f.diff(x)
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[21]>", line 1, in <module>
        p[2] = f.diff(x)
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 94, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p.show()
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[24]>", line 1, in <module>
        p.show()
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 95, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p.clear()
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[25]>", line 1, in <module>
        p.clear()
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 96, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[26]>", line 1, in <module>
        p
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 98, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p[1] =  x**2+y**2
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[27]>", line 1, in <module>
        p[1] =  x**2+y**2
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 99, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p[1].style = 'solid'
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[28]>", line 1, in <module>
        p[1].style = 'solid'
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 100, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p[2] = -x**2-y**2
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[29]>", line 1, in <module>
        p[2] = -x**2-y**2
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 101, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p[2].style = 'wireframe'
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[30]>", line 1, in <module>
        p[2].style = 'wireframe'
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 102, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p[1].color = z, (0.4,0.4,0.9), (0.9,0.4,0.4)
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[31]>", line 1, in <module>
        p[1].color = z, (0.4,0.4,0.9), (0.9,0.4,0.4)
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 103, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p[1].style = 'both'
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[32]>", line 1, in <module>
        p[1].style = 'both'
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 104, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p[2].style = 'both'
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[33]>", line 1, in <module>
        p[2].style = 'both'
    NameError: name 'p' is not defined
**********************************************************************
File "C:\Users\Hickman\Documents\GitHub\sympy\sympy\plotting\pygletplot\__init__.py", line 105, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    p.close()
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Hickman\AppData\Local\Programs\Python\Python35-32\lib\doctest.py", line 1320, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.pygletplot.__init__.PygletPlot[34]>", line 1, in <module>
        p.close()
    NameError: name 'p' is not defined

============================================ tests finished: 3 passed, 1 failed, 8 skipped, 11 exceptions, in 3.13 seconds ============================================
DO *NOT* COMMIT!
```

I think this is caused by a dot not being used for relative imports e.g. `import plot` should be `from .plot import PygletPlot` in https://github.com/sympy/sympy/blob/59e9ab5c5a2f1cf2cd809c23b7c3d89d442c069a/sympy/plotting/pygletplot/__init__.py#L139. This is not getting picked up from the doctests on TravisCI because pyglet is not installed on the travis build and "sympy/plotting/pygletplot" is therefore blacklisted (https://github.com/sympy/sympy/blob/59e9ab5c5a2f1cf2cd809c23b7c3d89d442c069a/sympy/utilities/runtests.py#L652).

**Comment by ThomasHickman** [comment]
Just seen http://stackoverflow.com/questions/25791425/plot-with-sympy-in-python-3. pygletplot therefore should be blacklisted in all cases, not just if pyglet is not installed.

**Comment by asmeurer** [comment]
It should work, though. It's just not the recommended way of plotting.

**Comment by jbm950** [comment]
When run locally I get the following.

``` python
>>> sympy.doctest("plotting")
================================================================================ test process starts ================================================================================
executable:         /Users/james/anaconda/bin/python3  (3.5.1-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
hash randomization: on (PYTHONHASHSEED=2864459397)

sympy/plotting/experimental_lambdify.py[2] ..                                                                                                                                    [OK]
sympy/plotting/plot.py[8] ........                                                                                                                                               [OK]
sympy/plotting/plot_implicit.py[1] /Users/james/anaconda/lib/python3.5/site-packages/matplotlib/pyplot.py:516: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)
.                                                                                                                                             [OK]

==================================================================== tests finished: 11 passed, in 7.47 seconds =====================================================================
```

On mine it looks like the pygletplot tests were not run at all. I do not know how the doctests work though so I do not know where to look to see if they have been removed or have already been blacklisted.

**Comment by asmeurer** [comment]
It's probably skipped entirely unless you have pyglet installed.

**Comment by jbm950** [comment]
I agree with Thomas that the errors seem to be from relative import errors. Two fixes would be to define the whole path to the module as is done in [physics/mechanics/kane.py](https://github.com/sympy/sympy/blob/master/sympy/physics/mechanics/kane.py) or doing the relative imports like Thomas mentioned which is currently done in [physics/mechanics/\__init\__.py](https://github.com/sympy/sympy/blob/master/sympy/physics/mechanics/__init__.py) (these just happen to be the files that I've been working with recently and show the different import procedures). I agree with Aaron though on not simply blacklisting the tests because they aren't working. That kind of defeats the whole point of having tests. Is there a way to add pyglet to the test environment so that these tests are run more often?

Another interesting note is that the relative imports is a Python 3.X problem. On 2.X I get no import errors but rather a multitude of `KeyError`'s. This is probably a separate problem masked by the fact that these tests aren't often run.

**Comment by asmeurer** [comment]
It seems this file was never converted to Python 3.

**Comment by neutrinoceros** [comment]
Python 3.5 has been unsupported for a while now, but better safe than sorry: I tested this in Python 3.8 (the oldest supported version at the moment) and Python 3.13.0rc1 with the master branch and the latest release (1.13.1) and it worked in all cases, so I think this can safely be closed.

**Comment by oscarbenjamin** [comment]
Thanks!

I think we should also drop 3.8 and 3.9 now so that 3.10 is the minimum version for the next release.
