### ISSUE TITLE
FallingFactorial(k, k-1) can be simplified

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#10938]
Currently, if
```python
>>> k = Symbol('k', integer=True)
```
then
```python
>>> ff(k, k)
factorial(k)
```
but
```python
>>> fk(k, k-1)
FallingFactorial(k, k - 1)
```
and even
```python
>>> simplify(ff(k, k-1))
zoo/gamma(-k)
```
and
```python
solve(Eq(ff(k, k-1), factorial(k)))
```
raises
```pytb
Traceback (most recent call last):
  File "<ipython-input-32-0b07fff95566>", line 1, in <module>
    solve(Eq(ff(k, k-1), factorial(k)))
  File "sympy/solvers/solvers.py", line 1053, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "sympy/solvers/solvers.py", line 1619, in _solve
    raise NotImplementedError('\n'.join([msg, not_impl_msg % f]))
NotImplementedError: multiple generators [FallingFactorial(k, k - 1), factorial(k)]
No algorithms are implemented to solve equation FallingFactorial(k, k - 1) - factorial(k)
```

I think `ff(k, k-1)` should be simplified to `factorial(k)`, just like `ff(k, k)`.

**Comment by Nitin216** [comment]
@pelegm If you use rewrite with ff then it gives right answer.
```
In [11]: ff(k,k-1).rewrite(factorial)
Out[11]: k!
In [12]: ff(k,k-2).rewrite(factorial)
Out[12]:
k!
--
2
In [13]: ff(k,k-3).rewrite(factorial)
Out[13]:
k!
--
6
In [14]: solve(Eq(ff(k,k-1).rewrite(factorial),factorial(k)))
Out[14]: True
```

**Comment by pelegm** [comment]
I agree, but I am not sure this is a solution.

Perhaps we should have some `full_simplify` method that will try to simplify using a rewrite as factorial as well?
