### ISSUE TITLE
Infinite loop in sympy.parsing.sympy_parser.parse_expr

### ISSUE THREAD

**Issue by wohnjayne** [sympy/sympy#10952]
sympy.parsing.sympy_parser.parse_expr goes into an infinite loop for specific inputs.

one of them is 
`sin(cos(exp(exp(exp(exp(1))))))`

minimum example:

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> print sympy.__version__
1.0
>>> str="sin(cos(exp(exp(exp(exp(1))))))"
>>> from sympy.parsing.sympy_parser import parse_expr
>>> f=parse_expr(str) 
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/sympy/parsing/sympy_parser.py", line 894, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/usr/local/lib/python2.7/dist-packages/sympy/parsing/sympy_parser.py", line 807, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/compatibility.py", line 899, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/function.py", line 385, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/compatibility.py", line 899, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/function.py", line 209, in __new__
    evaluated = cls.eval(*args)
  File "/usr/local/lib/python2.7/dist-packages/sympy/functions/elementary/trigonometric.py", line 261, in eval
    i_coeff = arg.as_coefficient(S.ImaginaryUnit)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/expr.py", line 1444, in as_coefficient
    r = self.extract_multiplicatively(expr)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/expr.py", line 1920, in extract_multiplicatively
    quotient = self / c
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/decorators.py", line 118, in binary_op_wrapper
    return func(self, other)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/expr.py", line 161, in __div__
    return Mul(self, Pow(other, S.NegativeOne))
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/compatibility.py", line 899, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/operations.py", line 41, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/mul.py", line 181, in flatten
    if not a.is_zero and a.is_Rational:
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 245, in getit
    return _ask(fact, self)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 300, in _ask
    _ask(pk, obj)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 288, in _ask
    a = evaluate(obj)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/expr.py", line 697, in _eval_is_positive
    n2 = self._eval_evalf(2)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/function.py", line 503, in _eval_evalf
    v = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/mpmath/ctx_mp_python.py", line 993, in f
    return ctx.make_mpf(mpf_f(x._mpf_, prec, rounding))
  File "/usr/local/lib/python2.7/dist-packages/mpmath/libmp/libelefun.py", line 1378, in mpf_cos
    def mpf_cos(x, prec, rnd=round_fast): return mpf_cos_sin(x, prec, rnd, 1)
  File "/usr/local/lib/python2.7/dist-packages/mpmath/libmp/libelefun.py", line 1359, in mpf_cos_sin
    t, n, wp = mod_pi2(man, exp, mag, wp)
  File "/usr/local/lib/python2.7/dist-packages/mpmath/libmp/libelefun.py", line 1270, in mod_pi2
    pi2 = pi_fixed(wpmod-1)
  File "/usr/local/lib/python2.7/dist-packages/mpmath/libmp/libelefun.py", line 99, in g
    f.memo_val = f(newprec, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mpmath/libmp/libelefun.py", line 245, in pi_fixed
    g, p, q = bs_chudnovsky(0, N, 0, verbose)
  File "/usr/local/lib/python2.7/dist-packages/mpmath/libmp/libelefun.py", line 227, in bs_chudnovsky
    g2, p2, q2 = bs_chudnovsky(mid, b, level+1, verbose)
  File "/usr/local/lib/python2.7/dist-packages/mpmath/libmp/libelefun.py", line 230, in bs_chudnovsky
    q = q1*p2 + q2*g1
KeyboardInterrupt

```

(I interrupted the command after a couple of seconds, but it runs forever)

**Note 1:**
On second try, command immediately returns:

```
[continued from above]
>>> f=parse_expr(str) 
>>> print f
sin(cos(exp(exp(exp(E)))))
```

... but then, f.evalf() will not work and loop infinitely
`f.evalf()`

```
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 1385, in evalf
    result = evalf(self, prec + 4, options)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 1278, in evalf
    r = rf(x, prec, options)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 754, in evalf_trig
    re, im, re_acc, im_acc = evalf(arg, xprec, options)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 1278, in evalf
    r = rf(x, prec, options)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 777, in evalf_trig
    re, im, re_acc, im_acc = evalf(arg, xprec, options)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 1278, in evalf
    r = rf(x, prec, options)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 1247, in <lambda>
    Pow(S.Exp1, x.args[0], evaluate=False), prec, options),
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 689, in evalf_pow
    yre, yim, _, _ = evalf(exp, prec, options)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 1278, in evalf
    r = rf(x, prec, options)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 1247, in <lambda>
    Pow(S.Exp1, x.args[0], evaluate=False), prec, options),
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 689, in evalf_pow
    yre, yim, _, _ = evalf(exp, prec, options)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 1278, in evalf
    r = rf(x, prec, options)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 1247, in <lambda>
    Pow(S.Exp1, x.args[0], evaluate=False), prec, options),
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 689, in evalf_pow
    yre, yim, _, _ = evalf(exp, prec, options)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 1278, in evalf
    r = rf(x, prec, options)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/evalf.py", line 1241, in <lambda>
    Exp1: lambda x, prec, options: (mpf_e(prec), None, prec, None),
  File "/usr/local/lib/python2.7/dist-packages/mpmath/libmp/libelefun.py", line 116, in f
    v = fixed(wp)
  File "/usr/local/lib/python2.7/dist-packages/mpmath/libmp/libelefun.py", line 99, in g
    f.memo_val = f(newprec, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mpmath/libmp/libelefun.py", line 279, in e_fixed
    return ((p+q)<<prec)//q
KeyboardInterrupt
```

Edit: removed Note 2, wrong usage of sympy.var()

**Comment by smichr** [comment]
Use `evaluate=False` when parsing or else this will try to compute `sin(cos(2.33e+1656520))`. Not sure how you will compute the final expression, however.

**Comment by smichr** [comment]
duplicates #6835
