### ISSUE TITLE
BlockMatrix assumes Symbols are matrices unless complex=True

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10959]
Not sure if this is intentional:

```
>>> x = Symbol('x')
>>> BlockMatrix([[x]]).transpose()
Matrix([[x']])
>>> x = Symbol('x', complex=True)
>>> BlockMatrix([[x]]).transpose()
Matrix([[x]])
>>>
```

It seems to me that symbols should be treated as scalars always, since if I wanted to use a matrix I would have used a MatrixSymbol.

(from https://stackoverflow.com/questions/36353593/suppress-the-transpose-of-a-symbol-in-sympy-output-when-the-symbol-is-a-scalar).

**Comment by czgdp1807** [comment]
Update:
```python
>>> x = Symbol('x')
>>> BlockMatrix([[x]]).transpose()
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/matrices/expressions/blockmatrix.py", line 98, in __new__
    ok = len({i.rows for i in r}) == 1
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/matrices/expressions/blockmatrix.py", line 98, in <setcomp>
    ok = len({i.rows for i in r}) == 1
AttributeError: 'Symbol' object has no attribute 'rows'
>>> x = Symbol('x', complex=True)
>>> BlockMatrix([[x]]).transpose()
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/matrices/expressions/blockmatrix.py", line 98, in __new__
    ok = len({i.rows for i in r}) == 1
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/matrices/expressions/blockmatrix.py", line 98, in <setcomp>
    ok = len({i.rows for i in r}) == 1
AttributeError: 'Symbol' object has no attribute 'rows'
```
Is the issue still valid?

**Comment by asmeurer** [comment]
I guess symbols no longer work at all in BlockMatrix, so this can be closed.
