### ISSUE TITLE
Sum((-n + (n**3 + 1)**(S(1)/3))/log(n), (n, 1, oo)).is_convergent() raises Recursion Error

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#10973]
```
>>> n = Symbol('n', integer=True)
>>> Sum((-n + (n**3 + 1)**(S(1)/3))/log(n), (n, 1, oo)).is_convergent()
Traceback (most recent call last):
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 241, in getit
    return self._assumptions[fact]
KeyError: 'zero'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 241, in getit
    return self._assumptions[fact]
KeyError: 'zero'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 241, in getit
    return self._assumptions[fact]
KeyError: 'real'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 241, in getit
    return self._assumptions[fact]
KeyError: 'complex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 241, in getit
    return self._assumptions[fact]
KeyError: 'complex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 241, in getit
    return self._assumptions[fact]
KeyError: 'complex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 241, in getit
    return self._assumptions[fact]
KeyError: 'zero'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1593, in _solve
    rv = {inv.subs(isym, xi) for xi in _solve(eq, isym, **flags)}
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 1585, in _solve
    u = unrad(f_num, symbol)
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 3174, in unrad
    return _canonical(eq, cov)
  File "/home/gxyd/Public/sympy/sympy/solvers/solvers.py", line 3023, in _canonical
    eq = eq.xreplace(rep)
  File "/home/gxyd/Public/sympy/sympy/core/basic.py", line 1093, in xreplace
    value, _ = self._xreplace(rule)
  File "/home/gxyd/Public/sympy/sympy/core/basic.py", line 1107, in _xreplace
    a_xr = a._xreplace(rule)
  File "/home/gxyd/Public/sympy/sympy/core/basic.py", line 1107, in _xreplace
    a_xr = a._xreplace(rule)
  File "/home/gxyd/Public/sympy/sympy/core/basic.py", line 1114, in _xreplace
    return self.func(*args), True
  File "/home/gxyd/Public/sympy/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/gxyd/Public/sympy/sympy/core/function.py", line 405, in __new__
    pr = max(cls._should_evalf(a) for a in result.args)
  File "/home/gxyd/Public/sympy/sympy/core/function.py", line 405, in <genexpr>
    pr = max(cls._should_evalf(a) for a in result.args)
  File "/home/gxyd/Public/sympy/sympy/core/function.py", line 429, in _should_evalf
    m = arg.match(a + b*S.ImaginaryUnit)
  File "/home/gxyd/Public/sympy/sympy/core/basic.py", line 1497, in match
    return pattern.matches(self, old=old)
  File "/home/gxyd/Public/sympy/sympy/core/add.py", line 368, in matches
    return AssocOp._matches_commutative(self, expr, repl_dict, old)
  File "/home/gxyd/Public/sympy/sympy/core/operations.py", line 215, in _matches_commutative
    d1 = w.matches(last_op, repl_dict)
  File "/home/gxyd/Public/sympy/sympy/core/mul.py", line 859, in matches
    return AssocOp._matches_commutative(self, expr, repl_dict, old)
  File "/home/gxyd/Public/sympy/sympy/core/operations.py", line 201, in _matches_commutative
    newexpr = self._combine_inverse(expr, exact)
  File "/home/gxyd/Public/sympy/sympy/core/mul.py", line 968, in _combine_inverse
    return lhs/rhs
  File "/home/gxyd/Public/sympy/sympy/core/decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "/home/gxyd/Public/sympy/sympy/core/decorators.py", line 118, in binary_op_wrapper
    return func(self, other)
  File "/home/gxyd/Public/sympy/sympy/core/expr.py", line 161, in __div__
    return Mul(self, Pow(other, S.NegativeOne))
  File "/home/gxyd/Public/sympy/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/gxyd/Public/sympy/sympy/core/operations.py", line 41, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "/home/gxyd/Public/sympy/sympy/core/mul.py", line 182, in flatten
    if not a.is_zero and a.is_Rational:
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 245, in getit
    return _ask(fact, self)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 288, in _ask
    a = evaluate(obj)
  File "/home/gxyd/Public/sympy/sympy/core/mul.py", line 1040, in _eval_is_zero
    z = a.is_zero
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 245, in getit
    return _ask(fact, self)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 288, in _ask
    a = evaluate(obj)
  File "/home/gxyd/Public/sympy/sympy/core/add.py", line 502, in _eval_is_zero
    if a.is_real:
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 245, in getit
    return _ask(fact, self)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 288, in _ask
    a = evaluate(obj)
  File "/home/gxyd/Public/sympy/sympy/core/mul.py", line 1072, in _eval_is_real
    return self._eval_real_imag(True)
  File "/home/gxyd/Public/sympy/sympy/core/mul.py", line 1078, in _eval_real_imag
    if not t.is_complex:
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 245, in getit
    return _ask(fact, self)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 288, in _ask
    a = evaluate(obj)
  File "/home/gxyd/Public/sympy/sympy/core/power.py", line 455, in _eval_is_complex
    if all(a.is_complex for a in self.args):
  File "/home/gxyd/Public/sympy/sympy/core/power.py", line 455, in <genexpr>
    if all(a.is_complex for a in self.args):
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 245, in getit
    return _ask(fact, self)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 288, in _ask
    a = evaluate(obj)
  File "/home/gxyd/Public/sympy/sympy/core/add.py", line 454, in <lambda>
    (a.is_complex for a in self.args), quick_exit=True)
  File "/home/gxyd/Public/sympy/sympy/core/logic.py", line 78, in _fuzzy_group
    for a in args:
  File "/home/gxyd/Public/sympy/sympy/core/add.py", line 454, in <genexpr>
    (a.is_complex for a in self.args), quick_exit=True)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 245, in getit
    return _ask(fact, self)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 300, in _ask
    _ask(pk, obj)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 300, in _ask
    _ask(pk, obj)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 300, in _ask
    _ask(pk, obj)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 300, in _ask
    _ask(pk, obj)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 300, in _ask
    _ask(pk, obj)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 300, in _ask
    _ask(pk, obj)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 288, in _ask
    a = evaluate(obj)
  File "/home/gxyd/Public/sympy/sympy/core/power.py", line 1034, in _eval_is_algebraic
    if self.base.is_zero or (self.base - 1).is_zero:
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 245, in getit
    return _ask(fact, self)
  File "/home/gxyd/Public/sympy/sympy/core/assumptions.py", line 288, in _ask
    a = evaluate(obj)
  File "/home/gxyd/Public/sympy/sympy/core/add.py", line 511, in _eval_is_zero
    elif (S.ImaginaryUnit*a).is_real:
  File "/home/gxyd/Public/sympy/sympy/core/decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "/home/gxyd/Public/sympy/sympy/core/decorators.py", line 118, in binary_op_wrapper
    return func(self, other)
  File "/home/gxyd/Public/sympy/sympy/core/expr.py", line 141, in __mul__
    return Mul(self, other)
  File "/home/gxyd/Public/sympy/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/gxyd/Public/sympy/sympy/core/operations.py", line 41, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "/home/gxyd/Public/sympy/sympy/core/mul.py", line 537, in flatten
    n, p = divmod(p, q)
  File "/home/gxyd/Public/sympy/sympy/core/numbers.py", line 1765, in __divmod__
    return Tuple(*(divmod(self.p, other.p)))
  File "/home/gxyd/Public/sympy/sympy/core/containers.py", line 36, in __new__
    args = [ sympify(arg) for arg in args ]
  File "/home/gxyd/Public/sympy/sympy/core/containers.py", line 36, in <listcomp>
    args = [ sympify(arg) for arg in args ]
  File "/home/gxyd/Public/sympy/sympy/core/sympify.py", line 253, in sympify
    return converter[cls](a)
  File "/home/gxyd/Public/sympy/sympy/core/numbers.py", line 1720, in __new__
    if isinstance(i, string_types):
RecursionError: maximum recursion depth exceeded in __instancecheck__
```

**Comment by sachin-4099** [comment]
No longer raises `RecursionError` but raises:
`NotImplementedError: The algorithm to find the Sum convergence of (-n + (n**3 + 1)**(1/3))/log(n) is not yet implemented.`
