### ISSUE TITLE
plotting.intervalmath test fails (problem with float rounding)

### ISSUE THREAD

**Issue by vasdommes** [sympy/sympy#10987]
latest sympy master branch
numpy 1.11.0
Python 3.5.1
Win10 x64

sympy\plotting\intervalmath\tests\test_interval_functions.py
test_tan() fails:
```python
Failure
Traceback (most recent call last):
  File "C:\Anaconda\envs\sympy\lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "C:\Anaconda\envs\sympy\lib\unittest\case.py", line 600, in run
    testMethod()
  File "C:\Anaconda\envs\sympy\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\vasdommes\Source\Repos\sympy\sympy\plotting\intervalmath\tests\test_interval_functions.py", line 173, in test_tan
    assert a.end == np.tan(np.pi / 4)
AssertionError
```

If fact this test should pass: `a.end - np.tan(np.pi / 4)` evaluates to `1.11022302463e-16`, so it's just rounding error.
I assume that test should use something like `numpy.isclose()` (or py3.5. `math.isclose()`) instead of `==`.

**Comment by Nitin216** [comment]
@vasdommes I am getting no assertion Error. I am getting this output:
```
In [2]: s.test('sympy/plotting/intervalmath/tests/test_interval_functions.py')
============================= test process starts =============================
executable:         c:\Users\Nitin\Miniconda2\python.exe  (2.7.11-final-0) [CPyt
hon]
architecture:       32-bit
cache:              yes
ground types:       python
random seed:        98718177
hash randomization: on (PYTHONHASHSEED=833558430)

sympy\plotting\intervalmath\tests\test_interval_functions.py[24] ..............
..........                                                                 [OK]

================= tests finished: 24 passed, in 0.19 seconds ==================
Out[2]: True
```
So Please check if your repo is latest.

**Comment by vasdommes** [comment]
@Nitin216 yes, my repo is latest (BTW, last change in intervalmath was one year ago).

The last line fails in this test:
```python
def test_tan():
    a = tan(interval(0, np.pi / 4))
    assert a.start == 0
    assert a.end == np.tan(np.pi / 4)
```

But if I replace it with
```python
assert a.end == np.sin(np.pi / 4) / np.cos(np.pi / 4)
```
then everything works fine.


So test fails if `np.sin(np.pi / 4) / np.cos(np.pi / 4) == np.tan(np.pi / 4)` is `False`.
I assume that in almost all cases it returns `True`, but sometimes _float_ rounding messes things up (as in my case). On my machine
`np.sin(np.pi / 4) / np.cos(np.pi / 4) - np.tan(np.pi / 4)` returns `1.11022302463e-16`.

P.S. As far as I know, testing floating-point numbers for equality with `==` operator is generally considered as bad idea.

**Comment by Nitin216** [comment]
Sorry @vasdommes, but mine is not giving any error and my ```test_tan()``` is:
```
def test_tan():
    a = tan(interval(0, np.pi / 4))
    assert a.start == 0
    assert a.end == np.tan(np.pi / 4)

    a = tan(interval(np.pi / 4, 3 * np.pi / 4))
    #discontinuity
    assert a.is_valid is None
```

**Comment by vasdommes** [comment]
@Nitin216 my `test_tan()` is the same as yours.

I noticed from your output that you used Python 2.7. So I ran the tests under Python 2.7 & numpy 1.9.3, and everything worked fine.
For me the error arises under Python 3.5.1 & numpy 1.10.4 or 1.11.0. Could you check it on your machine?

**Comment by Nitin216** [comment]
@vasdommes Will check ok
