### ISSUE TITLE
diophantine(x**3+y**3-2) -> KeyError instead of {(1, 1)}

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#11026]
```
>>> diophantine(x**3+y**3-2)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/sympy/sympy/solvers/diophantine.py", line 86, in diophantine
    var_t, jnk, eq_type = classify_diop(base)
  File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/sympy/sympy/solvers/diophantine.py", line 328, in classify_diop
    coeff[term] == Integer(0)
KeyError: x**2*y
```

**Comment by lePerdu** [comment]
`coeff[term] == Integer(0)` should be `coeff[term] = Integer(0)` (assignment, not equality)

Now:
```python
>>> classify_diop(x**3+y**3-2)
([x, y], {y**3: 1, 1: -2, x*y**2: 0, x**2*y: 0, x**3: 1}, 'cubic_thue')
```

**Comment by smichr** [comment]
Thanks, got it in #10997.
