### ISSUE TITLE
Error while simplifying equations containing csc and sec using trigsimp_groebner 

### ISSUE THREAD

**Issue by kirankonduru** [sympy/sympy#11062]
>>> from sympy import *
>>> from sympy.simplify.trigsimp import *
>>> from sympy.abc import x,y
>>> trigsimp_groebner(csc(x) * sin(x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\sympy\simplify\trigsimp.py", line 379, in trigsimp_groebner
    num = Poly(num, gens=gens+freegens).eject(*gens)
NameError: name 'Poly' is not defined

**Comment by parsoyaarihant** [comment]
@kirankonduru  I would like to work on this issue, how do i start?

**Comment by OMantere** [comment]
Shouldn't this be closed?
