### ISSUE TITLE
No algorithms are implemented for solving (-2)**x=4

### ISSUE THREAD

**Issue by trxrunner** [sympy/sympy#11096]
> > > solve(Eq((-2)**x,4))

Traceback (most recent call last):
  File "<pyshell#97>", line 1, in <module>
    solve(Eq((-2) *\* x,4))
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\solvers\solvers.py", line 1053, in solve
    solution = _solve(f[0], _symbols, *_flags)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\solvers\solvers.py", line 1619, in _solve
    raise NotImplementedError('\n'.join([msg, not_impl_msg % f]))
NotImplementedError: 
No algorithms are implemented to solve equation (-2) *\* x - 4

**Comment by parsoyaarihant** [comment]
I would like to work on this issue. @aktech , could you give some advice on how to go ahead on this one?

**Comment by asmeurer** [comment]
And solveset gives the wrong answer (`2` is a real solution)

```
In [26]: solveset(Eq((-2)**x,4), domain=S.Reals)
Out[26]: ∅
```
