### ISSUE TITLE
'denom' is not defined error with sympifying some expressions

### ISSUE THREAD

**Issue by trxrunner** [sympy/sympy#11167]
```
>>> sympify(Abs(Abs(Pow(Integer(2), Rational(1, 2)))))
Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    sympify(Abs(Abs(Pow(Integer(2), Rational(1, 2)))))
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\function.py", line 385, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\function.py", line 209, in __new__
    evaluated = cls.eval(*args)
  File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\functions\elementary\complexes.py", line 471, in eval
    if denom(exponent.as_content_primitive()[0]):
NameError: name 'denom' is not defined


>>> sympify(Abs(Abs(Pow(Integer(2), Integer(2)))))
4
```
It only has an error for certain cases.

**Comment by jksuom** [comment]
I cannot reproduce the error. This is what I get:
```
>>> sympify(Abs(Abs(Pow(Integer(2), Rational(1, 2)))))
sqrt(2)
```
It also seems that there is no line containing `denom(exponent.as_content_primitive()[0])`.
