### ISSUE TITLE
Plot: axis_center=(x, y) does not work together with xscale='log'

### ISSUE THREAD

**Issue by spors** [sympy/sympy#11185]
Using axis_center=(x0, y0) together with xscale='log' in sympy.plot generates an empty image. For instance

`sym.plot(sym.exp(t), (t,1,10), xscale='log', axis_center=(5, 0))`

Using a linearly scaled x-axis works fine

sym.plot(sym.exp(t), (t,1,10), axis_center=(5, 0))

**Comment by highintothesky** [comment]
this issue still has not been fixed, any updates? accessing the matplotlib backend also doesn't seem to work.

**Comment by oscargus** [comment]
This is the current error:

```
sym.plot(sym.exp(t), (t,1,10), xscale='log', axis_center=(5, 0))
/nobackup/data/sympy/sympy/plotting/plot.py:1243: UserWarning: Tight layout not applied. The left and right margins cannot be made large enough to accommodate all axes decorations. 
  self.fig.tight_layout()
Traceback (most recent call last):

  File "/nobackup/data/anaconda3/lib/python3.7/site-packages/IPython/core/formatters.py", line 341, in __call__
    return printer(obj)

  File "/nobackup/data/anaconda3/lib/python3.7/site-packages/IPython/core/pylabtools.py", line 244, in <lambda>
    png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))

  File "/nobackup/data/anaconda3/lib/python3.7/site-packages/IPython/core/pylabtools.py", line 128, in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File "/nobackup/data/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
    **kwargs)

  File "/nobackup/data/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 527, in print_png
    FigureCanvasAgg.draw(self)

  File "/nobackup/data/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 386, in draw
    self.renderer = self.get_renderer(cleared=True)

  File "/nobackup/data/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 399, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)

  File "/nobackup/data/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 86, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi)

ValueError: Image size of 333537x264 pixels is too large. It must be less than 2^16 in each direction.
```
Not clear if it is Matplotlib or SymPy that claims that 333547 pixels are required...

(Skipping the `tight_layout` call gives the same error later.)
