### ISSUE TITLE
`Eq` does not lambdified with sympy module

### ISSUE THREAD

**Issue by fokinpv** [sympy/sympy#11248]
SymPy 1.0. Seems this is a bug. Could not lambdify `Eq` with sympy, with numpy it works ok. 

```
>>> f = Eq(x, y)
>>> f_ = lambdify((x, y), f, 'sympy')
>>> f_(1, 1)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
NameError: global name 'Eq' is not defined

>>> f_ = lambdify((x, y), f, 'numpy')
>>> f_(1, 1)
True
```

**Comment by oscargus** [comment]
This seems to have been fixed since.

```
from sympy import *
x = Symbol('x')
y = Symbol('y')
f = Eq(x, y)
ff = lambdify((x, y), f, 'sympy')
ff(1, 1)
Out[6]: True
```

Now, the result uses `==` which works for numerical problems, but not for symbolic. Still, I think this can be closed.

**Comment by oscarbenjamin** [comment]
I've added the could close label which I use to find and close issues later if no one responds.

In some cases I do think that the issue should be closed by adding a test so it doesn't break again though.
