### ISSUE TITLE
geometry module - problem with the line intersection

### ISSUE THREAD

**Issue by saeedghsh** [sympy/sympy#11272]
Hello,

Please consider the following case of intersecting two line entities (sym.Line):
```
>>> l1 = sym.Line(sym.Point(0,0),  slope=+1)
>>> l2 = sym.Line(sym.Point(0,0),  slope=-1)
>>> print sym.intersection(l1,l2)
[Point2D(0, 0)]
```
Which works all right.

But when I define a new class "LineModified" inheriting from "sym.Line" as its baseclass, it fails to perform the intersection procedure.
```
>>> class LineModified(sym.Line):
>>>     pass
>>>
>>> l1 = LineModified(sym.Point(0,0),  slope=+1)
>>> l2 = LineModified(sym.Point(0,0),  slope=-1)
>>> print sym.intersection(l1,l2)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../mySandbox.py", line 608, in <module>
    print sym.intersection(f[0],f[1])
  File "/usr/local/lib/python2.7/dist-packages/sympy-1.0-py2.7.egg/sympy/geometry/util.py", line 215, in intersection
    res = entities[0].intersection(entities[1])
  File "/usr/local/lib/python2.7/dist-packages/sympy-1.0-py2.7.egg/sympy/geometry/line.py", line 803, in intersection
    if prec.index(expr.func) > prec.index(o.func):
ValueError: tuple.index(x): x not in tuple
```
It seems the ```LinearEntity``` of the geometry module supports intersection of line entities of different types, namely (Line, Ray, Segment). To handle these different types, a precedence is defined ([see here](https://github.com/sympy/sympy/blob/master/sympy/geometry/line.py#L801)). And to set the precedence of input entities, their type is fetched relying on the ```__class__``` variable of each instance via the ```func``` method. The precedence procedure is something like this (from the previous link):
```
        prec = (Line, Ray, Segment)
        expr = self
        if prec.index(expr.func) > prec.index(o.func):
            expr, o = o, expr
```
Note that the ```expr.func``` method is inherited hierarchically as follow:
```
class LinearEntity(GeometrySet)
class GeometrySet(GeometryEntity, Set)
class GeometryEntity(Basic)
class Basic(with_metaclass(ManagedProperties))
    def func(self):
        return self.__class__
```
( see them here: [LinearEntity](https://github.com/sympy/sympy/blob/master/sympy/geometry/line.py#L37),  [GeometrySet](https://github.com/sympy/sympy/blob/master/sympy/geometry/entity.py#L461), [GeometryEntity](https://github.com/sympy/sympy/blob/master/sympy/geometry/entity.py#L55), [Basic](https://github.com/sympy/sympy/blob/master/sympy/core/basic.py#L15), [func](https://github.com/sympy/sympy/blob/master/sympy/core/basic.py#L613) )

I can go around this either by setting the ```__class__``` variable of the "modified" subclass, which I have been advised against (strongly!):
```
class LineModified(sym.Line):
    __class__ = sym.Line
```
Or the ```line.py``` could be adjusted as:
```
        try:
            if prec.index(expr.func) > prec.index(o.func):
                expr, o = o, expr
        except ValueError:
            pass
```

Any thought on that?

-------------------------------------------
PS: this problem is from the latest version of the library (sympy '1.0'), and it works fine in previous versions (e.g. '0.7.4.1')

**Comment by smichr** [comment]
I just started an experimental branch named `gsolve` where I introduced a function that should handle intersections of all geometric objects. This would eliminate the need for (much) special handling of objects. I can't track this down now, but I imagine that having a general intersection method for GeometryEntity is the way I would go and override that in any classes that need special handling. e.g. Segment isn't represented by f(x,y) -- it doesn't have an `equation` method -- so it would need an override.

Feel free to experiment with the branch if you want. BTW, the checking of the solutions is the slow step; the checking can be disabled, however, by setting `check=False`.

```
>>> from sympy.geometry.util import gsolve
>>> from time import time
>>> import random
>>> r=random.randint
>>> t1=0
>>> t2=0
>>> for i in range(2):
...   e1 = Ellipse((r(-10,10),r(-10,10)),r(1,10),r(1,10))
...   e2 = Ellipse((r(-10,10),r(-10,10)),r(1,10),r(1,10))
...   t=time()
...   ok = gsolve(e1, e2, check=False)
...   t1+=time()-t
...   t=time()
...   ok = gsolve(e1, e2, check=True)
...   t2+=time()-t
...
>>> t1,t2
(1.736999750137329, 163.07100009918213)
>>>
```

ping @szymag
