### ISSUE TITLE
coset_enumeration_c raises "AttributeError: 'CosetTable' object has no attribute 'lookahead'"

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#11352]
```
gaurav@stallman:~/Public/sympy$ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> from sympy.combinatorics.free_group import free_group
>>> from sympy.combinatorics.fp_groups import FpGroup, coset_enumeration_c, coset_enumeration_r
>>> F, a, b, c = free_group("a, b, c")
>>> f = FpGroup(F, [a**11, b**5, c**4, (a*c)**3, b**2*c**-1*b**-1*c, a**4*b**-1*a**-1*b])
>>> H = [c, b, c**2]
>>> C = coset_enumeration_c(f, H)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gaurav/Public/sympy/sympy/combinatorics/fp_groups.py", line 793, in coset_enumeration_c
    C.process_deductions(R_c_list[C.A_dict[x]], R_c_list[C.A_dict_inv[x]])
  File "/home/gaurav/Public/sympy/sympy/combinatorics/fp_groups.py", line 466, in process_deductions
    self.lookahead()
AttributeError: 'CosetTable' object has no attribute 'lookahead'
```

**Comment by jksuom** [comment]
But `look_ahead` does exist.

**Comment by kritkaran94** [comment]
@gxyd @jksuom I got the same error. Is it a bug ?

**Comment by gxyd** [comment]
This is to be a small fix. The [line 460](https://github.com/sympy/sympy/blob/master/sympy/combinatorics/fp_groups.py#L460) should be changed from `self.lookahead()` -> `self.look_ahead()`. Perhaps the test should also be added. Also remove [this comment](https://github.com/sympy/sympy/blob/master/sympy/combinatorics/fp_groups.py#L443) , since `look_ahead()` will then be tested.

**Comment by kritkaran94** [comment]
@gxyd I will do that right away.

**Comment by kritkaran94** [comment]
Do we need the test too ?
