### ISSUE TITLE
refine(aE.T * aE) gives "AttributeError: 'Symbol' object has no attribute 'T'" error.

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11359]
Reported from https://stackoverflow.com/questions/38240986/refinea-e-t-a-e-fails

```py
from sympy import *
from sympy.abc import a, l

E = MatrixSymbol('E', l, l)
aE = a * E

with assuming(Q.orthogonal(E)):
    print(refine(E.T * E))
    print(refine(aE.T * aE))
```

Gives

```pytb
/Users/wakita/anaconda3/envs/pyqtgl/bin/python "/Users/wakita/Dropbox (smartnova)/work/pysandbox/testsympy/aE.py"
Traceback (most recent call last):
  File "/Users/wakita/Dropbox (smartnova)/work/pysandbox/testsympy/aE.py", line 9, in <module>
    print(refine(aE.T * aE))
  File "/Users/wakita/anaconda3/envs/pyqtgl/lib/python3.5/site-packages/sympy/assumptions/refine.py", line 29, in refine
    args = [refine(arg, assumptions) for arg in expr.args]
  File "/Users/wakita/anaconda3/envs/pyqtgl/lib/python3.5/site-packages/sympy/assumptions/refine.py", line 29, in <listcomp>
    args = [refine(arg, assumptions) for arg in expr.args]
  File "/Users/wakita/anaconda3/envs/pyqtgl/lib/python3.5/site-packages/sympy/assumptions/refine.py", line 29, in refine
    args = [refine(arg, assumptions) for arg in expr.args]
  File "/Users/wakita/anaconda3/envs/pyqtgl/lib/python3.5/site-packages/sympy/assumptions/refine.py", line 29, in <listcomp>
    args = [refine(arg, assumptions) for arg in expr.args]
  File "/Users/wakita/anaconda3/envs/pyqtgl/lib/python3.5/site-packages/sympy/assumptions/refine.py", line 40, in refine
    new_expr = handler(expr, assumptions)
  File "/Users/wakita/anaconda3/envs/pyqtgl/lib/python3.5/site-packages/sympy/matrices/expressions/matmul.py", line 265, in refine_MatMul
    if arg == last.T and ask(Q.orthogonal(arg), assumptions):
AttributeError: 'Symbol' object has no attribute 'T'
```

The problem is that MatMul can have a scalar as the first argument, but `refine_MatMul` is assuming all the arguments are matrix expressions. This is probably easy to fix.

**Comment by parsoyaarihant** [comment]
I am working on this.
