### ISSUE TITLE
Problem with matrix element  and multiply when integratimg

### ISSUE THREAD

**Issue by kafrankel** [sympy/sympy#11376]
I am having a problem with integration in sympy with matrix elements.
I upgraded sympy frorm the anaconda installation and get the same problem in either anaconda2 
(Python 2.7.11)
or anaconda3 (Python 3.5.1), also on Sage
The following works

import sympy
from sympy import *
sympy.**version**
# output is '1.0'

x=Symbol('x')
y=Symbol('y')
M=IndexedBase('M')

integrate(cos(M[0] + x),x)
# output is
# sin(x + M[0])
# and this works

integrate(cos(y*x),x)
# output is
# Piecewise((x, Eq(y, 0)), (sin(x*y)/y, True))
# but this fails

integrate(cos(M[0] \* x),x)

I can do an explicit  workaround by just using symbols. ( I only use 2 matrix elements, otherwise the project overruns computer memory, so  I can just write my formula explicitly, but it's cleaner with matrix elements). I tried running with the python debugger to find the problem but it proved tedious to me.
Any thoughts? All I could find in the documentation is that sympy sometmes has problems!
Thanks in advance.
Ken Frankel
# The output is
#11375

integrate(cos(M \* x),x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/integrals/integrals.py", line 1280, in integrate
    risch=risch, manual=manual)
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/integrals/integrals.py", line 486, in doit
    conds=conds)
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/integrals/integrals.py", line 860, in _eval_integral
    h = trigintegrate(g, x, conds=conds)
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/integrals/trigonometry.py", line 100, in trigintegrate
    return Piecewise((zz, Eq(a, 0)), (fx / a, True))
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/functions/elementary/piecewise.py", line 110, in __new__
    r = cls.eval(_newargs)
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/functions/elementary/piecewise.py", line 146, in eval
    cond_eval = cls.__eval_cond(cond)
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/functions/elementary/piecewise.py", line 507, in __eval_cond
    if checksol(cond, {}, minimal=True):
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/solvers/solvers.py", line 227, in checksol
    if not val.is_constant(_list(sol.keys()), simplify=not minimal):
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/core/expr.py", line 535, in is_constant
    simultaneous=True)
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/core/basic.py", line 893, in subs
    rv = rv._subs(old, d_m, *_kwargs)
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/core/basic.py", line 1016, in _subs
    rv = fallback(self, old, new)
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/core/basic.py", line 988, in fallback
    arg = arg._subs(old, new, *_hints)
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/core/basic.py", line 1016, in _subs
    rv = fallback(self, old, new)
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/core/basic.py", line 993, in fallback
    rv = self.func(_args)
  File "/home/Users/frankel/anaconda2/lib/python2.7/site-packages/sympy/tensor/indexed.py", line 334, in __new__
    raise TypeError("Base label should be a string or Symbol.")
TypeError: Base label should be a string or Symbol.

**Comment by oscarbenjamin** [comment]
This works fine now:
```julia
In [69]: x=Symbol('x') 
    ...: y=Symbol('y') 
    ...: M=IndexedBase('M') 

In [72]: integrate(cos(M[0] * x),x) 
    ...:  
    ...:                                                                                                                                                      
Out[72]: 
⎧sin(x⋅M[0])              
⎪───────────  for M[0] ≠ 0
⎨    M[0]                 
⎪                         
⎩     x        otherwise  
```
