### ISSUE TITLE
ReferenceFrame error

### ISSUE THREAD

**Issue by jbm950** [sympy/sympy#11503]
There's a spot in frame.py where it tries to delete dictionary keys while iterating through the dictionary which causes an error. I'm posting a PR with the fix shortly.

``` python
from sympy.physics.mechanics import ReferenceFrame

A = ReferenceFrame("A")
B = A.orientnew("B", "Axis", [35, A.y])
C = ReferenceFrame("C")
A.orient(C, "Axis", [70, C.z])
```

results in

``````
Traceback (most recent call last):
  File "../other/testing2.py", line 6, in <module>
    A.orient(C, "Axis", [70, C.z])
  File "/Users/james/git_repos/sympy_work/sympy/sympy/physics/vector/frame.py", line 562, in orient
    for frame in frames:
RuntimeError: dictionary changed size during iteration```
``````

**Comment by oscarbenjamin** [comment]
This seems to be fixed. Looks like it just didn't get closed when #11504 was merged.
