### ISSUE TITLE
"Piecewise((1,Eq(data[0],0)), (-1,True))" fails where "data" is a matrix

### ISSUE THREAD

**Issue by micklat** [sympy/sympy#11521]
Just tried this in the Live Shell (Python console for SymPy 1.0 (Python 2.7.5)).

```
>>> data = MatrixSymbol('data', 1, 4)
>>> Piecewise((1,Eq(data[0],0)), (-1,True))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/functions/elementary/piecewise.py", line 110, in __new__
    r = cls.eval(*newargs)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/functions/elementary/piecewise.py", line 146, in eval
    cond_eval = cls.__eval_cond(cond)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/functions/elementary/piecewise.py", line 507, in __eval_cond
    if checksol(cond, {}, minimal=True):
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/solvers/solvers.py", line 227, in checksol
    if not val.is_constant(*list(sol.keys()), simplify=not minimal):
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/core/expr.py", line 568, in is_constant
    deriv = expr.diff(w)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/core/expr.py", line 2866, in diff
    return Derivative(self, *new_symbols, **assumptions)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/core/function.py", line 1055, in __new__
    if v._diff_wrt:
AttributeError: 'MatrixSymbol' object has no attribute '_diff_wrt'
```

**Comment by oscarbenjamin** [comment]
This seems to be fixed now on master:
```julia
In [65]: data = MatrixSymbol('data', 1, 4)

In [66]: Piecewise((1,Eq(data[0],0)), (-1,True))
Out[66]: 
⎧1   for data₀₀ = 0
⎨                  
⎩-1    otherwise
```
