### ISSUE TITLE
powsimp(-0.5**x + 2**(-x)) throws error

### ISSUE THREAD

**Issue by michaeldong21** [sympy/sympy#11544]
```
>>> powsimp(-0.5**x + 2**(-x))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/simplify/powsimp.py", line 118, in powsimp
    expr = expr.func(*[recurse(w) for w in expr.args])
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/simplify/powsimp.py", line 109, in recurse
    return powsimp(arg, _deep, _combine, _force, _measure)
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/simplify/powsimp.py", line 169, in powsimp
    m = multiplicity(abs(b), abs(coeff))
  File "/base/data/home/apps/s~sympy-live-hrd/46.393464279709602171/sympy/sympy/ntheory/factor_.py", line 231, in multiplicity
    raise ValueError('expecting ints or fractions, got %s and %s' % (p, n))
ValueError: expecting ints or fractions, got 0.500000000000000 and 1
```

**Comment by bjodah** [comment]
Try to avoid Python floats (IEEE754 float64 numbers):
```
In [1]: powsimp((-S(1)/2)**x + 2**-x)
Out[1]: 
    x    -x
-1/2  + 2  
```

**Comment by bjodah** [comment]
I guess you actually wanted simplify here:
```
In [11]: ((-S(1)/2)**x + 2**-x).simplify()
Out[11]: 
 -x ⎛    x    ⎞
2  ⋅⎝(-1)  + 1⎠
```
