### ISSUE TITLE
Support derivate like d(f(x))/d(2*x) (Chain Rule)

### ISSUE THREAD

**Issue by latot** [sympy/sympy#11573]
Hi all, well i think can be good idea implement this, basically is this:

```
>>> b=sympy.S("x")
>>> b.diff(2*b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/sympy/core/expr.py", line 2881, in diff
    return Derivative(self, *new_symbols, **assumptions)
  File "/usr/lib64/python2.7/site-packages/sympy/core/function.py", line 1112, in __new__
    Can\'t calculate %s%s derivative wrt %s.''' % (count, ordinal, v)))
ValueError: 
Can't calculate 1st derivative wrt 2*x.
```

i this case should be:

```
d(b)/d(2*x)=(d(b)/d(x))/(d(2*x)/d(x))
```

Thx. Cya.

**Comment by smichr** [comment]
The reasons for not supporting differentiation wrt expressions is given in the docstring of Derivative.
