### ISSUE TITLE
Solve: Normalize Input (f, *symbols...)

### ISSUE THREAD

**Issue by latot** [sympy/sympy#11653]
Hi, i think this should be normalized, if we have only eqs we can pass symbols as a list, but if it have a ineq we get an error:

```
>>> solve((y>1), [x])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/sympy/solvers/solvers.py", line 830, in solve
    return reduce_inequalities(f, symbols=symbols)
  File "/usr/lib64/python2.7/site-packages/sympy/solvers/inequalities.py", line 664, in reduce_inequalities
    symbols = (set(symbols) or gens) & gens
TypeError: unhashable type: 'list'

>>> solve([Eq(x+y, 1), Eq(x-y, 1)], [x, y])
{x: 1, y: 0}
```

Thx. Cya.

**Comment by oscarbenjamin** [comment]
This now gives
```julia
In [14]: solve((y>1), [x])
Out[14]: 1 < y ∧ y < ∞
```
I don't know whether I think that's reasonable or not.
