### ISSUE TITLE
Function unicode name bug in Py27

### ISSUE THREAD

**Issue by sn6uv** [sympy/sympy#11669]
SymPy 1.0 crashes on Python 2.7 if the function name is a unicode string. No crash on PyPy or Python3.4.

```
Python 2.7.12 (default, Jun 28 2016, 08:31:05) 
[GCC 6.1.1 20160602] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.0'
>>> sympy.Function(u'f')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/sympy/core/cache.py", line 95, in wrapper
    retval = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 366, in __new__
    return UndefinedFunction(*args, **options)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 738, in __new__
    ret = BasicMeta.__new__(mcl, name, (AppliedUndef,), kwargs)
TypeError: type() argument 1 must be string, not unicode
```

**Comment by oscarbenjamin** [comment]
This is still unfixed. Python 2 will be dropped soon though so maybe it doesn't need fixing.

**Comment by namannimmo10** [comment]
I think the issue is not relevant now.
