### ISSUE TITLE
pde_separate does not allow expressions as input

### ISSUE THREAD

**Issue by nicoguaro** [sympy/sympy#11726]
If I enter an equation to `separate_pde` it works

```
from __future__ import division
from sympy import symbols, pde_separate, Function
x, t = symbols('x t')
f  = symbols('f', cls=Function)
X, T = symbols('X T', cls=Function)

u = f(x, t)
eq = Eq(u.diff(x, 2) - u.diff(t, 2), 0)
sep = pde_separate(eq, u, [T(x), X(t)])
```

returning `[Derivative(T(x), x, x)/T(x), Derivative(X(t), t, t)/X(t)]`

But if I try to input an expression it fails

```
Traceback (most recent call last):

  File "<ipython-input-43-a24d40cd9b94>", line 1, in <module>
    runfile('C:/Users/nicoguaro/Desktop/pde.py', wdir='C:/Users/nicoguaro/Desktop')

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/nicoguaro/Desktop/pde.py", line 9, in <module>
    sep = pde_separate(eq, u, [T(x), X(t)])

  File "C:\Anaconda2\lib\site-packages\sympy\solvers\pde.py", line 856, in pde_separate
    if eq.rhs != 0:

AttributeError: 'Add' object has no attribute 'rhs'
```

Since `pdsolve` admit both inputs, I think that this is not consistent behavior.

**Comment by nicoguaro** [comment]
@oscarbenjamin, should this be closed? I tried it and it works now. Maybe also #11754.

**Comment by oscarbenjamin** [comment]
Yes, I guess it should have been closed before
