### ISSUE TITLE
series() calculation up to O(t**k) returns invalid coefficients for t**k * log(t)

### ISSUE THREAD

**Issue by symbolique** [sympy/sympy#11722]
Version: Sympy 1.0

## Description

The univariate expression `bad` defined below is `O(t**6 * log(t)**5)` around 0.

However, if we ask series() for an expansion up to order 5, spurious terms are returned instead of just `O(t**5)`:
```py
>>> series(bad, t, x0=0, n=5)
t**5*(-3*log(t)**3 - 22*log(t)**2 - 81*log(t)/2) + O(t**5)
```

They disappear when computing an expansion up to order 6:
```py
>>> series(bad, t, x0=0, n=6)
t**6*(-log(t)**5 - 215*log(t)**4/12 - 340*log(t)**3/3 - 1251*log(t)**2/4 - 13187*log(t)/36) + O(t**6)
```

Note that this time, all terms have the correct coefficients.

## Separating `t` and `log(t)` into a bivariate Taylor series

`bad` is constructed from the bivariate expression `good`, which has a Taylor series expansion in `g` and `t`, by replacing `g` with `log(1/t)`. All expansions of `good` with respect to `t` are correct:

```py
>>> series(good, t, x0=0, n=5)
O(t**5)
>>> series(good, t, x0=0, n=6)
O(t**6)
>>> series(good, t, x0=0, n=7)
t**6*(g**5 - 215*g**4/12 + 340*g**3/3 - 1251*g**2/4 + 13187*g/36 - 104179/720) + O(t**7)
```

## Exact definition

Unfortunately the exact expression is very lengthy because the bug didn't occur for lower orders:

```py
from sympy import *
t,g = var('t g')
good = sympify('-g**4*t**4/4 + 7*g**3*t**4/3 + g**3*t**3/3 - 27*g**2*t**4/4 - 2*g**2*t**3 - g**2*t**2/2 + 15*g*t**4/2 + 19*g*t**3/6 + 3*g*t**2/2 + g*t + g - 2009*t**4/720 - 13*t**3/9 - 5*t**2/6 - t/2 - (g + log(-t + 1) - 1 + (g + log(-t + 1))/(-1 + 1/t) - 1/(2*(-1 + 1/t)) - (g + log(-t + 1))**2/(2*(-1 + 1/t)**2) + 3*(g + log(-t + 1))/(2*(-1 + 1/t)**2) - 5/(6*(-1 + 1/t)**2) + (g + log(-t + 1))**3/(3*(-1 + 1/t)**3) - 2*(g + log(-t + 1))**2/(-1 + 1/t)**3 + 19*(g + log(-t + 1))/(6*(-1 + 1/t)**3) - 13/(9*(-1 + 1/t)**3) - (g + log(-t + 1))**4/(4*(-1 + 1/t)**4) + 7*(g + log(-t + 1))**3/(3*(-1 + 1/t)**4) - 27*(g + log(-t + 1))**2/(4*(-1 + 1/t)**4) + 15*(g + log(-t + 1))/(2*(-1 + 1/t)**4) - 2009/(720*(-1 + 1/t)**4) + 1/t)/(1 - 1/(g + log(-t + 1) - 1 + (g + log(-t + 1))/(-1 + 1/t) - 1/(2*(-1 + 1/t)) - (g + log(-t + 1))**2/(2*(-1 + 1/t)**2) + 3*(g + log(-t + 1))/(2*(-1 + 1/t)**2) - 5/(6*(-1 + 1/t)**2) + (g + log(-t + 1))**3/(3*(-1 + 1/t)**3) - 2*(g + log(-t + 1))**2/(-1 + 1/t)**3 + 19*(g + log(-t + 1))/(6*(-1 + 1/t)**3) - 13/(9*(-1 + 1/t)**3) - (g + log(-t + 1))**4/(4*(-1 + 1/t)**4) + 7*(g + log(-t + 1))**3/(3*(-1 + 1/t)**4) - 27*(g + log(-t + 1))**2/(4*(-1 + 1/t)**4) + 15*(g + log(-t + 1))/(2*(-1 + 1/t)**4) - 2009/(720*(-1 + 1/t)**4) + 1/t)) + 1/t')
bad = good.subs(g, log(1/t))
```

**Comment by anutosh491** [comment]
Currently the series for good as well as bad gives `NotImplementedError` with a very long list of traceback . I'll paste that here for reference . I haven't seen such a huge traceback of errors since long in the series module , would take some time to figure out where the actual error lies !
>>> bad.series(t, x0=0, n=5)
```
Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1953, in _eval_nseries
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1953, in _eval_nseries
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1717, in _eval_nseries
    _, d = g.leadterm(x)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3483, in leadterm
    l = self.as_leading_term(x, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3446, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 2016, in _eval_as_leading_term
    return self.func(*[t.as_leading_term(x, logx=logx, cdir=cdir) for t in self.args])
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 2016, in <listcomp>
    return self.func(*[t.as_leading_term(x, logx=logx, cdir=cdir) for t in self.args])
  File "c:\users\anuto\sympy\sympy\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3446, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 1067, in _eval_as_leading_term
    n0 = min.getn()
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 1287, in getn
    raise NotImplementedError('not sure of order of %s' % o)
NotImplementedError: not sure of order of log(_x)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1959, in _eval_nseries
    s = t.nseries(x, n=n1, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1731, in _eval_nseries
    gpoly = g._eval_nseries(x, n=ceiling(maxpow), logx=logx, cdir=cdir).removeO()
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in _eval_nseries
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in <listcomp>
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in _eval_nseries
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in <listcomp>
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in _eval_nseries
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in <listcomp>
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in _eval_nseries
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in <listcomp>
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1723, in _eval_nseries
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1953, in _eval_nseries
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1953, in _eval_nseries
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1717, in _eval_nseries
    _, d = g.leadterm(x)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3483, in leadterm
    l = self.as_leading_term(x, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3446, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 2016, in _eval_as_leading_term
    return self.func(*[t.as_leading_term(x, logx=logx, cdir=cdir) for t in self.args])
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 2016, in <listcomp>
    return self.func(*[t.as_leading_term(x, logx=logx, cdir=cdir) for t in self.args])
  File "c:\users\anuto\sympy\sympy\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3446, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 1067, in _eval_as_leading_term
    n0 = min.getn()
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 1287, in getn
    raise NotImplementedError('not sure of order of %s' % o)
NotImplementedError: not sure of order of log(_x)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1959, in _eval_nseries
    s = t.nseries(x, n=n1, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1731, in _eval_nseries
    gpoly = g._eval_nseries(x, n=ceiling(maxpow), logx=logx, cdir=cdir).removeO()
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in _eval_nseries
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in <listcomp>
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1731, in _eval_nseries
    gpoly = g._eval_nseries(x, n=ceiling(maxpow), logx=logx, cdir=cdir).removeO()
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in _eval_nseries
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in <listcomp>
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in _eval_nseries
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in <listcomp>
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in _eval_nseries
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in <listcomp>
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in _eval_nseries
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in <listcomp>
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1723, in _eval_nseries
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1953, in _eval_nseries
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1953, in _eval_nseries
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1717, in _eval_nseries
    _, d = g.leadterm(x)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3483, in leadterm
    l = self.as_leading_term(x, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3446, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 2016, in _eval_as_leading_term
    return self.func(*[t.as_leading_term(x, logx=logx, cdir=cdir) for t in self.args])
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 2016, in <listcomp>
    return self.func(*[t.as_leading_term(x, logx=logx, cdir=cdir) for t in self.args])
  File "c:\users\anuto\sympy\sympy\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3446, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 1067, in _eval_as_leading_term
    n0 = min.getn()
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 1287, in getn
    raise NotImplementedError('not sure of order of %s' % o)
NotImplementedError: not sure of order of log(_x)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1959, in _eval_nseries
    s = t.nseries(x, n=n1, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1731, in _eval_nseries
    gpoly = g._eval_nseries(x, n=ceiling(maxpow), logx=logx, cdir=cdir).removeO()
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in _eval_nseries
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in <listcomp>
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in _eval_nseries
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in <listcomp>
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in _eval_nseries
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in <listcomp>
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in _eval_nseries
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in <listcomp>
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1723, in _eval_nseries
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1953, in _eval_nseries
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1953, in _eval_nseries
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1717, in _eval_nseries
    _, d = g.leadterm(x)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3483, in leadterm
    l = self.as_leading_term(x, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3446, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 2016, in _eval_as_leading_term
    return self.func(*[t.as_leading_term(x, logx=logx, cdir=cdir) for t in self.args])
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 2016, in <listcomp>
    return self.func(*[t.as_leading_term(x, logx=logx, cdir=cdir) for t in self.args])
  File "c:\users\anuto\sympy\sympy\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3446, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 1067, in _eval_as_leading_term
    n0 = min.getn()
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 1287, in getn
    raise NotImplementedError('not sure of order of %s' % o)
NotImplementedError: not sure of order of log(_x)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 2990, in series
    rv = self.subs(x, xpos).series(xpos, x0, n, dir, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 2998, in series
    s1 = self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in _eval_nseries
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in <listcomp>
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in _eval_nseries
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in <listcomp>
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1731, in _eval_nseries
    gpoly = g._eval_nseries(x, n=ceiling(maxpow), logx=logx, cdir=cdir).removeO()
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in _eval_nseries
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in <listcomp>
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1731, in _eval_nseries
    gpoly = g._eval_nseries(x, n=ceiling(maxpow), logx=logx, cdir=cdir).removeO()
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in _eval_nseries
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in <listcomp>
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in _eval_nseries
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in <listcomp>
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in _eval_nseries
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\add.py", line 536, in <listcomp>
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in _eval_nseries
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\mul.py", line 1970, in <listcomp>
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
  File "c:\users\anuto\sympy\sympy\sympy\core\expr.py", line 3366, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "c:\users\anuto\sympy\sympy\sympy\core\power.py", line 1723, in _eval_nseries
    raise NotImplementedError()
NotImplementedError
```
