### ISSUE TITLE
plot option aspect_ratio has no effect with matplotlib backend

### ISSUE THREAD

**Issue by aananko** [sympy/sympy#11764]
``` python
from sympy import *
from sympy.plotting import plot_parametric
var('phi')
plot_parametric(cos(phi), sin(phi), (phi, 0, 2 * pi), aspect_ratio=(1,1))
```

gives an ellipse instead of circle.

**Comment by jondo** [comment]
This is still broken in Sympy 1.4.
A workaround is:
```python
from sympy import *
from sympy.plotting import plot_parametric
var('phi')
p=plot_parametric(cos(phi), sin(phi), (phi, 0, 2 * pi))
fig = p._backend.fig
ax = p._backend.ax
ax.set_aspect('equal')
fig.show() # or fig.savefig('plot.svg')
```

**Comment by czgdp1807** [comment]
Latest update on the issue,
```python
>>> from sympy import *
>>> from sympy.plotting import plot_parametric
>>> var('phi')
phi
>>> plot_parametric(cos(phi), sin(phi), (phi, 0, 2 * pi), aspect_ratio=(1,1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/czgdp1807/sympy_project/sympy/sympy/plotting/plot.py", line 1708, in plot_parametric
    plots.show()
  File "/home/czgdp1807/sympy_project/sympy/sympy/plotting/plot.py", line 191, in show
    self._backend.show()
  File "/home/czgdp1807/sympy_project/sympy/sympy/plotting/plot.py", line 1278, in show
    'The TextBackend supports only expressions over a 1D range')
ValueError: The TextBackend supports only expressions over a 1D range
>>> 
```
