### ISSUE TITLE
Bug: acot(-0.0) zero division error

### ISSUE THREAD

**Issue by UpmostScarab** [sympy/sympy#11809]
While this:
`>>> acot(-0)`
gives pi/2 as expected,
`>>>acot(-0.0)`
gives ZeroDivisionError.
I'm using Python 3.5.2 and SymPy 1.0
Here's a full log:
`>>> acot(-0.0)`
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sympy/core/evalf.py", line 1277, in evalf
    rf = evalf_table[x.func]
KeyError: acot

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/sympy/core/function.py", line 392, in __new__
    return result.evalf(mlib.libmpf.prec_to_dps(pr))
  File "/usr/local/lib/python3.5/site-packages/sympy/core/evalf.py", line 1385, in evalf
    result = evalf(self, prec + 4, options)
  File "/usr/local/lib/python3.5/site-packages/sympy/core/evalf.py", line 1284, in evalf
    re, im = x._eval_evalf(prec).as_real_imag()
  File "/usr/local/lib/python3.5/site-packages/sympy/core/function.py", line 503, in _eval_evalf
    v = func(*args)
  File "/usr/local/lib/python3.5/site-packages/mpmath/ctx_mp_python.py", line 1016, in f_wrapped
    retval = f(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/mpmath/functions/functions.py", line 109, in acot
    def acot(ctx, z): return ctx.atan(ctx.one / z)
  File "<string>", line 7, in __div__
  File "/usr/local/lib/python3.5/site-packages/mpmath/libmp/libmpf.py", line 934, in mpf_div
    raise ZeroDivisionError
ZeroDivisionError

**Comment by ArifAhmed1995** [comment]
This seems to be an bug in the `acot()` function for mpmath, not in the equivalent function of sympy
One could modify sympy's `acot()` to return 1.57079632679490 (that is : `(pi/2).evalf()`) but the change to existing code would look out of place.

You might consider posting an issue here : https://github.com/fredrik-johansson/mpmath/issues

**Comment by cascala** [comment]
I would agree with @ArifAhmed1995, but at the same time I would ask why "0" appears to be treated differently from "0.0". The former becomes a special number (Zero), the latter is an ordinary float.

Can the parser be changed to make them boh equal to the special number Zero?

**Comment by ArifAhmed1995** [comment]
@cascala That would need decision from Sympy's lead developers.
`0.0 == S(0)` yields `True` though.

**Comment by ArifAhmed1995** [comment]
@UpmostScarab Can you close this issue now ?

**Comment by UpmostScarab** [comment]
@ArifAhmed1995 does fixing it in mpmath fixes it in sympy?

**Comment by ArifAhmed1995** [comment]
Well,now that it's been fixed in mpmath one would need to use the latest development version of mpmath in order to avoid this issue.But either ways , this is not really a sympy issue.
