### ISSUE TITLE
Sympy can't do this integral?

### ISSUE THREAD

**Issue by trxrunner** [sympy/sympy#11813]
Sympy can't do this integral?

```
>>> integrate((x-t)**(-1/2)*t,(t,0,x))
Integral(t/sqrt(-t + x), (t, 0, x))

>>> integrate((x-t)**(-1/2)*t,(t,0,x))
  x              
  /              
 |               
 |      u        
 |  ---------- du
 |    ________   
 |  \/ -u + x    
 |               
/                
0
```

**Comment by latot** [comment]
what version are you using, i compile sympy this day and i get this result:
```
>>> integrate((x-t)**(-1/2)*t,(t,0,x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/sympy/integrals/integrals.py", line 1295, in integrate
    risch=risch, manual=manual)
  File "/usr/lib64/python3.4/site-packages/sympy/integrals/integrals.py", line 486, in doit
    conds=conds)
  File "/usr/lib64/python3.4/site-packages/sympy/integrals/integrals.py", line 908, in _eval_integral
    h = meijerint_indefinite(g, x)
  File "/usr/lib64/python3.4/site-packages/sympy/integrals/meijerint.py", line 1612, in meijerint_indefinite
    res = _meijerint_indefinite_1(f.subs(x, x + a), x)
  File "/usr/lib64/python3.4/site-packages/sympy/integrals/meijerint.py", line 1672, in _meijerint_indefinite_1
    r = hyperexpand(r.subs(t, a*x**b))
  File "/usr/lib64/python3.4/site-packages/sympy/simplify/hyperexpand.py", line 2455, in hyperexpand
    return f.replace(hyper, do_replace).replace(meijerg, do_meijer)
  File "/usr/lib64/python3.4/site-packages/sympy/core/basic.py", line 1402, in replace
    rv = bottom_up(self, rec_replace, atoms=True)
  File "/usr/lib64/python3.4/site-packages/sympy/simplify/simplify.py", line 998, in bottom_up
    rv = F(rv)
  File "/usr/lib64/python3.4/site-packages/sympy/core/basic.py", line 1387, in rec_replace
    new = _value(expr, result)
  File "/usr/lib64/python3.4/site-packages/sympy/core/basic.py", line 1330, in <lambda>
    _value = lambda expr, result: value(*expr.args)
  File "/usr/lib64/python3.4/site-packages/sympy/simplify/hyperexpand.py", line 2452, in do_meijer
    allow_hyper, rewrite=rewrite)
  File "/usr/lib64/python3.4/site-packages/sympy/simplify/hyperexpand.py", line 2348, in _meijergexpand
    t, 1/z0)
  File "/usr/lib64/python3.4/site-packages/sympy/simplify/hyperexpand.py", line 2276, in do_slater
    t, premult, bh, rewrite=None)
  File "/usr/lib64/python3.4/site-packages/sympy/simplify/hyperexpand.py", line 2036, in _hyperexpand
    ops += devise_plan(func, formula.func, z0)
  File "/usr/lib64/python3.4/site-packages/sympy/simplify/hyperexpand.py", line 1613, in devise_plan
    raise ValueError('Non-suitable parameters.')
ValueError: Non-suitable parameters.
```

**Comment by trxrunner** [comment]
Ok, whoops, try
```
integrate((x-t)**(-S(1)/2)*t,(t,0,x))
```
It should come out unevaluated

**Comment by solarjoe** [comment]
Same here, but what would be the correct result?

```
from sympy import integrate, Symbol, sqrt
t = Symbol('t')
x = Symbol('x')
print(integrate(t * sqrt(x-t),(t,0,x)))
```

`>>> Integral(t*sqrt(-t + x), (t, 0, x))`

And can't SymPy resolve the **(-1/2) to 1/sqrt() ?

**Comment by trxrunner** [comment]
According to Wolfram, the answer should be ```4/3*x**(3/2)```
or
```
   3/2
4*x   
------
  3   
```

**Comment by oscarbenjamin** [comment]
Now I get a large piecewise expression still containing unevaluated integrals. If I simplfy that then I get:
```julia
In [113]: simplify(integrate((x-t)**(-S(1)/2)*t,(t,0,x)))                                                                                                     
Out[113]: 
⎧⎧ 0                                           
⎪⎪ ⌠                                           
⎪⎪ ⎮        ____                               
⎪⎪ ⎮    t⋅╲╱ -x             │t│                
⎪⎪-⎮ ───────────── dt   for ─── < -1           
⎪⎪ ⎮       _______           x                 
⎪⎪ ⎮      ╱ t - x                              
⎪⎪ ⎮ x⋅  ╱  ─────                              
⎪⎪ ⎮   ╲╱     x                                
⎪⎪ ⌡                                           
⎪⎪ x                                           
⎪⎨                                    for x < 0
⎪⎪ 0                                           
⎪⎪ ⌠                                           
⎪⎪ ⎮         ____                              
⎪⎪ ⎮   ⅈ⋅t⋅╲╱ -x                               
⎪⎪-⎮ ────────────── dt   otherwise             
⎪⎪ ⎮       ________                            
⎪⎪ ⎮      ╱ -t + x                             
⎪⎪ ⎮ x⋅  ╱  ──────                             
⎨⎪ ⎮   ╲╱     x                                
⎪⎪ ⌡                                           
⎪⎩ x                                           
⎪                                              
⎪x                                             
⎪⌠                                             
⎪⎮ ⎧    -ⅈ⋅t             │t│                   
⎪⎮ ⎪──────────────   for ─── > 1               
⎪⎮ ⎪       _______        x                    
⎪⎮ ⎪      ╱ t - x                              
⎪⎮ ⎪√x⋅  ╱  ─────                              
⎪⎮ ⎪   ╲╱     x                                
⎪⎮ ⎨                             dt   otherwise
⎪⎮ ⎪       t                                   
⎪⎮ ⎪───────────────   otherwise                
⎪⎮ ⎪       ________                            
⎪⎮ ⎪      ╱ -t + x                             
⎪⎮ ⎪√x⋅  ╱  ──────                             
⎪⎮ ⎩   ╲╱     x                                
⎪⌡                                             
⎩0   
```
That doesn't look right since I have `t` outside of the integrals in the x<0 case. Calling doit on that gives another large expression.

**Comment by asmeurer** [comment]
This is solved in my risch-algebraic branch https://github.com/sympy/sympy/pull/30239

```
>>> var('a')
a
>>> pprint(integrate((a - x)**Rational(-1, 2)*x, (x, 0, a)))
   3/2
4⋅a
──────
  3
```

Compare to the current answer in master:

```
>>> pprint(integrate((a - x)**Rational(-1, 2)*x, (x, 0, a)))
⎧ 0                                                                                                                                                                       ↪
⎪ ⌠                                                                                                                                                                       ↪
⎪ ⎮ ⎧                   ________                                                   ________                                       ________                                ↪
⎪ ⎮ ⎪     2     5/2    ╱      x                                            7/2    ╱      x                                3/2    ╱      x                                 ↪
⎪ ⎮ ⎪  6⋅x ⋅(-a)   ⋅  ╱  -1 + ─               2   ____             6⋅x⋅(-a)   ⋅  ╱  -1 + ─                7/2     4⋅x⋅(-a)   ⋅  ╱  -1 + ─                    3/2          ↪
⎪ ⎮ ⎪               ╲╱        a              x ⋅╲╱ -a                          ╲╱        a     12⋅ⅈ⋅x⋅(-a)                    ╲╱        a              x⋅(-a)             ↪
⎪ ⎮ ⎪- ───────────────────────── + ───────────────────────────── + ──────────────────────── + ───────────────── - ──────────────────────── - ──────────────────────────── ↪
⎪ ⎮ ⎪                      2           ________                                       2                       2             2                    ________                 ↪
⎪ ⎮ ⎪      ⎛     2        ⎞           ╱      x  ⎛     2        ⎞      ⎛     2        ⎞        ⎛     2        ⎞         - 3⋅a  + 3⋅a⋅x           ╱      x  ⎛     2         ↪
⎪ ⎮ ⎪      ⎝- 3⋅a  + 3⋅a⋅x⎠          ╱  -1 + ─ ⋅⎝- 3⋅a  + 3⋅a⋅x⎠      ⎝- 3⋅a  + 3⋅a⋅x⎠        ⎝- 3⋅a  + 3⋅a⋅x⎠                                 ╱  -1 + ─ ⋅⎝- 3⋅a  + 3⋅a⋅x ↪
⎪ ⎮ ⎪                              ╲╱        a                                                                                               ╲╱        a                  ↪
⎪-⎮ ⎨                                                                                                                                                                     ↪
⎪ ⎮ ⎪                                                                                                                                                       _______       ↪
⎪ ⎮ ⎪                                                                                                                                              ____    ╱     x        ↪
⎪ ⎮ ⎪                                                                                                                                        2⋅ⅈ⋅╲╱ -a ⋅  ╱  1 - ─        ↪
⎪ ⎮ ⎪                                                                                                                         ⅈ⋅x                       ╲╱       a     2⋅ ↪
⎪ ⎮ ⎪                                                                                                               - ──────────────────── - ────────────────────── + ─── ↪
⎪ ⎮ ⎪                                                                                                                              _______             3                  ↪
⎪ ⎮ ⎪                                                                                                                     ____    ╱     x                                 ↪
⎪ ⎮ ⎪                                                                                                                 3⋅╲╱ -a ⋅  ╱  1 - ─                             3⋅  ↪
⎪ ⎮ ⎩                                                                                                                          ╲╱       a                               ╲ ↪
⎪ ⌡                                                                                                                                                                       ↪
⎪ a                                                                                                                                                                       ↪
⎨                                                                                                                                                                         ↪
⎪   a                                                                                                                                                                     ↪
⎪   ⌠                                                                                                                                                                     ↪
⎪   ⎮ ⎧                ________                                      ________                                       ________                ________                      ↪
⎪   ⎮ ⎪        9/2    ╱      x                             7/2      ╱      x                             5/2  2    ╱      x         5/2    ╱      x                       ↪
⎪   ⎮ ⎪  12⋅ⅈ⋅a   ⋅  ╱  -1 + ─             9/2        6⋅ⅈ⋅a   ⋅x⋅  ╱  -1 + ─            7/2         6⋅ⅈ⋅a   ⋅x ⋅  ╱  -1 + ─    2⋅ⅈ⋅a   ⋅  ╱  -1 + ─           5/2         ↪
⎪   ⎮ ⎪            ╲╱        a         12⋅a                      ╲╱        a        12⋅a   ⋅x                   ╲╱        a             ╲╱        a        4⋅a            ↪
⎪   ⎮ ⎪- ────────────────────── + ───────────────── + ─────────────────────── - ───────────────── + ──────────────────────── - ───────────────────── + ────────────── + ─ ↪
⎪   ⎮ ⎪                    2                      2                      2                      2                      2               2                    2             ↪
⎪   ⎮ ⎪    ⎛     2        ⎞       ⎛     2        ⎞       ⎛     2        ⎞       ⎛     2        ⎞       ⎛     2        ⎞           - 3⋅a  + 3⋅a⋅x       - 3⋅a  + 3⋅a⋅x     ↪
⎪   ⎮ ⎪    ⎝- 3⋅a  + 3⋅a⋅x⎠       ⎝- 3⋅a  + 3⋅a⋅x⎠       ⎝- 3⋅a  + 3⋅a⋅x⎠       ⎝- 3⋅a  + 3⋅a⋅x⎠       ⎝- 3⋅a  + 3⋅a⋅x⎠                                                   ↪
⎪   ⎮ ⎪                                                                                                                                                                 ╲ ↪
⎪   ⎮ ⎨                                                                                                                                                                   ↪
⎪   ⎮ ⎪                                                                                                                            _______                                ↪
⎪   ⎮ ⎪                                                                                                                           ╱     x                                 ↪
⎪   ⎮ ⎪                                                                                                                   2⋅√a⋅  ╱  1 - ─                                 ↪
⎪   ⎮ ⎪                                                                                                                        ╲╱       a        2⋅√a               x     ↪
⎪   ⎮ ⎪                                                                                                                 - ──────────────── + ───────────── + ──────────── ↪
⎪   ⎮ ⎪                                                                                                                          3                 _______            ___ ↪
⎪   ⎮ ⎪                                                                                                                                           ╱     x            ╱    ↪
⎪   ⎮ ⎪                                                                                                                                      3⋅  ╱  1 - ─    3⋅√a⋅  ╱  1  ↪
⎪   ⎮ ⎩                                                                                                                                        ╲╱       a         ╲╱      ↪
⎪   ⌡                                                                                                                                                                     ↪
⎩   0                                                                                                                                                                     ↪

↪
↪
↪                    ________                                     ________
↪            9/2    ╱      x                              5/2    ╱      x
↪     12⋅(-a)   ⋅  ╱  -1 + ─               9/2      2⋅(-a)   ⋅  ╱  -1 + ─             5/2                     5/2
↪                ╲╱        a      12⋅ⅈ⋅(-a)                   ╲╱        a     4⋅ⅈ⋅(-a)                  2⋅(-a)                   │x│
↪ ─ + ─────────────────────── + ───────────────── + ────────────────────── + ────────────── - ─────────────────────────────  for ─── < -1
↪                        2                      2            2                    2               ________                        a
↪ ⎞      ⎛     2        ⎞       ⎛     2        ⎞        - 3⋅a  + 3⋅a⋅x       - 3⋅a  + 3⋅a⋅x      ╱      x  ⎛     2        ⎞
↪ ⎠      ⎝- 3⋅a  + 3⋅a⋅x⎠       ⎝- 3⋅a  + 3⋅a⋅x⎠                                                ╱  -1 + ─ ⋅⎝- 3⋅a  + 3⋅a⋅x⎠
↪                                                                                             ╲╱        a
↪                                                                                                                                         dx  for a < 0
↪
↪
↪     ____
↪ ⅈ⋅╲╱ -a
↪ ──────────                                                                                                                  otherwise
↪    _______
↪   ╱     x
↪  ╱  1 - ─
↪ ╱       a
↪
↪
↪
↪
↪
↪                                               ________
↪                                     3/2      ╱      x
↪               5/2              4⋅ⅈ⋅a   ⋅x⋅  ╱  -1 + ─                 3/2                                 2
↪          2⋅ⅈ⋅a                            ╲╱        a              ⅈ⋅a   ⋅x                         ⅈ⋅√a⋅x                  │x│
↪ ──────────────────────────── - ─────────────────────── - ───────────────────────────── - ─────────────────────────────  for ─── > 1
↪    ________                             2                    ________                        ________                        a
↪   ╱      x  ⎛     2        ⎞       - 3⋅a  + 3⋅a⋅x           ╱      x  ⎛     2        ⎞      ╱      x  ⎛     2        ⎞
↪  ╱  -1 + ─ ⋅⎝- 3⋅a  + 3⋅a⋅x⎠                               ╱  -1 + ─ ⋅⎝- 3⋅a  + 3⋅a⋅x⎠     ╱  -1 + ─ ⋅⎝- 3⋅a  + 3⋅a⋅x⎠
↪ ╱        a                                               ╲╱        a                     ╲╱        a
↪                                                                                                                                     dx      otherwise
↪
↪
↪
↪
↪ ────                                                                                                                     otherwise
↪ ____
↪   x
↪ - ─
↪   a
↪
↪
```
