### ISSUE TITLE
Poly.set_modulus( some_polynomial ) not implemented

### ISSUE THREAD

**Issue by aureooms** [sympy/sympy#11826]
Is this implemented somewhere else?

```py
>>> from sympy import Poly
>>> from sympy.abc import x
>>> p = Poly(x)
>>> q = Poly(x**2)
>>> p.set_modulus(q)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/sympy/polys/polytools.py", line 450, in set_modulus
    modulus = options.Modulus.preprocess(modulus)
  File "/usr/lib/python3.5/site-packages/sympy/polys/polyoptions.py", line 576, in preprocess
    "'modulus' must a positive integer, got %s" % modulus)
sympy.polys.polyerrors.OptionError: 'modulus' must a positive integer, got Poly(x**2, x, domain='ZZ')
```

**Comment by jksuom** [comment]
set_modulus is intended for creating polynomials with the finite coefficient ring  `ZZ/<q>`. To get a quotient ring of a polynomial ring, see this:
```
>>> from sympy.polys.domains.quotientring import QuotientRing
>>> help(QuotientRing)
```
or [this](http://docs.sympy.org/latest/modules/polys/agca.html#base-rings).

**Comment by aureooms** [comment]
Ok thanks, I get it! Why the weird old_poly_ring method name?

**Comment by jksuom** [comment]
There are two implementations of polynomials. The 'new' one does not (yet) cover quotient rings.

**Comment by aureooms** [comment]
Ok. There seems to be an incompatibility :/ Should I use an old implementation of Poly?

```py
>>> R = QQ.old_poly_ring(x)/[2*x]
>>> R
QQ[x]/<2*x>
>>> Poly(5*x+1, x, R)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/sympy/polys/polytools.py", line 73, in __new__
    opt = options.build_options(gens, args)
  File "/usr/lib/python3.5/site-packages/sympy/polys/polyoptions.py", line 731, in build_options
    return Options(gens, args)
  File "/usr/lib/python3.5/site-packages/sympy/polys/polyoptions.py", line 154, in __init__
    preprocess_options(args)
  File "/usr/lib/python3.5/site-packages/sympy/polys/polyoptions.py", line 152, in preprocess_options
    self[option] = cls.preprocess(value)
  File "/usr/lib/python3.5/site-packages/sympy/polys/polyoptions.py", line 290, in preprocess
    elif has_dups(gens):
  File "/usr/lib/python3.5/site-packages/sympy/utilities/iterables.py", line 1521, in has_dups
    return any(True for s in seq if s in uniq or uniq.add(s))
  File "/usr/lib/python3.5/site-packages/sympy/utilities/iterables.py", line 1521, in <genexpr>
    return any(True for s in seq if s in uniq or uniq.add(s))
  File "/usr/lib/python3.5/site-packages/sympy/polys/domains/quotientring.py", line 134, in __hash__
    return hash((self.__class__.__name__, self.dtype, self.ring, self.base_ideal))
TypeError: unhashable type: 'ModuleImplementedIdeal'
```

**Comment by jksuom** [comment]
Unfortunately, the documentation on the subject is currently very meagre. There are examples in sympy/polys/domains/tests/test_quotientring.py. The method `.convert` can be used to create elements of a quotient ring from a polynomial expression.
```
R = QQ.old_poly_ring(x)/[x**10]  # a quotient ring
p = R.convert(x**2 + x)  # an element of R
```
([Here](http://docs.sympy.org/latest/modules/polys/agca.html#modules-ideals-and-their-elementary-properties) is a reference.)

**Comment by aureooms** [comment]
Ok! It works :)

**Comment by oscarbenjamin** [comment]
Is there an issue to solve here or should this be closed?

**Comment by smichr** [comment]
Perhaps this could be left open to highlight the need to improve documentation there.
