### ISSUE TITLE
Closely related integral raises exception.

### ISSUE THREAD

**Issue by b-v** [sympy/sympy#11845]
```
from sympy import integrate, Symbol, exp
y = Symbol('y')
x = Symbol('x')
integrate(exp(y)*exp(-x**3),(x,0,1))  # gives solution 
integrate(exp(-y)*exp(-x**3),(x,0,1))  # gives solution 
integrate(exp(y-x**3),(x,0,1))  # returns original integral
integrate(exp(-y-x**3),(x,0,1))   # returns error 
```
All integrals should give the same result, since exp(a+b)=exp(a)exp(b) (except for -y vs y). Sympy is able to solve the first two, but not the third and fourth expressions.

The error is 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sympy/polys/rings.py", line 369, in from_expr
    poly = self._rebuild_expr(expr, mapping)
  File "/usr/local/lib/python3.5/site-packages/sympy/polys/rings.py", line 363, in _rebuild_expr
    return _rebuild(sympify(expr))
  File "/usr/local/lib/python3.5/site-packages/sympy/polys/rings.py", line 355, in _rebuild
    return reduce(add, list(map(_rebuild, expr.args)))
  File "/usr/local/lib/python3.5/site-packages/sympy/polys/rings.py", line 357, in _rebuild
    return reduce(mul, list(map(_rebuild, expr.args)))
  File "/usr/local/lib/python3.5/site-packages/sympy/polys/rings.py", line 361, in _rebuild
    return domain.convert(expr)
  File "/usr/local/lib/python3.5/site-packages/sympy/polys/domains/domain.py", line 146, in convert
    raise CoercionFailed("can't convert %s of type %s to %s" % (element, type(element), self))
sympy.polys.polyerrors.CoercionFailed: can't convert exp(2*y) of type exp to ZZ(exp(y))[_A0,_A1,_A2,_A3,_A4,_A5,_A6,_A7,_A8,_A9]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/sympy/integrals/integrals.py", line 1280, in integrate
    risch=risch, manual=manual)
  File "/usr/local/lib/python3.5/site-packages/sympy/integrals/integrals.py", line 486, in doit
    conds=conds)
  File "/usr/local/lib/python3.5/site-packages/sympy/integrals/integrals.py", line 785, in _eval_integral
    return result + i.doit(risch=False)
  File "/usr/local/lib/python3.5/site-packages/sympy/integrals/integrals.py", line 486, in doit
    conds=conds)
  File "/usr/local/lib/python3.5/site-packages/sympy/integrals/integrals.py", line 887, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/usr/local/lib/python3.5/site-packages/sympy/integrals/heurisch.py", line 130, in heurisch_wrapper
    unnecessary_permutations)
  File "/usr/local/lib/python3.5/site-packages/sympy/integrals/heurisch.py", line 674, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/usr/local/lib/python3.5/site-packages/sympy/integrals/heurisch.py", line 662, in heurisch
    solution = _integrate()
  File "/usr/local/lib/python3.5/site-packages/sympy/integrals/heurisch.py", line 646, in _integrate
    numer = ring.from_expr(raw_numer)
  File "/usr/local/lib/python3.5/site-packages/sympy/polys/rings.py", line 371, in from_expr
    raise ValueError("expected an expression convertible to a polynomial in %s, got %s" % (self, expr))
ValueError: expected an expression convertible to a polynomial in Polynomial ring in _x0, _x1, _x2 over ZZ(exp(y))[_A0,_A1,_A2,_A3,_A4,_A5,_A6,_A7,_A8,_A9] with lex order, got _x1*exp(2*y) + (3*_x2**2*_x1*(2*_A1*_x0 + _A6 + _A7*_x2 + _A8*_x1) - (_A2*_x1 + 2*_A3*_x2 + _A4 + _A7*_x0 - 3*_x2**2*_x1*(_A2*_x2 + 2*_A5*_x1 + _A8*_x0 + _A9))*exp(y))*exp(y)
```

**Comment by jksuom** [comment]
This exception is caught in the current master (#10792).

**Comment by latot** [comment]
Hi, actually seems work, is the right result?
```
>>> integrate(exp(y)*exp(-x**3),(x,0,1))  # gives solution 
-exp(y)*gamma(1/3)*lowergamma(1/3, 0)/(9*gamma(4/3)) + exp(y)*gamma(1/3)*lowergamma(1/3, 1)/(9*gamma(4/3))
>>> integrate(exp(-y)*exp(-x**3),(x,0,1))  # gives solution 
-exp(-y)*gamma(1/3)*lowergamma(1/3, 0)/(9*gamma(4/3)) + exp(-y)*gamma(1/3)*lowergamma(1/3, 1)/(9*gamma(4/3))
>>> integrate(exp(y-x**3),(x,0,1))
exp(y)*Integral(exp(-x**3), (x, 0, 1))
>>> integrate(exp(-y-x**3),(x,0,1))
exp(-y)*Integral(exp(-x**3), (x, 0, 1))
```

**Comment by b-v** [comment]
Hi, thanks, it works indeed with the latest git version. Sorry, I should have tried that first.

A  small remaining issue is that the third (fourth) integral has the same solution as the first (second) one. Now it gives an intermediate result with an integral. This integral needs to be entered again to give the complete solution to the original integral. This is in contrast to `integrate(exp(-y-x**2),(x,0,1))`, which is integrated in only one step.

**Comment by jksuom** [comment]
I think this should be left open because of that remaining issue. It clear that SymPy can find the integral, but the code somehow misses it in case the exponentials have been combined.

**Comment by oscarbenjamin** [comment]
It seems it needs a second doit to actually evaluate the integral:
```julia
In [56]: I = Integral(exp(y-x**3),(x,0,1))                                                                                                                    

In [57]: I                                                                                                                                                    
Out[57]: 
1             
⌠             
⎮     3       
⎮  - x  + y   
⎮ ℯ         dx
⌡             
0             

In [58]: I.doit()                                                                                                                                             
Out[58]: 
   1        
   ⌠        
   ⎮    3   
 y ⎮  -x    
ℯ ⋅⎮ ℯ    dx
   ⌡        
   0        

In [59]: I.doit().doit()                                                                                                                                      
Out[59]: 
 y                 
ℯ ⋅Γ(1/3)⋅γ(1/3, 1)
───────────────────
      9⋅Γ(4/3)     
```
