### ISSUE TITLE
nsimplify on integral: repeating error

### ISSUE THREAD

**Issue by trxrunner** [sympy/sympy#11842]
When I run this on SymPy 1.0, it gives a repeated error:
```
>>> nsimplify(integrate(sin(x**2)))

Traceback (most recent call last):
File "<pyshell#80>", line 1, in <module>
    nsimplify(integrate(sin(x**2)))
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\simplify\simplify.py", line 1132, in nsimplify
    return sympify(as_int(expr))
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\compatibility.py", line 402, in as_int
    result = int(n)
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\expr.py", line 195, in __int__
    r = self.round(2)
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\expr.py", line 3151, in round
    return i.round(p) + S.ImaginaryUnit*r.round(p)
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\expr.py", line 3151, in round
    return i.round(p) + S.ImaginaryUnit*r.round(p)
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\expr.py", line 3151, in round
    return i.round(p) + S.ImaginaryUnit*r.round(p)
```

And errors keep happening hundreds of times:

```
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\expr.py", line 3151, in round
    return i.round(p) + S.ImaginaryUnit*r.round(p)
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\expr.py", line 3151, in round
    return i.round(p) + S.ImaginaryUnit*r.round(p)
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\expr.py", line 3151, in round
    return i.round(p) + S.ImaginaryUnit*r.round(p)
```

Then almost at the bottom, the error changes (probably not relevant):

```
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\expr.py", line 3151, in round
    return i.round(p) + S.ImaginaryUnit*r.round(p)
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\expr.py", line 3142, in round
    if x.is_number and not x.is_Atom:
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\expr.py", line 346, in is_number
    return all(obj.is_number for obj in self.args)
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\expr.py", line 346, in <genexpr>
    return all(obj.is_number for obj in self.args)
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\expr.py", line 346, in is_number
...
    return all(obj.is_number for obj in self.args)
File "C:\Program Files (x86)\Python 3.5\lib\site-packages\sympy-1.0-py3.5.egg\sympy\core\expr.py", line 346, in is_number
    return all(obj.is_number for obj in self.args)
RecursionError: maximum recursion depth exceeded
```

I'm assuming this is a bug? The same thing happens on SymPy Live.

**Comment by jksuom** [comment]
I cannot reproduce this error on 1.0.1.dev.
```
>>> nsimplify(integrate(sin(x**2)))
3*sqrt(2)*sqrt(pi)*fresnels(sqrt(2)*x/sqrt(pi))*gamma(3/4)/(8*gamma(7/4))
```

**Comment by trxrunner** [comment]
I guess it's fixed then in the development.
