### ISSUE TITLE
Master is failing on finite_diff doctest

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#11979]
See: https://travis-ci.org/sympy/sympy/jobs/186466413

```
_______________ sympy.calculus.finite_diff.differentiate_finite ________________

File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/sympy-1.0.1.dev0-py2.7.egg/sympy/calculus/finite_diff.py", line 440, in sympy.calculus.finite_diff.differentiate_finite

Failed example:

    from sympy import cos, sin, Function, differentiate_finite

Exception raised:

    Traceback (most recent call last):

      File "/opt/python/2.7.9/lib/python2.7/doctest.py", line 1315, in __run

        compileflags, 1) in test.globs

      File "<doctest sympy.calculus.finite_diff.differentiate_finite[0]>", line 1, in <module>

        from sympy import cos, sin, Function, differentiate_finite

    ImportError: cannot import name differentiate_finite

**********************************************************************

File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/sympy-1.0.1.dev0-py2.7.egg/sympy/calculus/finite_diff.py", line 443, in sympy.calculus.finite_diff.differentiate_finite

Failed example:

    differentiate_finite(f(x) + sin(x), x, 2)

Exception raised:

    Traceback (most recent call last):

      File "/opt/python/2.7.9/lib/python2.7/doctest.py", line 1315, in __run

        compileflags, 1) in test.globs

      File "<doctest sympy.calculus.finite_diff.differentiate_finite[3]>", line 1, in <module>

        differentiate_finite(f(x) + sin(x), x, 2)

    NameError: name 'differentiate_finite' is not defined

**********************************************************************

File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/sympy-1.0.1.dev0-py2.7.egg/sympy/calculus/finite_diff.py", line 445, in sympy.calculus.finite_diff.differentiate_finite

Failed example:

    differentiate_finite(f(x) + sin(x), x, 2, evaluate=False)

Exception raised:

    Traceback (most recent call last):

      File "/opt/python/2.7.9/lib/python2.7/doctest.py", line 1315, in __run

        compileflags, 1) in test.globs

      File "<doctest sympy.calculus.finite_diff.differentiate_finite[4]>", line 1, in <module>

        differentiate_finite(f(x) + sin(x), x, 2, evaluate=False)

    NameError: name 'differentiate_finite' is not defined

**********************************************************************

File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/sympy-1.0.1.dev0-py2.7.egg/sympy/calculus/finite_diff.py", line 447, in sympy.calculus.finite_diff.differentiate_finite

Failed example:

    differentiate_finite(f(x, y), x, y)

Exception raised:

    Traceback (most recent call last):

      File "/opt/python/2.7.9/lib/python2.7/doctest.py", line 1315, in __run

        compileflags, 1) in test.globs

      File "<doctest sympy.calculus.finite_diff.differentiate_finite[5]>", line 1, in <module>

        differentiate_finite(f(x, y), x, y)

    NameError: name 'differentiate_finite' is not defined

**********************************************************************

File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/sympy-1.0.1.dev0-py2.7.egg/sympy/calculus/finite_diff.py", line 450, in sympy.calculus.finite_diff.differentiate_finite

Failed example:

    differentiate_finite(f(x)*g(x), x, points=[x-h, x+h]).simplify()

Exception raised:

    Traceback (most recent call last):

      File "/opt/python/2.7.9/lib/python2.7/doctest.py", line 1315, in __run

        compileflags, 1) in test.globs

      File "<doctest sympy.calculus.finite_diff.differentiate_finite[7]>", line 1, in <module>

        differentiate_finite(f(x)*g(x), x, points=[x-h, x+h]).simplify()

    NameError: name 'differentiate_finite' is not defined

**********************************************************************

File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/sympy-1.0.1.dev0-py2.7.egg/sympy/calculus/finite_diff.py", line 452, in sympy.calculus.finite_diff.differentiate_finite

Failed example:

    differentiate_finite(f(x)*g(x), x, points=[x-h, x+h], evaluate=False)

Exception raised:

    Traceback (most recent call last):

      File "/opt/python/2.7.9/lib/python2.7/doctest.py", line 1315, in __run

        compileflags, 1) in test.globs

      File "<doctest sympy.calculus.finite_diff.differentiate_finite[8]>", line 1, in <module>

        differentiate_finite(f(x)*g(x), x, points=[x-h, x+h], evaluate=False)

    NameError: name 'differentiate_finite' is not defined

```

**Comment by madan96** [comment]
#11980

**Comment by madan96** [comment]
@moorepants I guess this can be closed now.
