### ISSUE TITLE
expand_mul() causes a crash for nilpotent terms

### ISSUE THREAD

**Issue by Pastafarianist** [sympy/sympy#11985]
```python
import sympy as sp

class Nilpotent(sp.Expr):
    def __pow__(self, power):
        assert power >= 0
        if power == 0:
            return 1
        elif power == 1:
            return self
        else:
            return 0

print(sp.expand_mul(Nilpotent() * (1 + Nilpotent())))
```

Result:

```
Traceback (most recent call last):
  File "/home/user/bugs/mul_flatten_crash.py", line 14, in <module>
    print(sp.expand_mul(Nilpotent() * (1 + Nilpotent())))
  File "/usr/lib/python3.5/site-packages/sympy/core/function.py", line 2057, in expand_mul
    power_base=False, basic=False, multinomial=False, log=False)
  File "/usr/lib/python3.5/site-packages/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/sympy/core/expr.py", line 2962, in expand
    expr, hit = Expr._expand_hint(expr, hint, deep=deep, **hints)
  File "/usr/lib/python3.5/site-packages/sympy/core/expr.py", line 2903, in _expand_hint
    newexpr = getattr(expr, hint)(**hints)
  File "/usr/lib/python3.5/site-packages/sympy/core/mul.py", line 818, in _eval_expand_mul
    terms = self.func._expandsums(sums)
  File "/usr/lib/python3.5/site-packages/sympy/core/mul.py", line 784, in _expandsums
    terms = [Mul(a, b) for a in left for b in right]
  File "/usr/lib/python3.5/site-packages/sympy/core/mul.py", line 784, in <listcomp>
    terms = [Mul(a, b) for a in left for b in right]
  File "/usr/lib/python3.5/site-packages/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/sympy/core/operations.py", line 41, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "/usr/lib/python3.5/site-packages/sympy/core/mul.py", line 352, in flatten
    if o12.is_commutative:
AttributeError: 'int' object has no attribute 'is_commutative'
```

Possible fix: replace [line 353 here](https://github.com/sympy/sympy/blob/9670ff89dd8bff7878c6d636ec4f493b87d092df/sympy/core/mul.py#L353) from

```python
if o12.is_commutative:
```

to

```python
if isinstance(o12, int) or o12.is_commutative:
```

**Comment by mamakancha** [comment]
@Pastafarianist How should I check if the code works after making the change?

**Comment by jksuom** [comment]
The objects created should be SymPy objects. `S.One` instead of 1 and `S.Zero` instead of 0.

**Comment by jksuom** [comment]
@Pastafarianist The error should go away if `class Nilpotent` is fixed to return only SymPy objects. Perhaps this issue can be closed?

**Comment by Pastafarianist** [comment]
@jksuom It does go away, thank you.
