### ISSUE TITLE
Cannot pickle sympy.polys.domains.mpelements.constant

### ISSUE THREAD

**Issue by mmckerns** [sympy/sympy#11999]
When I isolate all of the objects in `sympy` that are not serializable by `dill`, I see that there are only a very few.  In particular, there is one that fails: the `constant` object:
```
>>> import dill
>>> g,l = {},{}
>>> exec('from sympy import *',g,l)
>>> e = {i:dill.detect.errors(j) for i,j in l.items() if dill.detect.errors(j)}
>>> e
{'C': TypeError("'bool' object is not callable",), 'CC': PicklingError("Can't pickle <class 'sympy.polys.domains.mpelements.constant'>: it's not found as sympy.polys.domains.mpelements.constant",), 'RR': PicklingError("Can't pickle <class 'sympy.polys.domains.mpelements.constant'>: it's not found as sympy.polys.domains.mpelements.constant",)}
>>> import sympy
>>> sympy.polys.domains.mpelements      
<module 'sympy.polys.domains.mpelements' from '/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sympy/polys/domains/mpelements.py'>
>>> sympy.polys.domains.mpelements.constant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sympy.polys.domains.mpelements' has no attribute 'constant'
>>> sympy.CC
CC
>>> type(sympy.CC)
<class 'sympy.polys.domains.complexfield.ComplexField'>
>>> sympy.__version__
'1.0'
```
The above shows there is likely only one serialization error as the root cause… and to get some more info, we turn on `trace`.
```
>>> dill.detect.trace(True)
>>> dill.dumps(l['CC'])
T4: <class 'sympy.polys.domains.complexfield.ComplexField'>
# T4
D2: <dict object at 0x10912e888>
T4: <class 'sympy.polys.domains.mpelements.MPContext'>
# T4
D2: <dict object at 0x10912e548>
T4: <class 'sympy.polys.domains.mpelements.constant'>
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 268, in _getattribute
    obj = getattr(obj, subpath)
AttributeError: module 'sympy.polys.domains.mpelements' has no attribute 'constant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 907, in save_global
    obj2, parent = _getattribute(module, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 271, in _getattribute
    .format(name, obj))
AttributeError: Can't get attribute 'constant' on <module 'sympy.polys.domains.mpelements' from '/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sympy/polys/domains/mpelements.py'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python3.5/site-packages/dill-0.2.6.dev0-py3.5.egg/dill/dill.py", line 256, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/Users/mmckerns/lib/python3.5/site-packages/dill-0.2.6.dev0-py3.5.egg/dill/dill.py", line 249, in dump
    pik.dump(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 623, in save_reduce
    save(state)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python3.5/site-packages/dill-0.2.6.dev0-py3.5.egg/dill/dill.py", line 818, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 623, in save_reduce
    save(state)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python3.5/site-packages/dill-0.2.6.dev0-py3.5.egg/dill/dill.py", line 818, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mmckerns/lib/python3.5/site-packages/dill-0.2.6.dev0-py3.5.egg/dill/dill.py", line 1236, in save_type
    StockPickler.save_global(pickler, obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pickle.py", line 911, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle <class 'sympy.polys.domains.mpelements.constant'>: it's not found as sympy.polys.domains.mpelements.constant
>>> 
```
It seems that `dill` is trying to pickle an object that is dynamically created and thus the object fails to serialize. In this case, `sympy` is making a `sympy.polys.domains.complexfield.ComplexField` instance look like a `sympy.polys.domains.mpelements.constant.  Note that if I try this in python `3.4` or `2.7, I get a similar error.  Note, also, if I use the `cloudpickle` settings of `dill` (i.e. `dill.settings['recurse']=True`), the object still fails to serialize with the same error.

This issue was originally posted here: https://github.com/uqfoundation/dill/issues/186 by @Huyston.

What can be done to allow this object to be pickled?

**Comment by asmeurer** [comment]
Why is the class being generated dynamically? What happens if we just define those three classes normally in the module?

**Comment by zacmontague** [comment]
Is there any progress on this issue? I am attempting to parallelize using process pool but mpmath cannot be pickled.
