### ISSUE TITLE
FallingFactorial ufuncify autowrap error

### ISSUE THREAD

**Issue by wasd12345** [sympy/sympy#12172]
Trying to ufuncify the FallingFactorial function:
Sympy 1.0
Python 2.7

Seems there is a problem with the autowrap code?

```
from sympy.functions.combinatorial.factorials import FallingFactorial
from sympy.utilities.autowrap import ufuncify
from sympy.abc import A,B
FF = ufuncify((A,B), FallingFactorial(A,B))
```

Gives the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/home/person/venv/local/lib/python2.7/site-packages/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/data/home/person/venv/local/lib/python2.7/site-packages/sympy/core/compatibility.py", line 899, in wrapper
    result = user_function(*args, **kwds)
  File "/data/home/person/venv/local/lib/python2.7/site-packages/sympy/utilities/autowrap.py", line 888, in ufuncify
    return code_wrapper.wrap_code(routine, helpers=helps)
  File "/data/home/person/venv/local/lib/python2.7/site-packages/sympy/utilities/autowrap.py", line 145, in wrap_code
    mod = __import__(self.module_name)
ImportError: ./wrapper_module_0.so: undefined symbol: FallingFactorial
```

Or in another environment, with Sympy 0.7.4.1, gives the similar error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/sympy/utilities/autowrap.py", line 486, in ufuncify
    return autowrap(C.Equality(y[i], f(*args)), **kwargs)
  File "/usr/lib/python2.7/dist-packages/sympy/utilities/autowrap.py", line 404, in autowrap
    return code_wrapper.wrap_code(routine, helpers=helps)
  File "/usr/lib/python2.7/dist-packages/sympy/utilities/autowrap.py", line 141, in wrap_code
    mod = __import__(self.module_name)
ImportError: ./wrapper_module_0.so: undefined symbol: fallingfactorial_
```

**Comment by oscarbenjamin** [comment]
Still the same error on master on OSX now:
```
In [33]: from sympy.functions.combinatorial.factorials import FallingFactorial 
    ...: from sympy.utilities.autowrap import ufuncify 
    ...: from sympy.abc import A,B 
    ...: FF = ufuncify((A,B), FallingFactorial(A,B))                                                                                                          
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-33-cc45bb6d3e49> in <module>
      2 from sympy.utilities.autowrap import ufuncify
      3 from sympy.abc import A,B
----> 4 FF = ufuncify((A,B), FallingFactorial(A,B))

~/current/sympy/sympy/sympy/core/cache.py in wrapper(*args, **kwargs)
     92             def wrapper(*args, **kwargs):
     93                 try:
---> 94                     retval = cfunc(*args, **kwargs)
     95                 except TypeError:
     96                     retval = func(*args, **kwargs)

~/current/sympy/sympy/sympy/utilities/autowrap.py in ufuncify(args, expr, language, backend, tempdir, flags, verbose, helpers, **kwargs)
   1099         routines = [make_routine('autofunc{}'.format(idx), exprx, args) for
   1100                     idx, exprx in enumerate(expr)]
-> 1101         return code_wrapper.wrap_code(routines, helpers=helps)
   1102     else:
   1103         # Dummies are used for all added expressions to prevent name clashes

~/current/sympy/sympy/sympy/utilities/autowrap.py in wrap_code(self, routines, helpers)
    823             self._prepare_files(routines, funcname)
    824             self._process_files(routines)
--> 825             mod = __import__(self.module_name)
    826         finally:
    827             sys.path.remove(workdir)

ImportError: dlopen(/private/var/folders/7r/5s79v1k53sb1mzz7z_hh9tx0z0q4x7/T/tmpsw8uy0e3_sympy_compile/wrapper_module_0.cpython-37m-darwin.so, 2): Symbol not found: _FallingFactorial
  Referenced from: /private/var/folders/7r/5s79v1k53sb1mzz7z_hh9tx0z0q4x7/T/tmpsw8uy0e3_sympy_compile/wrapper_module_0.cpython-37m-darwin.so
  Expected in: flat namespace
 in /private/var/folders/7r/5s79v1k53sb1mzz7z_hh9tx0z0q4x7/T/tmpsw8uy0e3_sympy_compile/wrapper_module_0.cpython-37m-darwin.so
```

**Comment by asmeurer** [comment]
The problem is with the code generators, not ufuncify. Neither ccode nor fcode support `ff`. What is the best way to represent it in those languages? A rewrite as `gamma` first?
