### ISSUE TITLE
Mathematica Parser Error

### ISSUE THREAD

**Issue by parsoyaarihant** [sympy/sympy#12309]
Hi, I faced the following issue while parsing the following Mathematica code in SymPy:
``` python
>>> from sympy.parsing.mathematica import mathematica
>>> s = 'f[x_] := log[x]'
>>> mathematica(s)
Traceback (most recent call last):
  File "/Users/parsoyaarihant/anaconda/lib/python3.5/site-packages/sympy/core/sympify.py", line 322, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/Users/parsoyaarihant/anaconda/lib/python3.5/site-packages/sympy/parsing/sympy_parser.py", line 894, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/Users/parsoyaarihant/anaconda/lib/python3.5/site-packages/sympy/parsing/sympy_parser.py", line 807, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    Symbol ('f' )[Symbol ('x_' )]:=log (Symbol ('x' ))
                                 ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/parsoyaarihant/anaconda/lib/python3.5/site-packages/sympy/parsing/mathematica.py", line 8, in mathematica
    return sympify(parse(s))
  File "/Users/parsoyaarihant/anaconda/lib/python3.5/site-packages/sympy/core/sympify.py", line 324, in sympify
    raise SympifyError('could not parse %r' % a, exc)
sympy.core.sympify.SympifyError: Sympify of expression 'could not parse 'f[x_] :=log(x)'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)
```

I wanted to know if there are any plans to improve Mathematica parsing in SymPy for advanced syntax such as `:=`.

**Comment by Upabjojr** [comment]
```python
In [2]: from sympy.parsing.mathematica import parse_mathematica

In [4]: parse_mathematica('f[x_] := log[x]')
Out[4]: SetDelayed(f(Pattern(x, Blank())), log(x))
```
