### ISSUE TITLE
string formatting error in dmp_integrate_in

### ISSUE THREAD

**Issue by jwilk** [sympy/sympy#12325]
```pycon
>>> from sympy.polys import ring, QQ
>>> R, x, y = ring("x, y", QQ)
>>> R.dmp_integrate_in(x, 1, -1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sympy/polys/compatibility.py", line 457, in dmp_integrate_in
    return self.from_dense(dmp_integrate_in(self.to_dense(f), m, j, self.ngens-1, self.domain))
  File "/usr/lib/python3/dist-packages/sympy/polys/densetools.py", line 138, in dmp_integrate_in
    raise IndexError("0 <= j <= u expected, got %s" % (u, j))
TypeError: not all arguments converted during string formatting
```
Found using [pydiatra](https://github.com/jwilk/pydiatra).
Tested with sympy 1.0.

**Comment by mohit3011** [comment]
@jksuom ,If this issue is still open I would like to give it a try.
