### ISSUE TITLE
nonlinsolve gives AttributeError related to ConditionSet

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12346]
```
>>> nonlinsolve((x**2/25 + y**2/289 - 1, 25*y**2 + (1.001001*x - 4.004)**2 - 1), (x, y))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solveset.py", line 2144, in nonlinsolve
    polys_expr, symbols, exclude=denominators)
  File "sympy\solvers\solveset.py", line 1868, in substitution
    result += FiniteSet(tuple(temp))
  File "sympy\sets\sets.py", line 556, in __add__
    return self.union(other)
  File "sympy\sets\sets.py", line 90, in union
    return Union(self, other)
  File "sympy\sets\sets.py", line 1256, in __new__
    return Union.reduce(args)
  File "sympy\sets\sets.py", line 1279, in reduce
    finite_set = FiniteSet(*a)
  File "sympy\sets\sets.py", line 1869, in __new__
    args = list(ordered(frozenset(tuple(args)), Set._infimum_key))
  File "sympy\core\compatibility.py", line 625, in ordered
    for v in d[k]:
  File "sympy\core\compatibility.py", line 625, in ordered
    for v in d[k]:
  File "sympy\core\compatibility.py", line 606, in ordered
    d[f(a)].append(a)
  File "sympy\core\compatibility.py", line 459, in default_sort_key
    return item.sort_key(order=order)
  File "sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy\core\compatibility.py", line 807, in wrapper
    result = user_function(*args, **kwds)
  File "sympy\core\basic.py", line 278, in sort_key
    args = len(args), tuple([inner_key(arg) for arg in args])
  File "sympy\core\basic.py", line 273, in inner_key
    return arg.sort_key(order)
  File "sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy\core\compatibility.py", line 807, in wrapper
    result = user_function(*args, **kwds)
  File "sympy\core\expr.py", line 85, in sort_key
    [ default_sort_key(arg, order=order) for arg in args ])
  File "sympy\core\compatibility.py", line 459, in default_sort_key
    return item.sort_key(order=order)
  File "sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy\core\compatibility.py", line 807, in wrapper
    result = user_function(*args, **kwds)
  File "sympy\core\expr.py", line 78, in sort_key
    args = expr.as_ordered_terms(order=order)
  File "sympy\core\expr.py", line 927, in as_ordered_terms
    terms, gens = self.as_terms()
  File "sympy\core\expr.py", line 957, in as_terms
    coeff, _term = term.as_coeff_Mul()
AttributeError: 'ConditionSet' object has no attribute 'as_coeff_Mul'
```

The result it is trying to give is

```
{(-5.02783427882959, -1.79627356182793*I), (-5.02783427882959,
1.79627356182793*I), (5.00000069633403, -0.00897196854350799*I),
(5.00000069633403, 0.00897196854350799*I), (5*sqrt(-(-17 +
ConditionSet(y, Eq(25.0*y**2 - 2.35765176705882*sqrt(-(y - 17)*(y +
17)) - 0.0866784603807093*(y - 17)*(y + 17) + 15.032016, 0),
{-0.00897196854349534*I, 1.79627356182793*I}))*(17 + ConditionSet(y,
Eq(25.0*y**2 - 2.35765176705882*sqrt(-(y - 17)*(y + 17)) -
0.0866784603807093*(y - 17)*(y + 17) + 15.032016, 0),
{-0.00897196854349534*I, 1.79627356182793*I})))/17, ConditionSet(y,
Eq(25.0*y**2 - 2.35765176705882*sqrt(-(y - 17)*(y + 17)) -
0.0866784603807093*(y - 17)*(y + 17) + 15.032016, 0),
{-0.00897196854349534*I, 1.79627356182793*I})), (-5*sqrt(-(-17 +
ConditionSet(y, Eq(25.0*y**2 + 2.35765176705882*sqrt(-(y - 17)*(y +
17)) - 0.0866784603807093*(y - 17)*(y + 17) + 15.032016, 0),
{-1.79627356182793*I, 0.00897196854349534*I}))*(17 + ConditionSet(y,
Eq(25.0*y**2 + 2.35765176705882*sqrt(-(y - 17)*(y + 17)) -
0.0866784603807093*(y - 17)*(y + 17) + 15.032016, 0),
{-1.79627356182793*I, 0.00897196854349534*I})))/17, ConditionSet(y,
Eq(25.0*y**2 + 2.35765176705882*sqrt(-(y - 17)*(y + 17)) -
0.0866784603807093*(y - 17)*(y + 17) + 15.032016, 0),
{-1.79627356182793*I, 0.00897196854349534*I})), (-5*I*sqrt(-17 -
1.79627356182793*I)*sqrt(17 - 1.79627356182793*I)/17,
1.79627356182793*I), (5*I*sqrt(-17 - 0.00897196854349534*I)*sqrt(17 -
0.00897196854349534*I)/17, 0.00897196854349534*I), (-5*I*sqrt(-17 +
0.00897196854349534*I)*sqrt(17 + 0.00897196854349534*I)/17,
-0.00897196854349534*I), (5*I*sqrt(-17 + 1.79627356182793*I)*sqrt(17 +
1.79627356182793*I)/17, -1.79627356182793*I)}
```

I was able to see this by making the following modification:

```diff
diff --git a/sympy/core/expr.py b/sympy/core/expr.py
index 48e1cbb..ec449f6 100644
--- a/sympy/core/expr.py
+++ b/sympy/core/expr.py
@@ -954,7 +954,11 @@ def as_terms(self):
         gens, terms = set([]), []

         for term in Add.make_args(self):
-            coeff, _term = term.as_coeff_Mul()
+            try:
+                coeff, _term = term.as_coeff_Mul()
+            except AttributeError:
+                coeff = S.One
+                _term = term

             coeff = complex(coeff)
             cpart, ncpart = {}, []
```

**Comment by anca-mc** [comment]
I traced down the problem to the call of the groebner() method, which does not give a correct answer (ideal generators)
 for the above polynomial system, the third element of the basis appears to be a constant polynomial, 1.0:

>>> groebner([x**2/25 + y**2/289 - 1, 25*y**2 + (1.001001*x - 4.004)**2 - 1],x ,y ,domain=RR, order='lex')
GroebnerBasis([1.0*x - 3.10794308728373*y**2 - 5.00025087400312, 1.0*y**4 + 3.22667920514154*y**2 + 0.00025972899805903, 1.0], x, y, domain='RR', order='lex')

However, changing the (default) buchberger algorithm to the f5b algorithm gives the right answer:

>>> groebner([x**2/25 + y**2/289 - 1, 25*y**2 + (1.001001*x - 4.004)**2 - 1],x ,y ,domain=RR, order='lex', method='f5b')
GroebnerBasis([1.0*x - 3.10794308728373*y**2 - 5.00025087400312, 1.0*y**4 + 3.22667920514154*y**2 + 0.00025972899805903], x, y, domain='RR', order='lex')

Just to check that this solves the nonlinear system issue (not as a proposed solution to the issue) I changed in the polyconfig module
 the default from buchberger to f5b (line 23) and it works:

>>> nonlinsolve((x**2/25 + y**2/289 - 1, 25*y**2 + (1.001001*x - 4.004)**2 - 1), (x, y))
{(-5.02783427882959, -1.79627356182793*I), (-5.02783427882959, 1.79627356182793*I), (5.00000069633403, -0.00897196854350424*I), (5.00000069633403, 0.00897196854350424*I)}

I can look into the implementation of the Buchberger algorithm and try to fix the issue.

**Comment by anca-mc** [comment]
@smichr 
The problem stems in the approximations of the coefficients for the two equations. The equations are considered to have real coefficients and
 a degree of approximation occurs from the start.
The first equation is beforehand 'approximated' to  0.04*x**2 + 0.00346020761245675*y**2 - 1.0.
The coefficient of y**2, 0.0034602076124567475, is an approximation of 1/289:

>>> N(1/289,50)
0.0034602076124567475098880997563810524297878146171570

In consequence, when computing the Grobner basis (reductions included) some differences that should be zero (were computations exact) evaluate to non-zero:
For instance, the third (constant = 1) polynomial that appears 
in the Grobner basis computed above with the Buchberger algorithm is the reduction of the constant S-poly -4.33680868994202e-19,
 which should be zero if computations were exact.


A possible solution would be to implement for real coefficients an algorithm that handles approximations
 and has a 'zero criterion', such as the one 
described by Shirayanagi in the paper "An Algorithm to Compute Floating Point Groebner Bases", 
http://link.springer.com/chapter/10.1007%2F978-1-4612-0351-3_10

I could try to implement this algorithm.

**Comment by oscarbenjamin** [comment]
This now seems to work on master. I get:
```julia
In [22]: nonlinsolve((x**2/25 + y**2/289 - 1, 25*y**2 + (1.001001*x - 4.004)**2 - 1), (x, y))                                                                 
Out[22]: 
⎧                                                                                                                                                           
⎪                                                                                                                                                           
⎨(-5.02783427882959, -1.79627356182793⋅ⅈ), (-5.02783427882959, 1.79627356182793⋅ⅈ), (5.00000069633403, -0.00897196854350799⋅ⅈ), (5.00000069633403, 0.0089719
⎪                                                                                                                                                           
⎩                                                                                                                                                           

               ⎛     _______________________________________________________                      ⎞  ⎛    __________________________________________________
               ⎜-5⋅╲╱ -(-17 - 1.79627356182793⋅ⅈ)⋅(17 - 1.79627356182793⋅ⅈ)                       ⎟  ⎜5⋅╲╱ -(-17 - 0.00897196854349534⋅ⅈ)⋅(17 - 0.0089719685
6854350799⋅ⅈ), ⎜─────────────────────────────────────────────────────────────, -1.79627356182793⋅ⅈ⎟, ⎜──────────────────────────────────────────────────────
               ⎝                              17                                                  ⎠  ⎝                                17                    
                                                                                                                                                            

___________                        ⎞  ⎛    _____________________________________________________________                       ⎞  ⎛     ____________________
4349534⋅ⅈ)                         ⎟  ⎜5⋅╲╱ -(-17 + 0.00897196854349534⋅ⅈ)⋅(17 + 0.00897196854349534⋅ⅈ)                        ⎟  ⎜-5⋅╲╱ -(-17 + 1.796273561
───────────, -0.00897196854349534⋅ⅈ⎟, ⎜─────────────────────────────────────────────────────────────────, 0.00897196854349534⋅ⅈ⎟, ⎜─────────────────────────
                                   ⎠  ⎝                                17                                                      ⎠  ⎝                         
                                                                                                                                                            

___________________________________                     ⎞⎫
82793⋅ⅈ)⋅(17 + 1.79627356182793⋅ⅈ)                      ⎟⎪
────────────────────────────────────, 1.79627356182793⋅ⅈ⎟⎬
     17                                                 ⎠⎪
                                                         ⎭
```

I haven't

**Comment by smichr** [comment]
I checked the solution and get
```python
for i,j in ans:
  print([q.n(2) for q in eqs.subs(dict(zip((x,y),(i,j))))])
[-4.5e-17, 0]
[-4.5e-17, 0]
[-1.5e-16, -1.2e-15]
[-1.5e-16, -1.2e-15]
[1.5e-18, 1.2e-14]
[-9.2e-17, 5.3e-15]
[-9.2e-17, 5.3e-15]
[1.5e-18, 1.2e-14]
```
