### ISSUE TITLE
nonlinsolve (solve_biquadratic) gives no solution with radical

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12345]
solve_biquadratic is called in the process of using nonlinsolve but it does not give a solution (or error) when an equation contains a radical:

```
>>> nonlinsolve((x**2-y-sqrt(2), x**2+x*y-y**2), x,y)
EmptySet()
```

Replacing the radical with a rational approximation gives

```
>>> for i in nonlinsolve((x**2-y-1414/S(1000), x**2+x*y-y**2), x,y):
...     Point(i).n(2)
...
Point2D(-1.5, 0.95)
Point2D(2.2, 3.6)
Point2D(0.92, -0.57)
Point2D(-0.63, -1.0)
```

(and those roots were checked visually by graphing)

**Comment by maurogaravello** [comment]
I think the problem is in finding roots of polynomials. Indeed at line 89 of polysys.py the instruction
q_roots = list(roots(q).keys())
gives an empty list.
q in this case is the polynomial of degree 4: 
Poly(y**4 - 3*y**3 + (-3*sqrt(2) + 1)*y**2 + 2*sqrt(2)*y + 2, y, domain='QQ<sqrt(2)>')

**Comment by smichr** [comment]
Yes, and I tried raising an error there so the calling routine would fallback to something else and it didn't work either. I didn't look the other direction to see what has to be fixed in roots.

**Comment by szymag** [comment]
I run debugger during solving your equation and I found interesting things.
In your case, `roots` has problem with finding roots for this Poly: `Poly(y**4 - 3*y**3 + (-3*sqrt(2) + 1)*y**2 + 2*sqrt(2)*y + 2, y, domain='QQ<sqrt(2)>')`

I did some calculation for another polynomials and I found that, if poly has variables to the power greater than 3, the results may be wrong. For example: 
`Poly(y ** 12 - 3 * y ** 3 + (-3 * sqrt(2) + 1) * y ** 2 + 2 * sqrt(2) * y + 2, y, domain='QQ<sqrt(2)>') `
has roots: 
`{{y -> -1.1612 - 0.866924 I}, {y -> -1.1612 + 0.866924 I}, {y -> -0.528763}, {y -> 0.944865}, {y -> 1.9063}}` (calculated in Mathematica). Using `roots` I got `{}`.
What's more for poly without radical I also get wrong result. For example: 
`Poly(y ** 5 - 3 * y ** 3 + (-3 * 2 + 1) * y ** 2 + 2 * 2 * y + 2, y)` has roots: 
`{{y -> -1.2954 - 1.12862 I}, {y -> -1.2954 + 1.12862 I}, {y -> -0.367029}, {y -> 0.89482}, {y -> 2.06301}}`. Using `roots` I got `{}`.
Unfortunately, I couldn't find clear rule, because for that poly: `Poly(y ** 5 - 3 * y ** 3 + (-3 + 1) * y ** 2 + 2  * y + 2, y)` I got correct result: `{{y -> -1.}, {y -> -0.884646 - 0.589743 I}, {y -> -0.884646 + 0.589743 I}, {y -> 1.}, {y -> 1.76929}}`.

**Comment by smichr** [comment]
> Poly(y ** 5 - 3 * y ** 3 + (-3 * 2 + 1) * y ** 2 + 2 * 2 * y + 2, y)

Note that the docstring says, "Only roots expressible via radicals will be returned."

```
>>> p
Poly(y**5 - 3*y**3 - 5*y**2 + 4*y + 2, y, domain='ZZ')
>>> [i.n(2) for i in p.all_roots()]
[-0.37, 0.89, 2.1, -1.3 - 1.1*I, -1.3 + 1.1*I]  #<-- this matches your listed values
```

**Comment by jksuom** [comment]
It seems that `root` is currently treating algebraic coefficients such as `sqrt(2)` by default as elements of `EX` domain, which the specific cubic and quartic solvers cannot handle. If one sets the argument flag `extension=True`, then the polynomial will be constructed properly (line 877 of polyroots.py) but later `retract` in `polytools` will lose the domain. This could probably be fixed by adding the `extension` flag as argument to `preprocess_roots` and `retract`, and passing it over to `construct_domain`. It could also be possible to use the default `extension=True` in `roots`. (And maybe even in `construct_domain`.)

**Comment by maurogaravello** [comment]
I tried to add the following lines to the roots function.
        if len(result) == 0:
            for r in _try_heuristics(f):
                _update_dict(result, r, 1)

In this way, it seems to me that the roots of the polynomial are found correctly. All the tests are ok. I do not know if it is a good solution.
However, the result to the original problem 'nonlinsolve((x**2-y-sqrt(2), x**2+x*y-y**2), x,y)' is not an empy set, but it seems not correct.

**Comment by smichr** [comment]
Ohh...so perhaps that's it: solve_biquadratic relies on `roots` which only gives solutions 'expressible via radicals' so if the two quadratics don't have such a solution there will be no solution returned. Perhaps the only thing that needs to be done is to update the docstring to reflect this "feature." Better, there should be some sort of fallback to give a solution even if it takes longer.

**Comment by smichr** [comment]
@jksuom -- I just noticed that I didn't see your response. Thanks for identifying this. Are you trying any of these modifications or would you prefer that someone else do so?

**Comment by smichr** [comment]
Well, it's pretty straightforward to do as you have said. I got these results

```
>>> ans = nonlinsolve((x**2-y-sqrt(2), x**2+x*y-y**2), x,y)
>>> for i in ans:
...  print [i.n(2) for i in i]
...
[-1.5, 0.95]
[2.2, 3.6]
[-0.63, -1.0]
[0.92, -0.57]
```

with these modifications -- I"m not sure if I put the right defaults in but would have to think about that later.

```diff
diff --git a/sympy/polys/polyroots.py b/sympy/polys/polyroots.py
index 0108a7b..1001e20 100644
--- a/sympy/polys/polyroots.py
+++ b/sympy/polys/polyroots.py
@@ -717,7 +717,7 @@ def _integer_basis(poly):
             return div


-def preprocess_roots(poly):
+def preprocess_roots(poly, extension=None):
     """Try to get rid of symbolic coefficients from ``poly``. """
     coeff = S.One

@@ -727,7 +727,7 @@ def preprocess_roots(poly):
         return coeff, poly

     poly = poly.primitive()[1]
-    poly = poly.retract()
+    poly = poly.retract(extension=extension)

     # TODO: This is fragile. Figure out how to make this independent of constru
ct_domain().
     if poly.get_domain().is_Poly and all(c.is_term for c in poly.rep.coeffs()):
@@ -859,6 +859,7 @@ def roots(f, *gens, **flags):
     multiple = flags.pop('multiple', False)
     filter = flags.pop('filter', None)
     predicate = flags.pop('predicate', None)
+    extension = flags.pop('extension', True)

     if isinstance(f, list):
         if gens:
@@ -974,7 +975,7 @@ def _try_heuristics(f):
     else:
         zeros = {S(0): k}

-    coeff, f = preprocess_roots(f)
+    coeff, f = preprocess_roots(f, extension=extension)

     if auto and f.get_domain().has_Ring:
         f = f.to_field()
diff --git a/sympy/polys/polytools.py b/sympy/polys/polytools.py
index 77772f6..84b2b7f 100644
--- a/sympy/polys/polytools.py
+++ b/sympy/polys/polytools.py
@@ -694,7 +694,7 @@ def to_exact(f):

         return f.per(result)

-    def retract(f, field=None):
+    def retract(f, field=None, extension=None):
         """
         Recalculate the ground domain of a polynomial.

@@ -715,7 +715,7 @@ def retract(f, field=None):

         """
         dom, rep = construct_domain(f.as_dict(zero=True),
-            field=field, composite=f.domain.is_Composite or None)
+            field=field, composite=f.domain.is_Composite or None, extension=ext
ension)
         return f.from_dict(rep, f.gens, domain=dom)

     def slice(f, x, m, n=None):
```

With those mods, @szymag 's example works like this:

```
>>> eq1
y**4 - 3*y**3 + y**2*(-3*sqrt(2) + 1) + 2*sqrt(2)*y + 2
>>> roots(Poly(eq1,y),extension=None)
{}
>>> roots(Poly(eq1,y))
{-sqrt(7/8 + 3*sqrt(2)/2 + sqrt(5)*(15/8 + 5*sqrt(2)/2)/5) + sqrt(5)/4 + 3/4: 1,
 sqrt(5)/4 + 3/4 + sqrt(7/8 + 3*sqrt(2)/2 + sqrt(5)*(15/8 + 5*sqrt(2)/2)/5): 1,
-sqrt(5)/4 + 3/4 + sqrt(-sqrt(5)*(15/8 + 5*sqrt(2)/2)/5 + 7/8 + 3*sqrt(2)/2): 1,
 -sqrt(-sqrt(5)*(15/8 + 5*sqrt(2)/2)/5 + 7/8 + 3*sqrt(2)/2) - sqrt(5)/4 + 3/4: 1
}
```

To preserve backward compatibility, the default to `roots` should probably be `None`. Any thoughts?

**Comment by jksuom** [comment]
> would you prefer that someone else do so?

That was my intention. It should not be hard to do though some unit tests may have to be revised. I think that taking all measures against being forced to use the EX domain is highly important in polyroots (and also elsewhere in polys).

**Comment by szymag** [comment]
> To preserve backward compatibility, the default to roots should probably be None. Any thoughts?

I run all test in `polys` with your mods. Unfortunately, some test didn't pass. In every case I had the same output:
```python
  File "./polys/polyroots.py", line 978, in roots
    coeff, f = preprocess_roots(f, extension=extension)
  File "./polys/polyroots.py", line 730, in preprocess_roots
    poly = poly.retract(extension=extension)
  File "./polys/polytools.py", line 718, in retract
    field=field, composite=f.domain.is_Composite or None, extension=extension)
  File "/home/szymag/python/sympy/sympy/polys/constructor.py", line 222, in construct_domain
    opt = build_options(args)
  File "/home/szymag/python/sympy/sympy/polys/polyoptions.py", line 731, in build_options
    return Options(gens, args)
raise OptionError("'%s' option is not allowed together with '%s'" % (option, exclude_option))
sympy.polys.polyerrors.OptionError: 'composite' option is not allowed together with 'extension'
```
When I set False in extension flag
```python
extension = flags.pop('extension', False)
```
I preserve backwad compatibility. I'm still not sure if this error, `OptionError,` should be raised or we should change something more.

**Comment by smichr** [comment]
> taking all measures against being forced to use the EX domain is highly important in polyroots

Do you mean that you think the user should not have to worry about setting `extension=True` (thus, just make `roots` "do the right thing") or do you mean that `extension` should not be set True unless it really needs to be?

**Comment by jksuom** [comment]
It seems that the role of the composite flag in
`field=field, composite=f.domain.is_Composite or None, extension=extension)`
should be examined more closely. Under which circumstances is it necessary?

I think that it should be possible allow both composite and extension in construct_domain, at least if we want to give symbolic solutions to equations (of degree <= 4) having symbolic coefficients.

The easiest fix right now might be adding some logic to retract that would suppress extend when composite is True (or possibly the other way round).

**Comment by jksuom** [comment]
> the user should not have to worry about setting extension=True

I mean that extension could probably be always True in `roots` (unless maybe when the coefficients are Floats). It should not usually be harmful even if it is not really needed.

**Comment by smichr** [comment]
@szymag , I was reluctant to use False for extension because of this. Do you know the implications of False and None, @jksuom?

```
>>> roots(x**3-3*x-5,extension=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\polys\polyroots.py", line 978, in roots
    coeff, f = preprocess_roots(f, extension=extension)
  File "sympy\polys\polyroots.py", line 730, in preprocess_roots
    poly = poly.retract(extension=extension)
  File "sympy\polys\polytools.py", line 718, in retract
    field=field, composite=f.domain.is_Composite or None, extension=extension)
  File "sympy\polys\constructor.py", line 222, in construct_domain
    opt = build_options(args)
  File "sympy\polys\polyoptions.py", line 731, in build_options
    return Options(gens, args)
  File "sympy\polys\polyoptions.py", line 154, in __init__
    preprocess_options(args)
  File "sympy\polys\polyoptions.py", line 152, in preprocess_options
    self[option] = cls.preprocess(value)
  File "sympy\polys\polyoptions.py", line 541, in preprocess
    raise OptionError("'False' is an invalid argument for 'extension'")
sympy.polys.polyerrors.OptionError: 'False' is an invalid argument for 'extension'
```

**Comment by jksuom** [comment]
I didn't know about that. It looks like one more example of the very conservative restrictions on polynomial options.

**Comment by jksuom** [comment]
I think that `construct_domain` should be built in such a way that users would not have to be too much concerned about the flags. It should have sufficient logic to decide which would be the correct result.

**Comment by szymag** [comment]
> Do you know the implications of False and None, @jksuom?

 Sorry @smichr, I mean `None`. If we set `None` every test will pass.

**Comment by smichr** [comment]
OK, I will shortly open a PR. One additional thing that might be addressed (but I am open to some comment) is this:

```
>>> v = roots(Poly((x-I)*(x-3-2*I),x)). keys(); v
[3/2 - sqrt(8 - 12*I + 9*(1 + I)**2)/2 + 3*I/2,
3/2 + sqrt(8 - 12*I + 9*(1 + I)**2)/2 + 3*I/2]

Those roots should be really simple. Let's try simplify them:

```
>>> [simplify(i) for i in v]
[3/2 - sqrt(8 + 6*I)/2 + 3*I/2, 3/2 + sqrt(8 + 6*I)/2 + 3*I/2]
```

Try get the real and imaginary parts

```
>>> [i.as_real_imag() for i in _]
[(-sqrt(10)*cos(atan(3/4)/2)/2 + 3/2, -sqrt(10)*sin(atan(3/4)/2)/2 + 3/2), 
(3/2 + sqrt(10)*cos(atan(3/4)/2)/2, sqrt(10)*sin(atan(3/4)/2)/2 + 3/2)]
```

OK, use minpoly

```
>>> [minpoly(i) for i in v]
[_x**2 + 1, _x**2 - 6*_x + 13]
>>> [roots(i) for i in _]
[{I: 1, -I: 1}, {3 + 2*I: 1, 3 - 2*I: 1}]
```

Hmmm....it was difficult to obtain the simple imaginary solution. If someone is filtering for an imaginary result, should an attempt be made to return what is known to be imaginary to be simpler? Or, perhaps as in the "casus irreducibilis" case such simplification should be left to the user.

**Comment by smichr** [comment]
@jksuom , do you know how to fix this so `test_evalf_issue_939` passes?

**Comment by smichr** [comment]
OK, here's what I've found. In one place it was necessary to watch for a CoercionError and retry roots with `extension=False` to get it to work. In a couple of places, the roots that are coming back are too complicated for sets to work with properly. In one case I added simplification in the code (`Gt(...).simplify()`) and in another I simplified a result coming back in a test. This feels very hackish. 

Perhaps the `extension=True` could only be used when the domain is not composite and when the number of roots doesn't match the order and the user didn't say `extension=False`.

**Comment by jksuom** [comment]
I see that the EX domain is again involved. I don't know yet how to fix that, but I'll try to look into it. In any case, `construct_domain` should not offer EX when there is nothing worse in the coefficients than symbolic parameters (`composite`) and radicals (`extension`). It should be possible to make them live together.

**Comment by jksuom** [comment]
So, I think that `construct_domain` is the main target here. Right now we can only try to work around the problems by attempting various combinations of the keywords, but that also feels very hackish.

**Comment by skirpichev** [comment]
> construct_domain should not offer EX when there is nothing worse in the coefficients than symbolic parameters (composite) and radicals (extension).

EX here is for reasons.  It seems, working with algebraic number domains is slow (see #5428).  In my experiments in diofant/diofant#478, where 'extension' was enabled by default - there are several huge slowdowns.  And roots() output also appears much more complex.

**Comment by smichr** [comment]
> And roots() output also appears much more complex.

Yes. I haven't had a chance to track that down. So it seems like a smarter auto-selection of when to use it and when to not is needed.

**Comment by jksuom** [comment]
I have often seen that working with the EX domain is much slower than with other polys domains. I can imagine that having to deal with many algebraic numbers in different extensions may be slow when those extensions have to be combined. If the computations can be arranged so that a sufficiently large extension is constructed in the beginning, then algebraic numbers should not be slow.

**Comment by skirpichev** [comment]
On Mon, Mar 27, 2017 at 08:45:06AM -0700, Christopher Smith wrote:
>    So it seems like a smarter auto-selection of when to use it and when to not is needed.

I doubt there is.  Bad things happens even for simple coefficients
(and low poly degrees), e.g.:

(7 + 5*sqrt(2))*x**3 + (-6 - 4*sqrt(2))*x**2 + (-sqrt(2) - 1)*x + 2

There are very simple algebraic number field,  QQ<sqrt(2)>.

**Comment by oscargus** [comment]
Current master gives:
![image](https://user-images.githubusercontent.com/8114497/130335308-a36261d8-cc83-4fcd-8510-14eb9638ea1f.png)
