### ISSUE TITLE
polytool.poly() can't raise polynomial to negative power?

### ISSUE THREAD

**Issue by mehrdadn** [sympy/sympy#12400]
The code
```
import sympy
print(sympy.polys.polytools.poly(1 / (1 + sympy.sqrt(2)), sympy.Dummy('x')))
```
should not result in the following, right?
```
Traceback (most recent call last):
  File "Temp.py", line 2, in <module>
    print(sympy.polys.polytools.poly(1 / (1 + sympy.sqrt(2)), sympy.Dummy('x')))
  File "sympy\polys\polytools.py", line 6855, in poly
    return _poly(expr, opt)
  File "sympy\polys\polytools.py", line 6805, in _poly
    _poly(factor.base, opt).pow(factor.exp))
  File "sympy\polys\polytools.py", line 1404, in pow
    result = f.rep.pow(n)
  File "sympy\polys\polyclasses.py", line 446, in pow
    return f.per(dmp_pow(f.rep, n, f.lev, f.dom))
  File "sympy\polys\densearith.py", line 978, in dmp_pow
    return dup_pow(f, n, K)
  File "sympy\polys\densearith.py", line 943, in dup_pow
    raise ValueError("can't raise polynomial to a negative power")
ValueError: can't raise polynomial to a negative power
```

**Comment by jksuom** [comment]
This looks like a bug. Negative exponents should not be used in the construction of polynomials [here](https://github.com/sympy/sympy/blob/master/sympy/polys/polytools.py#L6862).
