### ISSUE TITLE
Incompatibility with Cx_Freeze/Py2Exe/PyInstaller.

### ISSUE THREAD

**Issue by DarkSuniuM** [sympy/sympy#12509]
Hello
Here is my script:
`import colorama                 # Used for fix cprint in Windows CMD
from sympy import *             # Used for calculate user input
import sys                      # Used for exit command
from termcolor import cprint    # Used for change color of output
colorama.init()
cprint("Inline Python Calculator!", 'cyan')
while True: # Infinity loop
    _input = input('Enter Your Equation: ')
    if _input == 'exit()' or _input == 'EXIT()' or _input == 'Exit()':
        sys.exit()
    else:
        _process = sympify(_input)
        print(_input, "=", _process)
    cprint("Type exit() to quit!", 'red')
    cprint("-" * 25, 'red')
`
I was trying to make an executable version of my script by Cx-Freeze and this errors showed up.
`PS C:\Users\Alireza\PycharmProjects\AdvancedCalculator> python Setup.py build
running build
running build_exe
Traceback (most recent call last):
  File "Setup.py", line 6, in <module>
    executables=[Executable("MyCalculator.py")])
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:\Program Files (x86)\Python36-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files (x86)\Python36-32\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Program Files (x86)\Python36-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Program Files (x86)\Python36-32\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Program Files (x86)\Python36-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files (x86)\Python36-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\dist.py", line 219, in run
    freezer.Freeze()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\freezer.py", line 623, in Freeze
    self._FreezeExecutable(executable)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\freezer.py", line 199, in _FreezeExecutable
    finder.IncludeFile(exe.script, exe.moduleName)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 633, in IncludeFile
    deferredImports)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 474, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 564, in _ScanCode
    module, relativeImportIndex)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 310, in _ImportModule
    deferredImports, namespace = namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 403, in _InternalImportModule
    parentModule, namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 416, in _LoadModule
    namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 485, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 474, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 564, in _ScanCode
    module, relativeImportIndex)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 310, in _ImportModule
    deferredImports, namespace = namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 403, in _InternalImportModule
    parentModule, namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 416, in _LoadModule
    namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 485, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 474, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 564, in _ScanCode
    module, relativeImportIndex)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 345, in _ImportModule
    deferredImports, namespace = namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 403, in _InternalImportModule
    parentModule, namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 474, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 564, in _ScanCode
    module, relativeImportIndex)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 345, in _ImportModule
    deferredImports, namespace = namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 403, in _InternalImportModule
    parentModule, namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 474, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 564, in _ScanCode
    module, relativeImportIndex)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 345, in _ImportModule
    deferredImports, namespace = namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 384, in _InternalImportModule
    namespace = namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 403, in _InternalImportModule
    parentModule, namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 416, in _LoadModule
    namespace)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 485, in _LoadPackage
    self._LoadModule(name, fp, path, info, deferredImports, parent)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 474, in _LoadModule
    self._ScanCode(module.code, module, deferredImports)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cx_Freeze\finder.py", line 561, in _ScanCode
    fromList, = arguments
ValueError: not enough values to unpack (expected 1, got 0)`

First I thought something wrong with Cx-Freeze but then I made "from sympy import *" comment and errors gone.
I even tried to make an executable file with Py2Exe and PyInstaller but they returned errors too..
Sorry for my bad English

**Comment by hocbaicungcon** [comment]
Me too. I can't build exe file.

**Comment by asmeurer** [comment]
I know folks have had issues with this in the past. I don't know if anyone has found a way to work around them. 

This looks like a bug in cx_Freeze. However, if a change to SymPy to make it work we should do it.

**Comment by oscarbenjamin** [comment]
@ghost is this still an issue?

**Comment by mohammadJavad12** [comment]
yes

**Comment by oscarbenjamin** [comment]
Can someone give a complete explanation of how to reproduce the problem here?
