### ISSUE TITLE
more robust detection of inequality args needed for Imageset (and other?)

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12523]
```
>>> imageset(n,
... -I*(I*(2*pi*n + atan(im(sqrt(-1 + I)*sqrt(S.Half - I/2))/re(sqrt(-1 +
... I)*sqrt(S.Half - I/2)))) + log(sqrt(im(sqrt(-1 + I)*sqrt(
... S.Half - I/2))**2 + re(sqrt(-1 + I)*sqrt(S.Half - I/2))**2))),
... S.Integers).intersect(Interval(0, pi))
(-atan(im(sqrt(-1 + I)*sqrt(1/2 - I/2))/re(sqrt(-1 + I)*sqrt(1/2 - I/2))) + I*lo
g(sqrt(im(sqrt(-1 + I)*sqrt(1/2 - I/2))**2 + re(sqrt(-1 + I)*sqrt(1/2 - I/2))**2
)))/(2*pi) (-atan(im(sqrt(-1 + I)*sqrt(1/2 - I/2))/re(sqrt(-1 + I)*sqrt(1/2 - I/
2))) - I*(-log(sqrt(im(sqrt(-1 + I)*sqrt(1/2 - I/2))**2 + re(sqrt(-1 + I)*sqrt(1
/2 - I/2))**2)) + I*pi))/(2*pi)
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "sympy\sets\sets.py", line 108, in intersect
    return Intersection(self, other)
  File "sympy\sets\sets.py", line 1480, in __new__

  File "sympy\sets\sets.py", line 1635, in reduce
    return Union(Intersection(arg, other) for arg in s.args)
  File "sympy\sets\fancysets.py", line 476, in _intersect
    new_inf, new_sup = new_sup, new_inf
  File "sympy\core\relational.py", line 195, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational
```

The offending line is `if new_inf > new_sup:` where it has been assumed that since the args are real they are going to pass the inequality test -- but they don't. So either proper handling of `Gt` instead of `>` should be done or better tests of the args leading to that point.

**Comment by oscarbenjamin** [comment]
On current master I get this:
```julia
In [12]: imageset(n, 
    ...: ... -I*(I*(2*pi*n + atan(im(sqrt(-1 + I)*sqrt(S.Half - I/2))/re(sqrt(-1 + 
    ...: ... I)*sqrt(S.Half - I/2)))) + log(sqrt(im(sqrt(-1 + I)*sqrt( 
    ...: ... S.Half - I/2))**2 + re(sqrt(-1 + I)*sqrt(S.Half - I/2))**2))), 
    ...: ... S.Integers).intersect(Interval(0, pi))                                                                                                           
Out[12]: 
⎧   ⎛                                                                              ⎛  ⎛               _______⎞⎞⎞⎫
⎪   ⎜   ⎛     ___________________________________________________________⎞         ⎜  ⎜  ________    ╱ 1   ⅈ ⎟⎟⎟⎪
⎪   ⎜   ⎜    ╱    ⎛               _______⎞      ⎛               _______⎞ ⎟         ⎜im⎜╲╱ -1 + ⅈ ⋅  ╱  ─ - ─ ⎟⎟⎟⎪
⎪   ⎜   ⎜   ╱    2⎜  ________    ╱ 1   ⅈ ⎟     2⎜  ________    ╱ 1   ⅈ ⎟ ⎟         ⎜  ⎝           ╲╱   2   2 ⎠⎟⎟⎪
⎨-ⅈ⋅⎜log⎜  ╱   im ⎜╲╱ -1 + ⅈ ⋅  ╱  ─ - ─ ⎟ + re ⎜╲╱ -1 + ⅈ ⋅  ╱  ─ - ─ ⎟ ⎟ + ⅈ⋅atan⎜──────────────────────────⎟⎟⎬
⎪   ⎜   ⎝╲╱       ⎝           ╲╱   2   2 ⎠      ⎝           ╲╱   2   2 ⎠ ⎠         ⎜  ⎛               _______⎞⎟⎟⎪
⎪   ⎜                                                                              ⎜  ⎜  ________    ╱ 1   ⅈ ⎟⎟⎟⎪
⎪   ⎜                                                                              ⎜re⎜╲╱ -1 + ⅈ ⋅  ╱  ─ - ─ ⎟⎟⎟⎪
⎩   ⎝                                                                              ⎝  ⎝           ╲╱   2   2 ⎠⎠⎠⎭
```

Does that look correct to you @smichr?

**Comment by smichr** [comment]
a non-error looks good to me
