### ISSUE TITLE
Cannot substitute upper limit of Sum created with Idx

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#12532]
Reported at https://stackoverflow.com/questions/43355448/substituting-symbols-in-summation-expression-in-sympy

```py
>>> i = Idx('i', (1, n))
>>> d = IndexedBase('d')
>>> s = Sum(d[i], i)
>>> s.subs(n, 5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/core/basic.py", line 915, in subs
    rv = rv._subs(old, new, **kwargs)
  File "./sympy/core/basic.py", line 1027, in _subs
    rv = self._eval_subs(old, new)
  File "./sympy/concrete/expr_with_limits.py", line 341, in _eval_subs
    return self.func(func, *limits)
  File "./sympy/concrete/summations.py", line 155, in __new__
    obj = AddWithLimits.__new__(cls, function, *symbols, **assumptions)
  File "./sympy/concrete/expr_with_limits.py", line 368, in __new__
    limits, orientation = _process_limits(*symbols)
  File "./sympy/concrete/expr_with_limits.py", line 59, in _process_limits
    if V[0].upper is not None and not bool(nlim[1] <= V[0].upper):
  File "./sympy/core/relational.py", line 195, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational
```

It works if you do the limits normally:

```
>>> i = Idx('i')
>>> s = Sum(d[i], (i, 1, n))
>>> s.subs(n, 5)
Sum(d[i], (i, 1, 5))
>>> s.subs(n, 5).doit()
d[1] + d[2] + d[3] + d[4] + d[5]
```

**Comment by Upabjojr** [comment]
This is related to a more complex issue: Should `d[i].free_symbols` output `(d, i)` or `d[i]`?

It currently defaults to `(d, i)`. Maybe it should output `(d, i, d[i])`?

If it were to output `(d[i],)` derivatives would fail.

**Comment by asmeurer** [comment]
Are there existing instances where free_symbols are not atomic?
