### ISSUE TITLE
Fourier Series of sqrt(x**2) and integrate(cos(k*x)*sqrt(x**2), x) are wrong

### ISSUE THREAD

**Issue by nicoguaro** [sympy/sympy#12557]
Computing the coefficients for the Fourier Series for ``sqrt(x**2)``

    from __future__ import division
    import sympy as sym
    x,y,z,t = sym.symbols('x y z t')
    k = sym.symbols("k", integer=True)
    fourier = sym.fourier_series(sym.cos(k*x)*sym.sqrt(x**2),
                                 (x, -sym.pi, sym.pi))

returns

    FourierSeries(sqrt(x**2), (x, -pi, pi), (pi/2, SeqFormula(Piecewise((pi**2, Eq(_n, 0)), (2*pi*sin(_n*pi)/_n + 2*cos(_n*pi)/_n**2, True))*cos(_n*x)/pi, (_n, 1, oo)), SeqFormula(0, (_k, 1, oo))))

That is not right. It is missing a -1.

If we directly compute the integral

    integrate(cos(k*x)*sqrt(x**2), (x, -pi, pi))

we see that is also wrong

    Piecewise((pi**2, Eq(k, 0)), (2*(-1)**k/k**2, True))

It should be

    Piecewise((pi**2, Eq(k, 0)), (2*((-1)**k - 1)/k**2, True))

**Comment by nicoguaro** [comment]
This is probably a consequence of #2868. Maybe #8430 is also related

If I compute the antiderivative of the piecewise version of the abs function

    import sympy as sym
    x = sym.symbols("x", real=True)
    abs2 = lambda x: sym.Piecewise((-x, x<=0), (x, x>0))
    inte = sym.integrate(abs2(x), x)

it returns 

    Piecewise((-x**2/2, x <= 0), (x**2/2, x > 0))

But if I try with the definite integral

    import sympy as sym
    x = sym.symbols("x", real=True)
    abs2 = lambda x: sym.Piecewise((-x, x<=0), (x, x>0))
    inte = sym.integrate(abs2(x), (x, -sym.pi, sym.pi))

it returns

    Traceback (most recent call last):
      File "C:\Users\nicoguaro\Desktop\abs_inte.py", line 4, in <module>
        inte = sym.integrate(abs2(x), (x, -sym.pi, sym.pi))
      File "C:\Anaconda2\lib\site-packages\sympy\integrals\integrals.py", line 1280, in integrate
        risch=risch, manual=manual)
      File "C:\Anaconda2\lib\site-packages\sympy\integrals\integrals.py", line 553, in doit
        evalued = Add(*others)._eval_interval(x, a, b)
      File "C:\Anaconda2\lib\site-packages\sympy\functions\elementary\piecewise.py", line 272, in _eval_interval
        int_expr = self._sort_expr_cond(sym, a, b)
      File "C:\Anaconda2\lib\site-packages\sympy\functions\elementary\piecewise.py", line 433, in _sort_expr_cond
        ", ".join([str((h[0], h[1])) for h in holes]))
    ValueError: Called interval evaluation over piecewise function on undefined intervals (-pi, 0), (0, pi)
