### ISSUE TITLE
_nsort can handle results of length 1

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12560]
```
>>> var('m x', real=True)
(m,x)
>>> solve_univariate_inequality(m<pi/x,x,S.Reals)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/solvers/inequalities.py", line 448, in solve_univariate_inequality
    raise NotImplementedError('sorting of these roots is not supported')
NotImplementedError: sorting of these roots is not supported
```

If there is only 1 real and/or 1 imaginary root, `_nsort` should return those roots as they don't need sorting.

**Comment by parsoyaarihant** [comment]
I am receiving different error:

```python 
>>> from sympy import *
>>> var('m x', real=True)
(m, x)
>>> solve_univariate_inequality(m<pi/x,x,S.Reals)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/parsoyaarihant/sympy/sympy/solvers/inequalities.py", line 487, in solve_univariate_inequality
    solved using solve_univariate_inequality.'''))
NotImplementedError:
The inequality cannot be                     solved using
solve_univariate_inequality.
```

**Comment by smichr** [comment]
Yes. It raises that error because `_nsort` raises an error. After looking at the docstring for `_nsort` I see that it is only intended to deal with numbers so the better place (perhaps) to deal with this is in the `solve_univariate_inequality` itself. I think that's what I am trying -- with success! -- in my `lts-wip` branch.
