### ISSUE TITLE
SeqFormulas addition is broken

### ISSUE THREAD

**Issue by Pastafarianist** [sympy/sympy#12630]
Sympy 1.0-2 from Manjaro repository.

```python
import sympy as sp
x, y = sp.symbols('x, y', commutative=False)
i, k = sp.symbols('i, k', integer=True)
terms = [sp.SeqFormula(y**2*(x*y)**i, (i, 0, k)), sp.SeqFormula(y*(x*y)**i*y, (i, 0, k))]
expr = terms[0] + terms[1]
print(expr)
```

Output:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(expr)
  File "/usr/lib/python3.6/site-packages/sympy/core/basic.py", line 396, in __str__
    return sstr(self, order=None)
  File "/usr/lib/python3.6/site-packages/sympy/printing/str.py", line 748, in sstr
    s = p.doprint(expr)
  File "/usr/lib/python3.6/site-packages/sympy/printing/printer.py", line 233, in doprint
    return self._str(self._print(expr))
  File "/usr/lib/python3.6/site-packages/sympy/printing/printer.py", line 257, in _print
    return getattr(self, printmethod)(expr, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sympy/printing/str.py", line 51, in _print_Add
    terms = self._as_ordered_terms(expr, order=order)
  File "/usr/lib/python3.6/site-packages/sympy/printing/printer.py", line 271, in _as_ordered_terms
    return expr.as_ordered_terms(order=order)
  File "/usr/lib/python3.6/site-packages/sympy/core/expr.py", line 888, in as_ordered_terms
    terms, gens = self.as_terms()
  File "/usr/lib/python3.6/site-packages/sympy/core/expr.py", line 918, in as_terms
    coeff, _term = term.as_coeff_Mul()
AttributeError: 'SeqFormula' object has no attribute 'as_coeff_Mul'
```

**Comment by oscarbenjamin** [comment]
I get the same on current master. Even `sepr` has the same problem.

I've distilled it a bit:
```python
from sympy import *
i = Symbol('i')
SeqFormula(0, (i, 0, 1)).as_coeff_mul()
```
This gives:
```
Traceback (most recent call last):
  File "t.py", line 3, in <module>
    SeqFormula(0, (i, 0, 1)).as_coeff_mul()
AttributeError: 'SeqFormula' object has no attribute 'as_coeff_mul'
```

**Comment by asmeurer** [comment]
If SeqFormula is something that is supposed to make sense in an Add, it should be subclassing from Expr, not Basic. 

But is it? The docstring describes it as a sequence, which I wouldn't expect to be an expression. 

Note if you want to add the terms of a sequence, you should use `Sum`, not `SeqFormula`. They have the same argument format, so `Sum(*s.args)` (if `s` is a `SeqFormula`) would convert one into the other.

**Comment by oscarbenjamin** [comment]
Oh okay that makes sense.

Maybe `Add` should check that its args are `Expr`. There are other cases where we can get garbage in, garbage out that could be checked for like this:
```julia
In [17]: M = BlockMatrix([[1, 0], [0, 1]])                                                                                                                    

In [18]: M.inv()                                                                                                                                              
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
...
AttributeError: 'One' object has no attribute 'shape'
```
The args do get sympified so maybe sympify could have an argument to check the types e.g.:
```python
args = [sympify(a, type=Expr) for a in args]
```
The idea is this would raise if sympify isn't going to return the expected type.

**Comment by asmeurer** [comment]
We could try that. We have to be careful when making changes to the core. It could break something we weren't expecting. It could also affect performance (you always have to check). 

Also, things start to get messy if with post processors like https://github.com/sympy/sympy/pull/15948 (although in that case, MatrixExpr is a subclass of Expr).
