### ISSUE TITLE
TypeError solving an integral

### ISSUE THREAD

**Issue by TorinCooperBennun** [sympy/sympy#12645]
**EDIT:** The issue spontaneously stopped occurring after I edited manualintegrate.py (just added a no-op print statement, and removed it later). Presumably, the issue occurred because the Spyder IDE somehow caused some state to persist. However, the integral is still thrown back at me unsolved.

----------------------------------------------------

Run the following code to reproduce:
```
from sympy import *
x, y = symbols("x, y", real=True)
print(integrate(sin(x*x + y*y), (x, -sqrt(pi - y*y), sqrt(pi - y*y)), (y, -sqrt(pi), sqrt(pi))))
```

The error is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "/home/tcb/.config/spyder-py3/temp.py", line 11, in <module>
    print(integrate(sin(x*x + y*y), (x, -sqrt(pi - y*y), sqrt(pi - y*y)), (y, -sqrt(pi), sqrt(pi))))
  File "/usr/lib/python3/dist-packages/sympy/integrals/integrals.py", line 1280, in integrate
    risch=risch, manual=manual)
  File "/usr/lib/python3/dist-packages/sympy/integrals/integrals.py", line 486, in doit
    conds=conds)
  File "/usr/lib/python3/dist-packages/sympy/integrals/integrals.py", line 912, in _eval_integral
    result = manualintegrate(g, x)
  File "/usr/lib/python3/dist-packages/sympy/integrals/manualintegrate.py", line 1145, in manualintegrate
    return _manualintegrate(integral_steps(f, var))
  File "/usr/lib/python3/dist-packages/sympy/integrals/manualintegrate.py", line 946, in integral_steps
    fallback_rule)(integral)
  File "/usr/lib/python3/dist-packages/sympy/strategies/core.py", line 85, in do_one_rl
    result = rl(expr)
  File "/usr/lib/python3/dist-packages/sympy/strategies/core.py", line 85, in do_one_rl
    result = rl(expr)
  File "/usr/lib/python3/dist-packages/sympy/strategies/core.py", line 65, in null_safe_rl
    result = rule(expr)
  File "/usr/lib/python3/dist-packages/sympy/integrals/manualintegrate.py", line 690, in trig_substitution_rule
    a = match[a]
TypeError: 'NoneType' object is not subscriptable
```

I'm using Debian 9 unstable, python3-sympy version 1.0-3, python3 version 3.5.3.

I haven't played around with the limits of the integral too much. On paper you can solve it trivially by transforming to polar coordinates first; the answer is 2*pi.

**Comment by jksuom** [comment]
It looks like `a` is redefined inside a loop on this line:
```
File "/usr/lib/python3/dist-packages/sympy/integrals/manualintegrate.py", line 690, in trig_substitution_rule
    a = match[a]
```
It is supposed to be a wild symbol for the match to work.

**Comment by TorinCooperBennun** [comment]
Bizarrely, I added `print(match)` under line 689 in manualintegrate.py, and the error stopped happening; now I just get the integral thrown back at me, unsolved. I reinstalled sympy and it continues to throw the integral back at me, without runtime errors.

I reckon it's because I was using the Spyder IDE, and some state somehow persisted after a previous run. Dunno, though.
