### ISSUE TITLE
Python3-only: simplify with numpy.array fails with unhashable type: 'ImmutableDenseNDimArray'

### ISSUE THREAD

**Issue by nschloe** [sympy/sympy#12665]
Simplifying expressions with `numpy.array`s works in Python 2, but _not_ Python 3.

MWE:
```python
import numpy
import sympy


class dot(sympy.Function):
    pass


a = numpy.array([1, 2, 3])
x = sympy.Symbol('x')

expr = dot(x, a)
print(expr)
sympy.simplify(expr)
```
Error message:
```
Traceback (most recent call last):
  File "b.py", line 15, in <module>
    sympy.simplify(expr)
  File "/usr/lib/python3/dist-packages/sympy/simplify/simplify.py", line 514, in simplify
    original_expr = expr = signsimp(expr)
  File "/usr/lib/python3/dist-packages/sympy/simplify/simplify.py", line 374, in signsimp
    e = sub_post(sub_pre(expr))
  File "/usr/lib/python3/dist-packages/sympy/simplify/cse_opts.py", line 20, in sub_pre
    e = e.xreplace(dict((a, Mul._from_args([S.NegativeOne, -a])) for a in reps))
  File "/usr/lib/python3/dist-packages/sympy/core/basic.py", line 1100, in xreplace
    value, _ = self._xreplace(rule)
  File "/usr/lib/python3/dist-packages/sympy/core/basic.py", line 1107, in _xreplace
    if self in rule:
  File "/usr/lib/python3/dist-packages/sympy/core/basic.py", line 110, in __hash__
    h = hash((type(self).__name__,) + self._hashable_content())
TypeError: unhashable type: 'ImmutableDenseNDimArray'
```
Tested with current master.

**Comment by jksuom** [comment]
This is probably a consequence of the new [rules](https://docs.python.org/3/reference/datamodel.html#object.__hash__) concerning equality and hashing in Python 3. This paragraph, in particular:

`If a class that overrides __eq__() needs to retain the implementation of __hash__() from a parent class, the interpreter must be told this explicitly by setting __hash__ = <ParentClass>.__hash__.`

In this case `__eq__()` is overridden in `NDimArray` but `__hash()__` is to be inherited from `Basic`.

cc. @Upabjojr

**Comment by nschloe** [comment]
Thanks everyone for the quick fix!
