### ISSUE TITLE
ValueError in subs

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#12709]
`(-512*b**3).subs(-2*b,-a+m)` gives `ValueError: negative shift count`

**Comment by ayush1999** [comment]
How can I view the source code for subs method?
Sorry to interrupt.

**Comment by ArifAhmed1995** [comment]
@ayush1999 Use a debugger like `puDB` , `WinPDB` , etc to step into the function calls triggered by the above statement.

**Comment by ayush1999** [comment]
@ArifAhmed1995 Suppose I use the pdb debugger. I'm not sure how it can help me in finding the source code of subs method. Can you help me out?
Thanks.

**Comment by ArifAhmed1995** [comment]
You should firstly clone the SymPy repository on your local machine.
Look up tutorials for `puDB`. I'm sure there are many available on the net.

**Comment by debugger22** [comment]
Interesting! This only fails when it can be represented as `2**n` where `n > 7`

```
>>> (-2**6*b**3).subs(-2*b,-a+m)
-8*(a - m)**3
>>> (-2**7*b**3).subs(-2*b,-a+m)
-16*(a - m)**3
>>> (-2**8*b**3).subs(-2*b,-a+m)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sudhanshu/workspace/sympy/sympy/core/basic.py", line 915, in subs
    rv = rv._subs(old, new, **kwargs)
  File "/Users/sudhanshu/workspace/sympy/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/sudhanshu/workspace/sympy/sympy/core/basic.py", line 1027, in _subs
    rv = self._eval_subs(old, new)
  File "/Users/sudhanshu/workspace/sympy/sympy/core/mul.py", line 1341, in _eval_subs
    return self._subs(-old, -new)
  File "/Users/sudhanshu/workspace/sympy/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/sudhanshu/workspace/sympy/sympy/core/basic.py", line 1027, in _subs
    rv = self._eval_subs(old, new)
  File "/Users/sudhanshu/workspace/sympy/sympy/core/mul.py", line 1433, in _eval_subs
    mult = S(multiplicity(abs(co_old), co_self))
  File "/Users/sudhanshu/workspace/sympy/sympy/ntheory/factor_.py", line 236, in multiplicity
    return trailing(n)
  File "/Users/sudhanshu/workspace/sympy/sympy/ntheory/factor_.py", line 179, in trailing
    if n == 1 << z:
ValueError: negative shift count
```

**Comment by smichr** [comment]
> This only fails when it can be represented as 2**n where n > 7

This happens because small_trailing are handled explicitly in trailing. Past that, bitcount is used -- it assumes `n >= 0`. The error above is triggered when n is negative. I'll open a PR shortly.
