### ISSUE TITLE
Rust printer runs wrong method

### ISSUE THREAD

**Issue by lej-la** [sympy/sympy#12773]
This code demonstrates the issue:

```
>>> from sympy import rust_code
>>> A = MatrixSymbol("A", 1, 3)
>>> rust_code(A[0,0])
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/lejla/sympy/sympy/printing/rust.py", line 620, in rust_code
    return RustCodePrinter(settings).doprint(expr, assign_to)
    File "/home/lejla/sympy/sympy/printing/codeprinter.py", line 81, in doprint
    lines = self._print(expr).splitlines()
    File "/home/lejla/sympy/sympy/printing/printer.py", line 257, in _print
    return getattr(self, printmethod)(expr, *args, **kwargs)
    File "/home/lejla/sympy/sympy/printing/rust.py", line 439, in _print_MatrixBase
    if A.cols == 1:
    AttributeError: 'MatrixElement' object has no attribute 'cols'
    _print_MatrixBase()` in `rust.py` is executed instead of `_print_MatrixElement()
```

**Comment by smichr** [comment]
> _print_MatrixBase() in rust.py is executed instead of _print_MatrixElement()

That's because the definition get overridden a few lines down. The following will fix the issue:

```diff
diff --git a/sympy/printing/rust.py b/sympy/printing/rust.py
index 814a305..efb92f1 100644
--- a/sympy/printing/rust.py
+++ b/sympy/printing/rust.py
@@ -449,7 +449,6 @@ def _print_MatrixElement(self, expr):
     # method from higher up the class hierarchy (see _print_NumberSymbol).
     # Then subclasses like us would not need to repeat all this.
     _print_Matrix = \
-        _print_MatrixElement = \
         _print_DenseMatrix = \
         _print_MutableDenseMatrix = \
         _print_ImmutableMatrix = \
```
