### ISSUE TITLE
No algorithm implemented to solve expression with LambertW

### ISSUE THREAD

**Issue by trxrunner** [sympy/sympy#12783]
Sympy cannot solve this simple expression with LambertW
```
>>> solve(Eq(LambertW(n),x),n)
Traceback (most recent call last):
  File "<pyshell#87>", line 1, in <module>
    solve(Eq(LambertW(n),x),n)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\sympy\solvers\solvers.py", line 1053, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\sympy\solvers\solvers.py", line 1619, in _solve
    raise NotImplementedError('\n'.join([msg, not_impl_msg % f]))
NotImplementedError: 
No algorithms are implemented to solve equation -x + LambertW(n)

>>> solveset(Eq(LambertW(n),x),n)
ConditionSet(n, Eq(-x + LambertW(n), 0), Complexes((-oo, oo) x (-oo, oo), False))

#The answer should be:
>>> solve(Eq(LambertW(n),x),n)
[x*exp(x)]
```

**Comment by smichr** [comment]
Hmm...we recognize when solutions should be given in terms of LambertW but didn't include this one. Are there branches to worry about or is exp(x)*x always the solution?

**Comment by trxrunner** [comment]
I believe exp(x)*x is always the solution.

**Comment by smichr** [comment]
If you want to give #12785 a look, I have a proposal there for a SymPy update.
