### ISSUE TITLE
left trim error while solving system of equations

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12815]
Regular solve runs into a problem with the following
```
>>> eqns[:2]
[x0**2 - x0, x0*x1 - x1]
>>> solve(_)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solvers.py", line 1071, in solve
    solution = _solve_system(f, symbols, **flags)
  File "sympy\solvers\solvers.py", line 1748, in _solve_system
    result = solve_poly_system(polys, *symbols)
  File "sympy\solvers\polysys.py", line 45, in solve_poly_system
    return solve_biquadratic(f, g, opt)
  File "sympy\solvers\polysys.py", line 86, in solve_biquadratic
    q = q.ltrim(-1)
  File "sympy\polys\polytools.py", line 634, in ltrim
    if monom not in terms:
sympy.polys.polyerrors.PolynomialError: can't left trim Poly(x0*x1 - x1, x0, x1,
 domain='ZZ')
>>> eqs
[x0**2 - x0, x0*x1 - x1]
```
Manually solving gives
```
>>> solve(eqs, manual=True)
[{x0: 1}, {x0: 0, x1: 0}]
```

**Comment by smichr** [comment]
I bellieve ltrim is miss assessing whether something is a dummy symbol. The criteria should be that that none of generators to be deleted appear in the monomials of the expression; alternitively, if any monomial has any of the generators that are being trimmed, the routine should signal failure.

**Comment by smichr** [comment]
```diff
diff --git a/sympy/polys/polytools.py b/sympy/polys/polytools.py
index 92e7ca6..3d91c51 100644
--- a/sympy/polys/polytools.py
+++ b/sympy/polys/polytools.py
@@ -614,7 +614,10 @@ def reorder(f, *gens, **args):
 
     def ltrim(f, gen):
         """
-        Remove dummy generators from the "left" of ``f``.
+        Remove dummy generators from ``f`` that are to the left of
+        specified ``gen`` in the generators as ordered. if ``gen``
+        is an integer, it refers to the generator at position ``gen``
+        within the tuple of generators.
 
         Examples
         ========
@@ -624,20 +627,24 @@ def ltrim(f, gen):
 
         >>> Poly(y**2 + y*z**2, x, y, z).ltrim(y)
         Poly(y**2 + y*z**2, y, z, domain='ZZ')
+        >>> Poly(z, x, y, z).ltrim(-1)
+        Poly(z, z, domain='ZZ')
 
         """
         rep = f.as_dict(native=True)
         j = f._gen_to_level(gen)
+
         terms = {}
 
         for monom, coeff in rep.items():
-            monom = monom[j:]
 
-            if monom not in terms:
-                terms[monom] = coeff
-            else:
+            if any(i for i in monom[:j]):
+                # some generator is used in the portion to be trimmed
                 raise PolynomialError("can't left trim %s" % f)
 
+            monom = monom[j:]
+            terms[monom] = coeff
+
         gens = f.gens[j:]
 
         return f.new(DMP.from_dict(terms, len(gens) - 1, f.rep.dom), *gens)
@@ -658,7 +665,7 @@ def has_only_gens(f, *gens):
         False
 
         """
-        indices = set([])
+        indices = set()
 
         for gen in gens:
             try:
diff --git a/sympy/polys/tests/test_polytools.py b/sympy/polys/tests/test_polytools.py
index 8e30ef1..32d1780 100644
--- a/sympy/polys/tests/test_polytools.py
+++ b/sympy/polys/tests/test_polytools.py
@@ -853,9 +853,10 @@ def test_Poly_reorder():
 def test_Poly_ltrim():
     f = Poly(y**2 + y*z**2, x, y, z).ltrim(y)
     assert f.as_expr() == y**2 + y*z**2 and f.gens == (y, z)
+    assert Poly(x*y - x, z, x, y).ltrim(1) == Poly(x*y - x, x, y)
 
     raises(PolynomialError, lambda: Poly(x*y**2 + y**2, x, y).ltrim(y))
-
+    raises(PolynomialError, lambda: Poly(x*y - x, x, y).ltrim(-1))
 
 def test_Poly_has_only_gens():
     assert Poly(x*y + 1, x, y, z).has_only_gens(x, y) is True
```
