### ISSUE TITLE
integrate((a + b*x)**(5/2)/x**5, x) error

### ISSUE THREAD

**Issue by parsoyaarihant** [sympy/sympy#12975]
```python
>>> integrate((a + b*x)**(5/2)/x**5, x)
Traceback (most recent call last):
  File "/Users/parsoyaarihant/sympy/sympy/polys/polyutils.py", line 209, in _parallel_dict_from_expr_if_gens
    monom[indices[base]] = exp
KeyError: RisingFactorial(_t + 1, 4.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/parsoyaarihant/sympy/sympy/polys/partfrac.py", line 83, in apart
    (P, Q), opt = parallel_poly_from_expr((P, Q), x, **options)
  File "/Users/parsoyaarihant/sympy/sympy/polys/polytools.py", line 4266, in parallel_poly_from_expr
    return _parallel_poly_from_expr(exprs, opt)
  File "/Users/parsoyaarihant/sympy/sympy/polys/polytools.py", line 4319, in _parallel_poly_from_expr
    reps, opt = _parallel_dict_from_expr(exprs, opt)
  File "/Users/parsoyaarihant/sympy/sympy/polys/polyutils.py", line 329, in _parallel_dict_from_expr
    reps, gens = _parallel_dict_from_expr_if_gens(exprs, opt)
  File "/Users/parsoyaarihant/sympy/sympy/polys/polyutils.py", line 214, in _parallel_dict_from_expr_if_gens
    raise PolynomialError("%s contains an element of the generators set" % factor)
sympy.polys.polyerrors.PolynomialError: RisingFactorial(_t + 1, 4.0) contains an element of the generators set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/parsoyaarihant/sympy/sympy/integrals/integrals.py", line 1295, in integrate
    risch=risch, manual=manual)
  File "/Users/parsoyaarihant/sympy/sympy/integrals/integrals.py", line 486, in doit
    conds=conds)
  File "/Users/parsoyaarihant/sympy/sympy/integrals/integrals.py", line 908, in _eval_integral
    h = meijerint_indefinite(g, x)
  File "/Users/parsoyaarihant/sympy/sympy/integrals/meijerint.py", line 1612, in meijerint_indefinite
    res = _meijerint_indefinite_1(f.subs(x, x + a), x)
  File "/Users/parsoyaarihant/sympy/sympy/integrals/meijerint.py", line 1677, in _meijerint_indefinite_1
    r = hyperexpand(r.subs(t, a*x**b), place=place)
  File "/Users/parsoyaarihant/sympy/sympy/simplify/hyperexpand.py", line 2471, in hyperexpand
    return f.replace(hyper, do_replace).replace(meijerg, do_meijer)
  File "/Users/parsoyaarihant/sympy/sympy/core/basic.py", line 1407, in replace
    rv = bottom_up(self, rec_replace, atoms=True)
  File "/Users/parsoyaarihant/sympy/sympy/simplify/simplify.py", line 998, in bottom_up
    rv = F(rv)
  File "/Users/parsoyaarihant/sympy/sympy/core/basic.py", line 1392, in rec_replace
    new = _value(expr, result)
  File "/Users/parsoyaarihant/sympy/sympy/core/basic.py", line 1335, in <lambda>
    _value = lambda expr, result: value(*expr.args)
  File "/Users/parsoyaarihant/sympy/sympy/simplify/hyperexpand.py", line 2468, in do_meijer
    allow_hyper, rewrite=rewrite, place=place)
  File "/Users/parsoyaarihant/sympy/sympy/simplify/hyperexpand.py", line 2345, in _meijergexpand
    slater1, cond1 = do_slater(func.an, func.bm, func.ap, func.bq, z, z0)
  File "/Users/parsoyaarihant/sympy/sympy/simplify/hyperexpand.py", line 2279, in do_slater
    t, premult, bh, rewrite=None)
  File "/Users/parsoyaarihant/sympy/sympy/simplify/hyperexpand.py", line 2025, in _hyperexpand
    formula = try_lerchphi(func)
  File "/Users/parsoyaarihant/sympy/sympy/simplify/hyperexpand.py", line 1766, in try_lerchphi
    part = apart(numer/denom, t)
  File "/Users/parsoyaarihant/sympy/sympy/utilities/decorator.py", line 37, in threaded_func
    return func(expr, *args, **kwargs)
  File "/Users/parsoyaarihant/sympy/sympy/polys/partfrac.py", line 86, in apart
    raise PolynomialError(msg)
sympy.polys.polyerrors.PolynomialError: RisingFactorial(_t + 1, 4.0) contains an element of the generators set
```

**Comment by cjekel** [comment]
I stumbled upon this when integrating a different function, but found that using ```nsimplify``` first like https://github.com/sympy/sympy/issues/2884#issuecomment-34587469 worked for me. Maybe this will be helpful for anyone else who finds into this issue.

**Comment by oscarbenjamin** [comment]
Rather than using nsimplify you should ensure that you always use rational numbers with e.g. `S(5)/2` or `Rational(5, 2)` instead of `5/2`:
```julia
In [14]: integrate((a + b*x)**(S(5)/2)/x**5, x)                                                                                   
Out[14]: 
                                                                                                                                
              3                        2                         3/2                    5/2                     7/2          5⋅b
             a                     23⋅a ⋅√b               127⋅a⋅b                  133⋅b                     5⋅b                
- ─────────────────────── - ───────────────────── - ───────────────────── - ────────────────────── - ───────────────────── + ───
                _________               _________               _________                _________               _________      
        9/2    ╱  a             7/2    ╱  a             5/2    ╱  a              3/2    ╱  a                    ╱  a            
  4⋅√b⋅x   ⋅  ╱  ─── + 1    24⋅x   ⋅  ╱  ─── + 1    96⋅x   ⋅  ╱  ─── + 1    192⋅x   ⋅  ╱  ─── + 1    64⋅a⋅√x⋅  ╱  ─── + 1       
            ╲╱   b⋅x                ╲╱   b⋅x                ╲╱   b⋅x                 ╲╱   b⋅x                ╲╱   b⋅x           

4      ⎛  √a ⎞
 ⋅asinh⎜─────⎟
       ⎝√b⋅√x⎠
──────────────
      3/2     
  64⋅a    
```
(assuming that's the correct answer...)
