### ISSUE TITLE
sympy generates exception on integrate(log(abs(x)),x)

### ISSUE THREAD

**Issue by nasser1** [sympy/sympy#12996]
copied from 

https://stackoverflow.com/questions/45181469/sympy-generates-exception-on-integratelogabsx-x

If sympy can't do an integral, should it not return the input unevaluated? Why does it generate an exception here?

integrate(log(abs(x)),x) gives exception. But integrate(log(x),x) does not. Why?

```
>python
Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> x=symbols('x')
>>> integrate(log(x),x)
x*log(x) - x
>>> integrate(log(abs(x)),x)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/anaconda3/lib/python3.6/site-packages/sympy/integrals/integrals.py", line 1295, in integrate
    risch=risch, manual=manual)
  File "/home/me/anaconda3/lib/python3.6/site-packages/sympy/integrals/integrals.py", line 486, in doit
    conds=conds)
  File "/home/me/anaconda3/lib/python3.6/site-packages/sympy/integrals/integrals.py", line 926, in _eval_integral
    for arg in result.args
  File "/home/me/anaconda3/lib/python3.6/site-packages/sympy/integrals/integrals.py", line 926, in <listcomp>
    for arg in result.args
  File "/home/me/anaconda3/lib/python3.6/site-packages/sympy/core/basic.py", line 1554, in doit
    for term in self.args]
  File "/home/me/anaconda3/lib/python3.6/site-packages/sympy/core/basic.py", line 1554, in <listcomp>
    for term in self.args]
  File "/home/me/anaconda3/lib/python3.6/site-packages/sympy/integrals/integrals.py", line 397, in doit
    function = function.doit(**hints)
  File "/home/me/anaconda3/lib/python3.6/site-packages/sympy/core/basic.py", line 1554, in doit
    for term in self.args]
  File "/home/me/anaconda3/lib/python3.6/site-packages/sympy/core/basic.py", line 1554, in <listcomp>
    for term in self.args]
  File "/home/me/anaconda3/lib/python3.6/site-packages/sympy/core/function.py", line 1315, in doit
    return self.func(expr, *self.variables, **hints)
  File "/home/me/anaconda3/lib/python3.6/site-packages/sympy/core/function.py", line 1208, in __new__
    expr = Expr.__new__(cls, expr, *unhandled_variables, **assumptions)
TypeError: __new__() got an unexpected keyword argument 'manual'
```

Posting it here in case this is new issue.

**Comment by asmeurer** [comment]
From gitter, proposed fix

```diff
diff --git a/sympy/core/function.py b/sympy/core/function.py
index d14e2e2954..1bf9bc2e26 100644
--- a/sympy/core/function.py
+++ b/sympy/core/function.py
@@ -1097,7 +1097,7 @@ def _diff_wrt(self):
         else:
             return False
 
-    def __new__(cls, expr, *variables, **assumptions):
+    def __new__(cls, expr, *variables, **kwargs):
 
         from sympy.matrices.common import MatrixCommon
         from sympy import Integer
@@ -1192,9 +1192,7 @@ def __new__(cls, expr, *variables, **assumptions):
         if len(variable_count) == 0:
             return expr
 
-        # Pop evaluate because it is not really an assumption and we will need
-        # to track it carefully below.
-        evaluate = assumptions.pop('evaluate', False)
+        evaluate = kwargs.pop('evaluate', False)
 
         # Look for a quick exit if there are symbols that don't appear in
         # expression at all. Note, this cannot check non-symbols like
@@ -1222,7 +1220,7 @@ def __new__(cls, expr, *variables, **assumptions):
             # Here we *don't* need to reinject evaluate into assumptions
             # because we are done with it and it is not an assumption that
             # Expr knows about.
-            obj = Expr.__new__(cls, expr, *variable_count, **assumptions)
+            obj = Expr.__new__(cls, expr, *variable_count)
             return obj
 
         # Compute the derivative now by repeatedly calling the
@@ -1292,7 +1290,7 @@ def __new__(cls, expr, *variables, **assumptions):
 
         if unhandled_variable_count:
             unhandled_variable_count = cls._sort_variable_count(unhandled_variable_count)
-            expr = Expr.__new__(cls, expr, *unhandled_variable_count, **assumptions)
+            expr = Expr.__new__(cls, expr, *unhandled_variable_count)
         else:
             # We got a Derivative at the end of it all, and we rebuild it by
             # sorting its variables.
@@ -1301,7 +1299,7 @@ def __new__(cls, expr, *variables, **assumptions):
                     expr.args[0], *cls._sort_variable_count(expr.args[1:])
                 )
 
-        if (nderivs > 1) == True and assumptions.get('simplify', True):
+        if (nderivs > 1) == True and kwargs.get('simplify', True):
             from sympy.core.exprtools import factor_terms
             from sympy.simplify.simplify import signsimp
             expr = factor_terms(signsimp(expr))
```
