### ISSUE TITLE
Error solving system of ODEs

### ISSUE THREAD

**Issue by jostheim** [sympy/sympy#13060]
I am a newbie to sympy, only used it for simple things before but I am getting some weird error messages, here is my code:

```
A, B = symbols("A B", cls=Function)
vm, A, B, kB, kA, t, A0, B0 = symbols("vm a b kB kA t A0 B0")
system = (Eq(A(t).diff(t), -1*(vm * A(t) * B(t) / (A(t) * B(t) + kB * A(t) + kA * B(t)))), 
          Eq(B(t).diff(t), -1*(vm * A(t) * B(t) / (A(t) * B(t) + kB * A(t) + kA * B(t)))))
ics = {A(0): A0, B(0): B0}
dsolve(system, [A(t), B(t)], ics=ics)
```

I get the following error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-407-c9ef03866839> in <module>()
     17           Eq(B(t).diff(t), -1*(vm * A(t) * B(t) / (A(t) * B(t) + kB * A(t) + kA * B(t)))))
     18 ics = {A(0): A0, B(0): B0}
---> 19 dsolve(system, [A(t), B(t)], ics=ics)
     20 
     21 

/usr/lib/python2.7/site-packages/sympy/solvers/ode.pyc in dsolve(eq, func, hint, simplify, ics, xi, eta, x0, n, **kwargs)
    615             else:
    616                 solvefunc = globals()['sysode_nonlinear_%(no_of_equation)seq_order%(order)s' % match]
--> 617             sols = solvefunc(match)
    618             return sols
    619     else:

/usr/lib/python2.7/site-packages/sympy/solvers/ode.pyc in sysode_nonlinear_2eq_order1(match_)
   7772         sol = _nonlinear_2eq_order1_type2(x, y, t, eq)
   7773     elif match_['type_of_equation'] == 'type3':
-> 7774         sol = _nonlinear_2eq_order1_type3(x, y, t, eq)
   7775     elif match_['type_of_equation'] == 'type4':
   7776         sol = _nonlinear_2eq_order1_type4(x, y, t, eq)

/usr/lib/python2.7/site-packages/sympy/solvers/ode.pyc in _nonlinear_2eq_order1_type3(x, y, t, eq)
   7894     G = r2[g].subs(x(t),u).subs(y(t),v)
   7895     sol2r = dsolve(Eq(diff(v(u),u), G.subs(v,v(u))/F.subs(v,v(u))))
-> 7896     for sol2s in sol2r:
   7897         sol1 = solve(Integral(1/F.subs(v, sol2s.rhs), u).doit() - t - C2, u)
   7898     sol = []

TypeError: 'Equality' object is not iterable
```

As far as I can tell I setup the problem correctly, does anyone have any advice?

James

**Comment by maurogaravello** [comment]
For the system in the example, the code
`    sol2r = dsolve(Eq(diff(v(u),u), G.subs(v,v(u))/F.subs(v,v(u))))
`
returns an `Equality`. I tried to avoid it inserting the code
`    if isinstance(sol2r, Eq):
        sol2r = [sol2r]
`
so that `sol2r` becomes a `list`. Unfortunately the output is
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/mgarav/gitHub/sympy/issue.py", line 16, in <module>
>     dsolve(system)
>   File "/home/mgarav/gitHub/sympy/sympy/solvers/ode.py", line 615, in dsolve
>     sols = solvefunc(match)
>   File "/home/mgarav/gitHub/sympy/sympy/solvers/ode.py", line 7905, in sysode_nonlinear_2eq_order1
>     sol = _nonlinear_2eq_order1_type3(x, y, t, eq)
>   File "/home/mgarav/gitHub/sympy/sympy/solvers/ode.py", line 8030, in _nonlinear_2eq_order1_type3
>     sol1 = solve(Integral(1/F.subs(v, sol2s.rhs), u).doit() - t - C2, u)
>   File "/home/mgarav/gitHub/sympy/sympy/solvers/solvers.py", line 1066, in solve
>     solution = _solve(f[0], *symbols, **flags)
>   File "/home/mgarav/gitHub/sympy/sympy/solvers/solvers.py", line 1635, in _solve
>     raise NotImplementedError('\n'.join([msg, not_impl_msg % f]))
> NotImplementedError: multiple generators [u, log(C1*kA/(kA - kB) - C1*kB/(kA - kB) + u), log(u)]
> No algorithms are implemented to solve equation -C2 - kA*log(u)/vm - kB*log(u + (C1*kA - C1*kB)/(kA - kB))/vm - t - u/vm
> 
It seems that no algorithm is implemented.

**Comment by oscarbenjamin** [comment]
I had to edit the code slightly to run it
```python
A, B = symbols("A B", cls=Function)
vm, kB, kA, t, A0, B0 = symbols("vm kB kA t A0 B0")
system = (Eq(A(t).diff(t), -1*(vm * A(t) * B(t) / (A(t) * B(t) + kB * A(t) + kA * B(t)))), 
          Eq(B(t).diff(t), -1*(vm * A(t) * B(t) / (A(t) * B(t) + kB * A(t) + kA * B(t)))))
ics = {A(0): A0, B(0): B0}
dsolve(system, [A(t), B(t)], ics=ics)
```
but still get the same error afterwards.

**Comment by cjmcgill** [comment]
Ran into this error today. Is there a resolution?

**Comment by oscarbenjamin** [comment]
This is still unfixed on master. The basic problem is easy to fix:
```diff
diff --git a/sympy/solvers/ode/ode.py b/sympy/solvers/ode/ode.py
index a2f1bd3eb2..698a3a070c 100644
--- a/sympy/solvers/ode/ode.py
+++ b/sympy/solvers/ode/ode.py
@@ -6692,7 +6692,7 @@ def _nonlinear_2eq_order1_type3(x, y, t, eq):
     F = r1[f].subs(x(t), u).subs(y(t), v(u))
     G = r2[g].subs(x(t), u).subs(y(t), v(u))
     sol2r = dsolve(Eq(diff(v(u), u), G/F))
-    if isinstance(sol2r, Expr):
+    if isinstance(sol2r, Equality):
         sol2r = [sol2r]
     for sol2s in sol2r:
         sol1 = solve(Integral(1/F.subs(v(u), sol2s.rhs), u).doit() - t - C2, u)
```
However the example then hits another problem which is
```julia
In [1]: A, B = symbols("A B", cls=Function) 
   ...: vm, kB, kA, t, A0, B0 = symbols("vm kB kA t A0 B0") 
   ...: system = (Eq(A(t).diff(t), -1*(vm * A(t) * B(t) / (A(t) * B(t) + kB * A(t) + kA * B(t)))),  
   ...:           Eq(B(t).diff(t), -1*(vm * A(t) * B(t) / (A(t) * B(t) + kB * A(t) + kA * B(t))))) 
   ...: ics = {A(0): A0, B(0): B0} 
   ...: dsolve(system, [A(t), B(t)], ics=ics)                                                                                                  
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-1-05a5f47a843b> in <module>
      4           Eq(B(t).diff(t), -1*(vm * A(t) * B(t) / (A(t) * B(t) + kB * A(t) + kA * B(t)))))
      5 ics = {A(0): A0, B(0): B0}
----> 6 dsolve(system, [A(t), B(t)], ics=ics)

~/current/sympy/sympy/sympy/solvers/ode/ode.py in dsolve(eq, func, hint, simplify, ics, xi, eta, x0, n, **kwargs)
    617             else:
    618                 solvefunc = globals()['sysode_nonlinear_%(no_of_equation)seq_order%(order)s' % match]
--> 619             sols = solvefunc(match)
    620             if ics:
    621                 constants = Tuple(*sols).free_symbols - Tuple(*eq).free_symbols

~/current/sympy/sympy/sympy/solvers/ode/ode.py in sysode_nonlinear_2eq_order1(match_)
   6569         sol = _nonlinear_2eq_order1_type2(x, y, t, eq)
   6570     elif match_['type_of_equation'] == 'type3':
-> 6571         sol = _nonlinear_2eq_order1_type3(x, y, t, eq)
   6572     elif match_['type_of_equation'] == 'type4':
   6573         sol = _nonlinear_2eq_order1_type4(x, y, t, eq)

~/current/sympy/sympy/sympy/solvers/ode/ode.py in _nonlinear_2eq_order1_type3(x, y, t, eq)
   6696         sol2r = [sol2r]
   6697     for sol2s in sol2r:
-> 6698         sol1 = solve(Integral(1/F.subs(v(u), sol2s.rhs), u).doit() - t - C2, u)
   6699     sol = []
   6700     for sols in sol1:

~/current/sympy/sympy/sympy/solvers/solvers.py in solve(f, *symbols, **flags)
   1095     ###########################################################################
   1096     if bare_f:
-> 1097         solution = _solve(f[0], *symbols, **flags)
   1098     else:
   1099         solution = _solve_system(f, symbols, **flags)

~/current/sympy/sympy/sympy/solvers/solvers.py in _solve(f, *symbols, **flags)
   1714 
   1715     if result is False:
-> 1716         raise NotImplementedError('\n'.join([msg, not_impl_msg % f]))
   1717 
   1718     if flags.get('simplify', True):

NotImplementedError: multiple generators [u, log(C1*kA/(kA - kB) - C1*kB/(kA - kB) + u), log(u)]
No algorithms are implemented to solve equation -C2 - kA*log(u)/vm - kB*log(u + (C1*kA - C1*kB)/(kA - kB))/vm - t - u/vm
```
That's because `solve` is unable to solve this equation for `u`:
```julia
In [2]: C1, C2 = symbols('C1, C2')                                                                                                             

In [3]: u = Symbol('u')                                                                                                                        

In [4]: eq = -C2 - kA*log(u)/vm - kB*log(u + (C1*kA - C1*kB)/(kA - kB))/vm - t - u/vm                                                          

In [5]: eq                                                                                                                                     
Out[5]: 
                        ⎛    C₁⋅kA - C₁⋅kB⎞         
                  kB⋅log⎜u + ─────────────⎟         
      kA⋅log(u)         ⎝       kA - kB   ⎠       u 
-C₂ - ───────── - ───────────────────────── - t - ──
          vm                  vm                  vm
```
This is a transcendental equation but it might be solvable in terms of `LambertW`. Alternatively it's possible that `dsolve` could return an implicit solution when the equation isn't solvable.

The diff above does allow `dsolve` to solve some simpler examples though e.g.:
```julia
In [4]: system2 = [Eq(Derivative(A(t), t), A(t)*B(t)), Eq(Derivative(B(t), t), A(t)*B(t))]                                                     

In [5]: system2                                                                                                                                
Out[5]: 
⎡d                     d                   ⎤
⎢──(A(t)) = A(t)⋅B(t), ──(B(t)) = A(t)⋅B(t)⎥
⎣dt                    dt                  ⎦

In [6]: sol = dsolve(system2)                                                                                                                  

In [7]: sol                                                                                                                                    
Out[7]: 
⎡           C₁⋅(C₂ + t)                   C₁⋅(C₂ + t) ⎤
⎢       C₁⋅ℯ                          C₁⋅ℯ            ⎥
⎢A(t) = ────────────────, B(t) = C₁ + ────────────────⎥
⎢            C₁⋅(C₂ + t)                   C₁⋅(C₂ + t)⎥
⎣       1 - ℯ                         1 - ℯ           ⎦

In [8]: checkodesol(system2, sol)                                                                                                              
Out[8]: (True, [0, 0])
```
Master gives the same `'TypeError: 'Equality' object is not iterable` for `system2`.

I'm adding the good first issue label because it would be a good fix to add the diff above along with a test for `system2`.

The issue could remain open for `system` though either to say that `dsolve` should return an implicit solution for that case or that `solve` should be improved to handle that case.

**Comment by oscarbenjamin** [comment]
The `system` example can have a solution given in implicit form. Basically the method for solving this system is:

1. We have dA/dt = f(A, B), dB/dt = g(A, B)

2. Divide one equation by the other to get `dA/dB = f(A, B) / g(A, B) := h(A, B)

3. Solve `dA/dB = g(A, B)` to get `A = a(B)`

4. Substitute that into the equation for `dB/dt` to eliminate `A(t)` which gives a single ODE `dB/dt = g(a(B(t), B(t))`.

5. Solve that ODE for `B(t)` and then `A(t) = a(B(t))`.

For this example the steps are
```julia
In [15]: A, B = symbols("A B", cls=Function) 
    ...: vm, kB, kA, t, A0, B0 = symbols("vm kB kA t A0 B0") 
    ...: system = (Eq(A(t).diff(t), -1*(vm * A(t) * B(t) / (A(t) * B(t) + kB * A(t) + kA * B(t)))),  
    ...:           Eq(B(t).diff(t), -1*(vm * A(t) * B(t) / (A(t) * B(t) + kB * A(t) + kA * B(t)))))                                            

In [16]: eq1, eq2 = system                                                                                                                     

In [17]: eq1                                                                                                                                   
Out[17]: 
d                  -vm⋅A(t)⋅B(t)        
──(A(t)) = ─────────────────────────────
dt         kA⋅B(t) + kB⋅A(t) + A(t)⋅B(t)

In [18]: eq2                                                                                                                                   
Out[18]: 
d                  -vm⋅A(t)⋅B(t)        
──(B(t)) = ─────────────────────────────
dt         kA⋅B(t) + kB⋅A(t) + A(t)⋅B(t)

In [19]: Eq(eq1.lhs / eq2.lhs, eq1.rhs / eq2.rhs)                                                                                              
Out[19]: 
d           
──(A(t))    
dt          
──────── = 1
d           
──(B(t))    
dt 
```
The gives `A(t) = B(t) + C1` so
```julia
In [20]: eq2b = eq2.subs(A(t), B(t) + Symbol('C1'))                                                                                            

In [21]: eq2b                                                                                                                                  
Out[21]: 
d                     -vm⋅(C₁ + B(t))⋅B(t)            
──(B(t)) = ───────────────────────────────────────────
dt         kA⋅B(t) + kB⋅(C₁ + B(t)) + (C₁ + B(t))⋅B(t)
```
At this point the method tries to solve this by integrating but it should actually be handled by calling `dsolve` recursively:
```julia
In [22]: solB = dsolve(eq2b, B(t))                                                                                                             

In [23]: solB                                                                                                                                  
Out[23]: kA⋅log(C₁ + B(t)) + kB⋅log(B(t)) + t⋅vm + B(t) = C₂

In [24]: solA = solB.subs(B(t), A(t) - Symbol('C1'))                                                                                           

In [25]: solA                                                                                                                                  
Out[25]: -C₁ + kA⋅log(A(t)) + kB⋅log(-C₁ + A(t)) + t⋅vm + A(t) = C₂
```
That gives implicit solutions for `A(t)` and `B(t)` because `solve` is unable to put them into explicit form.

I'm not sure whether `solve` should be able to get those into explicit form.

**Comment by cjmcgill** [comment]
The system that worded for me following this fix:
```
>>> eq1=Eq(f(x).diff(x),km1*g(x)-k1*f(x)*f(x))
>>> eq2=Eq(g(x).diff(x),-km1*g(x)+k1*f(x)*f(x))
>>> soln=dsolve((eq1,eq2))
```

The system that did not work for me:
```
>>> eq1=Eq(f(x).diff(x),km1*g(x)*g(x)-k1*f(x)*f(x))
>>> eq2=Eq(g(x).diff(x),-km1*g(x)*g(x)+k1*f(x)*f(x))
>>> soln=dsolve((eq1,eq2))
```
I will add a new issue for this unsupported (very difficult) system type
