### ISSUE TITLE
SympifyError('could not parse %r' % a, exc)

### ISSUE THREAD

**Issue by madeline-parsegon** [sympy/sympy#13072]
I have a python program that write polynomial functions and then uses Sympy's `solve()` function to find their inverses. 

```
x = Symbol('x')
y = Symbol('y')
for i in range(10):
    p = Poly.create_random()
    print("p orig " + str(p))
    solve(p, x)
    print("p in terms of x: " + str(p))
    solve(p, y)
    print("p in terms of y (inverse): " + str(p))
```

However, when I run the program I get the following error:

```
p orig y = 5*x**2 - 55*x**1 + 140
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sympy/core/sympify.py", line 354, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/usr/local/lib/python3.5/dist-packages/sympy/parsing/sympy_parser.py", line 894, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/usr/local/lib/python3.5/dist-packages/sympy/parsing/sympy_parser.py", line 807, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    Symbol ('y' )=Integer (5 )*Symbol ('x' )**Integer (2 )-Integer (55 )*Symbol ('x' )**Integer (1 )+Integer (140 )
                 ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "z.py", line 110, in <module>
    solve(p, x)
  File "/usr/local/lib/python3.5/dist-packages/sympy/solvers/solvers.py", line 833, in solve
    f, symbols = (_sympified_list(w) for w in [f, symbols])
  File "/usr/local/lib/python3.5/dist-packages/sympy/solvers/solvers.py", line 833, in <genexpr>
    f, symbols = (_sympified_list(w) for w in [f, symbols])
  File "/usr/local/lib/python3.5/dist-packages/sympy/solvers/solvers.py", line 824, in _sympified_list
    return list(map(sympify, w if iterable(w) else [w]))
  File "/usr/local/lib/python3.5/dist-packages/sympy/core/sympify.py", line 356, in sympify
    raise SympifyError('could not parse %r' % a, exc)
sympy.core.sympify.SympifyError: Sympify of expression 'could not parse 'y = 5*x**2 - 55*x**1 + 140'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)
```

Could someone explain to me the syntax error in my polynomial?

**Comment by smichr** [comment]
You have a single `=`; you should use Eq(y, f(x)) instead.

**Comment by madeline-parsegon** [comment]
@smichr When I do, `Eq(p, f(x))`, I get `NameError: name 'f' is not defined`. Pardon my very basic questions, I am very new to python. I also construct the polynomial as a string - would that pose an problem for Sympy?

**Comment by oscarbenjamin** [comment]
The error message above doesn't match the code shown. Running the example code on current master I get:
```
AttributeError: type object 'Poly' has no attribute 'create_random'
```

It looks like this issue was originally a misunderstanding so I'll close it. Feel free to open a new issue if you think there is something to fix.
