### ISSUE TITLE
Solveset to String to Parse_Expr

### ISSUE THREAD

**Issue by shutebt01** [sympy/sympy#13232]
I've been working on adding numpy to a site, and have noticed an odd error occuring.

When calling solveset on `sin(x+5)` for `Symbol("x")` it creates the solution following solution:

```Union(Intersection(Complexes(S.Reals x S.Reals, False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi - atan(sin(5)/cos(5))) + log(sqrt(cos(5)**2 + sin(5)**2)))), S.Integers)), Intersection(Complexes(S.Reals x S.Reals, False), ImageSet(Lambda(_n, -I*(I*(2*_n*pi - pi - atan(sin(5)/cos(5))) + log(sqrt(cos(5)**2 + sin(5)**2)))), S.Integers)))```

Parsing this back to an equation, via `parse_expr([String from above], transformations=standard_transformations)` it generates an invalid syntax error.

Simply put: `parse_expr(str(solveset(parse_expr("sin(x+5)"), Symbol("x"))))` creates an error

Sorry if this a stupid question, or if i've missed something in the docs.

**Comment by smichr** [comment]
Here is a simpler test case:
```python
>>> S(str(Intersection(S.Complexes, imageset(Lambda (x, x**2), S.Complexes))))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/core/sympify.py", line 386, in sympify
    raise SympifyError('could not parse %r' % a, exc)
SympifyError: Sympify of expression 'could not parse u'Intersection(Complexes(Reals x Reals, False), ImageSet(Lambda(x, x**2), Complexes(Reals x Reals, False)))'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)
```
