### ISSUE TITLE
:bug: sympify error when expr contains "ff"

### ISSUE THREAD

**Issue by uwevil** [sympy/sympy#13266]
Hello,

I had an error when I used sympy to simplify an algebraic expression which contains "ff" constant.
For example,

> a = "((ff + 12) + m)"
> sympify(a)

I got:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/gitlab/sort_algo/env/lib/python3.5/site-packages/sympy/core/basic.py", line 399, in __repr__
    return sstr(self, order=None)
  File "/home/vagrant/gitlab/sort_algo/env/lib/python3.5/site-packages/sympy/printing/str.py", line 788, in sstr
    s = p.doprint(expr)
  File "/home/vagrant/gitlab/sort_algo/env/lib/python3.5/site-packages/sympy/printing/printer.py", line 233, in doprint
    return self._str(self._print(expr))
  File "/home/vagrant/gitlab/sort_algo/env/lib/python3.5/site-packages/sympy/printing/printer.py", line 257, in _print
    return getattr(self, printmethod)(expr, *args, **kwargs)
  File "/home/vagrant/gitlab/sort_algo/env/lib/python3.5/site-packages/sympy/printing/str.py", line 51, in _print_Add
    terms = self._as_ordered_terms(expr, order=order)
  File "/home/vagrant/gitlab/sort_algo/env/lib/python3.5/site-packages/sympy/printing/printer.py", line 270, in _as_ordered_terms
    return expr.as_ordered_terms(order=order)
  File "/home/vagrant/gitlab/sort_algo/env/lib/python3.5/site-packages/sympy/core/expr.py", line 944, in as_ordered_terms
    terms, gens = self.as_terms()
  File "/home/vagrant/gitlab/sort_algo/env/lib/python3.5/site-packages/sympy/core/expr.py", line 974, in as_terms
    coeff, _term = term.as_coeff_Mul()
TypeError: as_coeff_Mul() missing 1 required positional argument: 'self'
```

But if I replace "ff" by "fa" or something else like "aa", it works fine:
> a = "((fa + 12) + m)"
>sympify(a)
`fa + m + 12`

> a = "((aa + 12) + m)"
>sympify(a)
`aa + m + 12`

Here is my "requirements.txt" file:
```
appdirs==1.4.3
cycler==0.10.0
matplotlib==2.0.2
mpmath==0.19
numpy==1.12.1
packaging==16.8
pyparsing==2.2.0
python-dateutil==2.6.0
pytz==2017.2
six==1.10.0
sympy==1.1.1
```

Best regards,
uwevil

**Comment by uwevil** [comment]
It likes something `FallingFactorial`.
>a = "ff"
> sympify(a)
`FallingFactorial`. 

So it is not an error!!!
