### ISSUE TITLE
<Expr>.is_positive can fail with InconsistentAssumptions

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#13298]
Consider `z = (cbrt(3) + 3**(S(5)/6)*I)**6*LambertW(1) + 1`, a real, positive number.  Sympy sometimes concludes `.is_positive` is True and simulateously False.

To reproduce, run this a few times (doesn't fail every time):
`python3 -c "from sympy import *; z = (cbrt(3) + 3**(S(5)/6)*I)**6*LambertW(1) + 1; print(z.is_positive)"`

````
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sympy/core/assumptions.py", line 243, in getit
    return self._assumptions[fact]
KeyError: 'positive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/sympy/core/assumptions.py", line 247, in getit
    return _ask(fact, self)
  File "/usr/lib/python3.6/site-packages/sympy/core/assumptions.py", line 292, in _ask
    assumptions.deduce_all_facts(((fact, a),))
  File "/usr/lib/python3.6/site-packages/sympy/core/facts.py", line 524, in deduce_all_facts
    if not self._tell(k, v) or v is None:
  File "/usr/lib/python3.6/site-packages/sympy/core/facts.py", line 495, in _tell
    raise InconsistentAssumptions(self, k, v)
sympy.core.facts.InconsistentAssumptions: {
	commutative: True,
	complex: True,
	composite: False,
	even: False,
	hermitian: True,
	imaginary: False,
	integer: False,
	negative: False,
	noninteger: True,
	nonnegative: True,
	nonpositive: False,
	nonzero: True,
	odd: False,
	positive: True,
	prime: False,
	real: True,
	zero: False}, positive=False
````
Note it is both positive and not positive...

The key feature that leads to this seems to be this expression:
````
>>> a = (cbrt(3) + 3**(S(5)/6)*I)**6
>>> simplify(a)
576
````
(in fact with `...**3` it is -24; gives similar results but is a little harder to reproduce.)

- - - - - -
Here's some debugging:

First, evalf of `a` in any precision has a small imaginary component:
````
>>> a.evalf()
576.0 + 0.e-19*I
>>> a.evalf(32)
576.0 + 0.e-37*I
>>> a.evalf(64)
576.0 + 0.e-68*I
````

Eventually, I tracked the problem to Expr._eval_is_positive:
````
n, i = self.evalf(2).as_real_imag()
  ---- 8< ----
if n._prec != 1 and i._prec != 1:
    b  return bool(not i and n > 0)
````
This sort of thing is fine for `a` above (which does indeed have `i._prec == 1`).
**But it seems fragile!**  Are we really promising that `.evalf(2)` on any real expression will give either (a) no imaginary part or (b) an imaginary part which prec 1?
If that ever fails, the expression can return False from `is_positve` and `is_negative` (latter uses essentially the same code).

Indeed, this bug is a counterexample.  Supposing `a` is multiplied by some number that is not a Number such as `LambertW(1)`.  We have:
````
>>> n, i = (a*LambertW(1)).evalf(2).as_real_imag()
(3.3e+2, 1.7e-9)
>>> n._prec
10
>>> i._prec   # not 1
10
````
(Full bug with the InconsistentAssumptions exception happens on `a*LambertW(1) + 1`: the`Add` takes this code path.)

I think this is related to SymPy taking the maximal prec when multiplying two Floats.

**Comment by skirpichev** [comment]
I can reproduce this on py3.6 only.  And for <=v1.1 - there was just a wrong answer (False).

Instead of testing .\_prec for real/imag parts, you could use "strict" option of evalf, like I did [here](diofant/diofant#500).  One warning: sometimes with strict=True - evalf still produce imaginary part with \_prec=1, lower than requested precision (and no PrecisionExhausted raised).  I believe, this is a bug.

**Comment by asmeurer** [comment]
Shouldn't it use the minimum of the precs when multiplying?

**Comment by cbm755** [comment]
@skirpichev thanks!

@asmeurer I certainly think so, but lots of places in SymPy try to magically upscale low-precision Floats to higher-precision, as if that were actually possible to do.  (I think I could give more evidence of this by looking back through #12192 commits).
