### ISSUE TITLE
plotting.plot.plot does not plot Piecewise function, error in experimental_lambdify.py

### ISSUE THREAD

**Issue by BananaOrbit** [sympy/sympy#13320]
The following python 3.6.2 code causes the error 

TypeError: '>=' not supported between instances of 'complex' and 'float'

 in the experimental_lambdify module.

```
from sympy import Piecewise, And
from sympy.plotting.plot import plot
from sympy.abc import symbols

def getFedTax(alpha,p,AGI):
    # alpha is an array indicating the starting dollar amount of each tax bracket, 0 being the first entry
    # p[1] is an increasing list of tax percentages, not including 0 percent
    # Symbol x or var AGI is the Adjusted Gross Income for computation
    
    #Compute the list of cumulative sums, including 0 as the first.
    cumsums = [0.]
    i = 1
    while i<= list(enumerate(alpha))[-1][0]:
        cumsums.append(p[i-1]*(alpha[i] - alpha[i-1]) + cumsums[i-1])
        i = i + 1
    
    #Create the argument list of tuples for the SymPy.Piecewise function
    argtuples = []
    x = symbols('x')
    
    print('This is the piecewise function you have created: \n')
    for n,bracstart in enumerate(alpha):
        if n < list(enumerate(alpha))[-1][0]:
            argtuples.append((cumsums[n] + p[n]*(x - alpha[n]), And(alpha[n] <= x, x < alpha[n+1])))
        else:
            argtuples.append((cumsums[n] + p[n]*(x - alpha[n]), alpha[n]<=x))
        
        print(argtuples[n])

    t = Piecewise(*argtuples)
    return round(t.subs(x,AGI),2), t, argtuples

bracks17 = [0., 9325.00,37950.00,91900.00,191650.00,416700.00,418400.00]
perc17 = [0.10,0.15,0.25,0.28,.33,.35,.396]
ti = getFedTax(bracks17,perc17,450000.)
print('Tax owed: ', ti[0])
plot(ti[1],(x,0.,450000.))
```

In this code I have defined a Piecewise function to compute the Federal Income Tax and attempted to plot the result.  I know the piecewise function is giving me correct values because I have verified it against other tax calculators.

The output with traceback is:

```
runfile('C:/Users/galileo/Downloads/untitled0.py', wdir='C:/Users/galileo/Downloads')
This is the piecewise function you have created: 

(0.1*x, (x >= 0.0) & (x < 9325.0))
(0.15*x - 466.25, (x >= 9325.0) & (x < 37950.0))
(0.25*x - 4261.25, (x >= 37950.0) & (x < 91900.0))
(0.28*x - 7018.25, (x >= 91900.0) & (x < 191650.0))
(0.33*x - 16600.75, (x >= 191650.0) & (x < 416700.0))
(0.35*x - 24934.75, (x >= 416700.0) & (x < 418400.0))
(0.396*x - 44181.15, x >= 418400.0)
Tax owed:  134018.85
Traceback (most recent call last):

  File "<ipython-input-66-934e94216b63>", line 1, in <module>
    runfile('C:/Users/galileo/Downloads/untitled0.py', wdir='C:/Users/galileo/Downloads')

  File "c:\users\galileo\appdata\local\programs\python\python36\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "c:\users\galileo\appdata\local\programs\python\python36\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/galileo/Downloads/untitled0.py", line 37, in <module>
    plot(ti[1],(x,0.,450000.))

  File "c:\users\galileo\appdata\local\programs\python\python36\lib\site-packages\sympy\plotting\plot.py", line 1295, in plot
    plots.show()

  File "c:\users\galileo\appdata\local\programs\python\python36\lib\site-packages\sympy\plotting\plot.py", line 196, in show
    self._backend.show()

  File "c:\users\galileo\appdata\local\programs\python\python36\lib\site-packages\sympy\plotting\plot.py", line 1029, in show
    self.process_series()

  File "c:\users\galileo\appdata\local\programs\python\python36\lib\site-packages\sympy\plotting\plot.py", line 908, in process_series
    collection = self.LineCollection(s.get_segments())

  File "c:\users\galileo\appdata\local\programs\python\python36\lib\site-packages\sympy\plotting\plot.py", line 514, in get_segments
    f_start = f(self.start)

  File "c:\users\galileo\appdata\local\programs\python\python36\lib\site-packages\sympy\plotting\experimental_lambdify.py", line 231, in __call__
    result = self.lambda_func(args)

  File "c:\users\galileo\appdata\local\programs\python\python36\lib\site-packages\sympy\plotting\experimental_lambdify.py", line 316, in __call__
    return self.lambda_func(*args, **kwargs)

  File "<string>", line 1, in <lambda>

TypeError: '>=' not supported between instances of 'complex' and 'float'
```

**Comment by kangwonlee** [comment]
I also noticed similar problem.  Following code works on a Windows PC but not on a macOS.  `sympy` version = 1.0.

> import sympy as sy
> import sympy.plotting as splot
> 
> 
> def plot_numpy():
>     x = sy.Symbol('x', real=True)
>     y = sy.Piecewise((- x, x < 0), (x, x >= 0))
> 
>     splot.plot(y, (x, -5, 5))
> 
> 
> plot_numpy()

**Comment by normalhuman** [comment]
@kangwonlee @BananaOrbit Can you check whether the error still occurs in the current master branch of SymPy? I've submitted a pull request (#13826) but there is a doubt whether the bug still exists.

**Comment by BananaOrbit** [comment]
@normalhuman I am a Github noob. I have downloaded the GitHub for Windows GUI and I removed my pip version of SymPy. Then I cloned sympy in the GitHub for Windows, but when I try to import it in my python script it's not there. I normally just use the pip version of SymPy. I would be glad to test it if I can just figure out why SymPy is not importing.

**Comment by normalhuman** [comment]
@BananaOrbit If you clone SymPy into any directory, then it should be imported when you run python from that directory. Open a command line window, `cd` into the directory with SymPy and run python from there.

**Comment by BananaOrbit** [comment]
Thank you.

I ran the exact same code as in the original post. I think I might have had a programming error at the end because it gave me:
```PS C:\Users\galileo\Documents\GitHub\sympy> python untitled0.py
This is the piecewise function you have created:

(0.1*x, (x >= 0.0) & (x < 9325.0))
(0.15*x - 466.25, (x >= 9325.0) & (x < 37950.0))
(0.25*x - 4261.25, (x >= 37950.0) & (x < 91900.0))
(0.28*x - 7018.25, (x >= 91900.0) & (x < 191650.0))
(0.33*x - 16600.75, (x >= 191650.0) & (x < 416700.0))
(0.35*x - 24934.75, (x >= 416700.0) & (x < 418400.0))
(0.396*x - 44181.15, x >= 418400.0)
Tax owed:  134018.85
Traceback (most recent call last):
  File "untitled0.py", line 37, in <module>
    plot(ti[1],(x,0.,450000.))
NameError: name 'x' is not defined
```
So I added ``` x = symbols('x') ``` after the final print statement. Then I got:
```
PS C:\Users\galileo\Documents\GitHub\sympy> python untitled0.py
This is the piecewise function you have created:

(0.1*x, (x >= 0.0) & (x < 9325.0))
(0.15*x - 466.25, (x >= 9325.0) & (x < 37950.0))
(0.25*x - 4261.25, (x >= 37950.0) & (x < 91900.0))
(0.28*x - 7018.25, (x >= 91900.0) & (x < 191650.0))
(0.33*x - 16600.75, (x >= 191650.0) & (x < 416700.0))
(0.35*x - 24934.75, (x >= 416700.0) & (x < 418400.0))
(0.396*x - 44181.15, x >= 418400.0)
Tax owed:  134018.85
Traceback (most recent call last):
  File "C:\Users\galileo\Documents\GitHub\sympy\sympy\plotting\experimental_lambdify.py", line 194, in __call__
    result = complex(self.lambda_func(args))
  File "C:\Users\galileo\Documents\GitHub\sympy\sympy\plotting\experimental_lambdify.py", line 316, in __call__
    return self.lambda_func(*args, **kwargs)
  File "<string>", line 1, in <lambda>
TypeError: '>=' not supported between instances of 'complex' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "untitled0.py", line 38, in <module>
    plot(ti[1],(x,0.,450000.))
  File "C:\Users\galileo\Documents\GitHub\sympy\sympy\plotting\plot.py", line 1294, in plot
    plots.show()
  File "C:\Users\galileo\Documents\GitHub\sympy\sympy\plotting\plot.py", line 196, in show
    self._backend.show()
  File "C:\Users\galileo\Documents\GitHub\sympy\sympy\plotting\plot.py", line 1028, in show
    self.process_series()
  File "C:\Users\galileo\Documents\GitHub\sympy\sympy\plotting\plot.py", line 908, in process_series
    collection = self.LineCollection(s.get_segments())
  File "C:\Users\galileo\Documents\GitHub\sympy\sympy\plotting\plot.py", line 514, in get_segments
    f_start = f(self.start)
  File "C:\Users\galileo\Documents\GitHub\sympy\sympy\plotting\experimental_lambdify.py", line 231, in __call__
    result = self.lambda_func(args)
  File "C:\Users\galileo\Documents\GitHub\sympy\sympy\plotting\experimental_lambdify.py", line 316, in __call__
    return self.lambda_func(*args, **kwargs)
  File "<string>", line 1, in <lambda>
TypeError: '>=' not supported between instances of 'complex' and 'int'
```
