### ISSUE TITLE
solve(Eq(x, True)) raises error

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13349]
```
>>> solve(Eq(x, True))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/solvers/solvers.py", line 828, in solve
    f[i] = Add(fi.lhs, -fi.rhs, evaluate=False)
TypeError: bad operand type for unary -: 'BooleanTrue'

```

**Comment by ishanaj** [comment]
@smichr I think this issue is somewhat related to the issue #13348. The error won't show up if the the latter gets resolved as per PR #13391.
