### ISSUE TITLE
solveset() unable to solve -2*y*exp(-x**2 - y**2)*Abs(x)

### ISSUE THREAD

**Issue by parsoyaarihant** [sympy/sympy#13396]
```python
>>> from sympy.abc import x, y
>>> expr = -2*y*exp(-x**2 - y**2)*Abs(x)
>>> solveset(expr, y, domain=S.Reals)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/solvers/solveset.py", line 925, in solveset
    return _solveset(f, symbol, domain, _check=True)
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/solvers/solveset.py", line 699, in _solveset
    result = Union(*[solver(m, symbol) for m in f.args])
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/solvers/solveset.py", line 699, in <listcomp>
    result = Union(*[solver(m, symbol) for m in f.args])
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/solvers/solveset.py", line 678, in <lambda>
    solver = lambda f, x, domain=domain: _solveset(f, x, domain)
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/solvers/solveset.py", line 715, in _solveset
    lhs, rhs_s = inverter(f, 0, symbol)
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/solvers/solveset.py", line 683, in <lambda>
    inverter = lambda f, rhs, symbol: inverter_func(f, rhs, symbol, domain)
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/solvers/solveset.py", line 118, in invert_real
    return _invert(f_x, y, x, domain)
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/solvers/solveset.py", line 107, in _invert
    return x1, s.intersection(domain)
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/sets/sets.py", line 114, in intersection
    return self.intersect(other)
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/sets/sets.py", line 108, in intersect
    return Intersection(self, other)
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/sets/sets.py", line 1497, in __new__
    args = list(ordered(args, Set._infimum_key))
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/core/compatibility.py", line 608, in ordered
    d[f(a)].append(a)
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/sets/sets.py", line 58, in _infimum_key
    infimum = expr.inf
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/sets/sets.py", line 263, in inf
    return self._inf
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/sets/sets.py", line 2022, in _inf
    return Min(*self)
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/functions/elementary/miscellaneous.py", line 343, in __new__
    args = cls._find_localzeros(set(_args), **assumptions)
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/functions/elementary/miscellaneous.py", line 425, in _find_localzeros
    con = cls._is_connected(v, z)
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/functions/elementary/miscellaneous.py", line 447, in _is_connected
    r = hit(x >= y, Max, Min)
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/sympy-1.1.2.dev0-py3.6.egg/sympy/core/expr.py", line 255, in __ge__
    raise TypeError("Invalid comparison of complex %s" % me)
TypeError: Invalid comparison of complex sqrt(-x**2 + zoo)
```

**Comment by akash9712** [comment]
The latest version of the master branch appears to be working fine with this. It gave the following output:
```
>>> from sympy.abc import x, y
>>> expr = -2*y*exp(-x**2 - y**2)*Abs(x)
>>> solveset(expr, y, domain=S.Reals)
Union({0}, Intersection(S.Reals, {-sqrt(-x**2 + zoo), sqrt(-x**2 + zoo)}))
```

**Comment by oscarbenjamin** [comment]
@akash9712 is that the correct solution? I haven't spent any time thinking about this yet...

**Comment by akash9712** [comment]
@oscarbenjamin Although the first part of the answer, `{0}`  satisfies the equation, I am not sure about the values included in the intersection.
```
>>> from sympy import *
>>> from sympy.abc import x, y
>>> expr = -2*y*exp(-x**2 - y**2)*Abs(x)
>>> solveset(expr, y, domain=S.Reals)
Union({0}, Intersection(Reals, {-sqrt(-x**2 + zoo), sqrt(-x**2 + zoo)}))
>>> expr.xreplace({y:sqrt(-x**2 + zoo)})
nan
```
I think both LHS and RHS should evaluate to `zoo` on replacing `y` with `+\- sqrt(-x**2 + zoo)` for a finite and non-zero `x`.

**Comment by oscarbenjamin** [comment]
A simpler example:
```julia
In [28]: solveset(exp(x-y**2), y, domain=S.Reals)                                                                                 
Out[28]: 
    ⎧   _________    _________⎫
ℝ ∩ ⎨-╲╱ x + zoo , ╲╱ x + zoo ⎬
    ⎩                         ⎭

In [29]: x = Symbol('x', real=True)                                                                                               

In [30]: solveset(exp(x-y**2), y, domain=S.Reals)                                                                                 
Out[30]: 
    ⎧   _________    _________⎫
ℝ ∩ ⎨-╲╱ x + zoo , ╲╱ x + zoo ⎬
    ⎩                         ⎭
```

Actually it's clearly not right since we're solving over the reals so the solution should be a subset of the reals.

**Comment by oscargus** [comment]
But 
```
    ⎧   _________    _________⎫
ℝ ∩ ⎨-╲╱ x + zoo , ╲╱ x + zoo ⎬
    ⎩                         ⎭
```
will always to real, right? (As it is an intersection with Reals.)  Not sure if that is an empty intersection though...

**Comment by oscargus** [comment]
Mathematica returns {{y -> 0}, {y -> -I x}, {y -> I x}} for the original example.

**Comment by oscarbenjamin** [comment]
I don't know why I didn't spot before that this is a very simple equation. The equation is this:
```python
In [26]: expr
Out[26]: 
         2    2    
      - x  - y     
-2⋅y⋅ℯ         ⋅│x│
```
and we want to solve for `y`. The exponential function is nonzero for any complex argument so it can be factored out. Then the solution is `y=0` if the parameter `x` is not zero (and y = anything if x is zero).

How does Mathematica get `y -> I x` as a solution?
```python
In [27]: expr.subs(y, I*x)
Out[27]: -2⋅ⅈ⋅x⋅│x│
```
That's only a solution if `x` is zero in which case `y` can be anything.
