### ISSUE TITLE
encoding missing from physics/units/definitions?

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13444]
I get the following in 2.7 but not in Python 3.6:
```
Python 2.7.7 (default, Jun  1 2014, 14:17:13) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "\s\pythonstartup.py", line 18, in <module>
    from sympy.physics import units
  File "sympy\physics\__init__.py", line 5, in <module>
    from . import units
  File "sympy\physics\units\__init__.py", line 85, in <module>
    from .definitions import (
  File "sympy\physics\units\definitions.py", line 130
SyntaxError: Non-ASCII character '\xe2' in file sympy\physics\units\definitions.
py on line 130, but no encoding declared; see http://www.python.org/peps/pep-026
3.html for details
>>>
```

**Comment by jksuom** [comment]
There is  a utf-8 encoded EN DASH in stefan-boltzmann. It looks like  `â <80> <93>`  as latin1 characters.
