### ISSUE TITLE
(cos(x) > 0).subs(x, oo) ->SympifyError

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13499]
```
>>> (cos(x)>0).subs(x,oo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\core\basic.py", line 918, in subs
    rv = rv._subs(old, new, **kwargs)
  File "sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy\core\compatibility.py", line 809, in wrapper
    result = user_function(*args, **kwds)
  File "sympy\core\basic.py", line 1032, in _subs
    rv = fallback(self, old, new)
  File "sympy\core\basic.py", line 1009, in fallback
    rv = self.func(*args)
  File "sympy\core\relational.py", line 490, in __new__
    r = cls._eval_relation(lhs, rhs)
  File "sympy\core\relational.py", line 798, in _eval_relation
    return _sympify(lhs.__gt__(rhs))  <--------------------- lhs, rhs here is AccumBounds(-1, 1), 0
  File "sympy\core\sympify.py", line 396, in _sympify
    return sympify(a, strict=True)
  File "sympy\core\sympify.py", line 276, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: None
```

Perhaps related to #13159 (?)

**Comment by asmeurer** [comment]
`>` shouldn't be using op_priority. It looks like `cos(oo) > 0` just gives None

```
>>> cos(oo)
AccumBounds(-1, 1)
>>> print(cos(oo) > 0)
None
```

**Comment by asmeurer** [comment]
Looks like `AccumBounds.__lt__` etc. incorrectly return None in some cases. They should be falling back to the `__lt__` of the super class, which would create an Lt object.
