### ISSUE TITLE
Python code printer (pycode) should support Assignment

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#13598]
There is a lookup on 'contract', either we should give it a default in the `PythonCodePrinter` or we should make the code accessing `_settings` use `.get` with a default.

```
In [3]: from sympy.printing.pycode import pycode

In [4]: from sympy.codegen.ast import Assignment

In [5]: pycode(Assignment(x, 3))
KeyError
...
/home/bjorn/vc/sympy/sympy/printing/codeprinter.pyc in _print_Assignment(self, expr)
    309                 lines.append(code0)
    310             return "\n".join(lines)
--> 311         elif self._settings["contract"] and (lhs.has(IndexedBase) or
    312                 rhs.has(IndexedBase)):
    313             # Here we check if there is looping to be done, and if so

KeyError: 'contract'
```

**Comment by matveich** [comment]
Hi @bjodah! I'd like to make my first contribution. Can I work on this issue?

**Comment by bjodah** [comment]
Sure! You can have a look here for how to get started: https://github.com/sympy/sympy/wiki/Development-workflow

**Comment by amitmanchanda1995** [comment]
Hi @bjodah !
As you stated, I made the code accessing `_settings` use `.get` with a default `False`.
But now I am getting some other error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/printing/pycode.py", line 187, in pycode
    return PythonCodePrinter(settings).doprint(expr)
  File "sympy/printing/codeprinter.py", line 100, in doprint
    lines = self._print(expr).splitlines()
  File "sympy/printing/printer.py", line 257, in _print
    return getattr(self, printmethod)(expr, *args, **kwargs)
  File "sympy/printing/codeprinter.py", line 319, in _print_Assignment
    return self._get_statement("%s = %s" % (lhs_code, rhs_code))
  File "sympy/printing/codeprinter.py", line 250, in _get_statement
    raise NotImplementedError("This function must be implemented by "
NotImplementedError: This function must be implemented by subclass of CodePrinter.
```
Can you guide me in solving it?
