### ISSUE TITLE
integrate(x**2*sqrt(1-x**2), (x, -1, 1)) raises AttributeError with SymPy 1.1.1

### ISSUE THREAD

**Issue by jdolence** [sympy/sympy#13696]
```
>>> integrate(x**2*sqrt(1-x**2), (x, -1, 1))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sympy/integrals/integrals.py", line 1295, in integrate
    risch=risch, manual=manual)
  File "/usr/lib/python3/dist-packages/sympy/integrals/integrals.py", line 553, in doit
    evalued = Add(*others)._eval_interval(x, a, b)
  File "/usr/lib/python3/dist-packages/sympy/functions/elementary/piecewise.py", line 272, in _eval_interval
    int_expr = self._sort_expr_cond(sym, a, b)
  File "/usr/lib/python3/dist-packages/sympy/functions/elementary/piecewise.py", line 343, in _sort_expr_cond
    lower, upper = cond.lts, cond.gts  # part 1: initialize with givens
AttributeError: 'Or' object has no attribute 'lts'
```

**Comment by certik** [comment]
This works in the latest master:
```
In [1]: integrate(x**2*sqrt(1-x**2), (x, -1, 1))
Out[1]: 
π
─
8
```
Let me find out if this is an accident, or if it got fixed since SymPy 1.1.1.

**Comment by certik** [comment]
So this got fixed by 1c658e00ffa5cec777dd2d9f9453135ab55e75d0.

**Comment by certik** [comment]
@jdolence use the latest master for now, where this is fixed. We'll make a release eventually.

**Comment by certik** [comment]
Thanks @smichr for fixing this!
