### ISSUE TITLE
Live Shell throws a Value Error while running a live example

### ISSUE THREAD

**Issue by yashkgp** [sympy/sympy#13697]
Live Shell is throwing a Value Error while running a  code from the Physics.Vector module in the documentation. the code block was : 
```python
>>> from sympy import symbols
>>> from sympy.physics.vector import ReferenceFrame
>>> from sympy.physics.mechanics.functions import inertia
>>> a, b, c = symbols('a, b, c')
>>> N = ReferenceFrame('N')
>>> vector = a * N.x + b * N.y + c * N.z
>>> vector.to_matrix(N)
```
Its giving a Value error 
```
Exception in SymPy Live of type 
<type 'exceptions.ValueError'> 
for reference the last 5 stack trace entries are 
Traceback (most recent call last): 
File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/shell.py", line 781, in post live.evaluate(statement, session, printer, stream) 
File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/shell.py", line 453, in evaluate if name not in old_globals or val != old_globals[name]: 
File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/physics/vector/vector.py", line 171, in __ne__ return not self.__eq__(other)
 File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/physics/vector/vector.py", line 139, in __eq__ if expand((self - other) & v) != 0: 
File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/physics/vector/vector.py", line 105, in __and__ * (v1[0]))[0] 
ValueError: No Connecting Path found between N and N
```
While locally its running fine .

**Comment by harsh-98** [comment]
@yashkgp what u mean by live shell?

**Comment by ylemkimon** [comment]
Live Shell is running SymPy 1.0, which is about 6000 commits old. There is an open issue to upgrade it to latest version: https://github.com/sympy/sympy-live/issues/112. As it works in the development version, I'll close this issue. Thank you for reporting.

@harsh-98 http://live.sympy.org/
