### ISSUE TITLE
limit(gamma(n + p) / (n**p * gamma(n)), n, oo) fails for real p, but succeeds when p is positive, negative or zero

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#13701]
p = Symbol('p', real=True)
    print(limit(gamma(n + p) / (n**p * gamma(n)), n, oo))
    Traceback (most recent call last):
      File "C:\Users\ethan\Desktop\sympy\sympy\series\limits.py", line 190, in doit
        r = gruntz(e, z, z0, dir)
      File "C:\Users\ethan\Desktop\sympy\sympy\series\gruntz.py", line 646, in gruntz
        r = limitinf(e, z)
      File "C:\Users\ethan\Desktop\sympy\sympy\core\cache.py", line 93, in wrapper
        retval = cfunc(*args, **kwargs)
      File "C:\Users\ethan\Desktop\sympy\sympy\series\gruntz.py", line 427, in limitinf
        c0, e0 = mrv_leadterm(e, x)
      File "C:\Users\ethan\Desktop\sympy\sympy\core\cache.py", line 93, in wrapper
        retval = cfunc(*args, **kwargs)
      File "C:\Users\ethan\Desktop\sympy\sympy\series\gruntz.py", line 510, in mrv_leadterm
        f, logw = rewrite(exps, Omega, x, w)
      File "C:\Users\ethan\Desktop\sympy\sympy\series\gruntz.py", line 582, in rewrite
        raise NotImplementedError('Result depends on the sign of %s' % sig)
    NotImplementedError: Result depends on the sign of sign(p)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:/Users/ethan/Desktop/sympy/test.py", line 11, in <module>
        print(limit(gamma(n + p) / (n**p * gamma(n)), n, oo))
      File "C:\Users\ethan\Desktop\sympy\sympy\series\limits.py", line 50, in limit
        return Limit(e, z, z0, dir).doit(deep=False)
      File "C:\Users\ethan\Desktop\sympy\sympy\series\limits.py", line 203, in doit
        raise NotImplementedError()
    NotImplementedError

    p = Symbol('p', positive=True)
    print(limit(gamma(n + p) / (n**p * gamma(n)), n, oo))
    1

    p = Symbol('p', negative=True)
    print(limit(gamma(n + p) / (n**p * gamma(n)), n, oo))
    1

    p = S(0)
    print(limit(gamma(n + p) / (n**p * gamma(n)), n, oo))
    1

(In fact this limit is 1 for all complex p, but fixing the algorithm for the real case first might be easier).

**Comment by vishalg2235** [comment]
I would like to work on this issue. @ethankward can you guide me which file code I must look into? 
From error log I think `rewrite` function must be edited.

**Comment by Subhash-Saurabh** [comment]
I don't think the problem is due to `p` being real.
```
>>> p = Symbol('p', real=True, positive=True)
>>> print(limit(gamma(n + p) / (n**p * gamma(n)), n, oo))
1
```
The real problem is with sign function in gruntz.py that is unable to evaluate if the sign of `p` (postive,negative or zero) is not provided.
For example 
```
>>> p = Symbol('p', Integer=True)
>>> print(limit(gamma(n + p) / (n**p * gamma(n)), n, oo))
```
gives NotImplementedError
