### ISSUE TITLE
import filldedent in line.py

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13705]
The following should raise a ValueError:
```
>>> Line((x,1),(2,3)).arbitrary_point(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\geometry\line.py", line 236, in arbitrary_point
    raise ValueError(filldedent('''
NameError: global name 'filldedent' is not defined
```
The following mod to line.py should be made and a test of the above added to the place where `arbitrary_point` is tested in the `test_line.py` file.

```diff
diff --git a/sympy/geometry/line.py b/sympy/geometry/line.py
index a542ddb..8ac0dc8 100644
--- a/sympy/geometry/line.py
+++ b/sympy/geometry/line.py
@@ -33,7 +33,7 @@

 from .entity import GeometryEntity, GeometrySet
 from .point import Point, Point3D
-from sympy.utilities.misc import Undecidable
+from sympy.utilities.misc import Undecidable, filldedent


 class LinearEntity(GeometrySet):
```

**Comment by scheswick2015** [comment]
@smichr I would like to work on this issue. I have looked into the arbitrary_point tests and was wondering what would be the best way to write a test for the ValueError, since that error is raised in the arbitrary_point method in the line.py file as shown below
```
if t.name in (f.name for f in self.free_symbols):
            raise ValueError(filldedent('''
                Symbol %s already appears in object
                and cannot be used as a parameter.
                ''' % t.name))
```
