### ISSUE TITLE
lambdify can't handle substituting functions and their derivatives simultaneously

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#13753]
It would be nice if this didn't fail:

```
moorepants@garuda:~$ ipython
Python 3.5.4 | packaged by conda-forge | (default, Dec  9 2017, 16:18:50) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sympy as sm

In [2]: t = sm.symbols('t')

In [3]: f = sm.Function('f')(t)

In [4]: expr = f + f.diff()

In [5]: eval_expr = sm.lambdify((f, f.diff()), expr)
Traceback (most recent call last):

  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-5-423c76f9ef3a>", line 1, in <module>
    eval_expr = sm.lambdify((f, f.diff()), expr)

  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/sympy/utilities/lambdify.py", line 434, in lambdify
    func = eval(lstr, namespace)

  File "<string>", line 1
    lambda _Dummy_19,Derivative(f(t), t): (Derivative(_Dummy_19, t) + _Dummy_19)
                               ^
SyntaxError: invalid syntax


In [6]: eval_expr = sm.lambdify((f.diff(), f), expr)
Traceback (most recent call last):

  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-6-7cf46a1a2b77>", line 1, in <module>
    eval_expr = sm.lambdify((f.diff(), f), expr)

  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/sympy/utilities/lambdify.py", line 434, in lambdify
    func = eval(lstr, namespace)

  File "<string>", line 1
    lambda Derivative(f(t), t),_Dummy_20: (Derivative(_Dummy_20, t) + _Dummy_20)
                     ^
SyntaxError: invalid syntax
```

I think this has to do with the order that the dummies are substituted in. If `subs` is used there may be no guarantee that the order of the args passed to `lambdify` is preserved.

**Comment by ArighnaIITG** [comment]
I would like to this work on this issue.
Could you guide me as to which dummies should I change, and how should I proceed on with this issue?

**Comment by moorepants** [comment]
You should start by writing a unit test based on what I have written above. Then you need to find the code in lambdify that does the dummy substitution and modify it so that it subs in the highest order derivatives first. This should be robust for any order derivatives.

**Comment by ArighnaIITG** [comment]
I have looked at the code.
In lambdastr function, I will put an isinstance check to see if the args term contain derivatives or not.
But how do I sort the derivatives list according to their order?
@moorepants

**Comment by moorepants** [comment]
I'm sorry, I don't have time to help you with every detail. Please try something and submit a pull request.

**Comment by ac9888185875** [comment]
Can I work on this issue if it isn't yet resolved?..And if possible give me some inputs over it as I am a beginner.

**Comment by ac9888185875** [comment]
I am not able to make a pull request to this issue.It's showing a remote error on running the command: git push origin master.
What I should do?

**Comment by czgdp1807** [comment]
```python
Python console for SymPy 1.6.dev (Python 2.7.15-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/dev

Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(SymPyConsole)
>>> import sympy as sm
>>> t = sm.symbols('t')
>>> f = sm.Function('f')(t)
>>> expr = f + f.diff()
>>> eval_expr = sm.lambdify((f, f.diff()), expr)
>>> eval_expr
<function _lambdifygenerated at 0x7f4c406c9230>
>>> eval_expr = sm.lambdify((f.diff(), f), expr)
>>> eval_expr
<function _lambdifygenerated at 0x7f4c406c95f0>
>>> eval_expr(0, 1)
1
>>> eval_expr(0, 2)
2
>>> eval_expr(1, 2)
3
```

It looks like the issue has been resolved in current master. ping @moorepants

**Comment by czgdp1807** [comment]
Closing in reference to https://github.com/sympy/sympy/issues/13753#issuecomment-557864575
If someone wants to get it re-opened please comment below. Thanks.
