### ISSUE TITLE
how to use "rs_series" to get the correct result for multivariate expressions

### ISSUE THREAD

**Issue by linspirit** [sympy/sympy#13933]
I wrote the following code:
from sympy import *
from sympy.polys.ring_series import rs_series
lambda_, t, x =symbols(lambda_, t,x)
rs_series(-lambda_**2*x**3*exp(t) - lambda_**2*x**3*exp(-t), lambda_, 4)
but I can the following result:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\opt\Python27\lib\site-packages\sympy\polys\ring_series.py", line 1984, in rs_series
    series = _rs_series(expr, series, a, prec)
  File "C:\opt\Python27\lib\site-packages\sympy\polys\ring_series.py", line 1926, in _rs_series
    _series = _rs_series(args[i], R(args[i]), a, prec)
  File "C:\opt\Python27\lib\site-packages\sympy\polys\rings.py", line 339, in ring_new
    return self.from_expr(element)
  File "C:\opt\Python27\lib\site-packages\sympy\polys\rings.py", line 387, in from_expr
    raise ValueError("expected an expression convertible to a polynomial in %s, got %s" % (self, expr))
ValueError: expected an expression convertible to a polynomial in Polynomial ring in x, exp(t), lambda_ over QQ with lex order, got -lambda_**2*x**3*exp(-t)

How can I get the correct result ?

**Comment by normalhuman** [comment]
Please use triple backticks before and after the code block to get it formatted. Hard to read when asterisks turn into bold.

**Comment by linspirit** [comment]
Thank you very much.
Using function rs_series has two reasons. Firstly,  the rs_series  is faster than series. Secondly, I donot need O(t**) for the example -2*lambda_**2*x**3 - lambda_**2*t**2*x**3 + O(t**4).

**Comment by normalhuman** [comment]
Please use code formatting (single backticks for inline code, triple backtickes for multiline code blocks). 

Please clarify if you want expansion in terms of lambda_, as originally stated, or in terms of t.

**Comment by normalhuman** [comment]
If you don't need O you can remove it with `removeO`:
```
series(-lambda_**2 * x**3 * exp(t) - lambda_**2 * x**3 * exp(-t), t, 0, 4).removeO()
```
returns `-lambda_**2*t**2*x**3 - 2*lambda_**2*x**3`. 

Yes, `rs_series` is much faster but it is also much more limited in scope at present.

**Comment by linspirit** [comment]
Thank you!!!
