### ISSUE TITLE
integrate(log(x)*(1-x)**(-1), (x, 0, 1)) causes an error

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14075]
The integral evaluates to `-pi**2/6`

I am surprised by this because `integrate(log(x)*(1+x)**(-2), (x, 0, 1))` is correctly evaluated

`>>> integrate(log(x)*(1-x)**(-1), (x, 0, 1))`
Traceback (most recent call last):

  File "<ipython-input-5-ba95d81624e1>", line 1, in <module>
    integrate(log(x)*(1-x)**(-1), (x, 0, 1))

  File "C:\Users\Roland\Anaconda3\lib\site-packages\sympy\integrals\integrals.py", line 1295, in integrate
    risch=risch, manual=manual)

  File "C:\Users\Roland\Anaconda3\lib\site-packages\sympy\integrals\integrals.py", line 553, in doit
    evalued = Add(*others)._eval_interval(x, a, b)

  File "C:\Users\Roland\Anaconda3\lib\site-packages\sympy\core\expr.py", line 815, in _eval_interval
    if B.has(S.NaN, S.Infinity, S.NegativeInfinity, S.ComplexInfinity):

AttributeError: 'int' object has no attribute 'has'

**Comment by normalhuman** [comment]
In the current master branch, I get 
```
>>> integrate(log(x)*(1-x)**(-1), (x, 0, 1))
-polylog(2, -exp_polar(I*pi))
```
which still needs a bit of improvement (apparently #13965 did not go far enough in un-polarifying polylog), but is correct: `-polylog(2, 1)` is the answer.
