### ISSUE TITLE
TypeError for triple integral of 1/(1+x+y+z)**2

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14096]
```
var('x y z')
integrate(1/(1 + x + y + z)**2, (x, 0, 1), (y, 0, 1), (z, 0, 1))
```
throws
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/sympy/sympy/integrals/integrals.py", line 1364, in integrate
    risch=risch, manual=manual)
  File "/home/ubuntu/sympy/sympy/integrals/integrals.py", line 595, in doit
    evalued = Add(*others)._eval_interval(x, a, b)
  File "/home/ubuntu/sympy/sympy/core/expr.py", line 866, in _eval_interval
    if a < s < b:
  File "/home/ubuntu/sympy/sympy/core/numbers.py", line 2147, in __lt__
    return Rational.__lt__(self, other)
  File "/home/ubuntu/sympy/sympy/core/numbers.py", line 1805, in __lt__
    return Expr.__lt__(expr, other)
  File "/home/ubuntu/sympy/sympy/core/expr.py", line 341, in __lt__
    dif = self - other
  File "/home/ubuntu/sympy/sympy/core/numbers.py", line 2071, in __sub__
    return Rational.__sub__(self, other)
  File "/home/ubuntu/sympy/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/home/ubuntu/sympy/sympy/core/numbers.py", line 1595, in __sub__
    return Number.__sub__(self, other)
  File "/home/ubuntu/sympy/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/home/ubuntu/sympy/sympy/core/numbers.py", line 653, in __sub__
    return AtomicExpr.__sub__(self, other)
  File "/home/ubuntu/sympy/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/home/ubuntu/sympy/sympy/core/decorators.py", line 132, in binary_op_wrapper
    return func(self, other)
  File "/home/ubuntu/sympy/sympy/core/expr.py", line 130, in __sub__
    return Add(self, -other)
TypeError: bad operand type for unary -: 'And'
```

**Comment by ethankward** [comment]
Simpler example: `integrate(1/(x + y)**2, (x, 0, 1))`.

**Comment by ethankward** [comment]
The main problem seems to be on line 864 in expr.py: solveset generates a singularity that is an `And` object that cannot be compared with `a` and `b` on line 866.

```
>>> a, b = S(0), S(1)
>>> s = And(-y >= 0, -y <= 1)
>>> print(a < s < b)
...
TypeError: bad operand type for unary -: 'And'
```

**Comment by normalhuman** [comment]
Yes, I've created this issue in the process of fixing it (as it came up when I was fixing another one). Thanks for the simpler example.
