### ISSUE TITLE
ValueError in Sum((-1)**(2*n)/n, (n, 1, oo)).is_convergent()

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14152]
```
var('n')
Sum((-1)**(2*n)/n, (n, 1, oo)).is_convergent()
```
results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lvk/sympy/sympy/concrete/summations.py", line 489, in is_convergent
    maxima = solveset(sequence_term.diff(sym), sym, interval)
  File "/home/lvk/sympy/sympy/solvers/solveset.py", line 947, in solveset
    return _solveset(f, symbol, domain, _check=True)
  File "/home/lvk/sympy/sympy/solvers/solveset.py", line 763, in _solveset
    result += _solve_as_rational(equation, symbol, domain)
  File "/home/lvk/sympy/sympy/solvers/solveset.py", line 409, in _solve_as_rational
    valid_solns = _solveset(g, symbol, domain)
  File "/home/lvk/sympy/sympy/solvers/solveset.py", line 717, in _solveset
    result = Union(*[solver(m, symbol) for m in f.args])
  File "/home/lvk/sympy/sympy/solvers/solveset.py", line 717, in <listcomp>
    result = Union(*[solver(m, symbol) for m in f.args])
  File "/home/lvk/sympy/sympy/solvers/solveset.py", line 696, in <lambda>
    solver = lambda f, x, domain=domain: _solveset(f, x, domain)
  File "/home/lvk/sympy/sympy/solvers/solveset.py", line 736, in _solveset
    lhs, rhs_s = inverter(f, 0, symbol)
  File "/home/lvk/sympy/sympy/solvers/solveset.py", line 701, in <lambda>
    inverter = lambda f, rhs, symbol: inverter_func(f, rhs, symbol, domain)
  File "/home/lvk/sympy/sympy/solvers/solveset.py", line 122, in invert_real
    return _invert(f_x, y, x, domain)
  File "/home/lvk/sympy/sympy/solvers/solveset.py", line 104, in _invert
    x1, s = _invert_real(f_x, FiniteSet(y), x)
  File "/home/lvk/sympy/sympy/solvers/solveset.py", line 201, in _invert_real
    s, b = integer_log(rhs, base)
  File "/home/lvk/sympy/sympy/core/power.py", line 130, in integer_log
    raise ValueError('y cannot take value as 0')
ValueError: y cannot take value as 0
```

**Comment by Roland-Sands** [comment]
I'm confident I could find a large number of cases where .is_convergent() breaks down, I'm holding myself back

**Comment by gxyd** [comment]
Wouldn't this be fixed after https://github.com/sympy/sympy/issues/14112#issuecomment-364176502  is implemented?

**Comment by normalhuman** [comment]
Indeed, I tested in the branch of #14158 and got correct result (False) instead of the this error.
