### ISSUE TITLE
integrate((1 - x**4)**(-1/3), (x, 0, 1))  causes an error

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14154]
```
>>> pprint(integrate((1 - x**4)**(Rational(-1,3)), (x, 0, 1)))
        ┌─  ⎛1/4, 1/3 │  2⋅ⅈ⋅π⎞
Γ(1/4)⋅ ├─  ⎜         │ ℯ     ⎟
       2╵ 1 ⎝  5/4    │       ⎠
───────────────────────────────
            4⋅Γ(5/4)           
>>> integrate((1 - x**4)**(-1/3), (x, 0, 1))
Traceback (most recent call last):

  File "<ipython-input-13-ffd13c2a1df3>", line 1, in <module>
    integrate((1 - x**4)**(-1/3), (x, 0, 1))

  File ".\sympy\integrals\integrals.py", line 1295, in integrate
    risch=risch, manual=manual)

  File ".\sympy\integrals\integrals.py", line 486, in doit
    conds=conds)

  File ".\sympy\integrals\integrals.py", line 908, in _eval_integral
    h = meijerint_indefinite(g, x)

  File ".\sympy\integrals\meijerint.py", line 1612, in meijerint_indefinite
    res = _meijerint_indefinite_1(f.subs(x, x + a), x)

  File ".\sympy\integrals\meijerint.py", line 1637, in _meijerint_indefinite_1
    gs = _rewrite1(f, x)

  File ".\sympy\integrals\meijerint.py", line 1560, in _rewrite1
    g = _rewrite_single(g, x, recursive)

  File ".\sympy\integrals\meijerint.py", line 1463, in _rewrite_single
    exponents_only=True), x)

  File ".\sympy\integrals\meijerint.py", line 335, in _get_coeff_exp
    raise _CoeffExpValueError('expr not of form a*x**b: %s' % expr)

_CoeffExpValueError: expr not of form a*x**b: 0.373282173907395
```

**Comment by oscargus** [comment]
Problem is that `-1/3` will evaluate to a float before reaching SymPy, as opposed to `Rational(-1, 3)` (or `-S(1)/3`).
