### ISSUE TITLE
Geometry module refers to defunct pygletplot

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14168]
The documentation of [ellipses](http://docs.sympy.org/dev/modules/geometry/ellipses.html) offers this example of "Plotting:" 
```
>>> from sympy.plotting.pygletplot import PygletPlot as Plot
>>> from sympy import Circle, Segment
>>> c1 = Circle(Point(0,0), 1)
>>> Plot(c1)                                
[0]: cos(t), sin(t), 'mode=parametric'
>>> p = Plot()                              
>>> p[0] = c1                               
>>> radius = Segment(c1.center, c1.random_point())
>>> p[1] = radius                           
>>> p                                       
[0]: cos(t), sin(t), 'mode=parametric'
[1]: t*cos(1.546086215036205357975518382),
t*sin(1.546086215036205357975518382), 'mode=parametric'
```

Does any of this work? Not under Python 3 for sure. I don't have a suitable 2.7 environment with pyglet to test, but reading the issues about pygletplot suggests it's not something that is likely to work.

**Comment by Abogical** [comment]
Not sure if I did something wrong here, but you're right. It doesn't work.

``` 
Python 2.7.14 (default, Oct 12 2017, 15:50:02) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy.plotting.pygletplot import PygletPlot as Plot
>>> from sympy import Circle, Segment, Point
>>> c1 = Circle(Point(0,0), 1)
>>> Plot(c1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/sympy/plotting/pygletplot/__init__.py", line 140, in PygletPlot
    return plot.PygletPlot(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sympy/plotting/pygletplot/plot.py", line 242, in __init__
    self[0] = fargs
  File "/usr/lib/python2.7/site-packages/sympy/plotting/pygletplot/plot.py", line 319, in __setitem__
    f = PlotMode(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sympy/plotting/pygletplot/plot_mode.py", line 78, in __new__
    subcls = PlotMode._get_mode(mode_arg, i, d)
  File "/usr/lib/python2.7/site-packages/sympy/plotting/pygletplot/plot_mode.py", line 156, in _get_mode
    return PlotMode._get_default_mode(i, d)
  File "/usr/lib/python2.7/site-packages/sympy/plotting/pygletplot/plot_mode.py", line 170, in _get_default_mode
    return PlotMode._mode_default_map[d][i]
KeyError: 1
>>> 
```
