### ISSUE TITLE
Sum doesn't work for matrices

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14189]
```
>>> a = diag(1, -2, 3)
⎡1  0   0⎤
⎢        ⎥
⎢0  -2  0⎥
⎢        ⎥
⎣0  0   3⎦
>>> Sum(a**k, (k, 0, 4))
  4                  
______               
╲                    
 ╲     ⎡1    0    0 ⎤
  ╲    ⎢            ⎥
   ╲   ⎢       k    ⎥
    ╲  ⎢0  (-2)   0 ⎥
    ╱  ⎢            ⎥
   ╱   ⎢           k⎥
  ╱    ⎣0    0    3 ⎦
 ╱                   
╱                    
‾‾‾‾‾‾               
k = 0                
>>> Sum(a**k/factorial(k), (k, 0, oo))
    ∞                    
_________                
╲                        
 ╲        ⎡1            ⎤
  ╲       ⎢──    0    0 ⎥
   ╲      ⎢k!           ⎥
    ╲     ⎢             ⎥
     ╲    ⎢        k    ⎥
      ╲   ⎢    (-2)     ⎥
       ╲  ⎢0   ─────  0 ⎥
       ╱  ⎢      k!     ⎥
      ╱   ⎢             ⎥
     ╱    ⎢            k⎥
    ╱     ⎢           3 ⎥
   ╱      ⎢0     0    ──⎥
  ╱       ⎣           k!⎦
 ╱                       
╱                        
‾‾‾‾‾‾‾‾‾                
  k = 0                  
```

**Comment by Abogical** [comment]
You'll need to use the `doit()` method.
http://docs.sympy.org/0.7.6/modules/concrete.html?highlight=sum#sympy.concrete.summations.Sum

**Comment by Roland-Sands** [comment]
Thanks, I keep getting that wrong
The inconsistency with sums and integrals doesn't help

**Comment by Abogical** [comment]
Actually it is consistent, it's just that there is a difference between `Sum` and `sum`, `Integrate` and `integrate`, etc. Capital letters signify objects and doesn't evaluate the expression immediately, while the others are simply functions and does evaluate immediately.

**Comment by Roland-Sands** [comment]
```
>>> integrate(x**2, (x, 1, 10))
333
>>> Sum(k**2, (k, 1, 10)).doit()
385
>>> sum(k**2, (k, 1, 10))
Traceback (most recent call last):

  File "<ipython-input-15-e8b353c008c1>", line 1, in <module>
    sum(k**2, (k, 1, 10))

TypeError: 'Pow' object is not iterable
>>> sum(k, (k, 1, 10))
Traceback (most recent call last):

  File "<ipython-input-18-30a24b5504be>", line 1, in <module>
    sum(k, (k, 1, 10))

TypeError: 'Symbol' object is not iterable
```
`sum` and `integrate` don't seem the same to me

**Comment by Abogical** [comment]
Oh sorry, looks like this uses `sum` from the python library. I don't think there is a direct function like `integrate` for sums.
