### ISSUE TITLE
limit_seq(Sum(m**k, (m, 1, n))/(n**(k + 1)))  causes an error

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14196]
```
>>> k, n  = symbols('k, n', positive=True, integer=True)
>>> limit_seq(Sum(m**k, (m, 1, n))/(n**(k + 1)))
Traceback (most recent call last):

  File "<ipython-input-28-bf836c3bee11>", line 1, in <module>
    limit_seq(Sum(m**k, (m, 1, n))/(n**(k + 1)))

  File ".\sympy\series\limitseq.py", line 164, in limit_seq
    "specify a variable." % (expr))

ValueError: expr n**(-k - 1)*Sum(m**k, (m, 1, n)) has more than one variables. Pleasespecify a variable.
>>> limit_seq(Sum(m**k, (m, 1, n)).doit()/(n**(k + 1)))
Traceback (most recent call last):

  File "<ipython-input-35-4af6baaf1e8b>", line 1, in <module>
    limit_seq(Sum(m**k, (m, 1, n)).doit()/(n**(k + 1)))

  File ".\sympy\series\limitseq.py", line 164, in limit_seq
    "specify a variable." % (expr))

ValueError: expr n**(-k - 1)*Sum(m**k, (m, 1, n)) has more than one variables. Pleasespecify a variable.
```

The limit is 
```
  1  
─────
k + 1
```
Also, in the error message, "Pleasespecify" is a typo

**Comment by normalhuman** [comment]
Yes, there is a typo. But don't you think that the error message has a point? You didn't tell SymPy if n tends to infinity or k tends to infinity.

**Comment by Roland-Sands** [comment]
> You didn't tell SymPy if n tends to infinity or k tends to infinity

You're right

There is no error message, it returns the wrong value though

```
>>> k, n  = symbols('k, n', positive=True, integer=True)
>>> limit_seq(Sum(m**k, (m, 1, n)).doit()/(n**(k + 1)), n)
0
```
