### ISSUE TITLE
apart(1/(x**n + 1), x, full=True).doit()  causes an error

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14214]
```
>>> n  = symbols('n', positive=True, integer=True)
>>> apart(1/(x**n + 1), x, full=True).doit()
Traceback (most recent call last):

  File "<ipython-input-35-8b6f4d6cfef1>", line 1, in <module>
    apart(1/(x**n + 1), x, full=True).doit()

  File ".\sympy\utilities\decorator.py", line 37, in threaded_func
    return func(expr, *args, **kwargs)

  File ".\sympy\polys\partfrac.py", line 86, in apart
    raise PolynomialError(msg)

PolynomialError: x**n contains an element of the generators set
```
Also, I think "contains an element of the generators set" is a typo
I think it should be "contains an element of the generating set" or "contains an element of the set of generators"

```
>>> apart(1/((x + a)*(x + b)), x)
       1                 1       
─────────────── - ───────────────
(a - b)⋅(b + x)   (a - b)⋅(a + x)
```
Should this be a piecewise thing, depending on whether or not a = b

**Comment by ArighnaIITG** [comment]
Great, I am fixing the typo, and then will proceed with the main part of the issue.

**Comment by jksuom** [comment]
`apart` is intended for rational expressions. `PolynomialError` essentially says that the input expression is not a rational expression of the generator `x` as `n` does not denote a nonnegative integer. (Instead, it denotes a symbol.)

**Comment by Roland-Sands** [comment]
@jksuom I think it would be beneficial if it held for arbitrary positive integers
I have definitely seen some interesting mathematics resulting from splitting expressions similar to the one in the title
