### ISSUE TITLE
Bugs in minimal polynomial and evalf

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14227]
```
>>> f = minimal_polynomial(1/(2**(Rational(1,3)) + 2**(Rational(1,4))), x)
>>> y = f.subs(x, 2**(Rational(1,3)) + 2**(Rational(1,4)))
-556747 - 509616*2**(1/12) - 271224*2**(11/12) - 451848*2**(1/6) - 362800*2**(1/4) - 208200*2**(5/6) - 222252*2**(1/3) - 111688*2**(3/4) - 77952*2**(5/12) - 27648*2**(2/3) + 6576*sqrt(2) + 17184*2**(7/12)
>>> y.evalf(f)
Traceback (most recent call last):

  File "<ipython-input-28-234f3644a2c6>", line 1, in <module>
    y.evalf(f)

  File ".\sympy\core\evalf.py", line 1386, in evalf
    prec = dps_to_prec(n)

  File ".\mpmath\libmp\libmpf.py", line 67, in dps_to_prec
    return max(1, int(round((int(n)+1)*3.3219280948873626)))

  File ".\sympy\core\expr.py", line 207, in __int__
    raise TypeError("can't convert symbols to int")

TypeError: can't convert symbols to int
```
It looks to me that `f` is not the minimal polynomial

Yes, `f` can't be the minimal polynomial, the surds are independent

**Comment by Roland-Sands** [comment]
I don't know if this effects #14069 and #14088, the bug may not effect that computation

**Comment by asmeurer** [comment]
The argument to evalf should be the number of digits to evaluate to, not an expression.

**Comment by asmeurer** [comment]
You're also substituting a different expression (the redundant parentheses don't help, but you start with `1/(2**(1/3) + 2**(1/4))` and substitute `2**(1/3) + 2**(1/4)`. If you substitute the original, you get 0:

```py
>>> f.subs(x, 1/(2**(Rational(1,3)) + 2**(Rational(1,4))))
-8/(2**(1/4) + 2**(1/3))**3 - 192/(2**(1/4) + 2**(1/3))**7 - 6/(2**(1/4) + 2**(1/3))**4 - 240/(2**(1/4) + 2**(1/3))**10 - 32/(2**(1/4) + 2**(1/3))**9 - 96/(2**(1/4) + 2**(1/3))**11 + 8/(2**(1/4) + 2**(1/3))**12 + 12/(2**(1/4) + 2**(1/3))**8 + 24/(2**(1/4) + 2**(1/3))**6 + 1
>>> f.subs(x, 1/(2**(Rational(1,3)) + 2**(Rational(1,4)))).simplify()
0
>>> f.subs(x, 1/(2**(Rational(1,3)) + 2**(Rational(1,4)))).evalf()
0.e-132
```

**Comment by asmeurer** [comment]
As pointed out by @Roland-Sands in https://github.com/sympy/sympy/issues/14228, the minimal polynomial of `1/(2**(1/3) + 2**(1/4))` should be `f(1/x)*x**n`, where `f` is the minimal polynomial of `2**(1/3) + 2**(1/4)`.

```py
>>> minimal_polynomial(2**Rational(1,3) + 2**Rational(1,4), x)
x**12 - 8*x**9 - 6*x**8 + 24*x**6 - 192*x**5 + 12*x**4 - 32*x**3 - 240*x**2 - 96*x + 8
>>> minimal_polynomial(1/(2**Rational(1,3) + 2**Rational(1,4)), x)
8*x**12 - 96*x**11 - 240*x**10 - 32*x**9 + 12*x**8 - 192*x**7 + 24*x**6 - 6*x**4 - 8*x**3 + 1
>>> expand(minimal_polynomial(2**Rational(1,3) + 2**Rational(1,4), x).subs(x, 1/x)*x**12)
8*x**12 - 96*x**11 - 240*x**10 - 32*x**9 + 12*x**8 - 192*x**7 + 24*x**6 - 6*x**4 - 8*x**3 + 1
```

Also, according to `factor` the polynomial is indeed irreducible. 

```
>>> factor(minimal_polynomial(1/(2**Rational(1,3) + 2**Rational(1,4)), x))
8*x**12 - 96*x**11 - 240*x**10 - 32*x**9 + 12*x**8 - 192*x**7 + 24*x**6 - 6*x**4 - 8*x**3 + 1
```
