### ISSUE TITLE
n*x**(n-1) / (x+1) can be integrated for general n, positive n, and integer n, but not for positive integer n

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#14241]
```
>>> from sympy import *
>>> x = Symbol('x')
>>> f = lambda n: integrate(n * x**(n-1) / (x+1), x)
>>> print(f(Symbol('n')))
n**2*x**n*lerchphi(x*exp_polar(I*pi), 1, n)*gamma(n)/gamma(n + 1)
>>> print(f(Symbol('n', positive=True)))
n**2*x**n*lerchphi(x*exp_polar(I*pi), 1, n)*gamma(n)/gamma(n + 1)
>>> print(f(Symbol('n', integer=True)))
n**2*x**n*lerchphi(x*exp_polar(I*pi), 1, n)*gamma(n)/gamma(n + 1)
>>> print(f(Symbol('n', integer=True, positive=True)))
Traceback (most recent call last):
  File "/home/E/Desktop/sympy-master/test.py", line 157, in <module>
    print(f(Symbol('n', integer=True, positive=True)))
  File "/home/E/Desktop/sympy-master/test.py", line 153, in <lambda>
    f = lambda n: integrate(n * x**(n-1) / (x+1), x)
  File "/home/E/Desktop/sympy-master/sympy/integrals/integrals.py", line 1390, in integrate
    risch=risch, manual=manual)
  File "/home/E/Desktop/sympy-master/sympy/integrals/integrals.py", line 530, in doit
    function, xab[0], **eval_kwargs)
  File "/home/E/Desktop/sympy-master/sympy/integrals/integrals.py", line 991, in _eval_integral
    h = meijerint_indefinite(g, x)
  File "/home/E/Desktop/sympy-master/sympy/integrals/meijerint.py", line 1614, in meijerint_indefinite
    res = _meijerint_indefinite_1(f.subs(x, x + a), x)
  File "/home/E/Desktop/sympy-master/sympy/integrals/meijerint.py", line 1679, in _meijerint_indefinite_1
    r = hyperexpand(r.subs(t, a*x**b), place=place)
  File "/home/E/Desktop/sympy-master/sympy/simplify/hyperexpand.py", line 2473, in hyperexpand
    return f.replace(hyper, do_replace).replace(meijerg, do_meijer)
  File "/home/E/Desktop/sympy-master/sympy/core/basic.py", line 1412, in replace
    rv = bottom_up(self, rec_replace, atoms=True)
  File "/home/E/Desktop/sympy-master/sympy/simplify/simplify.py", line 1043, in bottom_up
    for a in rv.args])
  File "/home/E/Desktop/sympy-master/sympy/simplify/simplify.py", line 1043, in <listcomp>
    for a in rv.args])
  File "/home/E/Desktop/sympy-master/sympy/simplify/simplify.py", line 1046, in bottom_up
    rv = F(rv)
  File "/home/E/Desktop/sympy-master/sympy/core/basic.py", line 1397, in rec_replace
    new = _value(expr, result)
  File "/home/E/Desktop/sympy-master/sympy/core/basic.py", line 1340, in <lambda>
    _value = lambda expr, result: value(*expr.args)
  File "/home/E/Desktop/sympy-master/sympy/simplify/hyperexpand.py", line 2470, in do_meijer
    allow_hyper, rewrite=rewrite, place=place)
  File "/home/E/Desktop/sympy-master/sympy/simplify/hyperexpand.py", line 2347, in _meijergexpand
    slater1, cond1 = do_slater(func.an, func.bm, func.ap, func.bq, z, z0)
  File "/home/E/Desktop/sympy-master/sympy/simplify/hyperexpand.py", line 2315, in do_slater
    resid = residue(integrand, s, b_ + r)
  File "/home/E/Desktop/sympy-master/sympy/series/residues.py", line 57, in residue
    s = expr.series(x, n=0)
  File "/home/E/Desktop/sympy-master/sympy/core/expr.py", line 2655, in series
    rv = self.subs(x, xpos).series(xpos, x0, n, dir, logx=logx)
  File "/home/E/Desktop/sympy-master/sympy/core/expr.py", line 2662, in series
    s1 = self._eval_nseries(x, n=n, logx=logx)
  File "/home/E/Desktop/sympy-master/sympy/core/mul.py", line 1651, in _eval_nseries
    terms = [t.nseries(x, n=n, logx=logx) for t in self.args]
  File "/home/E/Desktop/sympy-master/sympy/core/mul.py", line 1651, in <listcomp>
    terms = [t.nseries(x, n=n, logx=logx) for t in self.args]
  File "/home/E/Desktop/sympy-master/sympy/core/expr.py", line 2861, in nseries
    return self._eval_nseries(x, n=n, logx=logx)
  File "/home/E/Desktop/sympy-master/sympy/functions/special/gamma_functions.py", line 184, in _eval_nseries
    return super(gamma, self)._eval_nseries(x, n, logx)
  File "/home/E/Desktop/sympy-master/sympy/core/function.py", line 669, in _eval_nseries
    raise PoleError("Cannot expand %s around 0" % (self))
sympy.core.function.PoleError: Cannot expand gamma(_x - n) around 0
```

**Comment by Roland-Sands** [comment]
Many of the problems I have encountered have been because of `lerchphi`
I believe `lerchphi` is a major issue
