### ISSUE TITLE
exp of MatrixSymbol throws an error

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#14256]
```
>>> A = MatrixSymbol("A", 2, 2)
>>> exp(A)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/sympy/sympy/core/function.py", line 441, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/home/ubuntu/sympy/sympy/core/function.py", line 250, in __new__
    evaluated = cls.eval(*args)
  File "/home/ubuntu/sympy/sympy/functions/elementary/exponential.py", line 305, in eval
    return arg.exp()
AttributeError: 'MatrixSymbol' object has no attribute 'exp'
```

Other functions, like sin(A) or cos(A), return the expected expressions.

**Comment by GYeyosi** [comment]
Here it's enough to check if the arg is an instance of MatrixBase or not. isn't it ?

**Comment by normalhuman** [comment]
Yes. You may notice a link to pull request just above your comment.
