### ISSUE TITLE
simplify((x**3 + 3*x + 2).subs(x, b)) does not return 0, where b is a root of x**3 + 3*x + 2

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14269]
```
>>> b = (sqrt(2) - 1)**(Rational(1,3)) - (sqrt(2) + 1)**(Rational(1,3))
>>> w = (x**3 + 3*x + 2).subs(x, b)
>>> simplify(w)
                                             3                    
    3 ________   ⎛  3 ________   3 _________⎞          3 _________
- 3⋅╲╱ 1 + √2  + ⎝- ╲╱ 1 + √2  + ╲╱ -1 + √2 ⎠  + 2 + 3⋅╲╱ -1 + √2 
>>> w.evalf()
0.e-128
```

**Comment by Him98** [comment]
This is the case with too.
``` >>> b = -1 + sqrt(5)
>>> w = ((1/4)*x**2 + (1/2)*x -1).subs(x,b)
>>> w.evalf()
-0.e-125 
```

The values are too small. Why can't they be ignored?
For ignoring we can see that if the value returned is a and the correct answer is b then if 
mod(a - b)/max(1,mod(b)) <= 10**-20. 10**-20 can be replaced by any acceptable number which on changing doesn't make a difference in answer.

**Comment by samyak-jain** [comment]
Can I work on this?

**Comment by Roland-Sands** [comment]
> Can I work on this?

I think it would be excellent if you did

**Comment by samyak-jain** [comment]
@Him98 If I were to work on the method you suggested, how will I know what the value of b is? Sorry, if it seems obvious, I am new to this.

**Comment by Him98** [comment]
@samyak-jain Yeah, that wasn't the correct way.
@Roland-Sands Can we just solve the equation using solve function and then do as follows:

```
>>> a = solve(x**3 + 3*x + 2,x)
>>> a
[3/((-1/2 - sqrt(3)*I/2)*(27 + 27*sqrt(2))**(1/3)) - (-1/2 - sqrt(3)*I/2)*(27 + 27*sqrt(2))**(1/3)/3, -(-1/2 + sqrt(3)*I/2)*(27 + 27*sqrt(2))**(1/3)/3 + 3/((-1/2 + sqrt(3)*I/2)*(27 + 27*sqrt(2))**(1/3)), -(27 + 27*sqrt(2))**(1/3)/3 + 3/(27 + 27*sqrt(2))**(1/3)]
>>> w = (x**3 + 3*x + 2).subs(x,a[0])
>>> w
2 + (3/((-1/2 - sqrt(3)*I/2)*(27 + 27*sqrt(2))**(1/3)) - (-1/2 - sqrt(3)*I/2)*(27 + 27*sqrt(2))**(1/3)/3)**3 + 9/((-1/2 - sqrt(3)*I/2)*(27 + 27*sqrt(2))**(1/3)) - (-1/2 - sqrt(3)*I/2)*(27 + 27*sqrt(2))**(1/3)
>>> w.evalf()
0.e-127 + 0.e-126*I 
```

So if the root is there in the answer we got using solve(), we directly returns 0.

**Comment by samyak-jain** [comment]
@Him98 This sounds good. I'll start working on this then?

**Comment by Roland-Sands** [comment]
> Can we just solve the equation using solve function and then ...

If I understand you correctly, you want to do a high precision evaluation and then conclude that a number so close to `0` must be `0`
If my understanding of SymPy is correct, then that is not the way to go, unless you provide a theoretical justification that lets you deduce an exact answer from an approximation

The intention of SymPy is to do things symbolically, which in this instance would be to transform these expressions into `0`

The problem is the nested radicals, for which there is no obvious simplification or transformation  
The issue would be solved (I think) if the radicals could be denested

**Comment by Roland-Sands** [comment]
I wonder if the example in the title could be done by expanding `(sqrt(2) + 1)**(Rational(1,3))` and `(sqrt(2) - 1)**(Rational(1,3))` by the binomial theorem and then cancelling everything

**Comment by Roland-Sands** [comment]
Would another possibility be doing a finite fourier expansion of `(x**3 + 3*x + 2).subs(x, b)`

**Comment by jksuom** [comment]
The computation should be done with the element `a` defined by `b` in the number field it generates.
```
>>> b = (sqrt(2) - 1)**(Rational(1,3)) - (sqrt(2) + 1)**(Rational(1,3))
>>> K = QQ.algebraic_field(b)
>>> a = K.from_sympy(b)
>>> p = Poly(x**3 + 3*x + 2, x, domain=K)
>>> p(a)
0
```
(This should be run on the latest master.)

**Comment by Him98** [comment]
@jksuom can you please tell what exactly you imported as I am getting following error:

```
>>> from sympy.polys.domains import domain
>>> import sympy
>>> from sympy import Rational
>>> from math import sqrt
>>> b = (sqrt(2)-1)**(Rational(1,3)) - (sqrt(2)+1)**(Rational(1,3))
>>> from sympy.polys.domains import QQ
>>> K = QQ.algebraic_field(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/himanshu/github/sympy/sympy/polys/domains/rationalfield.py", line 26, in algebraic_field
    return AlgebraicField(self, *extension)
  File "/home/himanshu/github/sympy/sympy/polys/domains/algebraicfield.py", line 33, in __init__
    self.ext = to_number_field(ext)
  File "/home/himanshu/github/sympy/sympy/polys/numberfields.py", line 1055, in to_number_field
    minpoly, coeffs = primitive_element(extension, gen, polys=True)
  File "/home/himanshu/github/sympy/sympy/polys/numberfields.py", line 841, in primitive_element
    extension = [ AlgebraicNumber(ext, gen=x) for ext in extension ]
  File "/home/himanshu/github/sympy/sympy/polys/numberfields.py", line 841, in <listcomp>
    extension = [ AlgebraicNumber(ext, gen=x) for ext in extension ]
  File "/home/himanshu/github/sympy/sympy/core/numbers.py", line 2369, in __new__
    expr, args.get('gen'), polys=True), expr
  File "/home/himanshu/github/sympy/sympy/polys/numberfields.py", line 664, in minimal_polynomial
    result = _minpoly_compose(ex, x, domain)
  File "/home/himanshu/github/sympy/sympy/polys/numberfields.py", line 578, in _minpoly_compose
    raise NotAlgebraic("%s doesn't seem to be an algebraic element" % ex)
sympy.polys.polyerrors.NotAlgebraic: -0.596071637983321 doesn't seem to be an algebraic element
```
I am not able to get the mistake. I have also the cloned the present master only.

**Comment by jksuom** [comment]
from math import sqrt

`sqrt` should be imported from SymPy. The `math` version will convert the exact `sqrt(2)` into an inexact float that is not algebraic in SymPy.

**Comment by smichr** [comment]
@jksuom has the best idea. For those not familiar with such methods, `w.equals(0)` returns True.

**Comment by samyak-jain** [comment]
@smichr What is the difference between `w==0` and `w.equals(0)`? Sounds counterintuitive.

**Comment by Him98** [comment]
@samyak-jain == in Sympy represents exact structural equality testing and not the general equality that we usually think of and it returns just a boolean value. For example, (x+1)**2 = x**2+2*x+1 but when we do (x+1)**2 == x**2+2*x+1 in sympy we get False due to the same reason of structural equality testing. If we had taken a = (x+1)**2 and b =  x**2+2*x+1 then a.equals(b) would have returned True.

**Comment by czarzival** [comment]
Tested on SymPy 1.14.0 with Python 3.13, simplify(w) now correctly returns 0. The original issue appears to be resolved. Could this be closed?
```python
from sympy import *
x = symbols('x')
b = (sqrt(2) - 1)**Rational(1,3) - (sqrt(2) + 1)**Rational(1,3)
w = (x**3 + 3*x + 2).subs(x, b)
print(simplify(w))   # 0
print(w.equals(0))   # True
```

**Comment by oscarbenjamin** [comment]
It can be closed if someone adds a test with the code you showed.
