### ISSUE TITLE
nsolve UnboundLocalError when trying to solve weird equation

### ISSUE THREAD

**Issue by dionyziz** [sympy/sympy#14417]
`nsolve` fails with "UnboundLocalError" when giving it a peculiar equation.

***Actual behavior***: An "UnboundLocalError" is thrown.

***Expected behavior***: Either a solution is found, or a "ValueError: Could not find root within given tolerance" is thrown.

Steps to reproduce:

```
>>> from sympy import Symbol
>>> from sympy import nsolve
>>> p = Symbol('p')
>>> nsolve((1 - p)**30 - 1, 0.9)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/sympy/utilities/decorator.py", line 91, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sympy/solvers/solvers.py", line 2826, in nsolve
    x = sympify(findroot(f, x0, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/mpmath/calculus/optimization.py", line 967, in findroot
    if not isinstance(x, (list, tuple, ctx.matrix)):
UnboundLocalError: local variable 'x' referenced before assignment
```

However, altering the equation slightly avoids the error:

```
>>> nsolve((1 - p)**25 - 1, 0.9)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/sympy/utilities/decorator.py", line 91, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sympy/solvers/solvers.py", line 2826, in nsolve
    x = sympify(findroot(f, x0, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/mpmath/calculus/optimization.py", line 975, in findroot
    % (norm(f(*xl))**2, tol))
ValueError: Could not find root within given tolerance. (4.4250942132223239692e+999 > 2.16840434497100886801e-19)
Try another starting point or tweak arguments.
```

My version:

```
Python 2.7.10 (default, Jul 15 2017, 17:16:57)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> sympy.__version__
'1.1.1'
```

This is on macOS 10.13.3 (17D102).

**Comment by jksuom** [comment]
This seems to be an mpmath issue. It should be checked before [this line](https://github.com/fredrik-johansson/mpmath/blob/master/mpmath/calculus/optimization.py#L967) that at least one iteration was found.

**Comment by dionyziz** [comment]
Should I submit an mpmath issue instead then?

**Comment by normalhuman** [comment]
Yes. For the mpmath issue, use sample code without SymPy (to which your SymPy code reduces): 
```
>>> from mpmath import findroot
>>> findroot(lambda p: (1 - p)**30 - 1, 0.9)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lvk/anaconda3/lib/python3.6/site-packages/mpmath/calculus/optimization.py", line 967, in findroot
    if not isinstance(x, (list, tuple, ctx.matrix)):
UnboundLocalError: local variable 'x' referenced before assignment
```

**Comment by oscarbenjamin** [comment]
Looks like the mpmath issue was fixed. I now get
```
In [1]: from sympy import Symbol                                                                                                                              

In [2]: >>> from sympy import Symbol 
   ...: >>> from sympy import nsolve 
   ...: >>> p = Symbol('p') 
   ...: >>> nsolve((1 - p)**30 - 1, 0.9)                                                                                                                      
---------------------------------------------------------------------------
ValueError: Could not find root using the given solver.
Try another starting point or tweak arguments.
```
I can find the root with a much closer starting point though:
```
In [29]: nsolve(eq, 0.001)                                                                                                                                    
Out[29]: 1.21412848945653e-23
```

**Comment by oscarbenjamin** [comment]
I think this is fixed so closing
