### ISSUE TITLE
Cannot evaluate third integral in iterated integral of f(x,y,z)

### ISSUE THREAD

**Issue by patrickwalls** [sympy/sympy#14437]
Iterated integral of a function of three variables f(x,y,z) gives an error on the last integral:

```
>>> from sympy import *
>>> x,y,z = symbols('x,y,z')
>>> f = Function('f')(x,y,z)
>>> Ix = integrate(f,(x,0,1))
>>> Ix
1              
⌠              
⎮ f(x, y, z) dx
⌡              
0    
>>> Ixy = integrate(Ix,(y,0,2))
>>> Ixy
2 1                 
⌠ ⌠                 
⎮ ⎮ f(x, y, z) dx dy
⌡ ⌡                 
0 0 
```
But the last integral fails:
```
>>> Ixyz = integrate(Ixy,(z,0,3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/patrickwalls/miniconda3/lib/python3.5/site-packages/sympy/integrals/integrals.py", line 1295, in integrate
    risch=risch, manual=manual)
  File "/Users/patrickwalls/miniconda3/lib/python3.5/site-packages/sympy/integrals/integrals.py", line 495, in doit
    function = self.func(*([function] + [xab])).factor()
  File "/Users/patrickwalls/miniconda3/lib/python3.5/site-packages/sympy/core/expr.py", line 3151, in factor
    return factor(self, *gens, **args)
  File "/Users/patrickwalls/miniconda3/lib/python3.5/site-packages/sympy/polys/polytools.py", line 6166, in factor
    return _generic_factor(f, gens, args, method='factor')
  File "/Users/patrickwalls/miniconda3/lib/python3.5/site-packages/sympy/polys/polytools.py", line 5858, in _generic_factor
    return _symbolic_factor(sympify(expr), opt, method)
  File "/Users/patrickwalls/miniconda3/lib/python3.5/site-packages/sympy/polys/polytools.py", line 5802, in _symbolic_factor
    return expr._eval_factor()
  File "/Users/patrickwalls/miniconda3/lib/python3.5/site-packages/sympy/concrete/expr_with_limits.py", line 417, in _eval_factor
    summand = self.func(self.function, self.limits[0:-1]).factor()
  File "/Users/patrickwalls/miniconda3/lib/python3.5/site-packages/sympy/integrals/integrals.py", line 75, in __new__
    obj = AddWithLimits.__new__(cls, function, *symbols, **assumptions)
  File "/Users/patrickwalls/miniconda3/lib/python3.5/site-packages/sympy/concrete/expr_with_limits.py", line 368, in __new__
    limits, orientation = _process_limits(*symbols)
  File "/Users/patrickwalls/miniconda3/lib/python3.5/site-packages/sympy/concrete/expr_with_limits.py", line 69, in _process_limits
    raise ValueError('Invalid limits given: %s' % str(symbols))
ValueError: Invalid limits given: (((x, 0, 1), (y, 0, 2)),)
```

**Comment by jksuom** [comment]
[This line](https://github.com/sympy/sympy/blob/master/sympy/concrete/expr_with_limits.py#L414) sends  `symbols` as a single list `self.limits[0:-1]` which becomes `((x, 0, 1), (y, 0, 2))`. There should be `*self.limits[0:-1]` instead.

**Comment by cbm755** [comment]
Thanks @jksuom.  @patrickwalls and I will try to fix this as part of our software seminar...
