### ISSUE TITLE
Codegen fails when used on Matrix object

### ISSUE THREAD

**Issue by woodscn** [sympy/sympy#14488]
I'm trying to make sense of what codegen is doing here. I've stripped this down to a simple test case to show the problem, though the real situation is more complicated.

I want to generate a function that takes input arguments and returns an array of values. Codegen appears to be creating a dummy output argument in order to facilitate this. However, it is not clear to me how I am supposed to reference this argument from python in the case where I need to specify the input arguments (with argument_sequence). 

I also see this problem with Fortran.

Thanks in advance!

Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from sympy import *; from sympy.abc import *; from sympy.utilities.codegen import codegen
>>> codegen(('test', Matrix([0, 1, x**2])), 'C')

[('test.c', '/******************************************************************************\n *                      Code generated with sympy 1.1.1                       *\n *                                                                            *\n *              See http://www.sympy.org/ for more information.               *\n *                                                                            *\n *                       This file is part of \'project\'                       *\n ******************************************************************************/\n#include "test.h"\n#include <math.h>\n\nvoid test(double x, double *out_6665829299164070667) {\n\n   out_6665829299164070667[0] = 0;\n   out_6665829299164070667[1] = 1;\n   out_6665829299164070667[2] = pow(x, 2);\n\n}\n'), ('test.h', "/******************************************************************************\n *                      Code generated with sympy 1.1.1                       *\n *                                                                            *\n *              See http://www.sympy.org/ for more information.               *\n *                                                                            *\n *                       This file is part of 'project'                       *\n ******************************************************************************/\n\n\n#ifndef PROJECT__TEST__H\n#define PROJECT__TEST__H\n\nvoid test(double x, double *out_6665829299164070667);\n\n#endif\n\n")]

>>> codegen(('test', Matrix([0, 1, x**2])), 'C', argument_sequence=(x,))
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/woodscn/anaconda3/lib/python3.6/site-packages/sympy/utilities/codegen.py", line 2024, in codegen
    global_vars))
  File "/Users/woodscn/anaconda3/lib/python3.6/site-packages/sympy/utilities/codegen.py", line 655, in routine
    raise CodeGenArgumentListError(msg, missing)
sympy.utilities.codegen.CodeGenArgumentListError: ("Argument list didn't specify: out_6665829299164070667 ", [OutputArgument(out_6665829299164070667, Matrix([
[   0],
[   1],
[x**2]]), out_6665829299164070667)])

**Comment by woodscn** [comment]
@certik

**Comment by stewpend0us** [comment]
I haven't had much luck with getting the arguments in the order I want. But...doing this at least got me a reasonably named argument then I just wrap the auto generated function with a function signature I like.

```python
codegen(('test',Eq(MatrixSymbol('output',3,1),Matrix([0, 1, x**2]))), 'C')
```

**Comment by vxj9800** [comment]
I am facing the same problem. Did anyone find any solution for this? Thanks in advance.

**Comment by vxj9800** [comment]
If someone is facing the same issue, here is the solution.

Code:
```
from sympy import *; from sympy.abc import *; from sympy.utilities.codegen import codegen
out = MatrixSymbol("out",3,1);
[(c_name, c_code), (h_name, c_header)] = codegen(('test',Equality(out,Matrix([0, 1, x**2]),evaluate=False) ), 'C', argument_sequence=(x,out));
print(c_code);
```

Output:
```
/******************************************************************************
 *                       Code generated with SymPy 1.12                       *
 *                                                                            *
 *              See http://www.sympy.org/ for more information.               *
 *                                                                            *
 *                       This file is part of 'project'                       *
 ******************************************************************************/
#include "test.h"
#include <math.h>

void test(double x, double *out) {

   out[0] = 0;
   out[1] = 1;
   out[2] = pow(x, 2);

}
```

**Comment by jabierros** [comment]
Hi!,

I'm following the recipe. Seems to work very well.

But  I'm stuck with CSE ("common subexpression elimination")

`replacements, reduced_exprs = cse(R_nn)`

I do not know how to use the outputs with `codegen`.

I would like to avoid the path in [scipy-2017-codegen-tutorial](https://www.sympy.org/scipy-2017-codegen-tutorial/notebooks/07-the-hard-way.html), it seem to be deprecated in some respects, and it requires more work.

Thank you
