### ISSUE TITLE
"ValueError: gamma function pole" in repr of expression involving factorial of sum

### ISSUE THREAD

**Issue by DRMacIver** [sympy/sympy#14567]
Attention conservation notice: This is a weird niche bug and I'm not really expecting you to care about it, but I thought I would mention it for completeness.

The following code raises "ValueError: gamma function pole":

```python
from sympy.abc import a, b
from sympy import Sum, factorial

print(factorial(Sum(-1, (a, 0, 0))) + b)
```

When run on Python 3.6.0 on Linux with sympy from master as of e2757bc8de0179cf4b4a917242125172e6da6bb2 I get the following traceback:

```python-traceback
Traceback (most recent call last):
  File "/home/david/scratch/sympy/sympy/core/evalf.py", line 1306, in evalf
    rf = evalf_table[x.func]
KeyError: factorial

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./printerror.py", line 4, in <module>
    print(factorial(Sum(-1, (a, 0, 0))) + b)
  File "/home/david/scratch/sympy/sympy/core/basic.py", line 401, in __str__
    return sstr(self, order=None)
  File "/home/david/scratch/sympy/sympy/printing/str.py", line 837, in sstr
    s = p.doprint(expr)
  File "/home/david/scratch/sympy/sympy/printing/printer.py", line 236, in doprint
    return self._str(self._print(expr))
  File "/home/david/scratch/sympy/sympy/printing/printer.py", line 274, in _print
    return getattr(self, printmethod)(expr, *args, **kwargs)
  File "/home/david/scratch/sympy/sympy/printing/str.py", line 53, in _print_Add
    terms = self._as_ordered_terms(expr, order=order)
  File "/home/david/scratch/sympy/sympy/printing/printer.py", line 287, in _as_ordered_terms
    return expr.as_ordered_terms(order=order)
  File "/home/david/scratch/sympy/sympy/core/expr.py", line 993, in as_ordered_terms
    terms, gens = self.as_terms()
  File "/home/david/scratch/sympy/sympy/core/expr.py", line 1032, in as_terms
    coeff *= complex(factor)
  File "/home/david/scratch/sympy/sympy/core/expr.py", line 259, in __complex__
    result = self.evalf()
  File "/home/david/scratch/sympy/sympy/core/evalf.py", line 1419, in evalf
    result = evalf(self, prec + 4, options)
  File "/home/david/scratch/sympy/sympy/core/evalf.py", line 1313, in evalf
    xe = x._eval_evalf(prec)
  File "/home/david/scratch/sympy/sympy/core/function.py", line 556, in _eval_evalf
    v = func(*args)
  File "/home/david/projects/Hypothesis-Paper-1/venv/lib/python3.6/site-packages/mpmath/ctx_mp_python.py", line 993, in f
    return ctx.make_mpf(mpf_f(x._mpf_, prec, rounding))
  File "/home/david/projects/Hypothesis-Paper-1/venv/lib/python3.6/site-packages/mpmath/libmp/gammazeta.py", line 2353, in mpf_factorial
    return mpf_gamma(x, prec, rnd, 1)
  File "/home/david/projects/Hypothesis-Paper-1/venv/lib/python3.6/site-packages/mpmath/libmp/gammazeta.py", line 1950, in mpf_gamma
    raise ValueError("gamma function pole")
ValueError: gamma function pole
```

If I insert a `doit()` call on the Sum I instead get `b + zoo`, so the problem isn't simply that it's calling `factorial(-1)` when the Sum is evaluated.

**Comment by DRMacIver** [comment]
BTW the recent spate of bugs from me are a result of using [Hypothesis's stateful testing](https://hypothesis.readthedocs.io/en/latest/stateful.html) on sympy as part of an experiment. If they're not useful to you, let me know and I'll stop bothering you with them. If they are useful to you I'd be happy to try to contribute some tests along these lines though due to various reasons the output is quite high noise at the moment (the bugs so far have involved a lot of manual cleanup).

**Comment by asmeurer** [comment]
I think fuzzing is useful. So long as you at least make a cursory effort to not report duplicate bugs (our issue tracker is huge I know, so I won't blame you if you miss an existing issue). 

This example shows one reason why I think it's bad that the printers use evalf. The problem is that factorial(Sum(-1, (a, 0, 0))).evalf() raises ValueError. For me the bigger issue with calling evalf in the printers is performance. 

I'm not sure if evalf should be allowed to raise ValueError, or if it should always return a value, even if that value is zoo or nan. As far as I know evalf doesn't return zoo anywhere. I remember discussing that before but I don't remember what we decided. @smichr do you recall if evalf ever can return zoo or not?

**Comment by oscarbenjamin** [comment]
This particular issue seems to be fixed now:
```julia
In [1]: from sympy.abc import a, b 
   ...: from sympy import Sum, factorial 
   ...:  
   ...: print(factorial(Sum(-1, (a, 0, 0))) + b)                                                                                  
b + factorial(Sum(-1, (a, 0, 0)))
```

Can this be closed?
