### ISSUE TITLE
integration fails in creation of piecewise result

### ISSUE THREAD

**Issue by rwst** [sympy/sympy#14613]
```
In [17]: b,c,p,m,n=symbols('b,c,p,m,n')
In [18]: integrate((c*x)**m*(b*x**n)**p,x)
...
/usr/lib/python3.4/site-packages/sympy-1.1.2.dev0-py3.4.egg/sympy/integrals/heurisch.py in heurisch_wrapper(f, x, rewrite, hints, mappings, retries, degree_offset, unnecessary_permutations)
    177                               degree_offset, unnecessary_permutations),
    178                               True))
--> 179     return Piecewise(*pairs)
    180 
    181 class BesselTable(object):

/usr/lib/python3.4/site-packages/sympy-1.1.2.dev0-py3.4.egg/sympy/functions/elementary/piecewise.py in __new__(cls, *args, **options)
    125         for ec in args:
    126             # ec could be a ExprCondPair or a tuple
--> 127             pair = ExprCondPair(*getattr(ec, 'args', ec))
    128             cond = pair.cond
    129             if cond is false:

/usr/lib/python3.4/site-packages/sympy-1.1.2.dev0-py3.4.egg/sympy/functions/elementary/piecewise.py in __new__(cls, expr, cond)
     21 
     22     def __new__(cls, expr, cond):
---> 23         expr = as_Basic(expr)
     24         if cond == True:
     25             return Tuple.__new__(cls, expr, true)

/usr/lib/python3.4/site-packages/sympy-1.1.2.dev0-py3.4.egg/sympy/core/basic.py in as_Basic(expr)
     24         raise TypeError(
     25             'Argument must be a Basic object, not `%s`' % func_name(
---> 26             expr))
     27 
     28 

TypeError: Argument must be a Basic object, not `NoneType`
```

**Comment by jashan498** [comment]
I think this is because the integral of `(b*x**n)**p*(c*x)**(-n*p - 1)` is being evaluated wrongly to `None` [here](https://github.com/sympy/sympy/blob/91f56cac98ecc15ee577768bfc9ff15b4bf4515c/sympy/integrals/heurisch.py#L163).

**Comment by jksuom** [comment]
It seems that SymPy is careful not to simplify the integrand under no assumptions on the symbols. The integration will succeed if the integrand is written in the expanded form `c**m*x**m*b**p*x**(n*p)`.

**Comment by jashan498** [comment]
`heurisch_wrapper` returning `[(b**p*c**m*x*x**m*(x**n)**p/(m + n*p + 1), Ne(m, -n*p - 1)), (None, True)]` is the main cause of bug. So, should there be a check inside `heurisch_wrapper` to replace `NoneType` with an unevaluated integral (something like `[(b**p*c**m*x*x**m*(x**n)**p/(m + n*p + 1), Ne(m, -n*p - 1)), (Integral((b*x**n)**p*(c*x)**(-n*p - 1), x), True)] `)?

**Comment by thecloisterbell** [comment]
I believe this is another example of the same issue. It demonstrates that integrate can handle each case but put them together to give a piecewise result as it can for the simpler integral.

```
x=Symbol('x')

alpha = Symbol('alpha', real=True)

integrate(x**alpha, x)
Out[4]: Piecewise((x**(alpha + 1)/(alpha + 1), Ne(alpha, -1)), (log(x), True))

integrate(x**(-1)*log(x), x)
Out[5]: log(x)**2/2

not_zero = Symbol('not_zero', real=True, nonzero=True)

alpha_two = not_zero - 1

integrate(x**(alpha_two)*log(x), x)
Out[8]: x**not_zero*log(x)/not_zero - x**not_zero/not_zero**2

integrate(x**(alpha)*log(x), x)
Traceback (most recent call last):

  File "<ipython-input-9-31dc8899c634>", line 1, in <module>
    integrate(x**(alpha)*log(x), x)

  File "/apps/linsw1/anaconda3/5.3.1_64/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1403, in integrate
    risch=risch, manual=manual)

  File "/apps/linsw1/anaconda3/5.3.1_64/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 538, in doit
    function, xab[0], **eval_kwargs)

  File "/apps/linsw1/anaconda3/5.3.1_64/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 985, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])

  File "/apps/linsw1/anaconda3/5.3.1_64/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 181, in heurisch_wrapper
    return Piecewise(*pairs)

  File "/apps/linsw1/anaconda3/5.3.1_64/lib/python3.7/site-packages/sympy/functions/elementary/piecewise.py", line 127, in __new__
    pair = ExprCondPair(*getattr(ec, 'args', ec))

  File "/apps/linsw1/anaconda3/5.3.1_64/lib/python3.7/site-packages/sympy/functions/elementary/piecewise.py", line 23, in __new__
    expr = as_Basic(expr)

  File "/apps/linsw1/anaconda3/5.3.1_64/lib/python3.7/site-packages/sympy/core/basic.py", line 26, in as_Basic
    expr))

TypeError: Argument must be a Basic object, not NoneType
```

**Comment by risubaba** [comment]
```
In [6]: integrate((c*x)**m*(b*x**n)**p,x)                        
Out[6]: 
⎧                    p                       
⎪      p  m    m ⎛ n⎞                        
⎪     b ⋅c ⋅x⋅x ⋅⎝x ⎠                        
⎪     ────────────────       for m ≠ -n⋅p - 1
⎪       m + n⋅p + 1                          
⎨                                            
⎪⌠                                           
⎪⎮       p                                   
⎪⎮ ⎛   n⎞       -n⋅p - 1                     
⎪⎮ ⎝b⋅x ⎠ ⋅(c⋅x)         dx     otherwise    
⎩⌡                 
```
Is this the correct expected output?

**Comment by jksuom** [comment]
> Is this the correct expected output?

The integrand of the second integral should simplify to constant times `1/x`. It looks like some simplification step is needed.

**Comment by risubaba** [comment]
> > Is this the correct expected output?
> 
> The integrand of the second integral should simplify to constant times `1/x`. It looks like some simplification step is needed.

This was the output produced when  `integrate` was called after substituting m = - n*p - 1. What changes should be made to simplify it further?
