### ISSUE TITLE
Lambdify with numpy failed on pypy

### ISSUE THREAD

**Issue by extraymond** [sympy/sympy#14658]
Hi! I've try to use sympy lambdify to convert my code while running in pypy.
However the below error is raised:

```
can't import 'None' with 'import_module('numpy')' command
```

I do have numpy installed, just that using numpy as lambdify modules is not working.
BTW, if using cython as lambdify module it worked.

**Comment by extraymond** [comment]
This is the traceback.

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/extraymond/miniconda3/envs/pypy/site-packages/sympy/utilities/lambdify.py", line 379, in lambdify
    buf = _get_namespace(m)
  File "/home/extraymond/miniconda3/envs/pypy/site-packages/sympy/utilities/lambdify.py", line 471, in _get_namespace
    _import(m)
  File "/home/extraymond/miniconda3/envs/pypy/site-packages/sympy/utilities/lambdify.py", line 160, in _import
    "can't import '%s' with '%s' command" % (module, import_command))
ImportError: can't import 'None' with 'import_module('numpy')' command

```

**Comment by jksuom** [comment]
It seems that there were errors with old versions of pypy, and it was [explictly excluded](https://github.com/sympy/sympy/blob/master/sympy/external/importtools.py#L128). Maybe that would not be necessary with new versions.

**Comment by extraymond** [comment]
Thanks! I will comment this out for now as a workaround.
