### ISSUE TITLE
parse_expr can not parse a very simple string "-beta". 

### ISSUE THREAD

**Issue by mzhenirovskyy** [sympy/sympy#14660]
sympy.__version__ =  '1.1.1'
Python 3.6.4
macOS 10.13.4

`parse_expr("-bet") `  # OK

BUT:

`parse_expr("-beta")`

```
Traceback (most recent call last):
  File "/Users/mazhenir/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-84d8235b5ab5>", line 1, in <module>
    parse_expr("-beta")
  File "/Users/mazhenir/anaconda3/lib/python3.6/site-packages/sympy/parsing/sympy_parser.py", line 894, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/Users/mazhenir/anaconda3/lib/python3.6/site-packages/sympy/parsing/sympy_parser.py", line 807, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
TypeError: bad operand type for unary -: 'FunctionClass'
```

**Comment by asmeurer** [comment]
`parse_expr` runs in the globals from `from sympy import *` by default. You can override this by setting `global_dict`. See the [docstring](http://docs.sympy.org/latest/modules/parsing.html#sympy.parsing.sympy_parser.parse_expr) of parse_expr for more information. Here, `beta` is the `beta` function.
