### ISSUE TITLE
Sage causing failures on travis

### ISSUE THREAD

**Issue by sidhantnagpal** [sympy/sympy#14766]
The error being thrown is:
```python
+sage -t sympy/external/tests/test_sage.py
init.sage does not exist ... creating
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/bin/sage-runtests", line 81, in <module>
    from sage.doctest.control import DocTestController
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sage/doctest/control.py", line 33, in <module>
    from .sources import FileDocTestSource, DictAsObject
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sage/doctest/sources.py", line 33, in <module>
    from .parsing import SageDocTestParser
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sage/doctest/parsing.py", line 52, in <module>
    from sage.all import RealIntervalField
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sage/all.py", line 113, in <module>
    from sage.schemes.all    import *
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sage/schemes/all.py", line 32, in <module>
    from .elliptic_curves.all import *
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sage/schemes/elliptic_curves/all.py", line 31, in <module>
    from .ell_rational_field import cremona_curves, cremona_optimal_curves
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sage/schemes/elliptic_curves/ell_rational_field.py", line 59, in <module>
    from . import ell_modular_symbols
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sage/schemes/elliptic_curves/ell_modular_symbols.py", line 98, in <module>
    from sage.libs.eclib.newforms import ECModularSymbol
ImportError: libec.so.3: cannot open shared object file: No such file or directory
```

**Comment by asmeurer** [comment]
CC @isuruf

**Comment by asmeurer** [comment]
I don't know what the issue is, but it looks like the recipe only imports `sage` instead of `sage.all` in the tests.

**Comment by asmeurer** [comment]
Here is a build with the failure https://travis-ci.org/sympy/sympy/jobs/387181728
