### ISSUE TITLE
Substituiton of UndefinedFunction in Integral fails

### ISSUE THREAD

**Issue by cklb** [sympy/sympy#14796]
Consider the problem

```
import sympy as sp
x = sp.symbols("x")
f, g = sp.symbols("f g", cls=sp.Function)
expr = f(x) + f(1) + 10
```
where `expr.subs(f, g)` yields: `g(1) + g(x) + 10`. But if the same expression is the argument of an integral
```
int_expr = sp.Integral(expr, (x, 0, 1))
```
the substitution `int_expr.subs(f, g)` fails with 

> Traceback (most recent call last):
>   File "/home/cklb/workspace/sympy/sympy/core/cache.py", line 93, in wrapper
>     retval = cfunc(*args, **kwargs)
>   File "/home/cklb/workspace/sympy/sympy/core/basic.py", line 1031, in _subs
>     rv = self._eval_subs(old, new)
>   File "/home/cklb/workspace/sympy/sympy/concrete/expr_with_limits.py", line 346, in _eval_subs
>     if len(xab[0].free_symbols.intersection(old.free_symbols)) != 0:
> TypeError: 'property' object is not iterable .

Herein, `old` is the `UndefinedFunction` f and `old.free_symbols` is returning the property object.
As it occures to me, polling the property `free_symbols` should return a (possibly) empty set which is what the `_eval_subs` routine is looking for. Since I was not able to deduce where this property is handled that's all I have to offer as a starting point.

I'm aware of the fact that doing a `int_expr.subs(f(x), g(x))` won't fail but this will not substitude `f(1)`, thus yielding  `Integral(f(1) + g(x) + 10, (x, 0, 1))`. 

My current workaround is to use the rather cumbersome call
```
int_expr.replace(f, lambda _x: g(_x))
```
which correctly yields  `Integral(g(1) + g(x) + 10, (x, 0, 1))` but doesn't scale nicely if the involved functions depend on different ammounts of parameters.

**Comment by DarylMcCullough** [comment]
I'd like to take a crack at working on this.

**Comment by DarylMcCullough** [comment]
Okay, looking into the problem, when you're doing `expr.subs(new, old)` and `expr` is an integral, then there is code that checks for the properties `free_symbols` and `args` and `atoms` of the `old` argument. In the case that `old` is an `UndefinedFunction`, it doesn't have any args or atoms or free_symbols. But the weird thing about the implementation is that `new.free_symbols` doesn't simply return the empty list, it returns a `property` object. I don't completely understand what that means, but you can't iterate over it. It seems to me that a function symbol should have no args and no free_symbols and no atoms.

I really don't understand the code. (in `sympy/concrete/expr_with_limits.py`) There is an explicit check if `old` is an `UndefinedFunction`, and then afterwards there is a call to `old.args`. I don't see under what circumstances that should ever return anything nonempty. Only a function application can have arguments, right?

**Comment by DarylMcCullough** [comment]
I was able to fix cklb's bug, but I'm a little worried about whether a more major revision is needed to address substitution within expressions. As I said in the above comment, I don't really understand what `.atoms`, `.args` and `.free_symbols` are supposed to do for objects of type `FunctionClass`. Should they raise an error? Should they return an empty list? Currently, they return a `property` object--I don't know what that means.

**Comment by DarylMcCullough** [comment]
Okay,, I'm not sure what the original reasoning was, but function symbols are represented in SymPy by classes, not objects. So for example `cos(x)` is an object of type `cos`. That explains why `cos.free_symbols` returns a property; that's saying that `free_symbols` is a property of objects of type `cos`. It isn't returning the free symbols of the `cos` object.

So function names are not objects in their own right, unlike expressions and symbols.

There are some kinds of mathematics that treat function names in exactly the same way as variable names. For example, the Lambda calculus. But given that SymPy didn't go down this road, my inclination would be to just disallow substitution to take a function name as an argument. I'm going to check through the code and examples and see if it would break anything that already works to do this.

It definitely is in an inconsistency to allow you to replace `f` by `cos` in `f(x)` to get `cos(x)`, but to raise an error when you try to replace `f` by `cos` in `Integral(f(x), (x,0,1)`. Either they both should raise an error, or neither should.

**Comment by asmeurer** [comment]
You can use `int_expr.replace(f, g)` to replace `f` with `g`. `subs` presently doesn't support replacing function objects. I'm not sure if support should be added.

**Comment by DarylMcCullough** [comment]
asmeurer,

My feeling is that if the program doesn't want to support replacing function names, then it should raise an exception, rather than sometimes work and sometimes not. As I said, there is no reason for

`f(x).subs(f,g)`

to result in

`g(x)`

and yet

`Integral(f(x), (x, 0, 1)).subs(f,g)`

to raise an exception. (Especially not the exception 

`TypeError: 'property' object is not iterable .`

My suggestion is that if we don't want to support that kind of substitution, then it should raise a meaningful exception, and should do so consistently. Perhaps `subs(f,g)` should always raise an exception if `f` or `g` is a function name.

**Comment by cklb** [comment]
First things first: I want to thank you both very much for your replies.

If `subs` is not meant to replace function objects I'm perfectly fine with that, but as Daryl stated it should be more consistent in its behaviour. In favour of this functionality, I might add that `_eval_subs` of `ExprWithLimits` already includes cases for `AppliedUndef` and `UndefindFunction` it just doesn't manage to reach those lines due to the problem stated in the initial comment.

For now, I'll go with  `replace(f, g)`. I don't now why this didn't come to my mind earlier.

**Comment by DarylMcCullough** [comment]
I don't know whether it was incorporated, or not, but fixing things so that

```Integral(f(x) + f(1) + 10,(x, 0, 1)).subs(f,g)```

works to produce

 ```Integral(g(x) + g(1) + 10,(x, 0, 1))```

was not too difficult. The problem as I found out was that the substitution code looks for things like `exp.args` and `exp.free_symbols` and `exp.atoms`. None of those work if `exp` is a function name. My fix is just to check if the substitution involves something of type `FunctionClass`, and then assume that it has no args or free-symbols or atoms.

So my fix works, even though it doesn't address the philosophical question of whether we want to substitute function names.

**Comment by czgdp1807** [comment]
The issue still persists on `master` so it is open for work.
