### ISSUE TITLE
Logical operators don't have is_commutative setm subs fails with simultaneous=True

### ISSUE THREAD

**Issue by arielbro** [sympy/sympy#14836]
"And" and "Or" inherit is_commutative, but the other logical operators in sympy.logic.boolalg don't have this field set.

This means that using subs with simultaneous=True and one of those operators as a replacement causes an error - 
`from sympy import *
x, y = symbols('x y')
Nand(x, y).subs({x: Nand(x, y)}, simultaneous=True)`

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/core/basic.py", line 889, in subs
    d = Dummy(commutative=new.is_commutative)
  File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/core/symbol.py", line 205, in __new__
    cls._sanitize(assumptions, cls)
  File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/core/symbol.py", line 65, in _sanitize
    '%scommutativity must be True or False.' % whose)
ValueError: Dummy commutativity must be True or False.`

Discovered by user6655984 in stackoverflow, more details [here](https://stackoverflow.com/questions/51013093/simultaneous-replacement-of-sympy-logic-function)

**Comment by iamarshsingh** [comment]
Seems like just adding `is_commutative = True` in `sympy.logic.boolalg.And` is not working. After making the change, we are getting error

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/arshdeep/Local Disk/Projects/Python/sympy/sympy/core/basic.py", line 910, in subs
    rv = rv._subs(old, d*m, **kwargs)
  File "/media/arshdeep/Local Disk/Projects/Python/sympy/sympy/core/basic.py", line 1033, in _subs
    rv = fallback(self, old, new)
  File "/media/arshdeep/Local Disk/Projects/Python/sympy/sympy/core/basic.py", line 1005, in fallback
    arg = arg._subs(old, new, **hints)
  File "/media/arshdeep/Local Disk/Projects/Python/sympy/sympy/core/basic.py", line 1033, in _subs
    rv = fallback(self, old, new)
  File "/media/arshdeep/Local Disk/Projects/Python/sympy/sympy/core/basic.py", line 1010, in fallback
    rv = self.func(*args)
  File "/media/arshdeep/Local Disk/Projects/Python/sympy/sympy/core/operations.py", line 411, in __new__
    _args = frozenset(cls._new_args_filter(args))
  File "/media/arshdeep/Local Disk/Projects/Python/sympy/sympy/logic/boolalg.py", line 537, in _new_args_filter
    args = BooleanFunction.binary_check_and_simplify(*args)
  File "/media/arshdeep/Local Disk/Projects/Python/sympy/sympy/logic/boolalg.py", line 436, in binary_check_and_simplify
    args = [as_Boolean(i) for i in args]
  File "/media/arshdeep/Local Disk/Projects/Python/sympy/sympy/logic/boolalg.py", line 436, in <listcomp>
    args = [as_Boolean(i) for i in args]
  File "/media/arshdeep/Local Disk/Projects/Python/sympy/sympy/logic/boolalg.py", line 54, in as_Boolean
    raise TypeError('expecting bool or Boolean, not `%s`.' % e)
TypeError: expecting bool or Boolean, not `_Dummy_18*_Dummy_19`.

Error is caused because as_Boolean(i) function( in sympy.logic.boolalg) in which the current parameter passed is of type `sympy.core.mul.Mul` which is not implemented in as_Boolean(i) doen't support

**Comment by arielbro** [comment]
Any update on this?
I'm not familiar enough with sympy to know how to mitigate this bug on user side (including finding out exactly when it manifests)

**Comment by oscargus** [comment]
The problem is that the replacement is done using a multiplication of two temporary (`Dummy`) symbols which is not allowed as an input to a boolean function. It happens here:
https://github.com/sympy/sympy/blob/f57d98d8e54169678e8bba7805f0f71546c11e75/sympy/core/basic.py#L940-L944

The solution would probably be to detect that there are boolean functions involved and in that case not multiply the two `Dummy` symbols together.

**Comment by oscarbenjamin** [comment]
> The solution would probably be to detect that there are boolean functions involved and in that case not multiply the two `Dummy` symbols together.

The quoted code looks hackish to me. I think that the best solution would be to remove it and write some explicit code that directly achieves whatever effect the dummy substitution gives. Basic routines should not need to have special cases for Boolean, Expr etc and the routines should be sufficiently general that subclasses don't need to override them.

**Comment by oscargus** [comment]
There is a variable `hack2` just above it (with corresponding keyword argument), so, yes, there are probably ways to improve it as well.
