### ISSUE TITLE
Error while executing sympy on R Studio

### ISSUE THREAD

**Issue by polexo** [sympy/sympy#14900]
Hello,

I went to this error while executing sympy on R Studio.

```
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.io.IOException: Resetting to invalid mark
	at java.io.BufferedInputStream.reset(Unknown Source)
	at org.python.core.ParserFacade.readEncoding(ParserFacade.java:394)
	at org.python.core.ParserFacade.prepBufReader(ParserFacade.java:301)
	at org.python.core.ParserFacade.prepBufReader(ParserFacade.java:356)
	at org.python.core.ParserFacade.parse(ParserFacade.java:200)
	at org.python.core.Py.compile_flags(Py.java:1685)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at RJavaTools.invokeMethod(RJavaTools.java:386)

java.io.IOException: java.io.IOException: Resetting to invalid mark 
```

**Comment by oscarbenjamin** [comment]
Do you have any information about how this happened?

**Comment by asmeurer** [comment]
What code did you run that resulted in this? The Java traceback is not very useful. Was there any kind of Python traceback as well?
