### ISSUE TITLE
simplify(log(foot) + foo) raises an error

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#14932]
```
>>> a=log(x)
>>> from sympy.physics.units import foot, inch
>>> b=log(foot)
>>> a+b
log(foot) + log(x)
>>> simplify(_)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\simplify\simplify.py", line 525, in simplify

    original_expr = expr = signsimp(expr)
  File "sympy\simplify\simplify.py", line 375, in signsimp

    e = sub_post(sub_pre(expr))
  File "sympy\simplify\cse_opts.py", line 15, in sub_pre
    reps = [a for a in e.atoms(Add) if a.could_extract_minus_sign()]
  File "sympy\simplify\cse_opts.py", line 15, in <listcomp
>
    reps = [a for a in e.atoms(Add) if a.could_extract_minus_sign()]
  File "sympy\core\expr.py", line 2272, in could_extract_m
inus_sign
    (negative_self).extract_multiplicatively(-1) is not None)
  File "sympy\core\expr.py", line 2037, in extract_multipl
icatively
    quotient = self / c
  File "sympy\core\decorators.py", line 91, in __sympifyit
_wrapper
    return func(a, b)
  File "sympy\core\decorators.py", line 132, in binary_op_
wrapper
    return func(self, other)
  File "sympy\core\expr.py", line 177, in __div__
    return Mul(self, Pow(other, S.NegativeOne))
  File "sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy\core\operations.py", line 48, in __new__
    obj = cls._exec_constructor_postprocessors(obj)
  File "sympy\core\basic.py", line 1724, in _exec_construc
tor_postprocessors
    obj = f(obj)
  File "sympy\physics\units\quantities.py", line 261, in _
Quantity_constructor_postprocessor_Add
    for i in expr.args
  File "sympy\physics\units\quantities.py", line 262, in <
setcomp>
    if i.free_symbols == set()  # do not raise if there are symbols
  File "sympy\physics\units\dimensions.py", line 442, in g
et_dimensional_dependencies
    return {str(i): j for i, j in dimdep.items()}
AttributeError: 'NoneType' object has no attribute 'items'
```

I get similar errors if I replace `log(x)` with `log(2)`, `2` and `log(inch)`.

**Comment by smichr** [comment]
Here is a suggested fix:

```diff
diff --git a/sympy/physics/units/dimensions.py b/sympy/physics/units/dimensions.py
index 2aabd59..561f06d 100644
--- a/sympy/physics/units/dimensions.py
+++ b/sympy/physics/units/dimensions.py
@@ -427,8 +427,10 @@ def _get_dimensional_dependencies_for_name(self, name):

             if isinstance(result, Dimension):
                 return dimsys_default.get_dimensional_dependencies(result)
-            # TODO shall we consider a result that is not a dimension?
-            # return Dimension._get_dimensional_dependencies_for_name(result)
+            elif result.func == name.func:
+                return {}
+            else:
+                return dimsys_default._get_dimensional_dependencies_for_name(result)

     def get_dimensional_dependencies(self, name, mark_dimensionless=False):
         if isinstance(name, Dimension):
diff --git a/sympy/physics/units/tests/test_quantities.py b/sympy/physics/units/
tests/test_quantities.py
index 8649301..af5b610 100644
--- a/sympy/physics/units/tests/test_quantities.py
+++ b/sympy/physics/units/tests/test_quantities.py
@@ -459,3 +459,7 @@ def test_eval_subs():
     expr2 = force/mass
     units = {force:gravitational_constant*kilogram**2/meter**2, mass:kilogram}
     assert expr2.subs(units) == gravitational_constant*kilogram/meter**2
+
+
+def test_issue_14923():
+    assert (log(inch) - log(2)).simplify() == log(inch/2)
```
