### ISSUE TITLE
AttributeError: 'list' object has no attribute 'xreplace'

### ISSUE THREAD

**Issue by drufat** [sympy/sympy#14941]
The following code used to work in the previous version of sympy:
```
import sympy as sy
x, y = sy.Dummy(), sy.Dummy()
func = sy.lambdify([x, y], [y, x], 'sympy')

```

However, with the latest version (1.2), I get an error:

```
Traceback (most recent call last):
  File "/home/foo/.local/lib/python3.6/site-packages/sympy/utilities/lambdify.py", line 750, in _subexpr
    expr = sympify(expr).xreplace(dummies_dict)
AttributeError: 'list' object has no attribute 'xreplace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trial.py", line 3, in <module>
    func = sy.lambdify([x, y], [y, x], 'sympy')
  File "/home/foo/.local/lib/python3.6/site-packages/sympy/utilities/lambdify.py", line 456, in lambdify
    funcstr = funcprinter.doprint(funcname, args, expr)
  File "/home/foo/.local/lib/python3.6/site-packages/sympy/utilities/lambdify.py", line 661, in doprint
    argstrs, expr = self._preprocess(args, expr)
  File "/home/foo/.local/lib/python3.6/site-packages/sympy/utilities/lambdify.py", line 732, in _preprocess
    expr = self._subexpr(expr, {arg: dummy})
  File "/home/foo/.local/lib/python3.6/site-packages/sympy/utilities/lambdify.py", line 761, in _subexpr
    expr = [sub_expr(sympify(a), dummies_dict) for a in expr]
  File "/home/foo/.local/lib/python3.6/site-packages/sympy/utilities/lambdify.py", line 761, in <listcomp>
    expr = [sub_expr(sympify(a), dummies_dict) for a in expr]
NameError: name 'sub_expr' is not defined

```

Any idea what is causing this error?

**Comment by jksuom** [comment]
`sub_expr` should probably be `_subexpr`.
