### ISSUE TITLE
Finding eigenvectors lead to PolynomialError

### ISSUE THREAD

**Issue by thatlittleboy** [sympy/sympy#15076]
Sympy: Version 1.2

In the example below, I am trying to find the set of symbolic eigenvectors for a 4x4 matrix:

```
from sympy import *
from sympy.abc import x, y, z
M = Matrix([[1, cos(x/4+y/4), cos(x/4+z/4), cos(y/4+z/4)],
            [cos(x/4+y/4), 1, cos(y/4-z/4), cos(x/4 - z/4)],
            [cos(x/4+z/4), cos(y/4-z/4), 1, cos(x/4-y/4)],
            [cos(y/4+z/4), cos(x/4-z/4), cos(x/4-y/4), 1]])
print(M.eigenvects())
```

When I run this, I get the following error:

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\polyutils.py", line 209, in _parallel_dict_from_expr_if_gens
    monom[indices[base]] = exp
KeyError: cos(x/2 + y/2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[redacted file path]/scrap_file.py", line 45, in <module>
    print(M.eigenvects())
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\matrices\matrices.py", line 1193, in eigenvects
    **flags)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\matrices\matrices.py", line 1129, in eigenvals
    eigs = roots(mat.charpoly(x=Dummy('x')), **flags)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\polyroots.py", line 1018, in roots
    for r in _try_heuristics(f):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\polyroots.py", line 966, in _try_heuristics
    result += roots_quartic(f)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\polyroots.py", line 325, in roots_quartic
    sols = _roots_quartic_euler(e, f, g, aon4)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\polyroots.py", line 231, in _roots_quartic_euler
    xsols = list(roots(Poly(eq, x), cubics=False).keys())
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\polytools.py", line 129, in __new__
    return cls._from_expr(rep, opt)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\polytools.py", line 239, in _from_expr
    rep, opt = _dict_from_expr(rep, opt)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\polyutils.py", line 366, in _dict_from_expr
    rep, gens = _dict_from_expr_if_gens(expr, opt)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\polyutils.py", line 305, in _dict_from_expr_if_gens
    (poly,), gens = _parallel_dict_from_expr_if_gens((expr,), opt)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\polyutils.py", line 215, in _parallel_dict_from_expr_if_gens
    "the set of generators." % factor)
sympy.polys.polyerrors.PolynomialError: cos(x/2 + y/2)**2 contains an element of the set of generators.

Process finished with exit code 1
```

A simpler example like `M = Matrix([[1, cos(x/4+y/4)], [cos(y/4-z/4), cos(x/4 - z/4)]])` works just fine.

**Comment by jksuom** [comment]
The error is caused by a bug in `_roots_quartic_euler`. It should define `x` as a `Dummy` on [this line](https://github.com/sympy/sympy/blob/master/sympy/polys/polyroots.py#L229).

That should be easy to fix, but the solution of the quartic characteristic polynomial may prove too hard nevertheless.

**Comment by thatlittleboy** [comment]
@jksuom Thanks for looking into this and locating the bug. I suspect that solutions might be too complex to find as well, but just wanted to give it a try.

**Comment by jksuom** [comment]
This matrix example is not a good choice for testing an issue in `_roots_quartic_euler` that has nothing to do with matrices. I would use something like this (added to test_polyroots.py, together with suitable imports):

    sol = roots_quartic(Poly(t**4 -  6*t**2 + t/x - 3, t))
    assert sol[0].has(x)

This test will currently raise a PolynomialError.

**Comment by bPhysicist** [comment]
The following change:
```diff
@@ -226,7 +226,7 @@ def _roots_quartic_euler(p, q, r, a):
     -sqrt(32*sqrt(5)/125 + 16/5) + 4*sqrt(5)/5
     """
     # solve the resolvent equation
-    x = Symbol('x')
+    x = Dummy('x')
     eq = 64*x**3 + 32*p*x**2 + (4*p**2 - 16*r)*x - q**2
     xsols = list(roots(Poly(eq, x), cubics=False).keys())
     xsols = [sol for sol in xsols if sol.is_rational and sol.is_nonzero]
```
gives an error when running the test_ode.py test:
```
___________________________________________ sympy/solvers/tests/test_ode.py:test_separable_reduced ___________________________________________
Traceback (most recent call last):
  File "/home/pc/sympy/sympy/solvers/tests/test_ode.py", line 2531, in test_separable_reduced
    assert sol.lhs - sol.rhs == \
AttributeError: 'list' object has no attribute 'lhs'
```
https://github.com/sympy/sympy/blob/master/sympy/solvers/tests/test_ode.py#L2531

**Comment by jksuom** [comment]
This test provided with two comments

    # this is the equation that does not like x to be real
    # generates PolynomialError in solve attempt

If `x` is defined by `Symbol('x')`, then it will be the same as `x` defined in `_roots_quartic_euler`, and therefore it will raise PolynomialError. `dsolve` will then return the solution in implicit form as shown on the assert line.

If `x` is defined by `Symbol('x', real=True)`, it will be different from the symbol `x` in `_roots_quartic_euler`, Then the computation can continue with no error and four solutions are returned. The solutions are far too complicated to be of practical use but there seems to be no reason to doubt their correctness.

This will also happen, if `Symbol` is replaced by `Dummy`. I think that the comments (that depend on a bug) should be removed and the assertion could be replaced with something like

    assert len(sol) = 4

There is probably no reason to copy the solutions as such.
