### ISSUE TITLE
Sympy's CSE does not like expressions that are just a number

### ISSUE THREAD

**Issue by mmohrhard** [sympy/sympy#15082]
The following code will fail with an error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/sympy/simplify/cse_main.py", line 500, in cse
    for e in exprs:
TypeError: 'int' object is not iterable

import sympy
expr = 1
sympy.cse(expr)

However adding the following to simplify/cse_opts.py fixes the issue:

if isinstance(e, numbers.Number):
    return e

**Comment by asmeurer** [comment]
A better solution is to call `_sympify` on the arguments at the top of `cse`.

**Comment by bjodah** [comment]
Don't think a fix is needed. This actually works for me on 1.2 and master, but not 1.1.1
