### ISSUE TITLE
Solving quartic with complex coefficients fails

### ISSUE THREAD

**Issue by johnomotani** [sympy/sympy#15090]
Minimal example, using sympy 1.2.0:
```
import sympy

x = sympy.Symbol('x')
i = sympy.I

quartic = i*x**4 + x**3 + x**2 + 1.

solutions = sympy.solve(quartic)
```
produces
```
Traceback (most recent call last):
  File "./sympy-complex-quartic.py", line 10, in <module>
    solutions = sympy.solve(quartic)
  File "/home/jomotani/.local/lib/python3.5/site-packages/sympy/solvers/solvers.py", line 1231, in solve
    solution = nfloat(solution, exponent=False)
  File "/home/jomotani/.local/lib/python3.5/site-packages/sympy/core/function.py", line 2769, in nfloat
    return type(expr)([nfloat(a, n, exponent) for a in expr])
  File "/home/jomotani/.local/lib/python3.5/site-packages/sympy/core/function.py", line 2769, in <listcomp>
    return type(expr)([nfloat(a, n, exponent) for a in expr])
  File "/home/jomotani/.local/lib/python3.5/site-packages/sympy/core/function.py", line 2803, in nfloat
    lambda x: isinstance(x, Function)))
  File "/home/jomotani/.local/lib/python3.5/site-packages/sympy/core/basic.py", line 1115, in xreplace
    value, _ = self._xreplace(rule)
  File "/home/jomotani/.local/lib/python3.5/site-packages/sympy/core/basic.py", line 1123, in _xreplace
    return rule[self], True
  File "/home/jomotani/.local/lib/python3.5/site-packages/sympy/core/rules.py", line 59, in __getitem__
    return self._transform(key)
  File "/home/jomotani/.local/lib/python3.5/site-packages/sympy/core/function.py", line 2802, in <lambda>
    lambda x: x.func(*nfloat(x.args, n, exponent)),
  File "/home/jomotani/.local/lib/python3.5/site-packages/sympy/core/function.py", line 2769, in nfloat
    return type(expr)([nfloat(a, n, exponent) for a in expr])
  File "/home/jomotani/.local/lib/python3.5/site-packages/sympy/core/function.py", line 2769, in <listcomp>
    return type(expr)([nfloat(a, n, exponent) for a in expr])
  File "/home/jomotani/.local/lib/python3.5/site-packages/sympy/core/function.py", line 2769, in nfloat
    return type(expr)([nfloat(a, n, exponent) for a in expr])
TypeError: __new__() missing 1 required positional argument: 'cond'
```

Note that changing the float `1.` to an int sympy produces solutions. They are Piecewise functions, but that would be OK because I could then simplify and evaluate them. My actual problem has complex float coefficients.

The problem seems to be evaluating nfloat(a, n, False) where a is a Piecewise. However, this should not be a problem because the Piecewise could be simplified into an expression that could be evaluated. Specifically, evaluating `nfloat(a, n, exponent)` fails, where 
```
a=Piecewise((I/4 + sqrt(-1/2 + 2*((-3/256 - 15*I/16)*(3/8 - I)/3 + (-1/8 + I/2)**2/8
- (3/8 - I)**3/108)**(1/3) + 2*I*(-1/8 + I/2)/sqrt(-1/4 + 2*I/3 - 2*((-3/256 -
15*I/16)*(3/8 - I)/3 + (-1/8 + I/2)**2/8 - (3/8 - I)**3/108)**(1/3)) + 4*I/3)/2 +
sqrt(-1/4 + 2*I/3 - 2*((-3/256 - 15*I/16)*(3/8 - I)/3 + (-1/8 + I/2)**2/8 -
(3/8 - I)**3/108)**(1/3))/2,
Eq(3/256 - (3/8 - I)**2/12 + 15*I/16, 0)),
(sqrt(-1/4 - 2*(3/256 - (3/8 - I)**2/12 + 15*I/16)/(3*(sqrt((3/256 - (3/8 - I)**2/12
+ 15*I/16)**3/27 + ((-3/256 - 15*I/16)*(3/8 - I)/3 + (-1/8 + I/2)**2/8 -
(3/8 - I)**3/108)**2/4) + (3/8 - I)**3/216 - (-1/8 + I/2)**2/16 -
(-3/256 - 15*I/16)*(3/8 - I)/6)**(1/3)) + 2*(sqrt((3/256 - (3/8 - I)**2/12 + 15*I/16)**3/27
+ ((-3/256 - 15*I/16)*(3/8 - I)/3 + (-1/8 + I/2)**2/8 - (3/8 - I)**3/108)**2/4) +
(3/8 - I)**3/216 - (-1/8 + I/2)**2/16 - (-3/256 - 15*I/16)*(3/8 - I)/6)**(1/3) + 2*I/3)/2 + I/4
+ sqrt(-1/2 + 2*I*(-1/8 + I/2)/sqrt(-1/4 - 2*(3/256 - (3/8 - I)**2/12 +
15*I/16)/(3*(sqrt((3/256 - (3/8 - I)**2/12 + 15*I/16)**3/27 + ((-3/256 - 15*I/16)*(3/8 - I)/3
+ (-1/8 + I/2)**2/8 - (3/8 - I)**3/108)**2/4) + (3/8 - I)**3/216 - (-1/8 + I/2)**2/16 -
(-3/256 - 15*I/16)*(3/8 - I)/6)**(1/3)) + 2*(sqrt((3/256 - (3/8 - I)**2/12 + 15*I/16)**3/27 +
((-3/256 - 15*I/16)*(3/8 - I)/3 + (-1/8 + I/2)**2/8 - (3/8 - I)**3/108)**2/4) +
(3/8 - I)**3/216 - (-1/8 + I/2)**2/16 - (-3/256 - 15*I/16)*(3/8 - I)/6)**(1/3) + 2*I/3)
- 2*(sqrt((3/256 - (3/8 - I)**2/12 + 15*I/16)**3/27 + ((-3/256 - 15*I/16)*(3/8 - I)/3
+ (-1/8 + I/2)**2/8 - (3/8 - I)**3/108)**2/4) + (3/8 - I)**3/216 - (-1/8 + I/2)**2/16
- (-3/256 - 15*I/16)*(3/8 - I)/6)**(1/3) + 2*(3/256 - (3/8 - I)**2/12 +
15*I/16)/(3*(sqrt((3/256 - (3/8 - I)**2/12 + 15*I/16)**3/27 + ((-3/256 - 15*I/16)*(3/8 - I)/3
+ (-1/8 + I/2)**2/8 - (3/8 - I)**3/108)**2/4) + (3/8 - I)**3/216 - (-1/8 + I/2)**2/16
- (-3/256 - 15*I/16)*(3/8 - I)/6)**(1/3)) + 4*I/3)/2,
True))

n=15

exponent=False
```
but evaluating the first condition gives
```
>>> nfloat(Eq(3/256 - (3/8 - I)**2/12 + 15*I/16, 0), 15, False)
False
```
and the Piecewise is equivalent to the second value, which nfloat has no problem with
```
>>> nfloat(sqrt(-1/4 - 2*(3/256 - (3/8 - I)**2/12 + 15*I/16)/(3*(sqrt((3/256 - (3/8 - I)**2/12 + 15*I/16)**3/27 + ((-3/256 - 15*I/16)*(3/8 - I)/3 + (-1/8 + I/2)**2/8 - (3/8 - I)**3/108)**2/4) + (3/8 - I)**3/216 - (-1/8 + I/2)**2/16 - (-3/256 - 15*I/16)*(3/8 - I)/6)**(1/3)) + 2*(sqrt((3/256 - (3/8 - I)**2/12 + 15*I/16)**3/27 + ((-3/256 - 15*I/16)*(3/8 - I)/3 + (-1/8 + I/2)**2/8 - (3/8 - I)**3/108)**2/4) + (3/8 - I)**3/216 - (-1/8 + I/2)**2/16 - (-3/256 - 15*I/16)*(3/8 - I)/6)**(1/3) + 2*I/3)/2 + I/4 + sqrt(-1/2 + 2*I*(-1/8 + I/2)/sqrt(-1/4 - 2*(3/256 - (3/8 - I)**2/12 + 15*I/16)/(3*(sqrt((3/256 - (3/8 - I)**2/12 + 15*I/16)**3/27 + ((-3/256 - 15*I/16)*(3/8 - I)/3 + (-1/8 + I/2)**2/8 - (3/8 - I)**3/108)**2/4) + (3/8 - I)**3/216 - (-1/8 + I/2)**2/16 - (-3/256 - 15*I/16)*(3/8 - I)/6)**(1/3)) + 2*(sqrt((3/256 - (3/8 - I)**2/12 + 15*I/16)**3/27 + ((-3/256 - 15*I/16)*(3/8 - I)/3 + (-1/8 + I/2)**2/8 - (3/8 - I)**3/108)**2/4) + (3/8 - I)**3/216 - (-1/8 + I/2)**2/16 - (-3/256 - 15*I/16)*(3/8 - I)/6)**(1/3) + 2*I/3) - 2*(sqrt((3/256 - (3/8 - I)**2/12 + 15*I/16)**3/27 + ((-3/256 - 15*I/16)*(3/8 - I)/3 + (-1/8 + I/2)**2/8 - (3/8 - I)**3/108)**2/4) + (3/8 - I)**3/216 - (-1/8 + I/2)**2/16 - (-3/256 - 15*I/16)*(3/8 - I)/6)**(1/3) + 2*(3/256 - (3/8 - I)**2/12 + 15*I/16)/(3*(sqrt((3/256 - (3/8 - I)**2/12 + 15*I/16)**3/27 + ((-3/256 - 15*I/16)*(3/8 - I)/3 + (-1/8 + I/2)**2/8 - (3/8 - I)**3/108)**2/4) + (3/8 - I)**3/216 - (-1/8 + I/2)**2/16 - (-3/256 - 15*I/16)*(3/8 - I)/6)**(1/3)) + 4*I/3)/2, 15, False)
0.780156137306755 + 1.03569383548369*I
```
so this seems like it should be a solvable issue?

**Comment by jksuom** [comment]
There should probably be a * in front of the list form argument on this line:

    return type(expr)([nfloat(a, n, exponent) for a in expr])

Otherwise there is only one argument.

**Comment by oscarbenjamin** [comment]
I don't see this problem any more on master:
```julia
In [9]: quartic = I*x**4 + x**3 + x**1 + 1                                                                                                                    

In [11]: solve(quartic)[0]                                                                                                                                    
Out[11]: 
                                                                                                                                                            
                                                                                                                                                            
                                                                                                                                                            
                                                                                                                                                            
                                                                                                                                                            
                                                                                                                                                            
                                                                                                                                                            
                                                                                                                                                            
                    _________________________________________________________________________________________________________________________               
                   ╱                                                                           _____________________________________________                
                  ╱                                                                           ╱               ________________________                      
                 ╱                                                                           ╱               ╱                      2                       
                ╱                                                                           ╱               ╱                ⎛1   ⅈ⎞                        
               ╱                                                                           ╱               ╱             3   ⎜─ - ─⎟                       ╱
              ╱        1                         2⋅(-1/4 + ⅈ)                             ╱       1       ╱    (-1/4 + ⅈ)    ⎝8   8⎠     ⅈ                ╱ 
             ╱       - ─ - ─────────────────────────────────────────────────────── + 2⋅3 ╱      - ── +   ╱     ─────────── + ────────  + ──              ╱  
            ╱          4             _____________________________________________     ╲╱         16   ╲╱           27          4        16             ╱   
           ╱                        ╱               ________________________                                                                           ╱    
          ╱                        ╱               ╱                      2                                                                           ╱     
         ╱                        ╱               ╱                ⎛1   ⅈ⎞                                                                           ╱      
        ╱                        ╱               ╱             3   ⎜─ - ─⎟                                                                          ╱       
       ╱                        ╱       1       ╱    (-1/4 + ⅈ)    ⎝8   8⎠     ⅈ                                                                   ╱        
      ╱                    3⋅3 ╱      - ── +   ╱     ─────────── + ────────  + ──                                                                 ╱         
ⅈ   ╲╱                       ╲╱         16   ╲╱           27          4        16                                                               ╲╱          
─ - ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── + ────────────
4                                                                       2                                                                                   

            ________________________________________________________________________________________________________________________________________________
           ╱                                                                                                                                                
          ╱                                                                                                                                                 
         ╱                                                                                                                                                  
        ╱                                                                                                                                                   
       ╱                                                                                                                                                    
      ╱        1                                                                       7⋅ⅈ                                                                  
     ╱       - ─ - ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    ╱          2                     _______________________________________________________________________________________________________________________
   ╱                                ╱                                                                           ____________________________________________
  ╱                                ╱                                                                           ╱               ________________________     
 ╱                                ╱                                                                           ╱               ╱                      2      
╱                                ╱                                                                           ╱               ╱                ⎛1   ⅈ⎞       
                                ╱                                                                           ╱               ╱             3   ⎜─ - ─⎟       
                               ╱        1                         2⋅(-1/4 + ⅈ)                             ╱       1       ╱    (-1/4 + ⅈ)    ⎝8   8⎠     ⅈ 
                   4⋅         ╱       - ─ - ─────────────────────────────────────────────────────── + 2⋅3 ╱      - ── +   ╱     ─────────── + ────────  + ──
                             ╱          4             _____________________________________________     ╲╱         16   ╲╱           27          4        16
                            ╱                        ╱               ________________________                                                               
                           ╱                        ╱               ╱                      2                                                                
                          ╱                        ╱               ╱                ⎛1   ⅈ⎞                                                                 
                         ╱                        ╱               ╱             3   ⎜─ - ─⎟                                                                 
                        ╱                        ╱       1       ╱    (-1/4 + ⅈ)    ⎝8   8⎠     ⅈ                                                           
                       ╱                    3⋅3 ╱      - ── +   ╱     ─────────── + ────────  + ──                                                          
                     ╲╱                       ╲╱         16   ╲╱           27          4        16                                                          
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                                                   2                        

_______________________________________________________________________________________________________________________
               _____________________________________________                                                           
              ╱               ________________________                                                                 
             ╱               ╱                      2                                                                  
            ╱               ╱                ⎛1   ⅈ⎞                                                                   
           ╱               ╱             3   ⎜─ - ─⎟                                                                   
          ╱       1       ╱    (-1/4 + ⅈ)    ⎝8   8⎠     ⅈ                           2⋅(-1/4 + ⅈ)                      
── - 2⋅3 ╱      - ── +   ╱     ─────────── + ────────  + ──  + ─────────────────────────────────────────────────────── 
__     ╲╱         16   ╲╱           27          4        16              _____________________________________________ 
_                                                                       ╱               ________________________       
                                                                       ╱               ╱                      2        
                                                                      ╱               ╱                ⎛1   ⅈ⎞         
                                                                     ╱               ╱             3   ⎜─ - ─⎟         
                                                                    ╱       1       ╱    (-1/4 + ⅈ)    ⎝8   8⎠     ⅈ   
                                                               3⋅3 ╱      - ── +   ╱     ─────────── + ────────  + ──  
                                                                 ╲╱         16   ╲╱           27          4        16  
                                                                                                                       
                                                                                                                       
                                                                                                                       
                                                                                                                       
                                                                                                                       
                                                                                                                       
                                                                                                                       
                                                                                                                       
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
