### ISSUE TITLE
test_core_undefinedfunctions failing from pickling test

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#15116]
```
$ bin/test pickling
============================= test process starts ==============================
executable:         C:\Users\sylee\AppData\Local\Continuum\anaconda3\envs\myEnvironment\python.exe  (3.6.6-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python
numpy:              1.15.0
random seed:        42911788
hash randomization: on (PYTHONHASHSEED=1681503245)

sympy\utilities\tests\test_pickling.py[41] .........Ff..........ff..f..........f
ff..                                                                      [FAIL]

________________________________________________________________________________
_____ sympy\utilities\tests\test_pickling.py:test_core_undefinedfunctions ______
Traceback (most recent call last):
  File "c:\users\sylee\onedrive\documents\github\sympy\sympy\utilities\tests\test_pickling.py", line 154, in test_core_undefinedfunctions
    check(f, exclude=exclude)
  File "c:\users\sylee\onedrive\documents\github\sympy\sympy\utilities\tests\test_pickling.py", line 77, in check
    c(a, b, d1)
  File "c:\users\sylee\onedrive\documents\github\sympy\sympy\utilities\tests\test_pickling.py", line 76, in c
    assert getattr(b, i) == attr, "%s != %s, protocol: %s" % (getattr(b, i), attr, protocol)
AssertionError: {'__doc__': None, '_extra_kwargs': {}, '__module__': None, '_explicit_class_assumptions': {}, 'default_assumptions': {}, '_prop_handler': {'complex': <function Function._eval_is_complex at 0x00000257D7828730>, 'commutative': <function Function._eval_is_commutative at 0x00000257D7828EA0>, 'positive': <function Expr._eval_is_positive at 0x00000257D7828F28>, 'negative': <function Expr._eval_is_negative at 0x00000257D72DF048>}, '_nargs': None} != {'_extra_kwargs': {}, '__module__': None, '__doc__': None, '_explicit_class_assumptions': {}, 'default_assumptions': {}, '_prop_handler': {'complex': <function Function._eval_is_complex at 0x00000257D5945158>, 'commutative': <function Function._eval_is_commutative at 0x00000257D59450D0>, 'positive': <function Expr._eval_is_positive at 0x00000257D580D268>, 'negative': <function Expr._eval_is_negative at 0x00000257D580D2F0>}, '_nargs': None}, protocol: <module 'cloudpickle' from 'C:\\Users\\sylee\\AppData\\Local\\Continuum\\anaconda3\\envs\\myEnvironment\\lib\\site-packages\\cloudpickle\\__init__.py'>

=== tests finished: 33 passed, 1 failed, 7 expected to fail, in 1.87 seconds ===
DO *NOT* COMMIT!
```

My anaconda environment has `cloudpickle 0.5.3` installed.

My local machine fails on this test with the latest 1.2.1.dev version currently up to date with this repository, and I can give you more necessary system information if you need help tracing down this issue.

**Comment by asmeurer** [comment]
I get the failure too. I guess we aren't testing cloudpickle on Travis.

**Comment by asmeurer** [comment]
Looks like the test has always been broken (it fails on the commit that added the test f81e96b8ef7055e3d9510233c942600a33dcd6aa). 

I guess a version of cloudpickle broke it. I checked the versions that are on conda and the first version that breaks the test is 0.4.0.

**Comment by asmeurer** [comment]
Bisected to cloudpickle commit https://github.com/cloudpipe/cloudpickle/commit/aec80d21ddff84cf2a83dce3cb5921a9f58ffd05

**Comment by asmeurer** [comment]
I opened an upstream issue https://github.com/cloudpipe/cloudpickle/issues/190. I don't know if this affects functionality. `f == f1` and `f(x) == f1(x)` are both True (where `f = Function('f')` and `f1 = cloudpickle.loads(cloudpickle.dumps(f))`). 

At any rate, I would just change the test for now so that cloudpickle is excluded.

**Comment by asmeurer** [comment]
PR skipping the test at https://github.com/sympy/sympy/pull/15139. Once the upstream is fixed and released we can unskip the test again.
