### ISSUE TITLE
simplification of matrix expressions

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15120]
From https://stackoverflow.com/questions/51943198/how-to-simplify-matrix-expressions-in-sympy

```py
import sympy as sy
n = sy.symbols('n')
A = sy.MatrixSymbol("A",n,n)
B = sy.MatrixSymbol("B",n,n)
C = sy.MatrixSymbol("C",n,n)
M = A.inverse()*B.inverse() - A.inverse()*C*B.inverse()
a = B.inverse()*M.inverse()*A.inverse()
```

The question is how to simplify the expression, which is `B^-1*(A^-1*B^-1 - A^-1*C*B^-1)^-1*A^-1`. The expression can be simplified by factoring out the A^-1 from the inner term on the left and B^-1 on the right, which cancels the whole thing to `(I - C)**-1`. 

I expected nc_simplify to do this, but it didn't change the expression. `factor` did something, but it fails when you try to print it

```pytb
>>> b = factor(a)
>>> b
Traceback (most recent call last):
  File "./sympy/core/basic.py", line 408, in __repr__
    return sstr(self, order=None)
  File "./sympy/printing/str.py", line 847, in sstr
    s = p.doprint(expr)
  File "./sympy/printing/printer.py", line 249, in doprint
    return self._str(self._print(expr))
  File "./sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "./sympy/printing/str.py", line 335, in _print_MatMul
    [self.parenthesize(arg, precedence(expr)) for arg in expr.args]
  File "./sympy/printing/str.py", line 335, in <listcomp>
    [self.parenthesize(arg, precedence(expr)) for arg in expr.args]
  File "./sympy/printing/str.py", line 33, in parenthesize
    return self._print(item)
  File "./sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "./sympy/printing/str.py", line 212, in _print_Inverse
    return "%s^-1" % self.parenthesize(I.arg, PRECEDENCE["Pow"])
  File "./sympy/printing/str.py", line 31, in parenthesize
    return "(%s)" % self._print(item)
  File "./sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "./sympy/printing/str.py", line 344, in _print_MatAdd
    for arg in expr.args]
  File "./sympy/printing/str.py", line 344, in <listcomp>
    for arg in expr.args]
  File "./sympy/printing/str.py", line 33, in parenthesize
    return self._print(item)
  File "./sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "./sympy/printing/str.py", line 335, in _print_MatMul
    [self.parenthesize(arg, precedence(expr)) for arg in expr.args]
TypeError: sequence item 1: expected str instance, Symbol found
>>> pprint(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/printing/pretty/pretty.py", line 2381, in pretty_print
    use_unicode_sqrt_char=use_unicode_sqrt_char))
  File "./sympy/printing/pretty/pretty.py", line 2341, in pretty
    return pp.doprint(expr)
  File "./sympy/printing/pretty/pretty.py", line 62, in doprint
    return self._print(expr).render(**self._settings)
  File "./sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "./sympy/printing/pretty/pretty.py", line 846, in _print_MatMul
    args[i] = self._print(a)
  File "./sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "./sympy/printing/pretty/pretty.py", line 858, in _print_MatPow
    pform = self._print(expr.base)
  File "./sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "./sympy/printing/pretty/pretty.py", line 77, in _print_Symbol
    symb = pretty_symbol(e.name)
  File "./sympy/printing/pretty/pretty_symbology.py", line 510, in pretty_symbol
    name, sups, subs = split_super_sub(symb_name)
  File "./sympy/printing/conventions.py", line 30, in split_super_sub
    if len(text) == 0:
TypeError: object of type 'Symbol' has no len()
```

**Comment by asmeurer** [comment]
Regarding the printing errors, somehow `factor` is producing the same expression but with the `.name` in all the matrices replaced by a Symbol instead of a string, which breaks the printer. If Symbol is supported for `MatrixSymbol.name` the printers should be fixed. Otherwise `factor` needs to be fixed.

**Comment by asmeurer** [comment]
Most likely Symbol should be supported as that avoids str in .args, but I don't know if that is intentional.

**Comment by asmeurer** [comment]
The problem is that `factor_nc` calls itself recursively on the args of the expression. But it also calls `sympify()`, which converts the string name into a Symbol. 

We really should change `MatrixSymbol.args[0]` to just always be Symbol (`MatrixSymbo.name` should stay a string). This is a breaking change, though, so it might not be easy to fix. It's also unrelated to the problem at hand here (as far as I can tell, `factor_nc`, without this bug, doesn't actually work on the expression.

**Comment by asmeurer** [comment]
There's actually two issues here, getting the non-commutative expression to simplify, and getting the various simplification functions to work with matrix expressions. Currently even if you use nc_simplify it doesn't simplify the expression

```
>>> A, B, C = symbols("A B C", commutative=False)
>>> from sympy.simplify.simplify import nc_simplify
>>> nc_simplify(B**-1*(A**-1*B**-1 - A**-1*C*B**-1)**-1*A**-1)
(A*(-A**(-1)*C*B**(-1) + (B*A)**(-1))*B)**(-1)
>>> factor(B**-1*(A**-1*B**-1 - A**-1*C*B**-1)**-1*A**-1)
B**(-1)*(A**(-1)*(1 - C)*B**(-1))**(-1)*A**(-1)
>>> expand(B**-1*(A**-1*B**-1 - A**-1*C*B**-1)**-1*A**-1)
B**(-1)*(A**(-1)*B**(-1) - A**(-1)*C*B**(-1))**(-1)*A**(-1)
```

I'm unclear to what degree after fixing these functions matrix expressions would just work too. There is potentially more work to be done for matrix expressions because A*B is invalid for matrices if they mismatched shapes.

CC @valglad

**Comment by valglad** [comment]
We can get `nc_simplify` to handle this. At the moment, it only simplifies products and when given a sum, it simplifies each term. But if we did `factor` on the sum first, that might work better. It does work here:
```
>>> from sympy.simplify.simplify import nc_simplify
>>> from sympy import *
>>> A,B,C=symbols("A B C", commutative=False)
>>> expr = factor(B**-1*(A**-1*B**-1 - A**-1*C*B**-1)**-1*A**-1)
>>> nc_simplify(expr)
(1 - C)**(-1)
```
I'll get this into a PR.

**Comment by valglad** [comment]
I feel like getting `simplify` and other functions like that to work on instances of `MatrixExpr` would be easier if it was a subclass of `Expr` and `MatAdd`, `MutMul` and `MatPow` subclasses of `Add`, `Mul` and `Pow`. Not sure how compatible they would be in practice but it feels like it should be possible.

**Comment by RituRajSingh878** [comment]
```
TypeError                                 Traceback (most recent call last)
<ipython-input-4-db12e0a8f0c9> in <module>
----> 1 factor(a)

~/asumer/sympy/sympy/polys/polytools.py in factor(f, *gens, **args)
   6328 
   6329     try:
-> 6330         return _generic_factor(f, gens, args, method='factor')
   6331     except PolynomialError as msg:
   6332         if not f.is_commutative:

~/asumer/sympy/sympy/polys/polytools.py in _generic_factor(expr, gens, args, method)
   6021     options.allowed_flags(args, [])
   6022     opt = options.build_options(gens, args)
-> 6023     return _symbolic_factor(sympify(expr), opt, method)
   6024 
   6025 

~/asumer/sympy/sympy/polys/polytools.py in _symbolic_factor(expr, opt, method)
   5966         if hasattr(expr,'_eval_factor'):
   5967             return expr._eval_factor()
-> 5968         coeff, factors = _symbolic_factor_list(together(expr), opt, method)
   5969         return _keep_coeff(coeff, _factors_product(factors))
   5970     elif hasattr(expr, 'args'):

~/asumer/sympy/sympy/polys/rationaltools.py in together(expr, deep)
     83         return expr
     84 
---> 85     return _together(sympify(expr))

~/asumer/sympy/sympy/polys/rationaltools.py in _together(expr)
     77                 return expr.__class__(base, exp)
     78             else:
---> 79                 return expr.__class__(*[ _together(arg) for arg in expr.args ])
     80         elif iterable(expr):
     81             return expr.__class__([ _together(ex) for ex in expr ])

~/asumer/sympy/sympy/polys/rationaltools.py in <listcomp>(.0)
     77                 return expr.__class__(base, exp)
     78             else:
---> 79                 return expr.__class__(*[ _together(arg) for arg in expr.args ])
     80         elif iterable(expr):
     81             return expr.__class__([ _together(ex) for ex in expr ])

~/asumer/sympy/sympy/polys/rationaltools.py in _together(expr)
     77                 return expr.__class__(base, exp)
     78             else:
---> 79                 return expr.__class__(*[ _together(arg) for arg in expr.args ])
     80         elif iterable(expr):
     81             return expr.__class__([ _together(ex) for ex in expr ])

~/asumer/sympy/sympy/matrices/expressions/inverse.py in __new__(cls, mat, exp)
     42             raise TypeError("mat should be a matrix")
     43         if not mat.is_square:
---> 44             raise ShapeError("Inverse of non-square matrix %s" % mat)
     45         return Basic.__new__(cls, mat, exp)
     46 

TypeError: mat should be a matrix

```

**Comment by RituRajSingh878** [comment]
```
TypeError                                 Traceback (most recent call last)
<ipython-input-4-db12e0a8f0c9> in <module>
----> 1 factor(a)

~/asumer/sympy/sympy/polys/polytools.py in factor(f, *gens, **args)
   6328 
   6329     try:
-> 6330         return _generic_factor(f, gens, args, method='factor')
   6331     except PolynomialError as msg:
   6332         if not f.is_commutative:

~/asumer/sympy/sympy/polys/polytools.py in _generic_factor(expr, gens, args, method)
   6021     options.allowed_flags(args, [])
   6022     opt = options.build_options(gens, args)
-> 6023     return _symbolic_factor(sympify(expr), opt, method)
   6024 
   6025 

~/asumer/sympy/sympy/polys/polytools.py in _symbolic_factor(expr, opt, method)
   5966         if hasattr(expr,'_eval_factor'):
   5967             return expr._eval_factor()
-> 5968         coeff, factors = _symbolic_factor_list(together(expr), opt, method)
   5969         return _keep_coeff(coeff, _factors_product(factors))
   5970     elif hasattr(expr, 'args'):

~/asumer/sympy/sympy/polys/rationaltools.py in together(expr, deep)
     83         return expr
     84 
---> 85     return _together(sympify(expr))

~/asumer/sympy/sympy/polys/rationaltools.py in _together(expr)
     77                 return expr.__class__(base, exp)
     78             else:
---> 79                 return expr.__class__(*[ _together(arg) for arg in expr.args ])
     80         elif iterable(expr):
     81             return expr.__class__([ _together(ex) for ex in expr ])

~/asumer/sympy/sympy/polys/rationaltools.py in <listcomp>(.0)
     77                 return expr.__class__(base, exp)
     78             else:
---> 79                 return expr.__class__(*[ _together(arg) for arg in expr.args ])
     80         elif iterable(expr):
     81             return expr.__class__([ _together(ex) for ex in expr ])

~/asumer/sympy/sympy/polys/rationaltools.py in _together(expr)
     77                 return expr.__class__(base, exp)
     78             else:
---> 79                 return expr.__class__(*[ _together(arg) for arg in expr.args ])
     80         elif iterable(expr):
     81             return expr.__class__([ _together(ex) for ex in expr ])

~/asumer/sympy/sympy/matrices/expressions/inverse.py in __new__(cls, mat, exp)
     42             raise TypeError("mat should be a matrix")
     43         if not mat.is_square:
---> 44             raise ShapeError("Inverse of non-square matrix %s" % mat)
     45         return Basic.__new__(cls, mat, exp)
     46 

TypeError: mat should be a matrix




```

I am trying to solve and now I am getting this traceback.
and here mat=`A**(-1)*B**(-1) - A**(-1)*C*B**(-1)`.which is a matrix expr.
