### ISSUE TITLE
Recursion error when taking the limit of an unsimplified expression

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#15202]
```
>>> from sympy import *
>>> n = Symbol('n')
>>> e = (2**n*(2 + 2**(-n)*(-2*2**n + n + 2))/(n + 1))**(n + 1)
>>> print(limit(simplify(e), n, oo))
E
>>> print(limit(e, n, oo))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/E/se/sympy/series/limits.py", line 68, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
  File "/home/E/se/sympy/series/limits.py", line 213, in doit
    r = gruntz(e, z, z0, dir)
  File "/home/E/se/sympy/series/gruntz.py", line 648, in gruntz
    r = limitinf(e, z)
  File "/home/E/se/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/E/se/sympy/series/gruntz.py", line 441, in limitinf
    return limitinf(c0, x)  # e0=0: lim f = lim c0
  File "/home/E/se/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/E/se/sympy/series/gruntz.py", line 441, in limitinf
    return limitinf(c0, x)  # e0=0: lim f = lim c0
  File "/home/E/se/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/E/se/sympy/series/gruntz.py", line 441, in limitinf
    return limitinf(c0, x)  # e0=0: lim f = lim c0
  File "/home/E/se/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/E/se/sympy/series/gruntz.py", line 441, in limitinf
...
  File "/home/E/se/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/E/se/sympy/series/gruntz.py", line 441, in limitinf
    return limitinf(c0, x)  # e0=0: lim f = lim c0
  File "/home/E/se/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/E/se/sympy/series/gruntz.py", line 441, in limitinf
    return limitinf(c0, x)  # e0=0: lim f = lim c0
  File "/home/E/se/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/E/se/sympy/series/gruntz.py", line 415, in limitinf
    e = e.rewrite('tractable', deep=True)
  File "/home/E/se/sympy/core/basic.py", line 1681, in rewrite
    return self._eval_rewrite(None, rule, **hints)
  File "/home/E/se/sympy/core/basic.py", line 1583, in _eval_rewrite
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1583, in <listcomp>
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1583, in _eval_rewrite
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1583, in <listcomp>
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1583, in _eval_rewrite
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1583, in <listcomp>
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1583, in _eval_rewrite
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1583, in <listcomp>
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1583, in _eval_rewrite
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1583, in <listcomp>
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1583, in _eval_rewrite
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1583, in <listcomp>
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1583, in _eval_rewrite
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1583, in <listcomp>
    for a in self.args]
  File "/home/E/se/sympy/core/basic.py", line 1592, in _eval_rewrite
    return self.func(*args)
  File "/home/E/se/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
RecursionError: maximum recursion depth exceeded while calling a Python object

```

**Comment by alex65536** [comment]
Got a similar issue.

~~~~
import sympy as sym
a, n = sym.symbols('a, n')
expr = (sym.log(n, 2)**7 + 10*n*sym.factorial(n) + 5**n) / (sym.factorial(n+1) + 3*sym.factorial(n) + 10**n)
sym.limit(expr, n, sym.oo) # Throws RecursionError
sym.limit(expr.simplify(), n, sym.oo) # Returns 10
~~~~

Also increasing the recursion limit using `sys.setrecursionlimit` results in a segmentation fault of Python interpreter.
