### ISSUE TITLE
deprecate Derivative.variables

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#15220]
If #15049 makes it into master, consider the following as a vote for deprecation
```
    @property
    def variables(self):
        # TODO: deprecate?  YES, make this 'enumerated_variables' and
        #       name _wrt_variables as variables
        # TODO: support for `d^n`?
```
In Lambda and Integral, variables means 'the variables of the function or of integration'
```python
>>> Lambda((x, y), x + y).variables
(x, y)
>>> Integral(f(x),x,y).variables
[x, y]
```
But in Derivative it means the enumerated list of variables *ignoring those with symbolic count*:
```python
>>> Derivative(f(x, y), x, (y, 2)).variables
(x, y, y)
>>> Derivative(f(x, y), x, (y, n)).variables
(x,)
```

In #15049 I made the symbolic case raise an error and direct the user to use the added `_wrt_variables` method.
```python
>>> Derivative(f(x,y),x,(y,n)).variables
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\core\function.py", line 1578, in variables
    _wrt_variables.'''))
TypeError:
Cannot give expansion for symbolic count. If you just want a list of
all variables of differentiation, use _wrt_variables.
```

**Comment by asmeurer** [comment]
Why _wrt_variables with a leading underscore? That suggests it is a private name not to be used by the end-user.

**Comment by asmeurer** [comment]
An error seems fine, but we could also just return `(x, (y, n))` for that case. I would expect `.variables` to just give something that can be used to recreate the derivative (but maybe less canonicalized than `.args[1:]`).

**Comment by smichr** [comment]
In the PR it's private because this issue here hasn't been addressed yet.

Here is a quick demo of what we've got now:
```python
>>> d = Derivative(f(x, y), x, 2, (y, n))
>>> d.variable_count
((x, 2), (y, n))
>>> d.variables
(x, x)
```
In my PRs, 
```
>>> d._wrt_variables
[x, y]
```
I would like to see `Derivative.variables` to behave like Integral and Lambda and use a more descriptive name for the enumerated variable list.
