### ISSUE TITLE
checkodesol Invalid NaN comparison

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15288]
While working on #15255 I found an intermittent (hash-seed dependent) bug when calling `checkodesol` for a particular ODE:

```python
from sympy.solvers.tests.test_ode import *
from sympy import Ei

eqn = Eq(Derivative(x*Derivative(f(x), x), x)/x, exp(x))
sol = Eq(f(x), C1 + C2*log(x) + exp(x) - Ei(x))
assert checkodesol(eqn, sol, order=2, solve_for_func=False)[0]
```

Note that the timings are consistently different in the cases where it crashes vs the cases where it doesn't. Somehow a hash-seed dependent code path is taken long before the point where the exception is raised.

```console
(venv) ~/current/sympy/sympy$ python --version
Python 3.6.2
(venv) ~/current/sympy/sympy$ time PYTHONHASHSEED=0 python rtest.py 

real	0m1.582s
user	0m1.307s
sys	0m0.092s
(venv) ~/current/sympy/sympy$ time PYTHONHASHSEED=1 python rtest.py 
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 78, in sort_key
    args = expr.as_ordered_terms(order=order)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 993, in as_ordered_terms
    terms, gens = self.as_terms()
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 1051, in as_terms
    gens = sorted(gens, key=default_sort_key)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 336, in __lt__
    raise TypeError("Invalid NaN comparison")
TypeError: Invalid NaN comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rtest.py", line 6, in <module>
    assert checkodesol(eqn, sol, order=2, solve_for_func=False)[0]
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/ode.py", line 2472, in checkodesol
    ode_or_bool = simplify(ode_or_bool)
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/simplify.py", line 521, in simplify
    return expr._eval_simplify(ratio=ratio, measure=measure, rational=rational, inverse=inverse)
  File "/Users/enojb/current/sympy/sympy/sympy/core/relational.py", line 217, in _eval_simplify
    elif dif.equals(0):  # XXX this is expensive
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 680, in equals
    constant = diff.is_constant(simplify=False, failing_number=True)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 611, in is_constant
    if b is not None and b is not S.NaN and b.equals(a) is False:
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 670, in equals
    diff = factor_terms(simplify(self - other), radical=True)
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/simplify.py", line 525, in simplify
    original_expr = expr = signsimp(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/simplify.py", line 375, in signsimp
    e = sub_post(sub_pre(expr))
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/cse_opts.py", line 15, in sub_pre
    reps = [a for a in e.atoms(Add) if a.could_extract_minus_sign()]
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/cse_opts.py", line 15, in <listcomp>
    reps = [a for a in e.atoms(Add) if a.could_extract_minus_sign()]
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 2294, in could_extract_minus_sign
    return bool(self.sort_key() < negative_self.sort_key())
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 95, in wrapper
    retval = func(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 78, in sort_key
    args = expr.as_ordered_terms(order=order)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 993, in as_ordered_terms
    terms, gens = self.as_terms()
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 1051, in as_terms
    gens = sorted(gens, key=default_sort_key)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 336, in __lt__
    raise TypeError("Invalid NaN comparison")
TypeError: Invalid NaN comparison

real	0m2.252s
user	0m1.971s
sys	0m0.098s
```

**Comment by oscarbenjamin** [comment]
The branch occurs here
[https://github.com/sympy/sympy/blob/sympy-1.3/sympy/solvers/ode.py#L369](https://github.com/sympy/sympy/blob/sympy-1.3/sympy/solvers/ode.py#L369)

Depending on the hash seed `reps.items()` can return results in different orders. This is diguised by calling `sorted` since the sort key is by derivative count which compares equal in this case. Under stable sorting this means that the hash-seed dependent order of `reps.items()` passes through to a hash-seed dependent order of `reps`. Then `eq.subs(reps)` returns a different result because the order of substitutions is important:

```julia
In [7]: eq = -exp(x) + Derivative(x*Derivative(f(x), x), x)/x

In [8]: _u = Symbol('u')

In [9]: reps = [(Derivative(f(x), x), _u), (Derivative(x*Derivative(f(x), x), x), _u)]

In [10]: eq.subs(reps)
Out[10]: 
       ∂      
       ──(u⋅x)
   x   ∂x     
- ℯ  + ───────
          x   

In [11]: eq.subs(reps[::-1])
Out[11]: 
u    x
─ - ℯ 
x    
```

I'm not really sure what `subs_func_doit`is supposed to be doing. It doesn't look as if it understands expressions with unexpanded derivatives.
