### ISSUE TITLE
Matplotlib tests failing in Travis (AttributeError: 'NoneType' object has no attribute 'pyplot')

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15374]
It's only in the 3.6 optional dependency build. It just started happening so it's probably related to some upstream change. Example https://travis-ci.org/sympy/sympy/jobs/439723277

```
File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/plotting/plot.py", line 244, in sympy.plotting.plot.Plot.append
Failed example:
    p1.show()
Exception raised:
    Traceback (most recent call last):
      File "/home/travis/miniconda/envs/test-environment/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest sympy.plotting.plot.Plot.append[7]>", line 1, in <module>
        p1.show()
      File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/plotting/plot.py", line 196, in show
        self._backend = self.backend(self)
      File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/plotting/plot.py", line 1097, in __new__
        return MatplotlibBackend(parent)
      File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/plotting/plot.py", line 887, in __init__
        self.plt = self.matplotlib.pyplot
    AttributeError: 'NoneType' object has no attribute 'pyplot'
```

**Comment by asmeurer** [comment]
matplotlib being None means the import failed. I'm not sure why this didn't just result in the doctest being skipped.

**Comment by asmeurer** [comment]
I guess it got fixed https://travis-ci.org/sympy/sympy/jobs/439832721. The main difference I see there is that the `python` conda package build number got incremented by 1. I never got the chance to actually figure out what the problem was, but I'm going to close this. If it comes back, let's reopen.

**Comment by moorepants** [comment]
I've seen this error before on travis. Not sure where though. Maybe wrt to one of the matplotlib plot directive PRs.

**Comment by ishanaj** [comment]
PR #17345 has a similar error with importing numpy
