### ISSUE TITLE
Exception in SymPy Live 

### ISSUE THREAD

**Issue by llucifer97** [sympy/sympy#15392]
>>> import numpy # doctest:+SKIP
>>> a = numpy.arange(10) # doctest:+SKIP
>>> expr = sin(x)
>>> f = lambdify(x, expr, "numpy") # doctest:+SKIP
>>> f(a) # doctest:+SKIP

Exception in SymPy Live of type 
<type 'exceptions.ValueError'>
for reference the last 5 stack trace entries are
Traceback (most recent call last):
  File "/base/data/home/apps/s~sympy-live-hrd/56.412575950366508090/shell.py", line 781, in post
    live.evaluate(statement, session, printer, stream)
  File "/base/data/home/apps/s~sympy-live-hrd/56.412575950366508090/shell.py", line 453, in evaluate
    if name not in old_globals or val != old_globals[name]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
>>> f = lambdify(x, expr, "numpy") # doctest:+SKIP
Exception in SymPy Live of type 
<type 'exceptions.ValueError'>
for reference the last 5 stack trace entries are
Traceback (most recent call last):
  File "/base/data/home/apps/s~sympy-live-hrd/56.412575950366508090/shell.py", line 781, in post
    live.evaluate(statement, session, printer, stream)
  File "/base/data/home/apps/s~sympy-live-hrd/56.412575950366508090/shell.py", line 453, in evaluate
    if name not in old_globals or val != old_globals[name]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
>>> f(a) # doctest:+SKIP
Exception in SymPy Live of type 
<type 'exceptions.ValueError'>
for reference the last 5 stack trace entries are
Traceback (most recent call last):
  File "/base/data/home/apps/s~sympy-live-hrd/56.412575950366508090/shell.py", line 781, in post
    live.evaluate(statement, session, printer, stream)
  File "/base/data/home/apps/s~sympy-live-hrd/56.412575950366508090/shell.py", line 453, in evaluate
    if name not in old_globals or val != old_globals[name]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[](https://docs.sympy.org/latest/tutorial/basic_operations.html)

**Comment by bjodah** [comment]
@llucifer97 would you mind opening this issue over at https://github.com/sympy/sympy-live/issues ?
