### ISSUE TITLE
Evaluating expressions with variables having NaN values

### ISSUE THREAD

**Issue by warnerjon12** [sympy/sympy#15417]
Originally from [StackOverflow](https://stackoverflow.com/questions/52939325/sympy-evaluating-an-expression-that-refers-to-variables-having-nan-values/52939380#52939380). The following code illustrates the problem:

```
>>> from sympy.parsing.sympy_parser import parse_expr
>>> data = {'result': {'a': 'nan', 'b': 123}}
>>> expr = "result['b'] + 123"    # <-- This works well.
>>> parse_expr(expr, data)
>>> 246
>>> expr = "result['a'] + 123"    # <-- This doesn't work.
>>> parse_expr(expr, data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../sympy-1.2rc1-py3.6.egg/sympy/parsing/sympy_parser.py", line 950, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File ".../sympy-1.2rc1-py3.6.egg/sympy/parsing/sympy_parser.py", line 863, in eval_expr
code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
TypeError: must be str, not Integer
```

It would be good to deal with NaN values, simplifying expressions to yield other NaN values, as would happen in floating-point evaluation.

**Comment by ishanaj** [comment]
I think this doesn't deal with `NaN`, as even the below fails:
```
>>> data = {'result': {'a': 'nan', 'b': '123'}}       # 123 changed to '123'
>>>expr = "result['b'] + 123"                       # TypeError of string + integer
>>>parse_expr(expr, data)
Traceback (most recent call last):
  File "sympy_parser.py", line 1058, in <module>
    print(parse_expr(expr, data))
  File "sympy_parser.py", line 966, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "sympy_parser.py", line 878, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
TypeError: Can't convert 'Integer' object to str implicitly
```
But this doesn't:
```
>>> data = {'result': {'a': 'nan', 'b': '123'}}       # 123 changed to '123'
>>>expr = "result['b'] + '123'"                     # No TypeError as it is string + string
>>>parse_expr(expr, data)
123123
```
So, this would work:
```
>>>data = {'result': {'a': nan, 'b': 123}}           # nan without qoutes
>>>expr = "result['a'] + 123"
>>>parse_expr(expr, data) 
nan
```

**Comment by asmeurer** [comment]
I agree this is intended behavior. The second argument to `parse_expr` is a globals dictionary that defines names to be used in the namespace when parsing. Since `a` is set to the string `'nan'`, the resulting expression parses to the equivalent of `'nan' + 123`. This has nothing to do with the fact that it's `nan` in the string. SymPy doesn't allow strings to be used in arithemetic operations (even using them in other places where they are allowed is [bad practice](https://github.com/sympy/sympy/wiki/Idioms-and-Antipatterns#strings-as-input)).
