### ISSUE TITLE
Infinite loop while intricated Max, sign and Abs rewrite as Piecewise.

### ISSUE THREAD

**Issue by bemichel** [sympy/sympy#15440]
Hi,
I am trying to generate code from Sympy and codegen to be able to compute flux for CFD  code and its Jacobian (cf. attached test file [flux.py.zip](https://github.com/sympy/sympy/files/2530750/flux.py.zip)).

Inside this flux expression, one can found intricated ```Max```, ```Abs``` and ```sign``` functions.

To be able to generate code for the flux jacobian, the ```_eval_rewrite_as_Piecewise``` method of each ```Max```, ```Abs``` and ```sign``` function has been overloaded as flollow :
```python
class Max(sympy.Max):

    def _eval_rewrite_as_Piecewise(self, *args):
        return _minmax_as_Piecewise('>=', *args)

class Abs(sympy.Abs):

    def _eval_rewrite_as_Piecewise(self, arg):
        return Piecewise((arg, arg >= S.Zero), (-arg, True))

class sign(sympy.sign):

    def _eval_rewrite_as_Piecewise(self, arg):
        return Piecewise((S.One, arg > S.Zero), (-S.One, arg < S.Zero), (S.Zero, True))
```
It works very well on "toy" problem, like : 
```python
from sympy import symbols, Max, Abs, sign
from sympy.functions      import Piecewise
from sympy.codegen.ast    import While, Assignment, aug_assign, Print, CodeBlock
from sympy.printing.fcode import fcode

t, dx, x = symbols('tol delta val', real=True)
a    = Max(x**2, 1.e-12).rewrite(Piecewise)
expr = a+a**2*sign(x).rewrite(Piecewise)
df0  = expr.diff(x)
cbp = CodeBlock( Assignment(dx, df0) )
whl = While(abs(dx) > t, [ cbp.cse(order='none'),
      aug_assign(x, '+', dx),
      Print([x])
])
print(fcode(whl, standard=95, source_format='free'))
```
which gives : 
```fortran
do while (abs(delta) > tol)
   x0 = val**2 <= 1.0d-12
   delta = merge(0, 2*val, x0) + merge(0, 4*val**3, x0)*merge(1, merge( &
      -1, 0, val < 0), val > 0)
   val = val + delta
   print *, val
end do
```

But, in my real case, for flux expression (cf. attached test file [flux.py.zip](https://github.com/sympy/sympy/files/2530750/flux.py.zip)), it seems that the multiple intricated ```Max```, ```Abs``` and ```sign``` functions rewrited as ```Piecewise``` vanish in a sort of "infinite loop" while trying to simplify those intricated ```Piecewise``` functions calling ```simplify_logic(c, form='cnf')``` in the method ```def piecewise_fold(expr)```  : 
```shell
$> python flux.py
 - Build Flux
 ------------
wll, wlr is built in  7.19616484642
^CTraceback (most recent call last):
  File "flux.py", line 509, in <module>
    codes = build_flux(limiter=limiter, flux=flux, build_jacobian=build_jacobian)
  File "flux.py", line 451, in build_flux
    fc = functionFlux(sn, normal, wfl, wfr)
  File "flux.py", line 331, in build_flux_type
    aa1 = _build_dissipation_coefficient(lambda1, small, E_CUTOFF_HARTEN)
  File "flux.py", line 287, in _build_dissipation_coefficient
    k = 0.5 - 0.5*(E_Sign(lambda_-small))
  File "flux.py", line 187, in E_Sign
    return sign(arg).rewrite(Piecewise)
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/core/basic.py", line 1681, in rewrite
    return self._eval_rewrite(None, rule, **hints)
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/core/basic.py", line 1589, in _eval_rewrite
    rewritten = getattr(self, rule)(*args)
  File "flux.py", line 52, in _eval_rewrite_as_Piecewise
    return Piecewise((S.One, arg > S.Zero), (-S.One, arg < S.Zero), (S.Zero, True))
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/functions/elementary/piecewise.py", line 129, in __new__
    pair = ExprCondPair(*getattr(ec, 'args', ec))
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/functions/elementary/piecewise.py", line 29, in __new__
    cond = piecewise_fold(cond)
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/functions/elementary/piecewise.py", line 1046, in piecewise_fold
    folded = list(map(piecewise_fold, args))
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/functions/elementary/piecewise.py", line 1046, in piecewise_fold
    folded = list(map(piecewise_fold, args))
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/functions/elementary/piecewise.py", line 1046, in piecewise_fold
    folded = list(map(piecewise_fold, args))
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/functions/elementary/piecewise.py", line 1046, in piecewise_fold
    folded = list(map(piecewise_fold, args))
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/functions/elementary/piecewise.py", line 993, in piecewise_fold
    c = simplify_logic(c, form='cnf')
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/logic/boolalg.py", line 1970, in simplify_logic
    s = [simplify(v) for v in variables]
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/simplify/simplify.py", line 521, in simplify
    return expr._eval_simplify(ratio=ratio, measure=measure, rational=rational, inverse=inverse)
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/core/relational.py", line 217, in _eval_simplify
    elif dif.equals(0):  # XXX this is expensive
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/core/expr.py", line 680, in equals
    constant = diff.is_constant(simplify=False, failing_number=True)
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/core/expr.py", line 618, in is_constant
    b = expr._random()
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/core/expr.py", line 457, in _random
    for zi in free])))
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/utilities/randtest.py", line 30, in random_complex_number
    I*nsimplify(B, rational=True, tolerance=tolerance))
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/simplify/simplify.py", line 1312, in nsimplify
    return _real_to_rational(expr, tolerance, rational_conversion)
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/simplify/simplify.py", line 1429, in _real_to_rational
    r = nsimplify(fl, rational=False)
  File ".../lib/python2.7/site-packages/sympy-1.3-py2.7.egg/sympy/simplify/simplify.py", line 1326, in nsimplify
    constants_dict = {}
KeyboardInterrupt
```

If I rewrite the function ```def piecewise_fold(expr)``` by returning directly the expression, like the following code:
```python
def piecewise_fold(expr):
    return expr
```

It has the benefit that it is working :
```shell
$> python flux.py
 - Build Flux
 ------------
wll, wlr is built in  2.16070985794
fc is built in  1.01476383209
  -> codeblock cse is built in  2.99989509583
  -> ffcode        is built in  0.23072886467
flux is generated in  6.43013310432

 - Build Jacobian Flux
 ---------------------
wll, wlr is built in  1.96448016167
  -> dWl_ll is built in  2.36562991142
  -> dWl_lr is built in  2.33478498459
  -> dWl_rl is built in  2.27538108826
  -> dWl_rr is built in  2.24039387703
dWl_ll, dWl_lr, dWl_rl, dWl_rr is built in  9.21634817123
fc is built in  0.672829151154
  -> Acl is built in  22.5307159424
  -> Acr is built in  21.6908020973
Acl, Acr is built in  44.2216000557
  -> codeblock cse is built in  201.012160063
  -> ffcode        is built in  0.943426132202
jacobian flux is generated in  258.132653952
```
and give me a generated code with visible ```Piecewise``` (cf result file [flux-ltype1-ftype1.f90.zip](https://github.com/sympy/sympy/files/2530778/flux-ltype1-ftype1.f90.zip)).

**My questions:**
- Is the "infinite loops" behaviour I noticed while calling ```simplify_logic(c, form='cnf')``` is normal ?
- Is there a better way to correct this behaviour ?

Thanks a lot to give help.

Bertrand M.

**NB**: I tried the master branch and I noticed that the computation time for the jacobian has significantly rise : 
```shell
$> python flux.py
 - Build Flux
 ------------
wll, wlr is built in  2.1577129364
fc is built in  1.02419090271
  -> codeblock cse is built in  2.98350286484
  -> ffcode        is built in  0.230612039566
flux is generated in  6.41960120201

 - Build Jacobian Flux
 ---------------------
wll, wlr is built in  1.9488658905
  -> dWl_ll is built in  3.79302787781
  -> dWl_lr is built in  3.6228890419
  -> dWl_rl is built in  3.54023504257
  -> dWl_rr is built in  3.63563203812
dWl_ll, dWl_lr, dWl_rl, dWl_rr is built in  14.5919339657
fc is built in  0.673840045929
  -> Acl is built in  95.2139079571
  -> Acr is built in  93.8472929001
Acl, Acr is built in  189.061281919
  -> codeblock cse is built in  203.05272007
  -> ffcode        is built in  0.955168008804
jacobian flux is generated in  410.334296942
```
I get ```Acl``` for ```95.2139079571``` seconds from the master branch of sympy instead of ```22.5307159424``` seconds from the sympy 1.3 version.

**Comment by oscargus** [comment]
Some late feedback. Not really a solution, but some related observations.

* `simplify_logic` uses Quine-McCluskey to do the logic minimization, which in turn relies on set covering, which as a worst case has exponential runtime. Since SymPy 1.4, it skips that part if there are more than eight variables involved (can be overridden by using setting `force=True` when calling it).
* `piecewise_fold` is a bit careless when it comes to certain types of expressions, typically integrals of Piecewise function.
