### ISSUE TITLE
(s-t) interpreted as boolean somehow?

### ISSUE THREAD

**Issue by troubas** [sympy/sympy#15492]
Hi,

I'm hoping that this issue isn't already recorded. I didn't find anything but there are tons of tickets so maybe I missed it.

Please take a quick look at the following code and maybe you see what I'm missing. When I declare p as `p = symbols('t-s')` I can integrate. If I type it directly in the equation I get a TypeError: BooleanAtom not allowed in context.

Definitions
```
$ s,t = symbols('s t')
$ k = symbols('k', real=True)
$ RC = symbols('RC', positive=True)
```

Integration with formula as is:
```
$ integrate(sin(k*s)*1/RC*exp((s-t)/RC),s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1465, in integrate
    risch=risch, manual=manual)
  File "/usr/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 538, in doit
    function, xab[0], **eval_kwargs)
  File "/usr/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 989, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/usr/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 161, in heurisch_wrapper
    slns = solve(eqs, dict=True, exclude=(x,)) + slns
  File "/usr/lib/python3.7/site-packages/sympy/logic/boolalg.py", line 188, in _noop
    raise TypeError('BooleanAtom not allowed in this context.')
TypeError: BooleanAtom not allowed in this context.
```

Integration with `p`
```
$ p = symbols('t-s')
$ pprint(simplify(integrate(sin(k*s)*1/RC*exp(-p/RC),s)))
⎧  -t-s
⎪  ─────
⎪    RC
⎪-ℯ     ⋅cos(k⋅s)
⎨─────────────────  for k ≠ 0
⎪       RC⋅k
⎪
⎪        0          otherwise
⎩
```

*Note:* The error doesn't appear if I leave the `sin` function out of the equation.

I'm a bit perplexed why changing the value in the exponential function leads to an error if in a multiplication with the sinus function and works otherwise. Is this a bug?

**Comment by asmeurer** [comment]
heurisch generating an equation to solve that reduces to False because of the assumptions (`Eq(RC, I/k)`). `solve` then returns `False`, which fails with the `+ slns` part. This is a bug in solve because the `dict=True` flag is provided, so the output type should be a list of dicts (particularly, an empty list). 

Probably easy to fix.

**Comment by asmeurer** [comment]
To clarify, a simpler reproducing example:

```py
>>> solve([False], dict=True)
False
```

**Comment by m-agboola** [comment]
Hi, @asmeurer I'm new here but I'd like to work on this.

**Comment by aggarwalaakash007** [comment]
Hi, @asmeurer I would like to take this issue.

**Comment by asmeurer** [comment]
Yes, feel free to work on it. You should figure out how to make `solve([False], dict=True)` return `[]` with the `dict` flag set to `True`.

**Comment by m-agboola** [comment]
Alright. I will begin right away.

**Comment by asmeurer** [comment]
Yes. Equalities sometimes reduces to booleans automatically, like `Eq(1, 2) -> False`. So when someone tries to solve an equality that reduces to False, it means that the equality has no solutions.

**Comment by Phantsure** [comment]
### Asking for some corner cases
so for `solve([True], dict=True)` output should be `[True]` or `True`
and for `solve([False])` output should be `False` or `<blank>`?

**Comment by asmeurer** [comment]
Without setting `dict`, the output should be the same as it is now. 

I'm not sure about [True]. dict=True is supposed to return a list of dicts, but I don't know how to represent that as such.

**Comment by Phantsure** [comment]
thanks

**Comment by pulkit6559** [comment]
I have made the required changes in pull request #15517 
@asmeurer please review?

**Comment by vishal-vardhan** [comment]
is anyone working on this??

**Comment by sharma-kunal** [comment]
If anyone is not working on the issue, I would like to take the issue.

**Comment by czgdp1807** [comment]
```python
>>> s,t = symbols('s t')
>>> k = symbols('k', real=True)
>>> RC = symbols('RC', positive=True)
>>> p = symbols('t-s')
>>> pprint(simplify(integrate(sin(k*s)*1/RC*exp((s-t)/RC),s)))
                             s - t
                             ─────
                               RC 
(-RC⋅k⋅cos(k⋅s) + sin(k⋅s))⋅ℯ     
──────────────────────────────────
              2  2                
            RC ⋅k  + 1            
>>> pprint(simplify(integrate(sin(k*s)*1/RC*exp(-p/RC),s)))
⎧  -t-s                      
⎪  ─────                     
⎪    RC                      
⎪-ℯ     ⋅cos(k⋅s)            
⎨─────────────────  for k ≠ 0
⎪       RC⋅k                 
⎪                            
⎪        0          otherwise
⎩                            
```
Both approaches now work. But I am not sure that whether answers are correct or not. Applying `Could Close` label on it.

**Comment by czgdp1807** [comment]
One more thing I observed is that the `s` in `p` is a character and not a symbol, so IMO, the answers of the two expressions are bound to differ. I support closing this issue.

**Comment by oscarbenjamin** [comment]
The first example seems correct:
```julia
In [6]: expr = sin(k*s)*1/RC*exp((s-t)/RC)                                                                                        

In [7]: expr                                                                                                                      
Out[7]: 
 s - t         
 ─────         
   RC          
ℯ     ⋅sin(k⋅s)
───────────────
       RC      

In [8]: integrate(expr, s)                                                                                                        
Out[8]: 
         s                 s           
         ──                ──          
    2    RC                RC          
  RC ⋅k⋅ℯ  ⋅cos(k⋅s)   RC⋅ℯ  ⋅sin(k⋅s) 
- ────────────────── + ────────────────
           t     t             t     t 
           ──    ──            ──    ──
     2  2  RC    RC      2  2  RC    RC
   RC ⋅k ⋅ℯ   + ℯ      RC ⋅k ⋅ℯ   + ℯ  
───────────────────────────────────────
                   RC                  

In [9]: simplify(_.diff(s) - expr)                                                                                                
Out[9]: 0
```
The second example also seems correct:
```julia
In [14]: expr = sin(k*s)*1/RC*exp(-p/RC)                                                                                          

In [15]: expr                                                                                                                     
Out[15]: 
 -t-s          
 ─────         
   RC          
ℯ     ⋅sin(k⋅s)
───────────────
       RC      

In [16]: integrate(expr, s)                                                                                                       
Out[16]: 
                          -t-s 
⎛⎧-cos(k⋅s)            ⎞  ─────
⎜⎪──────────  for k ≠ 0⎟    RC 
⎜⎨    k                ⎟⋅ℯ     
⎜⎪                     ⎟       
⎝⎩    0       otherwise⎠       
───────────────────────────────
               RC              

In [17]: integrate(expr, s).diff(s)                                                                                               
Out[17]: 
                        -t-s 
                        ─────
⎛⎧sin(k⋅s)  for k ≠ 0⎞    RC 
⎜⎨                   ⎟⋅ℯ     
⎝⎩   0      otherwise⎠       
─────────────────────────────
              RC             

In [18]: integrate(expr, s).diff(s) - expr                                                                                        
Out[18]: 
                        -t-s                   
                        ─────    -t-s          
⎛⎧sin(k⋅s)  for k ≠ 0⎞    RC     ─────         
⎜⎨                   ⎟⋅ℯ           RC          
⎝⎩   0      otherwise⎠          ℯ     ⋅sin(k⋅s)
───────────────────────────── - ───────────────
              RC                       RC      

In [19]: simplify(_)                                                                                                              
Out[19]: 
⎧        0          for k ≠ 0
⎪                            
⎪  -t-s                      
⎪  ─────                     
⎨    RC                      
⎪-ℯ     ⋅sin(k⋅s)            
⎪─────────────────  otherwise
⎪        RC                  
⎩      
```
That last expression should simplify to zero since `k=0` in the second case. Perhaps a new issue can be opened for that but otherwise the original issue seems to be fixed.

**Comment by troubas** [comment]
I can confirm that the integration is working now. I'll close the ticket (and hope that I'm not doing anything wrong in doing so ^).

Thank you all!
