### ISSUE TITLE
Should Point.distance(Line) return distance?

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#15531]
In Geometry module, `Line.distance(Point)` can be used to compute distance, but `Point.distance(Line)` cannot. Should this be made symmetric? 
```
>>> L = Line((1, 1), (2, 2))
>>> P = Point(1, 0)
>>> L.distance(P)
sqrt(2)/2
>>> P.distance(L)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/k3/sympy/sympy/geometry/point.py", line 416, in distance
    s, p = Point._normalize_dimension(self, Point(p))
  File "/home/k3/sympy/sympy/geometry/point.py", line 129, in __new__
    .format(func_name(coords))))
TypeError: 
Expecting sequence of coordinates, not `Line2D`
```

**Comment by FrackeR011** [comment]
I would like to implement this function .
