### ISSUE TITLE
Matplotlib tests failing under Python 2.7

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15546]
If I install matplotlib and run the tests for `sympy/plotting/tests/test_plot.py` under Python 2.7 I get a load of test errors. Without matplotlib the tests are skipped. The tests run fine under Python 3.7 with matplotlib.

Should I expect these to pass or is there a problem with my setup?

```console
$ bin/test !$
bin/test sympy/plotting/tests/test_plot.py
==================================================================== test process starts =====================================================================
executable:         /Users/enojb/current/sympy/27venv/bin/python  (2.7.10-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              1.15.4
random seed:        80924
hash randomization: on (PYTHONHASHSEED=141526262)

sympy/plotting/tests/test_plot.py[9] EEEEEE.EE                                                                                                          [FAIL]

______________________________________________________________________________________________________________________________________________________________
____________________________________________________ sympy/plotting/tests/test_plot.py:test_matplotlib_1 _____________________________________________________
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/sympy/sympy/plotting/tests/test_plot.py", line 336, in test_matplotlib_1
    plot_and_save_1('test')
  File "/Users/enojb/current/sympy/sympy/sympy/plotting/tests/test_plot.py", line 50, in plot_and_save_1
    p = plot(x)
  File "sympy/plotting/plot.py", line 1348, in plot
    plots.show()
  File "sympy/plotting/plot.py", line 196, in show
    self._backend = self.backend(self)
  File "sympy/plotting/plot.py", line 1097, in __new__
    return MatplotlibBackend(parent)
  File "sympy/plotting/plot.py", line 887, in __init__
    self.plt = self.matplotlib.pyplot
AttributeError: 'NoneType' object has no attribute 'pyplot'
...
```

**Comment by oscarbenjamin** [comment]
The same thing happens with `sympy/plotting/tests/test_plot_implicit.py`.

**Comment by asmeurer** [comment]
What version of matplotlib do you have? I think there are some issues with older versions.

**Comment by oscarbenjamin** [comment]
It's a fresh install from pip. I'll post a full setup repro in a moment.

**Comment by oscarbenjamin** [comment]
I'm on OSX using a virtualenv created from the system Python 2.7:

```console
$ python
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D
$ python -m virtualenv venv
New python executable in /Users/enojb/current/sympy/test_matplotlib/venv/bin/python
Installing setuptools, pip, wheel...done.
$ . venv/bin/activate
(venv) $ pip install -U pip
Requirement already up-to-date: pip in ./venv/lib/python2.7/site-packages (18.1)
(venv) $ pip install matplotlib
Collecting matplotlib
  Using cached https://files.pythonhosted.org/packages/23/16/8f83901b3094199078acd965657b9ee22604f33795fcb32a704566dd4cdf/matplotlib-2.2.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting kiwisolver>=1.0.1 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/79/d8/94633718f3f77dcb638687a77ba199325a1cb158d2d4b00c9dc17f2b5c72/kiwisolver-1.0.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting cycler>=0.10 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting subprocess32 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/1f/b5/dcb236f263f61cdaac6dad65df42bbff91f66ef90854ae1a96ad4c8dd654/subprocess32-3.5.3-cp27-cp27m-macosx_10_6_intel.whl
Collecting pytz (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/f8/0e/2365ddc010afb3d79147f1dd544e5ee24bf4ece58ab99b16fbb465ce6dc0/pytz-2018.7-py2.py3-none-any.whl
Collecting six>=1.10 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting backports.functools-lru-cache (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting numpy>=1.7.1 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/c0/b9/2b485bb32d0b26631f433580d90daad5dea830e6dc5bd18c4f227b1829f7/numpy-1.15.4-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/71/e8/6777f6624681c8b9701a8a0a5654f3eb56919a01a78e12bf3c73f5a3c714/pyparsing-2.3.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./venv/lib/python2.7/site-packages (from kiwisolver>=1.0.1->matplotlib) (40.6.2)
Installing collected packages: kiwisolver, six, cycler, subprocess32, pytz, backports.functools-lru-cache, numpy, pyparsing, python-dateutil, matplotlib
Successfully installed backports.functools-lru-cache-1.5 cycler-0.10.0 kiwisolver-1.0.1 matplotlib-2.2.3 numpy-1.15.4 pyparsing-2.3.0 python-dateutil-2.7.5 pytz-2018.7 six-1.11.0 subprocess32-3.5.3
(venv) $ pip install mpmath
Collecting mpmath
Installing collected packages: mpmath
Successfully installed mpmath-1.0.0
(venv) $ git clone https://github.com/sympy/sympy.git
Cloning into 'sympy'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 237656 (delta 44), reused 58 (delta 40), pack-reused 237570
Receiving objects: 100% (237656/237656), 94.29 MiB | 1.26 MiB/s, done.
Resolving deltas: 100% (189530/189530), done.
Checking out files: 100% (1653/1653), done.
(venv) $ cd sympy/
(venv) $ bin/test sympy/plotting/tests/test_plot.py 
==================================================================== test process starts =====================================================================
executable:         /Users/enojb/current/sympy/test_matplotlib/venv/bin/python  (2.7.10-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              1.15.4
random seed:        54783116
hash randomization: on (PYTHONHASHSEED=2717550402)

sympy/plotting/tests/test_plot.py[9] EEEEEE.EE                                                                                                          [FAIL]

______________________________________________________________________________________________________________________________________________________________
____________________________________________________ sympy/plotting/tests/test_plot.py:test_matplotlib_1 _____________________________________________________
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/test_matplotlib/sympy/sympy/plotting/tests/test_plot.py", line 336, in test_matplotlib_1
    plot_and_save_1('test')
  File "/Users/enojb/current/sympy/test_matplotlib/sympy/sympy/plotting/tests/test_plot.py", line 50, in plot_and_save_1
    p = plot(x)
  File "sympy/plotting/plot.py", line 1348, in plot
    plots.show()
  File "sympy/plotting/plot.py", line 196, in show
    self._backend = self.backend(self)
  File "sympy/plotting/plot.py", line 1097, in __new__
    return MatplotlibBackend(parent)
  File "sympy/plotting/plot.py", line 887, in __init__
    self.plt = self.matplotlib.pyplot
AttributeError: 'NoneType' object has no attribute 'pyplot'
...
```

**Comment by asmeurer** [comment]
Can you import matplotlib? It being None suggests the import failed.

**Comment by oscarbenjamin** [comment]
Er... good point.

Importing matplotlib works
```python
>>> import matplotlib
```

However importing pyplot does not
```python
>>> from matplotlib import pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/test_matplotlib/venv/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/enojb/current/sympy/test_matplotlib/venv/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/Users/enojb/current/sympy/test_matplotlib/venv/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 17, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

I should have tested this more thoroughly. Sorry for the noise!
