### ISSUE TITLE
rubi_integrate missing rule to integrate constant

### ISSUE THREAD

**Issue by nasser1** [sympy/sympy#15554]
This might be related to  #15543 (rubi_integrate can't integrate x). 

I do not know, so I am entering new bug. 

rubi_integrate can not integrate a constant. Which seems to me it is missing some basic rules like in the above.  

```
>which python
/opt/anaconda/bin/python

>python --version
Python 3.7.0

>python
Python 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0] :: Anaconda, Inc. on linux
>>> import sympy
>>> sympy.__version__
'1.3'
>>> from sympy import *
>>> from sympy.integrals.rubi.rubi import rubi_integrate 
>>> x,a=symbols('x a')
>>> rubi_integrate(1,x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/lib/python3.7/site-packages/sympy/integrals/rubi/rubi.py", line 308, in rubi_integrate
    expr = expr.replace(sym_exp, exp)
AttributeError: 'int' object has no attribute 'replace'

```
I found if I change ` rubi_integrate(1,x)` to  `rubi_integrate(S('1'),x)` then it works

```
>>> rubi_integrate(S('1'),x)
x

```

But in Sympy itself, this works

```
>>> integrate(1,x)
x
```

It also can't integrate a  symbol, as in

```
>>> rubi_integrate(a,x)
Integral(a, x)

```

Thank you
--Nasser

**Comment by czgdp1807** [comment]
The `rubi_integrate` has been moved to a different namespace. And the error isn't raised instead the result takes infinite time for computation. Opening a new issue.
