### ISSUE TITLE
Simplification of noncommutative and symbolic matrix exponentials

### ISSUE THREAD

**Issue by clyring** [sympy/sympy#15551]
Attempting to simplify some straightforward expressions involving exponentials of noncommutative or matrix symbols produces wrong results or TypeErrors in the following sample code:
```
from sympy import symbols, exp, exptrigsimp, MatrixSymbol

a,b = symbols('a b', commutative=False)
c = exp(a)*exp(b) - exp(b)*exp(a)
print(c) #Works as expected
print(c.simplify()) #Wrongly prints zero
print(exptrigsimp(c))
print(exptrigsimp(exp(a)*exp(b))) #Wrongly prints exp(a+b)


A = MatrixSymbol('A', 2, 2)
B = MatrixSymbol('B', 2, 2)
C = exp(A)*exp(B) - exp(B)*exp(A)
print(C)
print(C.simplify()) #This throws a TypeError.
print()
```

I have already coded up a (hackish) fix for the noncommutative symbol test case. (Pull request to follow...)

I have yet to closely look at the MatrixSymbol simplification TypeError, but it seems to come from attempting to add the scalar S.Pi/2 to the MatrixSymbol argument of some exponential function. This problem would likely be pervasive throughout the simplification code, and directly tackling it is likely to make the code significantly uglier. The task of simplifying expressions involving matrix exponentials is certainly very legitimate, but I'm wondering if it should best happen by other means.

**Comment by asmeurer** [comment]
This is the full traceback of simplify():

```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "./sympy/core/expr.py", line 3216, in simplify
    return simplify(self, ratio, measure)
  File "./sympy/simplify/simplify.py", line 613, in simplify
    short = exptrigsimp(short)
  File "./sympy/simplify/trigsimp.py", line 542, in exptrigsimp
    newexpr = bottom_up(expr, exp_trig)
  File "./sympy/simplify/simplify.py", line 1087, in bottom_up
    for a in rv.args])
  File "./sympy/simplify/simplify.py", line 1087, in <listcomp>
    for a in rv.args])
  File "./sympy/simplify/simplify.py", line 1087, in bottom_up
    for a in rv.args])
  File "./sympy/simplify/simplify.py", line 1087, in <listcomp>
    for a in rv.args])
  File "./sympy/simplify/simplify.py", line 1090, in bottom_up
    rv = F(rv)
  File "./sympy/simplify/trigsimp.py", line 540, in exp_trig
    choices.append(e.rewrite(cos))
  File "./sympy/core/basic.py", line 1749, in rewrite
    return self._eval_rewrite(None, rule, **hints)
  File "./sympy/core/basic.py", line 1656, in _eval_rewrite
    rewritten = getattr(self, rule)(*args, **hints)
  File "./sympy/functions/elementary/exponential.py", line 455, in _eval_rewrite_as_cos
    return cos(I*arg) + I*cos(I*arg + S.Pi/2)
  File "./sympy/matrices/expressions/matexpr.py", line 24, in __sympifyit_wrapper
    return func(a, b)
  File "./sympy/core/decorators.py", line 132, in binary_op_wrapper
    return func(self, other)
  File "./sympy/matrices/expressions/matexpr.py", line 87, in __add__
    return MatAdd(self, other, check=True).doit()
  File "./sympy/matrices/expressions/matadd.py", line 42, in __new__
    validate(*args)
  File "./sympy/matrices/expressions/matadd.py", line 77, in validate
    raise TypeError("Mix of Matrix and Scalar symbols")
TypeError: Mix of Matrix and Scalar symbols
```

The exptrigsimp issue was fixed by #15558.

**Comment by asmeurer** [comment]
The problem is in the course of attempting different simplifications, it tries to add pi/2 to the matrix expression. I don't see a way to fix this sort of thing generally, as this could happen anywhere. Is the rewrite that is being attempted valid for non-commutative expressions in general? 

Another thing we can do would be to implement matrix powers with scalar base (currently `2**A` raises NotImplementedError), and make exp(A) use that. That way, it won't call methods of exp that aren't supported on matrices.

**Comment by clyring** [comment]
The attempted rewrite in question is valid in any unital Banach algebra over the complex numbers, provided we interpret pi/2 to mean pi/2 times the multiplicative identity element and define exp and cos using power series. This can be shown in a direct, but painful way by expanding both the original and rewritten expressions in power series, using the fact that i, pi/2 times the identity element, and the argument to exp commute with one another to compute the latter power series. Someone more familiar with the holomorphic functional calculus probably has a cleaner proof at the ready. More generally, any identity of holomorphic functions on n-tuples of complex numbers can be interpreted as an identity valid on n-tuples of pairwise commuting elements of any complex unital Banach algebra in the same way.

I could only imagine the rewrite leading to a wrong result if attempted over the real quaternions viewed as a superset of the complex numbers, but this would seem deeply at odds with the fact that `S.ImaginaryUnit.is_commutative` is always `True` in SymPy. The ready availability of noncommutative analogues to various identities doesn't necessarily itself suggest the right way to code a solution, though.
