### ISSUE TITLE
Travis failure due to inaccurate return from sympy.rf or mpmath.rf

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15575]
I got a Python 2.7-only test failure on Travis that can be reproduced with
```console
$ bin/test sympy/functions/combinatorial/tests/test_comb_factorials.py --seed=51891955 -k test_rf_eval_apply
==================================================================== test process starts =====================================================================
executable:         /Users/enojb/current/sympy/27venv/bin/python  (2.7.10-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              None
random seed:        51891955
hash randomization: on (PYTHONHASHSEED=2303623249)

sympy/functions/combinatorial/tests/test_comb_factorials.py[1] F                                                                                        [FAIL]

______________________________________________________________________________________________________________________________________________________________
_______________________________________ sympy/functions/combinatorial/tests/test_comb_factorials.py:test_rf_eval_apply _______________________________________
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/sympy/sympy/functions/combinatorial/tests/test_comb_factorials.py", line 69, in test_rf_eval_apply
    assert (abs(mpmath_rf(x, k) - rf(x, k)) < 10**(-15))
AssertionError

==================================================== tests finished: 0 passed, 1 failed, in 0.28 seconds =====================================================
DO *NOT* COMMIT!
```

Looking at the failed test there is
```python
    import random
    from mpmath import rf as mpmath_rf
    for i in range(100):
        x = -500 + 500 * random.random()
        k = -500 + 500 * random.random()
        assert (abs(mpmath_rf(x, k) - rf(x, k)) < 10**(-15))
```

It looks as if the test is comparing sympy's `rf` function mpmath's and requiring the difference to be within rounding error. With this particular seed `x` and `k` are:
```python
(Pdb) p x
-255.5815971722918
(Pdb) p k
-0.5119253100282322
(Pdb) p abs(mpmath_rf(x, k) - rf(x, k))
mpf('8.8429263911393718e-14')
```

So the result is two orders of magnitude bigger than the threshold `1e-15`. I don't know if that implies a bug in sympy's `rf` or if it just means that the test is too stringent.

This failure only shows up for me (on Travis or locally) when using Python 2.7 but that's just to do with the random number generation. I can reliably reproduce this under 2.7 or 3.7 with:
```python
from sympy import rf
from mpmath import rf as mpmath_rf

x = -255.5815971722918
k = -0.5119253100282322
print(abs(mpmath_rf(x, k) - rf(x, k)))
assert (abs(mpmath_rf(x, k) - rf(x, k)) < 10**(-15))
```

I have no idea whether sympy's or mpmath's `rf` function is the one that is inaccurate.

**Comment by normalhuman** [comment]
SymPy does not have its own algorithm for this evaluation, its `rf.eval` does not handle noninteger k. The inconsistency is on mpmath side: the return value differs based on the working precision.  The default is 15, but changing that to 16 affects the supposedly precise digits.
```
>>> from mpmath import mp
>>> mp.rf(mp.mpf('-255.5815971722918'), mp.mpf('-0.5119253100282322'))
mpf('-0.19527202788048453')
>>> mp.dps = 16
>>> mp.rf(mp.mpf('-255.5815971722918'), mp.mpf('-0.5119253100282322'))
mpf('-0.1952720278805573952')
```
I think this is not supposed to happen. The last digit can be expected to change but not the last 5 digits. Compare to
```
>>> mp.dps = 15
>>> mp.sqrt(mp.mpf('0.1'))
mpf('0.31622776601683794')
>>> mp.dps = 16
>>> mp.sqrt(mp.mpf('0.1'))
mpf('0.3162277660168379342')
```

**Comment by oscarbenjamin** [comment]
Closing as this is now fixed upstream:
[https://github.com/fredrik-johansson/mpmath/issues/421](https://github.com/fredrik-johansson/mpmath/issues/421)

```console
$ cat t.py 
from sympy import rf
from mpmath import rf as mpmath_rf

x = -255.5815971722918
k = -0.5119253100282322
print(abs(mpmath_rf(x, k) - rf(x, k)))
assert (abs(mpmath_rf(x, k) - rf(x, k)) < 10**(-15))
$ python t.py 
8.84292639113937e-14
Traceback (most recent call last):
  File "t.py", line 7, in <module>
    assert (abs(mpmath_rf(x, k) - rf(x, k)) < 10**(-15))
AssertionError
$ pip install -U mpmath
...
Successfully installed mpmath-1.1.0
$ python t.py 
2.77555756156289e-17
```
