### ISSUE TITLE
Issues with MatrixExpr.from_index_summation from KroneckerProduct

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15580]
From https://github.com/sympy/sympy/pull/15562#issuecomment-442641365.

```py
>>> i, j = symbols('i j', integer=True)
>>> X = MatrixSymbol('X', 1, n*m)
>>> A1 = MatrixSymbol("A1", n, 1)
>>> A2 = MatrixSymbol("A2", m, 1)
>>> expr = X*KroneckerProduct(A1, A2)
>>> MatrixExpr.from_index_summation(expr._entry(i, j))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/matrices/expressions/matexpr.py", line 587, in from_index_summation
    return remove_matelement(retexpr, *ind0)
  File "./sympy/matrices/expressions/matexpr.py", line 468, in remove_matelement
    return rule(expr)
  File "./sympy/strategies/core.py", line 44, in chain_rl
    expr = rule(expr)
  File "./sympy/strategies/traverse.py", line 15, in <lambda>
    return chain(lambda expr: sall(bottom_up(rule, fns), fns)(expr), rule)
  File "./sympy/strategies/traverse.py", line 37, in all_rl
    return new(op(expr), *args)
  File "./sympy/strategies/core.py", line 44, in chain_rl
    expr = rule(expr)
  File "./sympy/strategies/traverse.py", line 15, in <lambda>
    return chain(lambda expr: sall(bottom_up(rule, fns), fns)(expr), rule)
  File "./sympy/strategies/traverse.py", line 37, in all_rl
    return new(op(expr), *args)
  File "./sympy/strategies/core.py", line 44, in chain_rl
    expr = rule(expr)
  File "./sympy/strategies/traverse.py", line 15, in <lambda>
    return chain(lambda expr: sall(bottom_up(rule, fns), fns)(expr), rule)
  File "./sympy/strategies/traverse.py", line 37, in all_rl
    return new(op(expr), *args)
  File "./sympy/strategies/core.py", line 44, in chain_rl
    expr = rule(expr)
  File "./sympy/strategies/traverse.py", line 15, in <lambda>
    return chain(lambda expr: sall(bottom_up(rule, fns), fns)(expr), rule)
  File "./sympy/strategies/traverse.py", line 37, in all_rl
    return new(op(expr), *args)
  File "./sympy/strategies/core.py", line 44, in chain_rl
    expr = rule(expr)
  File "./sympy/matrices/expressions/matexpr.py", line 467, in <lambda>
    rule = bottom_up(lambda x: reduce(lambda a, b: a*b, x.args) if isinstance(x, (Mul, MatMul)) else x)
  File "./sympy/matrices/expressions/matexpr.py", line 467, in <lambda>
    rule = bottom_up(lambda x: reduce(lambda a, b: a*b, x.args) if isinstance(x, (Mul, MatMul)) else x)
  File "./sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "./sympy/core/decorators.py", line 132, in binary_op_wrapper
    return func(self, other)
  File "./sympy/core/expr.py", line 151, in __mul__
    return Mul(self, other)
  File "./sympy/core/operations.py", line 45, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "./sympy/core/mul.py", line 297, in flatten
    elif o.is_commutative:
AttributeError: is_commutative
>>> MatrixExpr.from_index_summation(expr._entry(i, j))
X[i, _i_1]*A1*A2.T
```

There are two bugs: one is that it gives AttributeError on the first call but works on the second call, and the other is that the answer is wrong and has a dummy symbol in it.

**Comment by asmeurer** [comment]
CC @Upabjojr

**Comment by Upabjojr** [comment]
I would switch to recognize matrix expressions entirely with `sympy.codegen.array_utils`.

The failure does not surprise me, we don't have `KroneckerProduct` in `from_index_summation`.

**Comment by asmeurer** [comment]
It seems the algorithm is not very robust if it gives wrong answers for things it doesn't recognize.

**Comment by Upabjojr** [comment]
Yes, the new code in codegen is supposed to raise exceptions if it can not determine what it is.

**Comment by RituRajSingh878** [comment]
I would like to work on this issue

**Comment by RituRajSingh878** [comment]
```
In [42]: >>> i, j = symbols('i j', integer=True) 
    ...: >>> X = MatrixSymbol('X', 1, n*m) 
    ...: >>> A1 = MatrixSymbol("A1", n, 1) 
    ...: >>> A2 = MatrixSymbol("A2", m, 1) 
    ...: >>> expr = X*KroneckerProduct(A1, A2) 
    ...: >>> MatrixExpr.from_index_summation(expr._entry(i, j))                 
Out[42]: 
                T
(X)[i, i₁]⋅A₁⋅A₂ 


```
It is working now in sympy master(i don't know from which patch) So I think this issue can be closed.

**Comment by asmeurer** [comment]
The answer is still wrong. It should return `expr` back, and definitely shouldn't have an unbound dummy symbol in it.

**Comment by Upabjojr** [comment]
`.from_index_summation` is going to be deprecated eventually.

**Comment by asmeurer** [comment]
In favor of what?

**Comment by Upabjojr** [comment]
The new module.

**Comment by asmeurer** [comment]
I don't see why it should be deprecated. Can't we just make from_index_summation call the new code? Code that changes from mathematically wrong behavior to mathematically correct behavior doesn't require a deprecation.
