### ISSUE TITLE
Some issues with idiff

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15584]
idiff doesn't support Eq, and it also doesn't support f(x) instead of y. Both should be easy to correct.

```
>>> idiff(Eq(y*exp(y), x*exp(x)), y, x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/geometry/util.py", line 582, in idiff
    yp = solve(eq.diff(x), dydx)[0].subs(derivs)
IndexError: list index out of range
>>> idiff(f(x)*exp(f(x)) - x*exp(x), f(x), x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/geometry/util.py", line 574, in idiff
    raise ValueError("expecting x-dependent symbol(s) but got: %s" % y)
ValueError: expecting x-dependent symbol(s) but got: f(x)
>>> idiff(y*exp(y)- x*exp(x), y, x)
(x + 1)*exp(x - y)/(y + 1)
```

**Comment by krishna-akula** [comment]
Hi i am a beginner and i would like to work on this issue.

**Comment by smichr** [comment]
See comments on #15678. I can see adding `f(x)` support but not Eq for reasons given there. See #5030

**Comment by asmeurer** [comment]
But `idiff` is in the class of functions that assumes the expression = 0 (see the docstring). So I think it makes sense to accept an Eq.

**Comment by asmeurer** [comment]
Eq support was not added, but I still think it should be.
