### ISSUE TITLE
array_utils Travis/Azure doctest failures

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15588]
Travis/Azure tests are failing for unrelated PRs due to the array_utils doctest. See e.g. #15587, #15586 , #15576 .

The fail output is:
```
________________________________________________________________________________
______________ sympy.codegen.array_utils.parse_indexed_expression ______________
File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/codegen/array_utils.py", line 801, in sympy.codegen.array_utils.parse_indexed_expression
Failed example:
    parse_indexed_expression(expr, first_indices=[k])
Expected:
    CodegenArrayPermuteDims(CodegenArrayContraction(CodegenArrayTensorProduct(M, N), (1, 2)), (0 1))
Got:
    CodegenArrayPermuteDims(CodegenArrayContraction(CodegenArrayTensorProduct(M, N), (1, 2)), Permutation([1, 0]))
________________________________________________________________________________
______ sympy.codegen.array_utils.CodegenArrayPermuteDims.nest_permutation ______
File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/codegen/array_utils.py", line 438, in sympy.codegen.array_utils.CodegenArrayPermuteDims.nest_permutation
Failed example:
    cg
Expected:
    CodegenArrayPermuteDims(CodegenArrayTensorProduct(M, N), (0 1)(2 3))
Got:
    CodegenArrayPermuteDims(CodegenArrayTensorProduct(M, N), Permutation([1, 0, 3, 2]))
**********************************************************************
File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/codegen/array_utils.py", line 440, in sympy.codegen.array_utils.CodegenArrayPermuteDims.nest_permutation
Failed example:
    nest_permutation(cg)
Expected:
    CodegenArrayTensorProduct(CodegenArrayPermuteDims(M, (0 1)), CodegenArrayPermuteDims(N, (0 1)))
Got:
    CodegenArrayTensorProduct(CodegenArrayPermuteDims(M, Permutation([1, 0])), CodegenArrayPermuteDims(N, Permutation([1, 0])))
===== tests finished: 3501 passed, 2 failed, 10 skipped, in 457.11 seconds =====
DO *NOT* COMMIT!
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
Exception: Tests failed
```

I'm unable to reproduce the failure locally:
```julia
In [1]: import sympy

In [2]: sympy.doctest('array_utils.py')
==================================================================== test process starts =====================================================================
executable:         /Users/enojb/current/sympy/27venv/bin/python  (2.7.10-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              None
hash randomization: on (PYTHONHASHSEED=1343756605)

sympy/codegen/array_utils.py[9] .........                                                                                                                 [OK]

========================================================= tests finished: 9 passed, in 0.07 seconds ==========================================================
Out[2]: True
```

**Comment by jksuom** [comment]
The examples should fix the printing style of permutations by setting `Permutation.print_cyclic = True`.

**Comment by oscarbenjamin** [comment]
That looks like the right fix for now but...

There are lots of places in the doctests that modify `print_cyclic`. Changing global state like that in a doctest is a bad idea generally. Presumably the reason I can't reproduce the Travis test failures is because the tests are running in a different order on my machine: depending on the order `print_cyclic` may be `True` or `False` before this doctest runs.
