### ISSUE TITLE
Issue ufuncifying a two argument function with the Cython backend

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15628]
```
>>> ufuncify((x, y), x + y, backend='Cython')
Traceback (most recent call last):
  File "./sympy/utilities/autowrap.py", line 168, in _process_files
    retoutput = check_output(command, stderr=STDOUT)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/Users/aaronmeurer/anaconda3/bin/python', 'setup.py', 'build_ext', '--inplace']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/utilities/autowrap.py", line 1105, in ufuncify
    tempdir, args, flags, verbose, helpers, **kwargs)
  File "./sympy/utilities/autowrap.py", line 640, in autowrap
    return code_wrapper.wrap_code(routine, helpers=helps)
  File "./sympy/utilities/autowrap.py", line 149, in wrap_code
    self._process_files(routine)
  File "./sympy/utilities/autowrap.py", line 172, in _process_files
    " ".join(command), e.output.decode('utf-8')))
sympy.utilities.autowrap.CodeWrapError: Error while executing command: /Users/aaronmeurer/anaconda3/bin/python setup.py build_ext --inplace. Command output is:

Error compiling Cython file:
------------------------------------------------------------
...
    void autofunc(double *y_4785968, double *x_4785972, double *y_4785973, int m_4785969)

def autofunc_c(np.ndarray[np.double_t, ndim=1] _x, np.ndarray[np.double_t, ndim=1] _y):

    cdef int _m = _y.shape[0]
    cdef np.ndarray[np.double_t, ndim=1] _y = np.empty((_m))
                                        ^
------------------------------------------------------------

wrapper_module_3.pyx:10:41: '_y' redeclared

Error compiling Cython file:
------------------------------------------------------------
...
cimport numpy as np

cdef extern from 'wrapped_code_3.h':
    void autofunc(double *y_4785968, double *x_4785972, double *y_4785973, int m_4785969)

def autofunc_c(np.ndarray[np.double_t, ndim=1] _x, np.ndarray[np.double_t, ndim=1] _y):
                                                  ^
------------------------------------------------------------

wrapper_module_3.pyx:7:51: Previous declaration is here
warning: wrapper_module_3.pyx:10:41: cdef variable '_y' declared after it is used
Compiling wrapper_module_3.pyx because it changed.
[1/1] Cythonizing wrapper_module_3.pyx
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    setup(ext_modules=cythonize(ext_mods, **cy_opts))
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: wrapper_module_3.pyx
```

It works if the function just has one argument, or if you use a different backend.

**Comment by anpandey** [comment]
The issue seems like it's because `ufuncify` inserts dummy symbols called `y` and `m` into the generated function signature, but `dump_pyx` emits the string representation of the dummy symbols as variables within the Cython code without making sure that they're unique. The compilation error is because of the resulting name clash.

I think the simplest solution might be dummy symbols names, which always results in unique variable names, but I'm not sure if the `Dummy`'s default names would create an issue with the generated Cython code (it seems to work fine).
