### ISSUE TITLE
Issue with floor division with SetExpr

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15638]
```py
>>> from sympy.sets.setexpr import SetExpr
>>> SetExpr(Interval(0, 2))//2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "./sympy/core/decorators.py", line 132, in binary_op_wrapper
    return func(self, other)
  File "./sympy/core/expr.py", line 212, in __floordiv__
    return floor(self / other)
  File "./sympy/core/function.py", line 449, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "./sympy/core/function.py", line 270, in __new__
    evaluated = cls.eval(*args)
  File "./sympy/functions/elementary/integers.py", line 25, in eval
    if arg.is_imaginary or (S.ImaginaryUnit*arg).is_real:
  File "./sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "./sympy/core/decorators.py", line 131, in binary_op_wrapper
    return f(self)
  File "./sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "./sympy/core/decorators.py", line 132, in binary_op_wrapper
    return func(self, other)
  File "./sympy/sets/setexpr.py", line 51, in __rmul__
    return _setexpr_apply_operation(set_mul, other, self)
  File "./sympy/sets/setexpr.py", line 99, in _setexpr_apply_operation
    out = op(x, y)
  File "./sympy/sets/sets.py", line 2004, in set_mul
    return _apply_operation(_set_mul, x, y, commutative=True)
  File "./sympy/sets/sets.py", line 1989, in _apply_operation
    out = ImageSet(Lambda(d, op(x, d)), y).doit()
  File "./sympy/sets/fancysets.py", line 342, in doit
    return SetExpr(base_set)._eval_func(f).set
  File "./sympy/sets/setexpr.py", line 88, in _eval_func
    res = set_function(func, self.set)
  File "./sympy/sets/sets.py", line 2016, in set_function
    return _set_function(f, x)
  File "./sympy/multipledispatch/dispatcher.py", line 198, in __call__
    return func(*args, **kwargs)
  File "./sympy/sets/handlers/functions.py", line 86, in _set_function
    start, end = Min(*extr), Max(*extr)
  File "./sympy/functions/elementary/miscellaneous.py", line 350, in __new__
    args = frozenset(cls._new_args_filter(args))
  File "./sympy/functions/elementary/miscellaneous.py", line 523, in _new_args_filter
    raise ValueError("The argument '%s' is not comparable." % arg)
ValueError: The argument 'I' is not comparable.
```

I'm not sure where the imaginary number comes from.

**Comment by ethankward** [comment]
What does it mean to take the floor of a set?

**Comment by normalhuman** [comment]
I suppose that for any function f, the notation f(A) means {f(x): x in A}. 
So, if the function is f(x) = floor(x/2), then f(Interval(0, 2)) is {0, 1, 2}, considering that Interval is closed by default.

**Comment by asmeurer** [comment]
Yeah the set expressions compose mathematical functions with the elements of the set.

**Comment by jmig5776** [comment]
I would like to work on this issue.

**Comment by jmig5776** [comment]
In more naive way the problem is this check

>>S.ImaginaryUnit*SetExpr(Interval(0, 1))

here the multiplication of S.Imaginary Unit with an Interval is not able to be calculated.

**Comment by asmeurer** [comment]
Looks like there aren't any assumptions defined for SetExpr. The assumptions should probably give True or False if every element of the set satisfies it, and None otherwise. But this is probably not so trivial to implement. I think the best you can do is assign each assumption to its corresponding set and see if intersecting that set produces the same set or the empty set.

**Comment by jmig5776** [comment]
I had assigned only two assumptions to the corresponding interval and done as u said .I got able to get this

>>print((SetExpr(Interval(0,1)).is_imaginary))
False

and 
>>print((SetExpr(Interval(0,1)).is_real))
True

I am not able to do it further. I mean that i want to multiply S.ImaginaryUnit to the given SetExpr ,thats where error is occuring.
I am trying to solve it

**Comment by asmeurer** [comment]
Interval doesn't support imaginary intervals. It would need to create the interval representing the line segment in the complex plane, probably using ImageSet.

**Comment by asmeurer** [comment]
The interval can be represented using ImageSet. I don't know if things will always simplify, but everything should be representable.
