### ISSUE TITLE
MatrixSymbol should check that its arguments are valid

### ISSUE THREAD

**Issue by normalhuman** [sympy/sympy#15643]
Today I forgot the order of arguments in MatrixSymbol and typed
```
A = MatrixSymbol(9, 2, 'A')
```
No error messages were shown, and I proceeded to use this `A`, getting a confusing error: 
```
>>> A.T*A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/sympy/sympy/core/basic.py", line 407, in __repr__
    return sstr(self, order=None)
  File "/home/ubuntu/sympy/sympy/printing/str.py", line 843, in sstr
    s = p.doprint(expr)
  File "/home/ubuntu/sympy/sympy/printing/printer.py", line 249, in doprint
    return self._str(self._print(expr))
  File "/home/ubuntu/sympy/sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "/home/ubuntu/sympy/sympy/printing/str.py", line 335, in _print_MatMul
    [self.parenthesize(arg, precedence(expr)) for arg in expr.args]
TypeError: sequence item 1: expected str instance, int found
```
I think it's better to check that the arguments make sense when creating MatrixSymbol.

**Comment by asmeurer** [comment]
A consequence of my branch https://github.com/sympy/sympy/pull/15121 is that this now gives an error

```
>>> A = MatrixSymbol(9, 2, 'A')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/matrices/expressions/matexpr.py", line 673, in __new__
    n, m = _sympify(n), _sympify(m)
  File "./sympy/core/sympify.py", line 405, in _sympify
    return sympify(a, strict=True)
  File "./sympy/core/sympify.py", line 327, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: 'A'
```

**Comment by Puranjay25** [comment]
Is this issue resloved ? 
If not, then I want to work on this issue
