### ISSUE TITLE
Compilation tools in sympy.utilities do not handle nonstandard libgfortran location

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#15671]
See https://github.com/sympy/sympy/issues/15385#issuecomment-448715970. The failures in Azure pipelines are like 

```
2018-12-12T21:47:31.7271950Z ________________ sympy/codegen/tests/test_fnodes.py:test_bind_C ________________
2018-12-12T21:47:31.7271999Z Traceback (most recent call last):
2018-12-12T21:47:31.7272272Z   File "/usr/envs/optional-dependencies/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/codegen/tests/test_fnodes.py", line 185, in test_bind_C
2018-12-12T21:47:31.7272319Z     if not has_fortran():
2018-12-12T21:47:31.7272578Z   File "/usr/envs/optional-dependencies/lib/python2.7/site-packages/sympy-1.4.dev0-py2.7.egg/sympy/utilities/_compilation/availability.py", line 24, in has_fortran
2018-12-12T21:47:31.7272647Z     raise ValueError("Failed to compile test program:\n%s\n%s\n" % (stdout, stderr))
2018-12-12T21:47:31.7272686Z ValueError: Failed to compile test program:
```

**Comment by moorepants** [comment]
If core libs aren't in standard locations, shouldn't it be up to the user to set environment variables to ensure they are found? I don't think sympy should be responsible for finding the libs.
