### ISSUE TITLE
Continuousness of B splines

### ISSUE THREAD

**Issue by moesphere** [sympy/sympy#15677]
The piecewise objects that are returned when creating B splines, should be either right-continuous (preferred, see Carl de Boor's book or papers) or left-continuous.

Currently, the boundaries of an interval are also part of the adjacent intervals.
See e.g. [here](https://docs.sympy.org/latest/modules/functions/special.html#sympy.functions.special.bsplines.bspline_basis)

**Comment by normalhuman** [comment]
This is only relevant for `d=0`, right? Otherwise the splines are continuous. The support for degree-0 splines seems inconsistent at present.
```
>>> interpolating_spline(0, x, [1, 2, 3], [1, 2, 3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/k3/sympy/sympy/functions/special/bsplines.py", line 250, in interpolating_spline
    "Spline degree must be a positive integer, not %s." % d)
ValueError: Spline degree must be a positive integer, not 0.
```
but
```
>>> bspline_basis_set(0, [1, 2, 3], x)
[Piecewise((1, (x >= 1) & (x <= 2)), (0, True)), Piecewise((1, (x >= 2) & (x <= 3)), (0, True))]
```
I agree using closed intervals here is problematic because these Piecewise functions are __not__ a basis for degree 0 splines. To be consistent with [Wikipedia](https://en.wikipedia.org/wiki/B-spline#Definition) or the sources you mentioned, we need 
```
[Piecewise((1, (x >= 1) & (x < 2)), (0, True)), Piecewise((1, (x >= 2) & (x < 3)), (0, True))]
```

**Comment by moesphere** [comment]
In general it is at least possible to have jumps with higher degree splines, if the multiplicity of a knot is large enough.
