### ISSUE TITLE
Compilation test fail

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#15713]
The compilation test fails with numpy and cython installed.

```
$ bin/test compilation
============================= test process starts ==============================
executable:         C:\Users\sylee\AppData\Local\conda\conda\envs\sympy_dev_36\python.exe  (3.6.7-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python
numpy:              1.15.4
random seed:        20915741
hash randomization: on (PYTHONHASHSEED=424893019)

sympy\utilities\_compilation\tests\test_compilation.py[1] E               [FAIL]

________________________________________________________________________________
 sympy\utilities\_compilation\tests\test_compilation.py:test_compile_link_import_strings
Traceback (most recent call last):
  File "C:\Users\sylee\Documents\GitHub\sympy\sympy\utilities\_compilation\compilation.py", line 528, in compile_link_import_py_ext
    mod = import_module_from_file(os.path.join(build_dir, extname), sources)
  File "C:\Users\sylee\Documents\GitHub\sympy\sympy\utilities\_compilation\util.py", line 266, in import_module_from_file
    raise ImportError("Failed to import: '%s'" % filename)
ImportError: Failed to import: 'C:\Users\sylee\AppData\Local\Temp\tmp6djotwi2\_sigmoid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\sylee\documents\github\sympy\sympy\utilities\_compilation\tests\test_compilation.py", line 54, in test_compile_link_import_strings
    mod, info = compile_link_import_strings(_sources1, compile_kwargs=compile_kw)
  File "C:\Users\sylee\Documents\GitHub\sympy\sympy\utilities\_compilation\compilation.py", line 584, in compile_link_import_strings
    mod = compile_link_import_py_ext(source_files, build_dir=build_dir, **kwargs)
  File "C:\Users\sylee\Documents\GitHub\sympy\sympy\utilities\_compilation\compilation.py", line 531, in compile_link_import_py_ext
    cwd=build_dir, **compile_kwargs)
  File "C:\Users\sylee\Documents\GitHub\sympy\sympy\utilities\_compilation\compilation.py", line 97, in compile_sources
    dstpaths.append(src2obj(f, Runner, cwd=cwd, **file_kwargs))
  File "C:\Users\sylee\Documents\GitHub\sympy\sympy\utilities\_compilation\compilation.py", line 383, in src2obj
    run_linker=run_linker, cwd=cwd, flags=flags, **kwargs)
  File "C:\Users\sylee\Documents\GitHub\sympy\sympy\utilities\_compilation\runners.py", line 82, in __init__
    self.compiler_name, self.compiler_binary, self.compiler_vendor = self.find_compiler(preferred_vendor)
  File "C:\Users\sylee\Documents\GitHub\sympy\sympy\utilities\_compilation\runners.py", line 136, in find_compiler
    name, path = find_binary_of_command([cls.compiler_dict[x] for x in candidates])
  File "C:\Users\sylee\Documents\GitHub\sympy\sympy\utilities\_compilation\util.py", line 294, in find_binary_of_command
    raise CompilerNotFoundError('No binary located for candidates: {}'.format(candidates))
sympy.utilities._compilation.util.CompilerNotFoundError: No binary located for candidates: ['gcc', 'icc', 'clang']

=========== tests finished: 0 passed, 1 exceptions, in 0.05 seconds ============
DO *NOT* COMMIT!
```

**Comment by sylee957** [comment]
After adding the test to travis, I don't see the same error but another warning 
```
sympy/utilities/_compilation/tests/test_compilation.py[1] /home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/tmpa0vbm9cv/_sigmoid.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
.                 [OK]
```
