### ISSUE TITLE
Hang in rsolve (apparently due to slow casoratian determinant calculation)

### ISSUE THREAD

**Issue by ehren** [sympy/sympy#15751]
A number of solvable recurrence equations result in a hang when calling `rsolve`. This looks to be due to a slow calculation of the cassoration determinant.

Here's an example that still hangs after several hours of computation:

```
>>> from sympy import Function, symbols, rsolve
>>> n = symbols("n", integer=True)
>>> y = Function("y")
>>> f = y(n) + 21*y(n + 1) - 273*y(n + 2) - 1092*y(n + 3) + 1820*y(n + 4) + 1092*y(n + 5) - 273*y(n + 6) - 21*y(n + 7) + y(n + 8)
>>> rsolve(f, y(n))
```

Typical stack trace when interrupting the calculation:

```
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/solvers/recurr.py", line 792, in rsolve
    result = rsolve_hyper(coeffs, -i_part, n, symbols=True)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/solvers/recurr.py", line 643, in rsolve_hyper
    if casoratian(kernel + [K], n, zero=False) != 0:
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/matrices/dense.py", line 1074, in casoratian
    return Matrix(k, k, f).det()
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/matrices/matrices.py", line 429, in det
    return self._eval_det_bareiss()
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/matrices/matrices.py", line 219, in _eval_det_bareiss
    return cancel(bareiss(self))
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/matrices/matrices.py", line 217, in bareiss
    return sign*bareiss(self._new(mat.rows - 1, mat.cols - 1, entry), pivot_val)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/matrices/matrices.py", line 217, in bareiss
    return sign*bareiss(self._new(mat.rows - 1, mat.cols - 1, entry), pivot_val)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/matrices/matrices.py", line 217, in bareiss
    return sign*bareiss(self._new(mat.rows - 1, mat.cols - 1, entry), pivot_val)
  [Previous line repeated 2 more times]
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/matrices/dense.py", line 432, in _new
    rows, cols, flat_list = cls._handle_creation_inputs(*args, **kwargs)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/matrices/matrices.py", line 2154, in _handle_creation_inputs
    for j in range(cols)])
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/matrices/matrices.py", line 2154, in <listcomp>
    for j in range(cols)])
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/matrices/matrices.py", line 214, in entry
    cancel(ret)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/polys/polytools.py", line 6594, in cancel
    (F, G), opt = parallel_poly_from_expr((p, q), *gens, **args)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/polys/polytools.py", line 4313, in parallel_poly_from_expr
    return _parallel_poly_from_expr(exprs, opt)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/polys/polytools.py", line 4352, in _parallel_poly_from_expr
    expr = expr.expand()
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/expr.py", line 3124, in expand
    expr, hit = Expr._expand_hint(expr, hint, deep=deep, **hints)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/expr.py", line 3057, in _expand_hint
    arg, arghit = Expr._expand_hint(arg, hint, **hints)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/expr.py", line 3057, in _expand_hint
    arg, arghit = Expr._expand_hint(arg, hint, **hints)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/expr.py", line 3065, in _expand_hint
    newexpr = getattr(expr, hint)(**hints)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/mul.py", line 885, in _eval_expand_mul
    terms = self.func._expandsums(sums)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/mul.py", line 850, in _expandsums
    terms = [Mul(a, b) for a in left for b in right]
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/mul.py", line 850, in <listcomp>
    terms = [Mul(a, b) for a in left for b in right]
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/operations.py", line 45, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/mul.py", line 614, in flatten
    _mulsort(c_part)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/mul.py", line 34, in _mulsort
    args.sort(key=_args_sortkey)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/basic.py", line 196, in compare
    c = (n1 > n2) - (n1 < n2)
  File "/Users/ehren/Documents/abachi/37env/lib/python3.7/site-packages/sympy/core/core.py", line 102, in __gt__
    if cls.__cmp__(other) == 1:
KeyboardInterrupt
```

From profiling, most of the time is spent in `expand` (as a result of the `cancel` call in the determinant `'bareis'` method).

Switching `cassoration` to use the `'berkowitz'` method for the determinant allows examples like these to complete quickly (about 2 seconds for the above example):

```
>>> rsolve(f, y(n))  # using 'berkowitz'
C0*(-11/2 + 5*sqrt(5)/2)**n + C1*(-1/2 + sqrt(5)/2)**n + C2*(2 + sqrt(5))**n + C3*(29/2 + 13*sqrt(5)/2)**n + C4*(-13*sqrt(5)/2 + 29/2)**n + C5*(-5*sqrt(5)/2 - 11/2)**n + C6*(-sqrt(5) + 2)**n + C7*(-sqrt(5)/2 - 1/2)**n
```

 (using `'lu'` instead of the default `'bareis'` also results in a hang). 

Just a note: #11031 has another example where a determinant calculation using the Berkowitz algorithm performs much better

**Comment by asmeurer** [comment]
That other issue suggests that the problem is those other methods calling expand, rather than the method itself. Maybe we should just remove the expand calls, or have a flag to turn them off.

**Comment by ehren** [comment]
In the stack trace above the expand is due to the `cancel` calls in `_eval_det_bareiss`. It's easy to disable these but with the above testcase we still hang due to `cancel` calls from the use of `simplify` in `_find_reasonable_pivot`.

e.g. with this patch against my pull branch

```
diff --git a/sympy/matrices/dense.py b/sympy/matrices/dense.py
index 887c08ec6..6b8a20362 100644
--- a/sympy/matrices/dense.py
+++ b/sympy/matrices/dense.py
@@ -1084,7 +1084,8 @@ def casoratian(seqs, n, zero=True):
 
     k = len(seqs)
 
-    return Matrix(k, k, f).det(method="berkowitz")
+    # avoid use of _is_zero_after_expand_mul in _eval_det_bareiss
+    return Matrix(k, k, f).det(iszerofunc=_iszero)
 
 
 def eye(*args, **kwargs):
diff --git a/sympy/matrices/matrices.py b/sympy/matrices/matrices.py
index ba5d3a75c..aa7bbc8e6 100644
--- a/sympy/matrices/matrices.py
+++ b/sympy/matrices/matrices.py
@@ -211,12 +211,14 @@ def bareiss(mat, cumm=1):
             def entry(i, j):
                 ret = (pivot_val*tmp_mat[i, j + 1] - mat[pivot_pos, j + 1]*tmp_mat[i, 0]) / cumm
                 if not ret.is_Atom:
-                    cancel(ret)
+                    # cancel(ret)
+                    pass
                 return ret
 
             return sign*bareiss(self._new(mat.rows - 1, mat.cols - 1, entry), pivot_val)
 
-        return cancel(bareiss(self))
+        # return cancel(bareiss(self))
+        return bareiss(self)
 
     def _eval_det_berkowitz(self):
         """ Use the Berkowitz algorithm to compute the determinant."""

```

We'll hang with traces like

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/utilities/runtests.py", line 568, in _test
    enhance_asserts=enhance_asserts, fail_on_timeout=fail_on_timeout))
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/utilities/runtests.py", line 1107, in test
    enhance_asserts, fail_on_timeout)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/utilities/runtests.py", line 1243, in test_file
    f()
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/solvers/tests/test_recurr.py", line 209, in test_issue_15751
    assert rsolve(f, y(n)) is not None
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/solvers/recurr.py", line 792, in rsolve
    result = rsolve_hyper(coeffs, -i_part, n, symbols=True)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/solvers/recurr.py", line 643, in rsolve_hyper
    if casoratian(kernel + [K], n, zero=False) != 0:
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/matrices/dense.py", line 1089, in casoratian
    return Matrix(k, k, f).det(iszerofunc=_iszero)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/matrices/matrices.py", line 480, in det
    return self._eval_det_bareiss(iszerofunc=iszerofunc)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/matrices/matrices.py", line 221, in _eval_det_bareiss
    return bareiss(self)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/matrices/matrices.py", line 218, in bareiss
    return sign*bareiss(self._new(mat.rows - 1, mat.cols - 1, entry), pivot_val)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/matrices/matrices.py", line 218, in bareiss
    return sign*bareiss(self._new(mat.rows - 1, mat.cols - 1, entry), pivot_val)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/matrices/matrices.py", line 218, in bareiss
    return sign*bareiss(self._new(mat.rows - 1, mat.cols - 1, entry), pivot_val)
  [Previous line repeated 1 more time]
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/matrices/matrices.py", line 198, in bareiss
    iszerofunc=iszerofunc)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/matrices/matrices.py", line 4451, in _find_reasonable_pivot
    simped = simpfunc(x)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/simplify/simplify.py", line 565, in simplify
    _e = cancel(expr)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/polys/polytools.py", line 6611, in cancel
    (F, G), opt = parallel_poly_from_expr((p, q), *gens, **args)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/polys/polytools.py", line 4313, in parallel_poly_from_expr
    return _parallel_poly_from_expr(exprs, opt)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/polys/polytools.py", line 4352, in _parallel_poly_from_expr
    expr = expr.expand()
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/core/expr.py", line 3165, in expand
    expr, hit = Expr._expand_hint(expr, hint, deep=deep, **hints)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/core/expr.py", line 3098, in _expand_hint
    arg, arghit = Expr._expand_hint(arg, hint, **hints)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/core/expr.py", line 3106, in _expand_hint
    newexpr = getattr(expr, hint)(**hints)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/core/mul.py", line 884, in _eval_expand_mul
    terms = self.func._expandsums(sums)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/core/mul.py", line 849, in _expandsums
    terms = [Mul(a, b) for a in left for b in right]
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/core/mul.py", line 849, in <listcomp>
    terms = [Mul(a, b) for a in left for b in right]
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/core/operations.py", line 45, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/core/mul.py", line 445, in flatten
    if b != bi:
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/core/basic.py", line 352, in __ne__
    return not self == other
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/core/basic.py", line 321, in __eq__
    tself = type(self)
``` 

Removing any of those `cancel`s also results in a few determinate testcase failures.

```
  File "/Users/ehren/Documents/ehrensympy/sympy2/sympy/matrices/tests/test_commonmatrix.py", line 749, in test_det
    assert e.det() == 4*x - 24
AssertionError
```

**Comment by asmeurer** [comment]
Some related issues: https://github.com/sympy/sympy/issues/13805 and https://github.com/sympy/sympy/issues/11082.

**Comment by ehren** [comment]
With this testcase it's maybe not too surprising that cancel is taking so long. It's getting repeatedly called with larger and larger expressions due the complexity of the determinants calculated.

rsolve_hyper loops over the roots of the 8-th order characteristic polynomial associated with the recurrence here: https://github.com/sympy/sympy/blob/ab14b02dba5a7e3e4fb1e807fc8a954f1047a1a1/sympy/solvers/recurr.py#L643

For example the 5th iteration calculates the determinant of a 5x5 matrix whose determinant is very large:

```
sympify("Matrix([[(-13*sqrt(5)/2 + 29/2)**n, (29/2 + 13*sqrt(5)/2)**n, (-sqrt(5) + 2)**n, (2 + sqrt(5))**n, (-sqrt(5)/2 - 1/2)**n], [(-13*sqrt(5)/2 + 29/2)**(n + 1), (29/2 + 13*sqrt(5)/2)**(n + 1), (-sqrt(5) + 2)**(n + 1), (2 + sqrt(5))**(n + 1), (-sqrt(5)/2 - 1/2)**(n + 1)], [(-13*sqrt(5)/2 + 29/2)**(n + 2), (29/2 + 13*sqrt(5)/2)**(n + 2), (-sqrt(5) + 2)**(n + 2), (2 + sqrt(5))**(n + 2), (-sqrt(5)/2 - 1/2)**(n + 2)], [(-13*sqrt(5)/2 + 29/2)**(n + 3), (29/2 + 13*sqrt(5)/2)**(n + 3), (-sqrt(5) + 2)**(n + 3), (2 + sqrt(5))**(n + 3), (-sqrt(5)/2 - 1/2)**(n + 3)], [(-13*sqrt(5)/2 + 29/2)**(n + 4), (29/2 + 13*sqrt(5)/2)**(n + 4), (-sqrt(5) + 2)**(n + 4), (2 + sqrt(5))**(n + 4), (-sqrt(5)/2 - 1/2)**(n + 4)]])", locals={"n":n})
```

In the final iterations the determinants are too large to even print.

Incidentally, I'm pretty close to releasing a module that will better deal with expressions like the determinant of the above 5x5 (it can be simplified to `-12187500*(-1)**n*GoldenRatio**(n + 2)`). It will also simplify the output of rsolve in these cases (particular sequences matching the testcase recurrence have both an 'expanded' and 'factored' simplified fibonacci form). I don't think this module should be integrated into `rsolve` directly though, but integration with `simplify` might be a good approach.

**Comment by ehren** [comment]
Turns out there's an easy fix for this case that doesn't require switching to the berkowitz algorithm. There's a call to cancel in bareiss that drops the return value. Apparently this is causing cancel to be called repeatedly. I'll update the pull with this change.
