### ISSUE TITLE
Sympy does not apply series function to matrix elements

### ISSUE THREAD

**Issue by jmsureda** [sympy/sympy#15765]
When working with MutableDenseMatrix, I've found that applying directly the series function on the object does not work and does not rise any error. Evenmore if you apply the series function on each element of the matrix indepently (using a for loop or just on one element) does not work either. 

**This does not work:**

`B[0,0] = sp.series(B[0,0], x = epsilon,n=4)`

Converting first the sympy expression into a string and then converting it again into a sympy expression does work.

**This Works:**
        
`expr = str(B[0,0])`

`element = sp.sympify(expr) ` 

`B[0,0] = sp.series(element, x = epsilon,n=4)`

**Comment by rnhmjoj** [comment]
```
>>> series(sqrt(1+x))
         2    3      4      5        
    x   x    x    5⋅x    7⋅x     ⎛ 6⎞
1 + ─ - ── + ── - ──── + ──── + O⎝x ⎠
    2   8    16   128    256         
>>> series(Matrix([sqrt(1+x)]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/series/series.py", line 63, in series
    return expr.series(x, x0, n, dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/core/expr.py", line 3034, in series
    s1 = self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/core/expr.py", line 3418, in _eval_nseries
    raise NotImplementedError(filldedent("""
NotImplementedError: 
The _eval_nseries method should be added to <class 'sympy.matrices.immutable.ImmutableDenseMatrix'>
to give terms up to O(x**n) at x=0 from the positive direction so it is available when nseries calls it.
```
