### ISSUE TITLE
_xreplace error differentiating function of function

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15947]
It's possible to call f(g) when f and g are both functions. The result raises an error when differentiating:
```julia
In [1]: f, g = symbols('f g', cls=Function)                                                                                       

In [2]: f(g)                                                                                                                      
Out[2]: f(g)

In [3]: f(g).diff(g)                                                                                                              
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-eede1c664f27> in <module>
----> 1 f(g).diff(g)

~/current/sympy/sympy/sympy/core/expr.py in diff(self, *symbols, **assumptions)
   3065     def diff(self, *symbols, **assumptions):
   3066         assumptions.setdefault("evaluate", True)
-> 3067         return Derivative(self, *symbols, **assumptions)
   3068 
   3069     ###########################################################################

~/current/sympy/sympy/sympy/core/function.py in __new__(cls, expr, *variables, **kwargs)
   1351                 old_v = v
   1352                 v = Dummy('xi')
-> 1353                 expr = expr.xreplace({old_v: v})
   1354                 # Derivatives and UndefinedFunctions are independent
   1355                 # of all others

~/current/sympy/sympy/sympy/core/basic.py in xreplace(self, rule)
   1179 
   1180         """
-> 1181         value, _ = self._xreplace(rule)
   1182         return value
   1183 

~/current/sympy/sympy/sympy/core/basic.py in _xreplace(self, rule)
   1193             for a in self.args:
   1194                 try:
-> 1195                     a_xr = a._xreplace(rule)
   1196                     args.append(a_xr[0])
   1197                     changed |= a_xr[1]

TypeError: _xreplace() missing 1 required positional argument: 'rule'
```
This is an error but it's an odd error message. Probably this should be disallowed but it should be explicitly checked and disallowed with a better error message.

Perhaps f(g) should raise an error in the first place.

**Comment by smichr** [comment]
> Perhaps f(g) should raise an error in the first place.

Since `f+1, f*2, f**3` all raise, it is left to make raise the case `func(func)`...but maybe all cases could raise more intelligently by seeing that no arg is an Undefined function. They must be AppliedDef.

**Comment by smichr** [comment]
```
>>> f(x).diff(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\core\expr.py", line 3085, in diff
    return Derivative(self, *symbols, **assumptions)
  File "sympy\core\function.py", line 1246, in __new__
    "UndefinedFunction: %s" % v)
ValueError: cannot differentiate wrt UndefinedFunction: f
>>> f(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\core\function.py", line 811, in __new__
    's'*(len(u) > 1), ', '.join(u)))
ValueError: invalid argument: f
```

```diff
diff --git a/sympy/core/function.py b/sympy/core/function.py
index 74fd41c..92f10f4 100644
--- a/sympy/core/function.py
+++ b/sympy/core/function.py
@@ -805,6 +805,10 @@ class AppliedUndef(Function):
 
     def __new__(cls, *args, **options):
         args = list(map(sympify, args))
+        u = [a.name for a in args if isinstance(a, UndefinedFunction)]
+        if u:
+            raise ValueError('invalid argument%s: %s' % (
+                's'*(len(u) > 1), ', '.join(u)))
         obj = super(AppliedUndef, cls).__new__(cls, *args, **options)
         return obj
 
@@ -872,6 +876,11 @@ def __eq__(self, other):
     def __ne__(self, other):
         return not self == other
 
+    @property
+    def _diff_wrt(self):
+        return False
+
+
 
 class WildFunction(Function, AtomicExpr):
     """
@@ -1235,6 +1244,10 @@ def __new__(cls, expr, *variables, **kwargs):
                         v, count = v
                     if count == 0:
                         continue
+                elif isinstance(v, UndefinedFunction):
+                    raise ValueError(
+                        "cannot differentiate wrt "
+                        "UndefinedFunction: %s" % v)
                 else:
                     count = 1
                 variable_count.append(Tuple(v, count))
diff --git a/sympy/core/tests/test_function.py b/sympy/core/tests/test_function.py
index 130e19b..165d8f8 100644
--- a/sympy/core/tests/test_function.py
+++ b/sympy/core/tests/test_function.py
@@ -1224,3 +1224,9 @@ def test_Subs_Derivative():
 def test_issue_15360():
     f = Function('f')
     assert f.name == 'f'
+
+
+def test_issue_15947():
+    assert f._diff_wrt is False
+    raises(ValueError, lambda: f(f))
+    raises(ValueError, lambda: f(x).diff(f))
```

**Comment by mianzg** [comment]
I'd like to work on this. Could you guide me more?

**Comment by shafique18** [comment]
@mianzg are you still working on the issue, I want to work on this issue please guide me to get better understanding.
