### ISSUE TITLE
TypeError in as_independent

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#16011]
`sqrt(144*x**6 + 408*x**3 + 290).as_independent(Symbol('x', positive=True), as_Add=False)` raises `TypeError`. Without `as_Add=False` error is the same.

**Comment by oscargus** [comment]
I cannot reproduce it. Can you send a complete minimal example with imports etc?

**Comment by proy87** [comment]
Try this:

`x = Symbol('x', positive=True)`
`sqrt ((12*x**3 + 17)**2 + 1).as_independent(x)`

**Comment by oscargus** [comment]
```
In [1]: from sympy import Symbol, sqrt

In [2]: x = Symbol('x', positive=True)
   ...: sqrt ((12*x**3 + 17)**2 + 1).as_independent(x)
Out[2]: (1, sqrt((12*x**3 + 17)**2 + 1))
```
This is on the very latest master, Python 3.7.1, though.

**Comment by oscarbenjamin** [comment]
It also works in the lates release (1.3):
```julia
In [2]: x = Symbol('x', positive=True)                                                                                                                        

In [3]: sqrt ((12*x**3 + 17)**2 + 1).as_independent(x)                                                                                                        
Out[3]: 
⎛       ___________________⎞
⎜      ╱             2     ⎟
⎜     ╱  ⎛    3     ⎞      ⎟
⎝1, ╲╱   ⎝12⋅x  + 17⎠  + 1 ⎠
```
Which version are you using?

**Comment by proy87** [comment]
I tested it on sympy.live

**Comment by oscarbenjamin** [comment]
Does it only happen sometimes?

I just tried it on [https://live.sympy.org/](https://live.sympy.org/) and it worked fine.

**Comment by proy87** [comment]
Looks like the error is random.

expr.as_independent(symbol, as_Add=False)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/expr.py", line 1689, in as_independent
    if self.is_zero:
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 248, in getit
    return _ask(fact, self)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 303, in _ask
    _ask(pk, obj)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 291, in _ask
    a = evaluate(obj)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/power.py", line 459, in _eval_is_negative
    elif self.base.is_positive:
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 248, in getit
    return _ask(fact, self)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/assumptions.py", line 291, in _ask
    a = evaluate(obj)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/add.py", line 589, in _eval_is_positive
    v = _monotonic_sign(a)
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/exprtools.py", line 129, in _monotonic_sign
    if x.is_nonnegative and all(r <= x0 for r in roots):
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/relational.py", line 229, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational

**Comment by oscarbenjamin** [comment]
Is Sympy live using Python 2.7? That should be updated...

If it is random then it most likely depends on dict/set ordering somewhere. That's difficult to debug. 

How many times do you need to try it to see the error? Are you restarting SymPy between attempts or running it repeatedly within the same shell?

**Comment by proy87** [comment]
from sympy.core.cache import clear_cache
f=sqrt (144*x**6 + 408*x**3 + 290)
clear_cache()
f = f.replace(x, Symbol('x', positive=True))
clear_cache()
powsimp(f, deep=True, force=True)

**Comment by oscarbenjamin** [comment]
Okay now I can reproduce this but only on Python 2.7:
```console
(27venv) enojb@IT035770:~/current/sympy/sympy$ cat test.py 
from sympy import *
from sympy.core.cache import clear_cache
x = Symbol('x')
f=sqrt (144*x**6 + 408*x**3 + 290)
clear_cache()
f = f.replace(x, Symbol('x', positive=True))
clear_cache()
powsimp(f, deep=True, force=True)
(27venv) enojb@IT035770:~/current/sympy/sympy$ python --version
Python 2.7.10
(27venv) enojb@IT035770:~/current/sympy/sympy$ python test.py 
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    powsimp(f, deep=True, force=True)
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/powsimp.py", line 121, in powsimp
    return recurse(expr*_y, deep=False)/_y
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/powsimp.py", line 109, in recurse
    return powsimp(arg, _deep, _combine, _force, _measure)
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/powsimp.py", line 372, in powsimp
    recurse(newexpr, combine='base')
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/powsimp.py", line 109, in recurse
    return powsimp(arg, _deep, _combine, _force, _measure)
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/powsimp.py", line 390, in powsimp
    if not (all(x.is_nonnegative for x in b.as_numer_denom()) or e.is_integer or force or b.is_polar):
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/powsimp.py", line 390, in <genexpr>
    if not (all(x.is_nonnegative for x in b.as_numer_denom()) or e.is_integer or force or b.is_polar):
  File "/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py", line 248, in getit
    return _ask(fact, self)
  File "/Users/enojb/current/sympy/sympy/sympy/core/assumptions.py", line 291, in _ask
    a = evaluate(obj)
  File "/Users/enojb/current/sympy/sympy/sympy/core/add.py", line 647, in _eval_is_nonnegative
    v = _monotonic_sign(a)
  File "/Users/enojb/current/sympy/sympy/sympy/core/exprtools.py", line 129, in _monotonic_sign
    if x.is_nonnegative and all(r <= x0 for r in currentroots):
  File "/Users/enojb/current/sympy/sympy/sympy/core/relational.py", line 260, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational
```
