### ISSUE TITLE
NotImplementedError for series expansion of ( Integral((a+x)**(-1), (x, 0, 1)) )**(-1)

### ISSUE THREAD

**Issue by smheidrich** [sympy/sympy#16182]
Before you yell at me, the expression below is not the actual expression I want to do a series expansion on (would be pointless since it can be trivially evaluated analytically), it's just what I boiled down as the minimal reproducible example from the actual (much larger, not trivially simplifiable) expression.

So here goes:

```python
from sympy import Integral, Symbol, series

a = Symbol("a")
x = Symbol("x")
expr = ( Integral((a+x)**(-1), (x, 0, 1)) )**(-1)

expr_expansion = series(expr, a, n=1)
```

raises

```
Traceback (most recent call last):
  File "sympy_bug.py", line 7, in <module>
    expr_expansion = series(expr, a, n=1)
  File "/home/smheidrich/.local/lib/python3.7/site-packages/sympy/series/series.py", line 12, in series
    return expr.series(x, x0, n, dir)
  File "/home/smheidrich/.local/lib/python3.7/site-packages/sympy/core/expr.py", line 2662, in series
    rv = self.subs(x, xpos).series(xpos, x0, n, dir, logx=logx)
  File "/home/smheidrich/.local/lib/python3.7/site-packages/sympy/core/expr.py", line 2669, in series
    s1 = self._eval_nseries(x, n=n, logx=logx)
  File "/home/smheidrich/.local/lib/python3.7/site-packages/sympy/core/power.py", line 1375, in _eval_nseries
    raise NotImplementedError()
NotImplementedError
```

So it seems like something just isn't implemented yet (in ``_eval_nseries``), and this constitues a feature request more than a bug report...

Replacing ``Integral`` by ``integrate`` makes it work fine, but that is not an option for the actual expression I want to do a series expansion on, as ``integrate`` gets stuck on it.

**Comment by divyanshu132** [comment]
@smheidrich try this:

```
>>> expr = ( Integral((a+x)**(-1), (x, 0, 1)) )**(-1)
>>> expr=expr.doit()
>>> expr
1/(-log(a) + log(a + 1))
>>> expr_expansion = series(expr, a, n=1)
>>> expr_expansion
-1/log(a) + O(a)

```

**Comment by smheidrich** [comment]
@divyanshu132 ``doit()`` evaluates the integral, but like I said, that only works here because the integral is trivial. It's not possible in the actual expression I want to expand (not shown here).

**Comment by divyanshu132** [comment]
Can you provide the actual expression so, anyone can test it otherwise it will be difficult to resolve the actual issue.

**Comment by smheidrich** [comment]
Sure:

```python
from sympy import sqrt, Integral, Symbol, cos, pi, Function, elliptic_k, series

class alt_elliptic_k(Function):
  nargs = 1

  @classmethod
  def eval(cls, k):
    return elliptic_k(sqrt(k))

a = Symbol("a")
c = Symbol("c")
d = Symbol("d")
x = Symbol("x")
p = Symbol("p")

subexpr = 2/pi**2 * Integral(
  (1-cos(x))/(2*d*a+c*(1-cos(x)))
  *
  alt_elliptic_k(
    2*d*a/(2*d*a+c*(1-cos(x)))
  ),
  (x, 0, pi)
)

expr = (
  (1-p)*(c-a)/(a+1/subexpr-c)
  +
  p*c/(1/subexpr-a-c)
)

expr_series = series(expr, d, n=1)
```

But all this does it make things more complicated (and hence prevent ``doit()`` from doing much other than heating up the CPU), the issue is still the same.

A colleague of mine suggested I series expand just the integrand first, and that works just fine for my use case (as all I want for now is *some* approximation to this), so my actual problem is solved - I just thought I'd report this anyway.

**Comment by oscarbenjamin** [comment]
Thanks for reporting this.

NotImplementedError is raised from here:
[https://github.com/sympy/sympy/blob/d2fcf9ecdfef464b26f0e118018a7817059d22a2/sympy/core/power.py#L1375](https://github.com/sympy/sympy/blob/d2fcf9ecdfef464b26f0e118018a7817059d22a2/sympy/core/power.py#L1375)

At the point of raising k is nan. That nan comes from
[https://github.com/sympy/sympy/blob/d2fcf9ecdfef464b26f0e118018a7817059d22a2/sympy/core/power.py#L1358](https://github.com/sympy/sympy/blob/d2fcf9ecdfef464b26f0e118018a7817059d22a2/sympy/core/power.py#L1358)
where b and prefactor are:
```
(Pdb) p prefactor
-oo
(Pdb) p b
-oo + O(_x**3)
```
This comes from `b_orig._eval_nseries` where b_orig is:
```
(Pdb) p b_orig
Integral(1/(_x + x), (x, 0, 1))
(Pdb) p srepr(b_orig)
"Integral(Pow(Add(Dummy('x', positive=True, finite=True, dummy_index=5112205), Symbol('x')), Integer(-1)), Tuple(Symbol('x'), Integer(0), Integer(1)))"
```

Digging into that call we end up here:
[https://github.com/sympy/sympy/blob/d2fcf9ecdfef464b26f0e118018a7817059d22a2/sympy/integrals/integrals.py#L1094](https://github.com/sympy/sympy/blob/d2fcf9ecdfef464b26f0e118018a7817059d22a2/sympy/integrals/integrals.py#L1094)

From the debugger:
```
1089 	                symb = l[0]
1090 	                break
1091 	        terms, order = expr.function.nseries(
1092 	            x=symb, n=n, logx=logx).as_coeff_add(Order)
1093 	        order = [o.subs(symb, x) for o in order]
1094 ->	        return integrate(terms, *expr.limits) + Add(*order)*x
1095 	
1096 	    def _eval_as_leading_term(self, x):
1097 	        series_gen = self.args[0].lseries(x)
1098 	        for leading_term in series_gen:
1099 	            if leading_term != 0:
(Pdb) p expr
Integral(1/(_x + _0), (_0, 0, 1))
(Pdb) p terms
-_x/_0**2 + 1/_0
(Pdb) p integrate(terms, *expr.limits)
-oo
(Pdb) p expr.limits
((_0, 0, 1),)
```

Those terms are the series expansion of the integrand.

Going back to your first example what has happened is
```julia
In [1]: x = Symbol('x')                                                                                                                                       

In [2]: a = Symbol('a')                                                                                                                                       

In [3]: expr = 1 / (x + a)                                                                                                                                    

In [4]: expr.series(a, n=2)                                                                                                                                   
Out[4]: 
1   a     ⎛ 2⎞
─ - ── + O⎝a ⎠
x    2        
    x         

In [5]: integrate(1/x - a/x**2, (x, 0, 1))                                                                                                                    
Out[5]: a - ∞⋅sign(a)
```
So the problem is that the series expansion of the integrand leads to non-convergent integrals.

If we do the integral first and expansion after then we get:
```julia
In [25]: expr                                                                                                                                                 
Out[25]: 
  1  
─────
a + x

In [26]: integrate(expr, (x, 0, 1))                                                                                                                           
Out[26]: -log(a) + log(a + 1)

In [27]: integrate(expr, (x, 0, 1)).series(a)                                                                                                                 
Out[27]: 
               2    3    4    5        
              a    a    a    a     ⎛ 6⎞
-log(a) + a - ── + ── - ── + ── + O⎝a ⎠
              2    3    4    5  
```
The result has `log(a)` so this hasn't worked either but I think this is to be expected: you are trying to do a series expansion around a singular point (a=0).

**Comment by smheidrich** [comment]
Well, that's embarrassing :) Thank you very much for putting so much work into this, I guess I'll close this then.

**Comment by oscarbenjamin** [comment]
I'm reopening this because I think there is possibly something to fix. Ideally you would get a ValueError plus a helpful message here rather than NotImplementedError.

Maybe we should check for the infinity here:
[https://github.com/sympy/sympy/blob/d2fcf9ecdfef464b26f0e118018a7817059d22a2/sympy/integrals/integrals.py#L1094](https://github.com/sympy/sympy/blob/d2fcf9ecdfef464b26f0e118018a7817059d22a2/sympy/integrals/integrals.py#L1094)
or here:
[https://github.com/sympy/sympy/blob/d2fcf9ecdfef464b26f0e118018a7817059d22a2/sympy/core/power.py#L1354](https://github.com/sympy/sympy/blob/d2fcf9ecdfef464b26f0e118018a7817059d22a2/sympy/core/power.py#L1354)

**Comment by asmeurer** [comment]
The NotImplementedError could also use a message describing exactly what isn't implemented.

**Comment by sachin-4099** [comment]
> The NotImplementedError could also use a message describing exactly what isn't implemented.

Probably something like "Proper series expansions do not exist at singular points."
