### ISSUE TITLE
Solving Piecwise Functions with solve returns AttributeError

### ISSUE THREAD

**Issue by sharma-kunal** [sympy/sympy#16191]
Solving a piecewise function for `x` using `solve` returns `AttributeError`

```
>>> solve([Piecewise((Eq(x**2-1, 0), x > 0), (Eq(x, -1), x < 0))], [x])
Traceback (most recent call last):
  File "/home/kunal/github/sympy/app.py", line 60, in <module>
    print(solve([Piecewise((Eq(x**2-1, 0), x > 0), (Eq(x, -1), x < 0))], [x]))
  File "/home/kunal/github/sympy/sympy/solvers/solvers.py", line 1167, in solve
    solution = _solve_system(f, symbols, **flags)
  File "/home/kunal/github/sympy/sympy/solvers/solvers.py", line 1950, in _solve_system
    result = [r for r in result
  File "/home/kunal/github/sympy/sympy/solvers/solvers.py", line 1951, in <listcomp>
    if not any(checksol(e, r, **flags) is False for e in exprs)]
  File "/home/kunal/github/sympy/sympy/solvers/solvers.py", line 1951, in <genexpr>
    if not any(checksol(e, r, **flags) is False for e in exprs)]
  File "/home/kunal/github/sympy/sympy/solvers/solvers.py", line 290, in checksol
    if not val.is_constant(*list(sol.keys()), simplify=not minimal):
AttributeError: 'BooleanTrue' object has no attribute 'is_constant'
```

**Comment by oscarbenjamin** [comment]
You don't want to use Eqs as the expressions in a piecewise. The piecewise is an expression that should go inside an Eq:
```julia
In [5]: solve([Eq(Piecewise((x**2-1, x > 0), (x+1, x < 0)), 0)], [x])                                                                                         
Out[5]: [(-1,), (1,)]
```

**Comment by jmig5776** [comment]
I think this issue should be closed now.
