### ISSUE TITLE
Recreate random travis test failure

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16200]
In #16190 there is a test failure from a test that uses randomised values. I have tried to reproduce it with:
```
$ bin/test --seed=85383597 sympy/simplify/tests/test_hyperexpand.py -k test_partial_simp
```
and:
```
$ bin/test --seed=85383597 sympy/simplify/tests/test_hyperexpand.py
```
but neither shows the failure. It looks as if I need to run the entire 3/4 split to see this. I took a look at test_travis.sh but it doesn't seem to have the option to pass in a random seed.

The test header is:
```
Testing SYMPY, split 3/4
============================= test process starts ==============================
executable:         /home/travis/virtualenv/python3.6.7/bin/python  (3.6.7-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              None
random seed:        85383597
hash randomization: on (PYTHONHASHSEED=4043919829)
split:              3/4
```
and the failure is:
```
__________ sympy/simplify/tests/test_hyperexpand.py:test_partial_simp __________
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/utilities/runtests.py", line 1306, in _timeout
    function()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/simplify/tests/test_hyperexpand.py", line 637, in test_partial_simp
    hyperexpand(hyper([3], [1, d, e], z)), hyper([3], [1, d, e], z), z)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/simplify/hyperexpand.py", line 2491, in hyperexpand
    return f.replace(hyper, do_replace).replace(meijerg, do_meijer)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/core/basic.py", line 1490, in replace
    rv = bottom_up(self, rec_replace, atoms=True)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/simplify/simplify.py", line 1087, in bottom_up
    rv = F(rv)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/core/basic.py", line 1475, in rec_replace
    new = _value(expr, result)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/core/basic.py", line 1418, in <lambda>
    _value = lambda expr, result: value(*expr.args)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/simplify/hyperexpand.py", line 2480, in do_replace
    r = _hyperexpand(Hyper_Function(ap, bq), z, rewrite=rewrite)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/simplify/hyperexpand.py", line 2056, in _hyperexpand
    r = carryout_plan(formula, ops) + p
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/simplify/hyperexpand.py", line 1977, in carryout_plan
    make_derivative_operator(f.M.subs(f.z, z0), z0))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/simplify/hyperexpand.py", line 1507, in apply_operators
    res = o.apply(res, op)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/simplify/hyperexpand.py", line 986, in apply
    diffs.append(op(diffs[-1]))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/simplify/hyperexpand.py", line 1495, in doit
    r = r.applyfunc(make_simp(z))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/matrices/common.py", line 1553, in applyfunc
    return self._eval_applyfunc(f)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/matrices/common.py", line 1493, in _eval_applyfunc
    out = self._new(self.rows, self.cols, [f(x) for x in self])
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/matrices/common.py", line 1493, in <listcomp>
    out = self._new(self.rows, self.cols, [f(x) for x in self])
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/simplify/hyperexpand.py", line 467, in simp
    c, numer, denom = poly(numer, z).cancel(poly(denom, z))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/polys/polytools.py", line 3689, in cancel
    result = F.cancel(G, include=include)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/polys/polyclasses.py", line 697, in cancel
    cF, cG, F, G = dmp_cancel(F, G, lev, dom, include=False)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/polys/euclidtools.py", line 1869, in dmp_cancel
    _, p, q = dmp_inner_gcd(f, g, u, K)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/polys/euclidtools.py", line 1583, in dmp_inner_gcd
    return dup_inner_gcd(f, g, K)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/polys/euclidtools.py", line 1515, in dup_inner_gcd
    return dup_ff_prs_gcd(f, g, K)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/polys/euclidtools.py", line 1033, in dup_ff_prs_gcd
    cff = dup_quo(f, h, K)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/polys/densearith.py", line 1574, in dup_quo
    return dup_div(f, g, K)[0]
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/polys/densearith.py", line 1530, in dup_div
    return dup_ff_div(f, g, K)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/polys/densearith.py", line 1453, in dup_ff_div
    raise PolynomialDivisionFailed(f, g, K)
sympy.polys.polyerrors.PolynomialDivisionFailed: couldn't reduce degree in a polynomial division algorithm when dividing [EX(625), EX(0)] by [EX(-(-75 + 308*I)*(75 + 308*I)/100489)]. This can happen when it's not possible to detect zero in the coefficient domain. The domain of computation is EX. You may want to use a different simplification algorithm. Note that in general it's not possible to guarantee to detect zero in this domain.
```

I realise that in this example I should be able to reproduce this from the error message but in other cases the message is not so informative so:
1. It should be easily possible to locally reproduce a travis job.
2. From that error message how do I reproduce this particular failure?

**Comment by jksuom** [comment]
This error appears every now and then in computations with polynomials having floating point coefficients. The computations are based on Euclidean division identity, `f = q*g + r`, where `q, r = f.div(g)`. This identity is only approximately valid with inexact coefficients, and the cumulating error will occasionally lead to results that the algorithm can recognize as inconsistent.

I think that the only way to avoid those errors is to use exact coefficient.
