### ISSUE TITLE
Integrals with abs much slower recently

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#16217]
The following test was added in #15710

https://github.com/sympy/sympy/blob/8fc3b3a96b9f982ed6dc8f626129abee36bcda95/sympy/integrals/tests/test_integrals.py#L1480-L1487

In #16216 I marked it as slow as it took at least 100 seconds to run the test depending on Python version.

When I revisited the run times of tests in #16010 it was not close to being that slow as I marked everything taking more than 10 seconds as slow.

Hence, something merged in the last two weeks has severely slowed this down.

**Comment by oscargus** [comment]
It seems to be caused by #16185

**Comment by smichr** [comment]
Hopefully it is the automatic [rewriting as sign](https://github.com/sympy/sympy/pull/16185/files#diff-12f1481a8b98f5fa6ae6a07a5e8a3ab4R583) which takes `x/Abs(x) -> sign(x)`. I would start by reverting that line. If it is, then we either: 
1. accept that this rewriting is valuable and accept the slower times; 
1. find a smarter way to know if the rewrite is necessary (e.g. expand an only rewrite ratios that have foo in numerator when abs(foo) is in the denominator; 
1. revert the change and force the user to rewrite in terms of sign

**Comment by oscargus** [comment]
It times out every now and then for the coverage tests. However, it may give some idea to what happens:

```
___________ sympy/integrals/tests/test_integrals.py:test_issue_4311 ____________
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/utilities/runtests.py", line 1306, in _timeout
    function()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/tests/test_integrals.py", line 1482, in test_issue_4311
    assert integrate(x*abs(9-x**2), x) == Integral(x*abs(9-x**2), x)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/integrals.py", line 1477, in integrate
    return integral.doit(**doit_flags)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/integrals.py", line 541, in doit
    function, xab[0], **eval_kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/integrals.py", line 998, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/heurisch.py", line 132, in heurisch_wrapper
    unnecessary_permutations)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/heurisch.py", line 719, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/heurisch.py", line 719, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/heurisch.py", line 719, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/heurisch.py", line 705, in heurisch
    solution = _integrate()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/heurisch.py", line 681, in _integrate
    find_non_syms(raw_numer)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/heurisch.py", line 674, in find_non_syms
    list(map(find_non_syms, expr.args))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/heurisch.py", line 674, in find_non_syms
    list(map(find_non_syms, expr.args))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/heurisch.py", line 674, in find_non_syms
    list(map(find_non_syms, expr.args))
  [Previous line repeated 2 more times]
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/integrals/heurisch.py", line 671, in find_non_syms
    elif not expr.has(*syms):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/core/basic.py", line 1254, in has
    return any(self._has(pattern) for pattern in patterns)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/core/basic.py", line 1254, in <genexpr>
    return any(self._has(pattern) for pattern in patterns)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/core/basic.py", line 1271, in _has
    return any(match(arg) for arg in preorder_traversal(self))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/core/basic.py", line 1271, in <genexpr>
    return any(match(arg) for arg in preorder_traversal(self))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/core/basic.py", line 1277, in <lambda>
    return lambda other: self == other
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/core/basic.py", line 341, in __eq__
    return self._hashable_content() == other._hashable_content()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/core/symbol.py", line 359, in _hashable_content
    return Symbol._hashable_content(self) + (self.dummy_index,)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/core/symbol.py", line 252, in _hashable_content
    return (self.name,) + tuple(sorted(self.assumptions0.items()))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/core/symbol.py", line 262, in assumptions0
    in self._assumptions.items() if value is not None)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/core/symbol.py", line 262, in <genexpr>
    in self._assumptions.items() if value is not None)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sympy-1.4.dev0-py3.6.egg/sympy/utilities/runtests.py", line 1301, in callback
    raise TimeOutError("Timed out after %d seconds" % timeout)
sympy.utilities.runtests.TimeOutError: Timed out after 595 seconds
```

**Comment by oscargus** [comment]
It is late here so I may be to tired, but shouldn't it be possible to rewrite Abs(x) as x*sign(x) instead of x/sign(x)?

That makes things much faster, but not sure if it breaks something else...

**Comment by smichr** [comment]
> shouldn't it be possible

In fact, preferable since otherwise the ratio creates a singularity when x = 0

**Comment by jksuom** [comment]
I don't think that any function involving `Abs` or `sign` can be handled by `heurisch`. Those should probably be rejected in the beginning. Currently, `heurisch` makes a few attempts (3, by default) before giving up. (That is where the time is spent.) I also suspect that `Piecewise` functions should be integrated "piece by piece" if at all.

**Comment by oscargus** [comment]
@smichr apparently it breaks for imaginary numbers though, see #16219 so while it seems like a good idea, not really (although it should be a good idea if the expression is real).

@jksuom that is another aspect I was thinking about. So far I have not been able to `integrate` any function including Abs (although clearly, I have only tested a few, but since `Abs(x)` doesn't work it seems like, well, not many others will), so just giving up earlier would be a decent solution.

**Comment by supreet11agrawal** [comment]
Maybe the failures in Travis build are related to change in `.travis.yml` file. Looking back the pull requests of last 2-3 weeks, these are some of the PRs which might be looked into.
* #16154 [-q flag in .travis.yml for showing only error log during compilation] (By me actually)
* #16153 [Revived: Travis Code Coverage]
* #16130 [Remove code quality test from doctests matrix] (I don't think this has something to do with the issue)
* #16023 [Use a 2-stage split for Travis tests]
* #15998 [Remove Azure Pipelines] (I don't think this has something to do with the issue)
* #15997 [Reduce the Travis test splits to 2 ways]

I am not sure but maybe we should start by looking into these

**Comment by oscargus** [comment]
Yes and no. The newly introduced coverage makes the tests slower in general which is why the tests with coverage is split into four rather than two.

However, the particular test has gone from < 10 seconds to about 100 seconds (10 seconds is the limit for "slow" tests, so it can have been anything < 10 seconds before). With coverage this sometimes goes to beyond 600 seconds. In #16216 it is marked as slow, so once that is merged, there will at least not be this type of test failures. (The test is still much slower, which is a problem in itself, but it will not cause other problems.)
