### ISSUE TITLE
Region for the Fourier Transform existance

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#16242]
This is an example problem, derived from a fourier transform problem 
(Where I manually reduced a unit step function multiplied)

<img src="https://user-images.githubusercontent.com/34944973/54192380-2a612380-44fb-11e9-9e63-4c7aa96ba39a.png" width="384px">

When I evaluate this integral, I get the following conditional expression

<img src="https://user-images.githubusercontent.com/34944973/54192583-ac514c80-44fb-11e9-9637-170b71d81582.png" width="384px">

However, in my opinion, the condition should be `im(w) < 1`, instead of `abs(arg(w) + pi/2) <= pi/2`, to make `exp(-t * (1 + I*w))` to converge on `t -> oo`.
Because when rewrited as `1 + I*w` -> `1 + I * (re(w) + I*im(w))` -> `1 - im(w) + I*re(w)`,
when the real part `1 - im(w)` is larger than zero, the exponential would approach zero, regardless of the imaginary part.

From the mathematica, it gives the result 

<img src="https://user-images.githubusercontent.com/34944973/54193047-9ee89200-44fc-11e9-83e4-021656f8cd4c.png" width="384px">

And I can quickly verify that both conditional are different, from this visual
<img src="https://user-images.githubusercontent.com/34944973/54193383-4796f180-44fd-11e9-9eda-0be08f314373.png" width="384px">

I can `1 + I/2`, which only belongs to the above region, and as you can see, the formula extends to the point.

<img src="https://user-images.githubusercontent.com/34944973/54193455-77de9000-44fd-11e9-8ba4-127e065e434d.png" width="384px">

Though the integral is not really 'wrong', it is also not very precise in this claim is right.

**Comment by jksuom** [comment]
`meijerint` typically produces conditions like `abs(arg(w) + pi/2) <= pi/2`, which is easier to understand in the form `im(w) < 0`. It only gives sufficient conditions. It cannot usually produce necessary conditions like `im(w) < 1` even if that is valid in this case.

**Comment by asmeurer** [comment]
The problem it seems is that it only knows how to give convergence conditions in terms of `arg(w)`. But `im(w) < 1` should be in terms of `arg(w - I)`. To see this, note that `arg(w) + pi/2` taks the complex plane and rotates it 90º clockwise, so that `abs(arg(w) + pi/2) <= pi/2`, which is equivalent to `-pi/2 <= arg(w) + pi/2 <= pi/2`, is the same as `-pi <= arg(w) <= 0`, i.e., `im(w) <= 0`. We want to do the same but around the point `I` instead of `0`, so that we get the same thing in terms of `arg(w - I)`, which shifts the complex plan up by one unit before doing the rotating. 

If we subtract and add `I` from `w`, we find that the term that cancels is exactly `-t`, i.e., we can get this just by absorbing the original integrand into one exponential and factoring out `I*t`:

```
>>> pprint(integrate(exp(-I*(w - I)*t), (t, 0, oo)))
⎧       -ⅈ               │             π│   π
⎪      ─────         for │arg(w - ⅈ) + ─│ < ─
⎪      w - ⅈ             │             2│   2
⎪
⎪∞
⎨⌠
⎪⎮  -ⅈ⋅t⋅(w - ⅈ)
⎪⎮ ℯ             dt         otherwise
⎪⌡
⎪0
⎩
```

The convergence condition changed to strict equal here, which suggest that the algorithm somehow "knows" that it is more tight. 

So this maybe solvable by adding some logic somewhere that tries to find shifted versions of parameters to get tighter convergence conditions (this is different from the current "shift" logic in meijerg which is about shifting the integration variable).

(as an aside: there's an oddity here, which is that the two rational functions are equivalent to each other but neither changes under simplification:

```
>>> simplify(-I/(w - I))
-I/(w - I)
>>> simplify(1/(I*w + 1))
1/(I*w + 1)
>>> simplify(-I/(w - I) - 1/(I*w + 1))
0
```
)

Also, if you try shifting too far you get an error:

```py
>>> integrate(exp(t)*exp(-I*(w - 2*I)*t), (t, 0, oo))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/integrals/integrals.py", line 1570, in integrate
    return integral.doit(**doit_flags)
  File "./sympy/integrals/integrals.py", line 580, in doit
    ret = try_meijerg(function, xab)
  File "./sympy/integrals/integrals.py", line 564, in try_meijerg
    function, (x, a, b)), True))
  File "./sympy/functions/elementary/piecewise.py", line 136, in __new__
    r = cls.eval(*newargs)
  File "./sympy/functions/elementary/piecewise.py", line 187, in eval
    c = c.as_set().as_relational(x)
  File "./sympy/logic/boolalg.py", line 169, in as_set
    return self.subs(reps)._eval_as_set()
  File "./sympy/logic/boolalg.py", line 784, in _eval_as_set
    return Intersection(*[arg.as_set() for arg in self.args])
  File "./sympy/logic/boolalg.py", line 784, in <listcomp>
    return Intersection(*[arg.as_set() for arg in self.args])
  File "./sympy/logic/boolalg.py", line 169, in as_set
    return self.subs(reps)._eval_as_set()
  File "./sympy/core/relational.py", line 408, in _eval_as_set
    xset = solve_univariate_inequality(self, x, relational=False)
  File "./sympy/solvers/inequalities.py", line 522, in solve_univariate_inequality
    solns = solvify(e, gen, domain)
  File "./sympy/solvers/solveset.py", line 2434, in solvify
    solution_set = solveset(f, symbol, domain)
  File "./sympy/solvers/solveset.py", line 2304, in solveset
    rv = solveset(f.xreplace({symbol: x}), x, domain)
  File "./sympy/solvers/solveset.py", line 2328, in solveset
    return _solveset(f, symbol, domain, _check=True)
  File "./sympy/solvers/solveset.py", line 1108, in _solveset
    result += solver(equation, symbol)
  File "./sympy/solvers/solveset.py", line 1015, in <lambda>
    solver = lambda f, x, domain=domain: _solveset(f, x, domain)
  File "./sympy/solvers/solveset.py", line 1038, in _solveset
    result = solveset_real(a > 0, symbol)
  File "./sympy/core/decorators.py", line 266, in _func
    return func(self, other)
  File "./sympy/core/expr.py", line 372, in __gt__
    return StrictGreaterThan(self, other)
  File "./sympy/core/relational.py", line 706, in __new__
    raise TypeError("Invalid comparison of non-real %s" % me)
TypeError: Invalid comparison of non-real _R - 2*I
```

which is better than a wrong result, but is clearly a bug that should be fixed. It should at least give an unevaluated integral if it can't figure it out.

**Comment by asmeurer** [comment]
> However, in my opinion, the condition should be im(w) < 1, instead of abs(arg(w) + pi/2) <= pi/2, to make exp(-t * (1 + I*w)) to converge on t -> oo.
Because when rewrited as 1 + I*w -> 1 + I * (re(w) + I*im(w)) -> 1 - im(w) + I*re(w),
when the real part 1 - im(w) is larger than zero, the exponential would approach zero, regardless of the imaginary part.

> If we subtract and add I from w, we find that the term that cancels is exactly -t, i.e., we can get this just by absorbing the original integrand into one exponential and factoring out I*t:

I guess this is not a coincidence. The algorithm should try to rewrite the parameters in such a way that the "correct" convergence conditions fall out like this

```py
>>> pprint(integrate(exp(-(1 + I*w)*t), (t, 0, oo)))
⎧       -ⅈ                                     π
⎪      ─────         for │arg(-ⅈ⋅w - 1) + π│ < ─
⎪      w - ⅈ                                   2
⎪
⎪∞
⎨⌠
⎪⎮  t⋅(-ⅈ⋅w - 1)
⎪⎮ ℯ             dt           otherwise
⎪⌡
⎪0
⎩
```

Note that `abs(arg(-I*w - 1) + pi) < pi/2` is the same as `-3*pi/2 < arg(-I*w - 1) < -pi/2` -> `re(-I*w) < 1` -> `im(w) < 1` (we really need better functions to simplify convergence conditions).
