### ISSUE TITLE
isympy broken under Py2 on master

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16254]
```
$ isympy
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/27venv/bin/isympy", line 11, in <module>
    load_entry_point('sympy', 'console_scripts', 'isympy')()
  File "/Users/enojb/current/sympy/sympy/isympy.py", line 338, in main
    from sympy.interactive import init_session
  File "/Users/enojb/current/sympy/sympy/sympy/__init__.py", line 60, in <module>
    from .polys import *
  File "/Users/enojb/current/sympy/sympy/sympy/polys/__init__.py", line 5, in <module>
    from . import polytools
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 18, in <module>
    from sympy.polys.constructor import construct_domain
  File "/Users/enojb/current/sympy/sympy/sympy/polys/constructor.py", line 6, in <module>
    from sympy.polys.domains import ZZ, QQ, EX
  File "/Users/enojb/current/sympy/sympy/sympy/polys/domains/__init__.py", line 9, in <module>
    from . import finitefield
  File "/Users/enojb/current/sympy/sympy/sympy/polys/domains/finitefield.py", line 6, in <module>
    from sympy.polys.domains.groundtypes import SymPyInteger
  File "/Users/enojb/current/sympy/sympy/sympy/polys/domains/groundtypes.py", line 13, in <module>
    from .pythonrational import PythonRational
  File "/Users/enojb/current/sympy/sympy/sympy/polys/domains/pythonrational.py", line 12, in <module>
    from sympy.printing.defaults import DefaultPrinting
  File "/Users/enojb/current/sympy/sympy/sympy/printing/__init__.py", line 41, in <module>
    from .mathematica import mathematica_code
  File "/Users/enojb/current/sympy/sympy/sympy/printing/mathematica.py", line 187
SyntaxError: Non-ASCII character '\xe2' in file /Users/enojb/current/sympy/sympy/sympy/printing/mathematica.py on line 188, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

I think a recent PR has added a non-ascii character to the code.

**Comment by sylee957** [comment]
Okay, this was from my PR #16221
I wonder how the test got passed

**Comment by oscarbenjamin** [comment]
> I wonder how the test got passed

I also wonder how that passed.

I actually get the same error just for import sympy:
```
$ python
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/__init__.py", line 60, in <module>
    from .polys import *
  File "sympy/polys/__init__.py", line 5, in <module>
    from . import polytools
  File "sympy/polys/polytools.py", line 18, in <module>
    from sympy.polys.constructor import construct_domain
  File "sympy/polys/constructor.py", line 6, in <module>
    from sympy.polys.domains import ZZ, QQ, EX
  File "sympy/polys/domains/__init__.py", line 9, in <module>
    from . import finitefield
  File "sympy/polys/domains/finitefield.py", line 6, in <module>
    from sympy.polys.domains.groundtypes import SymPyInteger
  File "sympy/polys/domains/groundtypes.py", line 13, in <module>
    from .pythonrational import PythonRational
  File "sympy/polys/domains/pythonrational.py", line 12, in <module>
    from sympy.printing.defaults import DefaultPrinting
  File "sympy/printing/__init__.py", line 41, in <module>
    from .mathematica import mathematica_code
  File "sympy/printing/mathematica.py", line 187
SyntaxError: Non-ASCII character '\xe2' in file sympy/printing/mathematica.py on line 188, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

That should have shown up in the Python 2.7 tests.
