### ISSUE TITLE
Bug and Unnessesary Relation Complexity

### ISSUE THREAD

**Issue by bhgomes** [sympy/sympy#16260]
_Using `Sympy 1.3`_

I am trying to plot the solutions to the wave equation but keep the initial conditions factored out until the last moment.

Here is the minimal working example:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*- #

from sympy import *
from sympy.plotting import plot3d


def wave_equation(u0, u_prime0, c=1):
    def solution(x, t):
        s = symbols('s')
        ct = c * t
        left, right = x - ct, x + ct
        average_position = (u0(left) + u0(right)) / 2
        average_velocity = 1 / (2 * c) * integrate(u_prime0(s), (s, right, left))
        return average_position + average_velocity
    return solution


def f(s):
    """The initial height of the wave."""
    ### Cannot use comparison #############################################
    # if -2 <= s <= -1 or 1 <= s <= 2:
    #     return 1
    # return 0
    #######################################################################

    ### Cannot use piecewise ##############################################
    # def p(r):
    #     return Piecewise((1, -2 <= r <= -1 or 1 <= r <= 2), (0, True))
    # return p(s)
    #######################################################################

    left = Heaviside(s + 2, 0.5) - Heaviside(s + 1, 0.5)
    right = Heaviside(s - 1, 0.5) - Heaviside(s - 2, 0.5)
    return left + right


def g(s):
    """The initial velocity of the wave."""
    return 0


if __name__ == '__main__':
    x, t = symbols('x t')
    solution = wave_equation(f, g, c=1)
    plot3d((solution(x, t), (x, -10, 10), (t, 0, 3)), xlabel='x', ylabel='t', title='c = 1')
```

Which plots the appropriate thing but prints:

```bash
/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/experimental_lambdify.py:165: UserWarning: The evaluation of the expression is problematic. We are trying a failback method that may still work. Please report this as a bug.
  warnings.warn('The evaluation of the expression is'
```
(yes the error message ends there)

Is there some way of providing a simple comparison-like function as the first implementation of `f` above instead of using `Heaviside`? What about arbitrary indicator functions? Is there a way to provide lazy evaluation? It just seems unnecessarily complicated to do this sort of manipulation. I understand that this would work with comparison (well just with `Piecewise`) if I were to insert the `Piecewise` directly into the solution, but then there is no point in factoring out the code here. 

I appreciate any support here.

**Comment by smichr** [comment]
I'm almost sure this is written about in the gotchas, but such chains have to be spelled out in unevaluated form if the s is symbolic:

```python
Piecewise((1, -2 <= r <= -1 or 1 <= r <= 2), (0, True))
-> Piecewise((1, Or(And(-2 <= r, r <= -1), And(1 <= r, r <= 2))), (0, True))
```

**Comment by bhgomes** [comment]
I left it in that short notation just for illustration but if I replace it with the correct statement,

```Piecewise((1, Or(And(-2 <= r, r <= -1), And(1 <= r, r <= 2))), (0, True))```

it hangs the plotter and if I `^C` then it returns the following traceback:

```bash
^CTraceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/experimental_lambdify.py", line 194, in __call__
    result = complex(self.lambda_func(args))
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/experimental_lambdify.py", line 316, in __call__
    return self.lambda_func(*args, **kwargs)
  File "<string>", line 1, in <lambda>
TypeError: '>=' not supported between instances of 'complex' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./wave.py", line 88, in <module>
    move_sympyplot_to_axes(p2, axes[0, 1])
  File "./wave.py", line 70, in move_sympyplot_to_axes
    backend.process_series()
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 906, in process_series
    collection = self.LineCollection(s.get_segments())
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 515, in get_segments
    sample([self.start, f_start], [self.end, f_end], 0)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 490, in sample
    sample(new_point, q, depth + 1)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 489, in sample
    sample(p, new_point, depth + 1)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 489, in sample
    sample(p, new_point, depth + 1)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 489, in sample
    sample(p, new_point, depth + 1)
  [Previous line repeated 1 more time]
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 490, in sample
    sample(new_point, q, depth + 1)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 479, in sample
    ynew = f(xnew)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/experimental_lambdify.py", line 219, in __call__
    use_python_math=True)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/experimental_lambdify.py", line 242, in experimental_lambdify
    l = Lambdifier(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/plotting/experimental_lambdify.py", line 268, in __init__
    expr = expr.xreplace(dict(zip(args, newargs)))
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1115, in xreplace
    value, _ = self._xreplace(rule)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1129, in _xreplace
    a_xr = a._xreplace(rule)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1129, in _xreplace
    a_xr = a._xreplace(rule)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1136, in _xreplace
    return self.func(*args), True
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/functions/elementary/piecewise.py", line 138, in __new__
    r = cls.eval(*newargs)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/functions/elementary/piecewise.py", line 187, in eval
    c = c.as_set().as_relational(x)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/logic/boolalg.py", line 155, in as_set
    return self.subs(reps)._eval_as_set()
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/logic/boolalg.py", line 600, in _eval_as_set
    return Union(*[arg.as_set() for arg in self.args])
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/logic/boolalg.py", line 600, in <listcomp>
    return Union(*[arg.as_set() for arg in self.args])
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/logic/boolalg.py", line 146, in as_set
    if periodicity(r, x) not in (0, None):
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/calculus/util.py", line 398, in periodicity
    f = simplify(f)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/simplify/simplify.py", line 579, in simplify
    expr = hyperexpand(expr)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/simplify/hyperexpand.py", line 2473, in hyperexpand
    return f.replace(hyper, do_replace).replace(meijerg, do_meijer)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1341, in replace
    value = sympify(value)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/core/sympify.py", line 368, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/sympy/parsing/sympy_parser.py", line 958, in parse_expr
    exec_('from sympy import *', global_dict)
  File "<string>", line 1, in <module>
KeyboardInterrupt
```

**Comment by smichr** [comment]
cf #8616 where the same plotting error occurred

**Comment by oscargus** [comment]
This code works for me in current master:

```
from sympy import *
from sympy.plotting import plot3d


def wave_equation(u0, u_prime0, c=1):
    def solution(x, t):
        s = symbols('s')
        ct = c * t
        left, right = x - ct, x + ct
        average_position = (u0(left) + u0(right)) / 2
        average_velocity = 1 / (2 * c) * integrate(u_prime0(s), (s, right, left))
        return average_position + average_velocity
    return solution


def f(s):
    """The initial height of the wave."""
    ### Cannot use comparison #############################################
    # if -2 <= s <= -1 or 1 <= s <= 2:
    #     return 1
    # return 0
    #######################################################################

    ### Cannot use piecewise ##############################################
    # def p(r):
    #     return Piecewise((1, -2 <= r <= -1 or 1 <= r <= 2), (0, True))
    # return p(s)
    #######################################################################

    return Piecewise((1, Or(And(-2 <= s, s <= -1), And(1 <= s, s <= 2))), (0, True))
    


def g(s):
    """The initial velocity of the wave."""
    return 0


if __name__ == '__main__':
    x, t = symbols('x t')
    solution = wave_equation(f, g, c=1)
    plot3d((solution(x, t), (x, -10, 10), (t, 0, 3)), xlabel='x', ylabel='t', title='c = 1')
```

![image](https://user-images.githubusercontent.com/8114497/63286726-f4e61080-c2b8-11e9-9ebb-3ea858714d91.png)

The warning is still there though. (The reason it is cut of is that it both prints the complete warning message and then does the Python interpreter(?) print the line where the warning was raised.)
