### ISSUE TITLE
dsolve 1st_exact gives incorrect answers

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16282]
These come from 1st_exact:
```
In [1]: dsolve(Eq(f(x).diff(x),(cos(x+f(x))+cos(x-f(x)))),f(x))                                                                                               
Out[1]: 
⎡             ⎛  ⎛        ⅈ⋅x                -ⅈ⋅x              ⅈ⋅x      -ⅈ⋅x⎞⎞               ⎛  ⎛        ⅈ⋅x                -ⅈ⋅x              ⅈ⋅x      -ⅈ⋅x⎞
⎢             ⎜  ⎜   2⋅ⅈ⋅ℯ       2⋅C₁ + 2⋅ⅈ⋅ℯ          C₁ + ⅈ⋅ℯ    + ⅈ⋅ℯ    ⎟⎟               ⎜  ⎜   2⋅ⅈ⋅ℯ       2⋅C₁ + 2⋅ⅈ⋅ℯ          C₁ + ⅈ⋅ℯ    + ⅈ⋅ℯ    ⎟
⎢             ⎜ⅈ⋅⎝- ℯ         - ℯ                 + 2⋅ℯ                     ⎠⎟               ⎜ⅈ⋅⎝- ℯ         - ℯ                 - 2⋅ℯ                     ⎠
⎢f(x) = -ⅈ⋅log⎜──────────────────────────────────────────────────────────────⎟, f(x) = -ⅈ⋅log⎜──────────────────────────────────────────────────────────────
⎢             ⎜                      ⅈ⋅x                -ⅈ⋅x                 ⎟               ⎜                      ⅈ⋅x                -ⅈ⋅x                 
⎢             ⎜                 2⋅ⅈ⋅ℯ       2⋅C₁ + 2⋅ⅈ⋅ℯ                     ⎟               ⎜                 2⋅ⅈ⋅ℯ       2⋅C₁ + 2⋅ⅈ⋅ℯ                     
⎣             ⎝                ℯ         - ℯ                                 ⎠               ⎝                ℯ         - ℯ                                 

⎞⎤
⎟⎥
⎟⎥
⎟⎥
⎟⎥
⎟⎥
⎠⎦

In [2]: dsolve(Eq(f(x).diff(x),exp(x+f(x))*(cos(x+f(x))+cos(x-f(x)))),f(x))                                                                                   
Out[2]: 
⎡                       ⎛  -ⅈ⋅x⎞               ⎛  ⅈ⋅x⎞⎤
⎣f(x) = π, f(x) = -ⅈ⋅log⎝-ℯ    ⎠, f(x) = -ⅈ⋅log⎝-ℯ   ⎠⎦
```
In the first case the new solution you showed with this patch seems better. In the second the current behaviour gives an explicit form although I don't think it is correct.

Apparently the current solutions are coming from 1st_exact:
```
In [11]: classify_ode(eq)                                                                                                                                     
Out[11]: ('1st_exact', '1st_power_series', 'lie_group', '1st_exact_Integral')
```

_Originally posted by @oscarbenjamin in https://github.com/sympy/sympy/pull/16279#issuecomment-473595093_

**Comment by XtremeGood** [comment]
Even the first solution is also too badly displayed and rather f'(x) = 2 *cos(x) *cos(f(x)) which is equivalent to your equation should be converted to first and then solved. 
```
>>> f = Function("f")
>>> simplify(cos(x+f(x))+cos(x-f(x)))
2*cos(x)*cos(f(x))
>>> 
```
but running dsolve on that code gives me 
```
dsolve(Eq(f.diff(x),simplify(cos(x+f(x))+cos(x-f(x)))))
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    dsolve(Eq(f.diff(x),simplify(cos(x+f(x))+cos(x-f(x)))))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\solvers\ode.py", line 630, in dsolve
    x0=x0, n=n, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\solvers\deutils.py", line 175, in _desolve
    eq, func = _preprocess(eq, func)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\sympy\solvers\deutils.py", line 77, in _preprocess
    'automatically detected for %s.' % expr)
ValueError: The function cannot be automatically detected for -2*cos(x)*cos(f(x)) + 1.


```

**Comment by XtremeGood** [comment]
Once the equation is solved implementation of Lagrange inversion method can be used.

**Comment by oscarbenjamin** [comment]
It should be `f(x).diff(x)` not `f.diff(x)`. With that I get:
```
In [2]: dsolve(Eq(f(x).diff(x),simplify(cos(x+f(x))+cos(x-f(x)))))                                                                                            
Out[2]: 
⎡               ⎛         1         ⎞             ⎛         1         ⎞⎤
⎢f(x) = π - asin⎜───────────────────⎟, f(x) = asin⎜───────────────────⎟⎥
⎣               ⎝tanh(C₁ + 2⋅sin(x))⎠             ⎝tanh(C₁ + 2⋅sin(x))⎠⎦
```
which is the output from dsolve in #16279 without needint to call simplify first.

**Comment by XtremeGood** [comment]
Sorry, my bad again I made this stupid mistake.
But by integrating it manually I 'm getting arcsec(cos(2|cos(x)|)).Then how two solutions of a linear differential equation?

**Comment by oscarbenjamin** [comment]
It's non-linear.

**Comment by XtremeGood** [comment]
Yes, you are right.

**Comment by XtremeGood** [comment]
But any of the solutions doesn't match my solutions.

**Comment by naveensaigit** [comment]
`dsolve` is now able to solve this with the hint "factorable".
``` python
In [1]: eq=Eq(f(x).diff(x),exp(x+f(x))*(cos(x+f(x))+cos(x-f(x))))

In [2]: dsolve(eq)
Out[2]: 
f(x)
 ⌠
 ⎮     -y
 ⎮    ℯ                x           x
 ⎮   ────── dy = C₁ + ℯ ⋅sin(x) + ℯ ⋅cos(x)
 ⎮   cos(y)
 ⌡


In [3]: checkodesol(eq, _)
Out[3]: (True, 0)
```
I think the issue can be closed now.

**Comment by oscarbenjamin** [comment]
We need to confirm that `1st_exact` is not giving incorrect results any more.

**Comment by naveensaigit** [comment]
Looks like `1st_exact` is still giving the wrong answer. It takes a long time as well. Is the equation actually an exact differential equation? It doesn't seem to satisfy the `dM/dx = dN/dy` property.
