### ISSUE TITLE
Code quality test failing on python 2.7

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#16287]
```
$ bin/test quality
================================================= test process starts ==================================================
executable:         /home/sylee957/anaconda3/envs/sympy_dev_27/bin/python  (2.7.16-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python
numpy:              None
random seed:        32368406
hash randomization: on (PYTHONHASHSEED=3754087664)

sympy/utilities/tests/test_code_quality.py[6] F.....                                                              [FAIL]

________________________________________________________________________________________________________________________
________________________________ sympy/utilities/tests/test_code_quality.py:test_files _________________________________
Traceback (most recent call last):
  File "/mnt/c/users/sylee/documents/github/sympy/sympy/utilities/tests/test_code_quality.py", line 240, in test_files
    check_files(top_level_files, test)
  File "/mnt/c/users/sylee/documents/github/sympy/sympy/utilities/tests/test_code_quality.py", line 125, in check_files
    file_check(fname)
  File "/mnt/c/users/sylee/documents/github/sympy/sympy/utilities/tests/test_code_quality.py", line 149, in test
    test_this_file(fname, test_file)
  File "/mnt/c/users/sylee/documents/github/sympy/sympy/utilities/tests/test_code_quality.py", line 174, in test_this_file
    assert False, message_carriage % (fname, idx + 1)
AssertionError: File contains carriage returns at end of line: /mnt/c/users/sylee/documents/github/sympy/isympy.py, line 1

================================= tests finished: 5 passed, 1 failed, in 0.02 seconds ==================================
DO *NOT* COMMIT!
```

I have found this error. Though I could not reproduce on Travis.
I think it may be OS specific, since the git automatically handles line endings.
Do anyone else with Windows have same thing happening?

**Comment by abhinavsagar** [comment]
Yeah I just tested on my win 10 64. However I am using pip . Does it matter though?

**Comment by sylee957** [comment]
@abhinavsagar 
Well, it should not be dependent on python installations.
If you have any log, please paste here.
