### ISSUE TITLE
dsolve constantsimp should recognised cse style simplification

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16400]
This example ODE is solved by dsolve but the constants can be simplified:
```julia
In [2]: eqn = Eq(x*Derivative(f(x), x)**2 + Derivative(f(x), x, 2))                                                                            

In [3]: dsolve(eqn, f(x))                                                                                                                      
Out[3]: 
                _____    ⎛         _____    ⎞       _____    ⎛       _____    ⎞
               ╱ -1      ⎜        ╱ -1      ⎟      ╱ -1      ⎜      ╱ -1      ⎟
f(x) = C₁ -   ╱  ─── ⋅log⎜- C₂⋅  ╱  ───  + x⎟ +   ╱  ─── ⋅log⎜C₂⋅  ╱  ───  + x⎟
            ╲╱    C₂     ⎝     ╲╱    C₂     ⎠   ╲╱    C₂     ⎝   ╲╱    C₂     ⎠
```
The repeated `sqrt(-1/C2)` is a clear sign that simplification is possible but `constantsimp` doesn't check for it.

A nicer solution is:
```julia
In [8]: dsolve(eqn, f(x)).subs(Symbol('C2'), -1/Symbol('C3', positive=True)**2)                                                                
Out[8]: 
                  ⎛    1 ⎞         ⎛    1 ⎞
f(x) = C₁ + C₃⋅log⎜x - ──⎟ - C₃⋅log⎜x + ──⎟
                  ⎝    C₃⎠         ⎝    C₃⎠
```

**Comment by arooshiverma** [comment]
Hey @oscarbenjamin, I get this error. Can you help me out?
```
In [2]: eqn = Eq(x*Derivative(f(x), x)**2 + Derivative(f(x), x, 2))                                                                            

In [3]: dsolve(eqn, f(x))                                                                                                                      
Out[3]:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\aroos\Anaconda2\lib\site-packages\sympy\solvers\ode.py", line 630, in dsolve
    x0=x0, n=n, **kwargs)
  File "C:\Users\aroos\Anaconda2\lib\site-packages\sympy\solvers\deutils.py", line 235, in _desolve
    raise NotImplementedError(dummy + "solve" + ": Cannot solve " + str(eq))
NotImplementedError: solve: Cannot solve x*Derivative(f(x), x)**2 + Derivative(f(x), (x, 2))
```

**Comment by oscarbenjamin** [comment]
Are you working with SymPy master?

**Comment by arooshiverma** [comment]
Yes

**Comment by oscarbenjamin** [comment]
I just checked this again on SymPy master and I get
```julia
$ isympy
IPython console for SymPy 1.5.dev (Python 3.7.1-64-bit) (ground types: gmpy)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/dev


In [1]: eqn = Eq(x*Derivative(f(x), x)**2 + Derivative(f(x), x, 2))                                                                            

In [2]: dsolve(eqn, f(x))                                                                                                                      
Out[2]: 
                _____    ⎛         _____    ⎞       _____    ⎛       _____    ⎞
               ╱ -1      ⎜        ╱ -1      ⎟      ╱ -1      ⎜      ╱ -1      ⎟
f(x) = C₁ -   ╱  ─── ⋅log⎜- C₂⋅  ╱  ───  + x⎟ +   ╱  ─── ⋅log⎜C₂⋅  ╱  ───  + x⎟
            ╲╱    C₂     ⎝     ╲╱    C₂     ⎠   ╲╱    C₂     ⎝   ╲╱    C₂     ⎠
```

Your traceback is coming from site-packages. Are you sure you're using latest SymPy master?
