### ISSUE TITLE
Test failure in 1.4 branch

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#16453]
This is from running the tests in the release Docker container.

```
__________________________________________ sympy/functions/elementary/tests/test_miscellaneous.py:test_issue_11463 ___________________________________________
Traceback (most recent call last):
  File "/root/sympy/sympy/functions/elementary/tests/test_miscellaneous.py", line 353, in test_issue_11463
    assert f(numpy.array(-1)) < -1
  File "/opt/conda/envs/sympy-tests/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/root/sympy/sympy/utilities/pytest.py", line 196, in warns
    raise Failed(msg)
sympy.utilities.pytest.Failed: Failed: DID NOT WARN. No warnings of type <class 'RuntimeWarning'> was emitted. The list of emitted warnings is: [].

```

Here is the test header

```
executable:         /opt/conda/envs/sympy-tests/bin/python  (3.6.7-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 2.0.8
numpy:              1.16.2
random seed:        82542435
hash randomization: on (PYTHONHASHSEED=2983640490)
```

I'm guessing either the warning in question was removed in numpy 1.16, or some earlier test triggered the warning, making it not be emitted anymore.

**Comment by oscarbenjamin** [comment]
We could change this to ignore_warnings

**Comment by oscarbenjamin** [comment]
I've opened #16455 to fix this
