### ISSUE TITLE
abs(O(x**2)): conjugate has no _eval_as_leading_term routine

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16507]
I get an error from `abs(O(x**2))`:
```python
from sympy import *
x = Symbol('x')
print(abs(O(x**2)))
```
Leads to:
```
Traceback (most recent call last):
  File "g.py", line 3, in <module>
    print(abs(O(x**2)))
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 126, in __abs__
    return Abs(self)
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 458, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 277, in __new__
    evaluated = cls.eval(*args)
  File "/Users/enojb/current/sympy/sympy/sympy/functions/elementary/complexes.py", line 514, in eval
    conj = signsimp(arg.conjugate(), evaluate=False)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 943, in conjugate
    return c(self)
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 458, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 277, in __new__
    evaluated = cls.eval(*args)
  File "/Users/enojb/current/sympy/sympy/sympy/functions/elementary/complexes.py", line 684, in eval
    obj = arg._eval_conjugate()
  File "/Users/enojb/current/sympy/sympy/sympy/series/order.py", line 459, in _eval_conjugate
    return self.func(expr, *self.args[1:])
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/series/order.py", line 221, in __new__
    expr = expr.as_leading_term(*args)
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 3011, in as_leading_term
    obj = self._eval_as_leading_term(x)
  File "/Users/enojb/current/sympy/sympy/sympy/core/power.py", line 1551, in _eval_as_leading_term
    return self.func(self.base.as_leading_term(x), self.exp)
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 3011, in as_leading_term
    obj = self._eval_as_leading_term(x)
  File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 792, in _eval_as_leading_term
    '%s has no _eval_as_leading_term routine' % self.func)
NotImplementedError: conjugate has no _eval_as_leading_term routine
```

I would have though that `abs(O(x**2))` should give `O(x**2)`.

**Comment by oscarbenjamin** [comment]
This seems to solve my problem:
```diff
diff --git a/sympy/functions/elementary/complexes.py b/sympy/functions/elementary/complexes.py
index 2d07d4beec..95ef5769f2 100644
--- a/sympy/functions/elementary/complexes.py
+++ b/sympy/functions/elementary/complexes.py
@@ -706,6 +706,9 @@ def _eval_transpose(self):
     def _eval_is_algebraic(self):
         return self.args[0].is_algebraic
 
+    def _eval_as_leading_term(self, n):
+        return self.args[0]._eval_as_leading_term(n)
+
 
 class transpose(Function):
     """
```
It gives
```julia
In [1]: abs(O(x**2))                                                                                                                           
Out[1]: 
│ ⎛ 2⎞│
│O⎝x ⎠│
```
I think that's not correct though... what should the answer be?

**Comment by jksuom** [comment]
> what should the answer be?

I'm not sure that all functions should have a leading term. It seems that the method was designed for analytic and meromorphic functions.

**Comment by oscarbenjamin** [comment]
I agree that defining `conjugate._eval_as_leading_term` doesn't seem right but what should the solution be. Currently we also have
```
In [10]: abs(O(x))                                                                                                                             
Out[10]: │O(x)│
```

**Comment by jksuom** [comment]
I think that there should be an indication of error, perhaps a ValueError.

**Comment by anutosh491** [comment]
Yes indeed , even I think that there should be a error raised for the same !
