### ISSUE TITLE
conjugate of sqrt of CRootOf raises PolynomialError

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16511]
This example
```python
from sympy import *
x = Symbol('x')
sroot = sqrt(CRootOf(x**4 + x - 1, 2))
pprint(sroot.conjugate())
```
gives this
```
Traceback (most recent call last):
  File "croot_conjugate.py", line 4, in <module>
    pprint(sroot.conjugate())
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 943, in conjugate
    return c(self)
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 458, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 277, in __new__
    evaluated = cls.eval(*args)
  File "/Users/enojb/current/sympy/sympy/sympy/functions/elementary/complexes.py", line 684, in eval
    obj = arg._eval_conjugate()
  File "/Users/enojb/current/sympy/sympy/sympy/core/power.py", line 813, in _eval_conjugate
    expanded = expand_complex(self)
  File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 2776, in expand_complex
    log=False, mul=False, power_exp=False, power_base=False, multinomial=False)
  File "/Users/enojb/current/sympy/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 3191, in expand
    expr, hit = Expr._expand_hint(expr, hint, deep=deep, **hints)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 3124, in _expand_hint
    arg, arghit = Expr._expand_hint(arg, hint, **hints)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 3129, in _expand_hint
    expr = expr.func(*sargs)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/rootoftools.py", line 316, in __new__
    raise PolynomialError("only univariate polynomials are allowed")
sympy.polys.polyerrors.PolynomialError: only univariate polynomials are allowed
```

The error is raised from `ComplexRootOf.__new__(f, x)` with `f` as:
```python
I*(4*re(x)**3*im(x) - 4*re(x)*im(x)**3 + im(x)) + re(x)**4 - 6*re(x)**2*im(x)**2 + re(x) + im(x)**4 - 1
```

That expression comes from
```
Expr._expand_hint(CRootOf(x**4 + x - 1, 2), '_eval_expand_complex')
```

**Comment by arooshiverma** [comment]
> ```
> 
> That expression comes from
> 
> ```
> Expr._expand_hint(CRootOf(x**4 + x - 1, 2), '_eval_expand_complex')
> ```
How does this come?

**Comment by jksuom** [comment]
I think that this issue is related to #7691. It should be possible to compute the conjugate without writing the expression in the form `re(x) + I*im(x)` (where `re(x)` and `im(x)` are considered as two algebraically independent variables by the `polys` module). Instead, the private `_eval_conjugate` of `CRootOf` should be called.

**Comment by arooshiverma** [comment]
But if we call `_eval_conjugate` :
```
def _eval_conjugate(self):
        if self.is_real:
            return self
        expr, i = self.args
        return self.func(expr, i + (1 if self._get_interval().conj else -1))
```


```
>>> sroot.is_real
>>> sroot.args
(CRootOf(x**4 + x - 1, 2), 1/2)
>>> sroot.func(CRootOf(x**4+x-1, (1/2)+(1 if sroot._get_interval().conj else -1))
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Pow' object has no attribute '_get_interval'
```

**Comment by arooshiverma** [comment]
Why can't be something like this used to print the conjugate?
```
>>> x=Symbol('x')
>>> sroot
sqrt(CRootOf(x**4 + x - 1, 2))
>>> complex(sroot)
(0.8097724994169689-0.6384398468214395j)
>>> (complex(sroot)).conjugate()
(0.8097724994169689+0.6384398468214395j)
>>> pprint((complex(sroot)).conjugate())
(0.809772499417+0.638439846821j)

```

**Comment by guptapratykshh** [comment]
This issue can be solved by adding special handling for square roots of `CRootOf` objects in `_eval_conjugate` method, which avoids the problematic `expand_complex()` call that was causing the `PolynomialError` when trying to expand `CRootOf` into real and imaginary components.

```
    def _eval_conjugate(self):
        from sympy.functions.elementary.complexes import conjugate as c
        from sympy.polys.rootoftools import CRootOf

        if hasattr(self, 'exp') and hasattr(self, 'base'):
            if self.exp == S.Half and isinstance(self.base, CRootOf):
                if self.base.poly.is_real:
                    if self.base.is_real:
                        return self
                    else:
                        poly, idx = self.base.args
                        new_idx = idx + 1 if idx % 2 == 0 else idx - 1
                        conjugated_root = CRootOf(poly, new_idx)
                        return self.func(conjugated_root, self.exp)

            i = self.exp.is_integer
            p = self.base.is_positive

            if i:
                return c(self.base)**self.exp
            if p:
                return self.base**c(self.exp)
            if i is False and p is False:
                if isinstance(self.base, CRootOf) or any(
                        isinstance(arg, CRootOf) for arg in self.args if hasattr(arg, 'args')):
                    return None

                expanded = expand_complex(self)
                if expanded != self:
                    return c(expanded)

        if self.is_extended_real:
            return self

```

**Comment by oscarbenjamin** [comment]
What needs to fixed here is:
```python
In [4]: expand_complex(sroot)
---------------------------------------------------------------------------
PolynomialError 
```
This happens because `expand` will apply `expand_complex` to the args and then tries to reconstruct the object. That should not happen with a RootOf and would not happen if the RootOf was an atom. I wonder if perhaps it should be an atom given that it is generally not valid to do any manipulation with the args of a RootOf.

**Comment by guptapratykshh** [comment]
To fix this issue according to your suggestion then we have to make a `CRootOf` inherit from `AtomicExpr` instead of `Expr`  or override `is_Atom` to return True in the `CRootOf` class. This implements proper evaluation methods like `_eval_conjugate` that work without relying on decomposition.

This would be structural change that might prevent whole class of similar issues where standard recursive algorithms inappropriately try to manipulate internal structure of `RootOf`.
