### ISSUE TITLE
Still the issue  'numpy.core.multiarray' has no attribute '_get_ndarray_c_version'

### ISSUE THREAD

**Issue by kreegah** [sympy/sympy#16556]
Windows 10 64bit, Anaconda 3 (64 bit), Theano 1.0.3, Numpy 1.16.2.

Here is what I get:
Python 3.6.4 |Anaconda custom (64-bit)| (default, Mar  9 2018, 07:43:39) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import theano
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import theano
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\__init__.py", line 156, in <module>
    import theano.gpuarray
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gpuarray\__init__.py", line 33, in <module>
    from . import fft, dnn, opt, extra_ops, multinomial, reduction, sort, rng_mrg, ctc
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gpuarray\fft.py", line 14, in <module>
    from .opt import register_opt, op_lifter, register_opt2
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gpuarray\opt.py", line 2803, in <module>
    from .dnn import (local_abstractconv_cudnn,
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gpuarray\dnn.py", line 339, in <module>
    handle_type = CUDNNDataType('cudnnHandle_t', 'cudnnDestroy')
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gpuarray\dnn.py", line 259, in CUDNNDataType
    version=version(raises=False))
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gpuarray\dnn.py", line 319, in version
    if not dnn_present():
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gpuarray\dnn.py", line 209, in dnn_present
    dnn_present.avail, dnn_present.msg = _dnn_check_version()
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gpuarray\dnn.py", line 180, in _dnn_check_version
    v = version()
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gpuarray\dnn.py", line 330, in version
    profile=False)
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gof\op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1609, in cthunk_factory
    key = self.cmodule_key()
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1300, in cmodule_key
    c_compiler=self.c_compiler(),
  File "C:\Users\nmb31\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1379, in cmodule_key_
    np.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', DnnVersion(), '\n', "module 'numpy.core.multiarray' has no attribute '_get_ndarray_c_version'")
>>>

**Comment by sylee957** [comment]
Well, this may have to be posted to [theano](https://github.com/Theano/Theano/issues) issue tracker.
We had same issue #15784 with theano 1.03, and I guess you may have to upgrade theano to support numpy 1.16

**Comment by eric-wieser** [comment]
I think this was fixed in the linked numpy PR, so can be closed?
