### ISSUE TITLE
roots gives incorrect result

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#16589]
`roots(x**4 - 8*sqrt(2)*x**3 + 4*x**3 - 64*sqrt(2)*x**2 + 1024*x, x)` gives a set of roots, among which there is no `x=0` and there is `x=8sqrt(2)/3`, but it is not a root.

**Comment by oscarbenjamin** [comment]
It looks like the other three roots are correct:
```julia
In [87]: p = x**4 - 8*sqrt(2)*x**3 + 4*x**3 - 64*sqrt(2)*x**2 + 1024*x                                                                         

In [88]: rs = roots(p, x)                                                                                                                      

In [89]: p = x**4 - 8*sqrt(2)*x**3 + 4*x**3 - 64*sqrt(2)*x**2 + 1024*x                                                                         

In [90]: rs = list(roots(p, x))                                                                                                                

In [91]: [p.subs(x, r).evalf() for r in rs]                                                                                                    
Out[91]: [-0.e-121, 0.e-125 - 0.e-125⋅ⅈ, 0.e-125 + 0.e-125⋅ⅈ, 2384.49544824355]

In [92]: rs[3]                                                                                                                                 
Out[92]: 
8⋅√2
────
 3 
```

I guess there are two issues here:
1. Since there is a quartic formula that should give these roots, either the formula has a bug somewhere or it gives something that is incorrectly simplified.
2. Trivial `x=0` roots should probably be factored out before applying the formula.

**Comment by jksuom** [comment]
It seems that the zero roots are added too early to the result on this line.
https://github.com/sympy/sympy/blob/1b7514db3923012f6f0aad14315b24e95bef639c/sympy/polys/polyroots.py#L1029
That should be done only after the nontrivial roots have been translated to their proper places (after `if translate_x` block).

**Comment by smichr** [comment]
```diff
diff --git a/sympy/polys/polyroots.py b/sympy/polys/polyroots.py
index c87b61b..ff2b2e1 100644
--- a/sympy/polys/polyroots.py
+++ b/sympy/polys/polyroots.py
@@ -1026,8 +1026,6 @@ def _try_heuristics(f):
         for currentroot, k in _result.items():
             result[coeff*currentroot] = k
 
-    result.update(zeros)
-
     if filter not in [None, 'C']:
         handlers = {
             'Z': lambda r: r.is_Integer,
@@ -1049,26 +1047,30 @@ def _try_heuristics(f):
         for zero in dict(result).keys():
             if not predicate(zero):
                 del result[zero]
+
     if rescale_x:
         result1 = {}
         for k, v in result.items():
             result1[k*rescale_x] = v
         result = result1
+
     if translate_x:
         result1 = {}
         for k, v in result.items():
             result1[k + translate_x] = v
         result = result1
 
+    # include the trivial solutions now that
+    # the shifting/scaling is done
+    result.update(zeros)
+
     if not multiple:
         return result
     else:
-        zeros = []
-
-        for zero in ordered(result):
-            zeros.extend([zero]*result[zero])
-
-        return zeros
+        flat = []
+        for r in ordered(result):
+            flat.extend([r]*result[r])
+        return flat
 
 
 def root_factors(f, *gens, **args):
diff --git a/sympy/polys/tests/test_polyroots.py b/sympy/polys/tests/test_polyroots.py
index e2cd6e9..2b352ed 100644
--- a/sympy/polys/tests/test_polyroots.py
+++ b/sympy/polys/tests/test_polyroots.py
@@ -3,6 +3,7 @@
 from sympy import (S, symbols, Symbol, Wild, Rational, sqrt,
     powsimp, sin, cos, pi, I, Interval, re, im, exp, ZZ, Piecewise,
     acos, root, conjugate)
+from sympy.core.tests.test_evalf import NS
 
 from sympy.polys import Poly, cyclotomic_poly, intervals, nroots, rootof
 
@@ -521,6 +522,12 @@ def test_roots0():
          -sqrt(2) - root(7, 3)/2 + sqrt(3)*root(7, 3)*I/2: 1,
          -sqrt(2) + root(7, 3): 1}
 
+    # issue 16589
+    p  = x**4 - 8*sqrt(2)*x**3 + 4*x**3 - 64*sqrt(2)*x**2 + 1024*x
+    r = roots(p, x)
+    assert [NS(i, 2) for i in r] == ['-11.', '8.9 - 4.2*I', '8.9 + 4.2*I', '0']
+
+
 def test_roots_slow():
     """Just test that calculating these roots does not hang. """
     a, b, c, d, x = symbols("a,b,c,d,x")
```

**Comment by smichr** [comment]
I verified the roots from the diff above. That verification is much slower than the test included above, but I show the confirmation here:
```
>>> r
{-(-256*sqrt(2) + sqrt(-4*(144 + 128*sqrt(2))**3 + (21632 - 512*sqrt(2))**2)/2 +
 10816)**(1/3)/3 - (144 + 128*sqrt(2))/(3*(-256*sqrt(2) + sqrt(-4*(144 + 128*sqr
t(2))**3 + (21632 - 512*sqrt(2))**2)/2 + 10816)**(1/3)) - 4/3 + 8*sqrt(2)/3: 1,
-4/3 + 8*sqrt(2)/3 - (-1/2 + sqrt(3)*I/2)*(-256*sqrt(2) + sqrt(-4*(144 + 128*sqr
t(2))**3 + (21632 - 512*sqrt(2))**2)/2 + 10816)**(1/3)/3 - (144 + 128*sqrt(2))/(
3*(-1/2 + sqrt(3)*I/2)*(-256*sqrt(2) + sqrt(-4*(144 + 128*sqrt(2))**3 + (21632 -
 512*sqrt(2))**2)/2 + 10816)**(1/3)): 1, -4/3 + 8*sqrt(2)/3 - (144 + 128*sqrt(2)
)/(3*(-1/2 - sqrt(3)*I/2)*(-256*sqrt(2) + sqrt(-4*(144 + 128*sqrt(2))**3 + (2163
2 - 512*sqrt(2))**2)/2 + 10816)**(1/3)) - (-1/2 - sqrt(3)*I/2)*(-256*sqrt(2) + s
qrt(-4*(144 + 128*sqrt(2))**3 + (21632 - 512*sqrt(2))**2)/2 + 10816)**(1/3)/3: 1
, 0: 1}
>>> p
x**4 - 8*sqrt(2)*x**3 + 4*x**3 - 64*sqrt(2)*x**2 + 1024*x

>>> not any(p.subs(x, i).n(2, chop=True) for i in r)
True
>>> [p.subs(x, i).n(2) for i in r]
[0.e-106, 0.e-108 + 0.e-109*I, 0.e-108 - 0.e-109*I, 0]
```

**Comment by vorabrijesh** [comment]
When I use `r = roots_quartic(Poly('x**4 - 8*sqrt(2)*x**3 + 4*x**3 - 64*sqrt(2)*x**2 + 1024*x'))`
I get this error,
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/brijesh/untitled/sympy/sympy/polys/polyroots.py", line 288, in roots_quartic
    _, a, b, c, d = f.monic().all_coeffs()
  File "/home/brijesh/untitled/sympy/sympy/polys/polytools.py", line 861, in all_coeffs
    return [f.rep.dom.to_sympy(c) for c in f.rep.all_coeffs()]
  File "/home/brijesh/untitled/sympy/sympy/polys/polyclasses.py", line 326, in all_coeffs
    raise PolynomialError('multivariate polynomials not supported')
PolynomialError: multivariate polynomials not supported

```
so, it is not not going into roots_quartic function and if I do this I get the right ans,

`r=Poly('x**4 - 8*sqrt(2)*x**3 + 4*x**3 - 64*sqrt(2)*x**2 + 1024*x')`
`solve(r)`
 I get 0 as the ans and doesn't get 8sqrt(2)/3.
So, should we call solve function inside polyroot.py to solve the problem?

**Comment by rimibis** [comment]
Hi, I'm a uni student in a software engineering class and was looking for a good issue for a beginner start working on. Is this issue available for me to work on? Thank you!

**Comment by oscarbenjamin** [comment]
Yes you can start working on it. Send a PR and we can continue discussion there.

**Comment by joybhallaa** [comment]
@rimibis  are you still working on it, if not can I take it?

**Comment by rimibis** [comment]
@joybhallaa Go ahead.

**Comment by joybhallaa** [comment]
I will not be able to work on this, if anyone wants to work on it, please go ahead.

**Comment by smichr** [comment]
> When I use
> `r = roots_quartic(Poly('x**4 - 8*sqrt(2)*x**3 + 4*x**3 - 64*sqrt(2)*x**2 + 1024*x'))`
> I get this error,

If you use `Poly(..., x)` to indicate that `sqrt(2)` is not one of the generators then it works.

**Comment by aaditkamat** [comment]
Hi @joybhallaa and @rimibis, can I work on this issue?

**Comment by rimibiswas** [comment]
Yeah, sure! I'm not working in it either.
