### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by lzkim** [sympy/sympy#16621]
> Traceback (most recent call last):
  File "<ipython-input-1-157b59d24f34>", line 1, in <module>
    runfile('C:/Users/SEC/Desktop/ode_pack/MKM_ccode_generator.py', wdir='C:/Users/SEC/Desktop/ode_pack')
  File "C:\Users\SEC\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)
  File "C:\Users\SEC\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/SEC/Desktop/ode_pack/MKM_ccode_generator.py", line 40, in <module>   auto_odes=autowrap(ode_eq,backend="cython",tempdir="./autowraptmp")
  File "C:\Users\SEC\Anaconda3\lib\site-packages\sympy\utilities\autowrap.py", line 634, in autowrap
    return code_wrapper.wrap_code(routine, helpers=helps)
  File "C:\Users\SEC\Anaconda3\lib\site-packages\sympy\utilities\autowrap.py", line 149, in wrap_code
    self._process_files(routine)
  File "C:\Users\SEC\Anaconda3\lib\site-packages\sympy\utilities\autowrap.py", line 172, in _process_files
    " ".join(command), e.output.decode('utf-8')))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 996: invalid start byte

Python 3.6.2.
Sympy 1.3.

I tried patching line 172 in autowrap.py as followed
`` " ".join(command), e.output.decode('utf-16'))) ``

`` " ".join(command), e.output.decode('utf-8','ignore'))) ``

But both cases did not work.
How can I solve this problem?

**Comment by oscarbenjamin** [comment]
Without seeing the input I don't know how to advise.

The error means that what you have is not valid utf-8. Do you know that it should be utf-8? If so I think your problem has occurred earlier.
