### ISSUE TITLE
TypeError on Or.subs()

### ISSUE THREAD

**Issue by fpom** [sympy/sympy#16627]
Hi,

I'm trying to substitute variables in a Boolean expression but it raises a `TypeError`. I have this error both in 1.3 and 1.4 version of Sympy.

Thanks for your help!
Franck

```python
In [1]: import sympy                                                            

In [2]: e = sympy.Symbol("spam") | sympy.Symbol("foo")                          

In [3]: e.subs("foo", "bar", simultaneous=True)                                 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/sympy/core/cache.py in wrapper(*args, **kwargs)
     93                 try:
---> 94                     retval = cfunc(*args, **kwargs)
     95                 except TypeError:

~/.local/lib/python3.6/site-packages/sympy/core/basic.py in _subs(self, old, new, **hints)
   1110         if rv is None:
-> 1111             rv = fallback(self, old, new)
   1112         return rv

~/.local/lib/python3.6/site-packages/sympy/core/basic.py in fallback(self, old, new)
   1087             if hit:
-> 1088                 rv = self.func(*args)
   1089                 hack2 = hints.get('hack2', False)

~/.local/lib/python3.6/site-packages/sympy/core/operations.py in __new__(cls, *args, **options)
    412             # without having to sympify all values
--> 413             _args = frozenset(cls._new_args_filter(args))
    414         except ShortCircuit:

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in _new_args_filter(cls, args)
    774         rel = []
--> 775         args = BooleanFunction.binary_check_and_simplify(*args)
    776         for x in args:

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in binary_check_and_simplify(self, *args)
    449         from sympy.core.relational import Relational, Eq, Ne
--> 450         args = [as_Boolean(i) for i in args]
    451         bin = set().union(*[i.binary_symbols for i in args])

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in <listcomp>(.0)
    449         from sympy.core.relational import Relational, Eq, Ne
--> 450         args = [as_Boolean(i) for i in args]
    451         bin = set().union(*[i.binary_symbols for i in args])

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in as_Boolean(e)
     52         return e
---> 53     raise TypeError('expecting bool or Boolean, not `%s`.' % e)
     54 

TypeError: expecting bool or Boolean, not `_Dummy_19*_Dummy_20`.

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-3-a3f29c4f1997> in <module>
----> 1 e.subs("foo", "bar", simultaneous=True)

~/.local/lib/python3.6/site-packages/sympy/core/basic.py in subs(self, *args, **kwargs)
    986                 # in things like Derivative(f(x, y), x) in which x
    987                 # is both free and bound
--> 988                 rv = rv._subs(old, d*m, **kwargs)
    989                 if not isinstance(rv, Basic):
    990                     break

~/.local/lib/python3.6/site-packages/sympy/core/cache.py in wrapper(*args, **kwargs)
     94                     retval = cfunc(*args, **kwargs)
     95                 except TypeError:
---> 96                     retval = func(*args, **kwargs)
     97                 return retval
     98 

~/.local/lib/python3.6/site-packages/sympy/core/basic.py in _subs(self, old, new, **hints)
   1109         rv = self._eval_subs(old, new)
   1110         if rv is None:
-> 1111             rv = fallback(self, old, new)
   1112         return rv
   1113 

~/.local/lib/python3.6/site-packages/sympy/core/basic.py in fallback(self, old, new)
   1086                     args[i] = arg
   1087             if hit:
-> 1088                 rv = self.func(*args)
   1089                 hack2 = hints.get('hack2', False)
   1090                 if hack2 and self.is_Mul and not rv.is_Mul:  # 2-arg hack

~/.local/lib/python3.6/site-packages/sympy/core/operations.py in __new__(cls, *args, **options)
    411             # is done so short-circuiting can be done
    412             # without having to sympify all values
--> 413             _args = frozenset(cls._new_args_filter(args))
    414         except ShortCircuit:
    415             return sympify(cls.zero)

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in _new_args_filter(cls, args)
    773         newargs = []
    774         rel = []
--> 775         args = BooleanFunction.binary_check_and_simplify(*args)
    776         for x in args:
    777             if x.is_Relational:

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in binary_check_and_simplify(self, *args)
    448     def binary_check_and_simplify(self, *args):
    449         from sympy.core.relational import Relational, Eq, Ne
--> 450         args = [as_Boolean(i) for i in args]
    451         bin = set().union(*[i.binary_symbols for i in args])
    452         rel = set().union(*[i.atoms(Relational) for i in args])

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in <listcomp>(.0)
    448     def binary_check_and_simplify(self, *args):
    449         from sympy.core.relational import Relational, Eq, Ne
--> 450         args = [as_Boolean(i) for i in args]
    451         bin = set().union(*[i.binary_symbols for i in args])
    452         rel = set().union(*[i.atoms(Relational) for i in args])

~/.local/lib/python3.6/site-packages/sympy/logic/boolalg.py in as_Boolean(e)
     51     if isinstance(e, Boolean):
     52         return e
---> 53     raise TypeError('expecting bool or Boolean, not `%s`.' % e)
     54 
     55 

TypeError: expecting bool or Boolean, not `_Dummy_19*_Dummy_20`.
```

**Comment by divyanshu132** [comment]
If we don't use `simultaneous = True` then, the result seems correct.

```
>>> e = Symbol("spam") | Symbol("foo")
>>> e
foo | spam
>>> e.subs("foo", "bar") 
bar | spam
```

**Comment by fpom** [comment]
Indeed, it works without `simultaneous=True`, but I'd expected to to work also with it.  :)

**Comment by smichr** [comment]
It could be that this `m` hack is not needed:
```python
                d = Dummy(commutative=new.is_commutative)
                # using d*m so Subs will be used on dummy variables
                # in things like Derivative(f(x, y), x) in which x
                # is both free and bound
                rv = rv._subs(old, d*m, **kwargs)
                if not isinstance(rv, Basic):
                    break
                reps[d] = new
            reps[m] = S.One  # get rid of m
```
One could try `Derivative(f(x, y), x).subs({x: y, y:x}, simultaneous=True)` with `m=1` in the code to see if the right answer is obtained, `Derivative(f(y, x), y)`, and no other tests fail.

**Comment by Sc0rpi0n101** [comment]
In current master, I am getting this result, but shouldn't it be opposite?
Shouldn't it be d\dx(2) without simultaneous and the other one when simultaneous = True
```
>>> Derivative(((x + y)/y), x)
∂ ⎛x + y⎞
──⎜─────⎟
∂x⎝  y  ⎠
>>> Derivative(((x + y)/y), x).subs({y: x, x: y})
⎛∂ ⎛x + y⎞⎞│        
⎜──⎜─────⎟⎟│        
⎝∂x⎝  y  ⎠⎠│y=x, x=x
>>> Derivative(((x + y)/y), x).subs({y: x, x: y}, simultaneous = True)
⎛d    ⎞│   
⎜──(2)⎟│   
⎝dx   ⎠│x=y
>>> 
```
When I tried replacing m with 1, i got this resut, which is what we wanted
```
>>> Derivative(((x + y)/y), x)
∂ ⎛x + y⎞
──⎜─────⎟
∂x⎝  y  ⎠
>>> Derivative(((x + y)/y), x).subs({y: x, x: y})
⎛∂ ⎛x + y⎞⎞│        
⎜──⎜─────⎟⎟│        
⎝∂x⎝  y  ⎠⎠│y=x, x=x
>>> Derivative(((x + y)/y), x).subs({y: x, x: y}, simultaneous = True)
∂ ⎛x + y⎞
──⎜─────⎟
∂y⎝  x  ⎠
```
I tested the core module and only one test failed, but because it was being derivated  wrt 0, that test can be changed, removing simultaneous = True

```
>>> from sympy.abc import a, x, y, z
>>> reps = {x: 0, y: 0}
>>> Derivative(x, y, z).subs(reps, simultaneous=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 993, in subs
    return rv.xreplace(reps)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1182, in xreplace
    value, _ = self._xreplace(rule)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/basic.py", line 1204, in _xreplace
    return self.func(*args), True
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/function.py", line 1287, in __new__
    __)))
ValueError: 
Can't calculate derivative wrt 0.
>>> Derivative(x, y, z).subs(reps)
⎛   2    ⎞│   
⎜  d     ⎟│   
⎜─────(0)⎟│   
⎝dz dy   ⎠│y=0
>>> 
```

**Comment by Sc0rpi0n101** [comment]
```python
>>> e = Symbol("spam") | Symbol("foo")
>>> e.subs("foo", "bar", simultaneous=True)   
bar | spam
>>> e.subs({"foo":"bar", "spam": "repl"})
bar | repl
>>> e.subs({"foo":"bar", "spam": "repl"}, simultaneous = True)
bar | repl
>>> 
```

The issue seems to be resolved too after changing m to 1

**Comment by Sc0rpi0n101** [comment]
I have created a PR removing the use of m for review.
The current tests and the ones discussed in this issue are running successfully.
I have tested some functions for which m was being used and the results were the same.

If anyone finds any bugs in functions that might have used m, please let me know.

**Comment by Sc0rpi0n101** [comment]
So, most of the tests were successful

But I'm having some problems with `f(x).diff(x)**n` and checkdesol
