### ISSUE TITLE
parse_expr doesn't parse floating point numbers

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#16639]
From #16632,
```python
from sympy import *
from sympy.parsing.sympy_parser import parse_expr, standard_transformations, implicit_multiplication_application
transformations = (
    standard_transformations +
    (implicit_multiplication_application,))

expr = parse_expr('n1.1n22', transformations=transformations)
print(expr) # --> 2.2*n**2
```
The expression was interpreted like `n * 1 * .1 * n * 22` instead of `n*1.1*n*22`

sylee957 commented:
> It can't be handled in split_symbols, because I see the input already gets decomposed like
```
[
    (1, 'Symbol'), (53, '('), (1, "'n1'"), (53, ')'), 
    (1, 'Float'), (53, '('), (2, "'.1'"), (53, ')'),
    (1, 'Symbol'), (53, '('), (1, "'n22'"), (53, ')'), 
    (4, ''), (0, '')
]
```
before passed to the split_symbols.

There are some other floating point problem test cases [here](https://github.com/sympy/sympy/pull/16632#issuecomment-482804980) that involve exponentials and a means of handling them (perhaps).

So the easier case (integers) has been fixed (#2589) but this now remains.

cf related issue #7341

**Comment by smichr** [comment]
A test case should be added from #2589 
```python
from sympy.parsing.sympy_parser import parse_expr, standard_transformations, implicit_multiplication, split_symbols
t = (standard_transformations + ( split_symbols, implicit_multiplication))
parse_expr("33x", transformations = t) == parse_expr("x33", transformations = t) == 33*x
```

**Comment by Sc0rpi0n101** [comment]
So, how do you think this can be fixed?

```
>>> _refloat = regex.compile(r"((\d*\.\d+)|(\d+\.?\d?))([eE][-+]?\d+)?")
>>> assert len(_refloat.split('x1')) == 1 + 4
>>> def nspace(s):
...     g = _refloat.split(s)
...     if type(g) == type(s): return s
...     p = []
...     i = 0
...     while i < len(g):
...         if not g[i]:
...             i += 1
...         elif g[i][0].isdigit() or g[i][0]=='.':
...             if p and p[-1].endswith('_') and all(d.isdigit() for d in g[i]):
...                 p[-1] += g[i]
...             else:
...                 p.append(g[i])
...             i += 4
...         else:
...             p.append(g[i])
...             i += 1
...     return ' '.join(p)
>>> nspace('n1.1n22n3')
n 1.1 n 22 n 3
>>> nspace('n1.1n22n_3')
n 1.1 n 22 n_3  
```
Won't this be processed as n * (1.1) * n * 22 * n * 3
instead of (n * 1).(1 * n  * 22 * n * 3)?

**Comment by smichr** [comment]
If you parse the nspace line you get
```python
>>> print(filldedent([func_name(i) for i in t])[1:])
['lambda_notation', 'auto_symbol', 'repeated_decimals', 'auto_number',
'factorial_notation', '_split_symbols', 'implicit_multiplication']
>>> parse_expr("n 1.1 n 22 n_3 ", transformations=t)
24.2*n**2*n_3
```

**Comment by Sc0rpi0n101** [comment]
> If you parse the nspace line you get
> 
> ```python
> >>> print(filldedent([func_name(i) for i in t])[1:])
> ['lambda_notation', 'auto_symbol', 'repeated_decimals', 'auto_number',
> 'factorial_notation', '_split_symbols', 'implicit_multiplication']
> >>> parse_expr("n 1.1 n 22 n_3 ", transformations=t)
> 24.2*n**2*n_3
> ```

So, it's taking 1.1 as an individual identity as we have 24.2 * n**2 * n_3
So it multiplied the two n and multiplied 1.1 by 22 and n_3

But if it was to be processed as decimal, we should have got (n*1).(22*n*n_3)

**Comment by smichr** [comment]
> we should have got `(n*1).(22*n*n_3)`

we don't parse numbers with symbolic digits in SymPy...though that's an intriguing input possibility:

`foo('12x3') -> 1203 + 10*x`

Perhaps best left to the user?

**Comment by Sc0rpi0n101** [comment]
> Perhaps best left to the user?

Probably,
but how hard can it be to implement such a thing?

**Comment by smichr** [comment]
> will have to be written with spaces

So the idea is that the input string to `parse_expr` has, as its first step, rewriting via `nspace`. A potential problem, however, is that some user-function could have a name with a number in it like `log10(3n)` so maybe the number pattern would have to have `[A-Za-z]` anchors at either end to make it match only symbol-enclosed numbers (But `e3e2e` -> `e300e`.)

**Comment by smichr** [comment]
Else, perhaps this has to be handled in the split symbols step: if one symbol ends with an integer that is not preceded by an underscore than it should be broken off; if a symbol starts with anything that matches the number pattern then it should be split off and potentially concatenated with the previous number when present.
```
x3.2e4y5.6z -> 
x 3 .2 e 4 y 5 .6 z --number+e+number--> 
x 3 .2e4 y 5 .6 z  --number+number--> 
x 3.2e4 y 5.6 z
```

**Comment by Sc0rpi0n101** [comment]
```python
>>> nspace('log10(3n)')
log 10 ( 3 n)
>>> parse_expr('log 10 ( 3 n)', transformations=transformations)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 903, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    log (Integer (10 )*()Integer (3 )*Symbol ('n' ))
                               ^
SyntaxError: invalid syntax

```
gives a syntax error, but more importantly it is currently processing it as log(10 * 3 * n) and gives error due to the unexpected (

```python
>>> nspace('e3e2e')
e 3 e
>>> nspace('x3.2e4y5.6z')
x 3.2 y 5.6 z
>>> 
```
Also, I noticed, currently nspace just removes the exponential term insted of making it 10^n as is normally done.

```python
>>> parse_expr('x 3.2e4 y 5.6 z', transformations=transformations)
179200.0⋅x⋅y⋅z
>>> parse_expr('x3.2e4y5.6z', transformations=transformations)
18000.0⋅x⋅y⋅z
>>> parse_expr(nspace('x3.2e4y5.6z'), transformations=transformations)
17.92⋅x⋅y⋅z
>>> 
```

**Comment by smichr** [comment]
```diff
diff --git a/sympy/parsing/sympy_parser.py b/sympy/parsing/sympy_parser.py
index a2c400b..4dd4ae4 100644
--- a/sympy/parsing/sympy_parser.py
+++ b/sympy/parsing/sympy_parser.py
@@ -8,6 +8,7 @@
 from keyword import iskeyword
 
 import ast
+import re as regex
 import unicodedata
 
 from sympy.core.compatibility import exec_, StringIO, iterable
@@ -905,6 +906,34 @@ def eval_expr(code, local_dict, global_dict):
     return expr
 
 
+_refloat = regex.compile(r"((\d*\.\d+)|(\d+\.?\d?))([eE][-+]?\d+)?")
+def nspace(s, local_dict, global_dict):
+    g = _refloat.split(s)
+    if type(g) == type(s): return s
+    p = []
+    i = 0
+    while i < len(g):
+        if not g[i]:
+            i += 1
+        elif g[i][0].isdigit() or g[i][0]=='.':
+            num = g[i] + (g[i+3] or '')
+            if p and p[-1].endswith('_') and all(d.isdigit() for d in num):
+                p[-1] += num
+            else:
+                p.append(num)
+            i += 4
+        else:
+            p.append(g[i])
+            i += 1
+    for i in range(1, len(p)):
+        if all(_.isdigit() for _ in p[i]):
+            q = p[i + 1] + p[i]
+            if q in local_dict or q in global_dict:
+                p[i - 1]+= p[i]
+            p[i] = ''
+    return ' '.join(p)
+
+
 def parse_expr(s, local_dict=None, transformations=standard_transformations,
                global_dict=None, evaluate=True):
     """Converts the string ``s`` to a SymPy expression, in ``local_dict``
@@ -1000,6 +1029,7 @@ def parse_expr(s, local_dict=None, transformations=standard_transformations,
                 raise TypeError(filldedent('''
                     a transformation should be function that
                     takes 3 arguments'''))
+    s = nspace(s, local_dict, global_dict)
     code = stringify_expr(s, local_dict, global_dict, transformations)
 
     if not evaluate:

```
gives
```python
>>> parse_expr('x 3.2e4 y 5.6 z', transformations=transformations)
179200.0*x*y*z
>>> parse_expr('x_3e4yz', transformations=transformations)
30000.0*x_*y*z
>>> parse_expr('x_3yz', transformations=transformations)
x_3*y*z
>>> parse_expr('log10(3.2x)', transformations=transformations)
log(3.2*x)
```

**Comment by Sc0rpi0n101** [comment]
> ```python
> >>> parse_expr('x 3.2e4 y 5.6 z', transformations=transformations)
> 179200.0*x*y*z
> >>> parse_expr('x_3e4yz', transformations=transformations)
> 30000.0*x_*y*z
> >>> parse_expr('x_3yz', transformations=transformations)
> x_3*y*z
> >>> parse_expr('log10(3.2x)', transformations=transformations)
> log(3.2*x)
> ```

Ok, all these seem to be working fine with this definition.

Anything else you'd like me to test?

**Comment by Sc0rpi0n101** [comment]
Now, We have a problem

```python
sympy/parsing/tests/test_implicit_multiplication_application.py[5] EEE.E                                                 [FAIL]
sympy/parsing/tests/test_latex_deps.py[1] .                                                                                [OK]
sympy/parsing/tests/test_mathematica.py[1] E                                                                             [FAIL]
sympy/parsing/tests/test_maxima.py[3] EEE                                                                                [FAIL]
sympy/parsing/tests/test_sympy_parser.py[22] E..EEE....EEE.EE.E.E.E                                                      [FAIL]

_______________________________________________________________________________________________________________________________
________________ sympy/parsing/tests/test_implicit_multiplication_application.py:test_implicit_multiplication _________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_implicit_multiplication_application.py", line 38, in test_implicit_multiplication
    implicit = parse_expr(case, transformations=transformations2)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    (Symbol ('x' )+)*(Symbol ('x' )+)
                   ^
SyntaxError: invalid syntax
_______________________________________________________________________________________________________________________________
__________________ sympy/parsing/tests/test_implicit_multiplication_application.py:test_implicit_application __________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_implicit_multiplication_application.py", line 62, in test_implicit_application
    implicit = parse_expr(case, transformations=transformations2)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1032, in parse_expr
    s = nspace(s, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 930, in nspace
    q = p[i + 1] + p[i]
IndexError: list index out of range
_______________________________________________________________________________________________________________________________
________________ sympy/parsing/tests/test_implicit_multiplication_application.py:test_function_exponentiation _________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/power.py", line 286, in __new__
    obj = b._eval_power(e)
TypeError: _eval_power() missing 1 required positional argument: 'other'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_implicit_multiplication_application.py", line 84, in test_function_exponentiation
    implicit = parse_expr(case, transformations=transformations2)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/decorators.py", line 129, in binary_op_wrapper
    return func(self, other)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 183, in __rpow__
    return Pow(other, self)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/cache.py", line 96, in wrapper
    retval = func(*args, **kwargs)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/power.py", line 286, in __new__
    obj = b._eval_power(e)
TypeError: _eval_power() missing 1 required positional argument: 'other'
_______________________________________________________________________________________________________________________________
___________________ sympy/parsing/tests/test_implicit_multiplication_application.py:test_all_implicit_steps ___________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_implicit_multiplication_application.py", line 183, in test_all_implicit_steps
    implicit = parse_expr(case, transformations=transformations2)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
TypeError: FunctionClass object argument after * must be an iterable, not Symbol
_______________________________________________________________________________________________________________________________
__________________________________ sympy/parsing/tests/test_mathematica.py:test_mathematica ___________________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/sympify.py", line 384, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    -*Symbol ('x' )
     ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_mathematica.py", line 53, in test_mathematica
    assert mathematica(e) == sympify(d[e])
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/mathematica.py", line 18, in mathematica
    return sympify(parser.parse(s))
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/sympify.py", line 386, in sympify
    raise SympifyError('could not parse %r' % a, exc)
sympy.core.sympify.SympifyError: Sympify of expression 'could not parse '-6*x'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)
_______________________________________________________________________________________________________________________________
_______________________________________ sympy/parsing/tests/test_maxima.py:test_parser ________________________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/sympify.py", line 384, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    maxima_float (/)
                  ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_maxima.py", line 9, in test_parser
    assert Abs(parse_maxima('float(1/3)') - 0.333333333) < 10**(-5)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/maxima.py", line 65, in parse_maxima
    obj = sympify(str, locals=dct)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/sympify.py", line 386, in sympify
    raise SympifyError('could not parse %r' % a, exc)
sympy.core.sympify.SympifyError: Sympify of expression 'could not parse 'maxima_float(1/3)'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)
_______________________________________________________________________________________________________________________________
______________________________________ sympy/parsing/tests/test_maxima.py:test_injection ______________________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_maxima.py", line 16, in test_injection
    parse_maxima('c: x+1', globals=globals())
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/maxima.py", line 65, in parse_maxima
    obj = sympify(str, locals=dct)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/sympify.py", line 384, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1032, in parse_expr
    s = nspace(s, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 930, in nspace
    q = p[i + 1] + p[i]
IndexError: list index out of range
_______________________________________________________________________________________________________________________________
__________________________________ sympy/parsing/tests/test_maxima.py:test_maxima_functions ___________________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/sympify.py", line 384, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    maxima_expand ((Symbol ('x' )+)**)
                                  ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_maxima.py", line 24, in test_maxima_functions
    assert parse_maxima('expand( (x+1)^2)') == x**2 + 2*x + 1
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/maxima.py", line 65, in parse_maxima
    obj = sympify(str, locals=dct)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/sympify.py", line 386, in sympify
    raise SympifyError('could not parse %r' % a, exc)
sympy.core.sympify.SympifyError: Sympify of expression 'could not parse 'maxima_expand( (x+1)**2)'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)
_______________________________________________________________________________________________________________________________
_________________________________ sympy/parsing/tests/test_sympy_parser.py:test_sympy_parser __________________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_sympy_parser.py", line 57, in test_sympy_parser
    assert parse_expr(text) == result
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1032, in parse_expr
    s = nspace(s, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 930, in nspace
    q = p[i + 1] + p[i]
IndexError: list index out of range
_______________________________________________________________________________________________________________________________
_________________________________ sympy/parsing/tests/test_sympy_parser.py:test_repeated_fail _________________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_sympy_parser.py", line 99, in test_repeated_fail
    raises(TypeError, lambda: parse_expr(text))
  File "/home/sc0rpi0n101/Github/sympy/sympy/utilities/pytest.py", line 83, in raises
    code()
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_sympy_parser.py", line 99, in <lambda>
    raises(TypeError, lambda: parse_expr(text))
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    Integer (1 )[]
                 ^
SyntaxError: unexpected EOF while parsing
_______________________________________________________________________________________________________________________________
_______________________________ sympy/parsing/tests/test_sympy_parser.py:test_repeated_dot_only _______________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_sympy_parser.py", line 109, in test_repeated_dot_only
    assert parse_expr('1 + .[1]') == Rational(10, 9)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    Integer (1 )+.[]
                 ^
SyntaxError: invalid syntax
_______________________________________________________________________________________________________________________________
__________________________________ sympy/parsing/tests/test_sympy_parser.py:test_local_dict ___________________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_sympy_parser.py", line 120, in test_local_dict
    assert parse_expr(text, local_dict=local_dict) == result
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
TypeError: <lambda>() missing 1 required positional argument: 'x'
_______________________________________________________________________________________________________________________________
__________________________________ sympy/parsing/tests/test_sympy_parser.py:test_issue_7663 ___________________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_sympy_parser.py", line 158, in test_issue_7663
    assert parse_expr(e, evaluate=0) == parse_expr(e, evaluate=False)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1036, in parse_expr
    code = compile(evaluateFalse(code), '<string>', 'eval')
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1045, in evaluateFalse
    node = ast.parse(s)
  File "/home/sc0rpi0n101/anaconda3/envs/sympy-dev-py35/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    Integer (2 )*(Symbol ('x' )+)
                                ^
SyntaxError: invalid syntax
_______________________________________________________________________________________________________________________________
__________________________________ sympy/parsing/tests/test_sympy_parser.py:test_issue_10560 __________________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_sympy_parser.py", line 167, in test_issue_10560
    assert parse_expr(text, evaluate=False) == parse_expr(result, evaluate=False)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1032, in parse_expr
    s = nspace(s, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 930, in nspace
    q = p[i + 1] + p[i]
IndexError: list index out of range
_______________________________________________________________________________________________________________________________
__________________________________ sympy/parsing/tests/test_sympy_parser.py:test_issue_10773 __________________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_sympy_parser.py", line 176, in test_issue_10773
    assert parse_expr(text, evaluate=False) == parse_expr(result, evaluate=False)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1032, in parse_expr
    s = nspace(s, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 930, in nspace
    q = p[i + 1] + p[i]
IndexError: list index out of range
_______________________________________________________________________________________________________________________________
____________________________ sympy/parsing/tests/test_sympy_parser.py:test_split_symbols_function _____________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_sympy_parser.py", line 200, in test_split_symbols_function
    assert parse_expr("ay(x+1)", transformations=transformations) == a*y*(x+1)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    Symbol ('a' )*Symbol ('y' )*(Symbol ('x' )+)
                                               ^
SyntaxError: unexpected EOF while parsing
_______________________________________________________________________________________________________________________________
______________________________ sympy/parsing/tests/test_sympy_parser.py:test_functional_exponent ______________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/power.py", line 286, in __new__
    obj = b._eval_power(e)
TypeError: _eval_power() missing 1 required positional argument: 'other'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_sympy_parser.py", line 211, in test_functional_exponent
    assert parse_expr("sin^2(x)", transformations=t) == (sin(x))**2
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/decorators.py", line 129, in binary_op_wrapper
    return func(self, other)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/expr.py", line 183, in __rpow__
    return Pow(other, self)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/cache.py", line 96, in wrapper
    retval = func(*args, **kwargs)
  File "/home/sc0rpi0n101/Github/sympy/sympy/core/power.py", line 286, in __new__
    obj = b._eval_power(e)
TypeError: _eval_power() missing 1 required positional argument: 'other'
_______________________________________________________________________________________________________________________________
_____________________________ sympy/parsing/tests/test_sympy_parser.py:test_convert_equals_signs ______________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_sympy_parser.py", line 229, in test_convert_equals_signs
    assert parse_expr("1*2=x", transformations=transformations) == Eq(2, x)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    Eq (Integer (1 )*,Symbol ('x' ))
                     ^
SyntaxError: invalid syntax
_______________________________________________________________________________________________________________________________
_____________________________ sympy/parsing/tests/test_sympy_parser.py:test_split_symbols_numeric _____________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_sympy_parser.py", line 247, in test_split_symbols_numeric
    expr1 = parse_expr('2**n * 3**n')
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    Integer (2 )**Symbol ('n' )***Symbol ('n' )
                                 ^
SyntaxError: invalid syntax
_______________________________________________________________________________________________________________________________
_______________________________ sympy/parsing/tests/test_sympy_parser.py:test_python3_features ________________________________
Traceback (most recent call last):
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/tests/test_sympy_parser.py", line 269, in test_python3_features
    assert parse_expr("123_456") == 123456
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 1038, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/home/sc0rpi0n101/Github/sympy/sympy/parsing/sympy_parser.py", line 904, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    Integer (123 )Symbol ('_456' )
                       ^
SyntaxError: invalid syntax
```

All these tests start failing after adding s 

As soon as I comment out `s = nspace(s, local_dict, global_dict)`, all the tests pass again

**Comment by smichr** [comment]
The easiest way to fix this is for the user to put a delimiter next to floating point numbers that appear in expressions like:
```
x.1y --tokenizes as--> x/.1/y # this is unambiguous since it can't be a path
x1.1 -> x1/.1 /!\ is this x1*.1 or x*1.1
x1.e2y -> x1/./e2y /!\ though unlikely, this could be a module path
x1.1e2y -> x1/.1e2/y /!\ this is ambiguous: is it x*1.1e2*y or x1*.1e2*y
```
