### ISSUE TITLE
limit(binomial(n + z, n)*n**-z, n, oo) gives different answers based on assumptions of n and z

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#16722]
```pytb
>>> n, z = symbols('n z')
>>> limit(binomial(n + z, n)*n**-z, n, oo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/series/limits.py", line 82, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
  File "./sympy/series/limits.py", line 263, in doit
    r = gruntz(e, z, z0, dir)
  File "./sympy/series/gruntz.py", line 646, in gruntz
    r = limitinf(e, z)
  File "./sympy/series/gruntz.py", line 426, in limitinf
    c0, e0 = mrv_leadterm(e, x)
  File "./sympy/series/gruntz.py", line 510, in mrv_leadterm
    f, logw = rewrite(exps, Omega, x, w)
  File "./sympy/series/gruntz.py", line 582, in rewrite
    raise NotImplementedError('Result depends on the sign of %s' % sig)
NotImplementedError: Result depends on the sign of sign(z)
```

OK, that's fair, but if we make `z` positive:

```py
>>> z = symbols('z', positive=True)
>>> limit(binomial(n + z, n)*n**-z, n, oo)
1/gamma(z + 1)
```

This is the correct answer (`1/z!`). See https://www.johndcook.com/eqn/euler_factorial.html.

But now look what happens if I put assumptions on `n`

```py
>>> n = symbols('n', positive=True, integer=True)
>>> z = symbols('z', positive=True)
>>> limit(binomial(n + z, n)*n**-z, n, oo)
oo
```

and

```py
>>> n, z = symbols('n z', positive=True, integer=True)
>>> limit(binomial(n + z, n)*n**-z, n, oo)
Limit(n**(-z)*binomial(n + z, n), n, oo, dir='-')
```

The `oo` result is completely wrong. For both positive integers, there's no reason the limit shouldn't be computable, since `integer` is a restricted assumption on `n`.

**Comment by Saanidhyavats** [comment]
I want to contribute on this issue. I think the problem lies in `rewrite` function but not sure about it

**Comment by Saanidhyavats** [comment]
when only z is declared positive `mrv` function in first recursion gives different result as compared  to 2nd case where both n and z are declared positive.
