### ISSUE TITLE
Poly(1.*x**2 - 1.*oo, x).to_exact() generates ZeroDivisionError in polys

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#16720]
This works
```python
>>> Poly(1.*x**2 - 1.*oo)
Poly(1.0*x**2 + 1.0*(-inf), x, -inf, domain='RR')
>>> _.to_exact()
```
But when the x is given explicitly, it doesn't:
```python
Poly(x**2 + (-inf), x, -inf, domain='QQ')
>>> Poly(1.*x**2 - 1.*oo, x)
Poly(1.0*x**2 - inf, x, domain='RR')
>>> _.to_exact()
Traceback (most recent call last):
  File "C:\Users\leslie\Desktop\Dropbox\jnk.py", line 46, in <module>
    p.to_exact()
  File "polys\polytools.py", line 739, in to_exact
    result = f.rep.to_exact()
  File "polys\polyclasses.py", line 293, in to_exact
    return f.convert(f.dom.get_exact())
  File "polys\polyclasses.py", line 300, in convert
    return DMP(dmp_convert(f.rep, f.lev, f.dom, dom), dom, f.lev)
  File "polys\densebasic.py", line 563, in dmp_convert
    return dup_convert(f, K0, K1)
  File "polys\densebasic.py", line 540, in dup_convert
    return dup_strip([ K1.convert(c, K0) for c in f ])
  File "polys\densebasic.py", line 540, in <listcomp>
    return dup_strip([ K1.convert(c, K0) for c in f ])
  File "polys\domains\domain.py", line 107, in convert
    return self.convert_from(element, base)
  File "polys\domains\domain.py", line 97, in convert_from
    result = _convert(element, base)
  File "polys\domains\pythonrationalfield.py", line 61, in from_RealField
    p, q = K0.to_rational(a)
  File "polys\domains\realfield.py", line 100, in to_rational
    return self._context.to_rational(element, limit)
  File "polys\domains\mpelements.py", line 133, in to_rational
    a = n//d
ZeroDivisionError: integer division or modulo by zero
```

**Comment by jksuom** [comment]
It looks like a bug that `-inf` is accepted as a coefficient. It should have been filtered out by this:https://github.com/sympy/sympy/blob/b176f6a1d9890b42dc361857c887992315e3d5ad/sympy/polys/polyutils.py#L171-L173
It could be added to the list. However, it is probably not necessary to make infinite floats different from extended real infinities. (So `Float('-inf')` could be `-oo`.)

**Comment by smichr** [comment]
In master this now gives:
```python
>>> Poly(1.*x**2 - 1.*oo, x).to_exact()
Poly(1.0*x**2 - oo, x, domain='RR[-oo]')
>>> Poly(1.*x**2 - 1.*float(oo), x).to_exact()
Poly(1.0*x**2 - oo, x, domain='RR[-oo]')
```

**Comment by jksuom** [comment]
Hmm.. It seems that a bit of more work is needed to reject `oo` and `-oo` as generators.
