### ISSUE TITLE
sympy is not threadsafe (RuntimeError: dictionary changed size during iteration)

### ISSUE THREAD

**Issue by basnijholt** [sympy/sympy#16734]
I've been having this problem for over 2 years and it's incredibly hard to reproduce.

See [this](http://nbviewer.jupyter.org/url/files.nijho.lt/dask-sympy-fail.ipynb?flush_cache=true) notebook that you can use to reproduce it (sorry, if I make it more minimal the problem doesn't really happen).

Essentially, I think it's because `sympy` uses hashable default arguments.

The traceback is:
```
Traceback (most recent call last):
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/adaptive/runner.py", line 196, in _process_futures
    y = fut.result()
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/distributed/cfexecutor.py", line 32, in _cascade_future
    six.reraise(*result)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "<ipython-input-10-e1c11dc56422>", line 17, in f
    get_template({'V': 0})
  File "<ipython-input-10-e1c11dc56422>", line 10, in get_template
    template = kwant.continuum.discretize(ham, locals=subs)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/kwant/continuum/discretizer.py", line 141, in discretize
    tb, coords = discretize_symbolic(hamiltonian, coords, locals=locals)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/kwant/continuum/discretizer.py", line 225, in discretize_symbolic
    hoppings = _discretize_expression(expression, coords)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/kwant/continuum/discretizer.py", line 492, in _discretize_expression
    summand = _discretize_summand(summand * wf, coords)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/kwant/continuum/discretizer.py", line 417, in _discretize_summand
    result = -sympy.I * _differentiate(result, coordinate)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/kwant/continuum/discretizer.py", line 387, in _differentiate
    expr1 = expression.subs(coordinate, coordinate + h)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 997, in subs
    rv = rv._subs(old, new, **kwargs)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1111, in _subs
    rv = fallback(self, old, new)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1083, in fallback
    arg = arg._subs(old, new, **hints)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1106, in _subs
    if _aresame(self, old):
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 1855, in _aresame
    if i != j or type(i) != type(j):
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 352, in __ne__
    return not self == other
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 341, in __eq__
    return self._hashable_content() == other._hashable_content()
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/symbol.py", line 252, in _hashable_content
    return (self.name,) + tuple(sorted(self.assumptions0.items()))
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/symbol.py", line 262, in assumptions0
    in self._assumptions.items() if value is not None)
  File "/w2scratch/home/t-banij/miniconda3/lib/python3.7/site-packages/sympy/core/symbol.py", line 261, in <genexpr>
    return dict((key, value) for key, value
RuntimeError: dictionary changed size during iteration
```

**Comment by asmeurer** [comment]
Do you mean *un*hashable default arguments?

**Comment by asmeurer** [comment]
I don't know much about how to achieve thread safety in Python. What is the correct way to fix this? Replacing the dictionary in question with a copy would presumably fix the problem, but would that just be a bandaid? 

The code in question is the core assumptions, so we have to be careful changing it so that it doesn't affect performance.

**Comment by oscarbenjamin** [comment]
I think in general this problem could happen with any Basic object. Any time `_assumptions` is iterated over in one thread while another thread queries an unchecked fact like is_positive or something then the dict could be modified even if just to insert None as the value for `positive`. That would then cause the iterating thread to error out as in the OP.

Actually I'm not sure how this happens for Symbol though. I think that for a Symbol the _assumptions dict should be fully populated by the time `__new__` finishes. What we really need is the stack trace from the other thread...

Looking here:
https://github.com/sympy/sympy/blob/22e948b53ffec8b247528436a290a5511a25f814/sympy/core/symbol.py#L250-L252
Every time a Symbol is compared with anything using == the assumptions0 dict is rebuilt by looping over the full assumptions dict and extracting the not None facts. This comes from #1162.

For a Symbol assumptions0 will never change so instead it could be computed once and stored on the instance here:
https://github.com/sympy/sympy/blob/22e948b53ffec8b247528436a290a5511a25f814/sympy/core/symbol.py#L235
Then the assumptions0 property method could return a copy of that computed dict which would be threadsafe.

**Comment by asmeurer** [comment]
That sounds like it could be more performant as well.

**Comment by rikardn** [comment]
I think I have encountered the same problem when using sympy in threads. The exception is raised when comparing two symbols. Using sympy 1.10.1

```
  File "/domus/h1/.virtualenvs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/statements.py", line 1792, in _lookup_last_assignment
    if statement.symbol == symbol:
  File "/domus/h1/.virtualenvs/r-reticulate/lib/python3.8/site-packages/sympy/core/basic.py", line 376, in __eq__
    a, b = self._hashable_content(), other._hashable_content()
  File "/domus/h1/.virtualenvs/r-reticulate/lib/python3.8/site-packages/sympy/core/symbol.py", line 337, in _hashable_content
    return (self.name,) + tuple(sorted(self.assumptions0.items()))
  File "/domus/h1/.virtualenvs/r-reticulate/lib/python3.8/site-packages/sympy/core/symbol.py", line 349, in assumptions0
    return {key: value for key, value
  File "/domus/h1/.virtualenvs/r-reticulate/lib/python3.8/site-packages/sympy/core/symbol.py", line 349, in <dictcomp>
    return {key: value for key, value
RuntimeError: dictionary changed size during iteration
```

**Comment by oscarbenjamin** [comment]
> The exception is raised when comparing two symbols. Using sympy 1.10.1

Have you tried 1.11.1 or master? I did make some changes to improve how the assumptions system works with threads in 1.11.1 (gh-22557) but it maybe doesn't help this case.

**Comment by rikardn** [comment]
Thanks for the info. This is an extremely rare event. We have run our program several hundred times without this issue showing up so it is very hard to reproduce.

If this is only a problem for symbols one idea would be to introduce an alternative symbol class that cannot carry any assumptions.

**Comment by oscarbenjamin** [comment]
Here is a simpler reproducer:
```python
import threading
import sympy
import time



def thread1():
    global x, y
    for n in range(10000):
        x, y = sympy.symbols(f'x{n}, y{n}')
        x.is_positive
    x = None
    print('finished thread1')

def thread2():
    while x is not None:
        x == y
    print('finished thread2')

thread = threading.Thread(target=thread1)
thread.start()
thread2()
thread.join()
```
With that I can reproduce the problem with master and the fix I suggested above does not work.

**Comment by oscarbenjamin** [comment]
> This diff seems to fix it:

Although it breaks other things because it doesn't return the same result.

**Comment by oscarbenjamin** [comment]
This is a better fix:
```diff
diff --git a/sympy/core/symbol.py b/sympy/core/symbol.py
index 7b69f2c..654bfb0 100644
--- a/sympy/core/symbol.py
+++ b/sympy/core/symbol.py
@@ -224,7 +224,7 @@ class Symbol(AtomicExpr, Boolean):
 
     is_comparable = False
 
-    __slots__ = ('name',)
+    __slots__ = ('name', '_assumptions0')
 
     name: str
 
@@ -293,6 +293,7 @@ def __new__(cls, name, **assumptions):
 
         """
         cls._sanitize(assumptions, cls)
+
         return Symbol.__xnew_cached_(cls, name, **assumptions)
 
     @staticmethod
@@ -300,24 +301,16 @@ def __xnew__(cls, name, **assumptions):  # never cached (e.g. dummy)
         if not isinstance(name, str):
             raise TypeError("name should be a string, not %s" % repr(type(name)))
 
+        # The only assumption set by default is commutative=True.
+        assumptions.setdefault('commutative', True)
+
+        assumptions_kb = StdFactKB(assumptions)
+
         obj = Expr.__new__(cls)
         obj.name = name
+        obj._assumptions = assumptions_kb
+        obj._assumptions0 = dict(assumptions_kb)
 
-        # TODO: Issue #8873: Forcing the commutative assumption here means
-        # later code such as ``srepr()`` cannot tell whether the user
-        # specified ``commutative=True`` or omitted it.  To workaround this,
-        # we keep a copy of the assumptions dict, then create the StdFactKB,
-        # and finally overwrite its ``._generator`` with the dict copy.  This
-        # is a bit of a hack because we assume StdFactKB merely copies the
-        # given dict as ``._generator``, but future modification might, e.g.,
-        # compute a minimal equivalent assumption set.
-        tmp_asm_copy = assumptions.copy()
-
-        # be strict about commutativity
-        is_commutative = fuzzy_bool(assumptions.get('commutative', True))
-        assumptions['commutative'] = is_commutative
-        obj._assumptions = StdFactKB(assumptions)
-        obj._assumptions._generator = tmp_asm_copy  # Issue #8873
         return obj
 
     @staticmethod
@@ -351,8 +344,7 @@ def _eval_refine(self, assumptions):
 
     @property
     def assumptions0(self):
-        return {key: value for key, value
-                in self._assumptions.items() if value is not None}
+        return self._assumptions0.copy()
 
     @cacheit
     def sort_key(self, order=None):
```

**Comment by rikardn** [comment]
Wow, nice reproduction and fix! I was looking in the wrong direction for symbols where assumptions were set at the same time as `__eq__`

**Comment by oscarbenjamin** [comment]
The problem is querying an assumption that is not set on the symbol e.g.:
```python
In [4]: x = symbols('x')

In [5]: x._assumptions
Out[5]: {'commutative': True}

In [6]: x.is_positive

In [7]: x._assumptions
Out[7]: {'commutative': True, 'positive': None}
```
It is the insertion of `'positive':None` in the dict that causes the other thread iterating over the dict to fail.

**Comment by oscarbenjamin** [comment]
I've opened gh-24882 with the fix.
