### ISSUE TITLE
UserWarning in experimental_lambdify and NameError ('Integral' is not defined) when plotting

### ISSUE THREAD

**Issue by rolandog** [sympy/sympy#16786]
Hi.

I'm working through some examples of uncertainty modeling that were published
in this [this article](http://conference.scipy.org/proceedings/scipy2012/pdfs/matthew_rocklin.pdf).

I'm getting both a warning and an error:

<details><summary>Warning Message:</summary>

Input
```
p2 = plot(P(y > yf, evaluate=False), (t, 4.5, 6.5))
```

Warning
```
C:\Users\rolandog\Anaconda3\lib\site-packages\sympy\plotting\experimental_lambdify.py:233: UserWarning: The evaluation of the expression is problematic. We are trying a failback method that may still work. Please report this as a bug.
  warnings.warn('The evaluation of the expression is'
```
</details>

<details><summary>Error Message:</summary>

Input
```
p2 = plot(P(y > yf), (t, 4.5, 6.5))
```

Error
```
Traceback (most recent call last):

  File "<ipython-input-23-33111916b890>", line 1, in <module>
    p2 = plot(P(y > yf), (t, 4.5, 6.5))

  File "C:\Users\rolandog\Anaconda3\lib\site-packages\sympy\plotting\plot.py", line 1365, in plot
    plots.show()

  File "C:\Users\rolandog\Anaconda3\lib\site-packages\sympy\plotting\plot.py", line 187, in show
    self._backend.show()

  File "C:\Users\rolandog\Anaconda3\lib\site-packages\sympy\plotting\plot.py", line 1072, in show
    self.process_series()

  File "C:\Users\rolandog\Anaconda3\lib\site-packages\sympy\plotting\plot.py", line 934, in process_series
    collection = self.LineCollection(s.get_segments())

  File "C:\Users\rolandog\Anaconda3\lib\site-packages\sympy\plotting\plot.py", line 533, in get_segments
    f_start = f(self.start)

  File "C:\Users\rolandog\Anaconda3\lib\site-packages\sympy\plotting\experimental_lambdify.py", line 232, in __call__
    result = self.lambda_func(args)

  File "C:\Users\rolandog\Anaconda3\lib\site-packages\sympy\plotting\experimental_lambdify.py", line 317, in __call__
    return self.lambda_func(*args, **kwargs)

  File "<string>", line 1, in <lambda>

NameError: name 'Integral' is not defined
```
</details>

<details><summary>Example code:</summary>

Here's much of the code from the paper; I'm still learning SymPy so I thought it would be best to learn from examples.

I decided to copy/transcribe the code into Spyder, and run it in a cell-by-cell basis.

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 30 20:51:47 2019

@author: rolandog
"""

# %% imports and setup

# for trigonometric symbolic equations
from sympy import (
        atan,      # arc tangent
        cos,       # cosine
        pi,        # 3.14159265358979
        sin,       # sine
        sqrt       # square root
        )

# symbolic functions
from sympy import (
        simplify,  # simplifies equations
        solve,     # find solutions to symbolic equations
        Symbol,    # "a" -> a
        symbols    # "a, b" -> a, b
        )

# helps setup printing unicode characters
from sympy import init_printing

# helps plot symbolic functions
from sympy.plotting import plot

# help model symbolic variables with statistical distributions (e.g. Normal)
from sympy.stats import (
        density,   # probability density function
        E,         # Expected value
        Normal,    # Normal distribution
        P,         # Probability
        std        # standard deviation
        )

# enable printing in unicode
init_printing(use_unicode=True)

# %% first example
# http://conference.scipy.org/proceedings/scipy2012/pdfs/matthew_rocklin.pdf

# inputs for first example
x0 = 0
y0 = 0
yf = -30  # target is 30 meters below
g = -10  # gravitational constant
v = 30  # m/s
theta = pi / 4  # 45°
t = Symbol("t", positive=True)  # SymPy variable for time, infer positive sols.
x = x0 + v * cos(theta) * t
y = y0 + v * sin(theta) * t + g * t ** 2 / 2

# solution for first example, an exact solution
impact_time_solutions = solve(y - yf, t)
impact_time = solve(y - yf, t)[0]  # choose a solution
xf = x0 + v * cos(theta) * impact_time

# plot x vs. y for t in (0, impact_time)
p0 = plot(x, y, (t, 0, impact_time))

# evaluate xf numerically
xf.evalf()

# %% redefining as symbolic

# inputs for second example
x0, y0, yf, g, v, theta = symbols("x_0, y_0, y_f, g, v, theta")
t = Symbol("t", positive=True)  # SymPy variable for time, infer positive sols.
x = x0 + v * cos(theta) * t
y = y0 + v * sin(theta) * t + g * t ** 2 / 2

# solution for second example
impact_time_solutions = solve(y - yf, t)
impact_time = solve(y - yf, t)[1]  # choose a solution
xf = x0 + v * cos(theta) * impact_time

xf

# %% third example, redefinition as normally distributed variables

# inputs for third example
v = Normal("v", 30, 1)  # normally distributed value, m/s

# third example calculations
pdf = density(v)
z = Symbol("z")
p1 = plot(pdf(z),
          (z,
           E(v) - 3 * std(v),
           E(v) + 3 * std(v)
           ))
simplify(P(v > 31))

# %% fourth example

# inputs for fourth example
x0, y0 = (0, 0)  # starting position
yf = -30  # target is 30 meters below
g = -10  # gravitational constant, m / s ** 2
t = Symbol("t", positive=True)  # SymPy variable for time, infer positive sols.
v = Normal("v", 30, 1)  # normally distributed value, m/s
theta = pi / 4  # 45°

# outputs fourth example
x = x0 + v * cos(theta) * t
y = y0 + v * sin(theta) * t + g * t ** 2 / 2

# pick largest solution, sorting by sampled expected value
impact_time = max(solve(y - yf, t),
                  key=lambda s: E(s, numsamples=1000))
xf = x0 + v * cos(theta) * impact_time

xf

# %% takes a *long* while, outputs long equation that benefits from simplify
# but it still contains a symbolic integral
simplify(E(impact_time))

# %% this hangs if it weren't for evaluate=False
E(impact_time, evaluate=False)

# %% approximation
E(impact_time, numsamples=10000)

# %% this warns about a bug; doesn't fail, but takes a long time

# C:\Users\rolandog\Anaconda3\lib\site-packages\sympy\plotting\experimental_lambdify.py:232:
# UserWarning: The evaluation of the expression is problematic. We are trying a
# failback method that may still work. Please report this as a bug.
#   warnings.warn('The evaluation of the expression is'

p2 = plot(P(y > yf, evaluate=False), (t, 4.5, 6.5))

# %% this fails after taking a lot of time
p2 = plot(P(y > yf), (t, 4.5, 6.5))

```
</details>

<details><summary>Software and package versions:</summary>

```
|------------|--------------------------|
| sympy      | 1.4                      |
| python     | 3.7.3                    |
| conda      | 4.6.14                   |
| anaconda   | custom-py37_0            |
| Spyder     | 3.3.3                    |
| OS Name    | Microsoft Windows 10 Pro |
| OS Version | 10.0.18362 Build 18362   |
|------------|--------------------------|
```
</details>

Any clues to what could be wrong?

**Comment by asmeurer** [comment]
I guess experimental_lambdify doesn't know to evalf the Integral object. We really should replace experimental_lambdify with regular lambdify, though presently it doesn't handle Integral either. See https://github.com/sympy/sympy/issues/4471
