### ISSUE TITLE
Substituting symbols with SparseMatrix in simple expressions raises ValueError

### ISSUE THREAD

**Issue by cuihantao** [sympy/sympy#16800]
I'm trying to substitute symbols in an expression with SparseMatrix. This issue was discussed earlier on Gitter @asmeurer . The following code reproduces the error:

```
a = smp.SparseMatrix([[1, 2], [3, 4]])
b = smp.Matrix([[1, 2], [3, 4]])
c, d = smp.symbols('c d')
(c + d).subs([(c, a), (d, b)], simultaneous=True)
Traceback (most recent call last):
  File "<input>", line 5, in <module>
  File "/home/hcui7/miniconda3/envs/dian/lib/python3.7/site-packages/sympy/core/basic.py", line 984, in subs
    d = Dummy(commutative=new.is_commutative)
  File "/home/hcui7/miniconda3/envs/dian/lib/python3.7/site-packages/sympy/core/symbol.py", line 343, in __new__
    cls._sanitize(assumptions, cls)
  File "/home/hcui7/miniconda3/envs/dian/lib/python3.7/site-packages/sympy/core/symbol.py", line 178, in _sanitize
    '%scommutativity must be True or False.' % whose)
ValueError: Dummy commutativity must be True or False.
```

If `c` and `d` are `MatrixSymbol` with the correct shape, `subs` works but `doit` gives an AttributeError
```
a = smp.SparseMatrix([[1, 2], [3, 4]])
b = smp.Matrix([[1, 2], [3, 4]])
c, d = MatrixSymbol('c', 2, 2), MatrixSymbol('d', 2, 2)
(c*d).subs([(c, a), (d, b)])
(c*d).subs([(c, a), (d, b)]).doit()
Traceback (most recent call last):
  File "<input>", line 5, in <module>
  File "/home/hcui7/miniconda3/envs/dian/lib/python3.7/site-packages/sympy/matrices/expressions/matmul.py", line 138, in doit
    expr = canonicalize(MatMul(*args))
  File "/home/hcui7/miniconda3/envs/dian/lib/python3.7/site-packages/sympy/strategies/core.py", line 11, in exhaustive_rl
    new, old = rule(expr), expr
  File "/home/hcui7/miniconda3/envs/dian/lib/python3.7/site-packages/sympy/strategies/core.py", line 95, in switch_rl
    return rl(expr)
  File "/home/hcui7/miniconda3/envs/dian/lib/python3.7/site-packages/sympy/strategies/core.py", line 85, in do_one_rl
    result = rl(expr)
  File "/home/hcui7/miniconda3/envs/dian/lib/python3.7/site-packages/sympy/matrices/expressions/matmul.py", line 190, in any_zeros
    for arg in mul.args]):
  File "/home/hcui7/miniconda3/envs/dian/lib/python3.7/site-packages/sympy/matrices/expressions/matmul.py", line 190, in <listcomp>
    for arg in mul.args]):
  File "/home/hcui7/miniconda3/envs/dian/lib/python3.7/site-packages/sympy/matrices/matrices.py", line 2141, in __getattr__
    "%s has no attribute %s." % (self.__class__.__name__, attr))
AttributeError: ImmutableSparseMatrix has no attribute is_ZeroMatrix.
```

**Comment by asmeurer** [comment]
c and d really should be set to commutative=False, although this doesn't fix this issue. 

Also, it probably ought to work with `MatrixSymbol('a', n, n)`. Otherwise, to handle matrices with generic shape, you have to first substitute the shape `n` and then substitute the matrices.

**Comment by cuihantao** [comment]
> Otherwise, to handle matrices with generic shape, you have to first substitute the shape `n` and then substitute the matrices

How could I substitute the shape `n` of a matrix symbol? I tried to look it up in the documentation but couldn't find it.

**Comment by asmeurer** [comment]
I mean `expr.subs(n, 2)`.
