### ISSUE TITLE
MatrixExpr.from_index_summation 

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#16860]
```python3
>>> from sympy import *

>>> k = Symbol('k', integer=True)
>>> a, b = symbols('a, b')
>>> A = MatrixSymbol('A', k, k)

>>> expr = Sum(A[a, a], (a, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
Trace(A)

>>> expr = Sum(A[a, a], (a, 0, k-1), (b, 0, 1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
Trace(A)
```

Both are giving `Trace(A)`, however, should the latter one give `2*Trace(A)`?

**Comment by smichr** [comment]
> should the latter one give `2*Trace(A)`?

I think so,
```python
>>> Sum(x,(y,0,1)).doit()
2*x
```

**Comment by sylee957** [comment]
Some things in the example section are not correct.
For example, I think the summation should be a MatrixElement of a MatMul, than MatMul

```python3
>>> from sympy import *
>>> from sympy.matrices.expressions.matexpr import MatrixElement
>>> from sympy.abc import i, j, k, N

>>> A = MatrixSymbol("A", N, N)
>>> B = MatrixSymbol("B", N, N)

>>> expr = Sum(A[i, j]*B[j, k], (j, 0, N-1))
>>> MatrixExpr.from_index_summation(expr)
A*B

>>> MatMul(A, B)[i, k]
Sum(A[i, _i_1]*B[_i_1, k], (_i_1, 0, N - 1))
```

**Comment by solus9** [comment]
Hi @sylee957,
I have gone through the code and there is this thing I wanna ask that what if it's like this
```
>>> k = Symbol('k', integer=True)
>>> A = MatrixSymbol('A', k, k)
>>> a,b = symbols('a, b')
>>> expr = Sum(A[a,a], (b, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
A  
```
shouldn't it raise an error as range of `a` is not defined here
and another thing is that are we applying the operation on the matrix in order, I mean
```
Sum(A[a, a], (a, 0, k-1), (b, 0, k-1))
Sum(A[a, a], (b, 0, k-1), (a, 0, k-1))
```
assuming the correct answer that is 2*Trace(A), are the above two commands should give the same answer or the second one should raise an error?
Thank you for your time

**Comment by solus9** [comment]
Hi @sylee957 ,
I have made some changes to the code base,
```
>>> from sympy import *
>>> k = Symbol('k', integer=True)
>>> a, b = symbols('a, b')
>>> A = MatrixSymbol('A', k, k)

>>> expr = Sum(A[a, a], (a, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
Trace(A)

>>> expr = Sum(A[a, a], (a, 0, k-1), (b, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
k*Trace(A)

>>> expr = Sum(A[a, a], (b, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
k*Tracea[a, a]
```

I will be making a PR for this, please let me know if this thing needs any change, we can make further changes in the PR

**Comment by sylee957** [comment]
@solus9 
I think your third example should be
```python
>>> expr = Sum(A[a, a], (b, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
k*A[a, a]
```
But things can be further improved on if you open up a PR

**Comment by solus9** [comment]
```
>>> from sympy import *
>>> k = Symbol('k', integer=True)
>>> a, b = symbols('a, b')
>>> A = MatrixSymbol('A', k, k)
```
```
>>> expr = Sum(A[a, a], (a, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
Trace(A)
```
```
>>> expr = Sum(A[a, a], (a, 0, k-1), (b, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
k*Trace(A)
```
```
>>> expr = Sum(A[a, a], (b, 0, k-1))
>>> expr = MatrixExpr.from_index_summation(expr)
>>> print(expr)
k*A[a, a]
```
Sorry there must be some mistake in copy pasting the result

**Comment by Upabjojr** [comment]
There is a method in `sympy/codegen/array_utils.py` which is supposed to replace this one.

**Comment by czgdp1807** [comment]
@Upabjojr Can we open a new issue for the same and close this one as this is outdated?

**Comment by asmeurer** [comment]
Until from_index_summation is changed to use the new algorithm, this issue is valid. 

It looks like it has issues with this expression, although that's better than giving a wrong result

```py
>>> from sympy.codegen.array_utils import parse_indexed_expression
>>> expr = Sum(A[a, a], (a, 0, k-1))
>>> parse_indexed_expression(expr)
CodegenArrayContraction(A, (0, 1))
>>> expr = Sum(A[a, a], (a, 0, k-1), (b, 0, 1))
>>> parse_indexed_expression(expr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/codegen/array_utils.py", line 1104, in parse_indexed_expression
    result, indices = _codegen_array_parse(expr)
  File "./sympy/codegen/array_utils.py", line 926, in _codegen_array_parse
    i = _get_argindex(subindices, ind)
  File "./sympy/codegen/array_utils.py", line 914, in _get_argindex
    raise IndexError("%s not found in %s" % (ind, subindices))
IndexError: b not found in (a,)
```

**Comment by asmeurer** [comment]
But bugs notwithstanding, it looks like `Matrix.from_index_summation(expr)` should be replaced with `recognize_matrix_expression(parse_indexed_expression(expr))`.

**Comment by Upabjojr** [comment]
Yes, the code in `sympy.codegen.array_utils` is much more robust. I'm not sure whether all unit tests will pass, it may need some more fixes.
