### ISSUE TITLE
Which is the easiest way to replicate the previous behaviour of the Symbol?

### ISSUE THREAD

**Issue by loumalouomega** [sympy/sympy#16928]
Since Sympy 1.3:

https://github.com/sympy/sympy/wiki/Release-Notes-for-1.3

> Symbols no longer automatically convert to functions when called, e.g., if f = Symbol('f'), f(t) is now a TypeError. To create a function, use f = Function('f') or f = symbols('f', cls=Function).

Which would be the easiest way to replicate the same behavior?, or something similar. I want to operate the functions as symbols, for example define a matrix of functions and be able to multiple them.

**Comment by czgdp1807** [comment]
Can you please show the code where this problem is arising in your repository?

**Comment by loumalouomega** [comment]
For example, in order to define a dependency:

~~~py
from sympy import *

a = Symbol("a")
b = Symbol("b")

# A depends on b
list_dependency = [b]
a = a(*list_dependency) 

# Now a depends on b, so I I derive in a symbolic way:
dadb = diff(a, b)

print(dadb)
~~~

Result with 1.2:

~~~sh
Derivative(a(b), b)
~~~

With 1.3:

~~~
Traceback:
TypeError: 'Symbol' object is not callable
~~~

**Comment by czgdp1807** [comment]
So, you are using `Symbol` as `Function` wherever necessary. Then you can define `FSymbol` and make replacement of `Symbol` with `FSymbol` in your code wherever required. As `Function` and `Symbol` are different things in `SymPy`, this is the only way from my point of view. 
If your code doesn't contain much of such cases, where `Symbol` is used as `Function` you can go for it or otherwise wait for someone more experienced to suggest another easier method.

**Comment by loumalouomega** [comment]
I will try, thanks for the fast reply

**Comment by oscarbenjamin** [comment]
I don't understand the problem. The example given works fine if you write `a = Function('a')`.

In general it is a problem that SymPy doesn't have higher-order functions. It would be nice to be able to do something like `expr.subs(f, cos)` but it isn't possible (and would be hard to implement).

**Comment by loumalouomega** [comment]
The thing is that a function can not be operated as a symbol, imagine that I have a matrix with symbols as components, I can multiply them, but with Functions I cannot

**Comment by oscarbenjamin** [comment]
Can you give a short example of something that doesn't work?

**Comment by czgdp1807** [comment]
@oscarbenjamin please take a look at https://github.com/sympy/sympy/issues/16928#issuecomment-497360248.

**Comment by czgdp1807** [comment]
Ah! Mistook your point. Yes, @loumalouomega please provide an example where function don't work the way you want them too. Like Matrix of functions. What error exactly is thrown?

**Comment by loumalouomega** [comment]
This is the example to show the problem with using Function instead of Symbol:

~~~py
from sympy import *

a = Symbol("a")

matrix_a = Matrix([[a,2*a],[2*a,a]])
matrix_2a = Matrix([[2*a,4*a],[4*a,2*a]])

print(matrix_a * matrix_2a)

b = Function("b")

matrix_b = Matrix([[b,2*b],[2*b,b]])
matrix_2b = Matrix([[2*b,4*b],[4*b,2*b]])

print(matrix_b * matrix_2b)
~~~

Result:

~~~sh
Matrix([[10*a**2, 8*a**2], [8*a**2, 10*a**2]])
Traceback (most recent call last):
  File "test_sympy.py", line 12, in <module>
    matrix_b = Matrix([[b,2*b],[2*b,b]])
TypeError: unsupported operand type(s) for *: 'int' and 'UndefinedFunction'
~~~

**Comment by czgdp1807** [comment]
As far as I can figure out, `2*b` isn't supported when `b`is a function. @oscarbenjamin Should we support this?

**Comment by loumalouomega** [comment]
FSymbol is not defined BTW

**Comment by czgdp1807** [comment]
I suggested to make a class of your own and define the `__call__` in it. `FSymbol` is just a suggested a name for that class. Inherit, `Symbol` in `FSymbol`.

**Comment by loumalouomega** [comment]
Understood :+1: I will try

**Comment by oscarbenjamin** [comment]
You need to show a complete example. The new example works just fine if you declare b as either
```
b = Symbol('b')
b = Function('b')(a)
```
I'm not sure what it is you want in your actual problem because both examples are reduced just a little too much.

Please understand that we know that `2*f` doesn't work. Changing it so that symbols are not implicitly functions was a *deliberate* decision (#9064). I am trying to work out how you can solve your actual problem or whether there is something that should be changed in SymPy. I can't do that without a good demonstration of the problem though.

**Comment by loumalouomega** [comment]
> You need to show a complete example. The new example works just fine if you declare b as either
> 
> ```
> b = Symbol('b')
> b = Function('b')(a)
> ```
> 
> I'm not sure what it is you want in your actual problem because both examples are reduced just a little too much.
> 
> Please understand that we know that `2*f` doesn't work. Changing it so that symbols are not implicitly functions was a _deliberate_ decision (#9064). I am trying to work out how you can solve your actual problem or whether there is something that should be changed in SymPy. I can't do that without a good demonstration of the problem though.

Sorry If I simplified to much, I am a developer too, and I am use to work with simple cases to focus on the actual problem. Look at the case I post previously

**Comment by loumalouomega** [comment]
> This is the example to show the problem with using Function instead of Symbol:
> 
> ```python
> from sympy import *
> 
> a = Symbol("a")
> 
> matrix_a = Matrix([[a,2*a],[2*a,a]])
> matrix_2a = Matrix([[2*a,4*a],[4*a,2*a]])
> 
> print(matrix_a * matrix_2a)
> 
> b = Function("b")
> 
> matrix_b = Matrix([[b,2*b],[2*b,b]])
> matrix_2b = Matrix([[2*b,4*b],[4*b,2*b]])
> 
> print(matrix_b * matrix_2b)
> ```
> 
> Result:
> 
> ```shell
> Matrix([[10*a**2, 8*a**2], [8*a**2, 10*a**2]])
> Traceback (most recent call last):
>   File "test_sympy.py", line 12, in <module>
>     matrix_b = Matrix([[b,2*b],[2*b,b]])
> TypeError: unsupported operand type(s) for *: 'int' and 'UndefinedFunction'
> ```

@oscarbenjamin this one doesn't work for the functions

**Comment by oscarbenjamin** [comment]
The change in SymPy means that you need to choose between using

1. Symbol: `b = Symbol('b')`
2. Function: `b = Function('b')`
3. Applied function: `b = Function('b')(a)`

That example may not work with b a Function but it does with b a Symbol so just use Symbol (or an applied function).

If that answer doesn't work for your real problem then the example doesn't demonstrate the problem.

**Comment by loumalouomega** [comment]
> The change in SymPy means that you need to choose between using
> 
>     1. Symbol: `b = Symbol('b')`
> 
>     2. Function: `b = Function('b')`
> 
>     3. Applied function: `b = Function('b')(a)`
> 
> 
> That example may not work with b a Function but it does with b a Symbol so just use Symbol (or an applied function).
> 
> If that answer doesn't work for your real problem then the example doesn't demonstrate the problem.

I understand, but the issue comes from my previous comment, where I cannot use the Function for operations in the same way I can do with the Symbol (sum, multiplication, etc...). With the previous Symbol I was able to use the Symbol as a Function and operate with it, this is my problem

**Comment by oscarbenjamin** [comment]
> I cannot use the Function for operations

You can use an applied function for operations:
```julia
In [53]: a, b, c, d = symbols('a, b, c, d', cls=Function)                                                                         

In [54]: M = Matrix([[a(x), b(x)], [c(x), d(x)]])                                                                                 

In [55]: M                                                                                                                        
Out[55]: 
⎡a(x)  b(x)⎤
⎢          ⎥
⎣c(x)  d(x)⎦

In [56]: M.det()                                                                                                                  
Out[56]: a(x)⋅d(x) - b(x)⋅c(x)

In [57]: M.det().diff(x)                                                                                                          
Out[57]: 
     d               d               d               d       
a(x)⋅──(d(x)) - b(x)⋅──(c(x)) - c(x)⋅──(b(x)) + d(x)⋅──(a(x))
     dx              dx              dx              dx 
```

**Comment by loumalouomega** [comment]
OK, I will try (but I think I tried this and it did not work)

**Comment by RiccardoRossi** [comment]
Hello, i think i understand what @loumalouomega is tryinh to achieve. The point is that for finite element computations we have an expression that looks like the following

~~~py
B = Matrix([[B11,B12],[B21,B22]]) #here all the Bij are symbols
S = Vector([S1,S2])

f = B*S
~~~

this f represents the "internal forces" of a Finite Element calculation.
The point is that, in extreme simplification, both B and S are functions of a vector $u=Vector([u1,u2])$

so that

~~~py
f(u1,u2) = B(u1,u2)*S(u1,u2)
~~~

The exact expression of S(u1,u2), nevertheless we know that diff(S,U) defines a symmetric matrix C (which we can leave indicated). That is, every time we find diff(Si,uj) we can replace it by a symbol $Cij$
This would represent a Constitutive Law that comes as a black box, with the C given and with the s given.

**Comment by loumalouomega** [comment]
> ```julia
> = symbols('a, b, c, d', cls=Function)     
> ```

If I use symbols I get the following when multiplying matrices:

~~~sh
Traceback (most recent call last):
  File "/home/vicente/.local/lib/python3.7/site-packages/sympy/matrices/dense.py", line 193, in _eval_matrix_mul
    new_mat[i] = Add(*vec)
  File "/home/vicente/.local/lib/python3.7/site-packages/sympy/matrices/dense.py", line 191, in <genexpr>
    vec = (mat[a]*other_mat[b] for a,b in zip(row_indices, col_indices))
TypeError: unsupported operand type(s) for *: 'UndefinedFunction' and 'UndefinedFunction'
~~~

**Comment by loumalouomega** [comment]
But here it works:

https://live.sympy.org/

![imagen](https://user-images.githubusercontent.com/19991680/58689279-db52be00-8386-11e9-9f9d-2993ca8f7107.png)

**Comment by loumalouomega** [comment]
I am seeing this works on 1.2:

~~~py
from sympy import *
x, y =  symbols("x, y", cls=Function)
variable_list = [x, y]
a, b, c, d = symbols('a, b, c, d', cls=Function)
M = Matrix([[a(*variable_list), b(*variable_list)], [c(*variable_list), d(*variable_list)]])
print(M*M)
~~~

Result:

~~~sh
Matrix([[a(x, y)**2 + b(x, y)*c(x, y), a(x, y)*b(x, y) + b(x, y)*d(x, y)], [a(x, y)*c(x, y) + c(x, y)*d(x, y), b(x, y)*c(x, y) + d(x, y)**2]])
~~~

Maybe there is something wrong on my scripts

**Comment by loumalouomega** [comment]
Ok, I think I found the reason of my errors. I need to define the degrees of freedom of my system (do not depend of anything else) as symbols, and the rest as functions. I will try and I will tell

**Comment by smichr** [comment]
> It would be nice to be able to do something like `expr.subs(f, cos)` but it isn't possible

Do you mean like this?
```
>>> f(x).subs(f, cos)
cos(x)
```

**Comment by smichr** [comment]
Does this work?
```python
>>> class my(Symbol):
...     def __mul__(self, other):
...         return Function(self.name)(other)
>>> f=my('f')
>>> f*2
f(2)
```

**Comment by loumalouomega** [comment]
> Ok, I think I found the reason of my errors. I need to define the degrees of freedom of my system (do not depend of anything else) as symbols, and the rest as functions. I will try and I will tell

Still some problems related with diff and other operations
