### ISSUE TITLE
Test failures in Python 3.8 beta

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#16977]
In addition to the syntax warnings (https://github.com/sympy/sympy/issues/16973), there are some test failures in the Python 3.8 beta. I did not investigate them.

```
__________________________________________________________________________________ sympy/printing/tests/test_mathml.py:test_print_intervals ___________________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_mathml.py", line 961, in test_print_intervals
    assert mpp.doprint(Interval(0, a)) == \
AssertionError
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
_____________________________________________________________________________________ sympy/printing/tests/test_mathml.py:test_print_Abs ______________________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_mathml.py", line 1000, in test_print_Abs
    assert mpp.doprint(Abs(x)) == \
AssertionError
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
_________________________________________________________________________________ sympy/printing/tests/test_mathml.py:test_print_Determinant __________________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_mathml.py", line 1007, in test_print_Determinant
    assert mpp.doprint(Determinant(Matrix([[1, 2], [3, 4]]))) == \
AssertionError
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
__________________________________________________________________________________ sympy/printing/tests/test_mathml.py:test_mat_delim_print ___________________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_mathml.py", line 1073, in test_mat_delim_print
    assert mathml(expr, printer='presentation', mat_delim='[') == \
AssertionError
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
________________________________________________________________________________ sympy/printing/tests/test_mathml.py:test_print_set_frozenset _________________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_mathml.py", line 1123, in test_print_set_frozenset
    assert mpp.doprint(f) == \
AssertionError
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
__________________________________________________________________________________ sympy/printing/tests/test_mathml.py:test_print_FiniteSet ___________________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_mathml.py", line 1132, in test_print_FiniteSet
    assert mpp.doprint(f1) == \
AssertionError
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
____________________________________________________________________________________ sympy/printing/tests/test_mathml.py:test_print_SetOp _____________________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_mathml.py", line 1148, in test_print_SetOp
    assert mpp.doprint(Union(f1, f2, evaluate=False)) == \
AssertionError
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
____________________________________________________________________________________ sympy/printing/tests/test_mathml.py:test_print_floor _____________________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_mathml.py", line 1251, in test_print_floor
    assert mathml(expr, printer='presentation') == \
AssertionError
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
___________________________________________________________________________________ sympy/printing/tests/test_mathml.py:test_print_ceiling ____________________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_mathml.py", line 1257, in test_print_ceiling
    assert mathml(expr, printer='presentation') == \
AssertionError
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
_________________________________________________________________________________ sympy/printing/tests/test_mathml.py:test_print_AccumBounds __________________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_mathml.py", line 1281, in test_print_AccumBounds
    assert mpp.doprint(AccumBounds(0, 1)) == '<mfenced close="&#10217;" open="&#10216;"><mn>0</mn><mn>1</mn></mfenced>'
AssertionError
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
____________________________________________________________________________________ sympy/printing/tests/test_mathml.py:test_mathml_Range ____________________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_mathml.py", line 1318, in test_mathml_Range
    assert mpp.doprint(Range(1, 51)) == \
AssertionError
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
________________________________________________________________________________ sympy/printing/tests/test_mathml.py:test_print_MatrixElement _________________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_mathml.py", line 1449, in test_print_MatrixElement
    assert mathml(A[0,0],printer = 'presentation') == \
AssertionError
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
_____________________________________________________________________________ sympy/printing/tests/test_mathml.py:test_mathml_SingularityFunction _____________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_mathml.py", line 1674, in test_mathml_SingularityFunction
    assert mathml(SingularityFunction(x, 4, 5), printer='presentation') == \
AssertionError
```

Also some doctests and examples fail with

```
_____________________________________________________________________ /home/aaronmeurer/Documents/python/sympy/sympy/examples/advanced/pyglet_plotting.py _____________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/cpython/Lib/doctest.py", line 208, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
  File "/home/aaronmeurer/Documents/python/sympy/sympy/examples/advanced/pyglet_plotting.py", line 14, in <module>
    from time import sleep, clock
ImportError: cannot import name 'clock' from 'time' (unknown location)
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
________________________________________________________________________ /home/aaronmeurer/Documents/python/sympy/sympy/examples/advanced/pidigits.py _________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/cpython/Lib/doctest.py", line 208, in _normalize_module
    return __import__(module, globals(), locals(), ["*"])
  File "/home/aaronmeurer/Documents/python/sympy/sympy/examples/advanced/pidigits.py", line 12, in <module>
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)
```

```
Traceback (most recent call last):
  File "examples/all.py", line 167, in run_example
    mod = load_example_module(example)
  File "examples/all.py", line 119, in load_example_module
    mod = __import__(example)
  File "examples/all.py", line 110, in __import__
    return imp.load_module(module_name, fp, pathname, description)
  File "/home/aaronmeurer/Documents/cpython/Lib/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/aaronmeurer/Documents/cpython/Lib/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 778, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "examples/advanced/pidigits.py", line 12, in <module>
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)
```

The clock thing might be related to the fact that I'm running Python from a git build.

**Comment by asmeurer** [comment]
Here's the header:

```
===================================================================================================== test process starts =====================================================================================================
executable:         /home/aaronmeurer/Documents/cpython/python  (3.8.0-beta-1) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              None
random seed:        56677615
hash randomization: on (PYTHONHASHSEED=389278493)
```

**Comment by tirkarthi** [comment]
`time.clock` was removed in https://github.com/python/cpython/pull/13270

**Comment by bjodah** [comment]
I think a viable work around for clock would e.g. be:
```
try:
    from time import clock
except ImportError:
    from time import perf_counter as clock
```
perhaps this should go into `sympy.core.compatibility`?

**Comment by vighneshq** [comment]
[Documentation](https://docs.python.org/3.8/library/xml.dom.minidom.html#xml.dom.minidom.Node.toxml)  for ``` Node.toxml()``` in Python 3.8, 
> Changed in version 3.8: The toxml() method now preserves the attribute order specified by the user. 

The expected output in the tests has the attributes arranged alphabetically which was the case in Python 3.7 and earlier.

**Comment by vighneshq** [comment]
Is it okay If I take this up?

**Comment by oscarbenjamin** [comment]
Yes absolutely. Thanks!

**Comment by tirkarthi** [comment]
> The expected output in the tests has the attributes arranged alphabetically which was the case in Python 3.7 and earlier.

This could be due to https://bugs.python.org/issue34160 . From Python 3.8 and above canonicalization was added in https://github.com/python/cpython/pull/12966 which can be used for xml comparison.

**Comment by asmeurer** [comment]
Does the attribute order matter? I think we can just sort them ourselves.

**Comment by vighneshq** [comment]
@asmeurer  In the pull request, that I what I did. Manually sorted the attributes before insertion.

**Comment by asmeurer** [comment]
A warning in the doctests wasn't fixed. 

```
<doctest sympy.core.singleton.SingletonRegistry[3]>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  0 is S.Zero
```

We should also figure out how to make these warnings result in a failure in the doctester.

**Comment by vighneshq** [comment]
@asmeurer Which command was it that lead to this warning being displayed?

**Comment by oscarbenjamin** [comment]
It comes from a doctest. You can run all doctests with
```
>>> import sympy
>>> sympy.doctest()
```
That runs *all* the doctests though. We can narrow it down from the warning message using grep:
```console
$ git grep ' 0 is S.Zero'
sympy/core/singleton.py:    >>> 0 is S.Zero
```
You can run only doctests from that file with `sympy.doctest('singleton.py')`.

**Comment by vighneshq** [comment]
I see. 
I am assuming on Travis, the doctests are being run using the shell script test_travis.sh using,
```
if [[ "${TEST_DOCTESTS}" == "true" ]]; then
    # -We:invalid makes invalid escape sequences error in Python 3.6. See
    # -#12028.
    cat << EOF | python -We:invalid
print('Testing DOCTESTS')
import sympy
if not sympy.doctest():
    raise Exception('Tests failed')
EOF
    cd ..
    bin/doctest doc/
fi
```
Just like adding ``` -We::SyntaxWarning ``` in .travis.yml fixed the issue with comparisons in the code, I think adding the warning here should fix that as well.

**Comment by oscarbenjamin** [comment]
That sounds like it should work

**Comment by asmeurer** [comment]
The code in the doctests is compiled somewhere in the doctest module. We should be able to just change the warning to an exception in the module before that happens. The code may need to catch the exception so that it doesn't crash the doctester when it happens.
