### ISSUE TITLE
Summing matrix powers doesn't work

### ISSUE THREAD

**Issue by exap** [sympy/sympy#16989]
This example raises an exception:

```
>>> A = Matrix([ [0,1,0], [-1,0,0], [0,0,0] ])
>>> n = symbols("n")
>>> summation(A**n, (n, 1, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/sympy/concrete/summations.py", line 847, in summation
    return Sum(f, *symbols, **kwargs).doit(deep=False)
  File "/usr/lib/python3.7/site-packages/sympy/concrete/summations.py", line 184, in doit
    return self.expand().doit()
  File "/usr/lib/python3.7/site-packages/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/sympy/core/expr.py", line 3191, in expand
    expr, hit = Expr._expand_hint(expr, hint, deep=deep, **hints)
  File "/usr/lib/python3.7/site-packages/sympy/core/expr.py", line 3132, in _expand_hint
    newexpr = getattr(expr, hint)(**hints)
  File "/usr/lib/python3.7/site-packages/sympy/concrete/expr_with_limits.py", line 407, in _eval_expand_basic
    [self.func(i, *self.limits) for i in summand._mat])
AttributeError: 'MatPow' object has no attribute '_mat'
```

This example just never returns:

```
>>> B = Matrix([ [1/2, 1/2, 0,0], [1/2, 0, 1/2, 0], [1/2, 0,0,1/2], [0,0,0,1] ])
>>> n = symbols("n")
>>> summation(B**n, (n, 1, 1))
```

I'm using Sympy 1.4 with Python 3.

**Comment by vighneshq** [comment]
The two other classes which define the property ``` _mat ``` are  ``` ImmutableDenseMatrix ``` and ``` SparseMatrix ``` where it returns the matrix elements as list. Adding a similar property to MatPow solves the problem.

For the second part, the problem seems to be in the expression ``` B**n ```

**Comment by oscarbenjamin** [comment]
Looks like it hangs in jordan_form:
```julia
In [33]: B = Matrix([ [S(1)/2, S(1)/2, 0,0], [S(1)/2, 0, S(1)/2, 0], [S(1)/2, 0,0,S(1)/2], [0,0,0,1] ])                           

In [34]: B.jordan_form() # Hangs...
```

**Comment by oscarbenjamin** [comment]
The hangs because this hangs:
```python
M = Matrix([[S(1)/3 - (-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3) - 1/(9*(-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3)),                                                                                                                  S(1)/2,                                                                                                                    0,                                                                                                                   0],
[                                                                                                                S(1)/2, -S(1)/6 - (-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3) - 1/(9*(-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3)),                                                                                                                  1/2,                                                                                                                   0],
[                                                                                                                1/2,                                                                                                                    0, -S(1)/6 - (-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3) - 1/(9*(-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3)),                                                                                                                 S(1)/2],
[                                                                                                                  0,                                                                                                                    0,                                                                                                                    0, S(5)/6 - (-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3) - 1/(9*(-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3))]])
M.nullspace() # Hangs...
```

**Comment by sidhantnagpal** [comment]
> The hangs because this hangs:
> 
> ```python
> M = Matrix([[S(1)/3 - (-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3) - 1/(9*(-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3)),                                                                                                                  S(1)/2,                                                                                                                    0,                                                                                                                   0],
> [                                                                                                                S(1)/2, -S(1)/6 - (-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3) - 1/(9*(-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3)),                                                                                                                  1/2,                                                                                                                   0],
> [                                                                                                                1/2,                                                                                                                    0, -S(1)/6 - (-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3) - 1/(9*(-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3)),                                                                                                                 S(1)/2],
> [                                                                                                                  0,                                                                                                                    0,                                                                                                                    0, S(5)/6 - (-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3) - 1/(9*(-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1)/3))]])
> M.nullspace() # Hangs...
> ```

`M.nullspace()` hangs due to `M.rref()` which in turn gets stuck in `_find_reasonable_pivot` (For sanity, I replaced float entries in the above matrix to sympy rationals):

```py
In [16]: from sympy.matrices.matrices import _find_reasonable_pivot             

In [17]: m = [(-S(1)/3 - (-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1
    ...: )/3)/2 - 1/(2*(-S(9)/2 + 9*sqrt(3)*I/2)*(sqrt(33)/72 + S(19)/216)**(S(1
    ...: )/3)))*(-sqrt(33)*(3*sqrt(33) + 19)**(S(1)/3) - 5*(3*sqrt(33) + 19)**(S
    ...: (1)/3) - 2*sqrt(33) - 2 + (3*sqrt(33) + 19)**(S(2)/3) + sqrt(3)*I*(3*sq
    ...: rt(33) + 19)**(S(2)/3) + 5*sqrt(3)*I*(3*sqrt(33) + 19)**(S(1)/3) + 3*sq
    ...: rt(11)*I*(3*sqrt(33) + 19)**(S(1)/3))/(12*(1 + sqrt(3)*I)*(3*sqrt(33) +
    ...:  19)**(S(2)/3)) - (-S(1)/6 + 1/(2*(-S(9)/2 + 9*sqrt(3)*I/2)*(sqrt(33)/7
    ...: 2 + S(19)/216)**(S(1)/3)) + (-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(19
    ...: )/216)**(S(1)/3)/2)*(S(1)/12 + 1/(2*(-S(9)/2 + 9*sqrt(3)*I/2)*(sqrt(33)
    ...: /72 + S(19)/216)**(S(1)/3)) + (-S(1)/2 + sqrt(3)*I/2)*(sqrt(33)/72 + S(
    ...: 19)/216)**(S(1)/3)/2), 0]                                              

In [18]: _find_reasonable_pivot(m) # hangs
```

**Comment by oscargus** [comment]
I have not analyzed the flow (or read the code, writing from my phone...), but there seems so be a scope for checking if the `summation` is over a single term and in that case just do a `subs`... Not that it will solve the actual problem but at least avoid it sometimes...

**Comment by sylee957** [comment]
Actually, the attribute error matter is a different nature and may be fixed in #17241.
Though I see it may need some real algorithms to solve matrix summations in general.

**Comment by oscarbenjamin** [comment]
Also I think it would be good if Sum could refine the summand based on assumptions on n e.g. with #17241 the example from the OP here works if the symbol is declared nonnegative:
```julia
In [44]: A = Matrix([ [0,1,0], [-1,0,0], [0,0,0] ])                             

In [45]: A**Symbol('n')                                                         
Out[45]: 
            n
⎛⎡0   1  0⎤⎞ 
⎜⎢        ⎥⎟ 
⎜⎢-1  0  0⎥⎟ 
⎜⎢        ⎥⎟ 
⎝⎣0   0  0⎦⎠ 

In [46]: n = Symbol('n', nonnegative=True)                                      

In [47]: A**n                                                                   
Out[47]: 
⎡   n       n         n         n    ⎤
⎢  ⅈ    (-ⅈ)       ⅈ⋅ⅈ    ⅈ⋅(-ⅈ)     ⎥
⎢  ── + ─────    - ──── + ───────  0 ⎥
⎢  2      2         2        2       ⎥
⎢                                    ⎥
⎢   n         n      n       n       ⎥
⎢ⅈ⋅ⅈ    ⅈ⋅(-ⅈ)      ⅈ    (-ⅈ)        ⎥
⎢──── - ───────     ── + ─────     0 ⎥
⎢ 2        2        2      2         ⎥
⎢                                    ⎥
⎢                                   n⎥
⎣      0                0          0 ⎦

In [48]: summation(A**n, (n, 1, 1))                                             
Out[48]: 
⎡0   1  0⎤
⎢        ⎥
⎢-1  0  0⎥
⎢        ⎥
⎣0   0  0⎦
```

**Comment by sylee957** [comment]
Before anything new implemented in sympy summation module, I see this workaround can be fine for finite summations

```python
>>> from sympy import *
>>> A = Matrix([[0, 1, 0], [-1, 0, 0], [0, 0, 0]])
>>> sum((A**n for n in range(1, 2)), ZeroMatrix(3, 3))
Matrix([
[ 0, 1, 0],
[-1, 0, 0],
[ 0, 0, 0]])
>>> sum((A**n for n in range(1, 3)), ZeroMatrix(3, 3))
Matrix([
[-1,  1, 0],
[-1, -1, 0],
[ 0,  0, 0]])
```
Note that additional parenthesis and zero specification should be specified for this.

**Comment by sylee957** [comment]
If computing symbolic matrix power hangs in many cases, what about making symbolic exponents simply return unevaluated `MatPow`, rather than trying to compute?

The reason why 
```python3
A = Matrix([[0, 1, 0], [-1, 0, 0], [0, 0, 0]])
n = Symbol('n')

A ** n
```
returns MatPow, is that it is not an invertible matrix. And it seems like every invertible matrices are attempting to compute full jordan power.
And for implementing the matrix geometric series or such, I think that having already evaluated jordan power expression would be more of bottleneck.
For consistency issues, I can say that it can even be more consistent with scalar integer powers, such as `2**n`

**Comment by oscarbenjamin** [comment]
There should be both a way to create an unevaluated power and a way to evaluate the power. Currently there is and you can use doit to evaluate:
```
MatPow(M, n)  # Don't evaluate
MatPow(M, n).doit()  # Force evaluation afterwards
M**n   # Always evaluates if possible
```
This is analogous to other things like Derivative/diff, Integral/integrate, Subs/subs etc.

Usually `a**b` evaluates as far as possible. I guess this is a potentially more expensive case though.

**Comment by asmeurer** [comment]
> Usually `a**b` evaluates as far as possible. I guess this is a potentially more expensive case though.

I'd say it only does cheap evaluation. We have expand_power_* and powsimp to do full simplification. A more similar analogy for expressions might be powers of integers that create large numbers (like `10**100**10`), which currently evaluate, but it would be better if they didn't. 

See also https://github.com/sympy/sympy/wiki/Automatic-Simplification

**Comment by oscarbenjamin** [comment]
Okay so how about we have a function/method matpow or matrix_power that tries to evaluate matrix powers and `A**b` give `MatPow(A, b)` which doesn't evaluate without doit?

Note that users will probably expect `M**2` to evaluate but there can be good reasons for not doing this for integer powers either. Consider:
```julia
In [13]: M = Matrix([[1+x, 1-x], [1-x, 1+x]])                                                                                     

In [14]: M**100 # Complicated...
```
The Jordan form gives a better output here
```julia
In [15]: (M**n).subs(n, 100) # Much better
```
