### ISSUE TITLE
Piecewise doesn't works correctly

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#17112]
#### Example of problem
**Code**
```python
x = symbols('x')
cond = And(Le(x, 6), Ge(x, 1), S.Integers.contains(x))
p2 = Piecewise((S(1), cond), (S(0), True))
```

**Result**
```python
Traceback (most recent call last):
  File "/home/gagandeep/sympy_debug.py", line 593, in <module>
    p2 = Piecewise((S(1), cond), (S(0), True))
  File "/home/gagandeep/sympy/sympy/functions/elementary/piecewise.py", line 143, in __new__
    r = cls.eval(*newargs)
  File "/home/gagandeep/sympy/sympy/functions/elementary/piecewise.py", line 192, in eval
    c = c.as_set().as_relational(x)
  File "/home/gagandeep/sympy/sympy/logic/boolalg.py", line 156, in as_set
    return self.subs(reps)._eval_as_set()
  File "/home/gagandeep/sympy/sympy/logic/boolalg.py", line 737, in _eval_as_set
    return Intersection(*[arg.as_set() for arg in self.args])
  File "/home/gagandeep/sympy/sympy/sets/sets.py", line 1268, in __new__
    return simplify_intersection(args)
  File "/home/gagandeep/sympy/sympy/sets/sets.py", line 1988, in simplify_intersection
    raise TypeError("Input args to Union must be Sets")
TypeError: Input args to Union must be Sets
```
It's not working on `SymPy Live` as well, see the screenshot below,
![Screenshot from 2019-06-27 13-04-30](https://user-images.githubusercontent.com/36567889/60246816-21933280-98dd-11e9-80a7-a4fe9d090b0f.png)

#### Other comments/references
[1] https://github.com/sympy/sympy/pull/16962

@oscarbenjamin @Upabjojr told that it is working fine on their systems. 
@smichr Please help me out, either we should fix it or please suggest an alternative approach. I suspect that the error is caused, due to `c = c.as_set().as_relational(x)` in `Piecewise.eval`. May be at least `Logic` should be allowed to pass through the following loop,
```python
for e, c in _args:
            if not c.is_Atom and not isinstance(c, Relational): # `Relational` -> `Boolean` can fix it.(not tried)
                free = c.free_symbols
                if len(free) == 1:
                    funcs = [i for i in c.atoms(Function)
                        if not isinstance(i, Boolean)]
                    if len(funcs) == 1 and len(
                            c.xreplace({list(funcs)[0]: Dummy()}
                            ).free_symbols) == 1:
                        # we can treat function like a symbol
                        free = funcs
                    _c = c
                    x = free.pop()
                    try:
                        c = c.as_set().as_relational(x)
                    except NotImplementedError:
                        pass
                    else:
                        reps = {}
                        for i in c.atoms(Relational):
                            ic = i.canonical
                            if ic.rhs in (S.Infinity, S.NegativeInfinity):
                                if not _c.has(ic.rhs):
                                    # don't accept introduction of
                                    # new Relationals with +/-oo
                                    reps[i] = S.true
                                elif ('=' not in ic.rel_op and
                                        c.xreplace({x: i.rhs}) !=
                                        _c.xreplace({x: i.rhs})):
                                    reps[i] = Relational(
                                        i.lhs, i.rhs, i.rel_op + '=')
                        c = c.xreplace(reps)
            args.append((e, _canonical(c)))
```

**Comment by sylee957** [comment]
I don't think that set notations are supported in piecewise yet.

**Comment by oscarbenjamin** [comment]
I think this particular error might be trivial to fix by adding Contains.as_set as in:
```
>>> Contains(x, S.Integers).as_set()
S.Integers
```

**Comment by czgdp1807** [comment]
> >>> Contains(x, S.Integers).as_set()
> S.Integers

I tried it but the following happens,
```python
Traceback (most recent call last):
  File "/home/gagandeep/sympy_debug.py", line 593, in <module>
    p2 = Piecewise((S(1), cond), (S(0), True))
  File "/home/gagandeep/sympy/sympy/functions/elementary/piecewise.py", line 143, in __new__
    r = cls.eval(*newargs)
  File "/home/gagandeep/sympy/sympy/functions/elementary/piecewise.py", line 192, in eval
    c = c.as_set().as_relational(x)
AttributeError: 'Range' object has no attribute 'as_relational'
```

**Comment by oscarbenjamin** [comment]
Maybe we need Range.as_relational as well then. S.Integers.as_relational gives:
```
In [7]: S.Integers.as_relational(x)                                                                                               
Out[7]: ⌊x⌋ = x ∧ -∞ < x ∧ x < ∞
```
So I guess we could have `Range(a, b).as_relational` can be `Eq(floor(x), x) & (x >= a) & (x < b)`.

**Comment by czgdp1807** [comment]
> Eq(floor(x), x) & (x >= a) & (x < b) 

Well, we could have directly gone with this, well I have made a PR, take a look at it.

**Comment by oscarbenjamin** [comment]
I think that Contains is better for stats because you want to be able to make this work for any RV and they will all have an associated set.

**Comment by czgdp1807** [comment]
Ah! Right
