### ISSUE TITLE
Error in automatic construction of symbols when enable doctest as well

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#17125]
# Version:
sympy - 1.4
ipython - 7.5.0

# Reproduce

```bash
$ isympy -aid 
Traceback (most recent call last):
  File "/usr/bin/isympy", line 11, in <module>
    load_entry_point('sympy==1.4', 'console_scripts', 'isympy')()
  File "/usr/lib/python3.7/site-packages/isympy.py", line 339, in main
    init_session(ipython, **args)
  File "/usr/lib/python3.7/site-packages/sympy/interactive/session.py", line 443, in init_session
    raise RuntimeError("automatic construction of symbols is possible only in IPython 0.11 or above")
RuntimeError: automatic construction of symbols is possible only in IPython 0.11 or above

$ isympy -ad
Traceback (most recent call last):
  File "/usr/bin/isympy", line 11, in <module>
    load_entry_point('sympy==1.4', 'console_scripts', 'isympy')()
  File "/usr/lib/python3.7/site-packages/isympy.py", line 339, in main
    init_session(ipython, **args)
  File "/usr/lib/python3.7/site-packages/sympy/interactive/session.py", line 443, in init_session
    raise RuntimeError("automatic construction of symbols is possible only in IPython 0.11 or above")
RuntimeError: automatic construction of symbols is possible only in IPython 0.11 or above


isympy -id
Traceback (most recent call last):
  File "/usr/bin/isympy", line 11, in <module>
    load_entry_point('sympy==1.4', 'console_scripts', 'isympy')()
  File "/usr/lib/python3.7/site-packages/isympy.py", line 339, in main
    init_session(ipython, **args)
  File "/usr/lib/python3.7/site-packages/sympy/interactive/session.py", line 445, in init_session
    raise RuntimeError("automatic int to Integer transformation is possible only in IPython 0.11 or above")
RuntimeError: automatic int to Integer transformation is possible only in IPython 0.11 or above

```

But when run isympy as `isympy -ai`, it works fine.

**Comment by oscarbenjamin** [comment]
This is due to this line
https://github.com/sympy/sympy/blob/1e873561414e786c69be8bf1c53974bdc74935c7/isympy.py#L300

It is documented in the docstring:
https://github.com/sympy/sympy/blob/1e873561414e786c69be8bf1c53974bdc74935c7/isympy.py#L87-L90

I'm not sure why doctest mode should disable ipython mode though.
