### ISSUE TITLE
Non-deterministic exception from integrals/poly

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17132]
The script below fails non-deterministically for me:
```python
from sympy import *

t = Symbol('t')
f = t*exp(-3*t**2/2) + exp(t**2/2)
print(integrate(f, t))
```
Half the time I get
```console
$ python z.py 
sqrt(2)*sqrt(pi)*erfi(sqrt(2)*t/2)/2 - exp(-3*t**2/2)/3
```
which I think is the right answer.

The other half of the time I get:
```console
$ python z.py 
Traceback (most recent call last):
  File "z.py", line 5, in <module>
    print(integrate(f, t))
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 1520, in integrate
    return integral.doit(**doit_flags)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 573, in doit
    antideriv = self._eval_integral(
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 905, in _eval_integral
    result, i = risch_integrate(f, x, separate_integral=True,
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/risch.py", line 1754, in risch_integrate
    ans, i, b = integrate_hyperexponential(fa, fd, DE, conds=conds)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/risch.py", line 1521, in integrate_hyperexponential
    i = p - (qd*derivation(qa, DE) - qa*derivation(qd, DE)).as_expr()/\
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/risch.py", line 898, in derivation
    r += (d*pv.diff(v)).as_poly(t)
TypeError: unsupported operand type(s) for +=: 'Poly' and 'NoneType'
```
This happens with both Python 3.5 and 3.8 on OSX.

**Comment by jksuom** [comment]
There is a weakness in this construction where `va*t1**i/vd` is added to `qa/qd` https://github.com/sympy/sympy/blob/1d3327b8e90a186df6972991963a5ae87053259d/sympy/integrals/risch.py#L1459-L1460

`integrate_hyperexponential_polynomial` actually has to deal with Laurent polynomials. Positive and negative and exponents are handled separately earlier in the loop https://github.com/sympy/sympy/blob/1d3327b8e90a186df6972991963a5ae87053259d/sympy/integrals/risch.py#L1439-L1447

However, on line 1459 we now get polynomials with inverted generators for negative exponents, and those lead to problems later on:
```
In [6]: Poly(t**-3)
Out[6]: Poly((1/t)**3, 1/t, domain='ZZ')
```
It seems that we should put `Poly(t1**-i)` in the denominator `qd` in case `i < 0`.

**Comment by guptapratykshh** [comment]
This change is how we handle case when `i < 0` . I have split handling of positive and negative exponents at end of try-except block.

```
            aa, ad = frac_in(a, DE.t, field=True)
            aa, ad = aa.cancel(ad, include=True)
            iDt = Poly(i, t1)*dtt
            iDta, iDtd = frac_in(iDt, DE.t, field=True)
            try:
                va, vd = rischDE(iDta, iDtd, Poly(aa, DE.t), Poly(ad, DE.t), DE)
                va, vd = frac_in((va, vd), t1, cancel=True)
            except NonElementaryIntegralException:
                b = False
            else:
                if i < 0:
                    qa = qa*vd
                    qd = qd*vd*Poly(t1**(-i))
                else:
                    qa = qa*vd + va*Poly(t1**i)*qd
                    qd *= vd

    return (qa, qd, b)
```
