### ISSUE TITLE
simplify(x**(1 / acos(I))) recursion error

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#17141]
```
>>> from sympy import *
>>> x = Symbol('x')
>>> e = x**(1 / acos(I))
>>> print(simplify(e))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/e/se/sympy/simplify/simplify.py", line 559, in simplify
    expr = bottom_up(expr, lambda w: getattr(w, 'normal', lambda: w)())
  File "/home/e/se/sympy/simplify/simplify.py", line 1077, in bottom_up
    rv = F(rv)
  File "/home/e/se/sympy/simplify/simplify.py", line 559, in <lambda>
    expr = bottom_up(expr, lambda w: getattr(w, 'normal', lambda: w)())
  File "/home/e/se/sympy/core/expr.py", line 2141, in normal
    n, d = self.as_numer_denom()
  File "/home/e/se/sympy/core/power.py", line 1322, in as_numer_denom
    return self.func(n, exp), self.func(d, exp)
  File "/home/e/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se/sympy/core/power.py", line 283, in __new__
    if abs(e).is_infinite:
  File "/home/e/se/sympy/core/expr.py", line 167, in __abs__
    return Abs(self)
  File "/home/e/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se/sympy/core/function.py", line 462, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/home/e/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se/sympy/core/function.py", line 277, in __new__
    evaluated = cls.eval(*args)
  File "/home/e/se/sympy/functions/elementary/complexes.py", line 510, in eval
    return exp(re(exponent*z))
  File "/home/e/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se/sympy/core/function.py", line 462, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/home/e/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se/sympy/core/function.py", line 277, in __new__
    evaluated = cls.eval(*args)
  File "/home/e/se/sympy/functions/elementary/complexes.py", line 82, in eval
    real_imag = term.as_real_imag(ignore=arg)
  File "/home/e/se/sympy/core/mul.py", line 783, in as_real_imag
    r, i = a.as_real_imag()
  File "/home/e/se/sympy/functions/elementary/exponential.py", line 693, in as_real_imag
    abs = Abs(self.args[0].expand(deep, **hints))
  File "/home/e/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se/sympy/core/function.py", line 462, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/home/e/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se/sympy/core/function.py", line 277, in __new__
    evaluated = cls.eval(*args)
  File "/home/e/se/sympy/functions/elementary/complexes.py", line 510, in eval
    return exp(re(exponent*z))
  File "/home/e/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se/sympy/core/function.py", line 462, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/home/e/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se/sympy/core/function.py", line 277, in __new__
    evaluated = cls.eval(*args)

...

    retval = cfunc(*args, **kwargs)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by ethankward** [comment]
The recursion error is manifested when we try to call `as_real_imag()` on `log(acos(-I)*acos(I)/sqrt(acos(-I)**2*acos(I)**2))/2`.

**Comment by oscargus** [comment]
Even simpler example: `simplify(2**acos(I)**2)`

It seems like `asin(I)` evaluates to `I*log(1 + sqrt(2))` but `acos(I)` is kept unevaluated. One possibility would be to evaluate it to `-I*log(I+I*sqrt(2))` (see e.g. https://www.mathworks.com/help/matlab/ref/acos.html ). Not sure why it is done for `asin` and not `acos`.

**Comment by oscargus** [comment]
These lines are in `asin`, but nothing corresponding for `acos`:

https://github.com/sympy/sympy/blob/d2308e8eb55ed6acb24bcd8dbb8c410c9e5e9d5c/sympy/functions/elementary/trigonometric.py#L1972-L1974

**Comment by oscargus** [comment]
#17154 will fix these cases, but not: `simplify(2**acos(I+1)**2)`

It is worth noting that a RecursionError also happens for `(2**acos(I+1)**2).rewrite('log').expand()`. For this case, the minimum example I've found is `(2**(1 - log(sqrt(I) + 1)**2)).expand()`. Removing either the sqrt or any of the 1s leads to that it returns properly. Also changing - to + removes the RecursionError.

**Comment by oscargus** [comment]
The problem for the last example seems to be in computing: `atan2(0, atan(sqrt(2)/(2*(sqrt(2)/2 + 1)))**2 + log(sqrt(2)/2 - sqrt(2)*I/2 - sqrt(2)*sqrt(I)*I/2 + sqrt(2)*sqrt(I)/2+sqrt(I))**2)` which leads to a RecursionError.

A smaller example for this is: `atan2(0, 1 + log(-sqrt(2)*I/2 - sqrt(2)*sqrt(I)*I/2 + sqrt(2)*sqrt(I)/2+sqrt(I))**2)`

Removing any of the sqrt/I terms removes the error, so it seems to require a certain combination of terms here.

The bad circle is atan2 => `return -S.ImaginaryUnit*log((x + S.ImaginaryUnit*y)/sqrt(x**2 + y**2))`
sqrt => x**S.Half
Pow => `s = exp(2*S.Pi*S.ImaginaryUnit*other*floor(S.Half - e*arg(b)/(2*S.Pi)))`
arg => atan2 with same arguments.

(Removing the 1 in front makes SymPy "hang" (or at least take a very long time to compute).)
