### ISSUE TITLE
KeyError: 'ceil' when using lamdify for tensorflow 1.14

### ISSUE THREAD

**Issue by abmorris** [sympy/sympy#17198]
Here's a function I wrote and used a couple of years ago

```
def Wignerd(theta, j, m1, m2) :
  """
  Calculate Wigner small-d function. Needs sympy.
    theta : angle
    j : spin (in units of 1/2, e.g. 1 for spin=1/2)
    m1 and m2 : spin projections (in units of 1/2)
  """
  from sympy import Rational
  from sympy.abc import x
  from sympy.utilities.lambdify import lambdify
  from sympy.physics.quantum.spin import Rotation as Wigner
  d = Wigner.d(Rational(j,2), Rational(m1,2), Rational(m2,2), x).doit().evalf()
  return lambdify(x, d, "tensorflow")(theta)
```

This happens after updating to tensorflow 1.14.0

```
Traceback (most recent call last):
  File "./test.py", line 16, in <module>
    data_pdf = model(data_ph)
  File "./test.py", line 11, in model
    return MatrixElement(phsp, datapoint, GenerateModel(minimal_model), switches)
  File "/home/admorris/work/BsphiKK/TFA_fits/MatrixElement.py", line 98, in MatrixElement
    for hel, amp in HelicityMatrixDecayChain(Bs, helAmps).iteritems():
  File "/home/admorris/work/TensorFlowAnalysis/TensorFlowAnalysis/Kinematics.py", line 680, in HelicityMatrixDecayChain
    matrix_parent =  HelicityMatrixElement(parent,helAmps)
  File "/home/admorris/work/TensorFlowAnalysis/TensorFlowAnalysis/Kinematics.py", line 751, in HelicityMatrixElement
    *Conjugate(WignerD(phi,theta,0,parent.GetSpin2(),phel,d1hel-d2hel))
  File "/home/admorris/work/TensorFlowAnalysis/TensorFlowAnalysis/Kinematics.py", line 538, in WignerD
    return Exp(-i*CastComplex(m1*phi))*CastComplex(Wignerd(theta,j2,m2_1,m2_2))*Exp(-i*CastComplex(m2*psi))
  File "/home/admorris/work/TensorFlowAnalysis/TensorFlowAnalysis/Kinematics.py", line 552, in Wignerd
    return lambdify(x, d, "tensorflow")(theta)
  File "/home/admorris/.local/lib/python2.7/site-packages/sympy/utilities/lambdify.py", line 694, in lambdify
    buf = _get_namespace(m)
  File "/home/admorris/.local/lib/python2.7/site-packages/sympy/utilities/lambdify.py", line 812, in _get_namespace
    _import(m)
  File "/home/admorris/.local/lib/python2.7/site-packages/sympy/utilities/lambdify.py", line 158, in _import
    namespace[sympyname] = namespace[translation]
KeyError: 'ceil'
```
For now I have downgraded to tensorflow 1.12.0 and this problem is not there.

I am using sympy 1.4

**Comment by klicperajo** [comment]
From what I can tell this will be fixed in SymPy 1.5.
