### ISSUE TITLE
Recursion error: (2*sin(1)/(exp(-I) + exp(I))).round()

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#17262]
```
>>> e = 2*sin(1)/(exp(-I) + exp(I))
>>> print(e.round())
Traceback (most recent call last):
  File "testing.py", line 272, in <module>
    print(i.round())
  File "/home/e/se2/sympy/core/expr.py", line 3536, in round
    return i.round(n) + S.ImaginaryUnit*r.round(n)
  File "/home/e/se2/sympy/core/expr.py", line 3536, in round
    return i.round(n) + S.ImaginaryUnit*r.round(n)
  File "/home/e/se2/sympy/core/expr.py", line 3536, in round
    return i.round(n) + S.ImaginaryUnit*r.round(n)
  [Previous line repeated 969 more times]
  File "/home/e/se2/sympy/core/expr.py", line 3529, in round
    if not pure_complex(x.n(2), or_real=True):
  File "/home/e/se2/sympy/core/evalf.py", line 1465, in evalf
    return re + im*S.ImaginaryUnit
  File "/home/e/se2/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/home/e/se2/sympy/core/numbers.py", line 1314, in __mul__
    return Number.__mul__(self, other)
  File "/home/e/se2/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/home/e/se2/sympy/core/numbers.py", line 758, in __mul__
    return AtomicExpr.__mul__(self, other)
  File "/home/e/se2/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/home/e/se2/sympy/core/decorators.py", line 129, in binary_op_wrapper
    return func(self, other)
  File "/home/e/se2/sympy/core/expr.py", line 192, in __mul__
    return Mul(self, other)
  File "/home/e/se2/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se2/sympy/core/numbers.py", line 1393, in __eq__
    other = _sympify(other)
  File "/home/e/se2/sympy/core/sympify.py", line 422, in _sympify
    return sympify(a, strict=True)
  File "/home/e/se2/sympy/core/sympify.py", line 266, in sympify
    if a in sympy_classes:
  File "/home/e/se2/sympy/core/numbers.py", line 1485, in __hash__
    return super(Float, self).__hash__()
  File "/home/e/se2/sympy/core/numbers.py", line 810, in __hash__
    return super(Number, self).__hash__()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Can be manifested in various ways:

```
>>> e = -I*pi*(-exp(-I) + exp(I))/(exp(-I) + exp(I))
>>> print(exp(e))
...
```

```
>>> f = sech(pi/cot(1))
>>> print(f.rewrite(exp))
...
```

```
>>> g = x - sech(pi/cot(1))
>>> print(simplify(g))
...
```

**Comment by ethankward** [comment]
The `if not x.is_extended_real:` block on line 3534 seems to have several issues: `x.is_extended_real` can return `None` even if `.as_real_imag` functions correctly. `i` and `r` are reversed (minor but confusing). If `i == x` then obviously we get a recursion error.

Further down on line 3621 `sign = 1 if x > 0 else -1` can fail if `x > 0` doesn't directly evaluate.

**Comment by oscargus** [comment]
`if not x.is_extended_real:` can changed to `if fuzzy_not(x.is_extended_real):`, but then one gets the comparison issue. Maybe one should assign the value of the comparison and check if it still a Relational. If it is, one may try to simplify it before trying again. Might work for at least some cases...
