### ISSUE TITLE
Result improvement and dependent random variables for sympy.stats

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#17260]
**Purpose**

This issue is raised for discussing the following points for phase 3 of the project,

1. Re-fining results generated by `sympy.stats` - Reducing the complexity of results(espescially for continuous random variables) and some extensions(for example, allowing symbolic dimensions in finite random variables).

2. Support for dependent random variables

**Previous work**

Some work has already been done which has been summarised below,

1. Re-fining results generated by `sympy.stats` -  During the community bonding period, we observed that `sympy.stats.frv` and `sympy.stats.frv_types` were unable to support random variables with symbolic dimensions. This has been partly resolved by https://github.com/sympy/sympy/pull/16908 and https://github.com/sympy/sympy/pull/17146 has been opened for continuing the work.

2. Support for dependent random variables - During the community bonding period, @Upabjojr suggested the idea of class `DependentPSpace`.

**Future work**

1. I have mentioned some of the issues in my proposal in [this part](https://docs.google.com/document/d/1oIeaROiJyglpbris7X1uZPRE5ZeO0pD1ygCFhBIeATI/edit?pli=1#heading=h.p0czfgesqgo) and their possible solutions. I want comments from the community on the above ideas(the proposal is on Google docs and is open for vieiwing by anyone), and the PR will be opened according to the discussion takes place.

2. Before jumping on to the structure of `DependentPSpace`, I will first find some use cases(example problems, situations) and after that we can move on to the architecture. Probably, by the end of the evaluations of the second phase, I will come up with use-cases and a theoritical solution.

**Othe comments**

ping @sidhantnagpal @Upabjojr

**Comment by czgdp1807** [comment]
**Dependent Random Variables**

Basically, we aim to apply assumptions of dependence of random variables. For that we need to first to discuss the API. An example for forming the base of the discussion is given below,

**Current Situation**

```python
>>> from sympy.stats import Normal, P, Covariance, density
>>> from sympy import Eq
>>> X = Normal('X', 0, 1)
>>> Y = Normal('Y', 0, 1)
>>> density(X + Y, Eq(Covariance(X, Y), 0.1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../sympy/sympy/stats/rv.py", line 889, in density
    return Density(expr, condition).doit(evaluate=evaluate, **kwargs)
  File "../sympy/sympy/stats/rv.py", line 842, in doit
    return result.doit()
  File "../sympy/sympy/core/basic.py", line 1679, in doit
    for term in self.args]
  File "../sympy/sympy/core/basic.py", line 1679, in <listcomp>
    for term in self.args]
  File "../sympy/sympy/integrals/integrals.py", line 557, in doit
    ret = try_meijerg(function, xab)
  File "../sympy/sympy/integrals/integrals.py", line 529, in try_meijerg
    res = meijerint_definite(function, x, a, b)
  File "../sympy/sympy/integrals/meijerint.py", line 1787, in meijerint_definite
    innermost = _find_splitting_points(f, x)
  File "../sympy/sympy/integrals/meijerint.py", line 405, in _find_splitting_points
    compute_innermost(expr, innermost)
  File "../sympy/sympy/integrals/meijerint.py", line 398, in compute_innermost
    res.add(-m[q]/m[p])
KeyError: q_
```

As can be seen, currently, assuming the covariance of two random variables isn't possible at the time of making the query or in other terms, we cannot pass `Covariance` object as given condition.
`Covariance` is just an example, there are many other parameters through which one can assume that two variables are dependent.

How, `DependentPSpace` comes into picture? `DependentPSpace` will be having the implementation of logic to use the information of dependence received from the top level API and using it to determine the results.
For example, hypothetically, `DependentPSpace.compute_density` method will try to create a joint distribution or compound distribution of the dependent random variables using the information received and will try to compute throught the joint random variable and will return to the user. One can refer the proof in [this answer](https://stats.stackexchange.com/a/19953) for more ideas to solve this problem of assumptions of dependence.

ping @Upabjojr

**Comment by Upabjojr** [comment]
There is a potential confusion arising from the fact that both `X` and `Y` have already an associated P-space. Is `DependentPSpace` going to act like a special case of `JointPSPace` (e.g. when you don't know the joint PDF but just some hints about common properties of two RVs)?

**Comment by czgdp1807** [comment]
> Is `DependentPSpace` going to act like a special case of `JointPSPace` (e.g. when you don't know the joint PDF but just some hints about common properties of two RVs)?

No, it will decide what to use, `CompoundPSPace` or `JointPSPace` to find the result. If information is not sufficient then it will return un-evaluated results.
`DependentPSpace` is just one of the ways and there are other ways too for supporting assumptions of dependence.

**Comment by czgdp1807** [comment]
Any further comments? Please let me know if you have any critical objections regarding `DependentPSpace`. Actually, why I am suggesting the use of `DependentPSpace` is because, all the logic for dependent random variables will be encapsulated inside a single class. Though we can distribute the logic for example by modifying, `Density`, `Expectation`, etc. What do you prefer?

**Comment by Upabjojr** [comment]
No objections for now.
