### ISSUE TITLE
S.Reals give error on using symbol

### ISSUE THREAD

**Issue by ritesh99rakesh** [sympy/sympy#17267]
Code:
```python3
>>> from sympy import symbols, S
>>> k = symbols('k')
>>> a = S.Reals**k
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ritesh/Desktop/sympy/sympy/sets/sets.py", line 590, in __pow__
    if not sympify(exp).is_Integer and exp >= 0:
  File "/home/ritesh/Desktop/sympy/sympy/core/relational.py", line 309, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational
```
`S.Reals**k` is used to define the `set` of multivariate distributions, where `k` is `no. of rows` of matrix parameter. I think that symbolic `k` should be allowed.

**Comment by oscarbenjamin** [comment]
This could only be well defined for nonnegative integers. I'm not sure why `exp>=0` is being tested there. Making k negative leads to a different error:
```julia
In [8]: k = Symbol('k', integer=True, negative=True)                                                                              

In [9]: S.Reals**k                                                                                                                
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-da76b8199f5e> in <module>
----> 1 S.Reals**k

~/current/sympy/sympy/sympy/sets/sets.py in __pow__(self, exp)
    590         if not sympify(exp).is_Integer and exp >= 0:
    591             raise ValueError("%s: Exponent must be a positive Integer" % exp)
--> 592         return ProductSet([self]*exp)
    593 
    594     def __sub__(self, other):

TypeError: can't multiply sequence by non-int of type 'Symbol'
```
It probably should be possible to do this but I expect that the resulting object wouldn't be usable anywhere. What would you want to do with it after creating it?

**Comment by ritesh99rakesh** [comment]
They form the domain set of distribution and used to derive expectation, variance (ie use for integration or summation). @oscarbenjamin do you it would be good idea to look into it?

**Comment by asmeurer** [comment]
It doesn't look like ProductSet supports symbolic powers yet. 

Perhaps it would be best to add a general indexed product set https://en.wikipedia.org/wiki/Cartesian_product#Infinite_Cartesian_products, and make `A**n` be a shortcut for IndexedProductSet(A, n, Range(n)).
