### ISSUE TITLE
Min._from_args leads to a printing error (and no args)

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#17331]
```

In [23]: Min._from_args([x, y])
Traceback (most recent call last):

  File "C:\Users\Oscar\Anaconda3\lib\site-packages\IPython\core\formatters.py", line 702, in __call__
    printer.pretty(obj)

  File "C:\Users\Oscar\Anaconda3\lib\site-packages\IPython\lib\pretty.py", line 385, in pretty
    return self.type_pprinters[cls](obj, self, cycle)

  File "C:\Users\Oscar\sympy\sympy\interactive\printing.py", line 75, in _print_plain
    p.text(stringify_func(arg))

  File "C:\Users\Oscar\sympy\sympy\printing\pretty\pretty.py", line 2569, in pretty
    return pp.doprint(expr)

  File "C:\Users\Oscar\sympy\sympy\printing\pretty\pretty.py", line 65, in doprint
    return self._print(expr).render(**self._settings)

  File "C:\Users\Oscar\sympy\sympy\printing\printer.py", line 293, in _print
    return self.emptyPrinter(expr)

  File "C:\Users\Oscar\sympy\sympy\printing\pretty\pretty.py", line 55, in <lambda>
    self.emptyPrinter = lambda x: prettyForm(xstr(x))

  File "C:\Users\Oscar\sympy\sympy\printing\pretty\pretty_symbology.py", line 111, in xstr
    return unicode(*args)

  File "C:\Users\Oscar\sympy\sympy\core\basic.py", line 414, in __str__
    return sstr(self, order=None)

  File "C:\Users\Oscar\sympy\sympy\printing\str.py", line 888, in sstr
    s = p.doprint(expr)

  File "C:\Users\Oscar\sympy\sympy\printing\printer.py", line 249, in doprint
    return self._str(self._print(expr))

  File "C:\Users\Oscar\sympy\sympy\printing\printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)

  File "C:\Users\Oscar\sympy\sympy\printing\str.py", line 220, in _print_LatticeOp
    args = sorted(expr.args, key=default_sort_key)

  File "C:\Users\Oscar\sympy\sympy\core\operations.py", line 460, in args
    return tuple(ordered(self._argset))

AttributeError: 'Min' object has no attribute '_argset'

In [24]: _.args
Traceback (most recent call last):

  File "<ipython-input-24-8e48ece508d1>", line 1, in <module>
    _.args

  File "C:\Users\Oscar\sympy\sympy\core\operations.py", line 460, in args
    return tuple(ordered(self._argset))

AttributeError: 'Min' object has no attribute '_argset'
```

Works for e.g. Add and Mul, but I cannot really figure out what the difference is since I can only find a single definition of the method. (Same error for Max, And, Or.)

**Comment by oscargus** [comment]
Similar issue with `_new_rawargs`.

**Comment by ethankward** [comment]
In `LatticeOp` the `args` method is overridden (I guess just to sort the args?)- shouldn't it just `return tuple(ordered(self._args))`?

**Comment by oscargus** [comment]
Ah, you are right. Thanks! I had missed that it was overridden (I only looked up the hierarchy from `AssocOp`. One problem here though is that since `_from_args` and `_new_rawargs` is defined in `AssocOp` they do not call the constructor in `LatticeOp`. I guess the idea is really to use `_ argset` to avoid duplicate arguments, so probably the arguments in `LatticeOp` should indeed be stored in a set. Maybe a temporary solution is to see if there is an `_argset` arguments and if not use `args`? The only reason `_argset` is not there, is that the object is created using `_from_args` or `_new_rawargs`, which basically shouldn't need any of the filtering and set stuff anyway (because then one should not use those low-level functions).

I guess that there may be a better solution in the long run though...

**Comment by oscargus** [comment]
Gah!

The purpose of `_from_args` is really to bypass the `AssocOp` constructor with sorting. Hence, it is not straightforward to implement a similar function in `LatticeOp` (at least not one that will be almost identical to `__new__` without the `_sympify`-part.

Conditionally returning self.args lead to a recursion error when computing hash...

What I am trying to do is to speed up a new simplification process (#17330), but I guess I will have to live with it being a bit slower than it possibly could be if this cannot be sorted out...
