### ISSUE TITLE
Error when simplifying Max-relation

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#17354]
When investigating #13552 I found the following (maybe not related to the original issue, but this is a minimal example of failing simplification of the generated `Piecewise`).
```
In [27]: Max(y/(x - 1), y/(x + 1)) >= 0

In [28]: _.simplify()
Traceback (most recent call last):

  File "<ipython-input-28-20cad44b6496>", line 1, in <module>
    _.simplify()

  File "/nobackup/data/sympy/sympy/core/expr.py", line 3546, in simplify
    return simplify(self, **kwargs)

  File "/nobackup/data/sympy/sympy/simplify/simplify.py", line 552, in simplify
    return _eval_simplify(**kwargs)

  File "/nobackup/data/sympy/sympy/core/relational.py", line 292, in _eval_simplify
    elif dif.equals(0):  # XXX this is expensive

  File "/nobackup/data/sympy/sympy/core/expr.py", line 759, in equals
    constant = diff.is_constant(simplify=False, failing_number=True)

  File "/nobackup/data/sympy/sympy/core/expr.py", line 683, in is_constant
    simultaneous=True)

  File "/nobackup/data/sympy/sympy/core/basic.py", line 998, in subs
    return rv.xreplace(reps)

  File "/nobackup/data/sympy/sympy/core/basic.py", line 1192, in xreplace
    value, _ = self._xreplace(rule)

  File "/nobackup/data/sympy/sympy/core/basic.py", line 1214, in _xreplace
    return self.func(*args), True

  File "/nobackup/data/sympy/sympy/functions/elementary/miscellaneous.py", line 349, in __new__
    args = frozenset(cls._new_args_filter(args))

  File "/nobackup/data/sympy/sympy/functions/elementary/miscellaneous.py", line 522, in _new_args_filter
    raise ValueError("The argument '%s' is not comparable." % arg)

ValueError: The argument 'zoo' is not comparable.
```

**Comment by oscargus** [comment]
I think it comes from a division by zero returning `zoo`. If instead `oo` is returned the error goes away. Wouldn't it make sense to return `oo` if whatever is divided by 0 is real? Ping @smichr who added the `zoo` in #16770.

**Comment by smichr** [comment]
> Wouldn't it make sense to return `oo` if whatever is divided by 0 is real? [as in `1/S(0)`]

ping @jksuom

**Comment by oscargus** [comment]
The reason is really that `oo` works in comparisons, as opposed to `zoo`. Now I managed to solve this particular issue, but I'm quite sure that there will be more when an unexpected `zoo` shows up...

**Comment by jksuom** [comment]
Both `oo` and `-oo` work in comparisons but give different results. Returning `oo` for `1/0` cannot be always correct. Some code has to be added in any case. In this case, `arg` could be investigated before raising. It it is `zoo`, it could be replaced by something else, `AccumBounds(-oo, oo)`, for example. That would have max `oo` and min `-oo`.

**Comment by oscargus** [comment]
It turns out that 0/0 is NaN, so it is not really just an issue with `zoo` or not. I'd say that the problem really comes from the default `is_constant`, which blindly replaces variables with 1 or 0 and catches zero division exceptions. Hence, for now, the solution is really to catch `ValueError`exceptions. In the long run one can probably improve the `is_constant`logic as it is not really enough for all cases to just catch ValueError. See some examples in https://github.com/sympy/sympy/pull/17407#issuecomment-521051952 and later comments. Some of these are quite hard to avoid (but maybe they are not called with `is_constant` that often and it doesn't seem to happen with `simplify` for those examples).

**Comment by oscargus** [comment]
In this case we are not really interested in a "correct" result of the Min/Max operation, more that the code shouldn't break during execution. So catching the exception and returning false seems like a good enough approach to avoid that. Clearly, if there is an exception, the result can hardly be valid, which is enough for both `equals` and `is_constant` to make decision on. Maybe one should just pass instead of returning False though. Hard to say.

**Comment by oscargus** [comment]
I think that it is possible to solve the original issue. However, it turns out that the same problem bites at different locations.

New problem:
```
from sympy import symbols, Wild
x, y = symbols("x y", real=True)
a, b = symbols("a b", cls=Wild)
((0 <= x).reversed | (y <= x)).match((1/a <= b) | (a <= b))
```

Leads to:
```
Traceback (most recent call last):

  File "<ipython-input-16-b8df37a64090>", line 4, in <module>
    ((0 <= x).reversed | (y <= x)).match((1/a <= b) | (a <= b))

  File "C:\Users\Oscar\sympy\sympy\core\basic.py", line 1663, in match
    return pattern.matches(self, old=old)

  File "C:\Users\Oscar\sympy\sympy\core\basic.py", line 1617, in matches
    d = arg.xreplace(d).matches(other_arg, d, old=old)

  File "C:\Users\Oscar\sympy\sympy\core\basic.py", line 1192, in xreplace
    value, _ = self._xreplace(rule)

  File "C:\Users\Oscar\sympy\sympy\core\basic.py", line 1214, in _xreplace
    return self.func(*args), True

  File "C:\Users\Oscar\sympy\sympy\core\relational.py", line 650, in __new__
    r = cls._eval_relation(lhs, rhs)

  File "C:\Users\Oscar\sympy\sympy\core\relational.py", line 944, in _eval_relation
    return _sympify(lhs.__le__(rhs))

  File "C:\Users\Oscar\sympy\sympy\core\expr.py", line 363, in __le__
    raise TypeError("Invalid comparison of complex %s" % me)

TypeError: Invalid comparison of complex zoo
```

**Comment by oscargus** [comment]
Would it be OK to implement a new exception `InvalidComparisonError` or something similar to catch these? There are ZeroDivisionErrors in the code, but as far as I know, these are not really thrown.

**Comment by oscarbenjamin** [comment]
I would much rather that library code was catching something like `InvalidComparisonError` than `TypeError`. For backwards compatibility it would need to subclass `TypeError` though.

**Comment by oscargus** [comment]
It seems to be quite a mix between `ValueError` and `TypeError` for invalid input arguments.

This makes sense (to me) as a TypeError:
```
raise ValueError("constants must be real-valued")
```
this not so much:
```
raise ValueError('incompatible types')
```

Similar with `TypeError`:
```
raise TypeError('Expecting Plot or sequence of BaseSeries')
```
vs.
```
raise TypeError("Index is not an integer number.")
```

So, the question (now) is really how to deal with functions where the subs leads to incorrect input data? `InvalidComparion` makes less sense there...

**Comment by oscarbenjamin** [comment]
> So, the question (now) is really how to deal with functions where the subs leads to incorrect input data? `InvalidComparion` makes less sense there...

If those are the exceptions raised then they will need to be caught. In general though we should try to replace the places where these errors are raised with more specific subclasses. We could have BadArgsError as the standard way for a Basic subclass to complain about the objects it receives in `__new__`. It could be a subclass of `ValueError` or `TypeError` (or both?)...

Plain TypeError should be reserved for bugs and user errors, like calling a function with too few arguments or passing an unsympifiable object. If we're raising and catching that in normal operation something has gone wrong.

**Comment by smichr** [comment]
> Returning `oo` for `1/0` cannot be always correct.

Could you give an example of when this would be wrong?  I don't think any of the assumptions code would need to be changed in #17453 if we returned `oo` instead of `zoo`. And as far as the change in #16770...I suspect I was just taking my cues from what was in `numbers.py` for `Zero`.

**Comment by oscargus** [comment]
I was just playing around with a similar situation and what seems to make sense to me is that `limit(1/x, x, 0, '+')` and `limit(1/x, x, 0, '-')` are different: `oo` and `-oo`. If they both were `oo` I would be more in favour of changing back, now I'm starting to see the point of it from a mathematical perspective.

Still, from a programming perspective it is a bit annoying... But most comparisons are sorted out in #17443 anyway. (I think that there may be other places where it should be catched though, but no tests have triggered them...)

I also agree with @oscarbenjamin , that more specific errors is the way to go. Just a bit reluctant to go over the whole code-base and unify it...

**Comment by oscargus** [comment]
Somehow, the problem is not #16770, the problem is that some functions throws exceptions on `NaN` and `zoo`. At least for `NaN` one could expect all functions to return `NaN` (except for maybe relationals, I think `Max` and `Min` may very well return `NaN` for a `NaN` argument). For `zoo` it is not as obvious, but as long as all functions return `zoo` for a `zoo` argument, it shouldn't really be a problem.

**Comment by oscarbenjamin** [comment]
This is a longstanding issue and not a recent regression. I don't see any reason for this to hold up the next release so removing the milestone.
