### ISSUE TITLE
Should polygamma(a, b) raise NotImplementedError for noninteger (numeric) a?

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#17350]
mpmath's implementation of polygamma is valid only for integer first arguments. SymPy's implementation does not care, but this leads to many issues if you actually try to do things with such objects:

```
>>> (I*polygamma(I, pi)).as_real_imag()
Traceback (most recent call last):
  File "/home/eward/se2/sympy/core/assumptions.py", line 262, in getit
    return self._assumptions[fact]
KeyError: 'zero'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eward/se2/sympy/core/assumptions.py", line 262, in getit
    return self._assumptions[fact]
KeyError: 'finite'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eward/se2/sympy/core/assumptions.py", line 262, in getit
    return self._assumptions[fact]
KeyError: 'extended_positive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eward/se2/sympy/core/evalf.py", line 1308, in evalf
    rf = evalf_table[x.func]
KeyError: polygamma

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eward/se2/sympy/core/mul.py", line 798, in as_real_imag
    if i.is_zero:
  File "/home/eward/se2/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/eward/se2/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/eward/se2/sympy/core/assumptions.py", line 309, in _ask
    a = evaluate(obj)
  File "/home/eward/se2/sympy/core/expr.py", line 864, in _eval_is_negative
    finite = self.is_finite
  File "/home/eward/se2/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/eward/se2/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/eward/se2/sympy/core/assumptions.py", line 309, in _ask
    a = evaluate(obj)
  File "/home/eward/se2/sympy/core/expr.py", line 857, in _eval_is_positive
    extended_positive = self.is_extended_positive
  File "/home/eward/se2/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/eward/se2/sympy/core/assumptions.py", line 309, in _ask
    a = evaluate(obj)
  File "/home/eward/se2/sympy/core/expr.py", line 882, in _eval_is_extended_positive
    n2 = self._eval_evalf(2)
  File "/home/eward/se2/sympy/core/function.py", line 565, in _eval_evalf
    args = [arg._to_mpmath(prec + 5) for arg in self.args]
  File "/home/eward/se2/sympy/core/function.py", line 565, in <listcomp>
    args = [arg._to_mpmath(prec + 5) for arg in self.args]
  File "/home/eward/se2/sympy/core/evalf.py", line 1489, in _to_mpmath
    re, im, _, _ = evalf(self, prec, {})
  File "/home/eward/se2/sympy/core/evalf.py", line 1314, in evalf
    xe = x._eval_evalf(prec)
  File "/home/eward/se2/sympy/core/function.py", line 590, in _eval_evalf
    v = func(*args)
  File "/usr/local/lib/python3.6/dist-packages/mpmath/ctx_mp.py", line 265, in psi
    m = int(m)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'mpc'
>>> (tanh(polygamma(I, 1))).rewrite(exp)
...
    m = int(m)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'mpc'
>>> (I / polygamma(I, 4)).rewrite(exp)
...
    raise TypeError("Invalid comparison of complex %s" % me)
TypeError: Invalid comparison of complex I
```

**Comment by asmeurer** [comment]
I think we can set `is_number` to False to indicate to things that they shouldn't try to evalf.

**Comment by sylee957** [comment]
There is a more generalized definition for the polygamma function 
http://dauns01.math.tulane.edu/~vhm/papers_html/genoff.pdf
Can it be used here?

**Comment by ethankward** [comment]
Yes, but that would be on the mpmath side. If that's not changed then SymPy needs to be more careful about evaluation.
