### ISSUE TITLE
Value error when creating column vector with rational number string

### ISSUE THREAD

**Issue by royqh1979** [sympy/sympy#17430]
I can successfully create a row vector with rational numbers as the following:
`Q=Matrix([["5/6","-1/6","4/5"]])`

But when I was tring to create a column vector ,I got a ValueError :
```
from sympy import Matrix
Q=Matrix(["5/6","-1/6","4/5"])
```

The error message is as following:
```
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-9f7c17a31605>", line 1, in <module>
    Q=Matrix(["5/6","-1/6",1])
  File "D:\Python37\lib\site-packages\sympy\matrices\dense.py", line 433, in __new__
    return cls._new(*args, **kwargs)
  File "D:\Python37\lib\site-packages\sympy\matrices\dense.py", line 445, in _new
    rows, cols, flat_list = cls._handle_creation_inputs(*args, **kwargs)
  File "D:\Python37\lib\site-packages\sympy\matrices\matrices.py", line 2311, in _handle_creation_inputs
    sorted(list(ncol)))
ValueError: Got rows of variable lengths: [1, 3, 4]
```

**Comment by ethankward** [comment]
Appears to work in the development version.

**Comment by royqh1979** [comment]
> Appears to work in the development version, from commit [96d3535](https://github.com/sympy/sympy/commit/96d3535549918c4dc1c559bd95e30cde9ac530ce).

Yes, It's ok on development version
