### ISSUE TITLE
ValueError: solve((1 - x - I)**4, x)

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#17454]
```
>>> solve((1 - x - I)**4, x)
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    print(solve(e, x))
  File "/home/eward/se/sympy/solvers/solvers.py", line 1178, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/home/eward/se/sympy/solvers/solvers.py", line 1661, in _solve
    soln = roots(poly, **solvers)
  File "/home/eward/se/sympy/polys/polyroots.py", line 1017, in roots
    for currentroot in _try_decompose(f):
  File "/home/eward/se/sympy/polys/polyroots.py", line 915, in _try_decompose
    for currentroot in _try_heuristics(factors[0]):
  File "/home/eward/se/sympy/polys/polyroots.py", line 961, in _try_heuristics
    result += roots_quartic(f)
  File "/home/eward/se/sympy/polys/polyroots.py", line 315, in roots_quartic
    roots([1, e, g], multiple=True)]
ValueError: not enough values to unpack (expected 2, got 1)
```

Since [1, e, g] is a quadratic, `roots_quartic` is expecting two results on line 315. `roots` does not behave as expected if `e` is not expanded first:

```
>>> e = -12*I - 3*(-4 + 4*I)**2/8
>>> expand(e)
0
>>> roots([1, e, 0], multiple=True)
[0]
>>> roots([1, expand(e), 0], multiple=True)
[0, 0]
```

**Comment by oscargus** [comment]
`e = _mexpand(b - 3*a2/8)` seems to do the trick here. (`_mexpand` is simpler and faster than `expand` if I understand it correctly...)

**Comment by oscarbenjamin** [comment]
This issue goes back at least as far as sympy 1.2. Clearly it is an issue but it is a longstanding one and not a regression so I don't think it needs to hold up the 1.5 release
