### ISSUE TITLE
non-canonical Piecewise results

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#17486]
I get one of two alternating forms when entering, repeatedly, the following expression in the same session:
```python
>>> Piecewise((nan, ITE(ceiling(oo/c) <= 0, True, ITE(c > 0, Eq(c, 0), False))))

Piecewise((nan, ITE(ceiling(oo/c) <= 0, True, ITE(c > 0, Eq(c, 0), False))))
>>> Piecewise((nan, ITE(ceiling(oo/c) <= 0, True, ITE(c > 0, Eq(c, 0), False))))

Piecewise((nan, c < 0))
```
Not sure where the indeterminism is located.

**Comment by oscargus** [comment]
Third time I got an exception:

```
Piecewise((nan, ITE(ceiling(oo/c) <= 0, True, ITE(c > 0, Eq(c, 0), False))))
Traceback (most recent call last):

  File "<ipython-input-6-0463ef9cea8b>", line 1, in <module>
    Piecewise((nan, ITE(ceiling(oo/c) <= 0, True, ITE(c > 0, Eq(c, 0), False))))

  File "C:\Users\Oscar\sympy\sympy\functions\elementary\piecewise.py", line 139, in __new__
    r = cls.eval(*newargs)

  File "C:\Users\Oscar\sympy\sympy\functions\elementary\piecewise.py", line 190, in eval
    c = c.as_set().as_relational(x)

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 159, in as_set
    return self.subs(reps)._eval_as_set()

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 1417, in _eval_as_set
    return self.to_nnf().as_set()

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 150, in as_set
    if periodicity(r, x) not in (0, None):

  File "C:\Users\Oscar\sympy\sympy\calculus\util.py", line 539, in periodicity
    g = compogen(g_s[start_index:], symbol)

  File "C:\Users\Oscar\sympy\sympy\solvers\decompogen.py", line 98, in compogen
    foo = g_s[0].subs(symbol, g_s[1])

  File "C:\Users\Oscar\sympy\sympy\core\basic.py", line 1002, in subs
    rv = rv._subs(old, new, **kwargs)

  File "C:\Users\Oscar\sympy\sympy\core\basic.py", line 1116, in _subs
    rv = fallback(self, old, new)

  File "C:\Users\Oscar\sympy\sympy\core\basic.py", line 1093, in fallback
    rv = self.func(*args)

  File "C:\Users\Oscar\sympy\sympy\core\function.py", line 462, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)

  File "C:\Users\Oscar\sympy\sympy\core\function.py", line 277, in __new__
    evaluated = cls.eval(*args)

  File "C:\Users\Oscar\sympy\sympy\functions\elementary\integers.py", line 26, in eval
    if arg.is_imaginary or (S.ImaginaryUnit*arg).is_real:

  File "C:\Users\Oscar\sympy\sympy\core\assumptions.py", line 266, in getit
    return _ask(fact, self)

  File "C:\Users\Oscar\sympy\sympy\core\assumptions.py", line 321, in _ask
    _ask(pk, obj)

  File "C:\Users\Oscar\sympy\sympy\core\assumptions.py", line 311, in _ask
    assumptions.deduce_all_facts(((fact, a),))

  File "C:\Users\Oscar\sympy\sympy\core\facts.py", line 522, in deduce_all_facts
    if not self._tell(k, v) or v is None:

  File "C:\Users\Oscar\sympy\sympy\core\facts.py", line 493, in _tell
    raise InconsistentAssumptions(self, k, v)

InconsistentAssumptions: {
	algebraic: False,
	commutative: True,
	complex: False,
	composite: False,
	even: False,
	extended_negative: None,
	extended_positive: None,
	extended_real: None,
	imaginary: False,
	integer: False,
	irrational: False,
	negative: False,
	nonnegative: False,
	nonpositive: False,
	nonzero: False,
	odd: False,
	positive: False,
	prime: False,
	rational: False,
	real: False,
	transcendental: False,
	zero: False}, imaginary=True
```

(`c` defined without any assumptions.)

**Comment by oscargus** [comment]
With `c` extended_real this shows up after a while:

```
Piecewise((nan, ITE(ceiling(oo/c) <= 0, True, ITE(c > 0, Eq(c, 0), False))))
Traceback (most recent call last):

  File "<ipython-input-12-0463ef9cea8b>", line 1, in <module>
    Piecewise((nan, ITE(ceiling(oo/c) <= 0, True, ITE(c > 0, Eq(c, 0), False))))

  File "C:\Users\Oscar\sympy\sympy\functions\elementary\piecewise.py", line 139, in __new__
    r = cls.eval(*newargs)

  File "C:\Users\Oscar\sympy\sympy\functions\elementary\piecewise.py", line 190, in eval
    c = c.as_set().as_relational(x)

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 159, in as_set
    return self.subs(reps)._eval_as_set()

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 1417, in _eval_as_set
    return self.to_nnf().as_set()

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 159, in as_set
    return self.subs(reps)._eval_as_set()

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 802, in _eval_as_set
    return Union(*[arg.as_set() for arg in self.args])

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 802, in <listcomp>
    return Union(*[arg.as_set() for arg in self.args])

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 159, in as_set
    return self.subs(reps)._eval_as_set()

  File "C:\Users\Oscar\sympy\sympy\core\relational.py", line 319, in _eval_as_set
    return solve_univariate_inequality(self, x, relational=False)

  File "C:\Users\Oscar\sympy\sympy\solvers\inequalities.py", line 638, in solve_univariate_inequality
    '''  % (expr.subs(gen, _gen), _gen)))

ValueError: 
ceiling(oo/c) <= 0 contains imaginary parts which cannot be made 0 for
any value of c satisfying the inequality, leading to relations like I
< 0.
```

(which I assume you've also got considering #17487)

**Comment by oscargus** [comment]
This may have something to do with it:

```
(oo*I).is_finite
Out[9]: True
```

```
 (oo*I*c).is_imaginary
```
leads to a similar error with `c = Symbol('c', non_zero=True, real=True)`.

I think it boils down to imaginary implying finite. Time for `extended_imaginary`...

**Comment by oscarbenjamin** [comment]
> This may have something to do with it:
> 
> ```
> (oo*I).is_finite
> Out[9]: True
> ```

I can't reproduce that:
```console
$ cat f.py 
from sympy import *
print((oo*I).is_finite)
$ python f.py 
False
```
Do it 100 times:
```console
$ for x in `seq 1 100`; do python f.py; done
(lots of False)
```

**Comment by oscargus** [comment]
It might be that `(oo*I).is_finite` was a result of other errors/caching as I cannot get that anymore.

```
(oo*I).is_imaginary
Out[6]: False
```

Happens, though which combined with 
https://github.com/sympy/sympy/blob/fa1b3f9788e3601f9354c423f5bc1125a4925ddf/sympy/functions/elementary/integers.py#L26
I think is the source of the issue. Leading to that expressions involving `oo` and `I` are not properly rounded (assumption inconsistencies).

**Comment by oscarbenjamin** [comment]
I can't reproduce any of the problems referred to here
