### ISSUE TITLE
ValueError solving quartic polynomial (from sift)

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#17483]
While playing around with #17454 and #17482 I found the following:

```
from sympy import *
x = Symbol('x')
s = solve(((pi - x - sqrt(2)*I)**3*(sin(1) + x - sqrt(pi)*I)).expand(), x)
```

leads to 

```
Traceback (most recent call last):

  File "<ipython-input-2-d1e3e67ec6be>", line 2, in <module>
    s = solve(((pi - x - sqrt(2)*I)**3*(sin(1) + x - sqrt(pi)*I)).expand(), x)

  File "/nobackup/data/sympy/sympy/solvers/solvers.py", line 1171, in solve
    solution = _solve(f[0], *symbols, **flags)

  File "/nobackup/data/sympy/sympy/solvers/solvers.py", line 1657, in _solve
    soln = roots(poly, **solvers)

  File "/nobackup/data/sympy/sympy/polys/polyroots.py", line 1017, in roots
    for currentroot in _try_decompose(f):

  File "/nobackup/data/sympy/sympy/polys/polyroots.py", line 915, in _try_decompose
    for currentroot in _try_heuristics(factors[0]):

  File "/nobackup/data/sympy/sympy/polys/polyroots.py", line 961, in _try_heuristics
    result += roots_quartic(f)

  File "/nobackup/data/sympy/sympy/polys/polyroots.py", line 322, in roots_quartic
    sols = _roots_quartic_euler(e, f, g, aon4)

  File "/nobackup/data/sympy/sympy/polys/polyroots.py", line 228, in _roots_quartic_euler
    xsols = list(roots(Poly(eq, x), cubics=False).keys())

  File "/nobackup/data/sympy/sympy/polys/polyroots.py", line 1003, in roots
    res = to_rational_coeffs(f)

  File "/nobackup/data/sympy/sympy/polys/polytools.py", line 6153, in to_rational_coeffs
    r = _try_translate(f, f1)

  File "/nobackup/data/sympy/sympy/polys/polytools.py", line 6121, in _try_translate
    c1, c2 = sift(args, lambda z: z.is_rational, binary=True)

  File "/nobackup/data/sympy/sympy/utilities/iterables.py", line 706, in sift
    raise ValueError('keyfunc gave non-binary output')

ValueError: keyfunc gave non-binary output
```

caused by `is_rational` returning `None`. This should be a quite common possible error for `sift`:ing with `is_xx`, so not sure if it should be dealt with in `sift` or in `_try_translate`.

(And, yes, it is a made up example, but not unrealistic.)

**Comment by Soniyanayak51** [comment]
@oscargus should there be a check in _try_translate for when z.is_rational returns neither true nor false?

**Comment by oscargus** [comment]
I think that there are (possibly) two things to be solved here.

1) `sift` (which is basically a utility function to filter stuff in bins depending on a key function) require the result of the key function to be either `True` or `False` if the `binary` optional keyword is set. If not, it will filter in three bins, but the order is unknown. I'm thinking that maybe one should add another keyword (`binarynone`?) which sorts in three bins with defined order so that one can unpack them as `truebin, falsebin, nonebin = sift(..., binarynone=True)`.

2) `_try_translate` should indeed do something clever for the `None` results. Unclear what (since I haven't checked the code at all), but probably `None` and `False` should be dealt with in the same way if I'm about to guess.

Note that it is possible to avoid 1) by just not passing `binary=True` to `sift`. Instead one will have to do something like
```
s = sift(...)
c1 = s[True]
c2 = s[False]
c3 = s[None]
```
(and probably check that the key exists or use some get-method with default value or check if a defaultdict is used.)

Solving only 2. would solve the issue (I think), but solving 1. would be of great use for later issues.

Ping @smichr, any opinions on a three-valued binary/None `sift`-flag?

**Comment by smichr** [comment]
> and probably check that the key exists

Since defaultdict is used a key will always be there so one can do:
```python
>>> s=sift([x], lambda x: x.is_rational)
>>> c1,c2,c3 = (s[i] for i in (True, False, None))
>>> c1,c2,c3
([], [], [x])
```

**Comment by smichr** [comment]
As for another flag...maybe `fuzzy` could be used and then the return would be results for True, False and None.

**Comment by Soniyanayak51** [comment]
> >>> s=sift([x], lambda x: x.is_rational)
> >>> c1,c2,c3 = (s[i] for i in (True, False, None))

Right now in _try_translate is:
           else:
                args = [c]
            c1, c2 = sift(args, lambda z: z.is_rational, binary=True)
            alpha = -func(*c2)/n
            f2 = f1.shift(alpha)
            return alpha, f2
        return None
Should we add what you have suggested and handle c2 and c3 the same way?

**Comment by oscargus** [comment]
> Should we add what you have suggested and handle c2 and c3 the same way?

I think that is worth trying, yes. At least it should get rid of the `ValueError`.

Maybe it is possible to find a simpler polynomial that triggers the bug to use in testing. If not, the current one should be OK.

**Comment by oscargus** [comment]
The arguments that are being `sifted` are:
```
a = (S(9)/32, -3*pi**2/16, 3*pi/16, 3*cos(2)/32, -3*pi*sin(1)/8, 3*I*pi**(S(3)/2)/8, 3*sqrt(2)*sqrt(pi)/8, 3*sqrt(2)*I*pi/8, 3*sqrt(2)*I*sin(1)/8, 3*I*sqrt(pi)*sin(1)/8)
```

performing a `sift` (without `binary`)

```
sift(a, lambda z: z.is_rational)
```
gives
```
defaultdict(list,
            {True: [9/32],
             False: [-3*pi**2/16,
              3*pi/16,
              3*cos(2)/32,
              3*I*pi**(3/2)/8,
              3*sqrt(2)*sqrt(pi)/8,
              3*sqrt(2)*I*pi/8,
              3*sqrt(2)*I*sin(1)/8,
              3*I*sqrt(pi)*sin(1)/8],
             None: [-3*pi*sin(1)/8]})
```
so the assumption system cannot decide if `-3*pi*sin(1)/8` is `rational`. Hence, it should be OK to simply merge the `False` and `None` bins in this case.

It seems like most time is spent in `_try_rescale` which is sort of useless in the testing, but there is no clear way around it since `_try_translate` cannot be accessed directly AFAIK.

**Comment by oscargus** [comment]
Another way to improve the situation is to make `(-3*pi*sin(1)/8).is_rational` evaluate to `False`. It seems like SymPy knows that `sin(1)` is not rational and that `pi` is not rational, but when multiplied it is not known. As opposed to e.g. multiplying `sqrt(2)`and `sin(1)` or `sqrt(2)` and `pi`. So probably there is some special handling of multiplying `pi` and trigonometric functions.

```
In [2]: sin(1).is_rational
Out[2]: False

In [3]: sqrt(pi).is_rational
Out[3]: False

In [4]: pi.is_rational
Out[4]: False

In [5]: (pi*sin(1)).is_rational

In [6]: (pi*sqrt(2)).is_rational
Out[6]: False

In [7]: (pi*cos(2)).is_rational

In [8]: sin(1).is_zero
Out[8]: False

In [9]: (pi*sqrt(2)).is_rational
Out[9]: False

In [12]: (sqrt(2)*cos(pi/4, evaluate=False)).is_rational

In [13]: (sqrt(2)*cos(pi/5, evaluate=False)).is_rational

In [14]: (sqrt(2)*cos(2, evaluate=False)).is_rational
Out[14]: False

In [15]: (sqrt(2)*cos(1, evaluate=False)).is_rational
Out[15]: False

In [16]: (sqrt(2)*cos(1)).is_rational
Out[16]: False

In [17]: (pi*sqrt(2)*cos(1)).is_rational

In [18]: (pi*sqrt(2)).is_rational
Out[18]: False
```

(Not returning anything is `None`.)

Still, it would be good if the None-case is handled properly here and allowing a `fuzzy`-switch to `sift` will be beneficial in general.

**Comment by oscargus** [comment]
Btw, a very simple fix to just get away with the problem is to use:

` c1, c2 = sift(args, lambda z: z.is_rational is True, binary=True)`

but a better solution would be appreciated.

**Comment by oscargus** [comment]
This one currently seems to hang, aborting after a handful of minutes gives:
```
Traceback (most recent call last):

  Input In [1] in <module>
    s = solve(((pi - x - sqrt(2)*I)**3*(sin(1) + x - sqrt(pi)*I)).expand(), x)

  File ~\sympy\sympy\solvers\solvers.py:1106 in solve
    solution = _solve(f[0], *symbols, **flags)

  File ~\sympy\sympy\solvers\solvers.py:1632 in _solve
    soln = roots(poly, **solvers)

  File ~\sympy\sympy\polys\polyroots.py:1026 in roots
    _, factors = Poly(f.as_expr()).factor_list()

  File ~\sympy\sympy\polys\polytools.py:3342 in factor_list
    coeff, factors = f.rep.factor_list()

  File ~\sympy\sympy\polys\polyclasses.py:823 in factor_list
    coeff, factors = dmp_factor_list(f.rep, f.lev, f.dom)

  File ~\sympy\sympy\polys\factortools.py:1391 in dmp_factor_list
    coeff, factors = dmp_zz_i_factor(f, u, K0)

  File ~\sympy\sympy\polys\factortools.py:1206 in dmp_zz_i_factor
    coeff, factors = dmp_qq_i_factor(f, u, K1)

  File ~\sympy\sympy\polys\factortools.py:1195 in dmp_qq_i_factor
    coeff, factors = dmp_factor_list(f, u, K1)

  File ~\sympy\sympy\polys\factortools.py:1389 in dmp_factor_list
    coeff, factors = dmp_ext_factor(f, u, K0)

  File ~\sympy\sympy\polys\factortools.py:1265 in dmp_ext_factor
    f, F = dmp_sqf_part(f, u, K), f

  File ~\sympy\sympy\polys\sqfreetools.py:256 in dmp_sqf_part
    gcd = dmp_gcd(gcd, dmp_diff_in(f, 1, i, u, K), u, K)

  File ~\sympy\sympy\polys\euclidtools.py:1624 in dmp_gcd
    return dmp_inner_gcd(f, g, u, K)[0]

  File ~\sympy\sympy\polys\euclidtools.py:1583 in dmp_inner_gcd
    h, cff, cfg = _dmp_inner_gcd(f, g, u, K)

  File ~\sympy\sympy\polys\euclidtools.py:1548 in _dmp_inner_gcd
    return dmp_ff_prs_gcd(f, g, u, K)

  File ~\sympy\sympy\polys\euclidtools.py:1113 in dmp_ff_prs_gcd
    h = dmp_subresultants(F, G, u, K)[-1]

  File ~\sympy\sympy\polys\euclidtools.py:550 in dmp_subresultants
    return dmp_inner_subresultants(f, g, u, K)[0]

  File ~\sympy\sympy\polys\euclidtools.py:513 in dmp_inner_subresultants
    h = dmp_prem(f, g, u, K)

  File ~\sympy\sympy\polys\densearith.py:1237 in dmp_prem
    R = dmp_mul_term(r, lc_g, 0, u, K)

  File ~\sympy\sympy\polys\densearith.py:184 in dmp_mul_term
    return [ dmp_mul(cf, c, v, K) for cf in f ] + dmp_zeros(i, v, K)

  File ~\sympy\sympy\polys\densearith.py:184 in <listcomp>
    return [ dmp_mul(cf, c, v, K) for cf in f ] + dmp_zeros(i, v, K)

  File ~\sympy\sympy\polys\densearith.py:828 in dmp_mul
    coeff = dmp_add(coeff, dmp_mul(f[j], g[i - j], v, K), v, K)

  File ~\sympy\sympy\polys\densearith.py:828 in dmp_mul
    coeff = dmp_add(coeff, dmp_mul(f[j], g[i - j], v, K), v, K)

  File ~\sympy\sympy\polys\densearith.py:828 in dmp_mul
    coeff = dmp_add(coeff, dmp_mul(f[j], g[i - j], v, K), v, K)

  File ~\sympy\sympy\polys\densearith.py:807 in dmp_mul
    return dup_mul(f, g, K)

  File ~\sympy\sympy\polys\densearith.py:767 in dup_mul
    coeff += f[j]*g[i - j]

  File ~\sympy\sympy\polys\polyclasses.py:1739 in __mul__
    return f.mul(g)

  File ~\sympy\sympy\polys\polyclasses.py:1650 in mul
    return per(dup_rem(dup_mul(F, G, dom), mod, dom))

  File ~\sympy\sympy\polys\densearith.py:1557 in dup_rem
    return dup_div(f, g, K)[1]

  File ~\sympy\sympy\polys\densearith.py:1534 in dup_div
    return dup_ff_div(f, g, K)

  File ~\sympy\sympy\polys\densearith.py:1446 in dup_ff_div
    _dr, dr = dr, dup_degree(r)

  File ~\sympy\sympy\polys\densebasic.py:154 in dup_degree
    return len(f) - 1
```

Not sure if it means that the original error has been fixed and it hangs later on or if something else has changed that makes it hang without/before hitting that code.
