### ISSUE TITLE
Hard crash from pyglet doctests

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17497]
Running the doctests on OSX under pytest I got the crash below from the pygletplot tests:
```
$ pytest --doctest-plus -k 'not test_'
...
sympy/physics/vector/vector.py .............                                                                               [ 60%]
sympy/plotting/experimental_lambdify.py ..                                                                                 [ 60%]
sympy/plotting/plot.py .........                                                                                           [ 60%]
sympy/plotting/plot_implicit.py .                                                                                          [ 60%]
sympy/plotting/pygletplot/__init__.py F                                                                                    [ 60%]
sympy/plotting/pygletplot/plot.py Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/enojb/.local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/enojb/.local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/plotting/pygletplot/managed_window.py", line 56, in __event_loop__
    clock.set_fps_limit(self.fps_limit)
AttributeError: 'Clock' object has no attribute 'set_fps_limit'

Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1561.60.100/AppKit.subproj/NSView.m, line 14485.
Illegal instruction: 4
```
This crashed hard enough that pytest was unable to recover and didn't run the remaining tests or report details on the failures that had already occurred.

**Comment by asmeurer** [comment]
For me it opens up a bunch of windows and hangs until I kill it

```
$./bin/doctest sympy/plotting/
==================================================================== test process starts =====================================================================
executable:         /Users/aaronmeurer/anaconda3/bin/python  (3.6.7-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python
numpy:              1.16.2
hash randomization: on (PYTHONHASHSEED=1362783095)

sympy/plotting/plot.py[9] .........                                                                                                                       [OK]
sympy/plotting/experimental_lambdify.py[2] ..                                                                                                             [OK]
sympy/plotting/plot_implicit.py[1] .                                                                                                                      [OK]
sympy/plotting/pygletplot/plot.py[2] .2019-08-23 17:08:57.956 python[14156:8357973] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
        0   AppKit                              0x00007fff2aafb607 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 378
        1   AppKit                              0x00007fff2aaf89f7 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1479
        2   AppKit                              0x00007fff2aaf842a -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
        3   libffi.6.dylib                      0x000000010ee02884 ffi_call_unix64 + 76
        4   ???                                 0x00007000082a13a0 0x0 + 123145439286176
)
F                                                                                                                 [FAIL]
sympy/plotting/pygletplot/__init__.py[1] F                                                                                                              [FAIL]

______________________________________________________________________________________________________________________________________________________________
_________________________________________________________ sympy.plotting.pygletplot.plot.PygletPlot __________________________________________________________
File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/plotting/pygletplot/plot.py", line 96, in sympy.plotting.pygletplot.plot.PygletPlot
Failed example:
    Plot(1, mode='spherical')
Expected nothing
Got:
    [0]: 1, 'mode=cartesian'
______________________________________________________________________________________________________________________________________________________________
_______________________________________________________ sympy.plotting.pygletplot.__init__.PygletPlot ________________________________________________________
File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/plotting/pygletplot/__init__.py", line 79, in sympy.plotting.pygletplot.__init__.PygletPlot
Failed example:
    Plot(1, mode='spherical')
Expected nothing
Got:
    [0]: 1, 'mode=cartesian'

==================================================== tests finished: 13 passed, 2 failed, in 8.01 seconds ====================================================
DO *NOT* COMMIT!
2019-08-23 17:08:59.720 python[14156:8357973] WARNING: nextEventMatchingMask should only be called from the Main Thread! This will throw an exception in the future.

^CException ignored in: <module 'threading' from '/Users/aaronmeurer/anaconda3/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/Users/aaronmeurer/anaconda3/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/Users/aaronmeurer/anaconda3/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

The tests should not open GUI windows for plots.

**Comment by asmeurer** [comment]
@oscargus

**Comment by oscargus** [comment]
The fps-stuff is fixed in #17362 (#17351). Seems like the Pyglet tests are running on Travis now, but some other tests fail for unknown reason.

There is support in doctest (or runtests.py) to monkey patch the window class, but for some reason it doesn't work. It may have to do with the tests not running in the same Python instance, but that is more a guess based on the behavior.

**Comment by asmeurer** [comment]
What can be done about this? This seems to be the biggest issue blocking a release right now.

**Comment by oscarbenjamin** [comment]
I think we should just disable these tests. I don't see why we need doctests for pyglet.

**Comment by asmeurer** [comment]
If we can't get a fix for a hard crash soon, we should just disable them, with a note. 

I still think we should deprecate and remove the pyglet backend, but that's another discussion, and it's too soon before the release to make a decision like that IMO.

**Comment by oscarbenjamin** [comment]
I've opened #17923 which disables the pygletplot doctests

**Comment by oscarbenjamin** [comment]
I expected this to be automatically closed. Maybe that only happens when merging into master...
