### ISSUE TITLE
Condition set is not iterable

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#17569]
```
eq = -x - 1166245699035384121*y**5*(14407/14404 - 649*y/28808000)**(32/125)/(1984109067270940265676800000000000000000*(41046783/500000 - 1861981*y/1000000000)) + 25889216927585175703*y**4*(14407/14404 - 649*y/28808000)**(32/125)/(198410906727094026567680000000000000*(41046783/500000 - 1861981*y/1000000000)) - 574708703044252120729*y**3*(14407/14404 - 649*y/28808000)**(32/125)/(49602726681773506641920000000000*(41046783/500000 - 1861981*y/1000000000)) + 12757824783911464257847*y**2*(14407/14404 - 649*y/28808000)**(32/125)/(24801363340886753320960000000*(41046783/500000 - 1861981*y/1000000000)) - 283207984070589315196921*y*(14407/14404 - 649*y/28808000)**(32/125)/(24801363340886753320960000*(41046783/500000 - 1861981*y/1000000000)) + 6286868145616302409926103*(14407/14404 - 649*y/28808000)**(32/125)/(62003408352216883302400*(41046783/500000 - 1861981*y/1000000000))
solveset(eq,y)
```

**Comment by oscarbenjamin** [comment]
I guess you're seeing some kind of error?

I don't see any error for this on either master or version 1.4:
```julia
In [2]: eq = -x - 1166245699035384121*y**5*(14407/14404 - 649*y/28808000)**(32/125)/(1984109067270940265676800000000000000000*(410
   ...: 46783/500000 - 1861981*y/1000000000)) + 25889216927585175703*y**4*(14407/14404 - 649*y/28808000)**(32/125)/(19841090672709
   ...: 4026567680000000000000*(41046783/500000 - 1861981*y/1000000000)) - 574708703044252120729*y**3*(14407/14404 - 649*y/2880800
   ...: 0)**(32/125)/(49602726681773506641920000000000*(41046783/500000 - 1861981*y/1000000000)) + 12757824783911464257847*y**2*(1
   ...: 4407/14404 - 649*y/28808000)**(32/125)/(24801363340886753320960000000*(41046783/500000 - 1861981*y/1000000000)) - 28320798
   ...: 4070589315196921*y*(14407/14404 - 649*y/28808000)**(32/125)/(24801363340886753320960000*(41046783/500000 - 1861981*y/10000
   ...: 00000)) + 6286868145616302409926103*(14407/14404 - 649*y/28808000)**(32/125)/(62003408352216883302400*(41046783/500000 - 1
   ...: 861981*y/1000000000)) 
   ...: solveset(eq,y)                                                                                                            
Out[2]: 
⎧                                                                                                                               
⎨y | y ∊ ℂ ∧ -x⋅(3.97662569983412e+29 - 9019466272427276920959848⋅y)⋅(6.36260111973459e+30 - 144311460358836430735357568⋅y)⋅(5.0
⎩                                                                                                                               

                                                                                                                                
9008089578767e+31 - 1154491682870691445882860544⋅y)⋅(4.07206471663013e+33 - 92359334629655315670628843520⋅y)⋅(1.62882588665205e+
                                                                                                                                

                                                                                                                                
37 - 369437338518621262682515374080000⋅y)⋅(1.62882588665205e+41 - 3694373385186212626825153740800000000⋅y) - 1.16630787671586e+1
                                                                                                                                

   5                            0.256                                                                                           
8⋅y ⋅(1 - 2.25237731658222e-5⋅y)     ⋅(3.97662569983412e+29 - 9019466272427276920959848⋅y)⋅(6.36260111973459e+30 - 1443114603588
                                                                                                                                

                                                                                                                                
36430735357568⋅y)⋅(5.09008089578767e+31 - 1154491682870691445882860544⋅y)⋅(4.07206471663013e+33 - 92359334629655315670628843520⋅
                                                                                                                                

                                                                                        4                            0.256      
y)⋅(1.62882588665205e+37 - 369437338518621262682515374080000⋅y) + 2.58905971954475e+19⋅y ⋅(1 - 2.25237731658222e-5⋅y)     ⋅(3.97
                                                                                                                                

                                                                                                                                
662569983412e+29 - 9019466272427276920959848⋅y)⋅(6.36260111973459e+30 - 144311460358836430735357568⋅y)⋅(5.09008089578767e+31 - 1
                                                                                                                                

                                                                                                                                
154491682870691445882860544⋅y)⋅(4.07206471663013e+33 - 92359334629655315670628843520⋅y)⋅(1.62882588665205e+41 - 3694373385186212
                                                                                                                                

                                                 3                            0.256                                             
626825153740800000000⋅y) - 5.74739343289386e+20⋅y ⋅(1 - 2.25237731658222e-5⋅y)     ⋅(3.97662569983412e+29 - 90194662724272769209
                                                                                                                                

                                                                                                                                
59848⋅y)⋅(6.36260111973459e+30 - 144311460358836430735357568⋅y)⋅(5.09008089578767e+31 - 1154491682870691445882860544⋅y)⋅(1.62882
                                                                                                                                

                                                                                                                                
588665205e+37 - 369437338518621262682515374080000⋅y)⋅(1.62882588665205e+41 - 3694373385186212626825153740800000000⋅y) + 3.189626
                                                                                                                                

              2                            0.256                                                                                
23989607e+23⋅y ⋅(1 - 2.25237731658222e-5⋅y)     ⋅(3.97662569983412e+29 - 9019466272427276920959848⋅y)⋅(6.36260111973459e+30 - 14
                                                                                                                                

                                                                                                                                
4311460358836430735357568⋅y)⋅(4.07206471663013e+33 - 92359334629655315670628843520⋅y)⋅(1.62882588665205e+37 - 369437338518621262
                                                                                                                                

                                                                                                                                
682515374080000⋅y)⋅(1.62882588665205e+41 - 3694373385186212626825153740800000000⋅y) - 8.85072134787801e+26⋅y⋅(1 - 2.252377316582
                                                                                                                                

        0.256                                                                                                                   
22e-5⋅y)     ⋅(3.97662569983412e+29 - 9019466272427276920959848⋅y)⋅(5.09008089578767e+31 - 1154491682870691445882860544⋅y)⋅(4.07
                                                                                                                                

                                                                                                                                
206471663013e+33 - 92359334629655315670628843520⋅y)⋅(1.62882588665205e+37 - 369437338518621262682515374080000⋅y)⋅(1.628825886652
                                                                                                                                

                                                                                                    0.256                       
05e+41 - 3694373385186212626825153740800000000⋅y) + 4.91187759857005e+29⋅(1 - 2.25237731658222e-5⋅y)     ⋅(6.36260111973459e+30 
                                                                                                                                

                                                                                                                                
- 144311460358836430735357568⋅y)⋅(5.09008089578767e+31 - 1154491682870691445882860544⋅y)⋅(4.07206471663013e+33 - 923593346296553
                                                                                                                                

                                                                                                                                
15670628843520⋅y)⋅(1.62882588665205e+37 - 369437338518621262682515374080000⋅y)⋅(1.62882588665205e+41 - 3694373385186212626825153
                                                                                                                                

                   ⎫                                       
740800000000⋅y) = 0⎬ \ {44089.3682588598, 44089.3682588598}
                   ⎭ 
```

**Comment by proy87** [comment]
I tested it on live.sympy.org

**Comment by oscarbenjamin** [comment]
Okay I see it. I tested on live.sympy.org and I get:
```
>>> eq = -x - 1166245699035384121*y**5*(14407/14404 - 649*y/28808000)**(32/125)/(1984109067270940265676800000000000000000*(41046783/500000 - 1861981*y/1000000000)) + 25889216927585175703*y**4*(14407/14404 - 649*y/28808000)**(32/125)/(198410906727094026567680000000000000*(41046783/500000 - 1861981*y/1000000000)) - 574708703044252120729*y**3*(14407/14404 - 649*y/28808000)**(32/125)/(49602726681773506641920000000000*(41046783/500000 - 1861981*y/1000000000)) + 12757824783911464257847*y**2*(14407/14404 - 649*y/28808000)**(32/125)/(24801363340886753320960000000*(41046783/500000 - 1861981*y/1000000000)) - 283207984070589315196921*y*(14407/14404 - 649*y/28808000)**(32/125)/(24801363340886753320960000*(41046783/500000 - 1861981*y/1000000000)) + 6286868145616302409926103*(14407/14404 - 649*y/28808000)**(32/125)/(62003408352216883302400*(41046783/500000 - 1861981*y/1000000000))
... solveset(eq,y)
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/solvers/solveset.py", line 1714, in solveset
    return _solveset(f, symbol, domain, _check=True)
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/solvers/solveset.py", line 958, in _solveset
    result_rational = _solve_as_rational(equation, symbol, domain)
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/solvers/solveset.py", line 510, in _solve_as_rational
    valid_solns = _solveset(g, symbol, domain)
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/solvers/solveset.py", line 954, in _solveset
    solver)
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/solvers/solveset.py", line 751, in _solve_radical
    for s in result:
  File "/base/data/home/apps/s~sympy-live-hrd/57.417397408462217066/sympy/sympy/sets/fancysets.py", line 234, in __iter__
    for i in self.base_set:
TypeError: 'ConditionSet' object is not iterable
```
I don't see that on master or 1.4 when running locally though.

The calculation takes a while on sympy.live.org and rerunning it I get:
```
>>> solveset(eq, y)
Error: Operation timed out.
```
That makes me wonder if some kind of timeout exception is being raised and then caught in the wrong place by overly broad exception handling similar to #17543. A bare except could easily lead to this kind of wrong result.
