### ISSUE TITLE
Solve should be able to handle equations with Tuples in

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17570]
```
>>> from sympy import *
>>> x = Symbol('x')

>>> solve(Eq(x, (1, 2)), x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 982, in solve
    fi = fi.rewrite(Add, evaluate=False)
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1804, in rewrite
    return self._eval_rewrite(None, rule, **hints)
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1711, in _eval_rewrite
    rewritten = getattr(self, rule)(*args, **hints)
  File "/Users/enojb/current/sympy/sympy/sympy/core/relational.py", line 511, in _eval_rewrite_as_Add
    args = Add.make_args(L) + Add.make_args(-R)
TypeError: bad operand type for unary -: 'Tuple'

>>> solve(Eq((1, x), (1, 2)), x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 982, in solve
    fi = fi.rewrite(Add, evaluate=False)
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1804, in rewrite
    return self._eval_rewrite(None, rule, **hints)
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1711, in _eval_rewrite
    rewritten = getattr(self, rule)(*args, **hints)
  File "/Users/enojb/current/sympy/sympy/sympy/core/relational.py", line 511, in _eval_rewrite_as_Add
    args = Add.make_args(L) + Add.make_args(-R)
TypeError: bad operand type for unary -: 'Tuple'

>>> solve(Eq((1, 2), x), x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 1169, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 1506, in _solve
    f_num, sol = solve_linear(f, symbols=symbols)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 2081, in solve_linear
    n, d = eq.as_numer_denom()
  File "/Users/enojb/current/sympy/sympy/sympy/core/add.py", line 467, in as_numer_denom
    content, expr = self.primitive()
  File "/Users/enojb/current/sympy/sympy/sympy/core/add.py", line 936, in primitive
    c, m = a.as_coeff_Mul()
AttributeError: 'Tuple' object has no attribute 'as_coeff_Mul'
```

**Comment by sylee957** [comment]
I have made basic method to expand either an equality or an unequality of a Tuple in https://github.com/sylee957/sympy/tree/add_tuple_expand, but have not worked on solvers yet.
But I guess there would only be simple cases to consider.

**Comment by oscarbenjamin** [comment]
The cases would need to be simple I think. A Tuple can't be used in arithmetic/functions and can only be equal to another Tuple or a symbol. I think it just needs a method to recursively turn a Tuple equation into expanded equations:
```python
def expand_eqs(eq):
    lhs, rhs = eq.lhs, eq.rhs
    eqns = []
    if isinstance(lhs, Tuple) and isinstance(rhs, Tuple):
        if len(lhs) != len(rhs):
            return [S.false]
        for l, r in zip(lhs, rhs):
            eqns.extend(expand_eqs(Eq(l, r)))
    elif isinstance(lhs, Tuple) or isinstance(rhs, Tuple):
        if isinstance(lhs, Tuple):
            lhs, rhs = rhs, lhs
        if not lhs.is_symbol or rhs.has(lhs):
            return [S.false]
        eqns.append(Eq(lhs, rhs))
    else:
        eqns.append(eq)

    return eqns
```
This gives:
```julia
In [72]: expand_eqs(Eq((x, (2, 3)), (z, z)))
Out[72]: [x = z, z = (2, 3)]

In [73]: expand_eqs(Eq((x, y, z), (1, 2, 3)))
Out[73]: [x = 1, y = 2, z = 3]

In [74]: expand_eqs(Eq(x, (x, x)))
Out[74]: [False]

In [89]: expand_eqs(Eq(1, (2, 3)))
Out[89]: [False]
```
The equations that involve a symbol inside the tuple can be resolved by substitution later:
```julia
In [86]: expand_eqs(Eq((x, z), ((1, z), 3)))
Out[86]: [x = (1, z), z = 3]

In [87]: eq1, eq2 = expand_eqs(Eq((x, z), ((1, z), 3)))

In [88]: eq1.subs(z, solve(eq2, z)[0])
Out[88]: x = (1, 3)
```

Also relevant: I've added `Tuple._eval_Eq` in #17557
