### ISSUE TITLE
solveset and _is_exponential with multiplied powers

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#17604]
```
>>> from sympy import *
>>> from sympy.solvers.solveset import _is_exponential, _solve_exponential
>>> x = Symbol('x')
>>> lhs = -2**(3*x/11)*exp(x/11) + pi**(x/11)
>>> _is_exponential(lhs, x)
True
>>> _solve_exponential(lhs, 0, x, S.Complexes)
Traceback (most recent call last):
  File "test.py", line 88, in <module>
    print(_solve_exponential(lhs, 0, x, S.Complexes))
  File "/home/eward/se/sympy/solvers/solveset.py", line 1415, in _solve_exponential
    b_base, b_exp = b_term.base, b_term.exp
AttributeError: 'Mul' object has no attribute 'base'
```

`_solve_exponential` assumes that it's getting a sum of two `Pow`s and doesn't check further, but `_is_exponential` is more loose with what an "exponential" equation is.

This can be an issue on line 1821:

https://github.com/sympy/sympy/blob/e53c5b7f14f470fc517a17636abfe8f6720f5dc8/sympy/solvers/solveset.py#L1821-L1822

**Comment by oscargus** [comment]
This seems to be fixed in current master:

```
In [12]: _solve_exponential(lhs, 0, x, S.Complexes)
Out[12]: FiniteSet(0)
```
