### ISSUE TITLE
parse_latex 'NoneType' object is not callable

### ISSUE THREAD

**Issue by jarmarshall** [sympy/sympy#17629]
Observing this under Python 3.6.9 with Sympy 1.4 and was asked to submit as an issue - have not found a minimal environment that gives rise to this so including the full environment from my current project.

```
>>> from sympy.parsing.latex import parse_latex
>>> parse_latex('x')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda3/envs/mumot-env/lib/python3.6/site-packages/sympy/parsing/latex/__init__.py", line 34, in parse_latex
    return _latex.parse_latex(s)
  File "//anaconda3/envs/mumot-env/lib/python3.6/site-packages/sympy/parsing/latex/_parse_latex_antlr.py", line 74, in parse_latex
    lex = LaTeXLexer(stream)
TypeError: 'NoneType' object is not callable
```

Environment (sorry, there's quite a lot of stuff in there:
```
# packages in environment at //anaconda3/envs/mumot-env:
#
# Name                    Version                   Build  Channel
antlr4-python3-runtime    4.5.3                    pypi_0    pypi
appnope                   0.1.0                    pypi_0    pypi
attrs                     19.1.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.14.12              hc4e6be7_4  
certifi                   2016.9.26                py36_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.6.0                    pypi_0    pypi
entrypoints               0.3                   py36_1000    conda-forge
expat                     2.2.6                h0a44026_0  
fontconfig                2.13.0               h5d5b041_1  
freetype                  2.9.1                hb4e5f40_0  
fribidi                   1.0.5                h1de35cc_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.56.2               hd9629dc_0  
graphite2                 1.3.13               h2098e52_0  
graphviz                  2.40.1               hefbbd9a_2  
harfbuzz                  1.8.8                hb8d4a28_0  
icu                       58.2                 h4b95b61_1  
ipykernel                 4.6.1                    pypi_0    pypi
ipython                   7.8.0            py36h5ca1d4c_0    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                    pypi_0    pypi
jedi                      0.15.1                   py36_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9b                   he5867d9_2  
jsonschema                3.0.2                    py36_0    conda-forge
jupyter-client            5.3.3                    pypi_0    pypi
jupyter-contrib-core      0.3.3                    pypi_0    pypi
jupyter-contrib-nbextensions 0.5.1                    pypi_0    pypi
jupyter-core              4.5.0                    pypi_0    pypi
jupyter-highlight-selected-word 0.2.0                    pypi_0    pypi
jupyter-latex-envs        1.4.6                    pypi_0    pypi
jupyter-nbextensions-configurator 0.4.1                    pypi_0    pypi
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py36_0    conda-forge
kiwisolver                1.1.0                    pypi_0    pypi
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.17               h01d97ff_0    conda-forge
libtiff                   4.0.10               hcb84e12_2  
libxml2                   2.9.9                hf6e021a_1  
lxml                      4.4.1                    pypi_0    pypi
markupsafe                1.1.1            py36h1de35cc_0    conda-forge
matplotlib                3.1.1                    pypi_0    pypi
mistune                   0.8.4           py36h1de35cc_1000    conda-forge
mpmath                    1.1.0                    pypi_0    pypi
mumot                     1.0.0                    pypi_0    pypi
nbconvert                 5.6.0                    py36_1    conda-forge
nbformat                  4.4.0                    pypi_0    pypi
ncurses                   6.1                  h0a44026_1  
networkx                  2.3                      pypi_0    pypi
notebook                  5.4.1                    pypi_0    pypi
numpy                     1.17.2                   pypi_0    pypi
openssl                   1.1.1c               h01d97ff_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                    pypi_0    pypi
pango                     1.42.4               h060686c_0  
parso                     0.5.1                      py_0    conda-forge
pcre                      8.43                 h0a44026_0  
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                    pypi_0    pypi
pip                       19.2.2                   py36_0  
pixman                    0.38.0               h1de35cc_0  
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pydstool                  0.90.3                   pypi_0    pypi
pygments                  2.4.2                      py_0    conda-forge
pyparsing                 2.4.2                    pypi_0    pypi
pyrsistent                0.15.4           py36h01d97ff_0    conda-forge
python                    3.6.9                h359304d_0  
python-dateutil           2.8.0                      py_0    conda-forge
python-graphviz           0.13                     pypi_0    pypi
pyyaml                    5.1.2                    pypi_0    pypi
pyzmq                     16.0.4                   pypi_0    pypi
readline                  7.0                  h1de35cc_5  
scipy                     1.3.1                    pypi_0    pypi
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.0.1                   py36_0  
six                       1.12.0                   pypi_0    pypi
sqlite                    3.29.0               ha441bb4_0  
sympy                     1.4                      pypi_0    pypi
terminado                 0.8.2                    pypi_0    pypi
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.8                ha441bb4_0  
tornado                   4.5.3                    pypi_0    pypi
traitlets                 4.3.2                    pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.33.4                   py36_0  
widgetsnbextension        3.5.1                    pypi_0    pypi
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7             h1de35cc_1001    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0  
```

**Comment by asmeurer** [comment]
The real exception is swallowed by this https://github.com/sympy/sympy/blob/58e78209c8577b9890e957b624466e5beed7eb08/sympy/parsing/latex/_parse_latex_antlr.py#L19. 

That really should be looking for ImportError, but since the function already has a check for antlr at the top, why are those lines needed at all?

**Comment by asmeurer** [comment]
@jarmarshall can you comment out the `except Exception` line to see what the real error it is masking is?

**Comment by oscarbenjamin** [comment]
Grrr. We really need to clean up exception handling!

```console
$ git grep 'except Exception' | wc -l
      75
```

**Comment by asmeurer** [comment]
Yeah and the handling of the optional dependency here is bad even without the `except Exception`. I think I mentioned this on another issue, but we should write a guide on how to properly write submodules that require optional dependencies. Things should work so that

- The dependency really is optional
- The tests pass if the dependency is installed or not (and it should only be installed in the optional dependency build on Travis to test this)
- The function gives a good error message if the dependency is not installed
- If possible the error should come from using the function(s) in the submodule, rather than from importing it. That way other submodules can import the functions from the submodule at the top level without also having to do ImportError checks. 
- The exception guard should be ImportError only. Any other error should be bubbled up, as doing otherwise will mask bugs or issues in the user's environment.

**Comment by jarmarshall** [comment]
Sure @asmeurer :
```
>>> from sympy.parsing.latex import parse_latex
>>> parse_latex('x')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/mumot-env/lib/python3.7/site-packages/sympy/parsing/latex/__init__.py", line 31, in parse_latex
    __import__kwargs={'fromlist': ['X']})
  File "/anaconda3/envs/mumot-env/lib/python3.7/site-packages/sympy/external/importtools.py", line 133, in import_module
    mod = __import__(module, **__import__kwargs)
  File "/anaconda3/envs/mumot-env/lib/python3.7/site-packages/sympy/parsing/latex/_parse_latex_antlr.py", line 22
    ErrorListener = import_module('antlr4.error.ErrorListener',
                ^
SyntaxError: invalid syntax
```

**Comment by oscarbenjamin** [comment]
@jarmarshall I think you've instroduced a syntax error when you commented out except Exception. You need to do it like this:
```diff
diff --git a/sympy/parsing/latex/_parse_latex_antlr.py b/sympy/parsing/latex/_parse_latex_antlr.py
index 5be4fc2..a246ec7 100644
--- a/sympy/parsing/latex/_parse_latex_antlr.py
+++ b/sympy/parsing/latex/_parse_latex_antlr.py
@@ -11,13 +11,10 @@
 
 LaTeXParser = LaTeXLexer = MathErrorListener = None
 
-try:
-    LaTeXParser = import_module('sympy.parsing.latex._antlr.latexparser',
-                                __import__kwargs={'fromlist': ['LaTeXParser']}).LaTeXParser
-    LaTeXLexer = import_module('sympy.parsing.latex._antlr.latexlexer',
-                               __import__kwargs={'fromlist': ['LaTeXLexer']}).LaTeXLexer
-except Exception:
-    pass
+LaTeXParser = import_module('sympy.parsing.latex._antlr.latexparser',
+                            __import__kwargs={'fromlist': ['LaTeXParser']}).LaTeXParser
+LaTeXLexer = import_module('sympy.parsing.latex._antlr.latexlexer',
+                           __import__kwargs={'fromlist': ['LaTeXLexer']}).LaTeXLexer
 
 ErrorListener = import_module('antlr4.error.ErrorListener',
                               warn_not_installed=True,
```

**Comment by jarmarshall** [comment]
Sorry, was rushing this morning and out if the office all day - will look at it properly later

**Comment by jarmarshall** [comment]
Here you go @asmeurer @oscarbenjamin :
```
>>> from sympy.parsing.latex import parse_latex
>>> parse_latex('x')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda3/envs/mumot-env/lib/python3.6/site-packages/sympy/parsing/latex/__init__.py", line 31, in parse_latex
    __import__kwargs={'fromlist': ['X']})
  File "//anaconda3/envs/mumot-env/lib/python3.6/site-packages/sympy/external/importtools.py", line 133, in import_module
    mod = __import__(module, **__import__kwargs)
  File "//anaconda3/envs/mumot-env/lib/python3.6/site-packages/sympy/parsing/latex/_parse_latex_antlr.py", line 16, in <module>
    __import__kwargs={'fromlist': ['LaTeXParser']}).LaTeXParser
  File "//anaconda3/envs/mumot-env/lib/python3.6/site-packages/sympy/external/importtools.py", line 133, in import_module
    mod = __import__(module, **__import__kwargs)
  File "//anaconda3/envs/mumot-env/lib/python3.6/site-packages/sympy/parsing/latex/_antlr/latexparser.py", line 222, in <module>
    class LaTeXParser ( Parser ):
  File "//anaconda3/envs/mumot-env/lib/python3.6/site-packages/sympy/parsing/latex/_antlr/latexparser.py", line 226, in LaTeXParser
    atn = ATNDeserializer().deserialize(serializedATN())
  File "//anaconda3/envs/mumot-env/lib/python3.6/site-packages/antlr4/atn/ATNDeserializer.py", line 81, in deserialize
    self.checkUUID()
  File "//anaconda3/envs/mumot-env/lib/python3.6/site-packages/antlr4/atn/ATNDeserializer.py", line 118, in checkUUID
    " (expected " + str(SERIALIZED_UUID) + " or a legacy UUID).", uuid, SERIALIZED_UUID)
Exception: ('Could not deserialize ATN with UUID: 59627784-3be5-417a-b9eb-8131a7286089 (expected aadb8d7e-aeef-4415-ad2b-8204d6cf042e or a legacy UUID).', UUID('59627784-3be5-417a-b9eb-8131a7286089'), UUID('aadb8d7e-aeef-4415-ad2b-8204d6cf042e'))
```

**Comment by asmeurer** [comment]
I think this means your version of the antlr4-python-runtime is too old. Try installing the version from conda-forge.

**Comment by jarmarshall** [comment]
Thanks @asmeurer - as I said on Gitter I can fix this, but I thought you wanted me to raise an issue so you could diagnose the exception handling error...

**Comment by asmeurer** [comment]
Yes, this is still an issue that needs to be fixed. We need to remove that except Exception from the code.

**Comment by asmeurer** [comment]
I just wanted to verify that there wasn't some other bug in SymPy itself that this was masking. But it looks like the problem is in your environment only.

**Comment by jarmarshall** [comment]
I would also suggest that, if this is an environment error, a slightly more intelligible error message could be given. Or preferably update sympy’s dependency on antlr?

**Comment by asmeurer** [comment]
Yes, definitely. The antlr python runtime library on conda forge is a newer version than the one you had in your environment from PyPI (4.7.2 vs. 4.5.3). IIRC the generated parser can only work with a specific runtime library version at a time, but there should be version checks so we can get better error messages. CC @bollwyvl

**Comment by bollwyvl** [comment]
Yes, no doubt the bare except is my fault! Handling it more robustly at
import time and giving better feedback would certainly be there right path.
Is there a "gold standard" for doing it properly?

To the underlying issue: because it's generated code, it would not be
infeasible to generate and check in multiple compatible versions, for the
4.* back to a certain point, but that sounds ponderous.

Assuming we didn't do that, on the conda side, in sympy feedstock it would
be possible to add...

Requirements:
  run_constrained:
    - pythonX-antlr-runtime =4.7

...but that wouldn't catch the pip-installed pythonX-antlr-runtime.

Yet another option would be to have a sympy-antlr metapackage which
depended on both at the correct version. This could be generated basically
for free during the build of the main package.

**Comment by asmeurer** [comment]
We should add constraints to the conda package, but there also need to be runtime checks, so that people who install things manually get good error messages. I don't think we need to support multiple versions. Having good error reporting for older versions should be good enough.

**Comment by satels** [comment]
?

**Comment by arvindsamriya** [comment]
> 

Hii @jarmarshall @asmeurer , I am facing the same issue with v 4.11.1 and not able to understand how to resolve it, could you please help me in that, although the v 4.7.2 is working on the local machine but not on GCP during deployment. It will be helpful if you could suggest a common version which works on both.
![Screenshot (14)](https://user-images.githubusercontent.com/48277988/194212842-1ba4fb0d-7486-4f8a-91c8-7148ce41795a.png)


> Observing this under Python 3.6.9 with Sympy 1.4 and was asked to submit as an issue - have not found a minimal environment that gives rise to this so including the full environment from my current project.
> 
> ```
> >>> from sympy.parsing.latex import parse_latex
> >>> parse_latex('x')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "//anaconda3/envs/mumot-env/lib/python3.6/site-packages/sympy/parsing/latex/__init__.py", line 34, in parse_latex
>     return _latex.parse_latex(s)
>   File "//anaconda3/envs/mumot-env/lib/python3.6/site-packages/sympy/parsing/latex/_parse_latex_antlr.py", line 74, in parse_latex
>     lex = LaTeXLexer(stream)
> TypeError: 'NoneType' object is not callable
> ```
> 
> Environment (sorry, there's quite a lot of stuff in there:
> 
> ```
> # packages in environment at //anaconda3/envs/mumot-env:
> #
> # Name                    Version                   Build  Channel
> antlr4-python3-runtime    4.5.3                    pypi_0    pypi
> appnope                   0.1.0                    pypi_0    pypi
> attrs                     19.1.0                     py_0    conda-forge
> backcall                  0.1.0                      py_0    conda-forge
> bleach                    3.1.0                      py_0    conda-forge
> ca-certificates           2019.9.11            hecc5488_0    conda-forge
> cairo                     1.14.12              hc4e6be7_4  
> certifi                   2016.9.26                py36_0    conda-forge
> cycler                    0.10.0                   pypi_0    pypi
> decorator                 4.4.0                      py_0    conda-forge
> defusedxml                0.6.0                    pypi_0    pypi
> entrypoints               0.3                   py36_1000    conda-forge
> expat                     2.2.6                h0a44026_0  
> fontconfig                2.13.0               h5d5b041_1  
> freetype                  2.9.1                hb4e5f40_0  
> fribidi                   1.0.5                h1de35cc_0  
> gettext                   0.19.8.1             h15daf44_3  
> glib                      2.56.2               hd9629dc_0  
> graphite2                 1.3.13               h2098e52_0  
> graphviz                  2.40.1               hefbbd9a_2  
> harfbuzz                  1.8.8                hb8d4a28_0  
> icu                       58.2                 h4b95b61_1  
> ipykernel                 4.6.1                    pypi_0    pypi
> ipython                   7.8.0            py36h5ca1d4c_0    conda-forge
> ipython-genutils          0.2.0                    pypi_0    pypi
> ipython_genutils          0.2.0                      py_1    conda-forge
> ipywidgets                7.5.1                    pypi_0    pypi
> jedi                      0.15.1                   py36_0    conda-forge
> jinja2                    2.10.1                     py_0    conda-forge
> jpeg                      9b                   he5867d9_2  
> jsonschema                3.0.2                    py36_0    conda-forge
> jupyter-client            5.3.3                    pypi_0    pypi
> jupyter-contrib-core      0.3.3                    pypi_0    pypi
> jupyter-contrib-nbextensions 0.5.1                    pypi_0    pypi
> jupyter-core              4.5.0                    pypi_0    pypi
> jupyter-highlight-selected-word 0.2.0                    pypi_0    pypi
> jupyter-latex-envs        1.4.6                    pypi_0    pypi
> jupyter-nbextensions-configurator 0.4.1                    pypi_0    pypi
> jupyter_client            5.3.1                      py_0    conda-forge
> jupyter_contrib_core      0.3.3                      py_2    conda-forge
> jupyter_core              4.4.0                      py_0    conda-forge
> jupyter_nbextensions_configurator 0.4.1                    py36_0    conda-forge
> kiwisolver                1.1.0                    pypi_0    pypi
> libcxx                    4.0.1                hcfea43d_1  
> libcxxabi                 4.0.1                hcfea43d_1  
> libedit                   3.1.20181209         hb402a30_0  
> libffi                    3.2.1                h475c297_4  
> libiconv                  1.15                 hdd342a3_7  
> libpng                    1.6.37               ha441bb4_0  
> libsodium                 1.0.17               h01d97ff_0    conda-forge
> libtiff                   4.0.10               hcb84e12_2  
> libxml2                   2.9.9                hf6e021a_1  
> lxml                      4.4.1                    pypi_0    pypi
> markupsafe                1.1.1            py36h1de35cc_0    conda-forge
> matplotlib                3.1.1                    pypi_0    pypi
> mistune                   0.8.4           py36h1de35cc_1000    conda-forge
> mpmath                    1.1.0                    pypi_0    pypi
> mumot                     1.0.0                    pypi_0    pypi
> nbconvert                 5.6.0                    py36_1    conda-forge
> nbformat                  4.4.0                    pypi_0    pypi
> ncurses                   6.1                  h0a44026_1  
> networkx                  2.3                      pypi_0    pypi
> notebook                  5.4.1                    pypi_0    pypi
> numpy                     1.17.2                   pypi_0    pypi
> openssl                   1.1.1c               h01d97ff_0    conda-forge
> pandoc                    2.7.3                         0    conda-forge
> pandocfilters             1.4.2                    pypi_0    pypi
> pango                     1.42.4               h060686c_0  
> parso                     0.5.1                      py_0    conda-forge
> pcre                      8.43                 h0a44026_0  
> pexpect                   4.7.0                    py36_0    conda-forge
> pickleshare               0.7.5                    pypi_0    pypi
> pip                       19.2.2                   py36_0  
> pixman                    0.38.0               h1de35cc_0  
> prometheus_client         0.7.1                      py_0    conda-forge
> prompt_toolkit            2.0.9                      py_0    conda-forge
> ptyprocess                0.6.0                   py_1001    conda-forge
> pydstool                  0.90.3                   pypi_0    pypi
> pygments                  2.4.2                      py_0    conda-forge
> pyparsing                 2.4.2                    pypi_0    pypi
> pyrsistent                0.15.4           py36h01d97ff_0    conda-forge
> python                    3.6.9                h359304d_0  
> python-dateutil           2.8.0                      py_0    conda-forge
> python-graphviz           0.13                     pypi_0    pypi
> pyyaml                    5.1.2                    pypi_0    pypi
> pyzmq                     16.0.4                   pypi_0    pypi
> readline                  7.0                  h1de35cc_5  
> scipy                     1.3.1                    pypi_0    pypi
> send2trash                1.5.0                      py_0    conda-forge
> setuptools                41.0.1                   py36_0  
> six                       1.12.0                   pypi_0    pypi
> sqlite                    3.29.0               ha441bb4_0  
> sympy                     1.4                      pypi_0    pypi
> terminado                 0.8.2                    pypi_0    pypi
> testpath                  0.4.2                   py_1001    conda-forge
> tk                        8.6.8                ha441bb4_0  
> tornado                   4.5.3                    pypi_0    pypi
> traitlets                 4.3.2                    pypi_0    pypi
> wcwidth                   0.1.7                    pypi_0    pypi
> webencodings              0.5.1                    pypi_0    pypi
> wheel                     0.33.4                   py36_0  
> widgetsnbextension        3.5.1                    pypi_0    pypi
> xz                        5.2.4                h1de35cc_4  
> yaml                      0.1.7             h1de35cc_1001    conda-forge
> zeromq                    4.3.2                h6de7cb9_2    conda-forge
> zlib                      1.2.11               h1de35cc_3  
> zstd                      1.3.7                h5bba6e5_0  
> ```

**Comment by lunaluxie** [comment]
I have the same problem.

**Comment by jinlin82** [comment]
I have the same problem, too

**Comment by joachimlebovits** [comment]
Hi guys,

I also have the same problem:
My python code is this:


### #!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 13 09:34:03 2023


import sympy
from sympy.parsing.latex import parse_latex

expr = parse_latex(r"\frac {1 + \sqrt {\a}} {\b}")





And the error message I get is this:

 File "/Users/jlebovits/Dropbox/5-Latex_et_tous_logiciels_de_math_et_terminal/Programmation/9-Python/Programmes_Python/1-Prog_de_math_Python/Exemples de parsing sympy/1-Exemple-2_de_parsing_Sympy.py", line 12, in <module>
    expr = parse_latex(r"\frac {1 + \sqrt {\a}} {\b}")

  File "/Users/jlebovits/mambaforge/lib/python3.8/site-packages/sympy/parsing/latex/__init__.py", line 35, in parse_latex
    return _latex.parse_latex(s)

  File "/Users/jlebovits/mambaforge/lib/python3.8/site-packages/sympy/parsing/latex/_parse_latex_antlr.py", line 73, in parse_latex
    lex = LaTeXLexer(stream)

TypeError: 'NoneType' object is not callable







Any idea what is going wrong?
