### ISSUE TITLE
OverflowError/TypeError with ceiling(log(1)/log(2))

### ISSUE THREAD

**Issue by Mygod** [sympy/sympy#17639]
```python
import sympy

test = sympy.symbols('test')
print(sympy.ceiling(sympy.log(test) / sympy.log(2)).evalf(subs={test: 1}))

OverflowError: cannot convert float infinity to integer

print(sympy.ceiling(sympy.log(test) / sympy.log(3)).evalf(subs={test: 1}))

TypeError: unsupported operand type(s) for >>: 'int' and 'float'
```

Using sympy 1.4.

**Comment by oscarbenjamin** [comment]
It goes wrong here:
https://github.com/sympy/sympy/blob/58e78209c8577b9890e957b624466e5beed7eb08/sympy/core/evalf.py#L350-L356
The `reim` variable is `re(log(test)/log(2))` which is zero (if test=1). Then fastlog returns `-oo` which then give `size=oo` which is used as the `prec` argument in the recursive call to evalf. Perhaps `size` should be bounded at `maxprec` here.

**Comment by Mygod** [comment]
Another bug when `test = 5e-324`.

```
Traceback (most recent call last):
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 1442, in evalf
    result = evalf(self, prec + 4, options)
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 1309, in evalf
    r = rf(x, prec, options)
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 521, in evalf_add
    terms = [evalf(arg, prec + 10, options) for arg in v.args]
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 521, in <listcomp>
    terms = [evalf(arg, prec + 10, options) for arg in v.args]
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 1309, in evalf
    r = rf(x, prec, options)
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 720, in evalf_pow
    yre, yim, _, _ = evalf(exp, prec, options)
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 1309, in evalf
    r = rf(x, prec, options)
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 521, in evalf_add
    terms = [evalf(arg, prec + 10, options) for arg in v.args]
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 521, in <listcomp>
    terms = [evalf(arg, prec + 10, options) for arg in v.args]
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 1309, in evalf
    r = rf(x, prec, options)
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 410, in evalf_ceiling
    return get_integer_part(expr.args[0], 1, options)
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 315, in get_integer_part
    ire, iim, ire_acc, iim_acc = evalf(expr, assumed_size, options)
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 1309, in evalf
    r = rf(x, prec, options)
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 561, in evalf_mul
    arg = evalf(arg, prec, options)
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 1309, in evalf
    r = rf(x, prec, options)
  File "/path/to/lib/python3.7/site-packages/sympy/core/evalf.py", line 845, in evalf_log
    imaginary_term = (mpf_cmp(xre, fzero) < 0)
  File "/path/to/lib/python3.7/site-packages/mpmath/libmp/libmpf.py", line 581, in mpf_cmp
    ssign, sman, sexp, sbc = s
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by jksuom** [comment]
> The reim variable is re(log(test)/log(2)) which is zero (if test=1).

`re_im` comes from `fzero` assigned to `ire` on this line: https://github.com/sympy/sympy/blob/1ea2b2045cefd2d1faec91b47d0e2db51c175e01/sympy/core/evalf.py#L315
It seems that the internal `evalf` is expected to return `None` instead of `fzero`. In this case, `evalf_mul` should have checked the result of `log(1)*log(2)**-1`.
