### ISSUE TITLE
Convert integral -> piecewise to piecewise integral

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#17657]
When input the following expression

```python3
In [1]: integrate(S('sigma*2*pi*x*h/(4*pi*epsilon_0*(x**2+h**2)**(3/2))'),(x,0,'r'))                                                                                                                                                         
Out[1]: 
⎧ 0                                                                   
⎪ ⌠                                                                   
⎪ ⎮ ⎧                               _____          _____              
⎪ ⎮ ⎪                              ╱   2          ╱   2               
⎪ ⎮ ⎪       nan         for h = -╲╱  -x   ∨ h = ╲╱  -x                
⎪ ⎮ ⎪                                                                 
⎪-⎮ ⎨      h⋅σ⋅x                                         dx  for r < 0
⎪ ⎮ ⎪─────────────────             otherwise                          
⎪ ⎮ ⎪              3/2                                                
⎪ ⎮ ⎪     ⎛ 2    2⎞                                                   
⎪ ⎮ ⎩2⋅ε₀⋅⎝h  + x ⎠                                                   
⎪ ⌡                                                                   
⎪ r                                                                   
⎨                                                                     
⎪r                                                                    
⎪⌠                                                                    
⎪⎮ ⎧                               _____          _____               
⎪⎮ ⎪                              ╱   2          ╱   2                
⎪⎮ ⎪       nan         for h = -╲╱  -x   ∨ h = ╲╱  -x                 
⎪⎮ ⎪                                                                  
⎪⎮ ⎨      h⋅σ⋅x                                         dx   otherwise
⎪⎮ ⎪─────────────────             otherwise                           
⎪⎮ ⎪              3/2                                                 
⎪⎮ ⎪     ⎛ 2    2⎞                                                    
⎪⎮ ⎩2⋅ε₀⋅⎝h  + x ⎠                                                    
⎪⌡                                                                    
⎩0                     
```

The piecewise function is inside integral.

Is it possible to move piecewise out and simplify integral expression.

**Comment by oscarbenjamin** [comment]
I'm not sure how to simplify that. Declaring r to be positive or negative gives a simpler result but real is not a strong enough condition:
```julia
In [35]: i = S('sigma*2*pi*x*h/(4*pi*epsilon_0*(x**2+h**2)**(3/2))')                                                                           

In [36]: i                                                                                                                                     
Out[36]: 
      h⋅σ⋅x      
─────────────────
              3/2
     ⎛ 2    2⎞   
2⋅ε₀⋅⎝h  + x ⎠  

In [28]: r = Symbol('r', negative=True)                                                                                                        

In [29]: i.integrate((x, 0, r))                                                                                                                
Out[29]: 
    h⋅σ               h⋅σ       
──────────── - ─────────────────
        ____           _________
       ╱  2           ╱  2    2 
2⋅ε₀⋅╲╱  h     2⋅ε₀⋅╲╱  h  + r  

In [30]: r = Symbol('r', positive=True)                                                                                                        

In [31]: i.integrate((x, 0, r))                                                                                                                
Out[31]: 
    h⋅σ               h⋅σ       
──────────── - ─────────────────
        ____           _________
       ╱  2           ╱  2    2 
2⋅ε₀⋅╲╱  h     2⋅ε₀⋅╲╱  h  + r  

In [32]: r = Symbol('r', real=True)                                                                                                            

In [33]: i.integrate((x, 0, r))                                                                                                                
Out[33]: 
⎧ 0                                                             
⎪ ⌠                                                             
⎪ ⎮ ⎧       nan         for h = -ⅈ⋅│x│ ∨ h = ⅈ⋅│x│              
⎪ ⎮ ⎪                                                           
⎪ ⎮ ⎪      h⋅σ⋅x                                                
⎪-⎮ ⎨─────────────────          otherwise          dx  for r < 0
⎪ ⎮ ⎪              3/2                                          
⎪ ⎮ ⎪     ⎛ 2    2⎞                                             
⎪ ⎮ ⎩2⋅ε₀⋅⎝h  + x ⎠                                             
⎪ ⌡                                                             
⎪ r                                                             
⎨                                                               
⎪r                                                              
⎪⌠                                                              
⎪⎮ ⎧       nan         for h = -ⅈ⋅│x│ ∨ h = ⅈ⋅│x│               
⎪⎮ ⎪                                                            
⎪⎮ ⎪      h⋅σ⋅x                                                 
⎪⎮ ⎨─────────────────          otherwise          dx   otherwise
⎪⎮ ⎪              3/2                                           
⎪⎮ ⎪     ⎛ 2    2⎞                                              
⎪⎮ ⎩2⋅ε₀⋅⎝h  + x ⎠                                              
⎪⌡                                                              
⎩0    
```
I'm not sure where the Piecewise comes from.

Declaring h to be real leads to an exception:
```python
from sympy import *

sigma = Symbol('sigma')
epsilon_0 = Symbol('epsilon_0')
h = Symbol('h', real=True)
x = Symbol('x')
r = Symbol('r', real=True)
i = sigma*2*pi*x*h/(4*pi*epsilon_0*(x**2+h**2)**(S(3)/2))
pprint(i)
pprint(i.integrate((x, 0, r)))     
```
```console
$ python f.py 
      h⋅σ⋅x      
─────────────────
              3/2
     ⎛ 2    2⎞   
2⋅ε₀⋅⎝h  + x ⎠   
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 22, in as_Basic
    return _sympify(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/core/sympify.py", line 418, in _sympify
    return sympify(a, strict=True)
  File "/Users/enojb/current/sympy/sympy/sympy/core/sympify.py", line 286, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f.py", line 10, in <module>
    pprint(i.integrate((x, 0, r)))
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 3564, in integrate
    return integrate(self, *args, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 1517, in integrate
    return integral.doit(**doit_flags)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 462, in doit
    did = self.xreplace(reps).doit(**hints)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 573, in doit
    antideriv = self._eval_integral(
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 1030, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/heurisch.py", line 188, in heurisch_wrapper
    return Piecewise(*pairs)
  File "/Users/enojb/current/sympy/sympy/sympy/functions/elementary/piecewise.py", line 130, in __new__
    pair = ExprCondPair(*getattr(ec, 'args', ec))
  File "/Users/enojb/current/sympy/sympy/sympy/functions/elementary/piecewise.py", line 22, in __new__
    expr = as_Basic(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 24, in as_Basic
    raise TypeError(
TypeError: Argument must be a Basic object, not `NoneType`
```

**Comment by jksuom** [comment]
> I'm not sure where the Piecewise comes from.

It comes from `heurisch_wrapper`. There are several open issues on this error, e.g. https://github.com/sympy/sympy/issues/14613#issuecomment-381348772, https://github.com/sympy/sympy/issues/15213#issuecomment-420064167. I thought that this was fixed already but apparently not.
