### ISSUE TITLE
Lambidfy with dynamicsymbol gives invalid syntax

### ISSUE THREAD

**Issue by rcywongaa** [sympy/sympy#17656]
After finding the equation of motion, I wish to lambdify it so that I can easily find the acceleration given the current state (position, velocity) and applied force.

In the process of obtaining the equation of motion, `dynamicsymbols` is used for representing functions of time (position) and its derivatives (velocity, acceleration).

The code is like the following
```
from sympy.physics.vector import dynamicsymbols
from sympy.utilities.lambdify import lambdify
from sympy import Symbol, diff

t = Symbol('t')
theta1 = dynamicsymbols('theta1')
theta1_d = diff(theta1, t)
# theta1 = Symbol('theta1') # Uncommenting this works
# theta1_d = Symbol('theta1_d') # Uncommenting this works

tau1 = Symbol('tau1')

theta1_dd_eom = theta1 + theta1_d + tau1

calc_theta1_dd = lambdify([theta1, theta1_d, tau1], 
        theta1_dd_eom)
```
However, this throws the following error
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    theta1_dd_eom)
  File "/usr/lib/python3/dist-packages/sympy/utilities/lambdify.py", line 434, in lambdify
    func = eval(lstr, namespace)
  File "<string>", line 1
    lambda _Dummy_140,Derivative(theta1(t), t),_Dummy_141: (Derivative(_Dummy_140, t) + _Dummy_140 + _Dummy_141)
                                ^
SyntaxError: invalid syntax
```

I am using sympy `1.1.1`

**Comment by rcywongaa** [comment]
I managed to solve this by substituting all `dynamicsymbols` with normal symbols.  However, the fact that the order of substitution matters leaves much to be desired...
```
from sympy.physics.vector import dynamicsymbols
from sympy.utilities.lambdify import lambdify, implemented_function
from sympy import Symbol, diff, Derivative
import pdb

t = Symbol('t')
theta1 = dynamicsymbols('theta1')
theta1_d = diff(theta1, t)
theta1_0 = Symbol('theta1_0')
theta1_d_0 = Symbol('theta1_d_0')

# ORDER IS IMPORTANT!
# We want to substitute theta1_d before theta1 because Derivative(theta1, t) != Derivative(theta1_0, t)
# Substitution will fail if we substituted theta1 first
substitutions = [
        (theta1_d, theta1_d_0),
        (theta1, theta1_0)]

tau1 = Symbol('tau1')

theta1_dd_eom = theta1 + theta1_d + tau1
theta1_dd_eom_0 = theta1_dd_eom.subs(substitutions)

calc_theta1_dd = lambdify([theta1_0, theta1_d_0, tau1], theta1_dd_eom_0)
print(calc_theta1_dd(1.0, 2.0, 3.0))
```

**Comment by moorepants** [comment]
`lambdify` should work with sympy functions.
![Selection_581](https://user-images.githubusercontent.com/276007/65694314-853b1200-e02a-11e9-8efa-8436d7a694a2.png)

I recommend upgrading to SymPy 1.4.
