### ISSUE TITLE
is_integer produces random results

### ISSUE THREAD

**Issue by matthias314** [sympy/sympy#17729]
I want to do symbolic computations with non-commuting variables. Each variable `a` has a degree `deg(a)`. Even if the degree is again symbolic, I want SymPy to know that it's an integer so that expressions of the form `(-1)**(2*deg(a))` are simplified to `1`. Here is the kind of code I'm using:

```
class deg(Function):
    def _eval_is_integer(self):
        return True

myvars = symbols("a b c", commutative = False)

for x in myvars:
    # y = deg(x)
    # print " ", y, y.is_integer
    y = 2*deg(x)
    print y, y.is_integer
```
It produces apparently random results:
```
Python console for SymPy 1.4 (Python 2.7.15-64-bit) (ground types: python)
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2

>>> execfile("example.py")
2*deg(a) False
2*deg(b) True
2*deg(c) True
>>> execfile("example.py")
2*deg(a) False
2*deg(b) False
2*deg(c) True
>>> execfile("example.py")
2*deg(a) True
2*deg(b) False
2*deg(c) True
```
This happens with both Python and PyPy, and also if caching is turned off. Uncommenting the two lines that are commented out in the code produces the expected result, i.e., `is_integer` always gives `True`. With commuting variables the problem doesn't appear.
Am I missing something here, or is this a bug in SymPy?

**Comment by ethankward** [comment]
A non-commutative integer is an inconsistent assumption. If you try to create such a variable directly it will immediately give you an exception:

```
>>> x = Symbol('x', commutative=False, integer=True)
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    x = Symbol('x', commutative=False, integer=True)
  File "/home/eward/se/sympy/core/symbol.py", line 235, in __new__
    return Symbol.__xnew_cached_(cls, name, **assumptions)
  File "/home/eward/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/eward/se/sympy/core/symbol.py", line 257, in __new_stage2__
    obj._assumptions = StdFactKB(assumptions)
  File "/home/eward/se/sympy/core/assumptions.py", line 242, in __init__
    self.deduce_all_facts(facts)
  File "/home/eward/se/sympy/core/facts.py", line 522, in deduce_all_facts
    if not self._tell(k, v) or v is None:
  File "/home/eward/se/sympy/core/facts.py", line 493, in _tell
    raise InconsistentAssumptions(self, k, v)
sympy.core.facts.InconsistentAssumptions: {
	algebraic: False,
	commutative: False,
	complex: False,
	composite: False,
	even: False,
	extended_negative: False,
	extended_nonnegative: False,
	extended_nonpositive: False,
	extended_nonzero: False,
	extended_positive: False,
	extended_real: False,
	imaginary: False,
	integer: False,
	irrational: False,
	negative: False,
	noninteger: False,
	nonnegative: False,
	nonpositive: False,
	nonzero: False,
	odd: False,
	positive: False,
	prime: False,
	rational: False,
	real: False,
	transcendental: False,
	zero: False}, integer=True
```

I would call what you are doing undefined behavior.

**Comment by matthias314** [comment]
I'm not trying to create non-commutative integers. I want to define a **function** `deg` that takes non-commutative symbols as arguments and returns a (commutative) integer. Even if the function returns unevaluated, I want SymPy to take into account that `deg(a)` is an integer.

**Comment by smichr** [comment]
Try stating that your function is an integer:
```python
>>> x, y = var('x y', commutative=False)
>>> deg = Function('deg', integer=True)
>>> deg(x,y).is_integer
True
```

**Comment by matthias314** [comment]
Yes, that works. However, I also want the function `deg` to examine its argument and do certain simplifications that for readability I had left out in the code snippet I gave above. For example, I want to have the identity `deg(a*b)=deg(a)+deg(b)`. In my code that would be something like:
```
class deg(Function):
    nargs = 1

    @classmethod            
    def eval(cls, x):
        if x.func == Mul:
            return sum(map(cls, x.args))

    def _eval_is_integer(self):
        return True
```
Again, this is not the fully functional `deg` I have in mind, but it illustrates my point. How would this work in your approach? (Let me know if this is not the right place to ask this question.)
In any case, the random behaviour of the code I gave first is disturbing. Whatever the result is, shouldn't it be reproducible?

**Comment by oscarbenjamin** [comment]
The problem is this:
```julia
In [3]: class deg(Function): 
   ...:     def _eval_is_integer(self): 
   ...:         return True 
   ...:                                                                                                  

In [4]: deg(Symbol('x', commutative=False))                                                              
Out[4]: deg(x)

In [5]: deg(Symbol('x', commutative=False)).is_commutative                                               
Out[5]: False
```
That comes from here:
https://github.com/sympy/sympy/blob/147ee2c227f2c02c730d300bdf42a9b0579dae62/sympy/core/function.py#L621-L622

That method should be removed from Function but then added to many specific functions where it applies.

**Comment by matthias314** [comment]
I'm fairly new to SymPy, and I'm not claiming that the code for `is_commutative` mentioned above is not problematic or not related to the issue I'm having. I just want to point out that adding `is_commutative` to `deg` doesn't resolve the problem:
```
class deg(Function):
    is_commutative = True
    def _eval_is_integer(self):
        return True

myvars = symbols("a b c", commutative = False)
for x in myvars:
    y = 2*deg(x)
    print y, y.is_integer, deg(x).is_commutative
```
Here is some output. Again, the `is_integer` part seems random.
```
>>> execfile("example.py")
2*deg(a) True True
2*deg(b) False True
2*deg(c) False True
```

**Comment by asmeurer** [comment]
Is this coming from the shuffling in the assumptions?

**Comment by oscarbenjamin** [comment]
The non-determinism comes from the shuffling but the bug is that `Function._eval_is_commutative` is inconsistent with having a function that has non-commutative arguments but can return commutative values. As in all other cases where the assumption shuffling comes up the shuffling is exposing a bug.

It would be possible to fix it for this case by overriding `_eval_is_commutative` in `deg`. However it really shouldn't be defined speculatively like this in `Function` in the first place. Even if it is correct for most of the functions defined in SymPy this will lead to many other wrong results.

**Comment by oscarbenjamin** [comment]
> I just want to point out that adding `is_commutative` to `deg` doesn't resolve the problem:

It does for me. Are you sure you tested the right code? Are you testing with master?

**Comment by matthias314** [comment]
@oscarbenjamin I'm testing with SymPy 1.4.

**Comment by oscarbenjamin** [comment]
Whoops I was testing with my branch in #17699. There the behaviour is reliable if you have `is_commutative=True`.
