### ISSUE TITLE
lambdify([], E) raises KeyError

### ISSUE THREAD

**Issue by pckroon** [sympy/sympy#17834]
Hi all,

it seems that Euler's constant (`E`) is unknown to the code printer:
```pycon
>>> lambdify([], E)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../sympy/utilities/lambdify.py", line 767, in lambdify
    funcstr = funcprinter.doprint(funcname, args, expr)
  File ".../sympy/utilities/lambdify.py", line 997, in doprint
    funcbody.append('return ({})'.format(self._exprrepr(expr)))
  File ".../sympy/printing/codeprinter.py", line 100, in doprint
    lines = self._print(expr).splitlines()
  File ".../sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File ".../sympy/printing/pycode.py", line 74, in _print_known_const
    known = self.known_constants[expr.__class__.__name__]
KeyError: 'Exp1'
```
```bash
$ pip list
alabaster                     0.7.12       
atomicwrites                  1.2.1        
attrs                         19.3.0       
Babel                         2.6.0        
certifi                       2018.11.29   
chardet                       3.0.4        
coverage                      4.5.4        
coveralls                     1.5.1        
cycler                        0.10.0       
docopt                        0.6.2        
docutils                      0.14         
hypothesis                    4.42.4       
idna                          2.8          
imagesize                     1.1.0        
importlib-metadata            0.21         
Jinja2                        2.10         
kiwisolver                    1.0.1        
MarkupSafe                    1.1.1        
matplotlib                    3.0.2        
more-itertools                4.3.0        
mpmath                        1.0.0        
numpy                         1.17.3       
packaging                     19.0         
pip                           19.3.1       
pluggy                        0.13.0       
py                            1.7.0        
Pygments                      2.3.1        
pyparsing                     2.3.0        
PyQt5                         5.11.3       
PyQt5-sip                     4.19.13      
pytest                        5.2.2        
pytest-cov                    2.6.1        
python-dateutil               2.7.5        
pytz                          2018.9       
requests                      2.21.0       
scipy                         1.3.1        
setuptools                    41.2.0       
six                           1.11.0       
snowballstemmer               1.2.1        
Sphinx                        2.0.0        
sphinxcontrib-applehelp       1.0.1        
sphinxcontrib-devhelp         1.0.1        
sphinxcontrib-htmlhelp        1.0.1        
sphinxcontrib-jsmath          1.0.1        
sphinxcontrib-qthelp          1.0.2        
sphinxcontrib-serializinghtml 1.1.1        
symfit                        0.4.7.dev121 <...>
sympy                         1.4          
toposort                      1.5          
urllib3                       1.24.1       
wcwidth                       0.1.7        
wheel                         0.32.2       
zipp                          0.6.0        
```

Please let me know if you need more information from my side, and keep up the good work :)

**Comment by ethankward** [comment]
It seems like this is a problem specifically in the 1.4 release. Fixed by commit 47baf524e319c462dd7a06fbef7609fca7154c6e.

**Comment by pckroon** [comment]
Awesome! Is it worth making a bugfix release maybe?
Either way, feel free to close this issue, unless you want to keep it open until it's released.

**Comment by asmeurer** [comment]
The next release should be coming out in the next month.
