### ISSUE TITLE
Pretty print Range(-oo, oo) raises

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17857]
```python
>>> from sympy import *
>>> init_printing()
>>> Range(-oo, oo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/interactive/printing.py", line 30, in _displayhook
    print(stringify_func(arg, **settings))
  File "/Users/enojb/current/sympy/sympy/sympy/printing/pretty/pretty.py", line 2606, in pretty
    return pp.doprint(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/printing/pretty/pretty.py", line 64, in doprint
    return self._print(expr).render(**self._settings)
  File "/Users/enojb/current/sympy/sympy/sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/printing/pretty/pretty.py", line 1918, in _print_Range
    printset = dots, s[-1] - s.step, s[-1]
  File "/Users/enojb/current/sympy/sympy/sympy/sets/fancysets.py", line 842, in __getitem__
    raise ValueError(ooslice)
ValueError: cannot slice from the end with an infinite value
```

**Comment by ethankward** [comment]
What is a good thing to print here? `{…}` looks confusing.

**Comment by oscarbenjamin** [comment]
We have
```julia
In [1]: Range(-oo, 0)                                                                                                                                         
Out[1]: {…, -2, -1}

In [2]: Range(oo)                                                                                                                                             
Out[2]: {0, 1, …}
```
so I would go with
```julia
In [2]: Range(-oo, oo)                                                                                                                                             
Out[2]: {…, -1, 0, 1, …}
```
