### ISSUE TITLE
LaTeXParsingError expected to be thrown for (3-9) (5-15

### ISSUE THREAD

**Issue by charlesverge** [sympy/sympy#17874]
Having latex2sympy integrated is fantastic. Though a developer reported a minor issue where closing brackets cause expressions to not be evaluated correctly.

For example (3-9) (5-15 evaluates to -6. Vs throwing a LaTeXParsingError or returning 60

**Comment by asmeurer** [comment]
I guess it throws out the part with the unmatched brackets. I agree an error would be better.

**Comment by wermos** [comment]
With the Lark LaTeX parser, this is the output:
```python
>>> expr = parse_latex_lark(r"(3-9) (5-15")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tirthankar/projects/sympy/sympy/parsing/latex/lark/latex_parser.py", line 76, in parse_latex_lark
    return _lark_latex_parser.doparse(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tirthankar/projects/sympy/sympy/parsing/latex/lark/latex_parser.py", line 40, in doparse
    parse_tree = self.parser.parse(s)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/tirthankar/projects/sympy/env/lib/python3.11/site-packages/lark/lark.py", line 645, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tirthankar/projects/sympy/env/lib/python3.11/site-packages/lark/parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tirthankar/projects/sympy/env/lib/python3.11/site-packages/lark/parsers/earley.py", line 274, in parse
    raise UnexpectedEOF(expected_terminals, state=frozenset(i.s for i in to_scan))
lark.exceptions.UnexpectedEOF: Unexpected end-of-input. Expected one of:
        * CMD_FRAC
        * GREEK_SYMBOL
        * FUNC_ARCCSC
        * L_BRACE
        * BASIC_SUBSCRIPTED_SYMBOL
        * CMD_BINOM
        * FUNC_CSC
        * FUNC_INT
        * CMD_OVERLINE
        * ADD
        * CMD_BINOM
        * CMD_FRAC
        * CMD_LANGLE
        * FUNC_LN
        * FUNC_SEC
        * FUNC_PROD
        * FUNC_SEC
        * CMD_BINOM
        * BAR
        * CMD_FRAC
        * FUNC_COS
        * L_PAREN
        * CMD_FRAC
        * FUNC_TAN
        * CMD_LANGLE
        * SYMBOL
        * CMD_FRAC
        * BAR
        * FUNC_ARCOSH
        * SUB
        * FUNC_ARCCOT
        * FUNC_LIM
        * FUNC_LOG
        * CMD_OVERLINE
        * FUNC_ARCSEC
        * CMD_BINOM
        * FUNC_INT
        * ADD
        * CMD_FRAC
        * FUNC_COT
        * __ANON_1
        * CMD_BINOM
        * CMD_BINOM
        * FUNC_SIN
        * FUNC_COS
        * FUNC_INT
        * L_CEIL
        * BANG
        * CMD_FRAC
        * CMD_FRAC
        * SYMBOL_WITH_GREEK_SUBSCRIPT
        * FUNC_SINH
        * FUNC_MAX
        * FUNC_SQRT
        * FUNC_INT
        * FUNC_TANH
        * MUL_SYMBOL
        * FUNC_INT
        * FUNC_INT
        * SUB
        * R_PAREN
        * FUNC_SUM
        * SUB
        * FUNC_INT
        * FUNC_ARCSIN
        * FUNC_COT
        * FUNC_LOG
        * CMD_BINOM
        * FUNC_MIN
        * SUB
        * FUNC_SQRT
        * ADD
        * FUNC_LOG
        * FUNC_ARTANH
        * FUNC_INT
        * FUNC_CSC
        * FUNC_SIN
        * FUNC_COSH
        * DIV_SYMBOL
        * FUNC_LG
        * CARET
        * FUNC_ARSINH
        * BANG
        * GREEK_SUBSCRIPTED_SYMBOL
        * FUNC_LOG
        * CMD_MATHIT
        * FUNC_ARCCOS
        * L_FLOOR
        * FUNC_TAN
        * CMD_INFTY
        * FUNC_INT
        * CMD_BINOM
        * BANG
        * FUNC_EXP
        * FUNC_ARCTAN
```
