### ISSUE TITLE
Permutation repr test failure in master 

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#17884]
```
$./bin/test repr perm
===================================================================================================== test process starts =====================================================================================================
executable:         /home/aaronmeurer/anaconda3/bin/python  (3.7.3-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 2.1.0b1
numpy:              1.17.3
random seed:        57948523
hash randomization: on (PYTHONHASHSEED=372740668)

sympy/combinatorics/tests/test_perm_groups.py[57] ...............f...............f................w........                                                                                                                [OK]
sympy/combinatorics/tests/test_permutations.py[11] ...........                                                                                                                                                             [OK]
sympy/physics/quantum/tests/test_represent.py[9] .........                                                                                                                                                                 [OK]
sympy/printing/tests/test_lambdarepr.py[9] .........                                                                                                                                                                       [OK]
sympy/printing/tests/test_repr.py[41] ........................................F                                                                                                                                          [FAIL]

_______________________________________________________________________________________________________________________________________________________________________________________________________________________________
_____________________________________________________________________________________ sympy/printing/tests/test_repr.py:test_Permutation ______________________________________________________________________________________
Traceback (most recent call last):
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_repr.py", line 305, in test_Permutation
    sT(Permutation(1, 2), "Permutation(1, 2)", import_stmt)
  File "/home/aaronmeurer/Documents/python/sympy/sympy/sympy/printing/tests/test_repr.py", line 34, in sT
    assert srepr(expr) == string
AssertionError

==================================================================== tests finished: 123 passed, 1 failed, 1 skipped, 2 expected to fail, in 2.20 seconds =====================================================================
DO *NOT* COMMIT!
```

We can probably work around this by making sure print_cyclic is set correctly in the repr test. 

In the longer term, I think we should get rid of that flag https://github.com/sympy/sympy/issues/15201.

**Comment by aditisingh2362** [comment]
I would like to work on this issue.

**Comment by sylee957** [comment]
You may have to modify the tests to specify the variable temporarily and make it automatically revert to the default value like this.

```diff
$ git diff
diff --git a/sympy/printing/tests/test_repr.py b/sympy/printing/tests/test_repr.py
index dc9ce7bb58..301bf46596 100644
--- a/sympy/printing/tests/test_repr.py
+++ b/sympy/printing/tests/test_repr.py
@@ -302,4 +302,7 @@ def test_Cycle():

 def test_Permutation():
     import_stmt = "from sympy.combinatorics import Permutation"
+    print_cyclic = Permutation.print_cyclic
+    Permutation.print_cyclic = True
     sT(Permutation(1, 2), "Permutation(1, 2)", import_stmt)
+    Permutation.print_cyclic = print_cyclic
```

**Comment by sylee957** [comment]
And I don't think that this should be blocking the next release since this is a gotcha about mutating class variables. 
And this does not happen on the travis test, travis had luckily splited the combinatorics test and the printing test.
This only happens if you test combinatorics and `test_repr` in the same stage.
