### ISSUE TITLE
PurePoly is not recognized as something that can be solved

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#17880]
```python
>>> PurePoly(x**2-1)
PurePoly(x**2 - 1, x, domain='ZZ')
>>> solve(PurePoly(x**2-1))
[]
>>> solveset(PurePoly(x**2-1))
EmptySet

>>> solve(PurePoly(x**2-1).as_expr())
[-1, 1]
```

**Comment by asmeurer** [comment]
Do we have some kind of _eval_solve or _eval_solveset API?

**Comment by oscargus** [comment]
Current master now gives an error for `solveset`:
```
In [6]: solveset(PurePoly(x**2-1))
Traceback (most recent call last):

  File "<ipython-input-6-f58b77ab9035>", line 1, in <module>
    solveset(PurePoly(x**2-1))

  File "C:\Users\Oscar\sympy\sympy\solvers\solveset.py", line 2179, in solveset
    raise ValueError("%s is not a valid SymPy expression" % f)

ValueError: PurePoly(x**2 - 1, x, domain='ZZ') is not a valid SymPy expression
```

**Comment by oscarbenjamin** [comment]
Potentially the error message could be improved but I think that it is correct to give an error for Poly. The input should be required to Expr or Relational and not Poly or PurePoly (same goes for `solve` which *does* work for `Poly` but shouldn't)

**Comment by guptapratykshh** [comment]
Added check at beginning of both functions to determine if input is `Poly` or `PurePoly` object and if so convert it to symbolic expression using `as_expr()` method.

Please give suggestion on this if any changes is needed.
```
def solve(f, *symbols, **flags):

    from .inequalities import reduce_inequalities

    if isinstance(f, (Poly, PurePoly)):
        f = f.as_expr()

    # checking/recording flags
    ###########################################################################

    # set solver types explicitly; as soon as one is False
    # all the rest will be False
    hints = ('cubics', 'quartics', 'quintics')
    default = True
    for k in hints:
        default = flags.setdefault(k, bool(flags.get(k, default)))
```

```
def solveset(f, symbol=None, domain=S.Complexes):

    if isinstance(f, (Poly, PurePoly)):
        f = f.as_expr()
    else:
        f = sympify(f)
    symbol = sympify(symbol)

    if f is S.true:
        return domain

    if f is S.false:
        return S.EmptySet
```

```
>>> PurePoly(x**2-1)
PurePoly(x**2 - 1, x, domain='ZZ')
>>> solve(PurePoly(x**2-1).as_expr())
[-1, 1]
>>> solveset(PurePoly(x**2-1))
{-1, 1}
>>> solve(PurePoly(x**2-1))
[-1, 1]
```
