### ISSUE TITLE
Bug in using solve with Piecewise

### ISSUE THREAD

**Issue by j2kun** [sympy/sympy#17890]
The following snippet raises an exception (exception pasted at the end).

```
from sympy import Symbol
from sympy import solve
from sympy import Piecewise

x = Symbol('x')
f = Piecewise((-1.66666666666667 - (3 * x - 2.0) / (3 * x**3), x < 0.481089134572278), (0, True)) - 5.32064816919383
print(solve(f, x, minimal=True, quick=True))
```

I have tried this in sympy 1.3, 1.4, and at the current master. At 1.3 and 1.4, it crashes with the pasted exception. At master, it seems to never terminate (it seems to get stuck in polys/numberfields.py trying to compute a minimal polynomial).

Note that if I remove the use of Piecewise, and instead solve

```
g = (-1.66666666666667 - (3 * x - 2.0) / (3 * x**3)) - 5.32064816919383
```

Then I get the correct output:

```
[0.354742311312263, -0.177371155656131 - 0.487337741531747*I, -0.177371155656131 + 0.487337741531747*I]
```

Exception seen: 

```
Traceback (most recent call last):
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/evalf.py", line 1308, in evalf
    rf = evalf_table[x.func]
KeyError: <class 'sympy.core.relational.StrictGreaterThan'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reproduce_bug.py", line 9, in <module>
    print(solve(f, x, minimal=True, quick=True))
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/solvers/solvers.py", line 1243, in solve
    solution = nfloat(solution, exponent=False)
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/function.py", line 3082, in nfloat
    return type(expr)([nfloat(a, n, exponent) for a in expr])
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/function.py", line 3082, in <listcomp>
    return type(expr)([nfloat(a, n, exponent) for a in expr])
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/function.py", line 3116, in nfloat
    lambda x: isinstance(x, Function)))
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/basic.py", line 1182, in xreplace
    value, _ = self._xreplace(rule)
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/basic.py", line 1190, in _xreplace
    return rule[self], True
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/rules.py", line 59, in __getitem__
    return self._transform(key)
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/function.py", line 3115, in <lambda>
    lambda x: x.func(*nfloat(x.args, n, exponent)),
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/function.py", line 3082, in nfloat
    return type(expr)([nfloat(a, n, exponent) for a in expr])
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/function.py", line 3082, in <listcomp>
    return type(expr)([nfloat(a, n, exponent) for a in expr])
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/function.py", line 3082, in nfloat
    return type(expr)([nfloat(a, n, exponent) for a in expr])
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/function.py", line 3082, in <listcomp>
    return type(expr)([nfloat(a, n, exponent) for a in expr])
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/function.py", line 3089, in nfloat
    rv = rv.n(n)
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/evalf.py", line 1442, in evalf
    result = evalf(self, prec + 4, options)
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/evalf.py", line 1314, in evalf
    xe = x._eval_evalf(prec)
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/relational.py", line 185, in _eval_evalf
    return self.func(*[s._evalf(prec) for s in self.args])
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/relational.py", line 637, in __new__
    r = cls._eval_relation(lhs, rhs)
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/relational.py", line 946, in _eval_relation
    return _sympify(lhs.__gt__(rhs))
  File "/Users/jeremy/projects/restrepo-1957/code/venv/lib/python3.7/site-packages/sympy/core/expr.py", line 337, in __gt__
    raise TypeError("Invalid comparison of complex %s" % me)
TypeError: Invalid comparison of complex 0.1773711556561315 - 0.4873377415317472*I
```

I have also tried it with the simpler expression

```
f = Piecewise(((x - 1) / (x**3), x < 0.5), (0, True)) - 1 
```

Which also fails, but if I remove the trailing `-1` it reports the error `NotImplementedError: solve cannot represent interval solutions`

**Comment by smichr** [comment]
A workaround is `[i.n(2) for i in solve(nsimplify(f,rational=True,tolerance=0.0001))]'.

**Comment by j2kun** [comment]
Thanks! That seems to work!

But... I have no clue why. Is there a straightforward explanation of why the solver fails without `nsimplify`?

**Comment by oscarbenjamin** [comment]
I'm not sure exactly why this fails. The expression f is
```julia
In [9]: f                                                                                                                         
Out[9]: 
⎛⎧                    3⋅x - 2.0                           ⎞                   
⎜⎪-1.66666666666667 - ─────────  for x < 0.481089134572278⎟                   
⎜⎪                          3                             ⎟                   
⎜⎨                       3⋅x                              ⎟ - 5.32064816919383
⎜⎪                                                        ⎟                   
⎜⎪              0                        otherwise        ⎟                   
⎝⎩                                                        ⎠                   
```
Extracting the significant part we get something easily solvable:
```julia
In [10]: f.args[1].args[0][0]                                                                                                     
Out[10]: 
                    3⋅x - 2.0
-1.66666666666667 - ─────────
                          3  
                       3⋅x   

In [11]: solve(_, x)                                                                                                              
Out[11]: [0.481089134572278, -0.240544567286139 - 0.87953684775149⋅ⅈ, -0.240544567286139 + 0.87953684775149⋅ⅈ]
```
I note there that the real root is equal to the condition in the piecewise (for the digits we see here) which could be problematic.

I guess that the error comes from substituting the complex roots into the piecewise.
