### ISSUE TITLE
Lambdify returns KeyError: 'Exp1' when  called with expression 'exp(1)'

### ISSUE THREAD

**Issue by sirnicolaf** [sympy/sympy#17918]
As said in the title, when you try to lambdify the expression 'exp(1)', lambdify returns KeyError: 'Exp1'. The problem is caused by line 74 in `_print_known_const`(in `pycode.py`). The line is 
`known = self.known_constants[expr.__class__.__name__]`
Here, ` self.known_constants` gives back this dictionnary `{'GoldenRatio': 'scipy.constants.golden_ratio', 'Pi': 'scipy.constants.pi', 'E': 'scipy.constants.e'}` where the value of _e_ (2.718281...) is stored to the `E` key. On the other hand, ` expr.__class__.__name__` return `'Exp1'` which is not a key in the dictionnary, so lambdify is unable to convert the expression.

As far as I know, the problem only arises when you try to lambdify the exponential function to the power of 1. The power of zero returns 1, as expected and the powers above 1 also all seem the return the good value.

Example code;
```
import sympy

sympy.lambdify([],'exp(1)')
```
Will return (I included the full Traceback just in case, but I think only the last 3 lines are important);
```
Traceback (most recent call last):

  File "<ipython-input-1-8461e832a799>", line 1, in <module>
    runfile('/Repertory/anaconda3/lib/python3.7/site-packages/sympy/printing/debugScript.py', wdir='/Repertory/anaconda3/lib/python3.7/site-packages/sympy/printing')

  File "/Repertory/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/Repertory/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Repertory/anaconda3/lib/python3.7/site-packages/sympy/printing/debugScript.py", line 11, in <module>
    sympy.lambdify([],'exp(1)')

  File "/Repertory/anaconda3/lib/python3.7/site-packages/sympy/utilities/lambdify.py", line 767, in lambdify
    funcstr = funcprinter.doprint(funcname, args, expr)

  File "/Repertory/anaconda3/lib/python3.7/site-packages/sympy/utilities/lambdify.py", line 997, in doprint
    funcbody.append('return ({})'.format(self._exprrepr(expr)))

  File "/Repertory/anaconda3/lib/python3.7/site-packages/sympy/printing/codeprinter.py", line 100, in doprint
    lines = self._print(expr).splitlines()

  File "/Repertory/anaconda3/lib/python3.7/site-packages/sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)

  File "/Repertory/anaconda3/lib/python3.7/site-packages/sympy/printing/pycode.py", line 74, in _print_known_const
    known = self.known_constants[expr.__class__.__name__]

KeyError: 'Exp1'
```

**Comment by giorgosgiapis** [comment]
That's interesting! I can't seem to be able to reproduce this error.

**Comment by oscarbenjamin** [comment]
I can reproduce this with SymPy 1.4 but it seems to be fixed in master.

If you try the SymPy 1.5 beta release then you shouldn't see this problem. You can install it with
```
$ pip install --pre sympy
```

**Comment by sirnicolaf** [comment]
> I can reproduce this with SymPy 1.4 but it seems to be fixed in master.
> 
> If you try the SymPy 1.5 beta release then you shouldn't see this problem. You can install it with
> 
> ```
> $ pip install --pre sympy
> ```

Ok good! So no need to fix anything I guess then? Should I go ahead and close the issue?

**Comment by oscarbenjamin** [comment]
Have you tested yourself that it is fixed?
