### ISSUE TITLE
KeyError in Series

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#17942]
`Sum((-1)**n*((1/n)+1),(n, 1, oo)).doit()`

**Comment by ethankward** [comment]
Please provide version, I see no error in master, 1.4, or older releases.

**Comment by ethankward** [comment]
Fixed in master by commit 00105f3947c7e310d91fdbadb56f794f5728ed48.

**Comment by oscarbenjamin** [comment]
On 1.5 (or master) I get:
```
In [1]: Sum((-1)**n*((1/n)+1),(n, 1, oo)).doit()                                                                                  
Out[1]: 
  ∞                
 ____              
 ╲                 
  ╲                
   ╲      n ⎛    1⎞
   ╱  (-1) ⋅⎜1 + ─⎟
  ╱         ⎝    n⎠
 ╱                 
 ‾‾‾‾              
n = 1
```
Should that evaluate to something in particular?

**Comment by ethankward** [comment]
The sum does not converge, which is determined correctly:

```
>>> s = Sum((-1)**n * ((1/n) + 1), [n, 1, oo])
>>> s
Sum((-1)**n*(1 + 1/n), (n, 1, oo))
>>> s.is_convergent
<bound method Sum.is_convergent of Sum((-1)**n*(1 + 1/n), (n, 1, oo))>
>>> s.is_convergent()
False
```

The finite sum has a representation with `lerchphi`, but there's a different error here:

```
>>> Sum(e, [n, 1, m]).doit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eward/se/sympy/concrete/summations.py", line 235, in doit
    newf = eval_sum(f, (i, a, b))
  File "/home/eward/se/sympy/concrete/summations.py", line 987, in eval_sum
    value = eval_sum_symbolic(f.expand(), (i, a, b))
  File "/home/eward/se/sympy/concrete/summations.py", line 1093, in eval_sum_symbolic
    lrsum = telescopic(L, R, (i, a, b))
  File "/home/eward/se/sympy/concrete/summations.py", line 930, in telescopic
    sol = solve(L.subs(i, i + m) + R, m) or []
  File "/home/eward/se/sympy/solvers/solvers.py", line 1198, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/home/eward/se/sympy/solvers/solvers.py", line 1764, in _solve
    soln = _tsolve(f_num, symbol, **flags)
  File "/home/eward/se/sympy/solvers/solvers.py", line 2732, in _tsolve
    e_rat = simplify(posify(e_rat)[0])
  File "/home/eward/se/sympy/simplify/simplify.py", line 659, in simplify
    expr = shorter(expand_log(expr, deep=True), logcombine(expr))
  File "/home/eward/se/sympy/simplify/simplify.py", line 1079, in logcombine
    return bottom_up(expr, f)
  File "/home/eward/se/sympy/simplify/simplify.py", line 1150, in bottom_up
    rv = F(rv)
  File "/home/eward/se/sympy/simplify/simplify.py", line 1072, in f
    num*log(log1.pop(num).args[0]/log1.pop(den).args[0],
KeyError: zoo
```
