### ISSUE TITLE
Random tensorflow failure

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#17951]
See https://travis-ci.org/sympy/sympy/jobs/615612287?utm_medium=notification&utm_source=github_status

I've seen this intermittend failure on various PRs and it seems unrelated to any changes. The failure output is
```
_______ sympy/printing/tests/test_tensorflow.py:test_tensorflow_matrices _______
Traceback (most recent call last):
  File "sympy/utilities/runtests.py", line 1315, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.6.dev0-py2.7.egg/sympy/printing/tests/test_tensorflow.py", line 305, in test_tensorflow_matrices
    _compare_tensorflow_matrix((M,), expr, use_float=True)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.6.dev0-py2.7.egg/sympy/printing/tests/test_tensorflow.py", line 69, in _compare_tensorflow_matrix
    abs(a-b) < 10**-(4-int(log(abs(a), 10))) for a, b in zip(r, e))
AssertionError
```
I'm not sure what causes that but it comes up intermittently so presumably some randomness is involved. In that particular case the seeds are given by
```
============================= test process starts ==============================
executable:         /home/travis/miniconda/envs/test-environment/bin/python  (2.7.15-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 2.1.0b1
numpy:              1.16.5
random seed:        39295092
hash randomization: on (PYTHONHASHSEED=2055549550)
```

**Comment by oscarbenjamin** [comment]
Closing as duplicate of #18090
