### ISSUE TITLE
Deprecate string fallback in sympify

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#18066]
Currently if everything else fails in sympify(), it takes `str(expr)` and tries to parse it. We should deprecate and remove this feature. It is problematic for a few reasons:

- It can affect performance in major ways. See for instance https://github.com/sympy/sympy/issues/18056 and https://github.com/sympy/sympy/issues/15416 where it's caused up to 100x slowdowns. The issue is that whenever a function, and hence sympify is passed something it doesn't know how to sympify, for instance, a Python function type, it passes the string to parse_expr. This is significantly slower than the direct conversions that happen by default. This occurs specifically whenever `sympify()` is used in library code instead of `_sympify()` (or equivalently `sympify(strict=True)`), but presently this is done a lot. We should ultimately stop using strict=True in library code, but this is a harder change to make.

- It can cause security issues, since strings are evaled, and objects can return whatever string they want in their `__repr__`. See also https://github.com/sympy/sympy/pull/12524.

- It really isn't very useful to begin with. Just because an object's string form can be parsed into a SymPy expression doesn't mean it should be parsed that way. This is usually correct for custom numeric types, but an object's repr could be anything. For instance, if the string form of an object looks like a valid Python identifier, it will parse as a Symbol.

There are plenty of ways to make custom objects work inside of sympify(). 

- Firstly, if an object is intended to work alongside other SymPy expressions, it should subclass from Basic (or Expr). If it does, sympify() will just return it unchanged because it will already be a valid SymPy object.

- For objects that you control, you can add the `_sympy_` method. The [sympify docstring](https://docs.sympy.org/latest/modules/core.html#sympy.core.sympify.sympify) has an example of this.

- For objects that you don't control, you can add a custom converter to the `sympy.core.sympify.converter` dictionary (the docstring also has an example of this).

**Comment by sylee957** [comment]
There are some places that needs `strict=True` like in `ElementwiseApplyFunc` or `FuncMatrix` where it had to accept any user defined functions.
They can also be some backdoors for security

**Comment by asmeurer** [comment]
(I'm assuming you mean strict=False, strict=True disables this behavior).

First off, I don't see why it is really needed there. All that does is let you pass in the `lambda` function as a string. But you can just as easily convert it to a `Lambda` first, either manually, or by calling `sympify` yourself. 

Secondly, that is actually unrelated to this, because this is only about the string *fallback*. `sympify` should still convert actual strings. I'm only saying that the conversion of arbitrary objects that sympify doesn't know about by doing `sympify(str(obj))` should be removed. As far as I know, no actual use cases of this exist. If there are any, I guess we will find out once we deprecate it. Any uses in library code can be fixed simply by making it so that sympify knows directly about the corresponding objects. It might break user code, but it should be easy to fix as I noted above.

The use of strict=False everywhere in library code is something else we should do, but that's a separate issue from this one (it will break a lot more user code and should be considered more carefully).

**Comment by asmeurer** [comment]
To clarify, the string fallback doesn't actually let you parse lambda or function objects

```py
>>> sympify(lambda x: x + 1)
Traceback (most recent call last):
  File "./sympy/core/sympify.py", line 385, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "./sympy/parsing/sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "./sympy/parsing/sympy_parser.py", line 903, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    <Symbol ('function' )<lambda >Symbol ('at' )Integer (0x122824b70 )>
    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/core/sympify.py", line 387, in sympify
    raise SympifyError('could not parse %r' % a, exc)
sympy.core.sympify.SympifyError: Sympify of expression 'could not parse '<function <lambda> at 0x122824b70>'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)
```

All that does is waste a lot of time trying to parse `"<function <lambda> at 0x122e829d8>"` as a Python expression.

**Comment by oscarbenjamin** [comment]
I agree that this should be deprecated. The `parse_expr` function should be made more prominent so that you can do
```python
from sympy import parse_expr
```
rather than
```python
from sympy.parsing.sympy_parser import parse_expr
```
The docs can recommend something like
```
from sympy import parse_expr
P = parse_expr
expr = P('x**2 - sin(x)')
```
for users who like to use strings a lot. A lot of users do this so any deprecation needs to lead to a clear explanation of the alternatives.

**Comment by asmeurer** [comment]
Yeah, parse_expr should be in `__init__.py`. It's basically been public API for a while, since it's the only way to access the more advanced things like transformers. There's no reason not to include it.

**Comment by sylee957** [comment]
I saw it was rather advertised in the previous tutorial.

https://github.com/sympy/scipy-2016-tutorial/blob/master/tutorial_exercises/01-Symbols-Derivatives-Functions.ipynb

So the section should be modified too.

**Comment by asmeurer** [comment]
Which part of that advertises this?

**Comment by sylee957** [comment]
In the section called ‘sympify’, it features about passing a string to convert to arbitrary sympy expression

**Comment by asmeurer** [comment]
This issue is *not* about removing the string parsing in sympify. That is a very important feature that shouldn't be removed. This is about calling `str(x)` for arguments that aren't of a type that sympify knows how to parse as a final fallback.

**Comment by sylee957** [comment]
I have reopened this thread to track down the deprecation removal.

**Comment by Amna-A** [comment]
so for now, does this mean that I have to give up on this part of my project where I use sympify to get the first gradient and hard code it  or something ? I see this is still an issue.
