### ISSUE TITLE
Lambdify test failing

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#18079]
https://travis-ci.org/sympy/sympy/jobs/627051548?utm_medium=notification&utm_source=github_status

```python
________________________________________________________________________________
______________________ sympy.utilities.lambdify.lambdify _______________________
File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/utilities/lambdify.py", line 402, in sympy.utilities.lambdify.lambdify
Failed example:
    f.__globals__['sin']
Expected:
    <ufunc 'sin'>
Got:
    <function _deprecated.<locals>.wrap.<locals>.call at 0x7fe9bb18a9d8>
**********************************************************************
File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/utilities/lambdify.py", line 404, in sympy.utilities.lambdify.lambdify
Failed example:
    f.__globals__['cos']
Expected:
    <ufunc 'cos'>
Got:
    <function _deprecated.<locals>.wrap.<locals>.call at 0x7fe9bb1ff510>
**********************************************************************
File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/utilities/lambdify.py", line 406, in sympy.utilities.lambdify.lambdify
Failed example:
    f.__globals__['sin'] is numpy.sin
Expected:
    True
Got:
    False
```

I guess that some external packages have deprecated those functions.
But I'm unable to reproduce the issue with only `numpy` and `tensorflow` installed. Probably some other modules may have to be loaded

**Comment by sylee957** [comment]
I see it can be because of the scipy update.

**Comment by asmeurer** [comment]
We might want to get the fix for this into 1.5.1 @oscarbenjamin

**Comment by oscarbenjamin** [comment]
Yes this should go into 1.5.1. Looks like the fix is:
```diff
diff --git a/sympy/utilities/lambdify.py b/sympy/utilities/lambdify.py
index 72957efa06..0ed0151c95 100644
--- a/sympy/utilities/lambdify.py
+++ b/sympy/utilities/lambdify.py
@@ -697,7 +697,7 @@ def _lambdifygenerated(x):
             else:
                 modules = ["numpy"]
         else:
-            modules = ["scipy", "numpy"]
+            modules = ["numpy", "scipy"]
 
     # Get the needed namespaces.
     namespaces = []
```

**Comment by oscarbenjamin** [comment]
Locally I'm also seeing another failure:
```
_____________________________________ sympy/utilities/tests/test_lambdify.py:test_scipy_fns ______________________________________
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/sympy/sympy/utilities/tests/test_lambdify.py", line 1028, in test_scipy_fns
    assert abs(f(tv) - sympy_result) < 1e-13*(1 + abs(sympy_result))
  File "<lambdifygenerated-146>", line 2, in _lambdifygenerated
    return (factorial(x))
  File "/Users/enojb/current/sympy/37venv/lib/python3.7/site-packages/scipy/special/_basic.py", line 2154, in factorial
    return 0 if n < 0 else gamma(n + 1)
TypeError: '<' not supported between instances of 'complex' and 'int'

============================== tests finished: 94 passed, 6 skipped, 1 exceptions, in 6.92 seconds ===============================
DO *NOT* COMMIT!
```
Looks like the factorial function in scipy expects a real argument

**Comment by sylee957** [comment]
`scipy` may either have changed the factorial function not to work with complexes, or may just have introduced a bug.

**Comment by oscarbenjamin** [comment]
The docstring says it's only for integers:
https://github.com/scipy/scipy/blob/c0dc7fccc53d8a8569cde5d55673fca284bca191/scipy/special/_basic.py#L2001-L2002

**Comment by oscarbenjamin** [comment]
The change in scipy was here:
https://github.com/scipy/scipy/pull/10954
