### ISSUE TITLE
Is the benchmarks code in SymPy still needed?

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#18097]
There is a benchmarks package in sympy that has a few benchmarks tests in it. There is also benchmarks.py in the sympy.utilities package. However there is now a `sympy_benchmarks` repo. 

Is the benchmarking code in the main sympy repo still needed or can it be removed?

CC @moorepants @bjodah

**Comment by sylee957** [comment]
There was a migration attempt
https://github.com/sympy/sympy_benchmarks/pull/10

I think that setup.py script that can run the old benchmarks. I wonder if this should undergo deprecation cycle because of that.

**Comment by moorepants** [comment]
There are some open PRs on the benchmark repo that were made to move the code there, but I don't know if all of the code is present in those PRs and it would be nice to get those PRs merged before deleting anything here.

**Comment by oscarbenjamin** [comment]
There's no rush to delete anything but I'm trying to move things around in #18095 coming from #18091 and I noticed that the benchmarks code seems a bit broken:
```
>>> import sympy.utilities.benchmarking
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/utilities/benchmarking.py", line 6, in <module>
    from py.__.test.item import Item
ModuleNotFoundError: No module named 'py.__'
```

Of course even if it is deleted here in the SymPy repo it will still be in the history for anyone who wants to recover. Given that it doesn't work right now and isn't tested or used it's not gaining anything by being there.

**Comment by asmeurer** [comment]
I think everything should be moved over. The benchmarks are more useful as a separate repo because then they can more easily be run against older versions. I think we just never got around to migrating everything. The `py` import is something that has been broken for a while (it used to use py.bench, I'm not even sure if that exists any more).
