### ISSUE TITLE
Random test failing in tensorflow math

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#18090]
https://travis-ci.org/sympy/sympy/jobs/628093507?utm_medium=notification&utm_source=github_status

```
________________________________________________________________________________
_________ sympy/printing/tests/test_tensorflow.py:test_tensorflow_math _________
Traceback (most recent call last):
  File "sympy/utilities/runtests.py", line 1317, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.6.dev0-py2.7.egg/sympy/printing/tests/test_tensorflow.py", line 170, in test_tensorflow_math
    _compare_tensorflow_scalar((x,), expr, rng=lambda: random.random())
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sympy-1.6.dev0-py2.7.egg/sympy/printing/tests/test_tensorflow.py", line 102, in _compare_tensorflow_scalar
    assert abs(r-e) < 10**-6
AssertionError
```

**Comment by namannimmo10** [comment]
@sylee957 I tried running the tests and it's successful. 

`>>> sympy.test("_tensorflow")`
=========================================================================================== test process starts ===========================================================================================
executable:         /home/namannimmo/.pyenv/versions/3.7.3/bin/python  (3.7.3-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              None
random seed:        27790815
hash randomization: on (PYTHONHASHSEED=1607623356)

sympy/printing/tests/test_tensorflow.py[9] .s.ssss..                                                                                                                                                   [OK]

========================================================================== tests finished: 4 passed, 5 skipped, in 0.07 seconds ===========================================================================
True
>>>

**Comment by sylee957** [comment]
That is the random test, so you may have to run the test like 1000 times to check if the test succeeds

**Comment by namannimmo10** [comment]
Oh, I see.

**Comment by oscarbenjamin** [comment]
Possibly related (from #18390):
```
_______ sympy/printing/tests/test_tensorflow.py:test_tensorflow_matrices _______
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/testing/runtests.py", line 1328, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/printing/tests/test_tensorflow.py", line 305, in test_tensorflow_matrices
    _compare_tensorflow_matrix((M,), expr, use_float=True)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/printing/tests/test_tensorflow.py", line 69, in _compare_tensorflow_matrix
    abs(a-b) < 10**-(4-int(log(abs(a), 10))) for a, b in zip(r, e))
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/printing/tests/test_tensorflow.py", line 69, in <genexpr>
    abs(a-b) < 10**-(4-int(log(abs(a), 10))) for a, b in zip(r, e))
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.6.dev0-py3.6.egg/sympy/core/expr.py", line 300, in __int__
    raise TypeError("can't convert complex to int")
TypeError: can't convert complex to int
```

**Comment by oscarbenjamin** [comment]
Maybe we should xfail these tests

**Comment by sylee957** [comment]
Okay, I’m fine with xfailing these tests.
I’m quite busy now to pay attention to this issue

**Comment by oscarbenjamin** [comment]
I'm marking this as a good first issue. The fix is to add XFAIL to the two tests mentioned as failing above.

**Comment by Chanakya-Ekbote** [comment]
Could you please elaborate. I am not very sure what the task is. Should you just add ```@XFAIL``` before the method that is throwing random errors? Or is there something else?

**Comment by sylee957** [comment]
Yes, try to add `@XFAIL` before the problematic tests.
Numeric quality tests are not important tests we should have.

**Comment by Chanakya-Ekbote** [comment]
Please refer to PR #18469. Thank you.

**Comment by Smit-create** [comment]
Possibly related from #18503
```
________________________________________________________________________________
_______ sympy/printing/tests/test_tensorflow.py:test_tensorflow_matrices _______
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.6.dev0-py3.7.egg/sympy/testing/runtests.py", line 1328, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.6.dev0-py3.7.egg/sympy/printing/tests/test_tensorflow.py", line 305, in test_tensorflow_matrices
    _compare_tensorflow_matrix((M,), expr, use_float=True)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.6.dev0-py3.7.egg/sympy/printing/tests/test_tensorflow.py", line 69, in _compare_tensorflow_matrix
    abs(a-b) < 10**-(4-int(log(abs(a), 10))) for a, b in zip(r, e))
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.6.dev0-py3.7.egg/sympy/printing/tests/test_tensorflow.py", line 69, in <genexpr>
    abs(a-b) < 10**-(4-int(log(abs(a), 10))) for a, b in zip(r, e))
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.6.dev0-py3.7.egg/sympy/core/expr.py", line 300, in __int__
    raise TypeError("can't convert complex to int")
TypeError: can't convert complex to int
=========== tests finished: 8 passed, 1 exceptions, in 1.21 seconds ============
DO *NOT* COMMIT!
Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
Exception: Tests failed

```

**Comment by Arpan612** [comment]
Hi. May I work on this issue?

**Comment by Arpan612** [comment]
@sylee957 Is there any work left here which I can do?

**Comment by smichr** [comment]
> Is there any work left here which I can do?

looks like the PR did not close this. I think the work is done.
