### ISSUE TITLE
ValueError from integrate, sympy 1.5

### ISSUE THREAD

**Issue by nasser1** [sympy/sympy#18133]
I do not know if this is known or not. If it is, please feel free to close this.

Using 1.5 under conda on Linux ubuntu:

```
(base) >python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.5'
>>> from sympy import *
>>> from sympy.abc import t
>>> integrate(exp(t)/(1+t)**2,t)
Traceback (most recent call last):
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/meijerint.py", line 1504, in my_imt
    as_meijerg=True, needeval=True)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 874, in inverse_mellin_transform
    return InverseMellinTransform(F, s, x, strip[0], strip[1]).doit(**hints)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 134, in doit
    for x in fn.args]
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 134, in <listcomp>
    for x in fn.args]
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 123, in doit
    self.function_variable, self.transform_variable, **hints)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 818, in _compute_transform
    return _inverse_mellin_transform(F, s, x, strip, **hints)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 208, in wrapper
    res = func(*args, **kwargs)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 737, in _inverse_mellin_transform
    a, b, C, e, fac = _rewrite_gamma(g, s, strip[0], strip[1])
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 626, in _rewrite_gamma
    if left(c, is_numer):
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 502, in left
    raise MellinTransformStripError('Pole inside critical strip?')
sympy.integrals.transforms.MellinTransformStripError: Pole inside critical strip?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1522, in integrate
    return integral.doit(**doit_flags)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 576, in doit
    function, xab[0], **eval_kwargs)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 919, in _eval_integral
    return NonElementaryIntegral(f, x).doit(risch=False)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 576, in doit
    function, xab[0], **eval_kwargs)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1046, in _eval_integral
    h = meijerint_indefinite(g, x)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/meijerint.py", line 1621, in meijerint_indefinite
    res = _meijerint_indefinite_1(f.subs(x, x + a), x)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/meijerint.py", line 1646, in _meijerint_indefinite_1
    gs = _rewrite1(f, x)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/meijerint.py", line 1569, in _rewrite1
    g = _rewrite_single(g, x, recursive)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/meijerint.py", line 1538, in _rewrite_single
    g = my_imt(F, s, x, strip).subs(a, 1)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/meijerint.py", line 1508, in my_imt
    as_meijerg=True, needeval=True)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 874, in inverse_mellin_transform
    return InverseMellinTransform(F, s, x, strip[0], strip[1]).doit(**hints)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 134, in doit
    for x in fn.args]
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 134, in <listcomp>
    for x in fn.args]
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 123, in doit
    self.function_variable, self.transform_variable, **hints)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 818, in _compute_transform
    return _inverse_mellin_transform(F, s, x, strip, **hints)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 208, in wrapper
    res = func(*args, **kwargs)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/transforms.py", line 740, in _inverse_mellin_transform
    G = meijerg(a, b, C/x**e)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/functions/special/hyper.py", line 462, in __new__
    raise ValueError("no parameter a1, ..., an may differ from "
ValueError: no parameter a1, ..., an may differ from any b1, ..., bm by a positive integer
>>>

```

**Comment by oscarbenjamin** [comment]
I get the same error with 1.4, 1.5 and master.

**Comment by jksuom** [comment]
The call parameters of `meijerg()` on line 740 of transforms.py should be checked somewhere. The easiest way is probably the use of a try-except block:
```@@ -737,7 +737,10 @@ def _inverse_mellin_transform(F, s, x_, strip, as_meijerg=False):
             a, b, C, e, fac = _rewrite_gamma(g, s, strip[0], strip[1])
         except IntegralTransformError:
             continue
-        G = meijerg(a, b, C/x**e)
+        try:
+            G = meijerg(a, b, C/x**e)
+        except ValueError:
+            continue
         if as_meijerg:
             h = G
         else:
```

**Comment by risubaba** [comment]
Hi , can i work on this?

**Comment by jksuom** [comment]
Yes, of course.
