### ISSUE TITLE
TypeError from integrate using sympy 1.5 

### ISSUE THREAD

**Issue by nasser1** [sympy/sympy#18140]
I do not know if this is known issue. If it is, please feel free to close this.

```
(base) >python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.5'
>>> from sympy import *
>>> from sympy.abc import a,x,n
>>> integrate((x**n)-ln(x),x)
-x*log(x) + x + Piecewise((x**(n + 1)/(n + 1), Ne(n, -1)), (log(x), True))
>>> integrate((x**n)*ln(x),x)
Traceback (most recent call last):
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 22, in as_Basic
    return _sympify(expr)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/core/sympify.py", line 418, in _sympify
    return sympify(a, strict=True)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/core/sympify.py", line 286, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1522, in integrate
    return integral.doit(**doit_flags)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 576, in doit
    function, xab[0], **eval_kwargs)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1032, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 188, in heurisch_wrapper
    return Piecewise(*pairs)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/functions/elementary/piecewise.py", line 130, in __new__
    pair = ExprCondPair(*getattr(ec, 'args', ec))
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/functions/elementary/piecewise.py", line 22, in __new__
    expr = as_Basic(expr)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 26, in as_Basic
    expr))
TypeError: Argument must be a Basic object, not `NoneType`
>>>

```
It does not like `x**n`. Changing it to `x**2`, the error goes away

```
>>> integrate((x**2)*ln(x),x)
x**3*log(x)/3 - x**3/9

```

Here is another one that gives same TypeError, I am assuming it is related to same cause. If not, feel free to make it separate issue.

```
>>> integrate(1/(cos(x)+sin(x)),x)
Traceback (most recent call last):
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/matrices/dense.py", line 198, in _eval_matrix_mul
    new_mat[i] = Add(*vec)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/matrices/dense.py", line 196, in <genexpr>
    vec = (mat[a]*other_mat[b] for a,b in zip(row_indices, col_indices))
TypeError: unsupported operand type(s) for *: 'Expression' and 'PolyElement'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1522, in integrate
    return integral.doit(**doit_flags)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 576, in doit
    function, xab[0], **eval_kwargs)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1032, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 136, in heurisch_wrapper
    unnecessary_permutations, _try_heurisch)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 735, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 735, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 489, in heurisch
    unnecessary_permutations=unnecessary_permutations)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 721, in heurisch
    solution = _integrate()
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 709, in _integrate
    solution = solve_lin_sys(numer.coeffs(), coeff_ring, _raw=False)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/polys/solvers.py", line 60, in solve_lin_sys
    v = (echelon[i, p + 1:]*vect)[0]
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/core/decorators.py", line 129, in binary_op_wrapper
    return func(self, other)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/matrices/common.py", line 2205, in __mul__
    return self._eval_matrix_mul(other)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/matrices/dense.py", line 206, in _eval_matrix_mul
    new_mat[i] = reduce(lambda a,b: a + b, vec)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/matrices/dense.py", line 205, in <genexpr>
    vec = (mat[a]*other_mat[b] for a,b in zip(row_indices, col_indices))
TypeError: unsupported operand type(s) for *: 'Expression' and 'PolyElement'
>>>

```
Thank you
--Nasser

**Comment by oscarbenjamin** [comment]
I get the same error in 1.4, 1.5 and master

**Comment by risubaba** [comment]
Should the final output for the first integral be in the simplified form?
I am getting 
`Piecewise((n*x*x**n*log(x)/(n**2 + 2*n + 1) + x*x**n*log(x)/(n**2 + 2*n + 1) - x*x**n/(n**2 + 2*n + 1), Ne(n, -1)))`
as the output after some modification 
and 
`Piecewise((x**(n + 1)*(n*log(x) + log(x) - 1)/(n**2 + 2*n + 1), Ne(n, -1)))`
after calling a simplify function on the output

**Comment by jksuom** [comment]
The SympifyError/TypeError is a known issue with `heurisch_wrapper`, see e.g. https://github.com/sympy/sympy/issues/14613, https://github.com/sympy/sympy/issues/15213. It should not be hard to fix.

The issue with the second integral is the same as in https://github.com/sympy/sympy/issues/17841: an non-simplified expression is not recognized as having value 0. It can be fixed by improving the simplification of the elements of the `EX` domain.

**Comment by risubaba** [comment]
Looking at your comments on the other issues should i add a filter to the values in pair on basis of their return value for isisntance()
@jksuom

**Comment by risubaba** [comment]
@jksuom for the first issue , the _integrate function in heurisch.py is not able to solve the linear equations. Could you suggest some fix for that.

**Comment by jksuom** [comment]
The expr-cond pairs are created by this loop: https://github.com/sympy/sympy/blob/f7390e5fa2313be1c49959270358b2b0c62a1a57/sympy/integrals/heurisch.py#L168-L174
I would check the result of `heurisch` and `continue` without appending anything to `pairs` if the result `expr` is `None`.

**Comment by risubaba** [comment]
If we simply continue without expanding this is the result
```
In [6]: integrate(x**n*log(x),x)           
Out[6]: 
     n             n                  n    
n⋅x⋅x ⋅log(x)   x⋅x ⋅log(x)        x⋅x     
───────────── + ──────────── - ────────────
  2              2              2          
 n  + 2⋅n + 1   n  + 2⋅n + 1   n  + 2⋅n + 1
```
However if we separately calculate integral when `expr` is `None` value using the `integrate()` function, we get this output
```
In [5]: integrate(x**n*log(x),x)
Out[5]: 
⎧     n             n                  n                
⎪n⋅x⋅x ⋅log(x)   x⋅x ⋅log(x)        x⋅x                 
⎪───────────── + ──────────── - ────────────  for n ≠ -1
⎪  2              2              2                      
⎪ n  + 2⋅n + 1   n  + 2⋅n + 1   n  + 2⋅n + 1            
⎨                                                       
⎪                     2                                 
⎪                  log (x)                              
⎪                  ───────                    otherwise 
⎪                     2                                 
⎩                                                
```
The second output is better right?

**Comment by jksuom** [comment]
Yes, it is clearly better to append something. So we could also use `integrate()` to recompute `expr` in case `heurisch()` yields `None`.

**Comment by risubaba** [comment]
Okay. I will add a PR which does that. However in that should I mention that it fixes this issue as it does so only partially. The second integral in the issue still gives an error.
