### ISSUE TITLE
AttributeError: integrate(1 / (1 + x**4)**(S(1)/4), [x, 0, oo])

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#18193]
```
>>> from sympy import *
>>> x = Symbol('x')
>>> integrate(1 / (1 + x**4)**(S(1)/4), [x, 0, oo])
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    print(integrate(1 / (1 + x**4)**(S(1)/4), [x, 0, oo]))
  File "/home/eward/se/sympy/integrals/integrals.py", line 1522, in integrate
    return integral.doit(**doit_flags)
  File "/home/eward/se/sympy/integrals/integrals.py", line 669, in doit
    evalued = Add(*others)._eval_interval(x, a, b)
  File "/home/eward/se/sympy/core/expr.py", line 964, in _eval_interval
    B = _eval_endpoint(left=False)
  File "/home/eward/se/sympy/core/expr.py", line 949, in _eval_endpoint
    C = limit(self, x, c, "+" if left else "-")
  File "/home/eward/se/sympy/series/limits.py", line 71, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
  File "/home/eward/se/sympy/series/limits.py", line 261, in doit
    r = gruntz(e, z, z0, dir)
  File "/home/eward/se/sympy/series/gruntz.py", line 671, in gruntz
    r = limitinf(e0, z)
  File "/home/eward/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/eward/se/sympy/series/gruntz.py", line 435, in limitinf
    c0, e0 = mrv_leadterm(e, x)
  File "/home/eward/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/eward/se/sympy/series/gruntz.py", line 524, in mrv_leadterm
    series = calculate_series(f, w, logx=logw)
  File "/home/eward/se/sympy/series/gruntz.py", line 477, in calculate_series
    for t in e.lseries(x, logx=logx):
  File "/home/eward/se/sympy/core/expr.py", line 2924, in yield_lseries
    for si in s:
  File "/home/eward/se/sympy/core/expr.py", line 3136, in _eval_lseries
    series = self._eval_nseries(x, n=n, logx=logx)
  File "/home/eward/se/sympy/core/mul.py", line 1749, in _eval_nseries
    terms = [t.nseries(x, n=n, logx=logx) for t in self.args]
  File "/home/eward/se/sympy/core/mul.py", line 1749, in <listcomp>
    terms = [t.nseries(x, n=n, logx=logx) for t in self.args]
  File "/home/eward/se/sympy/core/expr.py", line 3223, in nseries
    return self._eval_nseries(x, n=n, logx=logx)
  File "/home/eward/se/sympy/core/function.py", line 673, in _eval_nseries
    a = [t.compute_leading_term(x, logx=logx) for t in args]
  File "/home/eward/se/sympy/core/function.py", line 673, in <listcomp>
    a = [t.compute_leading_term(x, logx=logx) for t in args]
AttributeError: 'TupleArg' object has no attribute 'compute_leading_term'
```

It is trying to compute the `nseries` of a hypergeometric function:

```
>>> hyper((S(1)/4, S(1)/4), (S(5)/4,), exp_polar(I*pi)/x**4).nseries()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eward/se/sympy/core/expr.py", line 3221, in nseries
    return self.series(x, x0, n, dir)
  File "/home/eward/se/sympy/core/expr.py", line 2870, in series
    rv = self.subs(x, xpos).series(xpos, x0, n, dir, logx=logx)
  File "/home/eward/se/sympy/core/expr.py", line 2877, in series
    s1 = self._eval_nseries(x, n=n, logx=logx)
  File "/home/eward/se/sympy/core/function.py", line 673, in _eval_nseries
    a = [t.compute_leading_term(x, logx=logx) for t in args]
  File "/home/eward/se/sympy/core/function.py", line 673, in <listcomp>
    a = [t.compute_leading_term(x, logx=logx) for t in args]
AttributeError: 'TupleArg' object has no attribute 'compute_leading_term'
```

**Comment by jksuom** [comment]
It seems that `hyper` (and other special functions) should have a private `_eval_nseries` method implemented.

**Comment by risubaba** [comment]
I would like to work on this. Could someone please guide where should i start.

**Comment by jksuom** [comment]
I would start by studying the existing implementations. Those can be found by running `git grep 'def _eval_nseries'`.

**Comment by dhruvmendiratta6** [comment]
Why are the following limits taken and how are conditions which decide whether `super()._eval_nseries()` or `self._eval_nseries()` will be called determined ?
https://github.com/sympy/sympy/blob/c31a29a77a8b405d19ef79193ff0878345c62189/sympy/functions/elementary/trigonometric.py#L1136

https://github.com/sympy/sympy/blob/c31a29a77a8b405d19ef79193ff0878345c62189/sympy/functions/special/gamma_functions.py#L195-L196

**Comment by dhruvmendiratta6** [comment]
@jksuom will something like this work:
```
def _eval_nseries(self, x, n, logx, ap, bq):

	from sympy.functions import factorial, RisingFactorial

	x0 = self.args[0].limit(x, 0)

	if not(x0==0):
	return super(gamma, self)._eval_nseries(x, n, logx)

	Rf1 = 1
	Rf2 = 1
	sum = 0

	for i in range(n):
		for p in range(len(ap)):
			Rf1 *= RisingFactorial(a,p+1)
		
		for q in range(len(bq)):
			Rf2 *= RisingFactorial(b,q+1)

		sum += ((Rf1/Rf2)*(x**i))/factorial(i)

	return sum
```
Another idea I had was to use an approach similar to ` _eval_rewrite_as_Sum()` but instead of taking a dummy variable a loop could be implemented

**Comment by jksuom** [comment]
> def _eval_nseries(self, x, n, logx, ap, bq)

`_eval_nseries` has no parameters `ap`, `bq`. If this is for `hyper` (as I assume), then these are the first two arguments of `self`: `self.args[0]` and `self.args[1]`. `x0` will be obtained from `self.args[2]`. This can be seen from the code where instances of `hyper` are created: https://github.com/sympy/sympy/blob/a8a3a3b026cc55aa14010fc7cd7909806b6e116c/sympy/functions/special/hyper.py#L185-L187

`not(x0==0)` is usually written `x0 != 0`.
`return super(gamma, self)._eval_nseries(x, n, logx)`  should not contain gamma if this is for hyper. In fact, I think that `super()` should suffice as Python 2 need not be supported.

Otherwise, the series expansion looks correct (though I did not check carefully).

**Comment by dhruvmendiratta6** [comment]
@jksuom I made the following changes but there are some tests failing locally.
```
--- a/sympy/functions/special/hyper.py
+++ b/sympy/functions/special/hyper.py
@@ -220,6 +220,32 @@ def _eval_rewrite_as_Sum(self, ap, bq, z, **kwargs):
         return Piecewise((Sum(coeff * z**n / factorial(n), (n, 0, oo)),
                          self.convergence_statement), (self, True))

+    def _eval_nseries(self, x, n, logx):
+
+        from sympy.functions import factorial, RisingFactorial
+
+        x0 = self.args[2].limit(x, 0)
+        ap = self.args[0]
+        bq = self.args[1]
+
+        if x0 != 0:
+            return super()._eval_nseries(x, n, logx)
+
+        Rf1 = 1
+        Rf2 = 1
+        series = 0
+
+        for i in range(n):
+            for a in ap:
+                Rf1 *= RisingFactorial(a, i)
+
+            for b in bq:
+                Rf2 *= RisingFactorial(b, i)
+
+            series += ((Rf1 / Rf2) * (x ** i)) / factorial(i)
+
+        return series
+
     @property
     def argument(self):
         """ Argument of the hypergeometric function. """

```
```
________________________________________________________________________________
_______ sympy\functions\special\tests\test_elliptic_integrals.py:test_K ________
Traceback (most recent call last):
  File "c:\users\mendiratta\sympy\sympy\functions\special\tests\test_elliptic_integrals.py", line 41, in test_K
    25*pi*z**3/512 + 1225*pi*z**4/32768 + 3969*pi*z**5/131072 + O(z**6)
AssertionError
________________________________________________________________________________
_______ sympy\functions\special\tests\test_elliptic_integrals.py:test_E ________
Traceback (most recent call last):
  File "c:\users\mendiratta\sympy\sympy\functions\special\tests\test_elliptic_integrals.py", line 111, in test_E
    5*pi*z**3/512 - 175*pi*z**4/32768 - 441*pi*z**5/131072 + O(z**6)
AssertionError
________________________________________________________________________________
___________ sympy\functions\special\tests\test_hyper.py:test_limits ____________
Traceback (most recent call last):
  File "c:\users\mendiratta\sympy\sympy\functions\special\tests\test_hyper.py", line 347, in test_limits
    O(k**6) # issue 6350
AssertionError

 tests finished: 441 passed, 3 failed, 12 skipped, 10 expected to fail,
in 146.80 seconds
DO *NOT* COMMIT!
```
I can't understand why

**Comment by ethankward** [comment]
This is not fixed.

**Comment by dhruvmendiratta6** [comment]
@jksuom Can this be resolved by adding better argument checking to class `TupleArg`.
Also I noticed that `integrate(1 / (1 + x**4)**(1/4), [x, 0, oo])` does not give an error

**Comment by oscargus** [comment]
It seems like `_eval_as _leading_term` must also be implemented for `hyper`.

**Comment by 0sidharth** [comment]
@oscargus `_eval_as_leading_term` was added for `hyper` that returns 1 at the origin otherwise calls `super` (in #21775). I am not sure if a more specific method could be implemented as the general case seems hard to comment on. I had previously discussed this issue with @jksuom and in such cases where the antiderivative cannot be transformed, it was thought that `NotImplementedError` could be raised.

**Comment by oscargus** [comment]
I just noted that it called `super`, which in turn called `as_leading_term` on the `TupleArg` argument of `hyper`, causing as error. No idea how to extend the `_eval_as_leading_term` for `hyper`, but that will, if possible, solve the problem (or implement the same method for `TupleArg`, which may be possible to do similar to the `limit` method of the same class: call `as_leading_term` on the arguments and compose a new object of the results).

**Comment by oscargus** [comment]
I have no idea if that will be correct though...

**Comment by oscargus** [comment]
This is the expression that is fed to `_eval_as_leading_term`: `hyper((1/4, 1/4), (5/4,), exp_polar(I*pi)/x**4)`. Then `x0 = zoo`, including `S.ComplexInfinity` with `S.NaN` in the check here https://github.com/sympy/sympy/blob/fa4182c9e832ead66f6f66ed20f4448a39086f26/sympy/functions/special/hyper.py#L225 leads to a new `x0 = -oo`. Not sure if one can tell something from that?

**Comment by arnabnandikgp** [comment]
I think the problem here is that integration for the expression `1/(1 + x**4)**(S(1)/4)` equates to 
`x*hyper((1/4, 1/4), (5/4,), x**4*exp_polar(I*pi))` and this for the given hyper expression the value of a-b is 0(an integer)
>It is trying to compute the nseries of a hypergeometric function:

and since for such hyper functions thier expansion(or limit) at infinity is not very well [defined](https://functions.wolfram.com/HypergeometricFunctions/Hypergeometric2F1/06/01/05/01/05/0001/)(8th formula here) hence giving us a divergent result as shown here in wolfram alpha
![image](https://github.com/sympy/sympy/assets/97181728/98a63ffb-a42b-4da7-acd9-025dd1ba8042)
maybe we should raise some kind of error while handling such integrals, although after @oscarbenjamin added a `as_leading_term` for `TupleArg` class, sympy now raises a Poleerror for `hyper((S(1)/4, S(1)/4), (S(5)/4,), exp_polar(I*pi)/x**4).nseries()`

**Comment by oscarbenjamin** [comment]
The usual way to handle this in SymPy is to return infinity if that makes sense:
```python
In [1]: integrate(x, (x, 0, oo))
Out[1]: ∞
```
