### ISSUE TITLE
PolynomialError has been raised with solve((tan(x)**2 + 1)*sin(x) + cos(x)*tan(x), x)

### ISSUE THREAD

**Issue by satels** [sympy/sympy#18227]
```python
Python console for SymPy 1.5 (Python 2.7.12)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)

>>> eq = Eq((tan(x)**2 + 1)*sin(x) + cos(x)*tan(x), 0)

>>> solve(eq.doit(), x)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/solvers/solvers.py", line 1174, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/solvers/solvers.py", line 1584, in _solve
    result = _solve(newf, symbol, **flags)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/solvers/solvers.py", line 1751, in _solve
    result = list(map(simplify, result))
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/simplify/simplify.py", line 580, in simplify
    simultaneous=False)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/basic.py", line 1539, in replace
    rv = bottom_up(self, rec_replace, atoms=True)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/simplify/simplify.py", line 1147, in bottom_up
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/simplify/simplify.py", line 1147, in bottom_up
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/simplify/simplify.py", line 1150, in bottom_up
    rv = F(rv)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/basic.py", line 1520, in rec_replace
    new = _value(expr, result)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/core/basic.py", line 1504, in <lambda>
    _value = lambda expr, result: value(expr)
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/simplify/simplify.py", line 579, in <lambda>
    lambda x: x.func(*[simplify(i, **kwargs) for i in x.args]),
  File "/base/data/home/apps/s~sympy-live-hrd/20191227t021942.423433632413966915/sympy/sympy/polys/rootoftools.py", line 322, in __new__
    raise PolynomialError("generator must be a Symbol")
PolynomialError: generator must be a Symbol
```

**Comment by AaronStiff** [comment]
No longer an issue in `1.7.1`:

```pycon
IPython console for SymPy 1.7.1 (Python 3.9.1-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/1.7.1/


In [1]: init_printing(use_unicode = False)

In [2]: eq = Eq((tan(x)**2 + 1)*sin(x) + cos(x)*tan(x), 0)

In [3]: solve(eq.doit(), x)
Out[3]:

                      /   /       ___\        /   ___\\     /   /      ___\
[0, -pi, pi, 2*pi, -I*\log\-1 + \/ 2 / + 2*log\-\/ I //, -I*\log\1 + \/ 2 / +


                                                              /    ___________
     /   ___\\     /   /      ___\        /    5/2\\          |   /   /      _
2*log\-\/ I //, -I*\log\1 + \/ 2 / + 2*log\(-I)   //, -2*I*log\-\/  I*\1 - \/


____\
__\ |    pi        /       ___\    pi        /      ___\  pi        /       __
2 / /, - -- - I*log\-1 + \/ 2 /, - -- - I*log\1 + \/ 2 /, -- - I*log\-1 + \/ 2
         2                         2                      2


_\  pi        /      ___\
 /, -- - I*log\1 + \/ 2 /]
    2
```
