### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'primitive'  using integrate in sympy 1.5

### ISSUE THREAD

**Issue by nasser1** [sympy/sympy#18383]
These below give different error from what I saw before in issue #18140, 18133, so I am opening new bug report just in case this is new bug in sympy integrate. If not, please feel free to close.

Using sympy 1.5 under anaconda 3.7.3

```
(base) >python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> x=symbols('x')
>>> integrate(csc(x)**6/(I+cot(x)),x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1522, in integrate
    return integral.doit(**doit_flags)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 576, in doit
    function, xab[0], **eval_kwargs)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/integrals.py", line 1032, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 136, in heurisch_wrapper
    unnecessary_permutations, _try_heurisch)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 735, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 735, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 489, in heurisch
    unnecessary_permutations=unnecessary_permutations)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 551, in heurisch
    v_split = _splitter(Q)
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 528, in _splitter
    q_split = _splitter(cancel(q / s))
  File "/home/me/anaconda3/lib/python3.7/site-packages/sympy/integrals/heurisch.py", line 516, in _splitter
    c, q = p.as_poly(y).primitive()
AttributeError: 'NoneType' object has no attribute 'primitive'

```

It seems when exponent on csc(x) is integer (other than 1) it fail. For example, all these fail with same error

```
csc(x)**2/(I+cot(x))
csc(x)**3/(I+cot(x))
csc(x)**4/(I+cot(x))
csc(x)**5/(I+cot(x))
csc(x)**6/(I+cot(x))
csc(x)**7/(I+cot(x))
```

Removing complex `I` also removes the error. So this works ok `integrate(csc(x)**2/(3+cot(x)),x)`

--Nasser

**Comment by risubaba** [comment]
This is happening as `gcd` doesn't give correct output if complex numbers are involved.
I tried fixing that but was unable to get a general fix. Could someone suggest a fix to make `gcd` work with complex coefficients.

**Comment by guptapratykshh** [comment]
I think it is giving the right answer but taking immense time in integrating this particular expression.

```
In [1]: from sympy import *

In [2]: x=symbols('x')

In [3]: integrate(csc(x)**6/(I+cot(x)),x)
Out[3]: 
⌠              
⎮     6        
⎮  csc (x)     
⎮ ────────── dx
⎮ cot(x) + ⅈ   
⌡              

In [16]: import timeit

In [17]: from sympy import symbols, csc, cot, integrate, I

In [18]: x = symbols('x')

In [19]: expr = csc(x)**6 / (I + cot(x))

In [20]: execution_time = timeit.timeit(lambda: integrate(expr, x), number=1)

In [21]: print("Time taken:", execution_time, "seconds")
Time taken: 39.466822542017326 seconds
```

**Comment by oscarbenjamin** [comment]
Making gcd work with complex coefficients was fixed in gh-19485.

Calling integrate would be faster with the PR gh-26000.

I'll close this.

**Comment by guptapratykshh** [comment]
Thank you for looking into this.
