### ISSUE TITLE
numba jit cache=True on lambdified sympy expression

### ISSUE THREAD

**Issue by AlexS12** [sympy/sympy#18432]
I am evaluating a big sympy generated expression to solve and ODE. I have been able to accelerate it by applying numba.jit to the lambdified expression. However, as the the compilation of the expression takes a long time I wanted to cache the jitted function. Unfortunately, this step returns an error.

A minimal working example is:

```python
from sympy import symbols, lambdify, sqrt
import numpy as np
from numba import jit


x, y = symbols('x y')

expr = sqrt(x**2 + y**2)

print("Evaluated expression: {}".format(expr))

fun = lambdify((x, y), expr, modules='numpy', dummify=False)

fun_jit = jit(fun, nopython=True)  # works
# fun_jit = jit(fun, nopython=True, cache=True)  # does not work

N = 10000
x, y = np.linspace(0, 100, N), np.linspace(0, 100,  N)

print('lambdify')
fun(x, y)
print('jitted lambdify')
fun_jit(x, y)
```

The error returned is

```
Traceback (most recent call last):
  File "C:\Users\xxx\user_programs\miniconda3_32\envs\py36_64\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-0a062e456430>", line 1, in <module>
    fun_jit = jit(fun, nopython=True, cache=True)
  File "C:\Users\xxx\user_programs\miniconda3_32\envs\py36_64\lib\site-packages\numba\decorators.py", line 161, in jit
    return wrapper(pyfunc)
  File "C:\Users\xxx\user_programs\miniconda3_32\envs\py36_64\lib\site-packages\numba\decorators.py", line 179, in wrapper
    disp.enable_caching()
  File "C:\Users\xxx\user_programs\miniconda3_32\envs\py36_64\lib\site-packages\numba\dispatcher.py", line 571, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "C:\Users\xxx\user_programs\miniconda3_32\envs\py36_64\lib\site-packages\numba\caching.py", line 614, in __init__
    self._impl = self._impl_class(py_func)
  File "C:\Users\xxx\user_programs\miniconda3_32\envs\py36_64\lib\site-packages\numba\caching.py", line 349, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function '_lambdifygenerated': no locator available for file '<lambdifygenerated-6>'
```

Maybe this is more a numba issue, but as I have seen some other lambdify + numba issues here I decided to ask you.

**Comment by oscarbenjamin** [comment]
I can reproduce this without sympy:
```python
>>> from numba import jit
>>> jit(eval('lambda x: x'), nopython=True, cache=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/38venv/lib/python3.8/site-packages/numba/decorators.py", line 175, in jit
    return wrapper(pyfunc)
  File "/Users/enojb/current/sympy/38venv/lib/python3.8/site-packages/numba/decorators.py", line 193, in wrapper
    disp.enable_caching()
  File "/Users/enojb/current/sympy/38venv/lib/python3.8/site-packages/numba/dispatcher.py", line 679, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/Users/enojb/current/sympy/38venv/lib/python3.8/site-packages/numba/caching.py", line 614, in __init__
    self._impl = self._impl_class(py_func)
  File "/Users/enojb/current/sympy/38venv/lib/python3.8/site-packages/numba/caching.py", line 348, in __init__
    raise RuntimeError("cannot cache function %r: no locator available "
RuntimeError: cannot cache function '<lambda>': no locator available for file '<string>'
```
Note that using `lambda x: x` works but `eval('lambda x: x')` does not.

I think this happens because lambdify does something similar: it creates a code string and `eval`s it to get the function it returns. I don't know what other options there are for numba but one possibility would be to get the code generated by lambdify and put it in a file:
```python
>>> print(inspect.getsource(fun))                                                                                                          
def _lambdifygenerated(x, y):
    return (sqrt(x**2 + y**2))
```
Then you can put the jit decorator on that and import it.

**Comment by asmeurer** [comment]
I would open an upstream numba issue about this.

**Comment by asmeurer** [comment]
Putting the source in a file is something that we could make easier. Ideally one could just call some code printer to get everything you need. Right now, you will have to manually add the imports (`from numpy import *` is probably enough for most use cases).

**Comment by AlexS12** [comment]
Thank you for your input! I didn't know that I could get the generated code like that. I followed you advise and opened an issue in numba also. Let's see what they say!
