### ISSUE TITLE
Add a percent (%) transformer to the optional transformers in sympy_parser.py

### ISSUE THREAD

**Issue by yarkaktus** [sympy/sympy#18558]
In spreadsheets such as an Excel / Google Docs spreadsheet, I can calculate the percentage of a number using a percent sign.

Example: Google Spreadsheet for equation  =500*10% give me answer 50.

I want to parse a similar expression with parse_expr, but I get an error
```
>> parse_expr('500*10%')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/path_to_python_libs//lib/python3.8/site-packages/sympy/parsing/sympy_parser.py", line 1008, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/path_to_python_libs/ib/python3.8/site-packages/sympy/parsing/sympy_parser.py", line 902, in eval_expr
    expr = eval(
  File "<string>", line 1
    Integer (500 )*Integer (10 )%
                                ^
SyntaxError: unexpected EOF while parsing
```

maybe there are simple tricks to enable or implement in SimPy processing the percent sign?
or only way is need implement my custom transformation?

thanks

**Comment by susanka068** [comment]
I'd like to work on this issue

**Comment by oscarbenjamin** [comment]
There is no special handling for percentages sympy. You just need to multiply/divide by 100:
```
>>> 500 * 10/100
50.0
```

**Comment by oscarbenjamin** [comment]
The `parse_expr` function is not intended for this. It should mostly just parse Python code.

**Comment by asmeurer** [comment]
I think it wouldn't be difficult to add an optional transformer for percentages to the transformers in sympy_parser.py.

**Comment by sylee957** [comment]
There is `percent` in `physics.units`. What about making a transformer to refer to the unit?

**Comment by yarkaktus** [comment]
@oscarbenjamin @asmeurer @sylee957 
thanks for you answers

in my case, i just make simple string replace 
`expression = expression.replace('%', '/100')`

in most cases this works as expected

**Comment by mocquin** [comment]
> There is `percent` in `physics.units`. What about making a transformer to refer to the unit?

Interested in this approach but not familliar with transformers. My attempt is the following : 
```python
import sympy as sp
from sympy.parsing.sympy_parser import standard_transformations 

def percent_transformer(tokens, local_dict, global_dict):
    return [tok if tok != "%" else  sp.physics.units.percent for tok in tokens]

sp.parsing.sympy_parser.parse_expr("%/K", transformations=((percent_transformer,) + standard_transformations))
```
but I still get a syntax error.

**Comment by markcheeky** [comment]
What about replacing `%` with `*percent` and then use:

```python3
sympy.parse_expr("20+50*percent", local_dict={"percent": sympy.physics.units.percents})
```

**Comment by markcheeky** [comment]
Can you reopen the issue? It is not solved.

Simple `expression.replace('%', '/100')` does not work in general because it does not work well with priority of operations.
For example:
`10% / 20%` should evaluate to `1/2`, but the simple replacement causes it to evaluate as `10/100 / 20/100` which is equal to `1/20000`

The same problem would occur with naive string replacement for `sympy.physics.units.percent`:
```
expr_string = "10% / 20%"
expr = sympy.parse_expr(
    expr_string.replace("%", "*percent"),
    local_dict={"percent": sympy.physics.units.percents},
)
sympy.physics.units.convert_to(expr, 1)
```
This also outputs `1/20000` instead of `1/2`. Adding `implicit_multiplication_application` to the transformations in `parse_expr`  instead of using explicit "*" is not helping either.

**Comment by asmeurer** [comment]
I agree. 

Note that you can also write your own transformer function that does this. A transformer is just a function that takes a list of `tokenize` tokens and a locals and globals dict and returns a new list of tokens. In this case, I think a way to do it would be to replace `x%` with `( x * percent )` (injecting `percent` into the `globals`). See sympy/parsing/sympy_parser.py for examples, and https://www.asmeurer.com/brown-water-python/ for a general guide to using the `tokenize` module. But if you want to contribute it to SymPy I think it would be a good fit to include as a built in transformer.

**Comment by asmeurer** [comment]
Although it would be a little more complex than that if you also want to continue to support `%` as `mod` when it's used as a binary op.

**Comment by smichr** [comment]
> But it assumes

It could be disambiguated if a space were required (when using this transformer) to refer to modulus, e.g. `x% % y%`

**Comment by asmeurer** [comment]
The tokenizer ignores whitespace. That would be tokenized the same as `x%%y%`. Anyway I don't think there should be ambiguity over whether % is binary or unary, similar to how `-` isn't ambiguous.

**Comment by markcheeky** [comment]
But what about cases with implicit multiplication? `10 % (2+3)` could mean either `10 mod 5` or `10 percent multiplied by 5`.

**Comment by asmeurer** [comment]
Just to be clear it is technically possible to extract some whitespace information from the tokens using the `start` and `end` columns. But one should consider that Python in general ignores whitespace in expressions, so making a syntax extension that is whitespace sensitive could be surprising.

> But what about cases with implicit multiplication? 10 % (2+3) could mean either 10 mod 5 or 10 percent multiplied by 5.

Implicit multiplication in general leads to a lot of ambiguity. There's a reason it isn't a native part of the language. How this example actually would end up working would depend on specific details of how the percent transformer is implemented as well as whether it is applied before or after the implicit multiplication transformation.

**Comment by markcheeky** [comment]
Yes, I agree that it is ambiguous. I would propose adding a `percent_notation` transformer to sympy, which would be disabled by default (not part of `standard_transformations`).

In this way, the user could opt-in by including the `percent_notation` transformer, but at the cost that all `%` are interpreted as division by 100 instead of modulo operand. This would be backward compatible and avoids ambiguity.

Sure, it does not cover all cases (one can't have % with different meanings in a single `parse_expr` call), but it's still a useful feature.

What do you think?

plus @asmeurer, could you please share some feedback for my `percent_notation` implementation above? It seems functional to me but I'm not knowledgeable in sympy internals/codebase, so any feedback would be appreciated.
