### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'is_Integer' from equals

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#18603]
```
>>> print(expr)
-M**2/(3*(-M**3)**(1/3)*(-1/2 - sqrt(3)*I/2)) + M/3 - (-M**3)**(1/3)*(-1/2 - sqrt(3)*I/2)/3
>>> expr.equals(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/core/expr.py", line 765, in equals
    constant = diff.is_constant(simplify=False, failing_number=True)
  File "./sympy/core/expr.py", line 691, in is_constant
    if b is not None and b is not S.NaN and b.equals(a) is False:
  File "./sympy/core/expr.py", line 817, in equals
    if all(si.is_Integer for si in sol):
  File "./sympy/core/expr.py", line 817, in <genexpr>
    if all(si.is_Integer for si in sol):
AttributeError: 'dict' object has no attribute 'is_Integer'
```

**Comment by asmeurer** [comment]
Now I can't reproduce this in a new session. Maybe it only occurs randomly.

**Comment by ethankward** [comment]
It happens every time for me.

**Comment by oscarbenjamin** [comment]
I can reproduce this:
```julia
In [7]: M = Symbol('M')                                                                                                                        

In [8]: -M**2/(3*(-M**3)**(S(1)/3)*(-S(1)/2 - sqrt(3)*I/2)) + M/3 - (-M**3)**(S(1)/3)*(-S(1)/2 - sqrt(3)*I/2)/3                                
Out[8]: 
                                   _____             
                                3 ╱   3  ⎛  1   √3⋅ⅈ⎞
              2                 ╲╱  -M  ⋅⎜- ─ - ────⎟
             M              M            ⎝  2    2  ⎠
- ─────────────────────── + ─ - ─────────────────────
       _____                3             3          
    3 ╱   3  ⎛  1   √3⋅ⅈ⎞                            
  3⋅╲╱  -M  ⋅⎜- ─ - ────⎟                            
             ⎝  2    2  ⎠                            

In [9]: _.equals(0)                                                                                                                            
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-1d40fa1e63b0> in <module>
----> 1 _.equals(0)

~/current/sympy/sympy/sympy/core/expr.py in equals(self, other, failing_expression)
    763             return False
    764 
--> 765         constant = diff.is_constant(simplify=False, failing_number=True)
    766 
    767         if constant is False:

~/current/sympy/sympy/sympy/core/expr.py in is_constant(self, *wrt, **flags)
    689                 except ZeroDivisionError:
    690                     b = None
--> 691                 if b is not None and b is not S.NaN and b.equals(a) is False:
    692                     return False
    693                 # try random real

~/current/sympy/sympy/sympy/core/expr.py in equals(self, other, failing_expression)
    815                             # the self-consistent result is present
    816                             return True
--> 817                         if all(si.is_Integer for si in sol):
    818                             # perfect powers are removed at instantiation
    819                             # so surd s cannot be an integer

~/current/sympy/sympy/sympy/core/expr.py in <genexpr>(.0)
    815                             # the self-consistent result is present
    816                             return True
--> 817                         if all(si.is_Integer for si in sol):
    818                             # perfect powers are removed at instantiation
    819                             # so surd s cannot be an integer

AttributeError: 'dict' object has no attribute 'is_Integer'
```

The dict comes from `sol` which comes from the output of `solve`:
https://github.com/sympy/sympy/blob/d90f7eab8cfeddf33a5fdbce3231f45be1918de6/sympy/core/expr.py#L812-L817

The problem seems to come down to this:
```julia
In [8]: expr = (2 - (-1)**(S(1)/6)*sqrt(3) - (-1)**(S(2)/3) + (-1)**(S(5)/6)*sqrt(3) + (-1)**(S(1)/3))/6                                       

In [9]: expr                                                                                                                                   
Out[9]: 
    6 ____          2/3       5/6      3 ____
1   ╲╱ -1 ⋅√3   (-1)      (-1)   ⋅√3   ╲╱ -1 
─ - ───────── - ─────── + ────────── + ──────
3       6          6          6          6   

In [10]: solve(expr, sqrt(3))                                                                                                                  
Out[10]: 
⎡  6 ____         5/6    ⎤
⎢- ╲╱ -1  + 2⋅(-1)    + ⅈ⎥
⎢────────────────────────⎥
⎢               2/3      ⎥
⎣      -1 + (-1)         ⎦

In [11]: solve(expr, (-1)**(S(5)/6))                                                                                                           
Out[11]: 
⎡⎧                                        2/5                    4/5⎫⎤
⎢⎪                              ⎛  √3   ⅈ⎞      √3⋅ⅈ   ⎛  √3   ⅈ⎞   ⎪⎥
⎢⎪                         -2 - ⎜- ── + ─⎟    - ──── + ⎜- ── + ─⎟   ⎪⎥
⎢⎪    5/6    √3   ⅈ  -√3        ⎝  2    2⎠       2     ⎝  2    2⎠   ⎪⎥
⎢⎨(-1)   : - ── + ─, ────: ─────────────────────────────────────────⎬⎥
⎢⎪           2    2   2                         __________          ⎪⎥
⎢⎪                                             ╱   √3   ⅈ           ⎪⎥
⎢⎪                                   √3 + 2⋅5 ╱  - ── + ─           ⎪⎥
⎣⎩                                          ╲╱     2    2           ⎭⎦
```
For some reason solving for `-1**5/6` translates to solving for `-1**5/6` and `sqrt(3)/2` which means solving for two things so that the return from solve becomes a list of dicts.

A simpler reproducer of that:
```julia
In [21]: e = (-1)**(S(5)/6)                                                                                                                    

In [22]: e                                                                                                                                     
Out[22]: 
    5/6
(-1)   

In [23]: solve(e + 1, e)                                                                                                                       
Out[23]: [-1]

In [24]: solve(e + sqrt(3), e)                                                                                                                 
Out[24]: 
⎡⎧            5/6   ⎫  ⎧      -ⅈ⋅π         5/6    π   ⎫⎤
⎢⎨1/2: 0, (-1)   : 0⎬, ⎨1/2: ────────, (-1)   : ──────⎬⎥
⎣⎩                  ⎭  ⎩     2⋅log(3)           log(3)⎭⎦
```

**Comment by asmeurer** [comment]
Calls to `solve` in library API should use dict=True so they get a consistent output type.

**Comment by oscarbenjamin** [comment]
> Calls to `solve` in library API should use dict=True so they get a consistent output type.

That's true but I'm not sure it's the problem here. I asked solve to solve for one thing but it's giving an answer as if I had asked to solve for two things.
