### ISSUE TITLE
Test is failing on master

### ISSUE THREAD

**Issue by mohitacecode** [sympy/sympy#18627]
I think there is some error in master `sympy.test("sympy/parsing/tests/test_c_parser.py")` is failing.

It is giving this error

```
Traceback (most recent call last):
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3365, in register_function
    func = getattr(lib, item[0])
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/tests/test_c_parser.py", line 34, in test_variable
    res1 = SymPyExpression(c_src1, 'c').return_expr()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/sym_expr.py", line 114, in __init__
    self._expr = parse_c(source_code)
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 653, in parse_c
    converter = CCodeConverter('output')
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 85, in __init__
    super(CCodeConverter, self).__init__()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 57, in __init__
    self.index = cin.Index.create()
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 2130, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 141, in __get__
    value = self.wrapped(instance)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3446, in lib
    register_functions(lib, not Config.compatibility_check)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3393, in register_functions
    register (function)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3390, in register
    return register_function(lib, item, ignore_errors)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3371, in register_function
    raise LibclangError(msg)
clang.cindex.LibclangError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens. Please ensure that your python bindings are compatible with your libclang.so version.
_______________________________________________________________________________________________________________________________________________
________________________________________________ sympy/parsing/tests/test_c_parser.py:test_int ________________________________________________
Traceback (most recent call last):
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3365, in register_function
    func = getattr(lib, item[0])
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/tests/test_c_parser.py", line 136, in test_int
    res1 = SymPyExpression(c_src1, 'c').return_expr()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/sym_expr.py", line 114, in __init__
    self._expr = parse_c(source_code)
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 653, in parse_c
    converter = CCodeConverter('output')
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 85, in __init__
    super(CCodeConverter, self).__init__()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 57, in __init__
    self.index = cin.Index.create()
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 2130, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 141, in __get__
    value = self.wrapped(instance)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3446, in lib
    register_functions(lib, not Config.compatibility_check)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3393, in register_functions
    register (function)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3390, in register
    return register_function(lib, item, ignore_errors)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3371, in register_function
    raise LibclangError(msg)
clang.cindex.LibclangError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens. Please ensure that your python bindings are compatible with your libclang.so version.
_______________________________________________________________________________________________________________________________________________
_______________________________________________ sympy/parsing/tests/test_c_parser.py:test_float _______________________________________________
Traceback (most recent call last):
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3365, in register_function
    func = getattr(lib, item[0])
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/tests/test_c_parser.py", line 207, in test_float
    res1 = SymPyExpression(c_src1, 'c').return_expr()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/sym_expr.py", line 114, in __init__
    self._expr = parse_c(source_code)
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 653, in parse_c
    converter = CCodeConverter('output')
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 85, in __init__
    super(CCodeConverter, self).__init__()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 57, in __init__
    self.index = cin.Index.create()
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 2130, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 141, in __get__
    value = self.wrapped(instance)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3446, in lib
    register_functions(lib, not Config.compatibility_check)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3393, in register_functions
    register (function)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3390, in register
    return register_function(lib, item, ignore_errors)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3371, in register_function
    raise LibclangError(msg)
clang.cindex.LibclangError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens. Please ensure that your python bindings are compatible with your libclang.so version.
_______________________________________________________________________________________________________________________________________________
_____________________________________________ sympy/parsing/tests/test_c_parser.py:test_function ______________________________________________
Traceback (most recent call last):
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3365, in register_function
    func = getattr(lib, item[0])
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/tests/test_c_parser.py", line 295, in test_function
    res1 = SymPyExpression(c_src1, 'c').return_expr()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/sym_expr.py", line 114, in __init__
    self._expr = parse_c(source_code)
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 653, in parse_c
    converter = CCodeConverter('output')
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 85, in __init__
    super(CCodeConverter, self).__init__()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 57, in __init__
    self.index = cin.Index.create()
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 2130, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 141, in __get__
    value = self.wrapped(instance)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3446, in lib
    register_functions(lib, not Config.compatibility_check)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3393, in register_functions
    register (function)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3390, in register
    return register_function(lib, item, ignore_errors)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3371, in register_function
    raise LibclangError(msg)
clang.cindex.LibclangError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens. Please ensure that your python bindings are compatible with your libclang.so version.
_______________________________________________________________________________________________________________________________________________
____________________________________________ sympy/parsing/tests/test_c_parser.py:test_parameters _____________________________________________
Traceback (most recent call last):
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3365, in register_function
    func = getattr(lib, item[0])
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/tests/test_c_parser.py", line 376, in test_parameters
    res1 = SymPyExpression(c_src1, 'c').return_expr()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/sym_expr.py", line 114, in __init__
    self._expr = parse_c(source_code)
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 653, in parse_c
    converter = CCodeConverter('output')
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 85, in __init__
    super(CCodeConverter, self).__init__()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 57, in __init__
    self.index = cin.Index.create()
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 2130, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 141, in __get__
    value = self.wrapped(instance)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3446, in lib
    register_functions(lib, not Config.compatibility_check)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3393, in register_functions
    register (function)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3390, in register
    return register_function(lib, item, ignore_errors)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3371, in register_function
    raise LibclangError(msg)
clang.cindex.LibclangError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens. Please ensure that your python bindings are compatible with your libclang.so version.
_______________________________________________________________________________________________________________________________________________
___________________________________________ sympy/parsing/tests/test_c_parser.py:test_function_call ___________________________________________
Traceback (most recent call last):
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3365, in register_function
    func = getattr(lib, item[0])
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/tests/test_c_parser.py", line 474, in test_function_call
    res1 = SymPyExpression(c_src1, 'c').return_expr()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/sym_expr.py", line 114, in __init__
    self._expr = parse_c(source_code)
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 653, in parse_c
    converter = CCodeConverter('output')
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 85, in __init__
    super(CCodeConverter, self).__init__()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 57, in __init__
    self.index = cin.Index.create()
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 2130, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 141, in __get__
    value = self.wrapped(instance)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3446, in lib
    register_functions(lib, not Config.compatibility_check)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3393, in register_functions
    register (function)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3390, in register
    return register_function(lib, item, ignore_errors)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3371, in register_function
    raise LibclangError(msg)
clang.cindex.LibclangError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens. Please ensure that your python bindings are compatible with your libclang.so version.
_______________________________________________________________________________________________________________________________________________
_______________________________________________ sympy/parsing/tests/test_c_parser.py:test_parse _______________________________________________
Traceback (most recent call last):
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3365, in register_function
    func = getattr(lib, item[0])
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/mohit/Downloads/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/tests/test_c_parser.py", line 596, in test_parse
    res1 = SymPyExpression('..a.h', 'c').return_expr()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/sym_expr.py", line 114, in __init__
    self._expr = parse_c(source_code)
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 653, in parse_c
    converter = CCodeConverter('output')
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 85, in __init__
    super(CCodeConverter, self).__init__()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/parsing/c/c_parser.py", line 57, in __init__
    self.index = cin.Index.create()
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 2130, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 141, in __get__
    value = self.wrapped(instance)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3446, in lib
    register_functions(lib, not Config.compatibility_check)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3393, in register_functions
    register (function)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3390, in register
    return register_function(lib, item, ignore_errors)
  File "/home/mohit/Downloads/lib/python3.6/site-packages/clang/cindex.py", line 3371, in register_function
    raise LibclangError(msg)
clang.cindex.LibclangError: /home/mohit/Downloads/bin/python: undefined symbol: clang_annotateTokens. Please ensure that your python bindings are compatible with your libclang.so version.

=========================================== tests finished: 0 passed, 7 exceptions, in 0.16 seconds ===========================================
DO *NOT* COMMIT!
False
>>> 
```

**Comment by namannimmo10** [comment]
You should ignore those failing tests. Basically, two unwanted files `..a.h` and `..b.h` are created when you run all the tests with `sympy.test()`. Make sure you don't add those files with your commit and delete them, I would say. Those tests will pass on the Travis anyway.

**Comment by mohitacecode** [comment]
>Basically, two unwanted files ..a.h and ..b.h are created when you run all the tests with sympy.test()

Yes exactly that is what happening.

**Comment by namannimmo10** [comment]
Maybe this will help you--  https://stackoverflow.com/questions/48663645/clang-cindex-libclangerror-undefined-symbol-clang-cxxrecord-isabstract
I think the process would be the same.

**Comment by mohitacecode** [comment]
ohhk Thanks @namannimmo10 I will look into it and try to fix it.
Any suggestion should I fix it and open a pr @jksuom ?

**Comment by smitgajjar** [comment]
I got the same error once. When libclang and clang versions are not same, it gives this kind of error. Run these commands to resolve it:
`pip uninstall clang`
`sudo aptitude install python-clang-6.0`
`cd /usr/lib/x86_64-linux-gnu/`
`sudo rm libclang.so`
`sudo ln -s libclang-6.0.so.1 libclang.so`
`pip install clang`

Explanation:
Removes current clang from pip, installs python-clang-6.0 via aptitude, removes current key and adds new one, installs clang from pip

After comparing versions of libclang and clang, some proper error message should be displayed by sympy too, I think.
