### ISSUE TITLE
Reduction of n derivative e.g., in integrals of Hermite polynomials using SymPy

### ISSUE THREAD

**Issue by cholmcc** [sympy/sympy#18652]
*SymPy* Version: 1.5.1 (Debian _sid_)

Question first posted on [stackexchange](https://stackoverflow.com/questions/29824790/how-to-check-the-current-version-of-sympy-and-upgrade-to-latest)

I'm trying to get _SymPy_ to reduce expressions with the _n_'th derivative where _n_ is a symbol, not a value.   However, _SymPy_ seems to insist on the order of differentiation be fixed for reduction to work.

Suppose you want to show that that the Hermite polynomials given by 

![formula](https://render.githubusercontent.com/render/math?math=$H_n(x)=(-1)^ne^{x^2}\frac{d^n}{dx^n}e^{-x^2}$)

and we want to show that these are orthogonal on ![formula](https://render.githubusercontent.com/render/math?math=\mathbb{R}) with the inner product defined by 

![formula](https://render.githubusercontent.com/render/math?mode=display&math=$\langle%20f,g\rangle=\int_{-\infty}^{\infty}dx\,f(x)g(x)e^{-x^2}$)

That is, we need to show that 

![formula](https://render.githubusercontent.com/render/math?math=$\langle%20H_k,H_l\rangle=\begin{cases}0%26k\neq%20l%5c%5c1%26k=1\end{cases}$)

To do this in _SymPy_, I do the following 

```python
>>> from sympy import *
>>> x = symbols('x',real=True)
>>> n, k, l = symbols('n k l',integer=True,negative=False)
>>> HN = (-1)**n*exp(x**2)*Derivative(exp(-x**2),(x,n)) 
```

One can evaluate this for various _n_ and get the correct expansion, for example 

```python
>>> [HN.subs(n,nn).doit() for nn in range(5)] 
[1, 2*x, 4*x**2 - 2, -4*x*(3 - 2*x**2), 16*x**4 - 48*x**2 + 12]
``` 
When evaluating the inner product of _H<sub>k</sub>_ with _H<sub>l</sub>_ , however, it fails 

```python 
>>> integrate(HN.subs(n,k)*HN.subs(n,l)*exp(-x**2),(x,-oo,oo))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sympy/integrals/integrals.py", line 1522, in integrate
    return integral.doit(**doit_flags)
  File "/usr/lib/python3/dist-packages/sympy/integrals/integrals.py", line 559, in doit
    ret = try_meijerg(function, xab)
  File "/usr/lib/python3/dist-packages/sympy/integrals/integrals.py", line 531, in try_meijerg
    res = meijerint_definite(function, x, a, b)
  File "/usr/lib/python3/dist-packages/sympy/integrals/meijerint.py", line 1788, in meijerint_definite
    innermost = _find_splitting_points(f, x)
  File "/usr/lib/python3/dist-packages/sympy/integrals/meijerint.py", line 406, in _find_splitting_points
    compute_innermost(expr, innermost)
  File "/usr/lib/python3/dist-packages/sympy/integrals/meijerint.py", line 397, in compute_innermost
    m = expr.match(p*x + q)
  File "/usr/lib/python3/dist-packages/sympy/core/basic.py", line 1663, in match
    return pattern.matches(self, old=old)
  File "/usr/lib/python3/dist-packages/sympy/core/add.py", line 417, in matches
    return AssocOp._matches_commutative(self, expr, repl_dict, old)
  File "/usr/lib/python3/dist-packages/sympy/core/operations.py", line 259, in _matches_commutative
    expr = collect(expr, free)
  File "/usr/lib/python3/dist-packages/sympy/simplify/radsimp.py", line 338, in collect
    for term in expr.args])
  File "/usr/lib/python3/dist-packages/sympy/simplify/radsimp.py", line 338, in <listcomp>
    for term in expr.args])
  File "/usr/lib/python3/dist-packages/sympy/simplify/radsimp.py", line 363, in collect
    terms = [parse_term(i) for i in args]
  File "/usr/lib/python3/dist-packages/sympy/simplify/radsimp.py", line 363, in <listcomp>
    terms = [parse_term(i) for i in args]
  File "/usr/lib/python3/dist-packages/sympy/simplify/radsimp.py", line 253, in parse_term
    sexpr, deriv = parse_derivative(expr)
  File "/usr/lib/python3/dist-packages/sympy/simplify/radsimp.py", line 191, in parse_derivative
    expr, sym, order = deriv.expr, deriv.variables[0], 1
  File "/usr/lib/python3/dist-packages/sympy/core/function.py", line 1668, in variables
    _wrt_variables.'''))
TypeError: 
Cannot give expansion for symbolic count. If you just want a list of
all variables of differentiation, use _wrt_variables.
```
The culprit, as far as I can tell, is that when the `Derivative(exp(-x**2),(x,n))` is reduced, the code underneath (`sympy.simplify.radsimp.parse_derivative`) sees `(x,n)` as free symbols and fails to recognize that `x` is the variable and `n` is a free symbol. 

The question is then 

_Am I doing something wrong?  Is this kind of reduction possible with *SymPy*?_  

BTW, it doesn't work with the predefined special function _hermite_ either.   That is, 

```python
>>> integrate(hermite(k,x)*hermite(l,x)*exp(-x**2),(x,-oo,oo))
Integral(exp(-x**2)*hermite(k, x)*hermite(l, x), (x, -oo, oo))
```
does not give a scaled Kronecker delta.

Thanks

**Comment by oscarbenjamin** [comment]
I guess that handling derivatives with symbolic count just isn't supported yet. I'm not sure what would be needed to get this working for the integral you show but here is a much simpler case that should be easy to handle:
```
In [1]: e = (exp(-x**2)).diff((x, n))                                                                                                          

In [2]: e                                                                                                                                      
Out[2]: 
  n⎛   2⎞
 d ⎜ -x ⎟
───⎝ℯ   ⎠
  n      
dx       

In [3]: integrate(e, x)                                                                                                                        
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-1179cd00c46a> in <module>
----> 1 integrate(e, x)

~/current/sympy/sympy/sympy/integrals/integrals.py in integrate(*args, **kwargs)
   1532 
   1533     if isinstance(integral, Integral):
-> 1534         return integral.doit(**doit_flags)
   1535     else:
   1536         new_args = [a.doit(**doit_flags) if isinstance(a, Integral) else a

~/current/sympy/sympy/sympy/integrals/integrals.py in doit(self, **hints)
    585                     antideriv = None
    586                 else:
--> 587                     antideriv = self._eval_integral(
    588                         function, xab[0], **eval_kwargs)
    589                     if antideriv is None and meijerg is True:

~/current/sympy/sympy/sympy/integrals/integrals.py in _eval_integral(self, f, x, meijerg, risch, manual, heurisch, conds)
   1056                 # rewrite using G functions
   1057                 try:
-> 1058                     h = meijerint_indefinite(g, x)
   1059                 except NotImplementedError:
   1060                     from sympy.integrals.meijerint import _debug

~/current/sympy/sympy/sympy/integrals/meijerint.py in meijerint_indefinite(f, x)
   1619 
   1620     results = []
-> 1621     for a in sorted(_find_splitting_points(f, x) | {S.Zero}, key=default_sort_key):
   1622         res = _meijerint_indefinite_1(f.subs(x, x + a), x)
   1623         if not res:

~/current/sympy/sympy/sympy/integrals/meijerint.py in _find_splitting_points(expr, x)
    405             compute_innermost(arg, res)
    406     innermost = set()
--> 407     compute_innermost(expr, innermost)
    408     return innermost
    409 

~/current/sympy/sympy/sympy/integrals/meijerint.py in compute_innermost(expr, res)
    396         if not isinstance(expr, Expr):
    397             return
--> 398         m = expr.match(p*x + q)
    399         if m and m[p] != 0:
    400             res.add(-m[q]/m[p])

~/current/sympy/sympy/sympy/core/basic.py in match(self, pattern, old)
   1617         """
   1618         pattern = sympify(pattern)
-> 1619         return pattern.matches(self, old=old)
   1620 
   1621     def count_ops(self, visual=None):

~/current/sympy/sympy/sympy/core/add.py in matches(self, expr, repl_dict, old)
    417 
    418     def matches(self, expr, repl_dict={}, old=False):
--> 419         return AssocOp._matches_commutative(self, expr, repl_dict, old)
    420 
    421     @staticmethod

~/current/sympy/sympy/sympy/core/operations.py in _matches_commutative(self, expr, repl_dict, old)
    264                         if free:
    265                             did.update(free)
--> 266                             expr = collect(expr, free)
    267                     if expr != was:
    268                         i += 0

~/current/sympy/sympy/sympy/simplify/radsimp.py in collect(expr, syms, func, evaluate, exact, distribute_order_term)
    361         c, nc = product.args_cnc(split_1=False)
    362         args = list(ordered(c)) + nc
--> 363         terms = [parse_term(i) for i in args]
    364         small_first = True
    365 

~/current/sympy/sympy/sympy/simplify/radsimp.py in <listcomp>(.0)
    361         c, nc = product.args_cnc(split_1=False)
    362         args = list(ordered(c)) + nc
--> 363         terms = [parse_term(i) for i in args]
    364         small_first = True
    365 

~/current/sympy/sympy/sympy/simplify/radsimp.py in parse_term(expr)
    251                 sexpr, rat_expo = exp(tail), coeff
    252         elif isinstance(expr, Derivative):
--> 253             sexpr, deriv = parse_derivative(expr)
    254 
    255         return sexpr, rat_expo, sym_expo, deriv

~/current/sympy/sympy/sympy/simplify/radsimp.py in parse_derivative(deriv)
    189         # scan derivatives tower in the input expression and return
    190         # underlying function and maximal differentiation order
--> 191         expr, sym, order = deriv.expr, deriv.variables[0], 1
    192 
    193         for s in deriv.variables[1:]:

~/current/sympy/sympy/sympy/core/function.py in variables(self)
   1651         for v, count in self.variable_count:
   1652             if not count.is_Integer:
-> 1653                 raise TypeError(filldedent('''
   1654                 Cannot give expansion for symbolic count. If you just
   1655                 want a list of all variables of differentiation, use

TypeError: 
Cannot give expansion for symbolic count. If you just want a list of
all variables of differentiation, use _wrt_variables.
```

**Comment by asmeurer** [comment]
I think you linked to the wrong stackoverflow question.

**Comment by cholmcc** [comment]
Hi

Sorry, for the wrong stackexhange posting - here's the right one 

https://stackoverflow.com/questions/58096306/reduction-of-n-derivative-e-g-in-integrals-of-hermite-polynomials-using-sympy

Thanks @asmeurer 

Yours, 

Christian

**Comment by cholmcc** [comment]
@oscarbenjamin you are of course right, but it seems to me - from looking over the code - that the culprit lies in that the `(x,n)` isn't split to a variable `x` and a free parameter `n`. I don't know how to fix it, but it seems that it is fixable and then the over problem would be solved. 

Christian

**Comment by cholmcc** [comment]
Hi, 

In `sympy.simplify.radsimp.parse_derivatives`  could be 

```python 
w = deriv._wrt_variables 
if len(w) != 1:
    raise NotImplementedError('Improve MV derivative support in collect')

sym = w[0]
expr = deriv.expr

c = [y[1] for in y deriv.variable_count if isinstance(y,Tuple) and y[0] is w[0]]
order = c[0] if len(c) == 1 else 1 

while isinstance(expr,Derivative):
    ww = expr._wrt_variables 
    if len(ww) != 1 or not  ww[0] is sym:
        break
    
    cc = [y[1] for in y expr.variable_count if isinstance(y,Tuple) and y[0] is ww[0]]
    order += cc[0] if len(cc) == 1 else 1 
    expr = expr.expr 

return expr, (sym, order)
```

Note, in the return, `order` may be `Symbol` and I'm not sure how the calling code will deal with that.
