### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by UoPTucson** [sympy/sympy#18678]
I'm trying to find the factors of z = 10**313+1.
I have removed the smaller factors and have left the C230: z = 
42833860072878954404824009229564433270071319650781126324877117522907396604403522744483579046857079731753552239073198452458579773288502846006554974668692035225247494507454866634642274246887388607157375949386373771958956185848070201
I get the following error:
factorint(z)
Traceback (most recent call last):
  File "<pyshell#18>", line 1, in <module>
    factorint(z)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\ntheory\factor_.py", line 1214, in factorint
    n, found_trial = _trial(factors, n, ps, verbose)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\ntheory\factor_.py", line 705, in _trial
    for d in candidates:
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\ntheory\generate.py", line 163, in primerange
    self.extend(b)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\ntheory\generate.py", line 105, in extend
    newsieve = _arange(begin, n + 1)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\ntheory\generate.py", line 27, in _arange
    return _array('l', range(a, b))
OverflowError: Python int too large to convert to C long

**Comment by jksuom** [comment]
It seems that the `generate` module was not designed to deal with integers of arbitrary size. It relies on Python's `array` module that is implemented in C, presumably for efficiency. https://github.com/sympy/sympy/blob/e3a95d9da50e63d49fee2ecf82d0a32965a6d5e6/sympy/ntheory/generate.py#L27-L28
The type code `l` means 'signed long' that usually has 32 bits. It could probably be replaced by `q` that means 'signed long long' with 64 bits. That would make it possible to work with bigger numbers though maybe still not big enough for `factorint(z)`. For Python integers of arbitrary size, it is probably necessary to replace the arrays by ordinary Python lists.

**Comment by mohitacecode** [comment]
I am working on this.

**Comment by UoPTucson** [comment]
You might consider using something like BigInt in C++ to handle the very large numbers.
Thank you for your time.
Randy


-----Original Message-----

**Comment by asmeurer** [comment]
How much does it affect performance? We can fallback to using int if we get OverflowError.

**Comment by asmeurer** [comment]
It looks like this is in the sieve code. Why is it trying to sieve very large numbers? That doesn't seem like it would ever finish, and could easily fill memory.

**Comment by mohitacecode** [comment]
Yes I tried it and it is giving `Error: Operation timed out.`
```
>>> z = 10**313+1
>>> factorint(z)
Error: Operation timed out.
```
