### ISSUE TITLE
linsolve issue

### ISSUE THREAD

**Issue by chelseas** [sympy/sympy#18679]
The following super simple code:

`A = np.matrix([[0.75265217, 0.86388777],
       [0.98795867, 0.61737957]])`
`b = np.matrix([[0.37138249],
       [0.51269589]])`
`x,y = symbols('x,y')`
`linsolve((A,b), x,y)
`

produces the error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Chelsea/miniconda3/envs/ova/lib/python3.7/site-packages/sympy/solvers/solveset.py", line 2523, in linsolve
    recursive=True) for i in system]
  File "/Users/Chelsea/miniconda3/envs/ova/lib/python3.7/site-packages/sympy/solvers/solveset.py", line 2523, in <listcomp>
    recursive=True) for i in system]
  File "/Users/Chelsea/miniconda3/envs/ova/lib/python3.7/site-packages/sympy/core/function.py", line 2789, in _mexpand
    while was != expr:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by chelseas** [comment]
Nevermind, I see now that I have to use sympy type Matrix, not numpy.matrix. This should be made more clear in the documentation.
