### ISSUE TITLE
AttributeError when plotting expressions containing EulerGamma

### ISSUE THREAD

**Issue by alex-fu27** [sympy/sympy#18695]
In sympy 1.5.1, `plot` fails for expressions that contain an EulerGamma:

```
Python 3.8.1 (default, Jan 22 2020, 06:38:00) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> x = symbols("x")
>>> plot(EulerGamma, (x, 0, 1))
/usr/lib/python3.8/site-packages/sympy/plotting/experimental_lambdify.py:233: UserWarning: The evaluation of the expression is problematic. We are trying a failback method that may still work. Please report this as a bug.
  warnings.warn('The evaluation of the expression is'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sympy/plotting/experimental_lambdify.py", line 195, in __call__
    result = complex(self.lambda_func(args))
  File "/usr/lib/python3.8/site-packages/sympy/plotting/experimental_lambdify.py", line 315, in __call__
    return self.lambda_func(*args, **kwargs)
  File "<string>", line 1, in <lambda>
AttributeError: module 'cmath' has no attribute 'eulerGamma'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/sympy/plotting/plot.py", line 1558, in plot
    plots.show()
  File "/usr/lib/python3.8/site-packages/sympy/plotting/plot.py", line 191, in show
    self._backend.show()
  File "/usr/lib/python3.8/site-packages/sympy/plotting/plot.py", line 1248, in show
    self.process_series()
  File "/usr/lib/python3.8/site-packages/sympy/plotting/plot.py", line 1245, in process_series
    self._process_series(series, ax, parent)
  File "/usr/lib/python3.8/site-packages/sympy/plotting/plot.py", line 1074, in _process_series
    collection = self.LineCollection(s.get_segments())
  File "/usr/lib/python3.8/site-packages/sympy/plotting/plot.py", line 663, in get_segments
    f_start = f(self.start)
  File "/usr/lib/python3.8/site-packages/sympy/plotting/experimental_lambdify.py", line 236, in __call__
    if abs(result.imag) > 1e-7 * abs(result):
AttributeError: type object 'EulerGamma' has no attribute 'imag'
```

**Comment by dubesar** [comment]
@alex-fu27  The code you mentioned above runs on my system.

![Screenshot from 2020-02-22 10-59-02](https://user-images.githubusercontent.com/38752758/75087184-05768c80-5563-11ea-828e-4c9a54c0dc93.png)

Maybe there is error due to library not installed well.

**Comment by sylee957** [comment]
I think that the bug exists for matplotlib backend.
You are not using matplotlib.
Maybe you should install matplotlib and check.

**Comment by alex-fu27** [comment]
I tried it both at home and at the university. And that's right, it works using the text backend, but it doesn't work with matplotlib.

**Comment by dubesar** [comment]
@alex-fu27  the plot function is written using matplotlib.
