### ISSUE TITLE
Reparametrization and KL Divergence

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#18718]
AFAIK, the following features aren't available right now in `sympy.stats`,

1. Kullback–Leibler divergence - https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence
2. Reparametrizing one distribution in terms of another - Read section 2.4 of https://arxiv.org/pdf/1312.6114.pdf or 3.1 of https://arxiv.org/pdf/1505.05424.pdf. Though this is related to neural networks but may be symbolically it should be possible to find the deterministic function `t`. This second task is not as necessary because it isn't there in any other CAS. We need to think more about it how it can be helpful to a CAS.

**Comment by Smit-create** [comment]
I would like to work on it. Also, I think this could also be added : [https://en.wikipedia.org/wiki/Cross_entropy](https://en.wikipedia.org/wiki/Cross_entropy)

**Comment by czgdp1807** [comment]
Feel free to propose the APIs as the first step. We will first finalise that and then proceed. Provide some examples and APIs which can be used to solve those examples.

**Comment by Smit-create** [comment]
Referring to the example: [https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence#Basic_example](https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence#Basic_example)
I was able to implement in sympy as following:
```
>>> from sympy.stats import *
>>> from sympy import Piecewise, log, Sum, Eq
>>> from sympy.abc import x
>>> B = Binomial('B', 2, 0.4)
>>> U = Piecewise((1/3, Eq(x, 0)),(1/3, Eq(x, 1)), (1/3, Eq(x, 2)), (0, True))
>>> f = density(B)(x)*log(density(B)(x)/U)
>>> Sum(f, (x, 0, 2)).doit()
0.0852996013183707
>>> f2 = U*log(U/density(B)(x))
>>> Sum(f2, (x, 0, 2)).doit()
0.0974550067853876
```

**Comment by Smit-create** [comment]
So for KL Divergence, we can design an API as:
1. Create a function `KL_divergence`
2. Check whether both rvs have the same` domain.set`, if not `raise` error.
3. if discrete produce required result by `Sum`.
4. if continuous produce required result by `integrate`.

@czgdp1807  Does this seems good?

**Comment by czgdp1807** [comment]
What will be the arguments to the `kl_divergence` function? Random variables or distributions?

**Comment by Smit-create** [comment]
The arguments will be two random variables

**Comment by czgdp1807** [comment]
> The arguments will be two random variables. Sounds good?

Mathematically, KL divergence is defined over distributions rather than random variables. So may be something like,
```python
>>> kl_divergence(NormalDistribution(0, 1), NormalDistribution(1, 1))
```
For the above to be possible, distribution classes should be shifted to `sympy.stats` namespace.

**Comment by Smit-create** [comment]
Yes, they must be shifted, also, I think that the users are generally used to RVs, so could we provide such flexibility of able to use either RVs or Distributions as the parameter.
If they pass RVs, we could go by `density(RV)` else `dist.compute_cdf()`.
Or else to provide this only for distributions, we need to raise an error if RVs are passed

**Comment by Smit-create** [comment]
@czgdp1807 Any comments on [this](https://github.com/sympy/sympy/issues/18718#issuecomment-597671337)?

**Comment by Smit-create** [comment]
ping @czgdp1807

**Comment by Smit-create** [comment]
> For the above to be possible, distribution classes should be shifted to `sympy.stats` namespace.

It might be possible that if we move all the distributions to `sympy.stats` namespace, the import time of the module gets be affected. Please share your thoughts on the type of arguments to be passed into the function.

**Comment by Smit-create** [comment]
@czgdp1807 Please share your thoughts on this.

**Comment by czgdp1807** [comment]
Well, my views are still the same. KL divergence should take distributions as input and return the divergence as output.

P.S. There should be a framework in sympy.stats that can allow users define their own distributions the way we define custom models in TF 2.0.

**Comment by Smit-create** [comment]
> KL divergence should take distributions as input and return the divergence as output.

Okay, I will then move the distributions to `sympy.stats` namespace and add a function for `kl_divergence`

**Comment by adamaequo** [comment]
I know this is a very old issue, but there is still no kl_divergence function available. At the same time, also a cross_entropy function is missing, a function very close to kl_divergence.
I want to propose a user interface in this comment and are willing to also implement it in a merge request.

Commenting on the ongoing discussion from 4 years ago:
- It seems that the NormalDistribution class is hidden from the user on purpose.
- Therefore I think we should write a kl_divergence function, which takes two random variabes as input.
```python
>>> from sympy.stats.crv_types import *
>>> NormalDistribution
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'NormalDistribution' is not defined
>>> from sympy.stats.crv_types import NormalDistribution
>>> NormalDistribution
<class 'sympy.stats.crv_types.NormalDistribution'>
```

Now I would like to propose the user interface:
- the new methods (`kl_divergence`, `cross_entropy`) should be available in the same file, where the `entropy` function can be found.
- therefore I propose to put the code into rv_interface.py
- it should be possible to compute the kl_divergence / cross_entropy for various random variables, no matter if continous/discrete/finite

A user would have the following interface to access the methods:
```python
>>> from sympy.stats import kl_divergence
>>> 
>>> # continous
>>> kl_divergence(Exponential("X", 1), Exponential("Y", 2)).doit()
1 - log(2)
>>> 
>>> # finite
>>> kl_divergence(Die("X", 4), Die("Y", 6)).doit()
log(3/2)
>>> 
>>> # discrete
>>> kl_divergence(Poisson("X", 1), Poisson("Y", 2)).doit()
1 - log(2)
>>> 
>>> # mix of classes is not possible
>>> kl_divergence(Exponential("X", 1), Die("Y", 6)).doit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 52, in kl_divergence
NotImplementedError: Make sure the distributions belong to the same class
```

The cross_entropy function does not need to reinvent the wheel and can just make use of kl_divergence and entropy functions.
```python
def cross_entropy(arg1, arg2, **kwargs):
    """
    https://en.wikipedia.org/wiki/Cross-entropy
    """
    return kl_divergence(arg1, arg2) + entropy(arg1)
```

Usage:
```python
>>> # usage of cross entropy
>>> cross_entropy(Poisson("X", 1), Poisson("Y", 2)).doit()
-log(2) + 1 + Sum(-exp(-1)*log(exp(-1)/factorial(X))/factorial(X), (X, 0, oo))
```

Let me hear your thoughts, wether you think the situation has indeed changed.

**Comment by oscarbenjamin** [comment]
> * It seems that the NormalDistribution class is hidden from the user on purpose.
> * Therefore I think we should write a kl_divergence function, which takes two random variabes as input.

You can use density:
```python
In [1]: from sympy.stats import *

In [2]: X = Normal('X', 0, 1)

In [3]: Y = Normal('Y', 0, 2)

In [4]: density(X)
Out[4]: NormalDistribution(0, 1)

In [5]: density(Y)
Out[5]: NormalDistribution(0, 2)
```
I don't think that it makes sense conceptually to compute the divergence between random variables.

In general it would probably be better if SymPy's stats module provided more of an "algebra" of distributions rather than only random variables.

Is there any clever way to compute KL divergence or cross entropy symbolically that is not just from the sum/integral definition?

**Comment by adamaequo** [comment]
Thanks for showing me that the density operator actually returns the distribution. I did not know that.

> I don't think that it makes sense conceptually to compute the divergence between random variables.

That may be true, and for me as a programmer adding a density function to both arguments before calling the function would be fine.

However then I thought, how I would implement this in code:
- kl_divergence uses Distributions
- cross_entropy uses Distributions
- entropy uses RVs

I cannot pass a distribution to the entropy function:
```
>>> from sympy.stats import *
>>> entropy(Poisson("X", 1))
Sum(-exp(-1)*log(exp(-1)/factorial(X))/factorial(X), (X, 0, oo))
>>> density(Poisson("X", 1))
PoissonDistribution(1)
>>> entropy(density(Poisson("X", 1)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sympy/stats/rv_interface.py", line 141, in entropy
    pdf = density(expr, condition, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sympy/stats/rv.py", line 940, in density
    return Density(expr, condition).doit(evaluate=evaluate, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sympy/stats/rv.py", line 878, in doit
    return Lambda(x, DiracDelta(x - expr))
                                ~~^~~~~~
TypeError: unsupported operand type(s) for -: 'Symbol' and 'PoissonDistribution'
```
So I cannot easily implement the cross entropy just by calling kl_divergence and entropy.

Also looking at the source code: It seems that the doc-string does not reflect, what type the parameter should have. It seems, that the terms Probability Distribution and Random Variable are used interchangeably.
```
def entropy(expr, condition=None, **kwargs):
    """
    Calculuates entropy of a probability distribution.

    Parameters
    ==========

    expression : the random expression whose entropy is to be calculated
```

I have to say I do not have a background in math, so I do not care too much about the specific conceptual differences. Just from a programming experience having functions that take different types seems to me over-complicating the issue.


> Is there any clever way to compute KL divergence or cross entropy symbolically that is not just from the sum/integral definition?

From what I have seen, that is not possible. At least not in the general form. Would be nice though, would make probabilistic inference for a lot of use cases incredibly fast!

**Comment by oscarbenjamin** [comment]
> I cannot pass a distribution to the entropy function:

Maybe that should be changed so that entropy works with distributions.

**Comment by adamaequo** [comment]
That sounds like a complete redesign of the stats module... Let me explain why:
- I tested almost all the functions, listed in the documentation here: https://docs.sympy.org/latest/modules/stats.html#interface
- they all work perfectly fine, if you pass them random variables. But they do not work with distributions!

```
from sympy.stats import *
X = density(Poisson("X", 1))
Y = density(Poisson("X", 3))
entropy(X)
variance(X)
std(X, 3)
covariance(X, Y)
correlation(X, Y)
cmoment(X, 3)
smoment(X, 3)
skewness(X)
kurtosis(X)
factorial_moment(X, 3)
given(X, X > 3)
P(X > 3)
```

The only thing that I found can be used with both types is the following, however I wonder how useful that is. It looks to me like this is just a return default value statement, so the function does not break existing code, not dealing with probabilities.
```
>>> E(density(Poisson("X", 1)))
PoissonDistribution(1)
>>> E(Poisson("X", 1))
1
```

I would conclude, that either the whole design of the module needs to changed, or newly added functions should behave the same way as the old ones. Otherwise it just creates inconsistencies.

**Comment by oscarbenjamin** [comment]
Most of those things should be defined for random variables rather than for distributions although for some either could make sense.

For the KL divergence in particular using random variables does not really make sense because you would have to use two different random variables but in SymPy's stats module distinct random variables are considered to be independent. Really the KL divergence is supposed to be between two different distributions considered for the same random variable but where typically one distribution is the "correct" one and the other is a candidate alternative distribution.

I'm not sure that the design of the whole module should be changed but there should be more of an emphasis on being able to work with distributions for some things rather than using random variables for everything. One thing that has been talked about for example is the idea that you could "simplify" a random variable like if `X` is `Normal(0, 1)` and `Y` is `Normal(0, 1)` then `X + Y` is equivalent to `Normal(0, 2)`. It doesn't make sense to `simplify` the random variable expression `X + Y` but it can make sense to simplify its distribution.
