### ISSUE TITLE
Poly(t**2 + I, t, domain='ZZ[sqrt(-1)]') raises CoercionFailed error

### ISSUE THREAD

**Issue by mohitacecode** [sympy/sympy#18714]
In the current master:
```
Poly(t**2 + I, t, domain='ZZ[sqrt(-1)]')
```
gives 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mohit/Documents/sympy-master/sympy/sympy/polys/polytools.py", line 159, in __new__
    return cls._from_expr(rep, opt)
  File "/home/mohit/Documents/sympy-master/sympy/sympy/polys/polytools.py", line 278, in _from_expr
    return cls._from_dict(rep, opt)
  File "/home/mohit/Documents/sympy-master/sympy/sympy/polys/polytools.py", line 225, in _from_dict
    rep[monom] = domain.convert(coeff)
  File "/home/mohit/Documents/sympy-master/sympy/sympy/polys/domains/domain.py", line 160, in convert
    raise CoercionFailed("can't convert %s of type %s to %s" % (element, type(element), self))
sympy.polys.polyerrors.CoercionFailed: can't convert I of type <class 'sympy.core.symbol.Symbol'> to ZZ[I]
```

**Comment by smitgajjar** [comment]
I tried the same, I am not getting any error, it is working fine!
Look at this:
![image](https://user-images.githubusercontent.com/38134283/75115485-fdaf0900-5684-11ea-9af6-4ae7b2d00883.png)

**Comment by jksuom** [comment]
It is working for me as well. Is it possible that the meaning of `I` was changed somewhere?

**Comment by smitgajjar** [comment]
Yes, I got it, @mohitacecode kept I to be a sympy symbol instead of sympy.core.numbers

**Comment by mohitacecode** [comment]
>Is it possible that the meaning of I was changed somewhere?

Yes you are right. I run this line `from sympy.abc import *` after `from sympy import *` so the `I` was override to `Sympy` Symbol.

**Comment by mohitacecode** [comment]
Closing This issue.
