### ISSUE TITLE
`TypeError: unhashable type: 'MutableDenseMatrix'` for valid quantum gate

### ISSUE THREAD

**Issue by vtomole** [sympy/sympy#18733]
This is a copy and paste of https://quantumcomputing.stackexchange.com/questions/9984/symbolic-quantum-computing-using-sympy-how-to-use-arbitrary-gate. When we try to apply an operation `Ry * Rx` to a qubit, It throws the error stated in the title.

To reproduce

```python
from sympy import Symbol, sin, cos, I, Matrix
from sympy.physics.quantum import qapply
from sympy.physics.quantum.qubit import Qubit
from sympy.physics.quantum.gate import UGate

theta = Symbol('theta')

Ry_mat = Matrix([[cos(theta/2), sin(theta/2)],[sin(theta/2),cos(theta/2)]]) 
Rx_mat = Matrix([[cos(theta/2), sin(theta/2)],[sin(theta/2),cos(theta/2)]]) 

Ry = UGate((0,), Ry_mat)
Rx = UGate((1,), Rx_mat)

c = Ry* Ry

qapply(c*Qubit('00'))

```

Output we get 
```
(venv3.6) vtomole@vtomole:~$ python test.py 
Traceback (most recent call last):
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/basic.py", line 126, in __hash__
    h = hash((type(self).__name__,) + self._hashable_content())
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/basic.py", line 126, in __hash__
    h = hash((type(self).__name__,) + self._hashable_content())
TypeError: unhashable type: 'MutableDenseMatrix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/basic.py", line 126, in __hash__
    h = hash((type(self).__name__,) + self._hashable_content())
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/basic.py", line 126, in __hash__
    h = hash((type(self).__name__,) + self._hashable_content())
TypeError: unhashable type: 'MutableDenseMatrix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 19, in <module>
    qapply(c*Qubit('00'))
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/physics/quantum/qapply.py", line 118, in qapply
    result = c_mul*qapply_Mul(nc_mul, **options)
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/physics/quantum/qapply.py", line 205, in qapply_Mul
    return qapply(e.func(*args)*result, **options)
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/physics/quantum/qapply.py", line 84, in qapply
    e = e.expand(commutator=True, tensorproduct=True)
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/cache.py", line 96, in wrapper
    retval = func(*args, **kwargs)
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/expr.py", line 3191, in expand
    expr, hit = Expr._expand_hint(expr, hint, deep=deep, **hints)
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/expr.py", line 3132, in _expand_hint
    newexpr = getattr(expr, hint)(**hints)
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/mul.py", line 879, in _eval_expand_mul
    terms = self.func._expandsums(sums)
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/mul.py", line 845, in _expandsums
    added = Add(*terms)
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/cache.py", line 96, in wrapper
    retval = func(*args, **kwargs)
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/operations.py", line 47, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/add.py", line 199, in flatten
    if s in terms:
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/basic.py", line 126, in __hash__
    h = hash((type(self).__name__,) + self._hashable_content())
  File "/home/vtomole/venv3.6/lib/python3.6/site-packages/sympy/core/basic.py", line 126, in __hash__
    h = hash((type(self).__name__,) + self._hashable_content())
TypeError: unhashable type: 'MutableDenseMatrix'


```

**Using ImmutableMatrix instead of Matrix fixes the problem.** Is there a reason it doesn't work for `Matrix` or is this a bug?

Related: https://github.com/sympy/sympy/issues/9043

**Comment by sylee957** [comment]
This can be the problem because `quantum` module is not automatically sympifying the matrix types to immutable ones.
I wonder if the quantum module is relying on the mutability of matrices.
If not so, then it would be easier to start coercing the types.

**Comment by Costor** [comment]
There is strong evidence that sylee957 is right. As this behaviour hit me from time to time I experimented to find another minimal example. This also demonstrates how erratic this behaviour is (a scalar factor in the term makes the difference...):

```
from sympy.matrices import Matrix, ImmutableMatrix
from sympy.physics.quantum.gate import UGate
UI = UGate(0, ImmutableMatrix([[1, 0], [0, 1]]))
UM = UGate(0, Matrix([[1, 0], [0, 1]]))
res = 2 * UI**2 * U 
print("ImmutableMatrix: res = ", res)
res = UM**2 * UM        # note that this will work
print("Mutable Matrix, without factor: res = ", res)
res = 2 * UM**2 * UM  # unhashable type: MutableDenseMatrix in cache.py
print("Mutable Matrix, with factor: res = ", res)  # never gets here
```

I don't see why UGate should require mutable matrix, so I would vote to enforce an immutable matrix type there. At least the documentation should clearly emphasise to use an immutable type to avoid potential type errors.

**Comment by ThePauliPrinciple** [comment]
Pretty strange, there seems to be code designed to `_sympify` the matrix (which should turn it into an immutable`):
https://github.com/sympy/sympy/blob/5ba43252efd64bcda5aa0f6bc27debdb6b0fefc2/sympy/physics/quantum/gate.py#L515-L532

**Comment by Costor** [comment]
Solution is simple: The `_sympify(mat)` has been added to the code base after version 1.7.1.  Most probably this bug is probably no longer present.  I'm running on 1.7.1 for some reason, and I silently assumed that as this issue was still open, no one had fixed it.
So would somebody running the latest version of sympy please verify it is gone?
