### ISSUE TITLE
KeyError in creating a polycylic group from Dihedral Group

### ISSUE THREAD

**Issue by mohitacecode** [sympy/sympy#18804]
I am getting this error when `n>2`and `n` is `even` is there any reason we are getting this?if yes should we raise a `exception` instead?
```
>>> G = DihedralGroup(10)
>>> A = G.polycyclic_group()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mohit/Documents/sympy-master/sympy/sympy/combinatorics/perm_groups.py", line 4862, in polycyclic_group
    return PolycyclicGroup(pc_sequence, pc_series, relative_order, collector=None)
  File "/home/mohit/Documents/sympy-master/sympy/sympy/combinatorics/pc_groups.py", line 33, in __init__
    self.collector = Collector(self.pcgs, pc_series, relative_order) if not collector else collector
  File "/home/mohit/Documents/sympy-master/sympy/sympy/combinatorics/pc_groups.py", line 80, in __init__
    self.pc_presentation = self.pc_relators()
  File "/home/mohit/Documents/sympy-master/sympy/sympy/combinatorics/pc_groups.py", line 477, in pc_relators
    word = self.collected_word(word)
  File "/home/mohit/Documents/sympy-master/sympy/sympy/combinatorics/pc_groups.py", line 318, in collected_word
    w = self.minimal_uncollected_subword(word)
  File "/home/mohit/Documents/sympy-master/sympy/sympy/combinatorics/pc_groups.py", line 123, in minimal_uncollected_subword
    if re[index[s1]] and (e1 < 0 or e1 > re[index[s1]]-1):
KeyError: x2**4
>>> G.is_solvable
True
```

**Comment by mohitacecode** [comment]
Ping @jksuom @divyanshu132

**Comment by divyanshu132** [comment]
I think this should work, may be there is some problem with the collection of word.

**Comment by mohitacecode** [comment]
The problem seems in the `pc_relators` function because on line `335` of `pc_groups.py` this (`self.pc_presentation[key]`) is returning a `x2**4` which is a exponential value.

**Comment by divyanshu132** [comment]
Mapped value can be exponential.

**Comment by divyanshu132** [comment]
Replace that line with below lines.
```
presentation = self.pc_presentation[key].array_form
sym, exp = presentation[0]
word_ = ((w[0][0], r), (sym, q*exp))
```

Probably, this will fix the above issue.
