### ISSUE TITLE
incorrect lambdify of constant times dot product

### ISSUE THREAD

**Issue by danshapero** [sympy/sympy#18824]
The following code:

```
import numpy as np
import sympy

x = sympy.MatrixSymbol('x', 3, 1)
H = 0.5 * x.T * x
fn = sympy.lambdify(x, H, 'numpy')
print(fn(np.ones(3)))
````

throws this error:

```
AttributeError: 'numpy.float64' object has no attribute 'dot'
```

The problem is that the lambdified `x.T * x` gives a scalar, which doesn't have a `dot` method.
Likewise, you can trigger the same problem with this code:

```
n = 1
x = MatrixSymbol('x', n, n)
y = MatrixSymbol('y', n, n)
z = MatrixSymbol('z', n, n)
f = lambdify((x, y, z), x*y*z)
a = np.ones(1)
f(a, a, a)
```

This is a different problem from #15827 but the two are similar.
As discussed with @asmeurer this could be fixed by using `np.dot` instead of the arrays `.dot` method.

**Comment by asmeurer** [comment]
The best way to work around this is to always pass in rank-2 arrays for matrices. `dot` has some odd behavior on rank-0 and -1 arrays that is undesirable. In fact, I wonder if we should somehow change the code that is generated to enforce this. For instance, if `a` and `b` are both rank-1, `np.dot(a, b)` treats `a` and `b` as row @ column so that you get a scalar. If you are supposing that rank-1 arrays are always column vectors, this can lead to bugs. Since that is how `MatrixSymbol` works (always rank-2), I think this is very possible.

I opened an upstream numpy issue for scalars not having `dot` https://github.com/numpy/numpy/issues/15737 for anyone interested.

**Comment by asmeurer** [comment]
At any rate, changing the code printer to use `np.dot` instead of `array.dot` is a simple fix for this. I also think we should use `*` for the scalar part of MatMul. If anything, this will make the generated code less confusing to read.

**Comment by asmeurer** [comment]
Another problem with `np.dot` on rank-1 arrays. If you combine a rank-1 and rank-2 array, it treats the rank-1 array as a row vector if it is on the left and a column vector if it is on the right (and it also returns a rank-1 array, meaning it will propagate upward).

```py
>>> x = np.array([1, 2]) # Rank-1 
>>> a = np.array([[1, 2], [3, 4], [5, 6]]) # 3 x 2
>>> b = np.array([[1, 2, 3], [4, 5, 6]]) # 2 x 3

>>> # Treated as (1 x 2) * (3 x 2)
>>> np.dot(x, a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: shapes (2,) and (3,2) not aligned: 2 (dim 0) != 3 (dim 0)
>>> # Treated as (1 x 2) * (2 x 3)
>>> np.dot(x, b)
array([ 9, 12, 15])

>>> # Treated as (3 x 2) * (2 x 1)
>>> np.dot(a, x)
array([ 5, 11, 17])
>>> # Treated as (2 x 3) * (2 x 1)
>>> np.dot(b, x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)
```

But with generated code, you don't even know which arguments are first or second arguments to `dot`. The problem is that we are generating code from MatrixSymbol, which always works like a rank-2 matrix, so can lead to the behavior of the SymPy expression not matching the behavior of the lambdified function. I don't *think* this can produce wrong answers (but I need to think about it further). It can definitely lead to code that you would expect to give some sort of ValueError on incorrect shapes not doing so.

**Comment by asmeurer** [comment]
OK, maybe this is something that could lead to wrong answers. The problem is 

1. dot of two rank-1 arrays produces a rank 0 array (scalar)
2. dot of scalar does scalar multiplication

So you have

```py
>>> from numpy import dot, array
>>> x = array([1, 2, 3])
>>> x = array([1, 2])
>>> A = array([[1, 2], [3, 4]])
>>> dot(dot(x, x), A)
array([[ 5, 10],
       [15, 20]])
>>> dot(x, dot(x, A))
27
```

i.e., `np.dot` is not associative if you don't pass it rank-2 arrays. I can easily see this causing issues with `lambdify`, since the expression you start with can be so far divorced from the code that is generated. 

Observe additionally

- `x.T` gives `x` if `x` is rank-1, so the above can be made "correct" if `x` is actually shape `(2, 1)`. 
- Don't be fooled into thinking it is fine because the left-associated version gives the right answer, and `lambdify` will always produce `dot` calls that are left-associated:

```py
>>> dot(A, dot(x, x))
array([[ 5, 10],
       [15, 20]])
>>> dot(dot(A, x), x)
27
```

I'm not sure if there's a good way to enforce that MatrixSymbol arguments to lambdified functions are rank-2, but we should at least document that it's a very good idea to always use rank-2 arrays numpy to represent matrices in conjunction with lambdify (or generally IMO).

**Comment by asmeurer** [comment]
It looks like we can avoid that by using `@` instead of `dot`, as it disallows rank-0 operations

```py
>>> array(1) @ A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)
```

we couldn't use it previously because of Python 2, but we don't support Python 2 anymore. It doesn't fix the rank 1 issues, but at least we wouldn't get wrong answers by the sort of thing I showed with `dot`.

**Comment by sylee957** [comment]
I think that `@` would be same as using `numpy.matmul`

**Comment by asmeurer** [comment]
I would prefer to use `@` because it's more human-readable, which can make debugging the generated function easier, just like we use `+` and `*` instead of `np.add` and `np.prod`. We have to make sure we get the parentheses right, but that's already the case for other operators. `@` has the exact same precedence as `*` so it shouldn't be hard.
