### ISSUE TITLE
Import sympy fails on Python 3.5

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#18970]
I guess this is to do with my setup since 3.5 is tested on Travis.
```
$ python
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oscar/current/sympy/sympy.git/sympy/__init__.py", line 149, in <module>
    from .concrete import product, Product, summation, Sum
  File "/home/oscar/current/sympy/sympy.git/sympy/concrete/__init__.py", line 2, in <module>
    from .summations import summation, Sum
  File "/home/oscar/current/sympy/sympy.git/sympy/concrete/summations.py", line 3, in <module>
    from sympy.calculus.singularities import is_decreasing
  File "/home/oscar/current/sympy/sympy.git/sympy/calculus/__init__.py", line 4, in <module>
    from .singularities import (singularities, is_increasing,
  File "/home/oscar/current/sympy/sympy.git/sympy/calculus/singularities.py", line 21, in <module>
    from sympy.solvers.solveset import solveset
  File "/home/oscar/current/sympy/sympy.git/sympy/solvers/__init__.py", line 19, in <module>
    from .ode import checkodesol, classify_ode, dsolve, \
  File "/home/oscar/current/sympy/sympy.git/sympy/solvers/ode/__init__.py", line 1, in <module>
    from .ode import (allhints, checkinfsol, classify_ode,
  File "/home/oscar/current/sympy/sympy.git/sympy/solvers/ode/ode.py", line 8458, in <module>
    from .single import (NthAlgebraic, Factorable, FirstLinear, AlmostLinear,
  File "/home/oscar/current/sympy/sympy.git/sympy/solvers/ode/single.py", line 5, in <module>
    from typing import ClassVar, Dict, Iterable, List, Optional, Type
ImportError: cannot import name 'ClassVar'
```

**Comment by smitgajjar** [comment]
`typing.ClassVar` is supported in python version>= 3.5.3. Refer [this](url).

**Comment by jksuom** [comment]
I also have 3.5.2 in Ubuntu 16.04. I had to load 3.6 from Debian and put a symlink to that on local PATH to make importing SymPy possible.

**Comment by oscarbenjamin** [comment]
If we support 3.5 then we should support 3.5.0. I don't know why CPython added this in 3.5.3 but that is not good practice in a point release.

Since we don't actually use mypy it should be easy enough to fix this. The import can just be removed.

Perhaps a better way would be to guard some of these imports like in https://github.com/pydata/xarray/pull/2831

**Comment by jksuom** [comment]
> If we support 3.5 then we should support 3.5.0.

I agree.

**Comment by sava-1729** [comment]
I wish I had opened this issue. I was facing this problem for the past 10 days. I realized that Python3.5.2 (newest version on my OS, Ubuntu 16.04) was the default Python3 and a lot later realized that sympy runs fine on Python3.6, but not on versions lower than that. That way this issue cleared things up for me.
Kindly review my PR.

**Comment by oscarbenjamin** [comment]
Thanks @sava-1729 I guess we're all running Ubuntu 16.04 :). Having been forced to work at home I've started using an older computer again and quickly ran into this.
