### ISSUE TITLE
is_finite_set property not implemented for Range

### ISSUE THREAD

**Issue by sava-1729** [sympy/sympy#18999]
Currently,
```
>>> from sympy import Range
>>> Range(5).is_finite_set

```
returns nothing, since is_finite_set is not implemented in class Range. I'd like to do that. I was thinking of something like this:
```
@property
def is_finite_set(self):
    return self.size.is_finite
```
Any suggestions/views/ideas are highly appreciated. I will submit a PR for the above changes soon.
Also there are some other issues, like:
`sup` and `inf` don't work for ranges in which one of the elements is a symbolic integer, i.e.,
```
>>> from sympy import *
>>> n = Symbol('n', integer=True)
>>> s = Range(n, oo, 1)
>>> s.sup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sava/gsoc/sympy/sympy/sets/sets.py", line 283, in sup
    return self._sup
  File "/home/sava/gsoc/sympy/sympy/sets/fancysets.py", line 898, in _sup
    return self[-1]
  File "/home/sava/gsoc/sympy/sympy/sets/fancysets.py", line 862, in __getitem__
    raise ValueError(ooslice)
ValueError: cannot slice from the end with an infinite value
```
Any ideas regarding fixing the same are highly appreciated, I'd really like to fix it.

**Comment by sava-1729** [comment]
Also,
```
>>> n = Symbol('n', integer=True)
>>> Range(n, -oo).size
oo
```
Even though the size should be zero, because since n is an integer, it must be greater than -oo, therefore Range(n, -oo) would be empty.
The previous problem arises because in Range.size, it says:
```
if dif.is_infinite:
    return S.Infinity
```
We should change this to:
```
if dif.is_infinite:
    if dif.is_positive:
        return S.Infinity
    if dif.is_negative:
        return S.Zero
```
I probed into the previous error a little further, and realized that
```
>>> a = -oo
>>> a.is_negative
False
```
Shouldn't this return True?

**Comment by sava-1729** [comment]
@smichr @oscarbenjamin @asmeurer Could any of you please help me out with this?
Thanks.
