### ISSUE TITLE
sympy.prime() -> OverflowError: int too large to convert to float

### ISSUE THREAD

**Issue by joernheissler** [sympy/sympy#18998]
Hello,

getting an OverflowError when checking if a large (8192 bit) number is a prime.

System is debian/unstable on amd64. Installed sympy from pypi.

```
Package       Version
------------- -------
mpmath        1.1.0  
pip           20.0.2 
pkg-resources 0.0.0  
setuptools    46.1.3 
sympy         1.5.1  
wheel         0.34.2 
```

```python
>>> import sympy
>>> p = 0xec4136d820d4c726637269fb8e24a5e9339580ca2c7a18e0dac7271b48d6bdb526c44e65b91d7e16b4787187e5acaa3b436fd8f224399450fcd09e7cae0f52991893daeccb4a449a80376bf04bb747d157425626cb17da52c8349a830d50fb300057b4e381ec35ac0d4d3f998cbe81c288ea23daf0d565039f124431139295068facb4bdf52c054da6ec59d970b54e8885ff45386391887af901bb278fccd76498633fba6f5c19cee2f01066e50b3fec373ef21b04535b7588d16703433fd556c62046d884f178927b633ece44e5f42447e84be29bcbc1f58c92239ecf4c64f685f6f79b764c2d97b206e27cc3d2e7f40532007a2551c2aaf3eadf62e5e9fb20016e3fd92115fb47357a64b8a4aeb257843c65e2e46b6234b49bc5c954d65a8514d40cc57bc37e47ce3ab56f7c2894f8a4ae0914d7a7196e2ef9ba9431d8b5e407773e6254b011f0a57097831aa1358896517f58a53d1a7f56690b777b671223881557dde3dbbb16679a2ef6116e7f9f76766592a9545dd25800053e79e4e610cb60e9dee06617deabe56d736505c80f3284752fa9588f6fcdd80512f20adc97fa75842d80529069700530293d746684b7038e7e400bd3f32b600e726cc545c0a97c4294539574a09e7ffb00d057f8ac04a38883ec6d6d8382c2bcd76783c251635236e313b37e8a20f4c206de7fbddd462072c81cbcb75391c44d7232b9faf1ab38100defe4b8dafa3651e0e5333e793e9d5200a0c6abd2420109f00df919f9708ce31c106cdd91653d37d51d8606b9f09f79995c84ad442e96f283d69d801d0b2670502a7fd534c01e4ffec327a9dd201e8d18c8880d456a68351917ccdf0df364ac2360f26dfb9666b5c53c3fa3102d229abf0e239a7622587709d3f28180a64425b64e2d4606c8e6caa386a8d5feb84dd9327d370ea4543332bc0edffa569a75f2e3bfdc59bcc5b2fa806c5034b6542680cd95acd57ac55c78154d87e6d4157018564db6f1f556cf5ad7b5c6982b981e5135c7a0938780f2899f98b652ea4d9f5557df211f1afe9cb745a72e7b4b33953db414fe769d1aca358b932b8b61663464d1734221469910fab1fd1358afe0ee28b8802753ce7259789795bc9d54acc746b61ffb8dfa16ca74c180b3dd2c72bfab741d15a720fbfedb2d2eda2f6e4fbc6c3564035c3f0c711ee3d6783aacb814e3bb7bd9285c1ab129bde002b78a2831ab11373d6d4301acd3e79193321151e1b13fc82ae7a331fe08e103a78d03f3dd3a17f69b6e3ff8f18ea07c87beabc9ceea19859aa0c0e9ae4e623a8941f0509f8d35fd4f367f7d40363336a20bbef9921b9274184cd0e7115c88c8db8b59105ea19a2085be82437feb744e268250311d11c9d2b367265cad692cf808078d17464c996826c8a9d17d88b13f28ffe10f928ad591d2f027347b6c4d4806ca49
>>> sympy.prime(p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.venv/sympy/lib/python3.8/site-packages/sympy/ntheory/generate.py", line 386, in prime
    n_primes = primepi(a - 1)
  File "/home/user/.venv/sympy/lib/python3.8/site-packages/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/user/.venv/sympy/lib/python3.8/site-packages/sympy/core/function.py", line 473, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/home/user/.venv/sympy/lib/python3.8/site-packages/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/user/.venv/sympy/lib/python3.8/site-packages/sympy/core/function.py", line 288, in __new__
    evaluated = cls.eval(*args)
  File "/home/user/.venv/sympy/lib/python3.8/site-packages/sympy/ntheory/generate.py", line 479, in eval
    lim = int(n ** 0.5)
OverflowError: int too large to convert to float
```

**Comment by joernheissler** [comment]
Never mind, I have been wanting to use `isprime`, not `prime`.
