### ISSUE TITLE
signsimp() create invalid tree when matrices are involved

### ISSUE THREAD

**Issue by jlherren** [sympy/sympy#18991]
I have an expression involving symbolic matrices that raises an error when given to `simplify()`. I reduced it to the following code which also fails:
```
from sympy import *
A = MatrixSymbol('A', 2, 2)
e = signsimp(-A * A - A)
print(e)
```
Stack trace:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    e = signsimp(-A * A - A)
  File "/path/sympy/sympy/simplify/simplify.py", line 385, in signsimp
    e = sub_post(sub_pre(expr))
  File "/path/sympy/sympy/simplify/cse_opts.py", line 29, in sub_pre
    e = e.xreplace(negs)
  File "/path/sympy/sympy/core/basic.py", line 1148, in xreplace
    value, _ = self._xreplace(rule)
  File "/path/sympy/sympy/core/basic.py", line 1163, in _xreplace
    a_xr = _xreplace(rule)
  File "/path/sympy/sympy/core/basic.py", line 1170, in _xreplace
    return self.func(*args), True
  File "/path/sympy/sympy/matrices/expressions/matmul.py", line 48, in __new__
    factor, matrices = obj.as_coeff_matrices()
  File "/path/sympy/sympy/matrices/expressions/matmul.py", line 114, in as_coeff_matrices
    raise NotImplementedError("noncommutative scalars in MatMul are not supported.")
NotImplementedError: noncommutative scalars in MatMul are not supported.
```
Obviously no noncommutative scalars are involved here. The reason seems to be a `Mul` object that has matrix arguments, which to my understanding is an invalid tree. The following diff fixes the problem, but I'm unsure whether that is the correct fix:
```
diff --git a/sympy/simplify/cse_opts.py b/sympy/simplify/cse_opts.py
index 754394d43f..16daefc0ba 100644
--- a/sympy/simplify/cse_opts.py
+++ b/sympy/simplify/cse_opts.py
@@ -14,7 +14,7 @@ def sub_pre(e):
     """
     # replacing Add, A, from which -1 can be extracted with -1*-A
     adds = [a for a in e.atoms(Add) if a.could_extract_minus_sign()]
-    reps = dict((a, Mul._from_args([S.NegativeOne, -a])) for a in adds)
+    reps = dict((a, Mul(S.NegativeOne, -a)) for a in adds)
     e = e.xreplace(reps)
 
     # repeat again for persisting Adds but mark these with a leading 1, -1
```
`Mul._from_args()` always seems to create a `Mul` object, whereas `Mul(...)` checks its arguments and returns a `MatMul` if the arguments are matrices.

Would the above be an acceptable fix? `Mul._from_args()` is probably being used for performance reasons, which is lost when using `Mul()`. So perhaps `Mul._from_args()` should be fixed instead... (Note: there are more calls to `Mul._from_args()` in that file.)

**Comment by jlherren** [comment]
This seems much more sensible:
```
diff --git a/sympy/core/mul.py b/sympy/core/mul.py
index a7801c0958..455195ba68 100644
--- a/sympy/core/mul.py
+++ b/sympy/core/mul.py
@@ -94,6 +94,15 @@ class Mul(Expr, AssocOp):
 
     is_Mul = True
 
+    @classmethod
+    def _from_args(cls, args, is_commutative=None):
+        """Create new instance with already-processed args.
+        Make sure to return MatMul if any argument is a matrix"""
+        from sympy.matrices.expressions.matmul import MatMul
+        if cls is not MatMul and any(a.is_Matrix for a in args):
+            return MatMul._from_args(args, is_commutative)
+        return super(Mul, cls)._from_args(args, is_commutative)
+
     def __neg__(self):
         c, args = self.as_coeff_mul()
         c = -c
```
Unfortunately it breaks `test_issue_3959`.
