### ISSUE TITLE
Smith Normal Form error, Gaussian Integers

### ISSUE THREAD

**Issue by jrexmo** [sympy/sympy#19002]
It looks like the `smith_normal_form()` function is unable to recognize that the entries of a matrix do in fact come from a PID. In particular, 
``` python
>>> from sympy import I
>>> from sympy.matrices import eye
>>> from sympy.matrices.normalforms import smith_normal_form
>>> A = I*eye(3, 4)
>>> smith_normal_form(A)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jackmorris/sympy/sympy/matrices/normalforms.py", line 24, in smith_normal_form
    invs = invariant_factors(m, domain=domain)
  File "/Users/jackmorris/sympy/sympy/matrices/normalforms.py", line 48, in invariant_factors
    "The matrix entries must be over a principal ideal domain")
ValueError: The matrix entries must be over a principal ideal domain
```
I realize that I could just set domain to be the Gaussian integers, but is there any way that we could recognize that the Gaussian integers are the "smallest" ring that the entries of this matrix come from and then set that to be the domain?

**Comment by oscarbenjamin** [comment]
The Gaussian integers are not explicitly implemented as a domain yet #15396

**Comment by oscarbenjamin** [comment]
The Gaussian integers are now added as the `ZZ_I` domain. The PR https://github.com/sympy/sympy/pull/21402 moves the Smith Normal Form code to DomainMatrix which can recognise the Gaussian integers automatically. However there are two problems:

1. `ZZ_I` does not has `is_PID=True` set.
2. The SNF routines need `gcdex` which is not implemented for the Gaussian domains.
