### ISSUE TITLE
valid latex input is not parsed by ANTLR

### ISSUE THREAD

**Issue by bhpayne** [sympy/sympy#19075]
I have a Latex math expression that has an explicit space. This causes sympy.parsing.latex.errors.LaTeXParsingError to raise an exception. 

None of the Latex spacings of `\ ` or `\,` or `\:` or `\;` appear to be parsed by ANTLR. 

These spacings are used on [Wikipedia](https://en.wikipedia.org/wiki/Help:Displaying_a_formula#Spacing) and are in the [amsmath documentation](https://www.latex-project.org/help/documentation/amsldoc.pdf)

The output for the first is below. 

    $ python3
    Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
    [GCC 8.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import sympy
    >>> sympy.__version__
    '1.5.1'
    >>> from sympy.parsing.latex import parse_latex
    >>> parse_latex('\lambda = v\ T')
    ANTLR runtime and generated code versions disagree: 4.8!=4.7.1
    ANTLR runtime and generated code versions disagree: 4.8!=4.7.1
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/antlr4/Lexer.py", line 128, in nextToken
        ttype = self._interp.match(self._input, self._mode)
      File "/usr/local/lib/python3.6/dist-packages/antlr4/atn/LexerATNSimulator.py", line 99, in match
        return self.execATN(input, dfa.s0)
      File "/usr/local/lib/python3.6/dist-packages/antlr4/atn/LexerATNSimulator.py", line 191, in execATN
        return self.failOrAccept(self.prevAccept, input, s.configs, t)
      File "/usr/local/lib/python3.6/dist-packages/antlr4/atn/LexerATNSimulator.py", line 250, in failOrAccept
        raise LexerNoViableAltException(self.recog, input, self.startIndex, reach)
    antlr4.error.Errors.LexerNoViableAltException: LexerNoViableAltException('\')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.6/dist-packages/sympy/parsing/latex/__init__.py", line 34, in parse_latex
        return _latex.parse_latex(s)
      File "/usr/local/lib/python3.6/dist-packages/sympy/parsing/latex/_parse_latex_antlr.py", line 83, in parse_latex
        relation = parser.math().relation()
      File "/usr/local/lib/python3.6/dist-packages/sympy/parsing/latex/_antlr/latexparser.py", line 394, in math
        self.relation(0)
      File "/usr/local/lib/python3.6/dist-packages/sympy/parsing/latex/_antlr/latexparser.py", line 475, in relation
        self.relation(3)
      File "/usr/local/lib/python3.6/dist-packages/sympy/parsing/latex/_antlr/latexparser.py", line 451, in relation
        self.expr()
      File "/usr/local/lib/python3.6/dist-packages/sympy/parsing/latex/_antlr/latexparser.py", line 553, in expr
        self.additive(0)
      File "/usr/local/lib/python3.6/dist-packages/sympy/parsing/latex/_antlr/latexparser.py", line 601, in additive
        self.mp(0)
      File "/usr/local/lib/python3.6/dist-packages/sympy/parsing/latex/_antlr/latexparser.py", line 689, in mp
        self.unary()
      File "/usr/local/lib/python3.6/dist-packages/sympy/parsing/latex/_antlr/latexparser.py", line 872, in unary
        self.postfix()
      File "/usr/local/lib/python3.6/dist-packages/sympy/parsing/latex/_antlr/latexparser.py", line 1003, in postfix
        self.exp(0)
      File "/usr/local/lib/python3.6/dist-packages/sympy/parsing/latex/_antlr/latexparser.py", line 1357, in exp
        self.comp()
      File "/usr/local/lib/python3.6/dist-packages/sympy/parsing/latex/_antlr/latexparser.py", line 1558, in comp
        la_ = self._interp.adaptivePredict(self._input,20,self._ctx)
      File "/usr/local/lib/python3.6/dist-packages/antlr4/atn/ParserATNSimulator.py", line 342, in adaptivePredict
        alt = self.execATN(dfa, s0, input, index, outerContext)
      File "/usr/local/lib/python3.6/dist-packages/antlr4/atn/ParserATNSimulator.py", line 465, in execATN
        input.consume()
      File "/usr/local/lib/python3.6/dist-packages/antlr4/BufferedTokenStream.py", line 99, in consume
        if self.sync(self.index + 1):
      File "/usr/local/lib/python3.6/dist-packages/antlr4/BufferedTokenStream.py", line 111, in sync
        fetched = self.fetch(n)
      File "/usr/local/lib/python3.6/dist-packages/antlr4/BufferedTokenStream.py", line 123, in fetch
        t = self.tokenSource.nextToken()
      File "/usr/local/lib/python3.6/dist-packages/antlr4/Lexer.py", line 130, in nextToken
        self.notifyListeners(e)		# report error
      File "/usr/local/lib/python3.6/dist-packages/antlr4/Lexer.py", line 285, in notifyListeners
        listener.syntaxError(self, None, self._tokenStartLine, self._tokenStartColumn, msg, e)
      File "/usr/local/lib/python3.6/dist-packages/antlr4/error/ErrorListener.py", line 60, in syntaxError
        delegate.syntaxError(recognizer, offendingSymbol, line, column, msg, e)
      File "/usr/local/lib/python3.6/dist-packages/sympy/parsing/latex/_parse_latex_antlr.py", line 57, in syntaxError
        raise LaTeXParsingError(err)
    sympy.parsing.latex.errors.LaTeXParsingError: I don't understand this
    \lambda = v\ T
    ~~~~~~~~~~~^

**Comment by bhpayne** [comment]
I think the Sympy source file to be edited would be https://github.com/sympy/sympy/blob/master/sympy/parsing/latex/LaTeX.g4

**Comment by bhpayne** [comment]
The problem is more challenging than I thought. The challenge is the difference between Latex being for presentation and Sympy having semantic meaning.

To display addition of two variables in Latex, I could write

    a + b

or

    a\\ +\\ b

In that context, the `\\ ` is used for changing the presentation but not the math. To multiply two numbers, I could write

    a b

or

    a\\ b

If I don't include the space, `ab` might be a single variable or two. So we can't treat white space as multiplication, and we can't ignore white space.

**Comment by bhpayne** [comment]
This issue is better addressed by removing spaces before the string is passed to Sympy.
