### ISSUE TITLE
Sampling from Student T distribution fails

### ISSUE THREAD

**Issue by maichmueller** [sympy/sympy#19095]
Hello,
trying to sample from a Student-T distribution fails.

Code:
```
from sympy.stats import StudentT, sample_iter
samples = list(sample_iter(StudentT("", 2), numsamples=1))
```

Error message

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-6e39a94cf726> in <module>
----> 1 samples = list(sample_iter(StudentT("", 2), numsamples=1))

~/anaconda3/envs/causalpy/lib/python3.7/site-packages/sympy/stats/rv.py in sample_iter_subs(expr, condition, numsamples, **kwargs)
   1178     count = 0
   1179     while count < numsamples:
-> 1180         d = ps.sample()  # a dictionary that maps RVs to values
   1181 
   1182         if condition is not None:  # Check that these values satisfy the condition

~/anaconda3/envs/causalpy/lib/python3.7/site-packages/sympy/stats/crv.py in sample(self)
    506         Returns dictionary mapping RandomSymbol to realization value.
    507         """
--> 508         return {self.value: self.distribution.sample()}
    509 
    510     def compute_expectation(self, expr, rvs=None, evaluate=False, **kwargs):

~/anaconda3/envs/causalpy/lib/python3.7/site-packages/sympy/stats/crv.py in sample(self)
    172     def sample(self):
    173         """ A random realization from the distribution """
--> 174         icdf = self._inverse_cdf_expression()
    175         return icdf(random.uniform(0, 1))
    176 

~/anaconda3/envs/causalpy/lib/python3.7/site-packages/sympy/stats/crv.py in _inverse_cdf_expression(self)
    189         except NotImplementedError:
    190             inverse_cdf = None
--> 191         if not inverse_cdf or len(inverse_cdf) != 1:
    192             raise NotImplementedError("Could not invert CDF")
    193 
```

Sympy version: 1.5.1
Python version: 3.7
OS: ubuntu 19.04

**Comment by maichmueller** [comment]
could be resolved by #19096

**Comment by Smit-create** [comment]
This issue be closed as on the current master I get,
```python
>>> from sympy.stats import StudentT, sample_iter
>>> samples = list(sample_iter(StudentT("", 2), numsamples=1))
>>> samples
[array([0.963186])]
>>> samples = list(sample_iter(StudentT("", 2), numsamples=5))
>>> samples
[array([-4.69531071]), array([0.33248148]), array([0.14548725]), array([15.9515637]), array([1.19208882])]
```

**Comment by maichmueller** [comment]
Pefectly fine for me. I'll close it then. Thanks for the work!

**Comment by maichmueller** [comment]
The initial problem of not being able to sample from a StudentT distribution seems to persist in Sympy 1.6.2:
Doing
```
from sympy.stats import StudentT, sample_iter
samples = list(sample_iter(StudentT("", 2), numsamples=1))
```
or 
```
from sympy.stats import StudentT, sample_iter
samples = list(sample_iter(StudentT("", 2), numsamples=1, library='scipy'))
```
results in 
```
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/home/michael/anaconda3/envs/scm/lib/python3.8/site-packages/sympy/stats/rv.py", line 1194, in sample_iter_subs
    d = ps.sample(size)  # a dictionary that maps RVs to values
  File "/home/michael/anaconda3/envs/scm/lib/python3.8/site-packages/sympy/stats/crv.py", line 504, in sample
    return {self.value: self.distribution.sample(size)}
  File "/home/michael/anaconda3/envs/scm/lib/python3.8/site-packages/sympy/stats/crv.py", line 176, in sample
    icdf = self._inverse_cdf_expression()
  File "/home/michael/anaconda3/envs/scm/lib/python3.8/site-packages/sympy/stats/crv.py", line 196, in _inverse_cdf_expression
    if not inverse_cdf or len(inverse_cdf) != 1:
TypeError: object of type 'ConditionSet' has no len()
```

Is there potentially a new call mechanism to sampling from a scipy distribution?
Sympy version 1.6.2:
Ubuntu 20.04
Python 3.8.5

**Comment by naveensaigit** [comment]
This is currently working on master with Python 3.7.6
``` python
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy.stats import StudentT, sample_iter
>>> samples = list(sample_iter(StudentT("", 2), numsamples=1))
>>> samples
[0.9814657131522821]
```
