### ISSUE TITLE
PolynomialError from CRootOf in solve with trig functions

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#19113]
From stackoverflow:
https://stackoverflow.com/questions/61182099/python-sympy-solver-got-error-while-solving-triangle-equation
```python
from sympy.solvers import solve
from sympy import Symbol,sin,cos,simplify
x = Symbol('x')
solve( sin(x)**5 - cos(x)**5 , x)
```
Here `solve` gives:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 1187, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 1771, in _solve
    result = list(map(simplify, result))
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/simplify.py", line 573, in simplify
    expr = expr.replace(
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1494, in replace
    rv = bottom_up(self, rec_replace, atoms=True)
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/simplify.py", line 1149, in bottom_up
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/simplify.py", line 1149, in <listcomp>
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/simplify.py", line 1149, in bottom_up
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/simplify.py", line 1149, in <listcomp>
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/simplify.py", line 1152, in bottom_up
    rv = F(rv)
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1475, in rec_replace
    new = _value(expr, result)
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1459, in <lambda>
    _value = lambda expr, result: value(expr)
  File "/Users/enojb/current/sympy/sympy/sympy/simplify/simplify.py", line 581, in <lambda>
    lambda x: x.func(*[simplify(i, **kwargs) for i in x.args]),
  File "/Users/enojb/current/sympy/sympy/sympy/polys/rootoftools.py", line 322, in __new__
    raise PolynomialError("generator must be a Symbol")
sympy.polys.polyerrors.PolynomialError: generator must be a Symbol
```

The error comes from calling replace on this:
```python
2*atan(CRootOf(tan(x/2)**8 - 2*tan(x/2)**7 - 2*tan(x/2)**5 + 14*tan(x/2)**4 + 2*tan(x/2)**3 + 2*tan(x/2) + 1, 0))
```
I'm not sure how that CRootOf get created though because:
```julia
In [4]: CRootOf(tan(x/2)**8 + tan(x/2), 0)                                                                                        
---------------------------------------------------------------------------
PolynomialError                           Traceback (most recent call last)
<ipython-input-4-b61ba9cd17b0> in <module>
----> 1 CRootOf(tan(x/2)**8 + tan(x/2), 0)

~/current/sympy/sympy/sympy/polys/rootoftools.py in __new__(cls, f, x, index, radicals, expand)
    320             # PurePoly(sin(x) + 1) == PurePoly(x + 1) but the roots of
    321             # x for each are not the same: issue 8617
--> 322             raise PolynomialError("generator must be a Symbol")
    323 
    324         degree = poly.degree()

PolynomialError: generator must be a Symbol
```

**Comment by jksuom** [comment]
This is something that we have discussed before (https://github.com/sympy/sympy/issues/18226) but did not come to a decision: How should a PurePoly be created? Perhaps now that https://github.com/sympy/sympy/pull/18613 has been merged it would be time to consider PurePoly objects. One possibility could be always using something like `Symbol('_')` as the generator. (Actually, it should not matter how the generator does look like, it is only used in printed output, not in internal computations. It only should be a symbol.)

**Comment by oscarbenjamin** [comment]
The example just comes from trying to simplify the CRootOf but I'm not sure how the CRootOf gets created in solve in the first place:
```
ipdb> p x                                                                                                                         
CRootOf(tan(x/2)**8 - 2*tan(x/2)**7 - 2*tan(x/2)**5 + 14*tan(x/2)**4 + 2*tan(x/2)**3 + 2*tan(x/2) + 1, 0)
ipdb> p x.simplify()                                                                                                              
*** sympy.polys.polyerrors.PolynomialError: generator must be a Symbol
```

**Comment by jksuom** [comment]
> how the CRootOf gets created in solve

`solve` calls `roots`; here, for example: https://github.com/sympy/sympy/blob/f09b26cfd7ecaf38423d89c08c6e95865cc167e4/sympy/solvers/solvers.py#L1680

**Comment by oscarbenjamin** [comment]
I didn't think that `roots` return `RootOf`:
```julia
In [6]: roots(x**5 - x + 1)                                                                                                       
Out[6]: {}
```
I tried hooking the debugger into `CRootOf.__new__` but it seems that the `CRootOf` is somehow created bypassing `__new__`.

**Comment by oscarbenjamin** [comment]
It comes from `all_roots` with
```
p = Poly((tan(x/2))**10 - 5*(tan(x/2))**8 + 10*(tan(x/2))**6 + 32*(tan(x/2))**5 - 10*(tan(x/2))**4 + 5*(tan(x/2))**2 - 1, tan(x/2), domain='ZZ')
```
That gives CRootOf:
```julia
In [13]: p = Poly((tan(x/2))**10 - 5*(tan(x/2))**8 + 10*(tan(x/2))**6 + 32*(tan(x/2))**5 - 10*(tan(x/2))**4 + 5*(tan(x/2))**2 - 1,
    ...:  tan(x/2), domain='ZZ')                                                                                                  

In [14]: p.all_roots()                                                                                                            
Out[14]: 
⎡                         ⎛   8⎛x⎞        7⎛x⎞        5⎛x⎞         4⎛x⎞        3⎛x⎞        ⎛x⎞       ⎞         ⎛   8⎛x⎞        7
⎢-√2 - 1, -1 + √2, CRootOf⎜tan ⎜─⎟ - 2⋅tan ⎜─⎟ - 2⋅tan ⎜─⎟ + 14⋅tan ⎜─⎟ + 2⋅tan ⎜─⎟ + 2⋅tan⎜─⎟ + 1, 0⎟, CRootOf⎜tan ⎜─⎟ - 2⋅tan 
⎣                         ⎝    ⎝2⎠         ⎝2⎠         ⎝2⎠          ⎝2⎠         ⎝2⎠        ⎝2⎠       ⎠         ⎝    ⎝2⎠         

⎛x⎞        5⎛x⎞         4⎛x⎞        3⎛x⎞        ⎛x⎞       ⎞         ⎛   8⎛x⎞        7⎛x⎞        5⎛x⎞         4⎛x⎞        3⎛x⎞   
⎜─⎟ - 2⋅tan ⎜─⎟ + 14⋅tan ⎜─⎟ + 2⋅tan ⎜─⎟ + 2⋅tan⎜─⎟ + 1, 1⎟, CRootOf⎜tan ⎜─⎟ - 2⋅tan ⎜─⎟ - 2⋅tan ⎜─⎟ + 14⋅tan ⎜─⎟ + 2⋅tan ⎜─⎟ + 
⎝2⎠         ⎝2⎠          ⎝2⎠         ⎝2⎠        ⎝2⎠       ⎠         ⎝    ⎝2⎠         ⎝2⎠         ⎝2⎠          ⎝2⎠         ⎝2⎠   

     ⎛x⎞       ⎞         ⎛   8⎛x⎞        7⎛x⎞        5⎛x⎞         4⎛x⎞        3⎛x⎞        ⎛x⎞       ⎞         ⎛   8⎛x⎞        7⎛
2⋅tan⎜─⎟ + 1, 2⎟, CRootOf⎜tan ⎜─⎟ - 2⋅tan ⎜─⎟ - 2⋅tan ⎜─⎟ + 14⋅tan ⎜─⎟ + 2⋅tan ⎜─⎟ + 2⋅tan⎜─⎟ + 1, 3⎟, CRootOf⎜tan ⎜─⎟ - 2⋅tan ⎜
     ⎝2⎠       ⎠         ⎝    ⎝2⎠         ⎝2⎠         ⎝2⎠          ⎝2⎠         ⎝2⎠        ⎝2⎠       ⎠         ⎝    ⎝2⎠         ⎝

x⎞        5⎛x⎞         4⎛x⎞        3⎛x⎞        ⎛x⎞       ⎞         ⎛   8⎛x⎞        7⎛x⎞        5⎛x⎞         4⎛x⎞        3⎛x⎞    
─⎟ - 2⋅tan ⎜─⎟ + 14⋅tan ⎜─⎟ + 2⋅tan ⎜─⎟ + 2⋅tan⎜─⎟ + 1, 4⎟, CRootOf⎜tan ⎜─⎟ - 2⋅tan ⎜─⎟ - 2⋅tan ⎜─⎟ + 14⋅tan ⎜─⎟ + 2⋅tan ⎜─⎟ + 2
2⎠         ⎝2⎠          ⎝2⎠         ⎝2⎠        ⎝2⎠       ⎠         ⎝    ⎝2⎠         ⎝2⎠         ⎝2⎠          ⎝2⎠         ⎝2⎠    

    ⎛x⎞       ⎞         ⎛   8⎛x⎞        7⎛x⎞        5⎛x⎞         4⎛x⎞        3⎛x⎞        ⎛x⎞       ⎞         ⎛   8⎛x⎞        7⎛x
⋅tan⎜─⎟ + 1, 5⎟, CRootOf⎜tan ⎜─⎟ - 2⋅tan ⎜─⎟ - 2⋅tan ⎜─⎟ + 14⋅tan ⎜─⎟ + 2⋅tan ⎜─⎟ + 2⋅tan⎜─⎟ + 1, 6⎟, CRootOf⎜tan ⎜─⎟ - 2⋅tan ⎜─
    ⎝2⎠       ⎠         ⎝    ⎝2⎠         ⎝2⎠         ⎝2⎠          ⎝2⎠         ⎝2⎠        ⎝2⎠       ⎠         ⎝    ⎝2⎠         ⎝2

⎞        5⎛x⎞         4⎛x⎞        3⎛x⎞        ⎛x⎞       ⎞⎤
⎟ - 2⋅tan ⎜─⎟ + 14⋅tan ⎜─⎟ + 2⋅tan ⎜─⎟ + 2⋅tan⎜─⎟ + 1, 7⎟⎥
⎠         ⎝2⎠          ⎝2⎠         ⎝2⎠        ⎝2⎠       ⎠⎦

In [15]: p.all_roots()[2].simplify()                                                                                              
---------------------------------------------------------------------------
PolynomialError
```

**Comment by oscarbenjamin** [comment]
I see the problem. The `all_roots` method uses `CRootof._new` which bypasses `CRootOf.__new__`:
https://github.com/sympy/sympy/blob/f09b26cfd7ecaf38423d89c08c6e95865cc167e4/sympy/polys/rootoftools.py#L354-L360
(I think that's generally not a good approach)

**Comment by jksuom** [comment]
I think that the idea is that only the coefficients of the polynomial are needed. Actually, it should not be necessary to save any generator in a PurePoly object.

**Comment by jksuom** [comment]
How about defining a `PurePoly.__new__` that would replace the generator by `Symbol('_')` and then go on to `Poly.__new__`.

**Comment by smichr** [comment]
What about redefining PurePoly to only store coefficients and then to have the printer show `x`?

**Comment by smichr** [comment]
> I think that the idea is that only the coefficients of the polynomial are needed

Note, too, that a PurePoly can be multivariate:
```
>>> PurePoly(x**2 + y)
PurePoly(x**2 + y, x, y, domain='ZZ')
```

**Comment by jksuom** [comment]
>  PurePoly can be multivariate

That is currently true, in principle, but those are not used in SymPy, and it would suffice to consider only univariate polys for the purposes of `rootof`.

**Comment by oscarbenjamin** [comment]
I think having `PurePoly` canonicalise the symbols to x1, x2, etc makes sense. Then we can remove the PurePoly methods `__eq__`, `__hash__` and `_hashable_content`.

**Comment by smichr** [comment]
> having `PurePoly` canonicalise the symbols

Is this correct?
```python
>>> PurePoly(x**5+3*x+y)
PurePoly(x0**5 + 3*x0 + x1, x0, x1, domain='ZZ')
>>> PurePoly(y**5+3*y+x)
PurePoly(x0 + x1**5 + 3*x1, x0, x1, domain='ZZ')
```
A suggestion that it is is that if the otuputs are created in master they do not compare as equal.

**Comment by oscarbenjamin** [comment]
That seems correct to me. I think that the ordering of the generators affects the order of the monomials so these would not generate equal outputs e.g. when generating a Groebner basis:
```julia
In [3]: exprs = x**2, x*y                                                                                                         

In [4]: p1, p2 = [PurePoly(e, x, y) for e in exprs]                                                                               

In [5]: groebner([p1, p2])                                                                                                        
Out[5]: 
             ⎛⎡ 2     ⎤                           ⎞
GroebnerBasis⎝⎣x , x⋅y⎦, x, y, domain=ℤ, order=lex⎠

In [6]: p1, p2 = [PurePoly(e, y, x) for e in exprs]                                                                               

In [7]: groebner([p1, p2])                                                                                                        
Out[7]: 
             ⎛⎡      2⎤                           ⎞
GroebnerBasis⎝⎣x⋅y, x ⎦, y, x, domain=ℤ, order=lex⎠
```

**Comment by smichr** [comment]
Any chance you could put the following where it belongs in #19113 or help for the same? I'm not sure how to make this happen. I can't change the attributes of the PurePoly like `self.expr = newexpr` and yet I prefer to handle the object once all the other Poly-dazzle is done (expansion, identification and ordering of generators, translation of expr/dict/list inputs, etc...).
```
# given the expr, gens and domain for PurePoly, make
# gens (and expr) canonical
from sympy.utilities.iterables import numbered_symbols
c = dict(zip(gens, numbered_symbols('x')))
e = expr.xreplace(c)
g = tuple([c[i] for i in gens])
return PurePoly(e, g, domain)
```

**Comment by jksuom** [comment]
I think that PurePoly should always be called with explicit generators (at least one). Those symbols, etc.. that are not given as generators should go the the coefficient domain.

**Comment by oscarbenjamin** [comment]
I guess you mean #19117? This is #19113...

I think that this should happen as part of `PurePoly.__new__` rather than in `CRootOf` so it is automatic for all `PurePoly`. Maybe the best way is to define `PurePoly.new` and replace the `gens` before passing them to `Poly.new`. I think that `rep` is independent of the generators so doesn't need to be changed.

The Poly construction process is quite complicated though so I haven't follow all paths...

**Comment by jksuom** [comment]
> Maybe the best way is to define PurePoly.new and replace the gens before passing them to Poly.new.

That is what I had in mind, too. If the `rep` argument is an expression, then `rep.subs()` seems necessary. If it is a Poly, then its `rep` need not be changed.
