### ISSUE TITLE
[Feature Request] Scatter plots support

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#19263]
While working on #19073 for adding wrapper of plotting in `stats` module to plot `density` and `cdf` of the random variables, I found that the `plot` function works good with the continuous random variable but to plot FRV and DRV, it will be good to have scatter plots available in `plotting`, so as to allow discrete plots as [here](https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Poisson_pmf.svg/325px-Poisson_pmf.svg.png)

**Comment by faze-geek** [comment]
Hi @Davide-sd, firstly thanks for all the work done with the plotting module. Tagging you because I would like to tread with some guidance here.

As this request is about a scatter plot, can we look forward to supporting a `plot_list()` function? It a function to map an x_list and a y_list of values.

I just came across this - 
https://github.com/sympy/sympy/blob/002bf92c2238a96a07955d003158ea1dff3e4893/sympy/plotting/series.py#L1229-L1230

and tried this -
```
>>> x = [1,2,3]
>>> y = [3,4,5]
>>> series = List2DSeries(sympify(x), sympify(y))
>>> plot = Plot(series)
>>> plot.show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kunni\sympy\sympy\sympy\plotting\backends\base_backend.py", line 354, in show
    raise NotImplementedError
NotImplementedError
```

This will be of great help !

**Comment by Davide-sd** [comment]
@faze-geek if the merging of the new plotting module proceed as planned, there will be a `plot_list` function. However, I can't give you any timeline for when it will be achieved...

**Comment by faze-geek** [comment]
> @faze-geek if the merging of the new plotting module proceed as planned, there will be a `plot_list` function.

Thanks a lot ! Is the road map of the plotting module documented somewhere? I would like to have a look and play with it.

**Comment by Davide-sd** [comment]
#23036 is where I collect all the PRs related to the merging. As for the roadmap:

* currently, #25531 is the latest PR. Because it is one of the core features of the new plotting module, if it doesn't get merged I won't put any more effort into the merging... Sad but true.
* If that PR is going to be merged, coming up next is the refactoring of `MatplotlibBackend`, which would allow to plot `List2DSeries`.
* After `MatplotlibBackend`'s refactoring, it will be the time to properly document existing plotting functions and add new ones, like `plot_list`.
