### ISSUE TITLE
Piecewise and Boolean cause TypeError

### ISSUE THREAD

**Issue by GitRay** [sympy/sympy#19373]
I have two environments, plus I've tried Sympy Live. The old environment has Sympy 1.0.1 installed, and the following code produces the expected result:
```
>>> import sympy
>>> expr = 'Piecewise((True, Eq(a, b)), (c >= d, True))'
>>> s = sympy.sympify(expr)
>>> a = sympy.And(s,True)
>>> print(s)
Piecewise((True, Eq(a, b)), (c >= d, True))
```

However, on Sympy 1.4 and on Sympy Live (version 1.5.1), it instead throws an exception:
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/core/operations.py", line 418, in __new__
    _args = frozenset(cls._new_args_filter(args))
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/logic/boolalg.py", line 669, in _new_args_filter
    args = BooleanFunction.binary_check_and_simplify(*args)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/logic/boolalg.py", line 456, in binary_check_and_simplify
    args = [as_Boolean(i) for i in args]
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/logic/boolalg.py", line 54, in as_Boolean
    raise TypeError('expecting bool or Boolean, not `%s`.' % e)
TypeError: expecting bool or Boolean, not `Piecewise((True, Eq(a, b)), (c >= d, True))`.

```

**Comment by oscarbenjamin** [comment]
I think that Piecewise should only be used for Expr values rather than Boolean. Your example is handled by ITE:
```julia
In [37]: And(ITE(Eq(a, b), True, c>=d), True)                                                                                     
Out[37]: 
⎧True   for a = b
⎨                
⎩c ≥ d  otherwise
```
https://docs.sympy.org/latest/modules/logic.html#sympy.logic.boolalg.ITE

**Comment by GitRay** [comment]
@oscarbenjamin thank you very much, I think that will probably work just fine.

**Comment by GitRay** [comment]
It looks like this just shifts my problem elsewhere. The substituting the following expression into my test code yields the same error:
`>>> expr = "ITE(a, Max(b, c), d)"`
Just like above, this code runs fine in my old 1.0.1 version.

**Comment by oscarbenjamin** [comment]
In your previous version everything was a Boolean. Where did `Max(b, c)` come from?

**Comment by GitRay** [comment]
I have a massive set of equations that get converted into Sympy expressions. I hit the error and reduced it to the minimum required to trigger the error. Once I converted from Piecewise to ITE, I ran into the error again. Once again, I reduced the expression to a simple form in order to demonstrate the error. Sorry that I wasn't clear in my last message.

**Comment by oscarbenjamin** [comment]
The question is are you dealing with Expr or Boolean i.e. are your expressions something like numbers or are they logical True/False type values? I suggested ITE because in your original example the expressions in the `Piecewise` were all Boolean. Your new example uses `Max(b, c)` which is `Expr` rather than `Boolean`. In that case `Piecewise` is appropriate.

**Comment by GitRay** [comment]
All of my expressions stay symbolic, and then later I convert them to c-code. I guess what I need to do is use Piecewise when the result of the expression is expected to be a function and ITE when the result is expected to be a boolean. I'll give that a try. Or, more likely, try one way and then catch the exception and try the other way :)

**Comment by oscarbenjamin** [comment]
> I guess what I need to do is use Piecewise when the result of the expression is expected to be a function and ITE when the result is expected to be a boolean.

Yes, that's the way I expect these to be used.
