### ISSUE TITLE
Bug in dsolve(_, f(x), hint='2nd_power_series_regular')

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#19388]
```python
>>> a = Symbol('a')
>>> f = Function('f')
>>> x = Symbol('x')
>>> -a*x*f(x) + x*f(x).diff(x, 2) + f(x).diff(x)
                2                 
               d          d       
-a⋅x⋅f(x) + x⋅───(f(x)) + ──(f(x))
                2         dx      
              dx                  
>>> dsolve(_, f(x), hint='2nd_power_series_regular')
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/solvers/ode/ode.py", line 656, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/solvers/ode/ode.py", line 687, in _helper_simplify
    sols = solvefunc(eq, func, order, match)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/solvers/ode/ode.py", line 3696, in ode_2nd_power_series_regular
    term = series(term, n=1, x0=x0)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/series/series.py", line 65, in series
    return expr.series(x, x0, n, dir)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/core/expr.py", line 2891, in series
    raise ValueError('x must be given for multivariate functions.')
ValueError: x must be given for multivariate functions.
```

**Comment by naveensaigit** [comment]
The `a` is causing it to fail. `dsolve` can solve the equation if it is removed. I think there would be some way around this.
``` python
>>> dsolve(-x*f(x) + x*f(x).diff(x, 2) + f(x).diff(x), f(x), hint='2nd_power_series_regular')
Eq(f(x), C1*(x**4/64 + x**2/4 + 1) + O(x**6))
```

**Comment by czgdp1807** [comment]
The problem is that `a` is considered as a variable but it's a constant.

**Comment by czgdp1807** [comment]
The bug is in `sympy/solvers/ode/ode.py`,
```python
    for term in [p, q]:
        if not term.has(x):
            indicial.append(term)
        else:
            term = series(term, n=1, x0=x0) # no check for constants/dummys and more than one symbols. If there is only variable, then that should be passed as `x` argument of `series`.
            if isinstance(term, Order):
                indicial.append(S.Zero)
            else:
                for arg in term.args:
                    if not arg.has(x):
                        indicial.append(arg)
                        break
```

**Comment by cocoa1231** [comment]
Hello

This bug still exists -

```
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from sympy import *

In [2]: x, n = symbols('x, n')

In [3]: y = Function('y')(x)

In [4]: eq = Eq(diff(y,x,x) + ((1-x)/x)*diff(y,x) + (n/x)*y, 0)

In [5]: eq
Out[5]: Eq(n*y(x)/x + Derivative(y(x), (x, 2)) + (1 - x)*Derivative(y(x), x)/x, 0)

In [6]: dsolve(eq, y)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-b3632f123e4f> in <module>
----> 1 dsolve(eq, y)

/usr/lib/python3/dist-packages/sympy/solvers/ode/ode.py in dsolve(eq, func, hint, simplify, ics, xi, eta, x0, n, **kwargs)
    662             # The key 'hint' stores the hint needed to be solved for.
    663             hint = hints['hint']
--> 664             return _helper_simplify(eq, hint, hints, simplify, ics=ics)
    665 
    666 def _helper_simplify(eq, hint, match, simplify=True, ics=None, **kwargs):

/usr/lib/python3/dist-packages/sympy/solvers/ode/ode.py in _helper_simplify(eq, hint, match, simplify, ics, **kwargs)
    693             sols = solvefunc.get_general_solution()
    694         else:
--> 695             sols = solvefunc(eq, func, order, match)
    696         if iterable(sols):
    697             rv = [odesimp(eq, s, func, hint) for s in sols]

/usr/lib/python3/dist-packages/sympy/solvers/ode/ode.py in ode_2nd_power_series_regular(eq, func, order, match)
   3599             indicial.append(term)
   3600         else:
-> 3601             term = series(term, n=1, x0=x0)
   3602             if isinstance(term, Order):
   3603                 indicial.append(S.Zero)

/usr/lib/python3/dist-packages/sympy/series/series.py in series(expr, x, x0, n, dir)
     63     """
     64     expr = sympify(expr)
---> 65     return expr.series(x, x0, n, dir)

/usr/lib/python3/dist-packages/sympy/core/expr.py in series(self, x, x0, n, dir, logx, cdir)
   2911                 return self
   2912             elif len(syms) > 1:
-> 2913                 raise ValueError('x must be given for multivariate functions.')
   2914             x = syms.pop()
   2915 

ValueError: x must be given for multivariate functions.
```

I don't think I understand the code base well enough to solve the issue myself but just wanted to report it.
