### ISSUE TITLE
Non-existant bi-directional limit gives ValueError

### ISSUE THREAD

**Issue by weakit** [sympy/sympy#19442]
When you try to find the bi-directional limit where the limit doesn't exist, you get this:
```python
>>> sympy.limit(1/x, x, 0, '-')
-oo
>>> sympy.limit(1/x, x, 0, '+-')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\sympy\series\limits.py", line 70, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
  File "C:\Program Files\Python37\lib\site-packages\sympy\series\limits.py", line 258, in doit
    % (l, r))
ValueError: The limit does not exist since left hand limit = -oo and right hand limit = oo
```

Shouldn't it return Indeterminate or `NaN` instead of throwing an error? 

It'd be much better that way.

**Comment by oscarbenjamin** [comment]
It would be better to raise a more specific exception class than ValueError at least.

**Comment by weakit** [comment]
Yes, agreed.

**Comment by gschintgen** [comment]
A few notes:
In #11667 there's another recent discussion of this specific aspect.
Also worth mentioning is that with current master, the bidirectional limit of 1/x is returning `zoo` and no longer raises. However that's not intended as a fix, but rather a side effect of unrelated changes.
Here's an example of a limit that still exhibits the criticized behavior:
```
In [5]: limit(exp(1/x), x, 0, dir='+-')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-838d67dc5cf4> in <module>
----> 1 limit(exp(1/x), x, 0, dir='+-')

~/sympy/sympy/series/limits.py in limit(e, z, z0, dir)
     63     """
     64
---> 65     return Limit(e, z, z0, dir).doit(deep=False)
     66
     67

~/sympy/sympy/series/limits.py in doit(self, **hints)
    265                 l = gruntz(e, z, z0, '-')
    266                 if l != r:
--> 267                     raise ValueError("The limit does not exist since "
    268                             "left hand limit = %s and right hand limit = %s"
    269                             % (l, r))

ValueError: The limit does not exist since left hand limit = 0 and right hand limit = oo
```

**Comment by weakit** [comment]
Isn't this a duplicate of #11667 then?

**Comment by anutosh491** [comment]
@oscarbenjamin . In my opinion `nan` is the most correct way to represent the "Does not exist" phrase and should be implemented for the same . The `ValueError` also reads out "The limit does not exist....." but It's not an an Exception really , like there was nothing wrong and sympy correctly calculated a value that does not exist!!! 

Also for the bi-directional limit above `limit(1/x, x, 0, '+-')` , has it been decided to stick to `zoo` ??? cause even in this case my personal take would be to return `nan`/`Indeterminant` like most other CAS. It's just more convinient for users.

Anyways, do we plan on returning the specific exception you pointed above, `Nan`, `Indeterminant` (Any one of these) for only cases with either left/right sided limit as `oo` or for all cases where both limits would be different .
