### ISSUE TITLE
Indicator function

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#19481]
Since SymPy tries to keep numeric expression and set types distinct, it would be useful to have an indicator function object to represent 1_A(x) = {1 if x is in A, 0 if x is not in A (see https://en.wikipedia.org/wiki/Indicator_function).

It would also be useful to have a similar concept for booleans, as a shorthand for `Piecewise((1, boolean), (0, True))`. I don't know if we should reuse the same function or if there is a better name for this for booleans.

**Comment by jgulian** [comment]
Hello,

I started working on a pull request for this. I'm a little new to sympy though, and was hoping for some guidance on whether my implantation is alright, or where it needs improvement. Currently the function works, and there are some examples, and tests. However, I was unsure how to add pretty printing, although I was able to implement latex printing (I did not commit it though).

Thank you

**Comment by cuihantao** [comment]
The background for this issue is that in version 1.5.1, the code below works fine:

```python
import numpy as np
from sympy import lambdify, Piecewise
from sympy.abc import a, b, c

f = c * (a < b)
fcall = lambdify((a, b, c), f)

x = np.linspace(11, 20, 1000)
y = np.linspace(1, 30, 1000)
z = 5 * np.ones(1000)
fcall(x, y, z)
```
The source code of `fcall` is

```python
>>> import inspect
>>> print(inspect.getsource(fcall))
def _lambdifygenerated(a, b, c):
    return (c*(less(a, b)))
```
which is as expected - it's concise and efficient. 

In SymPy 1.6.0+, `<` is constructed as a `Relational` type `LessThan`, and operation `*` for `Symbol` and `LessThan` is not defined.

The suggestion from @asmeurer was to construct a piecewise function for the expression, as in this PR, such as 

```
Piecewise((c, a <= b), (0, True))
```
But this method may be suboptimal. First, `Piecewise` lambdifies to `np.select` that is very slow to evaluate, because `np.select` uses list comprehension. Second, `np.select` cannot be optimized by `numba.jit`. Lastly, I have to rewrite equations. 

The benchmark code is here:

```python

In [7]: pf = Piecewise((c, a<b), (0, True))

In [9]: pfcall = lambdify((a, b, c), pf)

In [11]: %timeit fcall(x, y, z)
2.51 µs ± 41.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [12]: %timeit pfcall(x, y, z)
47.1 µs ± 594 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

```
In nontrivial cases, the time difference will be greater. 


Will my original code will be working again if https://github.com/sympy/sympy/pull/17097 gets done? If the answer is yes, I might work on it as this issue is preventing me to update to SymPy 1.6.

**Comment by oscarbenjamin** [comment]
> ```python
> from sympy.abc import a, b, c
> 
> f = c * (a < b)
> fcall = lambdify((a, b, c), f)
> ```

The fact that this worked at all in `sympy<1.6` was purely an accident.

A boolean indicator function is the right way to get that behaviour.

**Comment by cuihantao** [comment]
> The fact that this worked at all in sympy<1.6 was purely an accident.
> A boolean indicator function is the right way to get that behaviour.
> ```

Ok. With a boolean indicator function, is there a way not to use `np.select` for the generated code for the sake of performance? I understand SymPy want to keep a type distinction between booleans and numbers, but numpy can mix them for numerical computation.

**Comment by oscarbenjamin** [comment]
> With a boolean indicator function, is there a way not to use `np.select`

I'm sure there is but we don't have a boolean indicator function yet.

**Comment by asmeurer** [comment]
Until this is fixed, you can work around it by defining a simple Indicator class

```py
class Indicator(Expr):
    def _numpycode(self, printer):
        return printer._print(self.args[0])
```

```py
>>> f = lambdify((x, y, z), z*Indicator(x > y))
>>> import inspect
>>> print(inspect.getsource(f))
def _lambdifygenerated(x, y, z):
    return (z*greater(x, y))

>>> f(0, 1, 2)
0
>>> f(1, 0, 2)
2
```

**Comment by cuihantao** [comment]
@asmeurer Thanks a lot! Let me try that into my code.

**Comment by cuihantao** [comment]
@asmeurer 

Hi Aaron,

Sorry for my late reply. I tried your code and it works. 

If I need to lambdify strings into functions, then the following code won't work.

```python
from sympy import Expr, lambdify, sympify 
import inspect

class Indicator(Expr):
    def _numpycode(self, printer):
        return printer._print(self.args[0])

f = lambdify((x, y, z), z*Indicator(x > y))  # works fine
print(inspect.getsource(f))
# def _lambdifygenerated(x, y, z):
#     return (z*greater(x, y))

g = lambdify((x, y, z), 'z*Indicator(x > y)')   # won't work
print(inspect.getsource(f))
# def _lambdifygenerated(x, y, z):
#     return (z*Indicator(greater(x, y)))
```

```python
>>> g(1, 1, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<lambdifygenerated-6>", line 2, in _lambdifygenerated
NameError: name 'Indicator' is not defined
```

It looks like `Indicator`is parsed as a function, which can be passed through `locals`. Is there another way to get this working?

**Comment by jksuom** [comment]
`Boolean` already has the method `as_set`. How about adding `as_Integer`?

**Comment by oscarbenjamin** [comment]
> `Boolean` already has the method `as_set`. How about adding `as_Integer`?

Is that the Iverson Bracket operator from #20151

**Comment by bluthej** [comment]
For people who need this, you can just override the `modules` when calling `lambdify`:

```python
lambdify(
    args,
    expr,
    modules=[
        {
            "Indicator": lambda cond: cond.astype(float),
        },
        # Then put whatever modules you need
        ...,
    ],
)
```

Then this should work just fine and return floats (0.0 and 1.0):

```python
import numpy as np
from sympy import lambdify
from sympy.abc import x

fun = lambdify(
    x,
    "Indicator(x > 1)",
    modules=[
        {
            "Indicator": lambda cond: cond.astype(float),
        },
        "numpy",
        "scipy",
    ],
)

print(fun(np.linspace(0, 2)))
```
