### ISSUE TITLE
solve(Eq(1/((x - 5)**8), 3), x) takes a long time

### ISSUE THREAD

**Issue by satels** [sympy/sympy#19509]
```python
>>> import sympy
>>> sympy.__version__
'1.6'
>>> Eq(1/((x - 5)**8), 3)
KeyboardInterrupt
>>> from sympy import *
>>> from sympy.abc import *
>>> Eq(1/((x - 5)**8), 3)
Eq((x - 5)**(-8), 3)
>>> solve(Eq(1/((x - 5)**8), 3), x)
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/solvers.py", line 1094, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/solvers.py", line 1606, in _solve
    soln = roots(poly, **solvers)
  File "/usr/local/lib/python3.8/site-packages/sympy/polys/polyroots.py", line 1023, in roots
    for currentroot in _try_decompose(f):
  File "/usr/local/lib/python3.8/site-packages/sympy/polys/polyroots.py", line 930, in _try_decompose
    for currentroot in _try_heuristics(g):
  File "/usr/local/lib/python3.8/site-packages/sympy/polys/polyroots.py", line 961, in _try_heuristics
    result += list(map(cancel, roots_quadratic(f)))
  File "/usr/local/lib/python3.8/site-packages/sympy/polys/polyroots.py", line 103, in roots_quadratic
    D = factor_terms(_sqrt(d)/A)
  File "/usr/local/lib/python3.8/site-packages/sympy/polys/polyroots.py", line 71, in _sqrt
    return sqrt(d)
  File "/usr/local/lib/python3.8/site-packages/sympy/functions/elementary/miscellaneous.py", line 151, in sqrt
    return Pow(arg, S.Half, evaluate=evaluate)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/power.py", line 317, in __new__
    obj = b._eval_power(e)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/mul.py", line 657, in _eval_power
    return p._eval_expand_power_base()
  File "/usr/local/lib/python3.8/site-packages/sympy/core/power.py", line 1050, in _eval_expand_power_base
    rv *= Mul(*[self.func(b, e, evaluate=False) for b in cargs])
  File "/usr/local/lib/python3.8/site-packages/sympy/core/decorators.py", line 251, in _func
    return func(self, other)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/decorators.py", line 127, in binary_op_wrapper
    return func(self, other)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/expr.py", line 198, in __mul__
    return Mul(self, other)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/operations.py", line 52, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/mul.py", line 512, in flatten
    coeff *= Pow(g, e_i)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/decorators.py", line 89, in __sympifyit_wrapper
    return func(a, b)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/numbers.py", line 1745, in __mul__
    return Rational(self.p*other.p, self.q*other.q, igcd(self.p, other.q)*igcd(self.q, other.p))
  File "/usr/local/lib/python3.8/site-packages/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/numbers.py", line 1638, in __new__
    q = Rational(q)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/numbers.py", line 1664, in __new__
    return Integer(p)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/numbers.py", line 2086, in __new__
    @cacheit
KeyboardInterrupt
>>>
```

But in the previous version had been had the result (sympy 1.4 has result):

```python
>>> import sympy
>>> sympy.__version__
'1.4'
>>> from sympy import *
>>> from sympy.abc import *
>>> Eq(1/((x - 5)**8), 3)
Eq((x - 5)**(-8), 3)
>>> solve(Eq(1/((x - 5)**8), 3), x)
[5 - 3**(7/8)/3, 5 - 3**(7/8)*sqrt(I)/3, 5 + 3**(7/8)*sqrt(I)/3, 5 - 3**(7/8)*I/3, 5 + 3**(7/8)*I/3, 5 - 3**(7/8)*sqrt(-I)/3, 5 + 3**(7/8)*sqrt(-I)/3, 3**(7/8)/3 + 5]
>>>
```

**Comment by smichr** [comment]
Hmm. `solve(1/x**8 - 3)` is very fast...could be that expansion is attempted rather than solving this in terms of generator `x - 5` and then further solving for `x` once the values for `x-5` are known:
```python
>>> solve(1/x**8-3)
[-3**(7/8)/3, 3**(7/8)/3, -3**(7/8)*I/3, 3**(7/8)*I/3, -sqrt(2)*3**(7/8)/6 - sqrt(2)*3**(7/8)*I/6, -sqrt(2)*3**(7/8)/6 + sqrt(2)*3**(7/8)*I/6, sqrt(2)*3**(7/8)/6 - sqrt(2)*3**(7/8)*I/6, sqrt(2)*3**(7/8)/6 + sqrt(2)*3**(7/8)*I/6]
>>> [i+5 for i in _]
[5 - 3**(7/8)/3, 3**(7/8)/3 + 5, 5 - 3**(7/8)*I/3, 5 + 3**(7/8)*I/3, -sqrt(2)*3**(7/8)/6 + 5 - sqrt(2)*3**(7/8)*I/6, -sqrt(2)*3**(7/8)/6 + 5 + sqrt(2)*3**(7/8)*I/6, sqrt(2)*3**(7/8)/6 + 5 - sqrt(2)*3**(7/8)*I/6, sqrt(2)*3**(7/8)/6 + 5 + sqrt(2)*3**(7/8)*I/6]
```
