### ISSUE TITLE
Exception while solving a polynomial

### ISSUE THREAD

**Issue by WhiteBlackGoose** [sympy/sympy#19510]
```python
import sympy

x = sympy.Symbol('x')
a = sympy.Symbol('a')

expr = x ** 4 + (-12.000001 - a) * x ** 3 + (47 + 12 * a) * x ** 2 + (-60 + -47 * a) * x + 60 * a

from sympy.solvers import solve
solve(expr, x)
```
If we put 12 instead of 12.000001, we get correct roots [3, 4, 5, a]. But if we make it 12.000001, it throws [an exception](http://code.re/pdc):
```
D:\main\programs\anaconda\lib\site-packages\sympy\core\function.py in nfloat(expr, n, exponent)
   3080             return type(expr)([(k, nfloat(v, n, exponent)) for k, v in
   3081                                list(expr.items())])
-> 3082         return type(expr)([nfloat(a, n, exponent) for a in expr])
   3083     rv = sympify(expr)
   3084 

TypeError: __new__() missing 1 required positional argument: 'cond'
```

**Comment by WhiteBlackGoose** [comment]
It also crashes with just a random polynomial
```
x ** 4 + (-1 * -32.1243254644 * a - (sqrt(5) * (1 / 16) + sqrt(3) * (1 / 2) + 424.323244)) * x ** 3 + (sqrt(3) * sqrt(5) * (1 / 32) + (sqrt(5) * (1 / 16) + sqrt(3) * (1 / 2)) * 424.323244 + (-1 * (sqrt(5) * (1 / 16) * 32.1243254644 + 13631.0979923660145136) - sqrt(3) * (1 / 2) * 32.1243254644) * a) * x ** 2 + ((sqrt(3) * (sqrt(5) * (1 / 32) + (1 / 2) * 424.323244) * 32.1243254644 + sqrt(5) * (1 / 16) * 13631.0979923660145136) * a - sqrt(3) * sqrt(5) * (1 / 32) * 424.323244) * x + -1 * sqrt(3) * sqrt(5) * (1 / 32) * 13631.0979923660145136 * a
```
(well at least my engine surpasses sympy at something)

**Comment by smichr** [comment]
Which version of SymPy? It passes with `1.6` tested on repl.it
```python
>>> import sympy
>>> sympy.__version__
'1.6'
```

**Comment by oscarbenjamin** [comment]
The example with `12.000001` works fine for me with sympy 1.6 although the returned roots are complicated.

The "random polynomial" above gives an exception on 1.6 and master:
```python
>>> from sympy import *
>>> x = Symbol('x')
>>> a = Symbol('a')
>>> expr = x ** 4 + (-1 * -32.1243254644 * a - (sqrt(5) * (1 / 16) + sqrt(3) * (1 / 2) + 424.323244)) * x ** 3 + (sqrt(3) * sqrt(5) * (1 / 32) + (sqrt(5) * (1 / 16) + sqrt(3) * (1 / 2)) * 424.323244 + (-1 * (sqrt(5) * (1 / 16) * 32.1243254644 + 13631.0979923660145136) - sqrt(3) * (1 / 2) * 32.1243254644) * a) * x ** 2 + ((sqrt(3) * (sqrt(5) * (1 / 32) + (1 / 2) * 424.323244) * 32.1243254644 + sqrt(5) * (1 / 16) * 13631.0979923660145136) * a - sqrt(3) * sqrt(5) * (1 / 32) * 424.323244) * x + -1 * sqrt(3) * sqrt(5) * (1 / 32) * 13631.0979923660145136 * a
>>> solve(expr, x)
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/sympy/sympy/utilities/iterables.py", line 816, in sift
    sift[keyfunc(i)].append(i)
TypeError: tuple indices must be integers or slices, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 1094, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 1606, in _solve
    soln = roots(poly, **solvers)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polyroots.py", line 1023, in roots
    for currentroot in _try_decompose(f):
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polyroots.py", line 921, in _try_decompose
    for currentroot in _try_heuristics(factors[0]):
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polyroots.py", line 967, in _try_heuristics
    result += roots_quartic(f)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polyroots.py", line 322, in roots_quartic
    sols = _roots_quartic_euler(e, f, g, aon4)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polyroots.py", line 228, in _roots_quartic_euler
    xsols = list(roots(Poly(eq, x), cubics=False).keys())
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polyroots.py", line 1009, in roots
    res = to_rational_coeffs(f)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 6165, in to_rational_coeffs
    r = _try_translate(f, f1)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 6133, in _try_translate
    c1, c2 = sift(args, lambda z: z.is_rational, binary=True)
  File "/Users/enojb/current/sympy/sympy/sympy/utilities/iterables.py", line 818, in sift
    raise ValueError('keyfunc gave non-binary output')
ValueError: keyfunc gave non-binary output
```
The use of `sift` supposes that is is always possible to determine if the inputs are rational or not but we the offending item is:
```
ipdb> p i                                                                                                                         
-19349480372675592668763*a**2/100000000000000000000
ipdb> p i.is_rational                                                                                                             
None
```
As a workaround I tried declaring `a` to be rational but then hit on the same error for a different input due to a bug in the assumptions handling somewhere:
```julia
In [17]: a = Symbol('a', rational=True)                                                                                           

In [18]: print((-80310813661*sqrt(3)*a/40000000000).is_rational)                                                                  
None
```

**Comment by WhiteBlackGoose** [comment]
@smichr 1.4

**Comment by WhiteBlackGoose** [comment]
@oscarbenjamin after having updated to 1.6 even the last polynomial worked for me
```python
import sympy

x = sympy.Symbol('x')
a = sympy.Symbol('a')

sqrt = lambda x: x ** 0.5
expr = x ** 4 + (-1 * -32.1243254644 * a - (sqrt(5) * (1 / 16) + sqrt(3) * (1 / 2) + 424.323244)) * x ** 3 + (sqrt(3) * sqrt(5) * (1 / 32) + (sqrt(5) * (1 / 16) + sqrt(3) * (1 / 2)) * 424.323244 + (-1 * (sqrt(5) * (1 / 16) * 32.1243254644 + 13631.0979923660145136) - sqrt(3) * (1 / 2) * 32.1243254644) * a) * x ** 2 + ((sqrt(3) * (sqrt(5) * (1 / 32) + (1 / 2) * 424.323244) * 32.1243254644 + sqrt(5) * (1 / 16) * 13631.0979923660145136) * a - sqrt(3) * sqrt(5) * (1 / 32) * 424.323244) * x + -1 * sqrt(3) * sqrt(5) * (1 / 32) * 13631.0979923660145136 * a

from sympy.solvers import solve
print(solve(expr, x))
```
But it's not master, it's from pip's packages.

**Comment by oscarbenjamin** [comment]
That's because of the `sqrt = lambda x: x ** 0.5`. If you use the exact `sqrt` you'll get
```
~/current/sympy/sympy/sympy/utilities/iterables.py in sift(seq, keyfunc, binary)
    826             sift[keyfunc(i)].append(i)
    827         except (IndexError, TypeError):
--> 828             raise ValueError('keyfunc gave non-binary output')
    829     return T, F
    830 

ValueError: keyfunc gave non-binary output```
