### ISSUE TITLE
rs_series throws TypeError

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#19543]
```python
>>> from sympy.polys.ring_series import rs_series
>>> from sympy.abc import a, b
>>> rs_series(sin(a**QQ(3,7))*exp(a + b**QQ(6,7)), a, 2)
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/polys/ring_series.py", line 1997, in rs_series
    series = _rs_series(expr, series, a, prec)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/polys/ring_series.py", line 1926, in _rs_series
    min_pows[i])
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/polys/ring_series.py", line 1910, in _rs_series
    R(a), prec)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/polys/ring_series.py", line 1148, in rs_exp
    return const*rs_exp(p1, x, prec)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/polys/ring_series.py", line 1155, in rs_exp
    for k in range(prec):
TypeError: 'Rational' object cannot be interpreted as an integer
```

**Comment by gschintgen** [comment]
Why are you filing an exact duplicate? Old issues are perfectly searchable (and even more so if they're properly labeled). Maybe I'm missing something.

**Comment by czgdp1807** [comment]
The original issue doesn't highlight the `TypeError` in the OP.

**Comment by oscarbenjamin** [comment]
You can edit the original issue to change it's title or add details.

**Comment by czgdp1807** [comment]
Well, let it remain open here. I don't know whether the reason for `TypeError` is the same as that of incorrect results(as the OP of the original issue suggests). So, may be both are different.

**Comment by guptapratykshh** [comment]
we could ensure converting `prec` to integer using `int(prec)` avoids `TypeError` when `range(prec)` is been called.

```
    if len(p) > 20:
        return _exp1(p, x, prec)
    one = R(1)
    n = 1
    c = []
    prec = int(prec)
    for k in range(prec):
        c.append(one/n)
        k += 1
        n *= k
```

**Comment by oscarbenjamin** [comment]
The problem is here where prec is computed as a rational:
https://github.com/sympy/sympy/blob/cc300e2d39576163eb17cfb10e6c1f65b1b002ea/sympy/polys/ring_series.py#L1919-L1926
That code assumes that the exponents are all integers. I'm not sure how exactly `prec` should be interpreted when considering rational exponents.

**Comment by guptapratykshh** [comment]
There is a fix that simplifies recursive call by passing original precision - `_series = _rs_series(args[i], R(args[i]), a, prec)` instead of using more complex calculation (prec - sum_pows + min_pows[i]) that gives rational values. This approach is mathematically sounds good for rational exponents with maintaining correctness for integer exponents.

```
        sum_pows = sum(min_pows)
        series = R(1)

        for i in range(n):
            _series = _rs_series(args[i], R(args[i]), a, prec) 
            R = R.compose(_series.ring)
            _series = _series.set_ring(R)
```

```
>>> from sympy.polys.ring_series import rs_series
>>> from sympy.abc import a, b
>>> rs_series(sin(a**QQ(3,7))*exp(a + b**QQ(6,7)), a, 2)
a**(10/7)*(exp(b**(6/7))) - 1/6*a**(9/7)*(exp(b**(6/7))) + a**(3/7)*(exp(b**(6/7)))
```

**Comment by guptapratykshh** [comment]
Please look into the fix of this issue above and suggest if this is possible or this needs some changes.
