### ISSUE TITLE
make ConditionSet signature like Lamda

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#19578]
from #19512 comment by @oscarbenjamin 
```
Maybe [ConditionSet] should do the same as Lambda and convert a single symbol to a 1-tuple:

In [25]: Lambda(x, y).signature                                                                                                                
Out[25]: (x,)

In [26]: Lambda((x,), y).signature                                                                                                             
Out[26]: (x,)

In [27]: Lambda((x, y), y).signature                                                                                                           
Out[27]: (x, y)
```
Note that ConditionSet does not have a `signature` attribute: it uses `sym`:

```
>>> ConditionSet(x,x>0,Integers).sym
x
>>> ConditionSet((x,y),x>0,Integers**2).sym
(x, y)
```

**Comment by sylee957** [comment]
If a single signature can be wrapped in Tuple, then `x` and `Tuple(x)` should be identically same.
But I don't think that it is considered same
```
>>> from sympy import *
>>> x = Symbol('x', real=True)
>>> x in S.Reals
True
>>> Tuple(x) in S.Reals
False
>>> Tuple(x) in S.Reals**1
True
>>> x in S.Reals**1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sylee\Documents\Github\sympy\sympy\sets\sets.py", line 672, in __contains__
    raise TypeError('did not evaluate to a bool: %r' % c)
TypeError: did not evaluate to a bool: None
>>> x, y = symbols('x y', real=True)
>>> Tuple(x, y) in S.Reals**2
True
```

**Comment by oscarbenjamin** [comment]
The idea is not that `x == Tuple(x)` but just that the common case as a 1-tuple so we can make that convenient as is done for Lambda. Otherwise every use of `ConditionSet(x, ...)` would have to become `ConditionSet((x,), ...)` to make the univariate and multivariate cases consistent.

I would prefer to require the 1-tuple but it's not backwards compatible and it isn't hard to continue to support this in a mostly backwards compatible way. We just have to wrap a non-tuple in a 1-tuple in `__new__` as is done for `Lambda` (for the same reasons):
https://github.com/sympy/sympy/blob/a06054f7a419b0308d7ad530dbf23b903deb6029/sympy/core/function.py#L1962

Doing that once in `__new__` means that everything else is consistent internally. The disadvantage is just that the constructor is over-permissive in some more complex cases that would otherwise be registered as errors.

**Comment by sylee957** [comment]
I'm not sure how the first and the second case should be distinguished if the signature of conditionset is always put to tuple
```
1 in ConditionSet(x, x>0, S.Reals) => True
(1,) in ConditionSet((x,), x>0, S.Reals**1) => True
(1, 1) in ConditionSet((x, y), x>0 & y>0, S.Reals**2) => True
```

**Comment by oscarbenjamin** [comment]
Oh, I think you're right...

Following the way that this works with Lambda, ImageSet and ProductSet which I think are consistent then the rule is that if the first argument to Lambda is not a tuple then we wrap it to make a 1-tuple. That means that `Lambda(x, ...)` is equivalent to `Lambda((x,), ...)` and we can presume that the first arg is always a tuple.

With `ImageSet(Lambda((x, y), x+y), S1, S2)` x is an element of S1 and y is an element of S2. With `ImageSet(Lambda(((x, y),), x+y, S1*S2)` we have that `(x, y)` is an element of `S1*S2`. These sets are equivalent but are presented differently:
```julia
In [19]: ImageSet(Lambda((x, y), x+y), Reals, Integers)                                                                                        
Out[19]: {x + y | x ∊ ℝ , y ∊ ℤ}

In [20]: ImageSet(Lambda(((x, y),), x+y), Reals*Integers)                                                                                      
Out[20]: {x + y | (x, y) ∊ ℝ × ℤ}
```
That doesn't make sense for ConditionSet though because the first argument not only represents how to match the symbols to the base set but also what the output set elements are like...

**Comment by oscarbenjamin** [comment]
I originally suggested this in response to some code that was special casing the single and multiple symbol cases but that doesn't seem to be there any more...

I think that ConditionSet is fine and does not need to be change in this way. The expression (tuple or not) should be identified with the base set so
```
ConditionSet(x, ..., X) # x represents an element of X
ConditionSet((x, y), ..., X*Y) # (x, y) represents an element of X*Y
ConditionSet((x,), ..., X**1) # (x,) represents an element of X**1
```
I don't think that there is any ambiguity/inconsistency there.

**Comment by sylee957** [comment]
I rather think that Lambda can have limited capability for tuples because it always needs unpacking
```
x, y = symbols('x y')
f1 = Lambda((x, y), (2*x, 2*y))
f2 = Lambda((x, y), (3*x, 3*y))
f3 = Lambda((x, y), (4*x, 4*y))

f3(*f2(*f1(1, 1)))
```
```
f1 = Lambda(x, (2*x,))
f2 = Lambda(x, (3*x,))
f3 = Lambda(x, (4*x,))

f3(*f2(*f1(1)))
```
```
f1 = Lambda(x, 2*x)
f2 = Lambda(x, 3*x)
f3 = Lambda(x, 4*x)

f3(f2(f1(1)))
```
And I don't think that it's possible to build such compositions symbolically.

**Comment by sylee957** [comment]
```
A = MatrixSymbol('A', 2, 1)
f1 = Lambda(A, Matrix([2*A[0, 0], 2*A[1, 0]]))
f2 = Lambda(A, Matrix([3*A[0, 0], 4*A[1, 0]]))

f2(f1(Matrix([1, 2])))
```
I still see that it's possible with matrix expressions though.

**Comment by oscarbenjamin** [comment]
> I rather think that Lambda can have limited capability for tuples because it always needs unpacking
> 
> ```
> x, y = symbols('x y')
> f1 = Lambda((x, y), (2*x, 2*y))
> f2 = Lambda((x, y), (3*x, 3*y))
> f3 = Lambda((x, y), (4*x, 4*y))
> 
> f3(*f2(*f1(1, 1)))
> ```

If you want to pass a single argument to the Lambda and have it unpack the tuple then the signature needs to be wrapped in a 1-tuple to show that it represents a single argument:
```
x, y = symbols('x y') 
f1 = Lambda(((x, y),), (2*x, 2*y)) 
f2 = Lambda(((x, y),), (3*x, 3*y)) 
f3 = Lambda(((x, y),), (4*x, 4*y)) 

f3(f2(f1((1, 1))))                                                                                                                     
```

**Comment by sylee957** [comment]
Okay, it makes me clear
But I still think that it doesn't match the signature correctly because 
```
f1 = Lambda(Tuple(Tuple(x, y)), Tuple(2*x, 2*y))
f2 = Lambda(Tuple(Tuple(x, y)), Tuple(3*x, 3*y))
f3 = Lambda(Tuple(Tuple(x, y)), Tuple(4*x, 4*y))

f3(f2(f1((1,))))
```
gives `(24, 24*y)` where it should raise error

**Comment by oscarbenjamin** [comment]
You mean this?
```julia
In [4]: f1 = Lambda(Tuple(Tuple(x, y)), Tuple(2*x, 2*y))                                                                                       

In [5]: f1                                                                                                                                     
Out[5]: ((x, y),) ↦ (2⋅x, 2⋅y)

In [6]: f1((1,))                                                                                                                               
Out[6]: (2, 2⋅y)
```
Yes, I think that should raise...
