### ISSUE TITLE
Gaussian integer division raises TypeError

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#19579]
Gaussian integer division raises error when `auto=True` is enabled, which is default behavior. 
```python3
>>> from sympy import *
>>> from sympy.polys.domains.gaussiandomains import ZZ_I, QQ_I
>>> x = Symbol('x')
>>> p = Poly(2+3*I, x, domain=ZZ_I)
>>> q = Poly(1-I, x, domain=ZZ_I)
>>> p.div(q, auto=False)
(Poly(0, x, domain='ZZ_I'), Poly(2 + 3*I, x, domain='ZZ_I'))
>>> p.div(q, auto=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sylee\Documents\Github\sympy\sympy\polys\polytools.py", line 1663, in div
    F, G = F.to_field(), G.to_field()
  File "C:\Users\sylee\Documents\Github\sympy\sympy\polys\polyclasses.py", line 289, in to_field
    return f.convert(f.dom.get_field())
  File "C:\Users\sylee\Documents\Github\sympy\sympy\polys\polyclasses.py", line 300, in convert
    return DMP(dmp_convert(f.rep, f.lev, f.dom, dom), dom, f.lev)
  File "C:\Users\sylee\Documents\Github\sympy\sympy\polys\densebasic.py", line 562, in dmp_convert
    return dup_convert(f, K0, K1)
  File "C:\Users\sylee\Documents\Github\sympy\sympy\polys\densebasic.py", line 539, in dup_convert
    return dup_strip([ K1.convert(c, K0) for c in f ])
  File "C:\Users\sylee\Documents\Github\sympy\sympy\polys\densebasic.py", line 539, in <listcomp>
    return dup_strip([ K1.convert(c, K0) for c in f ])
TypeError: convert() takes 2 positional arguments but 3 were given
```

It works fine with Gaussian rationals. 
```python3
>>> p = Poly(2+3*I, x, domain=QQ_I)
>>> q = Poly(1-I, x, domain=QQ_I)
>>> p.div(q, auto=True)
(Poly(-1/2 + 5*I/2, x, domain='QQ_I'), Poly(0, x, domain='QQ_I'))
>>> p.div(q, auto=False)
(Poly(-1/2 + 5*I/2, x, domain='QQ_I'), Poly(0, x, domain='QQ_I'))
```

**Comment by oscarbenjamin** [comment]
This is fixed in #19485:
```julia
In [16]: p.div(q, auto=False)                                                                                                                                 
Out[16]: (Poly(0, x, domain='ZZ_I'), Poly(2 + 3*I, x, domain='ZZ_I'))

In [17]: p.div(q, auto=True)                                                                                                                                  
Out[17]: (Poly(-1/2 + 5*I/2, x, domain='QQ_I'), Poly(0, x, domain='QQ_I'))
```
