### ISSUE TITLE
dsolve((eq1, eq2)) AttributeError: 'list' object has no attribute 'func'

### ISSUE THREAD

**Issue by satels** [sympy/sympy#19656]
```python
Python 3.8.2 (default, Feb 26 2020, 15:09:34)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> x, y = symbols("x y", cls=Function)
>>> t = Symbol("t")
>>> x(t), y(t)
(x(t), y(t))
>>> eq1 = Eq(-5*y(t).diff(t)+(Rational(5, 2))*x(t).diff(t)+(Rational(1, 2)), y(t).diff(t))
>>> eq2 = Eq(-(Rational(8, 5))*y(t).diff(t)+(Rational(83, 100))*x(t).diff(t)+(Rational(4, 25)), x(t).diff(t))
>>> dsolve((eq1, eq2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 575, in dsolve
    match = classify_sysode(eq, func)
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 1956, in classify_sysode
    type_of_equation = check_linear_2eq_order1(eq, funcs, func_coef)
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 1996, in check_linear_2eq_order1
    x = func[0].func
AttributeError: 'list' object has no attribute 'func'
```

**Comment by oscarbenjamin** [comment]
I see this problem with sympy 1.6. It is already fixed on master though:
```julia
In [37]: >>> from sympy import * 
    ...: >>> x, y = symbols("x y", cls=Function) 
    ...: >>> t = Symbol("t") 
    ...: >>> x(t), y(t) 
    ...: (x(t), y(t)) 
    ...: >>> eq1 = Eq(-5*y(t).diff(t)+(Rational(5, 2))*x(t).diff(t)+(Rational(1, 2)), y(t).diff(t)) 
    ...: >>> eq2 = Eq(-(Rational(8, 5))*y(t).diff(t)+(Rational(83, 100))*x(t).diff(t)+(Rational(4, 25)), x(t).diff(t)) 
    ...: >>> dsolve((eq1, eq2))                                                                                                                
Out[37]: 
⎡            ⌠                                ⎤
⎢            ⎮  97                  ⌠         ⎥
⎢y(t) = C₁ + ⎮ ──── dt, x(t) = C₂ + ⎮ 8/251 dt⎥
⎢            ⎮ 1004                 ⌡         ⎥
⎣            ⌡                                ⎦
```
@mijo2 which PR fixed this?

**Comment by mijo2** [comment]
Well the system of ODEs defined in this issue is of Type 2 and this solver was added in PR #19341

**Comment by mijo2** [comment]
Type 2 means linear n equations constant coefficient non-homogeneous solver.

**Comment by oscarbenjamin** [comment]
So has the buggy code been removed?

**Comment by mijo2** [comment]
No, I don't think that the buggy code has been removed, I have to check that but this specific case is fixed by the new solver since this type of equation matches with the n equations matching code and thus for this specific case, the program doesn't reach the buggy code.

If the buggy code still persists, then I would add a fix soon.

**Comment by mijo2** [comment]
I think this problem is the same where the `funcs` variable can sometimes be a list of lists. I never understood completely why `dsolve` requires this kind of arrangement, but in the hopes where we don't break anything but following the simplest fix of replacing this list of lists logic, what we can do for now is get the dependent variables in `check_linear_2eq_order1` and write a code so that it extracts the dependent variables no matter how the two dependent variables are stored in the list of lists.

This is a very temporary fix, later, we can try to replace this list of lists thing without breaking anything.

**Comment by naveensaigit** [comment]
This issue can be closed now. On master, I get -
``` python
In [1]: from sympy import *
   ...: x, y = symbols("x y", cls=Function)
   ...: t = Symbol("t")
   ...: x(t), y(t)
Out[1]: (x(t), y(t))

In [2]: eq1 = Eq(-5*y(t).diff(t)+(Rational(5, 2))*x(t).diff(t)+(Rational(1, 2)), y(t).diff(t))
   ...: eq2 = Eq(-(Rational(8, 5))*y(t).diff(t)+(Rational(83, 100))*x(t).diff(t)+(Rational(4, 25)), x(t).diff(t))
   ...: dsolve((eq1, eq2))
Out[2]: 
⎡            97⋅t              8⋅t⎤
⎢y(t) = C₁ + ────, x(t) = C₂ + ───⎥
⎣            1004              251⎦

```

**Comment by oscarbenjamin** [comment]
It is possible to confirm that the `funcs` variable is never a list of lists? That was the root of this. Somewhere something was returning a list of lists instead of a single list.
