### ISSUE TITLE
strip_whitespace script not working with Python3

### ISSUE THREAD

**Issue by friyaz** [sympy/sympy#19654]
Using python 3.5
```python
>>> ./bin/strip_whitespace sympy/vector/integrals.py
Traceback (most recent call last):
  File "./bin/strip_whitespace", line 99, in <module>
    main()
  File "./bin/strip_whitespace", line 94, in main
    strip_file(args[0], not options.dry, options.verbose)
  File "./bin/strip_whitespace", line 21, in strip_file
    if line.endswith(" \n"):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```
It works with Python 2.7.`

**Comment by oscarbenjamin** [comment]
It probably shouldn't open the file in binary mode.
