### ISSUE TITLE
sin(y'') + y' = x TypeError: Invalid NaN comparison

### ISSUE THREAD

**Issue by satels** [sympy/sympy#19655]
```python
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> x = Symbol('x')
>>> y = Function('y')
>>> dsolve(Eq(sin(Derivative(y(x), (x, 2))) + Derivative(y(x), x), x), y(x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 653, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 684, in _helper_simplify
    sols = solvefunc(eq, func, order, match)
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 3971, in ode_nth_order_reducible
    gsol = dsolve(geq, g(x))
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 653, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 682, in _helper_simplify
    sols = solvefunc.get_general_solution()
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/single.py", line 213, in get_general_solution
    return self._get_general_solution()
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/single.py", line 702, in _get_general_solution
    sol = dsolve(eq, func(x))
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 653, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 688, in _helper_simplify
    rv =  odesimp(eq, sols, func, hint)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/multidimensional.py", line 136, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 2544, in odesimp
    eq[i] = constant_renumber(eq[i], ode.free_symbols)
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 2997, in constant_renumber
    expr = _constant_renumber(expr)
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 2976, in _constant_renumber
    _constant_renumber(expr.rhs))
  File "/usr/local/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 2995, in _constant_renumber
    sortedargs.sort(key=sort_key)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/expr.py", line 405, in __lt__
    return self._cmp(other, "<", StrictLessThan)
  File "/usr/local/lib/python3.8/site-packages/sympy/core/expr.py", line 348, in _cmp
    raise TypeError("Invalid NaN comparison")
TypeError: Invalid NaN comparison
```

**Comment by oscarbenjamin** [comment]
It looks like this is handled by `nth_order_reducible` and then `factorable` finally leading to
```julia
In [27]: eq = Eq(y(x).diff(x), pi - asin(x - y(x)))

In [28]: eq
Out[28]: 
d                            
──(y(x)) = π - asin(x - y(x))
dx                           

In [29]: classify_ode(eq)
Out[29]: ('1st_power_series', 'lie_group')

In [30]: dsolve(eq)
---------------------------------------------------------------------------
TypeError: Invalid NaN comparison
```
So `dsolve` is attempting to use the power series method (#15916) and that gives an error somehow.

The nan comparison emerged during sorting here:
https://github.com/sympy/sympy/blob/a22dc7f998810b755f600651d101d55858915ec5/sympy/solvers/ode/ode.py#L2923

There are no nans in sortedargs but we get a nan from the application of `sort_key` defined here:
https://github.com/sympy/sympy/blob/a22dc7f998810b755f600651d101d55858915ec5/sympy/solvers/ode/ode.py#L2886-L2890

This code seems to presume that it's okay just to substitute all integration constants for 1 but that's not always valid. In this case we have:
```
ipdb> p sortedargs[2]                                                                                                                          
x**3*(-C1*(asin(C1) + pi)/(1 - C1**2)**(3/2) + C1/(1 - C1**2)**(3/2) + (asin(C1) + pi)*(C1*(asin(C1) + pi)/(1 - C1**2)**(3/2) - C1/(1 - C1**2)**(3/2) + 1/(1 - C1**2)) - 1/(1 - C1**2))/6
```
That is
```julia
In [36]: x**3*(-C1*(asin(C1) + pi)/(1 - C1**2)**(S(3)/2) + C1/(1 - C1**2)**(S(3)/2) + (asin(C1) + pi)*(C1*(asin(C1) + pi)/(1 - C1**2)**(S(3)/2)
    ...:  - C1/(1 - C1**2)**(S(3)/2) + 1/(1 - C1**2)) - 1/(1 - C1**2))/6
Out[36]: 
 3 ⎛  C₁⋅(asin(C₁) + π)        C₁                       ⎛C₁⋅(asin(C₁) + π)        C₁           1   ⎞      1   ⎞
x ⋅⎜- ───────────────── + ──────────── + (asin(C₁) + π)⋅⎜───────────────── - ──────────── + ───────⎟ - ───────⎟
   ⎜              3/2              3/2                  ⎜            3/2              3/2         2⎟         2⎟
   ⎜     ⎛      2⎞        ⎛      2⎞                     ⎜   ⎛      2⎞        ⎛      2⎞      1 - C₁ ⎟   1 - C₁ ⎟
   ⎝     ⎝1 - C₁ ⎠        ⎝1 - C₁ ⎠                     ⎝   ⎝1 - C₁ ⎠        ⎝1 - C₁ ⎠             ⎠          ⎠
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                       6  
```
You can see that we have `1-C1**2` in all the denominators. Since `sort_key` will substitute `C1=1` this gives a nan. I'm not sure why `sort_key` is doing that substitution but it should not. We can not presume that any particular value is valid for the integration constants.

**Comment by EricWay1024** [comment]
I'm working on this issue and I've come up with one possible solution. We could still use the "substitute all constants Ci to one" strategy, because it is convenient to use existing `sort_key` methods. However, we should always check if after substitution the argument becomes `nan`. If so, just change that argument into any number (say one), because the sorting here seems only to rely on the order of the arguments. I was wondering if this idea is okay, and if yes, I'll submit a pull request soon.

**Comment by oscarbenjamin** [comment]
That sounds like a quick fix which could be okay if it works. Really I think it would be better to find an approach that does not depend on substituting anything though.

I'm not sure but perhaps something like this:
```
def sort_key(expr):
    if not (expr.free_symbols & set(constantsymbols)):
        return default_sort_key(expr)
    else:
        return default_sort_key((type(expr),) + tuple(map(sort_key, expr.args)))
```

**Comment by EricWay1024** [comment]
The main problem with a substitution-free approach here is that the return values of `default_sort_key`, which relies on `sort_key` methods of several classes, have a pattern that depends on the specific type of the argument, and thus it is not easy to rewrite it recursively in a few lines when trying to regard every constant symbol as a number. 

After consideration I think a better way is to change how the substitution works here: 
1. Do not substitute when there is no constant symbol in the expression;
2. When all free symbols in the expression are constant symbols, just regard the entire expression as one;
3. In other cases, recursively substitute each argument of the expression.

In case 2 we avoid the risk of getting a `nan` by not doing the actual computation of the expression.

```python
    constantsymbols_set = set(constantsymbols)
    def subs_constantsymbols(expr: Expr):
        if not expr.free_symbols & constantsymbols_set:
            return expr
        elif expr.free_symbols.issubset(constantsymbols_set):
            return S.One
        else:
            return expr.func(*map(subs_constantsymbols, expr.args))

    def sort_key(expr: Expr):
        return default_sort_key(subs_constantsymbols(expr))
```
This actually works and I have locally passed the tests.

**Comment by oscarbenjamin** [comment]
I think that any value substituted will fail in some situations:
```python
In [18]: expr = 1 / (t - t*(C1 - C2))

In [19]: expr
Out[19]: 
       1        
────────────────
-t⋅(C₁ - C₂) + t

In [20]: subs_constantsymbols(expr)
Out[20]: zoo
```

**Comment by EricWay1024** [comment]
Indeed that will still fail. 

I guess we should do a `constantsimp` (defined in the same file) before substituting all the new constants to `1`. That would directly transform `1 / (t - t*(C1 - C2))` to `C1/t`. In such a way it prevents us from getting zero on the denominator (and other similar cases) after substitution.

```python
    C_1 = [(ci, S.One) for ci in constantsymbols]
    constantsymbols_set = set(constantsymbols)
    def subs_constantsymbols(expr: Expr):
        if not expr.free_symbols & constantsymbols_set:
            return expr
        else:
            return constantsimp(expr, constantsymbols_set).subs(C_1)

    def sort_key(expr: Expr):
        return default_sort_key(subs_constantsymbols(expr))
```

**Comment by oscarbenjamin** [comment]
There is no way to make sure that it is okay to randomly set all the constants to some value:
```python
In [48]: eq = (C1 + t)/(t*(C1 + C2) - 2*t)

In [49]: eq
Out[49]: 
      C₁ + t     
─────────────────
t⋅(C₁ + C₂) - 2⋅t

In [50]: subs_constantsymbols(eq)
Out[50]: 
zoo⋅(t + 1)
───────────
     t    
```
The solution is to have a sort key that is not based on substituting values into unknown expressions.

**Comment by EricWay1024** [comment]
Really I failed to consider those situations, thank you for the correction. 

Now I've tried to rewrite the `sort_key` method for the `Expr` class. while keeping everything else basically unchanged, we return the sort key of a constant when the expression is a constant:

```python
    constantsymbols_set = set(constantsymbols)
    constant_subexprs = _get_constant_subexpressions(expr, constantsymbols)
    def sort_key(expr: Expr):
        if not expr.free_symbols & constantsymbols_set:
            return default_sort_key(expr)
        if expr in constant_subexprs:
            return default_sort_key(S.One)

        coeff, expr = expr.as_coeff_Mul()
        if expr.is_Pow:
            if expr.base is S.Exp1:
                # If we remove this, many doctests will go crazy:
                # (keeps E**x sorted like the exp(x) function,
                #  part of exp(x) to E**x transition)
                expr, exp = Function("exp")(expr.exp), S.One
            else:
                expr, exp = expr.args
        else:
            expr, exp = expr, S.One

        if expr.is_Dummy:
            args = (expr.sort_key(),)
        elif expr.is_Atom:
            args = (str(expr),)
        else:
            if expr.is_Add:
                args = expr.as_ordered_terms()
            elif expr.is_Mul:
                args = expr.as_ordered_factors()
            else:
                args = expr.args
            args = tuple([sort_key(arg) for arg in args])

        args = (len(args), tuple(args))
        exp = exp.sort_key()
        return expr.class_key(), args, exp, coeff
```

The problem here is that to copy and paste so much code is generally not a good practice. But it seems we have to recursively call our `sort_key` function for each argument of the expression and thus conditioning on the exact type of the expression is needed.

**Comment by oscarbenjamin** [comment]
Is it possible to extend the main `sort_key` method so that it can also do what is needed here?

**Comment by EricWay1024** [comment]
It's possible to add an optional parameter to the `Expr.sort_key` method to pass all the constant symbols. But I think the most elegant way here is to define a subclass of `Symbol` which represents constant symbols. Then we could override the `sort_key` method for this subclass as the expected behavior for it here differs from non-constant symbols.

**Comment by oscarbenjamin** [comment]
Yes, that's a nice idea. There could be a kind of Symbol that is never equal to any other symbol just like Dummy but with a `sort_key`. That even makes me wonder if it shouldn't be done for Dummy already so that the sort key for a Dummy could just be the visible part of its name...

**Comment by EricWay1024** [comment]
But it appears here we can't just use Dummy variables:
```python
In [15]: D1 = Dummy('D1')

In [16]: D2 = Dummy('D2')

In [18]: (D1*x**2).sort_key() < (D2*x).sort_key()
Out[18]: True

In [19]: (x**2).sort_key() < (x).sort_key()
Out[19]: False
```
The subclass of constant symbols could have some special properties apart from that its sorting key is that of a number. For example, the `constantsimp` function could also be rewritten once this subclass is defined, as we could define operations like `C1+C2=C1` for constant symbols.

**Comment by oscarbenjamin** [comment]
There is an open issue (from ages ago) about introducing a special type of symbol for arbitrary constants.

**Comment by EricWay1024** [comment]
It seems there would be much work to do to introduce this special type of symbol. Will it be okay to temporarily use this rewriting of the `Expr.sort_key` method as I've mentioned above to have a quick fix of this issue?

> 
> ```python
>     constantsymbols_set = set(constantsymbols)
>     constant_subexprs = _get_constant_subexpressions(expr, constantsymbols)
>     def sort_key(expr: Expr):
>         if not expr.free_symbols & constantsymbols_set:
>             return default_sort_key(expr)
>         if expr in constant_subexprs:
>             return default_sort_key(S.One)
>         if expr.is_Dummy or expr.is_Atom:
>             return default_sort_key(expr)
> 
>         coeff, expr = expr.as_coeff_Mul()
>         if expr.is_Pow:
>             if expr.base is S.Exp1:
>                 # If we remove this, many doctests will go crazy:
>                 # (keeps E**x sorted like the exp(x) function,
>                 #  part of exp(x) to E**x transition)
>                 expr, exp = Function("exp")(expr.exp), S.One
>             else:
>                 expr, exp = expr.args
>         else:
>             expr, exp = expr, S.One
> 
>         if expr.is_Add:
>             args = expr.as_ordered_terms()
>         elif expr.is_Mul:
>             args = expr.as_ordered_factors()
>         else:
>             args = expr.args
>         args = tuple([sort_key(arg) for arg in args])
>         args = (len(args), tuple(args))
>         exp = sort_key(exp)
>         return expr.class_key(), args, exp, coeff
> ```

**Comment by oscarbenjamin** [comment]
> It seems there would be much work to do to introduce this special type of symbol.

Why is it hard to introduce the special kind of symbol?

I was just imagining that we create a special kind of symbol to use here in sorting rather than changing the type of symbol returned by dsolve.

**Comment by EricWay1024** [comment]
OK, I understand. I thought the usage of this symbol would be wider. Then if we are limiting the usage of this kind of symbol in sorting here, should it be defined in `core/basic` or the file where we use it?

**Comment by oscarbenjamin** [comment]
To be clear it would be good to change the type of symbol returned by `dsolve` but I'm not sure that we would want that new type of symbol to have the specific sorting requirements that we are talking about here so it does not necessarily solve this problem.

Also if we are going for a quick fix here then that seems a better option than copying out the `sort_key` function. I would just define the class in the file where it is used and name it with a leading underscore to indicate that it is private.

**Comment by EricWay1024** [comment]
After some attempts I found that we can't just define a class of constant symbol and override the sort key method to make it return a number's sort key, like this:

```python
class _ConstantSymbol(Symbol):
    def sort_key(self, order=None):
        return S.One.sort_key()
```

We have to somehow redefine how this class involves in addition/multiplication/etc (which is the main reason why it's hard to define this class). Otherwise we'll get undesired results:

```python
>>> C1 = _ConstantSymbol('C1')
>>> C2 = _ConstantSymbol('C2')
>>> x = Symbol('x')
>>> (C1 * C2 * x).sort_key()
((3, 0, 'Mul'), (3, (((1, 0, 'Number'), (0, ()), (), 1), ((1, 0, 'Number'), (0, ()), (), 1), ((2, 0, 'Symbol'), (1, ('x',)), ((1, 0, 'Number'), (0, ()), (), 1), 1))), ((1, 0, 'Number'), (0, ()), (), 1), 1)
>>> (C1 * x**2).sort_key()
((3, 0, 'Mul'), (2, (((1, 0, 'Number'), (0, ()), (), 1), ((2, 0, 'Symbol'), (1, ('x',)), ((1, 0, 'Number'), (0, ()), (), 2), 1))), ((1, 0, 'Number'), (0, ()), (), 1), 1)
>>> (C1 * C2 * x).sort_key() < (C1 * x**2).sort_key()
False
```

where `C1*C2*x` should have a smaller order key than `C1*x**2`.

**Comment by 1e9abhi1e10** [comment]
@oscarbenjamin Now it is working on the current master 
``` python 
>>> from sympy import *
>>> x = Symbol('x')
>>> y = Function('y')
>>> dsolve(Eq(sin(Derivative(y(x), (x, 2))) + Derivative(y(x), x), x), y(x))
[Eq(y(x), C1 + Integral(C2 - x - Integral(asin(_0)/(asin(_0) - pi + 1), (_0, -C3 + x)) + Integral(1/(asin(_0) - pi + 1), (_0, -C3 + x)) + pi*Integral(1/(asin(_0) - pi + 1), (_0, -C3 + x)), x)), Eq(y(x), C1 + Integral(C2 - x - Integral(asin(_0)/(asin(_0) - 1), (_0, -C3 + x)) - Integral(1/(asin(_0) - 1), (_0, -C3 + x)), x))]
```
