### ISSUE TITLE
Confusion Reg ODE dsolve usage

### ISSUE THREAD

**Issue by iammosespaulr** [sympy/sympy#19664]
Okay I'm trying to solve this particular set of ODE's and I'm unable to find out where I'm going wrong.

<img src="https://render.githubusercontent.com/render/math?math=\frac{dR}{dt} = R - 0.25 R F">
<img src="https://render.githubusercontent.com/render/math?math=\frac{dF}{dt} = 0.2 R F - 0.6 F">

```python3
import sympy as sp
R = sp.Function('R')
F = sp.Function('F')
t = sp.var('t')
dRdt = R(t).diff(t)
dFdt = F(t).diff(t)
expr1 = sp.Eq(dRdt, R(t) - (0.25 * R(t) * F(t)));expr1

-> Eq(Derivative(R(t), t), -0.25*F(t)*R(t) + R(t))

expr2 = sp.Eq(dFdt, -(0.6 * F(t)) + (0.2 * R(t) * F(t)));expr2

-> Eq(Derivative(F(t), t), 0.2*F(t)*R(t) - 0.6*F(t))

sp.dsolve([expr1, expr2], ics={R(0):10, F(0):6})

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mosespaul/.../sympy2/sympy/solvers/ode/ode.py", line 611, in dsolve
    sols = solvefunc(match)
  File "/Users/mosespaul/.../sympy2/sympy/solvers/ode/ode.py", line 7322, in sysode_nonlinear_2eq_order1
    sol = _nonlinear_2eq_order1_type3(x, y, t, eq)
  File "/Users/mosespaul/.../sympy2/sympy/solvers/ode/ode.py", line 7448, in _nonlinear_2eq_order1_type3
    for sol2s in sol2r:
TypeError: 'Equality' object is not iterable 
```

**Comment by oscarbenjamin** [comment]
I don't think you're doing anything wrong. This is just a bug. @mijo2 will be working on this solver at some point soon I think

**Comment by oscarbenjamin** [comment]
I'm not sure you'll get an analytic solution here but here are some steps towards it. First divide the two equations to get an equation for F in terms of R and solve that:
```julia
In [10]: f = Function('f')                                                                                                                     

In [11]: r = Symbol('r')                                                                                                                       

In [12]: eq = Eq(f(r).diff(r), (-0.25*f(r)*r + r)/(0.2*f(r)*r - 0.6*f(r)))                                                                     

In [13]: eq                                                                                                                                    
Out[13]: 
d             -0.25⋅r⋅f(r) + r  
──(f(r)) = ─────────────────────
dr         0.2⋅r⋅f(r) - 0.6⋅f(r)

In [14]: dsolve(eq)                                                                                                                            
Out[14]: 
            ⎛                              -0.9375  -0.3125⋅r⎞      
f(r) = 4.0⋅W⎝C₁⋅(0.333333333333333⋅r - 1.0)       ⋅ℯ         ⎠ + 4.0

```
Now substitute that to eliminate F from the equation for R and solve:
```julia
In [20]: expr1.subs(F(t), sol.rhs).subs(r, R(t))                                                                                               
Out[20]: 
d                 ⎛     ⎛                                 -0.9375  -0.3125⋅R(t)⎞      ⎞            
──(R(t)) = - 0.25⋅⎝4.0⋅W⎝C₁⋅(0.333333333333333⋅R(t) - 1.0)       ⋅ℯ            ⎠ + 4.0⎠⋅R(t) + R(t)
dt                                                                                                 

In [21]: dsolve(expr1.subs(F(t), sol.rhs).subs(r, R(t)))                                                                                       
---------------------------------------------------------------------------
_CoeffExpValueError                       Traceback (most recent call last)
```
That doesn't look solvable to me and unfortunately it gives an error:
```julia
~/current/sympy/sympy/sympy/integrals/meijerint.py in _get_coeff_exp(expr, x)
    336         return c, S.One
    337     else:
--> 338         raise _CoeffExpValueError('expr not of form a*x**b: %s' % expr)
    339 
    340 

_CoeffExpValueError: expr not of form a*x**b: 0.333333333333333
```

**Comment by iammosespaulr** [comment]
thanks @oscarbenjamin btw these eqns called the [Lotka–Volterra equations](https://www.wikiwand.com/en/Lotka%E2%80%93Volterra_equations) are 1st order nonlinear eqns, so I doubt they have an analytical solution. Anyways I'll post something here if I make any progress on my end 😁
