### ISSUE TITLE
Is cse deterministic?

### ISSUE THREAD

**Issue by Sbozzolo** [sympy/sympy#19675]
I am writing an OpenCL code-generating code. 

In the process, I am also writing some tests. To do this, I first run my sympy code, then, I run the output OpenCL code and I check that it returns the correct result. If this happens, I save the output code and I test my sympy code checking that it reproduces this specific case. The test is done by comparing character by character my reference file with the output. 

I found that running the tests multiple times without changing anything produces different results. I am attaching a log. I ran the tests twice without touching anything in between, what you should notice is that the "level" where the code fails is different. (The details don't matter, what matters is that the test fails in different ways)

In my sympy code, I use `sympy.cse`, and I found that the reason the test fails is because `sympy.cse` seems to make different choices every time it is run (at least, when the input is very complicated and hundreds of common sub-expressions are found). Note, even when the test fails, the output is "correct" in the sense that it produces the right result when run (as OpenCL program), so, `sympy.cse` is doing its job well. Is cse supposed to be deterministic? 

```
$ python -m unittest
....................
======================================================================
FAIL: test_generate_geodesic_clcode (test.test_generate_metric.TestGenerateMetric) (level=7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sbozzolo/documents/codes/gray2/gray-python/test/test_generate_metric.py", line 183, in test_generate_geodesic_clcode
    level_out[level])
AssertionError: 'real[6285 chars]y_subhb;\nreal gray_subbaf = gray_subdg*gray_s[16000 chars]};\n' != 'real[6285 chars]y_subbe;\nreal gray_subbaf = gray_subdd*gray_s[16000 chars]};\n'
Diff is 36046 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 21 tests in 104.901s

FAILED (failures=1)

~/documents/codes/gray2/gray-python master* 1m 45s
$ python -m unittest
....................
======================================================================
FAIL: test_generate_geodesic_clcode (test.test_generate_metric.TestGenerateMetric) (level=8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sbozzolo/documents/codes/gray2/gray-python/test/test_generate_metric.py", line 183, in test_generate_geodesic_clcode
    level_out[level])
AssertionError: 'real[8592 chars]_subbaf*gray_subbdc;\nreal gray_subbdj = gray_[14132 chars]};\n' != 'real[8592 chars]_subbcj*gray_subib;\nreal gray_subbdj = gray_s[14132 chars]};\n'
Diff is 23626 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 21 tests in 103.979s

FAILED (failures=1)

```

**Comment by moorepants** [comment]
I think it is best not to test against the output of CSE, simply because this may change with SymPy versions. I've always found it ot be deterministic for a given SymPy version, but its possible it isn't for some expressions. My recommendation is to test the numerical evaluation of the resulting output for known input-output combinations.
