### ISSUE TITLE
factor gets stuck with imaginary extension

### ISSUE THREAD

**Issue by AlanPearl** [sympy/sympy#19688]
# Overview
I'm not really an expert with sympy expressions, but this feature used to work and broke in version 1.6. Basically, running `sympy.factor(expr, extension=sympy.I)` on an expression should perform complex factoring. For example, factoring x^2 + 2ixy - y^2 into (x + iy)^2 worked in version 1.5.1. See the example below.

# Test case
> `ifactor-test.py`
```
import sympy as sp

x, y = sp.symbols("x y")
expr1 = x**2 + 2*sp.I*x*y - y**2
print(expr1)

expr2 = sp.factor(expr1, extension=sp.I)
print(expr2)
```

### In version 1.5.1, this works perfectly fine
> `pip install sympy==1.5.1`
> `python ifactor-test.py`
```
x**2 + 2*I*x*y - y**2
(x + I*y)**2
```

### In version 1.6, it gets stuck
> `pip install sympy==1.6`
> `python ifactor-test.py`
> *Hit Ctrl-C after a bit (the stack trace isn't always the same; seems like an infinite loop?)*
```
x**2 + 2*I*x*y - y**2
^CTraceback (most recent call last):
  File "sympy-bug.py", line 7, in <module>
    expr2 = sp.factor(expr1, extension=sp.I)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/polytools.py", line 6361, in factor
    return _generic_factor(f, gens, args, method='factor')
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/polytools.py", line 6033, in _generic_factor
    return _symbolic_factor(sympify(expr), opt, method)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/polytools.py", line 5973, in _symbolic_factor
    coeff, factors = _symbolic_factor_list(together(expr, fraction=opt['fraction']), opt, method)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/polytools.py", line 5938, in _symbolic_factor_list
    _coeff, _factors = func()
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/polytools.py", line 3303, in factor_list
    coeff, factors = f.rep.factor_list()
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/polyclasses.py", line 796, in factor_list
    coeff, factors = dmp_factor_list(f.rep, f.lev, f.dom)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/factortools.py", line 1269, in dmp_factor_list
    coeff, factors = dmp_ext_factor(f, u, K0)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/factortools.py", line 1150, in dmp_ext_factor
    s, g, r = dmp_sqf_norm(F, u, K)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/sqfreetools.py", line 164, in dmp_sqf_norm
    if dmp_sqf_p(r, u, K.dom):
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/sqfreetools.py", line 75, in dmp_sqf_p
    return not dmp_degree(dmp_gcd(f, dmp_diff(f, 1, u, K), u, K), u)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/euclidtools.py", line 1626, in dmp_gcd
    return dmp_inner_gcd(f, g, u, K)[0]
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/euclidtools.py", line 1585, in dmp_inner_gcd
    h, cff, cfg = _dmp_inner_gcd(f, g, u, K)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/euclidtools.py", line 1546, in _dmp_inner_gcd
    return dmp_qq_heu_gcd(f, g, u, K)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/euclidtools.py", line 1458, in dmp_qq_heu_gcd
    h, cff, cfg = dmp_zz_heu_gcd(f, g, u, K1)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/euclidtools.py", line 1343, in dmp_zz_heu_gcd
    cfg_, r = dmp_div(g, h, u, K)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/densearith.py", line 1630, in dmp_div
    return dmp_rr_div(f, g, u, K)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/densearith.py", line 1390, in dmp_rr_div
    c, R = dmp_rr_div(lc_r, lc_g, v, K)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/densearith.py", line 1373, in dmp_rr_div
    return dup_rr_div(f, g, K)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/densearith.py", line 1346, in dup_rr_div
    r = dup_sub(r, h, K)
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/densearith.py", line 614, in dup_sub
    return dup_strip([ a - b for a, b in zip(f, g) ])
  File "/home/alan/local/anaconda3/envs/main/lib/python3.8/site-packages/sympy/polys/densebasic.py", line 253, in dup_strip
    def dup_strip(f):
KeyboardInterrupt
```

**Comment by AlanPearl** [comment]
Sorry, didn't test this on the master branch (1.7.dev0) before. It is working, so I guess this issue is closed.

**Comment by oscarbenjamin** [comment]
It seems to have stopped working in cf84b0d732dcb2c41dc6cbe14143672e72cbf1b7 from #19040. It was then fixed in c80df9f414f34a12a0ba9c0d99eb161fd735080e from #19376 

Unfortunately I have literally just released sympy 1.6.1 which could have included that as a bugfix.

**Comment by rainwoodman** [comment]
It was a bit confusing that the milestone is 1.6.1 but the bug is not included in 1.6.1. 

Do you have estimates when there will be a release including this fix?

**Comment by oscarbenjamin** [comment]
The milestone is 1.6.1 because we don't have a 1.6.2 milestone and I didn't know if there would be a 1.6.2 release. Also I've been waiting to see if any other regressions arise but I'm not aware of any except maybe #19788.

If you want to open a PR against the 1.6 branch we could have a 1.6.2 release with just the fix for this and maybe #19788. Otherwise I expect 1.7 to be released in a few months.

**Comment by oscarbenjamin** [comment]
I'm going to release 1.6.2 with #19809. If anyone wants to open a PR for this against the 1.6 branch then that can go in too.

**Comment by rainwoodman** [comment]
It appears to be slightly more than a cherry pick, so perhaps I am very equipped for it. 

In any case, I'll look into this more closely over the weekend -- if you don't get there before me.

**Comment by oscarbenjamin** [comment]
Thanks, that would be great. I'm going away for a week or so now but I'll look at anything when I get back.
