### ISSUE TITLE
Autowrap tests failing on master

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#19700]
See e.g.:
https://travis-ci.org/github/sympy/sympy/jobs/704756564

It won't be possible to merge anything until that gets resolved.

An example failure:
```
________ sympy/external/tests/test_autowrap.py:test_wrap_twice_c_cython ________
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.7.dev0-py3.6.egg/sympy/utilities/autowrap.py", line 167, in _process_files
    retoutput = check_output(command, stderr=STDOUT)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/travis/miniconda/envs/test-environment/bin/python', 'setup.py', 'build_ext', '--inplace']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.7.dev0-py3.6.egg/sympy/testing/runtests.py", line 1359, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.7.dev0-py3.6.egg/sympy/external/tests/test_autowrap.py", line 221, in test_wrap_twice_c_cython
    runtest_autowrap_twice('C', 'cython')
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.7.dev0-py3.6.egg/sympy/external/tests/test_autowrap.py", line 53, in runtest_autowrap_twice
    f = autowrap((((a + b)/c)**5).expand(), language, backend)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.7.dev0-py3.6.egg/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.7.dev0-py3.6.egg/sympy/utilities/autowrap.py", line 646, in autowrap
    return code_wrapper.wrap_code(routine, helpers=helps)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.7.dev0-py3.6.egg/sympy/utilities/autowrap.py", line 148, in wrap_code
    self._process_files(routine)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.7.dev0-py3.6.egg/sympy/utilities/autowrap.py", line 171, in _process_files
    " ".join(command), e.output.decode('utf-8')))
sympy.utilities.autowrap.CodeWrapError: Error while executing command: /home/travis/miniconda/envs/test-environment/bin/python setup.py build_ext --inplace. Command output is:
Compiling wrapper_module_15.pyx because it changed.
[1/1] Cythonizing wrapper_module_15.pyx
running build_ext
building 'wrapper_module_15' extension
creating build
creating build/temp.linux-x86_64-3.6
/home/travis/miniconda/envs/test-environment/bin/x86_64-conda_cos6-linux-gnu-cc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/travis/miniconda/envs/test-environment/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/travis/miniconda/envs/test-environment/include -fPIC -I/home/travis/miniconda/envs/test-environment/include/python3.6m -c wrapped_code_15.c -o build/temp.linux-x86_64-3.6/wrapped_code_15.o -std=c99
/home/travis/miniconda/envs/test-environment/bin/x86_64-conda_cos6-linux-gnu-cc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/travis/miniconda/envs/test-environment/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/travis/miniconda/envs/test-environment/include -fPIC -I/home/travis/miniconda/envs/test-environment/include/python3.6m -c wrapper_module_15.c -o build/temp.linux-x86_64-3.6/wrapper_module_15.o -std=c99
creating build/lib.linux-x86_64-3.6
gcc -pthread -shared -B /home/travis/miniconda/envs/test-environment/compiler_compat -L/home/travis/miniconda/envs/test-environment/lib -Wl,-rpath=/home/travis/miniconda/envs/test-environment/lib -Wl,--no-as-needed -Wl,--sysroot=/ -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/travis/miniconda/envs/test-environment/lib -Wl,-rpath-link,/home/travis/miniconda/envs/test-environment/lib -L/home/travis/miniconda/envs/test-environment/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/travis/miniconda/envs/test-environment/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/travis/miniconda/envs/test-environment/include build/temp.linux-x86_64-3.6/wrapped_code_15.o build/temp.linux-x86_64-3.6/wrapper_module_15.o -o build/lib.linux-x86_64-3.6/wrapper_module_15.cpython-36m-x86_64-linux-gnu.so
gcc: error: unrecognized command line option \u2018-fno-plt\u2019
/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/tmpkf12jd67_sympy_compile/wrapper_module_15.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
error: command '/usr/bin/gcc' failed with exit code 1
```
The problem seems to be `\u2018-fno-plt\u2019` which apparently uses unicode quotation marks:
```julia
In [1]: print('\u2018-fno-plt\u2019')                                                                                                          
‘-fno-plt’
```

**Comment by asmeurer** [comment]
The recent commits to master aren't related to autowrap. This is most likely caused by an updated dependency on Travis.

**Comment by asmeurer** [comment]
Here is the last log to pass https://travis-ci.org/github/sympy/sympy/jobs/704609363
And the first log to fail https://travis-ci.org/github/sympy/sympy/jobs/704751515

I downloaded the logs and did a diff. The only different conda package is a newer version of setuptools. I don't see any other differences in the logs that suggest a dependency change (the gcc versions are the same).

**Comment by asmeurer** [comment]
`fno-plt` doesn't appear anywhere in the codebase. `‘` only appears in some documentation.

**Comment by asmeurer** [comment]
The -fno-plt thing comes from some conda scripts. Something must have broken there.

**Comment by oscarbenjamin** [comment]
Looks like this might have fixed itself...

https://travis-ci.org/github/sympy/sympy/builds/704970334

**Comment by oscarbenjamin** [comment]
I'm not sure what caused or fixed this but it doesn't seem to be a problem now

**Comment by asmeurer** [comment]
That's good. I couldn't figure out what was going on.
