### ISSUE TITLE
Bayesian networks support

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#19728]
Can we use compound distributions to represent Bayesian networks?

Some possible SymPy extensions:

- Support multiple compounded hyperparameters on one random symbol.
- Support nesting compound distributions (compound of compound RV).

**Comment by czgdp1807** [comment]
The second one should be possible. The marginalisation algorithm should be recursive in nature to find the densities. 
The following happens currently,
```python
>>> from sympy.stats import *
>>> N = Normal('N', 0, 1)
>>> M = Normal('M', N, 1)
>>> D = Normal('D', 0, M)
>>> density(D)(x)
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/stats/rv.py", line 882, in density
    return Density(expr, condition).doit(evaluate=evaluate, **kwargs)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/stats/rv.py", line 832, in doit
    result = pspace(expr).compute_density(expr, **kwargs)
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/stats/compound_rv.py", line 82, in compute_density
    new_pspace = self._get_newpspace()
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/stats/compound_rv.py", line 60, in _get_newpspace
    Lambda(x, self.distribution.pdf(x)))
  File "/home/czgdp1807ssd/sympy_project/sympy/sympy/stats/compound_rv.py", line 171, in pdf
    raise NotImplementedError("Compound Distributions for more than"
NotImplementedError: Compound Distributions for more than one random argument is not implemeted yet.
```

**Comment by Smit-create** [comment]
I made some changes to the marginalization algorithm and it produced the following result:
```py
>>> from sympy.stats import *
>>> N = Normal('N', 0, 1)
>>> M = Normal('M', N, 1)
>>> D = Normal('D', 0, M)
>>> from sympy import symbols
>>> x=symbols('x', real=True)
>>> density(D)(x)
Piecewise((0, Abs(arg(x)) <= pi/4), (oo*exp(-x**2/(2*M**2))/M, True))
```
While the `density` of `M` produces good results:
```py
>>> density(D)(x).simplify()
Piecewise((0, Abs(arg(x)) <= pi/4), (oo*exp(-x**2/(2*M**2))/M, True))
>>> density(M)(x).simplify()
exp(-x**2/4)/(2*sqrt(pi))
```

**Comment by czgdp1807** [comment]
As of now, is it possible to sample RVs of compound distributions?

**Comment by Smit-create** [comment]
Currently not, but I was able to sample with the following diff:
```diff
diff --git a/sympy/stats/compound_rv.py b/sympy/stats/compound_rv.py
index d136a3cf90..81783ddbb5 100644
--- a/sympy/stats/compound_rv.py
+++ b/sympy/stats/compound_rv.py
@@ -40,6 +40,10 @@ def __new__(cls, s, distribution):
     def value(self):
         return RandomSymbol(self.symbol, self)

+    @property
+    def values(self):
+        return self._get_newpspace().values
+
     @property
     def symbol(self):
         return self.args[0]
@@ -114,6 +118,9 @@ def conditional_space(self, condition, **kwargs):
         condition = condition.subs({self.value: new_pspace.value})
         return new_pspace.conditional_space(condition)

+    def sample(self, size=(), library='scipy'):
+        new_pspace = self._get_newpspace()
+        return new_pspace.sample(size, library)

 class CompoundDistribution(Basic, NamedArgsMixin):
     """
```
Examples:

```py
>>> from sympy.stats import *
>>> X = Normal('X', 1, 2)
>>> Y = Normal('Y', X, 4)
>>> next(sample(Y))
8.881784197001252e-15
>>> X = Beta('X', 1, 2)
>>> Y = Bernoulli('Y', X)
>>> next(sample(Y))
0
>>> next(sample(Y))
1
```

**Comment by Smit-create** [comment]
I don't know if #19808 is the required fix for this issue as we will still not able to verify until we can integrate/Sum complex expressions while marginalizing. Please have a look if #19808 fixes this or not @Upabjojr @czgdp1807

**Comment by czgdp1807** [comment]
#19808 seems to work correctly for the following test case,
```python
In [1]: from sympy.stats import *                                               

In [2]: N = Normal('N', 0, 1)                                                   

In [3]: M = Normal('M', N, 1)                                                   

In [4]: D = Normal('D', M, 1)                                                   

In [5]: integrate(density(D)(x), (x, -oo, oo))                                  
Out[5]: 1
```

**Comment by czgdp1807** [comment]
Are you sure diff in https://github.com/sympy/sympy/issues/19728#issuecomment-661679272 samples correctly? How is the PDF of the new compound variable passed to scipy correctly?

**Comment by Smit-create** [comment]
According to current roadmap we have `sample` -> `Compoundpspace.sample() `-> `Continuous/Discrete/FinitePSpace.sample()` -> `class SampleScipy` -> `lambdify to scipy custom dist` -> `return the sample`.

I'm not sure that this will work if we have pdf in unevaluated form

**Comment by czgdp1807** [comment]
> I'm not sure that this will work if we have pdf in unevaluated form

Try it out and let us know the error thrown.

**Comment by Smit-create** [comment]
```py
>>> from sympy.stats import *
>>> X = Poisson('X', 2)
>>> Y = Poisson('Y', X)
>>> from sympy.abc import x
>>> density(Y)(x).simplify() # the pdf is not in evaluated form
exp(-2)*Sum(2**X*exp(-X)*X**x/factorial(X), (X, 0, oo))/factorial(x)
>>> next(sample(Y))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smit/Smitlunagariya/sympy/sympy/stats/rv.py", line 1168, in return_generator
    d = ps.sample(size=size, library=library)  # a dictionary that maps RVs to values

  File "/home/smit/Smitlunagariya/sympy/sympy/stats/compound_rv.py", line 123, in sample
    return new_pspace.sample(size, library)
  File "/home/smit/Smitlunagariya/sympy/sympy/stats/drv.py", line 417, in sample
    return {self.value: self.distribution.sample(size, library=library)}
  File "/home/smit/Smitlunagariya/sympy/sympy/stats/drv.py", line 164, in sample
    samps = _get_sample_class_drv[library](self, size)
  File "/home/smit/Smitlunagariya/sympy/sympy/stats/drv.py", line 32, in __new__
    return cls._sample_scipy(dist, size)
  File "/home/smit/Smitlunagariya/sympy/sympy/stats/drv.py", line 66, in _sample_scipy
    return scipy_rv.rvs(size=size)
  File "/home/smit/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2
919, in rvs
    return super(rv_discrete, self).rvs(*args, **kwargs)
  File "/home/smit/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 9
76, in rvs
    vals = self._rvs(*args)
  File "/home/smit/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 9
11, in _rvs
    Y = self._ppf(U, *args)
  File "/home/smit/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 9
24, in _ppf
    return self._ppfvec(q, *args)
  File "/home/smit/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2091, in __
call__

    return self._vectorize_call(func=func, args=vargs)
  File "/home/smit/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2167, in _v
ectorize_call
    outputs = ufunc(*inputs)
  File "/home/smit/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2
536, in _drv2_ppfsingle
    qb = self._cdf(b, *args)
  File "/home/smit/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2
889, in _cdf
    return self._cdfvec(k, *args)
  File "/home/smit/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2091, in __
call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/smit/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2167, in _v
ectorize_call
    outputs = ufunc(*inputs)
  File "/home/smit/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2
885, in _cdf_single
    return np.sum(self._pmf(m, *args), axis=0)
  File "/home/smit/Smitlunagariya/sympy/sympy/stats/drv.py", line 63, in _pmf
    return handmade_pmf(x)
  File "<lambdifygenerated-2>", line 2, in _lambdifygenerated
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by Upabjojr** [comment]
> Are you sure diff in [#19728 (comment)](https://github.com/sympy/sympy/issues/19728#issuecomment-661679272) samples correctly?

Maybe we should try comparing the samples with some output samples from other probabilistic programing languages with a similar Bayesian network.

**Comment by czgdp1807** [comment]
Can we model a Bayesian network using `sympy.stats` as of now? Say for example, if I write probability distributions of each of the nodes of the network in Q3 d) of http://ai.berkeley.edu/exams/sp14_midterm2.pdf and then do some inference using it.

**Comment by Upabjojr** [comment]
An idea for sampling: https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/JointDistributionSequential

The joint object in `tensorflow_probability` can be sampled with its `.sample( )` method, for example `joint.sample(10000)`. It can be easily used to test whether our sampler is correct.
