### ISSUE TITLE
Issue with non-pretty printing in IPython window

### ISSUE THREAD

**Issue by lucasmyers97** [sympy/sympy#19758]
Here's the code, executed in an IPython window in Spyder:

```>>> import sympy as sy
>>> sy.init_printing(pretty_printing=False)
>>> M = sy.zeros(3, 3)
>>> M
```
The error message is this:

```Traceback (most recent call last):

  File "C:\Users\lucas\Miniconda3\lib\site-packages\IPython\core\formatters.py", line 341, in __call__
    return printer(obj)

  File "C:\Users\lucas\Miniconda3\lib\site-packages\sympy\interactive\printing.py", line 188, in _print_latex_png
    s = latex(o, mode=latex_mode, **settings)

TypeError: latex() got an unexpected keyword argument 'pretty_printing'

Traceback (most recent call last):

  File "C:\Users\lucas\Miniconda3\lib\site-packages\IPython\core\formatters.py", line 341, in __call__
    return printer(obj)

  File "C:\Users\lucas\Miniconda3\lib\site-packages\sympy\interactive\printing.py", line 228, in _print_latex_text
    s = latex(o, mode=latex_mode, **settings)

TypeError: latex() got an unexpected keyword argument 'pretty_printing'

Out[4]: 
⎡0  0  0⎤
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎣0  0  0⎦
```

Not sure if this is an IPython problem or a sympy problem.

**Comment by jksuom** [comment]
The keyword is `pretty_print`:
```
Help on function init_printing in module sympy.interactive.printing:

init_printing(pretty_print=True, order=None, use_unicode=None, use_latex=None, wrap_line=None, num_columns=None, no_global=False, ip=None, euler=False, forecolor=None, backcolor='Transparent', fontsize='10pt', latex_mode='plain', print_builtin=True, str_printer=None, pretty_printer=None, latex_printer=None, scale=1.0, **settings)
    Initializes pretty-printer depending on the environment.
    
    Parameters
    ==========
    
    pretty_print : boolean, default=True
        If True, use pretty_print to stringify or the provided pretty
        printer; if False, use sstrrepr to stringify or the provided string
        printer.
```
