### ISSUE TITLE
Failing test on travis: sympy/printing/tests/test_latex.py:test_latex_decimal_separator

### ISSUE THREAD

**Issue by Smit-create** [sympy/sympy#19768]
The [Travis build](https://travis-ci.org/github/sympy/sympy/jobs/707881986) in #19734 fails due to the following error:
```
________________________________________________________________________________

_______ sympy/printing/tests/test_latex.py:test_latex_decimal_separator ________

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.7.dev0-py3.6.egg/sympy/printing/tests/test_llvmjit.py", line 8, in <module>

    import sympy.printing.llvmjitcode as g

  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.7.dev0-py3.6.egg/sympy/printing/llvmjitcode.py", line 19, in <module>

    llvm = import_module('llvmlite.binding').binding

  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/sympy-1.7.dev0-py3.6.egg/sympy/external/importtools.py", line 132, in import_module

    mod = __import__(module, **import_kwargs)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/llvmlite/binding/__init__.py", line 4, in <module>

    from .dylib import *

  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/llvmlite/binding/dylib.py", line 3, in <module>

    from llvmlite.binding import ffi

  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/llvmlite/binding/ffi.py", line 153, in <module>

    raise OSError("Could not load shared object file: {}".format(_lib_name))

OSError: Could not load shared object file: libllvmlite.so

 tests finished: 1030 passed, 11 expected to fail, 

2 expected to fail but passed, 1 exceptions, in 17.12 seconds 

DO *NOT* COMMIT!

Traceback (most recent call last):

  File "<stdin>", line 10, in <module>

Exception: Tests failed
```

**Comment by oscarbenjamin** [comment]
I've opened #19781 which XFAILs the failing test.

I don't know what the cause of this issue is but if we want to unblock CI so that other work can continue then we can merge that for now.

**Comment by oscarbenjamin** [comment]
I see one PR has completed the tests successfully. Maybe this issue has fixed itself.

**Comment by Smit-create** [comment]
I will try restarting the job on my PR if it passes

**Comment by Smit-create** [comment]
Yes, the problem seems to be have fixed, it now passes the job.
