### ISSUE TITLE
AttributeError: 'Add' object has no attribute '_prec' from hyperexpand

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#19773]
```
>>> equ_laplace
470.0*s**2/(1.0*s**4 + 18.7*s**3 + 17.9*s**2 + 4.68*s + 0.131)
>>> inverse_laplace_transform(apart((equ_laplace), s, full=True).doit(), s, t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/integrals/transforms.py", line 1293, in inverse_laplace_transform
    return InverseLaplaceTransform(F, s, t, plane).doit(**hints)
  File "./sympy/integrals/transforms.py", line 121, in doit
    self.function_variable, self.transform_variable, **hints)
  File "./sympy/integrals/transforms.py", line 1245, in _compute_transform
    return _inverse_laplace_transform(F, s, t, self.fundamental_plane, **hints)
  File "./sympy/integrals/transforms.py", line 206, in wrapper
    res = func(*args, **kwargs)
  File "./sympy/integrals/transforms.py", line 1172, in _inverse_laplace_transform
    needeval=True, noconds=False)
  File "./sympy/integrals/transforms.py", line 875, in inverse_mellin_transform
    return InverseMellinTransform(F, s, x, strip[0], strip[1]).doit(**hints)
  File "./sympy/integrals/transforms.py", line 121, in doit
    self.function_variable, self.transform_variable, **hints)
  File "./sympy/integrals/transforms.py", line 819, in _compute_transform
    return _inverse_mellin_transform(F, s, x, strip, **hints)
  File "./sympy/integrals/transforms.py", line 206, in wrapper
    res = func(*args, **kwargs)
  File "./sympy/integrals/transforms.py", line 746, in _inverse_mellin_transform
    h = hyperexpand(G)
  File "./sympy/simplify/hyperexpand.py", line 2491, in hyperexpand
    return f.replace(hyper, do_replace).replace(meijerg, do_meijer)
  File "./sympy/core/basic.py", line 1492, in replace
    rv = walk(self, rec_replace)
  File "./sympy/core/basic.py", line 1476, in walk
    rv = F(rv)
  File "./sympy/core/basic.py", line 1485, in rec_replace
    v = _value(expr, result)
  File "./sympy/core/basic.py", line 1414, in <lambda>
    _value = lambda expr, result: value(*expr.args)
  File "./sympy/simplify/hyperexpand.py", line 2488, in do_meijer
    allow_hyper, rewrite=rewrite, place=place)
  File "./sympy/simplify/hyperexpand.py", line 2373, in _meijergexpand
    t, 1/z0)
  File "./sympy/simplify/hyperexpand.py", line 2299, in do_slater
    t, premult, bh, rewrite=None)
  File "./sympy/simplify/hyperexpand.py", line 2048, in _hyperexpand
    formula = build_hypergeometric_formula(func)
  File "./sympy/simplify/hyperexpand.py", line 1875, in build_hypergeometric_formula
    poly = Poly(expr, _x)
  File "./sympy/polys/polytools.py", line 163, in __new__
    return cls._from_expr(rep, opt)
  File "./sympy/polys/polytools.py", line 293, in _from_expr
    return cls._from_dict(rep, opt)
  File "./sympy/polys/polytools.py", line 237, in _from_dict
    domain, rep = construct_domain(rep, opt=opt)
  File "./sympy/polys/constructor.py", line 275, in construct_domain
    result = _construct_composite(coeffs, opt)
  File "./sympy/polys/constructor.py", line 200, in _construct_composite
    max_prec = max([c._prec for c in coeffs])
  File "./sympy/polys/constructor.py", line 200, in <listcomp>
    max_prec = max([c._prec for c in coeffs])
AttributeError: 'Add' object has no attribute '_prec'
>>> apart((equ_laplace), s, full=True).doit()
1.0*(4668.2356255633 - 20625.6381858767*(-0.482231200549273 - 0.0283089619304889*I)**2 - 1132.17600946867*(-0.482231200549273 - 0.0283089619304889*I)**3 + 292.024336992219*I)/(s + 0.482231200549273 + 0.0283089619304889*I) + 1.0*(4668.2356255633 - 292.024336992219*I - 1132.17600946867*(-0.482231200549273 + 0.0283089619304889*I)**3 - 20625.6381858767*(-0.482231200549273 + 0.0283089619304889*I)**2)/(s + 0.482231200549273 - 0.0283089619304889*I) - 28.1057785843441/(s + 17.7038273656911) + 0.131240160737718/(s + 0.0317102332103131)
```

**Comment by asmeurer** [comment]
Ran into another problem trying to integrate term-by-term

```
>>> [inverse_laplace_transform(i, s, t) for i in Add.make_args(apart((equ_laplace), s, full=True).doit())]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "./sympy/integrals/transforms.py", line 1293, in inverse_laplace_transform
    return InverseLaplaceTransform(F, s, t, plane).doit(**hints)
  File "./sympy/integrals/transforms.py", line 121, in doit
    self.function_variable, self.transform_variable, **hints)
  File "./sympy/integrals/transforms.py", line 1245, in _compute_transform
    return _inverse_laplace_transform(F, s, t, self.fundamental_plane, **hints)
  File "./sympy/integrals/transforms.py", line 206, in wrapper
    res = func(*args, **kwargs)
  File "./sympy/integrals/transforms.py", line 1176, in _inverse_laplace_transform
    f = meijerint_inversion(F, s, t)
  File "./sympy/integrals/meijerint.py", line 2116, in meijerint_inversion
    gs = _rewrite1(f, x)
  File "./sympy/integrals/meijerint.py", line 1569, in _rewrite1
    g = _rewrite_single(g, x, recursive)
  File "./sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "./sympy/integrals/meijerint.py", line 1472, in _rewrite_single
    exponents_only=True), x)
  File "./sympy/integrals/meijerint.py", line 338, in _get_coeff_exp
    raise _CoeffExpValueError('expr not of form a*x**b: %s' % expr)
sympy.integrals.meijerint._CoeffExpValueError: expr not of form a*x**b: 31.5355611977893
```

**Comment by asmeurer** [comment]
The second issue goes away if you replace the floats with rationals. The first issue is probably related to floats too.

**Comment by jprguez1993** [comment]
Hi Aaron,

I have tried to implement your solution but in my case, it does not work.

>>> Add(*[inverse_laplace_transform(nsimplify(i), s, t) for i in Add.make_args(apart((equ_laplace), s, full=True).doit())])

When I run the code this memory error showed up.

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2019.2.3\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/CISTER_Research_Centre/Thermal_Aware/Program/Python/Thermal-Aware/pruebitas_menores.py", line 28, in <module>
    print(Add(*[inverse_laplace_transform(nsimplify(i), s, t) for i in Add.make_args(apart((equ_laplace), s, full=True).doit())]))
  File "C:/CISTER_Research_Centre/Thermal_Aware/Program/Python/Thermal-Aware/pruebitas_menores.py", line 28, in <listcomp>
    print(Add(*[inverse_laplace_transform(nsimplify(i), s, t) for i in Add.make_args(apart((equ_laplace), s, full=True).doit())]))
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\integrals\transforms.py", line 1292, in inverse_laplace_transform
    return InverseLaplaceTransform(F, s, t, plane).doit(**hints)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\integrals\transforms.py", line 122, in doit
    return self._compute_transform(self.function,
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\integrals\transforms.py", line 1244, in _compute_transform
    return _inverse_laplace_transform(F, s, t, self.fundamental_plane, **hints)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\integrals\transforms.py", line 208, in wrapper
    res = func(*args, **kwargs)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\integrals\transforms.py", line 1170, in _inverse_laplace_transform
    f, cond = inverse_mellin_transform(F, s, exp(-t), (None, oo),
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\integrals\transforms.py", line 874, in inverse_mellin_transform
    return InverseMellinTransform(F, s, x, strip[0], strip[1]).doit(**hints)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\integrals\transforms.py", line 122, in doit
    return self._compute_transform(self.function,
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\integrals\transforms.py", line 818, in _compute_transform
    return _inverse_mellin_transform(F, s, x, strip, **hints)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\integrals\transforms.py", line 208, in wrapper
    res = func(*args, **kwargs)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\integrals\transforms.py", line 745, in _inverse_mellin_transform
    h = hyperexpand(G)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\simplify\hyperexpand.py", line 2491, in hyperexpand
    return f.replace(hyper, do_replace).replace(meijerg, do_meijer)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\core\basic.py", line 1539, in replace
    rv = bottom_up(self, rec_replace, atoms=True)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\simplify\simplify.py", line 1150, in bottom_up
    rv = F(rv)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\core\basic.py", line 1520, in rec_replace
    new = _value(expr, result)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\core\basic.py", line 1468, in <lambda>
    _value = lambda expr, result: value(*expr.args)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\simplify\hyperexpand.py", line 2487, in do_meijer
    r = _meijergexpand(G_Function(ap[0], ap[1], bq[0], bq[1]), z,
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\simplify\hyperexpand.py", line 2372, in _meijergexpand
    slater2, cond2 = do_slater(tr(func.bm), tr(func.an), tr(func.bq), tr(func.ap),
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\simplify\hyperexpand.py", line 2298, in do_slater
    hyp = _hyperexpand(Hyper_Function(nap, nbq), harg, ops,
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\simplify\hyperexpand.py", line 2015, in _hyperexpand
    return unpolarify(simplify(p).subs(z0, z))
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\simplify\simplify.py", line 600, in simplify
    _e = cancel(expr)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\polys\polytools.py", line 6620, in cancel
    (F, G), opt = parallel_poly_from_expr((p, q), *gens, **args)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\polys\polytools.py", line 4309, in parallel_poly_from_expr
    return _parallel_poly_from_expr(exprs, opt)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\polys\polytools.py", line 4398, in _parallel_poly_from_expr
    poly = Poly._from_dict(rep, opt)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\polys\polytools.py", line 185, in _from_dict
    return cls.new(DMP.from_dict(rep, level, domain), *gens)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\polys\polyclasses.py", line 277, in from_dict
    return cls(dmp_from_dict(rep, lev, dom), dom, lev)
  File "C:\Users\IL0007M\AppData\Roaming\Python\Python38\site-packages\sympy\polys\densebasic.py", line 1016, in dmp_from_dict
    h.append(dmp_zero(v))
MemoryError

**Comment by jprguez1993** [comment]
I also tried to replace the floats with rationals, as you suggested but the way I implemented leaded the code to an infinity loop. Below the code I used. No output is shown regarding equ_time.  

I am really grateful for your help.
Javier

####CODE#################
import sympy as sym
from fractions import Fraction

from sympy import *

s = sym.Symbol('s')
t = sym.Symbol('t', positive=True)

# Equation in the Laplace domain
equ_laplace = 470.0*s**2/(1.0*s**4 + 18.7*s**3 + 17.9*s**2 + 4.68*s + 0.131)

print(equ_laplace)

for a in preorder_traversal(equ_laplace):
    if isinstance(a, Float):
        temp = format(a, '.2f')
        equ_laplace = equ_laplace.subs(a, Fraction(temp).limit_denominator(1000))

print(equ_laplace)

# Moving to the Time domain
equ_time = sym.inverse_laplace_transform(equ_laplace, s, t)

print("equ_time =", equ_time)
##############################

**Comment by jksuom** [comment]
> sympy.integrals.meijerint._CoeffExpValueError: expr not of form a*x**b: 31.5355611977893

It seems that `as_coeff_mul` fails with `Float` arguments in `_get_coeff_exp`:
https://github.com/sympy/sympy/blob/586a43201d0357e92e8c93548d69a9f42bf548f4/sympy/integrals/meijerint.py#L327
```
>>> Rational(315, 10).as_coeff_mul(x)
(63/2, ())
>>> Float(31.5).as_coeff_mul(x)
(1, (31.5000000000000,))
```
