### ISSUE TITLE
Sympy crash : multiplication on a tread 

### ISSUE THREAD

**Issue by fbordeu** [sympy/sympy#19786]
I encountered this problem with the current version of sympy of anaconda:

The anaconda environment. env.yml
```
--- env.yml ----
    name: python38-sympy_error
    channels:
        - defaults
        - conda-forge
    dependencies:
        - python=3.8
        - sympy=1.6
-----------------

---- test Sympy_Error_1.6.py ----
from sympy.matrices import Matrix
from sympy import  Symbol,Function

print("In main thread ")
space = Matrix([Symbol('x'),Symbol('y'), Symbol("z")])
f = 3.
direction = Matrix([1,1,0])
ut = Matrix([Function("U_0")(*space),Function("U_1")(*space),Function("U_2")(*space)] ).T
res = f*direction*ut
print("In main thread OK ")

print("Not In main thread ")
from threading import Thread
class Work(Thread):
    def __init__(self):
        Thread.__init__(self)
    def run(self):
        space = Matrix([Symbol('x'),Symbol('y'), Symbol("z")])
        f = 3.
        direction = Matrix([1,1,0])
        ut = Matrix([Function("U_0")(*space),Function("U_1")(*space),Function("U_2")(*space)] ).T
        res = f*direction*ut
        print(res)

w = Work()
w.start()
w.join()

----- the error -----------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/local_scratch/fbordeu/env/python38-sympy_error/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "Sympy_Error_1.6.py", line 34, in run
    res = f*direction*ut
  File "/local_scratch/fbordeu/env/python38-sympy_error/lib/python3.8/site-packages/sympy/core/decorators.py", line 127, in binary_op_wrapper
    return func(self, other)
  File "/local_scratch/fbordeu/env/python38-sympy_error/lib/python3.8/site-packages/sympy/matrices/common.py", line 2494, in __mul__
    return self.multiply(other)
  File "/local_scratch/fbordeu/env/python38-sympy_error/lib/python3.8/site-packages/sympy/matrices/common.py", line 2508, in multiply
    isimpbool = _get_intermediate_simp_bool(False, dotprodsimp)
  File "/local_scratch/fbordeu/env/python38-sympy_error/lib/python3.8/site-packages/sympy/matrices/utilities.py", line 45, in _get_intermediate_simp_bool
    return _get_intermediate_simp(default, False, True, dotprodsimp)
  File "/local_scratch/fbordeu/env/python38-sympy_error/lib/python3.8/site-packages/sympy/matrices/utilities.py", line 34, in _get_intermediate_simp
    if dotprodsimp is False or _dotprodsimp_state.state is False:
AttributeError: '_thread._local' object has no attribute 'state'

--------------------------
```
Version 1.5 does not suffer of this issue.

Thanks
Felipe

**Comment by oscarbenjamin** [comment]
Thanks for reporting this.

It has now been fixed in #19810 and backported to the 1.6 branch so this should be fixed in the 1.6.2 release.
