### ISSUE TITLE
Abs sum hangs

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#19834]
`Sum(1/Abs(x+9), (x, 7, oo)).n()` hangs.

**Comment by shivangdubey** [comment]
> `Sum(1/Abs(x+9), (x, 7, oo)).n()` hangs.

On current master version, it returns an error>>

`TypeError: cannot determine truth value of Relational`

**Comment by anutosh491** [comment]
@proy87 , Yess I know having an error returned like the one shown below which is a general case for most of the divergent series would be preferred. 
```
>>> Sum(1/(x+9) , (x, 7, oo)).n()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\anuto\sympy\sympy\sympy\core\evalf.py", line 1514, in evalf
    result = evalf(self, prec + 4, options)
  File "c:\users\anuto\sympy\sympy\sympy\core\evalf.py", line 1366, in evalf
    r = rf(x, prec, options)
  File "c:\users\anuto\sympy\sympy\sympy\core\evalf.py", line 1223, in evalf_sum
    v = hypsum(func, n, int(a), prec2)
  File "c:\users\anuto\sympy\sympy\sympy\core\evalf.py", line 1169, in hypsum
    raise ValueError("Sum diverges like n^%i" % (-p))
ValueError: Sum diverges like n^-1
```
But the point is that I think this can't be implemented in `.n()/.evalf()` cause `evalf` calls `eval_sum()` which runs a check whether we can sum up the series considering them as hypergeometric series and at this place if the series is divergent we get the standard message as above which I guess would be expected in this case . But for the series to pass `is_hypergeomtric()` , it should be a rational function which `Abs` is not !!!! And the point is that there is nothing wrong with this as there might be such functions which would diverge but are not rational and generalizing might be tough . 
The following check from line 1134 in core/evalf.py was implemented considering functions would be rational and divergent, but doesn't deal with irrational and divergent series ,
```
    if start:
        expr = expr.subs(n, n + start)
    hs = hypersimp(expr, n)
    if hs is None:
        raise NotImplementedError("a hypergeometric series is required")
    num, den = hs.as_numer_denom()

    func1 = lambdify(n, num)
    func2 = lambdify(n, den)

    h, g, p = check_convergence(num, den, n)

    if h < 0:
        raise ValueError("Sum diverges like (n!)^%i" % (-h)) 
```

**Comment by anutosh491** [comment]
hence the following error :
```
Traceback (most recent call last):
  File "c:\users\anuto\sympy\sympy\sympy\core\evalf.py", line 1223, in evalf_sum
    v = hypsum(func, n, int(a), prec2)
  File "c:\users\anuto\sympy\sympy\sympy\core\evalf.py", line 1138, in hypsum
    raise NotImplementedError("a hypergeometric series is required")

NotImplementedError: a hypergeometric series is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\anuto\sympy\sympy\sympy\core\evalf.py", line 1514, in evalf
    result = evalf(self, prec + 4, options)
  File "c:\users\anuto\sympy\sympy\sympy\core\evalf.py", line 1366, in evalf
    r = rf(x, prec, options)
  File "c:\users\anuto\sympy\sympy\sympy\core\evalf.py", line 1233, in evalf_sum
    s, err = expr.euler_maclaurin(m=m, n=n, eps=eps,
  File "c:\users\anuto\sympy\sympy\sympy\concrete\summations.py", line 772, in euler_maclaurin
    if (eps and term and abs(term.evalf(3)) < eps) or (k > n):
  File "c:\users\anuto\sympy\sympy\sympy\core\relational.py", line 398, in __bool__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational
```
