### ISSUE TITLE
maximum return TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by wuyudi** [sympy/sympy#19869]
```python
from sympy import *
t = symbols('t')
maximum(
sqrt(3)*(t - 1)/(3*sqrt(t**2 + 1))  , t
)
```

returns TypeError: cannot unpack non-iterable NoneType object

**Comment by oscarbenjamin** [comment]
I see the same error in sympy 1.5.1:
```python
>>> from sympy import *
>>> t = symbols('t')
>>> maximum(
... sqrt(3)*(t - 1)/(3*sqrt(t**2 + 1))  , t
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/calculus/util.py", line 800, in maximum
    return function_range(f, symbol, domain).sup
  File "/Users/enojb/current/sympy/sympy/sympy/calculus/util.py", line 212, in function_range
    solution = solveset(f.diff(symbol), symbol, interval)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 1993, in solveset
    return solveset(f.xreplace({symbol: r}), r, domain
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 2011, in solveset
    return _solveset(f, symbol, domain, _check=True)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 964, in _solveset
    result += _solve_radical(equation,
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 740, in _solve_radical
    eq, cov = unrad(f)
TypeError: cannot unpack non-iterable NoneType object
```
However in sympy 1.6 or master I get:
```python
>>> from sympy import *
t = symbols('t')
maximum(
sqrt(3)*(t - 1)/(3*sqrt(t**2 + 1))  , t
)
>>> t = symbols('t')
>>> maximum(
... sqrt(3)*(t - 1)/(3*sqrt(t**2 + 1))  , t
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/calculus/util.py", line 796, in maximum
    return function_range(f, symbol, domain).sup
  File "/Users/enojb/current/sympy/sympy/sympy/calculus/util.py", line 194, in function_range
    solution = solveset(f.diff(symbol), symbol, interval)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 2092, in solveset
    rv = solveset(f.xreplace({symbol: x}), x, domain)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 2116, in solveset
    return _solveset(f, symbol, domain, _check=True)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 1057, in _solveset
    result += _solve_radical(equation,
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 835, in _solve_radical
    result = solveset_solver(eq, symbol) - \
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 986, in <lambda>
    solver = lambda f, x, domain=domain: _solveset(f, x, domain)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 1057, in _solveset
    result += _solve_radical(equation,
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 835, in _solve_radical
    result = solveset_solver(eq, symbol) - \
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 986, in <lambda>
    solver = lambda f, x, domain=domain: _solveset(f, x, domain)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 1057, in _solveset
    result += _solve_radical(equation,
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 835, in _solve_radical
    result = solveset_solver(eq, symbol) - \
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 986, in <lambda>
    solver = lambda f, x, domain=domain: _solveset(f, x, domain)
...
RecursionError: maximum recursion depth exceeded while calling a Python object
```
The problem is in solveset:
```julia
In [13]: e = -sqrt(3)*x*(x - 1)/(3*(x**2 + 1)**(S(3)/2)) + sqrt(3)/(3*sqrt(x**2 + 1))                                             

In [14]: solveset(e, x, Interval(-oo, oo))                                                                                        
---------------------------------------------------------------------------
RecursionError
```
This line sets up `_solveset` to call itself recursively:
https://github.com/sympy/sympy/blob/872060cb79ef0d7577cbc4c4acb7a7b4cbdcfe9c/sympy/solvers/solveset.py#L986
Here `_solve_radical` is called with `_solveset` as the `solver` argument:
https://github.com/sympy/sympy/blob/872060cb79ef0d7577cbc4c4acb7a7b4cbdcfe9c/sympy/solvers/solveset.py#L1054-L1059
This completes the recursion loop:
https://github.com/sympy/sympy/blob/872060cb79ef0d7577cbc4c4acb7a7b4cbdcfe9c/sympy/solvers/solveset.py#L830-L836

Maybe the problem is that `unrad` fails for this expression:
```julia
In [2]: from sympy.solvers.solvers import unrad                                                                                   

In [3]: e = -sqrt(3)*x*(x - 1)/(3*(x**2 + 1)**(S(3)/2)) + sqrt(3)/(3*sqrt(x**2 + 1))                                              

In [4]: e                                                                                                                         
Out[4]: 
   √3⋅x⋅(x - 1)         √3     
- ───────────── + ─────────────
            3/2        ________
    ⎛ 2    ⎞          ╱  2     
  3⋅⎝x  + 1⎠      3⋅╲╱  x  + 1 

In [6]: print(unrad(e))                                                                                                           
None
```

I think that `unrad` should return:
```julia
In [38]: (e.args[0]**2 - e.args[1]**2).as_numer_denom()[0].expand()                                                               
Out[38]: 
   5    4      3      2    
2⋅x  + x  + 2⋅x  + 2⋅x  + 1
```

**Comment by wuyudi** [comment]
This also meet problem.

```
t = symbols('t')
solveset((8*t - 2)/(3*sqrt(8*t**2 + 4)), t)
```

**Comment by almighty123789** [comment]
Unrad returns ``None`` for  ``e = -sqrt(3)*x*(x - 1)/(3*(x**2 + 1)**(S(3)/2)) + sqrt(3)/(3*sqrt(x**2 + 1))`` because of this
https://github.com/sympy/sympy/blob/62572863590b1c3363d6268f75aea6e83e385728/sympy/solvers/solvers.py#L3309-L3313

These are the ``poly.gens  = (x, sqrt(3))`` 
Theser are the ``gens = [x] ``
