### ISSUE TITLE
Ubuntu 18.04 symbolic package problem

### ISSUE THREAD

**Issue by merden-24** [sympy/sympy#19877]
` syms x
Symbolic pkg v2.9.0: /usr/local/lib/python3.6/dist-packages/sympy/__init__.py:676: SymPyDeprecationWarning:

importing sympy.core.compatibility with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.compatibility
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.

  deprecated_since_version="1.6").warn()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 12, in octoutput_drv
  File "<stdin>", line 54, in octoutput
  File "<stdin>", line 55, in octoutput
  File "/usr/local/lib/python3.6/dist-packages/sympy/__init__.py", line 677, in __getattr__
    return getattr(self.mod, name)
AttributeError: module 'sympy.core.compatibility' has no attribute 'integer_types'
Waiting...............warning: readblock: timeout of 30 exceeded, breaking out
warning: called from
    readblock at line 101 column 7
    python_ipc_popen2 at line 99 column 14
    python_ipc_driver at line 62 column 13
    pycall_sympy__ at line 163 column 9
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
no output so far

error: ipc_popen2: something wrong? timed out starting python
error: called from
    python_ipc_popen2 at line 101 column 7
    python_ipc_driver at line 62 column 13
    pycall_sympy__ at line 163 column 9
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13`

**Comment by oscarbenjamin** [comment]
I guess that this is a problem in octsympy @cbm755.

It looks like `octsympy` is doing `from sympy import compatibility` somewhere which is now deprecated. Also the `integer_types` attribute in the compatibility module has been removed because Python 2 is no longer supported.
