### ISSUE TITLE
Category theory examples from https://docs.sympy.org/latest/modules/categories.html fail on SymPy Live

### ISSUE THREAD

**Issue by catskillsresearch** [sympy/sympy#19933]
This example code fails on SymPy Live in https://docs.sympy.org/latest/modules/categories.html:

```
>>> from sympy.categories import Object, NamedMorphism
Exception in SymPy Live of type 
<type 'exceptions.TypeError'>
for reference the last 5 stack trace entries are
Traceback (most recent call last):
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/handlers.py", line 271, in post
    live.evaluate(statement, session, printer, stream)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/shell.py", line 284, in evaluate
    session_globals_dict = session.globals_dict()
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/models.py", line 87, in globals_dict
    for name, val in zip(self.global_names, self.globals))
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/models.py", line 87, in <genexpr>
    for name, val in zip(self.global_names, self.globals))
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/32fc9e2909a8cd9/python27/python27_dist/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
TypeError: name should be a string, not <class 'sympy.core.symbol.Symbol'>
```

**Comment by oscarbenjamin** [comment]
I just tried and it seemed to work fine...

**Comment by oscarbenjamin** [comment]
Thanks for reporting this.

If there is an issue here then it should be opened for the sympy live repo:
https://github.com/sympy/sympy-live/issues

I'll close this as it's not an issue in the sympy library.
