### ISSUE TITLE
Bug in sympy.integrate for complex valued integrands?

### ISSUE THREAD

**Issue by riemarc** [sympy/sympy#20034]
The output of the code snippet
```
import sympy as sp
z = sp.Symbol("z", real=True)
x = 1 + 1j
a = sp.integrate(sp.exp(x * z), (z, 0, 1)).n()
b = sp.integrate(sp.exp(x * z).expand(complex=True), (z, 0, 1)).n()
print(a)
print(b)
```
is
```
2.75604922709473 + 0.818661347262957*I
1.37802461354736 + 0.909330673631479*I
```
but actually `a` and `b` should have the same value. Even more weird is the fact that the value of `a` is alternating. Or I miss something?

**Comment by oscarbenjamin** [comment]
Interesting. With sympy 1.6.1 I get a different result each time I run this:
```
$ python e.py 
0.468693939915885 + 1.28735528717884*I
1.37802461354736 + 0.909330673631479*I
$ python e.py 
2.75604922709473 + 0.818661347262957*I
1.37802461354736 + 0.909330673631479*I
$ python e.py 
0
1.37802461354736 + 0.909330673631479*I
$ python e.py 
2.75604922709473 + 0.818661347262957*I
1.37802461354736 + 0.909330673631479*I
$ python e.py 
-2.28735528717884 + 0.468693939915885*I
1.37802461354736 + 0.909330673631479*I
```
On master I consistently get this error:
```
$ python e.py 
Traceback (most recent call last):
  File "e.py", line 4, in <module>
    a = sp.integrate(sp.exp(x * z), (z, 0, 1)).n()
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 1544, in integrate
    return integral.doit(**doit_flags)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 482, in doit
    did = self.xreplace(reps).doit(**hints)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 593, in doit
    antideriv = self._eval_integral(
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 929, in _eval_integral
    result, i = risch_integrate(f, x, separate_integral=True,
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/risch.py", line 1738, in risch_integrate
    DE = extension or DifferentialExtension(f, x, handle_first=handle_first,
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/risch.py", line 263, in __init__
    exp_new_extension = self._exp_part(exps)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/risch.py", line 462, in _exp_part
    arga, argd = frac_in(arg, self.t)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/risch.py", line 792, in frac_in
    fa, fd = fa.as_poly(t, **kwargs), fd.as_poly(t, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 1086, in as_poly
    poly = Poly(self, *gens, **args)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 163, in __new__
    return cls._from_expr(rep, opt)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 293, in _from_expr
    return cls._from_dict(rep, opt)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 237, in _from_dict
    domain, rep = construct_domain(rep, opt=opt)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/constructor.py", line 275, in construct_domain
    result = _construct_composite(coeffs, opt)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/constructor.py", line 219, in _construct_composite
    numer[monom] = ground.from_sympy(coeff)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/domains/pythonintegerring.py", line 36, in from_sympy
    raise CoercionFailed("expected an integer, got %s" % a)
sympy.polys.polyerrors.CoercionFailed: expected an integer, got 1.0*I
```

**Comment by riemarc** [comment]
Forgot to say: I use sympy 1.6.2

@oscarbenjamin: exactly the same behavior on my machine, thats what I meant with alternating

**Comment by jksuom** [comment]
It looks like `CC` should be added to `construct_domain`. Something like this, maybe:
```
--- a/sympy/polys/constructor.py
+++ b/sympy/polys/constructor.py
@@ -5,6 +5,7 @@
 from sympy.core import sympify
 from sympy.core.evalf import pure_complex
 from sympy.polys.domains import ZZ, QQ, ZZ_I, QQ_I, EX
+from sympy.polys.domains.complexfield import ComplexField
 from sympy.polys.domains.realfield import RealField
 from sympy.polys.polyoptions import build_options
 from sympy.polys.polyutils import parallel_dict_from_basic
@@ -176,7 +177,8 @@ def _construct_composite(coeffs, opt):
             coeffs.update(list(numer.values()))
             coeffs.update(list(denom.values()))
 
-    rationals = reals = gaussians = False
+    rationals = reals = gaussians = complexes = False
+    floats = []
 
     for coeff in coeffs:
         if coeff.is_Rational:
@@ -184,7 +186,7 @@ def _construct_composite(coeffs, opt):
                 rationals = True
         elif coeff.is_Float:
             reals = True
-            break
+            floats.append(coeff)
         else:
             is_complex = pure_complex(coeff)
             if is_complex is not None:
@@ -194,10 +196,17 @@ def _construct_composite(coeffs, opt):
                         rationals = True
                     gaussians = True
                 else:
-                    pass # XXX: CC?
+                    complexes = True
+                    if x.is_Float:
+                        floats.append(x)
+                    if y.is_Float:
+                        floats.append(y)
 
-    if reals:
-        max_prec = max([c._prec for c in coeffs])
+    max_prec = max(c._prec for c in floats) if floats else 53
+
+    if complexes:
+        ground = ComplexField(prec=max_prec)
+    elif reals:
         ground = RealField(prec=max_prec)
     elif gaussians:
         if rationals:
```

**Comment by oscarbenjamin** [comment]
With that diff we can get back to the non-deterministic behaviour so there is still some other bug:
```
$ python e.py 
2.75604922709473 + 0.818661347262957*I
1.37802461354736 + 0.909330673631479*I
$ python e.py 
0.468693939915885 + 1.28735528717884*I
1.37802461354736 + 0.909330673631479*I
$ python e.py 
-2.28735528717884 + 0.468693939915885*I
1.37802461354736 + 0.909330673631479*I
$ python e.py 
2.75604922709473 + 0.818661347262957*I
1.37802461354736 + 0.909330673631479*I
```

**Comment by oscarbenjamin** [comment]
I've added the 1.7 milestone because the exception currently raised on master indicates a regression since 1.6.

**Comment by oscarbenjamin** [comment]
The issue with the exception has been fixed now in #20194 so I'm removing the 1.7 milestone.

The problem with incorrect and non-deterministic output from heurisch remains.

**Comment by smichr** [comment]
I get a deterministic result from heurisch now (tested six times).
