### ISSUE TITLE
Can sympy.prime be symbolically evaluated?

### ISSUE THREAD

**Issue by GarkGarcia** [sympy/sympy#20053]
Hey all. I'm a contributor for [mathics/Mathics](https://github.com/mathics/Mathics) and I'm trying to fix the following test case:
```
Test failed: Product in Reference of built-in symbols / Arithmetic functions
Product[Prime[k], {k, 1, 12}]

Result: Prime[k] ^ 12
Wanted: 7420738134810

Additional output:
Prime::intpp: Positive integer argument expected in Prime[k].
Prime::intpp: Positive integer argument expected in Prime[k].
```

Fixing this test case would translate to doing something like the following in SymPy:

```
>>> from sympy import prime
>>> from sympy.abc import n
>>> prime(n)
Traceback (most recent call last):
  File "/home/pablo/.local/lib/python3.6/site-packages/sympy/core/compatibility.py", line 373, in as_int
    return operator.index(n)
TypeError: 'Symbol' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pablo/.local/lib/python3.6/site-packages/sympy/ntheory/generate.py", line 383, in prime
    n = as_int(nth)
```

The reason I'm trying to do such a weird thing is because I want to use it in the following matter:

```
>>> from sympy import product
>>> product(prime(n), (n, 1, 7))
```

I understand there are things like `primerange` that could produce similar results, but I'm not interested in those things. I need a more general solution that allows me to resolve `prime(n)` to the nth prime number if `n` is a non-negative integer and to `prime(n)` otherwise.

**Comment by GarkGarcia** [comment]
See https://github.com/mathics/Mathics/pull/821 for further details.

**Comment by oscarbenjamin** [comment]
There probably should be a class for this. It's not hard to do:
```julia
In [3]: class Prime(Function): 
   ...:     @classmethod 
   ...:     def eval(cls, n): 
   ...:         if n.is_Integer: 
   ...:             return prime(n) 

In [4]: Prime(3)                                                                                                                                              
Out[4]: 5

In [5]: Prime(n)                                                                                                                                              
Out[5]: Prime(n)
```
Perhaps a bit more validation could be used.

**Comment by GarkGarcia** [comment]
> There probably should be a class for this. It's not hard to do:
> 
> ```julia
> In [3]: class Prime(Function): 
>    ...:     @classmethod 
>    ...:     def eval(cls, n): 
>    ...:         if n.is_Integer: 
>    ...:             return prime(n) 
> 
> In [4]: Prime(3)                                                                                                                                              
> Out[4]: 5
> 
> In [5]: Prime(n)                                                                                                                                              
> Out[5]: Prime(n)
> ```
> 
> Perhaps a bit more validation could be used.

Thanks! Howcould I make it so that `sympy.product` can appropriately replace `n` (as in the following example)?

```
>>> import sympy
>>> sympy.product(Prime(n), (n, 0, 3))
>>> 30
```

**Comment by oscarbenjamin** [comment]
If the limits are not symbolic then you can use doit to evaluate the product explicitly:
```julia
In [7]: product(Prime(n), (n, 1, 3)).doit()                                                                                                                   
Out[7]: 30
```
Note that `prime(0)` gives an error.

**Comment by GarkGarcia** [comment]
> If the limits are not symbolic then you can use doit to evaluate the product explicitly:
> 
> ```julia
> In [7]: product(Prime(n), (n, 1, 3)).doit()                                                                                                                   
> Out[7]: 30
> ```
> 
> Note that `prime(0)` gives an error

Thanks again. Is there a way for me to retrieve `n` from `Prime(n)`?

**Comment by oscarbenjamin** [comment]
You can use
```julia
In [10]: Prime(n).args                                                                                                                                        
Out[10]: (n,)
```

**Comment by GarkGarcia** [comment]
@oscarbenjamin Thank you very much for your help!

**Comment by asmeurer** [comment]
Should we make prime() work symbolically? Are there symbolic manipulations that can be done with it other than evaluation on explicit integers?

**Comment by ehren** [comment]
Apparently other CASs support `Product(1/(1 - prime(n)**-s), (n, 1, oo)).doit()` or `zeta(s).rewrite(Product)`. I suppose the product evaluation is just special casing.

**Comment by oscarbenjamin** [comment]
We probably do want to have a symbolic nth prime function. I don't know how `prime` is currently used but making it `Basic` as I showed above will slow it down a bit so it might be better to have both a symbolic and a non-symbolic function.

**Comment by GarkGarcia** [comment]
> I don't know how `prime` is currently used but making it `Basic` as I showed above will slow it down a bit so it might be better to have both a symbolic and a non-symbolic function.

Seems quite reasonable.

**Comment by sylee957** [comment]
There are some symbolic examples of symbolic computation of `prime(n)` in mathematica
See the section *Symbolic Manipulation*
https://reference.wolfram.com/language/ref/Prime.html

**Comment by asmeurer** [comment]
This is related to this issue https://github.com/sympy/sympy/issues/16244
