### ISSUE TITLE
simplifications on combined (in)equalities

### ISSUE THREAD

**Issue by coproc** [sympy/sympy#20080]
`simplify` can do a few simplifications on combined (in)equalities, but expressions with `Or` seem to be preferred and many obvious simplifications are not done (see the expressions with `# would expect ...`):
```python
>>> from sympy import *
>>> x = Symbol('x', real=True)
>>> Or(x > 0, x <= 0)
True
>>> And(x > 0, x <= 0)
False
>>> Or(x >= 0, x <= 0)
(x >= 0) | (x <= 0)
>>> simplify((x >= 0) | (x <= 0))
True
>>> simplify((x >= 0) | (x <= 1)) # would expect 'True'
(x >= 0) | (x <= 1)
>>> simplify((x > 0) & (x < 0)) # would expect 'False'
(x > 0) & (x < 0)
>>> simplify((x <= 0) | (x <= 1))
x <= 1
>>> simplify((x <= 0) & (x <= 1)) # would expect 'x <= 0'
(x <= 0) & (x <= 1)
>>> simplify((x >= 0) & (x <= 0)) # would expect 'Eq(x, 0)'
(x >= 0) & (x <= 0)
>>> simplify(x**2 >= 0)
True
>>> simplify(x**2 < 0)
False
>>> simplify(x**2 <= 0) # would expect 'Eq(x, 0)'
x**2 <= 0
>>> simplify(x**2 - x >= 0) # would expect '(x <= 0) | (x >= 1)'
x**2 - x >= 0
>>> 0 <= x <= 1 # would expect '(x >= 0) & (x <= 1)'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\sympy\core\relational.py", line 384, in __nonzero__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational
>>> Eq(x, 0) | (x > 0)
Eq(x, 0) | (x > 0)
>>> simplify(Eq(x, 0) | (x > 0))
x >= 0
>>> simplify(x**2 + 2*x + 1 >= 0) # would expect 'True'
x**2 + 2*x >= -1
>>> simplify(factor(x**2 + 2*x + 1) >= 0)
True
```

**Comment by coproc** [comment]
I have just stumbled upon this paper on simplifying such expressions:
(
> Simplification of quantifier-free formulae over ordered fields. Journal of Symbolic Computation, 24(2):209-231, August 1997

which can be downloaded freely. Its algorithms are mostly implemented in the package [Redlog](http://redlog.eu/) of the computer algebra system [Reduce](http://www.reduce-algebra.com).

**Comment by ruan1998** [comment]
I also meet the same problems as you can see below.
------------------------------------------------------------
>>> vi, vk = sym.symbols('v_i, v_k', positive=True)
>>> sym.simplify(sym.Ne(vi, vk) & (vi > vk)) # I only expect to get 𝑣𝑖 > 𝑣𝑘
𝑣𝑖 > 𝑣𝑘 ∧ 𝑣𝑖 ≠ 𝑣𝑘
