### ISSUE TITLE
SympifyError from risch integrate

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#20155]
This integral leads to an exception:
```python
>>> from sympy import *
>>> x = Symbol('x')
>>> I = Integral(x**2*exp(x*(-x/2 + I)) + x**2*exp(-x*(x/2 + I)) - I*exp(x*(-x/2 + I))*sin(x) + I*exp(-x*(x/2 + I))*sin(x), x)/2
>>> I.doit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/core/operations.py", line 408, in doit
    terms = [term.doit(**hints) for term in self.args]
  File "/Users/enojb/current/sympy/sympy/sympy/core/operations.py", line 408, in <listcomp>
    terms = [term.doit(**hints) for term in self.args]
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 593, in doit
    antideriv = self._eval_integral(
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/integrals.py", line 929, in _eval_integral
    result, i = risch_integrate(f, x, separate_integral=True,
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/risch.py", line 1751, in risch_integrate
    ans, i, b = integrate_hyperexponential(fa, fd, DE, conds=conds)
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/risch.py", line 1518, in integrate_hyperexponential
    i = p - (qd*derivation(qa, DE) - qa*derivation(qd, DE)).as_expr()/\
  File "/Users/enojb/current/sympy/sympy/sympy/integrals/risch.py", line 893, in derivation
    r += (d.as_expr()*pv.diff(v).as_expr()).as_poly(t)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 64, in wrapper
    g = _sympify(g)
  File "/Users/enojb/current/sympy/sympy/sympy/core/sympify.py", line 498, in _sympify
    return sympify(a, strict=True)
  File "/Users/enojb/current/sympy/sympy/sympy/core/sympify.py", line 357, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: None
```
The `None` comes from `as_poly` because the expression in question is not a valid polynomial:
```
> /Users/enojb/current/sympy/sympy/sympy/integrals/risch.py(893)derivation()
    891             r += d.as_expr()*pv.diff(v)
    892         else:
--> 893             r += (d.as_expr()*pv.diff(v).as_expr()).as_poly(t)
    894 
    895     if basic:

ipdb> p (d.as_expr()*pv.diff(v).as_expr())                                                                                                     
(-_t1**2*_t0 - _t0)/_t1
ipdb> p t                                                                                                                                      
_t1
ipdb> p (d.as_expr()*pv.diff(v).as_expr()).as_poly(t)                                                                                          
None
```
I guess there is a bug leading up to this that results in a non-polynomial expression at this point.

**Comment by jksuom** [comment]
`integrate_hyperexponential` deals with Laurent polynomials while `derivation` can only handle regular polynomials. It is probably best to compute the derivative of the quotient `qa/qd` by using its expression form `ret`:
```
--- a/sympy/integrals/risch.py
+++ b/sympy/integrals/risch.py
@@ -1514,9 +1514,8 @@ def integrate_hyperexponential(a, d, DE, z=None, conds='piecewise'):
         ret += qas/qds
 
     if not b:
-        i = p - (qd*derivation(qa, DE) - qa*derivation(qd, DE)).as_expr()/\
-            (qd**2).as_expr()
-        i = NonElementaryIntegral(cancel(i).subs(s), DE.x)
+        i = p.subs(s) - ret.diff(DE.x)
+        i = NonElementaryIntegral(cancel(i), DE.x)
     return (ret, i, b)
```
The resulting `NonElementaryIntegral` cannot currently be computed  by SymPy. (It looks like the error function could be used. Maybe that could be added to `manualintegrate`.) In order to avoid the infinite loop (or what it looks like) in `heurisch`, something like this should be added to make `heurisch=False` effective:
```
 --- a/sympy/integrals/integrals.py
+++ b/sympy/integrals/integrals.py
@@ -941,7 +941,8 @@ def _eval_integral(self, f, x, meijerg=None, risch=None, manual=None,
                         from sympy.integrals.risch import NonElementaryIntegral
                         return NonElementaryIntegral(f, x).doit(risch=False)
                     else:
-                        return result + i.doit(risch=False)
+                        return result + i.doit(meijerg=meijerg, risch=False,
+                                   manual=manual, heurisch=heurisch)
                 else:
                     return result
```

**Comment by oscarbenjamin** [comment]
Sympy can compute this integral with a bit of help:
```julia
In [18]: integral = Integral(x**2*exp(x*(-x/2 + I)) + x**2*exp(-x*(x/2 + I)) - I*exp(x*(-x/2 + I))*sin(x) + I*exp(-x*(x/2 + I))*sin(x), x)/2   

In [19]: integral                                                                                                                              
Out[19]: 
⌠                                                                                     
⎮ ⎛      ⎛  x    ⎞          ⎛x    ⎞        ⎛  x    ⎞                ⎛x    ⎞       ⎞   
⎮ ⎜    x⋅⎜- ─ + ⅈ⎟       -x⋅⎜─ + ⅈ⎟      x⋅⎜- ─ + ⅈ⎟             -x⋅⎜─ + ⅈ⎟       ⎟   
⎮ ⎜ 2    ⎝  2    ⎠    2     ⎝2    ⎠        ⎝  2    ⎠                ⎝2    ⎠       ⎟   
⎮ ⎝x ⋅ℯ            + x ⋅ℯ           - ⅈ⋅ℯ           ⋅sin(x) + ⅈ⋅ℯ          ⋅sin(x)⎠ dx
⌡                                                                                     
──────────────────────────────────────────────────────────────────────────────────────
                                          2                                           

In [20]: powsimp(factor_terms(integral.rewrite(exp).expand()), deep=True)                                                                      
Out[20]: 
⌠                     ⌠                     ⌠            ⌠                    ⌠                 
⎮        2            ⎮        2            ⎮    2       ⎮     2              ⎮     2           
⎮       x             ⎮       x             ⎮  -x        ⎮    x               ⎮    x            
⎮     - ── - ⅈ⋅x      ⎮     - ── + ⅈ⋅x      ⎮  ────      ⎮  - ── - 2⋅ⅈ⋅x      ⎮  - ── + 2⋅ⅈ⋅x   
⎮  2    2             ⎮  2    2             ⎮   2        ⎮    2               ⎮    2            
⎮ x ⋅ℯ           dx   ⎮ x ⋅ℯ           dx   ⎮ ℯ     dx   ⎮ ℯ             dx   ⎮ ℯ             dx
⌡                     ⌡                     ⌡            ⌡                    ⌡                 
─────────────────── + ─────────────────── + ────────── - ────────────────── - ──────────────────
         2                     2                2                4                    4         

In [21]: _.doit()                                                                                                                              
Out[21]: 
  ⎛     2         2 ⎞         ⎛     2         2 ⎞                                                                                 
  ⎜   -x        -x  ⎟         ⎜   -x        -x  ⎟                                                                                 
  ⎜   ────      ────⎟         ⎜   ────      ────⎟                 ⎛√2⋅x⎞          -2    ⎛√2⋅x       ⎞          -2    ⎛√2⋅x       ⎞
  ⎜    2         2  ⎟  -ⅈ⋅x   ⎜    2         2  ⎟  ⅈ⋅x   √2⋅√π⋅erf⎜────⎟   √2⋅√π⋅ℯ  ⋅erf⎜──── - √2⋅ⅈ⎟   √2⋅√π⋅ℯ  ⋅erf⎜──── + √2⋅ⅈ⎟
  ⎝x⋅ℯ     - ⅈ⋅ℯ    ⎠⋅ℯ       ⎝x⋅ℯ     + ⅈ⋅ℯ    ⎠⋅ℯ               ⎝ 2  ⎠                ⎝ 2         ⎠                ⎝ 2         ⎠
- ───────────────────────── - ──────────────────────── + ─────────────── - ────────────────────────── - ──────────────────────────
              2                          2                      4                      8                            8   
```
I often see cases like this that risch/heurisch struggle with (either failing or being slow) when actually the individual terms of the Add can be integrated easily. I don't know if there is a reason for not splitting an integral of an Add and integrating each term but maybe it could be considered as a preliminary step.

**Comment by samithkavishke** [comment]
May I try this issue?

**Comment by oscarbenjamin** [comment]
Yes

**Comment by asmeurer** [comment]
The integrand here is elementary and has the same problem. https://github.com/sympy/sympy/issues/24838

**Comment by asmeurer** [comment]
The code in Risch is supposed to already handle Laurent polynomials (doing it all manually because Poly doesn't support them directly https://github.com/sympy/sympy/issues/5131). Apparently this particular code path isn't doing it correctly. 

Another thing: `as_poly` should not be returning `None`. It should raise an exception if it fails.
