### ISSUE TITLE
Integral of rational function with floats fails

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#20226]
```python
>>> Integral(-0.000425170068027211*x/(0.000212585034013605*x**2 - 1.0), x).doit()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/integrals/integrals.py", line 576, in doit
    function, xab[0], **eval_kwargs)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/integrals/integrals.py", line 907, in _eval_integral
    conds=conds)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/integrals/risch.py", line 1760, in risch_integrate
    ans = integrate(fa.as_expr()/fd.as_expr(), DE.x, risch=False)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/integrals/integrals.py", line 1522, in integrate
    return integral.doit(**doit_flags)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/integrals/integrals.py", line 576, in doit
    function, xab[0], **eval_kwargs)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/integrals/integrals.py", line 992, in _eval_integral
    parts.append(coeff * ratint(g, x))
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/integrals/rationaltools.py", line 102, in ratint
    R = log_to_real(h, q, x, t)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/integrals/rationaltools.py", line 351, in log_to_real
    R_u = roots(R, filter='R')
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/polys/polyroots.py", line 987, in roots
    for r in f.nroots():
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/polys/polytools.py", line 3596, in nroots
    n, maxsteps))
NoConvergence: convergence to root failed; try n < 15 or maxsteps > 50
```

**Comment by pjrenzov** [comment]
Hello @oscarbenjamin, I am new to open source community and would like to work on this issue. Please guide me where should I start working on  it.

**Comment by oscarbenjamin** [comment]
The underlying issue is with this Poly
```
p = Poly(-2.36284964398621e-20*x**4 + 2.22296894506223e-16*x**3 - 7.84263443817954e-13*x**2 + 1.22972507990655e-9*x - 7.23078346985052e-7, x, domain='RR')
```
Here `nroots `fails by default:
```
In [59]: p.nroots()
---------------------------------------------------------------------------
NoConvergence 
```
We can get something if we use lower precision and more steps:
```
In [60]: p.nroots(10, 500)
Out[60]: [2346.01543, 2358.005469, 2351.989551 - 5.99499007⋅ⅈ, 2351.989551 + 5.99499007⋅ⅈ]
```
However this is wrong because it gives two real roots and a conjugate pair. We can compute the roots exactly:
```
In [63]: r1, r2, r3, r4 = roots(Poly(nsimplify(p)))

In [64]: [r1.n(), r2.n(), r3.n(), r4.n()]
Out[64]: 
[2351.66521145239 - 0.334905062376065⋅ⅈ, 2351.66521145239 + 0.334905062376065⋅ⅈ, 2352.33478854761 - 0.334671864216464⋅ⅈ, 2352.33478854761 + 0.33467186421646
4⋅ⅈ]
```
Perhaps the code that attempts to determine how many roots are real has failed.

**Comment by oscarbenjamin** [comment]
The problem I think is that this polynomial is ill conditioned and has a discriminant that is close to zero:
```python
In [42]: p = -2.36284964398621e-20*x**4 + 2.22296894506223e-16*x**3 - 7.84263443817954e-13*x**2 + 1.22972507990655e-9*x - 7.23078346985052e-7

In [43]: p = nsimplify(p + 1e-20)

In [44]: p
Out[44]: 
                            4                                   3                               2                                                      
           236284964398621⋅x                   222296894506223⋅x               392131721908977⋅x            24594501598131⋅x         361539173492521   
- ─────────────────────────────────── + ─────────────────────────────── - ─────────────────────────── + ─────────────────────── - ─────────────────────
  10000000000000000000000000000000000   1000000000000000000000000000000   500000000000000000000000000   20000000000000000000000   500000000000000000000

In [45]: [r.evalf() for r in roots(p, x, multiple=True)]
Out[45]: [2351.99995842052 - 0.792854565255031⋅ⅈ, 2351.99995842052 + 0.792854565255031⋅ⅈ, 2352.79289619662, 2351.20718696236]

In [46]: p = nsimplify(p - 1e-20)

In [47]: [r.evalf() for r in roots(p, x, multiple=True)]
Out[47]: 
[2351.66521145239 + 0.334905062376065⋅ⅈ, 2352.33478854761 + 0.334671864216464⋅ⅈ, 2351.66521145239 - 0.334905062376065⋅ⅈ, 2352.33478854761 - 0.33467186421646
4⋅ⅈ]

In [50]: discriminant(p + 1e-20)
Out[50]: -2.29035200265372e-117

In [51]: discriminant(p - 1e-20)
Out[51]: 4.66633288661697e-117
```
