### ISSUE TITLE
Easy creation of parameterized/special/named matrices

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#20261]
It would be rather convenient if there existed methods to easily create matrices with special structure, e.g., Toeplitz, Vandermonde, and Moore matrices. Not sure where these should go though. `matrices.expressions`?

For example:

``` 
>>> vandermonde([x, y, z], 4)

[ 1  x  x**2 x**3]
[ 1  y  y**2 y**3]
[ 1  z  z**2 z**3]

>>> moore([x, y, z], q, 3)

[ x  x**q x**q**2]
[ y  y**q y**q**2]
[ z  z**q z**q**2]

>>> toeplitz([x, y, z], symmetric=True)

[ x  y  z ]
[ y  x  y ]
[ z  y  x ]
```
Where the first argument ideally is any iterable.

Possibly one should use the capitalized/class version of them and only return the above explicit matrices when calling `as_explicit`. That would require finding a good representation of them though.

**Comment by oscarbenjamin** [comment]
It would make sense for these to go into matrices.expressions if the idea is for them to be represented symbolically rather than explicitly.

Is it possibly to do anything clever with these without converting them to explicit matrices?

**Comment by asmeurer** [comment]
We have FunctionMatrix. This could build off of that. 

I think you can compute things on matrices whose entries are defined by a function. For example, if A_ij = f(i, j) and B_ij = g(i, j), then (A + B)_ij = f(i, j) + g(i, j), and (A*B)_ij = sum_k f(i, k)*g(k, j). It doesn't look like FunctionMatrix currently supports this, so it may need some refactoring. 

Some named matrices also have special properties that could be hard-coded into the class.

**Comment by oscargus** [comment]
> Is it possibly to do anything clever with these without converting them to explicit matrices?

Yes and no. Some expressions, such as inverting and computing the determinant can be simpler. But in general, the matrix is not well defined unless explicit (as opposed to e.g. the DFT matrix, where `DFT(4)` is enough to define it).

I primarily see the usefulness in allowing easy creation of explicit matrices, so I agree `expressions` is doubtful, but it was still the closest with some special matrices etc. Any additional benefits such that simpler determinant expressions or faster inversion is less important for me, but can of course be beneficial for others so, if possible, one should implement it in a way that makes it possible to implement it.

Maybe one way is to subclass from `ImmutableMatrix` so that as long as nothing is changed in the matrix it is still a `ToeplitzMatrix`, `VandermondeMatrix` and `MooreMatrix`, but as soon as it goes mutable, nothing special holds (but that could be how `MatExpr` is meant to work?).

**Comment by sylee957** [comment]
MatrixExpr would be best choice to implement special matrices because it can be the most sparse representation of the matrix and also it can add the code generation capability.
But I'd try to watch out for adding many keywords like `symmetric` that trivializes things, and try to pick the most generalizable representation.

**Comment by oscargus** [comment]
One may consider other forms as well, such as providing columns and optionally rows. So only providing one input will give the symmetric form.

```
ToeplitzMatrix(cols, rows=[]/None)
```

This is similar to Mathematica (and Matlab, although it it described differently there). In Mathematica one can also provide a number and one then gets a matrix with successive integers (not sure if it makes sense to provide that version symbolically, but should be feasible to implement if nothing else). So `ToeplitzMatrix(4) == ToeplitzMatrix(range(1, 4+1))`.

I think it makes sense, as you say, to use `MatExpr` as many of these matrices exists in other programs/languages so one would benefit from that in code generation etc.

**Comment by sylee957** [comment]
One of the other commonly used notation for Toeplitz matrix is triangular Toeplitz matrix, However, I think that it is no problem because 
One of the reason I don't like about Mathematica or MATLAB notation is that we can't forget about about whether the first column and row specification supplied are equal or not, and I have thought of specifying diagonal elements separately and begin row and column specification from index 1
- `Toeplitz(d, (c1, ...), (r1, ...)` 

rather than from index 0
- `Toeplitz((c0, c1, ...), (r0, r1, ...)` 

because we may be able to forget about whether the diagonal element is valid or not.
Code generation is not a problem because we can always translate the new notation, however, some people may be more familiar with inputs of matlab or mathematica.

**Comment by sylee957** [comment]
I see matlab and mathematica ignores the first row element if it is not valid.

**Comment by oscargus** [comment]
Yes, either one does it like that, ignoring, or one assumes that the first element in the column matrix is for the second column. Specifying it separately will lead to more complicated calls, especially for the symmetric case, so personally not in favor of that.

**Comment by oscargus** [comment]
It seems like there is a `_eval_determinant` that can be used, but no `.det()` method for `MatExpr`. Is there a particular reason for that? I mean, one can do `det(MatExpr)`, but not `MatExpr.det()`.

There is no corresponding `_eval_eigenvals`, right? Also, as the only way to evaluate eigenvalues is to call `.eigenvals` it seems like it is not really possible to do this on `MatExpr`?

A benefit of some of these matrices is that computing eigenvalues and/or determinants is quite simple. For example, for all `DFT` and `IDFT` matrices, the eigenvalues are +/-1 and +/- i. Hence, it is also simple to compute the determinant.

**Comment by sylee957** [comment]
Unlike determinant, I had an idea that such problem would be solved in most generic form if we have sympy framework for multisets. It can be used to represent eigenvalues of matrix, roots of polynomial, and prime factorization of integers in same idioms.

**Comment by oscarbenjamin** [comment]
Since we can use `rootof` to represent numbered roots from a polynomial we should be able to extend that to something like `eigenvalueof` which would essentially represent `RootOf(CharPoly(M), n)`.

**Comment by oscargus** [comment]
I think there are two different problems (if I am not interpreting you incorrectly). One is to be able to compute this for any matrix, another is to have special support for cases where the computations are much easier than the general case.

Hence, although one can do `.as_explicit().eigenvals()` it does not really make sense when there are closed form expressions for the eigenvalues, as for the DFT matrix, see #20275.

I also believe that it would make sense to add (at least) `.det()` to `MatExpr` and `MatrixSymbol` since there is a symbolic representation of it (the same as `det(MatrixSymbol` etc).

Here is an example of why:

```
In [51]: DFT(4).as_explicit().det()
Out[51]: I

In [52]: det(DFT(4).as_explicit())
Out[52]: I

In [53]: det(DFT(4))
Out[53]: Determinant(DFT(4))

In [54]: DFT(4).det()
Traceback (most recent call last):

  File "<ipython-input-54-3de2b0d19a7c>", line 1, in <module>
    DFT(4).det()

AttributeError: 'DFT' object has no attribute 'det'

In [55]: A = MatrixSymbol('A',3,3)

In [56]: det(A)
Out[56]: Determinant(A)

In [57]: A.det()
Traceback (most recent call last):

  File "<ipython-input-57-0c79b70f8c8e>", line 1, in <module>
    A.det()

AttributeError: 'MatrixSymbol' object has no attribute 'det'
```
