### ISSUE TITLE
Testsuite failure in test_as_dummy only with --enhance-asserts

### ISSUE THREAD

**Issue by ehren** [sympy/sympy#20268]
```
$ ./bin/test test_basic 
=========================================================================== test process starts ============================================================================
executable:         /Users/ehren/Documents/sympydev/env-3.8-1/bin/python  (3.8.5-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              None
random seed:        67006369
hash randomization: on (PYTHONHASHSEED=4022997947)

sympy/core/tests/test_basic.py[22] ......................                                                                                                               [OK]

================================================================ tests finished: 22 passed, in 0.09 seconds ================================================================
```

but

```
$ ./bin/test test_basic --enhance-asserts
=========================================================================== test process starts ============================================================================
executable:         /Users/ehren/Documents/sympydev/env-3.8-1/bin/python  (3.8.5-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              None
random seed:        80676375
hash randomization: on (PYTHONHASHSEED=1839426324)

sympy/core/tests/test_basic.py[22] ...................E..                                                                                                             [FAIL]

____________________________________________________________________________________________________________________________________________________________________________
_______________________________________________________________ sympy/core/tests/test_basic.py:test_as_dummy _______________________________________________________________
Traceback (most recent call last):
  File "/Users/ehren/Documents/sympydev/esym20/sympy/core/tests/test_basic.py", line 281, in test_as_dummy
    assert Lambda(x, x + _0).as_dummy() == Lambda(_1, _0 + _1)
  File "/Users/ehren/Documents/sympydev/esym20/sympy/core/function.py", line 1995, in __new__
    cls._check_signature(sig)
  File "/Users/ehren/Documents/sympydev/esym20/sympy/core/function.py", line 2021, in _check_signature
    rcheck(sig)
  File "/Users/ehren/Documents/sympydev/esym20/sympy/core/function.py", line 2015, in rcheck
    raise BadSignatureError("Lambda signature should be only tuples"
sympy.core.function.BadSignatureError: Lambda signature should be only tuples and symbols, not Lambda(_0, _0 + 1)

========================================================= tests finished: 21 passed, 1 exceptions, in 0.11 seconds =========================================================
DO *NOT* COMMIT!

```

Don't know if this is related to #20265. It works fine in an interactive session:

```
>>> from sympy import *
>>> u, v, x, y, z, _0, _1 = symbols('u v x y z _0 _1')
>>> assert Lambda(x, x + _0).as_dummy() == Lambda(_1, _0 + _1)
>>> Lambda(x, x + _0).as_dummy()
Lambda(_1, _0 + _1)
```

**Comment by oscarbenjamin** [comment]
I would use pytest rather than bin/test.
