### ISSUE TITLE
Error when computing eigenvals of DFT(5)

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#20275]
```
>>> DFT(5).as_explicit().eigenvals()
Traceback (most recent call last):

  File "<ipython-input-27-9e544e483ef5>", line 1, in <module>
    DFT(5).as_explicit().eigenvals()

  File "C:\Users\Oscar\sympy\sympy\matrices\matrices.py", line 368, in eigenvals
    return _eigenvals(self, error_when_incomplete=error_when_incomplete, **flags)

  File "C:\Users\Oscar\sympy\sympy\matrices\eigen.py", line 177, in _eigenvals
    **flags)

  File "C:\Users\Oscar\sympy\sympy\matrices\eigen.py", line 227, in _eigenvals_dict
    .format(block))

MatrixError: Could not compute eigenvalues for Matrix([[sqrt(5)/5, sqrt(5)/5, sqrt(5)/5, sqrt(5)/5, sqrt(5)/5], [sqrt(5)/5, sqrt(5)*exp(-2*I*pi/5)/5, sqrt(5)*exp(-4*I*pi/5)/5, sqrt(5)*exp(4*I*pi/5)/5, sqrt(5)*exp(2*I*pi/5)/5], [sqrt(5)/5, sqrt(5)*exp(-4*I*pi/5)/5, sqrt(5)*exp(2*I*pi/5)/5, sqrt(5)*exp(-2*I*pi/5)/5, sqrt(5)*exp(4*I*pi/5)/5], [sqrt(5)/5, sqrt(5)*exp(4*I*pi/5)/5, sqrt(5)*exp(-2*I*pi/5)/5, sqrt(5)*exp(2*I*pi/5)/5, sqrt(5)*exp(-4*I*pi/5)/5], [sqrt(5)/5, sqrt(5)*exp(2*I*pi/5)/5, sqrt(5)*exp(4*I*pi/5)/5, sqrt(5)*exp(-4*I*pi/5)/5, sqrt(5)*exp(-2*I*pi/5)/5]]). if you see this error, please report to SymPy issue tracker.
```

**Comment by oscarbenjamin** [comment]
This happens for any 5x5 matrix where the characteristic polynomial does not factor:
```julia
In [1]: M = Matrix([[0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1], [1, 0, 0, 1, 1]])                                      

In [2]: M.eigenvals()                                                                                                                          
---------------------------------------------------------------------------
MatrixError                               Traceback (most recent call last)
<ipython-input-2-1b9fc5a97195> in <module>
----> 1 M.eigenvals()

~/current/sympy/sympy/sympy/matrices/matrices.py in eigenvals(self, error_when_incomplete, **flags)
    366 
    367     def eigenvals(self, error_when_incomplete=True, **flags):
--> 368         return _eigenvals(self, error_when_incomplete=error_when_incomplete, **flags)
    369 
    370     def eigenvects(self, error_when_incomplete=True, iszerofunc=_iszero, **flags):

~/current/sympy/sympy/sympy/matrices/eigen.py in _eigenvals(M, error_when_incomplete, simplify, multiple, rational, **flags)
    173             M, error_when_incomplete=error_when_incomplete, simplify=simplify,
    174             **flags)
--> 175     return _eigenvals_dict(
    176         M, error_when_incomplete=error_when_incomplete, simplify=simplify,
    177         **flags)

~/current/sympy/sympy/sympy/matrices/eigen.py in _eigenvals_dict(M, error_when_incomplete, simplify, **flags)
    222         if error_when_incomplete:
    223             if sum(eigs.values()) != block.rows:
--> 224                 raise MatrixError(
    225                     "Could not compute eigenvalues for {}. if you see this "
    226                     "error, please report to SymPy issue tracker."

MatrixError: Could not compute eigenvalues for Matrix([[0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1], [1, 0, 0, 1, 1]]). if you see this error, please report to SymPy issue tracker.
```
I'm not sure why this needs to be reported to the issue tracker. The problem is straight-forward: Abel-Ruffini means we can not have explicit expressions for the roots and the eigenvalues code does not attempt to use `rootof`:
```julia
In [3]: M.charpoly()                                                                                                                           
Out[3]: PurePoly(lambda**5 - lambda**4 - lambda**3 - 1, lambda, domain='ZZ')

In [4]: rootof(M.charpoly(), 0)                                                                                                                
Out[4]: 
       ⎛ 5    4    3       ⎞
CRootOf⎝λ  - λ  - λ  - 1, 0⎠
```
At the moment `rootof` only works over `QQ` so it still wouldn't work for the DFT example but if the eigenvalues code was made to use rootof then rootof could be improved to expand the capability for computing eigenvalues.

**Comment by sylee957** [comment]
There is a closed form eigenvalues for DFT matrix of size 5, which I used Mathematica to compute
![image](https://user-images.githubusercontent.com/34944973/96349675-052b9280-10ec-11eb-9fe9-b5af6082a326.png)
I think that someone should clarify that a closed form solution exists for eigenvalues of DFT matrix in any size. I see wolfram sometimes gives slow results or unevaluated root of formulas.

**Comment by oscarbenjamin** [comment]
There seems to be a closed form in #20279

**Comment by sylee957** [comment]
Okay I didn't notice that the the solution is easier than what wolfram gives.
