### ISSUE TITLE
Why use rever for the release script?

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#20320]
The release script has just failed with:
```
$ ./release.sh 1.7 1.7rc1
...
activity-error:build_docs:activity failed with execption:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/rever/activity.xsh", line 83, in __call__
    self.func(*args, **kwargs)
  File "rever.xsh", line 121, in build_docs
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 22304, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured="hiddenobject")
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 22267, in run_subproc
    command.end()
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 15593, in end
    self._end(tee_output=tee_output)
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 15612, in _end
    self._raise_subproc_error()
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 15738, in _raise_subproc_error
    raise subprocess.CalledProcessError(rtn, spec.args, output=self.output)
subprocess.CalledProcessError: Command '['cp', 'sympy-1.7.rc1.pdf', '../../../dist/sympy-docs-pdf-1.7.rc1.pdf']' returned non-zero exit status 1.
rewinding to 9e7ae9413d0dbb665aaafacff03c3808f165b2db
```
Somewhere the version is being changed from 1.7rc1 to 1.7.rc1. I know this is a small problem and that it should be easy to fix but somehow it seems quite difficult to fix and the problem is basically the fact that we are using rever for the release script which overcomplicates simple things and makes it difficult to debug anything.

Running rever directly I get:
```
$ rever -a build_docs 1.7rc1
rever.xsh:8:import os
rever.xsh:9:import sys
rever.xsh:10:import unicodedata
rever.xsh:11:from collections import defaultdict, OrderedDict
rever.xsh:12:from collections.abc import Mapping
rever.xsh:13:from getpass import getpass
rever.xsh:14:from contextlib import contextmanager
rever.xsh:15:import json
rever.xsh:16:import glob
rever.xsh:17:import stat
rever.xsh:18:import configparser
rever.xsh:19:import time
rever.xsh:21:import requests
rever.xsh:22:from requests.auth import HTTPBasicAuth
rever.xsh:23:from requests_oauthlib import OAuth2
rever.xsh:25:from rever.activity import activity
rever.xsh:26:from rever.conda import run_in_conda_env
rever.xsh:28:cd ..
Activity '_version' has already been completed!
activity-start:build_docs:starting activity build_docs
The following xontribs are enabled but not installed: 
   xonda
To install them run 
    xpip install xonda
activity-error:build_docs:activity failed with execption:
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/rever/activity.xsh", line 83, in __call__
    self.func(*args, **kwargs)
  File "rever.xsh", line 100, in build_docs
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/rever/conda.xsh", line 29, in run_in_conda_env
    if env_exists(envname):
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/rever/conda.xsh", line 8, in env_exists
    envs = json.loads($(conda env list --json))["envs"]
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/built_ins.py", line 977, in subproc_captured_stdout
    return run_subproc(cmds, captured="stdout")
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/built_ins.py", line 961, in run_subproc
    command.end()
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/proc.py", line 2117, in end
    self._end(tee_output=tee_output)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/proc.py", line 2136, in _end
    self._raise_subproc_error()
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/proc.py", line 2262, in _raise_subproc_error
    raise subprocess.CalledProcessError(rtn, spec.args, output=self.output)
subprocess.CalledProcessError: Command '['conda', 'env', 'list', '--json']' returned non-zero exit status 1.
rewinding to 9e7ae9413d0dbb665aaafacff03c3808f165b2db
```
The command that fails is `conda env list --json` which works fine if I run it directly:
```
$ conda env list --json
{
  "envs": [
    "/Users/enojb/opt/miniconda3",
    "/Users/enojb/opt/miniconda3/envs/test-environment"
  ]
}
```
Over the last few releases I have found that messing around with rever has wasted a lot of time. Using rever makes everything run slowly and makes debugging simple things very tedious. Obviously rever is supposed to be a tool that helps in some way but from my experience so far I don't see any benefit from using it. It would be much simpler, faster, and easier to have a normal Python script that performs the checks and issues the release.

The fact that the release script always pulls from the release branch in github makes for a very slow turnaround time to fix small things. What that means is that it is much better if I can quickly test all of the release steps outside of the release script first, fix everything and then run the release script at the point when it should be expected to work first time. The structure of the rever file makes it difficult to run those steps independently because it insists on running the entire sympy test suite as a dependency. That's why I have moved some code out of the rever.xsh file and into separate .py files that can be run directly.

Really though I don't see what the point is in having anything in the rever.xsh file. I'm tempted to move everything out so that there are just a few plain Python scripts for each step of the release along with a master script that runs them all.

What am I missing here? Presumably rever has some benefits to rever in general but I think that either they don't apply to sympy or we're just not using it in the way that is intended.

**Comment by oscarbenjamin** [comment]
Rerunning the release script it fails with:
```console
$ ./release.sh 1.7 1.7rc1
...
activity-start:wheel:starting activity wheel
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 14887, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 14680, in proxy_two
    return f(args, stdin)
  File "/opt/conda/lib/python3.6/site-packages/xontrib/xonda.xsh", line 171, in _xonda
    @$(which -s conda) @(args)
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 22304, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured="hiddenobject")
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 22267, in run_subproc
    command.end()
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 15593, in end
    self._end(tee_output=tee_output)
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 15612, in _end
    self._raise_subproc_error()
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 15738, in _raise_subproc_error
    raise subprocess.CalledProcessError(rtn, spec.args, output=self.output)
subprocess.CalledProcessError: Command '['env', 'list', '--json']' returned non-zero exit status 127.
activity-error:wheel:activity failed with execption:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/rever/activity.xsh", line 83, in __call__
    self.func(*args, **kwargs)
  File "rever.xsh", line 93, in wheel
  File "/opt/conda/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.6/site-packages/rever/conda.xsh", line 29, in run_in_conda_env
    if env_exists(envname):
  File "/opt/conda/lib/python3.6/site-packages/rever/conda.xsh", line 8, in env_exists
    envs = json.loads($(conda env list --json))["envs"]
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 22278, in subproc_captured_stdout
    return run_subproc(cmds, captured="stdout")
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 22262, in run_subproc
    command.end()
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 15593, in end
    self._end(tee_output=tee_output)
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 15612, in _end
    self._raise_subproc_error()
  File "/opt/conda/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 15738, in _raise_subproc_error
    raise subprocess.CalledProcessError(rtn, spec.args, output=self.output)
subprocess.CalledProcessError: Command '['conda', 'env', 'list', '--json']' returned non-zero exit status 1.
rewinding to 9e7ae9413d0dbb665aaafacff03c3808f165b2db
```
I'm not sure whether that's just a bug in `rever` (since the exception comes from `run_in_conda_env`).

**Comment by asmeurer** [comment]
I believe the issue you are seeing should be fixed by updating to the latest version of rever. 

I don't feel strongly about using rever. I used rever at the time because it was a new library developed by my colleague @scopatz and it seemed like a good approach for automating releases. But we don't actually use much of the built-in behavior of rever, since we have to do most things slightly different. 

My feeling about it is that whoever is doing the releases should have full autonomy in doing whatever they want with the release scripts. Since you are the one doing the releases, if you want to move away from rever, that's fine with me. I would mainly say for the release automation to try to avoid regressions in terms of the sorts of things that it does and tests, and to make it so that however it works, that it can be easily run by anybody.

**Comment by oscarbenjamin** [comment]
I just updated to re-ver-0.4.7 and reran the `build_docs` command locally and now I get:
```console
$ rever -a build_docs 1.7rc1
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/bin/rever", line 2, in <module>
    from rever.main import main
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/rever/main.xsh", line 11, in <module>
    from rever import environ
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/rever/environ.xsh", line 146, in <module>
    'DAG': (default_dag(None), always_true, None, str,
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/rever/environ.xsh", line 63, in default_dag
    from rever.activities.appimage import AppImage
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/imphooks.py", line 123, in get_code
    code = execer.compile(src, glbs=ctx, locs=ctx)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/execer.py", line 235, in _parse_ctx_free
    raise original_error from None
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/execer.py", line 220, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/parsers/base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/parsers/base.py", line 3399, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/parsers/base.py", line 676, in _parse_error
    raise err
SyntaxError: /Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/rever/activities/appimage.xsh:35:19: ('code: run',)
            docker run -v @(path):/dir --rm -e GID=@$(id -g) -e UID=@$(id -u) python:3.7-slim-buster bash -c @('addgroup --gid $GID user && adduser --disabled-password --gecos "" --uid $UID --gid $GID user && apt update && apt install -y git file gpg && pip install git+https://github.com/niess/python-appimage && chown -R user:user /dir && su - user -c "cd /dir && python -m python_appimage build app ./appimage"')
                   ^
```

**Comment by scopatz** [comment]
Yeah, I think the idea for rever is that it provides a well-defined way of doing releases for a project. The goals are to mostly automate the process and check that someone has the ability to do a release before starting a release. This let's releases be consistent across contributors and platforms.

Rever (via @asmeurer) added a few capabilities that I believe only SymPy uses.  I am happy to help here however I can!

**Comment by scopatz** [comment]
I think that there is a fix for this issue on master.  I'll do another rever release now.

**Comment by scopatz** [comment]
rever v0.4.8 should be out now, if you want to try that

**Comment by oscarbenjamin** [comment]
Thanks. I just upgraded to 0.4.8 but I still get the same:
```console
$ rever -a build_docs 1.7rc1
Traceback (most recent call last):
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/bin/rever", line 2, in <module>
    from rever.main import main
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/rever/main.xsh", line 11, in <module>
    from rever import environ
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/rever/environ.xsh", line 146, in <module>
    'DAG': (default_dag(None), always_true, None, str,
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/rever/environ.xsh", line 63, in default_dag
    from rever.activities.appimage import AppImage
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/imphooks.py", line 123, in get_code
    code = execer.compile(src, glbs=ctx, locs=ctx)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/execer.py", line 135, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/execer.py", line 95, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/execer.py", line 235, in _parse_ctx_free
    raise original_error from None
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/execer.py", line 220, in _parse_ctx_free
    debug_level=(self.debug_level > 2),
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/parsers/base.py", line 543, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 1203, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/ply/ply/yacc.py", line 194, in call_errorfunc
    r = errorfunc(token)
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/parsers/base.py", line 3399, in p_error
    self._parse_error(msg, self.currloc(lineno=p.lineno, column=p.lexpos))
  File "/Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/xonsh/parsers/base.py", line 676, in _parse_error
    raise err
SyntaxError: /Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/rever/activities/appimage.xsh:35:19: ('code: run',)
            docker run -v @(path):/dir --rm -e GID=@$(id -g) -e UID=@$(id -u) python:3.7-slim-buster bash -c @(f'addgroup --gid $GID user && adduser --disabled-password --gecos "" --uid $UID --gid $GID user && apt update && apt install -y git file gpg && pip install git+https://github.com/niess/python-appimage && chown -R user:user /dir && su - user -c "cd /dir && python -m python_appimage build app {" ".join(python_ver)} {self.appimage_descr_dir}"')
                   ^
```

**Comment by oscarbenjamin** [comment]
I'm also not sure how to upgrade rever within the docker file that runs the release script.

I guess I should add a conda update command maybe here:
https://github.com/sympy/sympy/blob/ab864967e71c950a15771bb6c3723636026ba876/release/pull_and_run_rever.sh#L15-L19

**Comment by scopatz** [comment]
> I'm also not sure how to upgrade rever within the docker file that runs the release script

Yeah, I think @asmeurer is more knowledgeable about this stuff that is in sympy itself.  Also it might take an hour for rever to make it onto conda-forge

**Comment by asmeurer** [comment]
I think you might have to rebuild the docker image. There are instructions in the release/README.md

**Comment by oscarbenjamin** [comment]
@scopatz What I don't quite understand is what rever is doing that is more helpful than just running the same code directly. Reading the rever docs I see references to the idea that commands are undoable etc but it doesn't look to me like the sympy release script makes use of any of that. Possibly that's because the code in sympy's rever.xsh file is carried over from a previous system that didn't provide as many features.

A major part of what makes it awkward to debug problems is that we don't run rever directly. Rather the release script runs docker which checks out the release branch from github and runs rever on that. That means that if the release script fails and I want to try to fix it then to test a change I need to merge a PR from github and then rerun the release script but each of those two steps takes around 2 hours due to the tests running on Travis and then also in the release script (inside docker locally). That gives a ~5hr turnaround for testing any possible fix before seeing whether or not it has worked.

If all steps in the release process were usually successful that would not be so bad but actually in each of the releases I have managed there have been multiple problems that needed changes and fixes so there is always a need to debug the release script. The part where rever makes this awkward is that it also limits my ability to debug in this very slow change/test cycle.

One thing that would help would be if we could make it so that running the test suite was the absolute last step in the script. The sympy test suite is very slow and it's frustrating watching it run every time knowing that the real failure will be in one of the steps afterwards.

The other thing that would help would be moving all of the non-trivial code out of the rever.xsh file into plain .py files so that it can be more easily tested and fixed independently of the main release script.

**Comment by oscarbenjamin** [comment]
I wasn't aware of xonsh before using rever and it seems pretty nifty and like something that I might want to use in some situations. There is a strong disadvantage though in using a non-standard language which is that anyone would have to learn that language in order to work on the release script. The error I get with latest rever is:
```
SyntaxError: /Users/enojb/current/sympy/release.sympy.git/37venv/lib/python3.7/site-packages/rever/activities/appimage.xsh:35:19: ('code: run',)
            docker run -v @(path):/dir --rm -e GID=@$(id -g) -e UID=@$(id -u) python:3.7-slim-buster bash -c @(f'addgroup --gid $GID user && adduser --disabled-password --gecos "" --uid $UID --gid $GID user && apt update && apt install -y git file gpg && pip install git+https://github.com/niess/python-appimage && chown -R user:user /dir && su - user -c "cd /dir && python -m python_appimage build app {" ".join(python_ver)} {self.appimage_descr_dir}"')
                   ^
```
I have no idea whether or not that is a valid complaint that the xonsh syntax is incorrect because I don't know what the definition of valid xonsh syntax is.

**Comment by asmeurer** [comment]
I agree the tests should be run last, or least last before any destructive tasks like uploading. 

The Docker thing is annoying. I don't know if there is a better way to do it. I'm not an expert in using Docker. The main reason for using Docker is twofold. One is to completely isolate the release process, and make it relatively reproducible. If we ran the script just from the local checkout, there would be a risk that something on your computer could mess up the release build somehow. For example, it's happened in the past that untracked files made their way into the release tarballs. The second reason is that some of the dependencies for building are annoying to install, and Docker makes this easy (e.g., inkscape for building the docs).

**Comment by oscarbenjamin** [comment]
I think that docker is a good tool for getting a reproducible build. What I want though is to be able to run everything quickly outside of docker, fix everything and check that it's working and then put the final run of the release script through docker to generate the ultimate release files.

The parts of the release script that fail take much less time than the script as a whole so if I could run those quickly locally (or even in a VM) then it would take me about 1-2 hrs to put together a PR that would probably fix everything so that the release script could run successfully first time.

In fact if there was a script that could run all of these checks without running the full release script then we could run it as a job on Travis. Then these issues would get sorted out one PR at a time rather than at the point of release. The main thing that would be awkward about this is newer contributors needing to update AUTHORS and .mailmap but that's probably a good thing: we should be more transparent about how their contributions are attributed.

I get the impression that the real advantages of using rever are:

1. Being able to roll back changes if something goes wrong.
2. Ensuring that dependent tasks are run in the correct order when running tasks interactively.

At the moment I don't think that the sympy release script benefits from either of these because the release script is not used interactively and there are no undoers registered to be able to roll anything back.
