### ISSUE TITLE
OverflowError in test_sample_scipy 

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#20344]
https://travis-ci.org/github/sympy/sympy/jobs/738543139
This can be randomly failing

```
________________________________________________________________________________
__________ sympy/stats/tests/test_continuous_rv.py:test_sample_scipy ___________
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.8.dev0-py3.7.egg/sympy/testing/runtests.py", line 1343, in _timeout
    function()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.8.dev0-py3.7.egg/sympy/stats/tests/test_continuous_rv.py", line 1633, in test_sample_scipy
    samps = next(sample(X, size=size, library='scipy'))
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.8.dev0-py3.7.egg/sympy/stats/rv.py", line 1221, in return_generator
    d = ps.sample(size=size, library=library)  # a dictionary that maps RVs to values
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.8.dev0-py3.7.egg/sympy/stats/crv.py", line 601, in sample
    return {self.value: self.distribution.sample(size, library=library)}
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.8.dev0-py3.7.egg/sympy/stats/crv.py", line 290, in sample
    samps = _get_sample_class_crv[library](self, size)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.8.dev0-py3.7.egg/sympy/stats/crv.py", line 151, in __new__
    return cls._sample_scipy(dist, size)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.8.dev0-py3.7.egg/sympy/stats/crv.py", line 165, in _sample_scipy
    return scipy_rv.rvs(size=size)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1004, in rvs
    vals = self._rvs(*args, size=size, random_state=random_state)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 923, in _rvs
    Y = self._ppf(U, *args)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 938, in _ppf
    return self._ppfvec(q, *args)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2108, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2192, in _vectorize_call
    outputs = ufunc(*inputs)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1694, in _ppf_single
    while self._ppf_to_solve(right, q, *args) < 0.:
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1679, in _ppf_to_solve
    return self.cdf(*(x, )+args)-q
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1854, in cdf
    place(output, cond, self._cdf(*goodargs))
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1729, in _cdf
    return self._cdfvec(x, *args)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2108, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2192, in _vectorize_call
    outputs = ufunc(*inputs)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1726, in _cdf_single
    return integrate.quad(self._pdf, _a, x, args=args)[0]
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/scipy/integrate/quadpack.py", line 352, in quad
    points)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/scipy/integrate/quadpack.py", line 465, in _quad
    return _quadpack._qagie(func,bound,infbounds,args,full_output,epsabs,epsrel,limit)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sympy-1.8.dev0-py3.7.egg/sympy/stats/crv.py", line 162, in _pdf
    return handmade_pdf(x)
  File "<lambdifygenerated-423>", line 2, in _lambdifygenerated
    return (1/(pi*((Dummy_33940 - 1)**2 + 1)))
OverflowError: (34, 'Numerical result out of range')
```

**Comment by Maelstrom6** [comment]
Correct me if I'm wrong but I think this might be because of the Cauchy distribution in the tests. 

The following produces the same error:
```python
from scipy.stats import rv_continuous
import numpy as np

class scipy_pdf(rv_continuous):
    def _pdf(self, x):
        return 1/(np.pi*((x - 1)**2 + 1))

scipy_rv = scipy_pdf(name='scipy_pdf')
print(scipy_rv.rvs(size=1000))
```

So SciPy does not really support a Cauchy handmade pdf. I believe this has something to do with the expectation of the Cauchy distribution being divergent. 

We can either consider this as SciPy's fault or we could use SciPy's built in distributions when possible. I did most of the hard work for this in #19935 which is currently closed. I just haven't had anyone confirm that what I did was correct.
