### ISSUE TITLE
Finding the density or CDF for certain powers and roots of uniform random variables fails

### ISSUE THREAD

**Issue by peteroupc** [sympy/sympy#20400]
Given `unif=Uniform('U',0,1)`&mdash;

- finding `density(unif**2)` or `cdf(unif**2)` (or any even power) works, and
- finding `density(unif**(S(1)/3))` or `cdf(unif**(S(1)/3))` (or any odd root) works, but
- finding `density(unif**3)` or `cdf(unif**3)` (or any odd power greater than 3) fails with "TypeError: expecting Expr but got: `ExprCondPair`", and
- finding `density(unif**(S(1)/2))` or `cdf(unif**(S(1)/2))` (or any even root, including `sqrt(unif)`) fails with "TypeError: The computation had not completed because of the undecidable set membership is found in every candidates." (which is ungrammatical, by the way), and
- finding `density(unif**(S(3)/4))` (as well as other cases where the power is a multiple of 1/even) fails with the same TypeError.

**Comment by akshatsood2249** [comment]
Well for me `density(unif**3)` or `cdf(unif**3)` or any higher power is working and there are no errors. Maybe version issue, try updating sympy (if not). 
The last two points that you have mentioned are correct and displaying an error. I will try to work out on same and revet back

**Comment by willt-pearson** [comment]
Special override of __iter__ on Intersection() class throws a vague and grammatically incorrect TypeError as mentioned by @peteroupc. This is not a big deal, but it could be made clearer to eliminate confusion.

For my test case, I believe the intention of the TypeError is to convey that a variable exists in the expression, which makes the value undetermined. So if a restriction on value is provided, we can't decide if it is actually part of the FiniteSet.

Perhaps it could be more clearly conveyed as follows:
"An Exception was encountered while trying to iterate through the Set because the value of every element in the Set could not be determined, and a restriction on the Set's values was provided."

Also, consider adding a base Exception class to this module to throw instead of a generic TypeError. It would be much safer for end-users to import a more specific Exception class if expecting this scenario.

Test case using SymPy version 1.8 (not dev):
```
In: from sympy import *
In: v = Symbol("v", extended_real=True)
In: [x for x in Intersection(FiniteSet(-sqrt(10)*sqrt(v)/(10*sqrt(pi))), Interval(-pi, pi))].
Out: Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 1, in <listcomp>
  File "/Users/utollwi/.pyenv/versions/3.6.10/lib/python3.6/site-packages/sympy/sets/sets.py", line 1417, in __iter__
    "The computation had not completed because of the "
TypeError: The computation had not completed because of the undecidable set membership is found in every candidates.
```
