### ISSUE TITLE
Crash for calculation of expected value of exponentiated multivariate normal random variable

### ISSUE THREAD

**Issue by rikardn** [sympy/sympy#20540]
Sympy 1.7 crash when I try to calculate the expected value of an exponentiated multivariate normal variable.

```python
import sympy
import sympy.stats

X = sympy.stats.Normal('X', [0, 0], [[1, 0.1], [0.1, 1]])

sympy.stats.E(sympy.exp(X[0]))
```

crash with the following error

```
Traceback (most recent call last):

  File "<ipython-input-3-c601d87ef2e1>", line 5, in <module>
    sympy.stats.E(sympy.exp(X[0]))

  File "/home/.local/lib/python3.8/site-packages/sympy/stats/rv.py", line 770, in expectation
    return Expectation(expr, condition).doit(**kwargs)

  File "/home/.local/lib/python3.8/site-packages/sympy/stats/symbolic_probability.py", line 277, in doit
    return result.doit(**hints)

  File "/home/.local/lib/python3.8/site-packages/sympy/integrals/integrals.py", line 577, in doit
    ret = try_meijerg(function, xab)

  File "/home/.local/lib/python3.8/site-packages/sympy/integrals/integrals.py", line 549, in try_meijerg
    res = meijerint_definite(function, x, a, b)

  File "/home/.local/lib/python3.8/site-packages/sympy/integrals/meijerint.py", line 1795, in meijerint_definite
    res1 = _meijerint_definite_2(f.subs(x, x + c), x)

  File "/home/.local/lib/python3.8/site-packages/sympy/integrals/meijerint.py", line 1927, in _meijerint_definite_2
    res = _meijerint_definite_3(g, x)

  File "/home/.local/lib/python3.8/site-packages/sympy/integrals/meijerint.py", line 1944, in _meijerint_definite_3
    ress = [_meijerint_definite_4(g, x) for g in f.args]

  File "/home/.local/lib/python3.8/site-packages/sympy/integrals/meijerint.py", line 1944, in <listcomp>
    ress = [_meijerint_definite_4(g, x) for g in f.args]

  File "/home/.local/lib/python3.8/site-packages/sympy/integrals/meijerint.py", line 1997, in _meijerint_definite_4
    gs = _rewrite2(f, x)

  File "/home/.local/lib/python3.8/site-packages/sympy/integrals/meijerint.py", line 1583, in _rewrite2
    if any(_rewrite_single(expr, x, False) is None for expr in _mul_args(g)):

  File "/home/.local/lib/python3.8/site-packages/sympy/integrals/meijerint.py", line 1583, in <genexpr>
    if any(_rewrite_single(expr, x, False) is None for expr in _mul_args(g)):

  File "/home/.local/lib/python3.8/site-packages/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)

  File "/home/.local/lib/python3.8/site-packages/sympy/integrals/meijerint.py", line 1471, in _rewrite_single
    r1 = _get_coeff_exp(unpolarify(fac.subs(subs).subs(z, x),

  File "/home/.local/lib/python3.8/site-packages/sympy/integrals/meijerint.py", line 338, in _get_coeff_exp
    raise _CoeffExpValueError('expr not of form a*x**b: %s' % expr)

_CoeffExpValueError: expr not of form a*x**b: 1.00000000000000
```

A similar example without exponentiation works:

```python
import sympy
import sympy.stats

X = sympy.stats.Normal('X', [0, 0], [[1, 0.1], [0.1, 1]])

sympy.stats.E(X[0] * X[1])
```

(returns 0.100000000000000)

Trying to calculate the variance gives the same error.

**Comment by czgdp1807** [comment]
This is issue is since `1.6` as you can see on [this colab notebook](https://colab.research.google.com/drive/1TK18VJYcTV1znFwzfgtXULwe49lBJqIQ?usp=sharing). Thanks for sharing this. We will work on this idea of providing support for obtaining random variables when joint random variables are indexed.

**Comment by rikardn** [comment]
The indexed objects are supported by the `E` function as you can see in my working example. The problem is that you cannot use `exp`. @czgdp1807 I don't think your issue title change really reflects the issue.

**Comment by czgdp1807** [comment]
> The problem is that you cannot use `exp`

IMHO, that is why the problem is a bit deeper. If we would have got an RV by indexing JointRandomSymbol, then exp of that object would have also been an RV and would have been easily processed by other `sympy.stats`. But that is not the case as of now.

**Comment by rikardn** [comment]
Yes, true! Reminds me of a problem I had wanting to create two symbols being joint normally distributed, but using arbitrary symbol names. Something along the lines of:

```python
x1, x2 = sympy.stats.Normal(['x1', 'x2'], [0, 0], [[1, 0.1], [0.1, 1]])
```

Perhaps this could also be handled using a more general solution to this issue.

**Comment by czgdp1807** [comment]
I tried out the following on `master`. Basically it would be best to return a `RandomSymbol` having the correct distribution when we do `X[0]` where `X` is a `JointRandomSymbol`.
Though thanks for testing the code, we really need more cases where our code fails so that it can be enhanced for the end users.
```python
IPython console for SymPy 1.8.dev (Python 3.6.9-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/dev


In [1]: from sympy.stats import *

In [2]: X = Normal('X', [0, 0], [[1, 0.1], [0.1, 1]])

In [3]: N = Normal('N', 0, 1)

In [4]: E(Max(N, 0))
Out[4]: 
 √2 
────
2⋅√π

In [5]: E(Max(X[0], 0))
# Hangs
```

**Comment by czgdp1807** [comment]
Note the following example as well, 
```python
In [26]: X = Normal('X', [0, 0], [[1, 0], [0, 1]])

In [27]: E(exp(X[0]))
Out[27]: 
   ⎛        1/2    ⎛√2⎞            ⎞                      
   ⎜  √2⋅π⋅ℯ   ⋅erf⎜──⎟         1/2⎟                      
   ⎜               ⎝2 ⎠   √2⋅π⋅ℯ   ⎟   ⎛        ⎛√2⎞⎞  1/2
√2⋅⎜- ───────────────── + ─────────⎟   ⎜2 - erfc⎜──⎟⎟⋅ℯ   
   ⎝          2               2    ⎠   ⎝        ⎝2 ⎠⎠     
──────────────────────────────────── + ───────────────────
                2⋅π                             2         

In [28]: E(Max(X[0], 0))
Out[28]: 
 √2 
────
2⋅√π
In [31]: X = Normal('X', [0, 0], [[1, S(1)/2], [0, 1]])

In [32]: E(exp(X[0]))
Out[32]: 
   ⎛           128                          ⎞          ⎛                      
   ⎜           ───                       128⎟          ⎜           128        
   ⎜            15    ⎛8⋅√30⎞            ───⎟          ⎜           ───        
   ⎜  8⋅√30⋅π⋅ℯ   ⋅erf⎜─────⎟             15⎟          ⎜            15   8⋅√30
   ⎜                  ⎝  15 ⎠   8⋅√30⋅π⋅ℯ   ⎟  -8      ⎜  8⋅√30⋅π⋅ℯ           
√2⋅⎜- ─────────────────────── + ────────────⎟⋅ℯ     √2⋅⎜- ──────────── - ─────
   ⎝             15                  15     ⎠          ⎝       15             
───────────────────────────────────────────────── - ──────────────────────────
                       8⋅π                                                 8⋅π

    128           ⎞    
    ───           ⎟    
     15    ⎛8⋅√30⎞⎟    
⋅π⋅ℯ   ⋅erf⎜─────⎟⎟    
           ⎝  15 ⎠⎟  -8
──────────────────⎟⋅ℯ  
      15          ⎠    
───────────────────────
                       

In [33]: E(exp(X[1]))
Out[33]: 
   ⎛           8/15    ⎛2⋅√30⎞                ⎞                               
   ⎜  2⋅√30⋅π⋅ℯ    ⋅erf⎜─────⎟            8/15⎟                               
   ⎜                   ⎝  15 ⎠   2⋅√30⋅π⋅ℯ    ⎟         ⎛        ⎛2⋅√30⎞⎞  8/1
√2⋅⎜- ──────────────────────── + ─────────────⎟   2⋅√15⋅⎜2 - erfc⎜─────⎟⎟⋅ℯ   
   ⎝             15                    15     ⎠         ⎝        ⎝  15 ⎠⎠     
─────────────────────────────────────────────── + ────────────────────────────
                      2⋅π                                       15            

 
 
5
 
 
─
In [34]: X = Normal('X', [0, 0], [[1, S(1)/10], [S(1)/10, 1]])

In [35]: E(exp(X[0]))
# Hangs but no crash, might be a problem related to integrate
```
I think that covariance matrix `[[1, 0.1], [0.1, 1]]` should be written as `[[1, S(1)/10], [S(1)/10, 1]]` because `0.1` in binary format is not exactly `0.1` and hence the crash happens.

**Comment by czgdp1807** [comment]
Probably this is not an issue with `stats` but with `integrals` module.

**Comment by oscarbenjamin** [comment]
There is an issue with integrals but that doesn't mean we should close this.

On the stats side maybe it should be possible to recognise that `exp(X[0])` is log-normal. It seems that it isn't possible to compute the expectation of a log-normal random variate either though:
```python
In [47]: E(LogNormal('X', 1, 1))                                                                                                  
---------------------------------------------------------------------------
...
NotImplementedError: Moment generating function of the log-normal distribution is not defined.
```
Although the MGF of log-normal is not defined there is a formula for the nth moment so that could be used instead here.

The integrals issue is with meijerg:
```python
In [31]: Integral(exp(-x**2 + 0.1*x*y - y**2)*exp(x), (x, -oo, oo), (y, -oo, oo)).doit() 
...
~/current/sympy/sympy/sympy/integrals/meijerint.py in _get_coeff_exp(expr, x)
    336         return c, S.One
    337     else:
--> 338         raise _CoeffExpValueError('expr not of form a*x**b: %s' % expr)
    339 
    340 

_CoeffExpValueError: expr not of form a*x**b: 1.00000000000000
 ```

Replacing the float with rational it hangs or at least takes a long time in heurisch but we can force the use of meijerg again to see that it evaluates only partially:
```python
In [39]: Integral(exp(-x**2 + Rational(1, 10)*x*y - y**2)*exp(x), (x, -oo, oo), (y, -oo, oo)).doit(meijerg=True)                  
Out[39]: 
        ∞                  
        ⌠                  
        ⎮             2    
        ⎮   y   -399⋅y     
        ⎮   ──  ────────   
    1/4 ⎮   20    400      
√π⋅ℯ   ⋅⎮  ℯ  ⋅ℯ         dy
        ⌡                  
        -∞ 
```
It seems that this is sensitive to form of the integrand because a powsimp can complete the integral:
```python
In [40]: _.powsimp().doit()                                                                                                       
Out[40]: 
   ⎛            1/1596     ⎛√399⎞              ⎛        ⎛√399⎞⎞  1/1596⎞     
   ⎜10⋅√399⋅√π⋅ℯ      ⋅erfc⎜────⎟   10⋅√399⋅√π⋅⎜2 - erfc⎜────⎟⎟⋅ℯ      ⎟     
   ⎜                       ⎝798 ⎠              ⎝        ⎝798 ⎠⎠        ⎟  1/4
√π⋅⎜───────────────────────────── + ───────────────────────────────────⎟⋅ℯ   
   ⎝             399                                399                ⎠     

In [41]: _.n()                                                                                                                    
Out[41]: 4.04146810130492
```

**Comment by czgdp1807** [comment]
That's a nice point raised. In fact, it has been discussed earlier too. `sympy.stats` should be able to manage transformations of RVs. A possible approach can be to create a knowledge base (KB) that would contain pre-defined results. Issues like [this](https://github.com/sympy/sympy/pull/20512#issuecomment-739135379) are also related to transformations of RVs. @Upabjojr What do you say?

Ideally things, like, `exp(RV)` should return an RV but that would require a lot changes in other parts of `sympy`. Currently, there is partial support of managing `f(RV)` but not everything works correctly as I showed [here](https://github.com/sympy/sympy/pull/20512#issuecomment-739135379). This can be fixed, we just need to test which APIs are not having enough support for these transformations of RVs.

**Comment by rikardn** [comment]
Transformations of RVs would be nice, but not all expressions of RVs could be transformed into another standard distribution. It would still be useful to be able to manipulate expressions of RVs.

I know of one knowledge base for random distributions: http://probonto.org

**Comment by Upabjojr** [comment]
> Probably this is not an issue with `stats` but with `integrals` module.

`sympy.tensor.indexed.Indexed` should technically behave exactly as `Symbol` (i.e. `X[0]` and `X` should be behave exactly the same way in the equation solver and integrator). Unfortunately, if you try to solve equations or compute integrals, you will notice that that's not the case.

This is an issue that's buried deep in SymPy's core.

**Comment by Upabjojr** [comment]
> Ideally things, like, `exp(RV)` should return an RV but that would require a lot changes in other parts of `sympy`.

There are various possibilities:

1. Use `.is_random` property, which recurses into the expression tree and returns `True` if there is a RV, otherwise `False`.
2. Use a wrapping object. For example, in the matrix module, the class `ElementwiseApplyFunction` wraps a function and a matrix, it represents the function applied elementwisely to the matrix elements.
3. Subclass everything like it's done in `sympy.matrices.expressions`. I would not recommend this way.

Personally, I would just try to use the `.is_random` property and try not to increase the code complexity by adding new classes.

**Comment by Upabjojr** [comment]
> I know of one knowledge base for random distributions: http://probonto.org

Wow, that's nice.

**Comment by oscarbenjamin** [comment]
> Ideally things, like, `exp(RV)` should return an RV

I don't think that's necessary. Rather the distribution of this expression is something like `TransformDistribution(Lambda(x, exp(x)), Normal(0, 1))`. It should be possible to simplify that distribution to something like `LogNormalDistribution(0, 1)`.

What is needed is a way to get the distribution of an expression involving RVs and then a way to simplify or convert between different representations of a distribution.

**Comment by Upabjojr** [comment]
> What is needed is a way to get the distribution of an expression involving RVs and then a way to simplify or convert between different representations of a distribution.

We have a pattern matcher. If ours is not enough, we have a backend for [MatchPy](https://github.com/HPAC/matchpy).

**Comment by oscarbenjamin** [comment]
> you will notice that `repl` is a `LogNormal` distribution named `N_transformed`, as the replacement rule has been triggered.

It is not a *distribution*. It is a *random variable* that follows a `LogNormal` distribution. What I'm suggesting is that it would be better to apply these transformations to distributions rather than expressions involving random variables.

If the user creates a *named* random variable `X` then any expression involving `X` should still have that same symbol in it. However it should be possible to get the *distribution* of the random variable and then to operate on those distributions independently of any named symbol e.g.:
```python
>>> X = Normal(0, 1)
>>> exp(X)
exp(X)
>>> distribution(exp(X))
TransformedDistribution(Lambda(x, exp(x)), NormalDistribution(0, 1))
>>> distribution(exp(X)).rewrite(LogNormalDistribution)
LogNormalDistribution(0, 1)
>>> simplify(distribution(exp(X)))
LogNormalDistribution(0, 1)
>>> Y = RandomSymbol('Y', distribution(exp(X)))
```
Then something like `E(exp(X))` can call something like `distribution(X).simplify().moment(1)`.

**Comment by Upabjojr** [comment]
> What I'm suggesting is that it would be better to apply these transformations to distributions rather than expressions involving random variables.

It should be thought a bit. Acting on RVs has also some advantages. Consider that MatchPy can handle efficiently complex expression tree, so that should not be a problem.
