### ISSUE TITLE
Crash when trying to sample from multivariate normal random variable

### ISSUE THREAD

**Issue by rikardn** [sympy/sympy#20541]
Sympy 1.7 crash when I try to sample from a multivariate normal expression.

```python
import sympy
import sympy.random

X = sympy.stats.Normal('X', [0, 0], [[1, 0.1], [0.1, 1]])
next(sympy.stats.sample(X[0])
```

crash with the following trace:

```
Traceback (most recent call last):

  File "/home/rikard/.local/lib/python3.8/site-packages/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)

  File "/home/rikard/.local/lib/python3.8/site-packages/sympy/core/basic.py", line 1062, in _subs
    rv = fallback(self, old, new)

  File "/home/rikard/.local/lib/python3.8/site-packages/sympy/core/basic.py", line 1039, in fallback
    rv = self.func(*args)

  File "/home/rikard/.local/lib/python3.8/site-packages/sympy/tensor/indexed.py", line 158, in __new__
    raise TypeError(filldedent("""

TypeError: 
The base can only be replaced with a string, Symbol, IndexedBase or an
object with a method for getting items (i.e. an object with a
`__getitem__` method).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-11-840d7ac55bf8>", line 1, in <module>
    list(sympy.stats.sample(X[0]))

  File "/home/rikard/.local/lib/python3.8/site-packages/sympy/stats/rv.py", line 1093, in sample
    return sample_iter(expr, condition, size=size, library=library,

  File "/home/rikard/.local/lib/python3.8/site-packages/sympy/stats/rv.py", line 1202, in sample_iter
    expr = expr.subs(sub)

  File "/home/rikard/.local/lib/python3.8/site-packages/sympy/core/basic.py", line 948, in subs
    rv = rv._subs(old, new, **kwargs)

  File "/home/rikard/.local/lib/python3.8/site-packages/sympy/core/cache.py", line 74, in wrapper
    retval = func(*args, **kwargs)

  File "/home/rikard/.local/lib/python3.8/site-packages/sympy/core/basic.py", line 1062, in _subs
    rv = fallback(self, old, new)

  File "/home/rikard/.local/lib/python3.8/site-packages/sympy/core/basic.py", line 1039, in fallback
    rv = self.func(*args)

  File "/home/rikard/.local/lib/python3.8/site-packages/sympy/tensor/indexed.py", line 158, in __new__
    raise TypeError(filldedent("""

TypeError: 
The base can only be replaced with a string, Symbol, IndexedBase or an
object with a method for getting items (i.e. an object with a
`__getitem__` method).
```

It works to sample from the whole multivariate vector:

```python
list(sympy.stats.sample(X))
```

returning

```
[array([0.2260188 , 0.14658906])]
```

This way however doesn't allow sampling from an expression containing multivariate normal variables separately.

**Comment by czgdp1807** [comment]
We don't have support for this use case actually. SymPy 1.6 terminates with maximum recursion depth as I tested on Google Colab. You can see [here](https://colab.research.google.com/drive/1TK18VJYcTV1znFwzfgtXULwe49lBJqIQ?usp=sharing).
Thanks for sharing this idea. We will try to add support for sampling different random variables obtained by indexing a joint distribution.
The reason I can figure out for this is that, `X[0]` is not a random variable but instead it is an `sympy.tensor.indexed.Indexed`. So, one of the ways to implement the suggested feature is to return something like `RandomIndexed`, which can be processed by `sympy.stats.sample`.

**Comment by czgdp1807** [comment]
`GSoC` label doesn't mean that it cannot be fixed before `GSoC`. Anyone interested can work on this issue even before the starting of `GSoC`, though AFAICT, this is not that easy to fix as it will need some significant changes which can become a part of a project.

**Comment by rikardn** [comment]
I don't think the extra `RandomIndexed` is needed it would be possible to check if any indexed symbols are indexing a `JointRandomSymbol`.

```python
> type(X[0].args[0])
sympy.stats.joint_rv.JointRandomSymbol
```

**Comment by czgdp1807** [comment]
I cannot comment on what the fix would be without investigating and trying out various approaches. The best fix would be which changes the code and the current design minimally.

**Comment by czgdp1807** [comment]
I tried with more examples and this issue persists with those cases also. So possibly this needs a fix(which may not be easy),
