### ISSUE TITLE
Strange behavior of: as_int TypeError

### ISSUE THREAD

**Issue by antonmontagne** [sympy/sympy#20615]
The code below generates the exception: 

  File "/usr/lib/python3/dist-packages/sympy/core/compatibility.py", line 425, in as_int
    raise ValueError('%s is not an integer' % (n,))
    
But I can't understand why it should. I assume sp.sympify should be robust enough to pass
any expression generated with sympy.sympify(<String_that_represents_a_valid_expression>)
or am I wrong?
Not only sympy.sympify is generating this error, also sympy.Abs is doing it (and maybe more functions):

``` python
import sympy as sp
func = sp.sympify('-2e-1/(1.0 + 2*I*pi*f)')
print(sp.simplify(func))
```
Change "1.0" in the denominator into  "1" and the exception is not longer raised; very strange!?

The error log:
------------------

TypeError
    
During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-25-56085b31d8a6>", line 1, in <module>
    runfile('/home/anton/Desktop/NotAnInteger.py', wdir='/home/anton/Desktop')

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/anton/Desktop/NotAnInteger.py", line 15, in <module>
    print(sp.simplify(func))

  File "/usr/lib/python3/dist-packages/sympy/simplify/simplify.py", line 601, in simplify
    expr1 = shorter(_e, _mexpand(_e).cancel())  # issue 6829

  File "/usr/lib/python3/dist-packages/sympy/core/expr.py", line 3567, in cancel
    return cancel(self, *gens, **args)

  File "/usr/lib/python3/dist-packages/sympy/polys/polytools.py", line 6609, in cancel
    f = factor_terms(f, radical=True)

  File "/usr/lib/python3/dist-packages/sympy/core/exprtools.py", line 1258, in factor_terms
    return do(expr)

  File "/usr/lib/python3/dist-packages/sympy/core/exprtools.py", line 1254, in do
    *[do(a) for a in p.args])

  File "/usr/lib/python3/dist-packages/sympy/core/exprtools.py", line 1254, in <listcomp>
    *[do(a) for a in p.args])

  File "/usr/lib/python3/dist-packages/sympy/core/exprtools.py", line 1221, in do
    newargs = tuple([do(i) for i in args])

  File "/usr/lib/python3/dist-packages/sympy/core/exprtools.py", line 1221, in <listcomp>
    newargs = tuple([do(i) for i in args])

  File "/usr/lib/python3/dist-packages/sympy/core/exprtools.py", line 1248, in do
    p = gcd_terms(p,

  File "/usr/lib/python3/dist-packages/sympy/core/exprtools.py", line 1069, in gcd_terms
    cont, numer, denom = _gcd_terms(terms, isprimitive, fraction)

  File "/usr/lib/python3/dist-packages/sympy/core/exprtools.py", line 943, in _gcd_terms
    terms = list(map(Term, [t for t in terms if t]))

  File "/usr/lib/python3/dist-packages/sympy/core/exprtools.py", line 843, in __init__
    numer = Factors(numer)

  File "/usr/lib/python3/dist-packages/sympy/core/exprtools.py", line 375, in __init__
    if k is I or k in (-1, 1):

  File "/usr/lib/python3/dist-packages/sympy/core/numbers.py", line 1406, in __eq__
    return other.__eq__(self)

  File "/usr/lib/python3/dist-packages/sympy/core/numbers.py", line 2248, in __eq__
    return Rational.__eq__(self, other)

  File "/usr/lib/python3/dist-packages/sympy/core/numbers.py", line 1906, in __eq__
    integer_log(self.p//m, 2) == (t, True)

  File "/usr/lib/python3/dist-packages/sympy/core/power.py", line 147, in integer_log
    y = as_int(y)

  File "/usr/lib/python3/dist-packages/sympy/core/compatibility.py", line 425, in as_int
    raise ValueError('%s is not an integer' % (n,))

ValueError: -1 is not an integer

**Comment by oscarbenjamin** [comment]
What version of sympy are you using. With master I get a different error:
```
In [10]: import sympy as sp
    ...: func = sp.sympify('-2e-1/(1.0 + 2*I*pi*f)')
    ...: print(sp.simplify(func))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-2fb283976c98> in <module>
      1 import sympy as sp
      2 func = sp.sympify('-2e-1/(1.0 + 2*I*pi*f)')
----> 3 print(sp.simplify(func))

~/current/sympy/sympy/sympy/simplify/simplify.py in simplify(expr, ratio, measure, rational, inverse, doit, **kwargs)
    619     expr = bottom_up(expr, lambda w: getattr(w, 'normal', lambda: w)())
    620     expr = Mul(*powsimp(expr).as_content_primitive())
--> 621     _e = cancel(expr)
    622     expr1 = shorter(_e, _mexpand(_e).cancel())  # issue 6829
    623     expr2 = shorter(together(expr, deep=True), together(expr1, deep=True))

~/current/sympy/sympy/sympy/polys/polytools.py in cancel(f, *gens, **args)
   6715             return f.xreplace(dict(reps))
   6716 
-> 6717     c, (P, Q) = 1, F.cancel(G)
   6718     if opt.get('polys', False) and not 'gens' in opt:
   6719         opt['gens'] = R.symbols

~/current/sympy/sympy/sympy/polys/rings.py in cancel(self, g)
   2220             _, p, q = f.cofactors(g)
   2221 
-> 2222             if q.is_negative:
   2223                 p, q = -p, -q
   2224         else:

~/current/sympy/sympy/sympy/polys/rings.py in is_negative(self)
    848     @property
    849     def is_negative(self):
--> 850         return self.ring.domain.is_negative(self.LC)
    851 
    852     @property

~/current/sympy/sympy/sympy/polys/domains/domain.py in is_negative(self, a)
    448     def is_negative(self, a):
    449         """Returns True if ``a`` is negative. """
--> 450         return a < 0
    451 
    452     def is_nonpositive(self, a):

TypeError: '<' not supported between instances of 'ComplexElement' and 'int'
```
That's definitely a bug. I can reproduce it more simply:
```
In [11]: cancel(1.0/(pi + I))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-af0111a3ccfb> in <module>
----> 1 cancel(1.0/(pi + I))

~/current/sympy/sympy/sympy/polys/polytools.py in cancel(f, *gens, **args)
   6715             return f.xreplace(dict(reps))
   6716 
-> 6717     c, (P, Q) = 1, F.cancel(G)
   6718     if opt.get('polys', False) and not 'gens' in opt:
   6719         opt['gens'] = R.symbols

~/current/sympy/sympy/sympy/polys/rings.py in cancel(self, g)
   2220             _, p, q = f.cofactors(g)
   2221 
-> 2222             if q.is_negative:
   2223                 p, q = -p, -q
   2224         else:

~/current/sympy/sympy/sympy/polys/rings.py in is_negative(self)
    848     @property
    849     def is_negative(self):
--> 850         return self.ring.domain.is_negative(self.LC)
    851 
    852     @property

~/current/sympy/sympy/sympy/polys/domains/domain.py in is_negative(self, a)
    448     def is_negative(self, a):
    449         """Returns True if ``a`` is negative. """
--> 450         return a < 0
    451 
    452     def is_nonpositive(self, a):

TypeError: '<' not supported between instances of 'ComplexElement' and 'int'
```

**Comment by antonmontagne** [comment]
Dear Oscar,

Thank you for your reply. The exception was generated with sympy version 1.5.1. Yesterday I upgraded to sympy 1.7.1. This version generates the exception you showed.

I have read a post in which the use of simplify is only promoted for interactive mode.

In my program (a symbolic analysis tool for electronic circuits: https://github.com/Lenty/SLiCAP_python) I replaced all occurrences of simplify with more meaningful simplification instructions like 'expand' or 'factor' or '.as_numer_denom' so my users are not bothered by this exception. In version 1.5.1 also sympy.Abs() generated this error, this is resolved in 1.7.1.

Hope this helps improving sympy!
Thanks for your effort,

With kind regards,
Anton Montagne
