### ISSUE TITLE
Solve: GeneratorsNeeded with system involving constant equation

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#20610]
I don't think solve should convert all equations to Poly because it can be slow but at least there should be some checking for this case:
```python
>>> from sympy import *
>>> from sympy.abc import x, y
>>> solve([x + y, sqrt(2)], [x, y])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 1099, in solve
    solution = _solve_system(f, symbols, **flags)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 1774, in _solve_system
    subsol = _solve_system(subexpr, subsyms, **flags)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solvers.py", line 1805, in _solve_system
    poly = g.as_poly(*symbols, extension=True)
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 1109, in as_poly
    poly = Poly(self, *gens, **args)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 162, in __new__
    return cls._from_expr(rep, opt)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 292, in _from_expr
    return cls._from_dict(rep, opt)
  File "/Users/enojb/current/sympy/sympy/sympy/polys/polytools.py", line 229, in _from_dict
    raise GeneratorsNeeded(
sympy.polys.polyerrors.GeneratorsNeeded: can't initialize from 'dict' without generators
```

**Comment by ForceBru** [comment]
This is still present as of SymPy 1.9
