### ISSUE TITLE
Exception for probability with JointRV: pspace is not symbol-like

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#20634]
From SO:
https://stackoverflow.com/questions/65379312/can-sympy-calculate-the-probability-from-a-piecewise-joint-pdf

```python
from sympy import *
from sympy import Indexed, Piecewise, exp, Eq
from sympy.stats import JointRV, P

x1, x2 = (Indexed('x', i) for i in range(1,3))

# Original example:
# pdf = Piecewise((2 * exp(-x1 - x2), (0 < x1) & (x1 < x2) & (x2 < 10)), (0, False))

# Also shows the same bug:
pdf = exp(-x1**2/2 + x1 - x2**2/2 - S(1)/2)/(2*pi)

X = JointRV('x', pdf)

P(X[1] > 2, Eq(X[0], 1))
```
Output:
```
Traceback (most recent call last):
  File "q.py", line 15, in <module>
    P(X[1] > 2, Eq(X[0], 1))
  File "/Users/enojb/current/sympy/sympy/sympy/stats/rv.py", line 809, in probability
    return Probability(condition, given_condition).doit(**kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/stats/symbolic_probability.py", line 105, in doit
    return Probability(given(condition, given_condition)).doit()
  File "/Users/enojb/current/sympy/sympy/sympy/stats/rv.py", line 698, in given
    results = solveset(condition, rv)
  File "/Users/enojb/current/sympy/sympy/sympy/solvers/solveset.py", line 2087, in solveset
    return solveset(f[0], s[0], domain).xreplace(swap)
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1139, in xreplace
    value, _ = self._xreplace(rule)
  File "/Users/enojb/current/sympy/sympy/sympy/core/basic.py", line 1161, in _xreplace
    return self.func(*args), True
  File "/Users/enojb/current/sympy/sympy/sympy/sets/conditionset.py", line 127, in __new__
    raise ValueError('`%s` is not symbol-like' % i)
ValueError: `JointPSpace(x, JointDistributionHandmade(Lambda((x[1], x[2]), exp(-x[1]**2/2 + x[1] - x[2]**2/2 - 1/2)/(2*pi)), ProductSet(Reals, Reals)))` is not symbol-like
```

**Comment by Upabjojr** [comment]
I'm looking at the stats code... it definitely needs some overhaul.

**Comment by Upabjojr** [comment]
Apart from bugs raising the errors... `JointPSpace` does currently not implement three methods necessary for this computation:
1. `where`
2. `conditional_space`
3. `probability`

**Comment by joachimlebovits** [comment]
I will also be very interested by knowing to compute P(X>Y), when (X,Y) is joint distribution.
Any tips?
Thanks

**Comment by samithkavishke** [comment]
What is the expected out come?
