### ISSUE TITLE
UnicodeEncodeError in Sympy Live Shell

### ISSUE THREAD

**Issue by sayandip18** [sympy/sympy#20687]
Running any piece of code from the documentation in Sympy Live Shell shows this
```
Exception in SymPy Live of type 
<type 'exceptions.UnicodeEncodeError'>
for reference the last 5 stack trace entries are
Traceback (most recent call last):
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/handlers.py", line 271, in post
    live.evaluate(statement, session, printer, stream)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/shell.py", line 280, in evaluate
    exec code in statement_module.__dict__
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/printing/pretty/pretty.py", line 2665, in pretty_print
    imaginary_unit=imaginary_unit))
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/dd89b7af809b5e76/python27/python27_lib/versions/1/google/appengine/runtime/request_environment.py", line 104, in write
    self._request.errors.write(data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-4: ordinal not in range(128)
>>> x=2
```
Surprisingly, the [other Sympy Live Shell](https://live.sympy.org/) runs just fine.

**Comment by lastcodestanding** [comment]
Could you please explain the difference between "Sympy Live shell" and the "other Sympy live shell"? 
I don't get any such errors.

**Comment by sayandip18** [comment]
This is where I'm getting the error. The shell which starts running when you click on the code in docs.
![Screenshot from 2021-01-04 00-47-44](https://user-images.githubusercontent.com/42385886/103486881-29fbf000-4e27-11eb-8e1b-d2c2f1244160.png)

Whereas, this is running fine.

![Screenshot from 2021-01-04 00-54-43](https://user-images.githubusercontent.com/42385886/103486954-970f8580-4e27-11eb-87ee-4bda84e9eda3.png)

**Comment by sayandip18** [comment]
Closing because the issue is resolved for some reason now
