### ISSUE TITLE
ValueError: Abs(1*1) is not an integer

### ISSUE THREAD

**Issue by satels** [sympy/sympy#20694]
```
>>> from sympy.abc import x
>>> from sympy import sqrt, cbrt, evaluate
>>> from sympy import __version__
>>> __version__
'1.7.1'
>>> with evaluate(False):
...     (sqrt(9+2*x)-5)/(cbrt(x)-2)
... 
Traceback (most recent call last):
  File "/home/satels/workenvs/krcore/lib/python3.8/site-packages/sympy/core/compatibility.py", line 373, in as_int
    return operator.index(n)
TypeError: 'Abs' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/satels/workenvs/krcore/lib/python3.8/site-packages/sympy/functions/elementary/miscellaneous.py", line 208, in cbrt
    return Pow(arg, Rational(1, 3), evaluate=evaluate)
  File "/home/satels/workenvs/krcore/lib/python3.8/site-packages/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/satels/workenvs/krcore/lib/python3.8/site-packages/sympy/core/numbers.py", line 1664, in __new__
    gcd = igcd(abs(p), q)
  File "/home/satels/workenvs/krcore/lib/python3.8/site-packages/sympy/core/numbers.py", line 252, in igcd
    args_temp = [abs(as_int(i)) for i in args]
  File "/home/satels/workenvs/krcore/lib/python3.8/site-packages/sympy/core/numbers.py", line 252, in <listcomp>
    args_temp = [abs(as_int(i)) for i in args]
  File "/home/satels/workenvs/krcore/lib/python3.8/site-packages/sympy/core/compatibility.py", line 375, in as_int
    raise ValueError('%s is not an integer' % (n,))
ValueError: Abs(1*1) is not an integer

```

**Comment by oscarbenjamin** [comment]
The issue is with `Rational(1, 3)`:
```
In [4]: with evaluate(False):
   ...:     Rational(1, 3)
   ...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/current/sympy/sympy/sympy/core/compatibility.py in as_int(n, strict)
    300                 raise TypeError
--> 301             return operator.index(n)
    302         except TypeError:

TypeError: 'Abs' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-4-772850dbea56> in <module>
      1 with evaluate(False):
----> 2     Rational(1, 3)
      3 

~/current/sympy/sympy/sympy/core/cache.py in wrapper(*args, **kwargs)
     70         def wrapper(*args, **kwargs):
     71             try:
---> 72                 retval = cfunc(*args, **kwargs)
     73             except TypeError:
     74                 retval = func(*args, **kwargs)

~/current/sympy/sympy/sympy/core/numbers.py in __new__(cls, p, q, gcd)
   1651             p = -p
   1652         if not gcd:
-> 1653             gcd = igcd(abs(p), q)
   1654         if gcd > 1:
   1655             p //= gcd

~/current/sympy/sympy/sympy/core/numbers.py in igcd(*args)
    252         raise TypeError(
    253             'igcd() takes at least 2 arguments (%s given)' % len(args))
--> 254     args_temp = [abs(as_int(i)) for i in args]
    255     if 1 in args_temp:
    256         return 1

~/current/sympy/sympy/sympy/core/numbers.py in <listcomp>(.0)
    252         raise TypeError(
    253             'igcd() takes at least 2 arguments (%s given)' % len(args))
--> 254     args_temp = [abs(as_int(i)) for i in args]
    255     if 1 in args_temp:
    256         return 1

~/current/sympy/sympy/sympy/core/compatibility.py in as_int(n, strict)
    301             return operator.index(n)
    302         except TypeError:
--> 303             raise ValueError('%s is not an integer' % (n,))
    304     else:
    305         try:

ValueError: Abs(1*1) is not an integer
> /Users/enojb/current/sympy/sympy/sympy/core/compatibility.py(303)as_int()
    301             return operator.index(n)
    302         except TypeError:
--> 303             raise ValueError('%s is not an integer' % (n,))
    304     else:
    305         try:
```
These lines will create unevaluated `Mul`:
https://github.com/sympy/sympy/blob/5288eb336d12e4f3c3070bce67d75f38ab4d8376/sympy/core/numbers.py#L1634-L1639
Looking at it the whole method `Rational.__new__` method is a mess and should be rewritten from scratch. It shouldn't be creating multiple other `Rational` as part of the process of producing a single `Rational`.

The easy fix here is just to change the logic inside `Rational.__new__` so that it works entirely with plain `int` rather than `Rational`.

A better fix would be #20598

**Comment by Sandeep10021** [comment]
May i know more about this issue?
What is the input you are using and where are you using this code ?
As  when i am running this code there is no as such issue.

**Comment by sayandip18** [comment]
> As when i am running this code there is no as such issue.

Which version of Sympy are you running?

**Comment by kamilglod** [comment]
I have the same issue when I set `global_parameters.evaluate` flag to `False`
