### ISSUE TITLE
E and variance fail for Matrix distributions

### ISSUE THREAD

**Issue by czgdp1807** [sympy/sympy#20739]
@czgdp1807 
This is the output you get if you call Expectation or variance
```python
>>> from sympy.stats import density, MatrixStudentT, E, variance
>>> v = 2
>>> M = MatrixStudentT('M', v, [[1, 2]], [[1, 0], [0, 1]], [1])
>>> E(M)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/evilmorty/Documents/sympy/sympy/stats/rv.py", line 770, in expectation
    return Expectation(expr, condition).doit(**kwargs)
  File "/home/evilmorty/Documents/sympy/sympy/stats/symbolic_probability.py", line 275, in doit
    result = pspace(expr).compute_expectation(expr, evaluate=for_rewrite)
TypeError: compute_expectation() got an unexpected keyword argument 'evaluate'
>>> variance(M)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/evilmorty/Documents/sympy/sympy/stats/rv_interface.py", line 73, in variance
    return cmoment(X, 2, condition, **kwargs)
  File "/home/evilmorty/Documents/sympy/sympy/stats/rv_interface.py", line 229, in cmoment
    return CentralMoment(X, n, condition).doit()
  File "/home/evilmorty/Documents/sympy/sympy/stats/symbolic_probability.py", line 669, in doit
    return self.rewrite(Expectation).doit(**hints)
  File "/home/evilmorty/Documents/sympy/sympy/core/basic.py", line 1769, in rewrite
    return self._eval_rewrite(None, rule, **hints)
  File "/home/evilmorty/Documents/sympy/sympy/core/basic.py", line 1688, in _eval_rewrite
    rewritten = getattr(self, rule)(*args, **hints)
  File "/home/evilmorty/Documents/sympy/sympy/stats/symbolic_probability.py", line 673, in _eval_rewrite_as_Expectation
    return Moment(X, n, mu, condition, **kwargs).rewrite(Expectation)
  File "/home/evilmorty/Documents/sympy/sympy/core/basic.py", line 1769, in rewrite
    return self._eval_rewrite(None, rule, **hints)
  File "/home/evilmorty/Documents/sympy/sympy/core/basic.py", line 1688, in _eval_rewrite
    rewritten = getattr(self, rule)(*args, **hints)
  File "/home/evilmorty/Documents/sympy/sympy/stats/symbolic_probability.py", line 615, in _eval_rewrite_as_Expectation
    return Expectation((X - c)**n, condition)
  File "/home/evilmorty/Documents/sympy/sympy/matrices/expressions/matexpr.py", line 28, in __sympifyit_wrapper
    return func(a, b)
  File "/home/evilmorty/Documents/sympy/sympy/core/decorators.py", line 137, in binary_op_wrapper
    return func(self, other)
  File "/home/evilmorty/Documents/sympy/sympy/matrices/expressions/matexpr.py", line 115, in __sub__
    return MatAdd(self, -other, check=True).doit()
  File "/home/evilmorty/Documents/sympy/sympy/matrices/expressions/matexpr.py", line 97, in __neg__
    return MatMul(S.NegativeOne, self).doit()
  File "/home/evilmorty/Documents/sympy/sympy/matrices/expressions/matmul.py", line 172, in doit
    args = [arg.doit(**kwargs) for arg in self.args]
  File "/home/evilmorty/Documents/sympy/sympy/matrices/expressions/matmul.py", line 172, in <listcomp>
    args = [arg.doit(**kwargs) for arg in self.args]
  File "/home/evilmorty/Documents/sympy/sympy/stats/symbolic_probability.py", line 275, in doit
    result = pspace(expr).compute_expectation(expr, evaluate=for_rewrite)
TypeError: compute_expectation() got an unexpected keyword argument 'evaluate'
```

_Originally posted by @ks147 in https://github.com/sympy/sympy/issues/20651#issuecomment-753863477_

**Comment by prototypevito** [comment]
Hey @czgdp1807 I wanted to start working on this problem, but wanted some help on how to get started. What I've understood through some research is that we'll have to find the mean of each element in the distribution separately using the density of the distribution to calculate the same. However, since I am new to Sympy, I don't know how to proceed. Please let me know if you had something in mind for this issue.

**Comment by prototypevito** [comment]
The following code returns the expectation value for MatrixNormal Distribution. 

```
>>> from sympy import *
>>> from sympy.stats import density,MatrixNormal, MatrixStudentT,E, variance
>>> v=2
>>> M=MatrixNormal('M',[[1,2]],[1],[[1,0],[0,1]])
>>> x1,x2,x3,x4=symbols('x1,x2,x3,x4')
>>> X=Matrix([[x1,x2]])
>>> pdf=density(M)(X).doit()
>>> result=integrate(pdf*X,(x1,-oo,oo),(x2,-oo,oo))
>>> result_simplified=result.rewrite(erf)
>>> result_simplified=simplify(result)
>>> result_simplified
Matrix([[1, 2]])
```

However, computing the expected value for other more complicated distributions like MatrixGamma and MatrixStudentT is very complicated for the current integration module at Sympy. Should I write code for MatrixNormal/ other distributions that can be solved so that E(distribution) gives an output? 

I am planning to implement the same using the expectation method in other solvable distributions. Does that work?

**Comment by prototypevito** [comment]
The issue I am facing right now is: generalizing the limits for variables for integration according to the dimensions of the matrix given. 

For example (using the same example as above):
If the mean matrix was 2*2, to find the mean, we would have:

`
>>> X=Matrix([[x1,x2],[x3,x4]])
>>> pdf=density(M)(X).doit()
>>> result=integrate(pdf*X,(x1,-oo,oo),(x2,-oo,oo),(x3,-oo,oo),(x4,-oo,oo))

`
Just like this, given the dimensions of the mean matrix, how should I get the pdf in terms of individual variables (and not a matrix) and then use it to integrate over all variables involved. @czgdp1807 If you could just check this out, it'll be really helpful. Thanks!
