### ISSUE TITLE
piecewise_fold does not terminate

### ISSUE THREAD

**Issue by MauriceHendrix** [sympy/sympy#20850]
I'm having an issue with piecewise_fold on sympy 1.7: it doesn't finish.
The equation I'm trying to fold is rather long but of the form
` Piecewise((100000.0 - 100500.0*_calcium_dynamics__APtrack, piecewise_fold(p1)), (-500.0*_calcium_dynamics__APtrack, True))`
where p1 is of the form `ITE(Abs(_membrane__V) < 1.3356169352749131e-6, 1.0*.... < -150000.0, ITE(Abs(_membrane__V) < 2.6712338705498263e-6, 1.0*...< -150000.0, 1.0*<1500))`

**Comment by asmeurer** [comment]
Can you interrupt it with Control-C and paste the traceback so we can see where it is stuck. It would also help if you can paste your full expression.

**Comment by MauriceHendrix** [comment]
```
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> func=Function('func')
>>> X,Y,Z,A,_membrane__V,B,YX,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S = symbols('X,Y,Z,A,_membrane__V,B,YX,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S', real=True)
>>> P1 = Piecewise((100000.0 - 100500.0*A, ITE(Abs(_membrane__V) < 1.3356169352749131e-6, 1.0*(1.0*B*Y*(374358.8350780262*(_membrane__V + 1.3356169352749131e-6)*(1.042038e-5*(1.0*X*exp(-9.9999999999999996e-8) - 0.61380000000000006)/(exp(-9.9999999999999996e-8) - 1.0) + 1.042038e-5*(1.0*X*exp(9.9999999999999996e-8) - 0.61380000000000006)/(exp(9.9999999999999996e-8) - 1.0)) - 1.042038e-5*(1.0*X*exp(-9.9999999999999996e-8) - 0.61380000000000006)/(exp(-9.9999999999999996e-8) - 1.0))/(1666.6666666666668*X + 1.0) + 1.0*B*Y*(187179.4175390131*(_membrane__V + 2.6712338705498263e-6)*(1.8621604999999999e-9*(0.75*C*exp(-9.9999999999999996e-8) - 3.375)/(exp(-9.9999999999999996e-8) - 1.0) + 1.8621604999999999e-9*(0.75*C*exp(9.9999999999999996e-8) - 3.375)/(exp(9.9999999999999996e-8) - 1.0)) - 1.8621604999999999e-9*(0.75*C*exp(-9.9999999999999996e-8) - 3.375)/(exp(-9.9999999999999996e-8) - 1.0))/(1666.6666666666668*X + 1.0) + 1.0*B*Y*(187179.4175390131*(_membrane__V + 2.6712338705498263e-6)*(6.5127374999999997e-9*(0.75*D*exp(-9.9999999999999996e-8) - 99.0)/(exp(-9.9999999999999996e-8) - 1.0) + 6.5127374999999997e-9*(0.75*D*exp(9.9999999999999996e-8) - 99.0)/(exp(9.9999999999999996e-8) - 1.0)) - 6.5127374999999997e-9*(0.75*D*exp(-9.9999999999999996e-8) - 99.0)/(exp(-9.9999999999999996e-8) - 1.0))/(1666.6666666666668*X + 1.0) + 0.050000000000000003*E**2*F*(_membrane__V - 13.356169352749132*log(1.8/X)) + 1.1499999999999999*X/(X + 0.00050000000000000001) + 16.0*G**3*H*I*(_membrane__V - 26.712338705498264*log(132.0/D)) + 0.0070160275741043609*_membrane__V + 0.023862446088641736*J*K*(_membrane__V - 26.712338705498264*log(4.5/C))/(exp(0.044642857142857146*_membrane__V + 0.40178571428571431) + 1.0) + 0.433*L*M*N*(1.0 + 0.59999999999999998/(6.4818210260626453e-7*(1/X)**1.3999999999999999 + 1.0))*(_membrane__V - 26.712338705498264*log(6.9195599999999999/(C + 0.018329999999999999*D))) + 0.5*O**3*P*Q*(_membrane__V - 26.712338705498264*log(4.5/C))*exp(0.01*_membrane__V) + 0.00025000000000000001*(-2299968.0*X + 1.8*D**3*exp(0.037435883507802618*_membrane__V))*exp(-0.031820500981632226*_membrane__V)/(0.0001*(2299968.0*X + 1.8*D**3*exp(0.037435883507802618*_membrane__V))*exp(-0.031820500981632226*_membrane__V) + 1.0) + 0.0055199999999999997*(_membrane__V - 26.712338705498264*log(4.5/C))/(exp(1.2521739130434782 - 0.16722408026755852*_membrane__V) + 1.0) + 698.34626081908677*(_membrane__V - 26.712338705498264*log(4.5/C))/((1020.0/(exp(0.23849999999999999*_membrane__V - 6.3708927812613357*log(4.5/C) - 14.1227775) + 1.0) + 1000.0*(exp(0.061749999999999999*_membrane__V - 1.6494869150645178*log(4.5/C) - 36.698642499999996) + 0.49124000000000001*exp(0.080320000000000003*_membrane__V - 2.1455350448256206*log(4.5/C) + 0.43983232000000001))/(exp(-0.51429999999999998*_membrane__V + 13.738155796237757*log(4.5/C) - 2.4444679) + 1.0))*(exp(0.23849999999999999*_membrane__V - 6.3708927812613357*log(4.5/C) - 14.1227775) + 1.0)) + func(R)/Z - 0.040282206767891382*log(1.8/X) - 7.3656881518639836e-7*log(4.5/C) - 0.10684935482199306*log(132.0/D) + 1.6875/((1.0 + 100.0/D**2)*(0.036499999999999998*(0.14285714285714286*exp(1.961367013372957) - 0.14285714285714286)*exp(-0.037435883507802618*_membrane__V) + 0.1245*exp(-0.003743588350780262*_membrane__V) + 1.0)))/S < -150000.0, ITE(Abs(_membrane__V) < 2.6712338705498263e-6, 1.0*(7.801922635740725*B*Y*_membrane__V*(1.0*X*exp(0.074871767015605236*_membrane__V) - 0.61380000000000006)/((1666.6666666666668*X + 1.0)*(exp(0.074871767015605236*_membrane__V) - 1.0)) + 1.0*B*Y*(187179.4175390131*(_membrane__V + 2.6712338705498263e-6)*(1.8621604999999999e-9*(0.75*C*exp(-9.9999999999999996e-8) - 3.375)/(exp(-9.9999999999999996e-8) - 1.0) + 1.8621604999999999e-9*(0.75*C*exp(9.9999999999999996e-8) - 3.375)/(exp(9.9999999999999996e-8) - 1.0)) - 1.8621604999999999e-9*(0.75*C*exp(-9.9999999999999996e-8) - 3.375)/(exp(-9.9999999999999996e-8) - 1.0))/(1666.6666666666668*X + 1.0) + 1.0*B*Y*(187179.4175390131*(_membrane__V + 2.6712338705498263e-6)*(6.5127374999999997e-9*(0.75*D*exp(-9.9999999999999996e-8) - 99.0)/(exp(-9.9999999999999996e-8) - 1.0) + 6.5127374999999997e-9*(0.75*D*exp(9.9999999999999996e-8) - 99.0)/(exp(9.9999999999999996e-8) - 1.0)) - 6.5127374999999997e-9*(0.75*D*exp(-9.9999999999999996e-8) - 99.0)/(exp(-9.9999999999999996e-8) - 1.0))/(1666.6666666666668*X + 1.0) + 0.050000000000000003*E**2*F*(_membrane__V - 13.356169352749132*log(1.8/X)) + 1.1499999999999999*X/(X + 0.00050000000000000001) + 16.0*G**3*H*I*(_membrane__V - 26.712338705498264*log(132.0/D)) + 0.0070160275741043609*_membrane__V + 0.023862446088641736*J*K*(_membrane__V - 26.712338705498264*log(4.5/C))/(exp(0.044642857142857146*_membrane__V + 0.40178571428571431) + 1.0) + 0.433*L*M*N*(1.0 + 0.59999999999999998/(6.4818210260626453e-7*(1/X)**1.3999999999999999 + 1.0))*(_membrane__V - 26.712338705498264*log(6.9195599999999999/(C + 0.018329999999999999*D))) + 0.5*O**3*P*Q*(_membrane__V - 26.712338705498264*log(4.5/C))*exp(0.01*_membrane__V) + 0.00025000000000000001*(-2299968.0*X + 1.8*D**3*exp(0.037435883507802618*_membrane__V))*exp(-0.031820500981632226*_membrane__V)/(0.0001*(2299968.0*X + 1.8*D**3*exp(0.037435883507802618*_membrane__V))*exp(-0.031820500981632226*_membrane__V) + 1.0) + 0.0055199999999999997*(_membrane__V - 26.712338705498264*log(4.5/C))/(exp(1.2521739130434782 - 0.16722408026755852*_membrane__V) + 1.0) + 698.34626081908677*(_membrane__V - 26.712338705498264*log(4.5/C))/((1020.0/(exp(0.23849999999999999*_membrane__V - 6.3708927812613357*log(4.5/C) - 14.1227775) + 1.0) + 1000.0*(exp(0.061749999999999999*_membrane__V - 1.6494869150645178*log(4.5/C) - 36.698642499999996) + 0.49124000000000001*exp(0.080320000000000003*_membrane__V - 2.1455350448256206*log(4.5/C) + 0.43983232000000001))/(exp(-0.51429999999999998*_membrane__V + 13.738155796237757*log(4.5/C) - 2.4444679) + 1.0))*(exp(0.23849999999999999*_membrane__V - 6.3708927812613357*log(4.5/C) - 14.1227775) + 1.0)) + func(R)/Z - 0.040282206767891382*log(1.8/X) - 7.3656881518639836e-7*log(4.5/C) - 0.10684935482199306*log(132.0/D) + 1.6875/((1.0 + 100.0/D**2)*(0.036499999999999998*(0.14285714285714286*exp(1.961367013372957) - 0.14285714285714286)*exp(-0.037435883507802618*_membrane__V) + 0.1245*exp(-0.003743588350780262*_membrane__V) + 1.0)))/S < -150000.0, 1.0*(7.801922635740725*B*Y*_membrane__V*(1.0*X*exp(0.074871767015605236*_membrane__V) - 0.61380000000000006)/((1666.6666666666668*X + 1.0)*(exp(0.074871767015605236*_membrane__V) - 1.0)) + 0.00069711623550831475*B*Y*_membrane__V*(0.75*C*exp(0.037435883507802618*_membrane__V) - 3.375)/((1666.6666666666668*X + 1.0)*(exp(0.037435883507802618*_membrane__V) - 1.0)) + 0.0024381008236689765*B*Y*_membrane__V*(0.75*D*exp(0.037435883507802618*_membrane__V) - 99.0)/((1666.6666666666668*X + 1.0)*(exp(0.037435883507802618*_membrane__V) - 1.0)) + 0.050000000000000003*E**2*F*(_membrane__V - 13.356169352749132*log(1.8/X)) + 1.1499999999999999*X/(X + 0.00050000000000000001) + 16.0*G**3*H*I*(_membrane__V - 26.712338705498264*log(132.0/D)) + 0.0070160275741043609*_membrane__V + 0.023862446088641736*J*K*(_membrane__V - 26.712338705498264*log(4.5/C))/(exp(0.044642857142857146*_membrane__V + 0.40178571428571431) + 1.0) + 0.433*L*M*N*(1.0 + 0.59999999999999998/(6.4818210260626453e-7*(1/X)**1.3999999999999999 + 1.0))*(_membrane__V - 26.712338705498264*log(6.9195599999999999/(C + 0.018329999999999999*D))) + 0.5*O**3*P*Q*(_membrane__V - 26.712338705498264*log(4.5/C))*exp(0.01*_membrane__V) + 0.00025000000000000001*(-2299968.0*X + 1.8*D**3*exp(0.037435883507802618*_membrane__V))*exp(-0.031820500981632226*_membrane__V)/(0.0001*(2299968.0*X + 1.8*D**3*exp(0.037435883507802618*_membrane__V))*exp(-0.031820500981632226*_membrane__V) + 1.0) + 0.0055199999999999997*(_membrane__V - 26.712338705498264*log(4.5/C))/(exp(1.2521739130434782 - 0.16722408026755852*_membrane__V) + 1.0) + 698.34626081908677*(_membrane__V - 26.712338705498264*log(4.5/C))/((1020.0/(exp(0.23849999999999999*_membrane__V - 6.3708927812613357*log(4.5/C) - 14.1227775) + 1.0) + 1000.0*(exp(0.061749999999999999*_membrane__V - 1.6494869150645178*log(4.5/C) - 36.698642499999996) + 0.49124000000000001*exp(0.080320000000000003*_membrane__V - 2.1455350448256206*log(4.5/C) + 0.43983232000000001))/(exp(-0.51429999999999998*_membrane__V + 13.738155796237757*log(4.5/C) - 2.4444679) + 1.0))*(exp(0.23849999999999999*_membrane__V - 6.3708927812613357*log(4.5/C) - 14.1227775) + 1.0)) + func(R)/Z - 0.040282206767891382*log(1.8/X) - 7.3656881518639836e-7*log(4.5/C) - 0.10684935482199306*log(132.0/D) + 1.6875/((1.0 + 100.0/D**2)*(0.036499999999999998*(0.14285714285714286*exp(1.961367013372957) - 0.14285714285714286)*exp(-0.037435883507802618*_membrane__V) + 0.1245*exp(-0.003743588350780262*_membrane__V) + 1.0)))/S < -150000.0))), (-500.0*A, True))
>>>
>>> piecewise_fold(P1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\functions\elementary\piecewise.py", line 1065, in piecewise_fold
    c = simplify_logic(c, form='cnf')
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\logic\boolalg.py", line 2806, in simplify_logic
    s = [simplify(v) for v in variables]
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\logic\boolalg.py", line 2806, in <listcomp>
    s = [simplify(v) for v in variables]
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\simplify\simplify.py", line 561, in simplify
    return _eval_simplify(**kwargs)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\relational.py", line 306, in _eval_simplify
    r = r.func(*[i.simplify(**kwargs) for i in r.args])
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\relational.py", line 306, in <listcomp>
    r = r.func(*[i.simplify(**kwargs) for i in r.args])
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\basic.py", line 1671, in simplify
    return simplify(self, **kwargs)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\simplify\simplify.py", line 604, in simplify
    _e = cancel(expr)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\polys\polytools.py", line 6686, in cancel
    R, (F, G) = sring((p, q), *gens, **args)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\polys\rings.py", line 163, in sring
    reps, opt = _parallel_dict_from_expr(exprs, opt)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\polys\polyutils.py", line 325, in _parallel_dict_from_expr
    exprs = [ expr.expand() for expr in exprs ]
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\polys\polyutils.py", line 325, in <listcomp>
    exprs = [ expr.expand() for expr in exprs ]
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\expr.py", line 3570, in expand
    expr, hit = Expr._expand_hint(expr, hint, deep=deep, **hints)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\expr.py", line 3503, in _expand_hint
    arg, arghit = Expr._expand_hint(arg, hint, **hints)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\expr.py", line 3511, in _expand_hint
    newexpr = getattr(expr, hint)(**hints)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\mul.py", line 894, in _eval_expand_mul
    terms = self.func._expandsums(sums)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\mul.py", line 859, in _expandsums
    terms = [Mul(a, b) for a in left for b in right]
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\mul.py", line 859, in <listcomp>
    terms = [Mul(a, b) for a in left for b in right]
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\operations.py", line 85, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\mul.py", line 285, in flatten
    coeff *= o
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\numbers.py", line 2217, in __mul__
    return Rational.__mul__(self, other)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\decorators.py", line 96, in __sympifyit_wrapper
    return func(a, b)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\numbers.py", line 1755, in __mul__
    return other*self
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\decorators.py", line 96, in __sympifyit_wrapper
    return func(a, b)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\core\numbers.py", line 1320, in __mul__
    return Float._new(mlib.mpf_mul(self._mpf_, rhs, prec, rnd), prec)
  File "C:\Users\uczmh2\AppData\Local\Programs\Python\Python39\lib\site-packages\mpmath\libmp\libmpf.py", line 889, in python_mpf_mul
    man = sman*tman
KeyboardInterrupt
>>>
```

**Comment by smichr** [comment]
My guess is that simplification is being used and it is hanging there. Using `piecewise_fold` on the `cse` expression does not hang:
```python
>>> cse(eq)  # where eq is your expression
([(x0, Abs(_membrane__V)), (x1, 1/S), (x2, B*Y/(1666.66666666667*X + 1.0)), (x3, 1.0*x2), (x4, 187179.417539013*_membrane__V + 0.5), (x5, log(132.0/D)), (x6, 1/X), (x7, log(1.8*x6)), (x8, 1/C), (x9, log(4.5*x8)), (x10, 0.0374358835078026*_membrane__V), (x11, exp(-0.0318205009816322*_membrane__V)), (x12, exp(x10)), (x13, D**3*x12), (x14, 1/(5.07000951006702e-11*x8**(-6.37089278126134)*exp(0.2385*_membrane__V) + 1.0)), (x15, _membrane__V - 26.7123387054983*x9), (x16, 0.05*E**2*F*(_membrane__V - 13.3561693527491*x7) + 16.0*G**3*H*I*(_membrane__V - 26.7123387054983*x5) + 0.0238624460886417*J*K*x15/(1.49449105027909*exp(0.0446428571428571*_membrane__V) + 1.0) + 0.433*L*M*N*(1.0 + 0.6/(6.48182102606265e-7*x6**1.4 + 1.0))*(_membrane__V - 26.7123387054983*log(6.91956/(C + 0.01833*D))) + 0.5*O**3*P*Q*x15*exp(0.01*_membrane__V) + 1.15*X/(X + 0.0005) + 0.00701602757410436*_membrane__V + 1.0*x11*(-574.992*X + 0.00045*x13)/(x11*(229.9968*X + 0.00018*x13) + 1.0) + 1.0*x14*(698.346260819087*_membrane__V - 18654.4618527177*x9)/(1020.0*x14 + (30.2566005849132*x8**(-2.14553504482562)*exp(0.08032*_membrane__V) + 9.64976139044134e-15*x8**(-1.64948691506452)*exp(0.06175*_membrane__V))/(81717742.8102406*x8**13.7381557962378*exp(-0.5143*_membrane__V) + 1.0)) - 0.106849354821993*x5 - 0.0402822067678914*x7 - 7.36568815186398e-7*x9 + 1.0*(0.00552*_membrane__V - 0.14745210965435*x9)/(1.0 + 3.49793891302524*exp(-0.167224080267559*_membrane__V)) + 1.6875/((1.0 + 100.0/D**2)*(1.0 + 0.0318542725777997*exp(-x10) + 0.1245*exp(-0.00374358835078026*_membrane__V))) + 1.0*func(R)/Z), (x17, x16 + x3*(0.0139662030584829*C + x4*(1.39773666078813e-9*C + 6.27976839973066e-9) - 0.0628479200479647) + x3*(0.0488455288314816*D + x4*(4.88845723622955e-9*D + 6.44245671033161e-7) - 6.44761045051659)), (x18, exp(0.0748717670156052*_membrane__V)), (x19, _membrane__V*x2), (x20, 7.80192263574073*x19*(1.0*X*x18 - 0.6138)/(x18 - 1.0)), (x21, 0.75*x12), (x22, x19/(x12 - 1.0))], [Piecewise((100000.0 - 100500.0*A, ITE(x0 < 1.33561693527491e-6, x1*(x17 + x3*(104.203794840494*X + (1.04287087623334e-5*X + 6.3909170506804e-6)*(374358.835078026*_membrane__V + 0.5) - 63.9602956691246)) < -150000.0, ITE(x0 < 2.67123387054983e-6, x1*(x17 + x20) < -150000.0, x1*(x16 + x20 + 0.000697116235508315*x22*(C*x21 - 3.375) + 0.00243810082366898*x22*(D*x21 - 99.0)) < -150000.0))), (-500.0*A, True))])
))), (-500.0*A, True))''') + 0.00243810082366898*x22*(D*x21 - 99.0)) < -150000.0)
>>> ee
Piecewise((100000.0 - 100500.0*A, ITE(x0 < 1.33561693527491e-6, x1*(x17 + x3*(104.203794840494*X + (1.04287087623334e-5*X + 6.3909170506804e-6)*(374358.835078026*_membrane__V + 0.5) - 63.9602956691246)) < -150000.0, ITE(x0 < 2.67123387054983e-6, x1*(x17 + x20) < -150000.0, x1*(x16 + x20 + 0.000697116235508315*x22*(C*x21 - 3.375) + 0.00243810082366898*x22*(D*x21 - 99.0)) < -150000.0))), (-500.0*A, True))
>>> piecewise_fold(ee)
Piecewise((100000.0 - 100500.0*A, ((x0 >= 2.67123387054983e-6) | (x0 < 1.33561693527491e-6) | (x1*(x17 + x20) < -150000.0)) & ((x0 >= 1.33561693527491e-6) | (x1*(x17 + x3*(104.203794840494*X + (1.04287087623334e-5*X + 6.3909170506804e-6)*(374358.835078026*_membrane__V + 0.5) - 63.9602956691246)) < -150000.0)) & ((x0 < 1.33561693527491e-6) | (x0 < 2.67123387054983e-6) | (x1*(x16 + x20 + 0.000697116235508315*x22*(C*x21 - 3.375) + 0.00243810082366898*x22*(D*x21 - 99.0)) < -150000.0))), (-500.0*A, True))
```

**Comment by MauriceHendrix** [comment]
> My guess is that simplification is being used and it is hanging there. Using `piecewise_fold` on the `cse` expression does not hang:
...
> ```

Is there any reliable way to prevent (early) simplification? We've been fighting it at every corner so far.

**Comment by oscarbenjamin** [comment]
> Is there any reliable way to prevent (early) simplification? We've been fighting it at every corner so far.

The call to simplify should be removed somehow.

**Comment by smichr** [comment]
> > My guess is that simplification is being used and it is hanging there. Using `piecewise_fold` on the `cse` expression does not hang:
> > ...
> 
> Is there any reliable way to prevent (early) simplification? We've been fighting it at every corner so far.

fold the cse form and backsubstitute to get the folded expression (`e` in the following)?
```python
r, e = cse(eq)
e = piecewise_fold(eq[0])
for o, n in reversed(r):
    e = e.xreplace({o: n})
```

**Comment by MauriceHendrix** [comment]
> > > My guess is that simplification is being used and it is hanging there. Using `piecewise_fold` on the `cse` expression does not hang:
> > > ...
> > 
> > 
> > Is there any reliable way to prevent (early) simplification? We've been fighting it at every corner so far.
> 
> fold the cse form and backsubstitute to get the folded expression (`e` in the following)?
> 
> ```python
> r, e = cse(eq)
> e = piecewise_fold(e[0])
> for o, n in reversed(r):
>     e = e.xreplace({o: n})
> ```

that does work, but feels a bit like a horrible hack!

**Comment by oscargus** [comment]
I think part of the problem here is that ITE is not/should not be used for general expressions. It is inherently a Boolean function. 

Probably there is a need for something similar though, to be able to write two-part Piecewises in a simpler way than a Piecewise (if nothing else to be able to generate code using C-like `x ? y : z`).

**Comment by MauriceHendrix** [comment]
> Probably there is a need for something similar though, to be able to write two-part Piecewises in a simpler way than a Piecewise (if nothing else to be able to generate code using C-like `x ? y : z`).

IIRC it's our Piecewise that gets simplified to an ITE, we certainly don't generate ITEs
