### ISSUE TITLE
Reassigning values to variable in Manifold

### ISSUE THREAD

**Issue by che2712** [sympy/sympy#20859]
>>> from sympy.diffgeom import Manifold
    >>> m = Manifold('M', 2)
    >>> m
    M
    >>> m.dim
    2
>>> m = Manifold('N', 2)
Exception in SymPy Live of type 
<class 'sympy.core.sympify.SympifyError'>
for reference the last 5 stack trace entries are
Traceback (most recent call last):
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/handlers.py", line 271, in post
    live.evaluate(statement, session, printer, stream)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/shell.py", line 284, in evaluate
    session_globals_dict = session.globals_dict()
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/models.py", line 87, in globals_dict
    for name, val in zip(self.global_names, self.globals))
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/models.py", line 87, in <genexpr>
    for name, val in zip(self.global_names, self.globals))
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/39c5fa12ec80ea1d/python27/python27_dist/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
SympifyError: Sympify of expression 'could not parse u'<function N at 0x3ef373b6ced8>'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)

**Comment by 0sidharth** [comment]
On current master -
```py
>>> from sympy.diffgeom import Manifold
>>> m = Manifold('M', 2)
>>> m
M
>>> m.dim
2
>>> m = Manifold('N', 2)
>>> m
N
>>> m.dim
2
```
I think the behaviour was changed in 1.7

**Comment by che2712** [comment]
> On current master -
> 
> ```python
> >>> from sympy.diffgeom import Manifold
> >>> m = Manifold('M', 2)
> >>> m
> M
> >>> m.dim
> 2
> >>> m = Manifold('N', 2)
> >>> m
> N
> >>> m.dim
> 2
> ```
> 
> I think the behaviour was changed in 1.7

Yes, it has been changed, I am closing the issue.
