### ISSUE TITLE
Poly(x + 9671406556917067856609794, x).real_roots() is slow

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#20913]
```py
In [1]: %time Poly(x + 9671406556917067856609794, x).real_roots()
CPU times: user 7.42 s, sys: 24.8 ms, total: 7.45 s
Wall time: 7.46 s
Out[1]: [-9671406556917067856609794]
```

It seems to be spending most of the time factoring 9671406556917067856609794:

```py
In [2]: %time factorint(9671406556917067856609794)
CPU times: user 7.36 s, sys: 16.2 ms, total: 7.38 s
Wall time: 7.39 s
Out[2]: {2: 1, 13: 1, 131409534701: 1, 2830671123769: 1}
```

Here's a traceback from keyboard interrupting it

```pytb
>>> Poly(x + 9671406556917067856609794, x).real_roots()
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/polys/polytools.py", line 3572, in real_roots
    reals = sympy.polys.rootoftools.CRootOf.real_roots(f, radicals=radicals)
  File "./sympy/polys/rootoftools.py", line 405, in real_roots
    return cls._get_roots("_real_roots", poly, radicals)
  File "./sympy/polys/rootoftools.py", line 750, in _get_roots
    coeff, poly = cls._preprocess_roots(poly)
  File "./sympy/polys/rootoftools.py", line 714, in _preprocess_roots
    coeff, poly = preprocess_roots(poly)
  File "./sympy/polys/polyroots.py", line 773, in preprocess_roots
    basis = _integer_basis(poly)
  File "./sympy/polys/polyroots.py", line 696, in _integer_basis
    divs = reversed(divisors(gcd_list(coeffs))[1:])
  File "./sympy/ntheory/factor_.py", line 1599, in divisors
    return sorted(rv)
  File "./sympy/ntheory/factor_.py", line 1531, in _divisors
    factordict = factorint(n)
  File "./sympy/ntheory/factor_.py", line 1371, in factorint
    seed=high_)
  File "./sympy/ntheory/factor_.py", line 637, in pollard_rho
    if max_steps and (j > max_steps):
KeyboardInterrupt
```

**Comment by oscarbenjamin** [comment]
Is it not expected that finding a 12 digit prime factor would be slow?

**Comment by asmeurer** [comment]
factorint being slow is expected. But why does Poly need to call it to find the roots of a linear polynomial?

**Comment by asmeurer** [comment]
In general, finding rational roots via the rational root theorem does make use of divisors, which uses factorint. But I wonder if factorint and divisors should gain a `generator` flag that makes it yield the factors/divisors as they are found. Then algorithms like the rational root theorem that have the potential to exit early on small factors have a chance to do so (the idea may sound rather niche, but I've also often used `factorint` on large numbers and would appreciate being able to see the factors as they are found, other than via the `verbose=True` output).

**Comment by oscarbenjamin** [comment]
In this particular case it is not the rational root theorem but `_integer_basis` that is slow. It can probably be made faster for this case as for a poly like `a*x + b` all it does is either return `abs(b)` or `None`.
