### ISSUE TITLE
TypeErrors appearing for simple plynomial manipulations (did not happen in v1.6.1)

### ISSUE THREAD

**Issue by mgely** [sympy/sympy#20985]
Here is a minimal working example of the bug:
```
import sympy as sp 
w = sp.Symbol('w')
R = sp.Symbol('R')
poly =  1.0 + sp.I*w/R
sp.polys.polytools.degree(poly, gen=w)
```
Which produces the following error traceback:
```
Traceback (most recent call last):
  File "C:\Users\Mario\Desktop\test.py", line 5, in <module>
    print(sp.polys.polytools.degree(poly, gen=w))
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\polytools.py", line 4466, in degree
    p, _ = poly_from_expr(f, gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\polytools.py", line 4273, in poly_from_expr
    return _poly_from_expr(expr, opt)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\polytools.py", line 4303, in _poly_from_expr
    opt.domain, coeffs = construct_domain(coeffs, opt=opt)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\constructor.py", line 286, in construct_domain
    result = _construct_composite(coeffs, opt)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\constructor.py", line 243, in _construct_composite
    result.append(domain((numer, denom)))
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\domains\domain.py", line 84, in __call__
    return self.new(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\domains\fractionfield.py", line 38, in new
    return self.field.field_new(element)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\fields.py", line 217, in field_new
    return self.new(numer, denom)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\fields.py", line 166, in new
    numer, denom = numer.cancel(denom)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\rings.py", line 2219, in cancel
    if q.is_negative:
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\rings.py", line 847, in is_negative
    return self.ring.domain.is_negative(self.LC)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sympy\polys\domains\domain.py", line 450, in is_negative
    return a < 0
TypeError: '<' not supported between instances of 'ComplexElement' and 'int'

```

**Comment by oscarbenjamin** [comment]
In SymPy 1.6.1 the domain of the poly is EX. However in current master the domain is `CC(w)`:
```python
In [1]: Poly(1.0 + I*x/y, x)
Out[1]: Poly(1.0*I/y*x + 1.0, x, domain='CC(y)')
```
The fraction field `CC(y)` expects the base domain `CC` to have methods like `is_negative`. For `ZZ_I` and `QQ_I` these are all set to return False so we can do the same with `CC`. This diff fixes the problem:
```diff
diff --git a/sympy/polys/domains/complexfield.py b/sympy/polys/domains/complexfield.py
index a10e0b1eff..7bbce6d388 100644
--- a/sympy/polys/domains/complexfield.py
+++ b/sympy/polys/domains/complexfield.py
@@ -101,6 +101,22 @@ def get_exact(self):
         """Returns an exact domain associated with ``self``. """
         raise DomainError("there is no exact domain associated with %s" % self)
 
+    def is_negative(self, element):
+        """Returns ``False`` for any ``ComplexElement``. """
+        return False
+
+    def is_positive(self, element):
+        """Returns ``False`` for any ``ComplexElement``. """
+        return False
+
+    def is_nonnegative(self, element):
+        """Returns ``False`` for any ``ComplexElement``. """
+        return False
+
+    def is_nonpositive(self, element):
+        """Returns ``False`` for any ``ComplexElement``. """
+        return False
+
     def gcd(self, a, b):
         """Returns GCD of ``a`` and ``b``. """
         return self.one
```
With that we get:
```python
In [2]: import sympy as sp
   ...: w = sp.Symbol('w')
   ...: R = sp.Symbol('R')
   ...: poly =  1.0 + sp.I*w/R
   ...: sp.polys.polytools.degree(poly, gen=w)
Out[2]: 1
```
I'm marking this as easy to fix.

**Comment by Sohan022** [comment]
I would like to work on this issue.

**Comment by oscarbenjamin** [comment]
Go ahead.

Tests should be added for each of the new methods in `sympy/polys/domains/tests/test_domains.py`. A test for degree should be added in `sympy/polys/tests/test_polytools.py`.

**Comment by oscarbenjamin** [comment]
There should also be a test for `Poly(1.0*I/y*x + 1.0, x, domain='CC(y)')`
