### ISSUE TITLE
sympy.polys.polyerrors.CoercionFailed integration regressions?

### ISSUE THREAD

**Issue by mpeychev** [sympy/sympy#21024]
Hello,

I have come across the following expressions (`f`) which can be integrated by SymPy 1.4 in the following way:

```
>>> from sympy import *
>>> x = Symbol('x', real=True, nonzero=True)
>>> f = (x+exp(3))/x**2
>>> integrate(f, x)
```

(The `F`'s below are the results returned by the integration) but the integration (`integrate(f, x)`) fails in SymPy 1.7.1, raising a `CoercionFailed` error:

```
...
File ".../python3.9/site-packages/sympy/polys/domains/domain.py", line 160, in convert
    raise CoercionFailed("can't convert %s of type %s to %s" % (element, type(element), self))
```

```
f = (x + exp(3))/x**2
F = log(x) - exp(3)/x

f = (x**2 + exp(5))/x
F = x**2/2 + exp(5)*log(x)

f = x/(2*x + tanh(1))
F = x/2 - log(2*x + tanh(1))*tanh(1)/4

f = x - sinh(4)/x
F = x**2/2 - log(x)*sinh(4)

f = log(x + exp(5)/x)
F = x*log(x + exp(5)/x) - x + 2*exp(5/2)*atan(x*exp(-5/2))

f = x**5/(x + E)
F = x**5/5 - E*x**4/4 + x**3*exp(2)/3 - x**2*exp(3)/2 + x*exp(4) - exp(5)*log(x + E)

f = 4*x/(x + sinh(5))
F = 4*x - 4*log(x + sinh(5))*sinh(5)

f = x**2/(2*x + sinh(2))
F = x**2/4 - x*sinh(2)/4 + (-1 + E)**2*(1 + E)**2*(1 + exp(2))**2*exp(-4)*log(2*x + sinh(2))/32

f = -x**2/(x + E)
F = -x**2/2 + E*x - exp(2)*log(x + E)

f = (2*x + 3)*exp(5)/x
F = 2*x*exp(5) + 3*exp(5)*log(x)

f = x + 2 + cosh(3)/x
F = x**2/2 + 2*x + log(x)*cosh(3)

f = x - tanh(1)/x**3
F = x**2/2 + tanh(1)/(2*x**2)

f = (3*x - exp(6))/x
F = 3*x - exp(6)*log(x)

f = x**4/(x + exp(5))**2 + x
F = x**3/3 + x**2*(1/2 - exp(5)) + 3*x*exp(10) - 4*exp(15)*log(x + exp(5)) - exp(20)/(x + exp(5))

f = x*(x + exp(10)/x**2) + x
F = x**3/3 + x**2/2 + exp(10)*log(x)

f = x + x/(5*x + sinh(3))
F = x**2/2 + x/5 - log(5*x + sinh(3))*sinh(3)/25

f = (x + exp(3))/(2*x**2 + 2*x)
F = exp(3)*log(x)/2 - (-1 + E)*(1 + E + exp(2))*log(x + ((-1 + E)*(1 + E + exp(2)) + exp(3))/(-1 + 2*exp(3)))/2

f = log(x + 4*sinh(4))
F = x*log(x + 4*sinh(4)) - x + 4*log(x + 4*sinh(4))*sinh(4)

f = -x + 20*(exp(-5) - atan(4)/x)**3*sin(4)/x
F = (-x**2*exp(15)/2 + 20*log(x)*sin(4) + (180*x**2*exp(5)*sin(4)*atan(4) - 90*x*exp(10)*sin(4)*atan(4)**2 + 20*exp(15)*sin(4)*atan(4)**3)/(3*x**3))*exp(-15)

f = 2*x**2*exp(-4) + 6/x
F_true = (2*x**3/3 + 6*exp(4)*log(x))*exp(-4)
```

I can provide more examples. Is this a regression, or the difference in the behaviour is due to some bug fixes in the development process between the library updates, or you cannot reproduce the problem and the issue is on my side?

Thank you

**Comment by oscarbenjamin** [comment]
I've bisected the failure between 1.4 and 1.7.1 to 197ac0069b769b28324e47e481bbd90822a5bb65 in #19646 (CC @sachin-4099 @jksuom).

This seems to be fixed though on the current master branch (since 1.7.1). I've bisected that fix to 83a0c0d088336a8167d3198bd0cbf079d02040d6 from #20274.

It's possible though that the "fix" is only hiding the problem...

**Comment by oscarbenjamin** [comment]
Have you tested your examples with current sympy master?

**Comment by mpeychev** [comment]
Hi, thank you for the quick and useful reply!
I tested the examples above on the SymPy master version (1.8.dev0). All of them completed successfully.

Some of the integration results took an alternative form compared to the one pasted above. I am including them here for completeness.

```
f = x/(2*x + tanh(1))
F = x/2 - (-1 + E)*(1 + E)*log(2*x + tanh(1))/(4*(1 + exp(2)))

f = x - sinh(4)/x
F = x**2/2 - (-1 + E)*(1 + E)*(1 + exp(2))*(1 + exp(4))*exp(-4)*log(x)/2

f = 4*x/(x + sinh(5))
F = 4*x - 2*(-1 + E)*(1 + E)*(1 + E + exp(2) + exp(3) + exp(4))*(-exp(3) - E + 1 + exp(2) + exp(4))*exp(-5)*log(x + sinh(5))

f = x + 2 + cosh(3)/x
F = x**2/2 + 2*x + (1 + exp(2))*(-exp(2) + 1 + exp(4))*exp(-3)*log(x)/2

f = x - tanh(1)/x**3
F = x**2/2 + (-1 + exp(2))/(x**2*(2 + 2*exp(2)))

f = x + x/(5*x + sinh(3))
F = x**2/2 + x/5 - (-1 + E)*(1 + E)*(1 + E + exp(2))*(-E + 1 + exp(2))*exp(-3)*log(5*x + sinh(3))/50

f = (x + exp(3))/(2*x**2 + 2*x)
F = exp(3)*log(x)/2 + (1/2 - exp(3)/2)*log(x + 1)

f = log(x + 4*sinh(4))
F = x*log(x + 4*sinh(4)) - x + 2*(-1 + E)*(1 + E)*(1 + exp(2))*(1 + exp(4))*exp(-4)*log(x + 4*sinh(4))
```

Feel free to close the issue if you see it as resolved.
Should I try to include some of these examples as regression tests?

Thank you

**Comment by oscarbenjamin** [comment]
The underlying bug is still there in master although the integrals now work:
```python
In [1]: z = exp(3)

In [2]: z
Out[2]: 
 3
ℯ 

In [3]: domain, elements = construct_domain([z])

In [4]: domain
Out[4]: ZZ[E]

In [5]: elements
Out[5]: [E**3]

In [6]: domain.convert(z)
---------------------------------------------------------------------------
CoercionFailed                            Traceback (most recent call last)
<ipython-input-6-5d8fc6e882bd> in <module>
----> 1 domain.convert(z)

~/current/sympy/sympy/sympy/polys/domains/domain.py in convert(self, element, base)
    461                     pass
    462 
--> 463         raise CoercionFailed("can't convert %s of type %s to %s" % (element, type(element), self))
    464 
    465     def of_type(self, element):

CoercionFailed: can't convert exp(3) of type exp to ZZ[E]
```
It fails because `PolynomialRing.convert` does not recognise the function `exp(3)` as being the power `E**3`.

That can be fixed with:
```diff
diff --git a/sympy/polys/rings.py b/sympy/polys/rings.py
index fa5970caa8..549712e4d5 100644
--- a/sympy/polys/rings.py
+++ b/sympy/polys/rings.py
@@ -380,10 +380,14 @@ def _rebuild(expr):
                 return reduce(add, list(map(_rebuild, expr.args)))
             elif expr.is_Mul:
                 return reduce(mul, list(map(_rebuild, expr.args)))
-            elif expr.is_Pow and expr.exp.is_Integer and expr.exp >= 0:
-                return _rebuild(expr.base)**int(expr.exp)
             else:
-                return self.ground_new(domain.convert(expr))
+                # XXX: Use as_base_exp() to handle Pow(x, n) and also exp(n)
+                # XXX: E can be a generator e.g. sring([exp(2)]) -> ZZ[E]
+                base, exp = expr.as_base_exp()
+                if exp.is_Integer and exp > 1:
+                    return _rebuild(base)**int(exp)
+                else:
+                    return self.ground_new(domain.convert(expr))
 
         return _rebuild(sympify(expr))
```
I'm going to mark this as easy to fix.  These things should be done to close the issue.

1. Applying the diff I showed above.
2. Adding a test for `from_expr` in `sympy/polys/tests/test_rings.py`.
3. Adding a test for `domain.convert` (as shown above) to `sympy/polys/tests/test_domains.py`.
4. Adding the integral examples the tests in `sympy/integrals` somewhere.


Another problem remains though which is that some of these examples have combinations of `exp` and e.g. `sinh` and I'm not sure how the domain system should handle those. I think that should be deal with in a separate issue. We have e.g.:
```python
In [17]: dom, [e, s] = construct_domain([exp(1), sinh(1)])

In [18]: dom
Out[18]: ZZ[E,sinh(1)]

In [19]: e
Out[19]: E

In [20]: s
Out[20]: (sinh(1))

In [21]: expand(sinh(1).rewrite(exp)*exp(1))
Out[21]: 
       2
  1   ℯ 
- ─ + ──
  2   2 

In [22]: s*e
Out[22]: E*(sinh(1))
```
Here the ring `ZZ[E,sinh(1)]` has an algebraic relationship among the generators since if `e = E` and `s = sinh(1)` then `e**2 - 2*s*e - 1 = 0`.

**Comment by mpeychev** [comment]
As a short follow up, I found the following expression to fail under the master version with the same kind of error:

```
f = log(x)*log(4*x) + log(3*x + exp(2))
F = x*log(x)**2 + x*log(3*x + exp(2)) + x*(1 - 2*log(2)) + (-2*x + 2*x*log(2))*log(x) + exp(2)*log(3*x + exp(2))/3
```

**Comment by Mohammad-debug** [comment]
@oscarbenjamin I have added the above integral [test-cases](https://github.com/sympy/sympy/issues/21024#issue-820435825) in my draft pull request #21085  but they did not pass the tests.

>     4. Adding the integral examples the tests in `sympy/integrals`    
I faced the following issue.

```
>  f = x/(2*x + tanh(1))
>  F = x/2 - log(2*x + tanh(1))*tanh(1)/4
>  assert F == integrate(f, x)
Traceback (most recent call last):
  File "/home/anas/OSS/Code/Python.py", line 9, in <module>
    assert F==integrate(f, x)

>  F=integrate(f, x)
>  print(F)
x/2 - (-1 + E)*(1 + E)*log(2*x + tanh(1))/(4*(1 + exp(2)))
```
Should I remove these testcases as the results are same just the answer is in a different form.

**Comment by oscarbenjamin** [comment]
If the answer is correct and is just given in a different form then you can change the test to match what is actually returned by integrate.
```python
In [15]: F1 = x/2 - log(2*x + tanh(1))*tanh(1)/4

In [16]: F2 = x/2 - (-1 + E)*(1 + E)*log(2*x + tanh(1))/(4*(1 + exp(2)))

In [17]: cancel(expand(F1 - F2).rewrite(tanh))
Out[17]: 0
```
In general the answers can differ by a constant. The most important thing is that `integrate` returns a valid antiderivative:
```python
In [32]: f = x/(2*x + tanh(1))

In [33]: simplify(f - F1.diff(x))
Out[33]: 0

In [34]: simplify(f - F2.diff(x)).rewrite(tanh).cancel()
Out[34]: 0
```

**Comment by Mohammad-debug** [comment]
@oscarbenjamin I have added the test cases. Please have a look.
