### ISSUE TITLE
Fail to differentiate some element-wise matrix expressions.

### ISSUE THREAD

**Issue by sangongs** [sympy/sympy#21062]
Differentiating matrix expressions with element-wise operations works in simple cases. But most of time SymPy raises an error:
```
>>> x = MatrixSymbol('x', n, 1)
>>> M = MatrixSymbol('M', m, n)
>>> diff(x.applyfunc(exp), x)
DiagMatrix(Lambda(_d, exp(_d)).(x))
>>> diff((M*x).applyfunc(exp), x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/guoqiang/sympy/venv/lib/python3.6/site-packages/sympy/core/function.py", line 2492, in diff
    return f.diff(*symbols, **kwargs)
  File "/Users/guoqiang/sympy/venv/lib/python3.6/site-packages/sympy/core/expr.py", line 3474, in diff
    return _derivative_dispatch(self, *symbols, **assumptions)
  File "/Users/guoqiang/sympy/venv/lib/python3.6/site-packages/sympy/core/function.py", line 1941, in _derivative_dispatch
    return ArrayDerivative(expr, *variables, **kwargs)
  File "/Users/guoqiang/sympy/venv/lib/python3.6/site-packages/sympy/tensor/array/array_derivatives.py", line 17, in __new__
    obj = super(ArrayDerivative, cls).__new__(cls, expr, *variables, **kwargs)
  File "/Users/guoqiang/sympy/venv/lib/python3.6/site-packages/sympy/core/function.py", line 1468, in __new__
    obj = cls._dispatch_eval_derivative_n_times(expr, v, count)
  File "/Users/guoqiang/sympy/venv/lib/python3.6/site-packages/sympy/tensor/array/array_derivatives.py", line 116, in _dispatch_eval_derivative_n_times
    result = cls._call_derive_default(expr, v)
  File "/Users/guoqiang/sympy/venv/lib/python3.6/site-packages/sympy/tensor/array/array_derivatives.py", line 75, in _call_derive_default
    return _matrix_derivative(expr, v)
  File "/Users/guoqiang/sympy/venv/lib/python3.6/site-packages/sympy/matrices/expressions/matexpr.py", line 647, in _matrix_derivative
    lines = expr._eval_derivative_matrix_lines(x)
  File "/Users/guoqiang/sympy/venv/lib/python3.6/site-packages/sympy/matrices/expressions/applyfunc.py", line 158, in _eval_derivative_matrix_lines
    validator=CodegenArrayDiagonal._validate
  File "/Users/guoqiang/sympy/venv/lib/python3.6/site-packages/sympy/core/expr.py", line 4001, in __init__
    self.validate()
  File "/Users/guoqiang/sympy/venv/lib/python3.6/site-packages/sympy/core/expr.py", line 4011, in validate
    self.validator(*args)
  File "/Users/guoqiang/sympy/venv/lib/python3.6/site-packages/sympy/codegen/array_utils.py", line 674, in _validate
    raise ValueError("diagonalizing indices of different dimensions")
ValueError: diagonalizing indices of different dimensions

Reproduced with SymPy 1.7.1.

**Comment by oscarbenjamin** [comment]
CC @Upabjojr

**Comment by Upabjojr** [comment]
Hi, the matrix derivation algorithm is in the process of being rewritten. You can use the new algorithm (provided that you check out the latest SymPy master branch, or wait for the next SymPy version 1.8 to be released):

```python
In [5]: x = MatrixSymbol('x', n, 1)

In [6]: M = MatrixSymbol('M', m, n)

In [7]: from sympy.tensor.array.expressions.arrayexpr_derivatives import array_derive

In [8]: array_derive(x.applyfunc(exp), x)
Out[8]: ArrayDiagonal(ArrayTensorProduct(Lambda(_d, exp(_d)).(x), I, I), (0, 3), (1, 5))

In [9]: from sympy.tensor.array.expressions.conv_array_to_matrix import convert_array_to_matrix

In [10]: convert_array_to_matrix(array_derive(x.applyfunc(exp), x))
Out[10]: DiagMatrix(Lambda(_d, exp(_d)).(x))
```

and

```python
In [13]: array_derive((M*x).applyfunc(exp), x)
Out[13]: ArrayDiagonal(ArrayContraction(ArrayTensorProduct(Lambda(_d, exp(_d)).(M*x), I, I, M), (3, 7)), (0, 5), (1, 4))

In [14]: convert_array_to_matrix(array_derive((M*x).applyfunc(exp), x))
Out[14]:
 T
M ⋅DiagMatrix(Lambda(_d, exp(_d)).(M*x))
```

**Comment by sangongs** [comment]
@Upabjojr That looks amazing! Thanks for the work. Looking forward to the new release.
