### ISSUE TITLE
Bug in is_eq

### ISSUE THREAD

**Issue by almighty123789** [sympy/sympy#21073]
I found this issue while workin on issue #21063 . 
```
>>> from sympy.core.relational import is_eq
>>> a = S.Zero
>>> b = 0
>>> is_eq(a,b)
Traceback (most recent call last):
  File "C:\Users\2acha\Desktop\GSOC\sympy\sympy\multipledispatch\dispatcher.py", line 234, in __call__
    func = self._cache[types]
KeyError: (<class 'sympy.core.numbers.Zero'>, <class 'int'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\2acha\Desktop\GSOC\sympy\sympy\core\relational.py", line 1314, in is_eq
    retval = _eval_is_eq(lhs, rhs)
  File "C:\Users\2acha\Desktop\GSOC\sympy\sympy\multipledispatch\dispatcher.py", line 238, in __call__
    raise NotImplementedError(
NotImplementedError: Could not find signature for _eval_is_eq: <Zero, int>
```

**Comment by oscarbenjamin** [comment]
The `is_eq` function is only supposed to be used with already sympified objects.

**Comment by almighty123789** [comment]
Thanks @oscarbenjamin ! . I would close the issue now.
