### ISSUE TITLE
Solvify cannot solve Piecewise

### ISSUE THREAD

**Issue by sayandip18** [sympy/sympy#21079]
```
>>> p = Piecewise((0, x < -1), (x**2, x <= 1), (log(x), True))
>>> solvify(p,x,S.Reals)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sayandip/sympy/sympy/solvers/solveset.py", line 2446, in solvify
    period = periodicity(f, symbol)
  File "/home/sayandip/sympy/sympy/calculus/util.py", line 516, in periodicity
    g_s = decompogen(f, symbol)
  File "/home/sayandip/sympy/sympy/solvers/decompogen.py", line 47, in decompogen
    result += [f.subs(f.args[0], symbol)] + decompogen(f.args[0], symbol)
  File "/home/sayandip/sympy/sympy/solvers/decompogen.py", line 37, in decompogen
    raise TypeError('expecting Expr but got: `%s`' % func_name(f))
TypeError: expecting Expr but got: `ExprCondPair`
>>> solveset(p,x,S.Reals)
Union(FiniteSet(0), Interval.open(-oo, -1))

```

**Comment by peteroupc** [comment]
Related: #20597.
