### ISSUE TITLE
evalf gives incorrect results for division by zero when using subs option

### ISSUE THREAD

**Issue by mgreminger** [sympy/sympy#21076]
`evalf` gives incorrect result when division by zero occurs while using `subs` parameter. Expected result is obtained if `subs` is performed on the expression before `evalf`. If the denominator is `0.` instead of `0` for the `subs` option to `evalf`, then `evalf` raises `ZeroDivisionError`.  

```python
>>> import sympy
>>> x,y = sympy.symbols('x,y')
>>> test = x/y
>>> test.subs({x:1, y:0}).evalf()
zoo
>>> test.evalf(subs={x:1, y:0})
0
>>> test.evalf(subs={x:1, y:0.})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/grem/anaconda3/envs/jupyter/lib/python3.8/site-packages/sympy/core/evalf.py", line 1473, in evalf
    result = evalf(self, prec + 4, options)
  File "/home/grem/anaconda3/envs/jupyter/lib/python3.8/site-packages/sympy/core/evalf.py", line 1325, in evalf
    r = rf(x, prec, options)
  File "/home/grem/anaconda3/envs/jupyter/lib/python3.8/site-packages/sympy/core/evalf.py", line 574, in evalf_mul
    arg = evalf(arg, prec, options)
  File "/home/grem/anaconda3/envs/jupyter/lib/python3.8/site-packages/sympy/core/evalf.py", line 1325, in evalf
    r = rf(x, prec, options)
  File "/home/grem/anaconda3/envs/jupyter/lib/python3.8/site-packages/sympy/core/evalf.py", line 694, in evalf_pow
    return mpf_pow_int(re, p, target_prec), None, target_prec, None
  File "/home/grem/anaconda3/envs/jupyter/lib/python3.8/site-packages/mpmath/libmp/libmpf.py", line 1070, in mpf_pow_int
    if n == -1: return mpf_div(fone, s, prec, rnd)
  File "/home/grem/anaconda3/envs/jupyter/lib/python3.8/site-packages/mpmath/libmp/libmpf.py", line 960, in mpf_div
    raise ZeroDivisionError
ZeroDivisionError
>>>
```

**Comment by rishabhgargdps** [comment]
I think it might be because:
1. test.subs({x:1, y:0}).evalf() acts simply as a fraction to decimal converter in this case. test.subs({x:1, y:0}) returns complex infinity which is passed to the evalf() which again returns the same answer.
2. test.evalf(subs={x:1, y:0}) and test.evalf(subs={x:1,y:0.}) give different result due to some change in the prec parameter of evalf_subs where evalf is defined by x = x.subs(evalf_subs(prec, options['subs]))

This link may be viewed for reference: (https://stackoverflow.com/questions/50439037/what-exactly-is-the-subs-argument-of-the-evalf-method-of-sympy-expression-fo#:~:text=The%20subs%20dictionary%20tells%20the,in%20the%20nitty%2Dgritty%20details.&text=The%20documentation%20just%20says%3A&text=subs%3D%20Substitute%20numerical,y%3A1%2Bpi%7D)

**Comment by theanmolsharma** [comment]
I would like to work on this issue. Please guide me through it.
