### ISSUE TITLE
Invalid comparison of non-real when using integrate()

### ISSUE THREAD

**Issue by aplund** [sympy/sympy#21091]
The following definite integral should give zero, but instead throws an error

`from sympy import *
x = Symbol('x')
i = integrate(exp(-x**2)*sin(x),(x,-oo,oo))
print(i)
`
A snippet of the backtrack is below:

`
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/sympy/core/function.py", line 285, in __new__
    evaluated = cls.eval(*args)
  File "/usr/lib/python3.9/site-packages/sympy/functions/elementary/trigonometric.py", line 3399, in eval
    return Piecewise((S.Pi, re(x) < 0),
  File "/usr/lib/python3.9/site-packages/sympy/core/decorators.py", line 267, in _func
    return func(self, other)
  File "/usr/lib/python3.9/site-packages/sympy/core/expr.py", line 375, in __lt__
    return StrictLessThan(self, other)
  File "/usr/lib/python3.9/site-packages/sympy/core/relational.py", line 700, in __new__
    raise TypeError("Invalid comparison of non-real %s" % me)
TypeError: Invalid comparison of non-real I*im(exp_polar(-I*pi/2))*erf(I*exp_polar(0)*im(exp_polar(I*pi/2))/2)

During handling of the above exception, another exception occurred:
`

sympy.__version__  is '1.7.1'

**Comment by jksuom** [comment]
https://github.com/sympy/sympy/blob/62572863590b1c3363d6268f75aea6e83e385728/sympy/functions/elementary/trigonometric.py#L3396-L3398
It looks like there should be `Lt(re(x), 0)` instead of `re(x) < 0`.

**Comment by aplund** [comment]
>  It looks like there should be `Lt(re(x), 0)` instead of `re(x) < 0`.

This gives exactly the same error.

**Comment by almighty123789** [comment]
I think this is where the problem lies
```
>>> val = I*im(exp_polar(-I*pi/2))*erf(I*exp_polar(0)*im(exp_polar(I*pi/2))/2)
>>> reval = re(val)
>>> reval.is_real
False
```

**Comment by aplund** [comment]
I believe the guts of that problem is this:

```
>>> erf(I).is_imaginary == True
False
````

**Comment by aplund** [comment]
This patch makes the integral work, but isn't strictly speaking true.

[complex_erf_imaginary.patch](https://github.com/sympy/sympy/files/6142505/p.txt)

I don't know how to test if an erf value is purely imaginary in general.

**Comment by oscarbenjamin** [comment]
> I believe the guts of that problem is this:
> 
> ```
> >>> erf(I).is_imaginary == True
> False
> ```

While that could be improved it is legitimate for `erf(I).is_imaginary` to give `None` because `None` means "unknown". If that None causes a nan and then an exception then some other code must be doing something that it shouldn't.

**Comment by oscargus** [comment]
If `(0, Ne(x, 0)),` is changed to `(0, Ne(re(x), 0) and Ne(im(x), 0)),` the error disappears, but it is probably not the way one would like to solve it...
