### ISSUE TITLE
Deprecate Theano printer

### ISSUE THREAD

**Issue by brandonwillard** [sympy/sympy#21150]
Theano development officially ended and the project has been succeeded by a fork named [Aesara](https://github.com/pymc-devs/aesara).  The [README](https://github.com/Theano/Theano/blob/8e9611715b33672d4b65b3fe232988c4adac970a/README.rst) in the official Theano repository confirms this.

This issue proposes the deprecation of the Theano printer in SymPy.

N.B.: There is a related discussion [here](https://groups.google.com/g/sympy/c/Z6WWUuVFH6c/).

**Comment by oscargus** [comment]
Seems like theano is now causing issues in the optional dependency tests:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/theano/configparser.py", line 238, in fetch_val_for_key
    return self._theano_cfg.get(section, option)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'blas'

During handling of the above exception, another exception occurred:

...
```

**Comment by oscarbenjamin** [comment]
I think we should just remove support for Theano now.

**Comment by vprayag2005** [comment]
Do we still need the Theano printer code in the SymPy codebase? It requires numpy<1.23 to run and is no longer mentioned in the documentation. I'm not sure if any users still rely on it.

Test summary:
8 failed, 31 passed, 2 skipped, 6 warnings in 5.08s

**Comment by moorepants** [comment]
It should be deprecated and then ultimately removed.

**Comment by oscarbenjamin** [comment]
Theano is already deprecated since sympy 1.8 (4 years ago):
https://docs.sympy.org/latest/explanation/active-deprecations.html#sympy-printing-theanocode

From quick testing `import theano` works in Python 3.10 but fails in any newer Python version. Aesara works up to Python 3.12 but cannot be installed in 3.13.

SymPy still supports Python 3.9 upwards so in someone may be using Theano or Aesara in older Python versions. Removing them does not particularly bring any immediate benefit but they can certainly both be removed when SymPy no longer supports Python 3.12.
