### ISSUE TITLE
Make `solve_univariate_inequality` more effective.

### ISSUE THREAD

**Issue by MaqOwais** [sympy/sympy#21173]
```
>>> eq = -y + x/sqrt(-x**2 + 1)>0
>>> solve_univariate_inequality(eq,x, domain=S.Reals)
Traceback (most recent call last):
  File "~/sympy-master/sympy/sympy/solvers/inequalities.py", line 526, in solve_univariate_inequality
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/sympy-master/sympy/sympy/solvers/inequalities.py", line 530, in solve_univariate_inequality
    raise NotImplementedError(filldedent('''
NotImplementedError: 
The inequality, x/sqrt(1 - x**2) - y > 0, cannot be solved using
solve_univariate_inequality.
```

A lot of equations are not able to give results due to this limitation. Hence it has to be improved. 
```
Raises
======
NotImplementedError
  The solution of the inequality cannot be determined due to limitation
  in :func:`sympy.solvers.solveset.solvify`.

```
After this improvement, the not only `solve_univariate_inequality` will give results but also`solveset` will be able to solve more inequality equations.

**Comment by MaqOwais** [comment]
The related PR for this issue: #21174
