### ISSUE TITLE
Relational gives the AttributeError with Intersection.

### ISSUE THREAD

**Issue by MaqOwais** [sympy/sympy#21185]
Relational gives the `AttributeError` with `Intersection`. Whereas non-relational works pretty nicely.
```
>>> p = FiniteSet(0, 3)
>>> p.intersection(FiniteSet(0))
FiniteSet(0)

>>> p.as_relational(x)
Eq(x, 0) | Eq(x, 3)

>>> p = Eq(x, 0) | Eq(x, 3)
>>> p.intersection(FiniteSet(0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Or' object has no attribute 'intersection'

>>> p.intersection(Eq(x, 3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Or' object has no attribute 'intersection'
```

**Comment by oscarbenjamin** [comment]
This is as intended. `Relational` does not represent sets so intersections are not meaningful here. Relations can be combined with `And`. Sets can be combined with `Intersection`. You should not try to mix Set and Relational like this.
