### ISSUE TITLE
TypeError when raising ValueError in solveset

### ISSUE THREAD

**Issue by sliva0** [sympy/sympy#21335]
```python
>>> solveset("x", "x, x")
Traceback (most recent call last):
  File "...", line 1, in <module>
    solveset("x", "x, x")
  File "...\Python39\lib\site-packages\sympy\solvers\solveset.py", line 2063, in solveset
    raise ValueError("%s is not a valid SymPy symbol" % symbol)
TypeError: not all arguments converted during string formatting
```

**Comment by oscarbenjamin** [comment]
It should be:
```
raise ValueError("%s is not a valid SymPy symbol" % (symbol,))
```
or otherwise
```
raise ValueError(f"{symbol} is not a valid SymPy symbol")
```
