### ISSUE TITLE
`parse_latex` introduces unnecessary factor of -1

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#21517]
```python
>>> from symyp.parsing.latex import parse_latex
>>> srepr(parse_latex('1 - 2*(x + 1))'))
"Add(Integer(1), Mul(Integer(-1), Integer(2), Add(Symbol('x'), Integer(1))))"
>>> srepr(parse_latex('-3.14'))
"Mul(Integer(-1), Float('3.1400000000000001', precision=53))"
```

The solution to the first expression would involve using `_keep_coeff(S.NegativeOne, mul)` in a `convert_mul` routine that is similar to the `convert_add` routine.

The solution to the second issue involves 
```diff
diff --git a/sympy/parsing/latex/_parse_latex_antlr.py b/sympy/parsing/latex/_parse_latex_antlr.py
index ca50b4958a..2e4a45ad20 100644
--- a/sympy/parsing/latex/_parse_latex_antlr.py
+++ b/sympy/parsing/latex/_parse_latex_antlr.py
@@ -164,11 +164,8 @@ def convert_unary(unary):
         return convert_unary(nested_unary)
     elif unary.SUB():
         numabs = convert_unary(nested_unary)
-        if numabs == 1:
-            # Use Integer(-1) instead of Mul(-1, 1)
-            return -numabs
-        else:
-            return sympy.Mul(-1, convert_unary(nested_unary), evaluate=False)
+        # Use Integer(-n) instead of Mul(-1, n)
+        return -numabs
     elif postfix:
         return convert_postfix_list(postfix)
```

**Comment by wermos** [comment]
I thought I'd mention two things:
1. Your very first example actually has an extra closing parenthesis. ANTLR doesn't seem to mind too much but the Lark-based parser complains (as it should, imo):
```python
>>> srepr(parse_latex_lark('1 - 2*(x + 1))'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tirthankar/projects/sympy/sympy/parsing/latex/lark/latex_parser.py", line 76, in parse_latex_lark
    return _lark_latex_parser.doparse(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tirthankar/projects/sympy/sympy/parsing/latex/lark/latex_parser.py", line 40, in doparse
    parse_tree = self.parser.parse(s)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/tirthankar/projects/sympy/env/lib/python3.11/site-packages/lark/lark.py", line 645, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tirthankar/projects/sympy/env/lib/python3.11/site-packages/lark/parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tirthankar/projects/sympy/env/lib/python3.11/site-packages/lark/parsers/earley.py", line 266, in parse
    to_scan = self._parse(lexer, columns, to_scan, start_symbol)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tirthankar/projects/sympy/env/lib/python3.11/site-packages/lark/parsers/xearley.py", line 146, in _parse
    to_scan = scan(i, to_scan)
              ^^^^^^^^^^^^^^^^
  File "/home/tirthankar/projects/sympy/env/lib/python3.11/site-packages/lark/parsers/xearley.py", line 119, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan},
lark.exceptions.UnexpectedCharacters: No terminal matches ')' in the current parser context, at line 1 col 14

1 - 2*(x + 1))
             ^
Expected one of:
        * LT
        * BANG
        * EQUAL
        * SUB
        * DIV_SYMBOL
        * CARET
        * L_PAREN
        * ADD
        * GT
        * SYMBOL_WITH_GREEK_SUBSCRIPT
        * LTE
        * NOT_EQUAL
        * MUL_SYMBOL
        * BASIC_SUBSCRIPTED_SYMBOL
        * GTE
        * SYMBOL
        * GREEK_SUBSCRIPTED_SYMBOL
        * GREEK_SYMBOL
```
2. This issue is not present in the Lark based parser. It looks to me like it was fixed in ANTLR in #21518 as well, so I think we can close this issue.
