### ISSUE TITLE
Simplify does not terminate

### ISSUE THREAD

**Issue by kristianmitk** [sympy/sympy#21528]
Problematic expression: `Eq(-sqrt(x + 10) + sqrt(x - 2), 2*sqrt(x + 7))`

## Tested on:

- 1.8 (used in the following case), 
- 1.6.2 
- 1.5.1 at https://live.sympy.org/ (eventually returning a `Error: Operation timed out.`)

## Reproduce:

```sh
root@baa5b28bf15c:/# python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.simplify("Eq(-sqrt(x + 10) + sqrt(x - 2), 2*sqrt(x + 7))", ratio=1.0)
``` 

## Traceback:

```
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/sympy/simplify/simplify.py", line 592, in simplify
    return _eval_simplify(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sympy/core/relational.py", line 566, in _eval_simplify
    e = super()._eval_simplify(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sympy/core/relational.py", line 317, in _eval_simplify
    elif dif.equals(0):  # XXX this is expensive
  File "/usr/local/lib/python3.6/dist-packages/sympy/core/expr.py", line 751, in equals
    constant = diff.is_constant(simplify=False, failing_number=True)
  File "/usr/local/lib/python3.6/dist-packages/sympy/core/expr.py", line 674, in is_constant
    if b is not None and b is not S.NaN and b.equals(a) is False:
  File "/usr/local/lib/python3.6/dist-packages/sympy/core/expr.py", line 828, in equals
    mp = minimal_polynomial(diff)
  File "/usr/local/lib/python3.6/dist-packages/sympy/polys/numberfields.py", line 672, in minimal_polynomial
    result = _minpoly_compose(ex, x, domain)
  File "/usr/local/lib/python3.6/dist-packages/sympy/polys/numberfields.py", line 551, in _minpoly_compose
    res = _minpoly_add(x, dom, *ex.args)
  File "/usr/local/lib/python3.6/dist-packages/sympy/polys/numberfields.py", line 366, in _minpoly_add
    mp = _minpoly_op_algebraic_element(Add, p, px, x, dom, mp1=mp)
  File "/usr/local/lib/python3.6/dist-packages/sympy/polys/numberfields.py", line 279, in _minpoly_op_algebraic_element
    _, factors = r.factor_list()
  File "/usr/local/lib/python3.6/dist-packages/sympy/polys/polytools.py", line 3336, in factor_list
    coeff, factors = f.rep.factor_list()
  File "/usr/local/lib/python3.6/dist-packages/sympy/polys/polyclasses.py", line 795, in factor_list
    coeff, factors = dmp_factor_list(f.rep, f.lev, f.dom)
  File "/usr/local/lib/python3.6/dist-packages/sympy/polys/factortools.py", line 1381, in dmp_factor_list
    return dup_factor_list(f, K0)
  File "/usr/local/lib/python3.6/dist-packages/sympy/polys/factortools.py", line 1330, in dup_factor_list
    coeff, factors = dup_zz_factor(f, K)
  File "/usr/local/lib/python3.6/dist-packages/sympy/polys/factortools.py", line 676, in dup_zz_factor
    H = dup_zz_zassenhaus(g, K)
  File "/usr/local/lib/python3.6/dist-packages/sympy/polys/factortools.py", line 369, in dup_zz_zassenhaus
    q = q*g[i][-1]
KeyboardInterrupt
```

**Comment by oscarbenjamin** [comment]
It is slow because `Eq.simplify` calls `(lhs-rhs).equals(0)` which in turn calls `minpoly(lhs - rhs)` which leads to this:
```python
In [4]: e = -sqrt(11) + sqrt(10) + 2*sqrt(7) - sqrt(2)*(4 + I) + I

In [5]: e
Out[5]: -√11 + √10 + 2⋅√7 - √2⋅(4 + ⅈ) + ⅈ

In [6]: minpoly(e)
^C---------------------------------------------------------------------------
KeyboardInterrupt
```
That hangs while trying to factorise this polynomial over QQ:
```python
ipdb> p r
Poly(_x**64 - 2496*_x**62 + 2888064*_x**60 - 2060129280*_x**58 + 1016709325824*_x**56 - 369406369136640*_x**54 + 102677062821609472*_x**52 - 22396048864501825536*_x**50 + 3901580940814574026752*_x**48 - 549564169675083098357760*_x**46 + 63119185869280596002340864*_x**44 - 5942870852982872917810348032*_x**42 + 459929332747057043275528536064*_x**40 - 29260327069327825485457526882304*_x**38 + 1525910171668091004904030617993216*_x**36 - 64804394556452378255952984089296896*_x**34 + 2214939131504545291244067153046929408*_x**32 - 59684223222196057184202024656968876032*_x**30 + 1221143127106691865916068377917055303680*_x**28 - 17511635409934838511013885615210147872768*_x**26 + 137051953484966336317259244842235243528192*_x**24 + 363385212809984420386504799756036018798592*_x**22 - 20993754866120778058963575182953190202015744*_x**20 + 146931885353161642868397791196444981964308480*_x**18 + 1014085260637849440913667132776266378080419840*_x**16 - 15140901218796653631396852160706358964333314048*_x**14 - 36962219137827064918525598800663165721357844480*_x**12 + 663504254227348039949062670816935822594475556864*_x**10 + 2592580999204073363311408835547018363781238489088*_x**8 + 272754273504769972445826167045934401581234520064*_x**6 + 517775027643555420645770743932144766956536332288*_x**4 + 109503463185996182703589851620993429257838395392*_x**2 + 23337056215262268081958103253504347538871812096, _x, domain='QQ')
ipdb> p r.factor_list()
^C*** KeyboardInterrupt
```
We need some sort of bound in `minpoly` to stop it from trying to compute arbitrarily large minimal polynomials (#21479).

Also factorisation could be made faster. Using flint this polynomial can be factored in milliseconds:
```python
import flint

p = flint.fmpq_poly([1, 0, -2496, 0, 2888064, 0, -2060129280, 0, 1016709325824,
    0, -369406369136640, 0, 102677062821609472, 0, -22396048864501825536, 0,
    3901580940814574026752, 0, -549564169675083098357760, 0,
    63119185869280596002340864, 0, -5942870852982872917810348032, 0,
    459929332747057043275528536064, 0, -29260327069327825485457526882304, 0,
    1525910171668091004904030617993216, 0,
    -64804394556452378255952984089296896, 0,
    2214939131504545291244067153046929408, 0,
    -59684223222196057184202024656968876032, 0,
    1221143127106691865916068377917055303680, 0,
    -17511635409934838511013885615210147872768, 0,
    137051953484966336317259244842235243528192, 0,
    363385212809984420386504799756036018798592, 0,
    -20993754866120778058963575182953190202015744, 0,
    146931885353161642868397791196444981964308480, 0,
    1014085260637849440913667132776266378080419840, 0,
    -15140901218796653631396852160706358964333314048, 0,
    -36962219137827064918525598800663165721357844480, 0,
    663504254227348039949062670816935822594475556864, 0,
    2592580999204073363311408835547018363781238489088, 0,
    272754273504769972445826167045934401581234520064, 0,
    517775027643555420645770743932144766956536332288, 0,
    109503463185996182703589851620993429257838395392, 0,
    23337056215262268081958103253504347538871812096][::-1])
```
That gives:
```python
In [21]: %time p.factor()
CPU times: user 27.8 ms, sys: 611 µs, total: 28.4 ms
Wall time: 29.2 ms
Out[21]: 
(1,
 [(x^32 + (-1248)*x^30 + 512*x^29 + 665280*x^28 + (-458752)*x^27 + (-199664128)*x^26 + 178511872*x^25 + 37640210944*x^24 + (-38736625664)*x^23 + (-4699025457152)*x^22 + 5204611956736*x^21 + 398260267810816*x^20 + (-458127838281728)*x^19 + (-23059555978182656)*x^18 + 27302502200246272*x^17 + 900858111050579968*x^16 + (-1108326887223984128)*x^15 + (-22659935323805450240)*x^14 + 29859502950059081728*x^13 + 320796314031722856448*x^12 + (-479023035980787482624)*x^11 + (-1258008088545220100096)*x^10 + 3231150720160463060992*x^9 + (-26886533787115107385344)*x^8 + (-1290874230278771965952)*x^7 + 251155201535881454288896*x^6 + 139637065268086572056576*x^5 + 1537852411344280247861248*x^4 + 2193292943096465001021440*x^3 + 1685594291629702221135872*x^2 + 636785033280321296007168*x + 152764708670760302936064,
   1),
  (x^32 + (-1248)*x^30 + (-512)*x^29 + 665280*x^28 + 458752*x^27 + (-199664128)*x^26 + (-178511872)*x^25 + 37640210944*x^24 + 38736625664*x^23 + (-4699025457152)*x^22 + (-5204611956736)*x^21 + 398260267810816*x^20 + 458127838281728*x^19 + (-23059555978182656)*x^18 + (-27302502200246272)*x^17 + 900858111050579968*x^16 + 1108326887223984128*x^15 + (-22659935323805450240)*x^14 + (-29859502950059081728)*x^13 + 320796314031722856448*x^12 + 479023035980787482624*x^11 + (-1258008088545220100096)*x^10 + (-3231150720160463060992)*x^9 + (-26886533787115107385344)*x^8 + 1290874230278771965952*x^7 + 251155201535881454288896*x^6 + (-139637065268086572056576)*x^5 + 1537852411344280247861248*x^4 + (-2193292943096465001021440)*x^3 + 1685594291629702221135872*x^2 + (-636785033280321296007168)*x + 152764708670760302936064,
   1)])
```
We could use flint as an optional dependency to make things like this faster. It should also be possible to improve the algorithms in sympy to be within some factor of flint.

No matter how much factorisation improves though computing the minimal polynomial can easily become an extremely expensive operation so either `minpoly` should not be used in library code or it needs to have controllable limits as suggested in #21479

**Comment by oscarbenjamin** [comment]
To use flint as above I'm actually using the `python_flint` wrapper:
https://github.com/fredrik-johansson/python-flint

It can't be installed with pip but there are manylinux and OSX wheels there from as artifacts on the Github Actions jobs. Otherwise I think it can be installed using conda.
