### ISSUE TITLE
nC | documentation example is throwing error 

### ISSUE THREAD

**Issue by Shekharrajak** [sympy/sympy#21526]
While trying out how `nC`  works found that one of the example given in the doc: https://docs.sympy.org/latest/modules/functions/combinatorial.html#nc not working as expected.

```
>>> from sympy.functions.combinatorial.numbers import nC
>>> from sympy.utilities.iterables import multiset_combinations
>>> nC(3, 2)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/functions/combinatorial/numbers.py", line 1715, in nC
    return nC(_multiset_histogram(n), k, replacement)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/functions/combinatorial/numbers.py", line 1435, in _multiset_histogram
    n = list(n)
TypeError: 'Integer' object is not iterable

```

**Comment by naveensaigit** [comment]
Hi, what version of SymPy are you using? With SymPy 1.8 (latest release), I get -
``` python
>>> import sympy
>>> sympy.__version__
'1.8'
>>> from sympy.functions.combinatorial.numbers import nC
>>> from sympy.utilities.iterables import multiset_combinations
>>> nC(3, 2)
3
```

**Comment by Shekharrajak** [comment]
Cool! Python console for SymPy 1.5.1 (Python 2.7.12) through sympy cell
