### ISSUE TITLE
Multiple integrate problem

### ISSUE THREAD

**Issue by UlBoy** [sympy/sympy#21533]
![ssmrp](https://user-images.githubusercontent.com/84957780/119941579-c340c400-bfcb-11eb-9c35-bdff5a0d9b76.jpg)

Hello ! I'm new to using sympy and python. 
I'm trying to solve a multiple integrate problem include 2 variables.
But there are some TypeError and I don't know how to solve this.
```
#Codes
from sympy import *
init_printing()


z1 = symbols('z1')
z2 = symbols('z2')
I = integrate(exp(-0.5*(((-1/z1)+1.39)**2+((-1/z2)+1.23)**2))*(1/(z1**2))(1/(z2**2)),(z1,0,1),(z2,0,1))
print (I)

#results
PS C:\Users\6241\Documents\python\ssmrp> python inte.py
Traceback (most recent call last):
  File "C:\Users\6241\Documents\python\ssmrp\inte.py", line 9, in <module>
    I = integrate(exp(-0.5*(((-1/z1)+1.39)**2+((-1/z2)+1.23)**2))*(1/(z1**2))(1/(z2**2)),(z1,0,1),(z2,0,1))
TypeError: 'Pow' object is not callable
```

Thank you for your helps!!

**Comment by jksuom** [comment]
> `(1/(z1**2))(1/(z2**2))`

There should be a `*` between the factors.

**Comment by UlBoy** [comment]
![image](https://user-images.githubusercontent.com/84957780/119970020-39542380-bfea-11eb-84e6-1dc41ccda33a.png)
Yes I already put '*'. but That's what it looks like on this site.

**Comment by UlBoy** [comment]
Thanks a lot!
I try to do again after adding '*' on my codes.
But It is not calculated and comes out as an expression.
Is the expression itself wrong?

#results
PS C:\Users\6241\Documents\python\ssmrp> python inte.py
0.1786190416574*Integral(exp(-0.5/z1**2)*exp(1.39/z1)/z1**2, (z1, 0, 1))*Integral(exp(-0.5/z2**2)*exp(1.23/z2)/z2**2, (z2, 0, 1))

**Comment by oscarbenjamin** [comment]
It looks like an analytic result can not be computed for this integral currently. It should be possible to evaluate it numerically with `evalf` except that double integrals are not supported (even though mpmath has a routine for double integrals that could be used).

This particular integral can be factored into a product of two single integrals that can be evaluated numerically:
```python
In [33]: z1, z2 = symbols('z1, z2')

In [34]: I = Integral(exp(-0.5*(((-1/z1)+1.39)**2+((-1/z2)+1.23)**2))*(1/(z1**2))*(1/(z2**2)),(z1,0,1),(z2,0,1))

In [35]: I
Out[35]: 
1 1                                                                                   
⌠ ⌠                                                                                   
⎮ ⎮                                   2                                  2            
⎮ ⎮            ⎛    0.719424460431655⎞            ⎛    0.813008130081301⎞             
⎮ ⎮  - 0.96605⋅⎜1 - ─────────────────⎟  - 0.75645⋅⎜1 - ─────────────────⎟             
⎮ ⎮            ⎝            z₁       ⎠            ⎝            z₂       ⎠             
⎮ ⎮ ℯ                                                                                 
⎮ ⎮ ────────────────────────────────────────────────────────────────────── d(z₁) d(z₂)
⎮ ⎮                                  2   2                                            
⎮ ⎮                                z₁ ⋅z₂                                             
⌡ ⌡                                                                                   
0 0                                                                                   

In [36]: factor(I)
Out[36]: 
                ⎛1                   ⎞ 1                   
                ⎜⌠                   ⎟ ⌠                   
                ⎜⎮  -0.5             ⎟ ⎮  -0.5             
                ⎜⎮  ─────  1.39      ⎟ ⎮  ─────  1.23      
                ⎜⎮     2   ────      ⎟ ⎮     2   ────      
                ⎜⎮   z₁     z₁       ⎟ ⎮   z₂     z₂       
                ⎜⎮ ℯ     ⋅ℯ          ⎟ ⎮ ℯ     ⋅ℯ          
0.1786190416574⋅⎜⎮ ──────────── d(z₁)⎟⋅⎮ ──────────── d(z₂)
                ⎜⎮       2           ⎟ ⎮       2           
                ⎜⎮     z₁            ⎟ ⎮     z₂            
                ⎜⌡                   ⎟ ⌡                   
                ⎝0                   ⎠ 0                   

In [37]: factor(I).evalf()
Out[37]: 2.41992826790597
```
In principle it might be possible to compute these single integrals analytically since a similar definite integral can be computed:
```python
In [52]: I2 = Integral(exp(-(1-1/x)**2)/x**2, (x, 0, 1))

In [53]: I2
Out[53]: 
1              
⌠              
⎮          2   
⎮   ⎛    1⎞    
⎮  -⎜1 - ─⎟    
⎮   ⎝    x⎠    
⎮ ℯ            
⎮ ────────── dx
⎮      2       
⎮     x        
⌡              
0              

In [54]: I2.doit()
Out[54]: 
-√π 
────
 2  
```
That result seems to have the wrong sign though:
```python
In [55]: _.evalf()
Out[55]: -0.886226925452758

In [56]: I2.evalf()
Out[56]: 0.886226925452758
```

**Comment by UlBoy** [comment]
> It looks like an analytic result can not be computed for this integral currently. It should be possible to evaluate it numerically with `evalf` except that double integrals are not supported (even though mpmath has a routine for double integrals that could be used).
> 
> This particular integral can be factored into a product of two single integrals that can be evaluated numerically:
> 
> ```python
> In [33]: z1, z2 = symbols('z1, z2')
> 
> In [34]: I = Integral(exp(-0.5*(((-1/z1)+1.39)**2+((-1/z2)+1.23)**2))*(1/(z1**2))*(1/(z2**2)),(z1,0,1),(z2,0,1))
> 
> In [35]: I
> Out[35]: 
> 1 1                                                                                   
> ⌠ ⌠                                                                                   
> ⎮ ⎮                                   2                                  2            
> ⎮ ⎮            ⎛    0.719424460431655⎞            ⎛    0.813008130081301⎞             
> ⎮ ⎮  - 0.96605⋅⎜1 - ─────────────────⎟  - 0.75645⋅⎜1 - ─────────────────⎟             
> ⎮ ⎮            ⎝            z₁       ⎠            ⎝            z₂       ⎠             
> ⎮ ⎮ ℯ                                                                                 
> ⎮ ⎮ ────────────────────────────────────────────────────────────────────── d(z₁) d(z₂)
> ⎮ ⎮                                  2   2                                            
> ⎮ ⎮                                z₁ ⋅z₂                                             
> ⌡ ⌡                                                                                   
> 0 0                                                                                   
> 
> In [36]: factor(I)
> Out[36]: 
>                 ⎛1                   ⎞ 1                   
>                 ⎜⌠                   ⎟ ⌠                   
>                 ⎜⎮  -0.5             ⎟ ⎮  -0.5             
>                 ⎜⎮  ─────  1.39      ⎟ ⎮  ─────  1.23      
>                 ⎜⎮     2   ────      ⎟ ⎮     2   ────      
>                 ⎜⎮   z₁     z₁       ⎟ ⎮   z₂     z₂       
>                 ⎜⎮ ℯ     ⋅ℯ          ⎟ ⎮ ℯ     ⋅ℯ          
> 0.1786190416574⋅⎜⎮ ──────────── d(z₁)⎟⋅⎮ ──────────── d(z₂)
>                 ⎜⎮       2           ⎟ ⎮       2           
>                 ⎜⎮     z₁            ⎟ ⎮     z₂            
>                 ⎜⌡                   ⎟ ⌡                   
>                 ⎝0                   ⎠ 0                   
> 
> In [37]: factor(I).evalf()
> Out[37]: 2.41992826790597
> ```
> 
> In principle it might be possible to compute these single integrals analytically since a similar definite integral can be computed:
> 
> ```python
> In [52]: I2 = Integral(exp(-(1-1/x)**2)/x**2, (x, 0, 1))
> 
> In [53]: I2
> Out[53]: 
> 1              
> ⌠              
> ⎮          2   
> ⎮   ⎛    1⎞    
> ⎮  -⎜1 - ─⎟    
> ⎮   ⎝    x⎠    
> ⎮ ℯ            
> ⎮ ────────── dx
> ⎮      2       
> ⎮     x        
> ⌡              
> 0              
> 
> In [54]: I2.doit()
> Out[54]: 
> -√π 
> ────
>  2  
> ```
> 
> That result seems to have the wrong sign though:
> 
> ```python
> In [55]: _.evalf()
> Out[55]: -0.886226925452758
> 
> In [56]: I2.evalf()
> Out[56]: 0.886226925452758
> ```

**Comment by UlBoy** [comment]
> It looks like an analytic result can not be computed for this integral currently. It should be possible to evaluate it numerically with `evalf` except that double integrals are not supported (even though mpmath has a routine for double integrals that could be used).
> 
> This particular integral can be factored into a product of two single integrals that can be evaluated numerically:
> 
> ```python
> In [33]: z1, z2 = symbols('z1, z2')
> 
> In [34]: I = Integral(exp(-0.5*(((-1/z1)+1.39)**2+((-1/z2)+1.23)**2))*(1/(z1**2))*(1/(z2**2)),(z1,0,1),(z2,0,1))
> 
> In [35]: I
> Out[35]: 
> 1 1                                                                                   
> ⌠ ⌠                                                                                   
> ⎮ ⎮                                   2                                  2            
> ⎮ ⎮            ⎛    0.719424460431655⎞            ⎛    0.813008130081301⎞             
> ⎮ ⎮  - 0.96605⋅⎜1 - ─────────────────⎟  - 0.75645⋅⎜1 - ─────────────────⎟             
> ⎮ ⎮            ⎝            z₁       ⎠            ⎝            z₂       ⎠             
> ⎮ ⎮ ℯ                                                                                 
> ⎮ ⎮ ────────────────────────────────────────────────────────────────────── d(z₁) d(z₂)
> ⎮ ⎮                                  2   2                                            
> ⎮ ⎮                                z₁ ⋅z₂                                             
> ⌡ ⌡                                                                                   
> 0 0                                                                                   
> 
> In [36]: factor(I)
> Out[36]: 
>                 ⎛1                   ⎞ 1                   
>                 ⎜⌠                   ⎟ ⌠                   
>                 ⎜⎮  -0.5             ⎟ ⎮  -0.5             
>                 ⎜⎮  ─────  1.39      ⎟ ⎮  ─────  1.23      
>                 ⎜⎮     2   ────      ⎟ ⎮     2   ────      
>                 ⎜⎮   z₁     z₁       ⎟ ⎮   z₂     z₂       
>                 ⎜⎮ ℯ     ⋅ℯ          ⎟ ⎮ ℯ     ⋅ℯ          
> 0.1786190416574⋅⎜⎮ ──────────── d(z₁)⎟⋅⎮ ──────────── d(z₂)
>                 ⎜⎮       2           ⎟ ⎮       2           
>                 ⎜⎮     z₁            ⎟ ⎮     z₂            
>                 ⎜⌡                   ⎟ ⌡                   
>                 ⎝0                   ⎠ 0                   
> 
> In [37]: factor(I).evalf()
> Out[37]: 2.41992826790597
> ```
> 
> In principle it might be possible to compute these single integrals analytically since a similar definite integral can be computed:
> 
> ```python
> In [52]: I2 = Integral(exp(-(1-1/x)**2)/x**2, (x, 0, 1))
> 
> In [53]: I2
> Out[53]: 
> 1              
> ⌠              
> ⎮          2   
> ⎮   ⎛    1⎞    
> ⎮  -⎜1 - ─⎟    
> ⎮   ⎝    x⎠    
> ⎮ ℯ            
> ⎮ ────────── dx
> ⎮      2       
> ⎮     x        
> ⌡              
> 0              
> 
> In [54]: I2.doit()
> Out[54]: 
> -√π 
> ────
>  2  
> ```
> 
> That result seems to have the wrong sign though:
> 
> ```python
> In [55]: _.evalf()
> Out[55]: -0.886226925452758
> 
> In [56]: I2.evalf()
> Out[56]: 0.886226925452758
> ```
------------------------------------------------------------------------------------------------------------------------------------------
Thank you for your detailed help Oscar!
Actually I tried to solve integral problems with matrices variables
I found myself It seems easier to use variables in place of numbers
These are full of my equation and new codes I made
![P](https://user-images.githubusercontent.com/84957780/120442524-aab41d80-c3c0-11eb-9c39-0ad082a545fd.JPG)

#Codes
from sympy import *
init_printing()

x = symbols('x') 
u1 = symbols('u1') 
u2 = symbols('u2')
z1 = symbols('z1') 
z2 = symbols('z2')


x = 0.830
V = Matrix ([[1,x],[x,1]])
det.V = V.det()**1/2



u1 = ln(3.5/4.0)/sqrt(1.13**2+0.5**2)
u2 = ln(0.81/1.0)/sqrt(0.19**2+0.2**2)


Z = Matrix ([-1/z1 + u1 + 1],[-1/z2 + u2 + 1])

P = 2*pi**-1 * det.V **-0.5 * Integral(exp(-0.5* Z.T * V**-1 * Z) * 1/(z1**2) * 1/(Z2**2), (z1,0,1),(z2,0,1)) 
factor(P).evalf()

#Result
PS C:\Users\6241\Documents\python\ssmrp> python P.py
Traceback (most recent call last):
  File "C:\Users\6241\Documents\python\ssmrp\P.py", line 22, in <module>
    Z = Matrix ([-1/z1 + u1 + 1],[-1/z2 + u2 + 1])
  File "C:\Users\6241\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\matrices\dense.py", line 299, in __new__
    return cls._new(*args, **kwargs)
  File "C:\Users\6241\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\matrices\dense.py", line 310, in _new
    rows, cols, flat_list = cls._handle_creation_inputs(*args, **kwargs)
  File "C:\Users\6241\AppData\Local\Programs\Python\Python39\lib\site-packages\sympy\matrices\matrices.py", line 1121, in _handle_creation_inputs
    raise TypeError(filldedent('''
TypeError:
Data type not understood; expecting list of lists or lists of values.

I want to get 'P' but It didn't work. Could you find what problem is?
Thank you very much for your help again.

**Comment by oscarbenjamin** [comment]
I'm reopening this because this issue lists some problems in sympy that should be fixed.

**Comment by UlBoy** [comment]
> I'm reopening this because this issue lists some problems in sympy that should be fixed.

Thanks a lot. 
there an error about 'P'
>>> P = 2*pi**-1 * det.V **-0.5 * Integral(exp(-0.5* Z.T * V**-1 * Z) * 1/(z1**2) * 1/(z2**2), (z1,0,1),(z2,0,1))

I wrote z2 for capital before

**Comment by UlBoy** [comment]
> I'm reopening this because this issue lists some problems in sympy that should be fixed.

Hello Oscar! Is there any progress or problems identified?

**Comment by jksuom** [comment]
The double integral is the product of two single integrals of the type

    I(a) = Integral(exp(-0.5*(-1/z + a)**2)/z**2, (z, 0, 1))

where `a` is 1.39 or 1.23. It looks like this integral is non-elementary, but it can be expressed in terms of the error function.
Substituting `1/z` for `z`, and then `z -> z + a`, `z -> z*sqrt(2)`, we get something like

    I(a) = Integral(exp(-0.5*(z - a)**2), (z, 1, oo))
         = Integral(exp(- z**2/2), (z, 1 - a, oo))
         = 1/sqrt(2)*Integral(exp(-z**2), (z, (1 - a)/sqrt(2), oo))

The last integral can be computed from the error function

    erf(z) = 2/sqrt(pi)*Integral(exp(-t**z), (t, 0, z))

using `erf(oo) = 1`.
