### ISSUE TITLE
Wrong exponent of (a, 0, 0, 0) quaternion

### ISSUE THREAD

**Issue by vr050714** [sympy/sympy#21576]
In case of a quaternion with zero imaginary part division by `vector_norm` causes NaNs instead of 0 in the folowing lines of code. 
https://github.com/sympy/sympy/blob/d17907e248abe9f1b3d8aa98701ba6d48bd948d9/sympy/algebras/quaternion.py#L459-L463
Example:
![wrong_quaternion_exponent](https://user-images.githubusercontent.com/8076819/120902258-f4626980-c647-11eb-931f-24115955f772.png)

**Comment by mostlyaman** [comment]
An if-block can take care of this case.
```python
vector_norm = sqrt(q.b**2 + q.c**2 + q.d**2)

if vector_norm is S.Zero:
	a = exp(q.a)
	return Quaternion(a, S.Zero, S.Zero, S.Zero)
	
else:
	a = exp(q.a) * cos(vector_norm)
	b = exp(q.a) * sin(vector_norm) * q.b / vector_norm
	c = exp(q.a) * sin(vector_norm) * q.c / vector_norm
	d = exp(q.a) * sin(vector_norm) * q.d / vector_norm
	return Quaternion(a, b, c, d)
```
It fixes the problem, as expected.
```python
>>> from sympy.algebras import Quaternion
>>> X = Quaternion(1,0,0,0)
>>> X.exp()
E + 0*i + 0*j + 0*k
```
I am also adding tests if required. Please approve or suggest changes if needed.

**Comment by oscarbenjamin** [comment]
We also need to handle something like this:
```python
In [15]: a = Symbol('a')

In [16]: q = Quaternion(0, a, 0, 0)

In [17]: q.exp()
Out[17]: cos(sqrt(a**2)) + a*sin(sqrt(a**2))/sqrt(a**2)*i + 0*j + 0*k

In [18]: q.exp().subs(a, 0)
Out[18]: 1 + nan*i + 0*j + 0*k
```
Maybe `Piecewise` would be needed for this. If there is a formula that can handle the zero case without a divide by zero then maybe that could be used.

**Comment by vr050714** [comment]
> An if-block can take care of this case.
> 
> ```python
> vector_norm = sqrt(q.b**2 + q.c**2 + q.d**2)
> 
> if vector_norm is S.Zero:
> 	a = exp(q.a)
> 	return Quaternion(a, S.Zero, S.Zero, S.Zero)
> 	
> else:
> 	a = exp(q.a) * cos(vector_norm)
> 	b = exp(q.a) * sin(vector_norm) * q.b / vector_norm
> 	c = exp(q.a) * sin(vector_norm) * q.c / vector_norm
> 	d = exp(q.a) * sin(vector_norm) * q.d / vector_norm
> 	return Quaternion(a, b, c, d)
> ```
> 
> It fixes the problem, as expected.
> 
> ```python
> >>> from sympy.algebras import Quaternion
> >>> X = Quaternion(1,0,0,0)
> >>> X.exp()
> E + 0*i + 0*j + 0*k
> ```
> 
> I am also adding tests if required. Please approve or suggest changes if needed.

Looks good!

BTW, Is it any reason to avoid conventional `log` name for method. There is only `_ln`. Leading underscore in the method name may confuse since it looks like a private method. Maybe, adding `log = _ln` to the class definition makes sense.

**Comment by vr050714** [comment]
> We also need to handle something like this:
> 
> ```python
> In [15]: a = Symbol('a')
> 
> In [16]: q = Quaternion(0, a, 0, 0)
> 
> In [17]: q.exp()
> Out[17]: cos(sqrt(a**2)) + a*sin(sqrt(a**2))/sqrt(a**2)*i + 0*j + 0*k
> 
> In [18]: q.exp().subs(a, 0)
> Out[18]: 1 + nan*i + 0*j + 0*k
> ```
> 
> Maybe `Piecewise` would be needed for this. If there is a formula that can handle the zero case without a divide by zero then maybe that could be used.

Direct substitution in this case wont work. This is "0/0" indeterminate form actually. limit must be used instead. But on the other hand substitution should work too since the function like sin(x)/x is well defined at x = 0. Substitution should work in terms of limit as more general approach.

**Comment by mostlyaman** [comment]
Has limits for Quaternions implemented yet? It can produce limits for individual arguments of the Quaternion but not for the whole thing.
```python
>>> Q = Quaternion(1,x,0,0)
>>> Q.exp().subs(x,0)
E + nan*i + 0*j + 0*k
>>> Q.exp().b
       ⎛   ____⎞
       ⎜  ╱  2 ⎟
ℯ⋅x⋅sin⎝╲╱  x  ⎠
────────────────
       ____     
      ╱  2      
    ╲╱  x       
>>> Q.exp().b.limit(x,0)
0
>>> Q.exp().limit(x,0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aman/Desktop/testing/sympy/sympy/core/expr.py", line 3370, in limit
    return limit(self, x, xlim, dir)
  File "/home/aman/Desktop/testing/sympy/sympy/series/limits.py", line 63, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
  File "/home/aman/Desktop/testing/sympy/sympy/series/limits.py", line 329, in doit
    r = gruntz(e, z, z0, dir)
  File "/home/aman/Desktop/testing/sympy/sympy/series/gruntz.py", line 684, in gruntz
    r = limitinf(e0, z)
  File "/home/aman/Desktop/testing/sympy/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/aman/Desktop/testing/sympy/sympy/series/gruntz.py", line 449, in limitinf
    c0, e0 = mrv_leadterm(e, x)
  File "/home/aman/Desktop/testing/sympy/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/aman/Desktop/testing/sympy/sympy/series/gruntz.py", line 512, in mrv_leadterm
    Omega, exps = mrv(e, x)
  File "/home/aman/Desktop/testing/sympy/sympy/series/gruntz.py", line 317, in mrv
    raise NotImplementedError(
NotImplementedError: Don't know how to calculate the mrv of 'E*cos(1/_p) + E*sin(1/_p)*i + 0*j + 0*k'
```
 

A way to solve this may be to overwrite `.limit()` function for `class Quaternion` by calculating the limits for each argument of the Quaternion and returning a new Quaternion with the outputs of limits. Something like:
```python
class Quaternion(a,b,c,d):
    #within class Quaternion
    def limit(self, x, xlim): 
        qa = limit(self.a, x, xlim)
        qb = limit(self.b, x, xlim)
        qc = limit(self.c, x, xlim)
        qd = limit(self.d, x, xlim)
        return Quaternion(qa, qb, qc, qd)
```

>In [18]: q.exp().subs(a, 0)
>Out[18]: 1 + nan*i + 0*j + 0*k

This change will return correct limit for this example if we use `q.exp().limit(a, 0)`.

If we want `subs()` to produce the outputs with limits then we can overwrite it too so that it calls the `limit()` function everytime an output goes nan.

**Comment by oscarbenjamin** [comment]
We don't need to use limits here. Potentially a Piecewise could be used. Ideally there would be a symbolic way of expressing the formula that doesn't need special cases.

**Comment by vr050714** [comment]
Even better, `sinc` function can be used, since it explicitly appears in the exponent of quaternion.

**Comment by vr050714** [comment]
There is strange result of logarithm of quaternion in case when all imaginary components are zero.
In this case `acos(w)=0` when `w**2+x**2+y**2+z**2==1` and `x**2+y**2+z**2==0` since w=1 and 0/0 indeterminate form reduces to 1.
![qtrn_log_error](https://user-images.githubusercontent.com/8076819/121791081-bd172e00-cbee-11eb-93fb-3643d2046e6c.png)

**Comment by oscarbenjamin** [comment]
Please include code (copy-pastable) and not pictures of code.
```python
In [25]: w, x, y, z = symbols('w, x, y, z')

In [26]: q = Quaternion(w, x, y, z)

In [27]: q._ln()
Out[27]: 
log(sqrt(w**2 + x**2 + y**2 + z**2)) + x*acos(w/sqrt(w**2 + x**2 + y**2 + z**2))/sqrt(x**2 + y**2 + z**2)*i + y*acos(w/sqrt(w**2 + x**2 + y**2 + z**2))/sqrt
(x**2 + y**2 + z**2)*j + z*acos(w/sqrt(w**2 + x**2 + y**2 + z**2))/sqrt(x**2 + y**2 + z**2)*k

In [28]: q._ln().subs(w**2 + x**2 + y**2 + z**2, 1)
Out[28]: 0 + x*acos(w)/sqrt(x**2 + y**2 + z**2)*i + y*acos(w)/sqrt(x**2 + y**2 + z**2)*j + z*acos(w)/sqrt(x**2 + y**2 + z**2)*k

In [29]: q._ln().subs(w**2 + x**2 + y**2 + z**2, 1).subs({x:0, y:0, z:0})
Out[29]: 0 + 0*i + 0*j + nan*k
```
This looks like another case where a Piecewise or a better form for the expression could be used instead of e.g. `x*acos(w)/sqrt(x**2 + y**2 + z**2)` since that form does allow for the possibility that x, y and z could be all zero.

**Comment by vr050714** [comment]
The last example with logarithm is a bit weird since expressions for all three imaginary components are similar but only `d` is `nan`.

**Comment by oscarbenjamin** [comment]
That's because the substitutions are done one by one:
```python
In [6]: q._ln().subs(w**2 + x**2 + y**2 + z**2, 1)
Out[6]: 0 + x*acos(w)/sqrt(x**2 + y**2 + z**2)*i + y*acos(w)/sqrt(x**2 + y**2 + z**2)*j + z*acos(w)/sqrt(x**2 + y**2 + z**2)*k

In [7]: q._ln().subs(w**2 + x**2 + y**2 + z**2, 1).subs(x, 0)
Out[7]: 0 + 0*i + y*acos(w)/sqrt(y**2 + z**2)*j + z*acos(w)/sqrt(y**2 + z**2)*k

In [8]: q._ln().subs(w**2 + x**2 + y**2 + z**2, 1).subs(x, 0).subs(y, 0)
Out[8]: 0 + 0*i + 0*j + z*acos(w)/sqrt(z**2)*k

In [9]: q._ln().subs(w**2 + x**2 + y**2 + z**2, 1).subs(x, 0).subs(y, 0).subs(z, 0)
Out[9]: 0 + 0*i + 0*j + nan*k

In [10]: q._ln().subs(w**2 + x**2 + y**2 + z**2, 1).subs({x:0, y:0, z:0}, simultaneous=True)
Out[10]: 0 + nan*i + nan*j + nan*k
```

**Comment by mostlyaman** [comment]
>Potentially a Piecewise could be used

@oscarbenjamin I tried your Piecewise suggestion in the following way but it is not perfect. Could you please guide me?
```python
        vector_norm = sqrt(q.b**2 + q.c**2 + q.d**2)
        a = exp(q.a) * cos(vector_norm)
        b = exp(q.a) * Piecewise((0, all([i in (0,S.Zero) for i in q.args[1:]])),
                                 (sin(vector_norm) * q.b / vector_norm, True))
        c = exp(q.a) * Piecewise((0, all([i in (0,S.Zero) for i in q.args[1:]])),
                                 (sin(vector_norm) * q.c / vector_norm, True))
        d = exp(q.a) * Piecewise((0, all([i in (0,S.Zero) for i in q.args[1:]])),
                                 (sin(vector_norm) * q.d / vector_norm, True))

        return Quaternion(a, b, c, d)
```
```python
>>> q=Quaternion(a,b,c,d)
>>> q.subs({a:1,b:0,c:0,d:0}).exp() #works when the substitution takes place before the exp
E + 0*i + 0*j + 0*k
>>> q.exp().subs({a:1,b:0,c:0,d:0}) #does not work in this case
E + 0*i + 0*j + nan*k
```

**Comment by oscarbenjamin** [comment]
The condition in the piecewise needs to be a symbolic boolean expression. Print it out to see what you are passing there:
```
print( all([i in (0,S.Zero) for i in q.args[1:]] )
```

**Comment by mostlyaman** [comment]
I tried to make it return True when b==c==d==0 but I guess it is not supposed to work like that. I found that Not(vector_norm) is a better condition for piecewise but it not perfect either. Its my first time using Piecewise and symbolic Boolean expression. I read the docs but could not find much help. Could you guide me with some resource.

**Comment by oscarbenjamin** [comment]
Rather than `all` you should use sympy's symbolic `And` function.

**Comment by praneethratna** [comment]
So we have two possibilities of using `sinc` in place of sin , using sinc directly or rewriting sinc as piecewise function ie `sinx/x` by using sympy rewrite function, But I'm not sure of which one is a reasonable one to use. @oscarbenjamin

**Comment by oscarbenjamin** [comment]
Can you demonstrate what the different possibilities look like and what happens when manipulating them?

**Comment by praneethratna** [comment]
The 1st possibility is using sinc directly in the exp() method , the output is:
```
>>> Quaternion(1, 2, 3, 4).exp()
>>> E*cos(sqrt(29)) + 2*E*sinc(sqrt(29))*i + 3*E*sinc(sqrt(29))*j + 4*E*sinc(sqrt(29))*k
```
But when someone wants the imaginary part in terms of sin , I'm not sure of how to do that, I tried using .rewrite(sin) but which gives an output `(sinh(1) + cosh(1))*sin(pi/2 + sqrt(29)) + 2*sqrt(29)*(sinh(1) + cosh(1))*sin(sqrt(29))/29*i + 3*sqrt(29)*(sinh(1) + cosh(1))*sin(sqrt(29))/29*j + 4*sqrt(29)*(sinh(1) + cosh(1))*sin(sqrt(29))/29*k` where exponential is being written in terms of `sinh` and `cosh` .
and second possibility is using sinc.rewrite(sin) instead of sinc directly in the exp() method, which gives an output :
```
>>> Quaternion(1, 2, 3, 4).exp()
>>> E*sin(pi/2 + sqrt(29)) + 2*sqrt(29)*E*sin(sqrt(29))/29*i + 3*sqrt(29)*E*sin(sqrt(29))/29*j + 4*sqrt(29)*E*sin(sqrt(29))/29*k
```
This seems like a more clear output which is in terms of sin but is there any way to get this output from `E*cos(sqrt(29)) + 2*E*sinc(sqrt(29))*i + 3*E*sinc(sqrt(29))*j + 4*E*sinc(sqrt(29))*k` without rewriting the exponential in terms of sinh and cosh ? @oscarbenjamin

**Comment by vr050714** [comment]
> So we have two possibilities of using `sinc` in place of sin in exp() method, using `sinc` directly or rewriting `sinc` as piecewise function ie `sinx/x` by using sympy rewrite function, But I'm not sure of which is a reasonable one to use. @oscarbenjamin

Maybe just direct use of `Picewise` instead of `sinc` can be a solution to the problem. There is an example:

```python
>>> from sympy import sin, cos, exp, sqrt
>>> from sympy import Quaternion
>>> from sympy import Piecewise
>>>
>>> from sympy.abc import a
>>>
>>> def qtrn_exp(q):
...     phi = sqrt(q.b**2 + q.c**2 + q.d**2)
...     a = exp(q.a) * cos(phi)
...     b = exp(q.a) * Piecewise((q.b, phi.is_zero==True),
...                                 (q.b * sin(phi)/phi, True))
...     c = exp(q.a) * Piecewise((q.c, phi.is_zero==True),
...                                 (q.c * sin(phi)/phi, True))
...     d = exp(q.a) * Piecewise((q.d, phi.is_zero==True),
...                                 (q.d * sin(phi)/phi, True))
...     return Quaternion(a, b, c, d)
...
>>> q1 = Quaternion(0,a,0,0)
>>> qtrn_exp(q1)
cos(sqrt(a**2)) + a*sin(sqrt(a**2))/sqrt(a**2)*i + 0*j + 0*k
>>>
>>> q2 = Quaternion(a,0,0,0)
>>> qtrn_exp(q2)
exp(a) + 0*i + 0*j + 0*k
```

**Comment by praneethratna** [comment]
> > So we have two possibilities of using `sinc` in place of sin in exp() method, using `sinc` directly or rewriting `sinc` as piecewise function ie `sinx/x` by using sympy rewrite function, But I'm not sure of which is a reasonable one to use. @oscarbenjamin
> 
> Maybe just direct use of `Picewise` instead of `sinc` can be a solution to the problem. There is an example:
> 
> ```python
> >>> from sympy import sin, cos, exp, sqrt
> >>> from sympy import Quaternion
> >>> from sympy import Piecewise
> >>>
> >>> from sympy.abc import a
> >>>
> >>> def qtrn_exp(q):
> ...     phi = sqrt(q.b**2 + q.c**2 + q.d**2)
> ...     a = exp(q.a) * cos(phi)
> ...     b = exp(q.a) * Piecewise((q.b, phi.is_zero==True),
> ...                              (q.b * sin(phi)/phi, True))
> ...     c = exp(q.a) * Piecewise((q.c, phi.is_zero==True),
> ...                              (q.c * sin(phi)/phi, True))
> ...     d = exp(q.a) * Piecewise((q.d, phi.is_zero==True),
> ...                              (q.d * sin(phi)/phi, True))
> ...     return Quaternion(a, b, c, d)
> ...
> >>> q1 = Quaternion(0,a,0,0)
> >>> qtrn_exp(q1)
> cos(sqrt(a**2)) + a*sin(sqrt(a**2))/sqrt(a**2)*i + 0*j + 0*k
> >>>
> >>> q2 = Quaternion(a,0,0,0)
> >>> qtrn_exp(q2)
> exp(a) + 0*i + 0*j + 0*k
> ```

The Piecewise function that you have mentioned `Piecewise((q.b, phi.is_zero==True), (q.b * sin(phi)/phi, True))` is indeed the `sinc` function if we remove the `q.b` inside the Piecewise function.

**Comment by vr050714** [comment]
> > > So we have two possibilities of using `sinc` in place of sin in exp() method, using `sinc` directly or rewriting `sinc` as piecewise function ie `sinx/x` by using sympy rewrite function, But I'm not sure of which is a reasonable one to use. @oscarbenjamin
> > 
> > 
> > Maybe just direct use of `Picewise` instead of `sinc` can be a solution to the problem. There is an example:
> > ```python
> > >>> from sympy import sin, cos, exp, sqrt
> > >>> from sympy import Quaternion
> > >>> from sympy import Piecewise
> > >>>
> > >>> from sympy.abc import a
> > >>>
> > >>> def qtrn_exp(q):
> > ...     phi = sqrt(q.b**2 + q.c**2 + q.d**2)
> > ...     a = exp(q.a) * cos(phi)
> > ...     b = exp(q.a) * Piecewise((q.b, phi.is_zero==True),
> > ...                              (q.b * sin(phi)/phi, True))
> > ...     c = exp(q.a) * Piecewise((q.c, phi.is_zero==True),
> > ...                              (q.c * sin(phi)/phi, True))
> > ...     d = exp(q.a) * Piecewise((q.d, phi.is_zero==True),
> > ...                              (q.d * sin(phi)/phi, True))
> > ...     return Quaternion(a, b, c, d)
> > ...
> > >>> q1 = Quaternion(0,a,0,0)
> > >>> qtrn_exp(q1)
> > cos(sqrt(a**2)) + a*sin(sqrt(a**2))/sqrt(a**2)*i + 0*j + 0*k
> > >>>
> > >>> q2 = Quaternion(a,0,0,0)
> > >>> qtrn_exp(q2)
> > exp(a) + 0*i + 0*j + 0*k
> > ```
> 
> The Piecewise function that you have mentioned `Piecewise((q.b, phi.is_zero==True), (q.b * sin(phi)/phi, True))` is indeed the `sinc` function if we remove the `q.b` inside the Piecewise function.

That's true unless the expression with `sinc` will be simplified further. For example:
```python
>>> from sympy import sqrt, sin, sinc
>>> from sympy import symbols, simplify, trigsimp
>>>
>>> x = symbols('x')  # no assumptions
>>> a = symbols('a', real=True, positive=True)
>>>
>>> ex1 = x * sin(sqrt(x**2))/sqrt(x**2)
>>> ex1.simplify()
x*sin(sqrt(x**2))/sqrt(x**2)
>>>
>>> ex2 = a * sin(sqrt(a**2)) / sqrt(a**2)
>>> ex2  # it is already simplified
sin(a)
>>>
>>> ex3 = a * sinc(sqrt(a**2))
>>>
>>> # Both functions don't simplify despite that the variable `a` is a real
>>> # positive number
>>>
>>> simplify(ex3)
a*sinc(a)
>>>
>>> trigsimp(ex3)
a*sinc(a)
```
In the example the `ex3` expression cannot be simplified despite that `a` is a real positive value.

**Comment by praneethratna** [comment]
> > > > So we have two possibilities of using `sinc` in place of sin in exp() method, using `sinc` directly or rewriting `sinc` as piecewise function ie `sinx/x` by using sympy rewrite function, But I'm not sure of which is a reasonable one to use. @oscarbenjamin
> > > 
> > > 
> > > Maybe just direct use of `Picewise` instead of `sinc` can be a solution to the problem. There is an example:
> > > ```python
> > > >>> from sympy import sin, cos, exp, sqrt
> > > >>> from sympy import Quaternion
> > > >>> from sympy import Piecewise
> > > >>>
> > > >>> from sympy.abc import a
> > > >>>
> > > >>> def qtrn_exp(q):
> > > ...     phi = sqrt(q.b**2 + q.c**2 + q.d**2)
> > > ...     a = exp(q.a) * cos(phi)
> > > ...     b = exp(q.a) * Piecewise((q.b, phi.is_zero==True),
> > > ...                              (q.b * sin(phi)/phi, True))
> > > ...     c = exp(q.a) * Piecewise((q.c, phi.is_zero==True),
> > > ...                              (q.c * sin(phi)/phi, True))
> > > ...     d = exp(q.a) * Piecewise((q.d, phi.is_zero==True),
> > > ...                              (q.d * sin(phi)/phi, True))
> > > ...     return Quaternion(a, b, c, d)
> > > ...
> > > >>> q1 = Quaternion(0,a,0,0)
> > > >>> qtrn_exp(q1)
> > > cos(sqrt(a**2)) + a*sin(sqrt(a**2))/sqrt(a**2)*i + 0*j + 0*k
> > > >>>
> > > >>> q2 = Quaternion(a,0,0,0)
> > > >>> qtrn_exp(q2)
> > > exp(a) + 0*i + 0*j + 0*k
> > > ```
> > 
> > 
> > The Piecewise function that you have mentioned `Piecewise((q.b, phi.is_zero==True), (q.b * sin(phi)/phi, True))` is indeed the `sinc` function if we remove the `q.b` inside the Piecewise function.
> 
> That's true unless the expression with `sinc` will be simplified further. For example:
> 
> ```python
> >>> from sympy import sqrt, sin, sinc
> >>> from sympy import symbols, simplify, trigsimp
> >>>
> >>> x = symbols('x')  # no assumptions
> >>> a = symbols('a', real=True, positive=True)
> >>>
> >>> ex1 = x * sin(sqrt(x**2))/sqrt(x**2)
> >>> ex1.simplify()
> x*sin(sqrt(x**2))/sqrt(x**2)
> >>>
> >>> ex2 = a * sin(sqrt(a**2)) / sqrt(a**2)
> >>> ex2  # it is already simplified
> sin(a)
> >>>
> >>> ex3 = a * sinc(sqrt(a**2))
> >>>
> >>> # Both functions don't simplify despite that the variable `a` is a real
> >>> # positive number
> >>>
> >>> simplify(ex3)
> a*sinc(a)
> >>>
> >>> trigsimp(ex3)
> a*sinc(a)
> ```
> 
> In the example the `ex3` expression cannot be simplified despite that `a` is a real positive value.

It will not be simplified but you can rewrite in terms of `sin` using the `.rewrite()` function.

**Comment by oscarbenjamin** [comment]
It isn't necessary to quote the whole of a message when replying to it - the other messages can be seen above so quoting is just useful to clarify which part of which message you are replying to.

> In the example the `ex3` expression cannot be simplified despite that `a` is a real positive value.

It would be good to have improvements in simplify so that things like `x*sinc(x)` can be simplified. Also simplifying Piecewise could be improved:
```python
In [17]: e = sinc(x)*x

In [18]: e
Out[18]: x⋅sinc(x)

In [19]: e.rewrite(sin)
Out[19]: 
  ⎛⎧sin(x)           ⎞
  ⎜⎪──────  for x ≠ 0⎟
x⋅⎜⎨  x              ⎟
  ⎜⎪                 ⎟
  ⎝⎩  1     otherwise⎠

In [20]: simplify(_)
Out[20]: 
⎧sin(x)  for x ≠ 0
⎨                 
⎩  x     otherwise
```
It should be possible for simplify to figure out that this Piecewise can just be `sin(x)`. Since the first condition is `x != 0` we can substitute `x=0` into all cases below. It should then be possible to figure out that also substituting `x=0` into `sin(x)` gives `0` as well so that the two cases can be merged into `sin(x)`. If those improvements to simplifying `Piecewise` were made then it would be easy to add something to handle this kind of simplification of `sinc` by rewriting to `sin`.

I think that improvements to `simplify` are a separate question and should not be the deciding factor here. The question is what is a better form for the output.

**Comment by praneethratna** [comment]
> The question is what is a better form for the output.
>
I feel `sin` is better over `sinc` since the formula for exp() of a Quaternion is `e^a(cos||v|| + v/||v||*sin||v||)` and a output of `sinc(||v||)` instead of `sin(||v||)/||v||` is not what someone expects.

**Comment by praneethratna** [comment]
@oscarbenjamin Any solution for what might be better form of output?

**Comment by praneethratna** [comment]
> I think that improvements to `simplify` are a separate question and should not be the deciding factor here. The question is what is a better form for the output.

Maybe we can explicity mention in the docstrings regarding the form of output being `sinc` and mention about `rewrite` using `sin`?
