### ISSUE TITLE
SymPy Live Shell  /app/handlers.py

### ISSUE THREAD

**Issue by QGB** [sympy/sympy#21668]
```
xception in SymPy Live of type 
<type 'exceptions.TypeError'>
for reference the last 5 stack trace entries are
Traceback (most recent call last):
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/handlers.py", line 271, in post
    live.evaluate(statement, session, printer, stream)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/shell.py", line 280, in evaluate
    exec code in statement_module.__dict__
  File "<string>", line 1, in <module>
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by oscarbenjamin** [comment]
Can you explain what the issue is?
