### ISSUE TITLE
solve hangs while solving simutaneous equations

### ISSUE THREAD

**Issue by ashvinoli** [sympy/sympy#21694]
The system hangs while solving the given equation.
```
from sympy import *


ux,uy,uz,A_mn,B_mn,C_mn,n,x,y,a,m,b,C,nu,k1,k2,h,X,Y,Z,D_mn,E_mn,F_mn,E,l,beta,R,beta_0 = symbols("ux,uy,uz,A_mn,B_mn,C_mn,n,x,y,a,m,b,C,nu,k1,k2,h,X,Y,Z,D_mn,E_mn,F_mn,E,l,beta,R,beta_0")


eq1 = -pi**2*A_mn*m**2/l**2 + A_mn*n**2*nu/(2*R**2) - A_mn*n**2/(2*R**2) + pi*B_mn*m*n*nu/(2*R*l) + pi*B_mn*m*n/(2*R*l) + pi*C_mn*m*nu/(R*l) + D_mn/C

eq2 = pi*A_mn*m*n*nu/(2*R*l) + pi*A_mn*m*n/(2*R*l) + pi**2*B_mn*m**2*nu/(2*l**2) - pi**2*B_mn*m**2/(2*l**2) - B_mn*n**2/R**2 - pi**2*C_mn*h**2*m**2*n/(12*R**2*l**2) - C_mn*n/R**2 - C_mn*h**2*n**3/(12*R**4) + E_mn/C

eq3 = -pi*A_mn*m*nu/(R*l) + pi**2*B_mn*h**2*m**2*n/(12*R**2*l**2) + B_mn*n/R**2 + B_mn*h**2*n**3/(12*R**4) + pi**4*C_mn*h**2*m**4/(12*l**4) + pi**2*C_mn*h**2*m**2*n**2/(6*R**2*l**2) + C_mn/R**2 + C_mn*h**2*n**4/(12*R**4) - F_mn/C

solution = solve([eq1,eq2,eq3],[A_mn,B_mn,C_mn])

```

**Comment by oscarbenjamin** [comment]
What version of sympy are you using? With current master I get a solution in 23 seconds:
```python
In [1]: from sympy import *
   ...: 
   ...: 
   ...: ux,uy,uz,A_mn,B_mn,C_mn,n,x,y,a,m,b,C,nu,k1,k2,h,X,Y,Z,D_mn,E_mn,F_mn,E,l,beta,R,beta_0 = symbols("ux,uy,uz,A_mn,B_mn,C_mn,n,x,y,a,m,b,C,nu,k1,k2,h,X,
   ...: Y,Z,D_mn,E_mn,F_mn,E,l,beta,R,beta_0")
   ...: 
   ...: 
   ...: eq1 = -pi**2*A_mn*m**2/l**2 + A_mn*n**2*nu/(2*R**2) - A_mn*n**2/(2*R**2) + pi*B_mn*m*n*nu/(2*R*l) + pi*B_mn*m*n/(2*R*l) + pi*C_mn*m*nu/(R*l) + D_mn/C
   ...: 
   ...: eq2 = pi*A_mn*m*n*nu/(2*R*l) + pi*A_mn*m*n/(2*R*l) + pi**2*B_mn*m**2*nu/(2*l**2) - pi**2*B_mn*m**2/(2*l**2) - B_mn*n**2/R**2 - pi**2*C_mn*h**2*m**2*n/
   ...: (12*R**2*l**2) - C_mn*n/R**2 - C_mn*h**2*n**3/(12*R**4) + E_mn/C
   ...: 
   ...: eq3 = -pi*A_mn*m*nu/(R*l) + pi**2*B_mn*h**2*m**2*n/(12*R**2*l**2) + B_mn*n/R**2 + B_mn*h**2*n**3/(12*R**4) + pi**4*C_mn*h**2*m**4/(12*l**4) + pi**2*C_
   ...: mn*h**2*m**2*n**2/(6*R**2*l**2) + C_mn/R**2 + C_mn*h**2*n**4/(12*R**4) - F_mn/C

In [2]: %time solution = solve([eq1,eq2,eq3],[A_mn,B_mn,C_mn])
CPU times: user 22.8 s, sys: 268 ms, total: 23 s
Wall time: 23.1 s
```
I do think that should be faster but the answer is returned. Also `linsolve` is slower for some reason. That should be improved.

**Comment by ashvinoli** [comment]
I was using 1.7 previously. But after your answer I upgraded to 1.8, but the problem is still there. I tried running it on different device, it is stuck there as well. And whenever I interrupt it no matter after how long, the trace always looks like this, stuck at `return python_gcd(a,b)`:

```shell
Traceback (most recent call last):
  File "problem.py", line 13, in <module>
    solution = solve([eq1,eq2,eq3],[A_mn,B_mn,C_mn])
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\solvers\solvers.py", line 1097, in solve
    solution = _solve_system(f, symbols, **flags)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\solvers\solvers.py", line 1830, in _solve_system
    result = solve_linear_system(matrix, *symbols, **flags)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\solvers\solvers.py", line 2304, in solve_linear_system
    sol = solve_lin_sys(eqs, ring, _raw=False)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\solvers.py", line 227, in solve_lin_sys
    result = _solve_lin_sys(eqs_coeffs, eqs_rhs, ring)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\solvers.py", line 305, in _solve_lin_sys
    subsol = _solve_lin_sys_component(subsystem[0], subsystem[1], ring)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\solvers.py", line 353, in _solve_lin_sys_component
    echelon, pivots = matrix.rref()
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\matrices\domainmatrix.py", line 869, in rref
    rref_ddm, pivots = self.rep.rref()
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\matrices\ddm.py", line 243, in rref
    pivots = ddm_irref(b)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\matrices\dense.py", line 113, in ddm_irref
    ai[l] *= aijinv # ai[j] = one
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\fields.py", line 495, in __mul__
    return f.new(f.numer*g.numer, f.denom*g.denom)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\fields.py", line 299, in new
    return f.raw_new(*numer.cancel(denom))
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\rings.py", line 2220, in cancel
    _, p, q = f.cofactors(g)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\rings.py", line 2136, in cofactors
    h, cff, cfg = f._gcd(g)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\rings.py", line 2169, in _gcd
    return f._gcd_ZZ(g)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\rings.py", line 2174, in _gcd_ZZ
    return heugcd(f, g)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\heuristicgcd.py", line 80, in heugcd
    h, cff, cfg = heugcd(ff, gg)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\heuristicgcd.py", line 80, in heugcd
    h, cff, cfg = heugcd(ff, gg)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\heuristicgcd.py", line 80, in heugcd
    h, cff, cfg = heugcd(ff, gg)
  [Previous line repeated 7 more times]
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\heuristicgcd.py", line 78, in heugcd
    h, cff, cfg = domain.cofactors(ff, gg)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\domains\domain.py", line 1155, in cofactors
    gcd = self.gcd(a, b)
  File "C:\Users\Ashvin Oli\AppData\Local\Programs\Python\Python37\lib\site-packages\sympy\polys\domains\pythonintegerring.py", line 80, in gcd
    return python_gcd(a, b)

```

**Comment by smichr** [comment]
Try the following (modified from a recent [SO post](https://stackoverflow.com/questions/68177968/the-commands-linsolve-or-solve-from-sympy-cannot-solve-a-1d-linear-equation/68185736#68185736)):

```python
def keepx(eq, *x):
  """collapse non-x dependent Add and Mul into Duumy symbols
  and return e, r where e is the new expresion and r is
  the dictionary that can restore e: eq == e.xreplace(r)

  Examples
  ========

  >>> from sympy import solve, symbols
  >>> from sympy.abc import x
  >>> y = symbols('y', positive=True)
  >>> eq = 1/(3*x*y + 1) + 4*x*y + 5

  Dummy symbols with no name are used to keep track of the
  constants. The retain unique identity, however:

  >>> e, r = keepx(eq, x); e
  _ + _*x + 1/(_ + _*x)
  >>> assert e.xreplace(r) == eq
  >>> sol = solve(eq, x)
  >>> _sol = [i.xreplace(r).factor() for i in solve(e, x)]
  >>> assert sol == _sol
  """
  reps = {}
  def store(i):
      d = Dummy('')
      reps[d] = i
      return d
  def do(e):
    if e.is_Add or e.is_Mul:
        i, d = e.as_independent(*x)
        if i is not e.identity:
            i = store(i)
            d = do(d)
            return e.func(i, d)
    if not e.args:
        return e
    return e.func(*[do(i) for i in e.args])
  return do(eq), reps

v = symbols('A_mn,B_mn,C_mn')
e, r = zip(*[keepx(collect(i,v),*v) for i in (eq1,eq2,eq3)])
dsol = solve(e, v)[[0]
for k in dsol:
  s = dsol[k]
  for ri in r:
    s = s.xreplace(ri)
dsol
```

It solves in less than a blink online at replit.com.

Note, the collect step is important. It was much slower without that.

**Comment by smichr** [comment]
@moorepants , it would be interesting to see if this collection of symbols helps your dynamics calculations.

**Comment by moorepants** [comment]
I typically covert linear systems to matrix form and solve with `LUsolve()`, but when teaching dynamics it's nice if students can use `solve()` at first for simplicity. There are definitely past instances where that takes some time.

**Comment by ashvinoli** [comment]
@smichr 
I guess instead of `dsol = solve(e,v)[[0]`  almost at the end of file, it was `dsol = solve(e,v)` , right? Other than it it seems to work fine. Thanks!

**Comment by oscarbenjamin** [comment]
> But after your answer I upgraded to 1.8, but the problem is still there.

I just tried 1.8 and it took the same amount of time as current master (23 seconds):
```python
In [2]: %time solution = solve([eq1,eq2,eq3],[A_mn,B_mn,C_mn])
CPU times: user 22.9 s, sys: 310 ms, total: 23.2 s
Wall time: 23.3 s
```
However I have gmpy2 installed which can speed up some things a lot. I just tried without gmpy2 installed and it's a lot slower (not sure how long it takes).

I'm reopening because various things can be improved in sympy for this. Both `solve`, `linsolve` and `inv` can be faster for this.

The simplest implementation for such a small 3x3 system would be to compute the inverse via determinant and adjugate but the other methods should all be made faster as well:
```python
In [2]: A, b = linear_eq_to_matrix([eq1,eq2,eq3],[A_mn,B_mn,C_mn])

In [3]: %time sol = (A.adjugate() * b) / A.det()
CPU times: user 1.34 s, sys: 5.96 ms, total: 1.35 s
Wall time: 1.35 s
```

**Comment by smichr** [comment]
The time difference for this simple 3x3 system is dramatic.

But I worry a bit about treating all constants as independent of each other.

**Comment by oscarbenjamin** [comment]
> But I worry a bit about treating all constants as independent of each other.

What do you mean?

The formula I just showed as correct provided `detA != 0` which is:
```python
In [4]: repr(A.det())
Out[4]: '(-12*pi**8*R**10*h**2*m**8*nu + 12*pi**8*R**10*h**2*m**8 - 48*pi**6*R**8*h**2*l**2*m**6*n**2*nu + 48*pi**6*R**8*h**2*l**2*m**6*n**2 + 144*pi**4*R**8*l**4*m**4*nu**3 - 144*pi**4*R**8*l**4*m**4*nu**2 - 144*pi**4*R**8*l**4*m**4*nu + 144*pi**4*R**8*l**4*m**4 - 2*pi**6*R**6*h**4*l**2*m**6*n**2 - 72*pi**4*R**6*h**2*l**4*m**4*n**4*nu + 72*pi**4*R**6*h**2*l**4*m**4*n**4 + 24*pi**4*R**6*h**2*l**4*m**4*n**2*nu**2 + 24*pi**4*R**6*h**2*l**4*m**4*n**2*nu - 48*pi**4*R**6*h**2*l**4*m**4*n**2 + pi**4*R**4*h**4*l**4*m**4*n**4*nu - 5*pi**4*R**4*h**4*l**4*m**4*n**4 - 48*pi**2*R**4*h**2*l**6*m**2*n**6*nu + 48*pi**2*R**4*h**2*l**6*m**2*n**6 + 24*pi**2*R**4*h**2*l**6*m**2*n**4*nu**2 + 48*pi**2*R**4*h**2*l**6*m**2*n**4*nu - 72*pi**2*R**4*h**2*l**6*m**2*n**4 + 2*pi**2*R**2*h**4*l**6*m**2*n**6*nu - 4*pi**2*R**2*h**4*l**6*m**2*n**6 - 12*R**2*h**2*l**8*n**8*nu + 12*R**2*h**2*l**8*n**8 + 24*R**2*h**2*l**8*n**6*nu - 24*R**2*h**2*l**8*n**6 + h**4*l**8*n**8*nu - h**4*l**8*n**8)/(288*R**10*l**8)'
```
For almost all possible values of the system parameters `R, m, ...` this will be nonzero so the solution is valid in the generic case. It would be nice to let the user know the conditions of validity for a solution such as this but none of the current solvers does that.
