### ISSUE TITLE
Exception plotting integration result using plot3d

### ISSUE THREAD

**Issue by Jan-Blaha** [sympy/sympy#21861]
Hi,

using sympy (1.8), I'm solving a simple problem, that does not look problematic at all.

```
import sympy
x, p, v = sympy.symbols("x p v")
res = sympy.integrate((sympy.sin(2 * x + 3) - sympy.cos(v * x + p)) ** 2, (x, (-10, 10)))
sympy.plotting.plot3d(res)
```

instead of the expected plot I get an exception

```
Traceback (most recent call last):
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 23, in as_Basic
    return _sympify(expr)
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/core/sympify.py", line 512, in _sympify
    return sympify(a, strict=True)
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/core/sympify.py", line 433, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: array([[32.88035393+0.j, 26.06311306+0.j, 18.13834649+0.j, ...,
        27.41764318+0.j, 19.6010239 +0.j, 11.73858189+0.j],
       [32.88035393+0.j, 26.06311306+0.j, 18.13834649+0.j, ...,
        27.41764318+0.j, 19.6010239 +0.j, 11.73858189+0.j],
       [32.88035393+0.j, 26.06311306+0.j, 18.13834649+0.j, ...,
        27.41764318+0.j, 19.6010239 +0.j, 11.73858189+0.j],
       ...,
       [32.88035393+0.j, 26.06311306+0.j, 18.13834649+0.j, ...,
        27.41764318+0.j, 19.6010239 +0.j, 11.73858189+0.j],
       [32.88035393+0.j, 26.06311306+0.j, 18.13834649+0.j, ...,
        27.41764318+0.j, 19.6010239 +0.j, 11.73858189+0.j],
       [32.88035393+0.j, 26.06311306+0.j, 18.13834649+0.j, ...,
        27.41764318+0.j, 19.6010239 +0.j, 11.73858189+0.j]])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jan/.config/JetBrains/PyCharm2021.1/scratches/scratch_1.py", line 8, in <module>
    sympy.plotting.plot3d(res)
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 2186, in plot3d
    plots.show()
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 222, in show
    self._backend.show()
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 1416, in show
    self.process_series()
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 1413, in process_series
    self._process_series(series, ax, parent)
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 1255, in _process_series
    x, y, z = s.get_meshes()
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/plotting/plot.py", line 988, in get_meshes
    mesh_z = f(mesh_x, mesh_y)
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/plotting/experimental_lambdify.py", line 130, in __call__
    results = self.vector_func(*temp_args)
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/plotting/experimental_lambdify.py", line 272, in __call__
    return self.lambda_func(*args, **kwargs)
  File "<string>", line 1, in <lambda>
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/functions/elementary/piecewise.py", line 127, in __new__
    pair = ExprCondPair(*getattr(ec, 'args', ec))
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/functions/elementary/piecewise.py", line 19, in __new__
    expr = as_Basic(expr)
  File "/home/jan/miniconda3/lib/python3.7/site-packages/sympy/core/basic.py", line 27, in as_Basic
    expr))
TypeError: Argument must be a Basic object, not `ndarray`
```

The result of integral computation seems to be just a normal fine Piecewise, but changing the integrand (just removing p) does not throw exception anymore, so I figured this will be some bug.

**Comment by oscargus** [comment]
`res` is a piecewise function:
![image](https://user-images.githubusercontent.com/8114497/135110627-537059ca-f7e8-4ab5-aa5d-e735fb78f326.png)

so most likely this is related to other problems plotting piecewises.

**Comment by oscargus** [comment]
This can be fixed by also catching TypeError here:
https://github.com/sympy/sympy/blob/26a3cfc5a3b3de3495756cc1ad565d791fcc76ff/sympy/plotting/experimental_lambdify.py#L135

Not sure that is a good idea though...
