### ISSUE TITLE
ValueError: list.remove(x): x not in list occurs in nonlinsolve

### ISSUE THREAD

**Issue by Leone20010** [sympy/sympy#21984]
ValueError: list.remove(x): x not in list occurs trying to solve with nonlinsolve a system of non linear equations. 

Full traceback:
```python
Traceback (most recent call last):
  File "C:\Users\cinza\PycharmProjects\pHmetro\pHmetro.py", line 16, in <module>
    sol = nonlinsolve([eq1, eq2, eq3, eq4], [H, OH, HA, A])
  File "C:\Users\cinza\PycharmProjects\pHmetro\venv\lib\site-packages\sympy\solvers\solveset.py", line 3682, in nonlinsolve
    result = substitution(
  File "C:\Users\cinza\PycharmProjects\pHmetro\venv\lib\site-packages\sympy\solvers\solveset.py", line 3337, in substitution
    new_result_real, solve_call1, cnd_call1 = _solve_using_known_values(
  File "C:\Users\cinza\PycharmProjects\pHmetro\venv\lib\site-packages\sympy\solvers\solveset.py", line 3327, in _solve_using_known_values
    result.remove(res)
ValueError: list.remove(x): x not in list
```
Code:
```python
from sympy import *
from numpy import *

ka = 10 * * 5  
C0 = 10 * * -10
kw = 10**-14  #that is constant
H, OH, HA, A = symbols("H, OH, HA, A")  

eq1 = Eq((H*A/HA)-ka, 0)
eq2 = Eq(H*OH-kw, 0)
eq3 = Eq(A+OH-H, 0)
eq4 = Eq(HA+A-C0, 0)

sol = nonlinsolve([eq1, eq2, eq3, eq4], [H, OH, HA, A])
print(sol)
```
nonlinsolve works fine only for some values of ka and C0. In particular I observed: if ka is >100 C0 cannot be <10^-1. If ka less than 1 there's is a sort of relation that can make C0 smaller. It seems that the difference between C0 and ka matters. If you try with ka=10 and C0=0.500, it works.

This program is develop to solve a chemistry equilibrium: not only it should be able to perform with high ka and small C0, but also I wrote two years ago the same "code" on Mathematica (W.A.) and obv it worked. Just to say that I don't think that it's a generic math problem, but a nonlinsolve's math problem.

I searched online and found this #15422 where a similiar issue is analysed, but I don't get if someone has already fixed it. I'm using Python 3.9.6 in PyCharm 2021.2 with Sympy 1.8 module.

**Comment by Leone20010** [comment]
SOLVED: Thanks for pointing out Diofant, it works great!

**Comment by oscarbenjamin** [comment]
The bug is not fixed in SymPy so the issue should not be closed.
