### ISSUE TITLE
symengine job failing in CI

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#22054]
Looks like the 0.8.0 release of symengine (2 hours ago) broke some sympy tests so that CI is now failing on the symengine job with failures like:
```
__ sympy/physics/mechanics/tests/test_joint.py:test_pin_joint_double_pendulum __
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/physics/mechanics/tests/test_joint.py", line 70, in test_pin_joint_double_pendulum
    J1 = PinJoint('J1', C, PartP, speeds=u1, coordinates=q1,
  File "/home/runner/work/sympy/sympy/sympy/physics/mechanics/joint.py", line 494, in __init__
    super().__init__(name, parent, child, coordinates, speeds,
  File "/home/runner/work/sympy/sympy/sympy/physics/mechanics/joint.py", line 145, in __init__
    self._parent_axis = self._axis(parent, parent_axis)
  File "/home/runner/work/sympy/sympy/sympy/physics/mechanics/joint.py", line 246, in _axis
    if not ax.dt(body.frame) == 0:
  File "/home/runner/work/sympy/sympy/sympy/physics/vector/vector.py", line 650, in dt
    return time_derivative(self, otherframe)
  File "/home/runner/work/sympy/sympy/sympy/physics/vector/functions.py", line 198, in time_derivative
    outlist += [(express(v[0], frame,
  File "symengine_wrapper.pyx", line 3690, in symengine.lib.symengine_wrapper.DenseMatrixBase.diff
  File "symengine_wrapper.pyx", line 4067, in symengine.lib.symengine_wrapper.diff
TypeError: Cannot convert symengine.lib.symengine_wrapper.ImmutableDenseMatrix to symengine.lib.symengine_wrapper.Basic
```

I opened a symengine issue:
https://github.com/symengine/symengine.py/issues/365

There already seems to be a symengine PR:
https://github.com/symengine/symengine.py/pull/366

**Comment by oscarbenjamin** [comment]
This was fixed upstream. Thanks @isuruf !
