### ISSUE TITLE
`series` hangs on this example

### ISSUE THREAD

**Issue by 0sidharth** [sympy/sympy#22163]
`(exp(loggamma(1/x)) - 1).series(x, logx=-y)` does not terminate. Encountered this example while debugging one of my PRs.

**Comment by oscargus** [comment]
Seems like it is the addition of the `Order` terms that (probably) takes quite some time:

```
Traceback (most recent call last):

  File "C:\Users\Oscar\AppData\Local\Temp/ipykernel_28564/4152557824.py", line 1, in <module>
    (exp(loggamma(1/x)) - 1).series(x, logx=-y)

  File "C:\Users\Oscar\sympy\sympy\core\expr.py", line 3011, in series
    rv = self.subs(x, xpos).series(xpos, x0, n, dir, logx=logx, cdir=cdir)

  File "C:\Users\Oscar\sympy\sympy\core\expr.py", line 3042, in series
    s1 = self._eval_nseries(x, n=ndo, logx=logx, cdir=cdir)

  File "C:\Users\Oscar\sympy\sympy\core\add.py", line 502, in _eval_nseries
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]

  File "C:\Users\Oscar\sympy\sympy\core\add.py", line 502, in <listcomp>
    terms = [t.nseries(x, n=n, logx=logx, cdir=cdir) for t in self.args]

  File "C:\Users\Oscar\sympy\sympy\core\expr.py", line 3373, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)

  File "C:\Users\Oscar\sympy\sympy\functions\elementary\exponential.py", line 503, in _eval_nseries
    r += Order((arg_series - arg0)**n, x)

  File "C:\Users\Oscar\sympy\sympy\core\decorators.py", line 266, in _func
    return func(self, other)

  File "C:\Users\Oscar\sympy\sympy\core\decorators.py", line 136, in binary_op_wrapper
    return func(self, other)

  File "C:\Users\Oscar\sympy\sympy\core\expr.py", line 207, in __add__
    return Add(self, other)

  File "C:\Users\Oscar\sympy\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)

  File "C:\Users\Oscar\sympy\sympy\core\operations.py", line 85, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)

  File "C:\Users\Oscar\sympy\sympy\core\add.py", line 342, in flatten
    if o.contains(t):

  File "C:\Users\Oscar\sympy\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)

  File "C:\Users\Oscar\sympy\sympy\series\order.py", line 443, in contains
    obj = self.func(expr, *self.args[1:])

  File "C:\Users\Oscar\sympy\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)

  File "C:\Users\Oscar\sympy\sympy\series\order.py", line 230, in __new__
    expr = expr.as_leading_term(*args)

  File "C:\Users\Oscar\sympy\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)

  File "C:\Users\Oscar\sympy\sympy\core\expr.py", line 3452, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)

  File "C:\Users\Oscar\sympy\sympy\core\mul.py", line 1984, in _eval_as_leading_term
    return self.func(*[t.as_leading_term(x, logx=logx, cdir=cdir) for t in self.args])

  File "C:\Users\Oscar\sympy\sympy\core\mul.py", line 1984, in <listcomp>
    return self.func(*[t.as_leading_term(x, logx=logx, cdir=cdir) for t in self.args])

  File "C:\Users\Oscar\sympy\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)

  File "C:\Users\Oscar\sympy\sympy\core\expr.py", line 3452, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)

  File "C:\Users\Oscar\sympy\sympy\core\add.py", line 1023, in _eval_as_leading_term
    new_expr = new_expr.trigsimp().cancel()

  File "C:\Users\Oscar\sympy\sympy\core\expr.py", line 3741, in cancel
    return cancel(self, *gens, **args)

  File "C:\Users\Oscar\sympy\sympy\polys\polytools.py", line 6742, in cancel
    return c*(P.as_expr()/Q.as_expr())

  File "C:\Users\Oscar\sympy\sympy\core\decorators.py", line 266, in _func
    return func(self, other)

  File "C:\Users\Oscar\sympy\sympy\core\decorators.py", line 136, in binary_op_wrapper
    return func(self, other)

  File "C:\Users\Oscar\sympy\sympy\core\expr.py", line 268, in __truediv__
    return Mul(self, denom)

  File "C:\Users\Oscar\sympy\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)

  File "C:\Users\Oscar\sympy\sympy\core\operations.py", line 85, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)

  File "C:\Users\Oscar\sympy\sympy\core\mul.py", line 266, in flatten
    if not a.is_zero and a.is_Rational:

  File "C:\Users\Oscar\sympy\sympy\core\assumptions.py", line 466, in getit
    return _ask(fact, self)

  File "C:\Users\Oscar\sympy\sympy\core\assumptions.py", line 521, in _ask
    _ask(pk, obj)

  File "C:\Users\Oscar\sympy\sympy\core\assumptions.py", line 521, in _ask
    _ask(pk, obj)

  File "C:\Users\Oscar\sympy\sympy\core\assumptions.py", line 521, in _ask
    _ask(pk, obj)

  File "C:\Users\Oscar\sympy\sympy\core\assumptions.py", line 521, in _ask
    _ask(pk, obj)

  File "C:\Users\Oscar\sympy\sympy\core\assumptions.py", line 509, in _ask
    a = evaluate(obj)

  File "C:\Users\Oscar\sympy\sympy\core\add.py", line 640, in <lambda>
    _eval_is_algebraic = lambda self: _fuzzy_group(

  File "C:\Users\Oscar\sympy\sympy\core\logic.py", line 83, in _fuzzy_group
    continue

KeyboardInterrupt
```

(but of course hard to tell if this is actually where it is stalling.)

**Comment by 0sidharth** [comment]
I think the issue is that the execution gets stuck in a `while` loop present here - https://github.com/sympy/sympy/blob/fe125868e480747aedc14f65b8fcbeb5e3eb8089/sympy/core/expr.py#L3041

**Comment by anutosh491** [comment]
Not sure where but this seems to have been fixed somewhere on master . On master we have
```
>>> exp(loggamma(1/x) - 1).series(x, logx = -y)
exp(loggamma(1/x) - 1)
```

**Comment by 0sidharth** [comment]
It should be looked into which commit the issue was fixed, so we can conclude whether it's a proper fix or maybe some different code path being taken which is masking this issue.

**Comment by anutosh491** [comment]
> It should be looked into which commit the issue was fixed, so we can conclude whether it's a proper fix or maybe some different code path being taken which is masking this issue.

Hi , I overlooked this message but yeah the fix is proper , it is through one of my Prs #22870 (just an expanded form of that) and I've added a good amount of tests for the same as suggested here https://github.com/sympy/sympy/issues/14384#issuecomment-1013659520 and hence we don't really have to add anything for this as all basic cases have been covered !
