### ISSUE TITLE
Sympy live shell is giving UnicodeEncodeError

### ISSUE THREAD

**Issue by guu1227** [sympy/sympy#22380]
This seems to be occurring every time I try to run anything in sympy live, looks like a case of needing to use `.encode` instead of `str()` for encoding unicode:
`>>> str(Integral(sqrt(1/x), x))
Exception in SymPy Live of type 
<type 'exceptions.UnicodeEncodeError'>
for reference the last 5 stack trace entries are
Traceback (most recent call last):
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/handlers.py", line 271, in post
    live.evaluate(statement, session, printer, stream)
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/app/shell.py", line 280, in evaluate
    exec code in statement_module.__dict__
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/66.426491309333028408/sympy/sympy/printing/pretty/pretty.py", line 2665, in pretty_print
    imaginary_unit=imaginary_unit))
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3f4b27f16594164f/python27/python27_lib/versions/1/google/appengine/runtime/request_environment.py", line 104, in write
    self._request.errors.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2320' in position 0: ordinal not in range(128)
`

**Comment by oscarbenjamin** [comment]
I don't see these errors so I can't reproduce this. In any case this should be opened as an issue for sympy live not here:
https://github.com/sympy/sympy-live/issues
