### ISSUE TITLE
Max and Min of sets

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#22568]
It seems like the support for `Max` and `Min` over sets in very limited.

```
In [51]: Max(Range(5))
Traceback (most recent call last):

  File "C:\Users\Oscar\AppData\Local\Temp/ipykernel_3492/1594959331.py", line 1, in <module>
    Max(Range(5))

  File "C:\Users\Oscar\sympy\sympy\functions\elementary\miscellaneous.py", line 393, in __new__
    args = frozenset(cls._new_args_filter(args))

  File "C:\Users\Oscar\sympy\sympy\functions\elementary\miscellaneous.py", line 566, in _new_args_filter
    raise ValueError("The argument '%s' is not comparable." % arg)

ValueError: The argument 'Range(0, 5, 1)' is not comparable.
```

It may make sense to use `.sup` and `.inf` in case of sets, which will introduce at least basic support for `Range` and maybe some other sets.

**Comment by oscarbenjamin** [comment]
I don't think that Max itself should be used for this since it computes the maximum among its arguments. so it doesn't make sense to pass a set as an argument. There could be a MaxSet or something though.
