### ISSUE TITLE
Printer support for "all" classes

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#22654]
To get some impression of which SymPy classes that are (well) printable, I added the following lines to `_test_args`, which is executed on "all" classes:
```
    print("\nsrepr: ", srepr(obj))
    print("str:   ", str(obj))
    print("latex: ", latex(obj))
    print("pretty:")
    print(pretty(obj))
```

The (rather long) result is here:
[printing.txt](https://github.com/sympy/sympy/files/7698800/printing.txt)

Now, when I redirected to a file, it seems like the ASCII-printer was used, so some additional errors because of that.

I'll try to add specific issues identified in this thread, but it can be worth checking if one is up for improving the printer functionality.

**Comment by oscargus** [comment]
One step would to have the class names printed using `\text` for the LaTeX-printer. For example, now it looks like:
![image](https://user-images.githubusercontent.com/8114497/145714671-4234b013-36b3-4d88-bd3a-4f0824386e18.png)
while 
![image](https://user-images.githubusercontent.com/8114497/145714678-d9811ce1-78b8-4bc2-82f5-15c42961a202.png)

is better (Firefox messes up pasting PNGs...).

**Comment by oscargus** [comment]
This looks like a plain bug:
```
______ sympy\core\tests\test_args.py:test_sympy__codegen__fnodes__Extent _______
Traceback (most recent call last):
  File "c:\users\oscar\sympy\sympy\core\tests\test_args.py", line 435, in test_sympy__codegen__fnodes__Extent
    assert _test_args(Extent(x, y))
  File "c:\users\oscar\sympy\sympy\core\tests\test_args.py", line 104, in _test_args
    print("str:   ", str(obj))
  File "c:\users\oscar\sympy\sympy\core\_print_helpers.py", line 29, in __str__
    return sstr(self, order=None)
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 373, in __call__
    return self.__wrapped__(*args, **kwargs)
  File "c:\users\oscar\sympy\sympy\printing\str.py", line 997, in sstr
    s = p.doprint(expr)
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 293, in doprint
    return self._str(self._print(expr))
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 310, in _print
    return getattr(expr, self.printmethod)(self, **kwargs)
  File "c:\users\oscar\sympy\sympy\codegen\fnodes.py", line 285, in _sympystr
    return '%d:%d' % self.args
TypeError: %d format: a number is required, not Symbol
```
so `Extent(x, y)` does not have a working `str`-method.

**Comment by oscargus** [comment]
Generic statistical domains should probably print without calling `as_boolean`, e.g. 
```
Traceback (most recent call last):
  File "c:\users\oscar\sympy\sympy\core\tests\test_args.py", line 1190, in test_sympy__stats__rv__ConditionalDomain
    assert _test_args(ConditionalDomain(D, x > 1))
  File "c:\users\oscar\sympy\sympy\core\tests\test_args.py", line 104, in _test_args
    print("str:   ", str(obj))
  File "c:\users\oscar\sympy\sympy\core\_print_helpers.py", line 29, in __str__
    return sstr(self, order=None)
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 373, in __call__
    return self.__wrapped__(*args, **kwargs)
  File "c:\users\oscar\sympy\sympy\printing\str.py", line 997, in sstr
    s = p.doprint(expr)
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 293, in doprint
    return self._str(self._print(expr))
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 332, in _print
    return printmethod(expr, **kwargs)
  File "c:\users\oscar\sympy\sympy\printing\str.py", line 142, in _print_RandomDomain
    return 'Domain: ' + self._print(d.as_boolean())
  File "c:\users\oscar\sympy\sympy\stats\rv.py", line 174, in as_boolean
    return And(self.fulldomain.as_boolean(), self.condition)
AttributeError: 'RandomDomain' object has no attribute 'as_boolean'
```

Or implement `as_boolean` (this holds for many `*Domain` classes).

**Comment by oscargus** [comment]
There also seems to be an issue in `as_boolean` for some `*Domain`:

```
Traceback (most recent call last):
  File "c:\users\oscar\sympy\sympy\core\tests\test_args.py", line 1324, in test_sympy__stats__frv__FiniteDomain
    assert _test_args(FiniteDomain({(x, 1), (x, 2)}))  # x can be 1 or 2
  File "c:\users\oscar\sympy\sympy\core\tests\test_args.py", line 104, in _test_args
    print("str:   ", str(obj))
  File "c:\users\oscar\sympy\sympy\core\_print_helpers.py", line 29, in __str__
    return sstr(self, order=None)
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 373, in __call__
    return self.__wrapped__(*args, **kwargs)
  File "c:\users\oscar\sympy\sympy\printing\str.py", line 997, in sstr
    s = p.doprint(expr)
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 293, in doprint
    return self._str(self._print(expr))
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 332, in _print
    return printmethod(expr, **kwargs)
  File "c:\users\oscar\sympy\sympy\printing\str.py", line 142, in _print_RandomDomain
    return 'Domain: ' + self._print(d.as_boolean())
  File "c:\users\oscar\sympy\sympy\stats\frv.py", line 88, in as_boolean
    return Or(*[And(*[Eq(sym, val) for sym, val in item]) for item in self])
  File "c:\users\oscar\sympy\sympy\stats\frv.py", line 88, in <listcomp>
    return Or(*[And(*[Eq(sym, val) for sym, val in item]) for item in self])
  File "c:\users\oscar\sympy\sympy\stats\frv.py", line 88, in <listcomp>
    return Or(*[And(*[Eq(sym, val) for sym, val in item]) for item in self])
TypeError: cannot unpack non-iterable Symbol object
```

**Comment by oscargus** [comment]
A number of classes in `physics.quantum` seems to rely on incorrect printing methods, e.g.,
```
Traceback (most recent call last):
  File "c:\users\oscar\sympy\sympy\core\tests\test_args.py", line 3777, in test_sympy__physics__quantum__qubit__QubitState
    assert _test_args(QubitState(0, 1))
  File "c:\users\oscar\sympy\sympy\core\tests\test_args.py", line 104, in _test_args
    print("str:   ", str(obj))
  File "c:\users\oscar\sympy\sympy\core\_print_helpers.py", line 29, in __str__
    return sstr(self, order=None)
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 373, in __call__
    return self.__wrapped__(*args, **kwargs)
  File "c:\users\oscar\sympy\sympy\printing\str.py", line 997, in sstr
    s = p.doprint(expr)
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 293, in doprint
    return self._str(self._print(expr))
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 310, in _print
    return getattr(expr, self.printmethod)(self, **kwargs)
  File "c:\users\oscar\sympy\sympy\physics\quantum\state.py", line 180, in _sympystr
    return '%s%s%s' % (self.lbracket, contents, self.rbracket)
AttributeError: 'QubitState' object has no attribute 'lbracket'
```

**Comment by oscargus** [comment]
Probably it is better to fallback to the `str`-printer than to generate an exception when a pretty printer is not available, e.g.: 
```
Traceback (most recent call last):
  File "c:\users\oscar\sympy\sympy\core\tests\test_args.py", line 5194, in test_sympy__vector__dyadic__DyadicZero
    assert _test_args(DyadicZero())
  File "c:\users\oscar\sympy\sympy\core\tests\test_args.py", line 107, in _test_args
    print(pretty(obj))
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 373, in __call__
    return self.__wrapped__(*args, **kwargs)
  File "c:\users\oscar\sympy\sympy\printing\pretty\pretty.py", line 2820, in pretty
    return pp.doprint(expr)
  File "c:\users\oscar\sympy\sympy\printing\pretty\pretty.py", line 66, in doprint
    return self._print(expr).render(**self._settings)
  File "c:\users\oscar\sympy\sympy\printing\printer.py", line 332, in _print
    return printmethod(expr, **kwargs)
  File "c:\users\oscar\sympy\sympy\printing\pretty\pretty.py", line 1090, in _print_BasisDependent
    raise NotImplementedError("ASCII pretty printing of BasisDependent is not implemented")
NotImplementedError: ASCII pretty printing of BasisDependent is not implemented
```

**Comment by oscargus** [comment]
`DyadicMul` and `DyadicAdd` should have more clever parenthesis generation:
```
srepr:  DyadicMul(Integer(3), (C.i|C.j))
str:    3*(C.i|C.j)
latex:  (3)(\mathbf{\hat{i}_{C}}{|}\mathbf{\hat{j}_{C}})
pretty:
E
srepr:  DyadicAdd(DyadicMul(Integer(2), (C.i|C.i)), DyadicMul(Integer(2), (C.i|C.j)))
str:    2*(C.i|C.i) + 2*(C.i|C.j)
latex:  (2)(\mathbf{\hat{i}_{C}}{|}\mathbf{\hat{i}_{C}}) + (2)(\mathbf{\hat{i}_{C}}{|}\mathbf{\hat{j}_{C}})
pretty:
E
```

![image](https://user-images.githubusercontent.com/8114497/145715332-fb551797-83bf-4f1a-84be-92f75649b5d5.png)

Maybe the `{|}` should be `\mid`? Also, using `\left(` and `\right)` will make it look better.

**Comment by oscargus** [comment]
Probability, Expectation, Covariance, Variance can be printed using the standard abbreviations:
```
srepr:  Probability(StrictGreaterThan(RandomSymbol(Symbol('X'), SingleContinuousPSpace(Symbol('X'), NormalDistribution(Integer(0), Integer(1)))), Integer(0)))
str:    Probability(X > 0)
latex:  Probability\left(X > 0\right)
pretty:
Probability(X > 0)
.
srepr:  Expectation(StrictGreaterThan(RandomSymbol(Symbol('X'), SingleContinuousPSpace(Symbol('X'), NormalDistribution(Integer(0), Integer(1)))), Integer(0)))
str:    Expectation(X > 0)
latex:  Expectation\left(X > 0\right)
pretty:
Expectation(X > 0)
.
srepr:  Covariance(RandomSymbol(Symbol('X'), SingleContinuousPSpace(Symbol('X'), NormalDistribution(Integer(0), Integer(1)))), RandomSymbol(Symbol('Y'), SingleContinuousPSpace(Symbol('Y'), NormalDistribution(Integer(0), Integer(3)))))
str:    Covariance(X, Y)
latex:  Covariance\left(X, Y\right)
pretty:
Covariance(X, Y)
.
srepr:  Variance(RandomSymbol(Symbol('X'), SingleContinuousPSpace(Symbol('X'), NormalDistribution(Integer(0), Integer(1)))))
str:    Variance(X)
latex:  Variance\left(X\right)
pretty:
Variance(X)
.
```

**Comment by oscargus** [comment]
There should be some formatting for the LaTeX printing here, like `\text`, for the name part of the morphisms:
```
srepr:  IdentityMorphism(Object('A'))
str:    IdentityMorphism(Object("A"))
latex:  id:A\rightarrow A
pretty:
id:A——▶A
.
srepr:  NamedMorphism(Object('A'), Object('B'), Str('f'))
str:    NamedMorphism(Object("A"), Object("B"), "f")
latex:  f:A\rightarrow B
pretty:
f:A——▶B
```

**Comment by oscargus** [comment]
As above, "domain" should be printed as "\text{domain}" in 
```
srepr:  Poly(Integer(2), Symbol('x'), Symbol('y'))
str:    Poly(2, x, y, domain='ZZ')
latex:  \operatorname{Poly}{\left( 2, x, y, domain=\mathbb{Z} \right)}
pretty:
Poly(2, x, y, domain='ZZ')
.
srepr:  PurePoly(Integer(2), Symbol('x'), Symbol('y'))
str:    PurePoly(2, x, y, domain='ZZ')
latex:  \operatorname{PurePoly}{\left( 2, x, y, domain=\mathbb{Z} \right)}
pretty:
PurePoly(2, x, y, domain='ZZ')
```
Now: 
![image](https://user-images.githubusercontent.com/8114497/145794609-a326916e-2b0b-49f0-9d1e-bef6c6b947bd.png)

**Comment by oscargus** [comment]
LieDerivative can probably use better formatting for LaTeX, see https://en.wikipedia.org/wiki/Lie_derivative

```
srepr:  LieDerivative(BaseVectorField(CoordSystem(Str('name'), Patch(Str('name'), Manifold(Str('name'), Integer(3))), Tuple(Symbol('a'), Symbol('b'), Symbol('c')), Dict()), Integer(0)), Differential(BaseScalarField(CoordSystem(Str('name'), Patch(Str('name'), Manifold(Str('name'), Integer(3))), Tuple(Symbol('a'), Symbol('b'), Symbol('c')), Dict()), Integer(0))))
str:    LieDerivative(e_a, da)
latex:  LieDerivative\left(\partial_{a}, \operatorname{d}a\right)
pretty:
LieDerivative(e_a, da)
```
