### ISSUE TITLE
Seems like the optional dependencies test is failing

### ISSUE THREAD

**Issue by ThePauliPrinciple** [sympy/sympy#22662]
For a bunch of recent PRs, it seems an optional dependency is currently failing.

This is the error:
```
 ________________________________________________________________________________
_____________ sympy/polys/tests/test_ring_series.py:test_nth_root ______________
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/polys/tests/test_ring_series.py", line 232, in test_nth_root
    print(rs_nth_root(8*x, 3, x, 3))
  File "/home/runner/work/sympy/sympy/sympy/polys/ring_series.py", line 989, in rs_nth_root
    const = R(c**Rational(1, n))  # exponentiation with mpq object
TypeError: unsupported operand type(s) for ** or pow()
```

**Comment by ThePauliPrinciple** [comment]
https://github.com/sympy/sympy/blob/81cd2630631e315586f796646a7f9268e71bf484/sympy/polys/ring_series.py#L973-L992

Perhaps something changed upstream that changed the error from `ValueError` to `TypeError`?

**Comment by ThePauliPrinciple** [comment]
I tried using `TypeError`, but that doesn't fix it.

**Comment by oscarbenjamin** [comment]
I explained the problem and fix in https://github.com/sympy/sympy/pull/22657#issuecomment-992342721 and https://github.com/aleaxit/gmpy/issues/319

**Comment by casevh** [comment]
I released gmpy2 2.1.1 to fix the bug. Sorry about letting that one slip through.

**Comment by ThePauliPrinciple** [comment]
Thanks for fixing this!

**Comment by oscarbenjamin** [comment]
I'm reopening this to say that SymPy should test with prerelease versions of gmpy2 in CI. The release cycle for gmpy2 is sufficiently slow that anything like this would get picked up in SymPy's CI before the next release of gmpy2.
