### ISSUE TITLE
solve(particular=True) with integer variables fails with IndexError

### ISSUE THREAD

**Issue by user202729** [sympy/sympy#22718]
Example code:

```
import sympy
from sympy import Matrix, symbols, solve

A=Matrix([[1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0], [1, 1, 0, 1, 1, 0, 1, 0, 1, 0, -1, -1, 0, 0], [-1, -1, 0, 0, -1, 0, 0, 0, 0, 0, 1, 1, 0, 1], [1, 0, 1, 1, 0, 1, 1, 0, 0, 1, -1, 0, -1, 0], [-1, 0, -1, 0, 0, -1, 0, 0, 0, 0, 1, 0, 1, 1], [-1, 0, 0, -1, 0, 0, -1, 0, 0, 0, -1, 0, 0, -1], [0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, -1, -1, 0], [0, -1, -1, 0, 0, 0, 0, -1, 0, 0, 0, 1, 1, 1], [0, -1, 0, -1, 0, 0, 0, 0, -1, 0, 0, -1, 0, -1], [0, 0, -1, -1, 0, 0, 0, 0, 0, -1, 0, 0, -1, -1], [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0], [0, 0, 0, 0, -1, -1, 0, -1, 0, 0, 0, 0, 0, 0]])
v=Matrix(symbols("v:14", integer=True))
B=Matrix([[2], [-2], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]])


solve(A@v-B, particular=True)
```

Error message:

```
Traceback (most recent call last):
  File "FILE", line 11, in <module>
    solve(A@v-B, particular=True)
  File "PATH/python3.9/site-packages/sympy/solvers/solvers.py", line 1097, in solve
    solution = _solve_system(f, symbols, **flags)
  File "PATH/python3.9/site-packages/sympy/solvers/solvers.py", line 1812, in _solve_system
    result = minsolve_linear_system(matrix, *symbols, **flags)
  File "PATH/python3.9/site-packages/sympy/solvers/solvers.py", line 2232, in minsolve_linear_system
    bestsol = minsolve_linear_system(system, *symbols, quick=True)
  File "PATH/python3.9/site-packages/sympy/solvers/solvers.py", line 2214, in minsolve_linear_system
    val = solve(k)[0]
IndexError: list index out of range
```

Sympy version: 1.9 (installed from pypi)

If it's the case that solve(particular=True) with integer variables are not supported, in that case solve() should raise an error/raise NotImplementedError accordingly.

**Comment by smichr** [comment]
```python
>>> eqs=list(A@v-B)
>>> Tuple(*eqs).subs(solve(eqs[:-1]))[-1]
3*v9 - 4
```
There is no solution (in integers) and it was assumed that there would be.

**Comment by user202729** [comment]
... no, I don't think that's it, it's rather because the algorithm doesn't handle the integer variables case.

Consider (*note*. with the patch applied to 1.9 version from pypi, not latest GitHub version, may have discrepancies)

```
import sympy
from sympy import solve, symbols

a, b=symbols("a b", integer=True)

print( solve(2*a+3*b-13, particular=True) )
print( solve([2*a+3*b-13], particular=True) )

```

Output: (`#...` are comments added)

```
[{a: 13/2 - 3*b/2}]  # ? I asked for a particular solution
[]  # no solution returned
```

Clearly there's a solution (a=2, b=3 for example) in this case.

**Comment by smichr** [comment]
> a, b=symbols("a b", integer=True)
> 
> print( solve(2*a+3*b-13, particular=True) )
> print( solve([2*a+3*b-13], particular=True) )

Since `minsolve_linear_system` tries to maximize the number of 0s, you should not use this for such a system. Use `diophantine` to find solutions to such systems.
```python
>>> diophantine(2*a+3*b-13)
{(3*t_0 - 13, 13 - 2*t_0)}
```
