### ISSUE TITLE
Possible problem with simplifying sinh and cosh functions

### ISSUE THREAD

**Issue by GeoffCope** [sympy/sympy#22899]
It's not clear to me if the issue seems to be with the package EinsteinPy or with SymPy itself.

I am unable to evaluate the Ricci and Einstein tensors for a specific metric. The same error occurs in the following notebooks:

https://github.com/GeoffCope/General_Relativity_Python/blob/main/EhlersKundtRosenMetric.ipynb

https://github.com/GeoffCope/General_Relativity_Python/blob/main/Distinct_family_of%20colliding_gravitational_waves_in_general_relativity_by_Halilsoy.ipynb

A simpler case of the above metric does work as long as it doesn't involve the hyperbolic sin and cos:

https://github.com/GeoffCope/General_Relativity_Python/blob/main/Bell_Szekeres_Solution_and_Related_Solutions_of_the_Einstein_Maxwell_Equations_Barrabes_Hogan.ipynb

**Comment by asmeurer** [comment]
It's hard to tell exactly what the problem is without seeing the underlying expression that is being passed to trigsimp. The exception comes from collect, which raises it for things like this

```
>>> collect(f(x, y).diff(x, y), x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/simplify/radsimp.py", line 391, in collect
    terms = [parse_term(i) for i in args]
  File "./sympy/simplify/radsimp.py", line 391, in <listcomp>
    terms = [parse_term(i) for i in args]
  File "./sympy/simplify/radsimp.py", line 281, in parse_term
    sexpr, deriv = parse_derivative(expr)
  File "./sympy/simplify/radsimp.py", line 217, in parse_derivative
    raise NotImplementedError(
NotImplementedError: Improve MV Derivative support in collect
```

**Comment by GeoffCope** [comment]
Is it possible to trace thru the intermediate calculations to see which expression is being passed?  If not, let me know, and I'll see if I can give an equivalent expression in terms of derivatives and products of components of the Christoffel symbols which do calculate and simplify
