### ISSUE TITLE
python .\bin\mailmap_check.py fails

### ISSUE THREAD

**Issue by hanspi42** [sympy/sympy#22915]
In the present version,

```python .\bin\mailmap_check.py```

fails with 

```
Traceback (most recent call last):
  File ".\bin\mailmap_check.py", line 300, in <module>
    sys.exit(main(*sys.argv[1:]))
  File ".\bin\mailmap_check.py", line 56, in main
    lines_mailmap = read_lines(mailmap_path())
  File ".\bin\mailmap_check.py", line 289, in read_lines
    return [line.strip() for line in fin.readlines()]
  File "C:\Users\hansp\anaconda3\envs\devel\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 7774: character maps to <undefined>
```

It is caused by the character `č` in the name `Tokarčík` on line 167 of `.mailmap`

**Comment by oscarbenjamin** [comment]
I don't see this error myself on Linux.

Which OS are you on? If you change the shebang in the script to python3 does that fix it?
```diff
diff --git a/bin/mailmap_check.py b/bin/mailmap_check.py
index cb76501..e91add3 100755
--- a/bin/mailmap_check.py
+++ b/bin/mailmap_check.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 # -*- coding: utf-8 -*-
 """
 A tool to generate AUTHORS. We started tracking authors before moving to git,
```

**Comment by hanspi42** [comment]
It is Windows 10, ``python3`` does not help, but it works when I run a virtual Ubuntu machine that uses the Windows 10 file system.  The problem seems to be that the present ``.mailmap`` is not utf-8 anymore, and Ubuntu seems to be able to deal with this on the OS side.

**Comment by oscarbenjamin** [comment]
On my computer the file is in utf8:
```
>>> t = open('.mailmap', 'rb').read().decode('utf-8')
```
That would raise an error if it wasn't e.g.:
```
>>> open('test', 'wb').write(b'\x84')
1
>>> open('test', 'rb').read().decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 0: invalid start byte
```
Has the file been modified in your computer by an editor or by the script?

**Comment by hanspi42** [comment]
Not modified, no.  But look at this:

```
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> t = open('.mailmap', 'rb').read().decode('utf-8')
>>> with open('.mailmap') as fin:
...     a = [line.strip() for line in fin.readlines()]
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\hansp\anaconda3\envs\devel\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 7774: character maps to <undefined>
>>>
```

Your method works, the code in `mailmap_check.py` does not.

**Comment by hanspi42** [comment]
Update: adding `'rb'` solves it:

```
>>> with open('.mailmap', 'rb') as fin:
...     a = [line.strip() for line in fin.readlines()]
...
>>>
```

**Comment by oscarbenjamin** [comment]
It looks like your Python installation is using the cp1252 codec rather than utf8:
https://en.wikipedia.org/wiki/Windows-1252

**Comment by oscarbenjamin** [comment]
Add these lines at the top of the `mailmap_check.py` script and check what they output when you run the script:
```
import sys
print(sys.executable)
print(sys.version)
```

**Comment by oscarbenjamin** [comment]
Also this:
```
import locale
print(locale.getpreferredencoding())
```

**Comment by oscarbenjamin** [comment]
The fix is probably this to make sure that utf-8 is used regardless of locale settings:
```diff
diff --git a/bin/mailmap_check.py b/bin/mailmap_check.py
index cb76501..d2fb0e5 100755
--- a/bin/mailmap_check.py
+++ b/bin/mailmap_check.py
@@ -285,12 +285,12 @@ def sort_lines_mailmap(lines):
 
 
 def read_lines(path):
-    with open(path) as fin:
+    with open(path, 'r', encoding='utf-8') as fin:
         return [line.strip() for line in fin.readlines()]
 
 
 def write_lines(path, lines):
-    with open(path, 'w') as fout:
+    with open(path, 'w', encoding='utf-8') as fout:
         fout.write('\n'.join(lines))
         fout.write('\n')
```

**Comment by hanspi42** [comment]
Yes, it used cp1252, here it is:

```
C:\Users\hansp\anaconda3\envs\devel\python.exe
3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
cp1252
```

Your solution works, I tested it.

**Comment by hanspi42** [comment]
> It's a long time since I used Windows so I guess I forgot that it still doesn't read and write utf-8 by default. Various other things have changed to use utf-8 such as filenames and text on std iostreams but not the default encoding for the _contents_ of files.

It is frankly a terrible mess on Windows. Then again, even Linux can be set up to have a different default. I had these issues in the past on RHEL, so I think it is just good practice to define the encoding in the script.
