### ISSUE TITLE
No algorithms are implemented to solve equation besseli(1, x)

### ISSUE THREAD

**Issue by 0187773933** [sympy/sympy#22951]
- Trying to solve for zeroes of Airy disk - intensity function : https://en.wikipedia.org/wiki/Airy_disk#Mathematical_formulation
- It should be a 1st order Bessel function
- sympy is using `besseli` instead of `besselj` ?

```
q = sympy.Symbol( "q" )
x = sympy.Symbol( "x" )
sympy.solve( sympy.Sum( ( ( ( -1**q ) / ( sympy.factorial( q ) * sympy.gamma( q + 1 + 1 ) ) ) * ( ( x / 2 )**( ( 2*q ) + 1 ) ) ) , ( q , 0 , sympy.oo ) ).doit() , x )
```
Returns :

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/sympy/solvers/solvers.py", line 1095, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/usr/local/lib/python3.9/site-packages/sympy/solvers/solvers.py", line 1383, in _solve
    soln = _solve(m, symbol, **flags)
  File "/usr/local/lib/python3.9/site-packages/sympy/solvers/solvers.py", line 1714, in _solve
    raise NotImplementedError('\n'.join([msg, not_impl_msg % f]))
NotImplementedError:
No algorithms are implemented to solve equation besseli(1, x)
```

**Comment by oscarbenjamin** [comment]
The sum works out in terms of `besseli`:
```python
In [63]: s
Out[63]: 
  ∞               
_____             
╲                 
 ╲        2⋅q + 1 
  ╲    ⎛x⎞        
   ╲  -⎜─⎟        
   ╱   ⎝2⎠        
  ╱   ────────────
 ╱    q!⋅Γ(q + 2) 
╱                 
‾‾‾‾‾             
q = 0             

In [64]: s.doit()
Out[64]: -besseli(1, x)
```
Numerical evaluation suggests this is correct e.g.:
```python
In [66]: s.subs(x, 1 + I).n()
Out[66]: -0.365028028827088 - 0.614160334922904⋅ⅈ

In [67]: s.doit().subs(x, 1 + I).n()
Out[67]: -0.365028028827088 - 0.614160334922904⋅ⅈ
```
The solve function can't solve this though:
```
In [69]: solve(besseli(1, x))
---------------------------------------------------------------------------
NotImplementedError 
```
That's because there isn't a standard function to represent the inverse of a Bessel function. This particular case seems to be straight-forward though since `besseli(1, x) == 0` just implies that `x = 0`. The returned solution should just be `[0]`.

It's also easy to see from the definition of the summation itself that the only way it will be zero is if `x` is zero.

**Comment by oscarbenjamin** [comment]
Maybe solve should have a special case for handling certain Bessel functions. In the case of `besseli(n, f(x)) == 0` it seems that at least if `n > 0` then this implies that `f(x) == 0` so solve could make use of that.

**Comment by jksuom** [comment]
It seems that `besseli(n, z)` has an infinite number complex zeros, all different for different values of n: https://dlmf.nist.gov/10.42
