### ISSUE TITLE
limitations with overloaded round function - throws TypeError with Symbols

### ISSUE THREAD

**Issue by tkmiller3** [sympy/sympy#23052]
It appears that rather than a native SymPy round() function, SymPy overloads the native Python round() function so that it accepts and returns Sympy number types.  In the 1.9 documentation I find this:

> Notes
> 
> The Python round function uses the SymPy round method so it will always return a SymPy number (not a Python float or int):
> 
> Run code block in SymPy Live
> isinstance(round(S(123), -2), Number)
> True

This seems to work as advertised, but with significant limitations.  Round will not accept Symbols, unlike floor() and ceiling():
```
>>> x = Symbol('x')
>>> round(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tkm/Library/Python/3.8/lib/python/site-packages/sympy/core/expr.py", line 3763, in round
    raise TypeError("can't round symbolic expression")
TypeError: can't round symbolic expression
>>> floor(x)
floor(x)
>>> 
```

As a result of the above, round can't be used in processing expressions when given symbolic arguments:
```
>>> simplify(floor(x+x) - floor(2*x))
0
>>> simplify(round(x+x) - round(2*x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tkm/Library/Python/3.8/lib/python/site-packages/sympy/core/expr.py", line 3763, in round
    raise TypeError("can't round symbolic expression")
TypeError: can't round symbolic expression
```

It would seem easy enough to derive a SymPy-native round function from the RoundFunction base class, similar to floor and ceiling.  I wrote one that will probably work for my purposes, but I'm not well-versed in the SymPy internals enough to write a complete function.

**Comment by harshkasat** [comment]
@oscarbenjamin 

https://github.com/sympy/sympy/blob/c81c8169142f14a1b427664e073cde196f111d53/sympy/core/expr.py#L3795-L3833
* I can overcome this case by using x.has(Symbol) but I don't know how we find a way to float. 
* If this case passes, it will move on to the next case which will search for a float.

https://github.com/sympy/sympy/blob/c81c8169142f14a1b427664e073cde196f111d53/sympy/core/expr.py#L331-L340

* This checks if the expression is a float. Is there a way to convert symbols to floats? We can use floor and ceiling, but I'm not sure about floats. This is a new field for me in the Sympy repository, could you please guide me?

**Comment by oscarbenjamin** [comment]
A `round` expression class to represent rounding as a symbolic operation would need to be added:
https://docs.sympy.org/latest/guides/custom-functions.html

There are a lot of complications with rounding though that don't come up with `floor` and `ceiling`. There is the question of supporting two argument round like `round(1.1111, 2)` which rounds to a given number of decimal places and then all of the different kinds of tie-breaking rules. 

To keep it simple we could add a function that simply does round-half-even like Python's round function. I think that this is worth having just because it is a common computational operation. Somewhere though there is an issue about adding a `trunc` function for round ties towards zero (because that is a common operation in other languages).

Different cases can be represented in terms of existing SymPy functions:
```python
In [52]: def round_inf(x):
    ...:     """Round with ties towards infinity"""
    ...:     return x + S.Half - frac(x + S.Half)
    ...: 

In [53]: def round_nzero(x):
    ...:     """Round with ties away from zero"""
    ...:     return sign(x)*round_inf(abs(x))
    ...: 
```
Python's `round` function for floats uses round half even which is trickier to represent:
```python
In [56]: def round_half_even(x):
    ...:     """Round with ties towards infinity"""
    ...:     n = (2*x - 1) / 4
    ...:     return x - S.Half - frac(x + S.Half) - (floor(n) + floor(-n))
    ...: 

In [69]: round_half_even(x)
Out[69]: 
    ⎢1   x⎥   ⎢x   1⎥                   1
x - ⎢─ - ─⎥ - ⎢─ - ─⎥ - frac(x + 1/2) - ─
    ⎣4   2⎦   ⎣2   4⎦                   2
```
Maybe there is a better expression for this.

An awkward complication is that SymPy has already allowed round to be defined for complex numbers (a mistake in my opinion):
```python
In [72]: round(5.5+I*10.5)
Out[72]: 6 + 10⋅ⅈ
```

**Comment by westurner** [comment]
- https://math.stackexchange.com/a/17417/139078

```python
from sympy import Piecewise, ceiling, floor, symbols

def round_sympy(expr):
  """
  A sympy-compatible rounding function that approximates Python's round().
  but does not have an ndigits= parameter

  Args:
    expr: A sympy expression.

  Returns:
    A sympy expression representing the rounded value.
  """
  return Piecewise(
      (ceiling(expr - 0.5), expr <= 0),
      (floor(expr + 0.5), expr >= 0)
  )

x = symbols('x')
display(round_sympy(x))


import numpy as np
for n in np.linspace(-100, 100, 10000+2):
  x,y = round_sympy(n), round(n)
  assert x == y, (n, x, y)
```
