### ISSUE TITLE
Local failing tests after #22900(?)

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#23105]
It seems like the new deprecation system causes lots of error locally for me (Windows 10).

```
Traceback (most recent call last):
  File "c:\users\oscar\sympy\sympy\assumptions\tests\test_query.py", line 2090, in test_key_extensibility
    register_handler('my_key', MyAskHandler)
  File "C:\Users\Oscar\miniconda3\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "c:\users\oscar\sympy\sympy\testing\pytest.py", line 366, in warns_deprecated_sympy
    yield
  File "C:\Users\Oscar\miniconda3\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "c:\users\oscar\sympy\sympy\testing\pytest.py", line 286, in warns
    text = f.read()
  File "C:\Users\Oscar\miniconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 29435: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\oscar\sympy\sympy\assumptions\tests\test_query.py", line 2099, in test_key_extensibility
    remove_handler('my_key', MyAskHandler)
  File "C:\Users\Oscar\miniconda3\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "c:\users\oscar\sympy\sympy\testing\pytest.py", line 366, in warns_deprecated_sympy
    yield
  File "C:\Users\Oscar\miniconda3\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "c:\users\oscar\sympy\sympy\testing\pytest.py", line 286, in warns
    text = f.read()
  File "C:\Users\Oscar\miniconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 29435: character maps to <undefined>
```

**Comment by oscarbenjamin** [comment]
Does it depend what libraries you have installed? What happens if you try in a clean virtual environment with only mpmath installed?

Can you test with the 1.10 release candidate (`pip install --pre sympy`)?

**Comment by oscargus** [comment]
It could be that. I have some other tests failing seemingly because of that, but these seems like new ones.

As I run with conda/mamba, I prefer not to mess up the installation if I can avoid it. (At least not tonight...)
