### ISSUE TITLE
lambdifying an Integral fails if numpy is installed

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#23133]
These two tests pass if numpy is not installed and also pass if both numpy and scipy is installed but fail if numpy is installed and scipy is not:
https://github.com/sympy/sympy/blob/dfef951e777dba36ad75162c8dc9402b228d11ed/sympy/utilities/tests/test_lambdify.py#L336-L348
```console
$ pip install numpy
$ pip uninstall scipy
$ bin/test sympy/utilities/tests/test_lambdify.py 
======================================== test process starts ========================================
executable:         /home/oscar/current/sympy/sympy.git/38venv/bin/python  (3.8.9-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 2.1.2
numpy:              1.21.3
random seed:        7833176
hash randomization: on (PYTHONHASHSEED=1558188631)

sympy/utilities/tests/test_lambdify.py[116] ..................s.../home/oscar/current/sympy/sympy.git/38venv/lib/python3.8/site-packages/numexpr/expressions.py:189: RuntimeWarning: invalid value encountered in log
  return ConstantNode(func(*[x.value for x in args]))
.....EE.............s........ssssss
ssss..........................ss.....s.ss..s...ss.ss.ssss..                                    [FAIL]

_____________________________________________________________________________________________________
_______________________ sympy/utilities/tests/test_lambdify.py:test_integral ________________________
Traceback (most recent call last):
  File "/home/oscar/current/sympy/sympy.git/sympy/utilities/lambdify.py", line 884, in lambdify
    exec(ln, {}, namespace)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oscar/current/sympy/sympy.git/sympy/utilities/tests/test_lambdify.py", line 338, in test_integral
    l = lambdify(y, Integral(f(x), (x, y, oo)))
  File "/home/oscar/current/sympy/sympy.git/sympy/utilities/lambdify.py", line 890, in lambdify
    exec(ln, {}, namespace)
  File "<string>", line 1, in <module>
NameError: name 'scipy' is not defined
_____________________________________________________________________________________________________
____________________ sympy/utilities/tests/test_lambdify.py:test_double_integral ____________________
Traceback (most recent call last):
  File "/home/oscar/current/sympy/sympy.git/sympy/utilities/lambdify.py", line 884, in lambdify
    exec(ln, {}, namespace)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oscar/current/sympy/sympy.git/sympy/utilities/tests/test_lambdify.py", line 346, in test_double_integral
    l = lambdify([z], i)
  File "/home/oscar/current/sympy/sympy.git/sympy/utilities/lambdify.py", line 890, in lambdify
    exec(ln, {}, namespace)
  File "<string>", line 1, in <module>
NameError: name 'scipy' is not defined

=============== tests finished: 88 passed, 26 skipped, 2 exceptions, in 2.57 seconds ================
DO *NOT* COMMIT!
```
I think that when numpy is not installed mpmath is used. When numpy is installed it seems that it tries to use scipy but that will obviously fail if scipy is not also installed.

**Comment by ThePauliPrinciple** [comment]
Is this some kind of caching error?
When I run it with `-k` I obtain a different error:
```
bin/test sympy/utilities/tests/test_lambdify.py -k test_integral
======================================================= test process starts ========================================================
executable:         /home/thepauli/anaconda3/envs/sympy-dev/bin/python  (3.9.7-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python
numpy:              1.21.2
random seed:        47952199
hash randomization: on (PYTHONHASHSEED=2358816655)

sympy/utilities/tests/test_lambdify.py[1] ['numpy']
[{}, 'numpy']
<class 'sympy.printing.numpy.NumPyPrinter'>
E                                                                                   [FAIL]

____________________________________________________________________________________________________________________________________
_______________________________________ sympy/utilities/tests/test_lambdify.py:test_integral _______________________________________
Traceback (most recent call last):
  File "/mnt/c/Users/paul/Documents/PythonScripts/Libs/SymPy/sympy/sympy/utilities/tests/test_lambdify.py", line 339, in test_integral
    d = l(-oo)
  File "<lambdifygenerated-1>", line 4, in _lambdifygenerated
    Integral(exp(-x**2), (x, y, oo)))
NameError: name 'Integral' is not defined

===================================== tests finished: 0 passed, 1 exceptions, in 0.80 seconds ======================================
```
(note that I put print statements for `modules`, `namespace` and `type(printer)`)

**Comment by ThePauliPrinciple** [comment]
`_import` caches itself: it provides the `reload` parameter, but I don't think it is used.
