### ISSUE TITLE
BUG: sympy 1.10rc2 breaks unyt

### ISSUE THREAD

**Issue by neutrinoceros** [sympy/sympy#23148]
Minimal Reproducer:
```
python3.8 -m venv .env
source .env/bin/activate/
pip install -U pip
pip install --pre sympy
pip install unyt

python -c "import unyt"
```
output
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/.env/lib/python3.8/site-packages/unyt/__init__.py", line 75, in <module>
    from unyt import unit_symbols
  File "/private/tmp/.env/lib/python3.8/site-packages/unyt/unit_symbols.py", line 33, in <module>
    _namespace[_alt_name] = _Unit(_canonical_name, registry=_registry)
  File "/private/tmp/.env/lib/python3.8/site-packages/unyt/unit_object.py", line 227, in __new__
    raise UnitParseError(
unyt.exceptions.UnitParseError: Unit representation must be a string or sympy Expr. 'Min' has type '<class 'sympy.core.function.FunctionClass'>'.
```

**Comment by oscarbenjamin** [comment]
The change is basically this:
```python
>>> parse_expr('min')
Min
```
In SymPy 1.9 that returned `Symbol('min')` rather than the class `Min`.

What exactly is `unyt` doing with this?

**Comment by oscarbenjamin** [comment]
Oh, actually the change is this:
```python
In [4]: type(parse_expr("min", global_dict={'Symbol':Symbol}))
Out[4]: sympy.core.function.FunctionClass
```
This is a bug because if the user passes in an explicit global dict then we shouldn't insert new entries:
https://github.com/sympy/sympy/blob/edce10a6f6888a35c39d799c6198d3f0b4f72d55/sympy/parsing/sympy_parser.py#L1078-L1083
That should only happen if the dict was not provided:
https://github.com/sympy/sympy/blob/edce10a6f6888a35c39d799c6198d3f0b4f72d55/sympy/parsing/sympy_parser.py#L1050-L1052

**Comment by oscarbenjamin** [comment]
This seems to fix it:
```diff
diff --git a/sympy/parsing/sympy_parser.py b/sympy/parsing/sympy_parser.py
index 685a1b4..aca2f3e 100644
--- a/sympy/parsing/sympy_parser.py
+++ b/sympy/parsing/sympy_parser.py
@@ -1054,6 +1054,14 @@ def parse_expr(s, local_dict=None, transformations=standard_transformations,
     if global_dict is None:
         global_dict = {}
         exec('from sympy import *', global_dict)
+
+        builtins_dict = vars(builtins)
+        for name, obj in builtins_dict.items():
+            if isinstance(obj, types.BuiltinFunctionType):
+                global_dict[name] = obj
+        global_dict['max'] = Max
+        global_dict['min'] = Min
+
     elif not isinstance(global_dict, dict):
         raise TypeError('expecting global_dict to be a dict')
 
@@ -1079,13 +1087,6 @@ def parse_expr(s, local_dict=None, transformations=standard_transformations,
                     a transformation should be function that
                     takes 3 arguments'''))
 
-    builtins_dict = vars(builtins)
-    for name, obj in builtins_dict.items():
-        if isinstance(obj, types.BuiltinFunctionType):
-            global_dict[name] = obj
-    global_dict['max'] = Max
-    global_dict['min'] = Min
-
     code = stringify_expr(s, local_dict, global_dict, transformations)
 
     if not evaluate:
```
@neutrinoceros can you confirm if that works?

**Comment by neutrinoceros** [comment]
@oscarbenjamin I tested locally, this indeed fixes the problem AFAICT. Thank you !
