### ISSUE TITLE
KanesMethod cannot distinguish if a Body is Particle or RigidBody

### ISSUE THREAD

**Issue by HosikChae** [sympy/sympy#23269]
I am using `sympy==1.10` with `python==3.9`.

I am deriving the equation of motion of my system using KanesMethod and Body objects, and some of them represent `Particle`s and the others `RigidBody`:

```
particle = Body('p', mass=..., frame=..., masscenter=...)
body = Body('b', mass=..., frame=..., masscenter=..., central_inertia=...)

KM = KanesMethod(...)
KM.kanes_equations([particle, body], [...])
```

But the problem is, [`KanesMethod._form_frstar()`](https://github.com/sympy/sympy/blob/37c7a4e7599ae60db3e12012097c175777db2254/sympy/physics/mechanics/kane.py#L338) tries to refer to `body.central_inertia` even though the `body` is a `Particle`. 

It is because the function uses [`isinstance(body, RigidBody)`](https://github.com/sympy/sympy/blob/37c7a4e7599ae60db3e12012097c175777db2254/sympy/physics/mechanics/kane.py#L382) to determine if a `body` is an instance of `RigidBody` or `Particle`. Since [`Body`](https://github.com/sympy/sympy/blob/37c7a4e7599ae60db3e12012097c175777db2254/sympy/physics/mechanics/body.py#L10) class itself inherits both `RigidBody` and `Particle`, both `isinstance(body, RigidBody)` and `isinstance(body, Particle)` are always `true` no matter if it means to represent a `Particle` or `RigidBody`.
(It seems that the same code is being used in [`get_partial_velocity()`](https://github.com/sympy/sympy/blob/37c7a4e7599ae60db3e12012097c175777db2254/sympy/physics/mechanics/kane.py#L362), too.)

Could you review the issue? If I am using the class in a wrong way, please let me know!

**Comment by moorepants** [comment]
KanesMethod currently only works with Particle and RigidBody. I don't think it works with the Body object.

**Comment by HosikChae** [comment]
Thanks for the reply! 
As `Body` inherits both `Particle` and `RigidBody`, with updates introducing `Body.is_rigidbody` and `Body.masscenter` instead of `Particle.point` into `KanesMethod`, it looks there are no further issues that `KanesMethod` supports `Body` class too!

**Comment by moorepants** [comment]
If you'd like to make a pull request to fix it, that is welcome.

**Comment by HosikChae** [comment]
I am actually working on it, but there is another issue.
When I try to import `Body` from [`kane.py:L6~7`](https://github.com/sympy/sympy/blob/37c7a4e7599ae60db3e12012097c175777db2254/sympy/physics/mechanics/kane.py#L6-L7),
```python
...
from sympy.physics.mechanics.particle import Particle
from sympy.physics.mechanics.rigidbody import RigidBody
from sympy.physics.mechanics.body import Body
...
```
I face an `ImportError` due to circular import:
```shell
Traceback (most recent call last):
  File "***/test.py", line 2, in <module>
    from sympy.physics.mechanics import *
  File "***/sympy/sympy/physics/mechanics/__init__.py", line 43, in <module>
    from .kane import KanesMethod
  File "***/sympy/sympy/physics/mechanics/kane.py", line 8, in <module>
    from sympy.physics.mechanics.body import Body # circular import
  File "***/sympy/sympy/physics/mechanics/body.py", line 3, in <module>
    from sympy.physics.mechanics import RigidBody, Particle, inertia

ImportError: cannot import name 'RigidBody' from partially initialized module 'sympy.physics.mechanics' (most likely due to a circular import) (***/sympy/sympy/physics/mechanics/__init__.py)
```

With a workaround that importing Body inside the function, I was able to confirm that `KanesMethod` now works with `Body`. 

Do you have any idea to resolve the `ImportError`?

**Comment by moorepants** [comment]
> Do you have any idea to resolve the ImportError?

Importing inside the function is the typical solution.

**Comment by moorepants** [comment]
You should import from exactly where the functions/classes are.

from sympy.physics.mechanics.body import Body

**Comment by TJStienstra** [comment]
Do by the way also node that bodies can have loads stored internally, so you will also have to take those into account.

**Comment by TJStienstra** [comment]
We indeed should add an example of how the combination works and is done. Probably easiest is to make a property `loads` as with the `JointsMethod` which returns a list where the `Body.loads` are added to the `forceslist`.

**Comment by TJStienstra** [comment]
@moorepants the problem that `Body.loads` are currently not used by `_Method` has not been solved.
