### ISSUE TITLE
String formatting of `sympy.core.numbers.Zero`

### ISSUE THREAD

**Issue by nopria** [sympy/sympy#23290]
Given

```
>>> import sympy as sy
>>> x = sy.Symbol('x')
>>> y=x
```

you can avoid this

```
>>> '{:1.2f}'.format(y.subs(x,3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported format string passed to Integer.__format__
```

using `evalf()` or `float()`:

```
>>> '{:1.2f}'.format(y.subs(x,3).evalf())
'3.00'
>>> '{:1.2f}'.format(float(y.subs(x,3)))
'3.00'
```

But if the numeric result is zero, I discovered the hard way that only `float()` works:

```
>>> '{:1.2f}'.format(y.subs(x,0).evalf())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported format string passed to Zero.__format__
>>> '{:1.2f}'.format(float(y.subs(x,0)))
'0.00'
```

Is that behavior intentional?

**Comment by oscarbenjamin** [comment]
It looks like in SymPy the only class that actually defines `__format__` is Float.

**Comment by strikeraryu** [comment]
should I add this to other classes? and if yes then which?

**Comment by Sidd-the-kid163** [comment]
Works for me, had been struggling with it for quite a while, thanks a lot!
