### ISSUE TITLE
Sympy is unable to integrate this

### ISSUE THREAD

**Issue by Scoodood** [sympy/sympy#23299]
Sympy is unable to integrate this equation

```
import sympy as sp
sp.init_printing(use_latex=True)

a, x = sp.symbols('a x')
sp.integrate(a * x**(a-1) * sp.ln(x), (x,0,1))

  1                 
  ⌠                 
  ⎮  a - 1          
a⋅⎮ x     ⋅log(x) dx
  ⌡                 
  0                 
```

The output from [Wolframe](https://www.wolframalpha.com/input?i=integrate+a+*+Power%5Bx%2C+a-1%5D*+ln%28x%29+dx+from+0+to+1) is
<img src="https://render.githubusercontent.com/render/math?math=-1/a">

Any hint to fix this issue in Sympy?

**Comment by oscarbenjamin** [comment]
Wolfram alpha makes the assumption that `Re(a) > 0`. You can also assume that `a` is positive with sympy:
```python
In [1]: a, x = symbols('a, x', positive=True)

In [2]: integrate(a* x**(a-1) * ln(x), (x, 0, 1))
Out[2]: 
-1 
───
 a 
```

**Comment by asmeurer** [comment]
SymPy is able to compute the indefinite integral

```py
>>> pprint(integrate(a* x**(a-1) * ln(x), x))
  ⎛⎧ a           a           ⎞
  ⎜⎪x ⋅log(x)   x            ⎟
  ⎜⎪───────── - ──  for a ≠ 0⎟
  ⎜⎪    a        2           ⎟
  ⎜⎪            a            ⎟
a⋅⎜⎨                         ⎟
  ⎜⎪      2                  ⎟
  ⎜⎪   log (x)               ⎟
  ⎜⎪   ───────      otherwise⎟
  ⎜⎪      2                  ⎟
  ⎝⎩                         ⎠
```

The problem is it doesn't know how to compute the lower limits with the symbolic term.

```py
>>> integrate(a* x**(a-1) * ln(x), x).limit(x, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/core/expr.py", line 3390, in limit
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/series/limits.py", line 64, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/series/limits.py", line 359, in doit
    r = gruntz(e, z, z0, dir)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/series/gruntz.py", line 711, in gruntz
    r = limitinf(e0, z)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/series/gruntz.py", line 452, in limitinf
    c0, e0 = mrv_leadterm(e, x)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/series/gruntz.py", line 527, in mrv_leadterm
    Omega, exps = mrv(e, x)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/series/gruntz.py", line 261, in mrv
    s, expr = mrv(d, x)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/series/gruntz.py", line 306, in mrv
    l = [mrv(a, x) for a in e.args]
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/series/gruntz.py", line 306, in <listcomp>
    l = [mrv(a, x) for a in e.args]
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/series/gruntz.py", line 318, in mrv
    raise NotImplementedError(
NotImplementedError: Don't know how to calculate the mrv of '(log(1/_p)/(_p**a*a) - 1/(_p**a*a**2), Ne(a, 0))'
```

This this is an instance of the problem described here https://github.com/sympy/sympy/issues/13312. If `limit` were able to split out symbolic constants into piecewise components, it might have a chance of computing this, and thus resulting in a (Piecewise) answer to this integral for general `a`. 

Although in this case, it also looks like it is trying to handle the ExprCondPair from the Piecewise, so for this to work, Gruntz would need to be fixed to be able to handle Piecewise correctly as well.

In either case, manually setting the assumptions on `a` so that the a!=0 term is always true (like `Symbol('a', positive=True)`) makes the Piecewise go away and makes Gruntz able to determine what it needs to know about expressions containing `a`.

**Comment by Scoodood** [comment]
Wow, great tricks! Thanks

**Comment by anutosh491** [comment]
> Although in this case, it also looks like it is trying to handle the ExprCondPair from the Piecewise, so for this to work, Gruntz would need to be fixed to be able to handle Piecewise correctly as well.

It seems we would need to implement an `elif isinstance(e, Piecewise)` block in `def mrv()` method to address this . I'm not sure how `mrv` is defined for a Piecewise function though , is it just `mrv` of the piece ( the piece at `f(x0)` where `x0` is the point concerning the limit) . Something around this lines did give me the answer locally but not sure if that's completely mathematically correct . Maybe @jksuom could have a look here.

**Comment by asmeurer** [comment]
Doing that without actual support in the algorithm for splitting symbolic constants into piecewise components would lead to the same problems if the piecewise conditions themselves contain symbolic constants (so that the condition containing the point x0 depends on their value).

**Comment by asmeurer** [comment]
Or alternatively if the point x0 itself is symbolic.
