### ISSUE TITLE
There isn't solution of the equation x^2*(2 - x)*y'' + 2*x*y' - 2*y = e^(-x)*x^2*(2 - x)^2 in sympy, but wolfram has

### ISSUE THREAD

**Issue by Jen7777777** [sympy/sympy#23351]
Equation:
```
x^2*(2 - x)*y'' + 2*x*y' - 2*y = e^(-x)*x^2*(2 - x)^2
```

Sympy 1.10.1:

```python
Traceback (most recent call last):
  File "test_diffeq.py", line 14, in <module>
    sol = dsolve(eq, y(x))
  File "/home/kontrolnaya_rabota_ru/workenv/test_sympy_1101/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 640, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "/home/kontrolnaya_rabota_ru/workenv/test_sympy_1101/lib/python3.8/site-packages/sympy/solvers/ode/ode.py", line 669, in _helper_simplify
    sols = solvefunc.get_general_solution()
  File "/home/kontrolnaya_rabota_ru/workenv/test_sympy_1101/lib/python3.8/site-packages/sympy/solvers/ode/single.py", line 296, in get_general_solution
    return self._get_general_solution(simplify_flag=simplify)
  File "/home/kontrolnaya_rabota_ru/workenv/test_sympy_1101/lib/python3.8/site-packages/sympy/solvers/ode/single.py", line 920, in _get_general_solution
    raise NotImplementedError("The given ODE " + str(eq) + " cannot be solved by"
NotImplementedError: The given ODE Derivative(y(x), x) - (x**2*(x - 2)*exp(x)*Derivative(y(x), (x, 2)) + x**2*(x**2 - 4*x + 4) + 2*y(x)*exp(x))*exp(-x)/(2*x) cannot be solved by the factorable group method

```

Wolfram:
https://www.wolframalpha.com/input?i=x%5E2*%282+-+x%29*y%27%27+%2B+2*x*y%27+-+2*y+%3D+e%5E%28-x%29*x%5E2*%282+-+x%29%5E2

**Comment by oscarbenjamin** [comment]
Do you know what method can solve the equation?

**Comment by oscarbenjamin** [comment]
It looks like the substitution `y = x*z` gives an ODE for `z` that is solvable by reduction of order:
```python
In [66]: eq = Eq(x**2*(2 - x)*f(x).diff(x, 2) + 2*x*f(x).diff(x) - 2*f(x), exp(-x)*x**2*(2 - x)**2)

In [67]: eq
Out[67]: 
             2                                                
 2          d              d                    2        2  -x
x ⋅(2 - x)⋅───(f(x)) + 2⋅x⋅──(f(x)) - 2⋅f(x) = x ⋅(2 - x) ⋅ℯ  
             2             dx                                 
           dx                                                 

In [68]: eq.lhs.subs(f(x), x*g(x)).doit().expand().collect(g(x))
Out[68]: 
                                           2      
⎛     3      2⎞ d          ⎛   4      3⎞  d       
⎝- 2⋅x  + 6⋅x ⎠⋅──(g(x)) + ⎝- x  + 2⋅x ⎠⋅───(g(x))
                dx                         2      
                                         dx       

In [69]: dsolve(_ - eq.rhs)
Out[69]: 
                         ⎛     2⎞  -x
            C₂⋅(1 - x)   ⎝2 - x ⎠⋅ℯ  
g(x) = C₁ + ────────── + ────────────
                 2             2     
                x             x 
```
