### ISSUE TITLE
1.10.1: pytest test suite issue

### ISSUE THREAD

**Issue by kloczek** [sympy/sympy#23528]
I'm trying to package your module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

I found that pytest is runnimg forever in `sympy/matrices/tests/test_matrices.py::test_pinv_rank_deficient_when_diagonalization_fails` unit.
Fragment from pytest output:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-sympy-1.10.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-sympy-1.10.1-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -v
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/tkloczko/rpmbuild/BUILD/sympy-sympy-1.10.1, configfile: pytest.ini, testpaths: sympy, doc/src
collected 10797 items

sympy/algebras/tests/test_quaternion.py::test_quaternion_construction PASSED                                                                                         [  0%]
sympy/algebras/tests/test_quaternion.py::test_quaternion_axis_angle PASSED                                                                                           [  0%]
sympy/algebras/tests/test_quaternion.py::test_quaternion_axis_angle_simplification PASSED                                                                            [  0%]
sympy/algebras/tests/test_quaternion.py::test_quaternion_complex_real_addition PASSED                                                                                [  0%]

[..]

sympy/matrices/tests/test_matrices.py::test_simplify_immutable PASSED                                                                                                [ 41%]
sympy/matrices/tests/test_matrices.py::test_replace PASSED                                                                                                           [ 41%]
sympy/matrices/tests/test_matrices.py::test_replace_map PASSED                                                                                                       [ 41%]
sympy/matrices/tests/test_matrices.py::test_atoms PASSED                                                                                                             [ 41%]
sympy/matrices/tests/test_matrices.py::test_pinv PASSED                                                                                                              [ 41%]
sympy/matrices/tests/test_matrices.py::test_pinv_rank_deficient_when_diagonalization_fails
```
ps output
```console
tkloczko 2315283  0.0  0.0 232624 12920 pts/9    Ss   May17   0:10  |               \_ bash -rcfile .bashrc
tkloczko 3518859  0.0  0.0 232760 10916 pts/9    S+   17:49   0:00  |               |   \_ rpmbuild -ba --with check --with failing_tests python-sympy.spec
tkloczko 3537608  0.0  0.0 222960  3436 pts/9    S+   17:50   0:00  |               |       \_ /bin/sh -e /var/tmp/rpm-tmp.BOFkuT
tkloczko 3537609 98.8  0.6 7381196 791044 pts/9  R+   17:50 104:34  |               |           \_ /usr/bin/python3 /usr/bin/pytest -ra -v
tkl
```
Will try to add that unit to --deselect list.
May I ask for some hints to diagnose that issue? 🤔

**Comment by oscarbenjamin** [comment]
> I found that pytest is runnimg forever in `sympy/matrices/tests/test_matrices.py::test_pinv_rank_deficient_when_diagonalization_fails` unit.

That test is marked as being both "slow" and "xfail". The slow marker means it will only run in the slow tests which run with a timeout (under the `bin/test` test runner).

**Comment by kloczek** [comment]
That unit has been running +.4h and before I've killed pytest I've checked using `strace  -p<pid>` do I see any process activity and that process was doing nothing. After few other tests I've (re)started whole build and I see 
```console
sympy/solvers/ode/tests/test_single.py::test_SingleODESolver PASSED                                                                                                  [ 82%]
sympy/solvers/ode/tests/test_single.py::test_linear_coefficients PASSED                                                                                              [ 82%]
```
If it will be no errors (so far there is no errors) and will be able to build rpm package will try at the end repeat whole build with that unit enabled.

**Comment by oscarbenjamin** [comment]
I expect that that test is always extremely slow. The point of my comment is that the test is not usually executed except under a short timeout and it is not expected to pass.

**Comment by kloczek** [comment]
OK 👍  .. will give that test one more chance 😋

**Comment by kloczek** [comment]
After whole night I see that pytest still is running and it is stuck on
```console
sympy/solvers/ode/tests/test_systems.py::test_linear_3eq_order1_type4_slow PASSED                                                                                    [ 82%]
sympy/solvers/ode/tests/test_systems.py::test_linear_neq_order1_type2_slow1 PASSED                                                                                   [ 82%]
sympy/solvers/ode/tests/test_systems.py::test_linear_new_order1_type2_de_lorentz_slow_check
```
I'm going to restart pytest with added to --deselect that unit.

**Comment by kloczek** [comment]
I've restarted this time pytest with installed `pytest-xdist` and `dditional `-n auto` pytest param and only after few minutes I have now result
```console
[gw34] [ 92%] XFAIL sympy/utilities/tests/test_wester.py::test_H18
sympy/utilities/tests/test_wester.py::test_M13
INTERNALERROR> def worker_internal_error(self, node, formatted_error):
INTERNALERROR>         """
INTERNALERROR>         pytest_internalerror() was called on the worker.
INTERNALERROR>
INTERNALERROR>         pytest_internalerror() arguments are an excinfo and an excrepr, which can't
INTERNALERROR>         be serialized, so we go with a poor man's solution of raising an exception
INTERNALERROR>         here ourselves using the formatted message.
INTERNALERROR>         """
INTERNALERROR>         self._active_nodes.remove(node)
INTERNALERROR>         try:
INTERNALERROR> >           assert False, formatted_error
INTERNALERROR> E           AssertionError: Traceback (most recent call last):
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR> E                 session.exitstatus = doit(config, session) or 0
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR> E                 config.hook.pytest_runtestloop(session=session)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR> E                 raise ex[1].with_traceback(ex[2])
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/xdist/remote.py", line 91, in pytest_runtestloop
INTERNALERROR> E                 self.run_one_test(torun)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/xdist/remote.py", line 110, in run_one_test
INTERNALERROR> E                 self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR> E                 raise ex[1].with_traceback(ex[2])
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 111, in pytest_runtest_protocol
INTERNALERROR> E                 runtestprotocol(item, nextitem=nextitem)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 130, in runtestprotocol
INTERNALERROR> E                 reports.append(call_and_report(item, "call", log))
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 221, in call_and_report
INTERNALERROR> E                 report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR> E                 gen.send(outcome)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/skipping.py", line 265, in pytest_runtest_makereport
INTERNALERROR> E                 rep = outcome.get_result()
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR> E                 raise ex[1].with_traceback(ex[2])
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 365, in pytest_runtest_makereport
INTERNALERROR> E                 return TestReport.from_item_and_call(item, call)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/reports.py", line 345, in from_item_and_call
INTERNALERROR> E                 longrepr = item.repr_failure(excinfo)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/python.py", line 1801, in repr_failure
INTERNALERROR> E                 return self._repr_failure_py(excinfo, style=style)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/nodes.py", line 475, in _repr_failure_py
INTERNALERROR> E                 return excinfo.getrepr(
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/_code/code.py", line 666, in getrepr
INTERNALERROR> E                 return fmt.repr_excinfo(self)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/_code/code.py", line 926, in repr_excinfo
INTERNALERROR> E                 reprtraceback = self.repr_traceback(excinfo_)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/_code/code.py", line 867, in repr_traceback
INTERNALERROR> E                 reprentry = self.repr_traceback_entry(entry, einfo)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/_code/code.py", line 818, in repr_traceback_entry
INTERNALERROR> E                 s = self.get_source(source, line_index, excinfo, short=short)
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/_code/code.py", line 756, in get_source
INTERNALERROR> E                 lines.extend(self.get_exconly(excinfo, indent=indent, markall=True))
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/_code/code.py", line 768, in get_exconly
INTERNALERROR> E                 exlines = excinfo.exconly(tryshort=True).split("\n")
INTERNALERROR> E               File "/usr/lib/python3.8/site-packages/_pytest/_code/code.py", line 585, in exconly
INTERNALERROR> E                 lines = format_exception_only(self.type, self.value)
INTERNALERROR> E               File "/usr/lib64/python3.8/traceback.py", line 140, in format_exception_only
INTERNALERROR> E                 return list(TracebackException(etype, value, None).format_exception_only())
INTERNALERROR> E               File "/usr/lib64/python3.8/traceback.py", line 493, in __init__
INTERNALERROR> E                 context = TracebackException(
INTERNALERROR> E               File "/usr/lib64/python3.8/traceback.py", line 493, in __init__
INTERNALERROR> E                 context = TracebackException(
INTERNALERROR> E               File "/usr/lib64/python3.8/traceback.py", line 493, in __init__
INTERNALERROR> E                 context = TracebackException(
INTERNALERROR> E               [Previous line repeated 473 more times]
INTERNALERROR> E             RecursionError: maximum recursion depth exceeded
INTERNALERROR> E           assert False
INTERNALERROR>
INTERNALERROR> /usr/lib/python3.8/site-packages/xdist/dsession.py:192: AssertionError
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/xdist/dsession.py", line 117, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/xdist/dsession.py", line 140, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/xdist/dsession.py", line 179, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('sympy/stats/tests/test_continuous_rv.py::test_uniform_P', <WorkerController gw28>)
INTERNALERROR> assert not 'sympy/stats/tests/test_continuous_rv.py::test_uniform_P'

======================================= 1 failed, 9489 passed, 269 skipped, 191 xfailed, 8 xpassed, 11 warnings in 532.85s (0:08:52) =======================================
```
So looks like one unit is failing with `INTERNALERROR`. Going to restart pytest with added that unit as well to --deselect to confirm that everything else is OK.

**Comment by kloczek** [comment]
Looks like I;ve managed to narrow which one unit ius failing
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-sympy-1.10.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-sympy-1.10.1-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ xvfb-run -a /usr/bin/pytest -ra sympy/solvers/ode/tests/test_systems.py::test_linear_3eq_order1_type4_long_check
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
architecture: 64-bit
cache:        yes
ground types: python

rootdir: /home/tkloczko/rpmbuild/BUILD/sympy-sympy-1.10.1, configfile: pytest.ini
plugins: cov-3.0.0, mock-3.7.0, hypothesis-6.41.0, timeout-2.1.0, forked-1.4.0, xdist-2.5.0
collected 1 item

sympy/solvers/ode/tests/test_systems.py F                                                                                                                            [100%]

================================================================================= FAILURES =================================================================================
_________________________________________________________________ test_linear_3eq_order1_type4_long_check __________________________________________________________________

    @slow
    def test_linear_3eq_order1_type4_long_check():
        if ON_TRAVIS:
            skip("Too slow for travis.")

>       eq, sol = _linear_3eq_order1_type4_long()

sympy/solvers/ode/tests/test_systems.py:2286:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def _linear_3eq_order1_type4_long():
        x, y, z = symbols('x, y, z', cls=Function)
        t = Symbol('t')

        f = t ** 3 + log(t)
        g = t ** 2 + sin(t)

        eq1 = (Eq(diff(x(t), t), (4*f + g)*x(t) - f*y(t) - 2*f*z(t)),
               Eq(diff(y(t), t), 2*f*x(t) + (f + g)*y(t) - 2*f*z(t)), Eq(diff(z(t), t), 5*f*x(t) + f*y(
            t) + (-3*f + g)*z(t)))

        dsolve_sol = dsolve(eq1)
        dsolve_sol1 = [_simpsol(sol) for sol in dsolve_sol]

        x_1 = sqrt(-t**6 - 8*t**3*log(t) + 8*t**3 - 16*log(t)**2 + 32*log(t) - 16)
        x_2 = sqrt(3)
        x_3 = 8324372644*C1*x_1*x_2 + 4162186322*C2*x_1*x_2 - 8324372644*C3*x_1*x_2
        x_4 = 1 / (1903457163*t**3 + 3825881643*x_1*x_2 + 7613828652*log(t) - 7613828652)
        x_5 = exp(t**3/3 + t*x_1*x_2/4 - cos(t))
        x_6 = exp(t**3/3 - t*x_1*x_2/4 - cos(t))
        x_7 = exp(t**4/2 + t**3/3 + 2*t*log(t) - 2*t - cos(t))
        x_8 = 91238*C1*x_1*x_2 + 91238*C2*x_1*x_2 - 91238*C3*x_1*x_2
        x_9 = 1 / (66049*t**3 - 50629*x_1*x_2 + 264196*log(t) - 264196)
        x_10 = 50629 * C1 / 25189 + 37909*C2/25189 - 50629*C3/25189 - x_3*x_4
        x_11 = -50629*C1/25189 - 12720*C2/25189 + 50629*C3/25189 + x_3*x_4
        sol = [Eq(x(t), x_10*x_5 + x_11*x_6 + x_7*(C1 - C2)), Eq(y(t), x_10*x_5 + x_11*x_6), Eq(z(t), x_5*(
                -424*C1/257 - 167*C2/257 + 424*C3/257 - x_8*x_9) + x_6*(167*C1/257 + 424*C2/257 -
                167*C3/257 + x_8*x_9) + x_7*(C1 - C2))]

>       assert dsolve_sol1 == sol
E       AssertionError: assert [Eq(x(t), (-C.../4 - cos(t)))] == [Eq(x(t), (C1.../4 - cos(t)))]
E         At index 0 diff: Eq(x(t), (-C1 + C2)*exp(t**4/2 + t**3/3 + 2*t*(log(t) - 1) - cos(t)) + (-C1/29 - 31*C2/29 + 31*C3/29 + (-1862*sqrt(3)*C1*sqrt(-t**6 - 8*t**3*log(t) + 8*t**3 - 16*log(t)**2 + 32*log(t) - 16) - 3724*sqrt(3)*C2*sqrt(-t**6 - 8*t**3*log(t) + 8*t**3 - 16*log(t)**2 + 32*log(t) - 16) + 3724*sqrt(3)*C3*sqrt(-t**6 - 8*t**3*log(t) + 8*t**3 - 16*log(t)**2 + 32*log(t) - 16))/(2523*t**3 - 2697*sqrt(3)*sqrt(-t**6 - 8*t**3*log(t) + 8*t**3 - 16*log(t)**2 + 32*log(t) - 16) + 10092*log(t) - 10092))*exp(t**3/3 + sqrt(3)*t*sqrt(-t**6 + 8*t**3*(1 - log(t)) - 16*log(t)**2 + 3...
E
E         ...Full output truncated (2 lines hidden), use '-vv' to show

sympy/solvers/ode/tests/test_systems.py:2171: AssertionError
                                                                              DO *NOT* COMMIT!
========================================================================= short test summary info ==========================================================================
FAILED sympy/solvers/ode/tests/test_systems.py::test_linear_3eq_order1_type4_long_check - AssertionError: assert [Eq(x(t), (-C.../4 - cos(t)))] == [Eq(x(t), (C1.../4 - c...
```
