### ISSUE TITLE
Q: where I can find `sympylive` sphinx extension?

### ISSUE THREAD

**Issue by kloczek** [sympy/sympy#23523]
I'm trying to build `sympy` documentation and I found that it needs `sympylive` module.
Where I can find it? 🤔 
```console
+ /usr/bin/sphinx-build -n -T -b man doc/src build/sphinx/man
Running Sphinx v4.5.0
fatal: not a git repository (or any parent up to mount point /home/tkloczko)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/home/tkloczko/rpmbuild/BUILD/sympy-sympy-1.10.1/doc/src/conf.py:279: UserWarning: Failed to get the git commit hash as the command 'git rev-parse HEAD' is not working. The commit hash will be assumed as the SymPy master, but the lines may be misleading or nonexistent as it is not the correct branch the doc is built with. Check your installation of 'git' if you want to resolve this warning.
  warnings.warn(
loading translations [en]... done

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 425, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sympylive'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 428, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sympylive (exception: No module named 'sympylive')

Extension error:
Could not import extension sympylive (exception: No module named 'sympylive')
```

**Comment by asmeurer** [comment]
I'm not sure how to fix this for 1.10.1, but the development version of SymPy has removed the sympylive extension, and it won't be included in the next version. So this should no longer be a problem there. 

What is the command you are using to build the documentation? It seems like you are trying to build a man page, which we haven't supported. I wouldn't be surprised if some work is needed to make that work.

**Comment by kloczek** [comment]
Hmm I don't see any changes on 1.10 branch 🤔 
https://github.com/sympy/sympy/compare/1.10...sympy-1.10.1
May I ask to just drop hash of exact commit? 😄

**Comment by kloczek** [comment]
BTW I've been trying to generate documentation as man page. I've  removed using `sympylive` and with that sphinx is crashing with call trace
```console
+ /usr/bin/sphinx-build -n -T -b man doc/src build/sphinx/man
Running Sphinx v4.5.0
fatal: not a git repository (or any parent up to mount point /home/tkloczko)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/home/tkloczko/rpmbuild/BUILD/sympy-sympy-1.10.1/doc/src/conf.py:279: UserWarning: Failed to get the git commit hash as the command 'git rev-parse HEAD' is not working. The commit hash will be assumed as the SymPy master, but the lines may be misleading or nonexistent as it is not the correct branch the doc is built with. Check your installation of 'git' if you want to resolve this warning.
  warnings.warn(
loading translations [en]... done
making output directory... done
WARNING: favicon file '../_build/logo/sympy-notailtext-favicon.ico' does not exist
[autosummary] generating autosummary for: aboutus.rst, citing.rst, explanation/active-deprecations.md, explanation/gotchas.rst, explanation/index.rst, explanation/special_topics/classification.rst, explanation/special_topics/finite_diff_derivatives.rst, explanation/special_topics/index.rst, guides/assumptions.rst, guides/booleans.rst, ..., tutorial/gotchas.rst, tutorial/index.rst, tutorial/intro.rst, tutorial/manipulation.rst, tutorial/matrices.rst, tutorial/preliminaries.rst, tutorial/printing.rst, tutorial/simplification.rst, tutorial/solvers.rst, wiki.rst
/usr/lib64/python3.8/importlib/__init__.py:127: SymPyDeprecationWarning:

The sympy.testing.randtest submodule is deprecated. Use sympy.core.random instead.

See https://docs.sympy.org/latest/explanation/active-deprecations.html#deprecated-sympy-testing-randtest
for details.

This has been deprecated since SymPy version 1.10. It
will be removed in a future version of SymPy.

  return _bootstrap._gcd_import(name[level:], package, level)
myst v0.17.2: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['dollarmath'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=2, heading_slug_func=None, footnote_transition=True, sub_delimiters=('{', '}'), words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 272 added, 0 changed, 0 removed
/usr/lib/python3.8/site-packages/numpydoc/docscrape.py:440: UserWarning: Unknown section Explanation in the docstring of powsimp in /home/tkloczko/rpmbuild/BUILD/sympy-sympy-1.10.1/sympy/simplify/powsimp.py.
  warn(msg)
/usr/lib/python3.8/site-packages/numpydoc/docscrape.py:440: UserWarning: Unknown section Explanation in the docstring of args_cnc in /home/tkloczko/rpmbuild/BUILD/sympy-sympy-1.10.1/sympy/core/expr.py.
  warn(msg)
WARNING: error while formatting signature for sympy.algebras.Quaternion.to_rotation_matrix: Handler <function mangle_signature at 0x7f0a5addce50> for event 'autodoc-process-signature' threw an exception (exception: The section Examples appears twice in  Returns the equivalent rotation transformation matrix of the quaternion
which represents rotation about the origin if v is not passed.

Parameters
==========

v : tuple or None
    Default value: None

Returns
=======

tuple
    Returns the equivalent rotation transformation matrix of the quaternion
    which represents rotation about the origin if v is not passed.

Examples
========

>>> from sympy import Quaternion
>>> from sympy import symbols, trigsimp, cos, sin
>>> x = symbols('x')
>>> q = Quaternion(cos(x/2), 0, 0, sin(x/2))
>>> trigsimp(q.to_rotation_matrix())
Matrix([
[cos(x), -sin(x), 0],
[sin(x),  cos(x), 0],
[     0,       0, 1]])

Generates a 4x4 transformation matrix (used for rotation about a point
other than the origin) if the point(v) is passed as an argument.

Examples
========

>>> from sympy import Quaternion
>>> from sympy import symbols, trigsimp, cos, sin
>>> x = symbols('x')
>>> q = Quaternion(cos(x/2), 0, 0, sin(x/2))
>>> trigsimp(q.to_rotation_matrix((1, 1, 1)))
 Matrix([
[cos(x), -sin(x), 0,  sin(x) - cos(x) + 1],
[sin(x),  cos(x), 0, -sin(x) - cos(x) + 1],
[     0,       0, 1,                    0],
[     0,       0, 0,                    1]]) in the docstring of to_rotation_matrix in /home/tkloczko/rpmbuild/BUILD/sympy-sympy-1.10.1/sympy/algebras/quaternion.py.)

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/lib/python3.8/site-packages/numpydoc/numpydoc.py", line 219, in mangle_signature
    doc = get_doc_object(obj, config={'show_class_members': False})
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape_sphinx.py", line 442, in get_doc_object
    return SphinxFunctionDoc(obj, doc=doc, config=config)
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape_sphinx.py", line 396, in __init__
    FunctionDoc.__init__(self, obj, doc=doc, config=config)
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 572, in __init__
    NumpyDocString.__init__(self, doc, config)
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 147, in __init__
    self._parse()
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 410, in _parse
    self['See Also'] = self._parse_see_also(content)
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 332, in _parse_see_also
    self._error_location(f"Error parsing See Also entry {line!r}")
  File "/usr/lib/python3.8/site-packages/numpydoc/docscrape.py", line 438, in _error_location
    raise ValueError(msg)
ValueError: Error parsing See Also entry '.separatevars(), .expand(log=True), sympy.core.add.Add.as_two_terms(),' in the docstring of as_independent in /home/tkloczko/rpmbuild/BUILD/sympy-sympy-1.10.1/sympy/core/expr.py.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 283, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 407, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 181, in read_doc
    pub.publish()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 101, in read
    self.parse()
  File "/usr/lib/python3.8/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.8/site-packages/sphinx/parsers.py", line 89, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 3008, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/directive.py", line 165, in run
    result = parse_generated_content(self.state, params.result, documenter)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/directive.py", line 112, in parse_generated_content
    state.nested_parse(content, 0, node)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.8/site-packages/sphinx/domains/__init__.py", line 281, in run
    return super().run()
  File "/usr/lib/python3.8/site-packages/sphinx/directives/__init__.py", line 200, in run
    self.state.nested_parse(self.content, self.content_offset, contentnode)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2344, in explicit_markup
    self.explicit_list(blank_finish)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2369, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 318, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2647, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py", line 258, in run
    items = self.get_items(names)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py", line 385, in get_items
    sig = documenter.format_signature(show_annotation=False)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2208, in format_signature
    sig = super().format_signature(**kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1254, in format_signature
    sig = super().format_signature(**kwargs)  # type: ignore
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 517, in format_signature
    result = self.env.events.emit_firstresult('autodoc-process-signature',
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 112, in emit_firstresult
    for result in self.emit(name, *args, allowed_exceptions=allowed_exceptions):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 102, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function mangle_signature at 0x7f0a5addce50> for event 'autodoc-process-signature' threw an exception (exception: Error parsing See Also entry '.separatevars(), .expand(log=True), sympy.core.add.Add.as_two_terms(),' in the docstring of as_independent in /home/tkloczko/rpmbuild/BUILD/sympy-sympy-1.10.1/sympy/core/expr.py.)

Extension error (numpydoc.numpydoc):
Handler <function mangle_signature at 0x7f0a5addce50> for event 'autodoc-process-signature' threw an exception (exception: Error parsing See Also entry '.separatevars(), .expand(log=True), sympy.core.add.Add.as_two_terms(),' in the docstring of as_independent in /home/tkloczko/rpmbuild/BUILD/sympy-sympy-1.10.1/sympy/core/expr.py.)
```

**Comment by asmeurer** [comment]
The change is in the master branch. If you want to do this, I recommend working off the master branch as it has the sympylive extension removed, as well as some other improvements to the build process.

If you want, you can make a PR to make `make man` work in the docs. I expect we won't ever actually ship the man pages for the docs since they would be huge, but I'm not opposed to making it work for anyone who wants to make them themselves.

**Comment by kloczek** [comment]
> The change is in the master branch. If you want to do this, I recommend working off the master branch as it has the sympylive extension removed, as well as some other improvements to the build process.

I see 818 patches between sympy-1.10.1 and master.

> If you want, you can make a PR to make `make man` work in the docs. I expect we won't ever actually ship the man pages for the docs since they would be huge, but I'm not opposed to making it work for anyone who wants to make them themselves.

Currently conf.py is enough to use straight `sphinx-build` command as you may see that in copied build log.
To generate man page in packages with sphinx documentation I'm using my own rpm macro `%sphinx_build_man`
```spec
%sphinx_build       /usr/bin/sphinx-build
%sphinx_build_man   %{expand:\
        PBR_VERSION=%(v=%{version}; echo ${v%~*}) \
        PDM_PEP517_SCM_VERSION=%(v=%{version}; echo ${v%~*}) \
        SETUPTOOLS_SCM_PRETEND_VERSION=%(v=%{version}; echo ${v%~*}) \
        %sphinx_build -n -T -b man %["%{*}"?"%{*}":"docs"] build/sphinx/man}
```
This is in how many modules was possible to use that
```console
[tkloczko@devel-g2v SPECS]$ grep py3_build_sphinx_man python-* | wc -l; grep sphinx_build_man python-* | wc -l; ls -1 python-*| wc -l
135
406
940
```
Still I have 135 packages to migrate from use sphinx<>setuptools integration (`python setup.py build_sphinx`) to that new macro 😋 
Using Makefile will cause that in build env would be necessary to install make .. which with my my macro is not needed. As you see as well +5/9 of all packaged python modules have sphinx vased documentation.
