### ISSUE TITLE
Crash in `integrate`

### ISSUE THREAD

**Issue by agatha2** [sympy/sympy#23610]
Consider the following complete example:
```py
from sympy import * #Using SymPy 1.10.1 in Python 3.10.4

a = Symbol("a")
x = Symbol("x")

fxa = (x**a-1) / log(x)

Ia = Integral( fxa, (x,0,1) )
print(Ia)

dIa_da = simplify(diff(Ia,a))
print(dIa_da)

Ia = integrate( dIa_da, a ) #crash
print(Ia)
```
This produces:
```text
Integral((x**a - 1)/log(x), (x, 0, 1))
Integral(x**a, (x, 0, 1))
Traceback (most recent call last):
  File "path/to/test.py", line 14, in <module>
    Ia = integrate( dIa_da, a ) #crash
  File "path/to/sympy/integrals/integrals.py", line 1566, in integrate
    return integral.doit(**doit_flags)
  File "path/to/sympy/integrals/integrals.py", line 500, in doit
    did = self.xreplace(reps).doit(**hints)
  File "path/to/sympy/integrals/integrals.py", line 548, in doit
    antideriv = function._eval_integral(xab[0],
  File "path/to/sympy/functions/elementary/piecewise.py", line 502, in _eval_integral
    anti = integrate(abei[i][-2], x, **kwargs)
  File "path/to/sympy/integrals/integrals.py", line 1566, in integrate
    return integral.doit(**doit_flags)
  File "path/to/sympy/integrals/integrals.py", line 613, in doit
    antideriv = self._eval_integral(
  File "path/to/sympy/integrals/integrals.py", line 956, in _eval_integral
    result, i = risch_integrate(f, x, separate_integral=True,
  File "path/to/sympy/integrals/risch.py", line 1849, in risch_integrate
    i = NonElementaryIntegral(i.function.subs(DE.backsubs),i.limits)
AttributeError: 'NaN' object has no attribute 'function'. Did you mean: 'is_Function'?
```
I assume the `integrate` function is not supposed to ever crash, so this would be a bug.

Note that this example is intended as a simple demonstration of Feynman integration, and should be easily solvable by this means.

**Comment by asmeurer** [comment]
This does look like a bug in Risch. But I'm also not sure about this intermediate result

```
>>> integrate(x**a, (x, 0, 1))
Piecewise((-0**(a + 1)/(a + 1) + 1/(a + 1), (a > -oo) & (a < oo) & Ne(a, -1)), (oo, True))
>>> pprint(_)
⎧   a + 1
⎪  0          1
⎪- ────── + ─────  for a > -∞ ∧ a < ∞ ∧ a ≠ -1
⎨  a + 1    a + 1
⎪
⎪       ∞                   otherwise
⎩
```

**Comment by oscarbenjamin** [comment]
That zero seems to come from `_eval_interval` here:
https://github.com/sympy/sympy/blob/78bbfa804d00899aa92d61eb4f012d6f31d928c3/sympy/integrals/integrals.py#L711
I'm not really sure what `_eval_interval` is supposed to do but e.g.:
```python
In [21]: x, a = symbols('x, a')

In [22]: (x**a)._eval_interval(x, S.Zero, S.One)
Out[22]: 
     a
1 - 0 
```

**Comment by asmeurer** [comment]
_eval_interval calls limit. Perhaps it would be more useful if limit itself returned a Piecewise. `limit(x**a, x, 0, '+')` is `0` if `a >= 0` and `oo` if `a < 0` (actually `re(a)`). I think `0**a` actually represents the same thing except for `a = 0` (and that case is excluded in the final Piecewise), but a Piecewise giving the different values might be clearer and easier for other things to work with.

**Comment by klimanek** [comment]
Just restrict the parameter `t` to `nonnegative` and it will work. 

```python
a = Symbol("a", nonnegative=True)
```

I describe this problem here: https://github.com/sympy/sympy/issues/26949.
