### ISSUE TITLE
Series expansion not working!

### ISSUE THREAD

**Issue by gkdgoutam** [sympy/sympy#23635]
I want to expand the following 

`from sympy import Symbol, gamma, series`
`x=Symbol('x')`
`y=Symbol('y')`
`series(series(gamma(-x-y),x,n=2), y, n=2)`

> >>> series(series(gamma(-x-y),x,n=2), y, n=2)
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/sympy/core/mul.py", line 1955, in _eval_nseries
    coeff, exp = t.leadterm(x, logx=logx)
  File "/home/user/.local/lib/python3.8/site-packages/sympy/core/expr.py", line 3486, in leadterm
    raise ValueError(filldedent("""
ValueError: 
cannot compute leadterm(polygamma(0, -_x), _x). The coefficient should
have been free of _x but got polygamma(0, -_x)
%
During handling of the above exception, another exception occurred:
%
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/sympy/series/series.py", line 63, in series
    return expr.series(x, x0, n, dir)
  File "/home/user/.local/lib/python3.8/site-packages/sympy/core/function.py", line 744, in _eval_nseries
    raise PoleError("Cannot expand %s around 0" % (self))
sympy.core.function.PoleError: Cannot expand polygamma(0, -_x) around 0

I get the expansion in Mathematica as 

`-0.577216 - 0.989056 x - 0.907479 x^2 - (1. x^2)/y^3 + x/y^2 - 1./y + 
 0.00208333 (-474.747 - 871.18 x - 1413.69 x^2) y + (-0.907479 - 
    2.94518 x - 5.89197 x^2) y^2`

**Comment by gkdgoutam** [comment]
This only works when one writes the `gamma` in a different form as:

`series(series(gamma(1-x-y)/(-x-y),x,n=2).removeO(), y, n=2).removeO()`

**Comment by anutosh491** [comment]
`_eval_nseries` hasn't been implemented for the `polygamma` function which is the reason for the error.
