### ISSUE TITLE
SystemError: excessive stack use.  Sympy 1.10.1 using Python 3.10.4

### ISSUE THREAD

**Issue by nasser1** [sympy/sympy#23690]
I do not know if this is known issue or already fixed. If it is please feel free to close this. Just reporting an issue found.

```
>python
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> x=symbols('x')
>>> a=symbols('a')
>>> integrand="(a**2-4*cos(x)**2)**(3/4)*sin(2*x)"
>>> integrate(S(integrand),x)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 1566, in integrate
    return integral.doit(**doit_flags)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 613, in doit
    antideriv = self._eval_integral(
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 1084, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 143, in heurisch_wrapper
    res = heurisch(f, x, rewrite, hints, mappings, retries, degree_offset,
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 733, in heurisch
    solution = _integrate('Q')
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 711, in _integrate
    coeff_ring = PolyRing(poly_coeffs, ground)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/polys/rings.py", line 230, in __new__
    obj.monomial_mul = codegen.mul()
  File "/home/me/.local/lib/python3.10/site-packages/sympy/polys/monomials.py", line 424, in mul
    return self._build(code, name)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/polys/monomials.py", line 406, in _build
    exec(code, ns)
SystemError: excessive stack use: stack is 5005 deep

```

On Linux Ubutnu 22.04 under WSL 2.0 with 128 GB RAM.

**Comment by oscarbenjamin** [comment]
How long did it take to reach this error?

I just tried this code and after 5 minutes it's still running and I don't see an error yet. My guess is that this generates a polynomial ring with a very large number of generators and then the code here blows Python's internal stack:
https://github.com/sympy/sympy/blob/7871a97e1509bf20d42d2b5d43aa2d7e83acd6fe/sympy/polys/monomials.py#L412-L424

I added something to print out the number of generators used for each polynomial ring:
```diff
diff --git a/sympy/polys/monomials.py b/sympy/polys/monomials.py
index 51f94a9..6f7b286 100644
--- a/sympy/polys/monomials.py
+++ b/sympy/polys/monomials.py
@@ -400,6 +400,7 @@ class MonomialOps:
 
     def __init__(self, ngens):
         self.ngens = ngens
+        print(ngens)
 
     def _build(self, code, name):
         ns = {}
```
Then I ran the example code. So far I have this as output but it hasn't finished yet:
```
In [1]: >>> from sympy import *
   ...: >>> x=symbols('x')
   ...: >>> a=symbols('a')
   ...: >>> integrand="(a**2-4*cos(x)**2)**(3/4)*sin(2*x)"
   ...: >>> integrate(S(integrand),x)
3
1
1
1
1
2
2
2
2
1
2
5005
6
```
So a polynomial ring with 5005 generators was created. However here it didn't crash and has moved on to a new ring with 6 generators. It still hasn't finished though and I gave up waiting. I'm also running this on Ubuntu but with Python 3.8.

Maybe the problem is only with 3.10 (which I don't have available here for immediate testing).

We can test that code directly though like this:
```python
In [1]: from sympy.polys.monomials import MonomialOps

In [2]: mo = MonomialOps(5005)

In [3]: mo.mul()
Out[3]: <function monomial_mul(A, B)>
```
Can you test that? Does it also crash with SystemError?

I added something to the mul method to show the code that is generated and it looks like this:
```python
In [1]: from sympy.polys.monomials import MonomialOps

In [2]: mo = MonomialOps(5)

In [3]: mo.mul()
def monomial_mul(A, B):
    (a0, a1, a2, a3, a4,) = A
    (b0, b1, b2, b3, b4,) = B
    return (a0 + b0, a1 + b1, a2 + b2, a3 + b3, a4 + b4,)

Out[3]: <function monomial_mul(A, B)>
```
I guess that if the number of generators is large enough then CPython struggles to compile this code. However with Python 3.8 I can make this very large:
```python
In [1]: from sympy.polys.monomials import MonomialOps

In [2]: mo = MonomialOps(100000)

In [3]: mo.mul()
Out[3]: <function monomial_mul(A, B)>
```

**Comment by nasser1** [comment]
It took about 2 minutes from start to end. But I have very fast PC. Here is screen shot

![screen_shot_python](https://user-images.githubusercontent.com/15114517/175931370-2ff8de55-a375-4d97-9eb7-f135328dc12c.png)

**Comment by oscarbenjamin** [comment]
Thanks.

I wonder if this is due to https://github.com/python/cpython/pull/25403

I can see in the diff there what looks like the source of this exception:
https://github.com/python/cpython/blob/c0453a40faaadb43d2e69767af6c9680f8689063/Python/compile.c#L8649-L8658

**Comment by oscarbenjamin** [comment]
I opened a CPython issue: https://github.com/python/cpython/issues/94329

This should probably still be changed in SymPy though. For large tuples I expect it would be faster to use something like `tuple(map(add, m1, m2))` anyway.

**Comment by jksuom** [comment]
>  it would be faster to use something like `tuple(map(add, m1, m2))`

or `tuple(a + b for a, b in zip(A, B))`. The current `monomial_mul` looks very inefficient for a large number of generators. (5000 times store a and store b into local stack, then 5000 additions loading from the local stack.) We could probably dispense with the `monomial_xxx` methods altogether.

**Comment by oscarbenjamin** [comment]
Looks like using `tuple(map(add, m1, m2))` is faster than the comprehension:
```python
In [7]: N = 1000

In [8]: A = B = tuple(range(N))

In [9]: %timeit tuple(a + b for a, b in zip(A, B))
93.3 µs ± 360 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [10]: from operator import add

In [11]: %timeit tuple(map(add, A, B))
44.4 µs ± 69.7 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [12]: N = 2

In [13]: A = B = tuple(range(N))

In [14]: %timeit tuple(a + b for a, b in zip(A, B))
971 ns ± 13.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [15]: %timeit tuple(map(add, A, B))
575 ns ± 2.15 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
For small N it seems the compiled function is faster:
```python
In [52]: from operator import add

In [53]: from sympy.polys.monomials import MonomialOps

In [54]: N = 2

In [55]: A = B = tuple(range(N))

In [56]: mul1 = lambda m1, m2: tuple(map(add, m1, m2))

In [57]: mul2 = lambda m1, m2: tuple(a+b for a, b in zip(m1, m2))

In [58]: mul3 = MonomialOps(N).mul()

In [59]: %timeit mul1(A, B)
605 ns ± 8.53 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [60]: %timeit mul2(A, B)
1.04 µs ± 5.94 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [61]: %timeit mul3(A, B)
281 ns ± 4.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
I guess that's why this was written this way (since small `N` is the common case).

Timing on this machine it seems that at least measuring under timeit the compiled function is faster for N up to around 250. After that the `tuple(map(add, ...))` method is fastest although not by much compared to the compiled function:
```python
In [92]: N = 3000

In [93]: A = B = tuple(range(N))

In [94]: mul3 = MonomialOps(N).mul()

In [95]: %timeit mul1(A, B)
135 µs ± 296 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [96]: %timeit mul2(A, B)
280 µs ± 3.85 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [97]: %timeit mul3(A, B)
152 µs ± 355 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
Probably for this many generators we should use sparse monomials anyway (#20857).

**Comment by oscarbenjamin** [comment]
As an aside it looks like a list comprehension is faster than a generator expression:
```python
In [100]: mul4 = lambda m1, m2: tuple([a+b for a, b in zip(m1, m2)])

In [101]: mul2 = lambda m1, m2: tuple(a+b for a, b in zip(m1, m2))

In [102]: %timeit mul2(A, B)
277 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [103]: %timeit mul4(A, B)
227 µs ± 2.19 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by nasser1** [comment]
FYI,

Here is another one that gives similar error, but with different stack size deep number. Are these caused by same issue or do you like to open new issue on this?  Same system as above.

```
>python
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> x=symbols('x')
>>> integrate(S("cos(x)**2/(1+cos(x)**2+cos(x)**4)**(1/2)"),x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 1566, in integrate
    return integral.doit(**doit_flags)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 613, in doit
    antideriv = self._eval_integral(
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 1084, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 143, in heurisch_wrapper
    res = heurisch(f, x, rewrite, hints, mappings, retries, degree_offset,
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 750, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 750, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 750, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 507, in heurisch
    result = heurisch(f, x, rewrite=True, hints=hints,
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 733, in heurisch
    solution = _integrate('Q')
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 711, in _integrate
    coeff_ring = PolyRing(poly_coeffs, ground)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/polys/rings.py", line 230, in __new__
    obj.monomial_mul = codegen.mul()
  File "/home/me/.local/lib/python3.10/site-packages/sympy/polys/monomials.py", line 424, in mul
    return self._build(code, name)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/polys/monomials.py", line 406, in _build
    exec(code, ns)
SystemError: excessive stack use: stack is 3062 deep
>>>

```

**Comment by oscarbenjamin** [comment]
> Are these caused by same issue or do you like to open new issue on this?

Thanks for reporting but yes it's the same issue. The heurisch algorithm sometimes generates large polynomial rings and its implementation will fail with Python 3.10 and upwards. That's because of a bug in CPython but we should change the approach in SymPy as well because the it is not a good way to implement this.

**Comment by oscarbenjamin** [comment]
The CPython bug has been fixed on all branches so the next bugfix release of 3.10 will fix this. It would still be good to change this code but this does not need to be a release blocker any more so I'm removing the milestone.
