### ISSUE TITLE
why same integral gives exception under different version of Ubuntu and GCC?

### ISSUE THREAD

**Issue by nasser1** [sympy/sympy#23718]
I do not know if this is know or been reported before.

I noticed in a test I did that one integral gives exception now when it did not before.

Using sympy 1.10.1 on Ububtu 22.04 with GCC 11.2.0 this fails

```
>cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"

>uname -r
5.10.102.1-microsoft-standard-WSL2

>python
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.10.1'
>>> from sympy import *
>>> a,b,x=symbols('a b x')
>>> integrate(1/(b*cos(x)+a*sin(x)),x)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 1566, in integrate
    return integral.doit(**doit_flags)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 613, in doit
    antideriv = self._eval_integral(
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 1084, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 177, in heurisch_wrapper
    expr = heurisch(f.subs(sub_dict), x, rewrite, hints, mappings, retries,
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 570, in heurisch
    v_split = _splitter(Q)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 547, in _splitter
    q_split = _splitter(cancel(q / s))
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 535, in _splitter
    c, q = p.as_poly(y).primitive()
AttributeError: 'NoneType' object has no attribute 'primitive'
>>>
```

Using sympy 1.10.1 on Ubuntu 20.04 with GCC 9.4.0 same exact integrals does not evaluate but no exception. 

```
>cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"

>uname -r

5.10.102.1-microsoft-standard-WSL2

>python
Python 3.10.4 (main, Apr  8 2022, 17:35:13) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.10.1'
>>> from sympy import *
>>> a,b,x=symbols('a b x')
>>> anti=integrate(1/(b*cos(x)+a*sin(x)),x)
>>> integrate(1/(b*cos(x)+a*sin(x)),x)
Integral(1/(a*sin(x) + b*cos(x)), x)
>>>

```

Why the difference?

Using WSL 2.0 under windows 10 in both cases.

**Comment by oscarbenjamin** [comment]
I think if you just run this repeatedly then you'll see that it sometimes fails and sometimes doesn't:
```console
$ python bug.py 
Traceback (most recent call last):
  File "bug.py", line 5, in <module>
    pprint(integrate(1/(b*cos(x)+a*sin(x)),x))
  File "/home/oscar/current/sympy/sympy.git/sympy/integrals/integrals.py", line 1567, in integrate
    return integral.doit(**doit_flags)
  File "/home/oscar/current/sympy/sympy.git/sympy/integrals/integrals.py", line 612, in doit
    antideriv = self._eval_integral(
  File "/home/oscar/current/sympy/sympy.git/sympy/integrals/integrals.py", line 1084, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/home/oscar/current/sympy/sympy.git/sympy/integrals/heurisch.py", line 177, in heurisch_wrapper
    expr = heurisch(f.subs(sub_dict), x, rewrite, hints, mappings, retries,
  File "/home/oscar/current/sympy/sympy.git/sympy/integrals/heurisch.py", line 572, in heurisch
    v_split = _splitter(Q)
  File "/home/oscar/current/sympy/sympy.git/sympy/integrals/heurisch.py", line 549, in _splitter
    q_split = _splitter(cancel(q / s))
  File "/home/oscar/current/sympy/sympy.git/sympy/integrals/heurisch.py", line 537, in _splitter
    c, q = p.as_poly(y).primitive()
AttributeError: 'NoneType' object has no attribute 'primitive'
$ python bug.py 
⌠                       
⎮          1            
⎮ ─────────────────── dx
⎮ a⋅sin(x) + b⋅cos(x)   
⌡                       
```
In SymPy 1.9 when it succeeds it gives an evaluated integral:
```console
$ python bug.py 
⎧                  ⎛     ⎛   ⎛x⎞    ⎞      ⎛   ⎛x⎞    ⎞⎞                                 
⎪              zoo⋅⎜- log⎜tan⎜─⎟ - 1⎟ + log⎜tan⎜─⎟ + 1⎟⎟                for a = 0 ∧ b = 0
⎪                  ⎝     ⎝   ⎝2⎠    ⎠      ⎝   ⎝2⎠    ⎠⎠                                 
⎪                                                                                        
⎪                                                                                   _____
⎪                                 1                                                ╱   2 
⎪                     ──────────────────────────                        for a = -╲╱  -b  
⎪                                   _____                                                
⎪                                  ╱   2                                                 
⎪                     b⋅sin(x) + ╲╱  -b  ⋅cos(x)                                         
⎪                                                                                        
⎪                                                                                  _____ 
⎪                                 1                                               ╱   2  
⎪                     ──────────────────────────                        for a = ╲╱  -b   
⎪                                   _____                                                
⎪                                  ╱   2                                                 
⎨                     b⋅sin(x) - ╲╱  -b  ⋅cos(x)                                         
⎪                                                                                        
⎪                                ⎛   ⎛x⎞⎞                                                
⎪                             log⎜tan⎜─⎟⎟                                                
⎪                                ⎝   ⎝2⎠⎠                                                
⎪                             ───────────                                   for b = 0    
⎪                                  a                                                     
⎪                                                                                        
⎪     ⎛                  _________⎞      ⎛                  _________⎞                   
⎪     ⎜                 ╱  2    2 ⎟      ⎜                 ╱  2    2 ⎟                   
⎪     ⎜  a      ⎛x⎞   ╲╱  a  + b  ⎟      ⎜  a      ⎛x⎞   ╲╱  a  + b  ⎟                   
⎪  log⎜- ─ + tan⎜─⎟ - ────────────⎟   log⎜- ─ + tan⎜─⎟ + ────────────⎟                   
⎪     ⎝  b      ⎝2⎠        b      ⎠      ⎝  b      ⎝2⎠        b      ⎠                   
⎪- ──────────────────────────────── + ────────────────────────────────      otherwise    
⎪               _________                          _________                             
⎪              ╱  2    2                          ╱  2    2                              
⎩            ╲╱  a  + b                         ╲╱  a  + b          
```

**Comment by bjodah** [comment]
You can run `bug.py` with PYTHONHASHSEED set to reliably trigger the error, e.g. on my machine, the values of 1, 3 and 10 reliably trigger the bug (concluded after re-running the below loop a couple of times):
```console
$ for PHS in {1..13}; do echo $PHS; env PYTHONHASHSEED=$PHS python3 gh23718.py; done
```

**Comment by oscarbenjamin** [comment]
Using `PYTHONHASHSEED=2` avoids the AttributeError so that the integral returns unevaluated with master but evaluates with sympy-1.8. I've bisected when it stopped evaluating to 4acd98876636dae91afdec2799d8d2f8445cf58d from #22539.

The reason for the dependence on PYTHONHASHSEED is that there are loops over sets in several places. This diff seems to be enough to make the failure happen deterministically:
```diff
diff --git a/sympy/integrals/heurisch.py b/sympy/integrals/heurisch.py
index 85361d0..cd45568 100644
--- a/sympy/integrals/heurisch.py
+++ b/sympy/integrals/heurisch.py
@@ -477,6 +477,9 @@ def heurisch(f, x, rewrite=False, hints=None, mappings=None, retries=3,
     for g in set(terms):  # using copy of terms
         terms |= components(dcache.get_diff(g), x)
 
+    # For determinism
+    terms = list(ordered(terms))
+
     # TODO: caching is significant factor for why permutations work at all. Change this.
     V = _symbols('x', len(terms))
 
```

**Comment by oscarbenjamin** [comment]
As for the bug itself that causes the exception we get here:
https://github.com/sympy/sympy/blob/ab414d124bb9899eb9d677e95498c7a021c9bc29/sympy/integrals/heurisch.py#L537
```python
AttributeError: 'NoneType' object has no attribute 'primitive'
> /home/oscar/current/sympy/sympy.git/sympy/integrals/heurisch.py(540)_splitter()
    538 
    539             if _derivation(y) is not S.Zero:
--> 540                 c, q = p.as_poly(y).primitive()
    541 
    542                 q = q.as_expr()

ipdb> p p
(-_x1*b*sqrt(-b**2) + _x2*b**2)/(_x1*b + _x2*sqrt(-b**2))
ipdb> p y
_x1
```
Clearly p is not a polynomial in y. However the context implies that it should be a polynomial. It comes from the frame above:
https://github.com/sympy/sympy/blob/ab414d124bb9899eb9d677e95498c7a021c9bc29/sympy/integrals/heurisch.py#L549
```
> /home/oscar/current/sympy/sympy.git/sympy/integrals/heurisch.py(552)_splitter()
    550                     return (c_split[0], q * c_split[1])
    551 
--> 552                 q_split = _splitter(cancel(q / s))
    553 
    554                 return (c_split[0]*q_split[0]*s, c_split[1]*q_split[1])

ipdb> p q
-_x1*sqrt(-b**2) + _x2*b
ipdb> p s
_x1 + _x2*sqrt(-b**2)/b
```
The problem here is mixing up `sqrt(-b**2)` with `b`. It isn't really possible to do sensible arithmetic with things like that. So where does that come from? A couple of frames up we have:
```
> /home/oscar/current/sympy/sympy.git/sympy/integrals/heurisch.py(177)heurisch_wrapper()
    175     pairs = []
    176     for sub_dict in slns:
--> 177         expr = heurisch(f.subs(sub_dict), x, rewrite, hints, mappings, retries,
    178                         degree_offset, unnecessary_permutations,
    179                         _try_heurisch)

ipdb> p sub_dict
{a: -sqrt(-b**2)}
```
That comes from above:
https://github.com/sympy/sympy/blob/ab414d124bb9899eb9d677e95498c7a021c9bc29/sympy/integrals/heurisch.py#L151-L153
```
ipdb> p res
-log(-a/b + tan(x/2) - sqrt(a**2 + b**2)/b)/sqrt(a**2 + b**2) + log(-a/b + tan(x/2) + sqrt(a**2 + b**2)/b)/sqrt(a**2 + b**2)
ipdb> p denoms(res)
{sqrt(a**2 + b**2), 2, b}
ipdb> p list(denoms(res))[0]
sqrt(a**2 + b**2)
ipdb> p solve(list(denoms(res))[0])
[{a: -sqrt(-b**2)}, {a: sqrt(-b**2)}]
```
Really what we want instead of `+-sqrt(-b**2)` is `+-I*b`:
```python
In [7]: _x1, _x2, b = symbols('_x1, _x2, b')

In [8]: q = -_x1*sqrt(-b**2) + _x2*b

In [9]: s = _x1 + _x2*sqrt(-b**2)/b

In [10]: q/s
Out[10]: 
         _____        
        ╱   2         
- _x1⋅╲╱  -b   + _x2⋅b
──────────────────────
               _____  
              ╱   2   
        _x2⋅╲╱  -b    
  _x1 + ────────────  
             b        

In [11]: cancel(q/s)
Out[11]: 
           _____         
          ╱   2         2
- _x1⋅b⋅╲╱  -b   + _x2⋅b 
─────────────────────────
                  _____  
                 ╱   2   
   _x1⋅b + _x2⋅╲╱  -b    

In [12]: cancel(q/s).subs(sqrt(-b**2), I*b)
Out[12]: 
         2        2
- ⅈ⋅_x1⋅b  + _x2⋅b 
───────────────────
  _x1⋅b + ⅈ⋅_x2⋅b  

In [13]: cancel((q/s).subs(sqrt(-b**2), I*b))
Out[13]: -ⅈ⋅b

In [14]: cancel((q/s).subs(sqrt(-b**2), -I*b))
Out[14]: ⅈ⋅b
```

**Comment by oscarbenjamin** [comment]
> Really what we want instead of `+-sqrt(-b**2)` is `+-I*b`:

It seems that `solve` is inconsistent here:
```python
In [15]: solve(x**2 + y**2)
Out[15]: [{x: -ⅈ⋅y}, {x: ⅈ⋅y}]

In [16]: solve(sqrt(x**2 + y**2))
Out[16]: 
⎡⎧       _____⎫  ⎧      _____⎫⎤
⎢⎨      ╱   2 ⎬  ⎨     ╱   2 ⎬⎥
⎣⎩x: -╲╱  -y  ⎭, ⎩x: ╲╱  -y  ⎭⎦

In [17]: solve([sqrt(x**2 + y**2)])
Out[17]: [{x: -ⅈ⋅y}, {x: ⅈ⋅y}]
```

**Comment by oscarbenjamin** [comment]
This seems to be enough to make things deterministic, prevent the exception and restore the result that was previously calculated in sympy 1.8:
```diff
diff --git a/sympy/integrals/heurisch.py b/sympy/integrals/heurisch.py
index 85361d0..6bd5485 100644
--- a/sympy/integrals/heurisch.py
+++ b/sympy/integrals/heurisch.py
@@ -150,7 +150,7 @@ def heurisch_wrapper(f, x, rewrite=False, hints=None, mappings=None, retries=3,
     slns = []
     for d in denoms(res):
         try:
-            slns += solve(d, dict=True, exclude=(x,))
+            slns += solve([d], dict=True, exclude=(x,))
         except NotImplementedError:
             pass
     if not slns:
@@ -160,7 +160,7 @@ def heurisch_wrapper(f, x, rewrite=False, hints=None, mappings=None, retries=3,
     slns0 = []
     for d in denoms(f):
         try:
-            slns0 += solve(d, dict=True, exclude=(x,))
+            slns0 += solve([d], dict=True, exclude=(x,))
         except NotImplementedError:
             pass
     slns = [s for s in slns if s not in slns0]
@@ -477,6 +477,9 @@ def heurisch(f, x, rewrite=False, hints=None, mappings=None, retries=3,
     for g in set(terms):  # using copy of terms
         terms |= components(dcache.get_diff(g), x)
 
+    # For determinism
+    terms = list(ordered(terms))
+
     # TODO: caching is significant factor for why permutations work at all. Change this.
     V = _symbols('x', len(terms))
```
That gives:
```python
$ python bug.py 
⎧                  ⎛     ⎛   ⎛x⎞    ⎞      ⎛   ⎛x⎞    ⎞⎞                                 
⎪              zoo⋅⎜- log⎜tan⎜─⎟ - 1⎟ + log⎜tan⎜─⎟ + 1⎟⎟                for a = 0 ∧ b = 0
⎪                  ⎝     ⎝   ⎝2⎠    ⎠      ⎝   ⎝2⎠    ⎠⎠                                 
⎪                                                                                        
⎪                                ⎛   ⎛x⎞⎞                                                
⎪                             log⎜tan⎜─⎟⎟                                                
⎪                                ⎝   ⎝2⎠⎠                                                
⎪                             ───────────                                   for b = 0    
⎪                                  a                                                     
⎪                                                                                        
⎪                                -ⅈ                                                      
⎪                       ──────────────────────                            for a = -ⅈ⋅b   
⎪                       -ⅈ⋅b⋅sin(x) + b⋅cos(x)                                           
⎨                                                                                        
⎪                                  ⅈ                                                     
⎪                        ─────────────────────                             for a = ⅈ⋅b   
⎪                        ⅈ⋅b⋅sin(x) + b⋅cos(x)                                           
⎪                                                                                        
⎪     ⎛                  _________⎞      ⎛                  _________⎞                   
⎪     ⎜                 ╱  2    2 ⎟      ⎜                 ╱  2    2 ⎟                   
⎪     ⎜  a      ⎛x⎞   ╲╱  a  + b  ⎟      ⎜  a      ⎛x⎞   ╲╱  a  + b  ⎟                   
⎪  log⎜- ─ + tan⎜─⎟ - ────────────⎟   log⎜- ─ + tan⎜─⎟ + ────────────⎟                   
⎪     ⎝  b      ⎝2⎠        b      ⎠      ⎝  b      ⎝2⎠        b      ⎠                   
⎪- ──────────────────────────────── + ────────────────────────────────      otherwise    
⎪               _________                          _________                             
⎪              ╱  2    2                          ╱  2    2                              
⎩            ╲╱  a  + b                         ╲╱  a  + b              
```
