### ISSUE TITLE
evalf hangs in infinite loop with derivative of sign function

### ISSUE THREAD

**Issue by crasbe** [sympy/sympy#23814]
When working with the sign function I found that evalf() hangs in an infinite loop. The following code can be used to reproduce the problem, it occurs on calling the jMat.evalf() line.

It looks like sympy doesn't know what to do with the derivative of the sign function and evalf/doit are called recursively?

I'm using sympy version 1.10.1 and Python 3.8 on Windows 10.

Best regards,
Chris

```python
from sympy.abc import x
from sympy import sign, Matrix

fVec = Matrix([sp.sign(x)])
xVec = Matrix([[x]])

jMat = fVec.jacobian(xVec)      # Matrix([[Derivative(sign(x), x)]])
jMat = jMat.subs(x, 3)          # Matrix([[Subs(Derivative(sign(x), x), x, 3)]])

jMat.evalf()
```

```
Traceback (most recent call last):
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 479, in getit
    return self._assumptions[fact]
KeyError: 'zero'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 479, in getit
    return self._assumptions[fact]
KeyError: 'finite'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 479, in getit
    return self._assumptions[fact]
KeyError: 'extended_negative'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#29>", line 1, in <module>
    jMat.evalf()
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\matrices\common.py", line 2103, in evalf
    return self.applyfunc(lambda i: i.evalf(n, **options))
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\matrices\common.py", line 2061, in applyfunc
    return self._eval_applyfunc(f)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\matrices\common.py", line 2001, in _eval_applyfunc
    out = self._new(self.rows, self.cols, [f(x) for x in self])
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\matrices\common.py", line 2001, in <listcomp>
    out = self._new(self.rows, self.cols, [f(x) for x in self])
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\matrices\common.py", line 2103, in <lambda>
    return self.applyfunc(lambda i: i.evalf(n, **options))
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\function.py", line 2300, in evalf
    return self.doit().evalf(prec, **options)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\function.py", line 2300, in evalf
    return self.doit().evalf(prec, **options)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\function.py", line 2300, in evalf
    return self.doit().evalf(prec, **options)
  [Previous line repeated 991 more times]
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\function.py", line 2266, in doit
    if D not in e.xreplace({vi: D}).free_symbols:
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\basic.py", line 1183, in xreplace
    value, _ = self._xreplace(rule)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\basic.py", line 1198, in _xreplace
    a_xr = _xreplace(rule)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\basic.py", line 1205, in _xreplace
    return self.func(*args), True
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\function.py", line 476, in __new__
    result = super().__new__(cls, *args, **options)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\function.py", line 288, in __new__
    evaluated = cls.eval(*args)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\functions\elementary\complexes.py", line 362, in eval
    if arg.is_zero:  # it may be an Expr that is zero
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 483, in getit
    return _ask(fact, self)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 556, in _ask
    _ask(pk, obj)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 556, in _ask
    _ask(pk, obj)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 544, in _ask
    a = evaluate(obj)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\expr.py", line 835, in _eval_is_positive
    finite = self.is_finite
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 483, in getit
    return _ask(fact, self)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 556, in _ask
    _ask(pk, obj)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 544, in _ask
    a = evaluate(obj)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\expr.py", line 848, in _eval_is_negative
    extended_negative = self.is_extended_negative
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 483, in getit
    return _ask(fact, self)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 544, in _ask
    a = evaluate(obj)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\expr.py", line 900, in _eval_is_extended_negative
    return self._eval_is_extended_positive_negative(positive=False)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\expr.py", line 855, in _eval_is_extended_positive_negative
    from sympy.polys.numberfields import minimal_polynomial
  File "<frozen importlib._bootstrap>", line 1028, in _handle_fromlist
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by crasbe** [comment]
The code can be simplified even further:

```python
from sympy.abc import x
from sympy import sign, Derivative

Derivative(sign(x)).subs(x, 3).evalf()
```

This reduces the error trace a little bit to the important bits:

```
Traceback (most recent call last):
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 479, in getit
    return self._assumptions[fact]
KeyError: 'zero'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 479, in getit
    return self._assumptions[fact]
KeyError: 'finite'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 479, in getit
    return self._assumptions[fact]
KeyError: 'extended_positive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    Derivative(sign(x)).subs(x, 3).evalf()
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\function.py", line 2300, in evalf
    return self.doit().evalf(prec, **options)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\function.py", line 2300, in evalf
    return self.doit().evalf(prec, **options)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\function.py", line 2300, in evalf
    return self.doit().evalf(prec, **options)
  [Previous line repeated 996 more times]
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\function.py", line 2266, in doit
    if D not in e.xreplace({vi: D}).free_symbols:
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\basic.py", line 1183, in xreplace
    value, _ = self._xreplace(rule)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\basic.py", line 1198, in _xreplace
    a_xr = _xreplace(rule)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\basic.py", line 1205, in _xreplace
    return self.func(*args), True
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\function.py", line 476, in __new__
    result = super().__new__(cls, *args, **options)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\function.py", line 288, in __new__
    evaluated = cls.eval(*args)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\functions\elementary\complexes.py", line 362, in eval
    if arg.is_zero:  # it may be an Expr that is zero
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 483, in getit
    return _ask(fact, self)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 556, in _ask
    _ask(pk, obj)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 556, in _ask
    _ask(pk, obj)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 544, in _ask
    a = evaluate(obj)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\expr.py", line 845, in _eval_is_negative
    finite = self.is_finite
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 483, in getit
    return _ask(fact, self)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 556, in _ask
    _ask(pk, obj)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 544, in _ask
    a = evaluate(obj)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\expr.py", line 838, in _eval_is_positive
    extended_positive = self.is_extended_positive
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 483, in getit
    return _ask(fact, self)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\assumptions.py", line 544, in _ask
    a = evaluate(obj)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\expr.py", line 897, in _eval_is_extended_positive
    return self._eval_is_extended_positive_negative(positive=True)
  File "C:\Users\crasbe\AppData\Roaming\Python\Python38\site-packages\sympy\core\expr.py", line 855, in _eval_is_extended_positive_negative
    from sympy.polys.numberfields import minimal_polynomial
  File "<frozen importlib._bootstrap>", line 1028, in _handle_fromlist
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by oscarbenjamin** [comment]
This looks like the same problem as here: https://github.com/sympy/sympy/issues/11802#issuecomment-561275775

**Comment by oscarbenjamin** [comment]
There was a long discussion in #11802 about adding support for numerical differentiation which sidetracked the main point that the infinite recursion should be fixed even it doesn't make it possible to evaluate the Derivative. The fix for that is straight-forward:
```diff
diff --git a/sympy/core/function.py b/sympy/core/function.py
index 551cf41..fb8b907 100644
--- a/sympy/core/function.py
+++ b/sympy/core/function.py
@@ -2288,7 +2288,12 @@ def doit(self, **hints):
         return rv
 
     def evalf(self, prec=None, **options):
-        return self.doit().evalf(prec, **options)
+        # Try to do the substitution:
+        obj = self.doit()
+        if obj != self:
+            return obj.evalf(prec, **options)
+        else:
+            return self
 
     n = evalf  # type:ignore
```
A more comprehensive fix could just be to remove this `evalf` method altogether since it doesn't even get used recursively anyway (subclasses should not override these methods but rather `_eval_evalf`):
```diff
diff --git a/sympy/core/function.py b/sympy/core/function.py
index 551cf41..8c14d71 100644
--- a/sympy/core/function.py
+++ b/sympy/core/function.py
@@ -2287,11 +2287,6 @@ def doit(self, **hints):
             rv = rv.doit(**hints)
         return rv
 
-    def evalf(self, prec=None, **options):
-        return self.doit().evalf(prec, **options)
-
-    n = evalf  # type:ignore
-
     @property
     def variables(self):
         """The variables to be evaluated"""
```
