### ISSUE TITLE
Matrix should not flatten (big, especially sparse) Matrix at instantiation from Matrix

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#23825]
Instantiation of Matrix tries to create a flat list of elements of the input matrix -- it can run into memory problems for large, sparse matrices:
```python
>>> M = zeros(10**120, 10**120)
>>> M[10**100, 10**50] = 1
>>> s=SparseMatrix(M)
>>> d=Matrix(M)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\sympy\matrices\repmatrix.py", line 329, in __new__

    return cls._new(*args, **kwargs)
  File "sympy\sympy\matrices\repmatrix.py", line 340, in _new
    rows, cols, flat_list = cls._handle_creation_inputs(*args, **kwargs)
  File "sympy\sympy\matrices\matrices.py", line 982, in _handle_
creation_inputs
    return args[0].rows, args[0].cols, args[0].flat()
  File "sympy\sympy\matrices\repmatrix.py", line 155, in flat
    return self._rep.to_sympy().to_list_flat()
  File "sympy\sympy\polys\matrices\domainmatrix.py", line 669, i
n to_list_flat
    return self.rep.to_list_flat()
  File "sympy\sympy\polys\matrices\sdm.py", line 310, in to_list
_flat
    flat = [zero] * (m * n)
OverflowError: cannot fit 'int' into an index-sized integer
```

**Comment by oscarbenjamin** [comment]
The `MutableDenseMatrix._handle_creation_inputs` method is expected to return a flat dense list. It's not clear if it would be backwards compatible to change that but otherwise yes it would be good to clean it up and have it return a sparse representation. Ideally it would return the shape and a dict of dicts representation for the nonzero elements (since that is what will be used internally by `RepMatrix`). Then `_dod_to_DomainMatrix` could be used instead of `_flat_list_to_DomainMatrix`:
https://github.com/sympy/sympy/blob/39de9a2698ad4bb90681c0fdb70b30a78233145f/sympy/matrices/repmatrix.py#L127-L139

**Comment by smichr** [comment]
> is expected to return a flat dense list

At instantiation, before the call to `_handle_creation_inputs` there is a check for ImmutableDenseMatrix and a quick return for that. I suspect a similar thing should be done for SparseMatrix rather than allowing it to go to `_handle_creation_inputs`.

**Comment by oscarbenjamin** [comment]
I'm going to try and unify the `_handle_creation_inputs` methods and have them both return dict of dicts form.
