### ISSUE TITLE
 [Feature request] Make quantity objects json serializable and deserializable

### ISSUE THREAD

**Issue by kishaningithub** [sympy/sympy#23849]
It would be great if SI quantities can be serialized and deserialized from a json string

Note - I am not sure if there is a specification on how to represent quantities in json

### Current behavior

```python
import sympy.physics.units as u
import json

>>>  var = 5 * u.cm
>>> json.dumps(var)
```

### Expected result

Value should be both json serializable and deserialisable 

### Actual result

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Mul is not JSON serializable
```

### Operating system

Mac OS X

**Comment by oscarbenjamin** [comment]
Can you point to other examples of objects (from any library) that are serialisable? Is it common practice for a library to modify somehow the behaviour of `json.dumps`?

**Comment by oscarbenjamin** [comment]
If we were to do this then it would be for all sympy expressions not just quantity.

**Comment by kishaningithub** [comment]
For json.dumps / loads to succeed an custom json encoder/decoder must be implemented by the library and the consumers can use the same to encode/decode

https://realpython.com/lessons/encoding-custom-types-json/

Regarding other libraries i am not fully sure about that in python space (bit new here) but it exists in Java

https://www.meshcloud.io/2017/11/21/jsr-363-units-of-measurement-api-in-practice-json-serialization/

**Comment by sylee957** [comment]
Usually, the JSON representation of trees are not difficult to implement 
(e.g. `to_json(func(args...)) -> {'type': 'func', 'args': [to_json(arg) for arg in args]}`)
And since JSON is purely syntactical representation, everything from grammar is up for a choice, so we may not be able to agree on because there is no right answer for what should be implemented even if there are more applications.

**Comment by oscarbenjamin** [comment]
It would be useful to see an example of another library doing this so that we can see what interface they provide to users or if they have a robust approach for encoding an decoding custom objects mixed up with native objects that json can naturally represent. If you don't need to worry about things like that then you can just encode with `str` and decode with `parse_expr`.

**Comment by asmeurer** [comment]
I can imagine use-cases for exporting a SymPy expression to JSON in a structured way rather than just as a srepr blob that can only be understood by SymPy. For example, this might enable taking a SymPy expression and doing something with it in Javascript, e.g., with an equation editor. However, I agree that without one of these actually being concrete, it's hard to actually design a good JSON schema for expressions. If you only need to serialize and deserialize SymPy expressions simply using `srepr` should work.

Also, it's not even clear to me from [the docs](https://docs.python.org/3/library/json.html), but is it possible for custom objects to register themselves with `json` somehow? The only way I see is to define your own JSONEncoder subclass, but is there anything SymPy can do so that `json.dumps(sympy_expression)` automatically works?

**Comment by westurner** [comment]
To save output as a test fixture today:
```python
sy.Rational._repr_original = sy.Rational.__repr__

def Rational_repr(self):
    return f"""sy.Rational({self.numerator}, {self.denominator})"""
    # TODO: pi, sqrt, zoo -> sy.pi, sy.sqrt, sy.zoo


sy.Rational.__repr__ = Rational_repr
sy.Rational.__str__ = Rational_repr

n = sy.Rational(1,2)
n.__str__(), n.__repr__()
```

And then:
```python
import sympy
sympy.core.mul.Mul.__repr__??
sympy.printing.str.StrPrinter??
```

- https://github.com/sympy/sympy/blob/master/sympy/printing/printer.py#L235
- https://docs.sympy.org/latest/modules/printing.html

With just JSON primitives and RDFS, JSON-LD enables serialization and deserialization of complex types with JSON as the representation.

Mustn't there be schema to store complex sympy expression and basic type objects in JSON, and is there anything more universal than [W3C:] JSON-LD @context, RDFS, and also SHACL?
