### ISSUE TITLE
Integral of exp(-1/x)

### ISSUE THREAD

**Issue by dtlanghoff** [sympy/sympy#23846]
The floating-point approximation of $\displaystyle\int_0^t \mathrm{e}^{-1/x} \operatorname{d}\\\!x$ is given with a imaginary term even though the function is real-valued.

```
>>> integrate(exp(-1/x), (x, 0, t))
t*exp(-1/t) + Ei(exp_polar(I*pi)/t)
>>> _.n(subs={t: 1})
0.148495506775922 + 3.14159265358979*I
```

Also, the definite integral from anything negative to anything non-negative should not converge.

```
>>> integrate(exp(-1/x), (x, -1, 0))
E - Ei(-exp_polar(I*pi))
>>> _.n()
0.823164012103109
```

Version: SymPy 1.10.1 (Python 3.10.4-64-bit)

**Comment by cyy31459265** [comment]
Hey @dtlanghoff 

I've seen a similar error before. Just wondering how you defined `x` and `t` before calling `integrate`?

Cheers,
Eve

**Comment by dtlanghoff** [comment]
```python
import sympy
sympy.init_session(pretty_print=False)
```

**Comment by Avedeva** [comment]
```
import sympy as sp

x,t = sp.symbols("x,t")

sp.integrate(sp.exp(-1/x), (x, 0, t))
``` 
 
ran this code locally and getting this error

 
```
Traceback (most recent call last):
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\series\gruntz.py", line 520, in mrv_leadterm
    lt = f.leadterm(w, logx=logw)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\expr.py", line 3558, in leadterm
    l = self.as_leading_term(x, logx=logx, cdir=cdir)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\expr.py", line 3521, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\mul.py", line 2054, in _eval_as_leading_term
    return self.func(*[t.as_leading_term(x, logx=logx, cdir=cdir) for t in self.args])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\expr.py", line 3521, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\add.py", line 1048, in _eval_as_leading_term
    if not min or order not in min:
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\series\order.py", line 456, in __contains__
    result = self.contains(other)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\series\order.py", line 428, in contains
    l = Limit(ratio, s, point).doit(heuristics=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\series\limits.py", line 372, in doit
    raise NotImplementedError("Not sure of sign of %s" % ex)
NotImplementedError: Not sure of sign of -1 - exp_polar(-I*pi)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\mul.py", line 1980, in _eval_nseries
    coeff, exp = t.leadterm(x)
                 ^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\expr.py", line 3558, in leadterm
    l = self.as_leading_term(x, logx=logx, cdir=cdir)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\expr.py", line 3521, in as_leading_term
    obj = self._eval_as_leading_term(x, logx=logx, cdir=cdir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\add.py", line 1048, in _eval_as_leading_term
    if not min or order not in min:
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\series\order.py", line 456, in __contains__
    result = self.contains(other)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\series\order.py", line 428, in contains
    l = Limit(ratio, s, point).doit(heuristics=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\series\limits.py", line 372, in doit
    raise NotImplementedError("Not sure of sign of %s" % ex)
NotImplementedError: Not sure of sign of -1 - exp_polar(-I*pi)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\suees\skill\rough.py", line 5, in <module>
    sp.integrate(sp.exp(-1/x), (x, 0, t))
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\integrals\integrals.py", line 1575, in integrate
    return integral.doit(**doit_flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\integrals\integrals.py", line 717, in doit
    evalued = Add(*others)._eval_interval(x, a, b)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\expr.py", line 982, in _eval_interval
    A = _eval_endpoint(left=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\expr.py", line 971, in _eval_endpoint
    C = limit(self, x, c, "+" if left else "-")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\series\limits.py", line 66, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\series\limits.py", line 384, in doit
    r = gruntz(e, z, z0, dir)
        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\series\gruntz.py", line 695, in gruntz
    r = limitinf(e0, z)
        ^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\series\gruntz.py", line 452, in limitinf
    c0, e0 = mrv_leadterm(e, x)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\series\gruntz.py", line 526, in mrv_leadterm
    _series = f._eval_nseries(w, n=n0+incr, logx=logw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\mul.py", line 2004, in _eval_nseries
    facs = [t.nseries(x, n=ceiling(n-n0), logx=logx, cdir=cdir) for t in self.args]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\expr.py", line 3466, in nseries
    return self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\core\power.py", line 1533, in _eval_nseries
    res = exp(e*log(b))._eval_nseries(x, n=n, logx=logx, cdir=cdir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\functions\elementary\exponential.py", line 511, in _eval_nseries
    exp_series = exp(t)._taylor(t, nterms)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\suees\AppData\Local\Programs\Python\Python312\Lib\site-packages\sympy\functions\elementary\exponential.py", line 531, in _taylor
    for i in range(n):
             ^^^^^^^^
TypeError: 'Add' object cannot be interpreted as an integer

```


it is way different from the mentioned issue am i doing it wrong or what??

**Comment by Peter230655** [comment]
Strange:
I typed in this code:
```
import sympy as sm
x ,t = sm.symbols("x t")
sm.integrate(sm.exp(-1/x), (x, 0, t))
```
and got this result:

<img width="190" height="88" alt="Image" src="https://github.com/user-attachments/assets/d7d248a4-fc2e-4e48-931c-be8db1ef8f09" />

When I differentiated the result w.r.t. t I got the original function as it should be (except instead of -1 it gave e^(i*pi) )

**Comment by Avedeva** [comment]
@Peter230655  what is your sympy version ? due to that it is happening

**Comment by Peter230655** [comment]
1.13.3 
with 1.14.0 I also get this error.

**Comment by Avedeva** [comment]
> 1.13.3

mine is 1.14.0

**Comment by Avedeva** [comment]
can anyone please clarify me why is this. happening.

**Comment by Peter230655** [comment]
I have no idea.

**Comment by oscarbenjamin** [comment]
There is a bug that has been introduced since this issue was opened. Someone could find when it happened using `git bisect`.
