### ISSUE TITLE
InconsistentAssumptions from time to time

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#23874]
```
    from sympy import parse_expr, abc, Poly
    s = '(-1545008200379509166138595519225835015772483305590370912537615046383589187184769699472626050621482229582468531714054191397577498144237*x**2*sqrt(9652701250000017396208892402806395371977754899142349065641 - 98248161560407925000000000000*sqrt(9652701250000017396208892402806395371977754899142349065641))/10000000000000000 + 786278427932496324659119783310193643829610387502221670766582819203837983534395522728787220289239383907006865726740881*x**2*sqrt(93174641421751898340814641915672220313995893850347964694825383381954059545398337275359020289239383907006865726740881 - 948360151904353237302948049395927842340721558889133042106244655702561604925000000000000*sqrt(9652701250000017396208892402806395371977754899142349065641))/500000000000000000000000000000 - 8094710528451550385756075402603176656017180055288333311199733772208168320454555839673267757118626461535570964881427922679134926079211260820099326909835299597*sqrt(2)*x/488281250000 + 84367823778950839947902152795046907568142790217092619518107417797916060068049775302649030797738219314406419347863466870258439498251*sqrt(19305402500000034792417784805612790743955509798284698131282)*x/500000000000000 - 40165122290766033307136077686916998870611934766283491426664232769964381657834820433061160018804840457162451219207255832009841039203*y**2*sqrt(9652701250000017396208892402806395371977754899142349065641 - 98248161560407925000000000000*sqrt(9652701250000017396208892402806395371977754899142349065641))/5000000000000000 + 40881296558481137932602647984860498340959074902717124830341309152611638137388293423934995960760616092993134273259119*y**2*sqrt(93174641421751898340814641915672220313995893850347964694825383381954059545398337275359020289239383907006865726740881 - 948360151904353237302948049395927842340721558889133042106244655702561604925000000000000*sqrt(9652701250000017396208892402806395371977754899142349065641))/500000000000000000000000000000 - 7649873546189134677859370703996521850389328861884736779652594235414343390708959138591189912098461358894580459695235856433331624538832709784286391800849193764879*sqrt(2)*y/500000000000000 + 76037856752739721098667043112782409873630417479819819520481592575757012344453977963384156280717063618092274092019224840586191507*sqrt(19305402500000034792417784805612790743955509798284698131282)*y/488281250000 - 2302904437380019919391574689587616752987188230276169294670018145303263794104053834937340947062835153161395423325531903699*sqrt(9652701250000017396208892402806395371977754899142349065641 - 98248161560407925000000000000*sqrt(9652701250000017396208892402806395371977754899142349065641))/10000 + 2343966951446799461317966398886928487742421636233609357652345718275838447049472500000000*sqrt(93174641421751898340814641915672220313995893850347964694825383381954059545398337275359020289239383907006865726740881 - 948360151904353237302948049395927842340721558889133042106244655702561604925000000000000*sqrt(9652701250000017396208892402806395371977754899142349065641)))/((-372698565687007593363258567662666572744325656299752272968120755025613172698503614652426112164239383907006865726740881 + 3793440607617412949211792197583635681732354161245524126318733967107684814775000000000000*sqrt(9652701250000017396208892402806395371977754899142349065641))*sqrt(9652701250000017396208892402806395371977754899142349065641 - 98248161560407925000000000000*sqrt(9652701250000017396208892402806395371977754899142349065641)))'
    Poly(parse_expr(s), abc.x,abc.y)
```

```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 462, in getit
    return self._assumptions[fact]
KeyError: 'zero'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 462, in getit
    return self._assumptions[fact]
KeyError: 'extended_real'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 462, in getit
    return self._assumptions[fact]
KeyError: 'complex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 462, in getit
    return self._assumptions[fact]
KeyError: 'positive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 462, in getit
    return self._assumptions[fact]
KeyError: 'extended_positive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/_print_helpers.py", line 29, in __str__
    return sstr(self, order=None)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/printing/printer.py", line 372, in __call__
    return self.__wrapped__(*args, **kwargs)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/printing/str.py", line 987, in sstr
    s = p.doprint(expr)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/printing/printer.py", line 292, in doprint
    return self._str(self._print(expr))
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/printing/str.py", line 524, in _print_Poly
    for monom, coeff in expr.terms():
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/polys/polytools.py", line 914, in terms
    return [(m, f.rep.dom.to_sympy(c)) for m, c in f.rep.terms(order=order)]
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/polys/polyclasses.py", line 313, in terms
    return dmp_list_terms(f.rep, f.lev, f.dom, order=order)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/polys/densebasic.py", line 1734, in dmp_list_terms
    terms = _rec_list_terms(f, u, ())
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/polys/densebasic.py", line 1708, in _rec_list_terms
    terms.extend(_rec_list_terms(c, w, monom + (d - i,)))
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/polys/densebasic.py", line 1700, in _rec_list_terms
    if not c:
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/polys/domains/expressiondomain.py", line 136, in __bool__
    return not f.ex.is_zero
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 466, in getit
    return _ask(fact, self)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 509, in _ask
    a = evaluate(obj)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/add.py", line 691, in _eval_is_zero
    if a.is_extended_real:
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 466, in getit
    return _ask(fact, self)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 509, in _ask
    a = evaluate(obj)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/mul.py", line 1410, in _eval_is_extended_real
    return self._eval_real_imag(True)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/mul.py", line 1417, in _eval_real_imag
    if (t.is_complex or t.is_infinite) is False and t.is_extended_real is False:
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 466, in getit
    return _ask(fact, self)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 521, in _ask
    _ask(pk, obj)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 521, in _ask
    _ask(pk, obj)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 521, in _ask
    _ask(pk, obj)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 509, in _ask
    a = evaluate(obj)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/power.py", line 792, in _eval_is_composite
    ((self.base - 1).is_positive and (self.exp - 1).is_positive or
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 466, in getit
    return _ask(fact, self)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 509, in _ask
    a = evaluate(obj)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/expr.py", line 853, in _eval_is_positive
    extended_positive = self.is_extended_positive
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 466, in getit
    return _ask(fact, self)
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/assumptions.py", line 511, in _ask
    assumptions.deduce_all_facts(((fact, a),))
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/facts.py", line 520, in deduce_all_facts
    if not self._tell(k, v) or v is None:
  File "/home/user/.virtualenvs/project/lib/python3.6/site-packages/sympy/core/facts.py", line 491, in _tell
    raise InconsistentAssumptions(self, k, v)
sympy.core.facts.InconsistentAssumptions: {
	algebraic: True,
	commutative: True,
	complex: True,
	even: False,
	extended_negative: False,
	extended_nonnegative: True,
	extended_nonpositive: False,
	extended_nonzero: True,
	extended_positive: True,
	extended_real: True,
	finite: True,
	hermitian: True,
	imaginary: False,
	infinite: False,
	integer: True,
	irrational: False,
	negative: False,
	noninteger: False,
	nonnegative: True,
	nonpositive: False,
	nonzero: True,
	odd: True,
	positive: True,
	rational: True,
	real: True,
	transcendental: False,
	zero: False}, extended_positive=False

```

**Comment by oscarbenjamin** [comment]
The problem is to do with this:
```python
from sympy import *

e = -3726985656870075933632585676626665727443256562997522729681207550256131726985036146524261121642393839070068657267408810000000000000000*sqrt(9652701250000017396208892402806395371977754899142349065641 - 98248161560407925000000000000*sqrt(9652701250000017396208892402806395371977754899142349065641)) + 1 + 37934406076174129492117921975836356817323541612455241263187339671076848147750000000000000000000000000000*sqrt(9652701250000017396208892402806395371977754899142349065641)*sqrt(9652701250000017396208892402806395371977754899142349065641 - 98248161560407925000000000000*sqrt(9652701250000017396208892402806395371977754899142349065641))

pprint(e)
print(e.n())
print(e._eval_is_extended_negative())
```
The output is:
```
                                                                                                       
- 37269856568700759336325856766266657274432565629975227296812075502561317269850361465242611216423938390

                                   ____________________________________________________________________
70068657267408810000000000000000⋅╲╱ 9652701250000017396208892402806395371977754899142349065641 - 982481

____________________________________________________________________________________                   
61560407925000000000000⋅√9652701250000017396208892402806395371977754899142349065641  + 1 + 379344060761

                                                                                                       
74129492117921975836356817323541612455241263187339671076848147750000000000000000000000000000⋅√965270125

                                                    ___________________________________________________
0000017396208892402806395371977754899142349065641⋅╲╱ 96527012500000173962088924028063953719777548991423

_____________________________________________________________________________________________________
49065641 - 98248161560407925000000000000⋅√9652701250000017396208892402806395371977754899142349065641 
-1.16197776983864e+51
False
```
So numerical evaluation shows that this expression is negative bug `_eval_is_extended_negative` returns False.

**Comment by oscarbenjamin** [comment]
Evaluating this at low precision gives a spurious imaginary part that confuses `_eval_is_extended_negative`.
```python
In [3]: e.evalf(2)
Out[3]: 1.0 - 6.7e+148⋅ⅈ

In [4]: e.evalf(3)
Out[4]: 8.39e+147 - 3.36e+148⋅ⅈ

In [5]: e.evalf(4)
Out[5]: -1.162e+51

In [6]: e.evalf(5)
Out[6]: -1.1620e+51

In [7]: e.evalf()
Out[7]: -1.16197776983864e+51
```
