### ISSUE TITLE
int/str conversions broken by latest CPython bugfix releases

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#24033]
Python bugfix releases have just been issued that break converting large integers to and from strings:
```python
>>> import math
>>> n = math.factorial(1559)
>>> n
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Exceeds the limit (4300) for integer string conversion
```
The limit is set to 4300 decimal digits.

I spotted this after it was reported in Sage which is also affected:
https://trac.sagemath.org/ticket/34506

New releases of CPython 3.10.7, 3.9.14, 3.8.14, 3.7.14 were pushed out with this change yesterday and I think it will also feature in 3.11.0rc3. Note that it is too soon for these to hit SymPy CI yet (there is usually a few days delay before `actions/setup-python` picks them up):
https://mail.python.org/archives/list/python-dev@python.org/message/B25APD6FF27NJWKTEGAFRUDNSVVAFIHQ/

You can see the release note and docs for the change here:
https://docs.python.org/release/3.10.7/whatsnew/3.10.html#notable-security-feature-in-3-10-7
https://docs.python.org/release/3.10.7/library/stdtypes.html#int-max-str-digits

Particular problems about the way that this was done:

1. The change was pushed out in bug fix releases for all supported Python versions within a few days of being committed to there was no time for any downstream CI etc to pick it up.
2. Problems with this change were pointed out in the issue https://github.com/python/cpython/issues/95778 within days of commit but the discussion was just shut down.
3. No alternate API has been provided so there is no function that can be used in place of `str/int` for code that really does want to work with large integers.
4. The limit can be configured by environment variable, by command line, or by setting a global flag in the sys module but *none* of those is appropriate for a **library** like SymPy.
5. This is a significant backwards compatibility break being made in bugfix releases. Apparently the backwards compatibility policy (PEP 387) throws all consideration of mitigation out of the window if something is considered "insecure" and is granted an exception by the steering council.

As for what SymPy is supposed to do honestly I don't know. Nothing seems to have been provided that can even be used as a backwards compatibility shim like:
```python
try:
    from stdlib import old_string_to_int as parse_int
except ImportError:
    parse_int = int
```
Anywhere in the codebase that uses `int(string)` or `str(integer)` is now potentially a bug and no function has been provided that can be used in replacement. Likewise for users if sympy returns an `int` then there's no general way sympy can stop something like `print(num)` from failing.

The CPython issue was shut down but the suggestion was to discuss this at discuss.python.org so I'll do that.

**Comment by smichr** [comment]
Can we write a compatibility.[int|str] function that falls back to a custom version if the size limit is exceeded?

**Comment by smichr** [comment]
> The CPython issue was shut down but the suggestion was to discuss this at discuss.python.org so I'll do that.

Thanks for following up on this. The criticism raised there raised some very good points (as do you).

**Comment by oscarbenjamin** [comment]
I opened a mailing list discussion:
https://discuss.python.org/t/int-str-conversions-broken-in-latest-python-bugfix-releases/18889

**Comment by nascheme** [comment]
My PR is much too rough to be considered for merging and the performance is not yet good enough but this could be a way to solve the problem: https://github.com/python/cpython/pull/96673

Credit for the faster functions go to Tim and Mark.  I just did a fairly simple thing of "wiring" them into the CPython int object internals.

**Comment by bjodah** [comment]
I have a feeling that we might have to inspect `sys.version_info` at import time of sympy, and either alter global state of the whole python process (which might get arbitrarily ugly, replacing global functions under the feet of the user), or emit warnings with a recommendation to use anther python version for now (with an URL to the discussion on discuss.python.org).

**Comment by asmeurer** [comment]
I think we should do nothing. It's ridiculous that the core Python team thinks it's OK to make such a breaking change as this, especially in a PATCH release. When people run into this in SymPy, they should be reporting it upstream to Python, because that's where the issue really is.

Alternatively, we should set `set_int_max_str_digits(10**10000)` in `__init__.py`. Will that break any other library that imports sympy? Yes. But that's again just because of the limitations of how they decided to implement this.

**Comment by asmeurer** [comment]
I wrote that wrong. It won't "break" other libraries (if anything, it will fix them). What it will do is completely disable the whole point of the security fix. If enough libraries do this, it will effectively be as if the default limit is 0 (which is what IMO should have been done in the first place).

**Comment by asmeurer** [comment]
I have some technical questions:

- Do any tests in the test suite fail now that this limit is implemented?
- Are there places in the SymPy codebase that use `str(int)` or `int(str)`, other than in printing and parsing? 

If it's just those two, it really it just an end-user problem. It is unfortunate that every instance of the error will look like an error from SymPy. It would be nice if the error message directly mentioned the `sys.set_int_max_str_digits` function as a way to increase the limit.

If we are using these elsewhere, like in some algorithm, we should reconsider that. Unless an algorithm is directly manipulating the base-10 digits of a number, it shouldn't be using the string form of an integer. Things like the number of digits can be computed more efficiently with the logarithm. I'm not aware of anything off the top of my head that ought to be using these, but there probably is something I don't know about that has a good reason to use it.

**Comment by oscarbenjamin** [comment]
I haven't run the full test suite myself so I'm not sure if anything fails. Also this hasn't pulled through to CI yet because `actions/setup-python` still picks up the previous CPython releases (e.g. 3.10.6 rather than 3.10.7). We should also test what happens when the limit is set to its lowest value (640).

At least `import sympy` works which was not necessarily guaranteed because this problem also affects decimal literals that are literally in the code:
```python
>>> with open('temp.py', 'w') as fout:
...     fout.write('x = 1' + '0'*10000)
... 
10005
>>> import temp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "temp.py", line 1
    000000000000000
SyntaxError: Exceeds the limit (4300) for integer string conversion: value has 10001 digits - Consider hexadecimal for huge integer literals to avoid decimal conversion limits.
```
If the test suite does pass then that indicates that we might not be testing large integers very well. Probably all of our input/output tests don't use particularly large examples (because there has not previously been a need to distinguish those). It's possible that this is mostly something that will show up for users in an interactive context or when serialising and deserialising large expressions. SymPy's intermediate calculations won't convert integers to strings.

Note that if you have gmpy2 installed then that will be used for many things (e.g. ZZ and QQ in polys) but Python's int still gets used in `Integer` and `Rational` in any case. Same goes for mpmath which uses gmpy2 if installed but otherwise int so to test this properly you need to make sure you don't have gmpy2 installed.

**Comment by smichr** [comment]
I searched the repo for `str(` and got 1224 hits, all in files related to tests.

**Comment by smichr** [comment]
I don't find `''.join` at all. So if we don't create strings anywhere and we don't allow strings as args, then the only place we would do `int(str)` is in `sympify`, right?

**Comment by asmeurer** [comment]
`str()` could take many forms, `"%s" % x`, `f"{x}"`, `{0}.format(x)`, `print(x)`, `repr(x)`, etc.
I'm not sure what the lowest the limit can be set to, but the best way to test this would be to set it to the lowest value and run the tests. Or otherwise somehow monkeypatch `int.__str__` (which might only be doable by recompiling CPython). 

If there are places outside of the tests and printers that compute string forms of expressions, we should remove them, even ignoring this, because it can be slow to do that. For example, sometimes the string form of an expression is put in an error message, but this is a bad idea (at least without some sort of limit on how big of expressions we print), because expressions can be very large and this makes the error messages both slow and unwieldy. An `sstr(expr, limit=n)` flag that only prints the first `n` characters of `expr` and an ellipsis if it is longer would be useful. 

I don't think there are quite as many alternate ways of doing the reverse, `int(x)`. The only one I can think of that we do in a couple of places is `eval`/`exec` (e.g., in `lambdify`).

**Comment by asmeurer** [comment]
I ran the tests in Python 3.11 with 

```
sys.set_int_max_str_digits(640)
test(subprocess=False)
```

There was only one test failure, which is that sympy.core.tests.test_complex could not be imported because it has integer literals longer than 640 digits. They are not longer than the 4300 digits, however. 

640 is the smallest limit you can set. Really, I'm not surprised there were not test failures because it would require the tests themselves to actually include integers larger than $10^640$, which they don't (except in that one case). So to really test this, we need to patch the interpreter to flag every int(str) or str(int) call in the codebase. Some of them will be harmless, i.e., it will be effectively impossible for them to involve large integers. For example, the error in https://github.com/sympy/sympy/pull/24161 would be flagged, but it would be impossible for an explicit matrix to have $10^4300$ entries. Others will be in obvious places, like the printer tests. But I'm interested in which instances would show up in other unexpected places in the code, which could involve arbitrary expressions, and hence easily be triggered.

I'm not aware of any user complaints about this yet. Please let me know if there have been any.

**Comment by asmeurer** [comment]
I suppose we should also check mpmath. It makes extensive use of large integers, although I expect it tries to avoid converting them to and from strings.
