### ISSUE TITLE
sympy/core/tests/test_numbers.py:test_numpy_to_float fails on PPC64 architecture ("double-double" ABI)

### ISSUE THREAD

**Issue by chatcannon** [sympy/sympy#24071]
```
In [3]: sympy.test("sympy/core/tests/test_numbers.py")
=================================================================== test process starts ====================================================================
executable:         /usr/bin/python3.10  (3.10.6-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
numpy:              1.22.4
random seed:        17441784
hash randomization: on (PYTHONHASHSEED=2262671868)

sympy/core/tests/test_numbers.py[107] ..........................................................................f......................F.........     [FAIL]

____________________________________________________________________________________________________________________________________________________________
___________________________________________________ sympy/core/tests/test_numbers.py:test_numpy_to_float ___________________________________________________
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sympy/core/tests/test_numbers.py", line 2142, in test_numpy_to_float
    check_prec_and_relerr(x, Rational(2, 3))
  File "/usr/lib/python3.10/site-packages/sympy/core/tests/test_numbers.py", line 2135, in check_prec_and_relerr
    assert abs((x - y)/y) < 2**(-(prec + 1))
AssertionError

======================================== tests finished: 105 passed, 1 failed, 1 expected to fail, in 4.11 seconds =========================================
DO *NOT* COMMIT!
Out[3]: False
```

**Comment by chatcannon** [comment]
Running the test with `pdb=True` and investigating further:

```
core/tests/test_numbers.py(2135)check_prec_and_relerr()
-> assert abs((x - y)/y) < 2**(-(prec + 1))
(Pdb) abs((x - y)/y)
1.848892746611746418933738824882e-32
(Pdb) 2**(-(prec + 1))
6.162975822039155e-33
(Pdb) abs((x - y)/y) / 2**(-(prec + 1))
3.000000000000000000000000000000
```

**Comment by chatcannon** [comment]
With "double-double" arithmetic, the relationship between the number of bits in the mantissa (`np.finfo(npval).nmant`) and the precision is not the same as for IEEE 754 quadruple precision arithmetic.

**Comment by chatcannon** [comment]
Possibly related numpy issue: https://github.com/numpy/numpy/issues/21094

**Comment by chatcannon** [comment]
There doesn't seem to be an official way to detect when `np.longdouble` is using "double-double" format. Perhaps it could be done by checking `np.finfo().nmant` which is 105 for "double-double" and should be 112 for IEEE754 quad precision.

**Comment by oscarbenjamin** [comment]
What should be precision be if not `nmant + 1`?

**Comment by chatcannon** [comment]
> What should be precision be if not `nmant + 1`?

In this case, `nmant - 1` would get the test to pass. I will do some more tests to see if that holds for other rationals.

**Comment by oscarbenjamin** [comment]
Maybe the check should use something other than `nmant` like perhaps `eps`:
```python
In [20]: np.finfo(np.float128).eps
Out[20]: 1.084202172485504434e-19

In [21]: 2 ** -np.finfo(np.float128).nmant
Out[21]: 1.0842021724855044e-19
```

**Comment by chatcannon** [comment]
Here is the full `np.finfo` contents for a "double double" architecture:
```
In [58]: np.finfo(np.longdouble(1)).__dict__
Out[58]: 
{'dtype': dtype('float128'),
 'precision': 31,
 'iexp': 11,
 'maxexp': 1024,
 'minexp': -1022,
 'negep': -106,
 'machep': -105,
 'resolution': 1e-31,
 'epsneg': 1.23259516440783094595582588325435e-32,
 'smallest_subnormal': 5e-324,
 'bits': 128,
 'max': 1.79769313486231580793728971405301e+308,
 'min': -1.79769313486231580793728971405301e+308,
 'eps': 2.4651903288156618919116517665087e-32,
 'nexp': 11,
 'nmant': 105,
 '_machar': <numpy.core.getlimits.MachArLike at 0x3fff99b69a50>,
 '_str_tiny': 'nan',
 '_str_max': '1.79769313486231580793728971405301e+308',
 '_str_epsneg': '1.23259516440783094595582588325435e-32',
 '_str_eps': '2.4651903288156618919116517665087e-32',
 '_str_resolution': '1e-31',
 '_str_smallest_normal': 'nan',
 '_str_smallest_subnormal': '5e-324'}
```

**Comment by chatcannon** [comment]
`eps` is equal to `2**-nmant` just like on your architecture.

The test expects the relative error to be less than `2**-(nmant + 2)`, and this seems to work for IEE754 floats, but not for "double double"

**Comment by chatcannon** [comment]
Asserting the relative error to be less than `eps` passes for `Rational(2, 3)`. Using `hypothesis` I was able to discover an example `Rational(512776084643583063, 256388042321791534)` which has a relative error just greater than `eps`. There were no examples with relative error greater than `resolution`.

**Comment by oscarbenjamin** [comment]
I'm happy to change the sympy tests for this (e.g. to use `resolution`) but I do wonder if any of this should be considered a numpy bug rather than a sympy one.

**Comment by oscarbenjamin** [comment]
What is the exact value that you get for `np.longdouble(2)/3`?
```python
In [5]: (np.longdouble(2)/3).as_integer_ratio()
Out[5]: (12297829382473034411, 18446744073709551616)
```
Also what do you get when you convert that to a Float:
```python
In [6]: Float(np.longdouble(2)/3)._mpf_
Out[6]: (0, mpz(12297829382473034411), -64, 64)
```

**Comment by chatcannon** [comment]
```python
In [2]: (np.longdouble(2)/3).as_integer_ratio()
Out[2]: (108172851219475575594385340192085, 162259276829213363391578010288128)
```

```python
In [3]: Float(np.longdouble(2)/3)._mpf_
Out[3]: (0, 27043212804868893898596335048021, -105, 105)
```

**Comment by chatcannon** [comment]
> I'm happy to change the sympy tests for this (e.g. to use `resolution`) but I do wonder if any of this should be considered a numpy bug rather than a sympy one.

I think the main problem is that "double double" arithmetic doesn't match the expectations of the rest of the code. The `nmant` number in numpy is correct, so far as I can tell, but the conversion from that bit count to a value for `eps` and `resolution` is possibly wrong. (In fact, if `eps` is defined as the difference between `1.0` and the smallest representable number greater than `1.0` then the `eps` value is definitely wrong, as with "double double" that definition should make both `eps` and `negeps` equal to the smallest number representable as a double.)

**Comment by bjodah** [comment]
>/.../ (In fact, if `eps` is defined as the difference between `1.0` and the smallest representable number greater than `1.0` then the `eps` value is definitely wrong, as with "double double" that definition should make both `eps` and `negeps` equal to the smallest number representable as a double.)

Most implementations of double-double arithmetic that I've seen do not allow for a "gap" between the mantissa bits of the "low" and "high" value, i.e. the exponent of the "low" value are useless bits. But I'm not familiar with this IBM version of double-double arithmetic, do you happen to have a link to a reference document?

**Comment by chatcannon** [comment]
> The Float that you show has a slightly different value though:

So if the sympy `Float` object has a value that is not the same as the numpy `longdouble` object it was derived from, that is actually a bug in sympy and not just in the tests?

**Comment by chatcannon** [comment]
> Most implementations of double-double arithmetic that I've seen do not allow for a "gap" between the mantissa bits of the "low" and "high" value

I was not aware of this. Even then, `epsneg` should still be the same as `eps` rather than half of it.

**Comment by oscarbenjamin** [comment]
> So if the sympy `Float` object has a value that is not the same as the numpy `longdouble` object it was derived from, that is actually a bug in sympy and not just in the tests?

Yes, I think so. It should be possible for the Float to be exactly equal to the longdouble.

**Comment by oscarbenjamin** [comment]
Looks like it's handled here:
https://github.com/sympy/sympy/blob/d9df68a315460e3c11a62015f89d82c1fb8386c3/sympy/core/sympify.py#L90-L96
Maybe there's a problem with numpy's `str` or maybe there's a problem with sympy's string parsing code.

**Comment by bjodah** [comment]
> Even then, `epsneg` should still be the same as eps rather than half of it.

Usually not? Typically `1.0 - epsneg == nextafter(1.0, -1)` & `1.0 + eps == nextafter(1.0, 1)` & `eps == 2*epsneg`, but perhaps this doesn't hold for this double-double implementation?

**Comment by oscarbenjamin** [comment]
Maybe it should just be changed to use `as_integer_ratio` rather than `str`. I had thought that `as_integer_ratio` might be slow especially for large/small long doubles but it seems that the opposite is true at least on this system:
```python
In [34]: fmin = np.finfo(np.longdouble).min

In [35]: fmax = np.finfo(np.longdouble).max

In [36]: %timeit fmin.as_integer_ratio()
944 ns ± 5.53 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [37]: %timeit fmax.as_integer_ratio()
964 ns ± 10.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [38]: %timeit str(fmin)
87.6 µs ± 348 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [39]: %timeit str(fmax)
87.9 µs ± 489 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
I think that the way to construct a `float` from `as_integer_ratio` and `prec` is:
```python
def to_Float(f, prec):
    num, den = f.as_integer_ratio()
    mpf_tuple = (int(num < 0), abs(num), 1-den.bit_length(), num.bit_length())
    f = Float(mpf_tuple, prec)
    f._prec = prec
    return f

def np_to_Float(f):
    res = to_Float(f, np.finfo(f).nmant + 1)
    assert res._mpf_ == Float(f)._mpf_
    assert res._prec == Float(f)._prec
    return res
```
This is more accurate and more efficient than going through str because we can avoid converting binary to decimal and back again.

@chatcannon can you confirm if that works with `np.longdouble` on your architecture?

**Comment by chatcannon** [comment]
The difference isn't as big, but `.as_integer_ratio()` is still faster:
```python
In [4]: %timeit fmin.as_integer_ratio()
9.31 µs ± 91.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [5]: %timeit fmax.as_integer_ratio()
7.05 µs ± 470 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [6]: %timeit str(fmin)
15.7 µs ± 293 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [7]: %timeit str(fmax)
17.1 µs ± 329 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

**Comment by oscarbenjamin** [comment]
The speed is only a secondary issue here. The first question is accuracy. The questions (that I can't answer directly myself without access to your hardware) are:

1. Whether constructing a Float from `as_integer_ratio` as shown above gives the correct value so that the Float has the *exact* same value as the longdouble.
2. Whether having the Float with the correct value means that the test passes.
3. What str gives for the longdouble (i.e. what the string `a` is that is currently parsed by Float in the highlighted code above) and whether that is correct or should be improved in numpy.
4. If the string is correct whether Float is correctly parsing that string (I need to know exactly what string it is to check this).

What happens with this code on your system:
```python
In [1]: d = np.longdouble(2)/3

In [2]: d
Out[2]: 0.6666666666666666667

In [3]: prec = np.finfo(d).nmant + 1

In [4]: prec
Out[4]: 64

In [5]: x = Float(d)

In [6]: y = Float(Rational(2, 3), precision=prec)

In [7]: x._mpf_
Out[7]: (0, mpz(12297829382473034411), -64, 64)

In [8]: y._mpf_
Out[8]: (0, mpz(12297829382473034411), -64, 64)

In [9]: x._prec
Out[9]: 64

In [10]: y._prec
Out[10]: 64

In [11]: abs((x - y)/y) < 2**(-(prec + 1))
Out[11]: True
```
This is the important bit:
```python
In [19]: d.as_integer_ratio()
Out[19]: (12297829382473034411, 18446744073709551616)

In [12]: num, den = d.as_integer_ratio()

In [13]: t = (int(num < 0), abs(num), 1-den.bit_length(), num.bit_length())

In [16]: x2 = Float(t, precision=prec)

In [17]: x2._mpf_
Out[17]: (0, mpz(12297829382473034411), -64, 64)

In [18]: abs((x2 - y)/y) < 2**(-(prec + 1))
Out[18]: True
```

**Comment by chatcannon** [comment]
```python
In [1]: import numpy as np

In [2]: d = np.longdouble(2)/3

In [3]: d
Out[3]: 0.66666666666666666666666666666666

In [4]: prec = np.finfo(d).nmant + 1

In [5]: prec
Out[5]: 106

In [6]: x = Float(d)

In [7]: y = Float(Rational(2, 3), precision=prec)

In [8]: x._mpf_
Out[8]: (0, 27043212804868893898596335048021, -105, 105)

In [9]: y._mpf_
Out[9]: (0, 54086425609737787797192670096043, -106, 106)

In [10]: x._prec
Out[10]: 106

In [11]: y._prec
Out[11]: 106

In [12]: abs((x - y)/y) < 2**(-(prec + 1))
Out[12]: False

In [13]: d.as_integer_ratio()
Out[13]: (108172851219475575594385340192085, 162259276829213363391578010288128)

In [14]: num, den = d.as_integer_ratio()

In [15]: t = (int(num < 0), abs(num), 1-den.bit_length(), num.bit_length())

In [16]: x2 = Float(t, precision=prec)

In [17]: x2._mpf_
Out[17]: (0, 27043212804868893898596335048021, -105, 105)

In [18]: abs((x2 - y)/y) < 2**(-(prec + 1))
Out[18]: False
```

**Comment by chatcannon** [comment]
Also potentially relevant:
```python
In [28]: d = np.longdouble(2)/3

In [29]: num, den = d.as_integer_ratio()

In [30]: x3 = Float(Rational(num, den), prec)

In [31]: x3._mpf_
Out[31]: (0, 108172851219475575594385340192085, -107, 107)

In [32]: abs((x3 - y)/y) < 2**(-(prec + 1))
Out[32]: False
```

**Comment by oscarbenjamin** [comment]
Make sure to use `precision=prec` rather than just `prec` because one is decimal precision and the other is binary precision:
```python
In [30]: num, den = (108172851219475575594385340192085, 162259276829213363391578010288128)

In [31]: t = (int(num < 0), abs(num), 1-den.bit_length(), num.bit_length())

In [32]: t
Out[32]: (0, 108172851219475575594385340192085, -107, 107)

In [33]: Float(t, 106)._mpf_
Out[33]: (0, mpz(108172851219475575594385340192085), -107, 107)

In [34]: Float(t, precision=106)._mpf_
Out[34]: (0, mpz(27043212804868893898596335048021), -105, 105)

In [35]: Float(Rational(2, 3), precision=106)._mpf_
Out[35]: (0, mpz(54086425609737787797192670096043), -106, 106)
```

**Comment by chatcannon** [comment]
Well spotted. With `precision=prec` the values are the same:
```python
In [52]: d = np.longdouble(2)/3

In [53]: num, den = d.as_integer_ratio()

In [54]: x = Float(d)

In [55]: x._mpf_
Out[55]: (0, 27043212804868893898596335048021, -105, 105)

In [56]: x3 = Float(Rational(num, den), precision=prec)

In [57]: x3._mpf_
Out[57]: (0, 27043212804868893898596335048021, -105, 105)
```

**Comment by chatcannon** [comment]
I found an even worse example `3483252843105403 / 13933011372409071` which is just greater than 1/4.

For this number, the precision estimated by the number of bits in the mantissa is three bits too much:

```python
In [1]: a, b = (3483252843105403, 13933011372409071)

In [3]: y = Rational(a, b)

In [4]: d = np.longdouble(a) / np.longdouble(b)

In [5]: d.as_integer_ratio()
Out[5]: (40564819207339852940225539762219, 162259276829213363391578010288128)

In [6]: x = Float(d)

In [7]: x
Out[7]: 0.2500000000002250231422482434444

In [8]: prec = np.finfo(d).nmant + 1

In [9]: x._mpf_
Out[9]: (0, 40564819207339852940225539762219, -107, 106)

In [13]: abs(x - y) / y
Out[13]: 4.930380657626885984831066881718e-32

In [14]: (abs(x - y) / y) * 2**(prec + 1)
Out[14]: 7.999999999992799259448062691111
```

**Comment by oscarbenjamin** [comment]
Here I have:
```python
In [17]: num, den = (np.longdouble(2)/3).as_integer_ratio()

In [18]: t = (int(num < 0), abs(num), 1-den.bit_length(), num.bit_length())

In [19]: t
Out[19]: (0, 12297829382473034411, -64, 64)

In [20]: np.finfo(np.longdouble).nmant + 1
Out[20]: 64
```
Your system seems to give a numerator with a bit length that is greater than `nmant + 1`:
```python
In [21]: num, den = (108172851219475575594385340192085, 162259276829213363391578010288128)

In [22]: num.bit_length()
Out[22]: 107
```
That means that trying to construct an mpf from `as_integer_ratio` leads to a rounding:
```python
In [23]: t = (int(num < 0), abs(num), 1-den.bit_length(), num.bit_length())

In [24]: t
Out[24]: (0, 108172851219475575594385340192085, -107, 107)

In [25]: Float(t, precision=106)._mpf_
Out[25]: (0, mpz(27043212804868893898596335048021), -105, 105)
```
This means that there are two roundings to build the Float and the double rounding means that it is no longer the closest Float of that precision to 2/3. The two roundings are the division `np.longdouble(2)/3` and then the conversion to Float. Had the precision been recorded as 107 there would be no second rounding:
```python
In [33]: Float(t, precision=107)._mpf_
Out[33]: (0, mpz(108172851219475575594385340192085), -107, 107)
```
The fact that `as_integer_ratio` gives a 107 bit (odd) numerator implies that the precision should be recorded as 107 in this case but that's `nmant + 2` rather than `nmant + 1`.

Maybe I'm misunderstanding how the double double architecture works here. In ordinary double precision 52 bits are stored explicitly for the mantissa but there's an implicit leading 1 so the precision is really 53 bits. In double double there should be 52 explicit bits in each double or 53 bits if you count the implicit 1 but that only gets us to 106 bits in total even if both implicit ones are counted. Where does the extra bit come from to make a precision of 107?

I'm also a bit confused about what `nmant` is supposed to mean now. If it's supposed to be the number of bits used explicitly for the mantissa then in the double double format should it not be an even number?

**Comment by oscarbenjamin** [comment]
I've opened a numpy issue to clarify if this is a bug or how exactly `nmant` is supposed to be interpretted: https://github.com/numpy/numpy/issues/22333

**Comment by chatcannon** [comment]
> I'm also a bit confused about what nmant is supposed to mean now. If it's supposed to be the number of bits used explicitly for the mantissa then in the double double format should it not be an even number?

From my understanding (based on the Wikipedia page), the extra bit comes from the sign bit of the second double. For example, numbers between `1` and `1 + 2**-53` would be represented with `1.0` as the first double and a positive second double with exponent `-53`, while numbers between `1 + 2**-53` and `1 + 2**-52` would be represented with `1 + 2**-52` as the first double and a negative second double.

**Comment by chatcannon** [comment]
```python
In [13]: def split_long_double(x):
    ...:     assert x.dtype == np.longdouble
    ...:     arr = np.ndarray(buffer=x.data, dtype='f8', shape=(2,))
    ...:     return arr[0], arr[1]
    ...: 

In [14]: d1, d2 = split_long_double(d)

In [16]: Float(d1)._mpf_
Out[16]: (0, mpz(6004799503160661), -53, 53)

In [17]: Float(d2)._mpf_
Out[17]: (0, mpz(6004799503160661), -107, 53)
```

**Comment by chatcannon** [comment]
> Most implementations of double-double arithmetic that I've seen do not allow for a "gap" between the mantissa bits of the "low" and "high" value, i.e. the exponent of the "low" value are useless bits. But I'm not familiar with this IBM version of double-double arithmetic, do you happen to have a link to a reference document?

Looking at the long double representation of 2/3 above, there is indeed a one-bit gap between the mantissa bits of `d1` and `d2`. That makes sense, since the binary representation of 2/3 is `0.[10]` recurring so there is a gap between `1` bits. That is what causes the numerator to have 107 bits instead of the expected 106.

**Comment by chatcannon** [comment]
So the problem here is that, for "double double" arithmetic, the number of bits of precision that can be expressed depends on the number being represented, whereas the numpy and sympy code assumes that the precision is a property. This is also the case for IEEE 754 floats (subnormal numbers have less precision), but is easier to ignore because we do not come across the problem as often. If I create a sympy `Float` from a subnormal IEEE754 double, it also has incorrect precision:

```python
In [24]: d = 5 * np.finfo(np.float64).smallest_subnormal

In [27]: Float(d)._mpf_
Out[27]: (0, mpz(5697116953585955), -1124, 53)

In [28]: Float(d)._prec
Out[28]: 53

In [29]: np.finfo(d).precision
Out[29]: 15

In [30]: np.finfo(d).nmant
Out[30]: 52
```

**Comment by chatcannon** [comment]
I have another question about the test function:
```python
    def check_prec_and_relerr(npval, ratval):
        prec = np.finfo(npval).nmant + 1
        x = Float(npval)
        assert x._prec == prec
        y = Float(ratval, precision=prec)
        assert abs((x - y)/y) < 2**(-(prec + 1))
```
Given that `2**(-prec)` is the smallest possible relative difference between `Float(precision=prec)` values, isn't the `assert` statement at the end equivalent to `assert x == y`? Wouldn't it be better to assert that the difference between the `Float` value and the desired `Rational` value is smaller than a given threshold? e.g. 
```python
        assert abs((Rational(x) - ratval) / ratval) < Rational(1, 2**(prec + 1))
```

In fact, it is not clear what is being tested here. Is it testing that the numpy float arithmetic gives a good approximation (to within the stated precision) of the value 2/3, or is it testing the conversion from numpy value to sympy `Float`?

**Comment by chatcannon** [comment]
> Looking at the long double representation of 2/3 above, there is indeed a one-bit gap between the mantissa bits of `d1` and `d2`. That makes sense, since the binary representation of 2/3 is `0.[10]` recurring so there is a gap between `1` bits. That is what causes the numerator to have 107 bits instead of the expected 106.

Taking a number with much longer runs of zeros in its binary representation can give a higher precision by allowing a bigger gap between the mantissa bits of the first and second doubles:
```python
In [20]: a = 2**24

In [21]: b = 2**25 - 1

In [22]: d = np.longdouble(a) / np.longdouble(b)

In [23]: d
Out[23]: 0.50000001490116163793687933495281

In [24]: d.as_integer_ratio()
Out[24]: (42535297132767945940084216282776338433, 85070591730234615865843651857942052864)

In [25]: d.as_integer_ratio()[0].bit_length()
Out[25]: 126

In [26]: d1, d2 = split_long_double(d)

In [27]: d1, d2
Out[27]: (0.5000000149011616, 1.3234890195278907e-23)

In [28]: Float(d1)._mpf_
Out[28]: (0, mpz(1125899940397057), -51, 51)

In [29]: Float(d2)._mpf_
Out[29]: (0, mpz(1125899940397057), -126, 51)

In [30]: y = Rational(a, b)

In [32]: abserr = abs(Rational(*(d.as_integer_ratio())) - y)

In [33]: relerr = abserr / y

In [34]: N(relerr)
Out[34]: 7.00649232162409e-46

In [35]: N(log(relerr) / log(2))
Out[35]: -150.000000000000
```

**Comment by chatcannon** [comment]
> The test is that SymPy converts the value to Float correctly.

Then I think this would be a better test:
```python
def check_numpy_float_against_sympy(np_val, sy_val):
    assert isinstance(np_val, np.floating)
    assert isinstance(sy_val, Float)

    # Check that values are equal
    assert Rational(*np_val.as_integer_ratio()) == Rational(sy_val)

    # Check that precision is correct
    # eps should be the smallest value that can be added to np_val to give a different value of the same dtype
    eps_exponent = sy_val._mpf_[2] + sy_val._mpf_[3] - sy_val._prec
    eps_sign = -1 ** sy_val._mpf_[0]  # Sign only matters for numbers like -1.0 where the eps is different for adding vs subtracting
    eps = eps_sign * np_val.dtype(2) ** eps_exponent
    assert np_val != np_val + eps
    assert np_val  == np_val + (eps / 2)
```
