### ISSUE TITLE
Sympy 1.10+ erro when creating Piecewises with equations containing booleans: Booleans appear in AttributeError: 'BooleanTrue' object has no attribute 'as_coeff_Add' error when creating a piecewise

### ISSUE THREAD

**Issue by MauriceHendrix** [sympy/sympy#24086]
I get the following error when I'm trying to turn the following into a piecewise. This is (part of) what I'm getting from a compiler ranslating MathML.

**This issue seems to be happening with 1.10. and 1.11.1,, but does not happenw ith sympy 1.9**

```
>>> eqs
(_1, Eq(Eq(_Ax, _0), True))
>>> sympy.Piecewise(eqs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\uczmh2\Desktop\chaste_codegen\lib\site-packages\sympy\functions\elementary\piecewise.py", line 145, in __new__
    r = cls.eval(*newargs)
  File "C:\Users\uczmh2\Desktop\chaste_codegen\lib\site-packages\sympy\functions\elementary\piecewise.py", line 190, in eval
    cond = cond.replace(
  File "C:\Users\uczmh2\Desktop\chaste_codegen\lib\site-packages\sympy\core\basic.py", line 1577, in replace
    rv = walk(self, rec_replace)
  File "C:\Users\uczmh2\Desktop\chaste_codegen\lib\site-packages\sympy\core\basic.py", line 1562, in walk
    rv = F(rv)
  File "C:\Users\uczmh2\Desktop\chaste_codegen\lib\site-packages\sympy\core\basic.py", line 1570, in rec_replace
    v = _value(expr, result)
  File "C:\Users\uczmh2\Desktop\chaste_codegen\lib\site-packages\sympy\core\basic.py", line 1536, in <lambda>
    _value = lambda expr, result: value(expr)
  File "C:\Users\uczmh2\Desktop\chaste_codegen\lib\site-packages\sympy\core\relational.py", line 52, in _canonical_coeff
    b, l = rel.lhs.as_coeff_Add(rational=True)
AttributeError: 'BooleanTrue' object has no attribute 'as_coeff_Add'
```

**Comment by oscarbenjamin** [comment]
For some reason relationals have `is_Boolean = False`. This should fix it:
```diff
diff --git a/sympy/core/relational.py b/sympy/core/relational.py
index b12bb59..9283a65 100644
--- a/sympy/core/relational.py
+++ b/sympy/core/relational.py
@@ -144,6 +144,7 @@ class Relational(Boolean, EvalfMixin):
     ValidRelationOperator = {}  # type: tDict[tUnion[str, None], Type[Relational]]
 
     is_Relational = True
+    is_Boolean = True
 
     # ValidRelationOperator - Defined below, because the necessary classes
     #   have not yet been defined

```

**Comment by MauriceHendrix** [comment]
@oscarbenjamin that fixes it indeed
