### ISSUE TITLE
solve of quadratic congruence leads to infinite recursion depth

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#24115]
```
solve(Mod(x**2, 4096), x)
```

leads to infinite recursion depth:

```
>>> solve(Mod(x**2, 4096), x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1142, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1758, in _solve
    iv = _solve(u - t, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1809, in _solve
    soln = _tsolve(f_num, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 2782, in _tsolve
    return _solve(rewrite - rhs, sym, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1758, in _solve
    iv = _solve(u - t, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1809, in _solve
    soln = _tsolve(f_num, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 2782, in _tsolve
    return _solve(rewrite - rhs, sym, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1758, in _solve
    iv = _solve(u - t, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1809, in _solve
    soln = _tsolve(f_num, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 2782, in _tsolve
    return _solve(rewrite - rhs, sym, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1758, in _solve
    iv = _solve(u - t, symbol, **flags)
...
    soln = _tsolve(f_num, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 2782, in _tsolve
    return _solve(rewrite - rhs, sym, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1758, in _solve
    iv = _solve(u - t, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1809, in _solve
    soln = _tsolve(f_num, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 2782, in _tsolve
    return _solve(rewrite - rhs, sym, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1758, in _solve
    iv = _solve(u - t, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1809, in _solve
    soln = _tsolve(f_num, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 2782, in _tsolve
    return _solve(rewrite - rhs, sym, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1758, in _solve
    iv = _solve(u - t, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1809, in _solve
    soln = _tsolve(f_num, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 2782, in _tsolve
    return _solve(rewrite - rhs, sym, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1758, in _solve
    iv = _solve(u - t, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1809, in _solve
    soln = _tsolve(f_num, symbol, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 2782, in _tsolve
    return _solve(rewrite - rhs, sym, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 1546, in _solve
    f_num, sol = solve_linear(f, symbols=symbols)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/solvers/solvers.py", line 2254, in solve_linear
    dnewn_dxi = newn.diff(xi)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/expr.py", line 3567, in diff
    return _derivative_dispatch(self, *symbols, **assumptions)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/function.py", line 1914, in _derivative_dispatch
    return Derivative(expr, *variables, **kwargs)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/function.py", line 1442, in __new__
    obj = cls._dispatch_eval_derivative_n_times(expr, v, count)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/function.py", line 1903, in _dispatch_eval_derivative_n_times
    return expr._eval_derivative_n_times(v, count)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 1785, in _eval_derivative_n_times
    obj2 = obj._eval_derivative(s)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/add.py", line 508, in _eval_derivative
    return self.func(*[a.diff(s) for a in self.args])
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/add.py", line 508, in <listcomp>
    return self.func(*[a.diff(s) for a in self.args])
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/expr.py", line 3567, in diff
    return _derivative_dispatch(self, *symbols, **assumptions)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/function.py", line 1914, in _derivative_dispatch
    return Derivative(expr, *variables, **kwargs)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/function.py", line 1442, in __new__
    obj = cls._dispatch_eval_derivative_n_times(expr, v, count)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/function.py", line 1903, in _dispatch_eval_derivative_n_times
    return expr._eval_derivative_n_times(v, count)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 1785, in _eval_derivative_n_times
    obj2 = obj._eval_derivative(s)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/function.py", line 610, in _eval_derivative
    l.append(df * da)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/decorators.py", line 236, in _func
    return func(self, other)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/decorators.py", line 106, in binary_op_wrapper
    return func(self, other)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/expr.py", line 218, in __mul__
    return Mul(self, other)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/function.py", line 2339, in __hash__
    return super().__hash__()
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 158, in __hash__
    h = hash((type(self).__name__,) + self._hashable_content())
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/function.py", line 2343, in _hashable_content
    ) + tuple(ordered([(v, p) for v, p in
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/function.py", line 2344, in <listcomp>
    zip(self.variables, self.point) if not self.expr.has(v)]))
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 382, in __eq__
    if a != b:
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/containers.py", line 100, in __eq__
    return super().__eq__(other)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 382, in __eq__
    if a != b:
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/basic.py", line 381, in __eq__
    a, b = self._hashable_content(), other._hashable_content()
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/symbol.py", line 453, in _hashable_content
    return Symbol._hashable_content(self) + (self.dummy_index,)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/symbol.py", line 342, in _hashable_content
    return (self.name,) + tuple(sorted(self.assumptions0.items()))
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/core/symbol.py", line 355, in assumptions0
    in self._assumptions.items() if value is not None}
RecursionError: maximum recursion depth exceeded while calling a Python object
```

`quadratic_congruence` can find the solution basis immediately.

```
>>> quadratic_congruence(1, 0, 0, 4096)
[0, 64, 128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536, 1600, 1664, 1728, 1792, 1856, 1920, 1984, 2048, 2112, 2176, 2240, 2304, 2368, 2432, 2496, 2560, 2624, 2688, 2752, 2816, 2880, 2944, 3008, 3072, 3136, 3200, 3264, 3328, 3392, 3456, 3520, 3584, 3648, 3712, 3776, 3840, 3904, 3968, 4032]
```

**Comment by asmeurer** [comment]
solveset works correctly

```
>>> solveset(Mod(x**2, 4096), x, Integers)
Union(ImageSet(Lambda(_n, 4096*_n), Integers), ImageSet(Lambda(_n, 4096*_n + 64), Integers), ImageSet(Lambda(_n, 4096*_n + 128), Integers), ImageSet(Lambda(_n, 4096*_n + 192), Integers), ImageSet(Lambda(_n, 4096*_n + 256), Integers), ImageSet(Lambda(_n, 4096*_n + 320), Integers), ImageSet(Lambda(_n, 4096*_n + 384), Integers), ImageSet(Lambda(_n, 4096*_n + 448), Integers), ImageSet(Lambda(_n, 4096*_n + 512), Integers), ImageSet(Lambda(_n, 4096*_n + 576), Integers), ImageSet(Lambda(_n, 4096*_n + 640), Integers), ImageSet(Lambda(_n, 4096*_n + 704), Integers), ImageSet(Lambda(_n, 4096*_n + 768), Integers), ImageSet(Lambda(_n, 4096*_n + 832), Integers), ImageSet(Lambda(_n, 4096*_n + 896), Integers), ImageSet(Lambda(_n, 4096*_n + 960), Integers), ImageSet(Lambda(_n, 4096*_n + 1024), Integers), ImageSet(Lambda(_n, 4096*_n + 1088), Integers), ImageSet(Lambda(_n, 4096*_n + 1152), Integers), ImageSet(Lambda(_n, 4096*_n + 1216), Integers), ImageSet(Lambda(_n, 4096*_n + 1280), Integers), ImageSet(Lambda(_n, 4096*_n + 1344), Integers), ImageSet(Lambda(_n, 4096*_n + 1408), Integers), ImageSet(Lambda(_n, 4096*_n + 1472), Integers), ImageSet(Lambda(_n, 4096*_n + 1536), Integers), ImageSet(Lambda(_n, 4096*_n + 1600), Integers), ImageSet(Lambda(_n, 4096*_n + 1664), Integers), ImageSet(Lambda(_n, 4096*_n + 1728), Integers), ImageSet(Lambda(_n, 4096*_n + 1792), Integers), ImageSet(Lambda(_n, 4096*_n + 1856), Integers), ImageSet(Lambda(_n, 4096*_n + 1920), Integers), ImageSet(Lambda(_n, 4096*_n + 1984), Integers), ImageSet(Lambda(_n, 4096*_n + 2048), Integers), ImageSet(Lambda(_n, 4096*_n + 2112), Integers), ImageSet(Lambda(_n, 4096*_n + 2176), Integers), ImageSet(Lambda(_n, 4096*_n + 2240), Integers), ImageSet(Lambda(_n, 4096*_n + 2304), Integers), ImageSet(Lambda(_n, 4096*_n + 2368), Integers), ImageSet(Lambda(_n, 4096*_n + 2432), Integers), ImageSet(Lambda(_n, 4096*_n + 2496), Integers), ImageSet(Lambda(_n, 4096*_n + 2560), Integers), ImageSet(Lambda(_n, 4096*_n + 2624), Integers), ImageSet(Lambda(_n, 4096*_n + 2688), Integers), ImageSet(Lambda(_n, 4096*_n + 2752), Integers), ImageSet(Lambda(_n, 4096*_n + 2816), Integers), ImageSet(Lambda(_n, 4096*_n + 2880), Integers), ImageSet(Lambda(_n, 4096*_n + 2944), Integers), ImageSet(Lambda(_n, 4096*_n + 3008), Integers), ImageSet(Lambda(_n, 4096*_n + 3072), Integers), ImageSet(Lambda(_n, 4096*_n + 3136), Integers), ImageSet(Lambda(_n, 4096*_n + 3200), Integers), ImageSet(Lambda(_n, 4096*_n + 3264), Integers), ImageSet(Lambda(_n, 4096*_n + 3328), Integers), ImageSet(Lambda(_n, 4096*_n + 3392), Integers), ImageSet(Lambda(_n, 4096*_n + 3456), Integers), ImageSet(Lambda(_n, 4096*_n + 3520), Integers), ImageSet(Lambda(_n, 4096*_n + 3584), Integers), ImageSet(Lambda(_n, 4096*_n + 3648), Integers), ImageSet(Lambda(_n, 4096*_n + 3712), Integers), ImageSet(Lambda(_n, 4096*_n + 3776), Integers), ImageSet(Lambda(_n, 4096*_n + 3840), Integers), ImageSet(Lambda(_n, 4096*_n + 3904), Integers), ImageSet(Lambda(_n, 4096*_n + 3968), Integers), ImageSet(Lambda(_n, 4096*_n + 4032), Integers))
```

**Comment by oscarbenjamin** [comment]
I think there's already another issue referencing more or less the same thing which is this line here:
https://github.com/sympy/sympy/blob/10deed6f64f49501269e7e5a6f376b23e5c198d7/sympy/solvers/solvers.py#L2755-L2757
Basically the check `rewrite != lhs` is supposed to guard against infinite recursion but doesn't work because rewrite might produce something that eventually gets transformed to become the same input for `eq` here.

In this case:
```
ipdb> p eq
-_t + Mod(x**2, 4096)
ipdb> p lhs
Mod(x**2, 4096)
ipdb> p rhs
_t
ipdb> p rewrite
Mod(exp(2*log(x)), 4096)
```
Somewhere along the line `_vsolve` calls `_solve` which then turns `exp(2*log(x))` back into `x**2`.

Of course another question is how this particular equation ends up in `_tsolve` at all.

**Comment by asmeurer** [comment]
Would `solve` even have a chance at solving this? The presence of `Mod` should tell it to solve using integer routines. Those routines apparently exist somewhere in solveset. Also, setting `x = Symbols('x', integer=True)` should do this, but it doesn't make a difference here.
