### ISSUE TITLE
NotImplementedError: Result depends on the sign of sign(log(sqrt(2)*cos(x)))

### ISSUE THREAD

**Issue by galenseilis** [sympy/sympy#24139]
I was testing SymPy to see if I could find an integral that it couldn't handle (but purportedly has a solution). Here is an AMM Problem:

 [Problem 12362 - 10 - A. Garcia (France).](https://www.mat.uniroma2.it/~tauraso/AMM/amm.html)

![](https://www.mat.uniroma2.it/~tauraso/AMM/Gif/12362.gif)

```python
from sympy import *
n = Symbol('n', integer=True, positive=True)
x = Symbol('x', real=True)

f = n / ((sqrt(2) * cos(x))**n + (sqrt(2) * sin(x))**n)
limit(integrate(f, (x, 0, pi / 2)), n, oo)
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sympy/series/limits.py", line 62, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
  File "/usr/lib/python3/dist-packages/sympy/series/limits.py", line 344, in doit
    r = gruntz(e, z, z0, dir)
  File "/usr/lib/python3/dist-packages/sympy/series/gruntz.py", line 699, in gruntz
    r = limitinf(e0, z)
  File "/usr/lib/python3/dist-packages/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/sympy/series/gruntz.py", line 450, in limitinf
    c0, e0 = mrv_leadterm(e, x)
  File "/usr/lib/python3/dist-packages/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/sympy/series/gruntz.py", line 537, in mrv_leadterm
    f, logw = rewrite(exps, Omega, x, w)
  File "/usr/lib/python3/dist-packages/sympy/series/gruntz.py", line 620, in rewrite
    raise NotImplementedError('Result depends on the sign of %s' % sig)
NotImplementedError: Result depends on the sign of sign(log(sqrt(2)*cos(x)))
```

AMM doesn't appear to have posted an answer yet, so no rush in giving an implementation for this problem. My intent isn't to spoil the problem. 

I am curious though, is such a dependence on a signum of a function such as `log(sqrt(2)*cos(x))` something that can be implemented? Since `cos(pi/2) = 0`, `log(sqrt(2)*cos(x))` is not defined at `pi/2`, handling this case isn't obvious to me.

**Comment by 1e9abhi1e10** [comment]
Hii , I am interested in that issue and like to work could u assign me this issue!

**Comment by asmeurer** [comment]
For me the integral doesn't evaluate and I get `NotImplementedError: Don't know how to calculate the mrv of 'Integral(1/(sin(x)**_p + cos(x)**_p), (x, 0, pi/2))'`. What version of SymPy are you using? Perhaps an older version switched the order of integration and limit. 

It's an open issue to make limit return a Piecewise instead of giving this error. Beyond that, SymPy would need to learn how to split the integral across the cases. That's assuming whatever would be returned from `limit` is a useful result.

**Comment by galenseilis** [comment]
> For me the integral doesn't evaluate and I get `NotImplementedError: Don't know how to calculate the mrv of 'Integral(1/(sin(x)**_p + cos(x)**_p), (x, 0, pi/2))'`. What version of SymPy are you using? Perhaps an older version switched the order of integration and limit.
> 
> It's an open issue to make limit return a Piecewise instead of giving this error. Beyond that, SymPy would need to learn how to split the integral across the cases. That's assuming whatever would be returned from `limit` is a useful result.

Here is my SymPy version:

```bash
$ python3
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.9'
```
