### ISSUE TITLE
MatAdd should filter out S.Zero .

### ISSUE THREAD

**Issue by JRF-2018** [sympy/sympy#24131]
The following code worked in 1.10.1 but not in 1.11.1.

```python
from sympy import *
m1 = MatrixSymbol("m1", 2, 2)
m2 = MatrixSymbol("m2", 2, 2)
m3 = MatrixSymbol("m3", 2, 2)
Add(0, m1) # no error
MatAdd(0, m1) # TypeError
(m1 + m2 + m3).subs(m1 + m2, m3) # TypeError

```

When calling ``sympy.matrices.expressions.matadd.MatAdd.__new__`` without
'check', MatAdd forcibly calls 'validate' from 1.11. If you do, I
think you should change MatAdd to filter out S.Zero from arguments.

**Comment by asmeurer** [comment]
I'm not sure why it would have worked in 1.10, but this behavior seems correct to me. MatAdd only allows matrix arguments. Scalar arguments, even 0, give an error. 

The last line, with subs, seems like a legitimate issue. MatAdd should be able to substitute a MatAdd with a MatrixSymbol without creating an intermediate scalar.

**Comment by asmeurer** [comment]
This is what happened in 1.10.1:

```py
>>> from sympy import *
... m1 = MatrixSymbol("m1", 2, 2)
... m2 = MatrixSymbol("m2", 2, 2)
... m3 = MatrixSymbol("m3", 2, 2)
... Add(0, m1)
... MatAdd(0, m1)
... (m1 + m2 + m3).subs(m1 + m2, m3)
0 + 0 + m3 + m3
```

Those 0s are S.Zero, not ZeroMatrix. So this issue has always existed, just something changed to make MatAdd more strict about not allowing scalars. 

I would argue that that fix was correct. It's subs that should be fixed to not introduce zeros into the expression. I'm not even clear why it would do that in the first place. It seems like an inefficient way to do a substitution, even for Expr.

**Comment by JRF-2018** [comment]
The identity of MatAdd is ``sympy.matrices.expressions.special.GenericMatrix`` which has no shape.  Since no shape matrix is allowed, I think S.Zero should be allowed too.  It's more convenient.

**Comment by oscarbenjamin** [comment]
This was changed in #23671 and I think is correct.

The bug is in `subs` somewhere for introducing zeros.

**Comment by oscarbenjamin** [comment]
The zeros come from here:
https://github.com/sympy/sympy/blob/0c4cc831ab88b6ba39685540f74d9551544d06e5/sympy/core/add.py#L930-L931
It seems that `Add` and `MatAdd` share the same code for `_eval_subs`. Maybe `MatAdd.as_coeff_Add` should be changed to return a zero matrix:
https://github.com/sympy/sympy/blob/0c4cc831ab88b6ba39685540f74d9551544d06e5/sympy/core/add.py#L911-L912
```python
In [5]: m1.shape
Out[5]: (2, 2)

In [6]: m1.as_coeff_Add()
Out[6]: (0, m₁)

In [7]: type(m1.as_coeff_Add()[0])
Out[7]: sympy.core.numbers.Zero
```

**Comment by asmeurer** [comment]
I agree. It looks like there are some other issues that would crop up as well:

```
>>> MatAdd() + -MatAdd()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matexpr.py", line 99, in __neg__
    return MatMul(S.NegativeOne, self).doit()
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matmul.py", line 202, in doit
    expr = canonicalize(MatMul(*args))
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/strategies/core.py", line 8, in exhaustive_rl
    new, old = rule(expr), expr
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/strategies/core.py", line 92, in switch_rl
    return rl(expr)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/strategies/core.py", line 82, in do_one_rl
    result = rl(expr)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/matmul.py", line 263, in any_zeros
    return ZeroMatrix(matrices[0].rows, matrices[-1].cols)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/matrices/expressions/special.py", line 82, in rows
    raise TypeError("GenericZeroMatrix does not have a specified shape")
TypeError: GenericZeroMatrix does not have a specified shape
```

This also relates to this discussion https://github.com/sympy/sympy/issues/24149.
