### ISSUE TITLE
Fix broken links in the docs

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#24140]
If you run `make linkcheck` in the docs, there are several links that are broken and should be fixed. There's also a bunch of permanent redirects that can be updated.  

There are also several links to `docs.sympy.org`. These should be replaced with relative links using Sphinx (it would be nice if there were an automated check for this).

**Comment by rohitkoh123** [comment]
Please allow me to work on this, I will like to add in this as my first contribution

**Comment by asmeurer** [comment]
You don't need to ask for permission to work on an issue. Just work on it.

**Comment by tuhinmallick** [comment]
Is this issue still open, if yes i would like to work on it

**Comment by ayush3781** [comment]
@asmeurer how to run make link check

**Comment by asmeurer** [comment]
In the SymPy repo run 

```
cd doc/
make linkcheck
```

You may need to install the dependencies to build the docs first https://docs.sympy.org/latest/contributing/build-docs.html

**Comment by asmeurer** [comment]
You can also use an external tool like https://github.com/lycheeverse/lychee. The GitHub Action https://github.com/lycheeverse/lychee-action might be a good choice for doing this on CI (but we need to make sure it is setup in a way that doesn't produce a lot of false positives).

**Comment by theWiseAman** [comment]
@asmeurer I found about 56 links that are reported as broken by `linkcheck`. I have stored them in a text file manually using `make linkcheck` and `grep`. So should I automate the creation of `currentBrokenLinks.txt` file by adding makefile script in `doc/MakeFile`?
Below is that file mentioned above. Suggest the new links for the broken links while I check for alternative link myself.
[currentBrokenLinks.txt](https://github.com/sympy/sympy/files/10476649/currentBrokenLinks.txt)

_Sidenote_:- I am new to open source but eager to learn things.

**Comment by asmeurer** [comment]
I don't know if there is a benefit of creating the file. What needs to happen is to fix the links. Then ideally something that alerts us if a link gets broken in the future.

**Comment by theWiseAman** [comment]
@asmeurer I noticed some anomaly while running `linkcheck`. There are some wikipedia reference links which contains `)` at the end of the url. Those link are apparently not broken but `linkcheck` is sending http requests with last `)` truncated in those urls and reporting 'broken link error'.

Source Code:- 
```python
References
    ==========

    .. [1] https://en.wikipedia.org/wiki/Entropy_(information_theory)
```
Sample error:-

<code>modules\stats.rst:40: [broken] https://en.wikipedia.org/wiki/Entropy_(information_theory: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Entropy_(information_theory</code>

**Comment by asmeurer** [comment]
> One thing I can do for now is to replace ) with it's url encode character.

That's a good idea. I wonder if these URLs work correctly in the rendered HTML documentation.

**Comment by asmeurer** [comment]
You shouldn't use "fixes #24140" in a pull request unless it completely fixes an issue. There are still several broken links identified by `make linkcheck`. And besides, even if we fix all the links, I'd like to at least investigate if we can add something to CI to prevent broken links in the future (I'm still not convinced it will actually work well, but we can't know until we try).

**Comment by theWiseAman** [comment]
@asmeurer Ya sorry my bad. I thought closes would close the issue automatically.

**Comment by asmeurer** [comment]
No problem. For the future, both "fixes" and "closes" cause the issue to close when the PR is merged. If you just want to cross-reference an issue without closing it, just list the issue number without any words before it.

**Comment by Anant-2005** [comment]
I would like to work on this issue, please assign it to me

**Comment by theWiseAman** [comment]
@asmeurer 
> I'd like to at least investigate if we can add something to CI to prevent broken links in the future (I'm still not convinced it will actually work well, but we can't know until we try).

I was trying to add a build test routine to CI but I ran into some problem. I have a small doubt. It seems like makefile doesn't work. Am I doing something wrong?
![image](https://user-images.githubusercontent.com/77196231/215240841-a3b268d9-6405-4ed9-a532-bf4016bd6435.png)

**Comment by theWiseAman** [comment]
@asmeurer @sylee957 Can someone review my draft PR #24619? I have now opened it for merging.

**Comment by theWiseAman** [comment]
> @asmeurer @sylee957 Can someone review my draft PR #24619? I have now opened it for merging.

@asmeurer @sylee957 Can someone look at the PR again and merge it? Else I fear it would be forgotten.

**Comment by chandra20500** [comment]
Hi I want to solve this issue please assign it to me.

**Comment by asmeurer** [comment]
@chandra20500 do not spam issues like this. It is not necessary to ask permission to work on an issue. If you want to work on it, just work on it.

**Comment by theWiseAman** [comment]
@asmeurer @sylee957 I have fixed a lot of redirected links in the PR #24702. Please review it as there are a lot of files.

**Comment by theWiseAman** [comment]
> There are also several links to `docs.sympy.org`. These should be replaced with relative links using Sphinx (it would be nice if there were an automated check for this).

@asmeurer Can you elaborate this point further? What type of automated checks is needed? Does `make linkcheck` not cover these links? Is this required after my above PR merge. If yes please quote the example of this type of link.

**Comment by asmeurer** [comment]
```
$ git grep 'docs\.sympy\.org' doc/src/**/*.{md,rst} | cat
doc/src/contributing/dependencies.md:  https://docs.sympy.org/latest/install.html#mpmath for more information.
doc/src/contributing/dependencies.md:at https://docs.sympy.org/dev/index.html.
doc/src/contributing/documentation-style-guide.rst:The SymPy documentation found at `docs.sympy.org
doc/src/contributing/documentation-style-guide.rst:<https://docs.sympy.org/latest/index.html>`_ is generated from docstrings in the
doc/src/contributing/documentation-style-guide.rst:**SymPy Documentation** https://docs.sympy.org
doc/src/contributing/documentation-style-guide.rst:to the docs.sympy.org site automatically. There are two primary types of pages
doc/src/explanation/gotchas.rst:Although all docs are available at `docs.sympy.org <https://docs.sympy.org/>`_ or on the
doc/src/modules/physics/mechanics/autolev_parser.rst:Refer to the `SymPy Tutorial <https://docs.sympy.org/latest/tutorial/index.html>`_
doc/src/modules/physics/mechanics/sympy_mechanics_for_autolev_users.rst:|                       |                       | ttp://docs.sympy.org/ |
```

All of these should use RST or Markdown cross-reference syntax. make linkcheck doesn't check for this as far as I know. We would need a separate test for it (but it could be as simple as checking the above grep returns nothing).

**Comment by palash018** [comment]
When i ran ```make linkcheck``` in doc i got "Could not import extension sphinx_reredirects (exception: No module named 'sphinx_reredirects')" i'm running Sphinx 7.0.1

**Comment by asmeurer** [comment]
Make sure you installed all the dependencies required to build the docs https://github.com/sympy/sympy/blob/master/doc/requirements.txt

**Comment by haru-44** [comment]
Redirects should be fixed when, for example, the link is out of date. The following redirects should not be fixed

- `doi.org`
  - DOIs are a more resistant to link rot. 
- `docs.github.com`
  - Redirect to a page appropriate for the user's language environment.

Note that the need to fix redirects should be considered on a case-by-case basis.

c.f.,
https://github.com/sympy/sympy/pull/25505#discussion_r1293051942
https://github.com/sympy/sympy/pull/26415#issuecomment-2026632947
https://github.com/sympy/sympy/pull/26415#pullrequestreview-1968170474

**Comment by skarkloff** [comment]
Buenas, soy nuevo en contribuciones, lei la documentacion, contributors.md, probe la libreria y observe la estructura del proyecto. Como puedo empezar a contribuir, intente leyendo las issues pero se ven complejas y no se si estan obsoletas.

Hello, I am new to contributions, I read the documentation, contributors.md, tried the library and observed the structure of the project. How can I start contributing? I tried reading the issues but they look complex and I don't know if they are obsolete.

**Comment by davilaerte** [comment]
Hello, I add a new [PR](https://github.com/sympy/sympy/pull/27260) to fix more to fix more broken links.

**Comment by Nitish-Naik** [comment]
is the issue solved

**Comment by LordAnvayM** [comment]
I have added a new PR(#27420) to fix more broken links. Could you please review it?

**Comment by LordAnvayM** [comment]
Hello, I have added a new [PR](#27431) to fix more broken links.
@asmeurer

**Comment by deusMatheus** [comment]
When I try to run `make linkchekc` at ~/doc directory it returns the following error:
`~/doc/make linkcheck
mkdir -p _build/linkcheck _build/doctrees
sphinx-build -b linkcheck -d _build/doctrees  src _build/linkcheck
Running Sphinx v8.1.3

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/matheus/Codes/Projetos Pessoais/Contribuições Projetos Open Source/sympy/venv/lib/python3.12/site-packages/sphinx/config.py", line 529, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/matheus/Codes/Projetos Pessoais/Contribuições Projetos Open Source/sympy/doc/src/conf.py", line 19, in <module>
    from intersphinx_registry import get_intersphinx_mapping
ModuleNotFoundError: No module named 'intersphinx_registry'

make: *** [Makefile:125: linkcheck] Error 2
`

Am I doing something wrong? At first I though it could be that sphinx wasn't installed at sympy folder and did it through venv, however the error still continues.

**Comment by deusMatheus** [comment]
When I try to run `make linkchekc` at ./doc directory it returns the following error:

$make linkcheck
mkdir -p _build/linkcheck _build/doctrees
sphinx-build -b linkcheck -d _build/doctrees  src _build/linkcheck
Running Sphinx v8.1.3

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "./sympy/venv/lib/python3.12/site-packages/sphinx/config.py", line 529, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "./sympy/doc/src/conf.py", line 19, in <module>
    from intersphinx_registry import get_intersphinx_mapping
ModuleNotFoundError: No module named 'intersphinx_registry'

make: *** [Makefile:125: linkcheck] Error 2


Am I doing something wrong? At first I though it could be that sphinx wasn't installed at sympy folder and did it through venv, however the error still continues.

**Comment by oscarbenjamin** [comment]
There s a requirements file:
```
pip install -r doc/requirements.txt
```

**Comment by deusMatheus** [comment]
Thanks a lot!

**Comment by LordAnvayM** [comment]
@oscarbenjamin could you please look at the [PR](https://github.com/sympy/sympy/pull/27431)?

**Comment by GhazanfarTaqi** [comment]
Is the issue solved? If not, then I would like to work on this issue

**Comment by coffeecookey** [comment]
Is this issue open?

**Comment by ishita-eng** [comment]
“Hi, I’d like to work on this issue as my first contribution. Thanks!”

**Comment by haru-44** [comment]
There are several types of redirects, and I don't think we should mechanically replace all of them. The status code can serve as one criterion. For example, I think it's fine to fix a 301 redirect, but a 302 redirect doesn't need to be fixed.

**Comment by ishita-eng** [comment]
Regarding the remaining linkcheck warnings, my investigation suggests the tool is producing false positives or encountering issues outside of the repository's control:
1)Authentication Walls: Sources like GitLab often require user sign-up/login when accessed by a bot, causing the check to incorrectly report a failure, though the links work for human users.
2)Source Code Cleanliness: When I navigate to the source files mentioned in the logs (e.g., autolev_parser.rst), the reported broken link does not exist in the source code; it appears to be generated by Sphinx or included from another file.
3) many links tagged as broken , are completely functioning and relavent.

**Comment by DextroDark-12** [comment]
Hii ,
 I’m a new contributor, can I work on fixing the broken links for this issue?

**Comment by oscarbenjamin** [comment]
If you make a PR for this issue please don't write "Fixes gh-24140" in the commit messages or in the PR description. When the PR is merged it causes the issue to get closed but no individual PR is going to fix this issue.
