### ISSUE TITLE
NameError: name 'Derivative' is not defined in _lambdifygenerated

### ISSUE THREAD

**Issue by w-kerman** [sympy/sympy#24318]
To reproduce:
```
import sympy
x = sympy.symbols("x")
expr = sympy.arg(1j*x)
sympy.lambdify(x, expr.diff(x))(1)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<lambdifygenerated-3>", line 5, in _lambdifygenerated
NameError: name 'Derivative' is not defined
```

**Comment by oscarbenjamin** [comment]
Currently we have:
```python
In [14]: arg(x).diff(x)
Out[14]: 
      d                 d        
re(x)⋅──(im(x)) - im(x)⋅──(re(x))
      dx                dx       
─────────────────────────────────
           2        2            
         re (x) + im (x)

In [24]: arg(I*x).diff(x)
Out[24]: 
      d                 d        
re(x)⋅──(im(x)) - im(x)⋅──(re(x))
      dx                dx       
─────────────────────────────────
           2        2            
         re (x) + im (x) 
```
The complex derivative here is not defined so this shouldn't evaluate:
https://math.stackexchange.com/questions/484211/prove-that-fz-arg-z-is-not-analytic-on-d#:~:text=arg(z)%20is%20constant%20on,constant%2C%20which%20is%20not%20so.

If `x` is declared real then we get:
```python
In [17]: x = symbols('x', real=True)

In [18]: arg(x).diff(x)
Out[18]: 0

In [19]: arg(I*x).diff(x)
Out[19]: 0
```
which is correct for a real derivative (and will work with `lambdify`).

**Comment by w-kerman** [comment]
Oh, makes sense. Thank you.
Maybe the error message is a bit misleading.

**Comment by oscarbenjamin** [comment]
> Maybe the error message is a bit misleading.

I think it is misleading. This is a common problem with `lambdify`.
