### ISSUE TITLE
Piecewise is always assumed to be scalar during code generation

### ISSUE THREAD

**Issue by MaPePeR** [sympy/sympy#24359]
Example code:
```python
from sympy import Matrix, MatrixSymbol, Piecewise, ccode, Symbol

x = Symbol('x')
M = MatrixSymbol('M', 2, 1)

f = Piecewise(
    (Matrix([[1], [1]]), x >= 0),
    (Matrix([[0], [0]]), True),
)

# Can assign Matrix to MatrixSymbol
print(ccode(Matrix([[1], [1]]), assign_to=M))

# Cannot assign Piecewise containing Matrix to MatrixSymbol
print(ccode(f, assign_to=M))
```

I expected it to generate code like this:
```c
if (x >= 0) {
    M[0] = 1;
    M[1] = 1;
} else {
    M[0] = 0;
    M[1] = 0;
}
```

Instead I get 
```
Traceback (most recent call last):
  File "sympy_piecewise_scalar.py", line 15, in <module>
    print(ccode(f, assign_to=M))
  File "[...]\lib\site-packages\sympy\printing\codeprinter.py", line 741, in ccode
    return c_code_printers[standard.lower()](settings).doprint(expr, assign_to)
  File "[...]\lib\site-packages\sympy\printing\codeprinter.py", line 152, in doprint
    expr = _handle_assign_to(expr, assign_to)
  File "[...]\lib\site-packages\sympy\printing\codeprinter.py", line 149, in _handle_assign_to
    return Assignment(assign_to, expr)
  File "[...]\lib\site-packages\sympy\codegen\ast.py", line 416, in __new__
    cls._check_args(lhs, rhs)
  File "[...]\lib\site-packages\sympy\codegen\ast.py", line 452, in _check_args
    raise ValueError("Cannot assign a scalar to a matrix.")
ValueError: Cannot assign a scalar to a matrix.
```

Using sympy 1.11.1, Python 3.9.15 on Windows using Miniconda3.

Is there a workaround?

**Comment by ThePauliPrinciple** [comment]
Maybe being able to use a `Matrix` in `Piecewise` should be considered a bug, since  `is_scalar=True` of the resulting object. Although I don't think changing that behaviour would solve the problem with printing. 

Something like this would be a work around:
```python
from sympy.codegen.ast import Assignment, CodeBlock
from sympy.printing.c import ccode
from sympy import *
from sympy.abc import x
MS = MatrixSymbol('M', 2, 1)
M1 = Matrix([[1], [1]])
M2 = Matrix([[0], [0]])
f = Piecewise(
    (CodeBlock(*[Assignment(lhs, rhs) for lhs, rhs in zip(MS,M1)]), x >=0),
    (CodeBlock(*[Assignment(lhs, rhs) for lhs, rhs in zip(MS,M2)]), True),
)
print(ccode(f))
```
Giving:
```c
if (x >= 0) {
   M[0] = 1;
   M[1] = 1;
}
else {
   M[0] = 0;
   M[1] = 0;
}
```
Not exactly ideal though.

**Comment by oscargus** [comment]
My guess is that there should be a `PiecewiseMatrix` in that case, as most matrix-related stuff are moved to distinct functions.
