### ISSUE TITLE
Floor division with sympy.Integer gives: Argument of Integer should be of numeric type, got floor(1024/s0)

### ISSUE THREAD

**Issue by ezyang** [sympy/sympy#24369]
```
import sympy

s0 = sympy.Symbol('s0')
sympy.Integer(1024)//s0
```

gives

```
Traceback (most recent call last):
  File "/Users/ezyang/Dev/sympy/sympy/core/numbers.py", line 2098, in __new__
    ival = int(i)
  File "/Users/ezyang/Dev/sympy/sympy/core/expr.py", line 320, in __int__
    raise TypeError("Cannot convert symbols to int")
TypeError: Cannot convert symbols to int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "repro.py", line 4, in <module>
    sympy.Integer(1024)//s0
  File "/Users/ezyang/Dev/sympy/sympy/core/decorators.py", line 65, in __sympifyit_wrapper
    return func(a, b)
  File "/Users/ezyang/Dev/sympy/sympy/core/numbers.py", line 2426, in __floordiv__
    return Integer(divmod(self, other)[0])
  File "/Users/ezyang/Dev/sympy/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/Users/ezyang/Dev/sympy/sympy/core/numbers.py", line 2100, in __new__
    raise TypeError(
TypeError: Argument of Integer should be of numeric type, got floor(1024/s0).
```

oddly enough, it works if the lhs is a plain Python int.

**Comment by oscarbenjamin** [comment]
The fix seems to be
```diff
diff --git a/sympy/core/numbers.py b/sympy/core/numbers.py
index 3b1aec2..52f7ea4 100644
--- a/sympy/core/numbers.py
+++ b/sympy/core/numbers.py
@@ -2423,7 +2423,7 @@ def __floordiv__(self, other):
             return NotImplemented
         if isinstance(other, Integer):
             return Integer(self.p // other)
-        return Integer(divmod(self, other)[0])
+        return divmod(self, other)[0]
 
     def __rfloordiv__(self, other):
         return Integer(Integer(other).p // self.p)
```
