### ISSUE TITLE
Inverse Laplace Transform Failure to converge

### ISSUE THREAD

**Issue by fredty58** [sympy/sympy#24424]
I am testing Sympy for use in a linear electronics circuits class where we use Laplace/Inverse Laplace transforms to solved transient response issues. Currently, the inverse Laplace transform fails to converge for some cases that are easily handled in Matlab or Mathematica. The following example correctly solves the circuit s-Domain analysis problem but fails in the last step - the inverse transform. The Matlab results, while oddly formulated, are correct. The are shown in a comment line.
[EECS215FA21_HW8_P5.txt](https://github.com/sympy/sympy/files/10299096/EECS215FA21_HW8_P5.txt)

**Comment by oscarbenjamin** [comment]
In what way does it fail?

**Comment by oscarbenjamin** [comment]
CC @hanspi42

**Comment by hanspi42** [comment]
This is already working in the present state of development of the pull request I have just linked.

**Comment by fredty58** [comment]
@hanspi42
It fails to converge when taking the `inverse`** Laplace transform.
Output:
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\polys\polytools.py", line 3695, in nroots
    roots = mpmath.polyroots(coeffs, maxsteps=maxsteps,

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\mpmath\calculus\polynomials.py", line 196, in polyroots
    raise ctx.NoConvergence("Didn't converge in maxsteps=%d steps." \

NoConvergence: Didn't converge in maxsteps=50 steps.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\polys\polytools.py", line 3705, in nroots
    roots = mpmath.polyroots(coeffs, maxsteps=maxsteps,

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\mpmath\calculus\polynomials.py", line 196, in polyroots
    raise ctx.NoConvergence("Didn't converge in maxsteps=%d steps." \

NoConvergence: Didn't converge in maxsteps=50 steps.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\fredt\dropbox (university of michigan)\python resources\python_examples\eecs215fa21_hw8_p5.py", line 75, in <module>
    vC=invL(VC)

  File "c:\users\fredt\dropbox (university of michigan)\python resources\python_examples\eecs215fa21_hw8_p5.py", line 23, in invL
    return sy.inverse_laplace_transform(F, s, t)

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\integrals\transforms.py", line 2102, in inverse_laplace_transform
    return InverseLaplaceTransform(F, s, t, plane).doit(**hints)

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\integrals\transforms.py", line 171, in doit
    fn, T = self._try_directly(**hints)

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\integrals\transforms.py", line 135, in _try_directly
    T = self._compute_transform(self.function,

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\integrals\transforms.py", line 2049, in _compute_transform
    return _inverse_laplace_transform(F, s, t, self.fundamental_plane, **hints)

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\integrals\transforms.py", line 255, in wrapper
    res = func(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\integrals\transforms.py", line 1972, in _inverse_laplace_transform
    f, cond = inverse_mellin_transform(F, s, exp(-t), (None, S.Infinity),

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\integrals\transforms.py", line 936, in inverse_mellin_transform
    return InverseMellinTransform(F, s, x, strip[0], strip[1]).doit(**hints)

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\integrals\transforms.py", line 171, in doit
    fn, T = self._try_directly(**hints)

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\integrals\transforms.py", line 135, in _try_directly
    T = self._compute_transform(self.function,

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\integrals\transforms.py", line 875, in _compute_transform
    return _inverse_mellin_transform(F, s, x, strip, **hints)

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\integrals\transforms.py", line 255, in wrapper
    res = func(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\integrals\transforms.py", line 791, in _inverse_mellin_transform
    a, b, C, e, fac = _rewrite_gamma(g, s, strip[0], strip[1])

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\integrals\transforms.py", line 672, in _rewrite_gamma
    rs = roots(p, s)

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\polys\polyroots.py", line 1086, in roots
    for r in f.nroots():

  File "C:\ProgramData\Anaconda3\envs\Fred2_dev\lib\site-packages\sympy\polys\polytools.py", line 3710, in nroots
    raise NoConvergence(

NoConvergence: convergence to root failed; try n < 15 or maxsteps > 50

**Comment by fredty58** [comment]
@hanspi42
Thanks very much. I looked through your code postings and it looks like you are doing some very logical and good stuff. Sorry if this is a stupid question, but I'm new to Python programming (old hand at other languages) - Are your improvements something I can use now or should I just wait for the release of 1.12?

**Comment by hanspi42** [comment]
> @hanspi42 Thanks very much. I looked through your code postings and it looks like you are doing some very logical and good stuff. Sorry if this is a stupid question, but I'm new to Python programming (old hand at other languages) - Are your improvements something I can use now or should I just wait for the release of 1.12?

Ah, well, if you want to risk it, you can, but I am still changing things.

You should then use the latest version from https://github.com/hanspi42/sympy/tree/rule-based_inverse_laplace where all tests succeeded.

**Comment by fredty58** [comment]
Thanks for very much for your response. For now, I think I will wait as my
needs are not urgent and I don't think I'm good enough in Python to be of
help. Thanks for your reply and your work on this project.

Fred L. Terry, Jr.
(pronouns: he/him/his)
Professor of EECS
734-763-9764 (EECS)

Multiple Sclerosis Fundraising pages
M.S. Society Page
<https://streaklinks.com/BVRYD3TLi9Q5Pf_hKQBOrxdu/https%3A%2F%2Fmssociety.donordrive.com%2Fparticipant%2F85983>
Facebook Fundraiser page
<https://streaklinks.com/BVRYD3PPjx9mhqpqqgjqpO_F/https%3A%2F%2Fwww.facebook.com%2Fdonate%2F525830449145437>


ᐧ

**Comment by hanspi42** [comment]
@fredty58: Everything works now, even if you do it symbolically:

```python
%prun -s cumulative vc = sy.inverse_laplace_transform(VC.simplify(), s, t)

8491535 function calls (7496246 primitive calls) in 4.027 seconds

print(vc)
-IG*R1*((C*R1*R2 - 2*C*R2*(R1 + R2) + L)*sin(t*sqrt(-C**2*R1**2*R2**2 + 2*C*L*R1*R2 + 4*C*L*R2**2 - L**2)/(2*C*L*(R1 + R2))) - sqrt(-C**2*R1**2*R2**2 + 2*C*L*R1*R2 + 4*C*L*R2**2 - L**2)*cos(t*sqrt(-C**2*R1**2*R2**2 + 2*C*L*R1*R2 + 4*C*L*R2**2 - L**2)/(2*C*L*(R1 + R2))))*exp(-t*(C*R1*R2 + L)/(2*C*L*(R1 + R2)))*Heaviside(t)/(C*(R1 + R2)*sqrt(-C**2*R1**2*R2**2 + 2*C*L*R1*R2 + 4*C*L*R2**2 - L**2))
```
