### ISSUE TITLE
sympy.polys.polyerrors.HeuristicGCDFailed: no luck -- when multiplying two Polys

### ISSUE THREAD

**Issue by jaypantone** [sympy/sympy#24461]
The following code snipped produces an error for me in python3.11 using sympy 1.11.1:
```python
import sympy
x,y,C = sympy.symbols("x,y,C")
a = sympy.Poly(x**4/(C**2 + 3*C + 2)*y, y, domain='ZZ(x,C)')
b = sympy.Poly((12*C**12*x**8 + 60*C**12*x**7 + 72*C**12*x**6 + 24*C**12*x**5 + 108*C**11*x**8 + 540*C**11*x**7 + 660*C**11*x**6 + 240*C**11*x**5 + 12*C**11*x**4 + 414*C**10*x**8 + 2076*C**10*x**7 + 2580*C**10*x**6 + 1008*C**10*x**5 + 84*C**10*x**4 + 876*C**9*x**8 + 4608*C**9*x**7 + 5824*C**9*x**6 + 2400*C**9*x**5 + 240*C**9*x**4 + 1194*C**8*x**8 + 6876*C**8*x**7 + 8820*C**8*x**6 + 3816*C**8*x**5 + 408*C**8*x**4 + 1203*C**7*x**8 + 7596*C**7*x**7 + 9912*C**7*x**6 + 4560*C**7*x**5 + 540*C**7*x**4 + 897*C**6*x**8 + 6348*C**6*x**7 + 8474*C**6*x**6 + 4176*C**6*x**5 + 564*C**6*x**4 + 438*C**5*x**8 + 3816*C**5*x**7 + 5236*C**5*x**6 + 2784*C**5*x**5 + 408*C**5*x**4 + 96*C**4*x**8 + 1488*C**4*x**7 + 2170*C**4*x**6 + 1344*C**4*x**5 + 240*C**4*x**4 + 288*C**3*x**7 + 484*C**3*x**6 + 384*C**3*x**5 + 96*C**3*x**4)/(72*C**13 + 864*C**12 + 4680*C**11 + 15408*C**10 + 35280*C**9 + 61056*C**8 + 83952*C**7 + 93600*C**6 + 84744*C**5 + 61920*C**4 + 35784*C**3 + 15408*C**2 + 4320*C + 576)*y**2 + (4*C**6*x**4 + 12*C**6*x**3 + 4*C**6*x**2 + 20*C**5*x**4 + 60*C**5*x**3 + 20*C**5*x**2 + 37*C**4*x**4 + 108*C**4*x**3 + 36*C**4*x**2 + 36*C**3*x**4 + 108*C**3*x**3 + 36*C**3*x**2 + 32*C**2*x**4 + 96*C**2*x**3 + 32*C**2*x**2 + 16*C*x**4 + 48*C*x**3 + 16*C*x**2)/(12*C**7 + 84*C**6 + 240*C**5 + 384*C**4 + 420*C**3 + 348*C**2 + 192*C + 48)*y + 1, y, domain='ZZ(x,C)')

a * b
```

The traceback is:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/polytools.py", line 72, in wrapper
    return func(f, g)
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/polytools.py", line 4183, in __mul__
    return f.mul(g)
           ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/polytools.py", line 1512, in mul
    result = F.mul(G)
             ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/polyclasses.py", line 457, in mul
    return per(dmp_mul(F, G, lev, dom))
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/densearith.py", line 807, in dmp_mul
    return dup_mul(f, g, K)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/densearith.py", line 767, in dup_mul
    coeff += f[j]*g[i - j]
             ~~~~^~~~~~~~~
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/fields.py", line 497, in __mul__
    return f.new(f.numer*g.numer, f.denom*g.denom)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/fields.py", line 301, in new
    return f.raw_new(*numer.cancel(denom))
                      ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/rings.py", line 2223, in cancel
    _, p, q = f.cofactors(g)
              ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/rings.py", line 2139, in cofactors
    h, cff, cfg = f._gcd(g)
                  ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/rings.py", line 2172, in _gcd
    return f._gcd_ZZ(g)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/rings.py", line 2177, in _gcd_ZZ
    return heugcd(f, g)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/heuristicgcd.py", line 80, in heugcd
    h, cff, cfg = heugcd(ff, gg)
                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sympy/polys/heuristicgcd.py", line 118, in heugcd
    raise HeuristicGCDFailed('no luck')
sympy.polys.polyerrors.HeuristicGCDFailed: no luck
```

**Comment by oscarbenjamin** [comment]
There should be a fallback method for HEUGCD (#20874 and #23131)
