### ISSUE TITLE
Replace ManagedProperties metaclass with __init_subclass__

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#24633]
As suggested at https://github.com/sympy/sympy/pull/24598#discussion_r1088711548.

See https://docs.python.org/3/reference/datamodel.html#customizing-class-creation and https://peps.python.org/pep-0487/. I don't know if we will also need to make use of `__set_name__`.

This will (hopefully) improve the general performance as it would make Basic no longer have a metaclass (at least after BasicMeta is also removed https://github.com/sympy/sympy/pull/19907). Even if the overall performance ends up being similar, it's much better to avoid using a metaclass if possible, as they can lead to other problems and are generally confusing to developers. 

I tried just moving `ManagedProperties.__init__` into `Basic.__init_subclass__`, but it fails with

```py
>>> import sympy
...
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/functions/elementary/exponential.py", line 1146, in LambertW
    _singularities = (-Pow(S.Exp1, -1, evaluate=False), S.ComplexInfinity)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/core/expr.py", line 189, in __neg__
    return Mul._from_args((S.NegativeOne, self), c)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/core/operations.py", line 123, in _from_args
    obj.is_commutative = is_commutative
AttributeError: can't set attribute
```

Here `AssocOp._from_args` creates the object and then sets `is_commutative` on it: https://github.com/sympy/sympy/blob/c4d6b3eb1c7b39832116f7b02baf524a1ffadfba/sympy/core/operations.py#L108-L123

This works with the current metaclass design because `is_commutative` is in `AssocOp.__slots__` https://github.com/sympy/sympy/blob/c4d6b3eb1c7b39832116f7b02baf524a1ffadfba/sympy/core/operations.py#L48

This also means that you can do

```py
>>> a = x*y
>>> a.is_positive = False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: can't set attribute
>>> a.is_commutative = False
>>> a.is_commutative
False
```

I'm not clear yet why `__init_subclass__` works differently here. 

It seems that `AssocOp` really shouldn't be doing that. Being able to mutate an assumption on an object after it's been created isn't ideal. But it's also done for performance reasons so I want to be careful about changing it. If I can maintain what's currently happening for backwards compatibility for now that would be my preference.

**Comment by asmeurer** [comment]
The last line of `ManagedProperties.__init__`:

https://github.com/sympy/sympy/blob/c4d6b3eb1c7b39832116f7b02baf524a1ffadfba/sympy/core/assumptions.py#L661-L665

In the metaclass, this only applies to `Basic`, but in `__init_subclass__` it applies to every subclass. So the two aren't exactly interchangeable.

**Comment by asmeurer** [comment]
Oh right it's because `__init_subclass__` only gets called on subclasses, so it doesn't get called on Basic itself. So we either need to move some of the logic into `Basic.__init__` or make a new base class of Basic with the `__init_subclass__`. I just tested this and it appears to work.

**Comment by asmeurer** [comment]
The work is here if anyone wants to play with it. https://github.com/sympy/sympy/pull/24634
