### ISSUE TITLE
Recursion error when lambdifying an expression with 108k operations

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#24673]
I was trying to make a contrived long expression to demonstrate lambdify evaluation speeds and wrote:

```python
import sympy as sm
print(sm.__version__)

a, b, c, x, y, z = sm.symbols('a, b, c, x, y, z')
expr1 = a*x**2 + a*x**5 + b*sm.sqrt(y) + b*y**4 + c*z + c*(x - y - z)**3
expr2 = c*x**2 + a*x**5 + b*sm.sqrt(y) + b*y**4 + c*z + c*(x - y - z)**3
expr3 = ((expr1*expr2)**3).expand()
eval_expr3 = sm.lambdify((a, b, c, x, y, z), expr3)
```

This gives me a RecursionError:

```
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.33.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: run recursion_limit_test.py
1.10.1
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
~/recursion_limit_test.py in <module>
      6 expr2 = c*x**2 + a*x**5 + b*sm.sqrt(y) + b*y**4 + c*z + c*(x - y - z)**3
      7 expr3 = ((expr1*expr2)**3).expand()
----> 8 eval_expr3 = sm.lambdify((a, b, c, x, y, z), expr3)

~/miniconda/envs/sympy1.10/lib/python3.7/site-packages/sympy/utilities/lambdify.py in lambdify(args, expr, modules, printer, use_imps, dummify, cse)
    898     filename = '<lambdifygenerated-%s>' % _lambdify_generated_counter
    899     _lambdify_generated_counter += 1
--> 900     c = compile(funcstr, filename, 'exec')
    901     exec(c, namespace, funclocals)
    902     # mtime has to be None or else linecache.checkcache will remove it

RecursionError: maximum recursion depth exceeded during compilation
```

This surprised me because lambdify regularly handles expressions of millions of operations. My only guess at the moment is that I've created an invalid expression, but I'm not seeing it. Any idea what I'm doing wrong? Or if this is a bug in SymPy?

More here: https://github.com/moorepants/learn-multibody-dynamics/issues/121

**Comment by moorepants** [comment]
I've also run with Python 3.8 and SymPy 1.11.1 and get the same result.

**Comment by asmeurer** [comment]
The error is coming from `compile`, which means you're running into some limitation of Python itself. The expression is just a polynomial, so I guess somehow Python has a limit to the number of terms that can appear in an expression?

**Comment by ThePauliPrinciple** [comment]
I tried printing it with the printer and paste that code into a python interpreter and it gave me a "maximum parse depth error" (on google colab).

**Comment by asmeurer** [comment]
Indeed:

```py
>>> compile('+x'*10000, '<stdin>', 'exec')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RecursionError: maximum recursion depth exceeded during compilation
```

This is the first I've heard of this limitation.

**Comment by asmeurer** [comment]
Doesn't work if you put it in a file either:

```py
with open('test.py', 'w') as f:
    f.write('x = 1\n')
    f.write('+x'*10000)
    f.write('\n')
```

```
$ python test.py
RecursionError: maximum recursion depth exceeded during compilation
```

**Comment by ThePauliPrinciple** [comment]
Should python printers print a warning if `Add.args` is too large?

**Comment by asmeurer** [comment]
Actually the real limit is much smaller than 10000 (I used that because `expr3` has over 10000 terms). 

```py
>>> compile('+x'*2977, '<stdin>', 'exec')
<code object <module> at 0x7fd1c2be7800, file "<stdin>", line 1>
>>> compile('+x'*2978, '<stdin>', 'exec')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RecursionError: maximum recursion depth exceeded during compilation
```

I think the only way to workaround this is to split the expression up into smaller expressions. Maybe that could be done automatically similar to the `cse` option. Although this is the first time I've heard about this so I don't know how common it is in practice.

**Comment by oscarbenjamin** [comment]
Probably `lambdify` should use `sum` or `fsum` or `np.sum` etc for an `Add`.

**Comment by asmeurer** [comment]
`np.sum` operates on an axis of a single array. In order for that to work, the terms would need to be combined into an array. This gets particularly complicated when you take into account broadcasting (it's the same issue as https://github.com/sympy/sympy/issues/5642#issuecomment-801489328). In principle that is a good idea because it fuses the operations, but it's hard to do generically. I'm less concerned about non-NumPy backends.

**Comment by ThePauliPrinciple** [comment]
The string printer would also fail to print something that recovers the original SymPy expression.

**Comment by moorepants** [comment]
Here is an example with 1M operations that lambdify doesn't choke on:

```python
import sympy as sm
from sympy.physics.mechanics.models import n_link_pendulum_on_cart
eom = n_link_pendulum_on_cart(20)
expr = sum(eom.mass_matrix_full @ eom.forcing_full)
expr.count_ops()  # returns 1109992
syms = list(expr.free_symbols)
syms.remove(me.dynamicsymbols._t)
var_syms = list(me.find_dynamicsymbols(expr))
args = syms + var_syms
f = sm.lambdify(args, expr)  # slow, can also use cse=True
f(*[3.0]*len(args))  # evaluates
```
The expression this creates is not a polynomial.

As side notes, it looks like cse and no cse give different numerical accuracies:

```
In [34]: f = sm.lambdify(args, expr)

In [35]: f(*[3.0]*len(args))
Out[35]: -755068.5175701997

In [36]: f = sm.lambdify(args, expr, cse=True)

In [37]: f(*[3.0]*len(args))
Out[37]: -755068.517570188
```

and this example shows the value of the cse for evaluation time clearly:

```
In [38]: f2 = sm.lambdify(args, expr)

In [39]: vals = np.random.random(len(args))

In [40]: %timeit f2(*vals)
225 ms ± 7.02 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [41]: %timeit f(*vals)
737 µs ± 29.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

**Comment by moorepants** [comment]
Another example of a recursionerror with lambdify: https://github.com/sympy/sympy/issues/23692

**Comment by moorepants** [comment]
And another: https://github.com/sympy/sympy/issues/10934

**Comment by sylee957** [comment]
I think that there's a warning about `compile` can crash the parser for the large string 

> It is possible to crash the Python interpreter with a sufficiently large/complex string when compiling to an AST object due to stack depth limitations in Python’s AST compiler.

https://docs.python.org/3/library/functions.html#compile

I'm not sure if the workaround can be done if we can directly build `ast` for pycode instead of relying on the string printer, at least the warning only applies to strings.

**Comment by moorepants** [comment]
One other note is that you can do `sys.setrecursionlimit()` to higher values for these things to work. I'm not sure the consequences of that though.

**Comment by moorepants** [comment]
> I think that there's a warning about compile can crash the parser for the large string

But the error I'm seeing here can't strictly be tied to the length of the string, because I show that 1M operations works fine, which must have a string length longer than the first example with only 100k operations (or maybe that is bad assumption).

**Comment by oscarbenjamin** [comment]
When you write something in Python like
```
x + y + z + t
```
then really that is actually
```
(((x + y) + z) + t)
```
This means that the depth of the AST grows with the number of terms in a sum. Presumably the AST parser is recursive and so parsing a deep AST can exceed the recursion limit.

**Comment by moorepants** [comment]
Ah, that may be the difference then. If the expression in the opening comment produces a deeper AST.

**Comment by oscarbenjamin** [comment]
Using `sum([x, y, z, t])` would avoid the problem.

**Comment by bjodah** [comment]
A short term work around would be:
```diff
-import sympy as sm
+import symengine as sm
...
-eval_expr3 = sm.lambdify((a, b, c, x, y, z), expr3)
+eval_expr3 = sm.lambdify((a, b, c, x, y, z), [expr3])
```
with the benefit (I know @moorepants knows this, but maybe not everybody knows) that `eval_expr3` is pretty fast:
```pycon
>>> eval_expr3(0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
array(0.54184541)
>>> %timeit eval_expr3(0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
2.72 ms ± 3.11 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
using SymPy with [677fc6b](https://github.com/sympy/sympy/pull/24685/commits/677fc6b88491f265fd30ee8d9b818b0f9fb861e1) from gh-24685 we get:
```pycon
>>> eval_expr3(0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
0.5418454112859763

>>> %timeit eval_expr3(0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
4.17 ms ± 1.48 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
I'm actually surprised that SymEngine is just 50% faster, but that's not a SymPy-issue.

**Comment by isuruf** [comment]
Going off topic here. `backend='llvm'` and `backend='lambda'` have wildly different performance number in SymEngine.

```python
In [10]: eval_expr3 = sm.lambdify((a, b, c, x, y, z), [expr3])

In [9]: %timeit eval_expr3(0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
896 µs ± 13.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [10]: eval_expr3 = sm.lambdify((a, b, c, x, y, z), [expr3], backend="llvm")

In [11]: %timeit eval_expr3(0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
12.4 µs ± 172 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

**Comment by oscarbenjamin** [comment]
> Going off topic here.

Going even more off topic I just got confused for a while looking for SymEngine's lambdify function. Turns out that if numpy is not installed then the lambdify function is hidden. It would be better I think to raise an error that tells the user to install numpy rather than silently hiding the function.
