### ISSUE TITLE
lambdify error: invalid syntex

### ISSUE THREAD

**Issue by niwaka-ame** [sympy/sympy#24711]
Hi, I was trying to evaluate the following code:
```{python}
from sympy import *
R = Symbol("R")
lambdify((sqrt(2)*(sqrt(pi)*(R - 1)*exp((R - 1)**2/(2*(R**2 + 1)))*erf(sqrt(2)*(R - 1)/(2*sqrt(R**2 + 1)))/2 + sqrt(2*R**2 + 2)/2)*exp(-1)/(pi*(R**2 + 1)**(3/2))), (R,))
```
and it prompts the following error:
```{python}
Traceback (most recent call last):

  File "/home/y/.anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "/tmp/ipykernel_14457/3802332091.py", line 1, in <module>
    lambdify((sqrt(2)*(sqrt(pi)*(R - 1)*exp((R - 1)**2/(2*(R**2 + 1)))*erf(sqrt(2)*(R - 1)/(2*sqrt(R**2 + 1)))/2 + sqrt(2*R**2 + 2)/2)*exp(-1)/(pi*(R**2 + 1)**(3/2))), (R,))

  File "/home/y/.anaconda3/lib/python3.8/site-packages/sympy/utilities/lambdify.py", line 892, in lambdify
    c = compile(funcstr, filename, 'exec')

  File "<lambdifygenerated-1>", line 1
    def _lambdifygenerated(sqrt(2)*(sqrt(pi)*(R - 1)*exp((R - 1)**2/(2*R**2 + 2))*erf(sqrt(2)*(R - 1)/(2*sqrt(R**2 + 1)))/2 + sqrt(2*R**2 + 2)/2)*exp(-1)/(pi*(R**2 + 1)**1.5)):
                               ^
SyntaxError: invalid syntax
```
and I'm sure the expression is valid by evaluating
```{python}
(sqrt(2)*(sqrt(pi)*(R - 1)*exp((R - 1)**2/(2*(R**2 + 1)))*erf(sqrt(2)*(R - 1)/(2*sqrt(R**2 + 1)))/2 + sqrt(2*R**2 + 2)/2)*exp(-1)/(pi*(R**2 + 1)**(3/2)))
```

I'm not sure whether this is a bug or something I missed? Many thanks.

**Comment by niwaka-ame** [comment]
My environment: Python 3.10.0, SymPy 1.11.1 within a conda environment.

**Comment by oscarbenjamin** [comment]
You are passing the arguments to `lambdify` in the wrong order.
