### ISSUE TITLE
`optional-dependencies` jobs in CI failing due to test error in `sympy/printing/tests/test_aesaracode.py`

### ISSUE THREAD

**Issue by brocksam** [sympy/sympy#24746]
Full traceback is:
```
____________ sympy/printing/tests/test_aesaracode.py:test_Rationals ____________
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/testing/runtests.py", line 1337, in _timeout
    function()
  File "/home/runner/work/sympy/sympy/sympy/printing/tests/test_aesaracode.py", line 267, in test_Rationals
    assert theq(aesara_code_(sy.Integer(2) / 3), aet.true_div(2, 3))
  File "/home/runner/work/sympy/sympy/sympy/printing/tests/test_aesaracode.py", line 57, in aesara_code_
    return aesara_code(expr, **kwargs)
  File "/home/runner/work/sympy/sympy/sympy/printing/aesaracode.py", line 347, in aesara_code
    return AesaraPrinter(cache=cache, settings={}).doprint(expr, **kwargs)
  File "/home/runner/work/sympy/sympy/sympy/printing/aesaracode.py", line 307, in doprint
    return self._print(expr, dtypes=dtypes, broadcastables=broadcastables)
  File "/home/runner/work/sympy/sympy/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/home/runner/work/sympy/sympy/sympy/printing/aesaracode.py", line 241, in _print_Rational
    return aet.true_div(self._print(expr.p, **kwargs),
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/aesara/tensor/__init__.py", line 172, in __getattr__
    warn(msg, DeprecationWarning, stacklevel=2)
DeprecationWarning: `true_div` is deprecated; use `true_divide` or `divide` instead.
```

**Comment by brocksam** [comment]
This is currently causing multiple job failures in all CI.

**Comment by brocksam** [comment]
Opened PR #24747 to fix.

**Comment by brocksam** [comment]
Issue seems to stem from the use of `aesara.tensor.true_div` in the Aesara printer` as well as in the test, because this has been deprecated.

**Comment by brocksam** [comment]
Interestingly, it doesn't seem to be erroring with pytest.

**Comment by oscarbenjamin** [comment]
> Interestingly, it doesn't seem to be erroring with pytest.

With pytest warnings are collected and shown at the end. You can use `-Werror` to make warnings become errors under pytest:
https://docs.pytest.org/en/7.1.x/how-to/capture-warnings.html
