### ISSUE TITLE
Timeout for dsolve((2x^3+3y)+(3x+y-1)y'=0)

### ISSUE THREAD

**Issue by satels** [sympy/sympy#24957]
Wolfram solution:
[2x3_3yx_xy_1_y_diff1.pdf](https://github.com/sympy/sympy/files/11042205/2x3_3yx_xy_1_y_diff1.pdf)

Problem in master (commit: ff86df0122294fa1c95f3450283312cd709fa021)

```python
from sympy import dsolve, pprint
from sympy import S, Eq, Function, exp
from sympy.abc import x

y = Function('y')

eq = Eq((2*x**3+3*y(x))+(3*x+y(x)-1)*y(x).diff(), S.Zero)

pprint(eq)

print(dsolve(eq))

```

```
^CTraceback (most recent call last):
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/polys/polytools.py", line 6858, in cancel
    raise PolynomialError()
sympy.polys.polyerrors.PolynomialError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/polys/polytools.py", line 6858, in cancel
    raise PolynomialError()
sympy.polys.polyerrors.PolynomialError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/satels/Private/workspace/test_sympy/test_diff_equation.py", line 11, in <module>
    print(dsolve(eq))
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 640, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 669, in _helper_simplify
    sols = solvefunc.get_general_solution()
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/single.py", line 283, in get_general_solution
    return self._get_general_solution(simplify_flag=simplify)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/single.py", line 897, in _get_general_solution
    sol = dsolve(eq, func(x))
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 640, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 669, in _helper_simplify
    sols = solvefunc.get_general_solution()
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/single.py", line 283, in get_general_solution
    return self._get_general_solution(simplify_flag=simplify)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/single.py", line 2938, in _get_general_solution
    sol = _ode_lie_group(s, func, order, match=self.r3)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/lie_group.py", line 157, in _ode_lie_group
    sol = _ode_lie_group_try_heuristic(Eq(df, s), heuristic, func, match, inf)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/lie_group.py", line 87, in _ode_lie_group_try_heuristic
    sol = solve([r - rcoord, s - scoord], x, y, dict=True)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1147, in solve
    linear, solution = _solve_system(f, symbols, **flags)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1992, in _solve_system
    result = [r for r in result
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1993, in <listcomp>
    if not any(checksol(e, r, **flags) is False for e in exprs)]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1993, in <genexpr>
    if not any(checksol(e, r, **flags) is False for e in exprs)]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 310, in checksol
    val = simplify(f.subs(sol))
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/simplify/simplify.py", line 644, in simplify
    _e = cancel(expr)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/polys/polytools.py", line 6873, in cancel
    nc = [cancel(i) for i in nc]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/polys/polytools.py", line 6873, in <listcomp>
    nc = [cancel(i) for i in nc]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/polys/polytools.py", line 6873, in cancel
    nc = [cancel(i) for i in nc]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/polys/polytools.py", line 6873, in <listcomp>
    nc = [cancel(i) for i in nc]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/polys/polytools.py", line 6840, in cancel
    f = factor_terms(f, radical=True)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1267, in factor_terms
    return do(expr)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1230, in do
    newargs = tuple([do(i) for i in args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1230, in <listcomp>
    newargs = tuple([do(i) for i in args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1230, in do
    newargs = tuple([do(i) for i in args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1230, in <listcomp>
    newargs = tuple([do(i) for i in args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1263, in do
    *[do(a) for a in p.args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1263, in <listcomp>
    *[do(a) for a in p.args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1242, in do
    list_args = [do(a) for a in Add.make_args(p)]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1242, in <listcomp>
    list_args = [do(a) for a in Add.make_args(p)]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1230, in do
    newargs = tuple([do(i) for i in args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1230, in <listcomp>
    newargs = tuple([do(i) for i in args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1263, in do
    *[do(a) for a in p.args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1263, in <listcomp>
    *[do(a) for a in p.args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1242, in do
    list_args = [do(a) for a in Add.make_args(p)]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1242, in <listcomp>
    list_args = [do(a) for a in Add.make_args(p)]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1263, in do
    *[do(a) for a in p.args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1263, in <listcomp>
    *[do(a) for a in p.args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1230, in do
    newargs = tuple([do(i) for i in args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1230, in <listcomp>
    newargs = tuple([do(i) for i in args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1263, in do
    *[do(a) for a in p.args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1263, in <listcomp>
    *[do(a) for a in p.args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1242, in do
    list_args = [do(a) for a in Add.make_args(p)]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1242, in <listcomp>
    list_args = [do(a) for a in Add.make_args(p)]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1263, in do
    *[do(a) for a in p.args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1263, in <listcomp>
    *[do(a) for a in p.args])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1242, in do
    list_args = [do(a) for a in Add.make_args(p)]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1242, in <listcomp>
    list_args = [do(a) for a in Add.make_args(p)]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/exprtools.py", line 1240, in do
    cont, p = expr.as_content_primitive(radical=radical, clear=clear)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/mul.py", line 2063, in as_content_primitive
    c, p = a.as_content_primitive(radical=radical, clear=clear)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/power.py", line 1932, in as_content_primitive
    b = _keep_coeff(*b.as_content_primitive(radical=radical, clear=clear))
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/add.py", line 1202, in as_content_primitive
    con, prim = self.func(*[_keep_coeff(*a.as_content_primitive(
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/add.py", line 1202, in <listcomp>
    con, prim = self.func(*[_keep_coeff(*a.as_content_primitive(
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/mul.py", line 2070, in as_content_primitive
    return coef, self.func(*args)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/numbers.py", line 2289, in __hash__
    def __hash__(self):
KeyboardInterrupt

```

**Comment by oscarbenjamin** [comment]
It is getting stuck in the Lie group solver which is in turn getting stuck in `solve`. The problem in solve is actually quite a simple system of equations:
```python
In [6]: r, y, x, s = symbols('r, y, x, s')

In [7]: eqs = [r - y - 3*x, s - x**4/2 + 9*x**2/2 - 3*x]

In [8]: solve(eqs, [x, y])
```
Solving this is slow due to the checking which calls checksol. It shouldn't be necessary to do any checking here because it should be possible to just generate the correct solution by solving one equation for x and substituting that in to the other for y. It is generally slow to check solutions involving symbolic parameters and not even something that can be done reliably anyway.

**Comment by Ganesh910** [comment]
@satels 
I am unable to get how did you write (2x^3+3y)+(3x+y-1)y'=0 as Eq((2*x**3+3*y(x))+(3*x+y(x)-1)*y(x).diff(), S.Zero)

means I know How Eq() works, I wanted to just ask why have you written y(x) for every y in the equation. Can you please help me out?
