### ISSUE TITLE
Timeout for dsolve(y'' + 2*sin(y)^3*cos(y) = 0)

### ISSUE THREAD

**Issue by satels** [sympy/sympy#24956]
Wolfram solution contains in attached file
[y_diff2_cos3sin.pdf](https://github.com/sympy/sympy/files/11041727/y_diff2_cos3sin.pdf)

Problem in master (commit: ff86df0122294fa1c95f3450283312cd709fa021)

```python
from sympy import dsolve, pprint
from sympy import S, Eq, Function, sin, cos
from sympy.abc import x

y = Function('y')

eq = Eq(y(x).diff(x, 2)+(2*sin(y(x))**3)*cos(y(x)), S.Zero)

pprint(eq)

dsolve(eq)

```

```
^CTraceback (most recent call last):
  File "/home/satels/Private/workspace/test_sympy/test_diff_equation.py", line 13, in <module>
    dsolve(eq)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 640, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 673, in _helper_simplify
    rv = [odesimp(eq, s, func, hint) for s in sols]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 673, in <listcomp>
    rv = [odesimp(eq, s, func, hint) for s in sols]
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/multidimensional.py", line 130, in wrapper
    return f(*args, **kwargs)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 1627, in odesimp
    eq = _handle_Integral(eq, func, hint)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 2178, in _handle_Integral
    sol = expr.doit()
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/basic.py", line 1844, in doit
    terms = [term.doit(**hints) if isinstance(term, Basic) else term
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/core/basic.py", line 1844, in <listcomp>
    terms = [term.doit(**hints) if isinstance(term, Basic) else term
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 612, in doit
    antideriv = self._eval_integral(
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 1084, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 143, in heurisch_wrapper
    res = heurisch(f, x, rewrite, hints, mappings, retries, degree_offset,
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 766, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 766, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 766, in heurisch
    result = heurisch(f, x, mappings=mappings, rewrite=rewrite, hints=hints, retries=retries - 1, unnecessary_permutations=unnecessary_permutations)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 523, in heurisch
    result = heurisch(f, x, rewrite=True, hints=hints,
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 752, in heurisch
    solution = _integrate()
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 733, in _integrate
    solution = solve_lin_sys(numer.coeffs(), coeff_ring, _raw=False)
  File "/home/satels/workenv/test_sympy/lib/python3.10/site-packages/sympy/polys/solvers.py", line 267, in solve_lin_sys
    if sum(monom) != 1:
KeyboardInterrupt
```

**Comment by oscarbenjamin** [comment]
That commit doesn't look like it should affect anything.

**Comment by asmeurer** [comment]
I think @satels is just noting the commit on master that this was tested on.

**Comment by oscarbenjamin** [comment]
It's slow because this integral is slow in heurisch:
```python
In [6]: i = Integral(1/sqrt(x - sin(y)**4), y)

In [7]: %time i.doit()
...
```
