### ISSUE TITLE
add solve algorithm to solve equations involving `floor`

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#25001]
from #24368,
```
>>> sympy.solve(floor(s2/2 - S(1)/2) + 1, s2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/solvers/solvers.py", line 1144, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/solvers/solvers.py", line 1690, in _solve
    raise NotImplementedError('\n'.join([msg, not_impl_msg % f]))
NotImplementedError:
No algorithms are implemented to solve equation floor(s2/2 - 1/2) + 1
```
Solving `floor(expr) = n` means solving `n <= expr < n+1` -- the solver should be improved to do that.

**Comment by basantbhandari** [comment]
@smichr can i work on it?

**Comment by basantbhandari** [comment]
@smichr what is "s2" in this

**Comment by smichr** [comment]
Anyone can work on anything. (And I changed `s2` to `x` -- just a variable.

**Comment by Javeed9** [comment]
@basantbhandari can I help you?

**Comment by oscarbenjamin** [comment]
> Solving `floor(expr) = n` means solving `n <= expr < n+1` -- the solver should be improved to do that.

I don't think that the solver should be improved to do that. The `solve` function should be used for solving equations and not inequalities. It is not possible to have a coherent return type that represents the solutions of both equations and inequalities and the existing handling of inequalities already does not do what most users want. Adding functionality so that the user passes in equations and solve treats them as representing inequalities is a bad idea.

Currently we have:
```python
In [1]: solve([x**2 - 1], [x], dict=True)
Out[1]: [{x: -1}, {x: 1}]

In [2]: solve([x**2 - 1, x > 0], [x], dict=True)
Out[2]: x = 1
```
That last output should really just be `[{x: 1}]`. The problem is that `solve` treats inequalities differently from equations and calls a completely different solver that returns a completely different type of output. We should find a way of making that coherent and the expectation should be:

- The purpose of solve is to try to find explicit representations of the solutions of **equations**.
- Inequalities can be used with solve but their purpose should only be to **filter** the solutions of **equations**.
- The type returned by `solve` should be the same regardless of whether the inputs involve inequalities or not.

Once we have those things it should be possible to handle `floor` but it should be treated in the same way as something that **filters** solutions as in fact it already does:
```python
In [3]: solve([x**2 - 1, floor(x) - 1], [x], dict=True)
Out[3]: [{x: 1}]
```
Simply passing `floor(x) - 1` should be rejected by solve. Currently we have:
```python
In [4]: solve([floor(x) - 1], [x], dict=True)
---------------------------------------------------------------------------
NotImplementedError
```
That is correct or perhaps instead of `NotImplementedError` solve could give a more informative error message.

If someone would like to be able to solve inequalities then they should use the inequality solvers like `solve_univariate_inequalities` etc or there should be a new function with a different signature to solve that can represent the solutions of inequalities e.g. `solveset` could be improved to do better than this:
```python
In [21]: solveset(floor(x) - 1, x)
Out[21]: {x │ x ∊ ℂ ∧ (⌊x⌋ - 1 = 0)}
```
