### ISSUE TITLE
`sympify`  confuses user-defined symbols with special functions

### ISSUE THREAD

**Issue by rnwst** [sympy/sympy#25050]
Running the following code:
```python
from sympy import symbols, sympify

beta = symbols(r'\beta')
expr = sympify('beta + 1')
```
causes the following error:
```console
ValueError: Error from parse_expr with transformed code: 'beta +Integer (1 )'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/sympy/core/sympify.py", line 496, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/usr/lib/python3.10/site-packages/sympy/parsing/sympy_parser.py", line 1101, in parse_expr
    raise e from ValueError(f"Error from parse_expr with transformed code: {code!r}")
  File "/usr/lib/python3.10/site-packages/sympy/parsing/sympy_parser.py", line 1092, in parse_expr
    rv = eval_expr(code, local_dict, global_dict)
  File "/usr/lib/python3.10/site-packages/sympy/parsing/sympy_parser.py", line 907, in eval_expr
    expr = eval(
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'FunctionClass' and 'One'
```
I suspect this is because `sympify` ignores the defined symbol and interprets `beta` as the [special function of the same name](https://docs.sympy.org/latest/modules/functions/special.html#sympy.functions.special.beta_functions.beta) instead, though I haven't had a look at the code.

Any help would be greatly appreciated! I would prefer not to have to rename my symbols so that they don't clash with any of the special functions.

**Version info:**
Python 3.10.10
```console
>>> sympy.__version__
'1.11.1'
```

**Comment by ThePauliPrinciple** [comment]
You have to explicitly tell `sympify` about the variables you defined:
```python
from sympy import symbols, sympify

beta = symbols(r'\beta')
expr = sympify('beta + 1', locals = {'beta': beta})
```
Or if you are sure that you want everything that is defined you can do:
```python
from sympy import symbols, sympify

beta = symbols(r'\beta')
expr = sympify('beta + 1', locals = globals()) #or locals() depending on what you want
```
but that might result in unexpected clashes.

**Comment by rnwst** [comment]
Excellent, thank you, that fixes it. I should've read the docs 😳

And yes, I was trying to do something more complicated than in the MRE.
