### ISSUE TITLE
TypeError: loop of ufunc does not support argument 0 of type Add which has no callable tanh method

### ISSUE THREAD

**Issue by ramanshsharma2806** [sympy/sympy#25136]
Hi, I am trying to use `lambdify` to evaluate a sympy expression that contains `tanh`, but I get the following error.

```
TypeError: loop of ufunc does not support argument 0 of type Add which has no callable tanh method
```

The reproducible code and error is this

```python
from sympy import symbols, sympify, tanh
from sympy import lambdify
import json

x, y = symbols("x y")

exp = tanh(x ** 2 + tanh(y)) + y

# this will save the expression in a string in a json file
with open("file.json", "w") as f:
        json.dump(str(exp), f)

with open("file.json", "r") as f:
        loaded_exp = sympify(json.load(f))

# loaded_exp now contains a sympy expression

ld_exp = lambdify(x, loaded_exp) # lambdifying the expression only with respect to x

ld_exp(2) # this line results in the error
```

I think this might be happening because of the tanh function. Can anyone please help me?

**Comment by moorepants** [comment]
Your expression requires both x and y, but you only provide a value for x.

```
In [13]: ld_exp = lambdify((x, y), exp)

In [14]: ld_exp(2, 2)
Out[14]: 2.9999024315880503
```

**Comment by ramanshsharma2806** [comment]
Thank you for your response.

I believe we can form lambdify expressions with respect to only _some_ of the variables in an expression, right?

In my code above, this line runs fine
```python
ld_exp = lambdify(x, loaded_exp)
```

I can also do `help(ld_exp)` and see the analytical expression of the python function. It's the next line after that evaluating the function that is giving me trouble.

**Comment by bjodah** [comment]
@ramanshsharma2806 this is how Python operates. Consider a normal function:
```pycon
>>> def f(x):                                                                                                                                                                                                                                                                                                               
...     return x + y                                                                                                                                                                                                                                                                                                        
...                                                                                                                                                                                                                                                                                                                         
>>> help(f)  # ok                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
>>> f(2)                                                                                                                                                                                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                                                                                                                                                          
  File "<stdin>", line 1, in <module>                                                                                                                                                                                                                                                                                       
  File "<stdin>", line 2, in f                                                                                                                                                                                                                                                                                              
NameError: name 'y' is not defined```

**Comment by ramanshsharma2806** [comment]
@bjodah, thank you for the response.

Sorry, I should have been clearer with my last message. When I do not use `tanh` in the sympy expression, I can make the lambdify only with respect to x, and evaluate to get a sympy expression in terms of y, which can then be evaluated with a value for y.

<img width="940" alt="image" src="https://github.com/sympy/sympy/assets/24642071/9a1ff8f8-de2b-4b16-b4ec-f3a5892c7223">

**Comment by bjodah** [comment]
I see, by default lambdify uses numpy (when available). If you don't want a function using numpy.tanh you need to specify another module:
```pycon
>>> lambdify(x, x**2+tanh(y), modules='sympy')(2)                                                                                                            |    RETURN_(ALL_GOOD);                                                                                                                                        
tanh(y) + 4 
```

**Comment by ramanshsharma2806** [comment]
This fixed the error! Thank you. Can I ask you another question @bjodah?

I am trying to use PyTorch with sympy expressions. After the lambdified expression is ready, I want to pass in PyTorch tensors that have `requires_grad=True`. However, sympy throws this error

```
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```

Do you know if there is a way PyTorch tensors that have `requires_grad=True` can be passed to sympy lambdified expressions? Thank you.

**Comment by bjodah** [comment]
Sorry, I have no experience using `pytorch`. A quick google search led me to this project:
https://github.com/patrick-kidger/sympytorch

Not sure if that is of any help.

**Comment by ramanshsharma2806** [comment]
Thank you for the link. I tried that but I don't think sympytorch supports input that requires grad either.

**Comment by ramanshsharma2806** [comment]
Correction, I now see that sympytorch does have this capability.

**Comment by bjodah** [comment]
@ramanshsharma2806 feel free to reopen if something needs to be done on SymPy's side.
