### ISSUE TITLE
maximum failed with NotImplementedError when I try to find a max value of an expression

### ISSUE THREAD

**Issue by BEN425** [sympy/sympy#25187]
I tried to find a maximum value of an expression by `maximum` method, but it raised `NotImplementedError`.
Other expressions work normally, but this one failed. I am not sure whether this is a bug.

# Code
Here is the sample code:
```py
from sympy import *

x = symbols("x")
f = csc(x) * (1 - cos(2*pi*cos(x)))

print(maximum(f, x).evalf())
```
Output:
```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\python\notebook\test.py", line 6, in <module>
    print(maximum(f, x).evalf())
  File "c:\users\user\desktop\python\sympy\sympy\calculus\util.py", line 794, in maximum
    return function_range(f, symbol, domain).sup
  File "c:\users\user\desktop\python\sympy\sympy\calculus\util.py", line 199, in function_range
    raise NotImplementedError(
NotImplementedError: Unable to find critical points for (1 - cos(2*pi*cos(x)))*csc(x)
```

By Desmos, this function has the maximum value and is also differentiable.

I though Sympy didnt work maybe because some points are not defined, such as x=0 and x=pi.
So I tried to add an interval to maximum:
```py
from sympy import *

x = symbols("x")
f = csc(x) * (1 - cos(2*pi*cos(x)))

print(maximum(f, x, Interval.open(0, pi)).evalf())
```
or other intervals, it still didnt work.

**Comment by wermos** [comment]
Under the hood, `maximum` uses [`solveset`](https://github.com/sympy/sympy/blob/781f3257a1521f99fe1a2709d8335337f9ff7981/sympy/calculus/util.py#L197).

When that line runs, `solveset` returns
```
ConditionSet(x, Eq(-2*pi*sin(x)*sin(2*pi*cos(x)) + cos(2*pi*cos(x))*cot(x) - cot(x), 0), Interval.open(0, pi))
```
and since this is [not an iterable object](https://github.com/sympy/sympy/blob/781f3257a1521f99fe1a2709d8335337f9ff7981/sympy/calculus/util.py#L199), the program errors out with `NotImplementedError`.

**Comment by Avnitt** [comment]
Hii, Can I work on this issue?

**Comment by wermos** [comment]
Under the title at the top of the page the word "Open" or "Closed" appears to indicate the status of a PR. And if any pull request mentions this issue you will see a reference to the PR in the discussion thread.

**Comment by Avnitt** [comment]
@wermos Sorry I don't understand second part of your message. Can I start working on it? I am new to open source contribution. Can you explain a little bit more? Please

**Comment by wermos** [comment]
> Can I start working on it?

@Avnitt Yes, you may work on this issue.

**Comment by Avnitt** [comment]
@wermos thanks
