### ISSUE TITLE
Should Q.positive(x, y) throw an error?

### ISSUE THREAD

**Issue by TiloRC** [sympy/sympy#25276]
> But maybe Q.positive(x,y) should throw an error?

This used to be an error but a recent refactor of the predicates made it not one. In SymPy 1.0:

```py
>>> Q.positive(x, y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __call__() takes 2 positional arguments but 3 were given
```

We should reintroduce this type check.

_Originally posted by @asmeurer in https://github.com/sympy/sympy/issues/25221#issuecomment-1595264220_

**Comment by bobby-palmer** [comment]
From my limited understanding, there aren't any predicates that would require more than 1 argument. Am I understanding this right?

**Comment by TiloRC** [comment]
There are currently some predicates that require two arguments like `Q.gt(x,y)`. However, the new assumptions can't make very many inferences with them. However, hopefully by the the end of the summer they will be able to do things because this is what my GSoC project is about.

It's also possible for users to define their own assumptions with however many arguments they want.   

I think what should be  probably be done is that each individual predicate should raise an exception. Maybe it would also be a good idea to refactor things so that there's a unary predicate class that raises this exception that all the unary predicates inherit.

**Comment by bobby-palmer** [comment]
It seems like We couldn't make classes such as a Unary predicate class for positive to inherit since we would then need to make a class for every possible number of arguments, including user defined predicates.

What do you think about instead adding this to the __call__ method of the predicate base class : 
```
    def __call__(self, *args):
        required_args = type(self).__num_args__
        given_args = len(args)
        if given_args != required_args:
            raise TypeError(f"__call__() takes {required_args} positional arguments but {given_args} were given")
        return AppliedPredicate(self, *args)
```
Then for each predicate we make we would give it a num_args property such as : 
```
class PositivePredicate():
.....
    num_args = 1
```

**Comment by bobby-palmer** [comment]
also, should a given predicate then always accept the same number of parameters given that its handler can have multiple functions with different numbers of parameters.

**Comment by bobby-palmer** [comment]
This can be resolved by merging #25338

**Comment by TiloRC** [comment]
Currently user defined predicate with varying numbers of arguments are allowed. Should we disallow this?

**Comment by sylee957** [comment]
And I generally review that things like these are better done with static type checks, 
than implementing things in runtime.

**Comment by asmeurer** [comment]
Predicates with varying number of arguments could be useful.

**Comment by bobby-palmer** [comment]
Should I go ahead and close my PR then?

**Comment by sylee957** [comment]
I may think of keep it open. 

But if we use varying arguments of isPositive, it should be developed in the future to mean something like isPositive(x, y, z) = isPositive(x) and … and isPositive(z)

Although it is primarily used for saving the typing, I wonder if things like that can be used to define conjunctions efficiently.

**Comment by TiloRC** [comment]
> But if we use varying arguments of isPositive, it should be developed in the future to mean something like Q.positive(x, y, z) = Q.positive(x) and … and Q.positive(z)

This could be done in a preprocessing step along with some other ideas I had for preprocessing.

**Comment by TiloRC** [comment]
@sylee957 

> But if we use varying arguments of isPositive, it should be developed in the future to mean something like Q.positive(x, y, z) = Q.positive(x) and … and Q.positive(z)

One reason not to do something like this is that it might be confusing whether Q.predicate(x, y, z) means Q.predicate(x) & Q.predicate(y) & Q.predicate(z) or its a predicate with three arguments. 

For example, if the sexyprime predicate were to be introduced, it might be ambiguous whether Q.sexyprime(x, y) meant x and y are prime numbers that differ by 6 or whether x and y are prime numbers that differ by 6 from some other prime number and |x-y| might not be 6. `Q.sexyprime` is currently an used as an example in some tests and a docstring as a custom predicate that can be defined.

**Comment by sylee957** [comment]
That may be the reason, but the other aspect to overlook by looking at the example of `sexyprime` is that, 
`nargs` can be less general option than users can be happy with.

For example, `sexyprime` takes 2 or 3 arguments there, and if we have `nargs` option to be a single integer, it isn't be able to set options like 'just 2 or 3 integers', or '2 or more integers'.
I wonder if the numbers of arguments can just be inferred from the functions how users register with `@Predicate.register`.

**Comment by bobby-palmer** [comment]
early on in my PR I had changed the predicate call method to : 
```
    def __call__(self, *args):
        if len(self.handler.funcs):
            if all(len(sig) != len(args) for sig in self.handler.funcs):
                raise TypeError("Invalid number of arguments")
```
Would we want to revert to this idea instead of hard coding the accepted number of arguments?

**Comment by sylee957** [comment]
I think that we may need to get back to https://github.com/sympy/sympy/pull/25338#issuecomment-1626653181
I didn't see any problem of readability of that though.
The end result seems like adding more lines of code than the original one.

**Comment by sylee957** [comment]
Anyway, I'd also find another limitation of using 
`all(len(sig) != len(args) for sig in self.handler.funcs)` though.
It is not possible to register variadic functions with `multipledispatch` because of its fundamental limitation,

And I don't find any urgency to doing this, because any changes seems like involving same new things that users need to be aware of, or configure.
In the previous behavior, users had to confirm the number of arguments themselves without any help from SymPy,
And in this behavor, users anyway have to set the `arity` themselves.

**Comment by TiloRC** [comment]
> I didn't see any problem of readability of that though.

Fair enough. I trust your judgement more than mine. 

>  I am also be concerned that things can start to tear up if users defined things inconsistently (setting arity=1 for sexyprime for example)

Perhaps an exception can be thrown if a predicate is defined with an arity that doesn't match the arity of the handlers. 

> And in the PR, users anyway have to set the arity themselves.

The arity/nargs can be left undefined. It defaults to None in which case any number of arguments is allowed.

**Comment by sylee957** [comment]
I would just cast a neutral vote. 
So it means that I would agree to merge on, if we just want to encourage some new contributions.

**Comment by krishnavbajoria02** [comment]
Is this issue still relevant? Is there anything left to be done here ? 
I tried testing this locally : 
```
>>> x=symbols('z')
>>> x=symbols('x')
>>> z=symbols('z')
>>> print(ask(Q.positive(x,y,z),Q.positive(x) & Q.positive(y) & Q.positive(z)))
True
>>> print(ask(Q.negative(x,y,z),Q.positive(x) & Q.positive(y) & Q.positive(z)))
False
```
These seem to work.

**Comment by krishnavbajoria02** [comment]
I found an interesting case that raises ValueError here : 
```
>>> print(ask(Q.negative(x,y,z),Q.positive(x) & Q.positive(y) & Q.negative(z)))
Traceback (most recent call last):
  File "<python-input-57>", line 1, in <module>
    print(ask(Q.negative(x,y,z),Q.positive(x) & Q.positive(y) & Q.negative(z)))
          ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bajor\AppData\Roaming\Python\Python313\site-packages\sympy\assumptions\ask.py", line 493, in ask
    raise ValueError("inconsistent assumptions %s" % assumptions)
ValueError: inconsistent assumptions Q.negative(z) & Q.positive(x) & Q.positive(y)
```

**Comment by TiloRC** [comment]
> I tried testing this locally
The output you got is because `ask(Q.positive(x,y,z), Q.positive(x))` gives True.

**Comment by asmeurer** [comment]
I really think we should make Q.positive(x, y) an error. We could add an `nargs` attribute to the predicate classes that works the same as with Function (I don't know how straightforward it would be to actually reuse the code there. If it isn't simple we should just duplicate it). 

We could even make it required. That could be a backwards compatibility break, but I'm not sure to what degree custom predicates are considered public API at this point. Certainly if we want to refactor how things like handlers work we should not be thinking too hard about maintaining backwards compatibility with what is there.

**Comment by krishnavbajoria02** [comment]
> > I tried testing this locally
> 
> The output you got is because `ask(Q.positive(x,y,z), Q.positive(x))` gives True.

Sorry I don't understand why this is the reason the inconsistent assumptions error is being raised here. Till I understand about Q.positive(x,y,z) it is more of asking all three x,y and z are positive right ? or am I mistaken there?

**Comment by krishnavbajoria02** [comment]
> I really think we should make Q.positive(x, y) an error. We could add an `nargs` attribute to the predicate classes that works the same as with Function (I don't know how straightforward it would be to actually reuse the code there. If it isn't simple we should just duplicate it).
> 
> We could even make it required. That could be a backwards compatibility break, but I'm not sure to what degree custom predicates are considered public API at this point. Certainly if we want to refactor how things like handlers work we should not be thinking too hard about maintaining backwards compatibility with what is there.

I will check out the implementation once for ```nargs``` as you mentioned. Regarding ```Q.positive(x,y)``` being treated as error should this be done for all types of predicates which are currently supporting multiple args? (ofcourse eliminating ```Q.gt()``` which are basically like binary predicates requiring two arguments for any sort of comparisons to take place).

**Comment by asmeurer** [comment]
`nargs` is a way to specify exactly how many arguments a function should take. See https://docs.sympy.org/latest/modules/core.html#sympy.core.function.FunctionClass.nargs. All predicates including Q.positive and Q.gt could have their number of arguments represented by nargs. Most predicates would have `nargs = 1` but `Q.gt` would have `nargs = 2`, but it also supports listing a tuple of possible argument numbers for more complex cases. 

> Sorry I don't understand why this is the reason the inconsistent assumptions error is being raised here. Till I understand about Q.positive(x,y,z) it is more of asking all three x,y and z are positive right ? or am I mistaken there?

That isn't what it means. Q.positive just happens to accept multiple arguments, but the code assumes that it takes one and only looks at the first argument. So it thinks that `ask(Q.positive(x,y,z), Q.positive(x))` is just `ask(Q.positive(x), Q.positive(x))` because somewhere there is something that just checks `args[0]`. This is why `Q.positive(x, y)` needs to be an error.

**Comment by krishnavbajoria02** [comment]
> `nargs` is a way to specify exactly how many arguments a function should take. See https://docs.sympy.org/latest/modules/core.html#sympy.core.function.FunctionClass.nargs. All predicates including Q.positive and Q.gt could have their number of arguments represented by nargs. Most predicates would have `nargs = 1` but `Q.gt` would have `nargs = 2`, but it also supports listing a tuple of possible argument numbers for more complex cases.

Ohh ok thanks. I got it now. Thanks for the reference, I have quickly glanced through it once. I will see how I can implement it here to fix this issue. 

> That isn't what it means. Q.positive just happens to accept multiple arguments, but the code assumes that it takes one and only looks at the first argument. So it thinks that `ask(Q.positive(x,y,z), Q.positive(x))` is just `ask(Q.positive(x), Q.positive(x))` because somewhere there is something that just checks `args[0]`. This is why `Q.positive(x, y)` needs to be an error.

Ohh I see now where I was making the mistake. But still I dont understand why this will lead to a ValueError like in this statement : 

```
print(ask(Q.negative(x,y,z),Q.positive(x) & Q.positive(y) & Q.negative(z)))
```

Since the above is basically equivalent to this then since only first argument is looked at : 
```
print(ask(Q.negative(x),Q.positive(x) & Q.positive(y) & Q.negative(z))) 
```
it should return ```False``` as the latter statement does but not the former. Can you please clarify a bit on this. Thanks.

**Comment by asmeurer** [comment]
I don't know what's going on there. You'd have to do some debugging to figure it out. My guess is that some part of the code is treating `Q.negative(x, y, z)` the same as `Q.negative(x)` and some other part of the code is not, and it's confusing the solver.

**Comment by krishnavbajoria02** [comment]
I think I seem to have find out the bug that is causing this issue. I added logging steps and turned out that when I printed out the clauses of the local facts that were extracted from this line : 
```
 # extract the relevant facts from assumptions with respect to args
    local_facts = _extract_all_facts(assump_cnf, args)
```
the clauses were as follows as shown below in the first line of the output:
```
>>> print(ask(Q.negative(x,y),Q.positive(x) & Q.negative(y)))
{frozenset({Literal(Q.positive, False)}), frozenset({Literal(Q.negative, False)})}
```
The ```_extract_all_facts``` function extracts both these literals considering them to be associated with only one variable.
