### ISSUE TITLE
How should division of Transfer Functions be handled

### ISSUE THREAD

**Issue by faze-geek** [sympy/sympy#25308]
Phase 2 of my work in `GSOC` deals with improvements in `TransferFunction` methods and API. 

Right now division of Transfer Functions in SymPy leads to a ValueError.

```
>>> tf1 = TransferFunction.from_coeff_lists([1],[1,1],s)            # 1/(s+1)
>>> tf2 = TransferFunction.from_coeff_lists([2],[1,1],s)            # 2/(s+1)
>>> tf = tf1/tf2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kunni\sympy\sympy\sympy\physics\control\lti.py", line 929, in __truediv__
    raise ValueError("TransferFunction cannot be divided by {}.".
ValueError: TransferFunction cannot be divided by <class 'sympy.physics.control.lti.TransferFunction'>.
```
I went through previous discussions when `__truediv__` was implemented for the `TransferFunction` class, but did not find anything to justify it.

Relevant Comment :
1. https://github.com/sympy/sympy/pull/19390#discussion_r442357826

**Comment by faze-geek** [comment]
Relevant control algebra packages handle it as follows:

**MATLAB**
```
>> tf1 = tf([1],[1 1])
>> tf2 = tf([2],[1 1])
>> tf = tf1/tf2

tf =
 
   s + 1
  -------
  2 s + 2
```

**Python-control**
```
>>> tf1 = control.TransferFunction([1],[1,1])
>>> tf2 = control.TransferFunction([2],[1,1])
>>> print(tf1/tf2)

 s + 1
-------
2 s + 2
```

**Comment by faze-geek** [comment]
@Sc0rpi0n101 @Smit-create @moorepants I would like to know your views on it. Thanks !
