### ISSUE TITLE
integrate gives TypeError: Invalid NaN comparison  in Sympy 1.12

### ISSUE THREAD

**Issue by nasser1** [sympy/sympy#25310]
I do not know if this is known issue or not. If it is, feel free to close this.

```
>>> import sympy
>>> sympy.__version__
'1.12'
```

Here is an example

```
>python
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] on linux
>>> import sympy as sp
>>> a,x,b = sp.symbols('a x b')
>>> sp.integrate(a**x/(b**x),x)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 1567, in integrate
    return integral.doit(**doit_flags)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 612, in doit
    antideriv = self._eval_integral(
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 1084, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/heurisch.py", line 158, in heurisch_wrapper
    slns += solve([d], dict=True, exclude=(x,))
  File "/home/me/.local/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1147, in solve
    linear, solution = _solve_system(f, symbols, **flags)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1934, in _solve_system
    soln = _vsolve(eq2, s, **flags)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 2606, in _vsolve
    return [i[s] for i in _solve(e, s, **flags)]
  File "/home/me/.local/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1714, in _solve
    result = [r for r in result if
  File "/home/me/.local/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1715, in <listcomp>
    checksol(f_num, r, **flags) is not False]
  File "/home/me/.local/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 360, in checksol
    return (abs(val.n(18).n(12, chop=True)) < 1e-9) is S.true
  File "/home/me/.local/lib/python3.10/site-packages/sympy/core/decorators.py", line 236, in _func
    return func(self, other)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/core/expr.py", line 376, in __lt__
    return StrictLessThan(self, other)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/core/relational.py", line 824, in __new__
    raise TypeError("Invalid NaN comparison")
TypeError: Invalid NaN comparison

```

The result of integration should be

```
int(a^x/(b^x),x)
a^x/(b^x)/(ln(a)-ln(b))

```

**Comment by oscarbenjamin** [comment]
The underlying problem is with solve:
```python
solve(b**x*log(a) - b**x*log(b), b  # TypeError: Invalid NaN comparison
```
In turn that comes from `checksol`:
```python
In [39]: eq = b**x*log(a) - b**x*log(b)

In [40]: sol = {b: 0**(1/x)}

In [41]: checksol(eq, sol)
---------------------------------------------------------------------------
TypeError 
```
Probably `checksol` should reject this rather than raising an error. Perhaps it should catch this exception. Separately maybe `solve` should not generate this candidate solution.

**Comment by u7465990** [comment]
May I get this issue?
