### ISSUE TITLE
sympy integrate gives ValueError: Non-suitable parameters in V 12.1 from hyperexpand.py

### ISSUE THREAD

**Issue by nasser1** [sympy/sympy#25314]
This integral should give the value (per Maple)

```
integrand:=1/2/(1+x)^2/(-I+x^2)^(1/2)
int(integrand,x)

(-1/4-1/4*I)/(1+x)*((1+x)^2-1-I-2*x)^(1/2)-(1/4+1/4*I)/(1-I)^(1/2)*ln((-2*I-2*x+2*(1-I)^(1/2)*((1+x)^2-1-I-2*x)^(1/2))/(1+x))

```

In symy 12.1 it gives this exception

```
python
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy import *
>>> x = symbols('x')
>>> integrate(1/2/(1+x)**2/(-I+x**2)**(1/2),x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 1567, in integrate
    return integral.doit(**doit_flags)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 612, in doit
    antideriv = self._eval_integral(
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/integrals.py", line 1098, in _eval_integral
    h = meijerint_indefinite(g, x)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/meijerint.py", line 1668, in meijerint_indefinite
    res = _meijerint_indefinite_1(f.subs(x, x + a), x)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/meijerint.py", line 1694, in _meijerint_indefinite_1
    gs = _rewrite1(f, x)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/meijerint.py", line 1618, in _rewrite1
    g = _rewrite_single(g, x, recursive)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/meijerint.py", line 1572, in _rewrite_single
    F, strip, _ = mellin_transform(f, x, s, integrator=my_integrator,
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/transforms.py", line 405, in mellin_transform
    return MellinTransform(f, x, s).doit(**hints)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/transforms.py", line 161, in doit
    fn, T = self._try_directly(**hints)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/transforms.py", line 125, in _try_directly
    T = self._compute_transform(self.function,
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/transforms.py", line 344, in _compute_transform
    return _mellin_transform(f, x, s, **hints)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/transforms.py", line 245, in wrapper
    res = func(*args, **kwargs)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/transforms.py", line 268, in _mellin_transform
    F = integrator(x**(s - 1) * f, x)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/integrals/meijerint.py", line 1567, in my_integrator
    res = _my_unpolarify(hyperexpand(res, rewrite='nonrepsmall'))
  File "/home/me/.local/lib/python3.10/site-packages/sympy/simplify/hyperexpand.py", line 2494, in hyperexpand
    return f.replace(hyper, do_replace).replace(meijerg, do_meijer)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/core/basic.py", line 1666, in replace
    rv = walk(self, rec_replace)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/core/basic.py", line 1641, in walk
    newargs = tuple([walk(a, F) for a in args])
  File "/home/me/.local/lib/python3.10/site-packages/sympy/core/basic.py", line 1641, in <listcomp>
    newargs = tuple([walk(a, F) for a in args])
  File "/home/me/.local/lib/python3.10/site-packages/sympy/core/basic.py", line 1651, in walk
    rv = F(rv)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/core/basic.py", line 1659, in rec_replace
    v = _value(expr, result)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/core/basic.py", line 1588, in <lambda>
    _value = lambda expr, result: value(*expr.args)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/simplify/hyperexpand.py", line 2490, in do_meijer
    r = _meijergexpand(G_Function(ap[0], ap[1], bq[0], bq[1]), z,
  File "/home/me/.local/lib/python3.10/site-packages/sympy/simplify/hyperexpand.py", line 2375, in _meijergexpand
    slater2, cond2 = do_slater(tr(func.bm), tr(func.an), tr(func.bq), tr(func.ap),
  File "/home/me/.local/lib/python3.10/site-packages/sympy/simplify/hyperexpand.py", line 2301, in do_slater
    hyp = _hyperexpand(Hyper_Function(nap, nbq), harg, ops,
  File "/home/me/.local/lib/python3.10/site-packages/sympy/simplify/hyperexpand.py", line 2053, in _hyperexpand
    ops += devise_plan(func, formula.func, z0)
  File "/home/me/.local/lib/python3.10/site-packages/sympy/simplify/hyperexpand.py", line 1634, in devise_plan
    raise ValueError('Non-suitable parameters.')
ValueError: Non-suitable parameters.
>>> 



```

**Comment by oscarbenjamin** [comment]
The problem is in `hyperexpand` and is caused by having floats somehow:
```python
In [64]: e = meijerg(((1 - x/2, S(1)/2 - x/2, y), ()), ((S(3)/2 - x/2, 1 - x/2, 0), ()), exp_polar(0)
    ...: *exp_polar(I*pi/2))

In [65]: print(e)
meijerg(((1 - x/2, 1/2 - x/2, y), ()), ((3/2 - x/2, 1 - x/2, 0), ()), exp_polar(0)*exp_polar(I*pi/2))

In [66]: e
Out[66]: 
        ⎛    x  1   x       │        ⎞
        ⎜1 - ─, ─ - ─, y    │     ⅈ⋅π⎟
╭─╮3, 3 ⎜    2  2   2       │     ───⎟
│╶┐     ⎜                   │  0   2 ⎟
╰─╯3, 3 ⎜3   x      x       │ ℯ ⋅ℯ   ⎟
        ⎜─ - ─, 1 - ─, 0    │        ⎟
        ⎝2   2      2       │        ⎠

In [67]: hyperexpand(e.subs(y, S(1)/2))
Out[67]: 
        ⎛    x  1   x         │        ⎞
        ⎜1 - ─, ─ - ─, 1/2    │     ⅈ⋅π⎟
╭─╮3, 3 ⎜    2  2   2         │     ───⎟
│╶┐     ⎜                     │  0   2 ⎟
╰─╯3, 3 ⎜ 3   x      x        │ ℯ ⋅ℯ   ⎟
        ⎜ ─ - ─, 1 - ─, 0     │        ⎟
        ⎝ 2   2      2        │        ⎠

In [68]: hyperexpand(e.subs(y, 1/2))
---------------------------------------------------------------------------
ValueError
```
Removing floats from the original integral means that `meijerint` does not raise an exception but also does not compute a result. That leads to a different exception from manualintegrate:
```python
>>> integrate(S(1)/2/(1+x)**2/(-I+x**2)**(S(1)/2),x)
...
TypeError: Invalid comparison of non-real -I
```
That comes from:
https://github.com/sympy/sympy/blob/28276a5a18653903e360002ee9f911074b139d86/sympy/integrals/manualintegrate.py#L1801

CC @eagleoflqj

**Comment by oscarbenjamin** [comment]
> That comes from:

A simple fix would be to change `is_number` to `is_comparable` since that implies real. Even simpler would just be to avoid using `a > 0` since if `a.is_positive` is true then `a > 0` will be true.

The better fix would then be to adapt the code to be able to handle the general complex case.
