### ISSUE TITLE
Can't compute roots of y**3 - 6*y**2 + 11.25*y-6.25

### ISSUE THREAD

**Issue by RagonEbker** [sympy/sympy#25316]
When calculating the roots of y**3 - 6*y**2 + 11.25*y-6.25, sympy throws the error:

`Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/sympy/polys/polytools.py", line 3695, in nroots
    roots = mpmath.polyroots(coeffs, maxsteps=maxsteps,
  File "/home/pi/.local/lib/python3.10/site-packages/mpmath/calculus/polynomials.py", line 196, in polyroots
    raise ctx.NoConvergence("Didn't converge in maxsteps=%d steps." \
mpmath.libmp.libhyper.NoConvergence: Didn't converge in maxsteps=50 steps.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/sympy/polys/polytools.py", line 3705, in nroots
    roots = mpmath.polyroots(coeffs, maxsteps=maxsteps,
  File "/home/pi/.local/lib/python3.10/site-packages/mpmath/calculus/polynomials.py", line 196, in polyroots
    raise ctx.NoConvergence("Didn't converge in maxsteps=%d steps." \
mpmath.libmp.libhyper.NoConvergence: Didn't converge in maxsteps=50 steps.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.local/lib/python3.10/site-packages/sympy/polys/polyroots.py", line 1086, in roots
    for r in f.nroots():
  File "/home/pi/.local/lib/python3.10/site-packages/sympy/polys/polytools.py", line 3710, in nroots
    raise NoConvergence(
mpmath.libmp.libhyper.NoConvergence: convergence to root failed; try n < 15 or maxsteps > 50`

**Comment by bjodah** [comment]
What command did you use to compute the roots? `.all_roots` seems to work fine for me:

```pycon
>>> import sympy as sy
>>> y=sy.Symbol('y')
>>> p = sy.Poly(y**3 - 6*y**2 + 11.25*y-6.25) 
>>> p.all_roots()
[1, 5/2, 5/2]
```

**Comment by RagonEbker** [comment]
Hello Bjorn,

thank you for your comments and sorry for not specifying the comment. It is `roots(Poly(y**3 - 6*y**2 + 11.25*y-6.25,y))`.

**Comment by oscarbenjamin** [comment]
Alternatively:
```python
nroots(y**3 - 6*y**2 + 11.25*y-6.25)
...
NoConvergence: convergence to root failed; try n < 15 or maxsteps > 50
```
The failure happens because `nroots` attempts higher and higher precision and at some point gives up. The error message says to either ask for a lower precision (`n < 15`) or allow more iterations in the underlying `mpmath` routine (`maxsteps > 50`):
```python
In [4]: nroots(y**3 - 6*y**2 + 11.25*y-6.25, maxsteps=1000)
Out[4]: [1.0, 2.49999999999993, 2.50000000000044]
```
The reason that mpmath is used here is because of the float coefficients. With exact rational numbers the result would be found easily using exact methods:
```python
In [5]: roots(nsimplify(y**3 - 6*y**2 + 11.25*y-6.25))
Out[5]: {1: 1, 5/2: 2}
```
The floats lead to mpmath being used which uses approximate routines. Any approximate routines will always struggle with multiple roots because only exact arithmetic can distinguish a multiple root from two nearby real or nonreal roots.

There are a number of possible approaches that could be used:

1. Convert floats to rational (like `all_roots` does) and use the exact routines (but convert back to float at the end).
2. Convert floats to rational, compute the square free factorisation (to remove multiple roots) and then call the mpmath routine.

The situation in which `nroots` is the preferable method (rather than `all_roots` or `roots`) is where the coefficients are numeric but are not simple numbers. The `all_roots` method will always work for rational numbers and does a reasonable job for floats. When you have expressions like `sin(1)` in the coefficients then only `nroots` can find the roots numerically.

The square free factorisation is computed with `sqf` or `sqf_list`:
```python
In [9]: sqf_list(y**3 - 6*y**2 + 11.25*y-6.25)
Out[9]: (1.0, [(1.0⋅y - 1.0, 1), (1.0⋅y - 2.5, 2)])
```
Probably `nroots` should use that before calling into mpmath but I think it should go via rationals to compute the factorisation:
```python
In [19]: coeff, factors = sqf_list(nsimplify(y**3 - 6*y**2 + 11.25*y-6.25))

In [20]: factors
Out[20]: [(y - 1, 1), (2⋅y - 5, 2)]

In [22]: [(nroots(fac), mul) for fac, mul in factors]
Out[22]: [([1.0], 1), ([2.5], 2)]
```
That should be done only if the coefficients are floats or a mix of float rational. I am not sure if square free factorisation should be attempted in the case of more complicated expressions e.g.:
```python
In [23]: p = expand((x - sqrt(2))**2*(x - 1))

In [24]: p
Out[24]: 
 3         2    2                   
x  - 2⋅√2⋅x  - x  + 2⋅x + 2⋅√2⋅x - 2

In [25]: nroots(p)
Out[25]: [1.0, 1.41421352006887, 1.41421360467732]
```
The advantage of `nroots` for this case is precisely that it does not attempt any potentially slow symbolic manipulation.
