### ISSUE TITLE
Cannot match Piecewise with `replace`

### ISSUE THREAD

**Issue by lezcano** [sympy/sympy#25328]
Repro:
```python
 from sympy import Piecewise, Symbol, Wild

q0 = Symbol("q0")
expr = Piecewise((15 - q0, q0 > 7), (7 - q0, True))

def fn(a, b, c):
    return Piecewise((a, b), (c, True))

expr.replace(Piecewise((Wild("a"), Wild("b")), (Wild("c"), True)), fn)
```

cc @asmeurer

**Comment by asmeurer** [comment]
This is the traceback

``pytb
>>> expr.replace(pattern, fn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/core/basic.py", line 1666, in replace
    rv = walk(self, rec_replace)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/core/basic.py", line 1651, in walk
    rv = F(rv)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/core/basic.py", line 1659, in rec_replace
    v = _value(expr, result)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/core/basic.py", line 1613, in <lambda>
    if all(val for val in result.values()) else expr)
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/./sympy/core/relational.py", line 510, in __bool__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational
```

The issue is this line https://github.com/sympy/sympy/blob/e0784102f7b5a1172d2313d8a86d5ea51c3ec841/sympy/core/basic.py#L1613

From the comment, it is trying to filter out "null values" when exact=True. This presumably means `None`, but it is calling `bool` on the results directly, which ends up failing when it is a SymPy Relational. It would be good to confirm that this analysis is correct, but assuming it is, this should be as simple as making sure the above code uses `val is None` instead of just `val` in the `all()` call.
