### ISSUE TITLE
CoercionFailed on eq: 2*sqrt(x)/(x + 1)**2 - 1/(sqrt(x)*(x + 1)) - 1/(4*x**(3/2)))/(x + 1) = 0

### ISSUE THREAD

**Issue by satels** [sympy/sympy#25341]
```python
from sympy import Eq, Rational, sqrt
from sympy.abc import x


eq = Eq((2*sqrt(x)/(x + 1)**2 - 1/(sqrt(x)*(x + 1)) - 1/(4*x**(Rational(3, 2))))/(x + 1), 0)

eq.simplify()
```

The error:
```
Traceback (most recent call last):
  File "test_equation.py", line 7, in <module>
    eq.simplify()
  File "/env/lib/python3.10/site-packages/sympy/core/basic.py", line 1853, in simplify
    return simplify(self, **kwargs)
  File "/env/lib/python3.10/site-packages/sympy/simplify/simplify.py", line 601, in simplify
    return _eval_simplify(**kwargs)
  File "/env/lib/python3.10/site-packages/sympy/core/relational.py", line 679, in _eval_simplify
    e = super()._eval_simplify(**kwargs)
  File "/env/lib/python3.10/site-packages/sympy/core/relational.py", line 456, in _eval_simplify
    p = poly(dif, x)
  File "/env/lib/python3.10/site-packages/sympy/polys/polytools.py", line 7388, in poly
    return _poly(expr, opt)
  File "/env/lib/python3.10/site-packages/sympy/polys/polytools.py", line 7334, in _poly
    poly_factors.append(_poly(factor, opt))
  File "/env/lib/python3.10/site-packages/sympy/polys/polytools.py", line 7354, in _poly
    product = product.mul(factor)
  File "/env/lib/python3.10/site-packages/sympy/polys/polytools.py", line 1507, in mul
    return f.mul_ground(g)
  File "/env/lib/python3.10/site-packages/sympy/polys/polytools.py", line 1324, in mul_ground
    result = f.rep.mul_ground(coeff)
  File "/env/lib/python3.10/site-packages/sympy/polys/polyclasses.py", line 426, in mul_ground
    return f.per(dmp_mul_ground(f.rep, f.dom.convert(c), f.lev, f.dom))
  File "/env/lib/python3.10/site-packages/sympy/polys/domains/domain.py", line 451, in convert
    return self.from_sympy(element)
  File "/env/lib/python3.10/site-packages/sympy/polys/domains/integerring.py", line 64, in from_sympy
    raise CoercionFailed("expected an integer, got %s" % a)
sympy.polys.polyerrors.CoercionFailed: expected an integer, got -1/4

```

**Comment by oscarbenjamin** [comment]
This happens while trying to convert an expression to `Poly` in `poly` here:
https://github.com/sympy/sympy/blob/d59d9bd65c552ddc763071def5893f231c1f8294/sympy/polys/polytools.py#L7647-L7650
The code tries to take a shortcut if the `Expr` is `Number` which is a common case. However it fails if the domain is `ZZ` but the expr is `Rational`:
```python
In [1]: Poly(x)
Out[1]: Poly(x, x, domain='ZZ')

In [2]: Poly(x) * Rational(1, 4)
Out[2]: Poly(1/4*x, x, domain='QQ')

In [3]: Poly(x).mul(Rational(1, 4))
---------------------------------------------------------------------------
CoercionFailed 
```
It is not very well defined what the expectations are at different levels here. When the `expr` is not `Number`, `Poly._from_expr` is used. Otherwise `mul` is passed the input directly.

Should it be the job of `poly` to ensure that `mul` gets appropriate input? The waters are muddied by the fact that `mul` calls `sympify` and `unify`:
https://github.com/sympy/sympy/blob/d59d9bd65c552ddc763071def5893f231c1f8294/sympy/polys/polytools.py#L1504-L1509
Should the expectation be that the input to `mul` is either a `Poly` or an `Expr` that can be converted to the ground domain? I think maybe the answer is that is should be the job of `poly` to get this right before calling `mul` so the shortcut taken in `poly` needs to be guarded.

The fix is:
```diff
diff --git a/sympy/polys/polytools.py b/sympy/polys/polytools.py
index 48887be060..33c6c145ba 100644
--- a/sympy/polys/polytools.py
+++ b/sympy/polys/polytools.py
@@ -7353,7 +7353,7 @@ def _poly(expr, opt):
                 if factors:
                     factor = Mul(*factors)
 
-                    if factor.is_Number:
+                    if factor.is_Number and factor in product.domain:
                         product = product.mul(factor)
                     else:
                         product = product.mul(Poly._from_expr(factor, opt))
```
That gives:
```python
In [1]: from sympy import Eq, Rational, sqrt
   ...: from sympy.abc import x
   ...: 
   ...: 
   ...: eq = Eq((2*sqrt(x)/(x + 1)**2 - 1/(sqrt(x)*(x + 1)) - 1/(4*x**(Rational(3, 2))))/(x + 1), 0)
   ...: 
   ...: eq.simplify()
Out[1]: 
                          2    
   2               (x + 1)     
2⋅x  - x⋅(x + 1) - ────────    
                      4        
─────────────────────────── = 0
        3/2        3           
       x   ⋅(x + 1)
```
