### ISSUE TITLE
SymPy numbers and NumPy interoperability

### ISSUE THREAD

**Issue by idanpa** [sympy/sympy#25432]
Is there a way I could configure NumPy or SymPy so that NumPy functions would accept SymPy numbers (e.g. sympy.Rational)?

For example:
```python
>>> import numpy as np
>>> import sympy
>>> np.linspace(0, sympy.Rational(1,2), 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 180, in linspace
  File "C:\Users\idank\mambaforge\lib\site-packages\numpy\core\function_base.py", line 130, in linspace
    dt = result_type(start, stop, float(num))
  File "<__array_function__ internals>", line 180, in result_type
TypeError: Cannot interpret '0.500000000000000' as a data type

>>> np.isnan(sympy.Rational(1,2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Background:
I'm using IPython+SymPy+NumPy as a calculator ([details](https://github.com/idanpa/calcpy)).
For convenience, I automatically convert all divisions and floats to sympy.Rational
(and display results both as fractions and as decimals)
After such conversions stuff like np.log(2.33) fails.

(SymPy version 1.12, NumPy version 1.25.1)

From the discussion: https://groups.google.com/g/sympy/c/dNyL-zvmA1I

**Comment by oscarbenjamin** [comment]
I don't think there is anything that sympy can do here. The obvious thing would be for numpy to use the `__float__` method but it isn't used and numpy has not defined any other method that sympy could add to the types to make it work. Something would have to change in numpy before sympy could do anything about this.

**Comment by asmeurer** [comment]
Are you sure about that. I think defining `__array__` on Number would work.

**Comment by idanpa** [comment]
As @asmeurer suggested, I used the documentation:
[Interoperability with NumPy — NumPy v1.25 Manual](https://numpy.org/doc/stable/user/basics.interoperability.html)
And managed to solve this by adding this method to `Rational`:
```python
def __array__(self):
    from numpy import array
    return array(float(self))
```
(a real solution would probably need to support `dtype` argument)

BTW - I see that `MatrixBase` is already doing something like that.

Should I write and send a pull-request of a full solution?

**Comment by bjodah** [comment]
I'm -1 to adding __array__ to `Rational`. At least if it converts it to floating point number. I oftentimes put SymPy objects in NumPy arrays with the implicit `dtype=object` (nowadays perhaps out NDimensionalArray is a better fit, but back when I tried it, it wouldn't play nice for my purposes...).

**Comment by idanpa** [comment]
> I'm -1 to adding `__array__` to `Rational`. At least if it converts it to floating point number. I oftentimes put SymPy objects in NumPy arrays with the implicit `dtype=object` (nowadays perhaps our NDimensionalArray is a better fit, but back when I tried it, it wouldn't play nice for my purposes...).

@bjodah , how about something like this:
```python
def __array__(self, dtype=float):
    from numpy import empty
    a = empty((), dtype=dtype)
    if dtype==object:
        a[()] = self
    else:
        a[()] = float(self)
    return a
```
and then we can both be happy:
``` python
In [2]: np.array(sympy.Rational(1,2))
Out[2]: array(0.5)
In [3]: np.array(sympy.Rational(1,2), dtype=object)
Out[3]: array(1/2, dtype=object)
```

(need to refine casting and typing, just as a general idea)

**Comment by bjodah** [comment]
@idanpa, that's a lot better. :-)

I'm unsure about the dtype default, but if NumPy has any guidance we should follow that. Then there's the question of adding this consistently to all SymPy objects. I'd expect an instance of sympy's `Tuple` to also support this type of conversion if `Rational` does, but then the `Tuple` is likely to contain arbitrary expressions.

Then there's the question of whether the NumPy interop belongs on the SymPy classes themselves. Is there a risk of it becoming a slippery slope with e.g. pytorch wanting equivalent methods (I'm just guessing, I know nothing about pytorch)?

**Comment by asmeurer** [comment]
> (need to refine casting and typing, just as a general idea)

Yes, we'd want to actually use the dtype that is passed in, rather than `float` (`dtype=None` means `np.float64`).

This does still somewhat break backwards compatibility for people who are using SymPy objects in NumPy arrays.

But in general with NumPy if you actually do expect your array to have object dtype it's always good idea to explicitly specify `dtype=object` because you never know when your object might unexpectedly be treated as an array-like and cast to something else instead.

> I'm unsure about the dtype default, but if NumPy has any guidance we should follow that. Then there's the question of adding this consistently to all SymPy objects. I'd expect an instance of sympy's Tuple to also support this type of conversion if Rational does, but then the Tuple is likely to contain arbitrary expressions.

Not sure if I agree with that. For me, this really only makes sense on Number. I don't like the idea of trying to make NumPy work with more general SymPy classes (except maybe also the SymPy NDArray class just because it should work like an array).

> Then there's the question of whether the NumPy interop belongs on the SymPy classes themselves. Is there a risk of it becoming a slippery slope with e.g. pytorch wanting equivalent methods (I'm just guessing, I know nothing about pytorch)?

NumPy is rather unique in trying to accept anything and everything. No other array library has object dtypes, and most don't even accept "array-likes" like lists of floats outside of constructors. For example:

```py
>>> import torch
>>> torch.sin([1.0, 2.0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sin(): argument 'input' (position 1) must be Tensor, not list
```

This sort of thing is much cleaner from a typing perspective, and it removes a lot of potential errors and ambiguities that can come from being excessively lenient with typing. The NumPy way does have an advantage in that it allows interoperability with may custom types, which is the main thing we'd want to take advantage of here.
