### ISSUE TITLE
Failures with bin/doctest and master

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#25477]
I ran the doctests locally with `bin/doctest` while working on gh-25474 and found some fails. Those fails also show on master though. This is the output of `bin/doctest sympy` on master when running with `gmpy2` installed:
```console
$ bin/doctest sympy
======================================== test process starts ========================================
executable:         /home/oscar/.pyenv/versions/sympy-3.11.git/bin/python  (3.11.3-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       gmpy 2.1.5
numpy:              1.24.3
hash randomization: on (PYTHONHASHSEED=1055138358)

examples/advanced/gibbs_phenomenon.py[2] ..                                                      [OK]
sympy/abc.py[1] .                                                                                [OK]
sympy/algebras/quaternion.py[34] ..................................                              [OK]
...
sympy/ntheory/bbp_pi.py[1] .                                                                     [OK]
sympy/ntheory/continued_fraction.py[5] .....                                                     [OK]
sympy/ntheory/digits.py[3] ...                                                                   [OK]
sympy/ntheory/ecm.py[4] F...                                                                   [FAIL]
sympy/ntheory/egyptian_fraction.py[1] .                                                          [OK]
sympy/ntheory/elliptic_curve.py[8] ........                                                      [OK]
sympy/ntheory/factor_.py[37] .....................................                               [OK]
sympy/ntheory/generate.py[18] ..................                                                 [OK]
sympy/ntheory/modular.py[5] ..F..                                                              [FAIL]
sympy/ntheory/multinomial.py[4] ....                                                             [OK]
sympy/ntheory/partitions_.py[1] .                                                                [OK]
sympy/ntheory/primetest.py[10] ..........                                                        [OK]
sympy/ntheory/qs.py[2] ..                                                                        [OK]
sympy/ntheory/residue_ntheory.py[26] ..........................                                  [OK]
sympy/parsing/autolev/__init__.py[1] .                                                           [OK]
sympy/parsing/latex/__init__.py[1] .                                                             [OK]
sympy/parsing/mathematica.py[1] .                                                                [OK]
sympy/parsing/sympy_parser.py[8] ........                                                        [OK]
sympy/physics/continuum_mechanics/beam.py[43] ..............F............................      [FAIL]
sympy/physics/continuum_mechanics/cable.py[5] .....                                              [OK]
sympy/physics/continuum_mechanics/truss.py[13] /home/oscar/current/active/sympy/sympy/plotting/series.py:1102: RuntimeWarning: invalid value encountered in scalar divide
  cos_theta = dot_product / (vector_a_norm * vector_b_norm)
F............                                   [FAIL]
sympy/physics/control/control_plots.py[11] ...........                                           [OK]
sympy/physics/control/lti.py[60] ............................................................    [OK]
sympy/physics/hep/gamma_matrices.py[6] ......                                                    [OK]
...
_____________________________________________________________________________________________________
_______________________________________ sympy.ntheory.ecm.ecm _______________________________________
File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 328, in sympy.ntheory.ecm.ecm
Failed example:
    ecm(25645121643901801)
Exception raised:
    Traceback (most recent call last):
      File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 344, in ecm
        factor = _ecm_one_factor(n, B1, B2, max_curve, seed + n)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 216, in _ecm_one_factor
        randint = _randint(seed)
                  ^^^^^^^^^^^^^^
      File "/home/oscar/current/active/sympy/sympy/core/random.py", line 227, in _randint
        raise ValueError('_randint got an unexpected seed')
    ValueError: _randint got an unexpected seed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/oscar/.pyenv/versions/3.11.3/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest sympy.ntheory.ecm.ecm[1]>", line 1, in <module>
        ecm(25645121643901801)
      File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 346, in ecm
        raise ValueError("Increase the bounds")
    ValueError: Increase the bounds
**********************************************************************
File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 330, in sympy.ntheory.ecm.ecm
Failed example:
    ecm(9804659461513846513)
Exception raised:
    Traceback (most recent call last):
      File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 344, in ecm
        factor = _ecm_one_factor(n, B1, B2, max_curve, seed + n)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 216, in _ecm_one_factor
        randint = _randint(seed)
                  ^^^^^^^^^^^^^^
      File "/home/oscar/current/active/sympy/sympy/core/random.py", line 227, in _randint
        raise ValueError('_randint got an unexpected seed')
    ValueError: _randint got an unexpected seed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/oscar/.pyenv/versions/3.11.3/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest sympy.ntheory.ecm.ecm[2]>", line 1, in <module>
        ecm(9804659461513846513)
      File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 346, in ecm
        raise ValueError("Increase the bounds")
    ValueError: Increase the bounds
_____________________________________________________________________________________________________
____________________________________ sympy.ntheory.modular.crt1 _____________________________________
File "/home/oscar/current/active/sympy/sympy/ntheory/modular.py", line 127, in sympy.ntheory.modular.crt1
Failed example:
    for v in vs:
        print(crt2(m, v, mm, e, s))
Expected:
    (397042, 912285)
    (803206, 912285)
Got:
    (mpz(397042), mpz(912285))
    (mpz(803206), mpz(912285))
_____________________________________________________________________________________________________
_________________________ sympy.physics.continuum_mechanics.beam.Beam.draw __________________________
File "/home/oscar/current/active/sympy/sympy/physics/continuum_mechanics/beam.py", line 2149, in sympy.physics.continuum_mechanics.beam.Beam.draw
Failed example:
    p
Expected:
    Plot object containing:
    [0]: cartesian line: 25*SingularityFunction(x, 5, 0) - 25*SingularityFunction(x, 23, 0)
    + SingularityFunction(x, 30, 1) - 20*SingularityFunction(x, 50, 0)
    - SingularityFunction(x, 50, 1) + 5 for x over (0.0, 50.0)
    [1]: cartesian line: 5 for x over (0.0, 50.0)
Got:
    Plot object containing:
    [0]: cartesian line: 25*SingularityFunction(x, 5, 0) - 25*SingularityFunction(x, 23, 0) + SingularityFunction(x, 30, 1) - 20*SingularityFunction(x, 50, 0) - SingularityFunction(x, 50, 1) + 5 for x over (0.0, 50.0)
    [1]: cartesian line: 5 for x over (0.0, 50.0)
    [2]: <sympy.plotting.series.GenericDataSeries object at 0x7f19bcb1a8d0>
    [3]: <sympy.plotting.series.GenericDataSeries object at 0x7f19b7b62290>
    [4]: <sympy.plotting.series.GenericDataSeries object at 0x7f19b7a1bcd0>
    [5]: <sympy.plotting.series.GenericDataSeries object at 0x7f19bcb19b90>
    [6]: <sympy.plotting.series.GenericDataSeries object at 0x7f19c0557b10>
    [7]: <sympy.plotting.series.GenericDataSeries object at 0x7f19c0476050>
    [8]: <sympy.plotting.series.GenericDataSeries object at 0x7f19becf1350>
    [9]: <sympy.plotting.series.GenericDataSeries object at 0x7f19becf1310>
_____________________________________________________________________________________________________
________________________ sympy.physics.continuum_mechanics.truss.Truss.draw _________________________
File "/home/oscar/current/active/sympy/sympy/physics/continuum_mechanics/truss.py", line 809, in sympy.physics.continuum_mechanics.truss.Truss.draw
Failed example:
    p
Expected:
    Plot object containing:
    [0]: cartesian line: 1 for x over (1.0, 1.0)
Got:
    Plot object containing:
    [0]: cartesian line: 1 for x over (1.0, 1.0)
    [1]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc0fd0>
    [2]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc24d0>
    [3]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc1890>
    [4]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc1490>
    [5]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc3d50>
    [6]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc3e50>
    [7]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc3210>
    [8]: <sympy.plotting.series.GenericDataSeries object at 0x7f19bcaf3510>
    [9]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc3a50>
    [10]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc0790>
    [11]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc0810>
    [12]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc2250>
    [13]: <sympy.plotting.series.GenericDataSeries object at 0x7f19c0f8bf50>
    [14]: <sympy.plotting.series.GenericDataSeries object at 0x7f19c0f8b710>
    [15]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc1910>
    [16]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc3e90>
    [17]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc1650>
    [18]: <sympy.plotting.series.GenericDataSeries object at 0x7f19befc1ad0>
    [19]: <sympy.plotting.series.GenericDataSeries object at 0x7f19c0416350>
    [20]: <sympy.plotting.series.GenericDataSeries object at 0x7f19c0415b10>
    [21]: <sympy.plotting.series.GenericDataSeries object at 0x7f19c0415c10>
    [22]: <sympy.plotting.series.GenericDataSeries object at 0x7f19c0414850>
    [23]: <sympy.plotting.series.GenericDataSeries object at 0x7f19c04156d0>
    [24]: <sympy.plotting.series.GenericDataSeries object at 0x7f19c0415a10>
    [25]: <sympy.plotting.series.GenericDataSeries object at 0x7f19c0414710>

================ tests finished: 4334 passed, 4 failed, 8 skipped, in 639.11 seconds ================
DO *NOT* COMMIT!
======================================= rst/md doctests start =======================================

doc/src/contributing/dependencies.md [2]                                                         [OK]
doc/src/contributing/docstring.rst [24]                                                          [OK]
...
**********************************************************************
File "/home/oscar/current/active/sympy/doc/src/modules/ntheory.rst", line 227, in ntheory.rst
Failed example:
    ecm(7060005655815754299976961394452809, B1=100000, B2=1000000)
Exception raised:
    Traceback (most recent call last):
      File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 344, in ecm
        factor = _ecm_one_factor(n, B1, B2, max_curve, seed + n)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 216, in _ecm_one_factor
        randint = _randint(seed)
                  ^^^^^^^^^^^^^^
      File "/home/oscar/current/active/sympy/sympy/core/random.py", line 227, in _randint
        raise ValueError('_randint got an unexpected seed')
    ValueError: _randint got an unexpected seed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/oscar/.pyenv/versions/3.11.3/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest ntheory.rst[1]>", line 1, in <module>
        ecm(7060005655815754299976961394452809, B1=100000, B2=1000000)
      File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 346, in ecm
        raise ValueError("Increase the bounds")
    ValueError: Increase the bounds
**********************************************************************
File "/home/oscar/current/active/sympy/doc/src/modules/ntheory.rst", line 229, in ntheory.rst
Failed example:
    ecm(122921448543883967430908091422761898618349713604256384403202282756086473494959648313841, B1=100000, B2=1000000)
Exception raised:
    Traceback (most recent call last):
      File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 344, in ecm
        factor = _ecm_one_factor(n, B1, B2, max_curve, seed + n)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 216, in _ecm_one_factor
        randint = _randint(seed)
                  ^^^^^^^^^^^^^^
      File "/home/oscar/current/active/sympy/sympy/core/random.py", line 227, in _randint
        raise ValueError('_randint got an unexpected seed')
    ValueError: _randint got an unexpected seed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/oscar/.pyenv/versions/3.11.3/lib/python3.11/doctest.py", line 1351, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest ntheory.rst[2]>", line 1, in <module>
        ecm(122921448543883967430908091422761898618349713604256384403202282756086473494959648313841, B1=100000, B2=1000000)
      File "/home/oscar/current/active/sympy/sympy/ntheory/ecm.py", line 346, in ecm
        raise ValueError("Increase the bounds")
    ValueError: Increase the bounds
**********************************************************************
1 items had failures:
   2 of   5 in ntheory.rst
***Test Failed*** 2 failures.
doc/src/modules/ntheory.rst [5]                                                                   [2]
doc/src/modules/physics/continuum_mechanics/beam_problems.rst [198]                              [OK]
doc/src/modules/physics/mechanics/advanced.rst [7]                                               [OK]
doc/src/modules/physics/mechanics/examples/bicycle_example.rst [87]                              [OK]
^[[6~doc/src/modules/physics/mechanics/examples/four_bar_linkage_example.rst [22]                     [OK]
doc/src/modules/physics/mechanics/examples/lin_pend_nonmin_example.rst [53]                      [OK]
doc/src/modules/physics/mechanics/examples/multi_degree_freedom_holonomic_system.rst [29]        [OK]
doc/src/modules/physics/mechanics/examples/rollingdisc_example_kane.rst [31]                     [OK]
doc/src/modules/physics/mechanics/examples/rollingdisc_example_kane_constraints.rst [34]         [OK]
doc/src/modules/physics/mechanics/examples/rollingdisc_example_lagrange.rst [24]                 [OK]
doc/src/modules/physics/mechanics/joints.rst [15]                                                [OK]
...

DO *NOT* COMMIT!
```

**Comment by oscarbenjamin** [comment]
@haru-44 the ntheory failures are related to having gmpy2 installed: the stdlib random functions do not accept `gmpy.mpz` e.g. for the see argument. Are these failures related to any recent change?

**Comment by oscarbenjamin** [comment]
@Davide-sd are the plotting doctest fails related to recent changes in the plotting module? It seems like more output is shown when printing a plot object or something...

**Comment by oscarbenjamin** [comment]
@brocksam I am wondering why these test failures do not currently show up in CI. Is it a difference between `bin/doctest` and `pytest ---doctest-plus` r something like that?

**Comment by Davide-sd** [comment]
> @Davide-sd are the plotting doctest fails related to recent changes in the plotting module? It seems like more output is shown when printing a plot object or something...

The GenericDataSeries was introduced with #25117. Before that PR, numerical  data was added directly to matplotlib's axes, without any series. After that PR, an increased number of data series was expected. I wonder why tests passed back then? I'll take a better look tomorrow!

**Comment by haru-44** [comment]
> @haru-44 the ntheory failures are related to having gmpy2 installed: the stdlib random functions do not accept `gmpy.mpz` e.g. for the see argument. Are these failures related to any recent change?

Yes. Fixed in #25029 and #25294.
I failed to take into consideration the possibility that `n` could be `gmpy.mpz`. I think simply fixing it to `_ecm_one_factor(n, B1, B2, max_curve, seed)` instead of adding `n` will solve the problem.

The failure of `modular` was caused by the addition of doctest. I think `crt2` should be modified to always return int, regardless of whether gmpy is used or not.

As a side note, the reason I added `n` to seed is that I thought it was useless to use the same seed when `n1=A*B*C` and when `n2=A*B`. On second thought, that is wrong, and the correct answer is that it is useless to use the same `sigma`. There is no need to add `n` to the seed because the `sigma` chosen by `randint` depends on `n` even if the `seed` is the same.

**Comment by brocksam** [comment]
> @brocksam I am wondering why these test failures do not currently show up in CI. Is it a difference between `bin/doctest` and `pytest ---doctest-plus` r something like that?

Correct. `bin/test` is calling `pytest` but `bin/doctest` is not calling `pytest --doctest-only`, it's still using the `doctest` function from `sympy.testing.runtests`. I opened https://github.com/sympy/sympy/issues/24292 about this originally but haven't done any work on fixing since. Would need to restart efforts there.

**Comment by oscarbenjamin** [comment]
Yes it would good to move the doctests to pytest but the reason for these particular failures not showing up I now realise is unrelated. The optional dependency tests that install matplotlib do not cover the `continuum_mechanics` module which has some doctests that involve plotting. Likewise the ntheory module is not tested with gmpy2 although that is being fixed with gh-25480.
