### ISSUE TITLE
LCM gives ZeroDivisionError

### ISSUE THREAD

**Issue by dianetc** [sympy/sympy#25581]
When utilizing the `lcm` function for polynomials, there is unxpected behavior in that:
```
from sympy.abc import x
from sympy import  lcm, Poly

f = Poly(0, x, domain="QQ")
g = Poly(0, x, domain="QQ")

lcm(f,g)
```
returns a `ZeroDivisionError`, but **should** return 0. 

This doesn't happen in Sage. There
```
R.<x> = PolynomialRing(QQ)  
f = R(0)
g = R(0)

lcm_polynomial = lcm(f, g)
print(lcm_polynomial)
```
returns 0 as expected. 

Is this a bug? If so, is it worthwhile to fix?

**Comment by asmeurer** [comment]
I think it should be changed. Note that ilcm already does this:

```py
>>> ilcm(0, 0)
0
```

As I pointed out at https://github.com/sympy/sympy/pull/25517#discussion_r1302002202, gcd and lcm for a bounded distributed lattice with divisibility as the partial order. In this lattice, 1 is the bottom and 0 is the top, and lcm is the "join" operation, so the lcm of anything with 0 should be 0. `lcm` already does this for nonzero polynomials:

```py
>>> lcm(x, 0)
0
```

Furthermore, we have

```py
>>> lcm(0, 0)
0
>>> lcm(Poly(0, x), Poly(0, x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/polytools.py", line 5621, in lcm
    result = F.lcm(G)
             ^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/polytools.py", line 2939, in lcm
    result = F.lcm(G)
             ^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/polyclasses.py", line 694, in lcm
    return per(dmp_lcm(F, G, lev, dom))
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/euclidtools.py", line 1765, in dmp_lcm
    return dup_lcm(f, g, K)
           ^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/euclidtools.py", line 1693, in dup_lcm
    return dup_rr_lcm(f, g, K)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/euclidtools.py", line 1647, in dup_rr_lcm
    h = dup_quo(dup_mul(f, g, K),
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/densearith.py", line 1578, in dup_quo
    return dup_div(f, g, K)[0]
           ^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/densearith.py", line 1536, in dup_div
    return dup_rr_div(f, g, K)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/polys/densearith.py", line 1328, in dup_rr_div
    raise ZeroDivisionError("polynomial division")
ZeroDivisionError: polynomial division
```

which is clearly inconsistent.

**Comment by smichr** [comment]
I think the routines just need a quick exit for when the f or g is zero (K.zero?) This is a corner case that is not dealt with:
```python
def dmp_rr_lcm(f, g, u, K):
    fc, f = dmp_ground_primitive(f, u, K)
    gc, g = dmp_ground_primitive(g, u, K)

    c = K.lcm(fc, gc)

    h = dmp_quo(dmp_mul(f, g, u, K),
                dmp_gcd(f, g, u, K), u, K)

    return dmp_mul_ground(h, c, u, K)
```
