### ISSUE TITLE
AttributeError: module 'sympy' has no attribute 'Expr'

### ISSUE THREAD

**Issue by ezra-ch** [sympy/sympy#25609]
Traceback (most recent call last):
  File "G:\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "G:\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\anaconda3\Scripts\accelerate.exe\__main__.py", line 4, in <module>
  File "G:\anaconda3\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "G:\anaconda3\lib\site-packages\accelerate\accelerator.py", line 32, in <module>
    import torch
  File "G:\anaconda3\lib\site-packages\torch\__init__.py", line 1465, in <module>
    from . import _meta_registrations
  File "G:\anaconda3\lib\site-packages\torch\_meta_registrations.py", line 7, in <module>
    from torch._decomp import _add_op_to_registry, global_decomposition_table, meta_table
  File "G:\anaconda3\lib\site-packages\torch\_decomp\__init__.py", line 169, in <module>
    import torch._decomp.decompositions
  File "G:\anaconda3\lib\site-packages\torch\_decomp\decompositions.py", line 10, in <module>
    import torch._prims as prims
  File "G:\anaconda3\lib\site-packages\torch\_prims\__init__.py", line 33, in <module>
    from torch._subclasses.fake_tensor import FakeTensor, FakeTensorMode
  File "G:\anaconda3\lib\site-packages\torch\_subclasses\__init__.py", line 3, in <module>
    from torch._subclasses.fake_tensor import (
  File "G:\anaconda3\lib\site-packages\torch\_subclasses\fake_tensor.py", line 13, in <module>
    from torch._guards import Source
  File "G:\anaconda3\lib\site-packages\torch\_guards.py", line 78, in <module>
    class ShapeGuard(NamedTuple):
  File "G:\anaconda3\lib\site-packages\torch\_guards.py", line 79, in ShapeGuard
    expr: sympy.Expr
AttributeError: module 'sympy' has no attribute 'Expr'

**Comment by ezra-ch** [comment]
everything is a fresh install

**Comment by oscarbenjamin** [comment]
Have you created a file called `sympy.py`?

Either way I doubt that this is a SymPy issue.

**Comment by ezra-ch** [comment]
No idea what causes it but i fixed it somehow by reinstalling conda
