### ISSUE TITLE
Branches for series expansions involving the `abs` function is not handled correctly 

### ISSUE THREAD

**Issue by anutosh491** [sympy/sympy#25682]
```
>>> x = Symbol('x', negative=True)
>>> 1/abs(sqrt(1 - (-1 + 1/x)**2))
1/Abs(sqrt(1 - (-1 + 1/x)**2))
>>> _.series(x)
-x - x**2 - 3*x**3/2 - 5*x**4/2 - 35*x**5/8 + O(x**6)
>>>
>>> y = Symbol('y', positive=True)
>>> 1/abs(sqrt(1 - (-1 + 1/y)**2))
1/Abs(sqrt(1 - (-1 + 1/y)**2))
>>> _.series(y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\91989\sympy\sympy\sympy\core\expr.py", line 3034, in series
    s1 = self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "C:\Users\91989\sympy\sympy\sympy\core\power.py", line 1596, in _eval_nseries
    raise NotImplementedError()
NotImplementedError
```

There are two branches for the above series expansion but only one branch is being handled correctly. Results from wolfram 
<img width="254" alt="image" src="https://github.com/sympy/sympy/assets/87052487/b263ea71-a3b0-4181-8538-f2f6693446c3">

**Comment by arnabnandikgp** [comment]
I think this issue can be solved by pr #25756 . The problem is only when the variable `direction` mentioned in the pr turns imaginary which is in this case turning to +I and hence causing the problem.

**Comment by anutosh491** [comment]
@arnabnandikgp would you be interested to try out fixing this. I've marked the above PR as Please Take Over as I don't see any progress on it ! Go ahead and try finishing the PR.

**Comment by arnabnandikgp** [comment]
After going through the PR mentioned above I have stumbled upon the fact that the proposed change in the PR for replacing `return (s*sign(direction)).expand()` with `return (s/sign(direction)).expand()` is not always true even when `sign(direction)` is not zero. As we can see for this issue using the diff given in the PR  though we have 
```
In [3]: y = Symbol('y',positive=True)

In [4]: 1/abs(sqrt(1 - (-1 + 1/y)**2))  #leadterm is  (I, -1)

Out[4]: 1/Abs(sqrt(1 - (-1 + 1/y)**2))

In [5]: _.series(y)
Out[5]: y + y**2 + 3*y**3/2 + 5*y**4/2 + 35*y**5/8 + O(y**6)
```
but 
```
In [6]: x = Symbol('x',negative=True)

In [7]: 1/abs(sqrt(1 - (-1 + 1/x)**2))  # leadterm is (-I, -1)
Out[7]: 1/Abs(sqrt(1 - (-1 + 1/x)**2))

In [8]: _.series(x)
Out[8]:  x + x**2 + 3*x**3/2 + 5*x**4/2 + 35*x**5/8 + O(x**6)
```
so basically the fix in PR works when `expr.leadterm(x)[0]` is `I` and not for `-I`.
If we use the arguments of abs involved in these problems and see their usual expansion without `abs()` and compare them with the results that we are looking for:
```
In [8]: #expansions of arguments without abs

In [8]: sqrt(1 - (-1 + 1/y)**2).series(y)
Out[8]: I/y - I - I*y/2 - I*y**2/2 - 5*I*y**3/8 - 7*I*y**4/8 - 21*I*y**5/16 + O(y**6)

In [9]: sqrt(1 - (-1 + 1/x)**2).series(x)
Out[9]: -I/x + I + I*x/2 + I*x**2/2 + 5*I*x**3/8 + 7*I*x**4/8 + 21*I*x**5/16 + O(x**6)

In [10]: #expected/correct expansions with abs

In [11]: -1/x + 1 + x/2 + x**2/2 + 5*x**3/8 + 7*x**4/8 + 21*x**5/16 + O(x**6)
Out[11]: -1/x + 1 + x/2 + x**2/2 + 5*x**3/8 + 7*x**4/8 + 21*x**5/16 + O(x**6)

In [12]: 1/y - 1 - y/2 - y**2/2 - 5*y**3/8 - 7*y**4/8 - 21*y**5/16 + O(y**6) 
Out[12]: 1/y - 1 - y/2 - y**2/2 - 5*y**3/8 - 7*y**4/8 - 21*y**5/16 + O(y**6)
```
so we can see that this problem can be easily tackled with the following diff

```diff
--- a/sympy/functions/elementary/complexes.py
+++ b/sympy/functions/elementary/complexes.py
@@ -658,11 +658,15 @@ def _eval_power(self, exponent):
 
     def _eval_nseries(self, x, n, logx, cdir=0):
         from sympy.functions.elementary.exponential import log
+        from sympy.series.order import Order
         direction = self.args[0].leadterm(x)[0]
         if direction.has(log(x)):
             direction = direction.subs(log(x), logx)
         s = self.args[0]._eval_nseries(x, n=n, logx=logx)
-        return (sign(direction)*s).expand()
+        if direction.is_extended_real is False:
+            return im(s.removeO()) + Order(x**n, x)
+        else:
+            return (sign(direction)*s).expand()
 
     def _eval_derivative(self, x):
         if self.args[0].is_extended_real or self.args[0].is_imaginary:
```
and toggling through the git history it seems that this is somewhat similar to what were the initial implementations of the method.
