### ISSUE TITLE
TypeError on Eq(2*sign(x + 3)/(5*Abs(x + 3)**(3/5)), 0)

### ISSUE THREAD

**Issue by satels** [sympy/sympy#25701]
```python
from sympy import Symbol, Eq, sign, Abs, Rational

x = Symbol('x', real=True)

eq = Eq(2*sign(x + 3)/(5*Abs(x + 3)**Rational(3, 5)), 0)

eq.simplify()

```

Result:
```
Traceback (most recent call last):
  File "/home/satels/workenv/krcore/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-2fbb666c6791>", line 7, in <module>
    eq.simplify()
  File "/home/satels/workenv/krcore/lib/python3.10/site-packages/sympy/core/basic.py", line 1853, in simplify
    return simplify(self, **kwargs)
  File "/home/satels/workenv/krcore/lib/python3.10/site-packages/sympy/simplify/simplify.py", line 601, in simplify
    return _eval_simplify(**kwargs)
  File "/home/satels/workenv/krcore/lib/python3.10/site-packages/sympy/core/relational.py", line 692, in _eval_simplify
    e.rewrite(Add, evaluate=False), x)
  File "/home/satels/workenv/krcore/lib/python3.10/site-packages/sympy/core/basic.py", line 1981, in rewrite
    return self._rewrite(pattern, rule, method, **hints)
  File "/home/satels/workenv/krcore/lib/python3.10/site-packages/sympy/core/basic.py", line 1986, in _rewrite
    args = [a._rewrite(pattern, rule, method, **hints)
  File "/home/satels/workenv/krcore/lib/python3.10/site-packages/sympy/core/basic.py", line 1986, in <listcomp>
    args = [a._rewrite(pattern, rule, method, **hints)
  File "/home/satels/workenv/krcore/lib/python3.10/site-packages/sympy/core/basic.py", line 1986, in _rewrite
    args = [a._rewrite(pattern, rule, method, **hints)
  File "/home/satels/workenv/krcore/lib/python3.10/site-packages/sympy/core/basic.py", line 1986, in <listcomp>
    args = [a._rewrite(pattern, rule, method, **hints)
  File "/home/satels/workenv/krcore/lib/python3.10/site-packages/sympy/core/basic.py", line 2000, in _rewrite
    return self.func(*args)
  File "/home/satels/workenv/krcore/lib/python3.10/site-packages/sympy/functions/elementary/piecewise.py", line 33, in __new__
    raise TypeError(filldedent('''
TypeError: 
Second argument must be a Boolean, not `Add`
```

**Comment by oscarbenjamin** [comment]
This is because an `Eq` is rewritten as an `Add`:
```python
In [4]: Eq(x, 2).rewrite(Add)
Out[4]: x - 2
```
I have said before that this rewrite rule is a mistake: rewrite is not expected to turn one kind of expression into a different kind and in this case a Boolean should not be rewritten to an Expr.

This is a fix to the problem:
```diff
diff --git a/sympy/core/relational.py b/sympy/core/relational.py
index b2dbd1f395..a534926411 100644
--- a/sympy/core/relational.py
+++ b/sympy/core/relational.py
@@ -686,8 +686,7 @@ def _eval_simplify(self, **kwargs):
                 from .add import Add
                 from sympy.solvers.solveset import linear_coeffs
                 x = free.pop()
-                m, b = linear_coeffs(
-                    e.rewrite(Add, evaluate=False), x)
+                m, b = linear_coeffs(Add(e.lhs, -e.rhs, evaluate=False), x)
                 if m.is_zero is False:
                     enew = e.func(x, -b / m)
                 else:
```
With the diff above we have:
```python
In [4]: eq.simplify()
Out[4]: 
⎧      0         for x = -3    
⎪                              
⎪  2⋅(x + 3)                   
⎨──────────────  otherwise  = 0
⎪  │       8/5│                
⎪5⋅│(x + 3)   │                
⎩   
```
This is not completely correct but the basic bug here is fixed. The reason that this is not completely correct is that when `x = -2` the lhs should be undefined rather than `0`.

The `Eq.rewrite(Add)` should be removed entirely to fix that problem in general.

**Comment by oscarbenjamin** [comment]
Thanks @smichr for the rewrite fix.

There is still a problem here though:
```python
In [4]: from sympy import Symbol, Eq, sign, Abs, Rational
   ...: 
   ...: x = Symbol('x', real=True)
   ...: 
   ...: eq = Eq(2*sign(x + 3)/(5*Abs(x + 3)**Rational(3, 5)), 0)

In [5]: eq
Out[5]: 
2⋅sign(x + 3)    
───────────── = 0
         3/5     
5⋅│x + 3│        

In [6]: eq.lhs.subs(x, -3)
Out[6]: nan

In [7]: eq.simplify()
Out[7]: 
⎧      0         for x = -3    
⎪                              
⎪  2⋅(x + 3)                   
⎨──────────────  otherwise  = 0
⎪  │       8/5│                
⎪5⋅│(x + 3)   │                
⎩                              

In [8]: eq.simplify().subs(x, -3)
Out[8]: True
```
The `x = -3` case in the `Piecewise` is still incorrect.
