### ISSUE TITLE
IndexError when run dsolve(Eq(x*Derivative(y(x), x) + y(x)*log(y(x)), exp(x)), y(x))

### ISSUE THREAD

**Issue by satels** [sympy/sympy#25773]
```python
from sympy import Eq, Function, Symbol, log, exp, dsolve
x = Symbol('x')
y_x = Function('y')(x)
eq = Eq(x*y_x.diff(x) + y_x*log(y_x), exp(x))
dsolve(eq, y_x)
```

The error:
```
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-0e1f1eeaa1f7>", line 1, in <module>
    dsolve(eq, y_x)
  File "/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 640, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 669, in _helper_simplify
    sols = solvefunc.get_general_solution()
  File "/lib/python3.10/site-packages/sympy/solvers/ode/single.py", line 283, in get_general_solution
    return self._get_general_solution(simplify_flag=simplify)
  File "/lib/python3.10/site-packages/sympy/solvers/ode/single.py", line 897, in _get_general_solution
    sol = dsolve(eq, func(x))
  File "/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 640, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 669, in _helper_simplify
    sols = solvefunc.get_general_solution()
  File "/lib/python3.10/site-packages/sympy/solvers/ode/single.py", line 283, in get_general_solution
    return self._get_general_solution(simplify_flag=simplify)
  File "/lib/python3.10/site-packages/sympy/solvers/ode/single.py", line 2938, in _get_general_solution
    sol = _ode_lie_group(s, func, order, match=self.r3)
  File "/lib/python3.10/site-packages/sympy/solvers/ode/lie_group.py", line 157, in _ode_lie_group
    sol = _ode_lie_group_try_heuristic(Eq(df, s), heuristic, func, match, inf)
  File "/lib/python3.10/site-packages/sympy/solvers/ode/lie_group.py", line 87, in _ode_lie_group_try_heuristic
    sol = solve([r - rcoord, s - scoord], x, y, dict=True)
  File "/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1147, in solve
    linear, solution = _solve_system(f, symbols, **flags)
  File "/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1765, in _solve_system
    _linear, subsol = _solve_system(subexpr, subsyms, **flags)
  File "/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1815, in _solve_system
    matrix[i, j] = coeff
  File "/lib/python3.10/site-packages/sympy/matrices/repmatrix.py", line 400, in __setitem__
    rv = self._setitem(key, value)
  File "/lib/python3.10/site-packages/sympy/matrices/matrices.py", line 1157, in _setitem
    i, j = key = self.key2ij(key)
  File "/lib/python3.10/site-packages/sympy/matrices/matrices.py", line 1810, in key2ij
    return [a2idx(i, n) if not isinstance(i, slice) else i
  File "/lib/python3.10/site-packages/sympy/matrices/matrices.py", line 1810, in <listcomp>
    return [a2idx(i, n) if not isinstance(i, slice) else i
  File "/lib/python3.10/site-packages/sympy/matrices/common.py", line 3189, in a2idx
    raise IndexError("Index out of range: a[%s]" % (j,))
IndexError: Index out of range: a[1]

```

**Comment by oscarbenjamin** [comment]
This is a simpler reproducer of the error message:
```python
>>> from sympy import *
>>> x, y, a, b = symbols('x, y, a, b')
>>> solve([x - a, Integral(y, y) - b], [x, y])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/space/enojb/sympy/sympy.git/sympy/solvers/solvers.py", line 1172, in solve
    linear, solution = _solve_system(f, symbols, **flags)
  File "/space/enojb/sympy/sympy.git/sympy/solvers/solvers.py", line 1797, in _solve_system
    _linear, subsol = _solve_system(subexpr, subsyms, **flags)
  File "/space/enojb/sympy/sympy.git/sympy/solvers/solvers.py", line 1847, in _solve_system
    matrix[i, j] = coeff
  File "/space/enojb/sympy/sympy.git/sympy/matrices/repmatrix.py", line 480, in __setitem__
    rv = self._setitem(key, value)
  File "/space/enojb/sympy/sympy.git/sympy/matrices/matrices.py", line 1182, in _setitem
    i, j = key = self.key2ij(key)
  File "/space/enojb/sympy/sympy.git/sympy/matrices/matrices.py", line 1971, in key2ij
    return [a2idx(i, n) if not isinstance(i, slice) else i
  File "/space/enojb/sympy/sympy.git/sympy/matrices/matrices.py", line 1971, in <listcomp>
    return [a2idx(i, n) if not isinstance(i, slice) else i
  File "/space/enojb/sympy/sympy.git/sympy/matrices/common.py", line 3192, in a2idx
    raise IndexError("Index out of range: a[%s]" % (j,))
IndexError: Index out of range: a[1]
```
I'm not sure that I think solve should be able to solve these equations but the error message should be different so there are two problems:

- Solve should report an error saying that it cannot handle unevaluated integrals. Probably the error here arises from a bug in the logic used in solve somewhere.
- The Lie group ODE solver should not ask solve to try to handle unevaluated integrals like this.
