### ISSUE TITLE
AttributeError when run `dsolve(Eq(y(x)**3*Derivative(y(x), (x, 2)) + 1, 0), y(x))`

### ISSUE THREAD

**Issue by satels** [sympy/sympy#25776]
```python
from sympy import dsolve, Symbol, Function, Eq
y = Function('y')
x = Symbol('x')

eq = Eq(y(x).diff(x, 2)*y(x)**3 + 1, 0)
dsolve(eq, y(x))
```

The error:
```python
Traceback (most recent call last):
    dsolve(eq, y(x))
  File "/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 640, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 690, in _helper_simplify
    rv = _remove_redundant_solutions(eq, rv, order, func.args[0])
  File "/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 2627, in _remove_redundant_solutions
    if is_special_case_of(soln1, soln2):
  File "/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 2622, in is_special_case_of
    return _is_special_case_of(soln1, soln2, eq, order, var)
  File "/lib/python3.10/site-packages/sympy/solvers/ode/ode.py", line 2655, in _is_special_case_of
    soln1 = soln1.rhs - soln1.lhs
AttributeError: 'list' object has no attribute 'rhs'

```

**Comment by oscarbenjamin** [comment]
The dsolve code is all messed up about whether it returns a list of solutions or a single solution. Something like this is needed:
```diff
diff --git a/sympy/solvers/ode/ode.py b/sympy/solvers/ode/ode.py
index 75bccdf8d5..03dad28766 100644
--- a/sympy/solvers/ode/ode.py
+++ b/sympy/solvers/ode/ode.py
@@ -669,10 +669,17 @@ def _helper_simplify(eq, hint, match, simplify=True, ics=None, **kwargs):
             sols = solvefunc.get_general_solution()
         else:
             sols = solvefunc(eq, func, order, match)
-        if iterable(sols):
-            rv = [odesimp(eq, s, func, hint) for s in sols]
-        else:
-            rv =  odesimp(eq, sols, func, hint)
+
+        if not iterable(sols):
+            sols = [sols]
+
+        rv = []
+        for s in sols:
+            rvs = odesimp(s, func, order, match)
+            if iterable(rvs):
+                rv.extend(rvs)
+            else:
+                rv.append(rvs)
     else:
         # We still want to integrate (you can disable it separately with the hint)
         if isinstance(solvefunc, SingleODESolver):
@@ -680,31 +687,28 @@ def _helper_simplify(eq, hint, match, simplify=True, ics=None, **kwargs):
         else:
             match['simplify'] = False  # Some hints can take advantage of this option
             exprs = solvefunc(eq, func, order, match)
-        if isinstance(exprs, list):
-            rv = [_handle_Integral(expr, func, hint) for expr in exprs]
-        else:
-            rv = _handle_Integral(exprs, func, hint)
 
-    if isinstance(rv, list):
-        if simplify:
-            rv = _remove_redundant_solutions(eq, rv, order, func.args[0])
-        if len(rv) == 1:
-            rv = rv[0]
+        if not iterable(exprs):
+            exprs = [exprs]
+
+        rv = [_handle_Integral(expr, func, hint) for expr in exprs]
+
+    if simplify:
+        rv = _remove_redundant_solutions(eq, rv, order, func.args[0])
+
     if ics and 'power_series' not in hint:
-        if isinstance(rv, (Expr, Eq)):
-            solved_constants = solve_ics([rv], [r['func']], cons(rv), ics)
-            rv = rv.subs(solved_constants)
-        else:
-            rv1 = []
-            for s in rv:
-                try:
-                    solved_constants = solve_ics([s], [r['func']], cons(s), ics)
-                except ValueError:
-                    continue
-                rv1.append(s.subs(solved_constants))
-            if len(rv1) == 1:
-                return rv1[0]
-            rv = rv1
+        rv1 = []
+        for s in rv:
+            try:
+                solved_constants = solve_ics([s], [r['func']], cons(s), ics)
+            except ValueError:
+                continue
+            rv1.append(s.subs(solved_constants))
+        rv = rv1
+
+    if len(rv) == 1:
+        rv = rv[0]
+
     return rv
 
 def solve_ics(sols, funcs, constants, ics):
```
It will then just be extremely slow for this example because it calls `solve` to try to remove redundant solutions and that ends up being slow.

The diff above is still needed even if it does not allow this case to succeed.
