### ISSUE TITLE
TypeError when run `solve(Abs(x**3 + x + 2) / (x + 1))`

### ISSUE THREAD

**Issue by satels** [sympy/sympy#25777]
```python
from sympy import Abs, solve, Symbol
x = Symbol('x', real=True)
solve(Abs(x**3 + x + 2) / (x + 1))
```

The error:
```python
Traceback (most recent call last):
    solve(Abs(x**3 + x + 2) / (x + 1))
  File "/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1145, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/lib/python3.10/site-packages/sympy/solvers/solvers.py", line 1419, in _solve
    result.add(Piecewise(
  File "/lib/python3.10/site-packages/sympy/functions/elementary/piecewise.py", line 147, in __new__
    r = cls.eval(*newargs)
  File "/lib/python3.10/site-packages/sympy/functions/elementary/piecewise.py", line 189, in eval
    newargs = _piecewise_collapse_arguments(_args)
  File "/lib/python3.10/site-packages/sympy/functions/elementary/piecewise.py", line 1238, in _piecewise_collapse_arguments
    cond = cond.replace(
  File "/lib/python3.10/site-packages/sympy/core/basic.py", line 1666, in replace
    rv = walk(self, rec_replace)
  File "/lib/python3.10/site-packages/sympy/core/basic.py", line 1651, in walk
    rv = F(rv)
  File "/lib/python3.10/site-packages/sympy/core/basic.py", line 1659, in rec_replace
    v = _value(expr, result)
  File "/lib/python3.10/site-packages/sympy/core/basic.py", line 1625, in <lambda>
    _value = lambda expr, result: value(expr)
  File "/lib/python3.10/site-packages/sympy/core/relational.py", line 56, in _canonical_coeff
    return rel.func(lhs, rhs)
  File "/lib/python3.10/site-packages/sympy/core/relational.py", line 822, in __new__
    raise TypeError("Invalid comparison of non-real %s" % me)
TypeError: Invalid comparison of non-real 0.e-113 + 0.e-112*I
```

**Comment by vr050714** [comment]
This equations or function of $x\in \mathbb{R}$ is dincontinous at point $x = -1$.
The equation can be reduced to
$$\frac{|x+1|}{x+1}(x^2-x+2)=0$$
where the fraction corresponds to $\mathtt{sign}(x+1)$ function, and the quadratic polynom has no roots in real numbers.

Small investigation shows that no algorithms are implemented to solve equation sign(x + 1) despite that $\mathtt{sign}(0) = 0$

Also calling `simplify(x/abs(x)-sign(x))` results in piecewise function equal to NaN at x = 0 and 0 otherwise but $x=|x|\cdot \mathtt{sign}(x)$

May it be the reason?

But on the other hand, $x=-1$ should not be a solution, because it is excluded point for this equation.
