### ISSUE TITLE
Type error when solving multiple Abs(), and other error in other cases

### ISSUE THREAD

**Issue by BlankShrimp** [sympy/sympy#25779]
sympy.solve() test case: 
```python
eq1 = Eq(Abs(-1/6 - a) - b, 0)
eq2 = Eq(Abs(5/6 - a) - b, 0)
solve((eq1, eq2), (a, b))
```
which raised `TypeError: Invalid NaN comparison`

A little digging into this issue:
For each equation, sympy first rewrite Abs with Piecewise here
https://github.com/sympy/sympy/blob/368eb0f483f2b4cd84dc0de3edc7abdc876d3d46/sympy/solvers/solvers.py#L1000-L1006 However, it produces `-b + Piecewise((a + 1/6, a >= -1/6), (-a - 1/6, True))` somehow with a True case in it, where in my oipinion the Piecewise should be `Piecewise((a + 1/6, a >= -1/6), (-a - 1/6, a < -1/6))`

this risk leads to solve failed here https://github.com/sympy/sympy/blob/368eb0f483f2b4cd84dc0de3edc7abdc876d3d46/sympy/solvers/solvers.py#L1965-L1968, which produces `soln = Piecewise((5/6 - b, b > 0), (nan, True))` with a nan in it. 
Then finally when substituting the above intermediate results to the other equation, the nan cannot be evaluated to bool raising the error. 

Aside from this issue, following cases also occured to me:
```python
x = Symbol('x', real=True)
eq1 = Eq(Abs(x), 0)
solve(eq1, x) # pass

eq2 = Eq(Abs(sqrt(x)), 0)
solve(eq2, x) # failed

eq3 = Eq(Abs(4 + 1 / (4 * x)), 0)
solve(eq3, x) # failed

eq4 = Eq(Abs(x**2 - 2*x), 4)
solve(eq4, x) # failed
```
which all raises NotImplementedError. I understand and accept the fact that intermediate results may have chances to be evaluated to complex, but is there any way to discard complex results since that doesn't make sence to Abs() anyway? Since I've already set x to real.

**Comment by smichr** [comment]
```python
        for ec in product(*[
                (i.args if isinstance(i, Piecewise) else
                 [(i, true)]) for i in folded]):
            e, c = zip(*ec)
            new_args.append((expr.func(*e), And(*c)))
```
could maybe be changed to
```python
        for ec in product(*[
                (i.args if isinstance(i, Piecewise) else
                 [(i, true)]) for i in folded]):
            e, c = zip(*ec)
            if e is S.NaN and c == True:
                new_args.append((e, c))
            else:
                new_args.append((expr.func(*e), And(*c)))
```
in `sympy.functions.elementary.piecewise`

**Comment by BlankShrimp** [comment]
I don't think it would work (and it doesn't if I've done it correctly). It seems to me you simply check the value and pass it to next step, where the NaN could explode in other places. I'm not sure why there's a (NaN, True) in the piecewise or why it's considered valid when constructing the piecewise object (I mean, first piece with a range while the second with a range of True).

**Comment by oscarbenjamin** [comment]
The cases of a Piecewise need to be understood sequentially.  The second case only applies if the condition for the first case is False and the condition for the second case is True. Having a True condition just means that the second case always applies when the first does not.

**Comment by BlankShrimp** [comment]
Understood, and `(NaN, True)` must means being evaluated to empty then. Guess we should ignore NaN cases somewhere somehow?

**Comment by oscarbenjamin** [comment]
Here solving an equation with Abs (if the symbols are declared real=True) transforms the equations to Piecewise:
```python
In [14]: eq1
Out[14]: -b + │a + 1/6│ = 0

In [15]: eq2
Out[15]: -b + │a - 5/6│ = 0

In [16]: eq1.rewrite(Piecewise)
Out[16]: 
     ⎛⎧a + 1/6   for a ≥ -1/6⎞    
-b + ⎜⎨                      ⎟ = 0
     ⎝⎩-a - 1/6   otherwise  ⎠    

In [17]: eq2.rewrite(Piecewise)
Out[17]: 
     ⎛⎧a - 5/6  for a ≥ 5/6⎞    
-b + ⎜⎨                    ⎟ = 0
     ⎝⎩5/6 - a   otherwise ⎠ 
```
That is reasonable but then solve should split the cases and solve them separately:
```python
In [29]: eq = piecewise_exclusive(piecewise_fold(Tuple(eq1, eq2).rewrite(Piecewise)))

In [30]: eq
Out[30]: 
⎧ (a - b + 1/6 = 0, a - b - 5/6 = 0)        for a ≥ 5/6      
⎪                                                            
⎨(a - b + 1/6 = 0, -a - b + 5/6 = 0)   for a ≥ -1/6 ∧ a < 5/6
⎪                                                            
⎩(-a - b - 1/6 = 0, -a - b + 5/6 = 0)       for a < -1/6     

In [31]: for e, c in eq.args:
    ...:     sols = solve(e, [a, b], dict=True)
    ...:     for s in sols:
    ...:         print(c)
    ...:         print(s)
    ...:         print(c.subs(s))
    ...:         print()
    ...: 
(a >= -1/6) & (a < 5/6)
{a: 1/3, b: 1/2}
True
```

**Comment by oscarbenjamin** [comment]
> ```python
> eq4 = Eq(Abs(x**2 - 2*x), 4)
> solve(eq4, x) # failed
> ```

This case gives:
```
TypeError: Invalid comparison of non-real 4.0 - 0.e-7*I
```
It is the same problem that I described here: https://github.com/sympy/sympy/issues/25777#issuecomment-1753680555

**Comment by oscarbenjamin** [comment]
> ```python
> eq2 = Eq(Abs(sqrt(x)), 0)
> solve(eq2, x) # failed
> 
> eq3 = Eq(Abs(4 + 1 / (4 * x)), 0)
> solve(eq3, x) # failed
> ```

These two give
```
NotImplementedError: solving Abs(4 + 1/(4*x)) when the argument is not real or imaginary.
```
The problem is this logic in solve:
https://github.com/sympy/sympy/blob/368eb0f483f2b4cd84dc0de3edc7abdc876d3d46/sympy/solvers/solvers.py#L998-L1011

It will try to rewrite all Abs to Piecewise which will succeed only if the contents of the Abs is considered to be real. Actually there is a better way of handling this in `solve` that does not apply to general rewriting. The condition `Abs(f(z)) = c` can be replaced with `f(z) = x + I*y` and `x**2 + y**2 = c**2` where `x` and `y` are real. This way the `Abs` is transformed to polynomial equations. The special case that we have `Abs(f(z)) = 0` can obviously be handled more simply as just `f(z) = 0`.

**Comment by oscarbenjamin** [comment]
> Guess to fix this we should ignore NaN cases somewhere somehow?

I'm not sure what the NaNs are for but there should be no need to introduce them when handling the particular cases considered here.

**Comment by BlankShrimp** [comment]
> ```python
> In [29]: eq = piecewise_exclusive(piecewise_fold(Tuple(eq1, eq2).rewrite(Piecewise)))
> 
> In [31]: for e, c in eq.args:
>     ...:     sols = solve(e, [a, b], dict=True)
>     ...:     for s in sols:
>     ...:         print(c)
>     ...:         print(s)
>     ...:         print(c.subs(s))
>     ...:         print()
>     ...: 
> (a >= -1/6) & (a < 5/6)
> {a: 1/3, b: 1/2}
> True
> ```

Epic solution! This solution feels widely applicapable to me, is it possible to make this process built into sovlve() so that other piecewise involved functions could also enjoy the benefit? 

> It will try to rewrite all Abs to Piecewise which will succeed only if the contents of the Abs is considered to be real. Actually there is a better way of handling this in solve that does not apply to general rewriting. The condition Abs(f(z)) = c can be replaced with f(z) = x + I*y and x**2 + y**2 = c**2 where x and y are real. This way the Abs is transformed to polynomial equations. The special case that we have Abs(f(z)) = 0 can obviously be handled more simply as just f(z) = 0.

I also noticed that solve() was struggled to reasoning things like `Abs(sth) + sqrt(sth2) == 0`. I do believe if this patch was applied, the above case should also be covered.

**Comment by oscarbenjamin** [comment]
> is it possible to make this process built into sovlve() so that other piecewise involved functions could also enjoy the benefit?

It should be possible but making these changes in solve is always fiddly because the code is a mess and has many heuristic cases where a small change in one place breaks something unrelated elsewhere.

Note that the proper fix should not use `piecewise_exclusive` or `rewrite` but should rather handle the rewriting explicitly in `solve`.

**Comment by satels** [comment]
one more:

```python
from sympy import solve, Eq, Abs, symbols

x, y = symbols('x, y', real=True)

_equations = [
    Eq(-x**2 + y**2 + 3*y*Abs(x), -3),
    Eq(x**2 + y**2 - 2*y*Abs(x), 4)]


_vars = [y, x]


sol_lst = solve(_equations, _vars)

```

```python
Traceback (most recent call last):
    sol_lst = solve(_equations, _vars)
  File "sympy/solvers/solvers.py", line 1147, in solve
    linear, solution = _solve_system(f, symbols, **flags)
  File "sympy/solvers/solvers.py", line 1911, in _solve_system
    eq2 = eq.subs(r)
  File "sympy/core/basic.py", line 1040, in subs
    rv = rv._subs(old, new, **kwargs)
  File "sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/basic.py", line 1152, in _subs
    rv = self._eval_subs(old, new)
  File "sympy/functions/elementary/piecewise.py", line 774, in _eval_subs
    return self.func(*args)
  File "sympy/functions/elementary/piecewise.py", line 137, in __new__
    pair = ExprCondPair(*getattr(ec, 'args', ec))
  File "sympy/functions/elementary/piecewise.py", line 28, in __new__
    cond = piecewise_fold(cond)
  File "sympy/functions/elementary/piecewise.py", line 1085, in piecewise_fold
    new_args.append((expr.func(*e), And(*c)))
  File "sympy/core/relational.py", line 824, in __new__
    raise TypeError("Invalid NaN comparison")
TypeError: Invalid NaN comparison
```

**Comment by oscarbenjamin** [comment]
I have described the general approach for how these cases should be handled here: https://github.com/sympy/sympy/pull/25904#issuecomment-1817856500

The equations are
```
-x**2 + y**2 + 3*y*abs(x) = -3
x**2 + y**2 - 2*y*abs(x) = 4
```
Introduce a new variable `d = abs(x)` and then an equation and inequality:
```
-x**2 + y**2 + 3*y*d = -3
x**2 + y**2 - 2*y*d = 4
d**2 = x**2
d >= 0
```
Now the first three equations can be solved:
```python
In [4]: x, y, d = symbols('x, y, d')

In [5]: eqs = [Eq(-x**2 + y**2 + 3*y*d, -3), Eq(x**2 + y**2 - 2*y*d, 4), Eq(d**2, x**2)]

In [6]: eqs
Out[6]: 
⎡         2    2                 2    2       2    2⎤
⎣3⋅d⋅y - x  + y  = -3, -2⋅d⋅y + x  + y  = 4, d  = x ⎦

In [7]: sols = solve(eqs, [x, y, d], dict=True)

In [8]: cond = d >= 0

In [9]: for s in sols: print(s)
{d: -7/3, x: -7/3, y: -1/3}
{d: -7/3, x: 7/3, y: -1/3}
{d: -1, x: -1, y: 1}
{d: -1, x: 1, y: 1}
{d: 1, x: -1, y: -1}
{d: 1, x: 1, y: -1}
{d: 7/3, x: -7/3, y: 1/3}
{d: 7/3, x: 7/3, y: 1/3}

In [10]: for s in sols: print(s, cond.subs(s))
{d: -7/3, x: -7/3, y: -1/3} False
{d: -7/3, x: 7/3, y: -1/3} False
{d: -1, x: -1, y: 1} False
{d: -1, x: 1, y: 1} False
{d: 1, x: -1, y: -1} True
{d: 1, x: 1, y: -1} True
{d: 7/3, x: -7/3, y: 1/3} True
{d: 7/3, x: 7/3, y: 1/3} True
```
Once we have the solutions the condition can be checked:
```python
In [11]: [s for s in sols if cond.subs(s) != False]
Out[11]: [{d: 1, x: -1, y: -1}, {d: 1, x: 1, y: -1}, {d: 7/3, x: -7/3, y: 1/3}, {d: 7/3, x: 7/3, y: 1/3}]
```
Potentially better than using `d**2 = x**2` is to consider `d = +x` and `d = -x` separately:
```python
In [12]: eqs = [Eq(-x**2 + y**2 + 3*y*d, -3), Eq(x**2 + y**2 - 2*y*d, 4), Eq(d, x)]

In [13]: sols = solve(eqs, [x, y, d], dict=True)

In [14]: for s in sols: print(s, cond.subs(s))
{d: -7/3, x: -7/3, y: -1/3} False
{d: -1, x: -1, y: 1} False
{d: 1, x: 1, y: -1} True
{d: 7/3, x: 7/3, y: 1/3} True

In [15]: eqs = [Eq(-x**2 + y**2 + 3*y*d, -3), Eq(x**2 + y**2 - 2*y*d, 4), Eq(d, -x)]

In [16]: sols = solve(eqs, [x, y, d], dict=True)

In [17]: for s in sols: print(s, cond.subs(s))
{d: -7/3, x: 7/3, y: -1/3} False
{d: -1, x: 1, y: 1} False
{d: 1, x: -1, y: -1} True
{d: 7/3, x: -7/3, y: 1/3} True
```
