### ISSUE TITLE
ValueError: Rational Solution doesn't exist when solve differential equation: `Derivative(y(x), x) - (12*x + y(x)**2 + 8*y(x))/x`

### ISSUE THREAD

**Issue by satels** [sympy/sympy#25819]
```python
from sympy import Derivative, Function, Symbol
x = Symbol('x')
y = Function('y')
from sympy import Derivative, Function, Symbol, dsolve
dsolve(Derivative(y(x), x) - (12*x + y(x)**2 + 8*y(x))/x, y(x))

```

the error:

```python
Traceback (most recent call last):

  File "sympy/solvers/ode/ode.py", line 640, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "sympy/solvers/ode/ode.py", line 669, in _helper_simplify
    sols = solvefunc.get_general_solution()
  File "sympy/solvers/ode/single.py", line 283, in get_general_solution
    return self._get_general_solution(simplify_flag=simplify)
  File "sympy/solvers/ode/single.py", line 1043, in _get_general_solution
    return solve_riccati(fx, x, b0, b1, b2, gensol=True)
  File "sympy/solvers/ode/riccati.py", line 827, in solve_riccati
    raise ValueError("Rational Solution doesn't exist")
ValueError: Rational Solution doesn't exist

```

**Comment by oscarbenjamin** [comment]
The error message is because there are no rational solutions and the solver tries to find rational solutions. I think that it is correct that there are no rational solutions in this case.

I doubt that any of the other solvers would be able to solve this but perhaps the error message can be improved.
