### ISSUE TITLE
AttributeError: when solve differential equation: `y(x).diff(x).diff(x)*y(x)**3+49`

### ISSUE THREAD

**Issue by satels** [sympy/sympy#25820]
```python
from sympy import Derivative, Function, Symbol, dsolve
x = Symbol('x')
y = Function('y')
dsolve(y(x).diff(x).diff(x)*y(x)**3+49, y(x))
```

the error:
```python
Traceback (most recent call last):
  File "sympy/solvers/ode/ode.py", line 640, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "sympy/solvers/ode/ode.py", line 690, in _helper_simplify
    rv = _remove_redundant_solutions(eq, rv, order, func.args[0])
  File "sympy/solvers/ode/ode.py", line 2627, in _remove_redundant_solutions
    if is_special_case_of(soln1, soln2):
  File "sympy/solvers/ode/ode.py", line 2622, in is_special_case_of
    return _is_special_case_of(soln1, soln2, eq, order, var)
  File "sympy/solvers/ode/ode.py", line 2655, in _is_special_case_of
    soln1 = soln1.rhs - soln1.lhs
AttributeError: 'list' object has no attribute 'rhs'
```

**Comment by oscarbenjamin** [comment]
Some how the solutions are being returned from somewhere as a list of lists of solutions rather than a list of solutions.

**Comment by smichr** [comment]
```diff
diff --git a/sympy/solvers/ode/ode.py b/sympy/solvers/ode/ode.py
index 75bccdf8d5..2a6734d40a 100644
--- a/sympy/solvers/ode/ode.py
+++ b/sympy/solvers/ode/ode.py
@@ -639,6 +639,7 @@ def recur_len(l):
             hint = hints['hint']
             return _helper_simplify(eq, hint, hints, simplify, ics=ics)
 
+
 def _helper_simplify(eq, hint, match, simplify=True, ics=None, **kwargs):
     r"""
     Helper function of dsolve that calls the respective
@@ -670,7 +671,9 @@ def _helper_simplify(eq, hint, match, simplify=True, ics=None, **kwargs):
         else:
             sols = solvefunc(eq, func, order, match)
         if iterable(sols):
-            rv = [odesimp(eq, s, func, hint) for s in sols]
+            rv = []
+            for s in sols:
+                rv.extend(odesimp(eq, s, func, hint))
         else:
             rv =  odesimp(eq, sols, func, hint)
     else:
@@ -686,6 +689,7 @@ def _helper_simplify(eq, hint, match, simplify=True, ics=None, **kwargs):
             rv = _handle_Integral(exprs, func, hint)
 
     if isinstance(rv, list):
+        assert all(isinstance(i, Eq) for i in rv), rv
         if simplify:
             rv = _remove_redundant_solutions(eq, rv, order, func.args[0])
         if len(rv) == 1:
@@ -707,6 +711,7 @@ def _helper_simplify(eq, hint, match, simplify=True, ics=None, **kwargs):
             rv = rv1
     return rv
 
+
 def solve_ics(sols, funcs, constants, ics):
     """
     Solve for the constants given initial conditions
```
