### ISSUE TITLE
solve leads to `can't initialize from 'dict' without generators`

### ISSUE THREAD

**Issue by ThibaultLejemble** [sympy/sympy#25849]
The following code gives the error `sympy.polys.polyerrors.GeneratorsNeeded: can't initialize from 'dict' without generators`. 
```python
from sympy import *

# constant
a = Symbol('a')
b = Symbol('b')
c = Symbol('c')
d = Symbol('d')

# variable
x = Symbol('x')

eq = [
    x*a - x*b, 
    -d**2/(48*d + 48*c) - d*c/(24*d + 24*c) + d/48 - c**2/(48*d + 48*c) + c/48
]
print(collect(eq[0], x)) # x*(a - b)
print(simplify(eq[1]))   # 0
sol = solve(eq, x, dict=False) # line 18
print(sol)
```

The full error is 
```
Traceback (most recent call last):
  File "/home/test.py", line 18, in <module>
    sol = solve(eq, x, dict=False)
  File "/usr/lib/python3/dist-packages/sympy/solvers/solvers.py", line 1097, in solve
    solution = _solve_system(f, symbols, **flags)
  File "/usr/lib/python3/dist-packages/sympy/solvers/solvers.py", line 1757, in _solve_system
    subsol = _solve_system(subexpr, subsyms, **flags)
  File "/usr/lib/python3/dist-packages/sympy/solvers/solvers.py", line 1788, in _solve_system
    poly = g.as_poly(*symbols, extension=True)
  File "/usr/lib/python3/dist-packages/sympy/core/expr.py", line 1131, in as_poly
    poly = Poly(self, *gens, **args)
  File "/usr/lib/python3/dist-packages/sympy/polys/polytools.py", line 164, in __new__
    return cls._from_expr(rep, opt)
  File "/usr/lib/python3/dist-packages/sympy/polys/polytools.py", line 294, in _from_expr
    return cls._from_dict(rep, opt)
  File "/usr/lib/python3/dist-packages/sympy/polys/polytools.py", line 231, in _from_dict
    raise GeneratorsNeeded(
sympy.polys.polyerrors.GeneratorsNeeded: can't initialize from 'dict' without generators
```

Note that the two equations are equivalent to `[x*(a - b), 0]` so the solution should be `x = 0`. 

Why is there an error?

Calling `simplify` on `eq[1]` solve the issue. Does it mean I have to call `simplify` before any call to `solve`?

**Comment by oscarbenjamin** [comment]
> Does it mean I have to call `simplify` before any call to `solve`?

No, this is just a bug.

**Comment by oscarbenjamin** [comment]
With current master I just get the empty set:
```python
In [12]: solve(eq, x)
Out[12]: []
```
As you say though the answer should be `[0]`.

**Comment by smichr** [comment]
You can also just pass equations that depend on your symbol as in `solve([i for i in eq if i.has(x)],x)` if your source of equations might include equations that don't have the symbol of interest. But then you would have to confirm that the other equations are identically 0 , e.g. `assert `all(i.equals(0) for i in [i for i in eq if not i.has(x)])`

**Comment by oscarbenjamin** [comment]
> You can also just pass equations that depend on your symbol as in `solve([i for i in eq if i.has(x)],x)` if your source of equations might include equations that don't have the symbol of interest. But then you would have to confirm that the other equations are identically 0 , e.g. `assert `all(i.equals(0) for i in [i for i in eq if not i.has(x)])`

Ideally `solve` would do something equivalent to this.

**Comment by pranavkonidena** [comment]
Is this issue still open?

**Comment by ThibaultLejemble** [comment]
With Sympy 1.14.0, there is no raised error, but the result of `solve` is empty, whereas it must be `[0]`
