### ISSUE TITLE
Differentiation example in SymPy documentation is not working

### ISSUE THREAD

**Issue by invisibleroads** [sympy/sympy#2587]
The following example of computing a derivative with respect to two variables raises a SympifyError.
http://docs.sympy.org/dev/modules/mpmath/calculus/differentiation.html

    from sympy import *
    x, y, z, t = symbols('x y z t')
    k, m, n = symbols('k m n', integer=True)
    f, g, h = symbols('f g h', cls=Function)
    diff(lambda x,y: 3*x*y + 2*y - x, (0.25, 0.5), (1,1))

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/39.369438448182393855/sympy/sympy/core/function.py", line 1498, in diff
    return Derivative(f, *symbols, **kwargs)
  File "/base/data/home/apps/s~sympy-live-hrd/39.369438448182393855/sympy/sympy/core/function.py", line 883, in __new__
    expr = sympify(expr)
  File "/base/data/home/apps/s~sympy-live-hrd/39.369438448182393855/sympy/sympy/core/sympify.py", line 297, in sympify
    raise SympifyError('could not parse %r' % a, exc)
SympifyError: Sympify of expression 'could not parse u'<function <lambda> at 0xf964d9f0>'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)

**Comment by jcrist** [comment]
Fixed in current docs. Closing.
