### ISSUE TITLE
IndexError when run `classify_ode`

### ISSUE THREAD

**Issue by satels** [sympy/sympy#25882]
```python
from sympy import classify_ode, Derivative, Function, Symbol

y = Function('y')
x = Symbol('x')

eq = (x - 1)*Derivative(y(x), (x, 2)) - Derivative(y(x), x)

classify_ode(eq, y(x))

```

The error:
```python
Traceback (most recent call last):
    classify_ode(eq, y(x))
  File "sympy/solvers/ode/ode.py", line 1033, in classify_ode
    if solver.matches():
  File "sympy/solvers/ode/single.py", line 276, in matches
    self._matched = self._matches()
  File "sympy/solvers/ode/single.py", line 2082, in _matches
    self.match_object = match_2nd_2F1_hypergeometric(d['I0'], d['k'], d['sing_point'], func)
  File "sympy/solvers/ode/hypergeometric.py", line 161, in match_2nd_2F1_hypergeometric
    _delta = -gamma*sing_point[1]
IndexError: list index out of range
```

**Comment by pranavkonidena** [comment]
Is this issue still open?

**Comment by guptapratykshh** [comment]
Here is the one approach to fix this issue, if we put an early check for both empty sing_point and insufficient length - 

```
    delta = Wild("delta")
    if not sing_point or len(sing_point) < 2:
        return None
    # I0 of the standerd 2F1 equation.
    I0 = ((a-b+1)*(a-b-1)*x**2 + 2*((1-a-b)*c + 2*a*b)*x + c*(c-2))/(4*x**2*(x-1)**2)
    if sing_point != [0, 1]:
        # If singular point is [0, 1] then we have standerd equation.
        eqs = []
```
symbolic mathematics can be computationally expensive, so early checking can save resources.
Please look into this approach and suggest if some changes can be made.
