### ISSUE TITLE
nsolve: TypeError: '>=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by satels** [sympy/sympy#25897]
Code:
```python
from sympy import symbols, Eq, nsolve

x, y, z = symbols('x y z', real=True)

args = ([Eq(x + 1, y**2 + 2*y*z + z**2), Eq(4*y*z, 4*x + 1), Eq(x*(y + z), (y - z)**2)], [z, y, x], (-10, -10, -10))

kwargs = {'modules': ['mpmath', 'sympy']}

nsolve(*args, **kwargs)
```

The error:
```python
Traceback (most recent call last):
    nsolve(*args, **kwargs)
  File "sympy/utilities/decorator.py", line 87, in func_wrapper
    return func(*args, **kwargs)
  File "sympy/solvers/solvers.py", line 3065, in nsolve
    x = findroot(f, x0, J=J, **kwargs)
  File "mpmath/calculus/optimization.py", line 969, in findroot
    for x, error in iterations:
  File "mpmath/calculus/optimization.py", line 660, in __iter__
    s = self.ctx.lu_solve(Jx, fxn)
  File "mpmath/matrices/linalg.py", line 224, in lu_solve
    A, p = ctx.LU_decomp(A)
  File "mpmath/matrices/linalg.py", line 140, in LU_decomp
    ctx.swap_row(A, j, p[j])
  File "mpmath/matrices/matrices.py", line 880, in swap_row
    A[i,k], A[j,k] = A[j,k], A[i,k]
  File "mpmath/matrices/matrices.py", line 490, in __getitem__
    if key[0] >= self.__rows or key[1] >= self.__cols:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

**Comment by smichr** [comment]
This is highlighting issues with mpmath interactions. The `solve` routine is able to resolve:
```python
>>> solve(*args[:2])
[(-1/2, -1/2, 0), (1/2, 1/2, 0)]
```

**Comment by oscarbenjamin** [comment]
This is perhaps a bug in mpmath and should be reported there:
```python
In [27]: import mpmath

In [28]: A = mpmath.matrix([[40, 40, 1], [-40, -40, -4], [-10, -10, -20]])

In [29]: mpmath.lu(A)
---------------------------------------------------------------------------
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```
SymPy's LU solver can handle this:
```python
In [30]: A = Matrix([[40, 40, 1], [-40, -40, -4], [-10, -10, -20]])

In [31]: A.LUdecomposition()
Out[31]: 
⎛⎡ 1    0   0⎤                  ⎞
⎜⎢           ⎥  ⎡40  40  1 ⎤    ⎟
⎜⎢ -1   1   0⎥  ⎢          ⎥    ⎟
⎜⎢           ⎥, ⎢0   0   -3⎥, []⎟
⎜⎢      79   ⎥  ⎢          ⎥    ⎟
⎜⎢-1/4  ──  1⎥  ⎣0   0   0 ⎦    ⎟
⎝⎣      12   ⎦                  ⎠
```
The problem as you can see here from the U matrix computed by SymPy is caused by the Jacobian matrix being singular but it should raise `ZeroDivisionError('matrix is numerically singular')` rather than `TypeError`.

The determinant of the Jacobian is:
```python
In [40]: eqs = [e.lhs - e.rhs for e in eqs]

In [41]: Matrix(eqs).jacobian([x, y, z])
Out[41]: 
⎡  1     -2⋅y - 2⋅z     -2⋅y - 2⋅z  ⎤
⎢                                   ⎥
⎢ -4         4⋅z            4⋅y     ⎥
⎢                                   ⎥
⎣y + z  x - 2⋅y + 2⋅z  x + 2⋅y - 2⋅z⎦

In [42]: Matrix(eqs).jacobian([x, y, z]).det().factor()
Out[42]: 
           ⎛       2                    2      ⎞
-4⋅(y - z)⋅⎝x + 2⋅y  + 4⋅y⋅z + 6⋅y + 2⋅z  + 6⋅z⎠
```
This will be singular if `y = z` which is the case for the initial values picked `(-10,-10,-10)`.

For different initial values it fails according to its tolerance requirements though. I think mpmath's `findroot` function needs a lot of work or perhaps SymPy is not calling it with good parameter options.
