### ISSUE TITLE
Numerical solve system of equations function (there is Abs) raise NameError 

### ISSUE THREAD

**Issue by satels** [sympy/sympy#25895]
```python
from sympy import nsolve, Eq, Abs, symbols

x, y = symbols('x y')


args = ([Eq(x - Abs(y), 3), Eq(4*x + 5*Abs(y), 21)], [y, x], (-10, -10))
kwargs = {'modules': ['mpmath', 'sympy']}


sol = nsolve(*args, **kwargs)
```

The error:
```python
Traceback (most recent call last):
    sol = nsolve(*args, **kwargs)
  File "sympy/utilities/decorator.py", line 87, in func_wrapper
    return func(*args, **kwargs)
  File "sympy/solvers/solvers.py", line 3065, in nsolve
    x = findroot(f, x0, J=J, **kwargs)
  File "mpmath/calculus/optimization.py", line 969, in findroot
    for x, error in iterations:
  File "mpmath/calculus/optimization.py", line 659, in __iter__
    Jx = J(*x0)
  File "<lambdifygenerated-2>", line 5, in _lambdifygenerated
    ImmutableDenseMatrix([[-(re(y)*Derivative(re(y), y) + im(y)*Derivative(im(y), y))*sign(y)/y, 1], [5*(re(y)*Derivative(re(y), y) + im(y)*Derivative(im(y), y))*sign(y)/y, 4]]))
NameError: name 'Derivative' is not defined
```

**Comment by satels** [comment]
Code with `real=True` symbols is work fine

**Comment by oscarbenjamin** [comment]
This is because if the symbols are not real then the derivative is not defined:
```python
In [14]: abs(x).diff(x)
Out[14]: 
⎛      d                 d        ⎞        
⎜re(x)⋅──(re(x)) + im(x)⋅──(im(x))⎟⋅sign(x)
⎝      dx                dx       ⎠        
───────────────────────────────────────────
                     x 
```
I don't know where that comes from `abs(z)` is not complex-differentiable (and neither are `re(z)` and `im(z)`) so this should be unevaluated.

There should be a better way than setting real=True on the symbols to say when a real derivative is wanted e.g. `nsolve` knows that it wants a real derivative here.

**Comment by smichr** [comment]
cf #25779
