### ISSUE TITLE
Support for NumPy-arrays and/or integers in `SOPform` etc

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#26164]
Just stumbled upon this.

I wanted to create a Boolean function from a truth table that I happened to create using numpy and encountered the following two problems:

The check here:
https://github.com/sympy/sympy/blob/ac42c1da3f4888b9bdaf65e83184a4fb9d334e02/sympy/logic/boolalg.py#L2393-L2394
gave an error since one cannot check if numpy arrays are empty like that.

Converting the numpy-array to a list (easy enough) gave an error here:
https://github.com/sympy/sympy/blob/ac42c1da3f4888b9bdaf65e83184a4fb9d334e02/sympy/logic/boolalg.py#L2307-L2330
as the numpy.int64 did not match and of the types.

Not a big deal, and SymPy is not dependent on NumPy for sure, but it would still be convenient if this worked. Not so clear how to solve it in a transparent way though...

**Comment by shishir-11** [comment]
Can you give the code which you were trying to implement initially , I think I got a solution but i need to check if it works .

**Comment by oscargus** [comment]
Try something like:
``` python
minterms = np.array([1, 2])
```
to see the first problem and
``` python
minterms = list(minterms)
```
for the second.

**Comment by shishir-11** [comment]
The first error can be solved if we used 
"if len(minterms)==0" instead of "if not minterms" 
However we would need to Convert from a numpy array to a list before using it in the _input_to_binlist function that you did , but I dont know if it can be done without importing numpy in the file

**Comment by oscargus** [comment]
I guess it should be `if not len(minterms)` (means the same thing, but static linters doesn't really like the `== 0` approach).

I'm wondering if you actually need to convert it? You should be able to iterate over it and then you can add two more cases:
```

numpy = import_module(numpy)

...


elif numpy is not None and isinstance(val, numpy.array): 


elif numpy is not None and isinstance(val, (numpy.int64, ...)): 

``` 

I think.

**Comment by oscarbenjamin** [comment]
To be clear we are talking about this:
```python
>>> from sympy import *
>>> import numpy as np
>>> x, y, z = symbols('x, y, z')
>>> SOPform([x, y, z], [1, 2, 3])
(y & ~x) | (z & ~x)
```
It fails if the argument is a numpy array:
```python
>>> SOPform([x, y, z], np.array([1, 2, 3]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../sympy/logic/boolalg.py", line 2393, in SOPform
    if not minterms:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Or a list of numpy scalars:
```python
>>> SOPform([x, y, z], list(np.array([1, 2, 3])))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../sympy/logic/boolalg.py", line 2399, in SOPform
    minterms = _input_to_binlist(minterms, variables)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../sympy/logic/boolalg.py", line 2328, in _input_to_binlist
    raise TypeError("A term list can only contain lists,"
TypeError: A term list can only contain lists, ints or dicts.
```
There should be no need to special case numpy arrays explicitly here. We get into this kind of problem by being too permissive about what the input types are supposed to be. If it were something well defined like "an iterable of iterables of sympifiables" then the code could be written simply according to those assumptions and could work generically for many possible types of inputs in a well defined way.

That is how duck-typing works but duck-typing does not marry well with the explicit type checks that are used here. All sorts of weird combinations of options are supported and only type checks can make it work:
```python
In [5]: SOPform([x, y, z], [[0,1,2],2])
Out[5]: y ∧ ¬x ∧ ¬z

In [6]: SOPform([x, y, z], [1,2,3])
Out[6]: (y ∧ ¬x) ∨ (z ∧ ¬x)

In [7]: SOPform([x, y, z], [[1,2,3],2])
Out[7]: (x ∧ ¬y) ∨ (y ∧ ¬x ∧ ¬z)

In [8]: SOPform([x, y, z], [[1,2,3],[0,1,2]])
Out[8]: (x ∧ ¬y) ∨ (y ∧ ¬x ∧ ¬z)

In [9]: SOPform([x, y, z], [{x:1},2,[0,1,2]])
Out[9]: x ∨ (y ∧ ¬z) ∨ (y ∧ ¬x ∧ ¬z)
```
If numpy arrays are to be allowed then it could be 1d or 2d arrays:
```python
In [10]: SOPform([x, y, z], [1,2,3])
Out[10]: (y ∧ ¬x) ∨ (z ∧ ¬x)

In [11]: SOPform([x, y, z], [[1,2,3],[0,1,2]])
Out[11]: (x ∧ ¬y) ∨ (y ∧ ¬x ∧ ¬z)
```
Whatever happens we are going to iterate over minterms but each item in the iterable should be either a dict, an integer or something like a list of integers. Distinguishing a mapping from a sequence is awkward in Python but an explicit special case for dict is probably good enough. We are then left with an object that is either an integer (of some type) or an iterable of some type of integers which could mean a list, a tuple or a numpy array. What is needed is to distinguish between something that could be converted to an integer and something that is an iterable of integers. I suggest to use `iterable()` to distinguish these. Then any kind of integer can be converted to a Python integer with `operator.index`.
```python
for val in inputlist:
    if isinstance(val, dict):
        ...
    elif iterable(val):
        nums = [index(v) for v in val]
        ...
    else:
        nums = ibin(index(val))
    ...
```

**Comment by oscargus** [comment]
Good summary and idea!

**Comment by shishir-11** [comment]
> I guess it should be `if not len(minterms)` (means the same thing, but static linters doesn't really like the `== 0` approach).
> 
> I'm wondering if you actually need to convert it? You should be able to iterate over it and then you can add two more cases:
> 
> ```
> 
> numpy = import_module(numpy)
> 
> ...
> 
> 
> elif numpy is not None and isinstance(val, numpy.array): 
> 
> 
> elif numpy is not None and isinstance(val, (numpy.int64, ...)): 
> ```
> 
> I think.

Yes I guess that is a better way if we were to go about it .

**Comment by shishir-11** [comment]
@oscarbenjamin @oscargus I'm a bit confused on the implementation shown in the last comment , although I do understand the concept .  Is `iterable()` some inbuilt function or already defined somewhere ? Otherwise we could use `hasattr(<array_name>,'__iter__')` or a try and except block the perform the required changes if we are to allow numpy arrays .

**Comment by oscargus** [comment]
It is a SymPy-function:

https://github.com/sympy/sympy/blob/0b809238408bd4baa57146ffc9f82eb1685d8fd8/sympy/utilities/iterables.py#L3026

(although I admittedly forgot about it).

**Comment by shishir-11** [comment]
I was trying to add the support for numpy arrays in the way suggested above , and it works for 2D arrays , but for 1D numpy arrays the isinstance gives false . Is there a alternative to it or should i write function that checks  `!(val%1)` instead of instance

**Comment by shishir-11** [comment]
Kindly Review my PR and tell me if there are any suggestions / changes .

**Comment by shishir-11** [comment]
In PR #26200 I have made the required changes for working with numpy array in SOPform and POSform for both minterms and dont cares which I could not in the previous PR . Kindly look into it and tell me if problems persist .
