### ISSUE TITLE
Asymptotic series expansions for Shi & Chi functions

### ISSUE THREAD

**Issue by anutosh491** [sympy/sympy#26208]
Though the limits work for most general points, these limits can also work more simply through gruntz if we have asymptotic series expansions. Currently we have none 
```
>>> Shi(x).series(x, oo)
Traceback (most recent call last):
...................
sympy.core.function.PoleError:
Asymptotic expansion of Shi around [oo] is not implemented.
>>>
>>> Chi(x).series(x, oo)
Traceback (most recent call last):
.................
sympy.core.function.PoleError:
Asymptotic expansion of Chi around [oo] is not implemented.
```

**Comment by mohakmalviya** [comment]
@anutosh491 sir for the expansions of `Shi` and `Chi` series from `(x, oo)` there will be infinite terms so we have to take approximations of the terms?

**Comment by abhiphile** [comment]
I've tried using this function inside of `Shi` and it shows correct result for `oo` but shows error while performing expansion around `-oo` and I can't understand what is causing this error.


```
    def _eval_aseries(self, n, args0, x, logx):
        from sympy.series.order import Order
        point = args0[0]
        if point in (S.Infinity, S.NegativeInfinity):
            z = self.args[0]
            p = [factorial(2*k) / z**(2*k)
                    for k in range(int((n - 1)/2))] + [Order(1/z**n, x)]
            q = [factorial(2*k + 1) / z**(2*k + 1)
                    for k in range(int(n/2) - 1)] + [Order(1/z**n, x)]
            r = sinh(z + Add(*[Order(1/z**n, x)]))
            s = cosh(z + Add(*[Order(1/z**n, x)]))
            result = (s/z)*Add(*p) - (r/z)*Add(*q)
            if point is S.Infinity:
                result -= I*pi/2
            else:
                result += I*pi/2

            return result
        return super()._eval_aseries(n, args0, x, logx)
```

**Comment by abhiphile** [comment]
```>>> Shi(x).series(x,oo)
-I*pi/2 - (6/x**3 + 1/x + O(x**(-7), (x, oo)))*sinh(x + O(x**(-7), (x, oo)))/x + (24/x**4 + 2/x**2 + 1 + O(x**(-7), (x, oo)))*cosh(x + O(x**(-7), (x, oo)))/x
>>> Shi(x).series(x,-oo)
Traceback (most recent call last):
  File "/home/abhishek/contributing/sympy/sympy/core/mul.py", line 1962, in _eval_nseries
    coeff, exp = t.leadterm(x)
  File "/home/abhishek/contributing/sympy/sympy/core/expr.py", line 3533, in leadterm
    raise ValueError(filldedent("""
ValueError: 
cannot compute leadterm(Shi(1/_x), _x). The coefficient should have
been free of _x but got Shi(1/_x)

During handling of the above exception, another exception occurred:
.......................
  File "/home/abhishek/contributing/sympy/sympy/series/gruntz.py", line 320, in mrv
    raise NotImplementedError(
NotImplementedError: Don't know how to calculate the mrv of 'O(_x**(-7), (_x, oo))'```

**Comment by mohakmalviya** [comment]
> ```
> >>> Shi(x).series(x,oo)
> 
> -I*pi/2 - (6/x**3 + 1/x + O(x**(-7), (x, oo)))*sinh(x + O(x**(-7), (x, oo)))/x + (24/x**4 + 2/x**2 + 1 + O(x**(-7), (x, oo)))*cosh(x + O(x**(-7), (x, oo)))/x
> 
> >>> Shi(x).series(x,-oo)
> Traceback (most recent call last):
>   File "/home/abhishek/contributing/sympy/sympy/core/mul.py", line 1962, in _eval_nseries
>     coeff, exp = t.leadterm(x)
>   File "/home/abhishek/contributing/sympy/sympy/core/expr.py", line 3533, in leadterm
>     raise ValueError(filldedent("""
> ValueError: 
> cannot compute leadterm(Shi(1/_x), _x). The coefficient should have
> been free of _x but got Shi(1/_x)
> 
> During handling of the above exception, another exception occurred:
> .......................
>   File "/home/abhishek/contributing/sympy/sympy/series/gruntz.py", line 320, in mrv
>     raise NotImplementedError(
> NotImplementedError: Don't know how to calculate the mrv of 'O(_x**(-7), (_x, oo))'```
> ```
I think you are almost there....you just need to replace any order term at infinity with zero!
you can use this - `result.subs(Order(1/z**n, x), 0)`

**Comment by abhiphile** [comment]
> I think you are almost there....you just need to replace any order term at infinity with zero! you can use this - `result.subs(Order(1/z**n, x), 0)`
No, I think it is wrong because the series term should contain `Order` terms inside it.

**Comment by mohakmalviya** [comment]
> > I think you are almost there....you just need to replace any order term at infinity with zero! you can use this - `result.subs(Order(1/z**n, x), 0)`
> 
> No, I think it is wrong because the series term should contain `Order` terms inside it.

i tried it using your code and it worked fine for me

**Comment by abhiphile** [comment]
Yeah, I know it will work fine, but substituting is not a solution here because, in `series`, you must also include future terms.
Now, if you replace the order term, how will you get the future terms?

**Comment by mohakmalviya** [comment]
> Yeah, I know it will work fine, but substituting is not a solution here because, in `series`, you must also include future terms. Now, if you replace the order term, how will you get the future terms?

yes you are right! so instead of 0 you can replace it with calculated future_terms....it should be like this - 
```diff
+ future_terms = 'your calculated future terms'
-  result.subs(Order(1/z**n, x), 0)
+ result.subs(Order(1/z**n, x), future_terms)
```

**Comment by abhiphile** [comment]
I am unable to understand your point here. Can you explain to me in detail what needs to be done? I can see that the error arises in gruntz and that needs to be tackled I guess.

**Comment by samithkavishke** [comment]
I think [issue #25991](https://github.com/sympy/sympy/issues/25991) also links with this issue, since the `as_leading_term` does not give the correct output this also must throw an error.

**Comment by Jatinbhardwaj-093** [comment]
This is an issue in the expansion used by the Powsimp in mul.py function _eval_nseries.
https://github.com/sympy/sympy/blob/930b991f260ddb50c66d8094a091750d742bbecc/sympy/core/mul.py#L1997-L2009


As the `Shi` function is going to throw the negative factor out from the function it becomes the mul expression then it uses the `nseries` function of `mul`.


> 
> ```
>     def _eval_aseries(self, n, args0, x, logx):
>         from sympy.series.order import Order
>         point = args0[0]
>         if point in (S.Infinity, S.NegativeInfinity):
>             z = self.args[0]
>             p = [factorial(2*k) / z**(2*k)
>                     for k in range(int((n - 1)/2))] + [Order(1/z**n, x)]
>             q = [factorial(2*k + 1) / z**(2*k + 1)
>                     for k in range(int(n/2) - 1)] + [Order(1/z**n, x)]
>             r = sinh(z + Add(*[Order(1/z**n, x)]))
>             s = cosh(z + Add(*[Order(1/z**n, x)]))
>             result = (s/z)*Add(*p) - (r/z)*Add(*q)
>             if point is S.Infinity:
>                 result -= I*pi/2
>             else:
>                 result += I*pi/2
> 
>             return result
>         return super()._eval_aseries(n, args0, x, logx)
> ```


So there is no reason to check for the Negative Infinity in _eval_aseries as it never going to call a function for `-oo`.


I think checking explicitly for the Shi function in argument is the way to fix it if we go with the current way of simp with expanding it to try to open the `Shi` function.

**Comment by Jatinbhardwaj-093** [comment]
I’ve created a pull request for this. cc@anutosh491, could you please review it?

**Comment by hemanth678901-stack** [comment]
I would like to work on this issue. I will review the existing **_eval_aseries** implementations for **Si** and **Ci** and attempt to add analogous support for **Shi** and **Chi**. Please let me know if there are any specific constraints I should be aware of.
