### ISSUE TITLE
Asymptotic series expansion for Cosine Integral function

### ISSUE THREAD

**Issue by anutosh491** [sympy/sympy#26207]
I was just testing out the asymptotic series & limits at infinity for some error functions and I found this 
```
>>> Si(x).series(x, oo)
pi/2 - (-6/x**3 + 1/x + O(x**(-7), (x, oo)))*sin(x)/x - (24/x**4 - 2/x**2 + 1 + O(x**(-7), (x, oo)))*cos(x)/x
>>>
>>> Si(x).series(x, -oo)
-24*cos(x)/x**5 + 6*sin(x)/x**4 + 2*cos(x)/x**3 - sin(x)/x**2 - cos(x)/x - pi/2 + O(x**(-6), (x, -oo))
>>>
>>> Ci(x).series(x, oo)
-(-6/x**3 + 1/x + O(x**(-7), (x, oo)))*cos(x)/x + (24/x**4 - 2/x**2 + 1 + O(x**(-7), (x, oo)))*sin(x)/x
>>>
>>> Ci(x).series(x, -oo)
Traceback (most recent call last):
  File "C:\Users\91989\sympy\sympy\sympy\core\expr.py", line 2994, in series
    s = self.subs(x, cdir/x).series(x, n=n, dir='+', cdir=1)
  File "C:\Users\91989\sympy\sympy\sympy\core\expr.py", line 3015, in series
    rv = self.subs(x, xpos).series(xpos, x0, n, dir, logx=logx, cdir=cdir)
  File "C:\Users\91989\sympy\sympy\sympy\core\expr.py", line 3023, in series
    s1 = self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "C:\Users\91989\sympy\sympy\sympy\functions\special\error_functions.py", line 1800, in _eval_nseries
    return super()._eval_nseries(x, n, logx)
  File "C:\Users\91989\sympy\sympy\sympy\core\function.py", line 690, in _eval_nseries
    return self._eval_aseries(n, args0, x, logx)
  File "C:\Users\91989\sympy\sympy\sympy\functions\special\error_functions.py", line 2082, in _eval_aseries
    return super(Ci, self)._eval_aseries(n, args0, x, logx)
  File "C:\Users\91989\sympy\sympy\sympy\core\function.py", line 653, in _eval_aseries
    raise PoleError(filldedent('''
sympy.core.function.PoleError:
Asymptotic expansion of Ci around [-oo] is not implemented.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\91989\sympy\sympy\sympy\core\expr.py", line 2999, in series
    s = self.subs(x, cdir*x).aseries(x, n=n)
  File "C:\Users\91989\sympy\sympy\sympy\core\expr.py", line 3198, in aseries
    return self.subs(x, xpos).aseries(xpos, n, bound, hir).subs(xpos, x)
  File "C:\Users\91989\sympy\sympy\sympy\core\expr.py", line 3216, in aseries
    s = self.subs(x, exp(x)).aseries(x, n, bound, hir).subs(x, log(x))
  File "C:\Users\91989\sympy\sympy\sympy\core\expr.py", line 3238, in aseries
    s = func.series(k, 0, n)
  File "C:\Users\91989\sympy\sympy\sympy\core\expr.py", line 3023, in series
    s1 = self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "C:\Users\91989\sympy\sympy\sympy\functions\special\error_functions.py", line 1800, in _eval_nseries
    return super()._eval_nseries(x, n, logx)
  File "C:\Users\91989\sympy\sympy\sympy\core\function.py", line 690, in _eval_nseries
    return self._eval_aseries(n, args0, x, logx)
  File "C:\Users\91989\sympy\sympy\sympy\functions\special\error_functions.py", line 2082, in _eval_aseries
    return super(Ci, self)._eval_aseries(n, args0, x, logx)
  File "C:\Users\91989\sympy\sympy\sympy\core\function.py", line 653, in _eval_aseries
    raise PoleError(filldedent('''
sympy.core.function.PoleError:
Asymptotic expansion of Ci around [-oo] is not implemented.
```

**Comment by anutosh491** [comment]
What we have (which is the first 3 expansions) is perfectly correct but the last one doesn't work. `Ci(x)` at `-oo` , the expansion should be pretty similar to what we have at `oo` but an `I*pi` term. The expansion from wolfram can be viewed [here](https://www.wolframalpha.com/input?i=series+Ci%28x%29+at+-oo)

**Comment by mohakmalviya** [comment]
@anutosh491 hello sir i have noticed that sympy is representing order terms for negative expansions as O(-1/x**7) and the same term for positive expansion as O(x**(-7))

**Comment by haru-44** [comment]
I don't understand the basics, is this a correct result?

> ```python
>  >>> Ci(x).series(x, oo)
> -(-6/x**3 + 1/x + O(x**(-7), (x, oo)))*cos(x)/x + (24/x**4 - 2/x**2 + 1 + O(x**(-7), (x, oo)))*sin(x)/x
> ```

According to [Wikipedia](https://en.wikipedia.org/wiki/Trigonometric_integral#Asymptotic_series_(for_large_argument)),
```math
\mbox{Ci}(x) \sim \frac{\sin x}{x}\left(1-\frac{2!}{x^2}+\frac{4!}{x^4}-\frac{6!}{x^6}\cdots\right)
 - \frac{\cos x}{x}\left(\frac{1}{x}-\frac{3!}{x^{3}}+\frac{5!}{x^5}-\frac{7!}{x^7}\cdots\right)
```

My two questions are as follows.

* Why is there no `120/x**5` and `720/x**6`?
* If `series(x, oo, n=6)`, why not `O(x**(-6))`?

**Comment by anutosh491** [comment]
Yes these questions make sense
For eg we have 
```
>>> sin(1/x).series(x, oo)
1/(120*x**5) - 1/(6*x**3) + 1/x + O(x**(-6), (x, oo))
```
Similarly in the expanded form, we should have 
```
>>> Ci(x).series(x, oo).expand()
24*sin(x)/x**5 + 6*cos(x)/x**4 - 2*sin(x)/x**3 - cos(x)/x**2 + sin(x)/x + O(x**(-6), (x, oo))
```
And not 
```
>>> Ci(x).series(x, oo).expand()
24*sin(x)/x**5 + 6*cos(x)/x**4 - 2*sin(x)/x**3 - cos(x)/x**2 + sin(x)/x + O(x**(-8), (x, oo))
```

And I see this error being present in almost any error function for which we support asymptotic series currently, for eg
```
>>> Si(x).series(x, oo).expand()
-24*cos(x)/x**5 + 6*sin(x)/x**4 + 2*cos(x)/x**3 - sin(x)/x**2 - cos(x)/x + pi/2 + O(x**(-8), (x, oo))
```

**Comment by arnabnandikgp** [comment]
I think the problem with the order term stems from the following:
https://github.com/sympy/sympy/blob/473d05c1a00a136be535c63f56dff7a05d9b47bd/sympy/functions/special/error_functions.py#L1796-L1799
I am not sure why it was increased in the first place but it seems that it does not affect the series expansion in any other way except for the order term.

**Comment by anutosh491** [comment]
Okay I think the nseries methods for these trigonometric integral functions might need some revamping. I think they can be simplified/improved. @arnabnandikgp would like to look into it !

**Comment by arnabnandikgp** [comment]
I looked into it, and it seems that the line `n+=1` is not affecting the results in any way other than in order term though for the following line 
https://github.com/sympy/sympy/blob/24792d5f4fbf8fe4365101e53b735c6c1f140e0f/sympy/functions/special/error_functions.py#L1804
which essentialy mimics the process of integration involved in these functions. I am not sure if any improvement can be achieved here.
Though for the inconsistencies in the number of terms i.e for missing terms I think the following diff may solve the issue
```diff
     def _eval_aseries(self, n, args0, x, logx):
         from sympy.series.order import Order
         point = args0[0]
 
         if point in (S.Infinity, S.NegativeInfinity):
             z = self.args[0]
             p = [S.NegativeOne**k * factorial(2*k) / z**(2*k)
-                    for k in range(int((n - 1)/2))] + [Order(1/z**n, x)]
+                    for k in range(int(n/2))] + [Order(1/z**n, x)]
             q = [S.NegativeOne**k * factorial(2*k + 1) / z**(2*k + 1)
-                    for k in range(int(n/2) - 1)] + [Order(1/z**n, x)]
+                    for k in range(int((n)/2))] + [Order(1/z**n, x)]
             result = (sin(z)/z)*Add(*p) - (cos(z)/z)*Add(*q)

```

**Comment by anutosh491** [comment]
Hmm, that makes sense, good ahead and raise a PR for the same.
