### ISSUE TITLE
Wigner3j has problems with Half Integers 

### ISSUE THREAD

**Issue by shishir-11** [sympy/sympy#26219]
I was trying to find the result of this operation and am getting this error for half integers
```
>>> w3j = Wigner3j(0,0,1/2,1/2,1/2,-1/2)    
>>> w3j.doit()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:\Orgs\sympy\sympy\physics\quantum\cg.py", line 158, in doit 
    return wigner_3j(self.j1, self.j2, self.j3, self.m1, self.m2, self.m3)
  File "D:\Orgs\sympy\sympy\physics\wigner.py", line 199, in wigner_3j
    raise ValueError("j values must be integer or half integer")      
ValueError: j values must be integer or half integer
>>> w3j = Wigner3j(0.5,0.5,0.5,0.5,0.5,0.5)
>>> w3j.doit()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:\Orgs\sympy\sympy\physics\quantum\cg.py", line 158, in doit 
    return wigner_3j(self.j1, self.j2, self.j3, self.m1, self.m2, self.m3)
  File "D:\Orgs\sympy\sympy\physics\wigner.py", line 199, in wigner_3j    raise ValueError("j values must be integer or half integer")      
ValueError: j values must be integer or half integer
```
It is working fine for integer values but gives an error of values with half integers .

**Comment by oscarbenjamin** [comment]
What happens if rational numbers are used instead of floats?

**Comment by HimaTeju** [comment]
@shishir-11 
![Screenshot 2024-02-12 082826](https://github.com/sympy/sympy/assets/90406478/a06fdded-9fa2-469c-8f2d-78dbbc072057)

**Comment by shishir-11** [comment]
```
import sympy
from sympy import Rational
import sympy.physics.wigner as w

a = Rational(1,2)
b=w.Wigner3j(a,a,a,a,a,a)
b.doit()

0
```
I think Rationals are working fine in my case , although I dont think there should be any difference in handling sympy rationals and floating point numbers here .

**Comment by shishir-11** [comment]
This issue seems to be specific to the inbuilt sympy shell that we run in the local repository . The examples used by me initially are working fine on colab .

**Comment by T-vaccari** [comment]
Hello @shishir-11 , @oscarbenjamin : 



The function that rises the errors is this one : 

```
class Wigner3j(Function):

    def doit(self, **hints):
        if all(obj.is_number for obj in self.args):
            return wigner_3j(*self.args)
        else:
            return self
```

So the problems seems to be in handling half integer so I think we can modify the function as follow:
```
class Wigner3j(Function):

    def doit(self, **hints):
        # Check if all arguments are numbers (integers or floats)
        if all(obj.is_number for obj in self.args):
            # Check if all arguments are either integers or half-integers
            if all(obj % 1 == 0 or obj % 1 == Rational(1, 2) for obj in self.args):
                # Call the wigner_3j function with the numeric arguments
                return wigner_3j(*self.args)
            else:
                raise ValueError("j values must be integer or half integer")
        else:
            # If not all arguments are numbers, return self without evaluation
            return self

```

I am new to this project , so feel free to suggest  about my proposal for this function , thanks !!!

**Comment by oscarbenjamin** [comment]
With SymPy 1.12 we have:
```python
In [1]: from sympy.physics.wigner import Wigner3j

In [2]: Wigner3j(0,0,1/2,1/2,1/2,-1/2).doit()
Out[2]: 0
```
Probably the difference is that now floats and rationals don't compare equal any more.

**Comment by T-vaccari** [comment]
@oscarbenjamin so what do you suggest?

**Comment by shishir-11** [comment]
@T-vaccari The Value error is being handled inside the `wigner_3j` function so I dont't think we  need to handle it in the `doit` method .

**Comment by T-vaccari** [comment]
Show me the piece of code where we handle the value error in the `wigner_3j` function

**Comment by T-vaccari** [comment]
"We need to ensure that when inserting half-integer values, we use the `Rational` function, as opposed to Python's standard floating-point division (b = 1/2). This ensures accurate representation and proper handling of half-integer values in SymPy functions like Wigner3j, avoiding potential issues related to floating-point arithmetic

**Comment by shishir-11** [comment]
```
>>> from sympy.physics.quantum.cg import Wigner3j
>>> a = Rational(1,2)
>>> b = 0.5
>>> int(a*2)==a*2
True
>>> int(b*2)==b*2 
True
>>> w3j = Wigner3j(a,a,a,a,a,a)
>>> w3j

⎛1/2  1/2  1/2⎞
⎜             ⎟
⎝1/2  1/2  1/2⎠
>>> w3j.doit()
0
>>> w3j = Wigner3j(b,b,b,b,b,b) 
>>> w3j

⎛0.5  0.5  0.5⎞
⎜             ⎟
⎝0.5  0.5  0.5⎠
>>> w3j.doit()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:\Orgs\sympy\sympy\physics\quantum\cg.py", line 158, in doit 
    return wigner_3j(self.j1, self.j2, self.j3, self.m1, self.m2, self.m3)
  File "D:\Orgs\sympy\sympy\physics\wigner.py", line 199, in wigner_3j
    raise ValueError("j values must be integer or half integer")      
ValueError: j values must be integer or half integer
```

This behaviour is very ambiguous given the code handling this 
```
if int(j_1 * 2) != j_1 * 2 or int(j_2 * 2) != j_2 * 2 or \
            int(j_3 * 2) != j_3 * 2:
        raise ValueError("j values must be integer or half integer")
```
Is it happening cause of changes in data type . I printed the types of j values and got the following 

```
<class 'sympy.core.numbers.Half'> <class 'sympy.core.numbers.Half'> <class 'sympy.core.numbers.Half'>
<class 'sympy.core.numbers.Float'> <class 'sympy.core.numbers.Float'> <class 'sympy.core.numbers.Float'>
```

I suggest using some method to convert them all to a uniform type but as mentioned in several other places would be a problem with the ducktyping . I'd say we should find out where the parameters are being converted to the the above types . 

@oscarbenjamin Can you please explain why we are using the sympy number types and why some number can be compared to their python counterparts but others can't . Is it a flaw or something intentionally designed .

**Comment by T-vaccari** [comment]
The solution to the problem is to ensure that all input values provided to the Wigner3j function are represented using SymPy number types, such as Rational. Maybe we can work on this if we are allowed to.
What do you think @oscarbenjamin, @shishir-11 ?

**Comment by T-vaccari** [comment]
I think www can adjust the condition in the `Wigner_3j` function to check if the input is an integer or an half integer , so I think that we can modify the conditions as follow : 
```
def is_half_integer(num):
    return num.denominator == 2

# Validation checks
if not (isinstance(j_1, int, Rational) or is_half_integer(Fraction(j_1))) or \
        not (isinstance(j_2, int, Rational) or is_half_integer(Fraction(j_2))) or \
        not (isinstance(j_3, int, Rational) or is_half_integer(Fraction(j_3))):
    raise ValueError("j values must be integer or half integer")
if not (isinstance(m_1, int, Rational) or is_half_integer(Fraction(m_1))) or \
        not (isinstance(m_2, int, Rational) or is_half_integer(Fraction(m_2))) or \
        not (isinstance(m_3, int, Rational) or is_half_integer(Fraction(m_3))):
    raise ValueError("m values must be integer or half integer")
```
So now we are checking if the number is an integer or a Rational and otherwise we are checking if it's an half integer .
Tell me what do you think about this!
@oscarbenjamin @shishir-11

**Comment by T-vaccari** [comment]
Someone can please tell me how can I test if it works with this ?

**Comment by T-vaccari** [comment]
thank you @shishir-11 , what do you think about the code?

**Comment by shishir-11** [comment]
I'm relatively new to this project as well so I cant comment much on the solutions corrections . However from what I have noticed , we should try to minimise coercing to types , sympy has a lot of internally built classes which might cause the numbers to have different types which may cause the code to fail . We need to make solutions that can process on any type of integer/half integer values indiscriminately.

**Comment by T-vaccari** [comment]
I rune the test and its working , now I'm trying to write some test related to the issue

**Comment by shishir-11** [comment]
the problem with this issue was that all the tests ran fine initially as well , and it runs fine in the versions used in jupyter notebook as well . It is the ambiguous behavior ocurring in the `bin/isympy` that has this trouble . And I think we should actually be fixing the root cause of this issue . Wigner3j isn't the only one dependent on the function causing the issue .

**Comment by T-vaccari** [comment]
ok so we have to check also other functions?

**Comment by T-vaccari** [comment]
I think I resolved the problem, now the code pass the test cases with the input that raised error before ,  do you want to look at the code?

**Comment by oscarbenjamin** [comment]
There is a function `int_valued` that can be used for this:
```python
In [1]: from sympy.core.numbers import int_valued

In [2]: int_valued(2*0.5)
Out[2]: True
```

**Comment by shishir-11** [comment]
Was there any progress on the PR related to this issue . Are we allowed to open parallel PRs when one is already going on without any activity .

**Comment by oscarbenjamin** [comment]
You can open another PR if you want but in the first instance it is better to review and advise on the existing PR.

**Comment by shishir-11** [comment]
> You can open another PR if you want but in the first instance it is better to review and advise on the existing PR.

Thanks for the clarification , will keep that in mind .
