### ISSUE TITLE
Incompatibility with mpmath 1.4

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#26268]
I previously had a PR to make sympy compatible with recent changes in mpmath master branch. It ended up getting changed a lot and was not tested with mpmath master: https://github.com/sympy/sympy/pull/25290#discussion_r1501421097

With current mpmath master:
```
>>> import sympy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oscar/current/active/sympy/sympy/__init__.py", line 30, in <module>
    from sympy.core.cache import lazy_function
  File "/home/oscar/current/active/sympy/sympy/core/__init__.py", line 9, in <module>
    from .expr import Expr, AtomicExpr, UnevaluatedExpr
  File "/home/oscar/current/active/sympy/sympy/core/expr.py", line 4155, in <module>
    from .mul import Mul
  File "/home/oscar/current/active/sympy/sympy/core/mul.py", line 2194, in <module>
    from .numbers import Rational
  File "/home/oscar/current/active/sympy/sympy/core/numbers.py", line 4337, in <module>
    _sympy_converter[type(mpmath.rational.mpq(1, 2))] = sympify_mpmath_mpq
                          ^^^^^^^^^^^^^^^
AttributeError: module 'mpmath' has no attribute 'rational'
```

**Comment by oscarbenjamin** [comment]
After gh-26269 sympy is compatible with the latest changes in mpmath but a new sympy release is needed ASAP.

**Comment by oscarbenjamin** [comment]
See https://github.com/mpmath/mpmath/issues/704#issuecomment-1962390809

**Comment by oscarbenjamin** [comment]
As it stands the sympy master branch is compatible with mpmath's master branch. Just a new release of sympy is needed before the next release of mpmath.

**Comment by oscarbenjamin** [comment]
Closing as this is fixed in master.
