### ISSUE TITLE
sympify "N" (newton) error

### ISSUE THREAD

**Issue by memoriadecalculo** [sympy/sympy#26422]
When trying to sympify an expression with newton unit abreviated ("N"), it raises an exception because it considered "N" as an expression and not as a unit, as you can see below:

```
**>>> sympify('10*N')**
ValueError: Error from parse_expr with transformed code: 'Integer (10 )*N '

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sympy/core/sympify.py", line 472, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/usr/lib/python3/dist-packages/sympy/parsing/sympy_parser.py", line 1026, in parse_expr
    raise e from ValueError(f"Error from parse_expr with transformed code: {code!r}")
  File "/usr/lib/python3/dist-packages/sympy/parsing/sympy_parser.py", line 1017, in parse_expr
    rv = eval_expr(code, local_dict, global_dict)
  File "/usr/lib/python3/dist-packages/sympy/parsing/sympy_parser.py", line 911, in eval_expr
    expr = eval(
  File "<string>", line 1, in <module>
**TypeError: unsupported operand type(s) for *: 'Integer' and 'function'**
```

This probably happens because sympify module imports "N function" in the line 61:

```
from .core import (sympify, SympifyError, cacheit, Basic, Atom,
        preorder_traversal, S, Expr, AtomicExpr, UnevaluatedExpr, Symbol,
        Wild, Dummy, symbols, var, Number, Float, Rational, Integer,
        NumberSymbol, RealNumber, igcd, ilcm, seterr, E, I, nan, oo, pi, zoo,
        AlgebraicNumber, comp, mod_inverse, Pow, integer_nthroot, integer_log,
        Mul, prod, Add, Mod, Rel, Eq, Ne, Lt, Le, Gt, Ge, Equality,
        GreaterThan, LessThan, Unequality, StrictGreaterThan, StrictLessThan,
        vectorize, Lambda, WildFunction, Derivative, diff, FunctionClass,
        Function, Subs, expand, PoleError, count_ops, expand_mul, expand_log,
        expand_func, expand_trig, expand_complex, expand_multinomial, nfloat,
        expand_power_base, expand_power_exp, arity, PrecisionExhausted, **N**,
        evalf, Tuple, Dict, gcd_terms, factor_terms, factor_nc, evaluate,
        Catalan, EulerGamma, GoldenRatio, TribonacciConstant)
```

And again in the line 270:

```
__all__ = [
    # sympy.core
    'sympify', 'SympifyError', 'cacheit', 'Basic', 'Atom',
    'preorder_traversal', 'S', 'Expr', 'AtomicExpr', 'UnevaluatedExpr',
    'Symbol', 'Wild', 'Dummy', 'symbols', 'var', 'Number', 'Float',
    'Rational', 'Integer', 'NumberSymbol', 'RealNumber', 'igcd', 'ilcm',
    'seterr', 'E', 'I', 'nan', 'oo', 'pi', 'zoo', 'AlgebraicNumber', 'comp',
    'mod_inverse', 'Pow', 'integer_nthroot', 'integer_log', 'Mul', 'prod',
    'Add', 'Mod', 'Rel', 'Eq', 'Ne', 'Lt', 'Le', 'Gt', 'Ge', 'Equality',
    'GreaterThan', 'LessThan', 'Unequality', 'StrictGreaterThan',
    'StrictLessThan', 'vectorize', 'Lambda', 'WildFunction', 'Derivative',
    'diff', 'FunctionClass', 'Function', 'Subs', 'expand', 'PoleError',
    'count_ops', 'expand_mul', 'expand_log', 'expand_func', 'expand_trig',
    'expand_complex', 'expand_multinomial', 'nfloat', 'expand_power_base',
    'expand_power_exp', 'arity', 'PrecisionExhausted', **'N'**, 'evalf', 'Tuple',
    'Dict', 'gcd_terms', 'factor_terms', 'factor_nc', 'evaluate', 'Catalan',
    'EulerGamma', 'GoldenRatio', 'TribonacciConstant',
```

I could figured out only 3 possible solutions:

1. rename function "N" (but I don't know from where it comes);
2. delete function "N" from lines 61 and 270 (but I don't know the real importance of it); e
3. not use "N" for expressions with newton unit. Instead use only use "newton" (in full form).

Despite the fact I consider the third one the worst option, since people working with physics and mathematicians expressions usually use newton force as "N", I'm adopting this option as a workaround because I hope the solution 1, 2, or other better comes fast.

**Comment by oscarbenjamin** [comment]
You can use `parse_expr` to control the globals. It would be nice if there was a better way.

**Comment by aquazod** [comment]
if the resulting expression is "10*newton", would this be good?

**Comment by memoriadecalculo** [comment]
> if the resulting expression is "10*newton", would this be good?

The point is: if you input "10*N" (short form) you'll get an error and not the resulting expression you wrote.

**Comment by aquazod** [comment]
Can you give me some test inputs and the expected output for them after passing to sympify()?
try to make them as compound as you can please

**Comment by memoriadecalculo** [comment]
> Can you give me some test inputs and the expected output for them after passing to sympify()? try to make them as compound as you can please

For sure.
**Considering:**
```
Python 3.11.6 (main, Oct  4 2023, 09:27:52) on linux
>>> from sympy.core.sympify import sympify
```

**Right answer using "newton" instead of "N":**
```
>>> sympify("10*newton")
10*newton
>>> type(sympify("10*newton"))
<class 'sympy.core.mul.Mul'>
```

**Right answer if the use of "N" was ok inside sympify:**
```
>>> sympify("10*N")
10*newton
>>> type(sympify("10*N"))
<class 'sympy.core.mul.Mul'>
```

**Error happening nowadays;**
```
>>> sympify("10*N")
ValueError: Error from parse_expr with transformed code: 'Integer (10 )*N '

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/user/0/org.qpython.qpy/files/lib/python3.11/site-packages/sympy/core/sympify.py", line 495, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/org.qpython.qpy/files/lib/python3.11/site-packages/sympy/parsing/sympy_parser.py", line 1087, in parse_expr
    raise e from ValueError(f"Error from parse_expr with transformed code: {code!r}")
  File "/data/user/0/org.qpython.qpy/files/lib/python3.11/site-packages/sympy/parsing/sympy_parser.py", line 1078, in parse_expr
    rv = eval_expr(code, local_dict, global_dict)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/org.qpython.qpy/files/lib/python3.11/site-packages/sympy/parsing/sympy_parser.py", line 906, in eval_expr
    expr = eval(
           ^^^^^
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'Integer' and 'function'
```

I hope this helps.

**Comment by UltraMej** [comment]
Bug still there... It is sad, as we often use the symbol N in physics and math (in sums for n from 0 to N, for instance)

$ sp.sympify('M*(M-1)/2')
works all right

$ sp.sympify('M*(M-1)/2')
leads to
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: Error from parse_expr with transformed code: 'N *(N -Integer (1 ))/Integer (2 )'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)

**Comment by rfordyce** [comment]
While I understand this feels a little like a regression, I don't believe SymPy is intended to have meaningful support for arbitrary units (though I would excitedly welcome a strong integration with the venerable [Pint](https://github.com/hgrecco/pint)!), outside of the somewhat-orthogonal physics units system https://docs.sympy.org/latest/modules/physics/units/index.html, which _does_ maintain these

Therefore you could do this instead with the more featureful `parse_expr()`
```python
>>> from sympy.physics.units import *
>>> srepr(parse_expr('10*N', locals()))  # lazy, consider {"N": N}
'Mul(Integer(10), newton)'
>>> convert_to(parse_expr('10*N', locals()), kilogram*meter/second**2)
10*kilogram*meter/second**2
```

Here and more generally, I think this actually brings up two considerations
* should bare names like `N` become a `Symbol` if they're unused in SymPy? personally I'm not convinced, leaning more towards the other extreme: reserving all uppercase, single-letter names and expecting them to have special meaning in future versions of SymPy
* should `sympify()` (or `parse_expr()`) actually allow `N()` at all? (ie. is attempting to use `N()` a code smell to actively reject?)

That said, because SymPy did accept bare `N` in a previous version and the case is both easy to identify and a straightforward error in the newer versions, I think this specific case should go ahead and parse bare N to a Symbol anyways and also deprecate the behavior, warning that it will go away in a future version https://docs.sympy.org/latest/contributing/deprecations.html

state under 3.13.1 - note that over 20% of the uppercase ASCII letters are already reserved!

```python
>>> from sympy import *
>>> from string import ascii_uppercase as AtoZ
>>> for a in AtoZ:
...     try:
...         srepr(sympify(f"10*{a}"))
...     except Exception as ex:
...         print(f"caught {repr(ex)}")
...         
"Mul(Integer(10), Symbol('A'))"
"Mul(Integer(10), Symbol('B'))"
"Mul(Integer(10), Symbol('C'))"
"Mul(Integer(10), Symbol('D'))"
'Mul(Integer(10), E)'
"Mul(Integer(10), Symbol('F'))"
"Mul(Integer(10), Symbol('G'))"
"Mul(Integer(10), Symbol('H'))"
'Mul(Integer(10), I)'
"Mul(Integer(10), Symbol('J'))"
"Mul(Integer(10), Symbol('K'))"
"Mul(Integer(10), Symbol('L'))"
"Mul(Integer(10), Symbol('M'))"
caught TypeError("unsupported operand type(s) for *: 'Integer' and 'function'")
caught TypeError("unsupported operand type(s) for *: 'Integer' and 'type'")
"Mul(Integer(10), Symbol('P'))"
caught TypeError("unsupported operand type(s) for *: 'Integer' and 'AssumptionKeys'")
"Mul(Integer(10), Symbol('R'))"
caught TypeError("unsupported operand type(s) for *: 'Integer' and 'SingletonRegistry'")
"Mul(Integer(10), Symbol('T'))"
"Mul(Integer(10), Symbol('U'))"
"Mul(Integer(10), Symbol('V'))"
"Mul(Integer(10), Symbol('W'))"
"Mul(Integer(10), Symbol('X'))"
"Mul(Integer(10), Symbol('Y'))"
"Mul(Integer(10), Symbol('Z'))"
```

Finally, a clear (though slightly more verbose) technique could be to use underscores to mark names as units and `.subs()` them out with the physics units

```python
>>> from sympy import *
>>> from sympy.physics.units import N
>>> sympify("10*N_").subs("N_", N)  # can be more verbose like _unit
10*newton
```

**Comment by oscarbenjamin** [comment]
The first thing that sympy needs is a forwards compatible version of parse_expr that promises never to introduce new names or break compatibility. After that a version of parse_expr that makes it easier to control what names should be included from sympy itself.
