### ISSUE TITLE
TypeError: Invalid NaN comparison calling integrate in sympy 1.12

### ISSUE THREAD

**Issue by nasser1** [sympy/sympy#26503]
I do not know if this is known or reported before. Feel free to close if so.

I see lots of exceptions TypeError: Invalid NaN comparison. Here is just one example out of many

```
from sympy import *
x,a,b=symbols('x a b')
integrand="(a**x)/(b**x)"
integrate( sympify(integrand), x)

```

gives

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/sympy/integrals/integrals.py", line 1567, in integrate
    return integral.doit(**doit_flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sympy/integrals/integrals.py", line 612, in doit
    antideriv = self._eval_integral(
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sympy/integrals/integrals.py", line 1084, in _eval_integral
    h = heurisch_wrapper(g, x, hints=[])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sympy/integrals/heurisch.py", line 158, in heurisch_wrapper
    slns += solve([d], dict=True, exclude=(x,))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sympy/solvers/solvers.py", line 1147, in solve
    linear, solution = _solve_system(f, symbols, **flags)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sympy/solvers/solvers.py", line 1934, in _solve_system
    soln = _vsolve(eq2, s, **flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sympy/solvers/solvers.py", line 2606, in _vsolve
    return [i[s] for i in _solve(e, s, **flags)]
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sympy/solvers/solvers.py", line 1714, in _solve
    result = [r for r in result if
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sympy/solvers/solvers.py", line 1715, in <listcomp>
    checksol(f_num, r, **flags) is not False]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sympy/solvers/solvers.py", line 360, in checksol
    return (abs(val.n(18).n(12, chop=True)) < 1e-9) is S.true
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sympy/core/decorators.py", line 236, in _func
    return func(self, other)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sympy/core/expr.py", line 376, in __lt__
    return StrictLessThan(self, other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sympy/core/relational.py", line 824, in __new__
    raise TypeError("Invalid NaN comparison")
TypeError: Invalid NaN comparison
>>> 


```

Version info

```
>>> import sympy
>>> sympy.__version__
'1.12'

>python --version
Python 3.11.8
>
```

For reference the anti derivative should be

```
Integrate[(a^x)/(b^x),x]

(a^x b^-x)/(Log[a]-Log[b])

```

**Comment by oscarbenjamin** [comment]
This is coming from integrate calling solve which in turn calls checksol. Then we have:
```
    362         if numerical and val.is_number:
--> 363             return (abs(val.n(18).n(12, chop=True)) < 1e-9) is S.true
    364
    365     if flags.get('warn', False):
    366         warnings.warn("\n\tWarning: could not verify solution %s." % sol)
    367     # returns None if it can't conclude
    368     # TODO: improve solution testing
    369

ipdb> p val
nan
ipdb> p val.is_number
True
```
I wonder if `nan.is_number` should actually be False. The internal call to solve is:
```
In [7]: solve([b**x*log(a) - b**x*log(b)], exclude=(x,))
---------------------------------------------------------------------------
TypeError
```
