### ISSUE TITLE
plot error after a "clean" simpify check up

### ISSUE THREAD

**Issue by Napain** [sympy/sympy#26673]
So I'm trying to do a simple plot functions for a project. I know the plot works with sanitize equations. However I run through a "cleaning" the input with a try. Here the code below : 

```
class check_methods:

    def __init__(self, the_string):
         self.number = input(the_string)

    def check_sympy_equation (self):
        print('-------------Checking the sympyfication ----------\n ')
                    
        try :
    
            fct = sympify(self.number)
            print('----You hace successefully convert your str into a sympy function ----')

        except :
            print('You enter an invalid syntax. : type -help for list of function')

            return False
        
        return fct
```
and then I run through a plot class 

```
class Plot(check_methods):

    def __init__(self):
        pass
   def any_plot(self):
        checking = check_methods('Input your equation : ')
        equation = checking.check_sympy_equation()
        function = str(equation)
        print( ":---------------------",equation, ":---------------------")
        x_min, x_max = self.linspace()
        x = symbols('x') 
        plot(equation,(x,x_min,x_max), line_color = 'red')
```

I run the code and Input a wrong equation like "5x" instead of "5*x".
Finally the 5x pass the try check but the plot class trying to plot the wrong form throw this error : 
```
Input your equation : x5
-------------Checking the sympyfication ----------
 
----You hace successefully convert your str into a sympy function ----
:--------------------- x5 :---------------------
Please choose the min value of x: -5
Please choose the max value of x: 5

And this is the error : 
/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/experimental_lambdify.py:188: UserWarning: The evaluation of the expression is problematic. We are trying a failback method that may still work. Please report this as a bug.
  return self.__call__(args)
Traceback (most recent call last):
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/experimental_lambdify.py", line 176, in __call__
    result = complex(self.lambda_func(args))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/core/expr.py", line 356, in __complex__
    return complex(float(re), float(im))
                   ^^^^^^^^^
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/core/expr.py", line 351, in __float__
    raise TypeError("Cannot convert expression to float")
TypeError: Cannot convert expression to float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/experimental_lambdify.py", line 176, in __call__
    result = complex(self.lambda_func(args))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/core/expr.py", line 356, in __complex__
    return complex(float(re), float(im))
                   ^^^^^^^^^
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/core/expr.py", line 351, in __float__
    raise TypeError("Cannot convert expression to float")
TypeError: Cannot convert expression to float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simon/Desktop/advance_coding/calculator.py", line 70, in <module>
    console(my_calculator)
  File "/home/simon/Desktop/advance_coding/calculator.py", line 60, in console
    my_calculator.pick_plot()
  File "/home/simon/Desktop/advance_coding/calculators/Calculators_Type.py", line 71, in pick_plot
    self.any_plot()
  File "/home/simon/Desktop/advance_coding/calculators/check_methods.py", line 253, in any_plot
    plot(equation,(x,x_min,x_max), line_color = 'red')
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/plot.py", line 1873, in plot
    plots.show()
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/plot.py", line 251, in show
    self._backend.show()
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/plot.py", line 1549, in show
    self.process_series()
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/plot.py", line 1546, in process_series
    self._process_series(series, ax, parent)
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/plot.py", line 1367, in _process_series
    x, y = s.get_data()
           ^^^^^^^^^^^^
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/plot.py", line 605, in get_data
    points = self.get_points()
             ^^^^^^^^^^^^^^^^^
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/plot.py", line 779, in get_points
    f_start = f(self.start)
              ^^^^^^^^^^^^^
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/experimental_lambdify.py", line 188, in __call__
    return self.__call__(args)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/experimental_lambdify.py", line 196, in __call__
    return self.__call__(args)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/experimental_lambdify.py", line 184, in __call__
    raise e
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/plotting/experimental_lambdify.py", line 176, in __call__
    result = complex(self.lambda_func(args))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/core/expr.py", line 356, in __complex__
    return complex(float(re), float(im))
                   ^^^^^^^^^
  File "/home/simon/anaconda3/envs/advance_coding/lib/python3.12/site-packages/sympy/core/expr.py", line 351, in __float__
    raise TypeError("Cannot convert expression to float")
TypeError: Cannot convert expression to float
```
I know it has to do with the input being "Wrong" but should the "try" do the cleaning? Because with very wrong inputs the try does return the false and hence the code doesn't plot anything

**Comment by bjodah** [comment]
It's a bit hard to give advice here. If there is an underlying issue with sympy at play here, this is the right place to ask, but I don't think you've given us all the relevant code? (from the traceback I see lambdify being used, but I see no call to lambdify in your provided code).

If your question is about how to structure your code (what to put in try/except blocks, in your case perhaps both the parsing of the string, as well as the call doing the numerical evaluation is what you want), then the "Discussions" tab or one of stackexchange's sites is a better place to discuss design of 3rd party libraries/applications?

**Comment by Napain** [comment]
> It's a bit hard to give advice here. If there is an underlying issue with sympy at play here, this is the right place to ask, but I don't think you've given us all the relevant code? (from the traceback I see lambdify being used, but I see no call to lambdify in your provided code).
> 
Here are my import. I don't use the lambdify function in any of my code. 

```
from sympy.plotting import plot 
from sympy import * 
```
I y try with a condition like this one (Code below for the method "plot_any") It is also import to note that I name my class "check_methods" This is a rookie mistake by me, it should be name "CheckMethods" so we undertand is a class.

```
class Plot(check_methods):

    def __init__(self):
        pass

    def plot_any (self):
        checking = CheckMethods('Input your equation : ')
        equation = checking.check_sympy_equation()
        function = str(equation)
        if equation != False:
             print( ":---------------------",equation, ":---------------------")
             x_min, x_max = self.linspace()
             x = symbols('x') 
             plot(equation,(x,x_min,x_max), line_color = 'red')
```
Anyway, this condition allow me to check if the input is passing the Check on the try/except blocks. Again If a pass an input like "2?0~" The try/except block actually return the False and the code works as I intended.  

I figured this transformation comes from a "valid" input in the *try* block like "sinus(x)" (instead of sin(x)).
the input "sinus(x)" is a valid input, but the plot method doesn't recognize the "sinus(x)" and throws an error.

I was thinking of doing another method that checks if the plot is possible. I just want to know what simpify allows input that are not "plotable"

**Comment by sylee957** [comment]
What is the code for `self.linspace`?
I think that you are hiding some details about the class, however, the error is likely from giving wrong type for `x_min, x_max`
`x_min, x_max` should always be Python numbers, or SymPy numbers, and you may likely have some symbolic expressions that has variables like `x`, which does not have concrete numeric values, and which is invalid for plotting.

**Comment by Napain** [comment]
> What is the code for `self.linspace`? I think that you are hiding some details about the class, however, please show the details about the class because we cannot investigate the problem further.
> 
> however, the error is likely from giving wrong type for `x_min, x_max` `x_min, x_max` should always be Python numbers, or SymPy numbers, and you may likely have some symbolic expressions that has variables like `x`, which does not have concrete numeric values, and which is invalid for plotting.

 **self.linspace** is a method from the class Plot. 
 and here is the code for the method.

```
class Plot(CheckMethods): #Need to check the plot any with plot errors

    def __init__(self):
        pass

    def linspace(self):
        first_x = CheckMethods("Please choose the min value of x: ")
        x_min = first_x.check_float()
        second_x = CheckMethods("Please choose the max value of x: ")
        x_max = second_x.check_float()
        return x_min, x_max
```
Of course, since there also the usage of checking if the inputs are numbers. I also added a method for the **CheckMethods class** here below


```
class CheckMethods:

    def __init__(self, the_string):

        self.number = input(the_string)

    def check_float(self):

        while True:
            try:
                self.number = float(self.number)
                return(self.number)
            except ValueError:
                self.number = input('Please input a number')
```
I don't share the full project because, first is a project for Uni and I want it to keep it private until I summit it. Second It's long and I thought the necessary code was provide. I apologize  for taking so long to answer and not providing enough code. 

Don't hesitate to ask for more code. Once I finish it I will gladly share the integrity of my project!
