### ISSUE TITLE
Conversion of an expression to rust does not promote integers to float, yielding invalid rust code

### ISSUE THREAD

**Issue by IceTDrinker** [sympy/sympy#26967]
Hello,

tried the following sympy/python snippet :

```python
import sympy
from sympy.printing.rust import rust_code

a = sympy.Symbol('a')
expr  = 2.0 + 16 / a**2
print(rust_code(expr))
```

output:

```console
2.0 + 16/a.powi(2)
```

we can see sympy assumes a is a float (which is fine) as it calls the powi method (https://doc.rust-lang.org/std/index.html?search=powi) on it

however 16 is left as an integer, the 16 / a.powi(2) will not compile as a.powi(2) will be an f64 in my case and the division between an integer and an f64 is not defined in rust (no implicit conversion in that case)

```console
   Compiling playground v0.0.1 (/playground)
error[E0277]: cannot divide `{integer}` by `f64`
 --> src/main.rs:3:22
  |
3 |     let c = 2.0 + 16 / a.powi(2);
  |                      ^ no implementation for `{integer} / f64`
  |
  = help: the trait `Div<f64>` is not implemented for `{integer}`
...
```

I understand this is a case that probably did not arise too much with other languages like C where some automatic conversions can happen.

Not sure what the best approach here is for sympy, I'm not familiar enough with the package.

Cheers

**Comment by oscarbenjamin** [comment]
There was a recent PR that improved this sort of thing gh-26882. If you try latest master then you can see if it helps.

I think maybe you have to use an explicit cast or something.

**Comment by IceTDrinker** [comment]
Thanks for the pointers, I used a replace with a cast and it seems to be mostly ok, but as my solution is a bit manual I thought it would be good to share here

**Comment by gfrlv** [comment]
just checked, this example does not work correctly in the current master.
The Pow operator needs to be wrapped into a suitable type cast, the same way as it's done for the floor and ceil functions.

Another bad example: 
```python
from sympy.printing import rust_code
x = sympy.Symbol('x', integer=True, positive=True)
rust_code(x**2)
```
it prints the float method `x.powi(2)`,  instead of the integer method `x.pow(2)`
I'll see what can be done about it, @IceTDrinker thanks for pointing out.

**Comment by IceTDrinker** [comment]
hello hit another corner case of the conversion it seems but this time it crashes the export

```rust
import sympy
from sympy.printing.rust import rust_code

modulus = sympy.symbols("modulus", integer=True)

expr = modulus ** -2.0

print(rust_code(expr))
```

```console
Traceback (most recent call last):
  File "/home/redacted/code/redacted/bug.py", line 8, in <module>
    print(rust_code(expr))
          ^^^^^^^^^^^^^^^
  File "/home/redacted/code/redacted/envs/redacted/lib/python3.11/site-packages/sympy/printing/rust.py", line 614, in rust_code
    return RustCodePrinter(settings).doprint(expr, assign_to)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/code/redacted/envs/redacted/lib/python3.11/site-packages/sympy/printing/codeprinter.py", line 172, in doprint
    lines = self._print(expr).splitlines()
            ^^^^^^^^^^^^^^^^^
  File "/home/redacted/code/redacted/envs/redacted/lib/python3.11/site-packages/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/code/redacted/envs/redacted/lib/python3.11/site-packages/sympy/printing/rust.py", line 340, in _print_Pow
    expr = type(expr)(Float(expr.base), expr.exp)
                      ^^^^^^^^^^^^^^^^
  File "/home/redacted/code/redacted/envs/redacted/lib/python3.11/site-packages/sympy/core/numbers.py", line 909, in __new__
    _mpf_ = mpmath.mpf(num, prec=precision)._mpf_
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/code/redacted/envs/redacted/lib/python3.11/site-packages/mpmath/ctx_mp_python.py", line 79, in __new__
    v._mpf_ = mpf_pos(cls.mpf_convert_arg(val, prec, rounding), prec, rounding)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/code/redacted/envs/redacted/lib/python3.11/site-packages/mpmath/ctx_mp_python.py", line 98, in mpf_convert_arg
    raise TypeError("cannot create mpf from " + repr(x))
TypeError: cannot create mpf from modulus
```

problem seems to be that the symbol assumes it's an integer and the rust printing code tries to convert it using sympy.Float but as far as I understand that does not work on a symbol
