### ISSUE TITLE
NotImplementedError: limit of derivative of undefined function to a symbol

### ISSUE THREAD

**Issue by vvavrychuk** [sympy/sympy#27143]
```
x = Symbol('x')
a = Symbol('a')
f = Function('f')
limit(f(x).diff(x), x, a)
```
crashes with
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../sympy/series/limits.py", line 64, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
  File ".../sympy/series/limits.py", line 375, in doit
    r = gruntz(e, z, z0, dir)
  File ".../sympy/series/gruntz.py", line 732, in gruntz
    r = limitinf(e0, z)
  File ".../sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File ".../sympy/series/gruntz.py", line 452, in limitinf
    c0, e0 = mrv_leadterm(e, x)
  File ".../sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File ".../sympy/series/gruntz.py", line 535, in mrv_leadterm
    Omega, exps = mrv(e, x)
  File ".../sympy/series/gruntz.py", line 319, in mrv
    raise NotImplementedError(
NotImplementedError: Don't know how to calculate the mrv of 'Subs(Derivative(f(_p), _p), _p, a + 1/_p)'
```

Note, limit to a constant works fine
```
>>> limit(f(x).diff(x), x, 0)
Subs(Derivative(f(xi), xi), xi, 0)
```

**Comment by karthiksmanian** [comment]
So if you substitute a on the limit, should it be converted to say a0 like x does for xi?

**Comment by vvavrychuk** [comment]
@karthiksmanian sorry, I am not sure why substitute a on the limit?

**Comment by sylee957** [comment]
I don't think that there is definite limit for the function. But it could be indefinite limit

`Limit(f(x).diff(x), x, a)`

**Comment by vvavrychuk** [comment]
Actually, for the NotImplementedError to reproduce limit point does not have to be a symbol. It can also be a number distinct from zero.
