### ISSUE TITLE
Integral of `Abs(cos(x + y))` typeerror

### ISSUE THREAD

**Issue by satels** [sympy/sympy#27234]
```python
>>> from sympy import symbols, Integral, Abs, cos
>>> x, y = symbols('x y', real=True)
>>> integral = Integral(Abs(cos(x + y)), y)
>>> integral.doit()
```

The error:

```python
Traceback (most recent call last):
  File "sympy/polys/polyutils.py", line 229, in _parallel_dict_from_expr_if_gens
    monom[indices[base]] = exp
          ~~~~~~~^^^^^^
KeyError: cos(x + y)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sympy/solvers/inequalities.py", line 811, in _solve_inequality
    p = Poly(expr, s)
        ^^^^^^^^^^^^^
  File "sympy/polys/polytools.py", line 186, in __new__
    return cls._from_expr(rep, opt)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/polys/polytools.py", line 315, in _from_expr
    rep, opt = _dict_from_expr(rep, opt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/polys/polyutils.py", line 386, in _dict_from_expr
    rep, gens = _dict_from_expr_if_gens(expr, opt)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/polys/polyutils.py", line 325, in _dict_from_expr_if_gens
    (poly,), gens = _parallel_dict_from_expr_if_gens((expr,), opt)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/polys/polyutils.py", line 234, in _parallel_dict_from_expr_if_gens
    raise PolynomialError("%s contains an element of "
sympy.polys.polyerrors.PolynomialError: cos(x + y) contains an element of the set of generators.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sympy/polys/polyutils.py", line 229, in _parallel_dict_from_expr_if_gens
    monom[indices[base]] = exp
          ~~~~~~~^^^^^^
KeyError: cos(x + y)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sympy/solvers/inequalities.py", line 250, in reduce_rational_inequalities
    (numer, denom), opt = parallel_poly_from_expr(
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/polys/polytools.py", line 4538, in parallel_poly_from_expr
    return _parallel_poly_from_expr(exprs, opt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/polys/polytools.py", line 4589, in _parallel_poly_from_expr
    reps, opt = _parallel_dict_from_expr(exprs, opt)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/polys/polyutils.py", line 350, in _parallel_dict_from_expr
    reps, gens = _parallel_dict_from_expr_if_gens(exprs, opt)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/polys/polyutils.py", line 234, in _parallel_dict_from_expr_if_gens
    raise PolynomialError("%s contains an element of "
sympy.polys.polyerrors.PolynomialError: cos(x + y) contains an element of the set of generators.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sympy/solvers/inequalities.py", line 820, in _solve_inequality
    rv = reduce_rational_inequalities([[ie]], s)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/solvers/inequalities.py", line 253, in reduce_rational_inequalities
    raise PolynomialError(filldedent('''
sympy.polys.polyerrors.PolynomialError: 
only polynomials and rational functions are supported in this context.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/integrals/integrals.py", line 554, in doit
    antideriv = function._eval_integral(xab[0],
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/functions/elementary/piecewise.py", line 401, in _eval_integral
    ok, abei = self._intervals(x)
               ^^^^^^^^^^^^^^^^^^
  File "sympy/functions/elementary/piecewise.py", line 643, in _intervals
    ok, s = _solve_relational(r)
            ^^^^^^^^^^^^^^^^^^^^
  File "sympy/functions/elementary/piecewise.py", line 614, in _solve_relational
    rv = _solve_inequality(r, sym)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/solvers/inequalities.py", line 822, in _solve_inequality
    rv = solve_univariate_inequality(ie, s)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/solvers/inequalities.py", line 493, in solve_univariate_inequality
    frange = function_range(e, gen, domain)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/calculus/util.py", line 266, in function_range
    solution = solveset(f.diff(symbol), symbol, interval)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/solvers/solveset.py", line 2517, in solveset
    return _solveset(f, symbol, domain, _check=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/solvers/solveset.py", line 1287, in _solveset
    result = _solve_trig(f, symbol, domain)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/solvers/solveset.py", line 821, in _solve_trig
    x, sol = _invert(f, 0, symbol, domain)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/solvers/solveset.py", line 203, in _invert
    return x1, s.intersect(domain)
               ^^^^^^^^^^^^^^^^^^^
  File "sympy/sets/sets.py", line 150, in intersect
    return Intersection(self, other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/sets/sets.py", line 1507, in __new__
    return simplify_intersection(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/sets/sets.py", line 2621, in simplify_intersection
    return Union(*(Intersection(arg, other) for arg in s.args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/sets/sets.py", line 2621, in <genexpr>
    return Union(*(Intersection(arg, other) for arg in s.args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/sets/sets.py", line 1507, in __new__
    return simplify_intersection(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/sets/sets.py", line 2644, in simplify_intersection
    new_set = intersection_sets(s, t)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "sympy/multipledispatch/dispatcher.py", line 243, in __call__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "sympy/sets/handlers/intersection.py", line 384, in _
    if new_inf > new_sup:
       ^^^^^^^^^^^^^^^^^
  File "sympy/core/relational.py", line 516, in __bool__
    raise TypeError("cannot determine truth value of Relational")
TypeError: cannot determine truth value of Relational

```

**Comment by satels** [comment]
Easy to fix ?

```
sympy/sets/handlers/intersection.py:384: in _
    if new_inf > new_sup:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = x/(2*pi) > (x + 2*pi)/(2*pi)

    def __bool__(self):
>       raise TypeError("cannot determine truth value of Relational")
E       TypeError: cannot determine truth value of Relational
```

**Comment by oscarbenjamin** [comment]
The basic bug is:
```python
In [4]: Intersection(Interval(0, 2*pi), ImageSet(Lambda(n, 2*n*pi - x), Integers))
...
TypeError: cannot determine truth value of Relational: x/(2*pi) > (x + 2*pi)/(2*pi)
```
I have a fix for that in gh-26872:
```python
In [1]: Intersection(Interval(0, 2*pi), ImageSet(Lambda(n, 2*n*pi - x), Integers))
Out[1]: [0, 2⋅π] ∩ {2⋅π⋅n - x │ n ∊ ℤ}
```
The fix is that I have deleted all of the code for computing interval between imageset and interval and replaced it with something much simpler than only handles linear imagesets with all numeric coefficients but does so robustly.

Unfortunately that does not fix the integral which than hangs because of another set-related problem. It goes into an infinite loop here:
https://github.com/sympy/sympy/blob/91ab0d56601537db30574666941424d4c24f3083/sympy/calculus/util.py#L277-L278
The loop is trying to find an element of this set:
```
In [6]: critical_points
Out[6]: ([0, 2⋅π] ∩ {2⋅π⋅n - x │ n ∊ ℤ}) ∪ ([0, 2⋅π] ∩ {2⋅π⋅n - x + π │ n ∊ ℤ})
```
It is looping over Z checking to see if any expression is an element. It should check to see that it has a finite set before trying to loop over it.

**Comment by pratykshg9999** [comment]
i want to work on this issue
