### ISSUE TITLE
Fix deprecation warning for compute_leading_term

### ISSUE THREAD

**Issue by anutosh491** [sympy/sympy#27281]
This deprecation warning doesn't work:
```python
In [1]: x.compute_leading_term(x)
...
TypeError: SymPyDeprecationWarning.__init__() got an unexpected keyword argument 'feature'
```
This is why we need tests for things that are deprecated. This has already been released in SymPy 1.12 and 1.13 now and is broken so at this stage it would be best just to delete this method rather than fixing the deprecation warning.

_Originally posted by @oscarbenjamin in https://github.com/sympy/sympy/pull/23844#discussion_r1832410815_

**Comment by Ytemiloluwa** [comment]
Hello @anutosh491 , I will like to work on this issue.

**Comment by anutosh491** [comment]
Go ahead and test the above properly.

**Comment by Jatinbhardwaj-093** [comment]
As per my findings `SymPyDeprecationWarning` class doesn’t take the parameters `feature`, `useinstead`, and `issue` as positional arguments. Instead, it expects the `message` to be passed as a regular argument, and `deprecated_since_version ` and `active_deprecations_target` must be passed as keyword arguments.
https://github.com/sympy/sympy/blob/7f0b42c29807be66eb3bc181c818a431f211ffd4/sympy/utilities/exceptions.py#L99-L100

Proposed fix can be 
```python
SymPyDeprecationWarning(
    "compute_leading_term() is deprecated. Use as_leading_term() instead.",
    deprecated_since_version="1.12",
    active_deprecations_target=21843
).warn()
```

@anutosh491 if this looks good I like to create a PR.

**Comment by oscarbenjamin** [comment]
I think we can just delete the method now. It was already broken in SymPy 1.12 and 1.13 so it has been broken for a long time in released SymPy versions. There is no need to deprecate if it is already broken.

**Comment by Jatinbhardwaj-093** [comment]
ok, does the removing of the method also apply to `calculate_series` in `gruntz.py` as this warning also raises TypeError.
```python
>>> calculate_series(eq,x)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/jatinbhardwaj/Documents/Github/sympy/sympy/series/gruntz.py", line 494, in calculate_series
    SymPyDeprecationWarning(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        feature="calculate_series",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        deprecated_since_version="1.12"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).warn()
    ^
TypeError: SymPyDeprecationWarning.__init__() got an unexpected keyword argument 'feature'
```

or [this](https://github.com/sympy/sympy/issues/27281#issuecomment-2486485311) piece of code replaced by structure like suggested above.

**Comment by oscarbenjamin** [comment]
Yes, just remove both functions.

**Comment by anutosh491** [comment]
Closing issue as completed through #27567
