### ISSUE TITLE
Converting from `numpy.float32(float('inf'))` throws

### ISSUE THREAD

**Issue by fefe982** [sympy/sympy#27284]
sympy==1.13.3
numpy==2.1.3
python 3.10.15

```python
import numpy
import sympy
sympy.Float(np.float32(float('inf')))
```
thows with:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.10/site-packages/sympy/core/numbers.py", line 805, in __new__
    num = _convert_numpy_types(num)
  File ".../lib/python3.10/site-packages/sympy/core/sympify.py", line 93, in _convert_numpy_types
    p, q = a.as_integer_ratio()
OverflowError: cannot convert Infinity to integer ratio
```

**Comment by oscarbenjamin** [comment]
The code here should be improved:
https://github.com/sympy/sympy/blob/efa1521b638e4f7f2b9a18e0280a0667a4bb16c8/sympy/core/sympify.py#L88-L105

**Comment by solvedbiscuit71** [comment]
I like to work on this issue.
