### ISSUE TITLE
simplify infinite loop

### ISSUE THREAD

**Issue by SamSamFR** [sympy/sympy#27320]
Simplifying the following expression **always** leads to an infinite loop : 

``` python
from sympy import *
x = Symbol('x', real=True)
expr = sin(tan(-4*x**2-3)**3)
print(expr)
expr2 = expr.simplify()
print("done.")
```

I got the same behavior using : 
- sympy 1.12    and Python 3.10.12 on linux
- sympy 1.11.1  and Python 3.10.5 on windows (Anaconda)
- https://live.sympy.org/

The infinite loop is not triggered if the minus sign is factored outside of tan and sin...

I found other reports about simplify hanging, but those were seemingly related to a function named zz_wang, which does not appear in this case : 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "SOMEDIR/sympy/core/basic.py", line 1853, in simplify
    return simplify(self, **kwargs)
  File "SOMEDIR/sympy/simplify/simplify.py", line 699, in simplify
    expr = trigsimp(expr, deep=True)
  File "SOMEDIR/sympy/simplify/trigsimp.py", line 564, in trigsimp
    expr_simplified = trigsimpfunc(expr)
  File "SOMEDIR/sympy/simplify/trigsimp.py", line 557, in <lambda>
    'matching': (lambda x: futrig(x)),
  File "SOMEDIR/sympy/simplify/trigsimp.py", line 1158, in futrig
    e = bottom_up(e, _futrig)
  File "SOMEDIR/sympy/core/traversal.py", line 236, in bottom_up
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in <listcomp>
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 239, in bottom_up
    rv = F(rv)
  File "SOMEDIR/sympy/simplify/trigsimp.py", line 1225, in _futrig
    e = greedy(tree, objective=Lops)(e)
  File "SOMEDIR/sympy/strategies/core.py", line 150, in minrule
    return min([rule(expr) for rule in rules], key=objective)
  File "SOMEDIR/sympy/strategies/core.py", line 150, in <listcomp>
    return min([rule(expr) for rule in rules], key=objective)
  File "SOMEDIR/sympy/strategies/core.py", line 64, in chain_rl
    expr = rule(expr)
  File "SOMEDIR/sympy/simplify/fu.py", line 755, in TR10i
    return bottom_up(rv, f)
  File "SOMEDIR/sympy/core/traversal.py", line 236, in bottom_up
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in <listcomp>
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in bottom_up
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in <listcomp>
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in bottom_up
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in <listcomp>
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in bottom_up
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in <listcomp>
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in bottom_up
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in <listcomp>
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in bottom_up
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in <listcomp>
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in bottom_up
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 236, in <listcomp>
    args = tuple([bottom_up(a, F, atoms, nonbasic) for a in args])
  File "SOMEDIR/sympy/core/traversal.py", line 239, in bottom_up
    rv = F(rv)
  File "SOMEDIR/sympy/simplify/fu.py", line 750, in f
    rv = do(rv)  # final pass to resolve any new inducible pairs
  File "SOMEDIR/sympy/simplify/fu.py", line 677, in do
    new = do(was)
  File "SOMEDIR/sympy/simplify/fu.py", line 691, in do
    split = trig_split(*args, two=True)
  File "SOMEDIR/sympy/simplify/fu.py", line 1770, in trig_split
    a, b = [Factors(i) for i in (a, b)]
  File "SOMEDIR/sympy/simplify/fu.py", line 1770, in <listcomp>
    a, b = [Factors(i) for i in (a, b)]
  File "SOMEDIR/sympy/core/exprtools.py", line 353, in __init__
    factors = dict(Mul._from_args(c).as_powers_dict())
  File "SOMEDIR/sympy/core/mul.py", line 1226, in as_powers_dict
    for b, e in term.as_powers_dict().items():
  File "SOMEDIR/sympy/core/expr.py", line 1952, in as_powers_dict
    d.update([self.as_base_exp()])
  File "SOMEDIR/sympy/core/basic.py", line 189, in __hash__
    def __hash__(self) -> int:
KeyboardInterrupt
```

**Comment by oscarbenjamin** [comment]
I think it might be doing something `expand(trig=True)` which generates an enormous expression.

**Comment by boopalan-s** [comment]
not only this case, there are several cases like this one how they are handled.
