### ISSUE TITLE
detect impossible solution request

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#2903]
The following could return "no solution" (as appropriate) rather than raising an error:

```
>>> b=var('b'); solve(b+sqrt(b**2)-I)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solvers.py", line 901, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "sympy\solvers\solvers.py", line 1209, in _solve
    u = unrad(f_num)
  File "sympy\solvers\solvers.py", line 2867, in unrad
    return (_canonical(eq), cov, list(dens))
  File "sympy\solvers\solvers.py", line 2713, in _canonical
    if (eq.coeff(free.pop()**degree(eq)) < 0) is True:
  File "sympy\core\decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "sympy\core\expr.py", line 248, in __lt__
    raise TypeError("Invalid comparison of complex %s" % dif)
TypeError: Invalid comparison of complex 2*I
```

**Comment by jcrist** [comment]
Currently fixed in master. Closing.
