### ISSUE TITLE
fix upgrading via setup.py or add a big fat warning

### ISSUE THREAD

**Issue by vks** [sympy/sympy#3963]
bc.. >>> from sympy import *
 Traceback (most recent call last):
  File "C:\Dokumente und Einstellungen\Vinzent\Desktop\newmax.py", line 1,
in <module>
    from sympy import *
  File "C:\Python25\Lib\site-packages\sympy__init__.py", line 22, in <module>
    from sympy.core import *
  File "C:\Python25\Lib\site-packages\sympy\core__init__.py", line 4, in
<module>
    from basic import Basic, S, C, sympify
  File "C:\Python25\Lib\site-packages\sympy\core\basic.py", line 5, in <module>
    import sympy.thirdparty.mpmath as mpmath
  File "C:\Python25\Lib\site-packages\sympy\thirdparty\mpmath__init__.py",
line 5, in <module>
    from mptypes import *
  File "C:\Python25\Lib\site-packages\sympy\thirdparty\mpmath\mptypes.py",
line 17, in <module>
    from libmpc import *
  File "C:\Python25\Lib\site-packages\sympy\thirdparty\mpmath\libmpc.py",
line 19, in <module>
    def mpc_add((a, b), (c, d), prec, rnd=round_fast):
NameError: name 'round_fast' is not defined

I installed latest revision via setup.py install on Windows. If this is due
to not removing sympy before, setup.py has to be fixed.

p. Original issue for "#3963":https://github.com/sympy/sympy/issues/3963: "http://code.google.com/p/sympy/issues/detail?id=864":http://code.google.com/p/sympy/issues/detail?id=864

p. Original author: "https://code.google.com/u/Vinzent.Steinberg@gmail.com/":https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by oscarbenjamin** [comment]
Installing/upgrading is generally done with pip these days. I'm not sure that upgrading from setup.py was ever really supported.

I think this can be closed.
