### ISSUE TITLE
dsolve() problem

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#5154]
```
Hello,

>>> from sympy import*
>>> x=Symbol('x')
>>> f=Function('f')
>>> dsolve(Eq(Derivative(f(x),x,x),1),f(x))
f(x) == C1 + C2*x + x**2/2

This example works correctly, but when I put String in dsolve, then the problem comes:

>>> a="Derivative(f(x),x,x)"
>>> dsolve(Eq(a,1),f(x))

Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    dsolve(Eq(a,1),f(x))
  File "C:\Python27\lib\site-packages\sympy\core\relational.py", line 30, in Eq
    return Relational(a,b,'==')
  File "C:\Python27\lib\site-packages\sympy\core\relational.py", line 117, in __new__
    lhs = _sympify(lhs)
  File "C:\Python27\lib\site-packages\sympy\core\sympify.py", line 185, in _sympify
    raise SympifyError("%r is NOT a valid SymPy expression" % (a,))
SympifyError: SympifyError: 'Derivative(f(x),x,x)' is NOT a valid SymPy expression

And after sympify this String, another error is coming out:

>>> a=sympify(a,locals=None,convert_xor=False)
>>> a
D(f(x), x, x)
>>> dsolve(Eq(a,1),f(x))

Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    dsolve(Eq(a,1),f(x))
  File "C:\Python27\lib\site-packages\sympy\solvers\ode.py", line 367, in dsolve
    return dsolve(eq.lhs-eq.rhs, func, hint=hint, simplify=simplify, **kwargs)
  File "C:\Python27\lib\site-packages\sympy\solvers\ode.py", line 383, in dsolve
    raise ValueError(str(eq) + " is not a differential equation in " + str(func))
ValueError: -1 + D(f(x), x, x) is not a differential equation in f(x)

I need to put String because I'm doing something from Java.
Thank's a lot!

Nikola Vidosavljevic
```

Original issue for #5154: http://code.google.com/p/sympy/issues/detail?id=2055
Original author: https://code.google.com/u/114598541356198505756/

**Comment by oscarbenjamin** [comment]
You can use `parse_expr` to convert a string to a sympy expression:
```
In [43]: a = parse_expr("Derivative(f(x),x,x)")                                                                                                               

In [44]: dsolve(Eq(a,1),f(x))                                                                                                                                 
Out[44]: 
                    2
                   x 
f(x) = C₁ + C₂⋅x + ──
                   2 
```
Passing strings to arbitrary sympy APIs is deprecated.
