### ISSUE TITLE
Logical operators should reject non-boolean arguments

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#5355]
```
Or(3, 11) is happily accepted by sympy, and Or(1, 15) even evaluates to True. The and/or/not operators should reject non-boolean arguments to avoid people mistaking them for bitwise operators.

(Distantly related to issue #2254 )
```

Original issue for #5355: http://code.google.com/p/sympy/issues/detail?id=2256
Original author: https://code.google.com/u/116979935720370605382/

**Comment by oscargus** [comment]
Seems to be fixed:

```
In [10]: Or(3, 11)
Traceback (most recent call last):

  File "<ipython-input-10-b7d486052b17>", line 1, in <module>
    Or(3, 11)

  File "C:\Users\Oscar\sympy\sympy\core\operations.py", line 418, in __new__
    _args = frozenset(cls._new_args_filter(args))

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 913, in _new_args_filter
    args = BooleanFunction.binary_check_and_simplify(*args)

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 460, in binary_check_and_simplify
    args = [as_Boolean(i) for i in args]

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 460, in <listcomp>
    args = [as_Boolean(i) for i in args]

  File "C:\Users\Oscar\sympy\sympy\logic\boolalg.py", line 55, in as_Boolean
    raise TypeError('expecting bool or Boolean, not `%s`.' % e)

TypeError: expecting bool or Boolean, not `3`.


In [11]: 

In [11]: 3|11
Out[11]: 11

In [12]: S(3) | S(11)
Traceback (most recent call last):

  File "<ipython-input-12-fc52ffa64499>", line 1, in <module>
    S(3) | S(11)

TypeError: unsupported operand type(s) for |: 'Integer' and 'Integer'
```

(That `3 | 11` works is expected.)
