### ISSUE TITLE
pyglet plotting fails - possibly a problem in the way in which it is installed

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#6240]
```
I use python 2.7.2 ans sympy 0.7.1.
I have tryed to use the plotting capabilities of sympy and I always ends up in getting the same error:

Traceback (most recent call last):
  File "C:\Projects\Wind\Engineering\PythonTools\Materials_PreProcessing\testgraph.py", line 12, in <module>
    figa.Plot()
  File "C:\Program Files\Python27\lib\site-packages\sympy\plotting\__init__.py", line 130, in Plot
    import plot
  File "C:\Program Files\Python27\lib\site-packages\sympy\plotting\plot.py", line 13, in <module>
    from plot_axes import PlotAxes
  File "C:\Program Files\Python27\lib\site-packages\sympy\plotting\plot_axes.py", line 5, in <module>
    from util import strided_range, billboard_matrix
  File "C:\Program Files\Python27\lib\site-packages\sympy\plotting\util.py", line 4, in <module>
    def get_model_matrix(array_type=c_float, glGetMethod=glGetFloatv):
NameError: name 'c_float' is not defined

I get this error with every example and even with the code:

import sympy as sym
sym.Plot()

I have tryed to use the solution proposed here: https://github.com/smichr/sympy/commit/768cc0f367614df7c48759ad96d2866b9fc1fe53 but it didn't work out...and more in  detail I think I do have a different folder path.
Can someone help me?

Bye 
Luca
```

Original issue for #6240: http://code.google.com/p/sympy/issues/detail?id=3141
Original author: https://code.google.com/u/117118583372889683404/

**Comment by oscargus** [comment]
This problem should have been solved in #16513
