### ISSUE TITLE
make doesn't work with the latest Cython

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#6729]
```
$make
python build.py build_ext --inplace
Compiling module sympy.polys.densearith ...
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    result = compile(source_file)
  File "/Users/aaronmeurer/Documents/cython/Cython/Compiler/Main.py", line 608, in compile
    return compile_single(source, options, full_module_name)
  File "/Users/aaronmeurer/Documents/cython/Cython/Compiler/Main.py", line 549, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/Users/aaronmeurer/Documents/cython/Cython/Compiler/Main.py", line 420, in run_pipeline
    pipeline = Pipeline.create_py_pipeline(context, options, result)
  File "/Users/aaronmeurer/Documents/cython/Cython/Compiler/Pipeline.py", line 255, in create_py_pipeline
    return create_pyx_pipeline(context, options, result, py=True)
  File "/Users/aaronmeurer/Documents/cython/Cython/Compiler/Pipeline.py", line 235, in create_pyx_pipeline
    create_pipeline(context, mode, exclude_classes=exclude_classes),
  File "/Users/aaronmeurer/Documents/cython/Cython/Compiler/Pipeline.py", line 142, in create_pipeline
    from Optimize import FlattenInListTransform, SwitchTransform, IterationTransform
  File "/Users/aaronmeurer/Documents/cython/Cython/Compiler/Optimize.py", line 1651, in <module>
    class InlineDefNodeCalls(Visitor.NodeRefCleanupMixin, Visitor.EnvTransform):
AttributeError: 'module' object has no attribute 'NodeRefCleanupMixin'
make: *** [all] Error 1

This is with Cython 0.18.
```
Original issue for #6729: http://code.google.com/p/sympy/issues/detail?id=3630
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by moorepants** [comment]
Is this relevant anymore? I'm not sure what it is referring to.

**Comment by asmeurer** [comment]
I guess we got rid of that stupid makefile.
