### ISSUE TITLE
powsimp should be attempted for multiple generators case in solve

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#6819]
```
>>> var('a,b,c,d',positive=True)
(a, b, c, d)
>>> solve(a*b**x-c*d**x, x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solvers.py", line 826, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "sympy\solvers\solvers.py", line 1333, in _solve
    "\nNo algorithms are implemented to solve equation %s" % f)
NotImplementedError: multiple generators [b**x, d**x]
No algorithms are implemented to solve equation b**x

But solve does know how to solve this:

>>> solve(b**x-a/c,x)
[(log(a) - log(c))/log(b)]

And powsimp can reduce the ratio of powers to a single power:

>>> powsimp(b**(-x)*d**x)
(d/b)**x

So a solution should be possible. But the algorithm doesn't leave the power together:

>>> solve(_-a/c,x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solvers.py", line 826, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "sympy\solvers\solvers.py", line 1333, in _solve
    "\nNo algorithms are implemented to solve equation %s" % f)
NotImplementedError: multiple generators [b**x, d**x]
No algorithms are implemented to solve equation b**x
```

Original issue for #6819: http://code.google.com/p/sympy/issues/detail?id=3720
Original author: https://code.google.com/u/117933771799683895267/

**Comment by oscarbenjamin** [comment]
This seems to be fixed now:
```julia
In [144]: var('a,b,c,d',positive=True)                                                                                                                        
Out[144]: (a, b, c, d)

In [145]: solve(a*b**x-c*d**x, x)                                                                                                                             
Out[145]: 
⎡   ⎛c⎞⎤
⎢log⎜─⎟⎥
⎢   ⎝a⎠⎥
⎢──────⎥
⎢   ⎛b⎞⎥
⎢log⎜─⎟⎥
⎣   ⎝d⎠⎦
```
This issue can be closed if a test is added for this case
