### ISSUE TITLE
integrate fail

### ISSUE THREAD

**Issue by satels** [sympy/sympy#6828]
```
integrate(1/(1.08*x**2-4.3), x)


Traceback (most recent call last): File "<string>", line 1, in <module> File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/utilities/decorator.py", line 25, in threaded_func return func(expr, *args, **kwargs) File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/integrals/integrals.py", line 1360, in integrate return integral.doit(deep = False, meijerg = meijerg, conds = conds) File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/integrals/integrals.py", line 734, in doit antideriv = self._eval_integral(function, xab[0], meijerg1) File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/integrals/integrals.py", line 979, in _eval_integral parts.append(coeff * ratint(g, x)) File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/integrals/rationaltools.py", line 48, in ratint g, h = ratint_ratpart(p, q, x) File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/integrals/rationaltools.py", line 150, in ratint_ratpart H = f - A.diff()*v + A*(u.diff()*v).quo(u) - B*u File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/core/decorators.py", line 67, in __sympifyit_wrapper return func(a, sympify(b, strict=True)) File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/polys/polytools.py", line 3535, in __mul__ return f.mul(g) File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/polys/polytools.py", line 1327, in mul _, per, F, G = f._unify(g) File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/polys/polytools.py", line 372, in _unify F = f.rep.convert(dom) File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/polys/polyclasses.py", line 274, in convert return DMP(dmp_convert(f.rep, f.lev, f.dom, dom), dom, f.lev) File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/polys/densebasic.py", line 552, in dmp_convert return dup_convert(f, K0, K1) File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/polys/densebasic.py", line 527, in dup_convert return dup_strip([ K1.convert(c, K0) for c in f ]) File "/base/data/home/apps/s~sympy-live-hrd/34.364711976382463821/sympy/sympy/polys/domains/domain.py", line 83, in convert raise CoercionFailed("can't convert %s of type %s to %s" % (a, K0, K1)) CoercionFailed: can't convert DMP([[1], []], ZZ, ZZ[_b2,_b1]) of type ZZ[_b2,_b1] to RR
```
Original issue for #6828: http://code.google.com/p/sympy/issues/detail?id=3729
Original author: https://code.google.com/u/112786146078013975159/

**Comment by oldk1331** [comment]
In sympy 1.0, this integral no longer fails:
````
In [1]: integrate(1/(1.08*x**2-4.3), x)
Out[1]: 0.23201918599571⋅log(1.0⋅x - 1.99536499956311) - 0.23201918599571⋅log(1.0⋅x + 1.99536499956311)
````

This bug can be closed now.
