### ISSUE TITLE
integrate((3*x - 5)**2/(2*x - 1)**(7/2), x) _CoeffExpValueError

### ISSUE THREAD

**Issue by ppuedom** [sympy/sympy#7149]
```
Correct answer is (-41 + 80*x - 45*x**2)/(5*(2*x-1)**Rational(5/2))

integrate((3*x - 5)**2/(2*x - 1)**(7/2), x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pape/sympy/sympy/utilities/decorator.py", line 35, in threaded_func
    return func(expr, *args, **kwargs)
  File "/home/pape/sympy/sympy/integrals/integrals.py", line 1628, in integrate
    risch=risch, manual=manual)
  File "/home/pape/sympy/sympy/integrals/integrals.py", line 894, in doit
    conds=conds)
  File "/home/pape/sympy/sympy/integrals/integrals.py", line 1282, in _eval_integral
    h = meijerint_indefinite(g, x)
  File "/home/pape/sympy/sympy/integrals/meijerint.py", line 1597, in meijerint_indefinite
    res = _meijerint_indefinite_1(f.subs(x, x + a), x)
  File "/home/pape/sympy/sympy/integrals/meijerint.py", line 1612, in _meijerint_indefinite_1
    gs = _rewrite1(f, x)
  File "/home/pape/sympy/sympy/integrals/meijerint.py", line 1549, in _rewrite1
    g = _rewrite_single(g, x, recursive)
  File "/home/pape/sympy/sympy/core/cache.py", line 93, in wrapper
    r = func(*args, **kw_args)
  File "/home/pape/sympy/sympy/integrals/meijerint.py", line 1455, in _rewrite_single
    exponents_only=True), x)
  File "/home/pape/sympy/sympy/integrals/meijerint.py", line 319, in _get_coeff_exp
    raise _CoeffExpValueError('expr not of form a*x**b: %s' % expr)
sympy.integrals.meijerint._CoeffExpValueError: expr not of form a*x**b: 0.0155061879258435
```
Original issue for #7149: http://code.google.com/p/sympy/issues/detail?id=4050
Original author: https://code.google.com/u/118279007905392951376/

**Comment by oldk1331** [comment]
This integral is no longer a bug in sympy 1.0:

````
In [16]: time(simplify(integrate((3*x - 5)**2/(2*x - 1)**(Rational(7,2)), x)))
CPU times: user 8 s, sys: 12.4 ms, total: 8.01 s
Wall time: 8.01 s
Out[16]: 
           2                  
     - 45⋅x  + 80⋅x - 41      
──────────────────────────────
    _________ ⎛   2          ⎞
5⋅╲╱ 2⋅x - 1 ⋅⎝4⋅x  - 4⋅x + 1⎠
````

The result returned by `integrate` is a bit long but can be simplified, and doesn't take too much time.

This bug can be closed now.
