### ISSUE TITLE
use old assumptions in code

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#7256]
in inequalities.py, a test is made using the new assumption system; until the old assumption system is removed, it seems like something depending on the old assumptions system should still work.  Here is the line that has the problem (and maybe there are more throughout the codebase):

```
if not ask(Q.real(gen), assumptions=assume):
```

Here is the test that fails:

```
>>> from sympy import *
>>> var('w',real=1)
w
>>> solve(abs(w)+6>12)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solvers.py", line 688, in solve
    symbols=symbols)
  File "sympy\solvers\inequalities.py", line 519, in reduce_inequalities
    abs_reduced.append(reduce_abs_inequalities(exprs, gen, assume))
  File "sympy\solvers\inequalities.py", line 359, in reduce_abs_inequalities
    for expr, rel in exprs ])
  File "sympy\solvers\inequalities.py", line 276, in reduce_abs_inequality
    raise NotImplementedError("can't solve inequalities with absolute "
NotImplementedError: can't solve inequalities with absolute values of a complex
variable
```

A workaround is to provide the symbol:

```
>>> solve(abs(w)+6>12,w)
Or(w < -6, w > 6)
```

**Comment by jondo** [comment]
This seems to be fixed. With the current SymPy (commit 86b8ff), I see:
```python
In [1]: var('w',real=1)
Out[1]: w
In [2]: solve(abs(w)+6>12)
Out[2]: (-∞ < w ∧ w < -6) ∨ (6 < w ∧ w < ∞)
```

**Comment by oscarbenjamin** [comment]
The motivating example here seems to be fixed:
```
In [2]: solve(abs(x)+6>12)
Out[2]: (-∞ < x ∧ x < -6) ∨ (6 < x ∧ x < ∞)

In [3]: solve(abs(x)+6>12, x)
Out[3]: (-∞ < x ∧ x < -6) ∨ (6 < x ∧ x < ∞)
```

**Comment by smichr** [comment]
I think this works because assumption values are sanitized so 1 -> True:

https://github.com/sympy/sympy/blob/b176f6a1d9890b42dc361857c887992315e3d5ad/sympy/core/assumptions.py#L325
