### ISSUE TITLE
preview() function give error

### ISSUE THREAD

**Issue by jigarmistry** [sympy/sympy#7266]
**When i write this in sympy live**

`from sympy import symbols, preview, Symbol
 x, y = symbols("x,y")
 preview(x + y, output='png')`

**it give me error like,**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/printing/preview.py", line 311, in preview
    shutil.rmtree(workdir) # delete directory
UnboundLocalError: local variable 'workdir' referenced before assignment

**Comment by oscarbenjamin** [comment]
I think this can be closed
