### ISSUE TITLE
nsimplify(Integral(x, (x, 0.0, 1.0))) gives TypeError: cannot create mpf from None

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#7416]
See https://github.com/sympy/sympy/issues/2884#issuecomment-38794481

```pytb
nsimplify(Integral(x, (x, 0.0, 1.0)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mn/anatu/cma-u3/tmac/usr/lib/python2.6/site-packages/sympy/simplify/simplify.py", line 3861, in nsimplify
    exprval = expr.evalf(prec, chop=True)
  File "/mn/anatu/cma-u3/tmac/usr/lib/python2.6/site-packages/sympy/core/evalf.py", line 1284, in evalf
    result = evalf(self, prec + 4, options)
  File "/mn/anatu/cma-u3/tmac/usr/lib/python2.6/site-packages/sympy/core/evalf.py", line 1184, in evalf
    r = rf(x, prec, options)
  File "/mn/anatu/cma-u3/tmac/usr/lib/python2.6/site-packages/sympy/core/evalf.py", line 959, in evalf_integral
    result = do_integral(expr, workprec, options)
  File "/mn/anatu/cma-u3/tmac/usr/lib/python2.6/site-packages/sympy/core/evalf.py", line 875, in do_integral
    xlow = as_mpmath(xlow, prec + 15, options)
  File "/mn/anatu/cma-u3/tmac/usr/lib/python2.6/site-packages/sympy/core/evalf.py", line 862, in as_mpmath
    return mpf(re)
  File "/mn/anatu/cma-u3/tmac/usr/lib/python2.6/site-packages/sympy/mpmath/ctx_mp_python.py", line 77, in __new__
    v._mpf_ = mpf_pos(cls.mpf_convert_arg(val, prec, rounding), prec, rounding)
  File "/mn/anatu/cma-u3/tmac/usr/lib/python2.6/site-packages/sympy/mpmath/ctx_mp_python.py", line 96, in mpf_convert_arg
    raise TypeError("cannot create mpf from " + repr(x))
TypeError: cannot create mpf from None
```

**Comment by smichr** [comment]
as_mpmath is not expecting a Float(0) after sympification

```diff
diff --git a/sympy/core/evalf.py b/sympy/core/evalf.py
index d628fc2..8d9f470 100644
--- a/sympy/core/evalf.py
+++ b/sympy/core/evalf.py
@@ -853,7 +853,7 @@ def evalf_bernoulli(expr, prec, options):

 def as_mpmath(x, prec, options):
     x = sympify(x)
-    if isinstance(x, C.Zero):
+    if isinstance(x, C.Zero) or x == 0:
         return mpf(0)
     if isinstance(x, C.Infinity):
         return mpf('inf')
```

Then

```
>>> nsimplify(Integral(x, (x, 0.0, 1.0)))
1/2
```

**Comment by smichr** [comment]
And a sufficient test in test_evalf for this issue is

```
from sympy.core.evalf import as_mpmath
assert as_mpmath(0.0, 10, {'chop': True}) == 0
```

**Comment by mihir-w** [comment]
Done.
