### ISSUE TITLE
simple symbolic integral fails when using tensor.IndexedBase variables

### ISSUE THREAD

**Issue by rtrwalker** [sympy/sympy#7423]
In a previous version (I think it was 0.7.3 or 0.7.2, I cant be sure) I succesfully did some symbolic integrals with expressions that contained tensor.IndexedBase variabes (e.g. y[k]).  I was not integrating with respect to any of the IndexedBase variables so essentially they are constants in the integration.   I have now upgraded to sympy version 0.7.4.1 (via pythonxy) and my IndexedBase integrations do not work.  Below is some code that performs the same integral in two ways.  The first does not use IndexedBase, the second does.  The First integral is successful, the second is not.  Any Ideas what is going on?  If I try and do a more complex integral such as multiplying `f1` by `cos(tau)` then both integrals are successful (note if you do multiply by `cos(tau)` the computation can take some time).

```
import sympy
from sympy import exp, symbols, integrate, diff, cos

print(sympy.__version__)

t1, t2, t, tau, y1, y2, m=symbols('t1, t2, t, tau, y1, y2, m')
y_ = sympy.tensor.IndexedBase('y_')
t_ = sympy.tensor.IndexedBase('t_')
k = sympy.tensor.Idx('k')

#Here is the integral without IndexedBase variables
f1 =  (y2 - y1) / (t2 - t1) * (tau - t1) + y1
print(f1)
f2 = diff(f1, tau) * exp(-m*(t-tau))
print(f2)
iii=integrate(f2, (tau, t1, t))
print(iii)

#Here is the integral with IndexedBase variables
f1_ = y_[k]+ (y_[k + 1] - y_[k]) / (t_[k + 1] - t_[k]) * (tau - t_[k])
print(f1_)
f2_ = diff(f1_, tau) * exp(-m * (t - tau))
print(f2_)
iii_=integrate(f2_, (tau, t_[k], t))
print(iii_)
print('#'*30)
```

The above code results in:

```
0.7.4.1
y1 + (-t1 + tau)*(-y1 + y2)/(-t1 + t2)
(-y1 + y2)*exp(-m*(t - tau))/(-t1 + t2)
Piecewise((t*(y1 - y2)/(t1 - t2) - t1*(y1 - y2)/(t1 - t2), m*t1 - m*t2 == 0), ((y1 - y2)/(m*t1 - m*t2) - (y1 - y2)*exp(-m*(t - t1))/(m*t1 - m*t2), True))
##############################
(y_[k + 1] - y_[k])*(t_[k + 1] - t_[k])**(-1)*(g - t_[k]) + y_[k]
exp(-m*(-g + t))*(y_[k + 1] - y_[k])*(t_[k + 1] - t_[k])**(-1)
Traceback (most recent call last):
  File "C:\Users\Rohan Walker\Desktop\untitled101.py", line 1535, in <module>
    iii_=integrate(f2_, (g, t_[k], t))
  File "C:\Python27\lib\site-packages\sympy\utilities\decorator.py", line 35, in threaded_func
    return func(expr, *args, **kwargs)
  File "C:\Python27\lib\site-packages\sympy\integrals\integrals.py", line 1283, in integrate
    risch=risch, manual=manual)
  File "C:\Python27\lib\site-packages\sympy\integrals\integrals.py", line 555, in doit
    conds=conds)
  File "C:\Python27\lib\site-packages\sympy\integrals\integrals.py", line 811, in _eval_integral
    result, i = risch_integrate(f, x, separate_integral=True, conds=conds)
  File "C:\Python27\lib\site-packages\sympy\integrals\risch.py", line 1664, in risch_integrate
    DE = extension or DifferentialExtension(f, x, handle_first=handle_first, rewrite_complex=rewrite_complex)
  File "C:\Python27\lib\site-packages\sympy\integrals\risch.py", line 394, in __init__
    self.fa, self.fd = frac_in(self.newf, self.t)
  File "C:\Python27\lib\site-packages\sympy\integrals\risch.py", line 727, in frac_in
    raise ValueError("Could not turn %s into a fraction in %s." % (f, t))
ValueError: Could not turn _t0*(y_[k + 1] - y_[k])*(t_[k + 1] - t_[k])**(-1) into a fraction in _t0.
```

**Comment by oscarbenjamin** [comment]
I updated the code sample:
```python
import sympy
from sympy import exp, symbols, integrate, diff, cos

print(sympy.__version__)

t1, t2, t, tau, y1, y2, m=symbols('t1, t2, t, tau, y1, y2, m')
y_ = sympy.IndexedBase('y_')
t_ = sympy.IndexedBase('t_')
k = sympy.Idx('k')

#Here is the integral without IndexedBase variables
f1 =  (y2 - y1) / (t2 - t1) * (tau - t1) + y1
print(f1)
f2 = diff(f1, tau) * exp(-m*(t-tau))
print(f2)
iii=integrate(f2, (tau, t1, t))
print(iii)

#Here is the integral with IndexedBase variables
f1_ = y_[k]+ (y_[k + 1] - y_[k]) / (t_[k + 1] - t_[k]) * (tau - t_[k])
print(f1_)
f2_ = diff(f1_, tau) * exp(-m * (t - tau))
print(f2_)
iii_=integrate(f2_, (tau, t_[k], t))
print(iii_)
print('#'*30)
```

On current master this gives:
```
1.5.dev
y1 + (-t1 + tau)*(-y1 + y2)/(-t1 + t2)
(-y1 + y2)*exp(-m*(t - tau))/(-t1 + t2)
Piecewise(((y1 - y2)/(m*t1 - m*t2) - (y1 - y2)*exp(-m*(t - t1))/(m*t1 - m*t2), Ne(m*t1 - m*t2, 0)), (t*(y1 - y2)/(t1 - t2) - t1*(y1 - y2)/(t1 - t2), True))
(tau - t_[k])*(y_[k + 1] - y_[k])/(t_[k + 1] - t_[k]) + y_[k]
(y_[k + 1] - y_[k])*exp(-m*(t - tau))/(t_[k + 1] - t_[k])
Piecewise(((y_[k + 1] - y_[k])/(m*t_[k + 1] - m*t_[k]) - (y_[k + 1] - y_[k])*exp(-m*(t - t_[k]))/(m*t_[k + 1] - m*t_[k]), Ne(m*t_[k + 1] - m*t_[k], 0)), (t*(y_[k + 1] - y_[k])/(t_[k + 1] - t_[k]) - (y_[k + 1] - y_[k])*t_[k]/(t_[k + 1] - t_[k]), True))
##############################
```

Using pprint that is:
```
1.5.dev
     (-t₁ + τ)⋅(-y₁ + y₂)
y₁ + ────────────────────
           -t₁ + t₂      
            -m⋅(t - τ)
(-y₁ + y₂)⋅ℯ          
──────────────────────
       -t₁ + t₂       
⎧                         -m⋅(t - t₁)                     
⎪  y₁ - y₂     (y₁ - y₂)⋅ℯ                                
⎪─────────── - ──────────────────────  for m⋅t₁ - m⋅t₂ ≠ 0
⎪m⋅t₁ - m⋅t₂        m⋅t₁ - m⋅t₂                           
⎨                                                         
⎪     t⋅(y₁ - y₂)   t₁⋅(y₁ - y₂)                          
⎪     ─────────── - ────────────            otherwise     
⎪       t₁ - t₂       t₁ - t₂                             
⎩                                                         
(τ - t_[k])⋅(y_[k + 1] - y_[k])        
─────────────────────────────── + y_[k]
       t_[k + 1] - t_[k]               
                     -m⋅(t - τ)
(y_[k + 1] - y_[k])⋅ℯ          
───────────────────────────────
       t_[k + 1] - t_[k]       
⎧                                             -m⋅(t - t_[k])                               
⎪  y_[k + 1] - y_[k]     (y_[k + 1] - y_[k])⋅ℯ                                             
⎪───────────────────── - ───────────────────────────────────  for m⋅t_[k + 1] - m⋅t_[k] ≠ 0
⎪m⋅t_[k + 1] - m⋅t_[k]          m⋅t_[k + 1] - m⋅t_[k]                                      
⎨                                                                                          
⎪     t⋅(y_[k + 1] - y_[k])   (y_[k + 1] - y_[k])⋅t_[k]                                    
⎪     ───────────────────── - ─────────────────────────                 otherwise          
⎪       t_[k + 1] - t_[k]         t_[k + 1] - t_[k]   
```

So looks like it's fixed now.
