### ISSUE TITLE
Cannot solve third order eq. if coefficients are real and positive

### ISSUE THREAD

**Issue by ggventurini** [sympy/sympy#7584]
Maybe I am doing something wrong, but I noticed I can't solve third order eq. if coefficients are real and positive.

For example:

```
>>> sympy.__version__
'0.7.5'
>>> sympy.S('a*x**3+b*x**2+c*x+d')
a*x**3 + b*x**2 + c*x + d
>>> r = sympy.S('a*x**3+b*x**2+c*x+d')
>>> from sympy.abc import x
>>> sympy.solve(r, x)
[(c/(3*a) - b**2/(9*a**2))/(sqrt((c/(3*a) - b**2/(9*a**2))**3 + (d/a - b*c/(3*a**2) + 2*b**3/(27*a**3))**2/4) + d/(2*a) - b*c/(6*a**2) + b**3/(27*a**3))**(1/3) - (sqrt((c/(3*a) - b**2/(9*a**2))**3 + (d/a - b*c/(3*a**2) + 2*b**3/(27*a**3))**2/4) + d/(2*a) - b*c/(6*a**2) + b**3/(27*a**3))**(1/3) - b/(3*a), (c/(3*a) - b**2/(9*a**2))/((-1/2 - sqrt(3)*I/2)*(sqrt((c/(3*a) - b**2/(9*a**2))**3 + (d/a - b*c/(3*a**2) + 2*b**3/(27*a**3))**2/4) + d/(2*a) - b*c/(6*a**2) + b**3/(27*a**3))**(1/3)) - (-1/2 - sqrt(3)*I/2)*(sqrt((c/(3*a) - b**2/(9*a**2))**3 + (d/a - b*c/(3*a**2) + 2*b**3/(27*a**3))**2/4) + d/(2*a) - b*c/(6*a**2) + b**3/(27*a**3))**(1/3) - b/(3*a), (c/(3*a) - b**2/(9*a**2))/((-1/2 + sqrt(3)*I/2)*(sqrt((c/(3*a) - b**2/(9*a**2))**3 + (d/a - b*c/(3*a**2) + 2*b**3/(27*a**3))**2/4) + d/(2*a) - b*c/(6*a**2) + b**3/(27*a**3))**(1/3)) - (-1/2 + sqrt(3)*I/2)*(sqrt((c/(3*a) - b**2/(9*a**2))**3 + (d/a - b*c/(3*a**2) + 2*b**3/(27*a**3))**2/4) + d/(2*a) - b*c/(6*a**2) + b**3/(27*a**3))**(1/3) - b/(3*a)]
```

But if I do:
```
>>> from sympy.abc import x
>>> a = sympy.Symbol('a', real=True, positive=True)
>>> b = sympy.Symbol('b', real=True, positive=True)
>>> c = sympy.Symbol('c', real=True, positive=True)
>>> d = sympy.Symbol('d', real=True, positive=True)
>>> r = a*x**3+b*x**2+c*x+d
>>> sympy.solve(r, x)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/me/python-env/local/lib/python2.7/site-packages/sympy/solvers/solvers.py", line 901, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "/home/me/python-env/local/lib/python2.7/site-packages/sympy/solvers/solvers.py", line 1374, in _solve
    quintics=True).keys())
  File "/home/me/python-env/local/lib/python2.7/site-packages/sympy/polys/polyroots.py", line 884, in roots
    for root in _try_decompose(f):
  File "/home/me/python-env/local/lib/python2.7/site-packages/sympy/polys/polyroots.py", line 787, in _try_decompose
    for root in _try_heuristics(factors[0]):
  File "/home/me/python-env/local/lib/python2.7/site-packages/sympy/polys/polyroots.py", line 831, in _try_heuristics
    result += roots_cubic(f)
  File "/home/me/python-env/local/lib/python2.7/site-packages/sympy/polys/polyroots.py", line 117, in roots_cubic
    elif q.is_real and q < 0:
  File "/home/me/python-env/local/lib/python2.7/site-packages/sympy/core/relational.py", line 111, in __nonzero__
    raise TypeError("symbolic boolean expression has no truth value.")
TypeError: symbolic boolean expression has no truth value.
```

Any advice welcome - maybe I am somehow triggering this myself?

Thanks for all the great work!

**Comment by hargup** [comment]
The issue is not present in the current master.
