### ISSUE TITLE
sympy.utilities.mathml.c2p does not work with Python 3

### ISSUE THREAD

**Issue by pyfisch** [sympy/sympy#7591]
The bug is probably located in sympy/utilities/pkgdata.py and  is caused by the Unicode changes in Python 3.

``````
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy.utilities.mathml import c2p
>>> mml = u'<apply><plus/><ci>x</ci><cn>1</cn></apply>'
>>> c2p(mml)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/sympy/utilities/mathml/__init__.py", line 62, in c2p
    return apply_xsl(mml, 'mathml/data/mmlctop.xsl')
  File "/usr/local/lib/python3.4/dist-packages/sympy/utilities/mathml/__init__.py", line 35, in apply_xsl
    s = etree.XML(get_resource(xsl).read())
  File "/usr/local/lib/python3.4/dist-packages/sympy/utilities/pkgdata.py", line 57, in get_resource
    return StringIO(data)
TypeError: initial_value must be str or None, not bytes
>>> ```
``````

**Comment by oscargus** [comment]
This seems to work in the current master, at least on my 3.7 installation, so I close it for now.
