### ISSUE TITLE
dsolve failing in integration routine

### ISSUE THREAD

**Issue by kundankrmodi** [sympy/sympy#7714]
`dsolve(sqrt(-4*C1/5 + C2/5 + 3*x(t)**2/5)*sqrt(5*C1/4 - C2/4 - 3*x(t)**2/2)*sin(t) + 3*Derivative(x(t), t))`
It is failing in integration routine. The error it gives is

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/solvers/ode.py", line 608, in dsolve
    return _helper_simplify(eq, hint, hints, simplify)
  File "sympy/solvers/ode.py", line 634, in _helper_simplify
    return odesimp(sols, func, order, cons(sols), hint)
  File "sympy/core/multidimensional.py", line 137, in wrapper
    return f(*args, **kwargs)
  File "sympy/solvers/ode.py", line 1797, in odesimp
    eq = _handle_Integral(eq, func, order, hint)
  File "sympy/solvers/ode.py", line 2571, in _handle_Integral
    sol = expr.doit()
  File "sympy/core/relational.py", line 99, in doit
    lhs = lhs.doit(**hints)
  File "sympy/integrals/integrals.py", line 579, in doit
    conds=conds)
  File "sympy/integrals/integrals.py", line 979, in _eval_integral
    result = manualintegrate(g, x)
  File "sympy/integrals/manualintegrate.py", line 1126, in manualintegrate
    return _manualintegrate(integral_steps(f, var))
  File "sympy/integrals/manualintegrate.py", line 930, in integral_steps
    fallback_rule)(integral)
  File "sympy/strategies/core.py", line 86, in do_one_rl
    result = rl(expr)
  File "sympy/strategies/core.py", line 86, in do_one_rl
    result = rl(expr)
  File "sympy/strategies/core.py", line 66, in null_safe_rl
    result = rule(expr)
  File "sympy/integrals/manualintegrate.py", line 686, in trig_substitution_rule
    a = match[a]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by oscarbenjamin** [comment]
The error no longer happens. Currently I get this:
```julia
In [14]: C1, C2 = symbols('C1 C2')                                                                                                             

In [15]: x = Function('x')                                                                                                                     

In [16]: dsolve(sqrt(-4*C1/5 + C2/5 + 3*x(t)**2/5)*sqrt(5*C1/4 - C2/4 - 3*x(t)**2/2)*sin(t) + 3*Derivative(x(t), t))                           
Out[16]: 
  x(t)                                                                  
   ⌠                                                                    
   ⎮                         1                                 √5⋅cos(t)
3⋅ ⎮   ───────────────────────────────────────────── dy = C₃ + ─────────
   ⎮      ____________________    __________________               10   
   ⎮     ╱      2                ╱    2                                 
   ⎮   ╲╱  - 6⋅y  + 5⋅C₁ - C₂ ⋅╲╱  3⋅y  - 4⋅C₁ + C₂                     
   ⌡                                                                    
                   
```
Maybe that integral can be evaluated but otherwise I don't see why dsolve should be able to get a better answer. The ODE is:
```julia
In [17]: sqrt(-4*C1/5 + C2/5 + 3*x(t)**2/5)*sqrt(5*C1/4 - C2/4 - 3*x(t)**2/2)*sin(t) + 3*Derivative(x(t), t)                                   
Out[17]: 
     _______________________      _____________________                    
    ╱                  2         ╱                2                        
   ╱    4⋅C₁   C₂   3⋅x (t)     ╱  5⋅C₁   C₂   3⋅x (t)             d       
  ╱   - ──── + ── + ─────── ⋅  ╱   ──── - ── - ─────── ⋅sin(t) + 3⋅──(x(t))
╲╱       5     5       5     ╲╱     4     4       2                dt      

```
