### ISSUE TITLE
`Equality` and `MatrixExpr`

### ISSUE THREAD

**Issue by jcrist** [sympy/sympy#7842]
There are a couple issues here, just not sure about the best way to fix them.

A couple things to setup the examples:

```
>>> A = MatrixSymbol('A', 3, 1)
>>> B = MatrixSymbol('B', 2, 1)
```

1.) A and B cannot be equal, but Symbol doesn't care:

```
>>> Eq(A, B)
A == B
```

I think this could be fixed by giving `MatrixSymbol` its own `_eval_Eq` method, as `ImmutableMatrix` does, but this method could also go in `MatrixExpr` itself. The second is probably preferrable, as it would work for anything containing `MatrixExpr`

2.) Individual elements should be able to be set equivalent (as you can with Symbol), but you can't:

```
>>> Eq(A[1,0], B[1, 0])
# Trimming long error
/home/jimmy/Code/sympy/sympy/core/expr.py in equals(self, other, failing_expression)
    554         # because if the expression ever goes to 0 then the subsequent
    555         # simplification steps that are done will be very fast.
--> 556         diff = factor_terms((self - other).simplify(), radical=True)
    557 
    558         if not diff:

/home/jimmy/Code/sympy/sympy/core/expr.py in simplify(self, ratio, measure)
   2882         from sympy.core.function import count_ops
   2883         measure = measure or count_ops
-> 2884         return simplify(self, ratio, measure)
   2885 
   2886     def nsimplify(self, constants=[], tolerance=None, full=False):

/home/jimmy/Code/sympy/sympy/simplify/simplify.py in simplify(expr, ratio, measure, fu)
   3692     _e = cancel(expr)
   3693     expr1 = shorter(_e, _mexpand(_e).cancel())  # issue 6829
-> 3694     expr2 = shorter(together(expr, deep=True), together(expr1, deep=True))
   3695 
   3696     if ratio is S.Infinity:

/home/jimmy/Code/sympy/sympy/simplify/simplify.py in shorter(*choices)
   3686         if not has_variety(choices):
   3687             return choices[0]
-> 3688         return min(choices, key=measure)
   3689 
   3690     expr = bottom_up(expr, lambda w: w.normal())

/home/jimmy/Code/sympy/sympy/core/function.py in count_ops(expr, visual)
   2263         while args:
   2264             a = args.pop()
-> 2265             if a.is_Rational:
   2266                 #-1/3 = NEG + DIV
   2267                 if a is not S.One:

AttributeError: 'str' object has no attribute 'is_Rational'
```

I have two thoughts on fixing this:
1. Make `MatrixElement` a subclass of Symbol. Perhaps this is a bad idea, but then it would work with the current `Eq` method.
2. Add `MatrixElement` to the `has` statement in `_eval_sides` method of `Relational` in sympy/core/Relational.py. This seems like a hackish thing though.

I think making MatrixElement a subclass of Symbol is the best bet, but doing that change results in tons of errors right now. Thoughts?

**Comment by asmeurer** [comment]
Latest situation in master:

```pypy
>>> Eq(A, B)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/core/relational.py", line 384, in __new__
    dif = lhs - rhs
  File "./sympy/matrices/expressions/matexpr.py", line 24, in __sympifyit_wrapper
    return func(a, b)
  File "./sympy/core/decorators.py", line 132, in binary_op_wrapper
    return func(self, other)
  File "./sympy/matrices/expressions/matexpr.py", line 97, in __sub__
    return MatAdd(self, -other, check=True).doit()
  File "./sympy/matrices/expressions/matadd.py", line 49, in __new__
    validate(*args)
  File "./sympy/matrices/expressions/matadd.py", line 89, in validate
    raise ShapeError("Matrices %s and %s are not aligned"%(A, B))
sympy.matrices.common.ShapeError: Matrices A and -B are not aligned
>>> Eq(A[1,0], B[1, 0])
Eq(A[1, 0], B[1, 0])
```

The first should be easy to fix by defining `_eval_Eq` on MatExpr. It would need to unconditionally return an Equality when it cannot return a bool, to avoid the code in the Eq constructor that does `lhs - rhs`. The `_eval_Eq` would be something like

```py
def _eval_Eq(self, other):
    if not isinstance(other, MatrixExpr:
        return False
    if self.shape != other.shape:
        return False
    if (self - other).is_ZeroMatrix:
        return True
    return Eq(self, other, evaluate=False)
```

`Eq(A[1,0], B[1, 0])` works so we should make sure it is tested, so it doesn't break again.
