### ISSUE TITLE
Random variables as valid parameters for distributions

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8128]
I am not sure whether this is a bug or a feature request. However, even if it is a feature request, some code should be changed to prompt/warn that this feature is not (yet?) implemented.

I tried to give a random variable as a valid parameter to another distribution. In particular, I've tried to create a binomial random variable whose number of trials is the result of another binomial random variable. That did not work.

Here's the code:

``` python
a = Binomial('a', 10, S(1)/2)
b = Binomial('b', a, S(1)/3)
print P(b>2)
```

and this raises

``` pytb
Traceback (most recent call last):
  File "<ipython-input-46-5ffbc1103b81>", line 1, in <module>
    P(b>2)
  File "sympy/stats/rv.py", line 621, in probability
    result = pspace(condition).probability(condition, **kwargs)
  File "sympy/stats/rv.py", line 436, in pspace
    return ProductPSpace(*[rv.pspace for rv in rvs])
  File "sympy/stats/rv.py", line 277, in __new__
    for value in space.values:
  File "sympy/stats/rv.py", line 151, in values
    return frozenset(RandomSymbol(self, sym) for sym in self.domain.symbols)
  File "sympy/stats/frv.py", line 318, in domain
    return SingleFiniteDomain(self.symbol, self.distribution.set)
  File "sympy/stats/frv.py", line 187, in set
    return list(self.dict.keys())
  File "sympy/core/cache.py", line 93, in wrapper
    retval = func(*args, **kwargs)
  File "sympy/stats/frv_types.py", line 196, in dict
    binomial(n, k) * p**k * (1 - p)**(n - k)) for k in range(0, n + 1))
  File "sympy/core/expr.py", line 180, in __int__
    r = self.round(2)
  File "sympy/core/expr.py", line 3022, in round
    raise TypeError('%s is not a number' % x)
TypeError: a + 1 is not a number
```

This is quite ok, but if these things are not supported, a warning or an exception should be raised earlier, when constructing the random variable.

Perhaps it is interesting to see that with Bernoulli variables an exception is not even raised, but rather:

``` python
a = Bernoulli('a', S(1)/2)
b = Bernoulli('b', a)
print P(b>0.5)
## prints a
```

**Comment by pelegm** [comment]
This now raises a different exception:
```pytb
Traceback (most recent call last):
  File "<ipython-input-8-b81ac5b17481>", line 1, in <module>
    print P(b>2)
  File "sympy/stats/rv.py", line 616, in probability
    result = pspace(condition).probability(condition, **kwargs)
  File "sympy/stats/rv.py", line 431, in pspace
    return ProductPSpace(*[rv.pspace for rv in rvs])
  File "sympy/stats/rv.py", line 272, in __new__
    for value in space.values:
  File "sympy/stats/rv.py", line 146, in values
    return frozenset(RandomSymbol(self, sym) for sym in self.domain.symbols)
  File "sympy/stats/frv.py", line 318, in domain
    return SingleFiniteDomain(self.symbol, self.distribution.set)
  File "sympy/stats/frv.py", line 187, in set
    return list(self.dict.keys())
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/stats/frv_types.py", line 223, in dict
    n = as_int(n)
  File "sympy/core/compatibility.py", line 389, in as_int
    raise ValueError('%s is not an integer' % n)
ValueError: a is not an integer
```

**Comment by snotskie** [comment]
Bumping this with a few more relevant examples to what I'm working on. Using random variables as parameters to other Sympy modules should definitely be a supported feature.

```
X = Uniform("X", 0, 1)
E(Bernoulli("Y", X))
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/sympy/stats/rv.py", line 569, in expectation
    result = pspace(expr).integrate(expr)
  File "/usr/lib/python2.7/site-packages/sympy/stats/rv.py", line 317, in integrate
    expr = space.integrate(expr, rvs & space.values, **kwargs)
  File "/usr/lib/python2.7/site-packages/sympy/stats/frv.py", line 272, in integrate
    for elem in self.domain])
  File "/usr/lib/python2.7/site-packages/sympy/core/basic.py", line 1083, in xreplace
    args.append(a.xreplace(rule))
  File "/usr/lib/python2.7/site-packages/sympy/core/basic.py", line 1088, in xreplace
    return self.func(*args)
  File "/usr/lib/python2.7/site-packages/sympy/stats/rv.py", line 178, in __new__
    raise TypeError("s should have been string or Symbol")
TypeError: s should have been string or Symbol
```
```
P(Eq(Bernoulli("Y", X), 1))
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/sympy/stats/rv.py", line 617, in probability
    result = pspace(condition).probability(condition, **kwargs)
  File "/usr/lib/python2.7/site-packages/sympy/stats/rv.py", line 163, in probability
    raise NotImplementedError()
NotImplementedError
```

**Comment by Smit-create** [comment]
> ```python
> a = Binomial('a', 10, S(1)/2)
> b = Binomial('b', a, S(1)/3)
> ```

This is incorrect as `a` has to be always a positive integer.
