### ISSUE TITLE
solve(Eq(cos(Abs(sin(x) + 1)), 1), x) typeerror on 0.7.5, but on 0.7.3 with result

### ISSUE THREAD

**Issue by satels** [sympy/sympy#8196]
solve(Eq(cos(Abs(sin(x) + 1)), 1), x)

On live.sympy.org:
<pre>
Traceback (most recent call last): File "<string>", line 1, in <module> File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/solvers/solvers.py", line 900, in solve solution = _solve(f[0], *symbols, **flags) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/solvers/solvers.py", line 1382, in _solve inversion = _solve(gen - u, symbol, **flags) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/solvers/solvers.py", line 1394, in _solve result = _tsolve(f_num, symbol, **flags) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/solvers/solvers.py", line 2199, in _tsolve soln.extend(_solve(lhs.args[0] - i, sym, **flags)) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/solvers/solvers.py", line 1418, in _solve checksol(f_num, {symbol: r}, **flags) is not False] File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/solvers/solvers.py", line 224, in checksol val, reps = posify(val) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/simplify/simplify.py", line 2074, in posify eq = eq.subs(reps) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/basic.py", line 949, in subs rv = rv._subs(old, new, **kwargs) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/cache.py", line 93, in wrapper r = func(*args, **kw_args) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/basic.py", line 1063, in _subs rv = fallback(self, old, new) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/basic.py", line 1035, in fallback arg = arg._subs(old, new, **hints) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/cache.py", line 93, in wrapper r = func(*args, **kw_args) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/basic.py", line 1063, in _subs rv = fallback(self, old, new) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/basic.py", line 1035, in fallback arg = arg._subs(old, new, **hints) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/cache.py", line 93, in wrapper r = func(*args, **kw_args) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/basic.py", line 1063, in _subs rv = fallback(self, old, new) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/basic.py", line 1035, in fallback arg = arg._subs(old, new, **hints) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/cache.py", line 93, in wrapper r = func(*args, **kw_args) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/basic.py", line 1063, in _subs rv = fallback(self, old, new) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/basic.py", line 1035, in fallback arg = arg._subs(old, new, **hints) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/cache.py", line 93, in wrapper r = func(*args, **kw_args) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/basic.py", line 1063, in _subs rv = fallback(self, old, new) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/basic.py", line 1040, in fallback rv = self.func(*args) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/cache.py", line 93, in wrapper r = func(*args, **kw_args) File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/power.py", line 119, in __new__ obj = b._eval_power(e)
File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/power.py", line 143, in _eval_power if b.is_real and not b_nneg and e.is_even:
File "/base/data/home/apps/s~sympy-live-hrd/43.373169527249054993/sympy/sympy/core/relational.py", line 226, in __nonzero__ raise TypeError("symbolic boolean expression has no truth value.")
TypeError: symbolic boolean expression has no truth value.
</pre>

On 0.7.3

<pre>
In [5]: solve(Eq(cos(Abs(sin(x) + 1)), 1), x)
Out[5]:
[-pi/2,
 3*pi/2,
 pi + asin(1 + 2*pi),
 pi + asin(-2*pi + 1),
 -asin(1 + 2*pi),
 -asin(-2*pi + 1)]
</pre>

And typeerror on 0.7.3 with other example: solve(Eq(cos(Abs(sin(x) + 1)), 2), x)

<pre>
in mpf_cmp(s, t)
    553     # A full subtraction is relatively slow, however, so we first try to
    554     # look at the components.
--> 555     ssign, sman, sexp, sbc = s
    556     tsign, tman, texp, tbc = t
    557

TypeError: 'NoneType' object is not iterable
</pre>

**Comment by smichr** [comment]
In master as of this date:

```python
>>> var('x',real=1)
x
>>> solve(Eq(cos(Abs(sin(x) + 1)), 1), x)
[-pi/2, 3*pi/2]
>>> solve(Eq(cos(Abs(sin(x) + 1)), 2), x)
[]
```

So I think this can be closed.
