### ISSUE TITLE
PMF of poisson rv is not implemented?

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8220]
While expectation and variance of poisson random variables work well, and expressions like

``` python
P(Eq(Bernoulli('b', S.Half), S.One))
```

make sense, expressions like

``` python
P(Eq(Poisson('p', S.Half), S.One))
```

raise

``` pytb
Traceback (most recent call last):
  File "<ipython-input-12-3e777ae197b3>", line 1, in <module>
    P(Eq(Poisson('p', S.Half), S.One))
  File "sympy/stats/rv.py", line 621, in probability
    result = pspace(condition).probability(condition, **kwargs)
  File "sympy/stats/rv.py", line 167, in probability
    raise NotImplementedError()
NotImplementedError
```

**Comment by oscarbenjamin** [comment]
Both expressions seem to work now:
```julia
In [1]: from sympy.stats import *                                                                                                              

In [2]: P(Eq(Bernoulli('b', S.Half), S.One))                                                                                                   
Out[2]: 1/2

In [3]: P(Eq(Poisson('p', S.Half), S.One))                                                                                                     
Out[3]: 
 -1/2
ℯ    
─────
  2  
```
