### ISSUE TITLE
PSpace cannot integrate an `int`

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8248]
While pspaces can integrate a symbolic integer (`Integer`), they cannot integrate a pythonic integer (`int`). Example:

``` python
In [4]: p = Poisson('p', 3)

In [5]: p.pspace.integrate(1)
```

raises

``` pytb
Traceback (most recent call last):
  File "<ipython-input-5-f408d8c9c5ad>", line 1, in <module>
    p.pspace.integrate(1)
  File "sympy/stats/drv.py", line 113, in integrate
    expr = expr.xreplace(dict((rv, rv.symbol) for rv in rvs))
AttributeError: 'int' object has no attribute 'xreplace'
```

I guess that since `Expr` has `xreplace`, this `AttributeError` should be caught, and the conclusion should be that the argument is not an `Expr`, and if it is `Expr`-friendly (python `int`', `float`, etc.), it should be casted into one (perhaps via `S(1)` or so).

**Comment by pelegm** [comment]
This is probably easy to fix (again, as `p.pspace.integrate(S.One)` works perfectly). I can do this, if you think it's the proper way to go. What do you think?

**Comment by oscarbenjamin** [comment]
I now get this:
```
In [4]: from sympy.stats import Poisson                                                                                                        

In [5]: p = Poisson('p', 3)                                                                                                                    

In [6]: p.pspace.integrate(1)                                                                                                                  
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-00337f2a13db> in <module>
----> 1 p.pspace.integrate(1)

AttributeError: 'SingleDiscretePSpace' object has no attribute 'integrate'
```

I guess that the API has changed in the mean time...

**Comment by smichr** [comment]
`integrate` -> `compute_expectation`: so `Poisson('p', 3).pspace.compute_expectation(1)` fails:
```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    print(Poisson('p', 3).pspace.compute_expectation(1))
  File "/home/runner/.local/lib/python3.6/site-packages/sympy/stats/drv.py", line 306, in compute_expectation
    expr = expr.xreplace(dict((rv, rv.symbol) for rv in rvs))
AttributeError: 'int' object has no attribute 'xreplace'
```
The `expr` should be sympified:

https://github.com/sympy/sympy/blob/b176f6a1d9890b42dc361857c887992315e3d5ad/sympy/stats/drv.py#L301-L310
