### ISSUE TITLE
TypeError: bad operand type for unary -: 'NoneType' on Sum of a piecewise sequence

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8299]
The following:

``` python
In [3]: n = Symbol('n', integer=True, nonnegative=True)

In [4]: a = Lambda(n, Piecewise((1, n<5), (0, True)))

In [5]: Sum(a(n), (n, 5, oo)).evalf()
```

raises

``` pytb
Traceback (most recent call last):
  File "<ipython-input-5-490f6f304653>", line 1, in <module>
    Sum(a(n), (n, 5, oo)).evalf()
  File "sympy/core/evalf.py", line 1317, in evalf
    result = evalf(self, prec + 4, options)
  File "sympy/core/evalf.py", line 1211, in evalf
    r = rf(x, prec, options)
  File "sympy/core/evalf.py", line 1112, in evalf_sum
    v = hypsum(func, n, int(a), prec2)
  File "sympy/core/evalf.py", line 1068, in hypsum
    raise ValueError("Sum diverges like n^%i" % (-p))
TypeError: bad operand type for unary -: 'NoneType'
```

It looks similar to the closed issue #6372.

**Comment by oscarbenjamin** [comment]
This now evaluates to 0 (which looks incorrect):
```
In [1]: n = Symbol('n', integer=True, nonnegative=True)                                                                                        

In [2]: a = Lambda(n, Piecewise((1, n<5), (0, True)))                                                                                          

In [3]: Sum(a(n), (n, 5, oo)).evalf() 
   ...:                                                                                                                                        
Out[3]: 0
```

Also:
```
In [4]: Sum(a(n), (n, 4, oo)).evalf()                                                                                                          
Out[4]: 1.00000000000000
```

So I think this is working fine now.

**Comment by pelegm** [comment]
Great.
