### ISSUE TITLE
inequality solving is not supported over EX

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8370]
This seems a rather naive/simple inequality, but apparently this is not implemented:
```python
In [3]: n = Symbol('n', integer=True, nonnegative=True)

In [4]: solve(n >= -sqrt(2) + 1)
```
raises
```pytb
Traceback (most recent call last):
  File "<ipython-input-4-7b450ffa0b02>", line 1, in <module>
    solve(n >= -sqrt(2) + 1)
  File "sympy/solvers/solvers.py", line 691, in solve
    return reduce_inequalities(f, symbols=symbols)
  File "sympy/solvers/inequalities.py", line 513, in reduce_inequalities
    poly_reduced.append(reduce_rational_inequalities([exprs], gen))
  File "sympy/solvers/inequalities.py", line 236, in reduce_rational_inequalities
    "inequality solving is not supported over %s" % opt.domain)
NotImplementedError: inequality solving is not supported over EX
```

**Comment by pelegm** [comment]
Update: this does not raise an error any more, but instead leaves an unevaluated relational. If this is the wanted behaviour (until we know how to solve it), perhaps we could close this issue.

**Comment by smichr** [comment]
It now gives True:

```python
>>> from sympy import *
>>> n = Symbol('n', integer=True, nonnegative=True)
>>>
>>> solve(n >= -sqrt(2) + 1)
True
```

**Comment by pelegm** [comment]
@smichr, perhaps we should add a test for this?
