### ISSUE TITLE
Sampling from poisson distribution fails

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8478]
The following:

``` python
>>> p = Poisson('p', Rational(1, 10))
>>> sample(p)
```

raises

``` pytb
Traceback (most recent call last):
  File "<ipython-input-5-16980c83ac2c>", line 1, in <module>
    sample(p)
  File "sympy/stats/rv.py", line 783, in sample
    return next(sample_iter(expr, condition, numsamples=1))
  File "sympy/stats/rv.py", line 879, in sample_iter_subs
    d = ps.sample()  # a dictionary that maps RVs to values
  File "sympy/stats/drv.py", line 106, in sample
    return {self.value: self.distribution.sample()}
  File "sympy/stats/drv.py", line 31, in sample
    icdf = self._inverse_cdf_expression()
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/stats/drv.py", line 47, in _inverse_cdf_expression
    raise NotImplementedError("Could not invert CDF")
NotImplementedError: Could not invert CDF
```

Inverting the CDF is only one way of sampling from a discrete distribution, and I am not even sure it is the most efficient.

**Comment by deepakgouda** [comment]
I would like to take up this issue. I have worked with Acceptance Rejection Methods to generate various sample.
@skirpichev

**Comment by NoumbissiValere** [comment]
@asmeurer  is this issue still open? i will like to take it

**Comment by Anjali167-sopho** [comment]
@pelegm can I work on this issue?
if possible could you also tell me how to start working on this issue?

**Comment by Anjali167-sopho** [comment]
I tested the above code and it is giving the correct output, I also tried changing the values of lambda to verify.
Hence, I suppose we can close this issue.
