### ISSUE TITLE
Wrong error raised trying to calculate limit of Poisson PMF

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8481]
The limit of the Poisson probability mass function (PMF) is 0. Trying to calculate it using SymPy looks like the following:

``` python
>>> k = Symbol('k', integer=True, nonnegative=True)
>>> lamda = Symbol('lamda', real=True, positive=True)
>>> limit(lamda**k * exp(-lamda) / factorial(k), k, oo)
```

but the last line raises the following error:

``` pytb
Traceback (most recent call last):
  File "<ipython-input-5-9e9c57cf4342>", line 1, in <module>
    limit(lamda**k * exp(-lamda) / factorial(k), k, oo)
  File "sympy/series/limits.py", line 42, in limit
    return Limit(e, z, z0, dir).doit(deep=False)
  File "sympy/series/limits.py", line 157, in doit
    r = gruntz(e, z, z0, dir)
  File "sympy/series/gruntz.py", line 637, in gruntz
    r = limitinf(e, z)
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/series/gruntz.py", line 420, in limitinf
    c0, e0 = mrv_leadterm(e, x)
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/series/gruntz.py", line 501, in mrv_leadterm
    f, logw = rewrite(exps, Omega, x, w)
  File "sympy/series/gruntz.py", line 573, in rewrite
    raise NotImplementedError('Result depends on the sign of %s' % sig)
NotImplementedError: Result depends on the sign of sign(log(lamda))
```

which is simply not right, as the result in this case does not depend on the sign of `log(lamda)`.

**Comment by sachin-4099** [comment]
Closing in favour of: https://github.com/sympy/sympy/pull/19292
Adding the testcase in: https://github.com/sympy/sympy/pull/19447
