### ISSUE TITLE
factorial2 of some floats causes infinite recursion

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8491]
While `factorial2(1.0)` returns a `Float`, `factorial2(1.1)` raises

``` pytb
...
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/core/function.py", line 199, in __new__
    evaluated = cls.eval(*args)
  File "sympy/functions/combinatorial/factorials.py", line 266, in eval
    return factorial2(arg - 2)*arg
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/core/function.py", line 375, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 872, in wrapper
    result = user_function(*args, **kwds)
  File "sympy/core/function.py", line 199, in __new__
    evaluated = cls.eval(*args)
  File "sympy/functions/combinatorial/factorials.py", line 266, in eval
    return factorial2(arg - 2)*arg
  File "sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy/core/compatibility.py", line 854, in wrapper
    key = make_key(args, kwds, typed) if kwds or typed else args
  File "sympy/core/compatibility.py", line 786, in _make_key
    return _HashedSeq(key)
  File "sympy/core/compatibility.py", line 764, in __init__
    self.hashvalue = hash(tup)
  File "sympy/core/numbers.py", line 947, in __hash__
    return super(Float, self).__hash__()
  File "sympy/core/numbers.py", line 413, in __hash__
    return super(Number, self).__hash__()
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

According to the function's docstring, it is not defined on non-integers, so maybe argcheck should be made.

**Comment by oscarbenjamin** [comment]
These examples raise ValueError now:
```julia
In [3]: factorial2(1.0)                                                                                                                        
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-225f209e0972> in <module>
----> 1 factorial2(1.0)

~/current/sympy/sympy/sympy/core/cache.py in wrapper(*args, **kwargs)
     92             def wrapper(*args, **kwargs):
     93                 try:
---> 94                     retval = cfunc(*args, **kwargs)
     95                 except TypeError:
     96                     retval = func(*args, **kwargs)

~/current/sympy/sympy/sympy/core/function.py in __new__(cls, *args, **options)
    456 
    457         evaluate = options.get('evaluate', global_evaluate[0])
--> 458         result = super(Function, cls).__new__(cls, *args, **options)
    459         if evaluate and isinstance(result, cls) and result.args:
    460             pr2 = min(cls._should_evalf(a) for a in result.args)

~/current/sympy/sympy/sympy/core/cache.py in wrapper(*args, **kwargs)
     92             def wrapper(*args, **kwargs):
     93                 try:
---> 94                     retval = cfunc(*args, **kwargs)
     95                 except TypeError:
     96                     retval = func(*args, **kwargs)

~/current/sympy/sympy/sympy/core/function.py in __new__(cls, *args, **options)
    275 
    276         if evaluate:
--> 277             evaluated = cls.eval(*args)
    278             if evaluated is not None:
    279                 return evaluated

~/current/sympy/sympy/sympy/functions/combinatorial/factorials.py in eval(cls, arg)
    396         if arg.is_Number:
    397             if not arg.is_Integer:
--> 398                 raise ValueError("argument must be nonnegative integer "
    399                                     "or negative odd integer")
    400 

ValueError: argument must be nonnegative integer or negative odd integer
```
so I think this is fixed.
