### ISSUE TITLE
Mathematica parser can't parse ((-2x+5)(4x-1)-4(-x^2+5x+1))/(4x-1)^2

### ISSUE THREAD

**Issue by redstoneleo** [sympy/sympy#8535]
```
>>> from sympy.parsing.mathematica import mathematica as M
>>> from sympy.abc import x
>>> M( '(-6x^2-x-7)(2x^3+3x^2-2x-5)' )
(-6*x**2 - x - 7)*(2*x**3 + 3*x**2 - 2*x - 5)
>>> M( '((-2x+5)(4x-1)-4(-x^2+5x+1))/(4x-1)^2' )
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\sympy-0.7.5_git-py3.4.egg\sympy\core\sympify.py", line 317, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "C:\Python34\lib\site-packages\sympy-0.7.5_git-py3.4.egg\sympy\parsing\sympy_parser.py", line 792, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Python34\lib\site-packages\sympy-0.7.5_git-py3.4.egg\sympy\parsing\sympy_parser.py", line 726, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1
    ((-Integer (2 )*Symbol ('x' )+Integer (5 ))*(Integer (4 )*Symbol ('x' )-Integer (1 ))-Integer (4 )*(-Symbol ('x' )**Integer (2 )+Integer (5 )*Symbol ('x' )+Integer (1 )))/(Integer (4 )Symbol ('x' )-Integer (1 ))
                                                                                                                                                                                                 ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    M( '((-2x+5)(4x-1)-4(-x^2+5x+1))/(4x-1)^2' )
  File "C:\Python34\lib\site-packages\sympy-0.7.5_git-py3.4.egg\sympy\parsing\mathematica.py", line 8, in mathematica
    return sympify(parse(s))
  File "C:\Python34\lib\site-packages\sympy-0.7.5_git-py3.4.egg\sympy\core\sympify.py", line 319, in sympify
    raise SympifyError('could not parse %r' % a, exc)
sympy.core.sympify.SympifyError: Sympify of expression 'could not parse '((-2*x+5)*(4*x-1)-4*(-x**2+5*x+1))/(4x-1)'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)
>>> 
```

**Comment by oscarbenjamin** [comment]
This now seems to be fixed:
```
In [32]: >>> from sympy.parsing.mathematica import mathematica as M 
    ...: >>> from sympy.abc import x 
    ...: >>> M( '(-6x^2-x-7)(2x^3+3x^2-2x-5)' )                                                                                                
Out[32]: 
⎛     2        ⎞ ⎛   3      2          ⎞
⎝- 6⋅x  - x - 7⎠⋅⎝2⋅x  + 3⋅x  - 2⋅x - 5⎠

In [33]:  M( '((-2x+5)(4x-1)-4(-x^2+5x+1))/(4x-1)^2' )                                                                                         
Out[33]: 
   2                                 
4⋅x  - 20⋅x + (5 - 2⋅x)⋅(4⋅x - 1) - 4
─────────────────────────────────────
                       2             
              (4⋅x - 1)              

```
Maybe this can be closed...
