### ISSUE TITLE
TypeError generated when checking solution with RootOf instances

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#8544]
```
import sympy as sy
q0,q1,x,y = sy.symbols('q_0,q_1,x,y')
s = sy.Matrix([sy.Eq(x-sy.cos(q0)-sy.cos(q0+q1),0),
            sy.Eq(y-sy.sin(q0)-sy.sin(q0+q1),0)]);
m = s.subs({x:2,y:0})
sol = sy.solve(m,q0,q1,check=False) # get solution without checking

Now check a solution that causes the error

>>> print filldedent(sol[4])

(-I*log(-sqrt(conjugate(RootOf(exp(6*I*q_1) - 10*exp(5*I*q_1) +
15*exp(4*I*q_1) + 4*exp(3*I*q_1) + 47*exp(2*I*q_1) + 6*exp(I*q_1) + 1,
2)))/Abs(RootOf(exp(6*I*q_1) - 10*exp(5*I*q_1) + 15*exp(4*I*q_1) +
4*exp(3*I*q_1) + 47*exp(2*I*q_1) + 6*exp(I*q_1) + 1, 2))),
-I*log(RootOf(exp(6*I*q_1) - 10*exp(5*I*q_1) + 15*exp(4*I*q_1) +
4*exp(3*I*q_1) + 47*exp(2*I*q_1) + 6*exp(I*q_1) + 1, 2)))
>>>
>>> checksol(m,dict(zip((q0,q1),sol[4])))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solvers.py", line 173, in checksol
    check = checksol(fi, sol, **flags)
  File "sympy\solvers\solvers.py", line 202, in checksol
    return numerically_zero(f.subs(sol), 2, prec=None) is not False
  File "sympy\utilities\randtest.py", line 100, in numerically_zero
    n2 = n.n(2, maxn=M)
  File "sympy\core\evalf.py", line 1331, in evalf
    result = evalf(self, prec + 4, options)
  File "sympy\core\evalf.py", line 1225, in evalf
    r = rf(x, prec, options)
  File "sympy\core\evalf.py", line 462, in evalf_add
    terms = [evalf(arg, prec + 10, options) for arg in v.args]
  File "sympy\core\evalf.py", line 1225, in evalf
    r = rf(x, prec, options)
  File "sympy\core\evalf.py", line 503, in evalf_mul
    arg = evalf(arg, prec, options)
  File "sympy\core\evalf.py", line 1225, in evalf
    r = rf(x, prec, options)
  File "sympy\core\evalf.py", line 726, in evalf_trig
    re, im, re_acc, im_acc = evalf(arg, xprec, options)
  File "sympy\core\evalf.py", line 1225, in evalf
    r = rf(x, prec, options)
  File "sympy\core\evalf.py", line 503, in evalf_mul
    arg = evalf(arg, prec, options)
  File "sympy\core\evalf.py", line 1225, in evalf
    r = rf(x, prec, options)
  File "sympy\core\evalf.py", line 773, in evalf_log
    xre, xim, xacc, _ = evalf(arg, workprec, options)
  File "sympy\core\evalf.py", line 1225, in evalf
    r = rf(x, prec, options)
  File "sympy\core\evalf.py", line 503, in evalf_mul
    arg = evalf(arg, prec, options)
  File "sympy\core\evalf.py", line 1225, in evalf
    r = rf(x, prec, options)
  File "sympy\core\evalf.py", line 620, in evalf_pow
    re, im, re_acc, im_acc = evalf(base, prec + 5, options)
  File "sympy\core\evalf.py", line 1225, in evalf
    r = rf(x, prec, options)
  File "sympy\core\evalf.py", line 230, in evalf_abs
    return get_abs(expr.args[0], prec, options)
  File "sympy\core\evalf.py", line 204, in get_abs
    re, im, re_acc, im_acc = evalf(expr, prec + 2, options)
  File "sympy\core\evalf.py", line 1231, in evalf
    re, im = x._eval_evalf(prec).as_real_imag()
  File "sympy\polys\rootoftools.py", line 556, in _eval_evalf
    root = findroot(func, x0)
  File "sympy\mpmath\calculus\optimization.py", line 931, in findroot
    fx = f(x0[0])
  File "<string>", line 1, in <lambda>
  File "sympy\core\expr.py", line 225, in __float__
    raise TypeError("can't convert expression to float")
TypeError: can't convert expression to float
```

**Comment by smichr** [comment]
duplicates #8155
