### ISSUE TITLE
fails in sage -t testing of test_sage.py

### ISSUE THREAD

**Issue by rwst** [sympy/sympy#8585]
In Sage-6.5beta2+sympy-0.7.5:
```
File "local/lib/python2.7/site-packages/sympy/external/tests/test_sage.py", line 175, in sympy.external.tests.test_sage.check_expression
Failed example:
    test_basics()
Exception raised:
    Traceback (most recent call last):
      File "/home/ralf/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 488, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/ralf/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 851, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sympy.external.tests.test_sage.check_expression[0]>", line 1, in <module>
        test_basics()
      File "./test_sage.py", line 69, in test_basics
      File "./test_sage.py", line 46, in check_expression
    AssertionError

sage -t local/lib/python2.7/site-packages/sympy/external/tests/test_sage.py  # 6 doctests failed
```
These fail in the line: `assert not "sin" in a`, so the author assumed that globals are always untouched. But testing with `sage -t` preloads `sage` into globals so the assert triggers.

**Comment by rwst** [comment]
Obsolete with mpmath unbundling.
