### ISSUE TITLE
Euler number of negative integers

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8786]
Currently `euler(-1)`, `euler(-3)`, etc. all evaluate to 0, as the first test in `euler.eval` is

``` python
        if m.is_odd:
            return S.Zero
```

but euler numbers are not defined on negative numbers, so this is wrong (and should probably raise a `ValueError`).

**Comment by czgdp1807** [comment]
Closing this in reference to the following code,
```python
>>> euler(-1)
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/czgdp1807/sympy_project/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/czgdp1807/sympy_project/sympy/sympy/core/function.py", line 473, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/home/czgdp1807/sympy_project/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/czgdp1807/sympy_project/sympy/sympy/core/function.py", line 288, in __new__
    evaluated = cls.eval(*args)
  File "/home/czgdp1807/sympy_project/sympy/sympy/functions/combinatorial/numbers.py", line 1026, in eval
    raise ValueError("Euler numbers are defined only"
ValueError: Euler numbers are defined only for nonnegative integer indices.
```
