### ISSUE TITLE
Inconsistency in errors raised or not raised by comparing non-sets and sets

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8830]
`int <= FiniteSet`
----
```python
>>> 0 <= FiniteSet(1)
```
raises
```pytb
Traceback (most recent call last):
  File "<ipython-input-33-4e173bb81b90>", line 1, in <module>
    0 <= FiniteSet(1)
  File "sympy/sets/sets.py", line 1799, in __ge__
    return other.is_subset(self)
AttributeError: 'int' object has no attribute 'is_subset'
```

`int < FiniteSet`
----
```python
>>> 0 < FiniteSet(1)
```
raises
```pytb
Traceback (most recent call last):
  File "<ipython-input-34-1e18cc8c6ce8>", line 1, in <module>
    0 < FiniteSet(1)
  File "sympy/sets/sets.py", line 1802, in __gt__
    return self.is_proper_superset(other)
  File "sympy/sets/sets.py", line 371, in is_proper_superset
    raise ValueError("Unknown argument '%s'" % other)
ValueError: Unknown argument '0'
```

`Symbol <= FiniteSet`
----
```python
>>> x = Symbol('x', real=True)
>>> x <= FiniteSet(1)
```
raises
```pytb
Traceback (most recent call last):
  File "<ipython-input-43-b4cdf88a3ab9>", line 1, in <module>
    x <= FiniteSet(1)
  File "sympy/core/expr.py", line 256, in __le__
    dif = self - other
  File "sympy/core/decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "sympy/core/decorators.py", line 118, in binary_op_wrapper
    return func(self, other)
  File "sympy/core/expr.py", line 131, in __sub__
    return Add(self, -other)
TypeError: bad operand type for unary -: 'FiniteSet'
```

`One <= FiniteSet`
----
```python
>>> S.One <= FiniteSet(1)
```
raises
```pytb
Traceback (most recent call last):
  File "<ipython-input-51-56fb2542986c>", line 1, in <module>
    S.One <= FiniteSet(1)
  File "sympy/core/numbers.py", line 1745, in __le__
    return Rational.__le__(self, other)
  File "sympy/core/numbers.py", line 1423, in __le__
    return Expr.__le__(expr, other)
  File "sympy/core/expr.py", line 256, in __le__
    dif = self - other
  File "sympy/core/numbers.py", line 1668, in __sub__
    return Rational.__sub__(self, other)
  File "sympy/core/decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "sympy/core/numbers.py", line 1223, in __sub__
    return Number.__sub__(self, other)
  File "sympy/core/decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "sympy/core/numbers.py", line 338, in __sub__
    return AtomicExpr.__sub__(self, other)
  File "sympy/core/decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "sympy/core/decorators.py", line 118, in binary_op_wrapper
    return func(self, other)
  File "sympy/core/expr.py", line 131, in __sub__
    return Add(self, -other)
TypeError: bad operand type for unary -: 'FiniteSet'
```

`int <= Interval`
----
```python
>>> 2 < Interval(2, 3)
True
>>> 7 < Interval(2, 3)
True
```
and these should raise. Same happens with `float < Interval`.

`int <= Set`
----
```python
>>> 2 < Set()
True
```
(same here)

`int <= EmptySet`
----
```python
>>> 2 < EmptySet()
True
```
(same here)

-----

We have to decide what is the error we raise when we compare two non-comparable objects. Perhaps the error should be of the form
```pytb
TypeError: Invalid comparison of ...
```

In addition, in all cases where an error was not raised, I guess it should be raised.

**Comment by oscarbenjamin** [comment]
Some of these examples have changed:
```julia
In [1]: 0 <= FiniteSet(1)                                                                                                                      
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-5db86b192d2c> in <module>
----> 1 0 <= FiniteSet(1)

~/current/sympy/sympy/sympy/sets/sets.py in __ge__(self, other)
   1658     def __ge__(self, other):
   1659         if not isinstance(other, Set):
-> 1660             raise TypeError("Invalid comparison of set with %s" % func_name(other))
   1661         return other.is_subset(self)
   1662 

TypeError: Invalid comparison of set with int

In [2]: 0 < FiniteSet(1)                                                                                                                       
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-b8c5de3cc98f> in <module>
----> 1 0 < FiniteSet(1)

~/current/sympy/sympy/sympy/sets/sets.py in __gt__(self, other)
   1663     def __gt__(self, other):
   1664         if not isinstance(other, Set):
-> 1665             raise TypeError("Invalid comparison of set with %s" % func_name(other))
   1666         return self.is_proper_superset(other)
   1667 

TypeError: Invalid comparison of set with int
```

These are still the same:
```
In [3]: x = Symbol('x', real=True)                                                                                                             

In [4]: x <= FiniteSet(1)                                                                                                                      
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-f0089d96240b> in <module>
----> 1 x <= FiniteSet(1)

~/current/sympy/sympy/sympy/core/expr.py in __le__(self, other)
    321             return _sympify(n2 <= 0)
    322         if self.is_real or other.is_real:
--> 323             dif = self - other
    324             if dif.is_nonpositive is not None and \
    325                     dif.is_nonpositive is not dif.is_positive:

~/current/sympy/sympy/sympy/core/decorators.py in __sympifyit_wrapper(a, b)
     89                 if not hasattr(b, '_op_priority'):
     90                     b = sympify(b, strict=True)
---> 91                 return func(a, b)
     92             except SympifyError:
     93                 return retval

~/current/sympy/sympy/sympy/core/decorators.py in binary_op_wrapper(self, other)
    127                     if f is not None:
    128                         return f(self)
--> 129             return func(self, other)
    130         return binary_op_wrapper
    131     return priority_decorator

~/current/sympy/sympy/sympy/core/expr.py in __sub__(self, other)
    139     @call_highest_priority('__rsub__')
    140     def __sub__(self, other):
--> 141         return Add(self, -other)
    142 
    143     @_sympifyit('other', NotImplemented)

TypeError: bad operand type for unary -: 'FiniteSet'

In [5]: S.One <= FiniteSet(1)                                                                                                                  
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-51d6116012e9> in <module>
----> 1 S.One <= FiniteSet(1)

~/current/sympy/sympy/sympy/core/numbers.py in __le__(self, other)
   2118         if other.is_Integer:
   2119             return _sympify(self.p <= other.p)
-> 2120         return Rational.__le__(self, other)
   2121 
   2122     def __hash__(self):

~/current/sympy/sympy/sympy/core/numbers.py in __le__(self, other)
   1810         elif other.is_number and other.is_real:
   1811             expr, other = Integer(self.p), self.q*other
-> 1812         return Expr.__le__(expr, other)
   1813 
   1814     def __hash__(self):

~/current/sympy/sympy/sympy/core/expr.py in __le__(self, other)
    321             return _sympify(n2 <= 0)
    322         if self.is_real or other.is_real:
--> 323             dif = self - other
    324             if dif.is_nonpositive is not None and \
    325                     dif.is_nonpositive is not dif.is_positive:

~/current/sympy/sympy/sympy/core/numbers.py in __sub__(self, other)
   2024             elif isinstance(other, Rational):
   2025                 return Rational(self.p*other.q - other.p, other.q, 1)
-> 2026             return Rational.__sub__(self, other)
   2027         return Rational.__sub__(self, other)
   2028 

~/current/sympy/sympy/sympy/core/decorators.py in __sympifyit_wrapper(a, b)
     89                 if not hasattr(b, '_op_priority'):
     90                     b = sympify(b, strict=True)
---> 91                 return func(a, b)
     92             except SympifyError:
     93                 return retval

~/current/sympy/sympy/sympy/core/numbers.py in __sub__(self, other)
   1582                 return -other + self
   1583             else:
-> 1584                 return Number.__sub__(self, other)
   1585         return Number.__sub__(self, other)
   1586     @_sympifyit('other', NotImplemented)

~/current/sympy/sympy/sympy/core/decorators.py in __sympifyit_wrapper(a, b)
     89                 if not hasattr(b, '_op_priority'):
     90                     b = sympify(b, strict=True)
---> 91                 return func(a, b)
     92             except SympifyError:
     93                 return retval

~/current/sympy/sympy/sympy/core/numbers.py in __sub__(self, other)
    639             elif other is S.NegativeInfinity:
    640                 return S.Infinity
--> 641         return AtomicExpr.__sub__(self, other)
    642 
    643     @_sympifyit('other', NotImplemented)

~/current/sympy/sympy/sympy/core/decorators.py in __sympifyit_wrapper(a, b)
     89                 if not hasattr(b, '_op_priority'):
     90                     b = sympify(b, strict=True)
---> 91                 return func(a, b)
     92             except SympifyError:
     93                 return retval

~/current/sympy/sympy/sympy/core/decorators.py in binary_op_wrapper(self, other)
    127                     if f is not None:
    128                         return f(self)
--> 129             return func(self, other)
    130         return binary_op_wrapper
    131     return priority_decorator

~/current/sympy/sympy/sympy/core/expr.py in __sub__(self, other)
    139     @call_highest_priority('__rsub__')
    140     def __sub__(self, other):
--> 141         return Add(self, -other)
    142 
    143     @_sympifyit('other', NotImplemented)

TypeError: bad operand type for unary -: 'FiniteSet'
```

These were giving True but are now errors:
```
In [6]: 2 < Interval(2, 3)                                                                                                                     
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-ecfbf0a4823b> in <module>
----> 1 2 < Interval(2, 3)

TypeError: '<' not supported between instances of 'int' and 'Interval'

In [7]: 7 < Interval(2, 3)                                                                                                                     
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-a30487ff6b9c> in <module>
----> 1 7 < Interval(2, 3)

TypeError: '<' not supported between instances of 'int' and 'Interval'

In [8]: 2 < Set()                                                                                                                              
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-9aeb7b45039b> in <module>
----> 1 2 < Set()

TypeError: '<' not supported between instances of 'int' and 'Set'

In [9]: 2 < EmptySet()                                                                                                                         
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-a21fcfe705c8> in <module>
----> 1 2 < EmptySet()

TypeError: '<' not supported between instances of 'int' and 'EmptySet'
```

**Comment by oscarbenjamin** [comment]
The fix here can be
```diff
diff --git a/sympy/sets/sets.py b/sympy/sets/sets.py
index c01edc3571..f6a576da36 100644
--- a/sympy/sets/sets.py
+++ b/sympy/sets/sets.py
@@ -2181,27 +2181,27 @@ def _eval_rewrite_as_PowerSet(self, *args, **kwargs):
                 return None
         return PowerSet(biggest)
 
-    def __ge__(self, other):
+    def __ge__(self, other: Set) -> bool | None:
         if not isinstance(other, Set):
-            raise TypeError("Invalid comparison of set with %s" % func_name(other))
+            return NotImplemented
         return other.is_subset(self)
 
-    def __gt__(self, other):
+    def __gt__(self, other: Set) -> bool | None:
         if not isinstance(other, Set):
-            raise TypeError("Invalid comparison of set with %s" % func_name(other))
+            return NotImplemented
         return self.is_proper_superset(other)
 
-    def __le__(self, other):
+    def __le__(self, other: Set) -> bool | None:
         if not isinstance(other, Set):
-            raise TypeError("Invalid comparison of set with %s" % func_name(other))
+            return NotImplemented
         return self.is_subset(other)
 
-    def __lt__(self, other):
+    def __lt__(self, other: Set) -> bool | None:
         if not isinstance(other, Set):
-            raise TypeError("Invalid comparison of set with %s" % func_name(other))
+            return NotImplemented
         return self.is_proper_subset(other)
 
-    def __eq__(self, other):
+    def __eq__(self, other: object) -> bool:
         if isinstance(other, (set, frozenset)):
             return self._args_set == other
         return super().__eq__(other)
```
Dunder methods like this should return NotImplemented rather than raising an error directly.

**Comment by leastloris** [comment]
@oscarbenjamin I ran tests for following combinations between 
` x = Symbol('x', real=True)`
`A = FiniteSet(1)`
`>>> for name, fn in tests:`
`...     try:`
`...         print(name,": ", fn())`
`...     except Exception as e:`
`...         print(name, ": Exception:", type(e).__name__,e)`

got these results : 

> x < A : Exception: TypeError Invalid comparison of set with Symbol
x <= A : Exception: TypeError Invalid comparison of set with Symbol
x > A : Exception: TypeError Invalid comparison of set with Symbol
x >= A : Exception: TypeError Invalid comparison of set with Symbol
A < x : Exception: TypeError Invalid comparison of set with Symbol
A <= x : Exception: TypeError Invalid comparison of set with Symbol
A > x : Exception: TypeError Invalid comparison of set with Symbol
A >= x : Exception: TypeError Invalid comparison of set with Symbol
x == A :  False
A == x :  False
x != A :  True
A != x :  True

I feel there's an inconsistency within relational (== and !=), is that an issue ?

**Comment by oscarbenjamin** [comment]
> I feel there's an inconsistency within relational (== and !=), is that an issue ?

No. It is generally bad form for `==` or `!=` to raise an exception. They should just evaluate to False for unknown type combinations. This is handled automatically when the `__eq__` and `__ne__` methods return `NotImplemented` or are not defined.
