### ISSUE TITLE
Comparing a symbol with a matrix symbol

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8832]
We don't have any assumption `is_matrix`, neither in the old nor in the new assumptions system. I guess it is like that since we have a different class for these: `MatrixSymbol`, which is not even a subclass of `Symbol`. In this case, I'd expect that one will not be able to compare instances of the classes `Symbol` and `MatrixSymbol`. However,
```python
>>> x = Symbol('x', real=True)
>>> A = MatrixSymbol('A', 2, 3)
>>> x < A
x < A
```
This should probably raise an error instead; which error? This is discussed briefly in #8830.

This also leads to the following error:
```python
>>> solve(x < A)
```
raises
```pytb
Traceback (most recent call last):
  File "<ipython-input-11-59ba69b135ec>", line 1, in <module>
    solve(x<A)
  File "sympy/solvers/solvers.py", line 695, in solve
    return reduce_inequalities(f, symbols=symbols)
  File "sympy/solvers/inequalities.py", line 553, in reduce_inequalities
    i = i.func(i.lhs.as_expr() - i.rhs.as_expr(), 0)
AttributeError: 'MatrixSymbol' object has no attribute 'as_expr'
```

**Comment by mschubert** [comment]
Would it be possible to be consistent with numpy here?

    >>> x = 3
    >>> A = np.array([1,3,2,4]).reshape(2,2)
    >>> x < A
    array([[False, False],
           [False,  True]], dtype=bool)

Obviously, sympy can't reduce an operation between a `MatrixSymbol` and a scalar to a boolean matrix, but:
 * Treating an operation between a matrix and a scalar as a scalar operation to each element of the matrix greatly increases readability of code
 * This is standard practice in numerical libraries (numpy, R, etc.)
 * There is no danger of performing the wrong operation, since an element-wise comparison as what is expected intuitively (at least for me - I assume for most others as well)
