### ISSUE TITLE
Comparing matrices

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8833]
The following is rather unexpected:
```python
>>> A = MatrixSymbol('A', 2, 3)
>>> B = MatrixSymbol('B', 2, 3)
>>> A < B
True
>>> A > B
False
```

I guess that this is so as `MatrixSymbol` does not define comparison methods?

**Comment by mschubert** [comment]
This is also true for scalar comparisons:

```python
>>> A = MatrixSymbol('A', 2, 3)
>>> A < 1
False
>>> A > 1
True
```

Now, this could throw an error but I would advocate for element-wise comparisons with the `>` and `<` operators (as in #8832).

**Comment by oscarbenjamin** [comment]
This seems to have changed:
```
>>> A = MatrixSymbol('A', 2, 3)
>>> B = MatrixSymbol('B', 2, 3)
>>> A<B
A < B
>>> A>B
A > B
```
I don't think that's meaningful though. What would it mean if the matrices were explicit?

The scalar example now raises an error:
```
>>> A<1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/core/expr.py", line 365, in __lt__
    dif = self - other
  File "/Users/enojb/current/sympy/sympy/sympy/matrices/expressions/matexpr.py", line 24, in __sympifyit_wrapper
    return func(a, b)
  File "/Users/enojb/current/sympy/sympy/sympy/core/decorators.py", line 129, in binary_op_wrapper
    return func(self, other)
  File "/Users/enojb/current/sympy/sympy/sympy/matrices/expressions/matexpr.py", line 97, in __sub__
    return MatAdd(self, -other, check=True).doit()
  File "/Users/enojb/current/sympy/sympy/sympy/matrices/expressions/matadd.py", line 49, in __new__
    validate(*args)
  File "/Users/enojb/current/sympy/sympy/sympy/matrices/expressions/matadd.py", line 84, in validate
    raise TypeError("Mix of Matrix and Scalar symbols")
TypeError: Mix of Matrix and Scalar symbols
```
