### ISSUE TITLE
Symbol subs Vector exception

### ISSUE THREAD

**Issue by huwpascoe** [sympy/sympy#8886]
```
A = ReferenceFrame('A')
v = A.x
s, t = symbols('s t')
```

```(s / t)```
output: s / t

```(v / t)```
output: 1/t n̂x 

```(s / t).subs(s, v)```
output:
```
anaconda3/lib/python3.4/site-packages/sympy/parsing/sympy_parser.py in eval_expr(code, local_dict, global_dict)
    689     """
    690     expr = eval(
--> 691         code, global_dict, local_dict)  # take local objects in preference
    692 
    693     return expr

<string> in <module>()

AttributeError: 'function' object has no attribute 'x'
```

**Comment by moorepants** [comment]
Which vector is this from? `sympy/vector` or `sympy/physics/vector`?

**Comment by moorepants** [comment]
I'm not sure this *should* work. Why should you be able substitute a vector in for a scalar? It doesn't make sense mathematically.

**Comment by huwpascoe** [comment]
It's from physics

**Comment by moorepants** [comment]
I don't think this should be supported. It is not mathematically correct to substitute scalars for vectors or vice versa. If you can prove why this should be allowed, then we can reconsider.

**Comment by moorepants** [comment]
I'm willing to provide a better error message for the `.subs()` method, saying that this isn't supported.

**Comment by huwpascoe** [comment]
I don't know if it should be allowed but better error messages are very welcome, thanks!

**Comment by moorepants** [comment]
See #8892.

**Comment by smichr** [comment]
> If you can prove why this should be allowed, then we can reconsider

I know this is old but there is an active PR at #10528: isn't the OP reason enough to support it? `foo/t` is defined for `foo in [s, v]` so `(foo/t).subs(foo, v)` should give `v/t`, shouldn't it? If you look at more of the error message you will see that the reason for the error is that Vector doesn't derive from Basic and is not in sympy_classes. If you read the `sympify` code you will find,

```
    try:
        return a._sympy_()
    except AttributeError:
        pass

    if not isinstance(a, string_types):
        for coerce in (float, int):
            try:
                return sympify(coerce(a))
            except (TypeError, ValueError, AttributeError, SympifyError):
                continue

    if strict:
        raise SympifyError(a)

    if iterable(a):
        try:
            return type(a)([sympify(x, locals=locals, convert_xor=convert_xor,
                rational=rational) for x in a])
        except TypeError:
            # Not all iterables are rebuildable with their type.
            pass
    if isinstance(a, dict):
        try:
            return type(a)([sympify(x, locals=locals, convert_xor=convert_xor,
                rational=rational) for x in a.items()])
        except TypeError:
            # Not all iterables are rebuildable with their type.
            pass

    # At this point we were given an arbitrary expression
    # which does not inherit from Basic and doesn't implement
    # _sympy_ (which is a canonical and robust way to convert  <--- this
    # anything to SymPy expression).
    #
    # As a last chance, we try to take "a"'s normal form via unicode()
    # and try to parse it. If it fails, then we have no luck and
    # return an exception
```

So it seems the simplest way to make this work is to just define a `_sympy_` routine for Vector that returns the Vector (and do the same for any mechanics quantities).

Doing so brings one to the next issue:

```python
>>> def _sympy_(self):
...     return self
...
>>> Vector._sympy_ = _sympy_
>>> eq.subs(foo, v)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\core\basic.py", line 902, in subs
    rv = rv._subs(old, new, **kwargs)
  File "sympy\core\cache.py", line 95, in wrapper
    retval = func(*args, **kwargs)
  File "sympy\core\basic.py", line 1016, in _subs
    rv = fallback(self, old, new)
  File "sympy\core\basic.py", line 989, in fallback
    if not _aresame(arg, args[i]):
  File "sympy\core\basic.py", line 1676, in _aresame
    if i != j or type(i) != type(j):
  File "sympy\physics\vector\vector.py", line 171, in __ne__
    return not self.__eq__(other)
  File "sympy\physics\vector\vector.py", line 131, in __eq__
    other = _check_vector(other)
  File "sympy\physics\vector\vector.py", line 680, in _check_vector
    raise TypeError('A Vector must be supplied')
TypeError: A Vector must be supplied
```

`_check_vector` is used in places where something must be a vector to proceed with the computation; in this case it is not needed for an equality check: it should just return False if `other` is not a Vector.

Doing so raises the next error:

```python
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "sympy\core\basic.py", line 902, in subs
    rv = rv._subs(old, new, **kwargs)
  File "sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy\core\compatibility.py", line 898, in wrapper
    result = user_function(*args, **kwds)
  File "sympy\core\basic.py", line 1016, in _subs
    rv = fallback(self, old, new)
  File "sympy\core\basic.py", line 993, in fallback
    rv = self.func(*args)
  File "sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy\core\compatibility.py", line 898, in wrapper
    result = user_function(*args, **kwds)
  File "sympy\core\operations.py", line 41, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "sympy\core\mul.py", line 181, in flatten
    if not a.is_zero and a.is_Rational:
AttributeError: 'Vector' object has no attribute 'is_zero'
```

So although `v/t` is probably handled with an `__rmul__` routine, `1/t*v` is not handled (or something like that) because:

```
>>> v/t
1/t*A.x
>>> 1/t*v
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\core\decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "sympy\core\decorators.py", line 118, in binary_op_wrapper
    return func(self, other)
  File "sympy\core\expr.py", line 141, in __mul__
    return Mul(self, other)
  File "sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy\core\compatibility.py", line 898, in wrapper
    result = user_function(*args, **kwds)
  File "sympy\core\operations.py", line 41, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "sympy\core\mul.py", line 178, in flatten
    if b.is_Rational:
AttributeError: 'Vector' object has no attribute 'is_Rational'
>>>
```

And I'm not sure what the best thing to do there is. Perhaps `__mul__` (or `__rmul__`) routines are needed (and others as well) so Vector plays better with others. e.g.

```python
>>> 2*v/t
2/t*A.x
>>> S(2)*v/t
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\core\numbers.py", line 1836, in __mul__
    return Rational.__mul__(self, other)
  File "sympy\core\decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "sympy\core\numbers.py", line 1396, in __mul__
    return Number.__mul__(self, other)
  File "sympy\core\decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "sympy\core\numbers.py", line 475, in __mul__
    return AtomicExpr.__mul__(self, other)
  File "sympy\core\decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "sympy\core\decorators.py", line 118, in binary_op_wrapper
    return func(self, other)
  File "sympy\core\expr.py", line 141, in __mul__
    return Mul(self, other)
  File "sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "sympy\core\compatibility.py", line 898, in wrapper
    result = user_function(*args, **kwds)
  File "sympy\core\operations.py", line 41, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "sympy\core\mul.py", line 178, in flatten
    if b.is_Rational:
AttributeError: 'Vector' object has no attribute 'is_Rational'
```
