### ISSUE TITLE
using nsolve to solve equations with radicals

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#8933]
When using nsolve to find the roots is that sometimes it needs a small imaginary component in the initial guess to find the root.

```
>>> expr1 = root(x, 3)*root(-1, 3)**2 - root(x, 5)*root(-1, 5)**2
>>> v = expr1.subs(x, -3)
>>> eq=expr1-v
>>> eq.subs(x,-3)
0
>>> nsolve(eq, -3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy\solvers\solvers.py", line 2691, in nsolve
    return findroot(f, x0, **kwargs)
  File "c:\Python26\lib\site-packages\mpmath\calculus\optimization.py", line 975
, in findroot
    % (norm(f(*xl))**2, tol))
ValueError: Could not find root within given tolerance. (581.199 > 2.1684e-19)
Try another starting point or tweak arguments.
>>> nsolve(eq, -3+.01j)
Traceback (most recent call last):
...
ValueError: Could not find root within given tolerance. (3.48915 > 2.1684e-19)
Try another starting point or tweak arguments.
>>> nsolve(eq, -3+.001j)
Traceback (most recent call last):
...
ValueError: Could not find root within given tolerance. (3.48915 > 2.1684e-19)
Try another starting point or tweak arguments.
>>> nsolve(eq, -3+.0001j)
mpc(real='-2.9999999999998855', imag='1.4631617279617564e-13')
>>>
```

Also, the solver='bisect' sometimes will generate an imaginary part to the number and not be able to continue. (So either a different solver must be employed or the non-mpmath bisection routine, bisect in sympy.polys.rootoftools can be tried.)

**Comment by oscarbenjamin** [comment]
The original example works fine now without any imaginary component:
```
In [2]: nsolve(eq, -3)                                                                                                                                        
Out[2]: -3.0 + 8.37935899515899e-22⋅ⅈ
```
