### ISSUE TITLE
BUG/DOC: Trig Functions "cannot create mpf from..." depending on namespace

### ISSUE THREAD

**Issue by jnmclarty** [sympy/sympy#9045]
I'm brand new to sympy, but either I found a bug (doubt it), or the docs need updating (more likely).

This works:
```
>>> from sympy import symbols, cos
>>> x = symbols('x')
>>> cos(x)
cos(x)
```

But, as mentioned in the [latest docs](http://docs.sympy.org/latest/modules/mpmath/functions/trigonometric.html):
```
>>> from sympy.mpmath import cos
>>> cos(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\WinPython-32bit-2.7.9.2-20150202\python-2.7.9\lib\site-packages\sympy\mpmath\ctx_mp_python.py", line 984, in f
    x = ctx.convert(x)
  File "C:\WinPython-32bit-2.7.9.2-20150202\python-2.7.9\lib\site-packages\sympy\mpmath\ctx_mp_python.py", line 662, in convert
    return ctx._convert_fallback(x, strings)
  File "C:\WinPython-32bit-2.7.9.2-20150202\python-2.7.9\lib\site-packages\sympy\mpmath\ctx_mp.py", line 614, in _convert_fallback
    raise TypeError("cannot create mpf from " + repr(x))
TypeError: cannot create mpf from x
```

I can likely find time to do a PR, assuming it's just doc strings's import statements, in ```mpmath\ctx_mp.py``` that need tweaking.

**Comment by oscarbenjamin** [comment]
I think the mpmath cos function is just for float evaluations and has no symbolic capability. That seems to be what the error message is telling you. As you noted sympy.cos is there with all the symbolic capability.

What exactly needs fixing here?

**Comment by csbrown** [comment]
I am running into this error when trying to `nsolve` a trigonometric equation.

e.g. 

    x = Symbol('x')
    nsolve(cos(x), x)

Is there a workaround for this?

**Comment by oscarbenjamin** [comment]
The docs page here should be updated:
https://docs.sympy.org/latest/install.html#mpmath

The file doc/src/install.md could do with a bit of a rewrite. It is very out of date. All reference to sympy.mpmath should be removed. It is probably not necessary to say much at all about mpmath because modern Python installers can install dependencies automatically.
