### ISSUE TITLE
log(0, n) for n > 2 hits endless recursion

### ISSUE THREAD

**Issue by bnjones** [sympy/sympy#9066]
Steps to reproduce:

```
>>> import sympy
>>> sympy.log(0, 2)
zoo
>>> sympy.log(0, 3)
Traceback (most recent call last):
[...]
  File "/home/ben/src/sympy-virtualenv/local/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/ntheory/factor_.py", line 257, in multiplicity
    return m + multiplicity(p, n)
  File "/home/ben/src/sympy-virtualenv/local/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/ntheory/factor_.py", line 257, in multiplicity
    return m + multiplicity(p, n)
  File "/home/ben/src/sympy-virtualenv/local/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/ntheory/factor_.py", line 209, in multiplicity
    p, n = as_int(p), as_int(n)
  File "/home/ben/src/sympy-virtualenv/local/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/core/compatibility.py", line 384, in as_int
    result = int(n)
```

I originally found this in 0.7.3, but it looks like it's also reproducible in 0.7.6.

**Comment by leosartaj** [comment]
This is getting caused due to infinite recursion in multiplicty(base, arg) on line 473 in sympy.functions.elementary.exponential. Bug can be solved by either defining what multiplicity(base, 0) should return or either applying a simple check before computing multiplicity.

**Comment by Sumith1896** [comment]
The above PR should fix the issue.

**Comment by slayah** [comment]
Is this issue resolved then?

**Comment by aktech** [comment]
> Is this issue resolved then?
No, It's not.
See the PR for current status.
