### ISSUE TITLE
Basic vector fails with maximum recursion depth exceeded

### ISSUE THREAD

**Issue by cjermain** [sympy/sympy#9159]
When trying out `sympy.physics.vector` for the first time on SymPy live [following the tutorial](http://docs.sympy.org/0.7.5/modules/physics/vector/vectors.html#using-vectors-and-reference-frames), I immediately ran into an error. Any suggestions?

```python
>>> from sympy.physics.vector import *
>>> N = ReferenceFrame('N')
>>> N.x
Exception in SymPy Live of type 
<type 'exceptions.RuntimeError'>
for reference the last 5 stack trace entries are 
Traceback (most recent call last): 
File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/shell.py", line 773, in post
    live.evaluate(statement, session, printer, stream) 
File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/shell.py", line 480, in evaluate
    session.set_global('_', val) 
File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/shell.py", line 537, in set_global 
    blob = db.Blob(self.fast_dumps(value, 1)) 
File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/shell.py", line 603, in fast_dumps
    p.dump(obj) 
File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj) RuntimeError: maximum recursion depth exceeded 
```

**Comment by moorepants** [comment]
The primary objects in sympy.physics.vector are not picklable, unfortunately. See https://github.com/sympy/sympy/issues/6668

You can try out the new sympy.vector package that should work on SymPy live.

**Comment by cjermain** [comment]
Thanks!
