### ISSUE TITLE
Bug : Multiplication between MatrixSymbol and Matrix

### ISSUE THREAD

**Issue by truongduy134** [sympy/sympy#9330]
A matrix A and a MatrixSymbol B are defined as follows:
```
>>> from sympy import *
>>> q = MatrixSymbol('q', 4, 1)
>>> A = Matrix([[q[0,0], 1, 2], [q[1,0], 2, 3], [q[2,0], 3, 4]])
>>> B = MatrixSymbol('B', 3, 3)
```
The behavior is different for A * B and B * A. The operation A * B succeeds:
```
>>> A * B
Matrix([
[q[0, 0], 1, 2],
[q[1, 0], 2, 3],
[q[2, 0], 3, 4]])*B
```
However, B * A crashes:
```
>>> B * A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/matrices/expressions/matexpr.py", line 21, in __sympifyit_wrapper
    return func(a, b)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/core/decorators.py", line 118, in binary_op_wrapper
    return func(self, other)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/matrices/expressions/matexpr.py", line 101, in __mul__
    return MatMul(self, other).doit()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/matrices/expressions/matmul.py", line 112, in doit
    return canonicalize(MatMul(*args))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/strategies/core.py", line 11, in exhaustive_rl
    new, old = rule(expr), expr
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/strategies/core.py", line 95, in switch_rl
    return rl(expr)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/strategies/core.py", line 85, in do_one_rl
    result = rl(expr)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/matrices/expressions/matmul.py", line 183, in xxinv
    if X.is_square and Y.is_square and X == Y.inverse():
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/matrices/expressions/matexpr.py", line 194, in inverse
    return self._eval_inverse()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/matrices/dense.py", line 307, in _eval_inverse
    rv = M.inverse_GE(iszerofunc=iszerofunc)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/matrices/matrices.py", line 2621, in inverse_GE
    red = big.rref(iszerofunc=iszerofunc, simplify=True)[0]
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/matrices/matrices.py", line 2679, in rref
    r[pivot, i] = simpfunc(r[pivot, i])
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/simplify/simplify.py", line 3700, in simplify
    expr2 = shorter(together(expr, deep=True), together(expr1, deep=True))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/simplify/simplify.py", line 3694, in shorter
    return min(choices, key=measure)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sympy-0.7.6_git-py2.7.egg/sympy/core/function.py", line 2290, in count_ops
    if a.is_Rational:
AttributeError: 'str' object has no attribute 'is_Rational'
```

The cause of the crash is related to issue https://github.com/sympy/sympy/issues/9324

Can we make the behavior of MatrixSymbol * Matrix same as Matrix * MatrixSymbol ? (Since multiplication is supposed to be commutative)

**Comment by debugger22** [comment]
Probably duplicate of https://github.com/sympy/sympy/issues/9324

**Comment by gxyd** [comment]
Has this bug been fixed ? To me it seems fixed.

**Comment by truongduy134** [comment]
@gxyd : This has been fixed thanks to https://github.com/sympy/sympy/pull/9392 . However, the behavior of ```Matrix * MatrixSymbol``` and ```MatrixSymbol * Matrix``` are still different. In the case of ```MatrixSymbol * Matrix```, simplification is performed, while it is not in ```Matrix * MatrixSymbol```. Is it OK to ignore this difference in the behavior of the two equivalent expressions?

**Comment by gxyd** [comment]
@truongduy134  I guess this simplification you are talking about ? I get this on my machine.
```
>>> L1 = A*B
>>> L2 = B*A
>>> L1[0, 0]
B1,0+2B2,0+q0,0B0,0
>>> L2[0, 0]
B0,0q0,0+B0,1q1,0+B0,2q2,0
```

**Comment by truongduy134** [comment]
@gxyd : Oh, nvm. I guess there is no more problem with multiplication. I think we can close this issue :D

**Comment by gxyd** [comment]
Probably this issue can be closed.

**Comment by truongduy134** [comment]
Close this issue for now :)
