### ISSUE TITLE
lambdify behaves differently with module or module name inputs

### ISSUE THREAD

**Issue by perimosocordiae** [sympy/sympy#9338]
Here's a small test case that illustrates the problem:

```
import numpy as np
from sympy.abc import a
from sympy.utilities.lambdify import lambdify

expr = abs(a)

func_numpy_name = lambdify((a,), expr, modules=['numpy'])
func_numpy_mod = lambdify((a,), expr, modules=[np])

x = np.array([-1, 2])
print func_numpy_name(x)
print func_numpy_mod(x)
```

The output is:

```
[1 2]
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    print func_numpy_mod(x)
  File "<string>", line 1, in <lambda>
NameError: global name 'Abs' is not defined
```

The function created using `modules=['numpy']` works fine, while the function created with `modules=[np]` fails. This may be related to #9334, but I'm not sure.

**Comment by perimosocordiae** [comment]
A closer reading of the docs shows:

```
Attention: There are naming differences between numpy and sympy. So if
                   you simply take the numpy module, e.g. sympy.atan will not be
                   translated to numpy.arctan. Use the modified module instead
                   by passing the string "numpy"
```

So, this may not be a bug, but it was still surprising when I encountered it. Perhaps a warning could be emitted if the user provides the actual numpy module instead of the string 'numpy'.

**Comment by moorepants** [comment]
`lambdify` is setup to take any module, i.e. you can create your own module with custom numerical functions and pass them in. Fixing issue #9339 may be the best option here to keep things general.
