### ISSUE TITLE
factor_list(sqrt(2)) raises exception

### ISSUE THREAD

**Issue by jwgarber** [sympy/sympy#9427]
With Sympy 0.7.6 and Python 3.4.3

```
>>> factor_list(sqrt(2))
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/sympy/polys/polytools.py", line 4100, in _poly_from_expr
    rep, opt = _dict_from_expr(expr, opt)
  File "/usr/local/lib/python3.4/site-packages/sympy/polys/polyutils.py", line 332, in _dict_from_expr
    rep, gens = _dict_from_expr_no_gens(expr, opt)
  File "/usr/local/lib/python3.4/site-packages/sympy/polys/polyutils.py", line 277, in _dict_from_expr_no_gens
    (poly,), gens = _parallel_dict_from_expr_no_gens((expr,), opt)
  File "/usr/local/lib/python3.4/site-packages/sympy/polys/polyutils.py", line 238, in _parallel_dict_from_expr_no_gens
    raise GeneratorsNeeded("specify generators to give %s a meaning" % arg)
sympy.polys.polyerrors.GeneratorsNeeded: specify generators to give 2 a meaning

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/sympy/polys/polytools.py", line 5889, in factor_list
    return _generic_factor_list(f, gens, args, method='factor')
  File "/usr/local/lib/python3.4/site-packages/sympy/polys/polytools.py", line 5634, in _generic_factor_list
    f, _ = _poly_from_expr(f, _opt)
  File "/usr/local/lib/python3.4/site-packages/sympy/polys/polytools.py", line 4102, in _poly_from_expr
    raise PolificationFailed(opt, orig, expr)
sympy.polys.polyerrors.PolificationFailed: can't construct a polynomial from 2
```

`factor` works fine on the other hand.

```
>>> factor(sqrt(2))
sqrt(2)
```

**Comment by oscarbenjamin** [comment]
Seems to work fine now:
```
In [15]: factor_list(sqrt(2))                                                                                                                  
Out[15]: (√2, [])

In [16]: factor(sqrt(2))                                                                                                                       
Out[16]: √2
```

**Comment by jwgarber** [comment]
I think we can close it then.
