### ISSUE TITLE
simplify throws ValueError

### ISSUE THREAD

**Issue by x-or** [sympy/sympy#9448]
SymPy 0.7.6 fails:
```
>>> import sympy as sy
>>> a = sy.sympify("1/(1 - (-1)**(2/3) - (-1)**(1/3)) + 1/(1 + (-1)**(2/3) + (-1)**(1/3))")
>>> a.simplify()

Traceback (most recent call last):
  File "issue.py", line 3, in <module>
    a.simplify()
  File "C:\Python27\lib\site-packages\sympy\core\expr.py", line 2922, in simplify
    return simplify(self, ratio, measure)
  File "C:\Python27\lib\site-packages\sympy\simplify\simplify.py", line 3762, in simplify
    n, d = fraction(radsimp(1/denom, symbolic=False, max_terms=1))
  File "C:\Python27\lib\site-packages\sympy\simplify\simplify.py", line 2026, in radsimp
    n, d = fraction(handle(expr))
  File "C:\Python27\lib\site-packages\sympy\simplify\simplify.py", line 1969, in handle
    if _d.is_Number and _d.equals(d):
  File "C:\Python27\lib\site-packages\sympy\core\expr.py", line 636, in equals
    for si in sol):
  File "C:\Python27\lib\site-packages\sympy\core\expr.py", line 636, in <genexpr>
    for si in sol):
  File "C:\Python27\lib\site-packages\sympy\simplify\simplify.py", line 3881, in nsimplify
    raise ValueError("constants must be real-valued")
ValueError: constants must be real-valued
```

**Comment by wanglongqi** [comment]
`nsimplify` is called with a complex number in `constants` argument. [This line](https://github.com/sympy/sympy/blob/master/sympy/core/expr.py#L658) does not handle the case, in which `s` is complex.

**Comment by wanglongqi** [comment]
If this is the case, I proposed a small patch for this case.

**Comment by leosartaj** [comment]
This issue should be closed. @hargup

**Comment by hargup** [comment]
@leosartaj Thanks!
