### ISSUE TITLE
Python 3.4.4: TypeError: unorderable types: NoneType() > NoneType()

### ISSUE THREAD

**Issue by AndrewUshakov** [sympy/sympy#9464]
Hi!

Using 64-bit Python 3.4.3 and sympy 0.7.6 program below:

``` python
import sympy
import sympy.tensor

x = sympy.Symbol('x')
n = sympy.Symbol('n')
A = sympy.tensor.IndexedBase('A')
solution = sympy.Sum(A[n]*sympy.chebyshevt(n, x), (n, 0, 5))
solution = solution.doit()

solution = solution.expand()    # <--- crashes here
print(solution)
```

crashes at line 10 with diagnostics:

```
Traceback (most recent call last):
  File "H:/My Documents/PyCharm/Film_Instability/sym_test.py", line 10, in <module>
    solution = solution.expand()
  File "C:\Program Files\Python34\lib\site-packages\sympy\core\cache.py", line 93, in wrapper
    retval = func(*args, **kwargs)
  File "C:\Program Files\Python34\lib\site-packages\sympy\core\expr.py", line 2871, in expand
    expr, hit = Expr._expand_hint(expr, hint, deep=deep, **hints)
  File "C:\Program Files\Python34\lib\site-packages\sympy\core\expr.py", line 2809, in _expand_hint
    expr = expr.func(*sargs)
  File "C:\Program Files\Python34\lib\site-packages\sympy\core\cache.py", line 93, in wrapper
    retval = func(*args, **kwargs)
  File "C:\Program Files\Python34\lib\site-packages\sympy\core\operations.py", line 41, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "C:\Program Files\Python34\lib\site-packages\sympy\core\add.py", line 257, in flatten
    _addsort(newseq)
  File "C:\Program Files\Python34\lib\site-packages\sympy\core\add.py", line 19, in _addsort
    args.sort(key=_args_sortkey)
  File "C:\Program Files\Python34\lib\site-packages\sympy\core\basic.py", line 190, in compare
    c = l.compare(r)
  File "C:\Program Files\Python34\lib\site-packages\sympy\core\basic.py", line 192, in compare
    c = (l > r) - (l < r)
TypeError: unorderable types: NoneType() > NoneType()
```

Debug confirmes that in this point l and r variables are both None, which produces error in Python 3.4.3. Error can be corrected by adding 2 lines after line 190 in \sympy\core\basic.py.

Here it is original code:

``` python
            if isinstance(l, Basic):
                c = l.compare(r)
            else:
                c = (l > r) - (l < r)  # <--- Error here
            if c:
                return c
```

Here is modified:

``` python
            if isinstance(l, Basic):
                c = l.compare(r)
            elif l is None or r is None:                     # <--- insert
                c = (l is not None) - (r is not None)        # <--- insert
            else:
                c = (l > r) - (l < r)
            if c:
                return c
```

**Comment by ThomasA** [comment]
I have just experienced this error in Python 3.4.3 (64 bit, Linux). In my case it involves trying to `simplify` a coefficient of a polynomial involving symbols created via `sympy.tensor.IndexedBase`. The same code does not produce the error in Python 2.7.10.

Please let me know if you need more details?

**Comment by jksuom** [comment]
Objects of ``IndexedBase`` are modified by ``doit()`` which makes their comparisons unreliable.
```
Python 3.4.3 (default, Sep  8 2015, 18:35:06) 
[GCC 4.6.3] on linux

>>> import sympy
>>> import sympy.tensor
>>> A = sympy.tensor.IndexedBase('A')
>>> A.compare(A.doit())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jks/test/sympy/sympy/core/basic.py", line 193, in compare
    c = (l > r) - (l < r)
TypeError: unorderable types: NoneType() > NoneType()
>>> A[0].doit().compare(A[1].doit())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jks/test/sympy/sympy/core/basic.py", line 191, in compare
    c = l.compare(r)
  File "/home/jks/test/sympy/sympy/core/basic.py", line 193, in compare
    c = (l > r) - (l < r)
TypeError: unorderable types: NoneType() > NoneType()
```
Looking at the code it is not hard to see what is happening in ``A.compare(A.doit())``.
```
(1)    if self is other:
            return 0
        n1 = self.__class__
        n2 = other.__class__
        c = (n1 > n2) - (n1 < n2)
        if c:
            return c
        #
(2)     st = self._hashable_content()
        ot = other._hashable_content()
        c = (len(st) > len(ot)) - (len(st) < len(ot))
        if c:
            return c
        for l, r in zip(st, ot):
            l = Basic(*l) if isinstance(l, frozenset) else l
            r = Basic(*r) if isinstance(r, frozenset) else r
            if isinstance(l, Basic):
                c = l.compare(r)
            else:
(3)             c = (l > r) - (l < r)
            if c:
                return c
        return 0
```
1) Objects are different.
```
>>> A is A.doit()
False
```
2) Hashable content includes ``None``.
```
>>> A._hashable_content()
(A, None)
```
3) Two ``None``s are compared. Python2 returns 0, but Python3 raises an exception.

Issue 1) can probably be fixed by making ``IndexedBase`` a subclass of ``AtomicExpr`` instead of plain ``Expr``.

Hashable content includes ``None`` when no ``_shape`` has been set. The ``_shape`` part should probably be included only if it is not ``None``.

**Comment by jksuom** [comment]
This is probably not hard to fix. If there is no shape in an instance of ``IndexedBase`` (i.e. ``self._shape`` is None), then `` + (self._shape,)`` should be omitted from ``IndexedBase._hashable_content`` (in the same way as in ``IndexedBase.args``).

The result should be tested with Python 3.

**Comment by jksuom** [comment]
This was fixed implicitly by https://github.com/sympy/sympy/pull/9758. Closing.
