### ISSUE TITLE
Fail in plot_implicit test on OSX 10.8.5

### ISSUE THREAD

**Issue by proteasome** [sympy/sympy#9652]
Sat Jul 11 13:55:27 EDT 2015```
└─╼ ./setup.py test
/Users/enzyme/anaconda/envs/sympy/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py:285: UserWarning: Normalizing '0.7.7.dev' to '0.7.7.dev0'
running test
============================= test process starts ==============================
executable:         /Users/enzyme/anaconda/envs/sympy/bin/python  (2.7.10-final-0) [CPython]
architecture:       64-bit
cache:              yes
ground types:       python 
random seed:        1582984
hash randomization: on (PYTHONHASHSEED=2446129600)```

``` sympy/plotting/tests/test_plot.py[3] ./Users/enzyme/anaconda/envs/sympy/lib/python2.7/site-packages/matplotlib/pyplot.py:424: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)
sympy/plotting/experimental_lambdify.py:165: UserWarning: The evaluation of the expression is problematic. We are trying a failback method that may still work. Please report this as a bug.
  warnings.warn('The evaluation of the expression is'
..                                    [OK]
sympy/plotting/tests/test_plot_implicit.py[2] .E                          [FAIL]  ```

```________________________________________________________________________________
__________ sympy/plotting/tests/test_plot_implicit.py:test_matplotlib __________
  File "/users/enzyme/mystuff/mypython/mysympy/sympy-sprint/sympy/sympy/plotting/tests/test_plot_implicit.py", line 70, in test_matplotlib
    plot_and_save('test')
  File "/users/enzyme/mystuff/mypython/mysympy/sympy-sprint/sympy/sympy/plotting/tests/test_plot_implicit.py", line 22, in plot_and_save
    plot_implicit(Eq(y, cos(x)), (x, -5, 5), (y, -2, 2)).save(tmp_file(name))
  File "sympy/plotting/plot_implicit.py", line 374, in plot_implicit
    p.show()
  File "sympy/plotting/plot.py", line 185, in show
    self._backend.show()
  File "sympy/plotting/plot.py", line 1018, in show
    self.process_series()
  File "sympy/plotting/plot.py", line 921, in process_series
    points = s.get_raster()
  File "sympy/plotting/plot_implicit.py", line 80, in get_raster
    temp = func(xinterval, yinterval)
  File "<string>", line 1, in <lambda>
NameError: global name 'Eq' is not defined
```________________________________________________________________________________
__________________ sympy.plotting.plot_implicit.plot_implicit __________________
File "sympy/plotting/plot_implicit.py", line 257, in sympy.plotting.plot_implicit.plot_implicit
Failed example:
    p1 = plot_implicit(Eq(x**2 + y**2, 5))
Exception raised:
    Traceback (most recent call last):
      File "/Users/enzyme/anaconda/envs/sympy/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest sympy.plotting.plot_implicit.plot_implicit[2]>", line 1, in <module>
        p1 = plot_implicit(Eq(x**2 + y**2, 5))
      File "sympy/plotting/plot_implicit.py", line 374, in plot_implicit
        p.show()
      File "sympy/plotting/plot.py", line 185, in show
        self._backend.show()
      File "sympy/plotting/plot.py", line 1018, in show
        self.process_series()
      File "sympy/plotting/plot.py", line 921, in process_series
        points = s.get_raster()
      File "sympy/plotting/plot_implicit.py", line 80, in get_raster
        temp = func(xinterval, yinterval)
      File "<string>", line 1, in <lambda>
    NameError: global name 'Eq' is not defined
**********************************************************************
File "sympy/plotting/plot_implicit.py", line 261, in sympy.plotting.plot_implicit.plot_implicit
Failed example:
    p2 = plot_implicit(Eq(x**2 + y**2, 3),
            (x, -3, 3), (y, -3, 3))
Exception raised:
    Traceback (most recent call last):
      File "/Users/enzyme/anaconda/envs/sympy/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest sympy.plotting.plot_implicit.plot_implicit[3]>", line 2, in <module>
        (x, -3, 3), (y, -3, 3))
      File "sympy/plotting/plot_implicit.py", line 374, in plot_implicit
        p.show()
      File "sympy/plotting/plot.py", line 185, in show
        self._backend.show()
      File "sympy/plotting/plot.py", line 1018, in show
        self.process_series()
      File "sympy/plotting/plot.py", line 921, in process_series
        points = s.get_raster()
      File "sympy/plotting/plot_implicit.py", line 80, in get_raster
        temp = func(xinterval, yinterval)
      File "<string>", line 1, in <lambda>
    NameError: global name 'Eq' is not defined
**********************************************************************
File "sympy/plotting/plot_implicit.py", line 266, in sympy.plotting.plot_implicit.plot_implicit
Failed example:
    p3 = plot_implicit(Eq(x**2 + y**2, 5),
            (x, -4, 4), (y, -4, 4), depth = 2)
Exception raised:
    Traceback (most recent call last):
      File "/Users/enzyme/anaconda/envs/sympy/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest sympy.plotting.plot_implicit.plot_implicit[4]>", line 2, in <module>
        (x, -4, 4), (y, -4, 4), depth = 2)
      File "sympy/plotting/plot_implicit.py", line 374, in plot_implicit
        p.show()
      File "sympy/plotting/plot.py", line 185, in show
        self._backend.show()
      File "sympy/plotting/plot.py", line 1018, in show
        self.process_series()
      File "sympy/plotting/plot.py", line 921, in process_series
        points = s.get_raster()
      File "sympy/plotting/plot_implicit.py", line 80, in get_raster
        temp = func(xinterval, yinterval)
      File "<string>", line 1, in <lambda>
    NameError: global name 'Eq' is not defined
**********************************************************************
File "sympy/plotting/plot_implicit.py", line 271, in sympy.plotting.plot_implicit.plot_implicit
Failed example:
    p4 = plot_implicit(Eq(x**2 + y**2, 5),
            (x, -5, 5), (y, -2, 2), adaptive=False)
Exception raised:
    Traceback (most recent call last):
      File "/Users/enzyme/anaconda/envs/sympy/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest sympy.plotting.plot_implicit.plot_implicit[5]>", line 2, in <module>
        (x, -5, 5), (y, -2, 2), adaptive=False)
      File "sympy/plotting/plot_implicit.py", line 374, in plot_implicit
        p.show()
      File "sympy/plotting/plot.py", line 185, in show
        self._backend.show()
      File "sympy/plotting/plot.py", line 1018, in show
        self.process_series()
      File "sympy/plotting/plot.py", line 921, in process_series
        points = s.get_raster()
      File "sympy/plotting/plot_implicit.py", line 80, in get_raster
        temp = func(xinterval, yinterval)
      File "<string>", line 1, in <lambda>
    NameError: global name 'Eq' is not defined
**********************************************************************
File "sympy/plotting/plot_implicit.py", line 276, in sympy.plotting.plot_implicit.plot_implicit
Failed example:
    p5 = plot_implicit(Eq(x**2 + y**2, 5),
            (x, -5, 5), (y, -2, 2),
            adaptive=False, points=400)
Exception raised:
    Traceback (most recent call last):
      File "/Users/enzyme/anaconda/envs/sympy/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest sympy.plotting.plot_implicit.plot_implicit[6]>", line 3, in <module>
        adaptive=False, points=400)
      File "sympy/plotting/plot_implicit.py", line 374, in plot_implicit
        p.show()
      File "sympy/plotting/plot.py", line 185, in show
        self._backend.show()
      File "sympy/plotting/plot.py", line 1018, in show
        self.process_series()
      File "sympy/plotting/plot.py", line 921, in process_series
        points = s.get_raster()
      File "sympy/plotting/plot_implicit.py", line 80, in get_raster
        temp = func(xinterval, yinterval)
      File "<string>", line 1, in <lambda>
    NameError: global name 'Eq' is not defined
**********************************************************************
File "sympy/plotting/plot_implicit.py", line 291, in sympy.plotting.plot_implicit.plot_implicit
Failed example:
    p8 = plot_implicit(y - 1, y_var=y)
Exception raised:
    Traceback (most recent call last):
      File "/Users/enzyme/anaconda/envs/sympy/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest sympy.plotting.plot_implicit.plot_implicit[9]>", line 1, in <module>
        p8 = plot_implicit(y - 1, y_var=y)
      File "sympy/plotting/plot_implicit.py", line 374, in plot_implicit
        p.show()
      File "sympy/plotting/plot.py", line 185, in show
        self._backend.show()
      File "sympy/plotting/plot.py", line 1018, in show
        self.process_series()
      File "sympy/plotting/plot.py", line 921, in process_series
        points = s.get_raster()
      File "sympy/plotting/plot_implicit.py", line 80, in get_raster
        temp = func(xinterval, yinterval)
      File "<string>", line 1, in <lambda>
    NameError: global name 'Eq' is not defined
**********************************************************************
File "sympy/plotting/plot_implicit.py", line 292, in sympy.plotting.plot_implicit.plot_implicit
Failed example:
    p9 = plot_implicit(x - 1, x_var=x)
Exception raised:
    Traceback (most recent call last):
      File "/Users/enzyme/anaconda/envs/sympy/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest sympy.plotting.plot_implicit.plot_implicit[10]>", line 1, in <module>
        p9 = plot_implicit(x - 1, x_var=x)
      File "sympy/plotting/plot_implicit.py", line 374, in plot_implicit
        p.show()
      File "sympy/plotting/plot.py", line 185, in show
        self._backend.show()
      File "sympy/plotting/plot.py", line 1018, in show
        self.process_series()
      File "sympy/plotting/plot.py", line 921, in process_series
        points = s.get_raster()
      File "sympy/plotting/plot_implicit.py", line 80, in get_raster
        temp = func(xinterval, yinterval)
      File "<string>", line 1, in <lambda>
    NameError: global name 'Eq' is not defined

===== tests finished: 2969 passed, 1 failed, 4 skipped, in 240.72 seconds ======
```

**Comment by proteasome** [comment]
```$ git bisect bad
8b39525f06ebfec7972e89f4a9f62df13298cf67 is the first bad commit
commit 8b39525f06ebfec7972e89f4a9f62df13298cf67
Author: Luv Agarwal <agarwal.iiit@gmail.com>
Date:   Mon Feb 2 02:38:46 2015 +0530```

**Comment by asmeurer** [comment]
8b39525f06ebfec7972e89f4a9f62df13298cf67
