### ISSUE TITLE
Problem plotting 3D figure with piecewise

### ISSUE THREAD

**Issue by KhaoticMind** [sympy/sympy#9654]
I'm filling this bug as suggested on an error message I'm getting when trying to plot a 3D function, with the code bellow:

```python
import sympy
sympy.init_session()
from sympy.plotting.plot import *
plot3d( Piecewise( (1, And(2<= x, x <= 3, 2<= y, y <= 3)), (0, True)  ), (x, 0, 5), (y, 0, 5))
```
Gives me the following error:

*D:\Miniconda3\lib\site-packages\sympy\plotting\experimental_lambdify.py:165: UserWarning: The evaluation of the expression is problematic. We are trying a failback method that may still work. Please report this as a bug.*

In the end the plot shows alright (the alternative method seens to work).
I
I'm running sympy 0.7.6 on windows with anaconda:

```
C:\Users\AntonioAugusto>conda list
# packages in environment at d:\Miniconda3:
#
alabaster                 0.7.3                    py34_0
babel                     1.3                      py34_0
certifi                   14.05.14                 py34_0
colorama                  0.3.3                    py34_0
conda                     3.14.1                   py34_0
conda-env                 2.3.0                    py34_0
decorator                 3.4.2                    py34_0
docutils                  0.12                     py34_1
ipython                   3.2.0                    py34_0
ipython-notebook          3.2.0                    py34_0
jedi                      0.8.1                    py34_0
jinja2                    2.7.3                    py34_2
jsonschema                2.4.0                    py34_0
markupsafe                0.23                     py34_0
mathjax                   2.2                           0
matplotlib                1.4.3                np19py34_1
menuinst                  1.0.4                    py34_0
mistune                   0.6                      py34_0
networkx                  1.9.1                    py34_0
nose                      1.3.7                    py34_0
numpy                     1.9.2                    py34_0
pandas                    0.16.2               np19py34_0
pep8                      1.6.2                    py34_0
pip                       7.1.0                    py34_0
psutil                    2.2.1                    py34_0
pycosat                   0.6.1                    py34_0
pyflakes                  0.9.2                    py34_0
pygments                  2.0.2                    py34_0
pyparsing                 2.0.3                    py34_0
pyqt                      4.10.4                   py34_1
pyreadline                2.0                      py34_0
python                    3.4.3                         0
python-dateutil           2.4.2                    py34_0
pytz                      2015.4                   py34_0
pyyaml                    3.11                     py34_1
pyzmq                     14.7.0                   py34_0
requests                  2.7.0                    py34_0
rope                      0.9.4                    py34_1
rope-py3k-0.9.4           1                         <pip>
scikit-learn              0.16.1               np19py34_0
scipy                     0.15.1               np19py34_0
seaborn                   0.6.0                np19py34_0
setuptools                18.0.1                   py34_0
six                       1.9.0                    py34_0
snowballstemmer           1.2.0                    py34_0
sphinx                    1.3.1                    py34_0
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py34_0
spyder                    2.3.5.2                  py34_0
sympy                     0.7.6                    py34_0
tornado                   4.2                      py34_0

C:\Users\AntonioAugusto>
```

**Comment by oscargus** [comment]
This now gives a different error (I have redefined x and y as real, so this is probably a pointer to why this new error happens).. Latest master of today.

```
plot3d( Piecewise( (1, And(2<= x, x <= 3, 2<= y, y <= 3)), (0, True)  ), (x, 0, 5), (y, 0, 5))
C:\Users\Oscar\sympy\sympy\plotting\experimental_lambdify.py:142: UserWarning: The evaluation of the expression is problematic. We are trying a failback method that may still work. Please report this as a bug.
  'The evaluation of the expression is problematic. '
Traceback (most recent call last):

  File "C:\Users\Oscar\sympy\sympy\plotting\experimental_lambdify.py", line 130, in __call__
    results = self.vector_func(*temp_args)

  File "C:\Users\Oscar\sympy\sympy\plotting\experimental_lambdify.py", line 272, in __call__
    return self.lambda_func(*args, **kwargs)

  File "<string>", line 1, in <lambda>

  File "C:\Users\Oscar\sympy\sympy\functions\elementary\piecewise.py", line 127, in __new__
    pair = ExprCondPair(*getattr(ec, 'args', ec))

  File "C:\Users\Oscar\sympy\sympy\functions\elementary\piecewise.py", line 20, in __new__
    if cond == True:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-8-eb9c0235df8b>", line 1, in <module>
    plot3d( Piecewise( (1, And(2<= x, x <= 3, 2<= y, y <= 3)), (0, True)  ), (x, 0, 5), (y, 0, 5))

  File "C:\Users\Oscar\sympy\sympy\plotting\plot.py", line 2186, in plot3d
    plots.show()

  File "C:\Users\Oscar\sympy\sympy\plotting\plot.py", line 222, in show
    self._backend.show()

  File "C:\Users\Oscar\sympy\sympy\plotting\plot.py", line 1416, in show
    self.process_series()

  File "C:\Users\Oscar\sympy\sympy\plotting\plot.py", line 1413, in process_series
    self._process_series(series, ax, parent)

  File "C:\Users\Oscar\sympy\sympy\plotting\plot.py", line 1255, in _process_series
    x, y, z = s.get_meshes()

  File "C:\Users\Oscar\sympy\sympy\plotting\plot.py", line 988, in get_meshes
    mesh_z = f(mesh_x, mesh_y)

  File "C:\Users\Oscar\sympy\sympy\plotting\experimental_lambdify.py", line 145, in __call__
    return self.__call__(*args)

  File "C:\Users\Oscar\sympy\sympy\plotting\experimental_lambdify.py", line 130, in __call__
    results = self.vector_func(*temp_args)

  File "C:\Users\Oscar\Anaconda3\lib\site-packages\numpy\lib\function_base.py", line 2108, in __call__
    return self._vectorize_call(func=func, args=vargs)

  File "C:\Users\Oscar\Anaconda3\lib\site-packages\numpy\lib\function_base.py", line 2192, in _vectorize_call
    outputs = ufunc(*inputs)

  File "C:\Users\Oscar\sympy\sympy\plotting\experimental_lambdify.py", line 272, in __call__
    return self.lambda_func(*args, **kwargs)

  File "<string>", line 1, in <lambda>

TypeError: '>=' not supported between instances of 'complex' and 'int'
```

**Comment by maxdanwitz** [comment]
Disabling the conversion to `complex` in the following line, I got the desired plot (see below).  Something similar was done in #15702. However, I don't know how to fix this in general.

https://github.com/sympy/sympy/blob/a380cfaa7c323ae6ee20988868649ed4c0761a5a/sympy/plotting/experimental_lambdify.py#L130

![piecewisePlot3d](https://user-images.githubusercontent.com/84030635/210814237-48ae1030-b1c4-45f1-934a-19c8e4c97799.png)
