### ISSUE TITLE
factor_list breaks on already-factored expression

### ISSUE THREAD

**Issue by lerks** [sympy/sympy#9684]
The issue is:
```
>>> import sympy
>>> x, y = sympy.symbols("x y")
>>> sympy.factor_list(x * (x + y))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/sympy/polys/polytools.py", line 5891, in factor_list
    return _generic_factor_list(f, gens, args, method='factor')
  File "/usr/lib/python3.4/site-packages/sympy/polys/polytools.py", line 5639, in _generic_factor_list
    fp = _sorted_factors(fp, method)
  File "/usr/lib/python3.4/site-packages/sympy/polys/polytools.py", line 5540, in _sorted_factors
    return sorted(factors, key=key)
TypeError: unorderable types: list() < mpz()
```
The problem lies in the fact that when converted to a list of Poly factors, the first will have only "x" as generator, whereas the second will have both variables. Thus their representations are nested lists of depth 1 and 2 respectively. And they aren't comparable.

**Comment by smichr** [comment]
Perhaps try the current master?

```
>>> factor_list(x * (x + y))
(1, [(x, 1), (x + y, 1)])
```

**Comment by lerks** [comment]
Still the same:
```
>>> import sympy
>>> sympy.__version__
'0.7.7.dev'
>>> x, y = sympy.symbols("x y")
>>> sympy.factor_list(x * (x + y))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/sympy/polys/polytools.py", line 5954, in factor_list
    return _generic_factor_list(f, gens, args, method='factor')
  File "/usr/lib/python3.4/site-packages/sympy/polys/polytools.py", line 5699, in _generic_factor_list
    fp = _sorted_factors(fp, method)
  File "/usr/lib/python3.4/site-packages/sympy/polys/polytools.py", line 5602, in _sorted_factors
    return sorted(factors, key=key)
TypeError: unorderable types: list() < mpz()
```

**Comment by jksuom** [comment]
This is what I get with another version of Python.
```
Python 2.7.3 (default, Jun 22 2015, 19:43:34) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'0.7.7.dev'
>>> x, y = sympy.symbols("x y")
>>> sympy.factor_list(x * (x + y))
(1, [(x, 1), (x + y, 1)])
```

**Comment by lerks** [comment]
Trying with the Python 2 installation on my machine, whose sympy library I didn't upgrade to master, I get the same result:
```
Python 2.7.10 (default, May 26 2015, 04:16:29) 
[GCC 5.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'0.7.6'
>>> x, y = sympy.symbols("x y")
>>> sympy.factor_list(x * (x + y))
(1, [(x, 1), (x + y, 1)])
```
So it may be a Python 3 issue...

**Comment by jksuom** [comment]
It appears that the comparisons are different in Python 3. I seem to have got that working also in Python 3 by adding the number generators to the comparison key.
```
--- a/sympy/polys/polytools.py
+++ b/sympy/polys/polytools.py
@@ -5597,7 +5597,7 @@ def key(obj):
         def key(obj):
             poly, exp = obj
             rep = poly.rep.rep
-            return (len(rep), exp, rep)
+            return (len(rep), len(poly.gens), exp, rep)
 
     return sorted(factors, key=key)
```

**Comment by smichr** [comment]
duplicates #7067
