### ISSUE TITLE
Substitution of Indexed expressions does not seem to work well with `simulataneous=True`

### ISSUE THREAD

**Issue by tschijnmo** [sympy/sympy#9791]
For simple substitution operation on expressions involving indexed objects from the tensor module, like

```Py
from sympy import *
a = IndexedBase('a')
b = IndexedBase('b')
i = symbols('i')
expr = a[i]
expr.subs({a: b})
```

would work fine. However, doing

```Py
expr.subs({a: b}, simultaneous=True)
```

will give an error of

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/sympy/core/cache.py", line 91, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python3.4/site-packages/sympy/core/basic.py", line 1006, in _subs
    rv = fallback(self, old, new)
  File "/usr/local/lib/python3.4/site-packages/sympy/core/basic.py", line 983, in fallback
    rv = self.func(*args)
  File "/usr/local/lib/python3.4/site-packages/sympy/tensor/indexed.py", line 146, in __new__
    Indexed expects string, Symbol or IndexedBase as base."""))
TypeError: 
Indexed expects string, Symbol or IndexedBase as base.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/sympy/core/basic.py", line 883, in subs
    rv = rv._subs(old, d*m, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/sympy/core/cache.py", line 93, in wrapper
    retval = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/sympy/core/basic.py", line 1006, in _subs
    rv = fallback(self, old, new)
  File "/usr/local/lib/python3.4/site-packages/sympy/core/basic.py", line 983, in fallback
    rv = self.func(*args)
  File "/usr/local/lib/python3.4/site-packages/sympy/tensor/indexed.py", line 146, in __new__
    Indexed expects string, Symbol or IndexedBase as base."""))
TypeError: 
Indexed expects string, Symbol or IndexedBase as base.
```

Any idea about how this could be fixed will be appreciated! Thank you!

**Comment by oliverlee** [comment]
When simultaneous is True, ```subs``` uses a product of dummy variables. This is not valid for the ```base``` argument ```Indexed.__new__()```. You could possibly write a special case for it in ```subs``` or define the ```_eval_subs``` method for ```Indexed```.
