### ISSUE TITLE
Quadratic forms with matrix expressions are handled poorly

### ISSUE THREAD

**Issue by Bonnevie** [sympy/sympy#9817]
There seems to be a number of issues with the handling of quadratic forms. 

``` python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sympy as s

In [2]: n = 3

In [3]: v = s.MatrixSymbol('v',3,1)

In [4]: A = s.MatrixSymbol('A',3,3) 

In [5]: quadratic = v.T*A*v

In [6]: x = s.Matrix([i+1 for i in xrange(n)])

In [7]: X = s.Identity(n)

In [8]: subbed = quadratic.xreplace({v:x,A:X})

In [9]: print subbed
Matrix([
[1],
[2],
[3]])'*I*Matrix([
[1],
[2],
[3]])

In [10]: print(subbed.as_explicit())
Matrix([[14]])

In [11]: print(s.simplify(s.trace(subbed)))
Trace(Matrix([
[1],
[2],
[3]])'*I*Matrix([
[1],
[2],
[3]]))
```

Many equations use the quadratic form v^T_A_v and expect a scalar, which is not the case in sympy. Substitution with xreplace does not lead to a resolution of the form, but if this is forced with as_explicit we get a (1,1) matrix which conflicts with scalar symbols. Taking the trace does circumvent this, but apparently prevents evaluation of the internal expression. 
I also tried v.dot(A*v) which would be a reasonable compromise, but even when the dimension is fixed to (n,1) MatrixSymbol does not believe it can apply the .dot method. As soon as the vector is instantiated with vector value x it can call the method. 

Finally, putting the xreplace outside works, but simplify fails on the now supposedly scalar expression.

``` python
In [15]: s.simplify((s.trace(quadratic.as_explicit())).xreplace({v:x,A:X}))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-2efc33ac8c3f> in <module>()
----> 1 s.simplify((s.trace(quadratic.as_explicit())).xreplace({v:x,A:X}))

/usr/local/lib/python2.7/dist-packages/sympy/simplify/simplify.pyc in simplify(expr, ratio, measure, fu)
   3706     _e = cancel(expr)
   3707     expr1 = shorter(_e, _mexpand(_e).cancel())  # issue 6829
-> 3708     expr2 = shorter(together(expr, deep=True), together(expr1, deep=True))
   3709 
   3710     if ratio is S.Infinity:

/usr/local/lib/python2.7/dist-packages/sympy/simplify/simplify.pyc in shorter(*choices)
   3700         if not has_variety(choices):
   3701             return choices[0]
-> 3702         return min(choices, key=measure)
   3703 
   3704     expr = bottom_up(expr, lambda w: w.normal())

/usr/local/lib/python2.7/dist-packages/sympy/core/function.pyc in count_ops(expr, visual)
   2250         while args:
   2251             a = args.pop()
-> 2252             if a.is_Rational:
   2253                 #-1/3 = NEG + DIV
   2254                 if a is not S.One:

AttributeError: 'str' object has no attribute 'is_Rational'
```

Possible solutions could be improved simplification of matrix expressions, a VectorSymbol class (or awareness of dot), or a quadratic form operator.

**Comment by oliverlee** [comment]
Discussion on this issue here: https://github.com/sympy/sympy/issues/9190

**Comment by asmeurer** [comment]
I now get this error here

```pytb
>>> subbed.as_explicit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/matrices/expressions/matexpr.py", line 349, in as_explicit
    for i in range(self.rows)])
  File "./sympy/matrices/expressions/matexpr.py", line 349, in <listcomp>
    for i in range(self.rows)])
  File "./sympy/matrices/expressions/matexpr.py", line 348, in <listcomp>
    for j in range(self.cols)]
  File "./sympy/matrices/expressions/matexpr.py", line 298, in __getitem__
    return self._entry(i, j)
  File "./sympy/matrices/expressions/matmul.py", line 64, in _entry
    matrices = [arg[indices[i], indices[i+1]] for i, arg in enumerate(matrices)]
  File "./sympy/matrices/expressions/matmul.py", line 64, in <listcomp>
    matrices = [arg[indices[i], indices[i+1]] for i, arg in enumerate(matrices)]
  File "./sympy/matrices/expressions/matexpr.py", line 298, in __getitem__
    return self._entry(i, j)
  File "./sympy/matrices/expressions/transpose.py", line 54, in _entry
    return self.arg._entry(j, i, expand=expand)
TypeError: _entry() got an unexpected keyword argument 'expand'
```

**Comment by asmeurer** [comment]
The `simplify` bit works in master, so a test should be added for it. 

The `as_explicit` thing should be easy to fix (remove the expand keyword from the `_entry` call).

**Comment by nileshpatra** [comment]
Can I work on it? Could I be guided as to how to solve it?

**Comment by czgdp1807** [comment]
Only `.as_explicit` needs to be fixed. Rest works fine.

**Comment by hyadav2k** [comment]
Hi @czgdp1807, I would like to work on this issue, can you guide what is to be fixed in .as_explicit. Thanks

**Comment by czgdp1807** [comment]
@hyadav2k I do not know about this side of SymPy. My comment just includes the bottom line of the discussions held so far in this issue. May be you can try re-producing the issue in the OP and add a fix accordingly.

**Comment by hyadav2k** [comment]
Thank you for replying, I will surely do that.

**Comment by 0sidharth** [comment]
`simplify` and `as_explicit` both are working in the current master, I believe only tests need to be added now for this issue to be closed.

**Comment by czgdp1807** [comment]
@0sidharth Could you please let us know the PR which contains the tests?

**Comment by 0sidharth** [comment]
Seems like the PR reference got lost between the commits, https://github.com/sympy/sympy/pull/20686 is the PR.
