### ISSUE TITLE
Hessian of a Matrix function (MatrixSymbol object has no attribute _diff_wrt)

### ISSUE THREAD

**Issue by tbsexton** [sympy/sympy#9840]
This input: 

```
H = MatrixSymbol('H', 3,3)
X = MatrixSymbol('x', 3, 1)
C = MatrixSymbol('c', 3, 1)
f = (1/2)*X.T*H*X + C.T*X
```
Gives
```
>>> hessian(f, [X])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/sympy/sympy/matrices/dense.py", line 1453, in hessian
    if not getattr(f, 'diff'):
AttributeError: 'MatAdd' object has no attribute 'diff'

```

Bypassing this by simply finding the 1st derivative and combining the terms into a single matrix like

```
>>> Matrix((1/2)*X.T*H*X + C.T*X).diff(X)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/sympy/sympy/matrices/matrices.py", line 3157, in diff
    lambda i, j: self[i, j].diff(*args))
  File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/sympy/sympy/matrices/dense.py", line 587, in _new
    rows, cols, flat_list = cls._handle_creation_inputs(*args, **kwargs)
  File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/sympy/sympy/matrices/matrices.py", line 155, in _handle_creation_inputs
    for j in range(cols)])
  File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/sympy/sympy/matrices/matrices.py", line 3157, in <lambda>
    lambda i, j: self[i, j].diff(*args))
  File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/sympy/sympy/core/expr.py", line 2775, in diff
    return Derivative(self, *new_symbols, **assumptions)
  File "/base/data/home/apps/s~sympy-live-hrd/45.380685391411058699/sympy/sympy/core/function.py", line 1005, in __new__
    if v._diff_wrt:
AttributeError: 'MatrixSymbol' object has no attribute '_diff_wrt'


```

The hessian should collapse to something like `H+1/2*H.T`. How to get this functionality?

**Comment by jacknlliu** [comment]
@tbsexton did you resolve the issue? I got the same error.

**Comment by oscarbenjamin** [comment]
I now get:
```
In [51]: hessian(f, [X])                                                                                                                       
---------------------------------------------------------------------------
ShapeError 
...
~/current/sympy/sympy/sympy/matrices/expressions/matmul.py in validate(*matrices)
    177         A, B = matrices[i:i+2]
    178         if A.cols != B.rows:
--> 179             raise ShapeError("Matrices %s and %s are not aligned"%(A, B))
    180 
    181 # Rules

ShapeError: Matrices 0.5*H.T and I are not aligned
```

The other example gives
```
In [53]: Matrix((1/2)*X.T*H*X + C.T*X).diff(X)                                                                                                 
Out[53]: [0]
```

Does that mean that this is fixed?

**Comment by tbsexton** [comment]
I get a much larger error code. 

```python
In [3]: hessian(f, [X])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-bd070d741159> in <module>()
----> 1 hessian(f, [X])

~/anaconda3/lib/python3.6/site-packages/sympy/matrices/dense.py in hessian(f, varlist, constraints)
   1282     for i in range(n):
   1283         for j in range(i, n):
-> 1284             out[i + m, j + m] = f.diff(varlist[i]).diff(varlist[j])
   1285     for i in range(N):
   1286         for j in range(i + 1, N):

~/anaconda3/lib/python3.6/site-packages/sympy/core/expr.py in diff(self, *symbols, **assumptions)
   3026         new_symbols = list(map(sympify, symbols))  # e.g. x, 2, y, z
   3027         assumptions.setdefault("evaluate", True)
-> 3028         return Derivative(self, *new_symbols, **assumptions)
   3029 
   3030     ###########################################################################

~/anaconda3/lib/python3.6/site-packages/sympy/core/function.py in __new__(cls, expr, *variables, **kwargs)
   1255                 # object, the default in `Basic` will call a loop over
   1256                 # `_eval_derivative`:
-> 1257                 obj = expr._eval_derivative_n_times(v, count)
   1258                 nderivs += count
   1259                 if not is_symbol:

~/anaconda3/lib/python3.6/site-packages/sympy/core/basic.py in _eval_derivative_n_times(self, s, n)
   1618             obj = self
   1619             for i in range(n):
-> 1620                 obj2 = obj._accept_eval_derivative(s)
   1621                 if obj == obj2:
   1622                     break

~/anaconda3/lib/python3.6/site-packages/sympy/core/basic.py in _accept_eval_derivative(self, s)
   1594     def _accept_eval_derivative(self, s):
   1595         # This method needs to be overridden by array-like objects
-> 1596         return s._visit_eval_derivative_scalar(self)
   1597 
   1598     def _visit_eval_derivative_scalar(self, base):

~/anaconda3/lib/python3.6/site-packages/sympy/core/basic.py in _visit_eval_derivative_scalar(self, base)
   1599         # Base is a scalar
   1600         # Types are (base: scalar, self: scalar)
-> 1601         return base._eval_derivative(self)
   1602 
   1603     def _visit_eval_derivative_array(self, base):

~/anaconda3/lib/python3.6/site-packages/sympy/matrices/expressions/matexpr.py in _eval_derivative(self, v)
    235         else:
    236             if m not in repl:
--> 237                 parsed = MatrixExpr.from_index_summation(res, m)
    238             elif i not in repl:
    239                 parsed = MatrixExpr.from_index_summation(res, i)

~/anaconda3/lib/python3.6/site-packages/sympy/matrices/expressions/matexpr.py in from_index_summation(expr, first_index, last_index)
    573                 return [(expr, None)]
    574 
--> 575         retvals = recurse_expr(expr)
    576         factors, indices = zip(*retvals)
    577         retexpr = Mul.fromiter(factors)

~/anaconda3/lib/python3.6/site-packages/sympy/matrices/expressions/matexpr.py in recurse_expr(expr, index_ranges)
    535                 ]
    536             elif expr.is_Add:
--> 537                 res = [recurse_expr(i) for i in expr.args]
    538                 d = collections.defaultdict(list)
    539                 for res_addend in res:

~/anaconda3/lib/python3.6/site-packages/sympy/matrices/expressions/matexpr.py in <listcomp>(.0)
    535                 ]
    536             elif expr.is_Add:
--> 537                 res = [recurse_expr(i) for i in expr.args]
    538                 d = collections.defaultdict(list)
    539                 for res_addend in res:

~/anaconda3/lib/python3.6/site-packages/sympy/matrices/expressions/matexpr.py in recurse_expr(expr, index_ranges)
    514                     index1 = pos_ind[cur_ind_pos[0]][cur_ind_pos[1]]
    515                     while True:
--> 516                         d, r = cur_ind_pos
    517                         if pos_arg[d] != 1:
    518                             if r % 2 == 1:

TypeError: 'int' object is not iterable
```

meanwhile: 
```python 
In [4]: Matrix((1/2)*X.T*H*X + C.T*X).diff(X)     
Out[4]: Matrix([[0]])
```

**Comment by oscarbenjamin** [comment]
I should say that I ran that on master
