### ISSUE TITLE
Regression: Second order tf inverse_laplace_transform 

### ISSUE THREAD

**Issue by alchemyst** [sympy/sympy#9900]
The following code returns a workable inverse in version 0.7.5 but causes an error in 0.7.6.1:

    import sympy
    tau, zeta, t = sympy.symbols('tau, zeta, t', real=True, positive=True)
    s = sympy.Symbol('s')

    G = 1/(tau**2*s**2 + 2*tau*zeta*s + 1)
    print sympy.inverse_laplace_transform(G, s, t)

Error: 

    Traceback (most recent call last):
      File "bugreport_secondorder_inverse.py", line 10, in <module>
        print sympy.inverse_laplace_transform(G, s, t)
      File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 1267, in inverse_laplace_transform
        return InverseLaplaceTransform(F, s, t, plane).doit(**hints)
      File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 118, in doit
        self.function_variable, self.transform_variable, **hints)
      File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 1219, in _compute_transform
        return _inverse_laplace_transform(F, s, t, self.fundamental_plane, **hints)
      File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 196, in wrapper
        res = func(*args, **kwargs)
      File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 1146, in _inverse_laplace_transform
        needeval=True, noconds=False)
      File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 862, in inverse_mellin_transform
        return InverseMellinTransform(F, s, x, strip[0], strip[1]).doit(**hints)
      File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 118, in doit
        self.function_variable, self.transform_variable, **hints)
      File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 806, in _compute_transform
        return _inverse_mellin_transform(F, s, x, strip, **hints)
      File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 196, in wrapper
        res = func(*args, **kwargs)
      File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 725, in _inverse_mellin_transform
        a, b, C, e, fac = _rewrite_gamma(g, s, strip[0], strip[1])
      File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 614, in _rewrite_gamma
        if left(c, is_numer):
      File "/Library/Frameworks/EPD64.framework/Versions/7.2/lib/python2.7/site-packages/sympy/core/relational.py", line 103, in __nonzero__
        raise TypeError("cannot determine truth value of\n%s" % self)
    TypeError: cannot determine truth value of
    -zeta/tau - sqrt(zeta + 1)*cos(atan2(0, zeta - 1)/2)*sqrt(Abs(zeta - 1))/tau < oo

**Comment by jksuom** [comment]
The error no longer appears in the current development version (0.7.7-dev),

**Comment by alchemyst** [comment]
Thanks, I'll try that.
