### ISSUE TITLE
srepr fails on various expressions (differential equation, function, Poly)

### ISSUE THREAD

**Issue by Adrien79** [sympy/sympy#9926]
In the current 0.7.7.dev branch, srepr fails on a simple differential equation:

    >>> x = Symbol('x')
    >>> y = Function('y')
    >>> y0 = y(x)
    >>> y1 = y0.diff(x)
    >>> y2 = y1.diff(x)
    >>> L = x**2 * y2 - y1 + y0
    >>> str(L)
    x**2*Derivative(y(x), x, x) + y(x) - Derivative(y(x), x)
    >>> srepr(L)
    Traceback (most recent call last):
      File "<pyshell#90>", line 1, in <module>
        srepr(L)
      File "c:\users\adrien\sympy\sympy\printing\repr.py", line 198, in srepr
        return ReprPrinter(settings).doprint(expr)
      File "c:\users\adrien\sympy\sympy\printing\printer.py", line 233, in doprint
        return self._str(self._print(expr))
      File "c:\users\adrien\sympy\sympy\printing\printer.py", line 257, in _print
        return getattr(self, printmethod)(expr, *args, **kwargs)
      File "c:\users\adrien\sympy\sympy\printing\repr.py", line 51, in _print_Add
        return "Add(%s)" % ", ".join(args)
      File "c:\users\adrien\sympy\sympy\printing\printer.py", line 257, in _print
        return getattr(self, printmethod)(expr, *args, **kwargs)
      File "c:\users\adrien\sympy\sympy\printing\repr.py", line 123, in _print_Mul
        return "Mul(%s)" % ", ".join(args)
      File "c:\users\adrien\sympy\sympy\printing\printer.py", line 260, in _print
        return self.emptyPrinter(expr)
      File "c:\users\adrien\sympy\sympy\printing\repr.py", line 41, in emptyPrinter
        l.append(self._print(o))
      File "c:\users\adrien\sympy\sympy\printing\printer.py", line 257, in _print
        return getattr(self, printmethod)(expr, *args, **kwargs)
      File "c:\users\adrien\sympy\sympy\printing\repr.py", line 144, in _print_Symbol
        d = expr._assumptions.generator
      File "c:\users\adrien\sympy\sympy\core\assumptions.py", line 228, in generator
        return self._generator.copy()
    AttributeError: 'StdFactKB' object has no attribute '_generator'

Also I find that the ordering of the terms when printing L is not very natural:

    >>> L
         2                        
     2  d                 d       
    x *---(y(x)) + y(x) - --(y(x))
         2                dx      
       dx

**Comment by Adrien79** [comment]
I get the same error message by passing several simpler expressions to `srepr`, like `srepr(y(x))` or `srepr(Poly(x**2,x))`. I've changed the title accordingly.

**Comment by jksuom** [comment]
I have not been able to reproduce these errors.
```
Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3] on linux2

>>> sympy.__version__
'0.7.7.dev'
>>> x = Symbol('x')
>>> y = Function('y')
>>> y0 = y(x)
>>> y1 = y0.diff(x)
>>> y2 = y1.diff(x)
>>> L = x**2 * y2 - y1 + y0
>>> srepr(L)
"Add(Mul(Pow(Symbol('x'), Integer(2)), Derivative(Function('y')(Symbol('x')), Symbol('x'), Symbol('x'))), Function('y')(Symbol('x')), Mul(Integer(-1), Derivative(Function('y')(Symbol('x')), Symbol('x'))))"
>>> srepr(y(x))
"Function('y')(Symbol('x'))"
>>> srepr(Poly(x**2, x))
"Poly(Pow(Symbol('x'), Integer(2)))"
```
There must be some essential difference in our systems.

**Comment by Adrien79** [comment]
I tinkered with my Python install and now I'm unable to reproduce the bug. I don't understand at all what happened, sorry.
