### ISSUE TITLE
conda doesn't install the mpmath dependency

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#9961]
```
moorepants@CaramelMonkeyU:sympy(notebook-matplotlib-printing-issue)$ conda create -n test-mpmath-auto sympy
Fetching package metadata: ....
Solving package specifications: ................
Package plan for installation in environment /home/moorepants/miniconda/envs/test-mpmath-auto:

The following NEW packages will be INSTALLED:

    fastcache:  1.0.2-py27_0  
    openssl:    1.0.1k-1      
    pip:        7.1.2-py27_0  
    python:     2.7.10-1      
    readline:   6.2-2         
    setuptools: 18.3.2-py27_0 
    sqlite:     3.8.4.1-1     
    sympy:      0.7.6.1-py27_0
    tk:         8.5.18-0      
    wheel:      0.26.0-py27_1 
    zlib:       1.2.8-0       

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|############################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate test-mpmath-auto
#
# To deactivate this environment, use:
# $ source deactivate
#
moorepants@CaramelMonkeyU:sympy(notebook-matplotlib-printing-issue)$ act test-mpmath-auto 
discarding /home/moorepants/miniconda/bin from PATH
prepending /home/moorepants/miniconda/envs/test-mpmath-auto/bin to PATH
(test-mpmath-auto)moorepants@CaramelMonkeyU:sympy(notebook-matplotlib-printing-issue)$ python -c "import sympy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "sympy/__init__.py", line 18, in <module>
    raise ImportError("SymPy now depends on mpmath as an external library. "
ImportError: SymPy now depends on mpmath as an external library. See http://docs.sympy.org/latest/install.html#mpmath for more information.
```

@asmeurer

**Comment by debugger22** [comment]
And also, this (`http://docs.sympy.org/latest/install.html#mpmath`) doesn't point to any mpmath installation instructions.

**Comment by asmeurer** [comment]
That's because mpmath isn't a dependency yet in the stable release. Also, that page won't exist until we do a release.

**Comment by moorepants** [comment]
Duh. Thanks. I was setting up dev environments and just got confused.

**Comment by debugger22** [comment]
Oh! And we distributed git versions to people at conference. No one had a clue. :(
